withastro/astro

.changeset/purple-pianos-greet.md, packages/astro/src/runtime/server/render/astro/render.ts, packages/astro/test/fixtures/partials/src/pages/partials/nested-conditional.astro, packages/astro/test/partials.test.js
- Our async iterable was closing too fast because with partials we skip the head parts. So there would be a pull of chunks that were empty even though rendering was still ongoing. The fix is to only end the iterator after both rendering is done and there are no more chunks to flush out.
- Closes https://github.com/withastro/astro/issues/11103
N/A, bug fix
=> Close iterator after rendering is complete and no more chunks remain

.changeset/early-melons-thank.md, packages/astro/src/content/runtime.ts, packages/astro/test/content-collections.test.js, packages/astro/test/fixtures/content-collections-mutation/astro.config.mjs, packages/astro/test/fixtures/content-collections-mutation/package.json, packages/astro/test/fixtures/content-collections-mutation/src/content/blog/first.md, packages/astro/test/fixtures/content-collections-mutation/src/content/blog/second.md, packages/astro/test/fixtures/content-collections-mutation/src/content/blog/third.md, packages/astro/test/fixtures/content-collections-mutation/src/content/config.ts, packages/astro/test/fixtures/content-collections-mutation/src/pages/another_page.astro, packages/astro/test/fixtures/content-collections-mutation/src/pages/index.astro, pnpm-lock.yaml
Currently, the first time `getCollection` is called in prod it returns the same array that is then cached, meaning that any mutations are applied to the cached value. Subsequent calls return a clone of the cached value (so these can be safely changed), but any changes made on the first call are still present. The original bug was fixed in #8022, but it missed the issue with the first invocation. This PR ensures that the array is always cloned before returning.
Fixes #10700
Adds a test fixture based on the #10700 repro. Thanks @SStembridge.
=> fix(astro): always return cloned content collection

.changeset/fuzzy-eggs-kneel.md, packages/astro/src/container/pipeline.ts, packages/astro/src/core/app/pipeline.ts, packages/astro/src/core/base-pipeline.ts, packages/astro/src/core/build/pipeline.ts, packages/astro/src/core/render-context.ts, packages/astro/src/vite-plugin-astro-server/pipeline.ts, packages/astro/test/fixtures/rewrite-server/astro.config.mjs, packages/astro/test/fixtures/rewrite-server/package.json, packages/astro/test/fixtures/rewrite-server/src/pages/[slug]/title.astro, packages/astro/test/fixtures/rewrite-server/src/pages/index.astro, packages/astro/test/rewrite.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/11204
This PR fixes two issues:
- Inside `RenderContext`, `pathname` is now updated during the rewriting. To correctly infer the correct pathname (`RouteData.pathame` sometimes is undefined, and `RouteData.route` **ins't** correct e.g. `/some-slug/title` VS `/[slug]/title`, and we need the former)
- The `tryRewrite` now returns the new `URL`, since we had the logic here in all the pipelines
- We recompute the `AstroPartial` object when rewriting because during rewriting, we were sending old information, such as `params`
Added two new test cases
N/A
=> fix(rewrite): purge old data when rewriting

.changeset/shaggy-camels-dream.md, packages/integrations/vercel/package.json, packages/integrations/vercel/src/serverless/adapter.ts, packages/integrations/vercel/src/serverless/middleware.ts, packages/integrations/vercel/test/edge-middleware.test.js, packages/integrations/vercel/test/fixtures/middleware-with-edge-file/src/middleware.js
- Vercel Edge Middleware does a fetch call to the remote, but Astro.cookies need to be set on the response.
- Addes the cookies similar to what happens inside of SSR.
- New test added. Also re-enables a test that was previously skipped.
N/A, bug fix
=> In Vercel Edge, include cookies set by Astro.cookies.set

.changeset/clever-jars-trade.md, .changeset/dirty-rabbits-act.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/base-pipeline.ts, packages/astro/src/env/constants.ts, packages/astro/src/env/runtime.ts, packages/astro/src/env/schema.ts, packages/astro/src/env/vite-plugin-env.ts, packages/astro/templates/env/module.mjs, packages/astro/templates/env/types.d.ts, packages/astro/test/fixtures/astro-env-server-fail/astro.config.mjs, packages/astro/test/fixtures/astro-env-server-fail/src/pages/index.astro, packages/astro/test/fixtures/astro-env-server-secret/src/pages/index.astro, packages/astro/test/fixtures/astro-env/astro.config.mjs, packages/astro/test/fixtures/astro-env/src/pages/index.astro, packages/astro/test/units/config/config-validate.test.js
- Removes the `PUBLIC_` prefix constraint
- Allows importing secrets from `astro:env/server` directly
Tests should still pass
Config reference updated
=> feat(astro): address astro env rfc feedback

.changeset/pink-experts-count.md, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/extension-matching.test.js, packages/astro/test/fixtures/extension-matching/astro.config.mjs, packages/astro/test/fixtures/extension-matching/package.json, packages/astro/test/fixtures/extension-matching/src/pages/index.astro, pnpm-lock.yaml
Checks the filename for the `.astro`, rather than the full ID. Fixes #11230, where a query that ended in the string `.astro` would incorrectly match.
I wasn't able to find a place where there were tests of this part of the code. If anyone has suggestions for a good place to test it then that would be welcome.
Nothing changed
=> fix(astro): ignore query params when matching .astro extension

.changeset/few-beans-tickle.md, packages/markdown/remark/package.json, pnpm-lock.yaml
This package wasn't marked as an internal dependency correctly, which introduced a race condition in the build process. Starting from now, `@astrojs/prism` will always be built first.
See discussion on Discord (contribute) for details.
Clear Turborepo cache, try building `@astrojs/markdown-remark` - you will see an error regarding `@astrojs/prism`.
Checkout to this branch, do the same steps - you will see no error, `@astrojs/prism` will be built first.
No changes needed
=> fix(markdown-remark): mark prism package as an internal dependency

packages/astro/src/@types/astro.ts
* There were two incorrect links for the `reference/api-reference` in JSDoc that now point to the right place.
Tried links before and after. Updated links work. 
These are JSDocs.
=> [docs] update JSDoc for API Reference links

.changeset/early-spies-bow.md, packages/astro/src/content/types-generator.ts
I have a large number of items in my content collections and I've noticed a considerable slowness when starting the dev server, having looked into it (with `--verbose`), I noticed that the JSON schema files were being changed repeatedly which made the HMR spend approximately 90ms reloading it. With a lot of content files, this quickly adds up and made my startup times approach a minute in some cases 🙈 
This PR changes the behaviour so that the JSON schema is only generated once rather than in the `for` loop like it was before, I can't think of any reason that it needed to be in that `for` loop but other people may know better than me!
I've tested this change in the project that was having the performance issue and it only generates the JSON schemas once and the dev server starts …
=> Fix a performance issue with JSON schema generation

.changeset/healthy-oranges-report.md, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/core/render-context.ts, packages/astro/test/fixtures/rewrite-server/src/pages/post/index.astro, packages/astro/test/fixtures/rewrite-server/src/pages/post/post-b.astro, packages/astro/test/fixtures/rewrite-server/src/pages/post/post-body-used.astro, packages/astro/test/rewrite.test.js
Experimental `Astro.rewrite()` clones the request, which throws a confusing error if the body has already been consumed. This PR detects this and throws a more helpful error instead.
Fixes #11247
Adds tests
@withastro/maintainers-docs This adds a new Astro error
=> fix: throw error if rewrite is attempted after body is used

.changeset/nice-pillows-teach.md, packages/db/virtual.d.ts
Following #11216 `Database` type was moved between files, but dts wasn't updated. In @astrojs/db 0.11.15 db is always type any as it can't be found in `'./dist/_internal/runtime/virtual.js'`
Sorry if there is anything wrong with the change, just started using the lib today.
=> Import Database type from correct file

.changeset/serious-humans-obey.md, packages/integrations/node/src/server.ts, packages/integrations/vercel/src/serverless/entrypoint.ts
- Even though the code uses a dynamic import with a catch, this still breaks in the build because Rollup tries to build that import.
- Moving the import specifier to a variable lets us hide from Rollup, while still dynamically importing this module at runtime.
- Can't create unit tests for this since it requires Astro <= 4.9. Tested manually.
N/A, bug fix
=> Fix backwards compat with Astro <= 4.9 in Node and Vercel adapters

.changeset/thin-icons-yell.md, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/src/utils.ts, packages/integrations/node/src/index.ts, packages/integrations/sitemap/src/index.ts
- Use the logger provided by Astro more consistently in integrations.
- Remove an old duplicate check in the sitemap integration.
No tests added because there are no integration log tests (to my knowledge).
No docs added because this is strictly stylistic.
=> chore: logging cleanup

.changeset/duplicated-brackets-generation.md, packages/astro/src/content/types-generator.ts
This PR fixed #11274
This is a minor patch fix which doesn't need test.
This doesn't introduce any new feature nor break changes. No doc is provided.
=> fix(astro): duplicated brackets are generated in data collections.

.changeset/old-walls-report.md, packages/astro/src/assets/internal.ts, packages/astro/src/assets/types.ts, packages/astro/src/content/runtime-assets.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/test/core-image.test.js, packages/astro/test/fixtures/core-image-base/tsconfig.json, packages/astro/test/fixtures/core-image-errors/src/pages/get-image-import-passed.astro, packages/astro/test/fixtures/core-image/tsconfig.json
Currently it is possible to pass an ESM image import directly to `getImage` without any type error. There will be an error at build or runtime, but it is more generic and doesn;t make it clear what the problem is.
This PR includes two changes. First it adds runtime error checks for this specific case. It detects if an ESM image has been passed directly and throws a more helpful error.
Second it uses branded types to prevent the ESM image object being passed. This was previously allowed because an ESM import is the correct shape. This is handled now by adding an internal field to the type returned by the ESM import which isn't permitted by getImage.
Fixes #10126 
Adds tests
@withastro/maintainers-docs includes a new AstroError
=> fix(astro): prevent ESM imports being passed directly to getImage

.changeset/silly-pens-fetch.md, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/fixtures/i18n-routing-manual/src/middleware.js, packages/astro/test/fixtures/i18n-routing-manual/src/pages/404.astro, packages/astro/test/fixtures/middleware space/src/pages/integration-post.astro, packages/astro/test/fixtures/middleware space/src/pages/integration-pre.astro, packages/astro/test/i18n-routing-manual.test.js
When a 404 page is prerendered, middleware is not run in production. This is because middleware is only run at build time for prerendered pages. Currently this behaves differently in dev, which was running middleware for all 404 requests. This is confusing, causing reports such as #10785 
As part of the work making this change it became clear there was a lot of unused logic in the dev 404 handling. Currently it checks if there is no matching route to handle the 404 case. However there is always a matched route in practice, because `ensure404Route` means a 404 route will always match it, so those code branches are never hit. This PR removes a lot of this unused code.
Added new tests, and fixed bugs in other tests.
Just fixes a bug, though maybe there could be docs explaining that …
=> fix(astro): don't run middleware in dev for prerendered 404 routes

.changeset/five-owls-check.md, .changeset/honest-shirts-trade.md, packages/astro/src/container/pipeline.ts, packages/astro/src/core/app/pipeline.ts, packages/astro/src/core/base-pipeline.ts, packages/astro/src/core/build/pipeline.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/core/routing/rewrite.ts, packages/astro/src/vite-plugin-astro-server/pipeline.ts, packages/astro/test/fixtures/rewrite-trailing-slash-never/astro.config.mjs, packages/astro/test/fixtures/rewrite-trailing-slash-never/package.json, packages/astro/test/fixtures/rewrite-trailing-slash-never/src/pages/foo.astro, packages/astro/test/fixtures/rewrite-trailing-slash-never/src/pages/index.astro, packages/astro/test/rewrite.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/11235
This PR fixes few bugs and reverts some changes:
- It's now possible to rewrite `404` (again). I believe it makes sense to rewrite `/404` even in SSG
- There were few bugs when calculating the URL to rewrite when `trailingSlash` is `"never"` and the user uses `Astro.rewrite("/")`
- I refactored the logic of `tryRewrite` and moved inside a generic function, since there was shared logic
- 
I created new test cases with custom `404.astro` and default 404.
I created new test cases with `trailingSlash: "never"`
N/A
=> fix(rewrite): allow to rewrite 404 and take `base` into consideration

.changeset/quiet-doors-eat.md, packages/astro/src/actions/runtime/virtual/server.ts
This PR removes the type override for the `accept` parameter in the `defineAction` Actions function.
Fernando Herrera pointed out earlier that the `accept` param for `defineAction` only suggested `json` in the intellisense instead of both `json` and `form`.
Now I'm not going to pretend I understand _everything_ going on in the typing for the `accept` param here. But I'm pretty sure the `= 'json'` here is redundant.
https://discord.com/channels/830184174198718474/1252972140161142816/1252996832238506056
Before:
After:
No tests are necessary here I think?
No docs are necessary as I think this is a bug fix?
=> bug: removes type override from defineAction

.changeset/big-eyes-share.md, packages/astro/src/core/app/index.ts, packages/astro/src/core/cookies/cookies.ts, packages/astro/src/core/cookies/response.ts, packages/astro/src/core/render-context.ts, packages/astro/test/astro-cookies.test.js, packages/astro/test/fixtures/astro-cookies/src/pages/from-endpoint.ts, packages/astro/test/fixtures/astro-cookies/src/pages/from.astro, packages/astro/test/fixtures/astro-cookies/src/pages/rewrite-target.astro, packages/astro/test/fixtures/astro-cookies/src/pages/to-endpoint.ts
Ensures that `set-cookie` headers are set when rewriting a request.
Fixes #11265
Adds a test case for a rewritten request
Just a bugfix
=> fix: allow cookies to be set in rewritten responses

.changeset/tricky-mirrors-carry.md, packages/astro-rss/src/index.ts
Closes https://github.com/withastro/astro/issues/11287
The types between type `RSSFeedItem` and the `rssSchema` were not aligned
I locally tested the change, and type error is now gone
N/A
=> fix(rss): correct types for `RSSFeedItem`

.changeset/small-badgers-juggle.md, packages/astro/e2e/fixtures/view-transitions/astro.config.mjs, packages/astro/e2e/fixtures/view-transitions/src/pages/one.astro, packages/astro/e2e/fixtures/view-transitions/src/pages/redirect.astro, packages/astro/e2e/view-transitions.test.js, packages/astro/src/transitions/router.ts
Fixes #11301 
when redirected to a different origin, interrupt loading and do a full page reload the redirected URL 
Added new e2e testcase
n.a.
=> Fall back to page reload when redirected to a cross origin URL

.changeset/lovely-parents-attend.md, packages/integrations/vercel/src/lib/nft.ts, packages/integrations/vercel/src/serverless/adapter.ts, packages/integrations/vercel/src/static/adapter.ts, packages/internal-helpers/package.json, packages/internal-helpers/src/fs.ts
The `@astrojs/vercel` package includes some filesystem helpers that would be useful in other packages. This PR moves them into the `internal-helpers` package.
There should be no change in behaviour
=> chore: extract fs helpers into shared internal-helpers package

.changeset/swift-ladybugs-sniff.md, packages/astro/src/vite-plugin-astro-server/error.ts
- Removes errors that occur during dev, such as code errors, as they result in a lot of telemetry data.
N/A
N/A
=> Remove non-fatal errors from telemetry

.changeset/rare-singers-try.md, packages/astro/src/runtime/client/dev-toolbar/ui-library/tooltip.ts
Fixes the margin in the tooltip title SVG icon to work in both RTL and LTR layouts
I didn't add a test because I think the change I made is extremely small. Plus I only found a test for [tooltip-positon](https://github.com/withastro/astro/blob/16af927e14b443eaf2722b51ab1d5c43e64812d1/packages/astro/e2e/fixtures/dev-toolbar/src/pages/tooltip-position.astro)
Nothing changed or needs to be changed in the docs.
=> [ui] fix margin around devtool tooltip icon in `rtl`

.changeset/selfish-impalas-cough.md, .changeset/strong-news-yawn.md, .npmrc, packages/astro/package.json, packages/astro/src/cli/install-package.ts, packages/db/package.json, packages/studio/package.json, pnpm-lock.yaml
We can use `require.resolve()` instead of the `resolve` package for resolving.
Also simplifies the resolving of `@astrojs/db` by hoisting it up so it can be resolved from `packages/astro/dist/cli/install-package.js`. While we could also install `@astrojs/db` as a devdep in `packages/astro/package.json` to fix it, it would however create a cyclic workspace dependency between `astro`, `@astrojs/db`, and `@astrojs/studio`.
In order to simplify the code, I had to tweak the exports condition of `@astrojs/db` and `@astrojs/studio` to allow importing ESM from CJS (by `require.resolve`). This would also unblock a future Node.js feature where you could import ESM from CJS as long as there's no top-level await. In practice, I also find that it's best practice to use the `import` condition only if …
=> Remove resolve package and refactor db & studio exports

.changeset/happy-boxes-collect.md, packages/astro/src/container/index.ts, packages/astro/src/container/pipeline.ts, packages/astro/src/content/vite-plugin-content-virtual-mod.ts, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/core/compile/compile.ts, packages/astro/src/core/config/config.ts, packages/astro/src/core/config/validate.ts, packages/astro/src/core/util.ts, packages/astro/src/core/viteUtils.ts, packages/astro/src/jsx/babel.ts, packages/astro/src/jsx/rehype.ts, packages/astro/src/vite-plugin-astro-server/pipeline.ts, packages/astro/src/vite-plugin-astro-server/resolve.ts, packages/astro/src/vite-plugin-astro-server/scripts.ts, packages/astro/src/vite-plugin-scanner/index.ts, packages/astro/test/units/config/config-validate.test.js, packages/astro/test/units/i18n/astro_i18n.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/11128
The container was indirectly pulling and importing some modules that were importing `vite`.
This PR attempts to breakdown the files in order to not import `vite` inside `astro/container`
I tested locally the reproduction provided.
N/A
=> fix(container): breakdown files to avoid importing `vite`

.changeset/famous-maps-notice.md, packages/astro/src/cli/install-package.ts
fix https://github.com/withastro/astro/issues/11344
Refactor the way `require.resolve` is called. It failed before because the `process.cwd()` didn't have a trailing slash, so it wasn't resolve from the project directory, but its parent, which doesn't contain the `node_modules` to check packages for.
I refactored it to use the `paths` option because it's simpler and we also had a similar code like this.
https://github.com/withastro/astro/blob/dc95d674af8792773693d491a1f7520d0260e20b/packages/astro/src/core/routing/manifest/create.ts#L347
Tested manually by editing the node_modules. I wasn't testing this correctly before because I linked the package, which resolves differently.
n/a. bug fix.
=> Fix getPackage resolve path

.changeset/curvy-elephants-fry.md, packages/astro/src/core/render-context.ts, packages/astro/test/actions.test.js, packages/astro/test/astro-cookies.test.js
Closes https://github.com/withastro/docs/issues/8660
N/A
=> fix: check experimental flag when using the rewrite function

.github/ISSUE_TEMPLATE/config.yml
- Puts Support 3rd instead of last to try avoid getting support in issues
=> chore: reorder issues templates

packages/astro/src/content/data-store.ts, packages/astro/src/content/file.ts, packages/astro/src/content/loaders.ts, packages/astro/src/content/utils.ts, packages/astro/src/content/vite-plugin-content-virtual-mod.ts, packages/astro/src/core/dev/dev.ts, packages/astro/test/content-layer.test.js, packages/astro/test/test-utils.js, packages/astro/types/content.d.ts
- adds a `watcher` to the loader props, which can be used to update data. I've not tried to do anythign with scoping the watcher, because I think it's best to allow flexibility there
- uses this watcher in the `file()` loader to reload data when the file changes
- because we now can change data in the store outside of the main lifecycle, I've needed to add support for automatically saving changes to disk. I did this with a debounced save function that's automatically called whenever the store is changed. This will save to disk 500ms after the last data change
- during dev, it watches the data store file and invalidates the virtual module when it changes
Adds `dev` tests, including one that edits the data file
=> fix: watch for content layer changes

.changeset/small-ties-sort.md, packages/astro/src/runtime/server/render/util.ts, packages/astro/test/astro-attrs.test.js, packages/astro/test/fixtures/astro-attrs/src/pages/index.astro, packages/integrations/mdx/test/mdx-vite-env-vars.test.js
fix https://github.com/withastro/astro/issues/11342
Makes sure that normal attributes (e.g. `foobar={...}`) and data attributes (.e.g `data-foobar={...}`) renders correctly if given `true` or `false` values, which now they will render as `="true"` and `="false"` respectively. Only known HTML [boolean attributes](https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML) can omit the value.
This refactor also enables reverting some fixes from https://github.com/withastro/astro/pull/2538 as the base case covers the behaviour now.
Updated `astro-attrs` test
Added changeset. I think the changes are a bit subtle and shouldn't break anything, but do we want to to list an exhaustive example of how different values get rendered as what?
=> Fix attribute rendering for boolean values

.changeset/fair-wolves-move.md, packages/astro/src/core/errors/overlay.ts
- This PR adjusts the color of punctuations in error layout, aiming to improve the contrast in light mode
- Closes #11373
| ------ | ----- |
| ![before](https://github.com/withastro/astro/assets/40516784/07ec3c71-3016-40a6-b9f4-1ae68a840c88) | ![after](https://github.com/withastro/astro/assets/40516784/a72186ab-fe8b-448a-92c7-c9086100bed1) |
- Manually tested
- N/A
=> fix(overlay): adjust the color of punctuations

.changeset/brave-mayflies-share.md, packages/astro/src/i18n/index.ts, packages/astro/src/virtual-modules/i18n.ts, packages/astro/test/fixtures/i18n-routing-manual-with-default-middleware/src/pages/en/start.astro, packages/astro/test/i18n-routing-manual-with-default-middleware.test.js
Closes https://github.com/withastro/astro/issues/11355
The utility functions were still using the `strategy = "manual"`. The fix updates `strategy` to the new value.
Added new test cases.
N/A
=> fix(i18n): update strategy when defining manually astro i18n middleware

.changeset/curvy-kids-call.md, packages/astro/src/core/render-context.ts, packages/astro/src/runtime/server/render/page.ts, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/fixtures/rewrite-i18n-manual-routing/astro.config.mjs, packages/astro/test/fixtures/rewrite-i18n-manual-routing/package.json, packages/astro/test/fixtures/rewrite-i18n-manual-routing/src/middleware.js, packages/astro/test/fixtures/rewrite-i18n-manual-routing/src/pages/index.astro, packages/astro/test/rewrite.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/11306
The issue was caused by `this.status` inside the `RenderContext` class. This status code is then passed to the `SSResult` and used as initial status of `Response`. 
This status code was passed by `route.ts`. It was a 404 because `/foo` didn't match any route, however we still call the middleware because the user chose `routing: 'manual'`.
When we arrived to the middleware, we executed the rewrite, and we need update this status code in case we find a `RouteData` and a `ComponentInstance`.
I moved the shared logic inside a new, private, function called `#executeRewrite` as per @florian-lefebvre suggestion.
N/A
=> fix(rewrite): correctly update the status code during a rewrite

packages/astro/src/content/loaders.ts, packages/astro/src/content/types-generator.ts, packages/astro/src/content/utils.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/content/config.ts, packages/astro/test/fixtures/content-layer/src/pages/collections.json.js, packages/astro/types/content.d.ts
Adds a simplified syntax for loaders, for cases where no granular updates or delta sync is needed. The loader returns an array of objects, which regenerates the collection from scratch, replacing the existing content. This is meant to be available in addition to the lower level loader API, but I don't know how best to explain this, or if this is the right approach so would welcome feedback. This is the API as implemented in this PR:
```ts
const cats = defineCollection({
type: "experimental_data",
loader: async function() {
return  [{
"breed": "Siamese",
"id": "siamese",
"size": "Medium",
"origin": "Thailand",
"lifespan": "15 years",
"temperament": ["Active", "Affectionate", "Social", "Playful"]
},
{
"breed": "Persian",
"id": "persian",
"size": "Medium",
"origin": "Iran",
"lifespan": "15 …
```
=> feat: adds simple loader

.changeset/calm-rules-trade.md, packages/astro/src/runtime/server/render/util.ts, packages/astro/test/astro-attrs.test.js, packages/astro/test/fixtures/astro-attrs/src/pages/index.astro, packages/integrations/mdx/test/mdx-vite-env-vars.test.js
This reverts commit e6de11f4a941e29123da3714e5b8f17d25744f0f.
- This was discovered to break Starlight.
- We should probably wait on 5.0 for this.
N/A
N/A
=> Revert "Fix attribute rendering for boolean values (#11369)"

packages/astro/e2e/fixtures/server-islands/src/components/Island.astro, packages/astro/e2e/fixtures/server-islands/src/pages/index.astro, packages/astro/e2e/server-islands.test.js, packages/astro/src/core/server-islands/endpoint.ts, packages/astro/src/runtime/server/render/component.ts, packages/astro/src/runtime/server/render/server-islands.ts, packages/astro/src/runtime/server/render/slot.ts
- Slots are statically rendered into a string and included in the original HTML.
- When an island posts back it includes those slots to the server environment so that it can use them.
- E2E test added to verify the full flow works.
N/A
=> Pass slots to server islands

examples/server-islands/astro.config.mjs, packages/astro/e2e/fixtures/server-islands/astro.config.mjs, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/plugins/plugin-ssr.ts, packages/astro/src/core/config/schema.ts, packages/astro/src/core/create-vite.ts, packages/astro/test/fixtures/server-islands/hybrid/astro.config.mjs, packages/astro/test/fixtures/server-islands/ssr/astro.config.mjs
- Create the experimental flag and only enable the vite plugin when its used.
- Updated tests
N/A
=> Require the experimental flag to use server islands

.changeset/nasty-poems-juggle.md, package.json, packages/astro/package.json, packages/astro/src/actions/runtime/utils.ts, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/src/actions/runtime/virtual/shared.ts, packages/astro/test/types/is-input-error.ts, packages/astro/tsconfig.tests.json, pnpm-lock.yaml
Expand `isInputError` to accept `unknown` as a type, so it can narrow any error object to an `ActionInputError`. This is [per feedback in the RFC.](https://github.com/withastro/roadmap/pull/912#issuecomment-2211537388)
- Add type override for `unknown`
- Document the purpose of `ErrorInferenceObject`. The reason for this utility type was unclear originally
Manually tested that `isInputError` still type narrows and preserves the `error.fields` types
=> Actions: expand `isInputError` to accept `unknown`

.changeset/swift-cows-walk.md, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/test/types/define-action-accept.ts
Fixes the issue originally reported by https://github.com/withastro/astro/pull/11292
Default the `accept` property to `undefined` instead of `json`. This shows the correct string completions while preserving behavior when `accept` is omitted.
Manual type testing
N/A
=> Fix: Actions `accept` type completions

.changeset/small-vans-own.md, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/test/types/action-return-type.ts
Expose an `ActionReturnType` utility to infer the result of an action. This is simpler than the usual `Awaited<ReturnType<typeof action>>`.
Added type test
See changeset
=> feat: `ActionReturnType`

.changeset/loud-socks-doubt.md, packages/astro/src/env/schema.ts, packages/astro/test/units/config/config-validate.test.js
This PR closes & fixes the bug reported in #11430 
- Updated the `EnvSchema` validators regex pattern to also allow for numbers
- Updated the `EnvSchema` validator to reject if the first character is a number (Not a valid identifier)
- Added 2 new unit tests to account for the above changes
- `Should allow schema variables with numbers`
- `Should not allow schema variables starting with a number`
Added changeset & did not update any docs as currently there is no documentation to modify informing users that numbers were not previously allowed.
Though I am unsure if it is worth adding a comment for users to be aware of this, or just let the edge case error message inform them?
=> feat: astro:env allow schema keys to include numbers

.changeset/plenty-socks-talk.md, packages/astro/src/@types/astro.ts, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/src/actions/runtime/virtual/shared.ts
Expose `astro:actions` utility types for library authors per [feedback in the RFC](https://github.com/withastro/roadmap/pull/912#issuecomment-2209635918).
- Expose `ACTION_ERROR_CODES` const with `ActionErrorCode` type
- Expose `ActionHandler` type
- Rename `Accept` to `ActionAccept` and `InputSchema` to `ActionInputSchema`. These types were already use-facing and deserve a namespace.
N/A
=> Actions: expose utility types

.changeset/calm-beans-jam.md, packages/astro/src/runtime/client/dev-toolbar/apps/audit/rules/a11y.ts
- Adds `tabpanel` to [`aria_non_interactive_roles`](https://github.com/withastro/astro/blob/88e2b43305c07ef8b489081a5a580584cbd7f342/packages/astro/src/runtime/client/dev-toolbar/apps/audit/rules/a11y.ts#L67)
- Allows `tabIndex` on elements with `tabpanel` role
- Closes #11239
| ------ | ----- |
| ![before](https://github.com/user-attachments/assets/92eb8507-e784-4efc-90d3-4a3b398f7607) | ![after](https://github.com/user-attachments/assets/9543d61e-b2bd-4e1c-917b-1cb65b213e7e) |
- Manually tested with a minimal Starlight project containing the built-in `Tabs` and `TabItem` components
- N/A
=> fix(audit): remove false positive warnings on elements with `tabpanel` role

.changeset/proud-singers-call.md, packages/astro/src/core/dev/container.ts
- Fixes #11374
- Running `astro dev --open` will no longer spawn extra tabs when saving config files
To reproduce the manual test locally:
Run build with changes
```
pnpm run build
```
Run astro dev
```
pnpm --filter astro dev
```
Test the changes using the following example:
```
pnpm --filter @example/minimal dev --open
```
**Expected behavior:**
- Open new tab on first run of dev command, then update the same tab on each file save
- Saving config files shouldn't spawn new tabs
Unexpected behavior has been fixed, no additional docs needed
=> fix(astro): do not open new tab when saving config files

.changeset/chatty-spies-jog.md, packages/astro/src/core/create-vite.ts
- Astro currently tells Vite to scan most of `src/` (excluding endpoints in `src/pages/`)
- This PR makes that scan much more targeted at only known framework component formats
- The thinking is that the target for that scan is to optimize client-side code and this will catch most of it
- It avoids eagerly transforming code that is not intended for the client, which can include:
- server utilities
- documentation snippets only imported with `?raw`
Tests should pass I think — would love feedback from @bluwy 
n/a — internal change
=> Only add framework component formats to Vite’s `optimizeDeps`

.changeset/wise-cameras-trade.md, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/env/validators.ts, packages/astro/src/env/vite-plugin-env.ts, packages/astro/test/env-secret.test.js, packages/astro/test/units/env/env-validators.test.js, pnpm-lock.yaml
- Closes #11381
- Improves `astro:env` errors by now tracking what constraints fail
Updated unit tests
N/A
=> feat: better astro:env errors

.changeset/new-mails-prove.md, packages/astro/src/actions/runtime/virtual/server.ts
In the experimental Astro actions, users can provide an input schema using zod and parse formdata natively with `accept: 'form'`. However, if a user uses the `.nullish()` zod modifier, it will always treat the field as a string, regardless of the intended type.
This is because zod's `.nullish()` is equivalent to `.nullable().optional()` and returns `z.ZodOptional<z.ZodNullable<ActualType>>` and must be double-unwrapped to get the underlying type.
This change swaps from a single-unwrap of `ZodOptional` and `ZodNullable` to a loop that can go as deep as needed.
This change was not tested.
No docs were written or changed as this is a bugfix.
=> Fix action form parsing for .nullish

.changeset/twenty-maps-glow.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/render/paginate.ts
Add `page.url.first`, `page.url.last` to the Page interface.
Closes https://github.com/withastro/roadmap/discussions/862
I couldn't find relevant tests for `page.url`. Let me know if there is one already.
This needs to be updated
https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/routing.mdx#complete-api-reference
=> feat: add first and last to the Page interface

.changeset/chilled-impalas-dance.md, packages/astro/src/core/constants.ts, packages/astro/src/core/render-context.ts, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/rewrite.test.js
Closes https://github.com/withastro/astro/issues/11306 once for all :)
The issue was specific to the dev server, where I didn't create a test for that.
I broke down the logic that was in place regarding the rerouting because it conflicts with the rewrite of the users. So I decided create a new header with its own logic
I created a test
=> fix: avoid response rewrite inside the dev server

.changeset/thin-dodos-serve.md, packages/astro/components/Code.astro
Adds Shiki's `defaultColor` option to the `<Code />` component
Because most of the work has been done by #11341, this PR is a partial implementation and depends on #11341 to work properly. Therefore this PR should be merged together with #11341, or alternatively let #11341 inherit this PR's changes and close this PR. (Pinging @madcampos for the heads up)
This PR comes from withastro/roadmap#897
Not sure how to make automated tests
I've published a [testing branch](https://github.com/ARipeAppleByYoursTruly/astro/tree/pr/11341). The tests are located at [examples/component-code](https://github.com/ARipeAppleByYoursTruly/astro/tree/pr/11341/examples/component-code). They test all possible values of `defaultColor`
How to run the example:
1. `pnpm install`
2. `pnpm run dev`
3. `pnpm --filter …
=> Add Shiki's `defaultColor` option to `<Code />` component

packages/astro/src/runtime/server/render/astro/factory.ts, scripts/smoke/check.js
- The example depends on `workspace:*` so skipping for now.
- In the Server Islands PR I replaced some `any`s with their real types. For some reason this one broke the `<Content />` component and I don't know why.
Fixes them
N/A
=> Fix smoke tests

.changeset/cuddly-days-relate.md, packages/astro/src/container/index.ts, packages/astro/src/core/app/index.ts, packages/astro/src/core/app/pipeline.ts, packages/astro/src/core/app/types.ts, packages/astro/src/core/base-pipeline.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/pipeline.ts, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/core/routing/default.ts, packages/astro/src/vite-plugin-astro-server/pipeline.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/astro/test/units/test-utils.js
- Cloudflare doesn't support `import.meta.url`. This functionality is only used in dev mode, so the URL doesn't matter in prod.
- Moved the logic for determining the root into the manifest so it has default values in the build. This value is "wrong" in prod but is ignored anyways.
- Existing tests should pass
N/A, bug fix
=> fix: make root serializable

.changeset/tidy-shrimps-grab.md, packages/astro/src/container/index.ts, packages/astro/src/core/app/index.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/routing/default.ts, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/core/routing/manifest/pattern.ts, packages/astro/src/core/server-islands/endpoint.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/integrations/vercel/test/fixtures/server-islands/astro.config.mjs, packages/integrations/vercel/test/fixtures/server-islands/package.json, packages/integrations/vercel/test/fixtures/server-islands/src/components/Island.astro, packages/integrations/vercel/test/fixtures/server-islands/src/pages/index.astro, packages/integrations/vercel/test/server-islands.test.js, pnpm-lock.yaml
- Vercel, and probably other adapters only allow pre-defined routes. This makes it so that the `astro:build:done` hook includes the `_server-islands/` route as part of the route data, which is used to configure available routes.
- Test added to Vercel
N/A, bug fix
=> Fix Server Islands in Vercel

packages/astro/CHANGELOG.md
Updates a code sample to fix a missing `:` in the CHANGELOG
no tests
only docs.
=> fix typo in CHANGELOG

.changeset/orange-boats-trade.md, packages/astro/e2e/dev-toolbar.test.js, packages/astro/src/runtime/client/dev-toolbar/toolbar.ts
The dev toolbar shows in every page when running `window.print()` (<kbd>CTRL</kbd> + <kbd>P</kbd>), which is useless and disturbing when working on styling a page for printing. This change hides the dev toolbar on printing.
If you see a point in having it on each page when printing, then I suggest adding a settings option to hide it.
Before:
After:
Tested by emulating media print and checking visibility with Playwright.
No usage instructions or important details to be mentioned.
=> Hide the dev toolbar on print

.changeset/cold-ravens-dream.md, packages/astro/client.d.ts
My initial PR added it to the type, but not to the exports of said type. oops
N/A
=> fix: inferRemoteSize not being exported in the type

.changeset/spotty-camels-joke.md, packages/astro/src/transitions/router.ts
Adds a missing export for the `getFallback()` function of the client side router.
makes this go away:
n.a. / bugfix
=> Adds missing export

.changeset/blue-jars-hang.md, packages/astro/src/core/messages.ts, packages/astro/src/vite-plugin-astro-server/route.ts
This PR enhances the logging of the dev server when there's a rewrite
I tested locally
The logic of the colours stays the same, which means the colour reflects the **final** status code.
=> fix: better logging for rewrites

.changeset/empty-onions-buy.md, packages/astro/src/@types/astro.ts
Just fixes two typos in the Server Islands config reference
no tests
only docs
=> [docs] fix typos in config reference

.changeset/smart-snakes-promise.md, packages/astro/src/runtime/server/render/server-islands.ts
Discussed with @FredKSchott that this is OK to disclose since Server Islands are still experimental.
It's generally not safe to use `JSON.stringify` to interpolate potentially attacker controlled data into `<script>` tags as JSON doesn't escape `<>"'` and so one can use it to break out of the script tag and e.g. make a new one with controlled content.
See https://pragmaticwebsecurity.com/articles/spasecurity/json-stringify-xss
No behavior change expected. All tests should still pass unless they trigger the encoding change.
Not at all. I couldn't get tests to run.
=> Fix an XSS in Server Islands.

.changeset/clever-pillows-boil.md, packages/astro/src/vite-plugin-astro-server/vite.ts, packages/astro/test/astro-basic.test.js, packages/astro/test/fixtures/astro-basic/src/pages/import-queries/_content.astro
fix https://github.com/withastro/astro/issues/11502
When crawling the module graph for scripts and styles to inline into the HTML, we skip modules with vite special queries like `?url` or `?raw`
updated test
n/a. bug fix.
=> Exclude hoisted scripts and styles from raw imports

packages/astro/src/content/data-store.ts, packages/astro/src/content/loaders/glob.ts, packages/astro/src/content/loaders/types.ts, packages/astro/src/content/runtime.ts, packages/astro/src/content/sync.ts, packages/astro/src/content/types-generator.ts, packages/astro/src/content/utils.ts, packages/astro/src/core/dev/dev.ts, packages/astro/src/core/sync/index.ts, packages/astro/templates/content/types.d.ts, packages/astro/test/fixtures/content-layer/src/content/config.ts, packages/astro/types/content.d.ts
Creates a separate `experimental_content` type alongside `experimental_data` to allow the `render()` and `rendered` properties to be added to the types. Makes the data store types generic and fixes the collection definition types so that types are enforced better for manually-defined loaders.
=> chore: fix content layer types

packages/astro/src/cli/build/index.ts, packages/astro/src/core/build/index.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/content/config.ts, packages/astro/test/fixtures/content-layer/src/pages/collections.json.js, packages/astro/test/test-utils.js
Cleans the content layer data store when `astro build --force` is run. This matches the behavior for content collection caching.
Added tests for builds with and without the flag.
This will need to be included in the docs when content layer is added
=> Clean content layer with `--force`

.changeset/mighty-mirrors-try.md, packages/astro/src/@types/astro.ts
Update the inline documentation (JSDoc comment) for `Astro.redirect`:
* Closes #11544
I haven't added a changeset since it is a small change. Should I?
No test. I only reworded a comment.
No doc needed since it does not change the behavior. However it could be a nice addition to clarify the difference between `server` and `static` with `Astro.redirect` (I can post a suggestion on `astro/docs` separately of this PR).
=> fix(types): update Astro.redirect JSDoc comment

.changeset/violet-coats-fail.md, packages/astro/src/cli/add/index.ts
- Fix how `astro add` handles packages with only prerelease versions.
No tests exist for `astro add`. Should we add some?
Not something that is documented or needs new documentation.
=> Fix astro add for prerelease packages

.changeset/tidy-needles-build.md, packages/astro/src/core/build/plugins/plugin-content.ts, packages/astro/test/experimental-content-collections-cache-invalidation.test.js, packages/astro/test/fixtures/content-collections-same-contents/astro.config.mjs, packages/astro/test/fixtures/content-collections-same-contents/package.json, packages/astro/test/fixtures/content-collections-same-contents/src/content/config.ts, packages/astro/test/fixtures/content-collections-same-contents/src/content/docs/one.md, packages/astro/test/fixtures/content-collections-same-contents/src/content/docs/two.md, packages/astro/test/fixtures/content-collections-same-contents/src/pages/docs.astro, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/9499
I added a new test case, and I tested it locally using the reproduction provided [here](https://github.com/withastro/astro/issues/9499#issuecomment-2028752134)
=> fix: cache collections using file name too

packages/astro/src/content/data-store.ts, packages/astro/src/content/types-generator.ts
Small fixes to types for rendered content layer content
=> Fixes to content layer render types

.changeset/wicked-books-sip.md, packages/astro/e2e/fixtures/server-islands/astro.config.mjs, packages/astro/e2e/server-islands.test.js, packages/astro/src/@types/astro.ts, packages/astro/src/core/render-context.ts, packages/astro/src/runtime/server/render/server-islands.ts
- Uses `trailingSlash` config in order to append a trailing slash to the island request. Only done when set to `always`.
- Test updated
N/A, bug fix
=> Fix server islands with trailingSlash: always

.changeset/gorgeous-timers-tease.md, packages/create-astro/src/actions/template.ts
If create-astro fails when downloading a template, it currently only logs something unhelpful like "fetch error". This leads to reports like #11396, which is probably mutliple different issues. This PR changes it to traverse into `err.cause` to find the underlying error from undici.
Fixes #11396
Tested by disabling the network after starting the command, which gave "Error: getaddrinfo ENOTFOUND api.github.com"
=> fix(create-astro): log fetch errors

.changeset/violet-drinks-film.md, packages/astro/e2e/errors.test.js, packages/astro/e2e/fixtures/errors/src/pages/dom-exception.astro, packages/astro/src/core/errors/dev/utils.ts
Unusually, some errors have some of their properties read-only. Since this has only happened once in the history of Astro, I figure it wasn't worth it to shield *everything*, but just adding checks for the common properties should be enough
Fixes https://github.com/withastro/astro/issues/11538
Added a test
N/A
=> fix: check before writing to errors

packages/astro/src/content/consts.ts, packages/astro/src/content/data-store.ts, packages/astro/src/content/sync.ts, packages/astro/src/content/vite-plugin-content-virtual-mod.ts, packages/astro/src/core/dev/dev.ts, packages/astro/src/core/sync/index.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/content/config.ts, packages/astro/test/fixtures/content-layer/src/pages/collections.json.js, packages/astro/test/fixtures/content-layer/src/utils.js
Switches content layer to use devalue for the data store serialization, so it supports Dates etc
Added a test
=> feat: use devalue to serialize content layer data

.changeset/old-bats-travel.md, packages/astro/e2e/errors.test.js, packages/astro/e2e/test-utils.js, packages/astro/src/core/errors/dev/vite.ts
Shiki 1.0 removed the `lineOptions` property, so our line highlighting stopped working. For some reason, this didn't cause a type error.
Added a test
N/A
=> fix: highlight line with error in the error overlay

.changeset/tasty-rockets-jog.md, packages/astro/src/actions/runtime/route.ts, packages/astro/test/actions.test.js, packages/astro/test/fixtures/actions/src/actions/index.ts
Allows actions to return falsy values by changing the result.data check to a strict inequality check for undefined. Fixes #11549
- Added tests for 0 and false return values.
I don't think this requires docs, reading them I'd expect returning a value of 0 or false to work.
=> actions: check result.data is not undefined instead of truthy

.changeset/light-chairs-happen.md, packages/astro/e2e/fixtures/actions-blog/src/components/Like.tsx, packages/astro/e2e/fixtures/actions-blog/src/components/PostComment.tsx, packages/astro/e2e/fixtures/actions-react-19/src/actions/index.ts, packages/astro/e2e/fixtures/actions-react-19/src/components/Like.tsx, packages/astro/src/@types/astro.ts, packages/astro/src/actions/runtime/middleware.ts, packages/astro/src/actions/runtime/route.ts, packages/astro/src/actions/runtime/utils.ts, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/templates/actions.mjs, packages/astro/test/fixtures/actions/astro.config.mjs, packages/astro/test/fixtures/actions/src/pages/subscribe.astro, packages/astro/test/types/action-return-type.ts, packages/astro/test/types/is-input-error.ts, packages/integrations/react/server.js
Make `.safe()` the default return value for actions. This means `{ data, error }` will be returned when calling an action directly. If you prefer to get the data while allowing errors to throw, chain the `.orThrow()` modifier.
```ts
import { actions } from 'astro:actions';
// Before
const { data, error } = await actions.like.safe();
// After
const { data, error } = await actions.like();
// Before
const newLikes = await actions.like();
// After
const newLikes = await actions.like.orThrow();
```
- Update types and implementation to reverse this pattern
- Remove support for using unsafe action calls with React 19. Chaining `.orThrow()` will remove progressive enhancement, since exceptions must be caught on the client.
Update test fixtures to use the new API pattern.
RFC updates to be pushed …
=> Actions: Make `.safe()` the default return value

packages/astro/e2e/fixtures/server-islands/src/components/Self.astro, packages/astro/e2e/fixtures/server-islands/src/pages/index.astro, packages/astro/e2e/server-islands.test.js
- No code changes, this already works, just adding a test.
- Imports self, sets server:defer, verifies it adds itself once.
N/A
=> Verify you can use server:defer on self-imported module

.changeset/spotty-rice-shake.md, packages/astro/src/core/build/generate.ts
A small change in DX that renders times that exceed the 500ms in red.
=> feat: log slow pages in red

packages/astro/src/@types/astro.ts, packages/astro/src/cli/build/index.ts, packages/astro/src/cli/dev/index.ts, packages/astro/src/cli/flags.ts, packages/astro/src/cli/sync/index.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/dev/container.ts, packages/astro/src/core/sync/index.ts, packages/astro/test/content-layer.test.js
Adds support for the `--force` flag to `dev` and `sync`. It was already supported in `build`. 
Fixes PLT-2369
=> Support --force flag in sync and dev

packages/astro/src/core/errors/errors-data.ts
This updates a link in an error message to point to the new docs for `Astro.rewrite()`, as part of 4.13 docs.
no tests!
all docs!
=> Update errors-data.ts for Astro.rewrite release in 4.13

packages/astro/src/content/data-store.ts, packages/astro/src/content/sync.ts, packages/astro/src/content/utils.ts, packages/astro/src/content/vite-plugin-content-imports.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/dev/dev.ts, packages/astro/src/core/sync/index.ts, packages/astro/test/content-layer.test.js, packages/astro/test/test-utils.js
- calculates a digest of the content config file and adds it to the config object
- when the data store is instantiated, checks if the value has changed, and if it has then it clears the data store
- stores the new digest value in the meta store
Fixes PLT-2372
Fixes PLT-2374
Added a test
=> fix: clear content layer cache if config has changed

packages/astro/src/core/build/index.ts, packages/astro/src/core/build/internal.ts, packages/astro/src/core/build/page-data.ts, packages/astro/src/core/build/plugins/plugin-analyzer.ts, packages/astro/src/core/build/plugins/plugin-internals.ts, packages/astro/src/core/build/plugins/plugin-ssr.ts
While working on the prerender refactor, I found some code that weren't used and can be removed. Some state were called with `.set()` but never again with `.get()`.
=> Remove unused code

examples/basics/src/layouts/Layout.astro
While modifying my landing page I stumble on a `background-size` property on html tag doing nothing. 
Probably author of this [PR](https://github.com/withastro/astro/pull/7760) forgot to remove that line while adding requested changes.
I toggled that property in browser devtools.
=> chore: Remove unnecessary CSS in basic example

packages/astro/src/core/errors/errors-data.ts
Adds a new heading in `errors-data.ts` so that Action errors don't show up under Content Collection errors on the Docs Error reference index page.
Note: We'll probably add more headings/organization in the future so that "Astro Errors" isn't a dumping ground, but this clears up an actual problem with errors being in the wrong section!
No tests, only docs
Only updates the docs site!
=> [error docs] adds section heading for Actions

packages/astro/src/content/loaders/glob.ts
Files in `src/content` are automatically processed by content collections, so the glob loader should not be used for these. This might not be immediately obvious, and it will be tempting to use that folder for data. This PR avoids that by skipping any globbed files in the content dir, and logging a warning.
Fixes PLT-2373
=> fix: skip glob files in content dir

.changeset/shy-bees-look.md, packages/astro/src/runtime/client/dev-toolbar/apps/audit/rules/perf.ts
- Fixes #10891
- Previously used `element.offsetTop` to find the y position of the image, which does not work when the element parent has a position: relative property. 
- Instead, this uses `element.getBoundingClientRect().y` to get the real y position of the image. 
- There's one issue though. `getBoundingClientRect` returns the position relative to the user's viewport, not the absolute position. 
- So, add window.scrollY to the value, and you have the element's absolute position.
No new tests were added as this is a trivial fix.
No docs needed for this fix.
=> fix: audit incorrectly flagging images as above the fold (#10891)

packages/astro/src/content/loaders/glob.ts, packages/astro/src/content/sync.ts, packages/astro/src/core/dev/dev.ts, packages/astro/src/core/sync/index.ts, packages/astro/test/test-utils.js
As suggested by @bluwy, this refactors content layer into a central location. This is most useful in dev, where variosu events can trigger a re-sync. Currently this includes the content config changing, but in future will also include hot keys and integrations.
=> Refactor content layer into shared instance

packages/astro/src/content/runtime.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/loaders/post-loader.ts, packages/astro/test/fixtures/content-layer/src/pages/collections.json.js, packages/astro/test/fixtures/content-layer/src/utils.js
Adds support for the `filter` arg in `getCollection`
Updated fixtures to use the filter.
=> fix: support filters in content layer `getCollection`

.changeset/config.json, CONTRIBUTING.md
From my experience in the last prerelease, setting the `baseBranch` as `next` helps `pnpm changeset` generates a better list of "changed packages". I updated `CONTRIBUTING.md` to note this and fix some of its typos/grammars.
Ran `pnpm changeset` locally
n/a. chore
=> Update changeset base branch

.changeset/tiny-poems-battle.md, packages/astro/src/actions/runtime/route.ts, packages/astro/templates/actions.mjs, packages/astro/test/actions.test.js
Resolves #11515. We discovered that Actions sets the `content-type` to `application/json` even when the body is `undefined`. We set `content-length` to `0` for this case, but it seems some deployment platforms (Vercel) may remove this header if it detects an empty body.
This fix removes the `content-type` when no body is present.
- Add test for empty content type
- Add test for unexpected content type
N/A
=> Actions: fix 500 on empty object for Vercel serverless

packages/astro/package.json, packages/astro/test/units/i18n/astro_i18n.test.js
The `#astro/*` subpath imports was added in https://github.com/withastro/astro/pull/161 but it doesn't look like we're using it much today. I'm not sure if we still want to continue pushing to use the subpath imports, we can discuss here if so!
If not, I figured to remove it so it doesn't interfere with the auto-imports path completion so we always stick with relative paths.
n/a
n/a
=> Remove `#astro/*` subpath imports

eslint.config.js, packages/astro/e2e/errors.test.js, packages/astro/src/actions/runtime/middleware.ts, packages/astro/src/assets/utils/vendor/image-size/types/svg.ts, packages/astro/src/core/app/index.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/errors/dev/vite.ts, packages/astro/src/events/error.ts, packages/astro/src/runtime/client/dev-toolbar/ui-library/radio-checkbox.ts, packages/astro/src/transitions/router.ts, packages/astro/test/css-order-import.test.js, packages/astro/test/css-order.test.js, packages/astro/test/solid-component.test.js, packages/astro/test/ssr-api-route.test.js, packages/create-astro/src/actions/verify.ts, packages/db/test/unit/column-queries.test.js, packages/db/test/unit/reference-queries.test.js, packages/integrations/markdoc/src/content-entry-type.ts, packages/integrations/mdx/test/units/rehype-optimize-static.test.js, packages/integrations/node/src/serve-static.ts, packages/integrations/vue/src/editor.cts, packages/markdown/remark/src/highlight.ts, packages/markdown/remark/src/rehype-collect-headings.ts
Adds the [regexp/prefer-regexp-test](https://ota-meshi.github.io/eslint-plugin-regexp/rules/prefer-regexp-test.html#regexp-prefer-regexp-test) and [regexp/prefer-regexp-exec](https://ota-meshi.github.io/eslint-plugin-regexp/rules/prefer-regexp-exec.html) lint rules, which helps with perf. I've benchmarked it in the past, like in https://github.com/lukeed/polka/pull/210, where preferring `regex.exec` over `string.match` is faster.
I didn't add a changeset as it's mostly a refactor, but if anyone feels like the changes are a bit big, I'm happy to add a changeset too.
=> Improve regex performance

packages/astro/src/content/runtime.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/test/fixtures/content-layer/src/pages/index.astro
The `getEntryBySlug` and `getDataEntryById` functions are deprecated. Previously they were implemented in content layer, but as they'll already be marked as deprecated once it is stable, we can safely not implement them for content layer collections. This PR adds a new AstroError that is thrown if a user attempts to call either of them with a content layer collection.
Adds a new AstroError
=> Throw when using deprecated `getEntryByX` functions with content layer

packages/astro/src/content/data-store.ts, packages/astro/src/content/loaders/types.ts
A few small changes to types and additions to JSDocs
=> Updates to content layer types and jsdocs

pnpm-lock.yaml, scripts/package.json, scripts/smoke/check.js
Remove `tsconfig-resolver` altogether as we've moved to `tsconfck`. I also simplified the `check.js` when an example has no tsconfig.
Ran `pnpm:test-examples` manually. Also tested that it fails if there's a TS error.
=> Remove tsconfig-resolver from repo

.changeset/young-pillows-shave.md, packages/astro/src/core/build/css-asset-name.ts, packages/astro/src/core/build/plugins/plugin-css.ts
Astro's css plugin generates chunk ids that include a hash of all of the chunk's parent ids.  These ids are currently the absolute file paths of the parent files.  The generated chunk ids are then inserted into those pages as import statements.
Because these import statements include a hash based on these absolute file paths, this causes rollup to generate different hashes for those pages when a build is run in different environments.  The exact same project will produce identical assets with different filenames when built on different machines, or when built from different directories on the same machine, etc.
To fix this, I've stripped out the working directory of these file paths before they are added to the hash.  This means that the hash will still change if the files referencing it …
=> Consistent file hashes

.changeset/big-tables-pump.md, packages/astro/src/actions/runtime/middleware.ts, packages/astro/test/actions.test.js
We currently raise an error when `_astroAction` is present on a GET request. This breaks page refreshes when viewing a POST result. We should remove the error for now, and reimplement if the redirect PR is accepted: https://github.com/withastro/astro/pull/11603
=> Actions: remove "action used with get" error

.changeset/early-experts-retire.md, packages/astro/src/@types/astro.ts
=> chore: improve astro:env docs

.changeset/gold-seas-crash.md, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/test/types/action-return-type.ts
Resolves [RFC comment](https://github.com/withastro/roadmap/pull/912#issuecomment-2275277245) reporting that `orThrow()` is missing when `input` is omitted.
This was uncaught due to type casting in the handler assignment code. A fix isn't simple in the near term, so a type test has been added.
- Add return type test when `input` is omittted.
N/A
=> Actions: fix missing orThrow type when input is omitted

packages/astro/src/@types/astro.ts, packages/astro/src/content/runtime.ts, packages/astro/templates/content/types.d.ts, packages/astro/test/fixtures/content-layer-rendering/content-outside-src-mdx/iguana.mdx, packages/astro/test/fixtures/content-layer/src/pages/spacecraft/[slug].astro
This PR updates the `render(entry)` function so that it returns the same values as `entry.render()` for all entry types. We will document this as the preferred way to access headings for markdown too.
Updated fixtures
I will update the RFC and other docs
=> Normalize content layer render function return value

.changeset/quick-ads-exercise.md, packages/astro/test/astro-component-code.test.js, packages/markdown/remark/src/shiki.ts
Originally planned in https://github.com/withastro/astro/pull/9643#discussion_r1446083665
The new token names follow Shiki v1's defaults and allows us to remove the compat replacements before.
Updated test
It doesn't look like docs document this particular usecase with css-variables shiki theme, so it doesn't need an update there, but it'll need an entry for the migration guide for sure.
=> Update to new shiki token names

packages/astro/package.json, packages/astro/src/content/loaders/glob.ts, packages/astro/test/content-layer-markdoc.test.js, packages/astro/test/content-layer-render.test.js, packages/astro/test/fixtures/content-layer-markdoc/astro.config.mjs, packages/astro/test/fixtures/content-layer-markdoc/content/_nested.mdoc, packages/astro/test/fixtures/content-layer-markdoc/content/blog/_counter.mdoc, packages/astro/test/fixtures/content-layer-markdoc/content/blog/with-components.mdoc, packages/astro/test/fixtures/content-layer-markdoc/markdoc.config.ts, packages/astro/test/fixtures/content-layer-markdoc/package.json, packages/astro/test/fixtures/content-layer-markdoc/src/components/Code.astro, packages/astro/test/fixtures/content-layer-markdoc/src/components/Counter.tsx, packages/astro/test/fixtures/content-layer-markdoc/src/components/CounterWrapper.astro, packages/astro/test/fixtures/content-layer-markdoc/src/components/CustomMarquee.astro, packages/astro/test/fixtures/content-layer-markdoc/src/components/DeeplyNested.astro, packages/astro/test/fixtures/content-layer-markdoc/src/content/config.ts, packages/astro/test/fixtures/content-layer-markdoc/src/pages/index.astro, pnpm-lock.yaml
Support markdoc (and any other integration that is implemented in the same way).
Really the only work here was ensuring `glob()` knew to handle types aside from 'mdx' using deferred rendering. Right now the way I've done it is to check if the entryType defines `contentModuleTypes`, but really it should be an explicit flag.
Added a new fixture and tests that are mostly taken from the markdoc tests
We can remove the bits saying markdoc isn't supported!
=> Add markdoc support to content layer

.changeset/rotten-months-report.md, packages/astro/src/actions/consts.ts, packages/astro/src/actions/runtime/middleware.ts, packages/astro/src/actions/runtime/virtual/shared.ts, packages/astro/src/actions/utils.ts, packages/astro/src/core/cookies/cookies.ts, packages/astro/src/core/render-context.ts, packages/astro/templates/actions.mjs, packages/astro/test/actions.test.js
This change adds automatic redirects when an action is called. This follows Laravel's POST/redirect/GET pattern to avoid a "confirm form resubmission" dialog and remove the `?_astroAction` param from the rendered result.
[See the changeset](https://github.com/withastro/astro/blob/d3ba81a8a6d990dd0411dd18cb60d3383fdec7c9/.changeset/rotten-months-report.md) for usage instructions.
- Persist action data in a cookie. **This cookie is not encrypted.** We are investigating a general encryption strategy for Astro as part of Astro Islands: #11535. If Astro adopts an encryption key as part of the runtime, we will revisit encryption of the action result cookie.
- Redirect to referrer on error, and the `url.pathname` on success.
- If an action cookie is present, populate `getActionResult` with the …
=> Actions: auto-redirect action response to avoid "confirm form resubmission" dialog

.changeset/good-birds-clap.md, packages/astro/src/vite-plugin-scanner/scan.ts
Closes https://github.com/withastro/astro/issues/11283
I tested it locally in a project of mine and it worked.
Existing CI should pass
N/A
=> fix: make semicolon optional when detecting `prerender` option

.changeset/nervous-garlics-beam.md, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/test/units/actions/form-data-to-object.test.js
Resolves #11659
This changes `formDataToObject` to allow default values to be set from zod.
Add tests to capture changes. I ran unit tests for this specific change and it passes. Not sure if the whole project tests are working correctly since I was getting some failures.
=> Set action input default values from zod if FormData key is not present

.changeset/small-ties-sort.md, packages/astro/src/runtime/server/render/util.ts, packages/astro/test/astro-attrs.test.js, packages/astro/test/fixtures/astro-attrs/src/pages/index.astro, packages/integrations/mdx/test/mdx-vite-env-vars.test.js
Cherry pick of https://github.com/withastro/astro/pull/11369 (which was reverted as it broke projects)
Has added tests
I've updated the changeset with better information of what's changed and how to migrate
=> Fix attribute rendering for boolean values (take 2)

.changeset/silver-horses-beam.md, packages/astro/src/actions/runtime/virtual/shared.ts
Closes #11675 
The stack trace of the error is saved in memory across submits. The stack trace is populated only in dev
I tested it against the reproduction of the issue, and I can successfully see the errors. No warnings regarding the size of the cookie
N/A
=> fix(actions): save error stack trace in memory

packages/astro/src/@types/astro.ts
Updates the content layer experimental flag docs, based on the changes made by @sarah11918
=> Update content layer flag docs

.changeset/odd-buttons-pay.md, packages/astro/components/Code.astro
Fixes withastro/roadmap#990
This fixes `Code.astro` so that passing the `meta` option to the shiki highlighter is supported.
The change is just a new prop and passing it to Shiki. Tests are implemented in Shiki.
The jsdoc is up-to-date.
docs pr: https://github.com/withastro/docs/pull/9054
=> fix: code component was missing support for meta string

packages/astro/src/@types/astro.ts
Updates an anchor link in `experimental.ContentLayer` docs to match the updated version of a heading.
No tests, passes Docs link checker now.
Only updates the docs. *BUT* since this change will be visible in people's editors, distributed via NPM, etc., we may want this released with the minor if possible, otherwise, in a patch.
=> [docs] updates link in Content Layer API

.changeset/new-boats-flash.md, packages/astro/src/core/build/plugins/plugin-ssr.ts, packages/astro/test/ssr-split-manifest.test.js
- Closes https://github.com/withastro/astro/issues/11700
- A different approach than https://github.com/withastro/astro/pull/11702, makes a virtual module that can be imported even if the adapter is external.
Preview release
N/A, bug fix
=> Prevent externalized adapters from breaking build

packages/astro/src/core/errors/errors-data.ts
Fixes two small typos: `occured` -> `occurred`
With the help of Oxford Dictionary.
#TeamDocs
=> Fix typos in 4.14 error references

.changeset/kind-bees-admire.md, packages/astro/e2e/fixtures/server-islands/astro.config.mjs, packages/astro/e2e/server-islands.test.js, packages/astro/src/runtime/server/render/server-islands.ts
- Fixes https://github.com/withastro/astro/issues/11703
- Test added
N/A, bug fix
=> Server Islands - Handle base + trailingSlash ignore

packages/astro/src/@types/astro.ts
This updates diff notation for docs with Expressive code. Not required for docs to merge (I've edited locally for releasing docs this morning. This reflects that change already in place.)
Does not require a patch release: docs looks the same, just changes the diff syntax.
just docs!
all docs!
=> [docs] updates experimental.contentLayer with Expressive Code

packages/astro/test/test-adapter.js
Chore PR, it doesn't change any functionality, but it removes some annoying errors we get in CI e.g.:
```
Error: 6 [ERROR] [config] The feature "assets" is not supported (used by test).
Error: 6 [ERROR] [config] The feature "hybridOutput" is not supported (used by test).
```
CI should pass
N/A
=> chore: updates the supported features of test adapter

.changeset/fresh-tigers-cheat.md, packages/astro/src/content/content-layer.ts, packages/astro/src/content/data-store.ts, packages/astro/src/content/loaders/types.ts, packages/astro/src/content/mutable-data-store.ts, packages/astro/src/content/utils.ts, packages/astro/src/core/dev/dev.ts, packages/astro/src/core/sync/index.ts
Separates all data store mutation methods into a subclass `MutableDataStore`, leaving the base class with just the get methods. This is so the immutable version can be used in the runtime without needing node builtins. It works because it loads the initial data as a virtual module. The mutable version includes all of the filesystem handling, but isn't needed at runtime.
Fixes #11720
Content layer tests still all pass.
=> fix: separate data store into mutable and immutable versions

.changeset/hungry-monkeys-talk.md, biome.json, package.json, packages/astro/src/assets/endpoint/node.ts, packages/astro/src/core/dev/dev.ts, packages/astro/src/core/logger/vite.ts, packages/astro/src/core/preview/static-preview-server.ts, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/vite-plugin-astro-server/response.ts, packages/astro/test/build-readonly-file.test.js, packages/db/src/core/integration/index.ts, packages/db/test/local-prod.test.js, packages/integrations/node/src/standalone.ts, packages/integrations/partytown/src/index.ts, packages/integrations/sitemap/src/write-sitemap.ts
- Updates fs import with prefix
- enable biome rule to catch such thing in the future
- depends on #11725
should pass
N/A, no changeset since internal only
=> refactor: enforce node prefix

.changeset/mighty-trees-teach.md, packages/integrations/mdx/src/vite-plugin-mdx.ts
fix https://github.com/withastro/astro/issues/11707
When we extract the frontmatter with `gray-matter` and it returns the `content`, it doesn't include the new lines from the stripped frontmatter, causing the MDX parser to incorrectly pinpoint the location of the error.
This PR manually adds the new lines to preserve the location.
Tested manually. The location is now correct: 
n/a. bug fix.
=> Fix MDX stack trace location with frontmatter

.changeset/spicy-houses-fry.md, packages/astro/src/core/sync/write-files.ts, packages/astro/test/astro-sync.test.js, packages/astro/test/units/dev/collections-renderentry.test.js
- Only use `normalizePath` for references
Should pass, reenables a test on windows
N/A
=> feat: simplifies sync paths

.changeset/weak-dancers-beam.md, packages/integrations/vercel/src/serverless/adapter.ts
- Marks `functionPerRoute` as deprecated in the Vercel adapter and warns against usage.
- N/A
- https://github.com/withastro/docs/pull/9108
=> Deprecate the functionPerRoute option

package.json
In vite-ecosystem-ci, Astro has been failing for a long time and seems to relate to the `test:types` fail: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/10414902461/job/28844581429#step:8:8664
I'm not sure why this happens as the errors imply that the built types were missing, but anyways we don't test Vite specific stuff in the types tests for now, so I figured to skip it.
If anyone has any ideas why the `test:types` test fails though, that'd also be great.
Will re-run vite-ecosystem-ci for Astro after merge
n/a
=> Update `test:vite-ci` script

.changeset/new-pillows-kick.md, packages/astro/src/vite-plugin-env/index.ts
cc @ascorbic 
The `export const prerender = import.meta.env....` warning should now only happen if the replacement actually happened. Previously even if there's no replacement, e.g. a false match of some docs/content, it will warn incorrectly.
tested manually.
n/a.
=> Reduce prerender dynamic value warning false positives

.changeset/smart-comics-doubt.md, packages/create-astro/src/actions/git.ts
I noticed that when initializing git, the initial git commit silently fails because the commit message wasn't wrapped in quotes.
tested manually with npm and pnpm
n/a, bug fix.
=> Fix create-astro initial git commit

.changeset/tiny-lamps-lick.md, packages/astro/src/env/vite-plugin-env.ts, packages/astro/test/astro-sync.test.js, packages/astro/test/fixtures/astro-env-content-collections/astro.config.mjs, packages/astro/test/fixtures/astro-env-content-collections/package.json, packages/astro/test/fixtures/astro-env-content-collections/src/content/config.ts, packages/astro/test/fixtures/astro-env-content-collections/tsconfig.json, pnpm-lock.yaml
- Closes #11754
- Keeps creating the virtual module in sync and only prevents validation error from being thrown
Adds a test
N/A
=> fix: astro:env sync error in content config

.changeset/weak-masks-do.md, packages/astro/src/core/config/vite-load.ts, packages/astro/src/core/sync/index.ts, packages/db/src/core/integration/index.ts
fix https://github.com/withastro/astro/issues/11003
The option was added at https://github.com/vitejs/vite/pull/16219 which is experimental, but it should be stable enough for us to use as its main usecase when the Vite team discussed was for Vitest and Astro specifically.
Disabling `server.ws` should disable Vite from creating a websocket server in the first place.
n/a. bug fix.
=> Disable server.ws vite config for loading config files

.changeset/odd-donuts-impress.md, packages/astro/src/integrations/hooks.ts
- Fixes the returned path from injectTypes
- Closes PLT-2427
N/A
=> fix: injectTypes path

.changeset/long-months-burn.md, packages/astro/src/integrations/features-validation.ts
The phrasing was misleading. This PR fixes it
CI should pass
=> fix: adapter features messaging

.changeset/fair-rats-fail.md, packages/astro/config.d.ts, packages/astro/src/assets/services/squoosh.ts
Astro 5.x removes the service completely see https://github.com/withastro/astro/pull/11770
Tested manually that the message works
Some of it is docs!
=> Deprecate the Squoosh image service

.changeset/chatty-cups-sleep.md, packages/astro/e2e/fixtures/actions-blog/src/pages/blog/[...slug].astro, packages/astro/src/actions/runtime/middleware.ts, packages/astro/src/core/render-context.ts, packages/astro/test/actions.test.js, packages/astro/test/fixtures/actions/src/pages/subscribe-prerendered.astro
This adds a check for whether a route is prerendered before running actions middleware.
- Resolves #11751
- Expose `isPrerendered` as untyped variable on `APIContext`. This is hidden from user-facing types for now to unblock actions, similar to our hidden `addContentEntryType()` when releasing content collections. Still, it sounds like integration authors will also benefit from this feature. It's worth discussing what a user-facing version would look like for the future.
- Assert  that cookies are ignored when rendering a prerendered route in dev.
N/A
=> [Actions] Fix middleware warning static mode

packages/astro/src/core/errors/errors-data.ts
I noticed this error was removed due to a false positive in a previous PR. It was used to prevent users from applying an Action without the `method="POST"` property on a form.
However, this is no longer detectable since we moved to using a query param for the action URL. When using `method="GET"`, this query param will get ignored, so we can no longer detect from the server and raise an exception.
N/A
N/A
=> chore: remove unused astro error

packages/astro/src/core/errors/errors-data.ts
Reverts https://github.com/withastro/astro/pull/11795 and marks the error as deprecated
N/A
N/A
=> chore: restore error and deprecate it

.changeset/four-rats-fail.md, packages/astro/src/content/loaders/file.ts
- Sets `filePath`  on collection entries in the `file()` loader when the loaded JSON is an object not array
- There was an inconsistency in the two code paths that meant that objects had been overlooked
- Amongst other things this fixes use of the `image()` schema utility which depends on `filePath`
- There’s probably an argument for refactoring the loader to first normalize the data, then run the other logic to avoid inconsistencies in the future, but I took the quick fix path for now.
Used as a patch in some work in the `astro.build` repo and working as expected
n/a — bug fix only
=> Fix file loader for JSON object files

.github/workflows/dispatch-event.yml, .github/workflows/preview-release.yml
This PR creates two new workflows:
- one to create a preview release when a PR is open, a PR is merged into `main`, and there's a workflow dispatch (manually triggered). It uses `pkg.pr.new`
- one to dispatch an event when a PR is merged to `main`. This event is dispatched to `withastro/starlight` and `withastro/adapters`. These two repositories can subscribe to this event and enable continuous testing whenever we merge a PR. 
The reason why I enabled the dispatch event only on `push` to `main`, is that it's not sustainable to trigger a test in other repositories at each commit.
This PR won't work until:
- ~~we enable `pkg.pr.new` as application for this repository (ideally for the entire org, I will sync with Matthew)~~
- ~~we create a …
=> ci: enable preview and repo dispatch

.github/workflows/preview-release.yml
I want to try to use `pull_request_review_comment` instead. It's not the same as `issue_comment`, but maybe `pkg.pr.new` will understand it and it will add a comment to the PR
Merge it and use another PR to trigger the event
N/A
=> ci: trigger using review comment instead

.github/workflows/preview-release.yml
The `pull_request_issue_comment` wasn't the event I needed. `issue_comment` is fine. 
[I worked before,](https://github.com/withastro/astro/actions/runs/10490295437) so I will merge this PR.
N/A
=> ci: use `issue_comment`

.changeset/poor-olives-battle.md, packages/astro/src/actions/runtime/virtual/shared.ts
- Resolves #11764
- Exposes `ActionAPIContext` utility type for integration authors.
N/A
N/A
=> Actions: expose ActionAPIContext

.changeset/pink-kids-taste.md, packages/astro/src/@types/astro.ts, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/test/actions.test.js, packages/astro/test/fixtures/actions/src/actions/index.ts, packages/astro/test/units/actions/form-data-to-object.test.js
Allow chaining utilities on `z.object()` when validating forms. This includes `.refine()`, `.transform()`, and `.passthrough()`.
- Resolves #11641
- Resolves #11693
- Unwrap nested effects to get basic Zod object
- Add check for the `passthrough` property. If present, pass unknown form data values as object keys
- Simplify Zod schema type for forms to `z.ZodType`. We originally tried to restrict this type, but it would grow quite complex to support infinitely nested `z.ZodEffect` objects. So, we relaxed the type and relaxed the handler. If we find a ZodObject in your validator, we massage `FormData`. Otherwise, we run your schema as-is.
- Add unit test for passthrough
- Add integration tests for refine and transform
N/A
=> Actions: Allow effect chaining on form input validators

.changeset/selfish-pianos-notice.md, packages/astro/e2e/actions-blog.test.js, packages/astro/e2e/fixtures/actions-blog/src/actions/index.ts, packages/astro/e2e/fixtures/actions-blog/src/components/Logout.tsx, packages/astro/e2e/fixtures/actions-blog/src/pages/blog/[...slug].astro, packages/astro/templates/actions.mjs
Fixes `undefined` result for actions with an empty return value.
- Correctly return `{ data: undefined, error: undefined }`
- Add e2e test with logout button
N/A
=> Actions: fix bad action result for actions with empty return value

.gitignore, .vscode/extensions.json, .vscode/settings.json
Right now, if you open Astro you don't get format-on-save code formatting without manually configuring it yourself. This PR makes it work with zero configuration!
- Add Biome VS Code extension to recommendations
- Set Biome as the default formatter for the appropriate file types (the same ones in the .prettierignore)
These changes have two good consequences:
- New contributors will get Biome's format-on-save in VS Code out-of-the-box with zero configuration. It'll just work.
- For people that work in some projects that use Prettier side-by-side with Astro (which uses Biome) this will allow automatic enabling of Biome as the default formatter in Astro, without interfering with the user's settings or other projects they work on with different configuration. When you open a project using …
=> Make Biome formatting work out-of-the-box in VS Code

.changeset/fuzzy-falcons-tan.md, packages/astro/src/core/create-vite.ts, packages/astro/src/vite-plugin-fileurl/index.ts
In the next Vite major with https://github.com/vitejs/vite/pull/17369, `file://` imports will be automatically externalized by Vite's resolver plugin, which causes problem with our `vite-plugin-fileurl` plugin because it's after vite's resolver plugin.
This PR marks it as `enforce: 'pre'` so that it runs before Vite's resolver plugin. In practice with this change now, it shouldn't break other plugins unless they also handle `file://` and with `enforce: 'pre'`, but I don't think that's a common case.
Existing should pass.
Added a changeset in case I'm wrong that this shouldn't break people.
=> Make vite-plugin-fileurl a pre plugin

.changeset/nasty-ladybugs-whisper.md, packages/astro/src/prefetch/index.ts
Prevents prefetching of same urls with different hashes.
This should not matter if cache works as expected but is annoying, especially in dev.
Before: ![image](https://github.com/user-attachments/assets/41491287-2b65-4893-a98d-81a59daf25bd)
Tested locally, not sure if this needs a test at all.
This should not need any documentation.
=> fix(astro): Prevent prefetching of same urls with different hashes

.changeset/perfect-socks-dress.md, packages/astro/src/core/errors/errors-data.ts
- Fix typo in `MissingImageDimension` error message
No tests are necessary for typos
No docs need to be updated for typos
=> Fix typo in `MissingImageDimension` error message

.changeset/eight-rice-tap.md, packages/integrations/partytown/src/index.ts
When using astro/partytown with astro:transitions, if partytown failed to load, it inserts "null" string into the page during transition. This mainly occurs in non-Secure Context where Service Worker that partytown needs can't be install. For example, if you're accessing it via an IP address on a LAN during development, it isn't served over HTTPS or on localhost so it's not Secure Context.
This PR prevent that by append a element only if found.
― The script going to append "null"
― The added "null" string node
Building @astrojs/partytown, linking it to my project, and confirming no "null" were inserted during page transitions.
This should be a minor bug fix affecting only special cases, so no docs will be required.
=> Prevent Partytown integration from inserting a 'null' string into the body

.changeset/thirty-bikes-peel.md, packages/astro/e2e/actions-blog.test.js, packages/astro/playwright.config.js, packages/astro/playwright.firefox.config.js, packages/astro/src/@types/astro.ts, packages/astro/src/actions/runtime/utils.ts, packages/astro/src/actions/runtime/virtual/shared.ts, packages/astro/src/core/constants.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/core/render-context.ts, packages/astro/test/actions.test.js
We give a pretty unfriendly DevalueError when an action returns non-serializable data. This is especially confusing when returning a Response or a redirect.
- Wrap the DevalueError with a well-formatted message
- Offer specific hints for Response and redirect objects
- Remove `redirect()` from the Action context object
N/A
N/A
=> Actions: give better guidance when a Response is returned by an Action

.changeset/eleven-papayas-rhyme.md, packages/astro/src/content/utils.ts, packages/astro/src/core/viteUtils.ts
The content utils use `normalizePath` imported from vite. This was causing problems because it was making vite a dependency of SSR chunks, causing bundling errors and bloated bundles. This was encountered in https://github.com/withastro/astro.build/pull/1225
This fixes the issue by re-implementing `normalizePath` (it's quite simple), so it can be used elsewhere.
Tested with https://github.com/withastro/astro.build/pull/1225
Bugfix
=> fix: ensure vite is not imported by runtime utils

.changeset/nasty-crabs-worry.md, packages/astro/src/core/middleware/index.ts, packages/astro/src/core/render-context.ts, packages/astro/src/types/public/context.ts, packages/astro/test/astro-global.test.js, packages/astro/test/fixtures/astro-global/src/components/Route.astro, packages/astro/test/fixtures/astro-global/src/middleware.js, packages/astro/test/fixtures/astro-global/src/pages/index.astro, packages/astro/test/fixtures/astro-global/src/pages/omit-markdown-extensions.astro, packages/astro/test/fixtures/astro-global/src/pages/posts/[page].astro
**For Astro 5.0**
Closes PLT-2339
It adds a new field to the `Astro` global called `routePattern`.
`route` is `RouteData.component` without `srcDir` and `pages`:
- `src/pages/index.astro` -> `index`
- `src/pages/blog/[post].astro` -> `blog/[post]`
I added new tests
https://github.com/withastro/docs/pull/9180
=> feat(next): add `Astro.routePattern`

.changeset/good-adults-punch.md, packages/integrations/markdoc/src/content-entry-type.ts, packages/integrations/markdoc/test/fixtures/render-with-extends-components/astro.config.mjs, packages/integrations/markdoc/test/fixtures/render-with-extends-components/markdoc.config.ts, packages/integrations/markdoc/test/fixtures/render-with-extends-components/package.json, packages/integrations/markdoc/test/fixtures/render-with-extends-components/src/components/Code.astro, packages/integrations/markdoc/test/fixtures/render-with-extends-components/src/components/CustomMarquee.astro, packages/integrations/markdoc/test/fixtures/render-with-extends-components/src/content/blog/with-components.mdoc, packages/integrations/markdoc/test/fixtures/render-with-extends-components/src/pages/index.astro, packages/integrations/markdoc/test/render-extends-components.test.js, pnpm-lock.yaml
This PR fixes an issue where rendering Astro components as Markdoc tags and nodes when configured using the `extends` property would lead to an error (`Unable to render [object Object]. No valid renderer was found for this file extension.`).
This would prevent for example Starlight users to have a configuration like this:
```ts
export default defineMarkdocConfig({
extends: [starlightMarkdoc()]
tags: {
custom: { render: component('./src/components/Custom.astro') },
},
});
```
The issue was that when creating the component configs for used tags and nodes, the user-defined Markdoc config was used instead of the computed one that also contains the merged configurations from the `extends` property.
I mostly duplicated the existing `test/fixtures/render-with-components` fixture and its …
=> Fix component defined in `extends` not rendered as Markdoc tags/nodes

.vscode/settings.json, biome.json, packages/astro/src/actions/utils.ts, packages/astro/src/core/build/plugins/plugin-content.ts, packages/astro/src/core/build/plugins/plugin-pages.ts, packages/astro/src/runtime/client/dev-toolbar/toolbar.ts, packages/astro/src/vite-plugin-astro-server/pipeline.ts, packages/astro/src/vite-plugin-scanner/index.ts, packages/db/src/core/cli/commands/link/index.ts, packages/db/src/core/cli/commands/push/index.ts, packages/db/src/core/cli/migration-queries.ts, packages/db/src/core/queries.ts, packages/db/src/runtime/index.ts, packages/integrations/markdoc/src/runtime.ts
This rule enables `useImportType` from Biome: https://biomejs.dev/linter/rules/use-import-type/
We've had issues where the syntax `import { type Something }` broke our build and downstream adapters.
This rule should prevent that.
Also, I updated the `settings.json` to apply safe fixes on save. 
=> chore: enable `useImportType` rule

.changeset/tiny-suns-sit.md, packages/integrations/mdx/src/rehype-apply-frontmatter-export.ts
fixes https://github.com/withastro/astro/issues/11040
we can revert the workaround made in https://github.com/withastro/astro/pull/4428 as Vite is able to handle circular imports invalidation better now. I tested manually and can confirm that when one `.mdx` file (that's part of a `Astro.glob` of the layout file) is edited, only that `.mdx` file gets re-transformed. The rest `.mdx` file will reuse the transform result from the cache. (Checked with `DEBUG="vite:cache,vite:plugin-transform" pnpm dev`)
Existing tests should pass. Also explained some manual testing method above.
n/a. bug fix.
=> Fix MDX layout style ordering

.changeset/afraid-apricots-develop.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/sync/index.ts, packages/astro/src/integrations/hooks.ts, packages/db/src/core/integration/file-url.ts, packages/db/src/core/integration/index.ts
Closes #10876 
I added a `"sync"` variant to the command. This will be useful to the extension too.
This is flagged as minor, because it adds new information. 
Existing CI should pass. Should I create a test? 🤔 
https://github.com/withastro/docs/pull/9110
=> feat: add `sync` variant

packages/astro/src/core/render-context.ts, packages/astro/test/astro-global.test.js
Turns out that we already had `Astro.routePattern` value. This PR uses it
Updated existing tests
=> refactor: `Astro.routePattern` is `RouteData.route`

packages/astro/test/fixtures/actions/astro.config.mjs, pnpm-lock.yaml
Check origin is now on by default, but the actions test needs to check against a particular test code when we hit an external domain
CI should pass
=> test: fix regression

.changeset/neat-swans-hear.md, packages/astro/src/cli/add/index.ts
Use default import instead of named imports when injecting adapters or integrations
Tested locally in the screenshots above
bug fix
=> Use default import in astro add

.changeset/little-zebras-march.md, packages/astro/src/@types/astro.ts
The example provided for `i18n.routing.fallbackType` was using the wrong filename (`dist/en/index.html` should be `dist/en/about.html` since the page is `src/pages/en/about.astro`).
No need.
* No additional documentation needed, this is a small fix in `i18n.routing.fallbackType` documentation
* I added a changeset since this fixes the documentation content
=> docs(i18n): fix typo in `fallbackType` JSDoc comment

.changeset/many-turtles-tie.md, packages/astro/src/core/logger/core.ts, packages/astro/src/core/sync/index.ts
- Actions throws in `astro:config:done` if the output is static. This change makes it so that the error surfaces to the user like it should.
Did so manually looks like:
```
ActionsWithoutServerOutputError: Actions enabled without setting a server build output. A server is required to create callable backend functions. To deploy routes to a server, add a server adapter to your astro config.
```
Bug fix
=> Provide an error message when Actions throws in setup

.changeset/mean-donkeys-switch.md, packages/astro/src/content/data-store.ts, packages/astro/src/content/loaders/types.ts, packages/astro/src/content/mutable-data-store.ts
The `LoaderContext` object that is passed to custom loaders is exported as a public type, but previously the individual properties used types that weren't public. This PR exports those types. It also changes the confusingly-named `ScopedDataStore` to `DataStore` to reflect the fact that it's the only public data store type.
=> Export `LoaderContext` types

.changeset/purple-ears-sneeze.md, packages/astro/src/assets/build/generate.ts
Moves the `loadImage` method call to after the image cache check, improving performance massively and reducing memory consumption for remote images.
| Website | Version | No cache | Cache |
|---------|---------|-----------|--------|
| brpartners.com.br | Before | <img width="895" alt="Before, no cache, 129.47s" src="https://github.com/user-attachments/assets/bd549f4c-9ff1-467e-808e-97f6b464c206"> | <img width="832" alt="Before, cache, 44.23s" src="https://github.com/user-attachments/assets/bfe3f9b9-00fc-415f-8d34-fc8ba571db01"> |
| brpartners.com.br | After | <img width="905" alt="After, no cache, 126.67s" src="https://github.com/user-attachments/assets/d161cec9-fc66-44aa-b8d8-fd83bcb94a12"> | <img width="835" alt="After, cache, 0,56s" …
=> perf(astro/assets): avoid downloading original image when using cache

.changeset/green-bulldogs-shout.md, packages/astro/src/cli/add/index.ts
Bring back the previous logic for selecting the adapter name, it was lost in the port to magicast.
Fixes https://github.com/withastro/astro/issues/11934
N/A
=> fix(add): Use proper export names when adding adapters

.changeset/long-lemons-add.md, packages/astro/test/fixtures/preact-component/src/components/ComponentWithNullProp.jsx, packages/astro/test/fixtures/preact-component/src/pages/signals.astro, packages/astro/test/preact-component.test.js, packages/integrations/preact/src/signals.ts
Following up on @ph1p's changes, we discovered our pages were suddenly failing. Example error message: 
```
TypeError [Error]: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at serializeSignals (file:///Users/lukasbachlechner/development/astro/packages/astro/test/fixtures/preact-component/dist/renderers.mjs:49:44)
at Object.renderToStaticMarkup (file:///Users/lukasbachlechner/development/astro/packages/astro/test/fixtures/preact-component/dist/renderers.mjs:146:3)
at renderFrameworkComponent (file:///Users/lukasbachlechner/development/astro/packages/astro/test/fixtures/preact-component/dist/chunks/astro/server_B-ybt-25.mjs:1263:53)
at async renderComponent (file:///Users/lukasbachlechner/development/astro/packages/astro/test/fixtures/preact-component/dist/chunks/ …
```
=> fix: explicitly check for null props in `serializeSignals`

.changeset/nasty-dogs-sort.md, packages/create-astro/src/actions/typescript.ts
- Updates the default Astro config with `// @ts-check` if the Typescript preset is `strict` or `strictest`
I don't think anything is needed
=> feat(create-astro): ts-check comment

.changeset/mighty-stingrays-press.md, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/test/actions.test.js, packages/astro/test/fixtures/actions/src/actions/index.ts
Adds support for Zod discriminated unions. Implemented from [this roadmap suggestion](https://github.com/withastro/roadmap/issues/898#issuecomment-2178131665) by @arihantverma. Thanks for the suggestion!
- Add check for discriminated union schemas, and unwrap the correct object depending on the union key.
- Add test for discriminated unions
Changeset for now, will update API reference
=> Actions: add discriminated union support

.changeset/sharp-worms-sniff.md, packages/astro/src/core/errors/errors-data.ts
Generalizes two error messages that assume your collections are stored in `src/content/`
No tests, docs
Only error message docs on `next`.
=> [error docs] Update error messages that reference src/content/

packages/astro/src/vite-plugin-astro-server/css.ts, packages/astro/test/0-css.test.js, packages/astro/test/fixtures/0-css/src/components/VueModules.vue
Fixed how the inline query is injected for CSS inlining.
The previous code injected the inline query at the end and injected unnecessary `=` after queries without values. This was incompatible with plugin-vue resulting in this workaround.
https://github.com/withastro/astro/blob/5d7bc70fc369724e2b6a4dad5a34cbe2a29c98f1/packages/astro/src/vite-plugin-astro-server/css.ts#L45-L49
The new code injects the inline query at the beginning and doesn't inject `=`.
This PR also fixes the tests failing with Vite 6 (envrionment API).
https://discord.com/channels/804011606160703521/1278362001437102163/1280816490655907863
I didn't add a changeset because this doesn't change user-facing behavior.
refs #9531
Updated a test
N/A since this is a bug fix.
=> fix(css): fix inline query injection for CSS inlining

.changeset/afraid-apricots-buy.md, .changeset/giant-rocks-thank.md, .changeset/poor-dots-add.md
It's all changesets for https://github.com/withastro/astro/pull/11824
N/A
N/A
=> feat: changesets for the hybrid removal

packages/astro/src/core/errors/errors-data.ts
Some legacy collections error messages were pointing to links that will no longer exist in beta 5 docs.
This updates these messages to:
- describe them as "legacy collections"
- use a link that will work, from which they can find their way to more specific docs
I didn't want to just deprecate these on next as we are still allowing both kinds of collections to work, so these errors are needed for those collections. But, since the eventual location of these docs depends on a lot of things, I've just made one simplified link for all those errors right now.
No tests, just error docs!
All error docs!
=> [docs] update legacy collections error messages

.changeset/nine-chairs-decide.md, packages/astro/src/@types/astro.ts
=> Fixes typo.

packages/astro/src/core/errors/errors-data.ts
Follow up to #11961 since the location of the docs for upgrading to new collections have moved. This updates only the links in the error messages.
No tests, just docs.
Just updates links to upgrade docs
=> [docs] update legacy collections error messages (again)

.changeset/eighty-bags-cross.md, packages/astro/templates/content/types.d.ts
Exports `RenderResult` type, which is the return type of `render()`
=> Export the RenderResult type

.changeset/lovely-dolphins-draw.md, packages/integrations/mdx/src/rehype-optimize-static.ts, packages/integrations/mdx/test/fixtures/mdx-optimize/astro.config.mjs, packages/integrations/mdx/test/mdx-optimize.test.js, pnpm-lock.yaml
fix https://github.com/withastro/astro/issues/11971
The MDX optimizer didn't handle `{ type: 'root', children: [] }` kind of hast node when combining the MDX into an HTML string, which resulted in incorrect output. The fix here is to treat root hast nodes as non-optimizable, like MDX nodes.
Added tests
n/a. bug fix.
=> Handle MDX optimize for root hast node

.changeset/quiet-lemons-collect.md, packages/astro/package.json, packages/astro/src/core/routing/manifest/generator.ts, pnpm-lock.yaml
- Remove dependency path-to-regexp
- Replace route placeholders directly in generate function
All existing test still run and code is already covered.
No change to docs necessary as this is only an internal implementation change.
=> Remove dependency on path-to-regexp

.changeset/polite-roses-fail.md, packages/underscore-redirects/src/astro.ts
=> feat(next): underscore redirects

.changeset/happy-ways-sin.md, packages/astro/package.json, packages/astro/src/core/routing/manifest/generator.ts, packages/astro/test/fixtures/get-static-paths-pages/src/pages/archive/[...slug]/[...page].astro, packages/astro/test/get-static-paths-pages.test.js, pnpm-lock.yaml
- Closes https://github.com/withastro/astro/issues/11990
- Reverts https://github.com/withastro/astro/commit/633eeaa9d8a8a35bba638fde06fd8f52cc1c2ce3
- Test added from #11190 
N/A, bug fix
=> Fix getStaticPaths regression

.changeset/healthy-donuts-yell.md, packages/astro/src/@types/astro.ts
Updates Content Layer RFC links in `@types/astro.ts`. Previous links led to 404 error...
N/A
* This is a doc fix already approved in `docs` repo (see https://github.com/withastro/docs/pull/9410) but the update should occur here!
* I don't think we need a changeset for this...
=> docs: fix Content Layer RFC Link

.changeset/fresh-pandas-drive.md, packages/astro/src/types/public/config.ts
The default value for `security.checkOrigin` has [changed in v5](https://5-0-0-beta.docs.astro.build/en/guides/upgrade-to/v5/#csrf-protection-is-now-set-by-default), so I updated the JSDoc comment to:
* fix the type of `security` (this is not a boolean if I make no mistake)
* define its default value
* add an example to show how to disable this behavior
N/A, it's doc.
This is a doc PR. I added a changeset, not sure if it was necessary since it is for v5 (first time I'm publishing to the next branch).
But a review from Team docs could be helpful!
=> docs: update `security.checkOrigin` JSDoc comment

.changeset/five-walls-build.md, packages/astro/e2e/fixtures/view-transitions/src/components/VueCounter.vue, packages/astro/e2e/fixtures/view-transitions/src/pages/island-vue-one.astro, packages/astro/e2e/fixtures/view-transitions/src/pages/island-vue-two.astro, packages/astro/e2e/view-transitions.test.js, packages/integrations/vue/client.js
This change keeps track of all initialized vue islands in order to update the existing instance rather than creating a new app, which resets the state.
I'm by no means a Vue expert and there might be more elegant ways to achieve this. I tried to follow the approach of the React implementation (using a `WeakMap`), however, patching the props is a bit more difficult than in in React. I'm happy to improve it in case anybody has a better idea.
This fixes #11854,
E2E test was added.
As this is only a fix, I don't think documentation is needed. However, it could be pointed out that state persistence is currently broken for all frameworks except for React and Vue if I'm not mistaken.
=> Fix vue resetting state when using view transition persistence

.changeset/grumpy-bobcats-rush.md, packages/astro/e2e/fixtures/view-transitions/astro.config.mjs, packages/astro/e2e/fixtures/view-transitions/package.json, packages/astro/e2e/fixtures/view-transitions/src/components/solid/Counter.jsx, packages/astro/e2e/fixtures/view-transitions/src/pages/island-solid-one.astro, packages/astro/e2e/fixtures/view-transitions/src/pages/island-solid-two.astro, packages/astro/e2e/view-transitions.test.js, packages/integrations/solid/src/client.ts, pnpm-lock.yaml
This changes addresses the issue that the state if SolidJS components would not be retained when using `transition:persist`.
It introduces a reactive store to update the props passed to the root component after initialization (similar approach as the React integration is using).
Related to #11854
E2E test was added.
Only a fix, so no docs update should be needed.
=> Fix SolidJS view transition state persistence

.changeset/warm-birds-cheer.md, packages/astro/e2e/fixtures/view-transitions/src/components/SvelteCounter.svelte, packages/astro/e2e/fixtures/view-transitions/src/pages/island-svelte-one.astro, packages/astro/e2e/fixtures/view-transitions/src/pages/island-svelte-two.astro, packages/astro/e2e/view-transitions.test.js, packages/integrations/svelte/client-v5.js, packages/integrations/svelte/client.js
This change fixes view transition state persistence for Svelte components. It keeps track of mounted components and updates props instead of remounting the component.
Related to #11854.
E2E test was added
This behavior is already documented but was not working until now.
=> Fix Svelte view transition state persistence

.changeset/rotten-phones-scream.md, packages/astro/e2e/actions-blog.test.js, packages/astro/e2e/fixtures/actions-blog/src/actions/index.ts, packages/astro/e2e/fixtures/actions-blog/src/pages/lots-of-fields.astro, packages/astro/src/actions/runtime/middleware.ts, packages/astro/src/actions/runtime/virtual/shared.ts
- base64 encode the action result that is saved within the cookie in the redirect flow.
- Additionally this trims down the input errors to only the used fields, otherwise it's very easy for it to be too large.
- Fixes https://github.com/withastro/astro/issues/11973
- Test added with a large form, 10 fields, all having validation errors. 
N/A, bug fix
=> Encode action result in cookie

.changeset/plenty-pandas-repeat.md, packages/integrations/tailwind/package.json
- Updates the `peerDependency` range so Tailwind can be installed in a 5.0 beta project.
- not really
N/A, bug fix
=> Make @astrojs/tailwind compat with Astro 5

.changeset/heavy-pugs-jam.md, .changeset/moody-cougars-taste.md, packages/astro/src/vite-plugin-markdown/index.ts, packages/integrations/mdx/src/vite-plugin-mdx.ts
close https://github.com/withastro/astro/issues/12015
I don't particular understand how the issue happen in the first place, but after reading the code, it looks like there's a perf opportunity to lazily initialize the processors only if there's `.md` or `.mdx` files, so I did that instead and it should also indirectly fix the issue.
n/a. refactor.
=> Lazily initialize the md and mdx processor

.changeset/light-pianos-sip.md, packages/astro/src/core/render/params-and-props.ts, packages/astro/test/dynamic-endpoint-collision.test.js, packages/astro/test/fixtures/dynamic-endpoint-collision/src/pages/api/safe/[...slug].ts
fix https://github.com/withastro/astro/issues/11957
The `validatePrerenderEndpointCollision` function should only be called after we know the path matches one of in `getStaticPaths`. Otherwise we're checking for a path that may not actually exist.
added a test
n/a. bug fix.
=> Check route collision after getStaticPaths

biome.json, eslint.config.js, package.json, pnpm-lock.yaml
This PR removes `eslint-plugin-no-only-tests`, which is not needed because Biome already has a rule for that, which is enabled in this PR.
I locally checked that using `.only` fails the build
N/A
=> chore: remove `eslint-plugin-no-only-tests`

.changeset/clever-vans-flash.md, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/i18n-routing-manual.test.js
Closes https://github.com/withastro/astro/issues/12033
The middleware **should** be called for prerendered `404.astro`, but it shouldn't be called for our default 404, because it's not a user component.
Updated an existing test
N/A
=> fix(routing): call middleware when rendering `404.astro`

.changeset/fast-queens-try.md, packages/astro/src/container/index.ts, packages/astro/src/container/polyfill.ts
Applies polyfill to the container API
CI should pass
N/A
=> fix(container): apply polyfill

.changeset/heavy-peas-sneeze.md
Svelte and Vue peer deps are only looking for Astro 4, by releasing a beta of them, you can now use the beta of them with Astro 5
Fix https://github.com/withastro/astro/issues/12059
N/A
N/A
=> Release a beta for Svelte and Vue

.changeset/smooth-panthers-heal.md, packages/astro/src/cli/add/index.ts
What the title says
N/A. Just a line removed.
It's not a breaking change, since this well, you don't depend on this output, but the docs changes related to SSG / SSR will somewhat touch on this.
=> feat: makes it so astro add does not set output server by default

.changeset/tame-pumpkins-swim.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts
The `checkOrigin` manifest flag was always `true`, because it didn't check the `buildOutput` flag.
Fixes https://github.com/withastro/astro/issues/12069
CI Should pass. Tested manually using a basic project.
N/A
=> fix: check origin in static build

.changeset/poor-seals-clap.md, packages/astro/package.json, packages/astro/src/cli/add/index.ts, packages/astro/src/cli/install-package.ts, packages/db/package.json, packages/db/src/core/cli/commands/link/index.ts, packages/db/src/core/cli/commands/login/index.ts, packages/studio/package.json, packages/studio/src/core/tokens.ts, pnpm-lock.yaml
`yocto-spinner` is a smaller alternative from the same author of ora.
https://github.com/sindresorhus/yocto-spinner
tested the spinner manually
n/a. refactor.
=> Replace ora with yocto-spinner

.changeset/fifty-squids-build.md, packages/astro/components/viewtransitions.css
Adds `mix-blend-mode: plus-lighter` to Astro's fade transitions 
Fixes #12045
manually tested
n.a. / bug fix
=> View Transitions: Fixes Astro's fade animation to prevent flicker during morph transitions

.changeset/sweet-timers-smash.md, packages/astro/package.json, packages/astro/src/content/utils.ts, packages/astro/src/vite-plugin-markdown/content-entry-type.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/integrations/markdoc/package.json, packages/integrations/markdoc/src/content-entry-type.ts, packages/integrations/markdoc/test/content-collections.test.js, packages/integrations/mdx/package.json, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/src/utils.ts, packages/integrations/mdx/src/vite-plugin-mdx.ts, packages/markdown/remark/package.json, packages/markdown/remark/src/frontmatter.ts, packages/markdown/remark/src/index.ts, pnpm-lock.yaml
Parse frontmatter ourselves instead of gray-matter. This shouldn't cause any breaking change as we're only relying on parsing yaml frontmatter instead of the other features offered gray-matter.
Current tests should pass
n/a. refactor.
=> Parse frontmatter ourselves

.changeset/afraid-candles-hear.md, packages/astro/src/content/types-generator.ts
Entries can (and often do) have a filePath property. It'd be great if it knew for sure that it existed for loaders that have it, but aalas, that's not how the world works.
N/A
=> Adds missing filePath property on content layer entries

.changeset/real-nails-tan.md, packages/astro/src/cli/add/index.ts
- Fix installing non-stable versions of packages with `astro add`. For example, `astro add node@beta`
Manually. No tests exist yet for `astro add`.
No change required
=> Fix non-stable versions for astro add

.changeset/bright-swans-shout.md, packages/astro/src/content/runtime.ts
When using references in schemas that refer to content layer there was sometimes a race condition causing them to incorrectly report as missing. We already checked for empty collections which may not have loaded yet, but were missing this case where even the stubbed collection had not been created. The fix is just to remove this particular error. It's ok because we still have a check later when querying, which will still give a helpful error message if the collection is missing. I did spend some time trying to see if I can get the collection list early enough to check, but there are too many race conditions and I think this approach is ok.
Fixes #12087
=> fix: defer check for schema references to content layer collections

.changeset/rich-apes-divide.md, packages/astro/src/runtime/server/render/server-islands.ts
fixes #11995
cc: @matthewp — we talked about this on Twitter.
Swaps the generic HTML comment placeholders with IE conditional comments. These placeholders have existed for a long time, and are much less likely to be removed by HTML minifiers, because they have traditionally been used to change the behavior of a site.
A similar fix was implemented in [Livewire](https://github.com/livewire/livewire/commit/b666304652006f3491987c92d53724bc14035d6a) to work around Cloudflare HTML minification removing the HTML comment placeholders Livewire was inserting for a similar purpose.
No tests changed, since it's just changing the content of an HTML comment. I haven't been able to set up the original commenter's complete environment for a complete fix verification, but I did look at the source code for …
=> Use IE conditional comment placeholders for server island start markers

.changeset/moody-doors-wink.md, packages/astro/src/core/app/node.ts, packages/astro/src/vite-plugin-astro-server/response.ts, packages/astro/test/fixtures/ssr-api-route/src/pages/food.json.js, packages/astro/test/ssr-api-route.test.js
The `Response` spec allows a custom `statusText` to be defined, which should be sent in the HTTP response. Currently we're not passing this in our response. This PR fixes this in dev and NodeApp. Other adapters will use their native Response handling.
Fixes #9401
=> fix: pass custom statusText in Response

.changeset/poor-doors-listen.md, packages/astro/src/runtime/server/endpoint.ts, packages/astro/test/fixtures/ssr-api-route/src/pages/fail.js, packages/astro/test/ssr-api-route.test.js
There are some scenarios where an endpoint may return an immutable response object. The main one is if they're directly returning the response to a `fetch`. Currently there are some cases where we try to set a header on a response object, which would fail in this case. This fixes that by catching the error and instead returning a new Response with the same init and body.
Fixes #11921
=> fix: handle immutable response object

.changeset/dull-worms-own.md, packages/astro/src/assets/utils/transformToPath.ts, packages/astro/test/core-image.test.js, packages/astro/test/fixtures/core-image-data-url/package.json, packages/astro/test/fixtures/core-image-data-url/src/pages/index.astro, pnpm-lock.yaml
currently data: urls are treated like normal urls and `basename` is used to get the filename to generate the cache and output files. however this can result in a very long filename depending on where the slashes (which are part of the base64 data) are, possibly resulting in errors.
to prevent this, can instead use a shorthash of the data url as the filename for data url images processed. so the final output image filename will be `[hash of data url]_[hash].[ext]` instead of `[arbitrary basename of data url]_[hash].[ext]`
added text fixture which processes data url images which would cause ENAMETOOLONG
should have no effect on user behaviour
=> use shorthash for data url image to prevent ENAMETOOLONG

.changeset/wise-pumas-fry.md, packages/astro/src/content/runtime.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/pages/missing.astro
Currently if an undefined entry is passed to `render()` it gives the unhelpful error about attempting to access `deferredRender` on `undefined`. This PR adds an explicit null check which throws a new AstroError if the entry is undefined.
Added a new test case and fixture
Adds a new error
=> fix: throw a useful error if rendering undefined entry

.changeset/strange-cats-notice.md, packages/astro-rss/README.md, packages/astro/CHANGELOG.md, packages/astro/client.d.ts, packages/astro/src/@types/astro.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/vite-plugin-env/README.md, packages/integrations/react/CHANGELOG.md, packages/integrations/svelte/CHANGELOG.md, packages/integrations/vue/CHANGELOG.md
Vite has a new domain so we are updating all documentation files to use this new domain (`vitejs.dev` > `vite.dev`). So I updated:
* `error-data.ts` to update auto-generated errors files
* `@types/astro.ts` to update the Configuration reference page
I haven't touch other files. But if needed I can update the Vite links in other files as well (mostly CHANGELOGs, a README file and `client.d.ts`).
N/A (well, I checked that the links are still working)
This helps closing an issue opened by Sarah in `withastro/docs`: https://github.com/withastro/docs/issues/9548
I don't think we need a changeset for that (unless they are used to determine when to update the doc?)
=> docs: update Vite links to use their new domain

.github/workflows/dispatch-event.yml
I was getting fails for this workflow in my forked repo. I think it shouldn't need to run in forks so I disabled it for forks.
n/a
n/a
=> Only run dispatch-event.yml in source repo

.changeset/ninety-monkeys-complain.md, packages/astro/src/content/content-layer.ts
New Astro versions can introduce changes that are incompatible with data stores created by other versions. This PR ensures that if the version has changed, the store will be cleared.
Tested manually. I'm not sure how to test this automatically because of the way the version is injected into builds
=> fix: clear content layer cache if astro version changes

.changeset/dull-moles-talk.md, packages/astro/src/core/dev/restart.ts
We currently trick Vite into restarting our dev server when it tries to restart its own server by overwriting the vite server's `restart()` method. Our method restarts our own dev server, which includes restarting Vite. The problem is that the calling function expects to still be able to read from the original Vite server instance, but we've created a new one. This causes it to emit a confusing error about missing server URLs. This PR copies across the URLs to the old server, just so that the calling function can read them. 
Fixes #12107
=> fix: copy server URLs to Vite dev server

.changeset/eighty-ligers-punch.md, packages/integrations/svelte/client-v5.js
Small code enhancement, which is easy to understand.
- Fix 'component is not defined' console error when unmounting svelte 5 component.
Console error: ![Screenshot 2024-10-01 110532](https://github.com/user-attachments/assets/0e198f57-2f66-4787-a5ed-c79f41a63678)
Defensive code added and tested locally.
=> Fix-component-undefined-svelte-v5

.changeset/eighty-ligers-punch.md, packages/integrations/svelte/client-v5.js
* - fix: 'component is not defined' error when unmount svelte 5 component
* added changeset
* Moving unmount listener to where the component is defined.
* Update .changeset/eighty-ligers-punch.md
Cherry-picked from dcc1e895abbad1311719803363c933541c0ad984
=> Fix-component-undefined-svelte-v5 (#12102)

.changeset/twenty-spoons-sneeze.md, packages/astro/package.json, pnpm-lock.yaml
This just updates `cookie` to get rid of warnings about [CVE 2024-47764](https://nvd.nist.gov/vuln/detail/CVE-2024-47764).
No change required.
No change required.
=> [CVE 2024-47764] Update package 'cookie'

.changeset/strong-pugs-stare.md, packages/astro/src/core/app/node.ts, packages/astro/src/vite-plugin-astro-server/response.ts
#12105 added support for setting the response statusMessage. However this is not supported by HTTP/2, so a warning was being logged. This PR first checks that the response is not HTTP/2 before setting it.
Fixes #12134
Tested manually with `astro-dev-http2` fixture
=> fix: don't set statusMessage in HTTP/2

.changeset/red-bugs-pump.md, packages/create-astro/package.json, packages/create-astro/src/actions/template.ts, packages/create-astro/src/actions/verify.ts, pnpm-lock.yaml
> NOTE: I'm totally fine if we decide to not land the PR at all. It uses a custom fork which may not be desirable for some, we could wait to upstream the features if needed. But below I'll explain the benefits we get in this PR.
Replaces `giget` with my partial fork `@bluwy/giget-core`. Main differences for us:
- Smaller dependency size ([before](https://npmgraph.js.org/?q=giget) vs [after](https://npmgraph.js.org/?q=%40bluwy%2Fgiget-core))
- Adds builtin APIs and behaviour change that allows us to remove some code
These changes should help users with limited bandwidth to install `create-astro` to download templates. From packagephobia, giget requires [1.9MB](https://packagephobia.com/result?p=giget) while the fork requires [48.3kB](https://packagephobia.com/result?p=%40bluwy%2Fgiget-core) …
=> Simplify giget dependency

.changeset/ninety-dolls-reply.md, .changeset/plenty-kings-swim.md, packages/astro-rss/README.md, packages/astro-rss/src/schema.ts, packages/astro-rss/test/rss.test.js, packages/astro-rss/test/test-utils.js
This PR fixes an issue reported in [Doc repository](https://github.com/withastro/docs/issues/9575): `pubDate` is optional when generating RSS items since #9610 but if not provided an error is thrown (`Invalid input (items.0.pubDate)`).
I have not created a ticket, but I have [a minimal reproduction](https://stackblitz.com/edit/astro-rss-pubdate-bug?file=src%2Fpages%2Ffeed.xml.ts&on=stackblitz) (just delete one of the pubDate).
* I updated the way we declare `pubDate` in `rssSchema` to prevent the validation to fail when `pubDate` is not included in the item.
* I updated the README to replace `required` with `optional` for the items updated in #9610
* I added a test and an item without date: it was failing before, now it passes.
* I tested manually with `pnpm link` with the minimal …
=> fix(@astrojs/rss): prevent an error when `pubDate` is missing

.changeset/stupid-seas-roll.md, packages/astro/src/actions/runtime/middleware.ts, packages/astro/src/core/middleware/index.ts, packages/astro/src/core/render-context.ts, packages/astro/src/i18n/utils.ts, packages/astro/test/fixtures/i18n-routing/astro.config.mjs, packages/astro/test/i18n-routing.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/12149
There was a already a test with a similar use case, I changed the default locale to match the one of the use case.
N/A
=> fix(routing): default locale when there's a list

.changeset/angry-ducks-kneel.md, packages/integrations/tailwind/package.json
- Adds keywords to the Tailwind integration `package.json` to improve categorization in the Astro integrations catalog
- Currently Tailwind shows up as “uncategorized” but adding the `css` keyword in this PR will mean it gets put in the “CSS + UI” category ([docs](https://docs.astro.build/en/reference/publish-to-npm/#categories))
n/a
n/a
=> Add `css` keyword to Tailwind integration

.github/workflows/ci.yml, package.json
This PR changes how we report linting errors in CI. We use the `biome ci` command, and we use the `--reporter=github` so errors are nicely reported in the workflow summary.
CI should pass
N/A
=> ci: use `ci` command

.changeset/dirty-socks-sip.md, packages/astro/src/core/config/schema.ts, packages/markdown/remark/src/index.ts, packages/markdown/remark/src/shiki.ts, packages/markdown/remark/src/types.ts, packages/markdown/remark/test/shiki.test.js
Closes https://github.com/withastro/roadmap/discussions/954
This PR adds support for [`langAlias`](https://shiki.style/guide/load-lang#custom-language-aliases)
I added new tests
https://github.com/withastro/docs/pull/9453
=> feat(markdown): add support for `shiki` option `langAlias`

.changeset/mean-bags-shave.md, packages/astro/src/core/dev/restart.ts
- Adds the .mts file extension to the configRE regex so it restarts when the `astro.config.mts` file changes
- Fixes #12159
N/A
=> Fix mts reloads

packages/astro/src/@types/astro.ts
This PR adds additional info about content intellisense.
The issue is discussed in the doc repo https://github.com/withastro/docs/issues/9122
No tests are needed since PR adds additional info
No Docs needed since PR adds additional info
=> add info about content intellisense

.changeset/funny-wolves-dream.md, packages/astro/src/content/utils.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/content/config.ts
The backward compat changes had introduced a bug, where content layer collections were having their `slug` field stripped. This PR fixes it so it only happens for legacy collections. This bug is not present in main.
Fixes #12162
Added a test
=> fix: don't strip "slug" from content layer data

.changeset/light-pears-accept.md, .changeset/three-days-cough.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/render-context.ts, packages/astro/src/core/routing/3xx.ts, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/vite-plugin-astro-server/route.ts
Closes https://github.com/withastro/astro/issues/10576
Closes PLT-2584
This PR brings **two** fixes.
1. The first fix was around the construction of `RouteData[]` during the scanning of the file system. When configure redirects, Astro requires to have the _old_ routes in the file system. The old routes are stored as `"page"` routes, but then we have the function that marks them as `"redirect"`. The end product was an array that contained both routes, and the first one was the `"page"`, which was picked first. The fix removes those routes if we have some redirects
2. The second fix provides some UX improvements to our users by returning an HTML response that emulates that one returned by a static build. This means that we return a `200` status code, which is a bit controversial, but it …
=> fix(routing): correct redirects in dev

packages/astro/types/content.d.ts
ignore for now as the file type is only used as a stub
`pnpm lint`
n/a
=> Fix biome lint warning

.changeset/tidy-bugs-yawn.md, packages/create-astro/src/actions/typescript.ts, packages/create-astro/test/typescript.test.js
Add new line at the end of generated package.json and tsconfig.json files.
before
```json
{
"extends": "astro/tsconfigs/strict"
}
```
after
```diff
{
"extends": "astro/tsconfigs/strict"
}
```
- I add a test case that check the file does end with new line.
- I run `node ./astro/packages/create-astro/create-astro.mjs` in my local machine, and check the files end with new line.
- Could this affect a user’s behavior? We probably need to update docs!
- No.
- Generated files will end with new line.
=> Ensure that the generated package.json and tsconfig.json end with a newline.

.changeset/tough-snakes-reflect.md, packages/astro/e2e/actions-blog.test.js, packages/astro/e2e/fixtures/actions-blog/src/actions/index.ts, packages/astro/e2e/fixtures/actions-blog/src/middleware.ts, packages/astro/e2e/fixtures/actions-blog/src/pages/rewritten.astro, packages/astro/src/actions/runtime/middleware.ts, packages/astro/src/core/constants.ts, packages/astro/src/core/middleware/sequence.ts, packages/astro/src/core/render-context.ts, packages/astro/src/core/routing/rewrite.ts
Closes https://github.com/withastro/astro/issues/12146
Closes PLT-2576
An Astro action uses `context.url.pathname`  for its redirect, however this is a bug because when there's a _rewrite_, the `APIContext` gets updated **in place** when using `next(/*payload*/). Astro actions need to redirect to the same original URL where the initial request started.
To fix the bug, we inject a well known header when we create `RenderContext`, so no matter how many rewrites happen, the original pathname is always there and the same
Created a new e2e test
N/A
=> fix(routing): actions should redirect the original pathname

.changeset/bright-bananas-run.md, packages/astro/templates/env/module.mjs
fix https://github.com/withastro/astro/issues/12210
The parameter name should be prefixed with an underscore as it's used here:
https://github.com/withastro/astro/blob/ed1adf97e3fba7e71e1b0793efd08c6f8f1ebb3b/packages/astro/src/env/vite-plugin-env.ts#L165-L168
Existing tests should pass. Probably should add a test for this, but I'm not sure how at the moment.
n/a
=> Fix setOnSetGetEnv parameter name

.changeset/tidy-dancers-act.md, packages/astro/src/core/app/node.ts
Closes https://github.com/withastro/astro/issues/12192
I tested it against the reproduction provided. It initially broke, but not it returns the correct URL.
I will create a preview and ask the user to use it.
N/A
=> fix: revert regression of port computation

.changeset/slimy-kids-peel.md, packages/astro/src/core/middleware/index.ts, packages/astro/src/core/routing/request.ts, packages/astro/test/units/routing/api-context.test.js
Closes #12215 
Closes PLT-2587
Added a unit test.
Existing CI should pass
N/A
=> fix(middleware): compute client address

.changeset/selfish-toes-carry.md, packages/astro/e2e/dev-toolbar-audits.test.js, packages/astro/e2e/fixtures/dev-toolbar/src/pages/a11y-labelable.astro, packages/astro/src/runtime/client/dev-toolbar/apps/audit/rules/a11y.ts
`button` element is [labelable according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#labelable) and it can be useful to [create switches](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/switch_role) for example. Due to the absence of `button` in `labellableElements`, the Audit app in Dev Toolbar reports a false positive in a11y checks when using `button` as child of a `label`.
Here is a minimal reproduction: https://stackblitz.com/edit/astro-dev-toolbar-audit-label?file=src%2Fpages%2Findex.astro
* When using `id`/`for` it works as expected
* When using `button` as child of `label` the Audit app reports an issue
Adds `button` in `labellableElements` used in the `a11y-invalid-label` rule.
I'm not sure if there are any tests with the …
=> fix(dev-toolbar): false positive in Audit with a11y check on labels

.changeset/eighty-donkeys-fly.md, packages/astro/src/core/client-directive/build.ts, packages/astro/src/core/middleware/vite-plugin.ts, packages/astro/src/core/preview/index.ts, packages/astro/src/core/render/renderer.ts, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/integrations/hooks.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/toolbar/vite-plugin-dev-toolbar.ts, packages/astro/src/types/public/integrations.ts, packages/astro/src/types/public/toolbar.ts, packages/astro/src/virtual-modules/container.ts, packages/astro/src/vite-plugin-integrations-container/index.ts, packages/astro/test/fixtures/middleware-no-user-middleware/astro.config.mjs, packages/astro/test/fixtures/middleware-no-user-middleware/integration-middleware-url.js, packages/astro/test/fixtures/multiple-renderers/renderers/two/index.mjs, packages/astro/test/fixtures/reuse-injected-entrypoint/astro.config.mjs, packages/astro/test/middleware.test.js, packages/astro/test/reuse-injected-entrypoint.test.js
Closes PLT-1993
The entrypoints of adapters, integrations and renderers (server and client) can now accept a `URL`. 
This isn't a breaking change and it should ease the life of integration developers. We already encourage them to use `fileURLtoPath` when providing a string.
Should we use `fileURLToPath` when printing the `URL`? At the moment I used `toString()` because `fileURLToPath` is a Node.js function, and there are cases where we don't have Node.js available.
- Renderers: I took and existing test and changed the correct renderer to be loaded using `URL`
- Middleware: I created a new middleware and added a new test case
- Injected routes: added a new test case
CI should pass
https://github.com/withastro/docs/pull/9680
=> feat: accept `URL` for entry points

.changeset/dirty-bags-double.md, packages/astro/src/core/create-vite.ts
silence vite on cssesc import in dev mode.
Fixes #12229
n.a., bug-fix
=> Fixes an issue with cssesc in dev mode when setting vite.ssr.noExternal: true

.changeset/silly-tomatoes-kick.md, packages/astro-rss/README.md
This tightens up the RSS README to remove unneeded guide pages (consistent with integration readmes) and reduce complexity of config options.
- Remove the guide section and reference our docs entry
- Inline the `RSSFeedItem` docs under `items`
- Remove a duplicate docs section for `content`
- Update types to show field types instead of `object`
- Add support and contributing sections based on other integration READMEs
N/A
Follow up from [this discussion on the RSS docs](https://github.com/withastro/docs/issues/9575#issuecomment-2395548316).
We should remove the inline documentation for `item` options and link to this README as a single source of truth. This should prevent out-of-date options. We should also clearly link to this README to learn more about config options.
=> Improved rss readme

.changeset/soft-rabbits-draw.md, packages/astro/src/container/index.ts, packages/astro/src/core/render-context.ts, packages/astro/test/container.test.js, packages/astro/test/fixtures/container-custom-renderers/src/pages/react-as-page.ts
The container API was rendering components as full-fledged pages, which was a bug.
This PR ships a breaking change to the rendered default behaviour of the container API. Now, the components are rendered as partials by default, and users can tweak the behaviour by passing `partial: false` as a new option
Added new assertions a new test case
https://github.com/withastro/docs/pull/9696
=> fix(container): emit components as partials

.github/workflows/ci.yml
Similar as https://github.com/withastro/astro/pull/12238 but reusing the CI file.
- actions/checkout should be checking out the `next` branch if the event is triggered on the `next` branch
- Use a ternary (kinda) to use the `5.0.0-beta` branch of the docs repo if the PR is against `next`, or the commit event happens on the `next` branch
The ternary is the tricky one, but I confirmed it works in my private gh action playground repo.
n/a
=> Setup CI for next branch

.changeset/tough-snakes-reflect.md, packages/astro/e2e/actions-blog.test.js, packages/astro/src/actions/runtime/middleware.ts, packages/astro/src/core/app/node.ts, packages/astro/src/core/constants.ts, packages/astro/src/core/middleware/sequence.ts, packages/astro/src/core/render-context.ts, packages/astro/src/core/routing/rewrite.ts
Second attempt.
Fixes https://github.com/withastro/astro/issues/12146
This time no headers, we use `Reflect`, which is a technique we already use extensively. We should have led with that approach in the first place.
The uncommented test should pass
N/A
=> fix(routing): actions should redirect the original pathname (#12173)

.changeset/swift-crabs-exercise.md, packages/astro/src/content/types-generator.ts
Builds have been failing with sites that don't have TypeScript installed when using some package managers. This is because `zod-to-ts` has a peer dependency on `typescript`. This PR changes typegen to dynamically import `zod-to-ts` inside a try/catch block, and return `any` for types if it fails.
Fixes #12204
=> fix: dynamically load zod-to-ts

.changeset/wise-parents-agree.md, packages/astro/src/assets/endpoint/node.ts, packages/astro/test/core-image.test.js
Currently the Node image endpoint incorrectly resolves local image paths when a site has a base path configured. This PR ensures that the base path is stripped from the path before attempting to find the image
Fixes #12190
Updated the integration tests to check this
=> fix: handle base path with images

.changeset/honest-dots-jump.md, packages/astro/e2e/fixtures/server-islands/src/pages/[conflicting]/[dynamicRoute].astro, packages/astro/src/core/server-islands/endpoint.ts
- Fixes #11793
The route was being added as the last route in the list, making it the lowest priority. The solution would be to either add it before the routes are sorted by priority or make it higher than other routes.
IMO internal routes should come first since they are required for native Astro features to work, so adding it to the front of the list is enough. If we think they should follow the normal route priority then the fix is different (insert the route based on the priority rules).
Added a conflicting route on the e2e test fixture to reproduce the problem.
Maybe document the prefixes reserved for Astro functionality (`_server-islands/`, `_actions/` and `_astro/`)
=> Add server island route to the front of the route list

.changeset/seven-elephants-suffer.md, packages/astro/src/actions/runtime/middleware.ts
- update wrong error message.
- If you enter "false" as currently shown, it will not work correctly - you must use a `fasle` of type boolean.
=> fix: update wrong action error message

README.md
Adds a CI badge for the `next` branch
Check the link of the new badge
N/A
=> chore: update CI badge

.changeset/twenty-gifts-kick.md, packages/astro/client.d.ts, packages/astro/src/@types/astro.ts, packages/integrations/mdx/template/content-module-types.d.ts
- Fixes #12244
- Add `components` property to Astro’s `MDXInstance` type definition.
- Add `components` property to RenderResult in the template type definition of `@astro/mdx` integration.
Only a type definition change, not sure how to test this properly over here?
Did run `pnpm --filter @astro/mdx run test`: all existing tests passed. 
`pnpm build` passes.
Tested locally on the [minimal reproduction repo](https://github.com/bmenant/astro-render-mdx-components-missing-type-issue).
Only a type definition change.
=> fix(@astro/mdx): add components property to RenderResult type definition

.changeset/loud-cougars-grow.md, packages/astro/src/cli/add/index.ts
This PR is follow-up of https://github.com/withastro/adapters/pull/424
CI should pass
N/A
=> feat: update `astro add vercel`

.changeset/gentle-scissors-bow.md, packages/astro/src/core/app/middlewares.ts
Closes  https://github.com/withastro/astro/issues/12292
Closes PLT-2601
The check origin header middleware was running for all pages. Now it doesn't for pre-rendered pages.
I tested it against the provided reproduction. The warnings aren't there anymore
N/A
=> fix(routing): don't check headers for prenredered pages

packages/astro/src/core/errors/errors-data.ts
This updates a link in an error message, corresponding to reference content that will be moving in https://github.com/withastro/docs/pull/9687
Created as a draft until that docs PR merges and the link is live.
No tests, just docs.
Only changes docs and error message shown.
=> [docs] update a link in error reference

.changeset/slimy-sloths-fry.md, packages/astro/src/core/middleware/vite-plugin.ts, packages/astro/test/config-vite.test.js
In the `config` method of `@astro/plugin-middleware`, we modified it to return an empty object instead of the received opts itself.
There was an issue where some configs were duplicated when using `getViteConfig()`.
This was caused by `@astro/plugin-middleware` returning the received `opts` as the config's return value, resulting in `opts` being merged with itself.
https://vite.dev/guide/api-plugin.html#config
> It can return a partial config object that will be deeply merged into existing config, or directly mutate the config (if the default merging cannot achieve the desired result).
In the config, it is recommended to return only the parts you want to change, rather than the entire modified config.
Since @astro/plugin-middleware does not need to change the config itself, it seems …
=> Fix: The problem getViteConfig() duplicates some config

packages/astro/src/core/errors/errors-data.ts
This updates a link in an error message to correspond to new API reference docs
No tests, just docs.
Only affects generating docs
=> Update link in error message

packages/astro/src/core/errors/errors-data.ts
Updates the links in three error messages related to images to correspond with the reorganized content in https://github.com/withastro/docs/pull/9801/
Just docs
Only affects generating docs errors
=> Update image error messages

.changeset/metal-birds-admire.md, .changeset/stupid-actors-tan.md, packages/astro/src/core/render/params-and-props.ts, packages/astro/test/fixtures/ssr-params/src/pages/[category].astro, packages/astro/test/params.test.js
Closes PLT-2596
Closes #12262 
The pathname coming from the server is usually encoded, so we need to decode it when computing the parameters.
N/A
=> fix(routing): match against decoded pathname

.changeset/gorgeous-foxes-divide.md, packages/astro/e2e/fixtures/i18n/astro.config.mjs, packages/astro/e2e/fixtures/i18n/components/Greeting.astro, packages/astro/e2e/fixtures/i18n/package.json, packages/astro/e2e/fixtures/i18n/src/pages/fr/island.astro, packages/astro/e2e/fixtures/i18n/src/pages/island.astro, packages/astro/e2e/i18n.test.js, packages/astro/src/core/render-context.ts, pnpm-lock.yaml
Closes PLT-2606
Closes #12307 
To fix this, when computing `Astro.currentLocale` we check if `RouteData.component` matches the known server island component. 
If so, we use the `referer` header as pathname. Since `referer` can contain an absolute or relative URL, we check if `referer` is parsable, and if so, we retrieve its `pathname`.
I created a new e2e test
N/A
=> fix(i18n): default locale in server islands

.changeset/itchy-flowers-report.md, packages/astro/src/cli/install-package.ts
- When I tried to run `pnpm astro check` in the env mentioned in _testing_ section. The CLI hints me that it will run `pnpm add @astrojs/check typescript` to install necessary dependenies. After installed, it show me error that `Cannot find package 'typescript' imported from node_modules/astro/dist/cli/install-package.js`.
- After adding logging statement in `install-package.js` file of astro, I surprisingly found that the command is running with `NODE_ENV=production`.
- Thus, I reset `NODE_ENV` to ensure install command run in dev mode
Before fixing.
After fixing. 
Create an astro project with `typescript` _installed as a devDependency_. and without `@astrojs/check` installed, then run `pnpm astro check`. Compare the results before  PR and after PR.
No docs is …
=> fix(cli): reset `NODE_ENV` to ensure install command run in dev mode

.changeset/clean-plums-tap.md, packages/astro/src/core/app/node.ts
PR to fix bug described in https://github.com/withastro/astro/issues/8714 that is still an issue
I have made a new reproducer to break the example ssr project if you apply this [https://github.com/imattacus/astro/commit/6ed890780fcdb5b8eeb7be9c1a82c2f1138886bd](https://github.com/imattacus/astro/commit/6ed890780fcdb5b8eeb7be9c1a82c2f1138886bd) patch.
Then build `npm run build` the ssr example, and run it `npm run server`.
Before this fix if you run `curl -i curl --raw -i -v localhost:4321` 
```
$ curl --raw -i -v localhost:4321
* Host localhost:4321 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:4321...
* Connected to localhost (::1) port 4321
> GET / HTTP/1.1
> Host: localhost:4321
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK …
```
=> fix: Destroy the node http server response stream if there was a caught error

.changeset/heavy-walls-rhyme.md, packages/astro/src/prefetch/vite-plugin-prefetch.ts
fix https://github.com/withastro/astro/issues/12306
We need to return a `map` property to not have rollup yelling that's we're generating invalid sourcemap
tested the repro manually
n/a
=> Fix prefetch sourcemap generation

.changeset/long-monkeys-exercise.md, packages/astro/src/assets/types.ts, packages/astro/src/type-utils.ts
This PR fixes #12319
As I mentioned in the issue, there are two ways of fixing the problem:
1. Use a type helper to properly handle `Omit`ting from types containing index signatures.
2. Remove that index signature from the `ImageTransform`.
I went with the first one since I guess that index signature was put there for a reason. :)
I also applied `Simplify`. This is to force TypeScript better resolve properties. Not doing that results in the following error when an empty options objects is passed to `getImage`:
```
Type '{}' is not assignable to type 'UnresolvedImageTransform'.
Property 'src' is missing in type '{}' but required in type '{ src: string | ImageMetadata | Promise<{ default: ImageMetadata; }>; inferSize?: boolean | undefined; }'.ts(2322)
```
With `Simplify` the error is:
``` …
```
=> fix(assets): fix `getImage` options type

.changeset/famous-timers-move.md, packages/astro/src/core/dev/restart.ts
- Fixes an issue in dev server watch file handling that could cause multiple restarts for a single file change.
- This issue was triggered by changes to watched files added by integrations through Astro's `addWatchFile` API. Our override for the Vite restart handler was missing a check for the container's `restartInFlight` flag and caused multiple overlapping restarts.
- This also fixes the repeated `Port 27969 is in use, trying another one...` message that appeared in this case.
- Tested locally by running Astro's test suite and on a Starlight site.
- Just a bugfix.
=> Fix watchfile multiple dev server restart

.changeset/cuddly-feet-float.md, packages/astro/src/config/index.ts
Use `inlineAstroConfig.logLevel` if passed to `getViteConfig`
Tested locally using fork.
There are no additional docs as this change fixes what should already happen.
=> fix: honor getViteConfig inlineAstroConfig.logLevel setting

.changeset/many-eyes-call.md, benchmark/bench/cli-startup.js, benchmark/bench/memory.js, benchmark/bench/render.js, benchmark/bench/server-stress.js, packages/astro/src/cli/add/index.ts, packages/astro/src/cli/docs/open.ts, packages/astro/src/cli/exec.ts, packages/astro/src/cli/install-package.ts, scripts/smoke/cleanup.js, scripts/smoke/index.js
close https://github.com/withastro/astro/issues/12241
In all of our tinyexec usage, we need `throwOnError: true` so that non-0 exit code will error out, which is the expected behaviour in most case. I added that in this PR.
However its error logs aren't the user-friendliest, so I wrapped it with a utility to improve it. I'm working to see if I can upstream the changes so we don't have to wrap it ourselves.
Tested manually. I tweaked the install dependencies command to `npm foobar` (which is expected to fail). Before:
After (now it properly surfaces the error):
n/a. bug fix
=> Improve tinyexec errors

packages/astro/client.d.ts, packages/astro/src/assets/types.ts, packages/astro/src/assets/vite-plugin-assets.ts, packages/astro/src/core/config/schema.ts, packages/astro/src/types/public/config.ts
Just creates the config option
=> feat: add experimental responsive images config option

.changeset/wise-bulldogs-jump.md, packages/astro/src/cli/index.ts, packages/astro/src/cli/sync/index.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/core/messages.ts, packages/astro/src/core/sync/index.ts
-`astro build` does not report which file has an invalid frontmatter for MDX files.
This PR fixes that. 
After the fix, the error looks like the below:
Closes #12352 
It was manually tested by running a local build.
Not needed as it just enhances existing error messages.
=> fix: show file name with invalid frontmatter errors for MDX

.changeset/dull-lemons-check.md, packages/astro/src/actions/runtime/middleware.ts, packages/astro/src/actions/runtime/route.ts, packages/astro/src/actions/runtime/utils.ts, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/src/actions/utils.ts, packages/astro/test/actions.test.js, packages/astro/test/fixtures/actions/src/pages/invalid.astro
Closes https://github.com/withastro/astro/issues/12393
Closes PLT-2625
The user code was invalid, but Astro didn't catch it. Now it does
N/A
=> fix(actions): better runtime check for invalid usages

.changeset/nine-mayflies-film.md, packages/astro/src/vite-plugin-astro-server/route.ts
This fixes unexpected `200` status codes for action errors in development. It seems that `status` was _always_ overridden with `200 | 404 | 500`, which prevents the correct `response.status` from being read.
Ensure tests for custom 404 and 500 routes still pass
N/A
=> Fix incorrect status code in dev server for action errors

packages/astro/components/Image.astro, packages/astro/src/assets/consts.ts, packages/astro/src/assets/internal.ts, packages/astro/src/assets/layout.ts, packages/astro/src/assets/services/service.ts, packages/astro/src/assets/services/sharp.ts, packages/astro/src/assets/types.ts, packages/astro/src/types/public/config.ts, packages/astro/test/core-image-layout.test.js, packages/astro/test/core-image-service.test.js, packages/astro/test/fixtures/core-image-layout/src/pages/build.astro, packages/astro/test/fixtures/core-image-layout/src/pages/fit.astro
Adds new `fit` and `position` parameter to `ImageTransform`, which tells an image service how to handle images when the requested aspect ratio is different fromt he source. Currently if both width and height are set then height is ignored. Now if `fit` is set then both are used, and cropping is enabled. 
- `fit` sets the behvior for an image service if the requested aspect ratio is different from the source image. Allowed values are CSS `object-fit` values, but it also accepts arbitrary strings that may be understood by a particular image service. 
- `postion` is used when cropping, to choose the point at which to focus the crop. It accepts CSS `object-position` values, but also allows arbitrary strings that may be supported by an image service. For example, the default sharp service …
=> feat: add crop support to image services

.changeset/spicy-ties-matter.md, packages/astro/src/core/constants.ts, packages/astro/src/core/middleware/noop-middleware.ts, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/fixtures/middleware space/src/middleware.js, packages/astro/test/middleware.test.js
Closes https://github.com/withastro/astro/issues/12391
Closes PLT-2627
The middleware is called even when a user doesn't have a route that doesn't match an existing FS route. Users can return a `Response` that isn't a 404.
The dev server didn't know that, so this PR fixes it.
To understand this use case, I decoded to add a tiny logic to our no-op middleware, which is used only when the user doesn't have a middleware. The no-op middleware adds an arbitrary header. If header **isn't present**, it means that the user have their own middleware, so we need to return any status returned by the `.render` function. 
Added two new test cases
N/A
=> fix(routing): middleware in dev

.changeset/brown-bulldogs-share.md, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/src/actions/utils.ts, packages/astro/test/fixtures/actions/src/pages/invalid.astro
This PR ports https://github.com/withastro/astro/pull/12402 into `next`. It was incorrectly lost during the merge, plus the actions code changed a lot, so it required some wiring.
CI should pass
N/A
=> fix(actions): internal symbol check

benchmark/bench/codspeed.js, benchmark/packages/adapter/src/server.ts
This PR adds 6 benchmarks to CodSpeed. It moves the building of the project to before running the benchmarks, it creates two apps, one with streaming enabled and one where it's not enabled.
The pet project that we create has three routes: `/astro`, `/md` and `/mdx`, so we already know in advance what **we want** to test.
This CI should work and we should see the results already.
CodSpeed will go crazy because we will remove the benchmark we already have, so we must acknowledge the deletion. 
N/A
=> chore: breakdown of benchmarks

.changeset/dirty-teachers-know.md, packages/astro/src/transitions/router.ts
do not access properties of the browsers history state if it is not defined 
defensive coding, no additional test
n.a.
=> prevents access to the history state if not set

packages/astro/src/assets/types.ts, packages/astro/src/assets/utils/imageAttributes.ts, packages/astro/src/types/public/config.ts
Updates the jsdocs for the experimental responsive images flag and config options, as well as the jsdocs for the Image component
This is a docs PR!
=> docs: add docs for responsive images

.changeset/wild-houses-learn.md, packages/integrations/svelte/package.json
Renamed `client.js` to `client.svelte.js` but forgot to include it in the `"files"`.
=> Publish missing file for svelte integration

STYLE_GUIDE.md
Fixes #12464
- The links to our linting and formatting configs were outdated since both files had been modified/renamed. This makes the links point to the new files.
I clicked the markdown preview links and got the files
No docs since this is a change only relevant for github
=> Update links to linting and formatting files in the style guide

.github/workflows/continuous_benchmark.yml
At the moment the PRs from non-maintainers fail the benchmark job because there's a check over the org. This PR removes that check
CI should pass
N/A
=> ci: remove owner check to enable external PR jobs

.github/workflows/continuous_benchmark.yml
This filters the paths for when the benchmarking workflow should be triggered.]
**UPDATE**
[I added the `token` part](https://docs.codspeed.io/integrations/ci/github-actions#2-create-the-benchmarks-workflow), which I completely forgot 😅  
That should fix the runs from third party PRs
It should *not* run in this PR I think 
N/A
=> ci: filter paths of when running the benchmark action

.changeset/six-pianos-draw.md, packages/astro/src/content/loaders/glob.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/pages/collections.json.js
- Closes #12195
- Closes PLT-2539
- The map was not initialized on load so deleting a non updated entry would not actually delete it from the data store
Adds a test case
N/A bugfix
=> fix: content layer glob deletion

.changeset/thin-cups-peel.md, packages/astro/src/core/build/plugins/plugin-ssr.ts
The middleware is now dynamically imported, which means we don't need to have it at the top of `entry.mjs`
Closes PLT-2659
I tested locally and checked the emitted file. That import is **unused**, so there's no need for new tests.
N/A
=> fix(build): generated entry

.changeset/early-scissors-beg.md, packages/astro/src/core/app/pipeline.ts, packages/astro/src/core/base-pipeline.ts, packages/astro/src/core/errors/errors-data.ts
- Removes the default throw for `getEnv`.
- Plan is to move away from having `astro:env` be dependent on timing; if some code runs before `setGetEnv` has been called it currently could result in incorrect or missing environment variables.
- Instead now we always default to the `process.env[key]` approach. Since this is what most adapters need anyways, we don't have to worry about bundling causing issues of code executing in unwanted order.
- Now only Cloudflare needs to ensure it calls `setGetEnv`, and it already has the constraint of not allowing vars to be grabbed at the top level.
- manual
N/A, bug fix
=> Remove default throw behavior in astro:env

packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/pipeline.ts, packages/astro/src/core/middleware/vite-plugin.ts
This PR refactors our build by removing the necessity of having a file called `middleware.mjs`. We were emitting `middleware.mjs` in order to have a predictable way to load the middleware file; however, since we started emitting the middleware chunk as a virtual module, we were emitting two files: `middleware.mjs` that simply do an export of `onRequest` from the middleware chunk.
`middleware.mjs` isn't needed anymore, and we directly import the chunk that rollup generates after the build.
This is an internal refactor; existing CI should pass, and no changeset is needed.
N/A
=> refactor(build): don't emit `middleware.mjs`

packages/astro/src/assets/internal.ts, packages/astro/src/types/public/config.ts
Improves the wording of the experimental flag docs for responsive images. Currently it says you should not set the sizes or widths values manually. This is true in some cases, but not all. This PR clarifies these, explainign when you might need it. It also ensures that the densities value is ignored if set. This was already listed as not supported, and this just aligns the actual behaviour with the docs.
Thanks @carlcs for the suggestion.
=> chore: clarify wording of responsive image props

.changeset/olive-garlics-marry.md, packages/astro/src/runtime/server/render/server-islands.ts
Closes https://github.com/withastro/astro/issues/12421
Closes PLT-2643
The PR just adds a check if `script` exists, because external libs could mess up with DOM and stuff. 
I tested it locally
N/A
=> fix: server island hydration

.changeset/rotten-dodos-judge.md, packages/astro/src/core/server-islands/endpoint.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/astro/test/fixtures/server-islands/ssr/src/components/Island.astro, packages/astro/test/server-islands.test.js
- Server islands should be able to set headers, specifically their own caching.
- Because we render the island inside of a template it won't be able to do so, because of streaming.
- Fix is to call the component early, so it can render before we start streaming out.
- Added the ability to use an `ASTRO_KEY` in dev too, needed for the tests, but users might also want the ability for testing as well.
N/A, bug fix
=> Call server island early so it can set headers

.changeset/unlucky-kids-compete.md, packages/astro/src/core/middleware/noop-middleware.ts
Closes https://github.com/withastro/astro/issues/12495
Closes https://github.com/withastro/astro/issues/12496
Closes https://github.com/withastro/astro/issues/12497
Closes PLT-2667
CI should pass 
I tested it with a local reproduction. Can't see the warning anymore.
N/A
=> fix(routing): don't access Request headers

.github/workflows/snapshot-release.yml, package.json, pnpm-lock.yaml
When publishing a snapshot, exit pre mode if needed. Snapshots can't currently be published in pre mode. The snapshot itself is still tagged as experimental, so that's not an issue.
=> ci: exit pre if needed

.changeset/red-paws-juggle.md, packages/astro/src/assets/runtime.ts, packages/astro/test/core-image-svg.test.js
This fixes the `id` generation for sprite icons. The previous implementation only ever generated one id per page. This caused the first icon to be used for all icons. Instead we need to increment on each unique icon. 
I was able to accomplish this by checking if a component had rendered already and generating a new id if it hadn't. This now stores the full id per page.
There were a few issues with the previous tests that I have addressed. I also updated the test to ensure that the ids are all unique which I should have asserted previously.
No docs necessary.
--- 
I can't request reviewers  but wanted to tag @ematipico, @natemoo-re and @bluwy since this was related to the changes requested and committed to my previous branch. https://github.com/withastro/astro/pull/12067#discussion_r1824671 …
=> Fix SVG Component sprite ids

examples/server-islands/tsconfig.json
- Removes `sever-islands/tsconfig.json` in the examples directory.
- Looks like this example was removed in #12196 but #12083 accidentally reintroduced it by adding the `tsconfig.json`.
- Noticed this on https://astro.new/next/templates/ which links to this example, but has no content
- n/a
- n/a
=> Delete empty `server-islands` example

.changeset/sixty-fishes-flow.md, packages/astro/e2e/actions-blog.test.js, packages/astro/src/actions/consts.ts, packages/astro/test/actions.test.js, packages/integrations/react/server.js, packages/integrations/react/src/actions.ts
Renames the generated `_astroAction` query param to `_action` when using HTML form actions. Some developers may prefer to avoid leaking the framework name into the URL bar, so I expect this to be a better default. If the name `_action` proves challenging for conflicts, we can investigate an `astro.config` option.
Update const and ensure tests still pass.
N/A - not documented
=> Rename Action query param to _action

packages/astro/src/core/errors/errors-data.ts
Updates links in error messages to match the new page URL in docs (`/guides/server-side-rendering/` -> `/guides/on-demand-rendering/`)
No tests, identified by docs link-checker as broken links with the new URL structure.
This will fix docs!
=> Update links in errors-data.ts

.changeset/young-terms-hammer.md, packages/integrations/mdx/src/index.ts
Changes the MDX integration to add the renderer entrypoint as a full path file instead of being a specifier. Astro v5 now accepts `URL` too, so it's a better of passing the correct `URL`
The existing CI should pass.
I tested it against [this reproduction](https://github.com/HiDeoo/starlight/tree/hd-astro-v5), by linking `@astrojs/mdx` package directly to my local version, and running `pnpm dev` inside the `/docs` folder. The project compiles and it renders the pages without errors. 
N/A
=> refactor(mdx): add entrypoint as full path file

.changeset/hot-dingos-dress.md, packages/astro/src/i18n/middleware.ts, packages/astro/src/vite-plugin-astro-server/request.ts, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/fixtures/i18n-routing/src/pages/404.astro, packages/astro/test/i18n-routing.test.js
Closes PLT-2671
Closes https://github.com/withastro/astro/issues/12509
The issue was caused by the i18n middleware doing all it's "routing strategy checks" when rendering the `404.astro` component. This should be an expection, because all the "routing strategy checks" were already done when rendering the non-existent route. 
To fix the issue, we have an internal header that we attach to a `Response`. We check that header at the very beginning of the middleware.
**Additional change**
I removed the recursions that we use in development, which **isn't needed**, and it should be things a bit more easy to debug. To remove the recursion, we just create a new `RenderContext` with the `/404` route, and render it.
Tested it against the issue of reproduction. Current tests should pass. Added a new …
=> fix(i18n): render `404.astro` when i18n is enabled

.github/workflows/snapshot-release.yml
Finds the base branch for the current changeset from the config and fetch that before doing a snapshot. This avoid errors resolving the base.
=> ci: fetch changeset base branch when snapshot

.changeset/bright-pants-trade.md, packages/astro/src/assets/utils/vendor/image-size/types/jpg.ts
Fixes #12530
* Fixed incorrect handling of non-`0xFF` blocks in the JPEG image size calculation. Instead of skipping one byte, the entire block is now skipped, improving performance and accuracy.
* Before this change, the code would incorrectly enter and parse non-`0xFF` blocks, leading to incorrect image size determination. This change ensures that only valid JPEG blocks are processed, skipping unnecessary metadata blocks.
This change was tested manually by verifying that the image size calculation is accurate for JPEG images with various metadata blocks. No new tests were added, as the existing tests should cover this scenario.
This change does not affect user behavior, so no documentation updates are required. The fix is internal to the JPEG image size calculation logic and does not …
=> Fix JPEG image size determination

.github/workflows/examples-deploy.yml, examples/blog/src/components/HeaderLink.astro, examples/portfolio/src/components/Nav.astro, examples/with-nanostores/src/layouts/Layout.astro, examples/with-nanostores/src/pages/index.astro, examples/with-nanostores/src/utils.ts
- This PR (partially) fixes support for `base` in the blog, portfolio, and with-nanostores examples.
- In the blog and portfolio examples, this fixes the highlighting of the current page in the site navigation components. It doesn’t fix other aspects of these templates to work with base (e.g. image paths etc.) just for simplicity’s sake, but we could in a follow up if we wanted.
- In the with-nanostores example, this fixes all user-authored links to use a base.
- This improves the deployments to preview.astro.new, which builds each example with `base` and then tries to auto-prefix with base when it can, but there are some edge cases it can’t handle, which this PR fixes
- This PR also adds a new GitHub workflow which runs when pushing to `main`. It checks to see if anything in the …
=> Examples fixes and preview.astro.new support

.github/workflows/benchmark.yml, .github/workflows/check.yml, .github/workflows/ci.yml, .github/workflows/continuous_benchmark.yml, .github/workflows/preview-release.yml, .github/workflows/release.yml, .github/workflows/scripts.yml, .github/workflows/snapshot-release.yml, .github/workflows/test-hosts.yml
Use node 22 instead of 18 since 22 is now the active LTS. Also added a new matrix to test ubuntu and node 22.
Theoretically it should be a little faster with node's recent perf improvements.
CI should pass
n/a
=> Use node 22 in CI

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/sync-examples.yml
This PR removes `next` from our workflows, mainly the release, ci checks and example sync.
It also adds the branch `4-legacy`, which we will use for security fixes regarding v4
CI should pass
N/A
=> ci: remove `next` from workflows

.changeset/blue-gorillas-accept.md, packages/astro/src/core/sync/index.ts, packages/astro/test/content-layer.test.js
Currently we're only referencing the content types in dev if the content dir exists. Since we no longer require that, in many cases this wasn't being generated. This PR changes the logic to ensure it's always created when needed.
Fixes #12555
Added a test
=> fix: generate types even without src/content

.changeset/tame-hats-fold.md, packages/astro/src/core/request.ts
Fixes #12548 
- Ensure that any existing value and writable properties are deleted from the headers descriptor before adding getters and setters.
- This prevents the error: `Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>`
- Removed the `value` and `writable` properties from the `headers` descriptor before defining getters and setters for the `headers` property on the `Request` object.
- Updated the `Object.defineProperty` call to prevent the `Invalid property descriptor` error during prerendering.
- Added a setter to `request.headers` to allow updating `_headers` if needed.
This change was tested by building the Astro project with `prerender = true` and confirming that the build completes without the `Invalid property descriptor` …
=> fix: remove value and writable properties from headers descriptor

.changeset/twenty-lobsters-think.md, packages/integrations/markdoc/src/html/tagdefs/html.tag.ts, packages/integrations/markdoc/test/fixtures/render-html/src/content/blog/simple.mdoc, packages/integrations/markdoc/test/render-html.test.js
Normalises boolean HTML attributes to boolean literals, because Markdoc treats `''` as falsy.
Fixes #12409
Adds a test
=> fix(markdoc): correctly render boolean HTML attributes

.changeset/dirty-bees-repair.md, packages/upgrade/src/actions/install.ts
Closes #12455
This change fixes an issue where `@astrojs/upgrade` announces integration updates for already up-to-date packages by removing the prefix from `targetVersion` while comparing. 
https://github.com/user-attachments/assets/41b2cf80-5cc0-4894-a298-497204bc934c
Manually Tested
N/A bug fix
=> fix(upgrade): remove the prefix from `targetVersion` while comparing versions

.changeset/empty-jobs-impress.md, packages/astro/src/actions/integration.ts
This updates the template that generates `.astro/actions.d.ts` file to make sure types work when `moduleResolution: "NodeNext"` is used on tsconfig.json.
I haven't added tests because I am not familiar on how to do so for type tests that require a different tsconfig.json.
No behavior changes.
---
Closes #12575
=> fix(actions): explicitly import index.ts to fix types when moduleResolution is NodeNext

README.md
This PR removes the badge of CI `next` from the readme
N/A
N/A
=> chore: remove next badge from readme

packages/integrations/sitemap/package.json, pnpm-lock.yaml
The `sitemap` tests are currently failing because it uses an outdated version of `@astrojs/node`.
This PR updates it
CI should pass
N/A
=> test: update `sitemap` tests to use the latest `@astrojs/node`

examples/starlog/src/styles/colors.scss, examples/starlog/src/styles/global.scss, examples/starlog/src/styles/layout.scss, examples/starlog/src/styles/type.scss
This PR follows up on a [post from Chris on Discord](https://discord.com/channels/830184174198718474/845430950191038464/1313290167746035763).
Vite now issues warnings because of some changes in Sass. This PR fixes that.
* Adds `@use` statements when needed for built-in modules (e.g. `sass:color`)
* Replaces all Sass `@import` with `@use` (I choose to reuse the filename as namespace... this can be a bit confusing for colors... since we also have `color` for `sass:color`.)
* Moves all top-level declaration before nested rules
Do I need to add a changeset? I wasn't sure since it is an example and not a package.
Manually by running the example. I haven't seen any changes in the browser so I think everything works as before. And with these changes, no warnings related to Sass in the console! …
=> fix(examples): update Sass usage in Starlog example

.changeset/fuzzy-bats-try.md, packages/astro/templates/content/types.d.ts
Currently the types for `getEntry` exclude undefined if the key passed is a key in the type. This works for the old system where there were types for every entry, but now they are types as `Record<string, {//...the type }>`, it means any key will match (because they're all strings), meaning the entries are incorrectly returned as not nullable. This PR changes this so that if the key type is `string` (i.e. the type does not have specific entries), then the return type is nullable.
This is technically a breaking change but I think we can slip it in in 5.0.x
Fixes #12598
Our migration guide already says that the types for getEntry have been loosened.
=> fix: include undefined in types for getEntry with content layer

examples/hackernews/package.json, examples/ssr/package.json, pnpm-lock.yaml
Few examples were using an alpha version of `@astrojs/node`. This PR updates that them.
CI should pass
N/A
=> chore: update examples to use latest node

.github/ISSUE_TEMPLATE/---01-bug-report.yml, .github/workflows/issue-labeled.yml
This PR updates:
- the CI message for requesting a reproduction, by sending users straight to stackblitz.
- the issue template to redirect users straight to stackblitz
Unfortunately, we can't use IDX for reproduction
N/A
N/A
=> ci: update repro link

.github/ISSUE_TEMPLATE/---01-bug-report.yml, .github/workflows/issue-labeled.yml
=> chore: use the `/repro` route for reproduction

.changeset/red-emus-repair.md, packages/db/src/core/integration/index.ts
In Astro DB we eagerly load the virtual module at startup. Currently we load the resolved virtual module ID, which is prefixed with a null byte. This worked fine previously, but fails in Vite 6/Astro 5. This PR changes the import to use the base virtual module ID (`astro:db`).
Fixes #12474
=> fix(db): import base virtual module ID

packages/astro/src/types/public/config.ts
Removes an incorrect and unnecessary link in our config reference docs.  
This is not urgent as live docs have been manually overwritten to be correct. This is needed as a correction at source.
no tests; change to docs text
only docs!
=> [docs] removes link in config reference

.changeset/silver-hats-agree.md, packages/astro/components/Image.astro, packages/astro/components/Picture.astro, packages/astro/test/core-image-layout.test.js
Fixes a bug where the class attribute was rendered twice on images during builds
Fixes #12629
Adds more tests for images during build, including tests of the raw HTML without cheerio
=> fix: don't apply duplicate class to images

.changeset/violet-bugs-enjoy.md, packages/astro/src/content/vite-plugin-content-virtual-mod.ts, packages/astro/src/core/dev/dev.ts
The content layer needs to know if it is running in dev, so that it knows whether to find the datastore in the `.astro` folder (so it can be watched for changes) or in `node_modules` (so it is cached between builds in production environments). Previously it was incorrectly detecting this in the Vite plugin by using the `isProduction` flag, which reports as false in a test enviornment. This PR changes it to instead use the `env.command`.
Fixes #12612
=> fix: use correct datastore location in test environment

.changeset/fuzzy-pans-cough.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/request.ts, packages/astro/src/vite-plugin-astro-server/route.ts
This PR adds the `routePattern` to the warning about `Astro.request.headers` being used in pre-rendered pages.
This should give us better information when debugging the annoying warning :)
CI should pass
N/A
=> chore: better warning

packages/astro/src/core/errors/errors-data.ts
Updates some error message URLs for our new content structure.
Not urgent as these are manually overwritten and live in docs; just updating the source for eventual consistency.
No tests, docs!
All docs!
=> [docs] update error message URLs

.changeset/heavy-buttons-compare.md, packages/astro/src/core/config/schema.ts, packages/astro/src/core/config/validate.ts, packages/astro/src/core/errors/zod-error-map.ts, packages/astro/src/core/messages.ts, packages/astro/test/content-collections.test.js, packages/astro/test/error-map.test.js, packages/astro/test/legacy-content-collections.test.js, packages/astro/test/units/config/config-validate.test.js
- Upstreams improvements to the Zod error map that we made in Starlight. We initially copied Astro’s error map and then iterated on it. It’s still similar, just with better handling for complex types like unions, and more consistent formatting (e.g. if you look at the changed tests you’ll see we’d report errors where some stuff was wrapped with backticks and other stuff wasn’t within the same error message and that that is now fixed).
- Updates error handling for user config parse errors to use the error map. With the v5 release, we’re seeing a fair amount of the rather confusing `output Invalid input` error when people leave `output: "hybrid"` in their config and this aims to improve that.
- This also updates the styling for these messages as they can now contain a bit more useful …
=> Improve Zod error messages and user config error messages

.changeset/angry-pumas-act.md, packages/astro/src/cli/info/index.ts, packages/astro/test/cli.test.js
`astro info` copy to clipboard has not been working on Mac because piping the input to `pbcopy` using `execSync` seems to not work. This PR fixes that by switching to `spawnSync` instead of `execSync`. It also adds a helper to read from the clipboard so we can check it works across platforms, and adds support for a `--copy` flag to avoid needing to prompt.
Fixes #12639
Adds a new test suite.
=> fix: correctly copy to clipboard in `astro info`

.changeset/loud-cobras-rhyme.md, packages/astro-rss/src/index.ts, packages/astro-rss/test/rss.test.js
According to https://www.rssboard.org/rss-mime-type-application.txt
The default content type for RSS should be `application/rss+xml`
=> fix(@astrojs/rss): use standard rss content type, add utf-8 charset

.changeset/wild-geckos-draw.md, packages/astro/src/container/index.ts, packages/astro/src/core/app/index.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/render-context.ts, packages/astro/src/core/request.ts, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/fixtures/client-address/src/middleware.ts
User observed that calling actions resulted in an error about not having clientRequest available.
This is because the user had a middleware that cloned the request, which loses all of the symbols.
- The fix is to pass the clientAddress directly into the RenderContext. This deprecates the `clientAddressSymbol`, but we need to keep it for now because some adapters set the clientAddress that way.
- Note that similar fixes should be done for other symbol usage on the Request object (locals is one).
- Middleware added to the client address fixture which recreates the problem.
N/A, bug fix.
=> Keep clientAddress on cloned requests

.changeset/proud-wombats-mate.md, packages/astro/src/core/app/index.ts, packages/astro/test/fixtures/ssr-error/package.json, packages/astro/test/fixtures/ssr-error/src/pages/[...slug].astro, packages/astro/test/fixtures/ssr-error/src/pages/index.astro, packages/astro/test/ssr-error-pages.test.js, pnpm-lock.yaml
Closes #12419 
Closes PLT-2669
This PR changes the merging strategy of the headers in SSR when we render an error page. It relies on a `Map` to remove the duplicates. 
N/A
=> fix(ssr): duplicate custom headers

.changeset/unlucky-wasps-refuse.md, packages/markdown/remark/src/frontmatter.ts, packages/markdown/remark/test/frontmatter.test.js
fix https://github.com/withastro/astro/issues/12656
The regex didn't account for file encoded in utf8 with bom. The bom character is now part of the regex.
Also, I'm not sure what I was smoking with https://github.com/withastro/astro/pull/12646, but I supported spaces before the `---` which doesn't makes sense as `---` should only be used on new lines. This is also fixed here.
Updated tests reflecting changes above.
n/a. bug fix.
=> Fix frontmatter parsing with utf8 bom

packages/astro/src/core/app/index.ts, packages/astro/src/core/base-pipeline.ts, packages/astro/src/core/middleware/index.ts, packages/astro/src/core/request.ts, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/units/routing/api-context.test.js, packages/astro/test/units/vite-plugin-astro-server/response.test.js
This PR refactors how we internally handle the `locals`. The use of the symbol on `Request` has been limited only to the dev server, because that's the only way for adapters to send us `locals` in dev.
Technically, this isn't a breaking change for the adapters because the `App.render` function already provides the APIs for passing initial locals. Plus, the `RenderContext` class already holds the locals when it's created, so it's safe to remove the places where `Reflect.set`/`Reflect.get` is used.
The only place where we need to keep the `Request` usage is a runtime, public API called `createContext`, which is only used my the edge middleware.
The CI should pass
N/A
=> fix(routing): don't attach locals to request

.changeset/green-coins-tie.md, packages/integrations/vue/package.json, pnpm-lock.yaml
Fix `vite` peer dependency issue for vue integration
```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @vitejs/plugin-vue-jsx@4.0.1
npm warn Found: vite@6.0.3
npm warn node_modules/vite
npm warn   vite@"^6.0.1" from @astrojs/vue@5.0.1
npm warn   node_modules/@astrojs/vue
npm warn     dev @astrojs/vue@"^5.0.1" from the root project
npm warn   4 more (@vitejs/plugin-legacy, @vitejs/plugin-vue, astro, vitefu)
npm warn
npm warn Could not resolve dependency:
npm warn peer vite@"^5.0.0" from @vitejs/plugin-vue-jsx@4.0.1
npm warn node_modules/@vitejs/plugin-vue-jsx
npm warn   @vitejs/plugin-vue-jsx@"^4.0.1" from @astrojs/vue@5.0.1
npm warn   node_modules/@astrojs/vue
npm warn
npm warn Conflicting peer dependency: vite@5.4.11
npm warn node_modules/vite
npm warn   peer …
```
=> chore: fix vite peer dependency issue for vue integration

.changeset/fast-adults-lick.md, packages/astro/src/assets/utils/node/emitAsset.ts, packages/astro/src/assets/vite-plugin-assets.ts, packages/astro/src/content/content-layer.ts, packages/astro/src/content/runtime-assets.ts, packages/astro/src/content/utils.ts, packages/astro/src/content/vite-plugin-content-imports.ts, packages/integrations/markdoc/src/content-entry-type.ts
A user that tried to upgrade to Astro v5 detected a memory leak during the build. The issue was discovered by @HiDeoo , and this PR fixes the issue.
The PR passes a boolean called `experimentaSvgEnabled` down to the three lines that cause the memory leak.
CI should pass
N/A
=> fix(svg): conditional opt-in

.changeset/shy-worms-talk.md, packages/astro/src/cli/info/index.ts
`xclip` process on OS Linux made `spawnSync` not [to return](https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options:~:text=with%20the%20exception%20that%20the%20function%20will%20not%20return%20until%20the%20child%20process%20has%20fully%20closed). Further info at [Stack Overflow](https://stackoverflow.com/questions/52169670/node-child-process-execsync-hangs-with-xclip).
Also updated the `xclip` arguments as per man pages for better familiarity, although the used arguments worked.
- Fixes [this issue comment](https://github.com/withastro/astro/issues/12639#issuecomment-2520897644).
- Needs review - not sure if it's a legit fix, as it globaly adds new settings to `spawnSync`. Could be changed to apply only for `xclip` if needed.
Tested locally, with linux and …
=> fix: copy info to clipboard on linux

.changeset/wild-ducks-decide.md, packages/upgrade/src/actions/verify.ts
`@astrojs/upgrade` checks if it's online by doign a DNS lookup for the registry host. This was broken for registries that have a port in the URL (mostly local ones like Verdaccio) because it was using url.host, which includes the port. This PR fixes that by using url.hostname.
Fixes #12660
=> fix: correctly check isOnline with port

.changeset/bright-crabs-kick.md, packages/astro/src/core/build/pipeline.ts, packages/astro/test/fixtures/middleware-full-ssr/package.json, packages/astro/test/fixtures/middleware-full-ssr/src/error.js, packages/astro/test/fixtures/middleware-full-ssr/src/middleware.js, packages/astro/test/fixtures/middleware-full-ssr/src/pages/index.astro, packages/astro/test/middleware.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/12690
The middleware was always imported during the build, even before its execution. 
This PR changes that by assigning a function that does the loading.
CI should pass. I created a new test case. In the test case the middleware imports a file that throws an error at runtime. In the test case the middleware isn't used because all pages SSR, so no errors should be thrown.
N/A
=> fix(middleware): don't import via entrypoint

.changeset/tidy-ligers-tan.md, packages/astro/src/core/util.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/false-positive.astro
Currently the markdown vite plugin just checks if the id ends in a makrdown extension. This breaks if the id includes a query param. This PR strips the query string before checking.
Fixes #12711
Added test
=> fix: strip query string before checking md extension

packages/astro/src/core/util.ts
Refactors #12712 to use shared helper
=> chore: refactor query param strip

.changeset/spicy-guests-protect.md, packages/astro/src/actions/plugins.ts, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/src/actions/runtime/virtual/shared.ts, packages/astro/templates/actions.mjs, packages/astro/test/actions.test.js
Closes https://github.com/withastro/adapters/issues/464
Problem: node adapter doesnt pass astro actions request and always redirect this to path with the / in the end
image
Solution: add trailing slash to actions url in case `trailingSlash: "always"` to pass node adapter static handler
Tested with node adapter and add new test for server actions handler
Probably no need to update docs
=> fix(actions): support trailing slash

.changeset/tame-bags-remember.md, packages/astro/src/content/mutable-data-store.ts
The data store has to write a number of different files to disk, which are in turn watched by the filesystem watcher. In some very large sites this was causing issues where the watcher would report the changed file before it had finished writing to disk.
This PR changes all data store file operations to use atomic writes: files are first written to a tmp dir, and then moved.
Fixes #12702
This is hard to reproduce. Tested manually using a reproduction with 50k pages and a deliberately shortened debounce time.
=> fix: use atomic writes for data store file operations

.changeset/twelve-donuts-hide.md, packages/astro/src/runtime/server/render/util.ts
- Addresses [#12727](https://github.com/withastro/astro/issues/12727) by adding `inert` to `htmlBooleanAttributes`
No functional changes, just adding a missing boolean attribute to be handled in the correct manner.
Simply addresses a minor defect.
=> Add inert attribute to boolean list

packages/integrations/tailwind/test/fixtures/basic/tailwind.config.js
The tailwind test suite became unstable, this PR should help with that.
All CI should be green
N/A
=> test: make tailwind test more stable

.changeset/twenty-keys-divide.md, packages/astro/src/cli/check/index.ts
- Removes try/catch around `sync` in `astro check`
- Closes #12724
- Closes PLT-2709
Manually
=> fix(cli): let sync throw in check

.changeset/tame-spoons-shop.md, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/static-build.ts, packages/astro/test/astro-basic.test.js, packages/astro/test/fixtures/astro-basic/astro.config.mjs, packages/astro/test/sourcemap.test.js
- During cleanup be sure to remove any `.map` files created from server JavaScript output. Otherwise these are left in and expose server source code to the client.
- Added a new test to our basics fixture.
N/A, bug fix
=> Clean sourcemaps from static output

.changeset/soft-cows-buy.md, packages/astro/src/core/build/static-build.ts
- Logging added while working on bug but not removed!
- Want to get a patch out so users don't see this.
- N/A
- N/A
=> Remove debug logging from output

.changeset/curly-snakes-shave.md, packages/astro/client.d.ts
- Vite 6 added import queries to [explicitly control asset inlining behaviour](https://vite.dev/guide/assets.html#explicit-inline-handling)
- Vite [declares types](https://github.com/vitejs/vite/blob/ccd1a4c4145ee1069d7baea56981a0322e7be864/packages/vite/client.d.ts#L249-L262) for these, but we didn’t add them to Astro’s client types when updating to Vite 6
=> Adds types for `?url&inline` & `?url&no-inline` import queries

.changeset/loud-emus-look.md, .changeset/tame-spoons-shop.md, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/static-build.ts, packages/astro/test/astro-basic.test.js, packages/astro/test/experimental-content-collections-render.test.js, packages/astro/test/fixtures/astro-basic/astro.config.mjs, packages/astro/test/sourcemap.test.js
- Ensures `.map` files are removed that belong to the server code during the build.
- Ported from:
- https://github.com/withastro/astro/pull/12746
- https://github.com/withastro/astro/pull/12749
- Tests added
N/A, bug fix
=> Prevent server sourcemaps from being part of client output

packages/astro/src/types/public/config.ts
Fixes docs typos and punctuation in `packages/astro/src/types/public/config.ts`.
Docs fixes only.
Docs fixes only.
=> docs: fix typos/punctuation

.changeset/shaggy-dancers-run.md, packages/astro/src/content/content-layer.ts, packages/astro/src/content/utils.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/astro.config.mjs
Currently the content layer cache is invalidated if the content config or Astro version changes. However this causes problems if there are changes in the Astro config that also affect the stored data. This can include things like markdown settings, but potentially lots of other things.
The apporach this PR takes is to hash everything except integrations, adapters and vite config. It switches the digest function to use a safe stringify function in case the Astro config includes circular refs.
Closes #12761
Adds a test case
=> fix: clear the content layer cache when the Astro config changes

.changeset/wise-boxes-develop.md, packages/astro/src/actions/plugins.ts, packages/astro/src/actions/runtime/virtual/shared.ts, packages/astro/templates/actions.mjs, packages/astro/test/actions.test.js, packages/astro/test/fixtures/actions/src/pages/get-action-path.astro, packages/astro/types/actions.d.ts
- Adds a new `getActionPath()` helper
Adds a test case
Changeset and https://github.com/withastro/docs/pull/10353
=> feat(actions): getActionPath()

.changeset/poor-mangos-fold.md, packages/astro/package.json, packages/astro/src/core/session.ts, packages/astro/test/fixtures/sessions/package.json, pnpm-lock.yaml
Updates unstorage to `1.14.0`, which adds new drivers. It also now supports kebab-case driver names, so this also updates the code and changesets to use that
=> chore(deps): update unstorage and use new syntax

packages/astro/src/core/errors/errors-data.ts
Fixes the links in the custom errors to point to the correct docs
=> chore: fix links in session errors

.changeset/afraid-sloths-shake.md, packages/astro/src/content/content-layer.ts, packages/astro/src/content/loaders/glob.ts, packages/astro/src/content/runtime.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/content.config.ts
This makes a number of improvements to logging for content layer config errors: 
- warns if glob base dir doesn't exist
- warns if glob matches no files
- updates warning for empty collection to be more accurate in content layer era
- logs a warning if there's an error when loading content config
Fixes #12795
Added tests
=> fix: better logs for invalid content config

.changeset/six-pumpkins-act.md, packages/astro/e2e/fixtures/server-islands/src/components/MediaTypeInHeader.astro, packages/astro/e2e/fixtures/server-islands/src/pages/index.astro, packages/astro/e2e/server-islands.test.js, packages/astro/src/runtime/server/render/server-islands.ts
- This PR fixes an issue where the client-side script injected for server islands would fail if the content-type header was modified from an external source, for example a reverse proxy.
- Added a new server island to the server islands tests which sets a header with a media type. The test checks if the island gets inserted even with the media type present (`content-type: text/html;charset=utf-8`). Normal cases are automatically handled by the other server islands which do not set the header and instead have the default header (`content-type: text/html`)
No docs needed as this is a bug fix and doesn't change the default behavior.
=> Fix server island script breaking when charset is added to content-type

.changeset/hot-pumas-attack.md, packages/astro-rss/src/index.ts, packages/astro-rss/test/rss.test.js
This fixes an issue where the RSS XML file generated by `@astrojs/rss` is displayed in plaintext due to a faulty `Content-Type` header by reverting the https://github.com/withastro/astro/pull/12644 pull request.
For more information, you can view the https://github.com/withastro/astro/issues/12828 issue that I filed.
**Before** (current, `Content-Type` header is set to `application/rss+xml; charset=utf-8` since `astro@5.0.3`)
**After** (manually overriding the `Content-Type` header to `application/xml` which was the value used by `@astrojs/rss` before the PR change)
A reproducible example can be found here: https://codesandbox.io/p/devbox/kind-hugle-27v5l?on=codesandbox
Or, if you want to reproduce it yourself:
- Go to https://astro.new and find the **Blog** template
- Open the **Blog** …
=> fix(@astrojs/rss): revert incorrect Content-Type header applied for RSS XML file

.changeset/fluffy-ants-reflect.md, packages/astro/src/content/runtime.ts, packages/astro/test/fixtures/content-layer/src/content.config.ts
Currently the transform used in `reference()` is async. This was a change with content collections to allow the store to be loaded. However this caused an issue during JSON schema generation when combined with `default()`. See https://github.com/withastro/docs/pull/10362 where this reported as part of a docs PR.
This PR updates the transform to instead preload the store and then make the transform itself sync.
Updated fixture to use the `reference().default()` syntax that previously broke.
=> fix: make `reference()` a sync transform

.changeset/hot-baboons-own.md, packages/astro/src/core/session.ts, packages/astro/test/sessions.test.js
Ensures that session IDs get regenerated when `regenerate()` is called. This fixes #12863.
Built astro with this change locally and ran it against https://stackblitz.com/edit/github-muwk6ati-gxwf5xkb?file=src%2Fpages%2Findex.astro and it functions as expected (new uuid shown on every refresh).
Docs should not be needed - this aligns the code's functionality with the current docs.
=> fix: session regeneration

.changeset/heavy-lemons-tie.md, packages/astro/src/core/session.ts, packages/astro/test/units/sessions/astro-session.test.js
Currently we're not passing any options to cookie.delete() when destroying a session. This was meaning the cookie wasn't being properly deleted, because when created it passes some default options.
This PR ensures that the same options are passed to both create and delete the cookie.
This bug was reported in a comment on the RFC
=> fix: pass cookie options to delete

.changeset/khaki-tools-live.md, .changeset/silver-cars-confess.md, .changeset/spotty-timers-shake.md, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/core/logger/core.ts, packages/astro/src/core/server-islands/vite-plugin-server-islands.ts, packages/underscore-redirects/src/astro.ts
- Adds errors logs when Astro Islands are incorrectly used	
- Absence of an adapter
- Incorrect buld output
- Fixes the logs, where the output format was incorrect
- Adds a new parameter to `underscore-redirects` package. Since `config.output` isn't reliable anymore, I added a new field, so we can update the adapters to pass the correct value
I tested the logs locally. 
=> fix(core): add error log for server islands

.changeset/rotten-baboons-roll.md, packages/astro/src/content/runtime.ts, packages/astro/test/fixtures/legacy-content-collections/src/pages/collections.json.js, packages/astro/test/legacy-content-collections.test.js
When emulating legacy collections, entries have extra fields applied, such as `slug` and the render function. Currently `getCollection` filter functions are being passed the non-emulated version of the entry. This PR ensures that the entry is the same one that is returned from the collection.
Fixes #12873
Added a test case
=> fix: pass emulated entry to getCollection filter function

.changeset/red-schools-marry.md, packages/astro/src/core/build/generate.ts
Astro adds a log when a file isn't created when a `Response` has not body
=> fix: missing log

.changeset/sour-bananas-rule.md, packages/astro/src/core/util.ts
Myself and @HiDeoo found an issue in his starlight-blog, which I encountered when using the integration in the Biome website.
There are cases now where the resolved paths from rollup contain a query parameter in their `URL`. This breaks some cases, and this was one of them.
[We fixed a similar bug before ](https://github.com/withastro/astro/pull/12712).
I tested it with the project where I found the issue. It works now
N/A
=> fix: injected route entrypoint

.changeset/strange-carpets-drop.md, packages/astro/types/content.d.ts
The generated `astro:content` runtime includes a `render` function, which has types that are created using typegen. However these types are missing from the stub types used before the first sync. This PR adds a stub declaration.
Fixes #12837 
Tested a preview build. It's hard to test in the monorepo because it tends to find random `content.d.ts` files scattered throughout the repo.
=> fix: add render() to stub content type defs

.changeset/small-maps-give.md, packages/astro/src/core/routing/manifest/create.ts
The previous code would cause file names like `index.xml.ts` to be treated as index files, when they aren't (the file basename excluding the extension `.ts` is `index.xml`, and `index` should be the index file). To match index files only, match the entire first half of the basename when splitting by the last occurrence of the period/file extension delimiter.
Pedantically this might not be correct -- i.e. some file extensions actually span multiple delimiters, like `index.tar.gz`. But in that case it's not an index file as well, so I think this is fine.
Fixes #12675
This was tested with my website repository that I'm using …
=> fix: match index files only by using entire basename

.changeset/shiny-hornets-relate.md, packages/underscore-redirects/src/redirects.ts
- In #11271 I used the wrong type for `force` (copy paste ftw)
N/A
N/A
=> fix(underscore-redirects): force type

examples/toolbar-app/package.json, pnpm-lock.yaml
Adds `@types/node` to the toolbar app example, because it uses tsc
Fixes #12903
=> chore(examples): add node types dep

.changeset/metal-phones-cross.md, packages/astro/src/core/build/index.ts
- Fixes a regression from #12597
N/A
N/A
=> fix: pass server island route to astro:build:done routes

.changeset/great-hotels-reply.md, packages/astro/src/core/sync/index.ts, packages/astro/src/types/astro.ts
- Closes #12901
- We only generate a reference instead of the stub, which was overriding the generated types in rare cases
Should pass
N/A
=> fix: do not generate a stub for content types

.changeset/seven-feet-juggle.md, packages/astro/src/vite-plugin-astro/compile.ts, packages/astro/test/units/vite-plugin-astro/compile.test.js
I modified compileAstro to reflect the settings in viteConfig.esbuild.
This change ensures that when `vite.esbuild.target` is specified in the Astro config, it is reflected during the compilation of Astro files. Previously, while the `vite.build.target` value would affect the `build` command output of an Astro project, it did not impact the `dev` command output. As a result, the esbuild target was effectively fixed to `esnext`. This update addresses and resolves that issue.
For example, by setting the configuration as follows, you can specify the esbuild target during the compilation of Astro files.
```js
// astro.config.mjs
export default {
vite: {
esbuild: {
target: 'es2018',
},
},
};
```
Fixes: [The vite.build.target setting does not take effect in dev mode. · Issue …
=> fix: Reflect the configuration for esbuild

.changeset/old-clouds-act.md, packages/astro/test/content-collections-render.test.js, packages/astro/test/fixtures/ssr-api-route/src/pages/fail.js, packages/astro/test/ssr-api-route.test.js, packages/astro/test/units/dev/collections-renderentry.test.js, packages/integrations/mdx/src/rehype-images-to-component.ts, packages/integrations/mdx/test/css-head-mdx.test.js, packages/integrations/mdx/test/mdx-math.test.js
Currently the rehype plugin checks if `imagePaths` is defined when deciding whether to inject the `Image` import. However since Astro 5, `imagePaths` is always defined, so the import was always being injected. This PR changes it to check if the list is empty.
There's a separate issuue related to responsive images that makes this hard to test correctly right now. I'll add tests as part of that.
=> fix(mdx): don't import image component when no images are used

.changeset/afraid-peas-smash.md, packages/astro/src/core/app/index.ts, packages/astro/src/core/config/schema.ts, packages/astro/src/core/middleware/sequence.ts, packages/astro/src/core/render-context.ts, packages/astro/src/core/render/params-and-props.ts, packages/astro/src/vite-plugin-astro-server/base.ts, packages/astro/src/vite-plugin-astro-server/request.ts, packages/astro/test/fixtures/ssr-params/src/pages/[category].astro, packages/astro/test/fixtures/ssr-params/src/pages/東西/[group].astro, packages/astro/test/params.test.js
Closes PLT-2724
Closes https://github.com/withastro/astro/issues/12847
There are two issues:
- we decoded the pathname multiple times
- we didn't decode the pathname **early** in all the pipelines
I tracked down the issue and fixed, I also added some comments to help developers with the code.
Added a new test to cover the issue that we fixed
N/A
=> fix(routing): multiple decoding

.changeset/green-buses-add.md, packages/astro/components/Image.astro, packages/astro/components/Picture.astro, packages/astro/components/ResponsiveImage.astro, packages/astro/components/ResponsivePicture.astro, packages/astro/src/assets/vite-plugin-assets.ts, packages/astro/test/content-collections-render.test.js, packages/astro/test/core-image.test.js, packages/astro/test/ssr-assets.test.js, packages/integrations/markdoc/test/propagated-assets.test.js, packages/integrations/mdx/test/css-head-mdx.test.js, packages/integrations/mdx/test/fixtures/mdx-images/astro.config.ts, packages/integrations/mdx/test/fixtures/mdx-images/src/pages/content-collection.astro, packages/integrations/mdx/test/fixtures/mdx-images/src/pages/no-image.mdx, packages/integrations/mdx/test/mdx-images.test.js
Responsive images need to include global styles, and currently these are being included even if responsive images are not enabled. This PR adds wrapper components that just add the styles to the main component, and conditionally export these according to whether the flag is enabled. This is temporary until the feature is unflagged.
Alongside #12921, this fixes #12868
Adds tests to ensure the styles aren't added to sites without the flag enabled. There are existing tests that check that they _are_ added to pages that do have them enabled.
This also adds tests to the MDX integration that were needed for #12921 and are now possible. These check whether the styles are being applied to pages with no images.
=> fix: conditionally import image style

.changeset/heavy-yaks-brake.md, .changeset/tiny-plums-crash.md, packages/underscore-redirects/src/astro.ts, packages/underscore-redirects/test/astro.test.js
- Closes PLT-2732
- Updates the API to accept routes from `astro:routes:resolved` and assets from `astro:build:done`
- Doesn't use `config.output` as a fallback anymore
Updated, will need a preview release to test against the adapters repo
Undocumented, changeset
=> feat(underscore-redirects): update API to support new hook

.changeset/strong-scissors-sip.md, packages/astro/src/content/vite-plugin-content-virtual-mod.ts
This is another fix in the saga of data store race conditions. When we changed the dev fs watcher to not start watching the data store file until after the content layer sync was complete, it was meanign that in some scenarios, newly-created data store files were not triggering a module reload. This PR adds a manual module invalidation at the same time as adding the file to the watcher.
Fixes #12866
This can't be reproduced when using pnpm (for some unclear reason), but I have manually tested it with the #12866 repro, using npm.
=> fix: invalidate data store module when dev server starts

.changeset/sweet-zoos-move.md, .changeset/tame-pianos-approve.md, packages/astro/src/core/render-context.ts, packages/astro/src/core/request.ts, packages/astro/src/core/routing/rewrite.ts
Closes https://github.com/withastro/astro/issues/12931
Closes PLT-2736
The issue was that doing `oldRequest.headers` during a rewrite was causing the warning to fire, because it triggers the `.get` method. 
This is fixed now by checking the `isPrerendered` flag.
Also, I updated the method `copyRequest` to use the internal method `copyRequest`, which creates the `headers` object based on `isPrenredererd`. This should fix cases (not caught, probably) where users could have used `Request.headers` during a rewrite.
I tested it locally using the reproduction provided. 
N/A
=> fix(routing): don't trigger get of headers

.changeset/light-buttons-compare.md, packages/astro/src/assets/build/generate.ts, packages/astro/src/assets/build/remote.ts, packages/astro/test/core-image.test.js
Store remote images in the cache as a standalone file instead of encoding the file as base64 inside of a json file. 
* This improves the storage size of the image cache, as well as decreasing the performance overhead involved in encoding, decoding, reading and writing the base64 blob to a json file. 
Automatically upgrade remote cached images to the new format.
* I've added some extra code to decode images in the old format and write them in the new format. This is optional - removing this section will cause the images to be re-downloaded instead of converted.
Ran `pnpm run test:match "image"`
Updated the 'has cache entries' test in `core-image.test.js` as the change caused it to fail. 
The test assumes that `.webp.json` and `.webp` files would each result in an output image, however …
=> feat(assets): Store remote cached images in binary format

.changeset/twelve-cobras-shake.md, packages/integrations/markdoc/components/Renderer.astro, packages/integrations/markdoc/components/TreeNode.ts, packages/integrations/markdoc/test/fixtures/render-with-components/src/content/blog/with-components.mdoc, packages/integrations/markdoc/test/fixtures/render-with-extends-components/src/content/blog/with-components.mdoc, packages/integrations/markdoc/test/render-components.test.js, packages/integrations/markdoc/test/render-extends-components.test.js, packages/integrations/markdoc/test/syntax-highlighting.test.js
Fix https://github.com/withastro/astro/issues/11656
The core of the issue is that sometimes Markdoc AST may return arrays within arrays (in `node.children`), e.g. in if tags, content within the if tag are grouped as an array. This PR handles that and refactors the rendering code slightly.
Added tests
n/a. bug fix
=> Fix markdoc render code block in if tag

examples/starlog/src/components/BaseHead.astro
The Starlog example was missing a `viewport` meta tag, which was causing issues on mobile devices (media queries not working properly):
Adding a default one fixes the issue:
Note: I haven't included achangeset as it was said they're not needed for examples.
By emulating mobile device on Chrome (Toggle device  toolbar in dev tools) and on a personal website 🙂 
No tests added as this is an example template.
No updates or changes required - it affects only Starlog example users on mobile devices.
=> fix(examples): add Starlog example viewport meta tag

.changeset/purple-pillows-lay.md, packages/astro/src/content/content-layer.ts, packages/astro/src/content/mutable-data-store.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/dev/container.ts, packages/astro/src/core/dev/dev.ts, packages/astro/src/core/sync/index.ts, packages/astro/test/astro-mode.test.js, packages/astro/test/fixtures/content-layer/src/pages/missing.astro
The content layer data store is created in a different location according to whether it is running in dev or build, so that it is either cachable or watchable by the fs watcher. These are mutually exclusive for Reasons. 
This needs to be the same locaiton for both writing (during sync) and reading (during runtime). Unfortunately knowing which of these we're running is not as simple as it could be, and there have been some bugs that have emerged due to conflicts. 
We'd mostly fixed these cases in #12640, but it missed the case where dev was run programatically with NODE_ENV set to something other than development (mostly in a test environment). 
Rather than playing whackamole for all of these scenarios, this PR changes the approach so that it never uses NODE_ENV, and always explicitly sets …
=> fix: explicitly set dev mode for data store

.changeset/sweet-turtles-flash.md, packages/integrations/react/server.js
fix https://github.com/withastro/astro/issues/12766
cherry pick of https://github.com/withastro/astro/pull/12686
n/a. We can't test react 19 yet without https://github.com/withastro/astro/pull/12686 (which has other issues). But I tested the repro manually which works with this.
n/a.
=> Support checking react 19 components

.changeset/four-kangaroos-develop.md, packages/astro/astro-jsx.d.ts
I missed the "blocking" attribute of the `<link>` element.
Added it. Came across missing "disabled" attribute. Added that, too.
Started sorting, but did not complete, because I haven't found "charset" at MDN.
n/a
n/a
Improvements of the changeset are welcome as always.
=> Adds "blocking" and "disabled" attributes to the TypeScript definition of the HTML link element

.changeset/calm-tips-think.md, packages/integrations/mdx/src/server.ts
close https://github.com/withastro/astro/issues/12958
close https://github.com/withastro/astro/issues/12951
Probably easier to revert for now but we could implement in a different fix for the original issue later on: https://github.com/withastro/astro/issues/12802
n/a
n/a
=> Revert "Make MDX integration check noop (#12913)"

.changeset/happy-radios-drive.md, packages/upgrade/src/actions/install.ts, packages/upgrade/src/messages.ts, packages/upgrade/test/install.test.js
- Updated the upgrade messaging to show both current and target versions
- Added arrow symbol (→) to visually represent the version change
Before:
```bash
@astrojs/tailwind can be updated to v5.1.3
```
After:
```bash
@astrojs/tailwind can be updated v4.0.0 → v5.1.3
```
Updated existing test suite by modifying test assertions to verify new message format
Should be self-explanatory
Coming from https://github.com/withastro/roadmap/discussions/1069
=> Version transitions in CLI outputs

.changeset/light-meals-press.md, packages/astro/src/content/mutable-data-store.ts
When data has changed in the content layer, the data store needs to write several different files, including the data store itself, asset imports (e.g. images) and module imports (e.g. mdx). These are all in the module graph, so will trigger HMR if changed. #12751 reported that when editing MDX it would reload twice, and the second time would take a long time for large sites. The double reload was because there was initially HMR from the changed MDX module itself. The slow second reload was because it was writing the big imports file itself too, causing Vite to re-parse the whole big graph. This isn't needed, because the imports file itself hasn't changed, just the file it was referring to.
This PR changes the write function to first check the old file content before writing, and skip if …
=> fix: check if content layer files have changed before writing

packages/integrations/mdx/test/fixtures/mdx-plus-react/src/pages/inline-component.mdx, packages/integrations/mdx/test/mdx-plus-react.test.js
Add test for https://github.com/withastro/astro/pull/12959. I couldn't figure out a fix for the react hook error at the meantime so I'm adding the test only for now.
This adds tests
n/a
=> Add inline mdx component test

.changeset/tiny-papayas-develop.md, packages/astro/src/content/loaders/glob.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/content/space/exomars.md, packages/astro/test/fixtures/content-layer/src/pages/collections.json.js, packages/astro/test/fixtures/content-layer/src/pages/spacecraft/index.astro
While the glob loader handles deleting or renaming a file, it didn't previously handle the scenario where a slug was changed inside a file. This PR ensures that the old entry is deleted.
Fixes #12668
Adds new test cases
=> fix: delete old entry when frontmatter slug changed

.changeset/happy-pianos-report.md, packages/astro/src/core/render-context.ts, packages/astro/test/fixtures/i18n-routing-fallback/src/pages/index.astro, packages/astro/test/i18n-routing.test.js
- This will fix the issue with Astro.currentLocale not working correctly in SSR. See issue #12838 
Adds similar logic to `computeCurrentLocale` as was used in #12709  to handle SSR manifests with fallback routes. 
Welcome feedback from a maintainer on whether there may be a more elegant solution to solve both of these - I dont have enough background on the decision process behind having such different manifests and i18n implementation between dev/SSR/SSG.
Just corrects a bug and inconsistent behavior across modes. No new docs needed.
=> Fix i18n current locale

packages/astro-rss/CHANGELOG.md, packages/astro/CHANGELOG.md, packages/astro/client.d.ts, packages/astro/e2e/fixtures/actions-blog/src/styles/global.css, packages/astro/e2e/fixtures/actions-react-19/src/styles/global.css, packages/astro/src/actions/runtime/virtual/server.ts, packages/astro/src/assets/build/generate.ts, packages/astro/src/assets/build/remote.ts, packages/astro/src/core/routing/manifest/create.ts, packages/astro/test/core-image-svg.test.js, packages/astro/test/fixtures/middleware-full-ssr/src/error.js, packages/astro/test/fixtures/rewrite-runtime-error-custom500/package.json, packages/astro/test/fixtures/rewrite-runtime-error/package.json, packages/create-astro/CHANGELOG.md, packages/db/CHANGELOG.md, packages/db/src/core/cli/commands/shell/index.ts, packages/db/src/core/integration/vite-plugin-db.ts, packages/db/src/runtime/db-client.ts, packages/integrations/mdx/CHANGELOG.md, packages/integrations/mdx/src/README.md, packages/integrations/preact/CHANGELOG.md, packages/integrations/react/CHANGELOG.md, packages/integrations/sitemap/test/config.test.js, packages/integrations/solid/CHANGELOG.md, packages/markdown/remark/CHANGELOG.md, packages/markdown/remark/test/shiki.test.js
Found few more misspellings.
Continuation of #10923
=> fix: correct more typos

.changeset/brown-flies-repeat.md, .changeset/curvy-pans-share.md, .changeset/smart-ties-hear.md, packages/integrations/react/src/index.ts, packages/integrations/solid/src/index.ts, packages/integrations/vue/src/index.ts
fix https://github.com/withastro/astro/issues/12896
ref https://github.com/withastro/astro/pull/12735 (revert)
- React: `@vitejs/plugin-react` will add `optimizeDeps.include` [themselves](https://github.com/vitejs/vite-plugin-react/blob/ab12dfafbab3260bfd4904d85375ea2c02c36afe/packages/plugin-react/src/index.ts#L274-L296)
- Vue: Added a comment of why we manually add `vue` to `optimizeDeps.include`
- Solid: Different issue, but I noticed that we don't optimize `@astrojs/solid-js/client.js` by default like how the other integrations do.
I didn't do this for Preact as we're still pinning to an older version, but once we can update to the latest (tracked https://github.com/withastro/astro/issues/12805), we can also do the same here for it.
n/a. bug fix.
=> Remove custom optimizeDeps.include in react integration

.changeset/bright-toes-wink.md, packages/astro/src/core/server-islands/endpoint.ts, packages/astro/src/runtime/server/render/server-islands.ts, packages/astro/test/fixtures/server-islands/ssr/src/components/ComponentWithProps.astro, packages/astro/test/fixtures/server-islands/ssr/src/pages/includeComponentWithProps.astro, packages/astro/test/server-islands.test.js
This change removes the encryption of `{}` in the case of a server island with no props. Fixes #12949.
Added two tests: one test that ensures components with props keep getting them re-encrypted, and one where components without props don't have an empty encryption passed through to them.
Nominally a bugfix, brings the docs mention of caching in line with reality.
=> Remove encryption of empty props to allow server island cacheability

.changeset/nasty-pandas-unite.md, packages/integrations/markdoc/components/TreeNode.ts, packages/integrations/markdoc/test/fixtures/render-null/markdoc.config.mjs, packages/integrations/markdoc/test/fixtures/render-null/src/components/DivWrapper.astro, packages/integrations/markdoc/test/fixtures/render-null/src/content/blog/render-null.mdoc, packages/integrations/markdoc/test/render.test.js
fix https://github.com/withastro/astro/issues/12964
It seems like `renderTreeNodeToFactoryResult` shouldn't be calling itself, but it should re-create the `ComponentNode` entirely as it handles nested component rendering. Same as how the `const slots` are constructed below the updated code.
n/a. bug fix
=> Fix component render in markdoc when `nodes.document.render` is `null`

.changeset/kind-horses-smile.md, .changeset/large-cherries-explain.md, packages/astro/src/content/content-layer.ts, packages/astro/src/content/loaders/file.ts, packages/astro/src/content/loaders/glob.ts, packages/astro/src/content/server-listeners.ts, packages/astro/src/content/types-generator.ts, packages/astro/src/content/watcher.ts, packages/astro/src/core/dev/container.ts, packages/astro/src/core/dev/restart.ts, packages/astro/src/core/sync/index.ts, packages/astro/test/content-layer.test.js, packages/markdown/remark/src/import-plugin-default.ts
This PR makes a number of changes to the way that file watchers work in dev with the content layer. There have been a few bugs related to the way that dev server restarts are handled, which were due to the way we were handling file watchers.
When the Astro config is edited, it restarts the dev container to ensure the site is using the latest config. This was causing several bugs: 
- when the server was restarted, it wasn't re-running the Astro sync. This meant that updates in the config were not reflected in the rendered config, for example changes to Markdown config wouldn't update the rendered content.
- the existing watcher was destroyed, but because the loaders weren't being re-run, the glob and file event listeners weren't being attached to the new watcher.
This PR correctly passes …
=> fix: better handling of resync and restarts in content layer

.changeset/heavy-fireants-melt.md, packages/astro/src/content/runtime.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/content.config.ts, packages/astro/test/fixtures/content-layer/src/data/cats.json
Currently we attempt to validate references in schemas by checking the referenced entry exists. This causes a problem if a new referenced entry is added at the same time as the reference is added, because there can be a race condition where the referenced entry has not yet been added to the store when the reference is validated. 
This PR removes that check. This is OK (and we already skip validation if the collection doesn't exist yet) because we also validate at runtime.
Fixes #12680
Fixes #12885
Adds a test
=> fix: defer validation of reference entries

.changeset/real-hairs-scream.md, packages/astro/src/actions/integration.ts
- Currently, we resolve the actions config to `${srcDir}/actions`. That means `src/actions.ts` is valid, just like `src/actions/index.ts`. However, typegen was harcoding `${srcDir}/actions/index.ts`. This PR updates the types to let TS figure out what file to resolve
Should still pass
N/A
=> fix: actions codegen types

.changeset/many-pianos-develop.md, packages/integrations/react/src/index.ts, packages/integrations/react/src/version.ts
Helps with #12824 (not complete fix yet, needs to check cloudflare adapter support)
Removes the `ssr.external` config as it's forcing them to be externalized even in builds for cloudflare where all dependencies should be bundled by default. (This is a similar change to https://github.com/withastro/astro/pull/10601)
n/a. bug fix.
=> Remove react integration ssr.external config

.changeset/large-dodos-bake.md, packages/astro/src/core/util.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/raw-content.json.js, packages/astro/test/fixtures/astro-markdown/src/pages/raw-content.txt.js
The fix in #12711 caused a regression for imports for markdown files as static assets using the `?raw` param. That only worked accidentally before, but this is the proper fix.
I am just checking the id for `?raw`. I realise this could in theory miss cases where there are multiple params, but I'm not aware of any cases where that would be legitimate so didn't think it was worth the cost of adding a full query param parse on every import. I'm open to other opinions on this though.
Fixes #13025
Added a test case
=> fix: allow imports of Markdown files as raw text

.changeset/fifty-socks-end.md, packages/astro/src/runtime/server/render/server-islands.ts, packages/astro/test/fixtures/server-islands/ssr/src/pages/empty-props.astro, packages/astro/test/fixtures/server-islands/ssr/src/pages/index.astro, packages/astro/test/server-islands.test.js
=> Revert "Revert "feat(server-islands): only encode ETAGO delimiter (#11513)""

.prettierignore, biome.jsonc, package.json, packages/astro/astro-jsx.d.ts, packages/astro/client.d.ts, pnpm-lock.yaml
Prettier was still formatting `biome.jsonc` file. `.jsonc` files are now ignored and correctly formatted by Biome.
I updated `biome` to the latest and run `format:code`
N/A
=> chore: ignore jsonc files

packages/astro/client.d.ts, packages/astro/src/core/config/schema.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/manifest/virtual-module.ts, packages/astro/src/types/public/config.ts, packages/astro/src/types/public/index.ts, packages/astro/src/types/public/manifest.ts, packages/astro/test/fixtures/astro-manifest/astro.config.mjs, packages/astro/test/fixtures/astro-manifest/package.json, packages/astro/test/fixtures/astro-manifest/src/pages/client.astro, packages/astro/test/fixtures/astro-manifest/src/pages/index.astro, packages/astro/test/fixtures/astro-manifest/src/pages/server.astro, packages/astro/test/serializeManifest.test.js, pnpm-lock.yaml
This PR a first round of implementation of the Stage 2 RFC https://github.com/withastro/roadmap/issues/1099
The PR **isn't** against `main` and it's meant to test the waters.
> [!IMPORTANT]
> Let's **not focus on the naming** of the virtual module, we will use the RFC Stage 3 for that. Focus on the technical implementation and the "expected usage" of the module, and see the information that we want to export from each module make sense
This PR will set the ground work for the Stage 3 RFC
Added new tests
Not at this stage
=> chore: first implementation for serialized config

.changeset/tall-bears-return.md, packages/integrations/alpinejs/src/index.ts
Related to issue https://github.com/withastro/astro/issues/12710#issuecomment-2596129872.
Externally loaded AlpineJS component scripts were loaded after `Alpine.start()` was triggered. Issue started with Astro V5.
- Runs `Alpine.start()` on the `DOMContentLoaded` event. According to MDN documentation (https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event), `DOMContentLoaded` fires immediately after HTML and deferred scripts are loaded. In short, this change guarantees that `Alpine.start()` is only called after all scripts are loaded.
- This is a bugfix and integrations do not appear to have tests.
- No documentation updates necessary; resolving a bug.
=> fix(alpinejs): start on DOMContentLoaded

examples/blog/src/components/BaseHead.astro
This PR fixes #13041 
- It edits only one file, `BaseHead.astro`, in [the Astro blog starter kit](https://github.com/withastro/astro/tree/main/examples/blog). It adds three new lines to that file.
- It adds a rel link to the (already-existing) `/sitemap-index.xml` file created by @astrojs/sitemap
- It adds a rel link to the (already-existing) `/rss.xml` file created by @astrojs/rss
- The link to the RSS feed file needs the global `SITE_TITLE`, so I added a line to the frontmatter to import that.
I created a personal blog using the Astro blog starter kit and noticed that these rel links were missing, so I added them. It worked.
No additional documentation is required because of this PR. In fact, I got most of the code for this PR from existing Astro documentation:
- [the documentation for …
=> Add rel links to sitemap and rss feed in blog starter kit

.changeset/seven-avocados-confess.md, packages/astro/src/i18n/index.ts, packages/astro/test/units/i18n/astro_i18n.test.js
fixes #13035 
`getLocaleRelativeUrl` will now return a '/' instead of an empty string in the case of `base: '/'` and `trailingSlash: 'never'`.
Changing this behavior of `getLocalRelativeUrl` caused a similar error in `getLocaleAbsoluteUrl` for `trailingSlash: 'never'` because it internaly uses `getLocaleRelativeUrl`. This is resolved similarly. 
Added tests for both cases - the logic for testing `base: '/'` had only been testing when `trailingSlash:'always'`.
=> Fix get relative locale

.changeset/clean-suns-shout.md, packages/astro/client.d.ts
#13029 seems to have introduced a syntax error in an import. This fixes it and adds a biome ignore
Fixes #13057
=> fix: correct broken import formatting

.github/workflows/issue-labeled.yml
Adds a new action when the `wontfix` label is applied which leaves a comment and closes the issue as "not planned"
=> chore: adds wontfix label action

packages/astro/test/serializeManifest.test.js
Part of https://github.com/withastro/roadmap/pull/1106
This PR adds more tests to cover SSG and SSR
Adds more tests. CI should stay green
N/A
=> chore: add tests to cover `astro:config` cases

.changeset/light-pants-smoke.md, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/core/redirects/render.ts, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/types/public/config.ts, packages/astro/test/redirects.test.js, packages/underscore-redirects/src/astro.ts
Closes PLT-2745
This PR adds support for external directs in the `redirects` configuration:
- Added a new error in case the user specify a URL that doesn't start with `http://` or `https://` or the URL isn't parsable
- No special handling for patterns. Astro can't know if the external an Astro site, so it's virtually impossible to handle route patterns e.g. `[...slug]`, `[slug]`
- No particular handling inside `underscore-redirects` (apart from tiny refactors)
Added new tests
https://github.com/withastro/docs/pull/10704
=> feat(routing): external redirects

packages/astro/src/types/public/config.ts
**For `5.2`** :
Since `@astrojs/tailwind` is deprecated and we recommend to remove the integration in favor of the Vite plugin, I think we should update the example in the [Configuration reference](https://docs.astro.build/en/reference/configuration-reference/#integrations) to replace `@astrojs/tailwind` with another integration (I chose MDX but I can change).
I didn't add a changeset because I don't think it's necessary (if merged in time 😄). This is somehow part of #13049.
N/A
This is docs, just a small change but in case we prefer another example:
=> docs: update the JSDoc of `integrations` to replace Tailwind integration

.changeset/large-waves-cheat.md, packages/astro/src/vite-plugin-astro-server/trailing-slash.ts, packages/astro/test/fixtures/astro-dev-headers/astro.config.mjs, packages/astro/test/ssr-error-pages.test.js
Skips internal Vite requests when checking trailing slashes
Fixes #13094
Adding tests now
=> fix: exclude Vite requests from trailing slash handling

.changeset/green-sloths-switch.md, packages/astro/src/cli/add/index.ts
Special-cases tailwind to ensure it doesn't install the integration package, which is deprecated. Previously it was always installing the integration package, even though it was also always added to the dependencies list. This changes it to only install the listed deps. It also adds an `integrationName` field, because in logs it was confusing having it log `@astrojs/tailwind` when that package wasn't actually installed.
Fixes #13097 
There are currently no tests for `atro add`. It's a tough one to test without some kind of mocking for the package manager, so I'll leave it for now, beacuse this bug is affecting lots of users.
=> fix: exclude tailwind package when installing integration

.changeset/silent-worms-whisper.md, packages/astro/src/core/render-context.ts, packages/astro/src/core/routing/match.ts, packages/astro/src/core/server-islands/endpoint.ts, packages/astro/src/i18n/index.ts, packages/astro/src/i18n/middleware.ts, packages/astro/test/fixtures/i18n-server-island/astro.config.mjs, packages/astro/test/fixtures/i18n-server-island/package.json, packages/astro/test/fixtures/i18n-server-island/src/components/Island.astro, packages/astro/test/fixtures/i18n-server-island/src/pages/en/island.astro, packages/astro/test/fixtures/i18n-server-island/src/pages/index.astro, packages/astro/test/i18n-routing.test.js, pnpm-lock.yaml
Closes #12817 
The i18n middleware now checks if the request is coming from a server island, and if so, it doesn't handle it.
Also did a minor refactor to move some utility functions in the proper file.
I added a new test with a new fixture to not tarnish the existing ones. I also tested it locally using OP reproduction. It now serves the island correctly.
N/A
=> fix(i18n): server island request

.changeset/afraid-kangaroos-hope.md, .changeset/pink-apes-invite.md, packages/astro/src/vite-plugin-astro-server/trailing-slash.ts, packages/astro/test/dev-routing.test.js, packages/astro/test/ssr-trailing-slash.test.js, packages/internal-helpers/src/path.ts, pnpm-lock.yaml
Multiple trailing slashes are supposed to be collapsed before applying trailing slash rules. However a regex mistake meant that it was also matching duplicate slashes that weren't trailing. This would have been a minor problem, except that in dev is was incorrectly matching against the full URL including query params, not just the path. This meant that duplicate slashes were collapsed in query params too, which is a problem when you might have `https://`.
This PR fixes both issues: corrects the traailing slash helper to only match trailing slashes, and ensures that the dev matching is applied to the pathname without query params
Adds a lot of tests for both dev and SSR to cover these.
Fixes #13127
=> fix: correct handling of collapsing slashes

.changeset/purple-suits-matter.md, packages/astro/src/core/routing/manifest/create.ts, packages/astro/test/units/routing/trailing-slash.test.js
#13111 removed special handling for endpoint trailing slashes, because they broke trailignSlash=always. However this caused a regression for endpoints that include a file extension. This PR changes the handling for endpoints that include a file extension, to always use `trailingSlash: "ignore"`. This means it will match with and without the extension. I've done it liek this rather than setting to `never`, because that would be a breakign change. Currently _file-based_ endpoints do obey trailing slash rules, even with file extensions. This is probably a mistake (who wants `/sitemap.xml/`), but some may rely on it so we'll move any change to Astro 6.
Fixes #13128
Adds tests
=> fix: ignore trailing slash for endpoints with file extensions

.changeset/lazy-readers-change.md, packages/astro/src/core/render-context.ts, packages/astro/src/core/routing/match.ts, packages/astro/src/i18n/middleware.ts, packages/astro/test/fixtures/redirects-i18n/astro.config.mjs, packages/astro/test/fixtures/redirects-i18n/package.json, packages/astro/test/redirects.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/13120
The fix is inside `RenderContext`, and now check if the route that we are about to render is an external redirect. If it is, we skip the whole middleware chain, and render the redirect straight away.
I checked with Matt and Florian, and they agree with the proposed solution. 
I added a new test and fixture based on the reproduction provided.
N/A
=> fix(routing): skip middleware for external redirects

.changeset/spotty-maps-sneeze.md, packages/astro/src/cli/add/index.ts, packages/astro/src/core/messages.ts
Making it more clear that a user action is required after onboarding to tailwind v4.
twitter thread: https://x.com/Hacksore/status/1885490439437857143
built locally and ran `node astro.js add tailwind` in the `packages/astro` dir.
N/A
=> Tailwind v4 onboarding enhancements

.github/workflows/snapshot-release.yml
Currently if the snapshot release fails it doesn't log anything, beacuse we redirect the output so we can include it in the comment. This PR changes it to use tee so that it logs it as well. It also uses the captured output to comment with an error if it fails
lol it's a GH action. Nobody knows how to test those
=> chore: print snapshot release error output

.changeset/mean-icons-applaud.md, packages/astro/src/core/errors/errors-data.ts
Fixes a typo inside the error message
N/A
=> fix: error message text

.github/workflows/preview-release.yml
This PR revamps the pkg.pr.new that we had disabled.
Changes:
- triggers the job only on `labeled` event
- uses `changeset status` to retrieve the upcoming releases
- uses a script to parse the JSON emitted by the previous step, and return a list of packages that have changesets. It returns a string
- if the previous string is empty, we write a message in the PR saying that no preview release was published
- if the previous string isn't empty, it's passed to the pkg pr new CLI
I tested the script locally.
This PR needs to be merged, I will enable the job again, and then open a PR to test it.
N/A
=> ci: preview release via pkg.pr.new for current packages

.github/workflows/preview-release.yml
This PR updates the pkg.pr.new to use the same workflow steps used by the previous workflow to "trick" changesets to use the correct ref.
I copied the same code. IT should work. We should merge the PR and trigger another the workflow again.
N/A
=> ci: trick changesets to use the correct ref

.changeset/cool-parents-love.md, packages/integrations/vercel/package.json, pnpm-lock.yaml
`@vercel/routing-utils` was pinned because of [a bug in the new version of the library](https://github.com/vercel/vercel/issues/13024). This has now been fixed, so this unpins it.
=> chore: unpin vercel routing lib

.changeset/thick-crabs-juggle.md, packages/astro/src/core/render/paginate.ts, packages/astro/src/types/public/common.ts
Resolves this issue #13196 
The paginate function allows for readonly arrays.
Just types were changed.
Just types were added
=> Fix:changes the paginate function to allow readonly array types

.github/workflows/preview-release.yml
As for now, I want to hardcode the packages. We can iterate about filter once we have pkg.pr.new working.
Merge and trigger it
N/A
=> ci: hardcode packages to publish of release

packages/astro/test/sessions.test.js
A test is failing because it asserted a message that we recently changed
Test should pass (checked locally, it passed)
N/A
=> test: update test assertion after error rename

benchmark/package.json, packages/astro/e2e/fixtures/actions-blog/package.json, packages/astro/e2e/fixtures/actions-react-19/package.json, packages/astro/e2e/fixtures/i18n/package.json, packages/astro/e2e/fixtures/server-islands-key/package.json, packages/astro/e2e/fixtures/server-islands/package.json, packages/astro/e2e/fixtures/view-transitions/package.json, packages/astro/test/fixtures/client-address-node/package.json, packages/astro/test/fixtures/custom-assets-name/package.json, packages/astro/test/fixtures/ssr-api-route/package.json, packages/astro/test/fixtures/static-build-ssr/package.json, packages/db/test/fixtures/ticketing-example/package.json, packages/integrations/sitemap/package.json, packages/integrations/web-vitals/test/fixtures/basics/package.json, pnpm-lock.yaml
This PR changes our monorepo to use the workspace version of the Node.js adapter.
I changed all packages, exception for the examples.
CI should pass
N/A
=> chore: use workspace Node.js adapter

.changeset/gentle-rings-confess.md, packages/integrations/cloudflare/src/entrypoints/image-service.ts
- Adds `onerror=redirect` to Cloudflare image transform params. This will allow images to continue to work after hitting Cloudflare's free limit. ([docs]( https://developers.cloudflare.com/images/transform-images/transform-via-url/#onerror))
I am not positive how this impacts sites that don't have the image service set up at all, since it might then load the original image as opposed to just erroring and loading nothing as it does now. If it still applies when the image service is disabled entirely, and shows the underlying image, it could cause some confusion with users not realizing the service isn't turned on.
None. It's a hardcoded value, and I more want to introduce the idea to see if this should be a configurable value, or just always applied.
This might be worth mentioning in the …
=> feat(cloudflare): Includes onerror passthrough

packages/astro/src/assets/fonts/providers/local.ts, packages/astro/src/assets/fonts/utils.ts, packages/astro/src/assets/fonts/vite-plugin-fonts.ts, packages/astro/test/units/assets/fonts/providers.test.js, packages/astro/test/units/assets/fonts/utils.test.js
- Simplifies code for url proxying and local font provider
- Introduces a way to refresh local fonts in development
- Local fonts hash is now computed based on the name and the file contents (RFC to be updated after this PR is merged)
Adds tests
N/A
=> feat(fonts): better local provider

.github/workflows/preview-release.yml
It seems that the issue was the fact that `if: ` was using a `|`. I removed the `|` but having a `:` inside the `pr: preview` label name was causing some parsing issue in the YAML file.
Solution? Remove the `:` from the label name
Merge and trigger it 
N/A
=> ci: remove colon from label

.changeset/fluffy-crabs-sneeze.md, packages/integrations/cloudflare/package.json, packages/integrations/vercel/package.json, pnpm-lock.yaml
This PR fixes an issue that was lurking around our adapters, where we forgot to update their workspace dependencies.
The CI should pass
N/A
=> fix: update deps of adapters

.changeset/late-mails-beam.md, packages/db/src/runtime/virtual.ts, packages/db/virtual.d.ts
Expose `ilike` function from drizzle-orm in astro:db runtime.
Fixes #13308 
Tested by modifying astro built-in example (not pushed of course), no tests added.
N/A, self documented via Typescript.
=> Expose ilike function from drizzle-orm

.changeset/clever-rice-compete.md, packages/astro/components/Image.astro, packages/astro/components/Picture.astro, packages/astro/src/assets/internal.ts, packages/astro/src/assets/utils/imageAttributes.ts
- Currently, `experimental.responsiveImages` only adds CSS variables to images included via the `<Image />` or `<Picture />` components.
- In my other PR #13254, we can only use `getImage` to transform images.
- I would like to have `getImage` participate more fully in the responsive images experiment.
- Moving the CSS variable logic inside `getImage` removes a lot of redundant/confusing logic anyways.
I tested this change by running my personal blog with it on. It provides a better outcome than when `getImage` is used on its own with this experiment turned on:
<table>
<thead>
<tr><th>Before</th><th>After</th></tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
Note: the before pic has `width: 100%` applied to it in page styles. Without that, it looks even worse (no …
=> feat: Add CSS variables in getImage for experimental.responsiveImages

.changeset/purple-jokes-pay.md, packages/astro/e2e/fixtures/view-transitions/src/pages/form-one.astro, packages/astro/src/transitions/router.ts
When a form contains an input field named attributes, this shadows the access to the form.attributes property.
Changed property access to get the real thing.
Closes #13307 
extended exiting form-one.astro
n.a., bugfix
=> fixes property shadowing for form.attributes

.changeset/flat-ladybugs-argue.md, package.json, packages/astro/package.json, packages/integrations/cloudflare/package.json, packages/integrations/markdoc/package.json, packages/integrations/netlify/package.json, packages/integrations/preact/package.json, packages/integrations/react/package.json, packages/integrations/solid/package.json, packages/integrations/svelte/package.json, packages/integrations/tailwind/src/index.ts, packages/integrations/vercel/package.json, packages/integrations/vue/package.json, pnpm-lock.yaml, scripts/package.json
Closes https://github.com/withastro/astro/issues/13322
This PR updates various packages to use the latest of, `vite` and `esbuild`, which are affected by the recent security advisory of `esbuild`
CI should pass
N/A
=> chore(deps): update `esbuild` and `vite` versions

.changeset/three-eyes-listen.md, .changeset/wet-frogs-visit.md, packages/astro/package.json, pnpm-lock.yaml
I was supposed to merge https://github.com/withastro/astro/pull/13202/, but it has too many changes, so I decided to just port the two changesets before the release.
This PR only updates `@astrojs/compiler` dependency, and it bumps `@astrojs/update` to a minor. 
CI should pass
N/A
=> chore: bump `compiler` and `upgrade` packages

.changeset/slimy-bulldogs-sell.md, packages/astro/src/core/session.ts, packages/astro/src/types/public/extendables.ts, packages/astro/test/types/session-data.ts, packages/astro/test/types/session-env.d.ts
Adds support for typing experimental session data. This works similarly to typing of Astro.locals, using `src/env.d.ts` to define ambient types that extend `App.SessionData`. For example:
```ts
declare namespace App {
interface SessionData {
user: {
id: string;
email: string;
};
lastLogin: Date;
}
}
```
Any keys not defined in this interface will be treated as `any`.
Then when you access `Astro.session` in your components, any defined keys will be typed correctly:
```astro
---
const user = await Astro.session.get('user');
//    ^? const: user: { id: string; email: string; } | undefined
const something = await Astro.session.get('something');
//    ^? const: something: any
Astro.session.set('user', 1);
//    ^? Argument of type 'number' is not assignable to parameter of type '{ id: string; …
```
=> feat: add support session typing

.changeset/fuzzy-planes-collect.md, packages/astro/src/content/runtime.ts, packages/astro/test/content-layer.test.js, packages/astro/test/fixtures/content-layer/src/content/space/lunar-module.md
In Markdown, the generated attributes in img elements were not being correctly esacaped. This meant that including `>` or `"` in the img alt would break the tag. This isn't a security issue because Markdown is trusted, and you can add an actual script tag if you want.
Fixes #13345
Added test case
=> fix: escape img attributes in Markdown

.changeset/forty-houses-taste.md, packages/astro/e2e/fixtures/view-transitions/src/pages/eight.astro, packages/astro/e2e/fixtures/view-transitions/src/pages/one.astro, packages/astro/e2e/fixtures/view-transitions/src/pages/page1-with-scripts.astro, packages/astro/e2e/fixtures/view-transitions/src/pages/page2-with-scripts.astro, packages/astro/e2e/fixtures/view-transitions/src/pages/page3-with-scripts.astro, packages/astro/e2e/view-transitions.test.js, packages/astro/src/transitions/router.ts, packages/astro/src/transitions/swap-functions.ts
- In a long session you might navigate between several pages, some contain the script and some not, but nevertheless the script should run a total of 1 time.
- This also helps with smaller bundled scripts in production, where some are inlined.
- Keeps track of scripts that have run, either by the src or by the inner text (for inline scripts) and uses that as a key, rather than the data attribute we previously adde.
- Updated the existing tests to navigate between more pages.
N/A, bug fix.
=> Prevent rerunning scripts already ran in router

.changeset/hip-horses-count.md, packages/db/src/core/integration/index.ts
adds `decodeURIComponent` to properly handle the pathname
closes: #13332
there's no need to update docs.
=> fix(astro:db): resolve Astro DB seed failure with paths containing spaces

packages/integrations/cloudflare/package.json, packages/integrations/netlify/package.json, packages/integrations/node/package.json, packages/integrations/vercel/package.json
This PR adds the command `build:ci` to the adapters we recently moved.
That command is used by the ecosystem CI of `vite`
Merge it and check with the vite team
N/A
=> ci: add new command for vite ecosystem CI

packages/astro/src/assets/fonts/constants.ts, packages/astro/src/assets/fonts/load.ts, packages/astro/src/assets/fonts/providers/google.ts, packages/astro/src/assets/fonts/providers/local.ts, packages/astro/src/assets/fonts/providers/utils.ts, packages/astro/src/assets/fonts/types.ts, packages/astro/src/assets/fonts/utils.ts, packages/astro/src/assets/fonts/vite-plugin-fonts.ts, packages/astro/src/core/config/schema.ts, packages/astro/test/units/assets/fonts/load.test.js, packages/astro/test/units/assets/fonts/utils.test.js
- Simplifies the `cache` util
- Removes duplicated loop while resolving font families
- Extracts code to a new `loadFonts` function, making it easier to test
- Extract things outside of the the vite plugin file
- Moves constants around to fix a circular dependency problem
Adds a unit test
N/A
=> feat(fonts): refactor loading logic

.changeset/metal-tomatoes-confess.md, packages/internal-helpers/src/remote.ts
This PR documents the asset utilities that we expose to users. 
It seems that these aren't properly documented, so I wanted to start from here, and then send a PR to docs to make it official.
N/A
FYI, I helped myself with an AI tool, so I would appreciate a second pair of eyes. I already checked what the AI tool wrote before sending the PR. 
=> docs: document asset utilities

.changeset/twenty-news-tease.md, packages/astro/src/assets/utils/index.ts
This PR removes `makeSvgComponent` from the exported functions. That function is meant to be used internally and shouldn't be exported.
I added a note at top of the file. 
CI should pass
N/A
=> fix(assets): remove export of internal function

packages/astro/src/assets/fonts/config.ts, packages/astro/src/assets/fonts/load.ts, packages/astro/src/assets/fonts/utils.ts, packages/astro/src/assets/fonts/vite-plugin-fonts.ts, packages/astro/src/core/config/schema.ts, packages/astro/test/units/assets/fonts/load.test.js, packages/astro/test/units/assets/fonts/utils.test.js
- Adds css variables generations
- Fixes a bug around fallbacks that impacted css variables
- RFC has been updated to remove the `cssVar` prop from the `Font` component as I'll go with another solution (upcoming PR)
Adds unit tests
N/A
=> feat(fonts): css vars

packages/astro/src/core/errors/errors-data.ts
A new Actions error was added in the "Astro Errors" section instead of the "Actions Errors" section. This just moves the error to the appropriate section so that in the main error reference listing page, it shows up with the other actions errors.
no tests; docs
only affects docs!
=> [docs] move location of an Actions error

.changeset/gold-pears-reply.md, packages/astro/src/assets/utils/imageKind.ts, packages/astro/src/assets/utils/metadata.ts, packages/astro/src/assets/utils/node/emitAsset.ts, packages/astro/src/assets/utils/queryParams.ts, packages/astro/src/assets/utils/remoteProbe.ts, packages/astro/src/assets/utils/transformToPath.ts
This PR adds more JsDoc to the utility functions that we expose for image services.
I used a LLM tool to generate the docs, and then reviewed them to make sure they seem correct.
I also noticed `resolveSrc` was awaiting **twice** the same resource in case no `.default` wasn't returned. I changed the code so the awaiting is done once every time.
I also slightly refactored `imageMetadata` because we were throwing an error inside a `try` block.
=> docs: document utility functions

.changeset/every-birds-stick.md, packages/astro/src/transitions/router.ts
In `typescript/lib/lib.dom.d.ts` the ViewTransition interface now includes the `types` property.
Added the property to our simulated viewTransition object for browsers without native support.  
https://discord.com/channels/830184174198718474/1055240348970000454/1346390166356361289  
Compiles without errors after removing the @ts-expect-error comment
n.a. / upstream change
=> Extend the simulated viewTransition object with the  `types` property

packages/astro/src/assets/fonts/config.ts, packages/astro/src/assets/fonts/load.ts, packages/astro/src/assets/fonts/types.ts, packages/astro/src/assets/fonts/utils.ts, packages/astro/src/assets/fonts/vite-plugin-fonts.ts, packages/astro/src/core/config/schema.ts, packages/astro/test/units/assets/fonts/load.test.js, packages/astro/test/units/assets/fonts/utils.test.js
- This adds an optional `as` property to a font family
- The RFC has been updated but TLDR use `as` if:
1. You are an integration and want to make sure you don't conflict with fonts declared by the user
2. Your font name can't be properly converted to a CSS variable name
Tests updated
RFC updated
=> feat(fonts): as prop

examples/blog/src/pages/index.astro
- Remove trailing spaces from blog example's links.
- A formatter introduced newlines inside the anchor tags on the blog example's home `index.astro` page, causing the link to include a trailing space.
- Not the worst thing, just looks a little unpolished compared to everything else I've experienced getting to know Astro :)
- I've put the anchor tags on their own lines to avoid this issue, _and_ prevent future formatters from re-introducing the issue (tested with Astro extension's formatter, at least).
- No changeset because this is in `examples/*`.
- Ran the example locally (`cd examples/blog && npm run dev`) and it fixes the issue.
- Ran Astro VS Code extension's formatter, confirmed issue is not re-introduced. (Also tried Prettier's.)
No docs added - small visual tweak to blog example …
=> Remove trailing spaces from blog example links.

.changeset/rude-maps-visit.md, packages/astro/src/types/public/config.ts
* Fixes `image.domains` and `image.remotePatterns` default values (these options expect an array, not an object).
* De-duplicates the type for `i18n` (the JSDoc `@type` tag was set twice)
* Merge `i18n.routing.manual` description into `i18n.routing` and updates the example.
`manual` is not a key of `i18n.routing` but an available value. So it currently seems odd that this is listed with the available keys [in the docs](https://docs.astro.build/en/reference/configuration-reference/#i18nroutingmanual). And the example is not helpful, this is the one used for `prefixDefaultLocale`.
* Fixes the type of `i18n.routing`
Unless I'm mistaken, the `Routing` type doesn't exist so maybe it's better to use `object`? And, the value can also be `"manual"`.
* Adds missing `@docs` tag to `i18n.domains` …
=> docs: fix config types (images, i18n)

.changeset/lazy-kings-rush.md, packages/astro/e2e/fixtures/view-transitions/src/pages/partial-swap.astro, packages/astro/e2e/view-transitions.test.js, packages/astro/src/transitions/router.ts
Fixes #13375 
Marks scripts executed on initial page load as executed to prevent their re-execution if they are not replaced with the next call to swap. 
This might happen if a custom swap() function only swaps part of the DOM and leaves some original scripts in place. 
added e2e test
n.a. / bug fix
=> ClientRouter: prevent double execution of scripts when custom swap() only swaps parts of the DOM

packages/astro/src/types/public/config.ts
Those additions should help users that try to use redirects to resolve issues with trailing slashes. Those redirects are not supported ATM. It is quite time consuming to debug those, so having something in the docs about it should save people some time.
More about the issue in https://github.com/withastro/astro/issues/12532#issuecomment-2703410890
This is a docs change. The test case is in https://github.com/withastro/astro/issues/12532#issuecomment-2703410890
This is only a docs change.
=> Docs: Clarify redirects use case

packages/astro/src/assets/fonts/config.ts, packages/astro/src/assets/fonts/load.ts, packages/astro/src/assets/fonts/providers/local.ts, packages/astro/src/assets/fonts/types.ts, packages/astro/src/assets/fonts/utils.ts, packages/astro/src/core/config/schema.ts, packages/astro/test/units/assets/fonts/load.test.js, packages/astro/test/units/assets/fonts/providers.test.js, packages/astro/test/units/assets/fonts/schemas.test.js, packages/astro/test/units/config/config-validate.test.js
This PR makes a bunch of changes related to the fonts configuration:
- Extracts schemas to be reused in the Astro config and in types
- Improves schemas to allow more font options (eg. `featureSettings`)
- Adds errors to avoid name conflicts. Consider the errors messages placeholders, we'll refine them once team docs make a proper review
- ~~I'd like your opinion on a TODO (I added a PR comment as well)~~
- Adds unit tests
- Disable whitespace sensitivty as I took the opportunity to improve some things in the config validation test
N/A
=> feat(fonts): resolve config todos

.changeset/small-masks-wink.md, packages/astro/src/assets/build/generate.ts
If Astro detects that sharp is not installed when trying to transform an image it will throw a `MissingSharp` error. However when this happens during a build, we currently catch it and instead throw a `CouldNotTransformImage` error, with a message suggesting the image is corrupt. The correct error is buried in the  `cause`. This PR checks if the thrown error is an AstroError, and if so rethrows it rather than throwing a `CouldNotTransformImage` error. This means that the `MissingSharp` error is logged correctly.
=> fix: rethrow astroerrors in image processing

packages/astro/src/types/public/config.ts
The default value for `markdown.syntaxHighlight.excludeLangs` didn't have backticks so the formatting in the [docs preview](https://deploy-preview-11212--astro-docs-2.netlify.app/en/reference/configuration-reference/#markdownsyntaxhighlightexcludelangs) was wrong.
Existing tests should still pass.
This is a docs fix.
=> docs: fix formatting of `excludeLangs` default value

.changeset/real-results-float.md, packages/astro/src/types/public/config.ts
=> fix: make preserveScriptOrder an optional flag

.changeset/dull-papers-fry.md, packages/astro/src/core/session.ts
Moves the storage object to a static property on `AstroSession`, meaning it can be reused between requests. This avoids memory leaks and excessive connections when using drivers that open persistent DB connections.
Fixes #13376
Tested manually. Passes all session tests.
=> fix: reuse storage objects in sessions

packages/astro/src/assets/fonts/config.ts, packages/astro/src/assets/fonts/vite-plugin-fonts.ts, packages/astro/src/core/config/schema.ts, packages/astro/test/units/assets/fonts/schemas.test.js, packages/astro/test/units/config/config-validate.test.js
- Validates the name of the font family, to make sure we can generate a proper css variable name
Added
N/A
=> feat(fonts): family name validation

.changeset/weak-grapes-join.md, packages/astro/src/core/build/plugins/plugin-css.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-astro/types.ts, packages/astro/test/0-css.test.js, packages/astro/test/astro-css-bundling.test.js, packages/astro/test/config-vite.test.js, packages/astro/test/css-inline-stylesheets.test.js, packages/astro/test/css-order-import.test.js, packages/astro/test/css-order.test.js, packages/astro/test/postcss.test.js, packages/astro/test/remote-css.test.js, packages/integrations/tailwind/test/fixtures/basic/astro.config.js
Reverts withastro/astro#13347
Closes https://github.com/withastro/astro/issues/13416
Unfortunately that PR created some unwanted regressions, and I am afraid we need to revert it
=> Revert "Replace internal cssScopeTo implementation to vite.cssScopeTo"

.changeset/ten-tips-share.md, packages/astro/src/cli/add/index.ts
Ensures that the "x is not an official Astro package" prompt respects the `--yes` flag
Fixes #13399
Manually tested.
=> fix: respect `--yes` flag for third-party integrations

packages/astro/src/assets/fonts/config.ts, packages/astro/src/assets/fonts/constants.ts, packages/astro/src/assets/fonts/load.ts, packages/astro/src/assets/fonts/utils.ts, packages/astro/test/units/assets/fonts/schemas.test.js, packages/astro/test/units/assets/fonts/utils.test.js
This follows a RFC review from @matthewp 
- By default, we try to generate automatic fallbacks
- With this PR, set `automaticFallback: false` on a family to disable this behaviors
Adds a test
RFC has been updated
=> feat(fonts): allow disabling automatic fallback generation

.changeset/bitter-rockets-pull.md, packages/astro/src/core/config/merge.ts
- Fixes: #13342 
- Fix handling of server.allowedHosts when the value is true.
- Ensures that a boolean `true` value is accepted without attempting to convert it into an array.
- Manually tested by setting allowedHosts: true in astro.config.mjs.
- Verified that astro info and astro dev no longer throw configuration errors.
No documentation updates needed as this aligns with existing Vite behavior.
=> fix(config): handle boolean server.allowedHosts

.changeset/empty-cloths-sort.md, packages/astro/src/content/content-layer.ts, packages/astro/src/content/mutable-data-store.ts, packages/astro/src/content/runtime.ts
This fixes a few race condition bugs that manifested in sites with lots of very large markdown files.
Adds a method to the data store object that returns a promise that resolves when saving to disk is complete. 
Resets the `#dirty` flag *before* saving to disk. The main cause of #13310 was that debounced saves that happened while the large data store file was being written to disk would be lost because the dirty flag was cleared once the file write was complete, missing the fact that more more entries need writing.
Fixes #13310
Tested with the #13310 repro
=> fix: race conditions in data store save

.changeset/ninety-cups-decide.md, packages/astro/e2e/fixtures/actions-blog/src/components/PostComment.tsx, packages/astro/src/container/index.ts, packages/astro/src/container/pipeline.ts, packages/astro/test/container.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/13264
This PR adds support for `Astro.rewrite` for the container API. A new method called `insertPageRoute` has been exposed that will help users to test routes that trigger a possible rewrite.
I added a new test
Will create a PR
=> feat: add new method `insertPageRoute` to container

.changeset/true-moose-report.md, packages/astro/src/core/app/node.ts, packages/astro/test/units/app/node.test.js
- If a bad value is provide by this header, we simply ignore it and fallback to the host provided by the host header (if there is one).
- Fixes https://github.com/withastro/astro/issues/13392
- Test added
N/A, bug fix
=> Handle bad values in x-forwarded-host

packages/astro/CHANGELOG.md
Fixes the changelog by adding the message of this PR: https://github.com/withastro/astro/pull/13427
The changelog was incorrect due to a mistake I made, where I reverted the PR just mentioned.
N/A
N/A
=> chore: fix changelog message due to a previous mistake

.github/renovate.json5
Due to the recent events that happened with [`changed-files`](https://github.com/tj-actions/changed-files/issues/2464), this PR enforces the use of the commit digests for our GH actions, instead of a tag.
I also added a group to renovate, so renovate will make a PR to update them all at once.
Once merged, renovate should update its dependency board. I will trigger a PR
N/A
=> ci: pin actions via digest

.changeset/bumpy-sites-ring.md, packages/astro/src/runtime/server/render/page.ts, packages/astro/test/custom-404-static.test.js, packages/astro/test/custom-500.test.js
Currently if a user has a custom `404.astro` or `500.astro` we set the correct status code in the response, but not the correct status text, instead leaving the default `OK`. This PR ensures the correct text is set too.
Fixes #13259
Added tests
=> fix: set correct statusText for custom error pages

.changeset/dark-rooms-enter.md, packages/astro/src/core/app/index.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/routing/3xx.ts, packages/astro/src/vite-plugin-astro-server/response.ts, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/redirects.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/13371
To avoid possible breaking changes with the canonical tag, now the function that creates the HTML redirect accepts a relative location and an absolution location. 
Added a new test. I also tested it manually to make sure that it keeps working as expected. 
N/A
=> fix(routing): don't add site to static redirects

.github/renovate.json5
This PR breaks down the groups handled by renovate.
At the moment when renovate sends a PR, it's fall all packages that we have in the monorepo. This can be overwhelming sometimes, and few times there are breaking changes that require fixes across packages.
This PR creates the following groups:
- the astro deps (`astro`, `@astrojs/mdx` and `@astrojs/markdown-remark`)
- adapters
- runtime integrations (react, solid, etc.)
- the rest
I'll check the board once this is merged
N/A
=> chore(renovate): group updates

.changeset/witty-socks-relax.md, packages/integrations/tailwind/README.md
- Updates the Tailwind integration README to show it is deprecated and remove links to docs which are no longer useful
n/a — docs only
=> Add deprecation notice to Tailwind integration README

packages/astro/client.d.ts, packages/astro/components/Font.astro, packages/astro/src/assets/fonts/constants.ts, packages/astro/src/assets/fonts/load.ts, packages/astro/src/assets/fonts/sync.ts, packages/astro/src/core/sync/index.ts, packages/astro/test/units/assets/fonts/load.test.js, packages/astro/types/fonts.d.ts
- Now generates types for the `Font` component family prop
- Fixes a bug where the map passed to the virtual module was not using `family.as` if provided
Updated + manual
N/A
=> feat(fonts): typegen for <Font /> family prop

.changeset/twelve-gifts-attend.md, packages/astro/src/core/config/vite-load.ts
Currently there is a strange error on Stackblitz where if the config cannot be loaded because of native addons it fails silently, because it throws an uncatchable error. This PR improves error handling so that those errors can be properly logged. This is not Stackblitz-specific, but does special-case the `ERR_DLOPEN_DISABLED` error that is thrown. This should be fine, because it's not the sort of error that would ever be recoverable by Vite, as it's due to a setting in Node. 
Fixes #13249
Manually tested on Stackblitz:
https://stackblitz.com/github/ascorbic/withastro-astro-banrd5uv/tree/ascorbic/patch-13439
=> fix: better error handling on Stackblitz

.changeset/wet-bottles-invite.md, packages/astro/src/core/app/index.ts, packages/astro/test/fixtures/middleware space/integration-middleware-post.js, packages/astro/test/middleware.test.js
Closes https://github.com/withastro/astro/issues/13409
The fixes use the same logic as the dev server. If we can't find a `RouteData` that matches the incoming request, we seek the `/404` route, which we usually have, and pass it to the `RenderContext`. The `RenderContext` eventually calls the middleware. 
I added a new test. Hopefully I didn't introduce any regressions
N/A
=> fix(app): call renderer when routes don't match

packages/astro/src/assets/fonts/config.ts, packages/astro/src/assets/fonts/load.ts, packages/astro/src/assets/fonts/types.ts, packages/astro/src/core/config/schema.ts, packages/astro/test/types/define-config.ts
- There was a regression in #13401 that made impossible to provide an object without a `provider` for a family
- This PR moves some things around to have types working properly
Updates the types tests
N/A
=> fix(fonts): config family types for inferred provider

.changeset/honest-loops-cheat.md, packages/astro/src/core/cookies/cookies.ts, packages/astro/test/units/cookies/get.test.js
Currently, when a cookie is first parsed from the header the value is cached. This means that if subsequent requests pass a different decode function it will be ignored. This PR changes the behaviour to cache the raw cookie values, and then decode them when getting them. This means the passed decode function will always be used.
Fixes #13078
=> fix: cache raw cookie value and decode when getting

.changeset/clever-tigers-dig.md, packages/astro/src/actions/noop-actions.ts, packages/astro/src/core/app/types.ts, packages/astro/src/core/base-pipeline.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/plugins/plugin-ssr.ts, packages/integrations/cloudflare/test/astro-env.test.js, packages/integrations/cloudflare/test/fixtures/astro-env/package.json, packages/integrations/cloudflare/test/fixtures/astro-env/src/actions.ts, packages/integrations/cloudflare/test/fixtures/astro-env/src/middleware.ts, packages/integrations/cloudflare/test/fixtures/astro-env/src/pages/test.astro, pnpm-lock.yaml
- Closes #13503 
- Dynamically imports actions in SSR
Adds a cloudflare test 
N/A
=> fix(astro): dynamically import actions

packages/astro/src/assets/fonts/constants.ts, packages/astro/src/assets/fonts/load.ts
- After discussing with @delucis, we came to the conclusion that having `sans-serif` as a default fallback makes sense so users can benefit from automatic fallback generation by default
N/A
Will be documented properly alongside all defaults
=> feat(fonts): set default fallbacks

.changeset/ninety-nights-hug.md, packages/astro/src/i18n/index.ts, packages/astro/src/i18n/utils.ts, packages/astro/src/virtual-modules/i18n.ts, packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/astro.config.mjs, packages/astro/test/i18n-routing.test.js
Closes https://github.com/withastro/astro/issues/13446
The PR fixes the bug of a couple of functions:
- added a new function to extract all codes
- `computePreferredLocale` *now* returns `locale.code`
- `computePreferredLocaleList` *now` return `locale.code`
Added a new test and updated the wrong one.
N/A
=> fix(i18n): return value from `preferredLocale`

.changeset/poor-squids-like.md, packages/astro/src/prefetch/index.ts
New `PrefetchOptions` param `eagerness` that can be explicitly stated for `prefetch()` function.
Usecase: letting a browser manage when a page should be prerendered will simplify web site code compared to default behavior (no `eagerness` passed will automatically default to `immediate`, causing headcaches if you want to use FIFO strategy available for `moderate` and `conservative` args)
Reference doc: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/speculationrules#eagerness
No tests added, as there weren't for `PrefetchOptions`
`prefetch()` doc should be updated accordingly to notify users a new option to be passed on
=> feat: Add `eagerness` support for `prefetch()`

.changeset/famous-areas-peel.md, packages/astro/src/core/session.ts, packages/astro/test/fixtures/sessions/src/actions/index.ts, packages/astro/test/sessions.test.js
Adds support for loading a session by ID
Adds a new `session.load()` method to the experimental session API that allows you to load a session by ID. In normal use a session is loaded automatically from the session cookie. This method allows a session to be loaded manually instead. This has been requested in the RFC, and is useful for cases where the session ID has been persisted somewhere other than the browser cookie. For example, a session ID might be stored in a user database. This would allow that user's session to be loaded when logging-in on another device or in a different browser. It would also allow a session to be loaded in an API when cookies can't be set, such as when loading across domains.
Added tests
I will do a separate docs PR
=> feat: add `session.load(id)` method

.changeset/famous-areas-peel.md
Adds content from the release blog to the session.load changeset
=> chore: better session.load changeset

.changeset/itchy-bulldogs-scream.md, packages/astro/package.json, packages/astro/src/assets/utils/svg.ts, packages/astro/test/core-image-svg.test.js, packages/astro/test/fixtures/core-image-svg/src/pages/strip.astro, pnpm-lock.yaml
Updating to the latest 1.6.0 which fixes the issue and brings in some optimizations to the regexes it uses.
Fixes #13496
Added a test to assert that there were no empty attributes `=""` in the resultant html with an SVG known to produce it.
Not necessary as this is just a bug fix.
=> fix(svg): prevent empty attributes

.changeset/heavy-months-sin.md, .changeset/old-animals-shop.md, packages/astro/src/core/config/schemas/base.ts, packages/astro/src/core/config/schemas/refined.ts, packages/astro/src/integrations/hooks.ts, packages/astro/test/fixtures/i18n-routing-prefix-always/astro.config.mjs, packages/astro/test/units/config/config-validate.test.js
Closes #13551
After 5.6.0, where we changed how we validate the astro configuration, we found out that Astro was validating incorrect values for `i18n.routing.
This PR fixes the values.
Updated tests and error message.
cc @delucis and @HiDeoo
=> fix(i18n): incorrect validation

.changeset/wet-onions-kick.md, packages/astro/src/cli/add/index.ts, packages/astro/src/cli/install-package.ts
- Deno requires a prefix when installing packages
- So, if you use Deno as your package manager, prepend `npm:` to the library name
It was manually tested on local. We can install and try out this PR's `astro`.
I think Astro don't officially supports Deno as a package manager, so I'll write about it if necessary.
=> fix: support for Deno to install npm packages

.changeset/good-worms-heal.md, packages/astro/src/assets/utils/index.ts, packages/astro/src/assets/utils/node/emitAsset.ts, packages/integrations/markdoc/src/content-entry-type.ts
Due to some mistake we've made, the utility function `emitESMImage` - which is exposed as public API - is broken. 
To remedy the mistake, we will expose a new function to userland, which has a different signature (we removed the things we don't need).
I updated `@astrojs/mdx` to use the new function.
I will send a PR to update the docs.
=> chore: deprecate `emitESMImage` function

.changeset/brown-lines-talk.md, packages/astro/src/core/build/plugins/plugin-prerender.ts
- (Potentially) fixes a regression introduced by #13519
- User on Discord reported a build failure introduced between [`5.6.0` and `5.6.1`](https://github.com/withastro/astro/compare/astro%405.6.0...astro%405.6.1). The cause seemed to be `astro-icon` chunks, which should only be prerendered, were leaking into the server bundle.
Looking through the commits, the only suspicious commit seems to be #13519, which ported over [the following lines](https://github.com/withastro/astro/pull/13519/files#r2020561968).
- Originally, this change was introduced by [an ecosystem patch to improve Rolldown compat](https://github.com/vitejs/vite-ecosystem-ci/blob/rolldown-vite/tests-patches/astro/astro.patch#L244-L249), but we don't have insight into what bug was being fixed. We're asking around for the …
=> fix(prerender): revert dynamic entry chunks included in server bundle

.changeset/five-rings-smile.md, packages/astro/src/assets/utils/node/emitAsset.ts, packages/astro/src/assets/vite-plugin-assets.ts, packages/astro/src/core/create-vite.ts
- adjusts `svg` handling to fix a memory leak
- see #12694 for original workaround, Erika's [suggestion on #12067](https://github.com/withastro/astro/pull/12067#discussion_r1780990317)
- unblocks #13578
1. Tested with a modified version of the `benchmark` script that included 10,000 `svg` files.
2. Tested against the real-world [`cloudflare-docs`](https://github.com/cloudflare/cloudflare-docs) repo, where the original bug report was surfaced. It generates 5K+ page and has 1100+ `.svg` files. Before this change, I got an OOM error. After this change, I was able to build the site successfully. [See Discord thread for full fix verification updates](https://discord.com/channels/830184174198718474/1357286171578994821)
Bug fix only
=> fix(svg): do not attach `svg` buffer to `imageMetadata`

.changeset/puny-masks-laugh.md, packages/astro/src/core/routing/rewrite.ts, packages/astro/test/units/routing/trailing-slash.test.js
Closes: #13585 
Fixes routing with base paths when `trailingSlash` is set to 'never', ensuring requests to '/base' are correctly matched when the base path is set to '/base'. The fix also maintains compatibility with rewrites, with all rewrite tests passing successfully.
I've added 2 🤏🏻 tests 🫡
=> fix(routing): handle base path with trailing slash 'never' configuration

packages/astro/src/assets/fonts/utils.ts, packages/astro/src/core/errors/errors-data.ts
This adds the `@message` property (and `message` to the ErrorData object) for one of the new error messages. @florian-lefebvre or someone please correct/verify the actual content!
Not tested, but the `@message` property is the one that generates the error message block in docs. Without it, we only get a "What went wrong?" section. (This might also affect the error message people see?)
e.g. without: (we had one slip by earlier!)
vs most other error messages:
All for docs!
=> add missing `message` to a Fonts API error

.changeset/tricky-adults-jump.md, packages/create-astro/src/actions/template.ts
Update the list of available choices when running `create astro` to include the `minimal` starter.
This is useful for people taking the introductory tutorial in docs, creating minimal reproductions, and for experienced users starting projects from scratch.
In particular, it avoids needing to document workarounds to installing the minimal template for the tutorial via a template flag. (For example, Powershell users cannot follow the command as provided. This leads to them choosing the wrong template at the start of the tutorial, and is confusing when their code doesn't match the tutorial instructions.)
Closes Docs Issue https://github.com/withastro/docs/issues/10843
Not tested! 
The tutorial docs will be updated (simplified) to no longer require installing the minimal starter using a …
=> Add the minimal example to `create astro` options

packages/astro/CHANGELOG.md, packages/integrations/cloudflare/CHANGELOG.md, packages/integrations/netlify/CHANGELOG.md, packages/integrations/node/CHANGELOG.md
The 5.7.0 changelog includes `<h2>` headings in the sessions details which is inconsistent with other headings in the changelog and is breaking some automated tooling that attempts to display a version’s notes (see e.g. this Renovate PR: https://github.com/withastro/astro.build/pull/1529)
n/a
n/a
=> Fix changelog heading levels

.changeset/young-peaches-serve.md, packages/astro/src/core/session.ts
Use the `| (string & {})` trick to ensure that key autocomplete always works
=> fix: improve autocomplete for session keys

.changeset/red-parents-tease.md, packages/astro/package.json, packages/astro/src/assets/fonts/load.ts, packages/astro/src/assets/fonts/metrics.ts, packages/astro/src/assets/fonts/utils.ts, packages/astro/src/assets/fonts/vite-plugin-fonts.ts, packages/astro/test/units/assets/fonts/utils.test.js, pnpm-lock.yaml
- RFC feedback
- Removes `@capsizecss/metrics` because it's heavy. Instead, we read the font files directly
- Simplifies the cache util
Should pass
Changeset
=> fix(fonts): lighter fallbacks

.changeset/thick-walls-open.md, packages/astro/components/Font.astro
- According to capo, preload link should come before style tags
- Updated after feedback on the RFC
N/A
Changeset
=> fix(fonts): component ordering

.changeset/orange-cloths-camp.md, packages/astro/src/core/routing/rewrite.ts, packages/astro/test/fixtures/rewrite-issue-13633/astro.config.mjs, packages/astro/test/fixtures/rewrite-issue-13633/package.json, packages/astro/test/fixtures/rewrite-issue-13633/src/middleware.js, packages/astro/test/fixtures/rewrite-issue-13633/src/pages/about.astro, packages/astro/test/fixtures/rewrite-issue-13633/src/pages/index.astro, packages/astro/test/rewrite.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/13633
A check was modified, but it turns out that it was required, in fact the tests introduced in https://github.com/withastro/astro/pull/13598 still pass
N/A
=> fix(routing): rewrite regression

.changeset/tasty-cities-warn.md, packages/astro/src/core/routing/manifest/create.ts, packages/astro/test/redirects.test.js
As per #13607, redirects had a regression with relative redirects introduced in #12979. This PR fixes it.
Fixes #13607
- Unit tests
- Tested with my local side project using the new changes
/cc @withastro/maintainers-docs for feedback! This was never documented but always worked since early versions of Astro so as mentioned by @ematipico on #13607 we should probaly update the docs. Happy to have a stab at it if you want too.
=> Fix relative redirects regression. Closes #13607

.changeset/chilled-pears-know.md, packages/create-astro/src/actions/template.ts
A trivial text change so I can add the proper changeset this time 😅 
(Follow up to #13603 which added the minimal template, but didn't trigger an update to the `create-astro` package)
No tests.
When this is released, I can improve instructions to the tutorial in docs
=> update create-astro minimal template wording

.changeset/rich-dancers-sniff.md, packages/astro/src/assets/fonts/utils.ts, packages/astro/test/units/assets/fonts/utils.test.js
- Closes #13637 
- Unifont deduplicates providers based on the provider name. However in our case the same provider can be called with a different config (eg. adobe), so we have some logic to hash the config and dedupe
- However, the logic AND the tests were wrong because in certain cases, the family provider name was not assigned a value and as such, the family could not be resolved by unifont 
Tests updated + manual
Changeset
=> fix(fonts): providers deduplication logic

.changeset/dirty-dryers-rush.md, packages/astro/src/actions/runtime/virtual/server.ts
Currently the action API context is created by destructuring the unused properties of the context object. This was causing warnings to be logged because it copies by value, meaning the session get method was being called.
This PR switches to using `Object.create` and `getOwnPropertyDescriptors`, which preserves the accessors on the object, menaing the `session` getter isn't called unless the user accesses it.
Fixes #13644
Tested with the repro for #13644
=> fix: clone actionAPIContext preserving accessors

.changeset/dull-teeth-cut.md, packages/astro/src/types/public/config.ts
- This PR adds `server.allowedHosts` docs comment to `AstroUserConfig`
- N/A
- Closes https://github.com/withastro/docs/issues/11336
=> fix(types): add `server.allowedHosts` docs comment to `AstroUserConfig`

.changeset/slick-eggs-laugh.md, packages/astro/src/assets/fonts/providers/index.ts
- The google config was not passed to the unifont provider (reported on Discord)
N/A
Changeset, https://github.com/withastro/docs/pull/11484
=> fix(fonts): google config

.changeset/moody-lines-clean.md, packages/astro/src/core/middleware/sequence.ts, packages/astro/src/core/render-context.ts, packages/astro/test/fixtures/reroute/src/pages/index.astro, packages/astro/test/rewrite.test.js
Closes https://github.com/withastro/astro/issues/13555
When creating a new request during the rewrite, the symbol was lost. This PR makes sure to add the symbol again with the correct value.
I updated one of the existing tests
`Astro.originPathname` isn't documented, I will send a PR later
=> fix(routing): origin pathname when using rewrites

packages/astro/src/container/index.ts, packages/astro/src/core/app/types.ts, packages/astro/src/core/astro-islands-hashes.ts, packages/astro/src/core/base-pipeline.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/core/config/schema.ts, packages/astro/src/core/csp/common.ts, packages/astro/src/core/render-context.ts, packages/astro/src/integrations/hooks.ts, packages/astro/src/runtime/server/astro-island-styles.ts, packages/astro/src/runtime/server/render/common.ts, packages/astro/src/runtime/server/render/head.ts, packages/astro/src/runtime/server/scripts.ts, packages/astro/src/types/public/config.ts, packages/astro/src/types/public/internal.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/astro/test/csp.test.js, packages/astro/test/fixtures/csp/astro.config.mjs, packages/astro/test/fixtures/csp/package.json, packages/astro/test/fixtures/csp/src/pages/index.astro, packages/astro/test/fixtures/csp/src/pages/index.css, packages/astro/test/test-adapter.js, pnpm-lock.yaml, scripts/cmd/prebuild.js
This PR updates Astro to use the information we already have of scripts and styles to create hashes and render them in the emitted HTML page.
This PR focus only SSG for now, I will follow up with another PR to implement the same logic for SSR.
- `SSRManifest` has been extended to track new information, such as hashes coming from scripts and styles. I prefer to keep them separated because we handle them differently throughout the code base.
-  `SSRResult` has been extended to pass the hashes during the rendering phase. As for now, these hashes are always injected. **I will change that later**, and inject them only for static outputs. I need to find a way to test the static output with predictable hashes.
- `ASTRO_STYLES` has been moved into a separate file, so I could add a better warning …
=> feat(csp): create hashes of tracked scripts and hashes

.changeset/social-bats-kiss.md, packages/astro/src/assets/fonts/utils.ts, packages/astro/src/assets/fonts/vite-plugin-fonts.ts, packages/astro/test/units/assets/fonts/utils.test.js
- RFC feedback
- People migrating to the fonts API with local fonts tend to leave their fonts in `public`, but this is not recommended as we copy fonts so files are effectively duplicated in the build output
Manual
https://github.com/withastro/docs/pull/11511 + changeset
=> feat(fonts): warn if local font is in public dir

.changeset/shaky-coins-fry.md, .changeset/tall-pots-fly.md, packages/astro/components/image.css, packages/astro/src/assets/internal.ts, packages/astro/src/assets/layout.ts, packages/astro/src/assets/types.ts, packages/astro/src/core/config/schemas/base.ts, packages/astro/src/types/public/config.ts, packages/astro/test/core-image-layout.test.js, packages/astro/test/fixtures/core-image-layout/astro.config.mjs, packages/integrations/vercel/test/fixtures/image/src/pages/index.astro
Renames experimental responsive image layout option from "responsive" to "constrained"
The previous name was causing confusion, because it is also the name of the feature. The `responsive` layout option is specifically for images that are displayed at the requested size, unless they do not fit the width of their container, at which point they would be scaled down to fit. They do not get scaled beyond the intrinsic size of the source image, or the `width` prop if provided. 
It became clear from user feedback that many people (understandably) thought that they needed to set `layout` to `responsive` if they wanted to use responsive images. They then struggled with overriding styles to make the image scale up for full-width hero images, for example, when they should have been using …
=> feat: rename layout and refactor styles

.changeset/chatty-taxes-retire.md, packages/astro/src/assets/fonts/config.ts, packages/astro/test/types/define-config.ts, packages/astro/test/units/config/config-validate.test.js, pnpm-lock.yaml
Regarding experimental fonts, the documentation says:
> To disable fallback fonts completely, configure an empty array:
>
> fallbacks: []
But I get a Typescript error if I do that. This is a simple typing issue, not a behavioral one, so in this PR I am:
- fixing the type so an empty array is allowed, to match the doc
Closes #13659
Added a type test that fails before this change and succeeds after:
BEFORE:
> $ pnpm test:types
> test/types/define-config.ts:150:8 - error TS2322: Type '[]' is not assignable to type '[string, ...string[]]'.
>   Source has 0 element(s) but target requires 1.
>
> 150        fallbacks: [],
>            ~~~~~~~~~
AFTER:
> $ pnpm test:types
succeeds
Bringing types in line with docs, no doc updates needed
=> Fonts: fix typing for disabled fallbacks (empty array)

.changeset/flat-chicken-shout.md, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/core/routing/manifest/create.ts
- It has been reported several times that people with complex redirects couldn't find the failing ones
- This PR makes it so that the corresponding error includes the origin and the destination
Should pass
Changeset
=> fix: improve external redirects message

.changeset/purple-horses-talk.md, packages/astro/src/types/public/config.ts
This update some vocabulary and links in the configuration reference `adapter` entry.
The vocabulary changes are consistent with us moving away from the term "SSR" and being in "SSR mode". The links also point to the full adapter integration documents themselves, rather than a section in the deploy guides.
No tests. Just docs improvements
Only affects docs!
=> [docs] better text/links in config ref adapter entry

.changeset/cyan-games-jog.md, packages/astro/package.json, packages/astro/src/assets/fonts/definitions.ts, packages/astro/src/assets/fonts/implementations/data-collector.ts, packages/astro/src/assets/fonts/implementations/font-fetcher.ts, packages/astro/src/assets/fonts/implementations/font-metrics-resolver.ts, packages/astro/src/assets/fonts/implementations/url-proxy.ts, packages/astro/src/assets/fonts/logic/normalize-remote-font-faces.ts, packages/astro/src/assets/fonts/logic/optimize-fallbacks.ts, packages/astro/src/assets/fonts/orchestrate.ts, packages/astro/src/assets/fonts/providers/local.ts, packages/astro/src/assets/fonts/types.ts, packages/astro/src/assets/fonts/vite-plugin-fonts.ts, packages/astro/test/units/assets/fonts/implementations.test.js, packages/astro/test/units/assets/fonts/logic.test.js, packages/astro/test/units/assets/fonts/orchestrate.test.js, packages/astro/test/units/assets/fonts/providers.test.js, pnpm-lock.yaml
- Updates unifont to 0.4.0 (latest)
- Adds support for passing fetch init (see https://github.com/unjs/unifont/pull/155)
- Refactors types a bit to avoid duplication
- For `init`, I chose to use `null` instead of an optional property to make sure we pass it through everything
- Updated tests so they still pass and TS is happy
- Updated the `orchestrate` test to make sure `init` is well forwarded to the end
Changeset
=> feat(fonts): update unifont

.changeset/tender-pugs-chew.md, packages/astro/package.json, packages/astro/test/fonts.test.js, pnpm-lock.yaml
- https://github.com/unjs/unifont/pull/171 impacts us
Manual
Changeset
=> fix(fonts): upstream unifont unicode range

.changeset/fuzzy-laws-kick.md, packages/astro/components/image.css
The "simplified" responsive image styles simpified things a bit far, and was causing the images to not correctly maontain aspect ratio in some cases. This PR adds `height: auto` back in, which fixes it
Fixes #13709
Tested manually. This shows we need e2e tests for images.
=> fix: set height: auto for responsive images

.changeset/tangy-eagles-train.md, packages/integrations/react/src/server-v17.ts, packages/integrations/react/src/server.ts, packages/integrations/svelte/src/server.ts, packages/integrations/vue/src/server.ts
- Closes #13712
- When migrating integrations to TS recently, the types were not 100% correct which could cause issues when using renderers with the Container API
Build should pass
Changeset
=> fix: renderers types

.changeset/bright-breads-report.md, packages/astro/types/content.d.ts
Previously `BaseSchema` used recursive type definitions to try to define "any Zod object, or wrapper type that contains objects". This contained self-referencing types that collapsed to `any`, meaning there was no typechecking for schema defintions. #13706 fixed that by refactoring out the self-references. However this caused Starlight typechecks to fail (and presumably other sites). At its core, this is because Zod types are inherently recursive, so it's impossible to accurately type them without using recursive types, unless you manually define an arbitrary number of depth of reference. There will always be another layer of abstraction that some user (or more likely integration or library) wants to create.
This PR throws it all away, and simply types `BaseSchema` as `ZodType`. This is …
=> fix: loosen the BaseSchema type

.changeset/thin-regions-know.md, packages/astro/src/content/loaders/file.ts
- remove todo comments
- **Replaced generic `Error` throws with `AstroError`** in `packages/astro/src/content/loader/file.ts`.
- Adds contextual error names and messages:
- `Glob Pattern Error` for disallowing `*` in `file()` loader paths.
- `Parser Not Found` when no parser is available for the file extension.
- Imports `AstroError` from `core/errors` so all runtime errors funnel through our unified error-handling layer.
- **Changeset included** (`pnpm exec changeset`) to surface in release notes.
- Ran the full test suite: `pnpm test` – all existing tests pass.
- Manual sanity check:
1. Created a sample project with a bad `data/*.json` glob; verified the new *Glob Pattern Error* message surfaces in the terminal with the Astro error banner.
2. Pointed the loader to an `.xml` file; saw …
=> refactor(astro): Replaced generic `Error` throws with `AstroError`

.changeset/smart-jokes-hide.md, examples/ssr/src/api.ts
- remove todo comment
- **Renamed helper**  
`get<T>` → `getJson<T>` to clarify that the helper always returns parsed JSON.
- **Timeout & abort support**  
Adds an `AbortController` with a 10 s default timeout to prevent hanging requests.
- **Richer error messages**  
* Distinguishes HTTP errors (`GET /api … → 503`) from network/abort errors (`failed: The user aborted a request`).  
* Includes status text for quicker debugging.
- **Less boilerplate**  
Helper now returns `response.json()` directly, so the four public API functions no longer need their own inline callbacks.
- **No functional change to callers**  
Signatures of `getProducts()`, `getProduct()`, `getUser()`, and `getCart()` remain identical; only internal implementation is updated.
- **Changeset included**  
`pnpm exec …
=> refactor(example): remove todo comment and normalize network errors

.changeset/mean-lands-pull.md, packages/astro/src/assets/fonts/logic/normalize-remote-font-faces.ts, packages/astro/test/units/assets/fonts/logic.test.js
- Closes #13754
- Some remote font providers return protocol relative URLs (starting with `//`), which are then considered absolute by the font fetcher and fails
- Now when we normalize remote font data, we default this kind of URL to `https`
Unit + manual
Changeset
=> fix(fonts): relative protocol urls

packages/astro/src/core/errors/errors-data.ts
- Improves [error page](https://deploy-preview-11635--astro-docs-2.netlify.app/en/reference/errors/cannot-determine-weight-and-style-from-font-file/)
=> feat(fonts): improve error

.changeset/calm-drinks-beg.md, packages/db/src/runtime/db-client.ts, packages/db/test/unit/db-client.test.js
This PR ensures proper params are being parsed and sent to the libsql Client, due to URLSearchParams being a `Record<string, string>` this object requires parsing to ensure the values are being parsed to number or boolean.
See https://discord.com/channels/830184174198718474/1370190284855705680 for context.
Added a new unit test for ensuring the URL parsing is correct in various circumstances.
This PR corrects internal logic to reflect the information on the docs.  No docs changes needed.
=> Fix(db): update db-client connection options parsing

packages/astro/src/assets/fonts/README.md
- Updates README to explain how the feature is structured
N/A
N/A
=> chore(fonts): document

.changeset/silent-states-shout.md, packages/db/src/runtime/index.ts
Now that Astro Studio has sunset, `db.transaction()` which has been previously un-typed, can now once again be typed. this PR removes the Omit<> that removes the transaction type from the DB client.
No functional changes have been made, only type changes
No docs are needed as there is no functional change, but could be included now that transactions are properly typed.
=> feat(db): Enable transaction types

.changeset/soft-memes-sin.md, packages/astro/src/assets/fonts/constants.ts, packages/astro/src/assets/fonts/definitions.ts, packages/astro/src/assets/fonts/implementations/url-proxy.ts, packages/astro/src/assets/fonts/implementations/url-resolver.ts, packages/astro/src/assets/fonts/vite-plugin-fonts.ts, packages/astro/test/fonts.test.js, packages/astro/test/units/assets/fonts/implementations.test.js, packages/astro/test/units/assets/fonts/orchestrate.test.js
- Closes #13779
- Updates the vite plugin to take `config.build.assets` and `config.build.assetsPrefix` into account. This required updating most paths handling as it was not robust enough
- Refactors the fixture test
- Updates existing unit tests
- Adds unit tests
- Refactors the fixture tests
- Adds fixture tests
- Manually tested
Changeset
=> fix(fonts): take build config into account

CONTRIBUTING.md
- This fixes the newlines and unsupported list syntax in the mermaid diagram in the CONTRIBUTING.md file. Seemed like a tiny change, unnecessary to open an issue for.
```mermaid
graph TD;
start{Followed issue\ntemplate?}
start --NO--> close1[Close and ask to\nfollow template]
start --YES--> dupe{Is duplicate?}
dupe --YES--> close2[Close and point\nto duplicate]
dupe --NO--> repro{Has proper\nreproduction?}
repro --NO--> close3[Label: 'needs reproduction'\nbot will auto close if no update\nhas been made in 3 days]
repro --YES--> real{Is actually a bug?}
real --NO--> maybefeat{Is it a feature request?}
maybefeat -- YES --> roadmap[Close the issue.\n Point user to the roadmap.]
maybefeat -- NO --> intended{Is the intended\nbehaviour?}
intended --YES--> explain[Explain and close\npoint to …
```
=> [syntax-fix] Line breaks and lists in mermaid diagram in CONTRIBUTING.md

packages/astro/test/units/assets/fonts/orchestrate.test.js
- Test is failing on main on windows 22. This PR fixes the affected test (it's once again caused by paths)
=> fix(fonts): windows test

.changeset/petite-rockets-relax.md, packages/astro/components/Font.astro
- In #13674, I updated the vite plugin to return en empty module if the fonts are not enabled. This caused the error in the Font component not to be thrown because the module always exists
- Now, I check if `fontsData` is properly set
Manual
Changeset
=> fix(fonts): properly throw error

.changeset/forty-peaches-talk.md, packages/integrations/cloudflare/src/entrypoints/image-service.ts, packages/integrations/cloudflare/src/utils/assets.ts, packages/integrations/netlify/src/image-service.ts
- Uses the `isESMImportedImage` function from the core package
- Removes inconsistent resolution of imported images
- Fixes https://github.com/withastro/astro/issues/13722
Existing tests should cover it
It's a fix
=> Unify isESMImportedImage in image service adapters

.changeset/fine-needles-send.md, packages/integrations/netlify/src/index.ts
Replaces the set constant `./dist/` with the output directory option from `AstroConfig.outdir` in the netlify integration.
Closes #13726 
Simple fix to a previously set constant. No additional tests were required.
Doesn't need documentation, since it is a simple patch.
=> fix: respect the outdir option in the netlify integration

packages/astro/src/actions/runtime/utils.ts, packages/astro/src/core/app/types.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/core/config/schemas/base.ts, packages/astro/src/core/config/schemas/refined.ts, packages/astro/src/core/csp/common.ts, packages/astro/src/core/csp/config.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/core/middleware/index.ts, packages/astro/src/core/render-context.ts, packages/astro/src/runtime/server/render/csp.ts, packages/astro/src/types/public/config.ts, packages/astro/src/types/public/context.ts, packages/astro/src/types/public/internal.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/astro/test/csp.test.js, packages/astro/test/units/config/config-validate.test.js
This PR adds support for additional directives inside the `<meta>` tag. As for now, Astro is only responsible for customising the `script-src` and `style-src` directives, however other directives aren't provided.
A user can always provide additional directives via the `Response` header; however, to avoid the use of multiple values (Response headers and meta data), and incurr in situations where the browser picks a different directive, Astro now allows user to add additional directives, which will be eventually rendered in the meta tag.
There's a very tiny level of validation, where if directives start with `script-src` or `style-src`, we throw an error. 
We will provide additional configurations in case users need to customise `script-src` and `style-src` directives.
To note that I …
=> feat(csp): allow additional directives

packages/astro/src/content/runtime.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/types/public/content.ts, packages/astro/test/fixtures/live-loaders/src/live.config.ts
Adds support for returning a `cacheHint` object with entries and collections. This can be used to suggest cache tags or ttl for the data, and in future could be integrated with route caching
Added new error for invalid cache hints
=> feat: add cache hint support to live loaders

package.json
This updates the `lint` check, and runs `knip` before `eslint`. The `eslint` is the slowest of checks, so it's best to run the fastest ones first to get a quicker feedback on CI
=> chore: check `knip` first

packages/astro/e2e/fixtures/view-transitions/astro.config.mjs, packages/astro/src/core/app/types.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/core/config/schemas/base.ts, packages/astro/src/core/config/schemas/refined.ts, packages/astro/src/core/csp/common.ts, packages/astro/src/core/csp/config.ts, packages/astro/src/core/encryption.ts, packages/astro/src/core/render-context.ts, packages/astro/src/runtime/server/render/csp.ts, packages/astro/src/types/public/config.ts, packages/astro/src/types/public/internal.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/astro/test/csp.test.js, packages/astro/test/types/define-config.ts, packages/astro/test/units/config/config-validate.test.js
This PR implements the following chapter of the RFC: https://github.com/withastro/roadmap/blob/feat/rfc-csp/proposals/0055-csp.md#customize-the-script-src-and-style-src-directives
Changes:
- The schema and validation of the hashes is now done via `z.custom`, which provides runtime validation and a better type check
- I did some internal renaming
- I refactored the code in order match the RFC. In the RFC I changed the structure of the configuration. From having `styleHashes` and `styleResources`, we now have `styleDirective.hash` and `styleDirective.resources`
I updated the validation test, since now we don't raise a custom message anymore.
Added new integration tests and updated the current ones.
=> feat(csp): resources for script and styles directives

.changeset/loud-brooms-kick.md, packages/integrations/netlify/src/image-service.ts
Fixes incorrect URL generation for SVGs with imageCDN enabled, for the netlify adapter. Fixes #13796 
- Adds a check for SVG images in `astro/packages/integrations/netlify/src/image-service.ts` to handle the return of the original `src` path for them.
- No specific tests were added since this is a fix between the image service logic of the netlify adapter, and existing tests should be enough.
- It was manually tested on a separate project, similar to how #13679 was handled.
It's an internal bug fix for the netlify adapter and should not need any documentation.
=> fix(@astrojs/netlify): Handle SVGs properly with imageCDN enabled

packages/astro/src/actions/runtime/utils.ts, packages/astro/src/core/app/types.ts, packages/astro/src/core/config/schemas/base.ts, packages/astro/src/core/csp/common.ts, packages/astro/src/core/csp/config.ts, packages/astro/src/core/middleware/index.ts, packages/astro/src/core/render-context.ts, packages/astro/src/runtime/server/render/csp.ts, packages/astro/src/types/public/config.ts, packages/astro/src/types/public/context.ts, packages/astro/test/csp.test.js, packages/astro/test/fixtures/csp/src/pages/scripts.astro, packages/astro/test/fixtures/csp/src/pages/styles.astro
This PR applies two main changes
I changed the way directives are passed: https://github.com/withastro/roadmap/blob/feat/rfc-csp/proposals/0055-csp.md#provide-additional-directives
Now it's a string, which is validated using a custom zod schema, and provides good safety in the editor.
RFC has been updated to match the implementation: https://github.com/withastro/roadmap/blob/feat/rfc-csp/proposals/0055-csp.md#runtime-apis
Here, we are doing **something new** that our runtime engine didn't support: allow to change `SSRResult` during the rendering. 
To provide such a level of mutation, I had to **save** the `SSRResult` inside the `RenderContext` class. This allows for the manipulation of information that belongs only to the route being rendered. I tried to manipulate `manifest.csp`, but …
=> feat(csp): runtime APIs

.changeset/cyan-doodles-wish.md, packages/astro/src/core/logger/vite.ts
ignore lightningcss unsupported pseudo-class warning. fixes #13658
there's no testing for logger
no need to updated docs, no affect on user’s behavior
=> ignore lightningcss global pseudo-class warning

.changeset/sixty-carrots-pick.md, packages/integrations/node/src/preview.ts
Handles module not found errors thrown when importing the `dist/server/entry.mjs` file. If the file itself is missing, the existing error will still be thrown
Manually. This was replicated by modifying a build output to import a missing package.
N/A
=> Handle module not found errors in server entrypoint

.changeset/silent-planes-show.md, packages/astro/e2e/dev-toolbar.test.js, packages/astro/e2e/fixtures/dev-toolbar/src/pages/tooltip-position.astro, packages/astro/src/runtime/client/dev-toolbar/apps/audit/ui/audit-list-window.ts
This fixes pop-ups and highlights rendering over the audit list window. 
Fixes #11114 
Added e2e test.
=> fix: audit list window covered by tooltip and highlight

.changeset/real-tigers-like.md, packages/astro/src/runtime/client/dev-toolbar/apps/settings.ts
The problem was the the content of the toolbar settings overflowed the toolbar. That made it very hard to read the text it looked broken.
I did a few things:
1. The text of the last row takes up the whole width of the section
2. If the content is still too large, the developer can scroll the content of the toolbar
https://github.com/user-attachments/assets/d188cb2a-c061-40f2-8432-d55d88ec5a53
I did some manual testing, by resizing the window and testing the changes on a real iPhone. I did not any automated tests, because there's now way to test this without a visual test. Please correct me if I'm wrong.
This change does not need documentation, it doesn't change how users
need to interact with Astro.
=> fix(astro): stop toolbar settings from overflowing

.changeset/fruity-pugs-cross.md, packages/astro/package.json, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/core/session.ts, pnpm-lock.yaml
Ponyfills `import.meta.resolve`, because it's behind a flag in Node.js 20.3-20.5. The `import-meta-resolve` package is already a dep of `@astrojs/markdown-remark`. We can't use it at runtime because of node builtins, so we split it into different functions, where the runtime one doesn't resolve the name and we import it directly. It's only important at build time, as it allows us to bundle the driver.
Fixes #13800
Session tests pass. Tested with Node 20.4
=> fix: ponyfill import.meta.resolve

packages/astro/e2e/dev-toolbar.test.js
This PR skips the test introduced in https://github.com/withastro/astro/pull/13373/
It seems that the PR https://github.com/withastro/astro/pull/13383 caused some regressions
e2e should pass
=> test: skip test due to some regression

packages/astro/src/core/app/types.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/core/config/schemas/base.ts, packages/astro/src/core/csp/common.ts, packages/astro/src/core/render-context.ts, packages/astro/src/runtime/server/render/csp.ts, packages/astro/src/types/public/config.ts, packages/astro/src/types/public/context.ts, packages/astro/src/types/public/internal.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/astro/test/csp.test.js
This PR implements the `strictDynamic` field from the RFC
=> feat(csp): add script-dynamic keyword support

.changeset/slick-pillows-smash.md, packages/astro/src/runtime/server/render/astro/instance.ts, packages/astro/test/units/render/rendering.test.js
- Closes #13856
- The check was too loose, because there are internal props starting with `client:`
Manually
Changeset
=> fix: client directive on astro component warning

.changeset/open-tables-sit.md, packages/astro/src/assets/vite-plugin-assets.ts, packages/astro/src/core/config/schemas/base.ts, packages/astro/src/types/public/config.ts, packages/astro/test/core-image-layout.test.js
Allows disabling default styles for responsive images
This change adds a new `image.experimentalDefaultStyles` option that allows you to disable the default styles applied to responsive images. 
When using experimental responsive images, Astro applies default styles to ensure the images resize correctly. In most cases this is what you want – and they are applied with low specificity so your own styles override them. However in some cases you may want to disable these default styles entirely. This is particularly useful when using Tailwind 4, because it uses CSS cascade layers to apply styles, making it difficult to override the default styles.
Adds tests
Adds docs for the new option. Needs an update to the main responsive image flag docs.
=> feat: allow disabling of default responsive image styles

.changeset/huge-islands-fold.md, packages/astro-rss/src/index.ts, packages/astro-rss/test/rss.test.js
Adds the `type="text/xsl"` attribute to xml-stylesheet processing instruction in rss when passing an xslt stylesheet.
Fixes #13866
Add test `should include xml-stylesheet instruction with xslt type when stylesheet is set to xslt file` which is based of `should include xml-stylesheet instruction with xsl type when stylesheet is set to xsl file` in the same file.
Do a string includes assert to have this processing instruction since the parser used (xml2js) doesn't process processing-instruction. See issue here: https://github.com/Leonidas-from-XIV/node-xml2js/issues/339. Should change parser or add extra tests for processing instructions.
Could update the docs to highlight which stylesheets are supported. Looking at the tests:
https://github.com/withastro/astro/blob/de2fc9b3c406c21683b8a692f …
=> Fix missing type-attribute in xml-stylesheet with xslt extension

packages/astro/src/core/config/merge.ts, packages/astro/src/types/public/config.ts
- Removes astro db related code, which is unused
N/A
I don't think this needs a changeset because this stuff was internal
=> chore: clean db specific code

.changeset/silly-peas-smash.md, packages/astro/e2e/fixtures/server-islands/src/pages/index.astro, packages/astro/e2e/server-islands.test.js, packages/astro/src/runtime/server/render/server-islands.ts
- Fixes fallback not being removed/deleted when server island is rendered.
- Fixes #13895
- Tested locally
- Added E2E test to check that fallback does not exist after server island renders
Bugfix, no new features or changes
=> fix: server island fallback not being deleted

.changeset/shy-showers-care.md, packages/astro/e2e/view-transitions.test.js, packages/astro/package.json, pnpm-lock.yaml
Updates compiler and reactivates some view transition e2e tests 
Fixes https://github.com/withastro/compiler/issues/1079
Reactivates skipped view transition e2e tests 
n.a.: bug fix.
=> bug fix for lost view transition names introduced by 5.9.0

.changeset/open-melons-start.md, packages/astro/e2e/fixtures/vite-virtual-modules/astro.config.mjs, packages/astro/e2e/fixtures/vite-virtual-modules/package.json, packages/astro/e2e/fixtures/vite-virtual-modules/src/pages/index.astro, packages/astro/e2e/fixtures/vite-virtual-modules/src/plugins/virtual.ts, packages/astro/e2e/vite-virtual-modules.test.js, packages/astro/src/core/util.ts, packages/astro/src/vite-plugin-astro-server/css.ts, pnpm-lock.yaml
fixes #13879
Converts `\0virtual:module.css` to `/@id/__x00__virtual:module.css`, this is the direct reversal of the `unwrapId` function in `core/utils.ts`
The `vite-virtual-modules` e2e test has been added.
This tests if the dev server response contains `style` and `script` tags with proper `data-vite-dev-id` and `src` values respectively.
This is a correctness change in the internal vite-astro-server plugin which does not have public facing documentation.
=> feat(vite-server): handle vite virtual module ids

.changeset/cold-views-mix.md, packages/astro/src/core/app/index.ts
When Astro serves an error page, it may use `fetch` to retrieve the prerendered error document from the origin that serves the original request. The returned error page is then forwarded to the client.
This PR drops the `Content-Encoding` and `Content-Length` headers from the forwarded response. This is because `fetch` implementations will return a decoded body in the body property. When the upstream `Content-Encoding` and `Content-Length` headers are added to that decoded response, a mismatch is created (e.g. plain text served with a `gzip` header). The browser will then try to decode the plain text as `gzip` and fail, pictured below is a failure to decode a 404 page:
*This PR allows Astro to successfully serve the error page even when the error document was compressed.* This is …
=> fix(errors): handle servers returning error docs with compression

.changeset/sharp-vans-greet.md, packages/astro/src/core/routing/manifest/create.ts, packages/astro/test/fixtures/static-redirect/astro.config.mjs, packages/astro/test/fixtures/static-redirect/package.json, packages/astro/test/fixtures/static-redirect/src/middleware.ts, packages/astro/test/fixtures/static-redirect/src/pages/index.astro, packages/astro/test/static-build.test.js, pnpm-lock.yaml
Closes #13875
Previously, `isPrerendered` would be `false` in statically built configured redirects (notably in middleware).
I added a test, happy to expand or reorganize. Additionally I've run the full test suite locally and I don't have any new failures (rosetta + devcontainers likely the culprit #12704).
This is a fix, so I don't think docs are necessary?
=> fix: isPrerendered now set correctly in static configured redirects.

.changeset/huge-crabs-remain.md, .changeset/silver-windows-accept.md, .changeset/sixty-icons-camp.md, .changeset/sweet-hotels-cross.md, packages/astro/test/csp.test.js, packages/integrations/cloudflare/src/index.ts, packages/integrations/netlify/package.json, packages/integrations/netlify/src/index.ts, packages/integrations/netlify/test/static/fixtures/static-headers/astro.config.mjs, packages/integrations/netlify/test/static/fixtures/static-headers/package.json, packages/integrations/netlify/test/static/fixtures/static-headers/src/components/Island.astro, packages/integrations/netlify/test/static/fixtures/static-headers/src/pages/index.astro, packages/integrations/netlify/test/static/static-headers.test.js, packages/underscore-redirects/src/astro.ts, packages/underscore-redirects/src/host-route.ts, packages/underscore-redirects/src/index.ts, packages/underscore-redirects/src/print.ts, packages/underscore-redirects/test/print.test.js, packages/underscore-redirects/test/weight.test.js, pnpm-lock.yaml
This PR adds support for static headers for the Netlify adapter. The initial implementation supports the experimental CSP feature. In the future, this may change, and we will update the documentation as needed.
To implement the feature, I had to make some breaking changes within `underscore-redirects`. The package is mostly for internal usage, so we don't have strong documentation and it's mostly for our needs, so the changesets are mostly technical. 
The functionality for redirects must stay the same. 
The printing logic has been removed from `Redirects`, instead consumers need to use `printAsRedirects` instead. The core functionality hasn't changed much, it now accounts for `.target`, because it's now optional.
The function that creates `config.json` is now called in the …
=> feat(netlify): add experimental support for static headers

.changeset/neat-worlds-hide.md, packages/astro/src/core/config/schemas/base.ts, packages/astro/src/core/session.ts, packages/astro/src/types/public/config.ts, packages/integrations/cloudflare/test/sessions.test.js
Currently the session config object is optional, but if provided it must have a driver specified. This caused issues when trying to provide custom configuration to an automatically-provided session driver, such as Cloudflare or Netlify. This PR makes the value optional. It still validates that a driver has been provided once it is first used, so this will catch cases where no driver is provided by either the user or the adapter.
Makes the session driver name optional in config. 
Fixes #13920
Added a test case
=> fix: make session driver name optional

.changeset/sixty-nights-drive.md, packages/astro/src/runtime/client/dev-toolbar/apps/astro.ts
- Closes #13841
- A browser extension could block a script we inject, breaking the devtoolbar
- This PR handles the case where `__astro_dev_toolbar__` is not set
N/A. Couldn't get the user to test it
Changeset
=> fix: devtoolbar data unset

.changeset/curly-masks-retire.md, packages/integrations/vercel/package.json, packages/integrations/vercel/src/index.ts, packages/integrations/vercel/test/fixtures/static-headers/astro.config.mjs, packages/integrations/vercel/test/fixtures/static-headers/package.json, packages/integrations/vercel/test/fixtures/static-headers/src/components/Island.astro, packages/integrations/vercel/test/fixtures/static-headers/src/pages/index.astro, packages/integrations/vercel/test/static-headers.test.js, pnpm-lock.yaml
Very similar to https://github.com/withastro/astro/pull/13952, it adds support for static headers in the Vercel adapter
The changeset is a copy-past from the netlify one, updated to use the vercel adapter. 
=> feat(vercel): experimental static headers

.changeset/stale-donkeys-bake.md, packages/astro/src/actions/integration.ts, packages/astro/src/actions/utils.ts, packages/astro/src/integrations/hooks.ts
- Closes #13903
- Instead of hardcoding what path to use, we grab the matched action filename and use directly
Manually
Changeset
=> fix: actions typegen path

packages/astro/src/types/public/config.ts
Some improvements to the config reference docs for responsive images becoming stable were made in the docs PR itself. This should align the source with those docs. (Reorders entries, adds external links for CSS properties, formatting syntax - nothing fundamentally affecting documentation. Should not require a rerelease.)
It's JSDoc for docs generation... we're just hoping it works!
To match live docs.
=> Updates image config ref docs for responsive images to match live docs

.changeset/legal-facts-teach.md, examples/blog/src/content/blog/markdown-style-guide.md, packages/astro/src/content/runtime.ts
- Closes #13221
- The dev toolbar relies on the `data-image-component` attribute for an audit
- In content collections md/mdx files, images are not created using the `<Image />` component so the attribute was not set in dev
Manually
Changeset
=> fix: toolbar image audit in content collections

.changeset/small-knives-feel.md, packages/astro/src/core/dev/restart.ts
This PR adds a small message that is shown in dev mode when users use CSP.
/cc @withastro/maintainers-docs for feedback! 
I would appreciate some feedback around the nature of the message. I decided to use info severity. Should we use warning?
=> fix: add info message in dev

.changeset/blue-olives-itch.md, packages/astro/src/types/public/context.ts
- Changes the example return values in the doc string for `Astro.routePattern` to have correct values.
- Manually tested by creating routes in an example project with the paths specified as examples in doc string for `Astro.routePattern` and checked the return value.
- Doesn't need changes since it is only a docstring change.
=> fix invalid examples in `Astro.routePattern` docstring

.changeset/petite-turtles-leave.md, packages/astro/src/content/config.ts, packages/astro/src/content/utils.ts, packages/astro/test/fixtures/live-loaders/src/live.config.ts
Now that live content collections are defined using a different function we can remove the requirement for type: 'live' to be set. Instead I have added error checks to ensure the wrong loader type isn't used.
Updated fixture.
I will do a docs PR
=> Make "type" optional when defining live collections

.changeset/rare-spies-join.md, packages/astro/src/core/app/pipeline.ts, packages/astro/src/core/build/pipeline.ts, packages/astro/src/core/render-context.ts, packages/astro/src/core/routing/rewrite.ts, packages/astro/test/fixtures/i18n-routing-fallback-rewrite-hybrid/astro.config.mjs, packages/astro/test/fixtures/i18n-routing-fallback-rewrite-hybrid/package.json, packages/astro/test/fixtures/i18n-routing-fallback-rewrite-hybrid/src/pages/[slug].astro, packages/astro/test/fixtures/i18n-routing-fallback-rewrite-hybrid/src/pages/about.astro, packages/astro/test/fixtures/i18n-routing-fallback-rewrite-hybrid/src/pages/es/index.astro, packages/astro/test/fixtures/i18n-routing-fallback-rewrite-hybrid/src/pages/index.astro, packages/astro/test/i18n-routing.test.js, pnpm-lock.yaml
- Fixes i18n fallback rewrites in server mode: i18n fallback rewrites (e.g., /es/about → /about) now work correctly when using SSR adapters with output: "server"
- Updates route matching for server builds: Server builds place static files in a client/ subdirectory, which was causing route matching to fail. Now uses the correct output directory based on build mode
- Allows i18n fallback rewrites in ForbiddenRewrite check: The safety check that prevents rewriting from SSR routes to static routes now correctly identifies and allows i18n fallback scenarios. This was required for dev mode, where the initial matched route for i18n fallbacks is 404 page (dynamic)
**Before**: /es/about-us with i18n fallback would throw ForbiddenRewrite: You tried to rewrite the on-demand route with the static …
=> fix i18n fallback rewrites failing in server mode

.changeset/great-sloths-rule.md, packages/astro/src/runtime/server/render/server-islands.ts, packages/astro/test/fixtures/server-islands/ssr/src/pages/fragment.astro, packages/astro/test/fixtures/server-islands/ssr/src/pages/named-fragment.astro, packages/astro/test/server-islands.test.js, pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/13969
This is a "weird" fix. When rendering the server island inside a fragment, the `init` function (where we calculate content and hostId, the undefined info of the issue)  is called after the `render` function. So put the generation of `hostId` and `islandContent` inside a shared function, and saved it inside the class.
Here's the weird part: when calling `render`, the `props` are correctly present and evaluated. However, and `init` is called, the props aren't there anymore. I'm not sure if this is a bug coming from somewhere else, or that's the expected behaviour.
As a workaround, I created two new functions where we save these props inside the class. Doing so fixes the bug and the rest of the tests keep passing. Still, it's weird
Added …
=> fix(render): server islands in fragments

.changeset/smart-mirrors-eat.md, packages/astro/e2e/fixtures/view-transitions/src/pages/skip.astro, packages/astro/e2e/view-transitions.test.js, packages/astro/src/transitions/events.ts, packages/astro/src/transitions/router.ts
Fallback view transition animations for browsers that do not support the View Transition API were running too early when using  `ClientRouter`. Specifically, the exit animation for the current page during navigation would run before the `astro:before-swap` event, even though it should run after it (but before the actual swap).
This bug only affects browsers that do *not* support the View Transition API and was first discovered in #14034 (the original issue was about navigating to self, but discussion led to finding this bug). The consequence of the bug is that calling `.skipTransition()` in the `astro:before-swap` event would only skip the *enter* animation of the new page, but not the *exit* animation of the current page — this is inconsistent with browsers that *do* support native view …
=> fix: run fallback view transition for old page only after dispatching `astro:before-swap` event

.changeset/great-pugs-find.md, packages/astro/src/assets/utils/vendor/image-size/types/heif.ts
- add `avis` brand for animated avif file
Manually tested using animated avif file
=> fix(astro): add support for 'avis' brand in HEIF

.changeset/easy-animals-glow.md, .changeset/fifty-pets-knock.md, packages/integrations/netlify/package.json, packages/integrations/netlify/src/index.ts, packages/integrations/netlify/test/development/fixtures/primitives/astro.config.mjs, packages/integrations/netlify/test/development/fixtures/primitives/src/pages/astronaut.astro, packages/integrations/netlify/test/development/primitives.test.js, pnpm-lock.yaml
This PR tackles a couple of issues that came up with the Netlify adapter's Vite plugin dev mode features.
First, the Vite plugin was injecting env vars from linked Netlify sites. This is nice DX, but is a change that could surprise peopel - suddenly their dev environment had variables they weren't expecting, which could mess with their local setup.
Second, remote images were broken in the image CDN. The local image server didn't take account of the permitted remote image domains injected by Astro during the build, meaning all remote images were shown as forbidden. 
The fixes:
- Added a new `devFeatures` option to the adapter config to allow enabling or disabling features
- Environment variables now default to disabled - You need to explicitly opt in with `devFeatures: { …
=> fix: regressions in Netlify adapter

.changeset/fuzzy-laws-feel.md, packages/astro/src/types/public/config.ts
This fixes a bug that caused a type error when trying to define session options without a named driver (e.g. if there's a default added by an adapter). The fix was a weird (but documented) TS fix, which involved wrapping the conditionals in tuples. See https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types
Closes #14090
Bug fix
=> fix: session options type fix

.changeset/fluffy-seas-shine.md, packages/astro/src/assets/types.ts, packages/astro/test/core-image.test.js, packages/astro/test/fixtures/core-image-ssg/src/pages/index.astro, packages/astro/test/fixtures/core-image/src/pages/index.astro
The `priority` prop used to be only available for responsive images, but since they moved to stable we allow it for any image. However the types were not updated, meaning there would be errors if you tried to use the prop with non-responsive props such as `densities`.
This PR moves `priority` to shared props
Fixes #14086
=> fix: move priority prop to shared image props

.changeset/stale-knives-rhyme.md, packages/astro/src/assets/vite-plugin-assets.ts
- Fixes a build failure that occurs when an integration enables the `imageService` option.
- Prevents the core assets Vite plugin from resolving server-only image service entrypoints during the client build.
- The plugin now checks for `options.ssr` and resolves to a `noop` service for client builds, stopping Node.js built-ins from leaking into the client pipeline.
- 
Fixes #14056. Fixes #14099.
This change was tested locally using the reproduction repository provided in issue #14056.
1.  Linked the local, patched `astro` package to the reproduction project.
2.  Enabled `imageService: true` in the `astro.config.mjs` via the `@astrojs/vercel` adapter.
3.  Ran `pnpm build`.
4.  The build completed successfully, whereas it previously failed. All warnings related to Node.js modules being …
=> fix(astro): prevent image service resolution on client build

.changeset/giant-adults-fry.md, packages/astro/client.d.ts
Added a simple `declare module` definition to get rid of TypeScript errors for Vite's `'...?no-inline'` import feature.
The typing is currently only defined for `'...?url&no-inline'` imports, but not for `'...?no-inline'` imports, for some reason.
> Note: The two errors reported on `client.d.ts` are from lines 182 and 189 - pretty unrelated to my change.
Manually modified the minimal example from `/examples/minimal` to import the SVG favicon with `'...?no-inline'`. Then checked the output of `astro check` before and after my change.
No unit tests or other forms of scripted tests were added, since I didn't find any for the already existing module declarations. Let me know in case I should add tests and how.
Since the current module declarations don't have specific docs either, except for …
=> fix(astro): add module declaration for `?no-inline` asset imports

.changeset/few-rules-lose.md, packages/astro/src/cli/throw-and-exit.ts
Currently we skip the exit error handling for config Zod errors, because it has already logged an error message. However it also skips the exit code handling, meaning it will appear to scripts that the command has succeeded.
This PR still skips the error logging and telemetry, but does `process.exit(1)` so that the command exits as an error
Fixes #13994
=> fix: exit with non-zero code for Zod errors

.changeset/cruel-pandas-wonder.md, packages/astro/src/jsx-runtime/index.ts, packages/integrations/mdx/test/fixtures/mdx-page/src/components/KeyTest.astro, packages/integrations/mdx/test/fixtures/mdx-page/src/pages/index.mdx, packages/integrations/mdx/test/mdx-page.test.js
The "key" prop is special in JSX, so when MDX compiles to JSX transforms it passes the key prop as the third argument for the JSX transform, rather than in the props record. This is expected when using React, because for React it *is* special. However with Astro it's a regular prop, and so was getting lost. This PR updates the Astro JSX transform to accept the key argument, and to add it to the props record.
Fixes #14010
Added a test to the MDX integration, though the fix is in the astro package.
The current magicness of `key` is undocumented, so this just makes it behave as expected.
=> fix: set key argument as prop in JSX transform

.changeset/floppy-shrimps-smile.md, packages/astro/src/assets/runtime.ts, packages/astro/test/core-image-svg.test.js, packages/astro/test/fixtures/core-image-svg/src/pages/serialize.json.ts
When SVG components were introduced, the metadata was attached to the component so that they were backwards-compatible with former usage. However because they are now component factories they're not serializable with JSON.stringify anymore. This is a particular issue when they are attached to content entries, which may be returned by an endpoint.
This PR adds a `toJSON` method to the component that returns just the metadata. This makes it serialisable again.
Fixes #13979
Added a test
=> fix: make SVG ImageMetadata serializable

pnpm-lock.yaml
Addressing this warning:
```
 WARN  Issues with peer dependencies found
packages/integrations/netlify
└─┬ @netlify/vite-plugin 2.4.1
└─┬ @netlify/dev 4.4.1
└─┬ @netlify/images 1.2.1
└─┬ ipx 3.0.3
└─┬ unstorage 1.15.0
└── ✕ unmet peer @netlify/blobs@"^6.5.0 || ^7.0.0 || ^8.1.0": found 10.0.5
```
`ipx` has dependency on `unstorage` that is not pinned, but `unstorage` version in lock file prevent using newer version that expanded `@netlify/blobs` peer range. 
Rely on existing tests. 
This is not user facing change, just repository level chore, so no changes impacting users here and therefore no docs changes.
=> chore: upgrade locked unstorage

.changeset/five-forks-guess.md, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/custom-500.test.js, packages/astro/test/fixtures/custom-500-middleware/astro.config.mjs, packages/astro/test/fixtures/custom-500-middleware/package.json, packages/astro/test/fixtures/custom-500-middleware/src/middleware.js, packages/astro/test/fixtures/custom-500-middleware/src/pages/500.astro, packages/astro/test/fixtures/custom-500-middleware/src/pages/index.astro, pnpm-lock.yaml
- Closes #13546
- Matches the behavior of `NodeApp#renderError`: if rendering `500.astro` fails, we try another time while disabling middleware in case the error is in the middleware
- We still log the error in the terminal anyways
Manually + fixture
Changeset
=> fix: show 500.astro if error occurs in middleware

.changeset/upset-pianos-sink.md, packages/integrations/node/src/serve-app.ts
Fixes #14136. A `set-cookie` header is now emitted when set by middleware (e.g. through `context.cookies` or implicitly by `context.session`) on routes that are not found.
Unfortunately, I wasn't able to get `pnpm run test` to work locally (same issue on my home and work computers and in and outside a devcontainer, some "cannot find module" thing). So, no new test, even though I'd like to add one.
Instead, I tested this by making this same change in a sample project's `node_modules`.
I'm not familiar enough with Astro's internals, so a question: Why is `app.render()` called with `req` in the 404 case and `request` in the happy case? Also, I wonder if `locals` should be passed in addition to `addCookieHeader`.
=> fix(node): emit set-cookie header from middlewares for not-found routes (#14136)

.changeset/stupid-ways-tie.md, packages/create-astro/src/shell.ts, packages/upgrade/src/shell.ts
Update to the new way the spawn command must be used, after the use of arrays was deprecated in Node.js 24 when the shell option is enabled, 
ref: https://nodejs.org/api/deprecations.html#DEP0190, https://github.com/nodejs/node/pull/57199 https://github.com/nodejs/help/issues/5063#issuecomment-3132899776
closes: #14139
Before:
After:
No changes to the documentation are needed, it's just a minor change.
=> fix: update spawn command to concatenate command and flags

CONTRIBUTING.md
- Fixes a typo in our issue triage guidance which mentions the wrong label
n/a
You bet
=> Fix issue label typo in issue triage docs

.changeset/purple-peaches-allow.md, packages/astro/src/assets/utils/transformToPath.ts, packages/astro/test/core-image.test.js, packages/astro/test/fixtures/core-image-ssg/src/pages/special-chars.astro
The filenames for transformed images is based on the source image filename and a hash of the transform. For local files this is fine, because rollup sanitises the filename when emitting the generated file. However for remote images, this is based on the remote image URL, which we are decoding, meaning any characters could be present. This caused #14026 because that used inferSize, but if it didn't it would've succeeded in the build but generated an image filename that could not be deployed to some platforms such as Netlify, which forbids `#` in deployed filenames.
This PR sanitizes the filename using the same regex as rollup, replacing special characters with undersocres. It also doesn't double-decode the URLs.
Fixes #14026 
Added tests, including uploading a test image to …
=> fix: sanitize generated image filenames

.github/PULL_REQUEST_TEMPLATE.md
We have [great docs on writing changesets](https://contribute.docs.astro.build/docs-for-code-changes/changesets/) but most people don't know that. This adds a link to the PR template. The ideal would be if we could link from the bot comment, but it doesn't seem to be customisable
=> chore: add link to changeset style guide in PR template

.changeset/rude-sites-heal.md, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/core/routing/manifest/prerender.ts, packages/astro/test/fixtures/redirects/src/pages/more/[dynamic]/[prerender].astro, packages/astro/test/redirects.test.js
Fixes https://github.com/withastro/astro/issues/14054
The issue was caused by the fact that when we generate the static redirect, the `prerender` flag was set to `false` for all redirect routes, when a server adapter is used. 
This PR now changes the logic that is used to check the presence of `export const pretender = true`. If the route has a `redirectRoute`, also that route has its `prerender` flag updated.
This is a safe assumption because before calling `getRoutePrerenderOption`, we provide the content of the destination route (AKA `route.redirectRoute`)
Added a new test case. Manually tested against the reproduction provided
N/A
=> fix(routing): static redirect with prerendered route

packages/astro/e2e/errors.test.js
Now a newer version of Vite is being used, and the test works correctly locally, so I want to see if it passes in CI to determine if it’s safe to re-enable it
=> test: enable test for style preprocess error line highlighting

.changeset/little-apples-serve.md, packages/db/src/core/schemas.ts, packages/db/src/runtime/index.ts, packages/db/src/runtime/types.ts
Adds support for enums on the text column for AstroDB
Not sure if there is a good way to test this, as per the [drizzle docs](https://orm.drizzle.team/docs/column-types/sqlite#text):
> You can define { enum: ["value1", "value2"] } config to infer insert and select types, it **won’t check runtime values**.
So i would assume it would need type testing similar to the [last PR](https://github.com/withastro/astro/pull/14186) I opened for db.
Currently there is no docs to specific features/options of the different columns, only ["shared options"](https://docs.astro.build/en/guides/integrations-guide/db/#columns)
If docs are required we should also be sure to document any other missing items from our schema.
=> feat(db): Adds enum support to text column

.changeset/eight-teeth-sniff.md, knip.js, packages/db/package.json, packages/db/src/runtime/types.ts, packages/db/src/runtime/virtual.ts, packages/db/test/types/table.ts, packages/db/test/types/tsconfig.json, pnpm-lock.yaml
Fixes type casting for text column and enum inference.
- Test Schema
- Before
- After
Implement type testing for tables
This fixes previously working behavior.
=> fix(db): Fix type casting for text column and enum handling

.changeset/plain-dragons-bow.md, packages/astro/src/core/config/schemas/base.ts, packages/astro/src/types/public/config.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/astro/test/chrome-devtools-workspace.test.js
Adds experimental support for auto-configuring [Chrome Devtools Workspaces](https://developer.chrome.com/docs/devtools/workspaces). 
When devtools are open, Chrome automatically requests `/.well-known/appspecific/com.chrome.devtools.json` to see if it can setup workspace config. This is a feature to make it easy to configure workspaces, that let users edit files directly in the browser and save them back to disk. See [this doc](https://chromium.googlesource.com/devtools/devtools-frontend/+/main/docs/ecosystem/automatic_workspace_folders.md#solution) for more info. Unfortunately this leads to lots of annoying console spam, so people tend to open issues against frameworks. Some (e.g. Nuxt) have implemented experimental features like this. Others (like SvelteKit) special-case the path to …
=> feat: add automatic chrome workspace handling

.changeset/kind-kids-listen.md, packages/astro/src/core/config/schemas/base.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/env/env-loader.ts, packages/astro/src/types/public/config.ts, packages/astro/test/astro-envs.test.js, packages/astro/test/fixtures/astro-envs/astro.config.mjs
- Replaces the `rawEnvValues` experimental flag by `staticImportMetaEnv`
- Instead of just disabling the coercion, this flag disables the replacement of `import.meta.env.X` by `process.env.X` if `process.env.X` is available during the build
Added test for the `process.env` replacement
Changeset + https://github.com/withastro/docs/pull/12105
=> feat: experimental static import.meta.env

.changeset/wet-brooms-take.md, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/astro/test/chrome-devtools-workspace.test.js
- Fixes the experimental automatic Chrome DevTools workspace folders support added in Astro 5.13.0
- #14122 added this but for some reason used a data format that did not match what Chrome is actually looking for.
- Chrome [documents their `com.chrome.devtools.json` format](https://chromium.googlesource.com/devtools/devtools-frontend/+/main/docs/ecosystem/automatic_workspace_folders.md#solution) like this:
```json
{
"workspace": {
"root": "/Users/foobar/Projects/my-awesome-web-project",
"uuid": "53b029bb-c989-4dca-969b-835fecec3717"
}
}
```
- Before this PR our endpoint was responding with:
```json
{
"version": "1.0",
"projectId": "53b029bb-c989-4dca-969b-835fecec3717"
"workspaceRoot": "/Users/foobar/Projects/my-awesome-web-project",
}
```
- These do not match 😁 
- This PR makes Astro …
=> Fix automatic Chrome DevTools workspace feature

.changeset/floppy-shoes-smell.md, packages/integrations/cloudflare/src/index.ts
The Cloudflare adapter currently logs a warning if it is used with a static build. However there are valid reasons to use it for static builds. Similar warnings have already been removed from other adapters.
Fixes #14236
=> fix(cloudflare): don't warn when using in static build

.changeset/wild-jeans-smash.md, packages/astro/e2e/actions-blog.test.js, packages/astro/e2e/fixtures/actions-blog/src/actions/index.ts, packages/astro/e2e/fixtures/actions-blog/src/components/ApplyForm.tsx, packages/astro/e2e/fixtures/actions-blog/src/pages/apply.astro, packages/astro/templates/actions.mjs
Addresses https://github.com/withastro/astro/issues/13528
Closes https://github.com/withastro/astro/issues/13528
- Fixes an issue where user actions could not be named apply (and, by extension, other function prototype names like call).
- Root cause: the proxy previously used objKey in target, which would return true even for properties on the function prototype chain.
- This meant that an action named apply conflicted with the function prototype’s .apply method and couldn’t be used.
- Updated the check to target.hasOwnProperty(objKey).
- Now only explicitly defined action properties are returned.
- Result: user actions can now safely be named apply.
- This change hid Function.prototype.valueOf, which Astro’s runtime internally relies on when invoking actions in progressive enhancement …
=> fix(astro): action named apply

.changeset/plenty-colts-hammer.md, packages/astro/src/vite-plugin-astro-server/request.ts, packages/astro/test/fixtures/ssr-trailing-slash/astro.config.mjs, packages/astro/test/fixtures/ssr-trailing-slash/package.json, packages/astro/test/fixtures/ssr-trailing-slash/src/pages/index.astro, packages/astro/test/ssr-trailing-slash.test.js, packages/astro/test/units/routing/trailing-slash.test.js, pnpm-lock.yaml
Closes: https://github.com/withastro/astro/issues/13736
When configuring Astro with:
- base: '/mybase'
- trailingSlash: 'never'
The Astro.url.pathname for the root route would return `/mybase/` (with trailing slash) instead of the expected `/mybase` (without trailing slash).
Before (Bug)
```js
// astro.config.mjs
{
base: '/mybase',
trailingSlash: 'never'
}
// In your Astro
Astro.url.pathname // Returns: '/mybase/' 🙅‍♂️(trailing slash not removed)
```
After (Fixed)
```js
// astro.config.mjs
{
base: '/mybase',
trailingSlash: 'never'
}
// In your Astro
Astro.url.pathname // Returns: '/mybase' 🙆‍♂️ (trailing slash correctly removed)
```
- Modified packages/astro/src/vite-plugin-astro-server/request.ts to apply trailing slash configuration after base path concatenation
- Added comprehensive …
=> fix(astro): Astro.url.pathname respects trailingSlash: 'never' with base path

.changeset/new-falcons-tickle.md, packages/integrations/vercel/src/image/build-service.ts, packages/integrations/vercel/test/fixtures/image/src/pages/index.astro, packages/integrations/vercel/test/image.test.js
The Vercel image CDN requires that widths are from a configured list – requesting any other will give an error. The image service does this in most cases, except when the source image is smaller than the requested size. The default getSrcSet clamps the width, ensuring that no sizes are requested larger than the source image, instead requesting the actual image size if a larger size is requested. This is correct for most services except Vercel, which requires us to request the larger breakpoint from the allowlist, for which it will return the original size. 
This PR implements a custom getSrcSet for the Vercel image service that ensures the widths are always from the allowlist.
Fixes #14250
Added tests
=> fix(vercel): ensure srcset widths are always from configured list

.changeset/angry-eels-unite.md, packages/astro/src/transitions/router.ts
in #9419 we started to keep copies of pointers to the history functions to fix an issue with Partytown (#8862).
This change reverts it.
Fixes #14282
Exiting tests succeed.
Will do a snapshot release.
n.a.
=> revert history function caching

packages/integrations/tailwind/CHANGELOG.md, packages/integrations/tailwind/README.md
Restores tailwind changelog, and readme file as stubs.  `@astrojs/upgrade` still creates references to these files when being used.
=> docs(tailwind): restore tailwind readme and changelog as stub

packages/astro/package.json, packages/astro/src/config/index.ts, packages/astro/src/core/app/common.ts, packages/astro/src/core/app/index.ts, packages/astro/src/core/app/types.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/core/dev/container.ts, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/core/sync/index.ts, packages/astro/src/i18n/index.ts, packages/astro/src/i18n/utils.ts, packages/astro/src/manifest/serialized.ts, packages/astro/src/manifest/virtual-module.ts, packages/astro/src/runtime/server/render/component.ts, packages/astro/src/virtual-modules/i18n.ts, packages/astro/src/vite-plugin-astro-server/app.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/astro/test/astro-assets-prefix-multi-cdn.test.js, packages/astro/test/astro-assets-prefix.test.js, packages/astro/test/astro-preview-headers.test.js, packages/astro/test/fixtures/content-layer/src/content.config.ts, packages/astro/test/fixtures/static-build-frameworks/astro.config.mjs, packages/astro/test/static-build-frameworks.test.js, packages/astro/test/units/i18n/astro_i18n.test.js, packages/astro/test/units/integrations/api.test.js, packages/astro/test/units/vite-plugin-astro-server/request.test.js
This PR refactors how the manifest is computed and pulled during development and build. 
There's a new module called `astro:serialized-manifest`. While it returns a deserialised manifest, it's actually deserialised during its creation. It means that it's computed from `AstroSettings`, and it's deserialised inside the virtual module. 
Happy to bikeshed the name.
Now `astro:config/server` and `astro:config/client` use this module to pull the information. Plus, I refactored them to use `this.environment.name` instead of `opts.ssr`
Updated. They should all pass
N/A
=> refactor: manifest as virtual module

packages/astro/src/core/create-vite.ts, packages/astro/src/manifest/serialized.ts, packages/astro/src/vite-plugin-astro-server/app.ts, packages/astro/src/vite-plugin-astro-server/entrypoint.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts
This refactors the dev server to use an entrypoint to load the application.
The minimal example works, the react example works.
=> refactor(dev): use entry point to bootstrap the app

packages/astro/package.json, packages/astro/src/core/app/dev/app.ts, packages/astro/src/core/app/dev/index.ts, packages/astro/src/core/app/dev/pipeline.ts, packages/astro/src/prerender/routing.ts, packages/astro/src/types/public/integrations.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, pnpm-lock.yaml
This PR does the following:
- adds a new specifier to Astro named `astro/app/dev`. This new specifier exposes two bindings: a `default`, which is `createExports`, and `DevApp` if users need to use it 
- adds a `devEntrypoint` to the adapters, which is used inside the Astro dev server plugin. If it is absent, the plugin uses `astro/app/dev` as a fallback
This should get us closer to use the cloudflare plugin
Minimal and React examples still work
=> refactor(dev): expose dev app and entrypoint

.changeset/kind-snakes-grow.md, packages/astro/src/content/utils.ts
When looking at ways to catch misuse of live collections I realised that currently we're silently ignoring errors when parsing content config. This PR changes it to log errors in these cases. Because these aren't currently fatal errors, throwing would be a breaking change, so I'm just logging for now.
Additionally, if live collections are enabled then it checks if it failed because`createLiveCollection` has been used in `content.config.ts` and if so it *does* throw an error (which was I was originally trying to do).
=> fix: log errors for invalid content config

.changeset/rare-avocados-sin.md, packages/astro/src/cli/info/index.ts
Fixes #14401 
previously, Bun users were seeing this when they used `bun` to install their npm packages, and then ran `astro dev`, `astro build`, etc. 
This was introduced in https://github.com/withastro/astro/pull/14300 to intentionally add the message to `astro info`, but not realizing that the helper function `getInfoOutput()` was called outside of `astro info` during normal render, for debugging purposes.
This PR removes that warning for now, since we shouldn't be printing inside of a helper utility like that. We could add it back in the future, but ~~I also don't think it's communicating the correct message about our Bun support (tldr: we support Node, and Bun is Node compatible, so Astro should be expected to work correctly in Bun. if it does not, that's bun's problem to solve, but …
=> Remove warning for bun, causing unexpected console spam

.changeset/rich-horses-begin.md, packages/astro/client.d.ts, packages/astro/src/transitions/vite-plugin-transitions.ts
- Closes https://github.com/withastro/astro/issues/14369 
All existing tests are passed when running `pnpm run test`
https://github.com/withastro/docs/pull/12347
=> Remove deprecated ViewTransitions component

.changeset/lazy-trains-switch.md, packages/astro/src/container/index.ts
- The `AddServerRenderer` type previously used `name: never` to forbid the `name` property when `renderer` was a `NamedSSRLoadedRendererValue`. However, this prevented the compiler from correctly matching the first union branch.
- Removing `name: never` from the name renderer union type branch will fix this.
- Verified that TypeScript correctly accepts both union branches.
- The existing docs already describe the intended behavior, so no changes are needed after this fix.
=> fix(types): remove invalid `name: never` from AddServerRenderer

packages/astro/CHANGELOG.md
- Fixes a typo in the changelog.
Tried to use the name from the changelog and received an error. Switched to the new name and it succeeded.
I've confirmed [the docs do not have this typo](https://github.com/withastro/docs/blob/db947a549bc43f0e04a1075ef91d6d0b67f061d7/src/content/docs/en/reference/experimental-flags/fail-on-prerender-conflict.mdx#L23).
=> Fix name of new flag in changelog

.github/workflows/changeset-validation-prompt.txt, .github/workflows/validate-changesets.yml
Adds a new workflow that checks any added changesets and validates them against the guidelines. It checks wording such as improper verbs, use of improper headings that break formatting, and ensures that it describes the user-facing changes. It uses [GitHub Models](https://github.com/marketplace/models) and should stay in the free tier (and if we hit the limit it won't charge us). It caches the response based on a hash of the prompt, so multiple pushes to the same PR won't keep sending requests unless the changeset changes. If there are failures it adds a comment.
I did manual tests and it's pretty good. Not something to rely on, but a good addition to our existing checks I think.
Example of a failure:
=> chore: add changeset validation workflow

.changeset/beige-clowns-read.md, .changeset/cuddly-worlds-beam.md, .github/workflows/ci.yml, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/internal.ts, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/core/server-islands/endpoint.ts, packages/astro/src/integrations/hooks.ts, packages/astro/src/types/public/integrations.ts, packages/astro/test/middleware.test.js, packages/astro/test/static-build-page-dist-url.test.js, packages/astro/test/test-adapter.js, packages/integrations/sitemap/src/index.ts, packages/integrations/vercel/src/index.ts
- Closes #14444
- Removes `routes` from `astro:build:done`
- Removes `entryPoints` from `astro:build:ssr` as it was unused since the removal of `functionPerRoute`
- Removes the `IntegrationRouteData` type
Updated
https://github.com/withastro/docs/pull/12445
=> feat: cleanup integration api

.changeset/cyan-crews-cross.md, .changeset/dull-mangos-travel.md, .changeset/pretty-forks-smash.md, packages/astro/components/ClientRouter.astro, packages/astro/e2e/fixtures/prefetch/src/pages/index.astro, packages/astro/src/content/data-store.ts, packages/astro/src/content/mutable-data-store.ts, packages/astro/src/core/app/index.ts, packages/astro/src/core/app/node.ts, packages/astro/src/prefetch/index.ts
- Removes APIs that were deprecated in v4 but got forgotten in v5
Updated
https://github.com/withastro/docs/pull/12469
=> feat: clean deprecated APIs

packages/astro/package.json, packages/astro/src/core/compile/compile.ts, pnpm-lock.yaml
- See https://github.com/withastro/compiler/pull/1114
- In v5, `renderScript` became the default so we update the compiler and remove the option
- Depends on #14480
Should pass
N/A, internal change
=> feat: remove renderScript option

packages/astro/src/core/app/types.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/plugins/plugin-manifest.ts, packages/astro/src/i18n/index.ts, packages/astro/src/i18n/vite-plugin-i18n.ts, packages/astro/src/manifest/serialized.ts, packages/astro/src/manifest/virtual-module.ts, packages/astro/src/virtual-modules/i18n.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/integrations/cloudflare/test/fixtures/vite-plugin/astro.config.mjs, packages/integrations/cloudflare/test/fixtures/vite-plugin/src/pages/fr/index.astro, packages/integrations/cloudflare/test/fixtures/vite-plugin/src/pages/index.astro
This PR adds support for i18n using the environment APIs in the new infrastructure.
- The i18n virtual module now uses `astro:config/server`
- We import the module using `* as config` because it doesn't have a default export, and we want to strictly type the `config` binding, so we get auto-completion
- Added `domains` to the SSRManifest. Until now, it wasn't needed. However, this is now required because we rely `astro:config/server`, which now depends on the virtual module of the manifest (we don't rely on `AstroConfig` anymore).
- removed unused code inside the i18n virtual module
- 
Added a new page to the fixture and made sure (during TBD!) that pages that don't exist for the new locale are correctly redirected to the default locale. 
N/A
=> feat: support i18n
