withastro/astro

.changeset/polite-coats-study.md, packages/create-astro/src/index.ts, packages/create-astro/src/templates.ts
- the prompts package fails when it sees an empty option
- a bad commit added an empty object to the "select template" screen
- Not testable since it only happened in interactive mode
- Tests continue to pass
=> fix create-astro template issue

.changeset/fair-students-cough.md, packages/astro/src/runtime.ts
- During build, we were seeing the file watcher running twice
- Last night I pushed a fix to turn this off, but the fix was too aggressive and ended up disabling file watching on the frontend during development
- This PR fixes that issue
=> watch files during development in both snowpack instances

examples/blog/astro.config.mjs
Not having this causes it to throw in the build
N/A
N/A
=> Give the blog template a default `site`

packages/astro/README.md
The link to the "Partial Hydration" section from "Markdown" didn't work because it was missing a hyphen. Since I was changing it, I also moved it to the list of link reference definitions at the bottom.
=> Fix broken partial hydration link in README

docs/styling.md
I'm not sure where the browserslist default link should redirect to, but I assumed: https://github.com/browserslist/browserslist#full-list
=> docs: fix browserlists link

.changeset/stupid-dryers-bow.md, packages/astro/src/dev.ts
Closes #345
Slight tweak of the error message on addr already used for dev server.
Before:
```
$ astro dev
[01:09:24] [snowpack] Ready!
[01:09:24] [snowpack] watching for file changes...
Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
at Server.setupListenHandle [as _listen2] (node:net:1306:16)
at listenInCluster (node:net:1354:12)
at doListen (node:net:1492:7)
at processTicksAndRejections (node:internal/process/task_queues:84:21)
```
After
```
$ node ../../packages/astro/astro.mjs dev .
[01:42:40] [snowpack] Ready!
[01:42:40] [snowpack] watching for file changes...
[dev server] Address 127.0.0.1:3000 already in use. Try changing devOptions.port in your config file
```
=> nit: ask user to modify devOptions.port when addr in use for dev

.github/workflows/nodejs.yml, examples/blog/meta.json, examples/starter/meta.json, package.json, packages/create-astro/README.md, packages/create-astro/package.json, packages/create-astro/src/index.ts, packages/create-astro/test/create-astro.test.js, tools/astro-vscode/package.json, www/package.json
Partially addresses #365. Adds testing for the **local branch version** of every template, for both dev and build.
But it’s a partial fix as it’s also using the local copy of `create-astro` (i.e. monorepo symlinked). So it won’t catch the dependency misses that #365 describes for `npm init astro`. That will have to be handled separately in a followup PR.
It adds at least 2 minutes runtime (on a fast Macbook Pro) to the test suite because we are doing full npm installs and cold dev server startups. Feedback welcome there on how to improve it.
⚠️ **Note**: this PR isn’t set to run these template tests on every PR, mostly due to slowness. When/how should we run these?
=> Add integration test for templates

.changeset/rare-nails-sneeze.md, docs/api.md, examples/snowpack/src/components/PluginSearchPage.jsx, packages/astro/src/build.ts, packages/astro/src/runtime.ts, packages/astro/src/snowpack-logger.ts, packages/astro/test/fixtures/astro-fallback/src/components/Client.jsx
This gets rid of having 2 snowpack instances. Instead there's just one, but no more `import.meta.env.astro`. So this is a breaking chance.
People can use `import.meta.env.SSR` for the same purpose.
- [✅] Tests are passing
- [✅] Tests updated where necessary
This wasn't documented, I'm adding it.
=> Remove second snowpack instance

.changeset/stale-cameras-teach.md, packages/astro/src/runtime.ts
Passes the Astro `site` config to Snowpack as `baseUrl`
No docs needed either
=> Pass Astro `site` to snowpack `baseUrl`

packages/astro/src/compiler/transform/doctype.ts, packages/astro/src/compiler/transform/postcss-scoped-styles/index.ts, packages/astro/src/compiler/transform/styles.ts, packages/astro/src/internal/h.ts, packages/astro/test/astro-doctype.test.js, packages/astro/test/fixtures/astro-doctype/src/pages/capital.astro
Fixes #413
Makes all of the places where we special case the doctype be case insensitive.
Added a test for all-caps doctype as is typical to write.
N/A
=> Make doctype be case insensitive

.changeset/sour-squids-trade.md, packages/astro/src/internal/h.ts, packages/astro/test/astro-attrs.test.js, packages/astro/test/astro-basic.test.js, packages/astro/test/fixtures/astro-attrs/src/components/Span.jsx, packages/astro/test/fixtures/astro-attrs/src/pages/component.astro, packages/astro/test/fixtures/astro-basic/src/pages/index.astro
Fixes #307
Makes the h() function serialize booleans by either omitting or adding the key, nothing more.
Added a test for this.
N/A
=> Serialize boolean attributes without a value

packages/astro/test/fixtures/preact-component/src/components/ArrowFunction.jsx, packages/astro/test/fixtures/preact-component/src/pages/fn.astro, packages/astro/test/fixtures/react-component/src/components/ArrowFunction.jsx, packages/astro/test/fixtures/react-component/src/pages/index.astro, packages/astro/test/preact-component.test.js, packages/astro/test/react-component.test.js, packages/renderers/renderer-preact/server.js, packages/renderers/renderer-react/server.js
This fixes the React and Preact component as arrow function use-case by checking for the prototype property (arrow functions don't)
Checks for `Component.prototype` because arrow funtions don't have them.
Added test to the Preact and React renderer.
N/A
=> Fix usage of arrow functions as components

.changeset/silent-rocks-relax.md, packages/astro/src/compiler/transform/postcss-scoped-styles/index.ts, packages/astro/test/astro-basic.test.js, packages/astro/test/fixtures/astro-basic/src/pages/empty-class.astro
Closes #340
For some reason postcss will keep running the plugin over and over on a class without a body if we modify the `selector` (this triggers it as being "dirty"). It doesn't do this for selectors with a body. But the fix was easy enough, only scope a rule once.
Added a test for this scenario.
N/A
=> Prevent postcss from crashing when scoping class without a body

docs/renderers.md
- Fixes https://github.com/snowpackjs/astro/issues/344
- rewrites some of the docs section to be more standalone, fewer `diff` examples = easier to copy
=> rewrite part of the renderer docs

.changeset/curly-emus-ring.md, packages/astro/snowpack-plugin.cjs, packages/astro/src/compiler/transform/head.ts, packages/astro/src/runtime.ts, packages/astro/test/astro-hmr.test.js, packages/astro/test/fixtures/astro-hmr/snowpack.config.json, packages/astro/test/fixtures/astro-hmr/src/components/Tour.jsx, packages/astro/test/fixtures/astro-hmr/src/pages/index.astro, packages/astro/test/fixtures/astro-hmr/src/pages/manual.astro
Fixes #404
This contains 2 fixes:
* If the user sets the hmrPort in their own snowpack config we use that port.
* If the user sets `window.HMR_WEBSOCKET_URL` we defer to that
Adds tests for this
N/A
=> Honor user's hmr settings

docs/collections.md
- Rewrites the collections API docs based on feedback recieved
- Reads less like a walkthrough, and more like a guide. Examples are now standalone (feedback: no one was reading the docs from top to finish. People gravitated to the examples).
- Most explanation now moved into the examples via comments (feedback: no one was reading the words)
- Removed some outdated docs that were tripping people up (ex: `$[collections].astro)
- N/A
- it docs.
=> new collections API docs

.changeset/mean-ligers-nail.md, docs/syntax.md, packages/astro-parser/src/parse/state/tag.ts, packages/astro/src/compiler/codegen/index.ts, packages/astro/test/astro-expr.test.js, packages/astro/test/fixtures/astro-expr/src/pages/multiple-children.astro
- Adds automatic Fragment support for inline expressions in `.astro` files
- Not any code changes, multiple top-level elements remains supported
- Not any code changes, users may use array syntax `[<a>, <b>, <c>]` for inline expressions
- Closes #405.
Manually, but should probably add a real test for this.
Yes, Syntax doc has been updated.
=> Add `<>` fragment support for expressions

examples/tailwindcss/tailwind.config.js
Add .svelte files to tailwind config so that svelte components can use tailwind classes.
This changes the tailwind's config.
Add .svelte files to tailwind config so that svelte components can use tailwind classes.
N/A
=> Add .svelte to the tailwind config

docs/dev.md
- Fixed docs (docs/dev.md)
- Before
- After
NA
=> docs: fixed ascii based folder strucure in dev.md

.changeset/breezy-parrots-bathe.md, docs/styling.md, packages/astro/src/@types/compiler.ts, packages/astro/src/compiler/transform/styles.ts, packages/astro/src/runtime.ts
Hey, congratulations on the launch! 🚀 
This pull request ensures that the configured Tailwind config file (`devOptions.tailwindConfig`) is passed to the `tailwindcss` plugin. As far as I can tell currently this option is only used as a "flag" to enable `tailwindcss` and the actual path is not used.
This pull request also updates the styling docs to fix what I think is a typo in the Tailwind config path.
**One question I have related to this, is whether the `tailwindConfig` option should also be passed in to [the other `transformStyle` call](https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/packages/astro/src/compiler/transform/styles.ts#L243-L248) in the style transformer?**
Example project: https://github.com/bradlc/astro-tailwind …
=> Pass configured Tailwind config file to the `tailwindcss` plugin

packages/astro/snowpack-plugin.cjs, packages/astro/src/compiler/transform/head.ts, packages/astro/src/runtime.ts, packages/astro/test/astro-basic.test.js
Fixes #463
Passes `mode` through, and only attaches HMR client in development mode.
Added a test.
N/A
=> Prevent HMR client from being part of build output

.changeset/eleven-cats-tan.md, .changeset/rare-weeks-explode.md, package.json, packages/astro-parser/package.json, packages/astro-prism/package.json, packages/astro/package.json, packages/create-astro/package.json, packages/markdown-support/package.json
Adds the git remote URL for each package to their respective package.json's so that services like renovatebot and dependabot can find them.
=> Add repository remotes for all astro packages

docs/styling.md
Fixes syntax errors in styling docs. Docs-only change.
Is docs
=> Fix syntax errors in styling docs

packages/astro/src/compiler/codegen/index.ts, packages/astro/src/compiler/utils.ts
Closes #455. Previously, errors inside of expressions would fail cryptically. This adds much better error handling and a code frame.
**Before**
**After**
Tested manually since we aren't really testing the logger output.
DX enhancement, no docs needed
=> feat(#455): improve error logging inside of expressions

docs/api.md
- Docs change
Docs only change.
- Documents the shape of data returned by Astro.fetchContent when used with markdown, closes #367 
- `{ astro.headers[]f }` still needs explanation since I haven't figured out what it will return, since it's been empty when I've printed it out.
=> Update the shape of data provided by `Astro.fetchContent("./*.md")`

.changeset/eight-garlics-rescue.md, packages/astro/README.md
Just fixing the README header:
1. Preserves aspect ratio on mobile.
2. Header is served from same branch. If image gets changed in a branch, the header in that branch gets updated, too.
| --- | --- |
| ![IMG_A04ADB39D28C-1](https://user-images.githubusercontent.com/31006608/122431240-919c9680-cf94-11eb-8a50-1f3aeb479543.jpeg) | ![IMG_5A2E805D6A76-1](https://user-images.githubusercontent.com/31006608/122431297-9eb98580-cf94-11eb-9050-7f1c389e0b91.jpeg) |
No docs changed
=> Fix README header aspect ratio

docs/collections.md
Very minor typo in the example code pulling results out of the `pokeapi` response
Docs change only, noticed when I tried running the exact code locally that `pokeapi.co` returns the data in an array named `results` rather than `result` 
Hit the same [pokeapi endpoint](https://pokeapi.co/api/v2/pokemon?limit=150) in a browser to confirm the prop is named `results`
Yes!  Only public docs were updated
=> DOCS: Update collections.md

examples/docs/public/index.css
Currently the theme switcher in the `example/docs` starter isn't tab targetable, made a small change so that keyboard users can navigate to theme switching.
Before:
Previously, you could only tab to the containing div of the radio group, but not into it.
After:
After the change, you able to tab target into the radio group and arrow key navigate between theme choices
N/A
=> Fix keyboard untargetable on theme switcher

.changeset/late-badgers-accept.md, tools/prettier-plugin-astro/package.json
- Adds `@types/prettier` to the `devDependencies` so that typescript can find the correct types.
- package added only
=> Add @types/prettier to astro-prettier-plugin

packages/astro/src/compiler/codegen/index.ts
If a component is not rendered because it doesn't exist the codegen still adds a closing parenthesis to the render function and therefore closes the last parent Element.
Adds additional marker for the code generator to know if a component was rendered and therefore isn't accidently closing the parent tag if not.
=> Fixes #251 closing the parent tag if the component rendering led to an error

.changeset/happy-cougars-scream.md, packages/astro/src/compiler/transform/styles.ts, packages/astro/test/astro-styles-ssr.test.js, packages/astro/test/fixtures/astro-styles-ssr/src/components/AstroNone.astro, packages/astro/test/fixtures/astro-styles-ssr/src/pages/index.astro
This is a partial solution for #472. Instead of injecting the `astro-*` class into every Astro component, this only injects it for components that use `<style>`.
Added a test in `astro-styles-ssr`. Maybe not the best place? It seemed like the most relevant area.
Nope, optimization only.
=> Skip scoped `astro-*` class if Astro component has no `<style>`

packages/astro/snowpack-plugin.cjs, packages/astro/src/@types/astro.ts, packages/astro/src/config_manager.ts, packages/astro/src/frontend/__astro_config.ts, packages/astro/src/internal/__astro_component.ts, packages/astro/src/runtime.ts, packages/astro/src/runtime/config.ts
Fixes #414
This moves the logic that handles renders to the `config_manager.ts`. This file exists to handle any configuration changes.
How it works is, the ConfigManager creates the dynamically generated `__astro_config.js` module. When the astro.config.mjs file changes it makes itself as dirty, and the next time a page load occurs it grabs a new version of the astro config and creates that __astro_config.js module.
It's a coordination between this ConfigManager and the snowpack plugin that makes this all work.
This was tested manually by loading up a dev server and changing the renderers in an example app. We don't currently have a way to unit test file changes in Astro.
N/A, this is expected user behavior.
=> Allow renderers configuration to update

.changeset/silly-bees-flash.md, docs/renderers.md, packages/astro/snowpack-plugin.cjs, packages/astro/src/config_manager.ts, packages/astro/src/runtime.ts, packages/astro/src/snowpack-logger.ts, packages/renderers/renderer-preact/index.js, packages/renderers/renderer-react/index.js, packages/renderers/renderer-vue/index.js, yarn.lock
Fixes #356
This gets rid of the snowpack warning suppression. The main way this achieves that is by adding a `knownEntrypoints` option to the renderer interface. We use that to add the knownEntrypoints that each renderer needs.
Manually as our existing warning unit tests have been flakey and were removed.
Doc added for new `knownEntrypoints` option.
=> Removes snowpack warning suppression

tools/prettier-plugin-astro/test/astro-prettier.test.js
- Change usage of `assert.equal` to `assert.fixture` so that error output is more readable, as it expects to compare two multiline strings, and formats errors with line numbers. 
- https://github.com/lukeed/uvu/blob/master/docs/api.assert.md#fixtureactual-string-expects-string-msg-message
- https://github.com/lukeed/uvu/blob/master/docs/api.assert.md#notfixtureactual-string-expects-string-msg-message
=> Use `assert.fixture` rather than `assert.equal` 

.changeset/shy-houses-do.md, docs/collections.md, packages/astro/src/runtime.ts, packages/astro/test/astro-collection.test.js, packages/astro/test/fixtures/astro-collection/src/pages/$grouped.astro, packages/astro/test/fixtures/astro-collection/src/pages/$individual.astro, packages/astro/test/fixtures/astro-collection/src/pages/post/nested/a.md, packages/astro/test/fixtures/astro-collection/src/pages/post/one.md, packages/astro/test/fixtures/astro-collection/src/pages/post/three.md, packages/astro/test/fixtures/astro-collection/src/pages/post/two.md
- Adds support for `pageSize: Infinity` when creating a collection
- Fixes #483 
- Adds test coverage for grouping a collection by item metadata (author, tag, etc)
- Adds test coverage for creating individual pages for each item in a collection
- Reverts the docs change that removed the references to Infinity
=> Update createCollection() to handle `pageSize: Infinity`

CODE_OF_CONDUCT.md, COMMUNITY.md, GOVERNANCE.md
- Adds code of conduct
- Adds governance doc
- Adds community doc (still WIP but not blocking this PR, should eventually become a hosted page on our docs site)
Note: Any existing contributors with write access (granted post-launch) will be grandfathered in to become L2 contributors. All other contributors will become L1.
/cc @snowpackjs/maintainers for review
=> add governance docs

docs/styling.md
This just adds `svelte` in the purged list under tailwind config
```js
// tailwind.config.js
module.exports = {
mode: 'jit',
purge: ['./public/**/*.html', './src/**/*.{astro,js,jsx,ts,tsx,vue,svelte}']
};
Only docs
Docs updated
=> add svelte extension to purge list

.changeset/old-buses-tell.md, packages/astro/src/compiler/transform/head.ts, packages/astro/test/astro-basic.test.js, packages/astro/test/astro-hmr.test.js, packages/astro/test/fixtures/astro-hmr/src/pages/static.astro
Fixes #527
Previously we only added the HMR script on pages with dynamic components. This now adds it all the time in dev, so livereload works with astro components.
Test added
N/A, bug fix.
=> Always add the HMR script in dev

.changeset/lazy-doors-watch.md, packages/astro/src/build.ts, packages/astro/src/logger.ts
- Removes unused trapWarn() function from loggger and all references to it
build passed
Bug fix only
=> Removed unused console.warn trap function

docs/collections.md
Fixes a typo in the collection docs. allPokemonResult.result should be allPokemonResult.results.
1. Add $pokemon.astro to pages.
2. Paste code from Example: Individual Pages from a Collection section in collections docs
3. Log allPokemonResult.result to show that it's undefined
4. Log allPokemonResult.results to show that it is correct
Public documentation was updated
=> Fix pokemon results typo in collections docs

package.json, tools/prettier-plugin-astro/test/astro-prettier.test.js, tools/prettier-plugin-astro/test/fixtures/in/attribute-with-embedded-expr.astro, tools/prettier-plugin-astro/test/fixtures/out/attribute-with-embedded-expr.astro
Adds a test for the currently failing prettier plugin case where there is JSX embedded in an attribute. Mentioned in https://github.com/snowpackjs/astro/issues/478
to run:
- `cd tools/prettier-plugin-astro`
- `yarn test`
=> prettier-plugin: Add a test for JSX embedded in an attribute. This test currently fails.

packages/astro/README.md
- previously, links were broken from https://github.com/snowpackjs/astro/blob/main/packages/astro/README.md
- now they are not
=> Update README.md relative docs links

.changeset/orange-grapes-divide.md, packages/astro/src/search.ts, packages/astro/test/astro-collection.test.js, packages/astro/test/fixtures/astro-collection/src/pages/$individuals.astro
This updates the RegExp used to match collection URLs to the Astro template file.
Added test coverage to make sure URLs for `$individual.astro` and `$individuals.astro` are mapped back to the correct template file
bug fix only
=> Fix collections regex

examples/blog/src/pages/$author.astro
Updates the order author is initialized until after the collection
`const author = authorData[collection.params.author];
`
Now is assigned after the createCollection() function.
Before
- Made the change
- Added a new author
- Opened each author page to confirm they loaded
No docs needed
=> bug: changed initialization order of the author

packages/astro/README.md
minor tweak to readme to remove redundant acronym.
none.
n/a.
=> Fix: Redundant acronym for ESM

.changeset/warm-terms-admire.md, examples/with-markdown/src/layouts/main.astro, examples/with-markdown/src/pages/external.astro, packages/astro/src/compiler/codegen/index.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/close.astro
Closes #494. Previously, `<Markdown content={content} />` would close its parent tag. Now `codegen` skips if any attributes are detected on the `Markdown` component.
Test added under `astro-markdown`.
Bug fix only.
=> Fix `<Markdown {content} />` closing parent tag

.changeset/eighty-dogs-notice.md, packages/astro/src/compiler/transform/styles.ts, packages/astro/test/astro-styles-ssr.test.js, packages/astro/test/fixtures/astro-styles-ssr/src/components/Astro.astro, packages/astro/test/fixtures/astro-styles-ssr/src/pages/index.astro
If a class is being passed into child components, pass in the scoped class name as well.
Test added
Bug fix only
=> Pass in scoped class name to child components

packages/astro/README.md
At the moment, the README file says that Yarn 2 does not support ES Modules, which is only partly correct. The Plug'n'Play feature doesn't, but when you add `nodeLinker: node-modules` to `.yarnrc.yml`, Astro works fine.
I created a base Astro app using the default "Starter Kit" template, and ran it in both dev and checked the built files. Both worked successfully.
Information in the README about Yarn 2 compatibility was updated. Detailed above.
=> Make it clear that Yarn 2 does support ESM when you disable Plug'n'Play

examples/blog-multiple-authors/src/pages/index.astro, examples/blog/src/pages/index.astro, examples/docs/src/layouts/Main.astro, examples/framework-multiple/src/pages/index.astro, examples/framework-preact/src/pages/index.astro, examples/framework-react/src/pages/index.astro, examples/framework-svelte/src/pages/index.astro, examples/framework-vue/src/pages/index.astro, examples/portfolio/src/pages/index.astro, examples/starter/src/pages/index.astro, examples/with-markdown/src/pages/index.astro, examples/with-nanostores/src/pages/index.astro, examples/with-tailwindcss/src/pages/index.astro
- Give more inline support to `npm init astro` users
- adds docs to the main page components in each example project
=> update example astro inline docs

examples/blog-multiple-authors/README.md, examples/blog/README.md, examples/docs/README.md, examples/framework-multiple/README.md, examples/framework-preact/README.md, examples/framework-react/README.md, examples/framework-svelte/README.md, examples/framework-vue/README.md, examples/with-markdown/README.md, examples/with-nanostores/README.md, examples/with-tailwindcss/README.md
- When you open an example in our repo, it's hard to know how to clone it
- The change adds `npm init astro` instructions for every example template README
=> update example readmes

docs/core-concepts/ui-renderers.md, packages/astro/src/config_manager.ts, packages/astro/src/internal/__astro_component.ts, packages/astro/src/runtime.ts, packages/astro/test/custom-elements.test.js, packages/astro/test/fixtures/custom-elements/my-component-lib/hydration-polyfill.js, packages/astro/test/fixtures/custom-elements/my-component-lib/index.js
Some renderers, such as Lit, need special polyfills only for hydration. We have the `polyfills` array, but that is intended for polyfills that always need to run. This adds a second type hydrationPolyfills that only run on elements that are `:load`, `:idle`, etc.
Tests added
Documented
=> Adds hydrationPolyfills config for renderers

.changeset/good-beers-worry.md, docs/reference/api-reference.md, packages/markdown-support/src/index.ts
Adds `astro.html` to results returned by `Astro.fetchContent`. Closes #571.
> **Note** there was a performance concern to rendering all `.md` files fetched with `Astro.fetchContent`, but it turns out we were already rendering them completely! This just exposes the result under the `astro.html` key.
No tests, just exposing another prop.
=> Expose `content.astro.html` to `Astro.fetchContent`

packages/astro/test/fixtures/preact-component/src/components/EmptyFrag.jsx, packages/astro/test/fixtures/preact-component/src/pages/frag.astro, packages/astro/test/preact-component.test.js, packages/renderers/renderer-preact/server.js
This is a bug fix. When a Preact component returns only an empty fragment like so `return <Fragment />` this should be treated as a valid Preact component.
Use-case I had was that I wanted nothing to rendered in a certain state. An `Alert` component that only shows something when there is a message.
Test added
N/A bug fix
=> Allow Preact components to return an empty Fragment

.changeset/bright-cherries-juggle.md, package.json, packages/astro/src/runtime.ts, packages/astro/test/builtins-polyfillnode.test.js, packages/astro/test/fixtures/builtins-polyfillnode/package.json, packages/astro/test/fixtures/builtins-polyfillnode/snowpack.config.json, packages/astro/test/fixtures/builtins-polyfillnode/src/pages/index.astro, yarn.lock
Fixes #569 by avoiding setting `node:` aliases when polyfillNode is being used.
Yep
N/A, bug fix.
=> Don't alias builtins if polyfillNode is used

.changeset/tame-cheetahs-yawn.md, packages/create-astro/README.md, packages/create-astro/src/index.ts, packages/create-astro/test/create-astro.test.js, packages/create-astro/test/external.test.js, packages/create-astro/test/helpers.js
Closes #558
This allows you to clone from an external repo like so:
```bash
npm init astro my-shopify --template cassidoo/shopify-react-astro
```
This will work with any string that degit supports, so you get simplified user/repo like shown above or https urls, from gitlab, etc.
Test added.
Docs updated
=> Implements templates from external repos

.changeset/metal-lions-try.md, packages/astro/src/runtime.ts
Previously, we were setting `snowpackConfig.alias = { ... }`, which would override a user's configured `alias`. Now we're merging the two.
Bugfix
Bugfix
=> Do not override snowpack alias

packages/create-astro/src/index.ts
Following up on @FredKSchott's comment. This introduces magic comments in `create-astro` starters that should be replaced by user's selected components. They are pretty self-explanatory.
```
/* ASTRO:COMPONENT_IMPORTS */
```
Manually!
Pre-emptive bug fix 🤣
=> Make `create-astro` component injection less brittle

examples/blog/src/pages/index.astro
I started a new blog project and found that, once I added more than one blog post, my posts weren't sorting by date.
Once I looked at the code, I realized it's because it was sorting on the `date` key which doesn't exist. The example blog posts use the `publishDate` key. So no sorting was occurring.
No tests written because idk how to write a test for this. AFAIK there wasn't one previously.
Bug fix in example only.
=> fix: sorting key for example blog posts

package.json
Updates the root `yarn test` command to not test for the nonexistent `prettier-plugin-astro` package that was moved to https://github.com/snowpackjs/prettier-plugin-astro/ for the moment.
=> Remove `prettier-plugin-astro` from root package.json

.changeset/twelve-lions-tie.md, packages/astro/src/compiler/codegen/index.ts, packages/astro/test/astro-basic.test.js, packages/astro/test/fixtures/astro-basic/src/pages/frontmatter-component.astro
Previously, components which were not pulled into a file using `import` would throw an Error. This meant you couldn't dynamically define a certain element based on component props. This change allows for components defined in Frontmatter to be rendered statically and throws an error if a user attempts to hydrate them.
This is now valid (and very useful!)
```
---
const { level = 1 } = Astro.props;
const Element = `h${level}`;
---
<Element>Hello world!</Element>
```
Added a test under `astro-basic`
No docs
=> Add support for components defined in frontmatter

.changeset/rude-deers-know.md, packages/astro/src/@types/astro.ts, packages/astro/src/config_manager.ts, packages/astro/src/internal/__astro_component.ts, packages/astro/src/internal/element-registry.ts, packages/astro/test/fixtures/react-component/src/components/Research.jsx, packages/astro/test/fixtures/react-component/src/pages/index.astro, packages/astro/test/react-component.test.js, packages/renderers/renderer-react/server.js, yarn.lock
Fixes #630
When server rendering React you use the `renderToString` method when you want to hydrate and you use `renderToStaticMarkup` when you don't plan on hydrating. This fixes it so we use the right one in each case.
Tests added.
N/A, bug fix.
=> Use correct React rendering API or hydration

packages/renderers/renderer-react/server.js
If using Astro <= 0.17.0 there is no `metadata` being passed. Even though no one should be using that version with this, adding some extra protection just in case.
=> Protect again no metadata being passed

.changeset/twelve-lions-tie.md, packages/astro/src/compiler/transform/head.ts, packages/astro/test/astro-hmr.test.js, packages/astro/test/fixtures/astro-hmr/src/components/Demo.astro, packages/astro/test/fixtures/astro-hmr/src/pages/no-elements.astro, packages/astro/test/fixtures/no-head-el/src/pages/no-elements.astro, packages/astro/test/no-head-el.test.js
Closes #605. Previously our `EndOfHead` implementation was ignoring pages which had no Element nodes (only InlineComponent) nodes. This change ensures that HMR and styles are _always_ injected.
Added two test cases
Bug fix only
=> Fix injection behavior for pages which contain no elements

.changeset/smart-forks-search.md, packages/astro/astro.cjs, packages/astro/astro.mjs, packages/astro/package.json, yarn.lock
Previously, `astro.mjs` was statically using `import { cli } from './dist/cli.js'` which would execute the CLI code and throw on unsupported Node versions.
This adds a simple `engines` check before _dynamically_ running `import('./dist/cli.js').then({ cli }) => cli())`, so any invalid code in `cli.js` won't be run until the version is verified.
I also added some handy links to Netlify, Vercel, and GitHub Actions documentation because why not!
**BEFORE**
**AFTER**
Manually, hard to test automatically
QOL Improvement
=> Improve error handling in unsupported node versions

.changeset/pink-buttons-destroy.md, packages/astro/src/build.ts
- Added a check to see if site is already set
Didn't add any extra test, couldn't find any specific test for the build output.
Ran all tests and they passed in the same way as in the main branch.
This does not actually change any functionality.
=> Only display notice if needed

.changeset/wicked-gifts-cover.md, docs/core-concepts/component-hydration.md, packages/astro/src/@types/astro.ts, packages/astro/src/@types/hydrate.ts, packages/astro/src/compiler/codegen/index.ts, packages/astro/src/frontend/hydrate/idle.ts, packages/astro/src/frontend/hydrate/load.ts, packages/astro/src/frontend/hydrate/media.ts, packages/astro/src/frontend/hydrate/visible.ts, packages/astro/src/internal/__astro_component.ts, packages/astro/test/astro-dynamic.test.js, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-dynamic/src/components/Counter.jsx, packages/astro/test/fixtures/astro-dynamic/src/pages/media.astro
Closes #396 and #514
Demo: https://www.loom.com/share/c7ffe9467ce445ee946c40583ef06b63
This adds support for `client:media`. The value passed to the attribute gets passed through the hydration metadata. It's not passed as a string so that references to scope values will be picked up. This is tested.
Added tests both for static values and using a scope variable. 
Docs updated.
=> Adds support for client:media hydrator

docs/core-concepts/astro-components.md
This PR fixes formatting of the `.astro`/`.jsx` formats comparison table.
Before:
After:
Documentation only
Updates the Astro component documentation
=> Fix astro/jsx comparison table formatting

.changeset/empty-otters-smell.md, packages/astro/package.json, packages/astro/snowpack-plugin.cjs, packages/astro/src/config.ts, yarn.lock
Closes #429.
This adds support for multiple Astro dev servers running simultaneously. Previously, trying to start a second server errored out because the fixed default ports were already in use. Now, when the default ports are in use, a random port is chosen.
I've tested this manually by running two of the examples in the repo at the same time. Not sure if this can be automatically tested against, but if it needs to be, I would like some pointers.
Bug fix only.
=> select random ports if defaults are taken

docs/src/pages/404.astro
- All invalid URLs will redirect to 404.astro. *Note: this needs to be enacted on Vercel (or whatever this is hosted on) for it to be seen live.*
- There is now **duplicate code** in 404.astro, index.astro, Main.astro. What's the best way to abstract this?
- It's plain, it would be awesome if someone could spruce up the design.
**Before**
**After**
None. 404.astro is static.
Can be seen on /404, but will not be a redirect until Vercel (or whatever this is hosted on) is configured.
=> [docs] Added 404.astro

docs/astro.config.mjs, docs/package.json, docs/src/components/AvatarList.astro, docs/src/layouts/Main.astro
After the release of the Astro Docs to docs.astro.build and the migration to this repo, I changed some URLs
Tests were updated
bug fix only
=> [docs] Changed URLs to match the release

examples/with-tailwindcss/README.md
Changes the example init command template name from "with-tailwind" to "with-tailwindcss"
ran in the example init command locally.
typo fix only
=> changed init example to correct template name

docs/src/components/ThemeToggle.tsx
- fixes a flash when navigating between docs pages in the light theme
Tested manually since there's no straightforward way to catch a flash like this in automation
Only a visual fix for the docs site, no docs were changed or added
=> Fix: 🐛 ThemeToggle should initialize from localstorage immediately

.changeset/odd-cameras-wave.md, packages/create-astro/src/index.ts
Fix the remove script to use `--force` to emulate a `rm -rf` to clear subdirectories during `create-astro`. I think this is a valid solution because the create script asks if it can override the files, but fails on subdirectories. 
What **would** be nice would be to save the `.git` directory and such. But not sure if that should be included in this PR.
Not sure how to perform testing because all the current testing is on templates. I also don't mind adding a section later in the test that is run under the fixtures directory.
Bug fix?
Fixes: #
=> fix: add force to rm script in create-astro

docs/public/index.css
- Docs
Makes it so that the links on the right side expand to fit their slot
Currently the highlighting makes it seem like you should be able to click on the link while not over the actual *text*, but the link is compactly located around the link text, rather than conforming to the highlighting.
=> docs: set header link width to 100% so that the link fills the entire box it sits in for easier selection

package.json
- Updates the `yarn format` script to format all files in the directory, so that we don't have to keep adding to the glob to support formatting `css` and `scss` files, etc.
=> Update `format` script to format all files not ignored via `.prettierignore` that `prettier` has a valid parser for.

docs/src/components/SiteSidebar.astro
- Docs
Updates SiteSidebar.astro to use [`aria-current="page"`](https://www.digitala11y.com/aria-current-state/) rather than `.nav-link.is-active` for styling and scrolling to current section.
=> docs: use `aria-current="page"` rather than `.is-active` in SiteSidebar.astro

docs/src/pages/installation.md
Remove trailing comma in package.json because JSON doesn't allow it.
I didn't test it because it is just a tiny syntax fix.
Public documentation is updated.
=> Remove trailing comma in package.json

docs/vercel.json, vercel.json, www/vercel.json
- Adds redirects for `https://astro.build/docs/:match*` to `https://docs.astro.build/:match*`
- Adds redirect for `/` to `/getting-started` on docs site
This also required a few small tweaks on the Vercel side to support our monorepo build step
This is me testing it!
N/A
=> Vercel Config

packages/astro/test/astro-attrs.test.js, packages/astro/test/astro-basic.test.js, packages/astro/test/astro-children.test.js, packages/astro/test/astro-collection.test.js, packages/astro/test/astro-components.test.js, packages/astro/test/astro-doctype.test.js, packages/astro/test/astro-dynamic.test.js, packages/astro/test/astro-expr.test.js, packages/astro/test/astro-fallback.test.js, packages/astro/test/astro-global.test.js, packages/astro/test/astro-hmr.test.js, packages/astro/test/astro-markdown-plugins.test.js, packages/astro/test/astro-markdown.test.js, packages/astro/test/astro-slots.test.js, packages/astro/test/astro-styles-ssr.test.js, packages/astro/test/benchmark/benchmark.js, packages/astro/test/builtins-polyfillnode.test.js, packages/astro/test/builtins.test.js, packages/astro/test/custom-elements.test.js, packages/astro/test/lit-element.test.js, packages/astro/test/no-head-el.test.js, packages/astro/test/plain-markdown.test.js, packages/astro/test/preact-component.test.js, packages/astro/test/react-component.test.js
- small test cleanup to leverage `uvu/assert` for simple checks
=> test cleanup: move if-check-then-throws to assertions

docs/src/config.ts, docs/src/layouts/Main.astro, docs/src/pages/index.astro
Outputs the `<title/>` as either `section name 🚀 Astro Documentation` or `Astro Documentation`
=> docs: fix the templating setup for the `<title/>` in `MainLayout.astro`

docs/src/components/MetaData.astro, docs/src/config.ts, docs/src/layouts/Main.astro
- Docs Closes #775 
Adds [Open Graph](https://ogp.me) and [Twitter Cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#attribution) tags to the docs site.
=> Docs/ Add MetaData component for Open Graph and Twitter embeds

docs/src/pages/quick-start.md, examples/blog-multiple-authors/README.md, examples/blog/README.md, examples/docs/README.md, examples/docs/src/pages/index.md, examples/portfolio/README.md, examples/snowpack/README.md, examples/snowpack/src/pages/tutorials/getting-started.md, examples/snowpack/src/pages/tutorials/quick-start.md, examples/snowpack/src/pages/tutorials/react.md, examples/snowpack/src/pages/tutorials/svelte.md, examples/starter/README.md
- docs: Quick Start
- examples: README
There was a mix of "npm run start" and "npm start" in the documentation, so it has been unified to "npm start".
It's not a mistake but it should be consistent.
=> Docs: replace `npm run start` with `npm start`

.changeset/two-squids-film.md, packages/astro-parser/src/parse/index.ts, packages/astro-parser/src/parse/read/expression.ts, packages/astro/test/custom-elements.test.js, packages/astro/test/fixtures/custom-elements/my-component-lib/server.js, packages/astro/test/fixtures/custom-elements/my-component-lib/shim.js, packages/astro/test/fixtures/custom-elements/src/components/my-element.js, packages/astro/test/fixtures/custom-elements/src/pages/nested.astro
Closes #714
Astro detects custom element tags and adds a runtime module that detects which import the element is associated with. This is the special `export tagName = 'my-element';` behavior.
This runtime is needed any time a custom element is on the page, even if you are not SSRing (because Astro doesn't know without checking).
We were not detecting that this module needed to be added in the case of elements used inside of JSX expressions (and never outside). This fixes that issue.
Test added with the scenario this fixes.
Bug fix only.
=> Handle custom elements in nested JSX

docs/src/config.ts, www/public/global.scss, www/src/components/Main.astro, www/src/components/MainHeader.astro, www/src/components/Space.astro, www/src/pages/index.astro
- Reuse blog header with helpful links
- Add video to tell people what its all about, faster
=> slight homepage redesign

.changeset/flat-apes-pump.md, packages/astro/src/compiler/codegen/index.ts, packages/astro/test/astro-basic.test.js, packages/astro/test/fixtures/astro-basic/src/pages/fragment.astro
Closes #582
This restores the ability to use `Fragment` in astro components. This is mostly not needed, as you can just use children everywhere but expressions. Fragment is used a bit internally and restoring this allows you to use it in a transform in the compiler. Also allows users to use `Fragment` instead of `<>` in expressions, if desired.
Test added
N/A
=> Allow using the Fragment built-in in Astro components

docs/src/pages/core-concepts/astro-components.md
Only documentation changes, no code or tests added/changed.
With the recently added documentation describing named slots, the previous Slots section was redundant, and was consolidated into the same section.
=> docs: remove duplicate section describing slots

docs/src/pages/guides/publish-to-npm.md
Added a section in the publish your own component page.
This is to rank community build components so we have a nice overview.
Tested by locally running
See this screenshot:
Yes only the docs were updated actually.
See above screenshot for added text.
=> Added docs for community plugins 📗

docs/src/pages/guides/deploy.md
Added `touch .nojekyll` to the deploy.sh example in the Github Pages section. Because `npm run build` doesn't pull through .nojekyll from public as outlined in step 2 I think because its a dotfile.
This was the original issue #816 
No tests added as its just an extra line and comment in the code example. 
Yes, the Github Pages deploy.sh script was updated.
=> Update deploy.sh to include touch .nojekyll

.changeset/lovely-cats-sin.md, packages/astro/snowpack-plugin-jsx.cjs
With no JSX renderers specified, JSX files would throw `"Hello world!"`. This was a test feature that accidentally got shipped.
Manually confirmed. We don't have a good way to test log messages.
N/A
=> Fix: JSX renderer "Hello world!" error

docs/src/pages/guides/markdown-content.md
No relevant changes or tests, docs-only.
Fix broken link in Markdown documentation.
As an alternative, the `<Markdown>` component section can also be renamed to just "Markdown Component", and keep the old link unchanged.
=> docs: fix broken link to Markdown component

docs/public/index.css, docs/src/layouts/Main.astro
Adds a Skip Link that is normally invisible but is focusable by tabbing to it at the top of the page so that keyboard users can skip the SiteSidebar and other nav and get directly to the main content.
=> 📘 DOC: adds a skip link so that you can skip the nav via keyboard

.changeset/healthy-pants-rule.md, packages/astro/src/internal/h.ts, packages/astro/test/astro-expr.test.js, packages/astro/test/fixtures/astro-expr/src/components/falsy.astro, packages/astro/test/fixtures/astro-expr/src/pages/falsy.astro
Fixes #679
This makes our handling of children inside of Fragments the same as inside of elements. This is the cause of the `false` values being rendered, our handling of fragments was too naive.
Test added
N/A, bug fix
=> Correctly serialize falsey values at top-level of components

docs/src/pages/guides/deploy.md
Added an example of a Github actions workflow in the deploy.md docs for github pages that pushes changes to \<YOUR USERNAME\>.github.io.
The yaml example code was tested on my personal repo, changes proposed here are only in the deploy.md Docs.
Yes, I added an example under the Github Actions heading in deploy.md.
Thank you, hope this is helpful.
=> 📘 DOC: Adding github actions example to deploy.md

.changeset/empty-trainers-chew.md, docs/src/pages/core-concepts/astro-components.md, docs/src/pages/guides/styling.md, packages/astro-parser/src/interfaces.ts, packages/astro-parser/src/parse/index.ts, packages/astro/src/compiler/codegen/index.ts, packages/astro/src/compiler/transform/index.ts, packages/astro/src/compiler/transform/styles.ts, packages/astro/test/astro-css-bundling.test.js, packages/astro/test/fixtures/astro-css-bundling/src/components/Nav.astro
Fixes RFC #507 
- Adds support for multiple `<style>` blocks in an Astro component
- Adds support for `<style global>` to skip scoped styles for all selectors in the style block
Updated the `astro-css-bundling` test to cover:
- the use of multiple scoped `<style>` blocks
- the use of `<style global>` blocks
- the use of `@keyframes` in scoped and global styles
Docs site updated to note support for `<style global>`, including a couple examples and details on when to use this (and that you should probably avoid it)
=> Introduce `<style global>`

docs/public/index.css
- switched table header color to use theme CSS var
Before:
After:
No tests, CSS change
bug fix only
=> fix table header text color

docs/src/pages/getting-started.md
Just added missing "a" in the first sentence.
First sentence did not include the "a". Please see updated file git comparison.
No test needed, single char added in documentation first page. Merge created in Github with merge checks.
Yes. Doc updated. Only 1 char added because it was missing in the sentence.
=> Fixed typo in getting-started.md

examples/blog/public/blog.scss, examples/blog/src/pages/posts/introducing-astro.md
Blog example contains components for `<Note>` and `<BlockQuote>`
- Converts `<Note>` and `<BlockQuote>` components in `.md` to markdown
- Adds blockquote styles to `blog.scss`
No tests added, maybe you could test for components in markdown though?
No docs added, bug fix only
=> Remove components from example md file

.changeset/seven-shoes-stare.md, packages/renderers/renderer-vue/index.js
It adds a `@vue/runtime-core` package to `external` of the `@astrojs/renderer-vue` config. 
More description about root causes of the issue are there -> https://github.com/snowpackjs/astro/issues/828
I was using a slightly modified version of Astro Vue app - https://github.com/Igloczek/astro-vue-nested-components
Then changed `node_modules/@astrojs/renderer-vue/index.js` to contains my changes, and run Astro.
It's just a bugfix.
=> Exclude @vue/runtime-core from processing to fix Vue SSR for nested components

.changeset/two-days-cry.md, docs/src/pages/reference/configuration-reference.md, examples/blog-multiple-authors/astro.config.mjs, examples/blog/astro.config.mjs, examples/docs/astro.config.mjs, examples/framework-lit/astro.config.mjs, examples/framework-multiple/astro.config.mjs, examples/framework-preact/astro.config.mjs, examples/framework-react/astro.config.mjs, examples/framework-solid/astro.config.mjs, examples/framework-svelte/astro.config.mjs, examples/framework-vue/astro.config.mjs, examples/portfolio/astro.config.mjs, examples/starter/astro.config.mjs, examples/with-markdown-plugins/astro.config.mjs, examples/with-tailwindcss/astro.config.mjs, packages/astro/test/fixtures/lit-element/astro.config.mjs, packages/create-astro/src/config.ts
Updates the default `tailwindConfig` property of `astro.config.mjs` to the commonly used path `./tailwind.config.js`. This allows the user to easily uncomment the property and start working for the common Tailwind config file.
Regarding this section https://docs.astro.build/guides/styling#-tailwind
I'm unsure if we should update the docs section to be worded differently with this change.
=> Update default `tailwindConfig` property

.changeset/heavy-pumas-cross.md, examples/blog/src/components/BlogPost.astro, examples/blog/src/layouts/BlogPost.astro, examples/blog/src/pages/posts/introducing-astro.md
- Adds an `alt` tag to the hero image of the blog example
Manually verified this adds an `alt` tag to the hero image
bug fix only
=> Add an alt tag for the hero image in the blog example

.changeset/cold-bikes-float.md, .changeset/itchy-bobcats-rest.md, packages/astro/src/compiler/transform/styles.ts
close #851 
- Adds `indentedSyntax: true` for compiling `sass` stylesheets, so that they are no longer compiled as `scss`
Tested by recreating steps in #851 (with locally built Astro), now shows correct behavior
Current behavior reflects that described in the documentation, thus no change needed
=> Correctly compile `lang="sass" styles`

.changeset/friendly-tigers-smoke.md, packages/renderers/renderer-solid/client.js
Fixes #847. Instead of creating the element and inserting it on the DOM, this PR makes use of Solid's `render` since it adds a reactive root to the component tree. Without it `createEffect` and other reactivity characteristics do not work. The `render` method also handles any kind of possible return from a Solid component since they are not necessarily native HTML elements.
No tests were added, I couldn't find any tests regarding renderers to guide me in this case.
Bug fix only
=> Fix `renderer-solid` not creating a reactive root

.changeset/wise-months-run.md, packages/astro/src/runtime.ts
With the blog template we get these warnings:
```
[14:01:30] [snowpack] astro/dist/internal/fetch-content.js: Unscannable package import found.
Snowpack scans source files for package imports at startup, and on every change.
But, sometimes an import gets added during the build process, invisible to our file scanner.
We'll prepare this package for you now, but should add "astro/dist/internal/fetch-content.js" to "knownEntrypoints"
in your config file so that this gets prepared with the rest of your imports during startup.
[14:01:30] [snowpack] + astro/dist/internal/fetch-content.js@0.18.0
[14:01:31] [snowpack] astro/dist/internal/__astro_slot.js: Unscannable package import found.
Snowpack scans source files for package imports at startup, and on every change.
But, sometimes an import gets …
```
=> Add internals to knownEntrypoints

.changeset/eight-monkeys-hammer.md, packages/astro/src/compiler/codegen/index.ts, packages/astro/test/astro-components.test.js, packages/astro/test/fixtures/astro-components/src/pages/client.astro
Closes #890
This prevents `client:load`, etc directives from being included in the resulting hyperscript, so they won't be passed to components or serialized in the client. 
This prevents a Svelte warning that occurs for unknown directives.
Test added
Bug fix
=> Prevent client: attributes from being passed to components

.changeset/popular-shrimps-sin.md, packages/create-astro/src/index.ts
PR based on comment: https://github.com/snowpackjs/astro/issues/835#issuecomment-885994107
I really want to avoid recommending "rm -rf ~/.degit/github/snowpackjs" as this will run on the home directory.
Just commented `degit` out and throw the expected error.
```js
// await emitter.clone(cwd);
throw new Error('zlib: unexpected end of file')
```
This was a bug (semi) fix only.
=> Add warning when encountering 'zlib: unexpected end of file' message (#655)

.changeset/heavy-ears-hope.md, packages/astro/snowpack-plugin-jsx.cjs, packages/astro/test/fixtures/preact-component/src/components/PragmaCommentTypeScript.tsx, packages/astro/test/fixtures/preact-component/src/components/TypeScriptComponent.tsx, packages/astro/test/fixtures/preact-component/src/pages/ts-components.astro, packages/astro/test/fixtures/react-component/src/components/PragmaComment.jsx, packages/astro/test/fixtures/react-component/src/components/PragmaCommentTypeScript.tsx, packages/astro/test/fixtures/react-component/src/components/TypeScriptComponent.tsx, packages/astro/test/fixtures/react-component/src/pages/index.astro, packages/astro/test/fixtures/react-component/src/pages/pragma-comment.astro, packages/astro/test/preact-component.test.js, packages/astro/test/react-component.test.js
- Fixes #904
- Fixes the issue we were seeing in docs
- Fixes bug: unused imports were stripped from TSX files, causing our JSX import checker to fail.
- Also, little mini fix to throw an error instead of logging one, which would then throw a more confusing error later down the road.
- Tests added
- Not needed
=> fix tsx+jsx error

.changeset/bright-doors-remain.md, packages/markdown-support/package.json
This was mistakenly a devDependency, breaking `npm init astro`
=> Move rehype-raw to a dependency

docs/package.json, yarn.lock
Adds a `yarn lint:a11y` and `yarn lint:a11y:remote` command to the docs project so we can test for accessibility easily. 
In reference to #756
=> 📘 DOC: Add `yarn lint:a11y` to the docs project

.changeset/pretty-wolves-flash.md, packages/astro-parser/src/parse/state/text.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/dash.md
Closes #720
This removes checking for `---` inside of text. At this point the codefences are already detected so this check only causes the parser to keep spinning.
Test added
Bug fix
=> Allow triple-dashes in markdown

docs/src/pages/guides/styling.md
Added a PostCSS section under the [Styling & CSS](https://docs.astro.build/guides/styling) page.
closes #946
=> 📘 DOC: Add PostCSS configuration on Astro

docs/src/pages/guides/styling.md
Adding a note to make clear that users of .scss files should still link to the final compiled .css files, as per https://discord.com/channels/830184174198718474/853350631389265940/871151798075949066.
=> Update styling.md re link-handling for .scss files

docs/src/pages/fi/getting-started.md, docs/src/pages/fi/installation.md, docs/src/pages/fi/quick-start.md, docs/src/pages/nl/getting-started.md
Adds a `lang` attribute to translated doc pages so that the pages have the correct language set.
=> Add `lang` variable to docs frontmatter for translations

.changeset/red-falcons-brush.md, packages/astro/src/compiler/codegen/index.ts, packages/astro/src/compiler/index.ts, packages/astro/test/astro-global.test.js, packages/astro/test/fixtures/astro-global/src/components/Child.astro, packages/astro/test/fixtures/astro-global/src/components/NestedChild.astro, packages/astro/test/fixtures/astro-global/src/pages/index.astro
This makes it so the `request` is threaded through to all child components via the compiler. This means it's always available on `Astro.request`.
Tests added
Bug fix
=> Make Astro.request available to all astro components

docs/src/pages/guides/deploy.md
- Adding description of how to set up an Astro site in Cloudflare Pages.
- Minor grammatical fix in the “Credits” area. :-) [Sorry, I have OCD about “off of.”]
- What does this change? Adds Cloudflare Pages setup installation and a minor grammatical fix.
Tested with my own site, now available (as of now) at https://astro-site.pages.dev.
Public documentation was updated as noted above.
=> Update deploy.md for Cloudflare Pages

.changeset/angry-hairs-return.md, packages/astro/src/compiler/codegen/index.ts, packages/astro/src/compiler/index.ts, packages/astro/src/compiler/transform/head.ts, packages/astro/src/compiler/transform/util/end-of-head.ts, packages/astro/src/internal/h.ts, packages/astro/test/astro-doctype.test.js, packages/astro/test/fixtures/astro-doctype/src/components/Meta.astro, packages/astro/test/fixtures/astro-doctype/src/components/SubMeta.astro, packages/astro/test/fixtures/astro-doctype/src/layouts/WithDoctype.astro, packages/astro/test/fixtures/astro-doctype/src/layouts/WithoutDoctype.astro, packages/astro/test/fixtures/astro-doctype/src/pages/in-layout-no-doctype.astro, packages/astro/test/fixtures/astro-doctype/src/pages/in-layout.astro, packages/astro/test/fixtures/astro-doctype/src/styles/global.css, packages/astro/test/fixtures/no-head-el/src/pages/index.astro, packages/astro/test/fixtures/no-head-el/src/pages/no-elements.astro, packages/astro/test/no-head-el.test.js
This fixes a problem that people have been seeing where the doctype and/or head content is put into the wrong place.
This updates the `head.ts` file that is responsible for injecting head content and makes it only do so if there is an html or head tag, rather than doing so for all page components.
Tests added
Bug fix only
=> Fixes duplicate head content

.changeset/cold-lies-move.md, packages/renderers/renderer-preact/client.js
- Currently, the preact renderer isn't able to update a component's placeholder state on the server.
- In reading the docs, `hydrate()` is intended when the server output and client output are exactly the same. If the component can change, we should be using `render()`.
- I'm not sure if we have a way to test this, currently.
=> fix preact render to update a component on first render

docs/src/components/HeadCommon.astro, examples/blog/src/components/BaseHead.astro, examples/framework-multiple/src/pages/index.astro, examples/framework-preact/src/pages/index.astro, examples/framework-react/src/pages/index.astro, examples/framework-solid/src/pages/index.astro, examples/framework-svelte/src/pages/index.astro, examples/framework-vue/src/pages/index.astro, examples/snowpack/src/components/BaseHead.astro, examples/snowpack/src/pages/tutorials/getting-started.md, examples/starter/src/pages/index.astro, examples/with-nanostores/src/pages/index.astro, packages/astro/test/fixtures/astro-dynamic/src/pages/media.astro, packages/astro/test/fixtures/vue-component/src/pages/index.astro, www/src/components/BaseHead.astro
This updates all meta viewport tags to `<meta name="viewport" content="width=device-width" />`, reducing the complexity developers experience creating web sites.
**Before** (there are 2 variants found in Astro):
```html
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
```
```html
<meta name="viewport" content="width=device-width, initial-scale=1" />
```
**After**:
```html
<meta name="viewport" content="width=device-width" />
```
The removed portions were applicable in older browsers; specifically iOS < 9.
Additional details from WebHint:
- https://webhint.io/docs/user-guide/hints/hint-meta-viewport/
Details of its removal at Vercel:
- https://github.com/vercel/next.js/pull/10823#issuecomment-594833527
More information on `viewport-fit` …
=> Reduce meta viewport tag

.changeset/kind-crabs-marry.md, packages/astro/src/compiler/codegen/index.ts, packages/astro/src/compiler/index.ts, packages/astro/src/compiler/transform/head.ts, packages/astro/src/compiler/transform/util/end-of-head.ts, packages/astro/test/astro-doctype.test.js, packages/astro/test/fixtures/astro-doctype/src/components/Meta.astro, packages/astro/test/fixtures/astro-doctype/src/components/SubMeta.astro, packages/astro/test/fixtures/astro-doctype/src/layouts/WithDoctype.astro, packages/astro/test/fixtures/astro-doctype/src/layouts/WithoutDoctype.astro, packages/astro/test/fixtures/astro-doctype/src/pages/in-layout-article.md, packages/astro/test/fixtures/astro-doctype/src/pages/in-layout-no-doctype.astro, packages/astro/test/fixtures/astro-doctype/src/pages/in-layout.astro, packages/astro/test/fixtures/astro-doctype/src/styles/global.css, packages/astro/test/fixtures/no-head-el/src/pages/index.astro, packages/astro/test/fixtures/no-head-el/src/pages/no-elements.astro, packages/astro/test/no-head-el.test.js
This fixes the revert that took place in https://github.com/snowpackjs/astro/pull/1001
The previous fix was intended to prevent duplicate head content and head content being inserted into the wrong spot. This was caused by out head detection being off.
The previous fix didn't account for layouts that are part of markdown pages. This now fixes that by making sure that we account for layouts being called differently in this scenario and ensuring that the page's CSS is passed down.
Test added.
Also tested manually to verify the docs site works properly.
Bug fix only
=> Handle layouts and head injection

docs/src/pages/installation.md
- Remove `css||` in style tag.
- This is confusing. The implication is you can use one or (`||`) the other, but the instructions above just say "copy-and-paste".
- At the moment, if you try following these instructions to the letter, it looks as though styling doesn't work. The differentiation between CSS and SCSS is explained elsewhere in the docs.
- No tests, just a docs edit.
- Typo fix only
=> Fix typo by removing `css||`

docs/src/components/Header/LanguageSelect.css
- Fixes #1043
- I also replaced the `z-index` hack (that used `background-image: transparent` to work) with `pointer-events: none` that accomplishes the same thing that the author wanted (button is still pressed even if the cursor is over the icon)
| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/35617441/128541458-81d68b24-1e46-4a5f-a0dc-e22244f0b784.png) | ![image](https://user-images.githubusercontent.com/35617441/128553396-81454924-f3d1-438a-84bc-1b3fedab292f.png) |
Built and tested locally in firefox and chrome. 
- No differences noticed in light mode.
- Dark mode is readable in both browsers.
The styling of the docs was updated
=> Fix contrast issue in lang picker

.github/workflows/release.yml, docs/public/theme.css, docs/src/components/Header/Search.css
Addressed Issue #943.
- Styled the dark version of the search bar (Algolia).
- Added an orange line above the footer for both themes. There is a white gap there (maybe comes from an overflow somewhere), that's why I used a `:before` - a border wouldn't fix the gap.
- Removed shadows from search results and added a border for both themes.
`yarn start`
Documentation styles adjusted.
=> Styled the dark version of the search bar.

packages/astro/package.json
Fixes `files` pointing to old `astro.mjs` file that’s been renamed
No testing needed
No docs needed / changesets
=> Fix package files

docs/reference/api-reference.md, docs/src/pages/reference/api-reference.md, docs/src/pages/reference/renderer-reference.md, examples/snowpack/src/pages/tutorials/react.md, examples/snowpack/src/pages/tutorials/svelte.md
This updates 5 code examples in Astro documentation that fail when copy-pasted due to some missing commas.
Copy-paste the code examples and then attempt to execute them in their intended context.
I think this is a bug fix only.
=> Fix code examples that would fail if copy-pasted

examples/framework-lit/public/style/global.css, examples/framework-multiple/src/pages/index.astro, examples/framework-preact/src/pages/index.astro, examples/framework-react/src/pages/index.astro, examples/framework-solid/src/pages/index.astro, examples/framework-svelte/src/pages/index.astro, examples/framework-vue/src/pages/index.astro, examples/starter/public/style/global.css, examples/with-markdown-plugins/public/global.css, examples/with-nanostores/public/style/global.css
Super-minor change: adds fallbacks for the `system-ui` font family which Firefox doesn’t understand.
**Before** (Firefox)
**After** (Firefox)
No docs or changeset needed
=> Fix example font on Firefox

examples/docs/src/layouts/Main.astro
Adds references to the CSS in the example project docs
| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/35617441/128646850-e9f538f6-a152-48c2-9bdf-bfd3b14c370a.png) | ![image](https://user-images.githubusercontent.com/35617441/128646867-4f908355-77b6-408f-a332-84cf50f88977.png) |
Found this problem when I set up a clean astro project with `npm init astro`. Used documentation template and when running it, the site had no theme or code CSS. Doesn't seem like the project references `theme.css` nor `code.css` anywhere. Guessing this is how it's supposed to be?
Tested locally. 
Only bug fix, no doc change required.
=> Add CSS in example project: docs

.changeset/strong-pets-turn.md, docs/src/pages/es/getting-started.md
- Replaces some words that have the same literal translation but are used for different cases.
- Some words are not translated because they are better understood in English for technical docs (template instead of modelo).
- Uses second person of singular (tú) more consistently.
- Minor fixes.
No tests were written.
Getting Started page for Spanish was updated.
=> [i18n][Docs] Change some Spanish translations for Getting Started page

.vscode/launch.json, tools/language-server/src/plugins/typescript/DocumentSnapshot.ts, tools/language-server/src/plugins/typescript/TypeScriptPlugin.ts, tools/language-server/src/plugins/typescript/utils.ts
Closes #1023 
https://www.loom.com/share/d1defd0411554997a40eb38f22030e7b
Makes it so that typescript knows about Astro's exports. Also falls back to trying to resolve imports ourselves (to work with other framework imports).
N/A
N/A, bug fix
=> Fix GoToDefinition for component imports (and component usage)

.changeset/fair-dogs-tie.md, packages/astro/src/internal/__astro_component.ts
Relates to #681.
- This escapes `</script>` tags in string literals properly so the browser wouldn't parse them as actual `</script>` tags.
- See https://codepen.io/risker/pen/dyWqxLW?editors=1000 for a very simple issue reproduction.
- It can be worked around by escaping the / in the string, which is what I've done here: https://codepen.io/risker/pen/OJmBLPo?editors=1000
A simple example what this allows. Previously, there could not be a `client:load` directive in `children` because browsers broke the injected script.
```astro
<Browser
client:load
items={[
{
children: await (
<>
<ReactCounter client:load />
</>
),
},
]}
/>
```
Manually tested in my work-in-progress repository by changing stuff in `node_modules`. We could possibly add some unit tests for the `serialize` function, if need …
=> Fix nested client load directive

.changeset/wild-suits-raise.md, packages/renderers/renderer-vue/package.json, yarn.lock
It's a followup for #924 to use latest stable Vue version.
Nothing major changed since `beta.7`, while basics are covered by automated tests.
Nothing to update.
=> Bump Vue version to latest stable

docs/src/components/RightSidebar/MoreMenu.astro, packages/astro/src/compiler/index.ts, packages/astro/src/internal/__astro_component.ts, packages/astro/test/fixtures/vue-component/src/pages/index.astro, packages/astro/test/vue-component.test.js
There was an issue on the docs site where two islands of the same component, hydrated with `client:visible`, caused the `onVisible` hook to observe both components multiple times. This caused some sort of conflict between the two and incorrect results for `entry.isIntersecting`. The result was that the visible theme toggle wasn't hydrating on page load with `client:visible`.
- Covered by existing `client:visible` test.
- Can't currently test this specific case in our test suite since it requires browser behavior.
- N/A
=> Do not observe visible hydrate components more than once

www/src/components/MainHeader.astro, www/src/pages/index.astro
Switched Twitter link for Documentation link in header and added
inline Twitter, and Github links to bottom of page.
=> fix astro.build header links

.changeset/few-carpets-sing.md, packages/astro/src/cli.ts
Resolves #872 
- Adds groundwork for allowing environment variables to be used by the CLI
- Keeps CLI Flags as priority over environment variables, [based on this post](https://stackoverflow.com/questions/32272911/precedence-of-configuration-options-environment-registry-configuration-file-a) (flag > envvar > config > default)
- Allows `PORT` environment variable to be used (`PORT=4200 yarn dev`)
Manually tested this by running the build and starting the cli directly from the `astro.cjs` file
I haven't updated this yet because I'm unsure where this information should live.
**NOTE:** I was attempting to set this up so we could easily support additional environment variables in the future without much effort. I could probably instead add just a simple change instead of the current PR like …
=> Add PORT env var to be used

.changeset/curly-queens-pay.md, packages/astro/components/Prism.astro, packages/astro/src/compiler/transform/prism.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/scopedStyles-code.astro, packages/markdown-support/src/index.ts
Enables the syntax highlight when it's used with scoped styles (eg: code within a div wrapper)
- Enabled remark transform of `remarkCodeBlocks`
The code was already there, but it was not used 🤷🏻. 
Enabling it will preserve the `lang` & `class` property for the `code` tag.
This will already enabled syntax highlight in prism, but the scoped className is not passed down correctly.
Because of that, i've made the following change:
- Prism transform should pass down the received `class`
Add the incoming scoped className to prism transformer.
- Finally, fix the Prism component to render correctly the `pre/code` tags 
- According to PRISM docs, the lang could be used only in the `code` tag
```jsx
<pre class={classNames}><code lang="language-xx">...</code></pre>
```
Added a UT for this specific …
=> Fixes #1033 - Markdown with applied scopedStyles doesn't run Prism syntax highlight

.github/workflows/ci.yml
- Currently, Vercel is bottlenecked at a single concurrent build
- We want to remove vercel from unrelated PRs to speed up Vercel feedback for the PRs that need it
- But... having docs & www sites build on all PRs gives us confidence that nothing broke in those PRs
- So... This moves that check into Github CI (which isn't bottlenecked) so that we can remove Vercel builds from unrelated PRs and stop using Vercel as a test suite :)
=> add docs and www smoke tests to github CI

packages/astro/package.json, packages/astro/src/build/page.ts, packages/astro/test/fixtures/astro-pagination/src/pages/posts/named-root-page/[page].astro, packages/astro/test/fixtures/astro-pagination/src/pages/posts/optional-root-page/[...page].astro, yarn.lock
- Fixes an issue with installers not getting the latest snowpack version, which had an essential bug fix in it.
- Fixes an issue where we were calling `.flat()` on a promise instead of the awaited, resolved value of the promise.
- updated yarn.lock file
Updated 2 of our tests to be async functions, which would have caught the flat issue
=> make routing fixes from discord feedback

packages/astro/src/compiler/codegen/index.ts, packages/astro/src/compiler/transform/prism.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/braces.astro, packages/markdown-support/src/codeblock.ts
This resolves an issue where left curly brackets are incorrectly formatted by Astro, addressing #727.
This is a patch of #936, preserving the excellent work of @mmarkelov, with 3 (minor) differences:
- The changes are reduced, to minimize the real or perceived impact of the fix.
- The fix is made really explicit to ease future development or refactoring — `LEFT_CURLY_BRACKET_FIX`.
- The fix includes a null character (`\0`), greatly reducing the possibility of any accidental "false positive" fixes.
Tests are included, all from @mmarkelov’s original PR.
This doesn’t change documentation, but it does improve it.
See: https://docs.astro.build/core-concepts/astro-components#comparing-astro-versus-jsx
=> Fix left curly bracket formatting

docs/src/pages/comparing-astro-vs-other-tools.md
- Nuxt.js Official website url corrected from "https://nextjs.org/" to "https://nuxtjs.org/"
=> Nuxt.js official page url corrected

docs/src/pages/reference/cli-reference.md
Removes sentence about (and link to) dev server docs since those don't exist yet.
None - I just removed a sentence from the docs.
This was an update to the docs.
=> Remove sentence about dev server docs

tools/language-server/src/index.ts, tools/language-server/src/plugins/astro/AstroPlugin.ts, tools/language-server/src/plugins/html/HTMLPlugin.ts, tools/language-server/src/plugins/typescript/LanguageServiceManager.ts
Closes https://github.com/snowpackjs/astro/issues/1021
Loom: https://www.loom.com/share/3e513a5a97e64446acf9d2af80d41e36
Updates the Astro plugin in the vscode extension to provide prop suggestions on components that export a `Props` interface.
=> Provide completion suggestions in component props

docs/public/index.css
Docs typesetting fix for the attached screenshot
=> Revert short line-height for `<ul>`'s

docs/src/pages/comparing-astro-vs-other-tools.md
- Add elder.js comparison
- Add Gatsby comparison
- update perf audit scores (including a lighthouse bump from 95->99 and a JS payload bump from ~7kb to ~70kb
=> DOC: Update astro comparisons

docs/public/index.css
Anchor links should be the same weight as the text without a link.
If we wanted to, we *could* set the font-weight as `heavier` maybe? Is that an option? So that it just chooses an increase in font-weight for differentiation from text outside of a link.
This was mainly a problem with headings that have links, the difference in font-weight stuck out like a sore thumb to me.
=> 📘 DOC: Remove `font-weight:400;` from anchor links 

docs/src/pages/core-concepts/astro-components.md
~~Bolds some words because a few people (me included) have missed these words 😄~~
Makes a paragraph in the docs into a blockquote and makes "In the future" **_Bold and Italic_**
Closes #1070 
Tested locally
Yes
=> Bold props interface words

.changeset/seven-singers-mate.md, docs/src/pages/reference/api-reference.md, packages/astro/src/compiler/codegen/index.ts, packages/astro/src/compiler/codegen/interfaces.ts, packages/astro/src/compiler/codegen/utils.ts, packages/astro/src/compiler/index.ts, packages/astro/test/astro-global-build.test.js, packages/astro/test/astro-global.test.js, packages/astro/test/fixtures/astro-global/src/components/ChildResolve.astro, packages/astro/test/fixtures/astro-global/src/pages/resolve.astro
Closes #310 and #1071
This adds support for Astro.resolve as described in the #1071 RFC.
Tests added.
Docs added.
=> Astro.resolve

.changeset/calm-walls-unite.md, packages/astro/src/compiler/transform/postcss-scoped-styles/index.ts, packages/astro/test/astro-scoped-styles.test.js
Fixes #1074. In certain situations, our CSS scoping would encounter unexpected characters and scope classes unnecessarily (like `body`). This PR adds better css sanitization
Test added.
Bugfix; no docs needed.
=> Fix body scoping

docs/src/config.ts, docs/src/pages/fr/getting-started.md, docs/src/pages/fr/installation.md, docs/src/pages/fr/quick-start.md
The French documentation has never been this big! 😄 
Hmm, not sure how to test markdown. Maybe add https://github.com/markdownlint/markdownlint in the future?
Oui, en effet.
=> docs: added 2 pages in French

CONTRIBUTING.md
- fix some bad docs in CONTRIBUTING.md related to prerelease mode
=> docs: Update prerelease contributing docs 

.github/workflows/congratsbot.yml
Makes this workflow not run in forks, since it sends emails to me when it fails:
_**I have not, and I have no idea how to test**_ 😅
I just saw this solution in an issue on https://github.com/actions/runner/, and also that most workflows use this in [quarkus.io](https://github.com/quarkusio/quarkus/tree/main/.github).
Definitely test somehow before merging! (or don't, I mean, the only effect it has is that I don't get a congratulation when the PR is merged if the code is wrong)
No
=> Make congratsbot not run in forks

packages/astro/src/compiler/codegen/index.ts, packages/astro/src/compiler/codegen/utils.ts
- #1085 added a "relative link" warning if a component uses a relative URL for an attribute
- this created false positive warnings for pages in the docs site:
```
[dev server] Server started in 904ms.
[dev server] Local: http://localhost:3000/
[access] /
[relative-link] This value will be resolved relative to the page: <a href="#article">
[access] /getting-started
[relative-link] This value will be resolved relative to the page: <a href="quick-start">
[relative-link] This value will be resolved relative to the page: <a href="#article">
```
- This PR removes warnings for `#hash` URLs which aren't really relative
- This PR also changes the warning to not warn on pages, since pages can assume relative URLs work. This is especially common for Markdown. In docs specifically, we use relative so …
=> fix too strict "relative link" errors in docs website

www/src/pages/blog/astro-019.astro
Thanks for catching this typo @bLaCkwEw!
Docs only, fixes a typo in the 0.19 blog post
None, gotta love one character fixes!
Fixes typo in the blog post, "1005" -> "100%"
=> Fix B#1156 typo in v0.19.0 blog post

docs/src/layouts/MainLayout.astro
Docs only, fixed a typo in the main layout that caused the mobile sidebar toggle to not work.
Mobile sidebar toggle now works on dev environment after change.
None added (bug fix only)
=> docs: fix mobile sidebar toggle

docs/src/pages/guides/markdown-content.md
- Fixes the heading levels of the [Markdown](https://docs.astro.build/guides/markdown-content) section of the docs
- Adds more information about `content.astro` (specifically `headers` and `source`)
- Rewording, clarifications, fixes typos, etc.
Tested locally
It is docs
=> [DOCS] Add more information about content.astro (markdown)

CONTRIBUTING.md, GOVERNANCE.md
- This is a PR to update a v2 of our governance docs, focused on improvements in the contributor model.
- It is based off of feedback over the last few months with our current governance model, collected recently in the #general thread in discord (astro.build/chat).
- new names for contributor levels: **Contributor** -> **Maintainer** -> **Core Maintainer**
- more explicit that coding isn't required to be a contributor/maintainer
- more explicit privileges listed for all levels (more clear why someone might want to become a contributor)
- more explicit responsibilities listed for all levels
- more explicit nomination instructions for all levels
- ~~WIP: Still needs a bit more clarity on voting processes, but the larger changes to contributor levels are ready to review.~~ Done!
- Looking …
=> Update Governance + Contributor Model

.changeset/late-moons-wave.md, packages/astro/src/compiler/transform/postcss-scoped-styles/index.ts, packages/astro/test/astro-scoped-styles.test.js
Fixes #1155. Basically a lazy RegEx assumed that the `:global()` selector always wraps the entire selector, when this may not be the case. 
Tests added.
I took a look at the existing `:global()` docs and they seem to suffice? I think this bug is more-or-less not working as expected rather than the documentation being missing or misleading.
=> Fix :global() scoping

.changeset/great-poets-pull.md, packages/astro/components/Prism.astro, packages/astro/test/astro-markdown.test.js
Fixes #1179 (yes, I just filed that 2 minutes ago :laughing:)
Adds the `language-___` class back to the `<pre>` tag when rendering Prism code blocks
Markdown code test updated to make sure the `<pre>` tag includes the correct class
Bug fix only, no doc updates needed
=> including the `language-` class on Prism's `<pre>` element

packages/astro/astro.js
- Fixes an issue brought up in Discord
- Manually tested on a bunch of different Node.js versions
=> add a real-world check for ESM<>CJS named export support

docs/src/components/HeadSEO.astro, docs/src/layouts/MainLayout.astro
This changes the `HeadSEO.astro` implementation so that `og:title` uses the **title** and the **site title** as the fallback. This is to follow [`og:title` guidance](https://developers.facebook.com/docs/sharing/webmasters/), and because it helps cards look "snappier" when embedded in cards on services like 
In progress...
This makes no changes to current documentation that I know of.
=> Use title, with site title as the fallback

docs/src/components/Header/LanguageSelect.css, docs/src/components/Header/Search.css, docs/src/components/Header/Search.tsx
- Fixes an issue blocking #1166 
- Can't test without #1166, so you can test manually by opening your devtools and setting `<html dir="rtl">` and seeing that the search bar look good.
=> fix the "rtl" displayed search bar & language selector

.changeset/wet-schools-dream.md, docs/src/config.ts, docs/src/pages/guides/debugging.md, docs/src/pages/reference/builtin-components.md, examples/minimal/package.json, packages/astro/components/Debug.astro, packages/astro/components/index.js, packages/astro/package.json
- Adds a `<Debug/>` component to Astro, closing #411 
You can use this with Astro's shorthand syntax by passing in any value surrounded by curly braces. You can also do something like `<Debug value={someValue} />`. The component supports any named prop, so it doesn't matter what you call it.
```astro
---
import { Debug } from 'astro/components';
const object = { /* ... */ };
---
<Debug {object} />
```
=> Add Astro `<Debug/>` component

docs/src/components/Header/LanguageSelect.tsx, docs/src/config.ts, docs/src/pages/index.astro, docs/src/pages/kr/getting-started.md
- Translated the Getting Started page into Korean.
- kr is added to KNOWN_LANGUAGE in docs/src/pages/index.astro.
- kr config is added to config.ts.
- kr option is added in the language selector.
- Functionality tested locally
- For better quality of translation, it would be nicer if someone else can check and review it.
This is only documentation update.
=> [i18n][Docs] Add Korean Translation of Getting Started page

.changeset/violet-crabs-deny.md, packages/astro/src/compiler/index.ts, packages/astro/test/astro-global.test.js, packages/astro/test/fixtures/astro-global/src/components/nested/InnerChild.astro, packages/astro/test/fixtures/astro-global/src/pages/resolve.astro
Fixes #1211
Previously `Astro.resolve` was being passed down from the page to child components, causing it to always resolve from the page. Since that's not the behavior we want, I removed that code.
Components were already tested, but nested components were not, which is why this bug was not caught in implementation.
Bug fix only.
=> Fix resolution of Astro.resolve in nested components

docs/src/pages/reference/builtin-components.md
If you don't like my text, you can change it. But, an issue was filed that our docs don't currently mention that you need to specify a language to get syntax highlighting, and the example doesn't even show a language. https://github.com/snowpackjs/astro/issues/1261
- Docs example for Prism component changed to include lang="js" because no language was previously specified 
- Link to Prism's list of supported languages/alias
- mentioned that lang="astro" is valid, too!
No tests.
Only documentation updated, as described above, to emphasize choosing a language when using the component.
=> Include lang="xxxx" in Prism component example

.changeset/silver-otters-eat.md, packages/create-astro/src/index.ts
- Formats console log statements so the code is easier to read by using template literals everywhere
- Add a check to see if the renderers array is empty and only show the message about using the templates default renderers if it isn't
=> create-astro: Format console logs and fix message about default renderers

docs/src/pages/guides/styling.md
Off the back of an issue raised [here](https://github.com/snowpackjs/astro/issues/1256), this PR adds a section to the tailwind styling documentation to let others know of a breaking change with bundling public styles. 
It looks like this once rendered: 
- I've added string interpolation to the example of `Astro.Resolve()` instead of quotation marks to get the code to render correctly, quotations wont work and stray from the styling of the documentation
- I've only done this documentation directly here, because I don't doubt the team has a bigger plan for rolling this out to all aspects of Astro
* This was tested and discussed in the attached issues
* This is only a doc update
As of [Version 20](https://github.com/snowpackjs/astro/releases/tag/astro%400.20.0), Astro will no longer bundle, …
=> Add v20 documentation for bundling assets

docs/src/pages/reference/api-reference.md
https://github.com/snowpackjs/astro/pull/960 was merged that allows `Astro.request` to be accessed in children components of pages, so this caveat no longer applies.
=> Remove caveat about `Astro.request` not being passed to components.

docs/src/pages/reference/api-reference.md
Minor update to api-reference.md
- Remove line that refers to 'Core Concepts - Collections' given these is now deprecated and the link returns a 404.
Tested using local dev/build.
This is purely an update to the docs.
=> Remove reference/link to Collections

.github/workflows/stat.yml, package.json, scripts/stats/index.js, scripts/stats/stats.csv, yarn.lock
- We want to get better about collecting stats on the repo health, community activity, etc.
- This runs a data collection GH action every 24 hours, automatically
- All of this data will be public in `scripts/stats/stats.csv`
- Tested locally and on GH actions (see GH result: https://github.com/snowpackjs/astro/pull/1284/commits/a992696772c5d6eb4aaf676a51cb1784745eb9b6)
=> Collect nightly stats on the repo

docs/src/pages/reference/api-reference.md
- Documentation update
- N/A
- Delete text referring to old (and now removed) Collections API
Fixes #1258
=> Delete docs text about removed Collections API

scripts/stats/index.js, scripts/stats/stats.csv
- GH considers PRs to be issues.
- For our collection we want to differentiate issues from PRs. This subtracts PRs from issues to get the number we are trying to track.
N/A
N/A
=> Nightly stats: don't count PRs as issues

.github/workflows/issue.yml
- We have trouble keeping our project boards up to date at all times
- Now that we have stats, this becomes an important stat to track
- This CI bot will auto-add new issues to the proper board, if it can be detected
- Unfortunately this one is hard to test since it won't run until merged to main. So, if the code looks good, I'd recommend that we merge and then we can test on main with a couple of mock issues.
=> add project assigner CI bot

.changeset/perfect-kids-occur.md, packages/astro/components/Markdown.astro, packages/astro/components/Prism.astro
- Adds interfaces for the `Prism` and `Markdown` component.
N/A
N/A
=> Add interfaces for built-in components

packages/astro/src/build/sitemap.ts, packages/astro/test/fixtures/astro-rss/src/pages/404.astro
- Sitemap generation skips `404.html` page (used for routes not otherwise found for the site).
- Updated sitemap test fixture (`astro-rss`) to include a `404.astro` page that should not be included in the sitemap output.
- Nothing to update in docs
=> skip 404.html pages in sitemap generation

docs/src/pages/reference/builtin-components.md
by using `import { Debug } from 'astro/debug'` to import the debug component we have :
> Error: Unable to render Debug because it is undefined! Did you forget to import the component or is it possible there is a typo?
because Debug = undefined
that hapend because of this ligne in astero's package.json :
```
"exports": {
...
"./debug": "./components/Debug.astro",
...
},
```
it means that `'astro/debug'` point directly to the component and we have to import it like a normal component :
```js
import SomeComponent from './SomeComponent.astro';
```
So in the exemple we have to importe the component like that
```js
import Debug from 'astro/debug';
```
with
```
---
import Debug from 'astro/debug';
const serverObject = {
a: 0,
b: "string",
c: {
nested: "object"
}
}
---
<Debug {serverObject} /> …
```
=> Debug component importation

docs/public/code.css
- Add some css rules to prevent users from selecting `+` `-` characters in `diff` block.
Currently I can select the `+` `-`:
Which means after I paste the selection into my `package.json` file, I have to delete the `+` to make it work.
With `user-select` set to `none`, we won't have such a problem.
Not needed.
None.
=> docs: set +/- prefix to non-selectable

docs/src/config.ts, docs/src/pages/guides/publish-to-npm.md, docs/src/pages/themes.astro
- Rewrites the "publish to npm" documentation
- Main goal was to make it clear how to set up your project directory
- DONE: Add a note about style rules currently being broken.
- TODO in a follow-up PR: Create an example github repo "template" that others can fork from
- TODO in a follow-up PR: Add that template to `npm init astro`
=> 📘 DOC: New "Publish to npm" documentation

.changeset/four-plums-train.md, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/empty-code.md, packages/markdown-support/src/codeblock.ts
Added a test at `packages/astro/test/astro-markdown.test.js`, I felt like it belonged in markdown-support, but it looks like that package doesn't have testing setup..
=> Fix parsing of an empty literal `<pre></pre>` in markdown source

docs/src/pages/installation.md
I see people often ask about opening up the app to local network so this looked like a good place to explain how to do it.
- Opens up the app on all local IP adresses to share on the network
Tested by opening an app from another computer on a network
Yes, public docs updated
=> Opening app to all IPs instead of localhost

www/src/pages/blog/netlify-astro-hosting-sponsorship.astro
- Fixing typos in the blog post announcing the Netlify sponsorship of Astro.
Only typo fixes. No semantic or structural changes were made.
P.S.: Congrats on the funding. :smiley:
=> Fix typos in Netlify sponsorship announcement blog post

.changeset/quiet-horses-turn.md, packages/astro/src/build/bundle/css.ts, packages/astro/test/astro-css-bundling.test.js, packages/astro/test/fixtures/astro-css-bundling/src/css/page-preload-merge-2.css, packages/astro/test/fixtures/astro-css-bundling/src/css/page-preload-merge.css, packages/astro/test/fixtures/astro-css-bundling/src/css/page-preload.css, packages/astro/test/fixtures/astro-css-bundling/src/pages/preload-merge.astro, packages/astro/test/fixtures/astro-css-bundling/src/pages/preload.astro
During CSS bundling, it prevents taking `<link rel="preload"` as stylesheet, by introducing a separate list for de-duping preloads.
It prevents from removing actual styles loading, and loosing attributes of these nodes for example `media` or `onload`.
In my case:
```astro
---
const stylesUrl = Astro.resolve('../styles.css')
---
<head>
<link rel="preload" as="styles" src={stylesUrl} />
<link rel="stylesheet" src={stylesUrl} media="print" onload="this.media='all'" />
</head>
```
compiles to
```astro
<head>
<link rel="stylesheet" type="text/css" href="/_astro/common-NA79w.css" />
</head>
```
Which breaks the whole async loading, I'm trying to use.
I wrote tests to cover this case.
It's a bug fix, I guess.
=> Prevent removing CSS preloads during bundling

.github/workflows/stat.yml
- We tried to do an npm install instead of a yarn install to speed it up
- npm decided to change our package.json, and then we would commit that change, causing the yarn.lock file to be outdated
- See example: https://github.com/snowpackjs/astro/commit/e758060e3bdf0a0a17188d6bb30b4371690c855a
=> fix outdated lockfile issue

.changeset/serious-fishes-lay.md, docs/src/pages/guides/deploy.md
- Adds a disclaimer+workaround to Github pages deploy guide
- > By default, github pages will deny access to the `_astro/` directory. Add an empty `.nojekyll` file in the `public` folder for your site to function properly.
- Am open to feedback about rewording/reformattimg the disclaimer
References:
https://discord.com/channels/830184174198718474/887002135403827240/ (help thread where this came up)
https://github.com/mpetrovich/stylemark/issues/65 (another issue with the fix)
No testing, only docs changed.
Documentation updated
=> Disclaimer for Github pages / jekyll quirk

.changeset/perfect-kids-occur.md, docs/src/components/Footer/AvatarList.astro, examples/blog-multiple-authors/src/pages/authors/[author].astro, examples/blog-multiple-authors/src/pages/index.astro, examples/blog-multiple-authors/src/pages/posts/[...page].astro, examples/blog/src/components/BlogPost.astro, examples/blog/src/pages/index.astro, examples/portfolio/src/pages/projects.astro
- This adds interfaces for `fetchContent` and for some props to get rid of errors that you see in the new VSCode extension with diagnostics on.
N/A
N/A
=> Add types to examples and docs

.changeset/perfect-kids-occur.md
@matthewp just confirming that this was unintentional, since this isn't actually a change to the `astro` package / doesn't touch `packages/astro`.
=> Delete incorrect changeset

docs/src/pages/guides/deploy.md
Changing directions for Netlify deployment! Details below.
N/A
Changing directions for Netlify deployment because of their [new build image](https://answers.netlify.com/t/all-new-sites-now-build-on-netlify-using-the-new-focal-build-image/42665), which uses Node 16 by default.
=> Update deployment docs for Netlify deployment

.changeset/blue-birds-pretend.md, packages/renderers/README.md, packages/renderers/renderer-lit/readme.md, packages/renderers/renderer-preact/README.md, packages/renderers/renderer-react/README.md, packages/renderers/renderer-solid/README.md, packages/renderers/renderer-svelte/README.md, packages/renderers/renderer-vue/README.md
Just adds a stub in the `packages/renderers/` folder pointing to the full documentation, as well as stubs in the renderer packages themselves linking to the documentation.
Matthew wrote such good docs for renderer-lit! I didn’t do the same for the rest; just wanted to get these started.
No tests needed.
Docs change only.
=> Docs: Add READMEs for renderers

.changeset/pink-toes-shake.md, docs/reference/api-reference.md, docs/src/pages/reference/api-reference.md, packages/astro/src/compiler/index.ts, packages/astro/test/astro-slots.test.js, packages/astro/test/fixtures/astro-slots/src/components/SlottedAPI.astro, packages/astro/test/fixtures/astro-slots/src/pages/slottedapi-default-filled.astro, packages/astro/test/fixtures/astro-slots/src/pages/slottedapi-default.astro, packages/astro/test/fixtures/astro-slots/src/pages/slottedapi-empty.astro, packages/astro/test/fixtures/astro-slots/src/pages/slottedapi-filled.astro
This adds the ability to check whether specific slots have been used in a component via `Astro.slots`, similar to `Astro.props`.
This fulfills the approved RFC #1301.
Tests were added to confirm the default slots behavior as well as the new `Astro.slots` functionality.
Documentation with example usage of `Astro.slots` is added to the **API Reference** section.
=> Expose slots to components

.changeset/five-phones-draw.md, packages/astro/src/build/stats.ts
- 13b instead of 0kb, if the number is small
- 13Mb instead of 13949kb, if the number is large
- Not output tests currently
- None needed
=> Make build stats prettier

packages/astro/test/benchmark/benchmark.js, packages/astro/test/benchmark/build.bench.js, packages/astro/test/benchmark/dev.bench.js, packages/astro/test/integration-docs.test.js, yarn.lock
- Our test suite doesn't run if you only change examples, so we didn't catch that removing the outdated snowpack example broke our benchmark test suite
- this moves the benchmark to use our docs site instead
- also, removing snowpack changed our yarn.lock file, so this updates that as well
=> fix bad benchmark test

package.json, packages/astro/package.json, packages/astro/src/runtime/hmr.ts, packages/astro/src/runtime/ssr.ts, yarn.lock
Fix `npm install astro@next--compiler`
=> Fix npm install

packages/astro/package.json, packages/astro/src/runtime/astro.ts, yarn.lock
There have been some changes to the compiler output lately! This just updates the `astro/internal` file to use them.
Manually tests
N/A
=> Update `@astrojs/compiler` to latest

docs/src/pages/guides/styling.md
Updating tailwind code example to match description.
N/A documentation change only.
Breaking change 0.19 to 0.20 documentation references `src` as the proper path but the code example below it uses `assets`. Updated the code to match the documentation.
=> update code to match description

docs/src/pages/core-concepts/astro-components.md
In the current documentation it is only shown how to receive props but not how to pass a component said props.
This adds a bit of example code which shows how to pass props to a component.
No tests needed.
The change was for the documentation.
=> 📘 DOC: show how to pass props

docs/src/pages/comparing-astro-vs-other-tools.md
[Zola](https://www.getzola.org/) is a fast, Rust powered Static Site Generator that is a lot like Hugo. I think that there should be a comparison page for it due to it becoming popular (7k stars).
- Added a Zola comparison to the Astro comparison page, based off of the Hugo comparison.
Tests not applicable due to no code change.
Refer to the changes section
=> Add Zola comparison

docs/src/pages/nl/getting-started.md
Fixes a typo (_odpracht_ → _opdracht_).
No tests were added, as no code changed.
Typo was fixed in the documentation.
=> Fix typo (odpracht→opdracht)

docs/src/components/Header/LanguageSelect.tsx, docs/src/config.ts, docs/src/pages/index.astro, docs/src/pages/ja/getting-started.md
- Translated the Getting Started page into Japanese.
- I have confirmed that all the links work in my local environment
Document update only
=> docs: Add Japanese translation of getting started page

.github/workflows/release-next.yml, packages/astro/package.json, packages/astro/src/build/index.ts, yarn.lock
On merge to `next`, a GitHub action publishes a snapshot release. Something about the `yarn` command in that context installs a slightly-different version of Rollup, or TypeScript, or something. Because there’s a type error about `@web/rollup-plugin-html` that prevented a CI build.
(can be tested on merge to `next`)
no docs necessary
=> Fix CI release on merge to next

.changeset/blue-wombats-hammer.md, packages/astro/src/compiler/codegen/index.ts, packages/astro/src/compiler/index.ts, packages/astro/test/astro-components.test.js, packages/astro/test/fixtures/astro-components/src/components/Props-Component.astro, packages/astro/test/fixtures/astro-components/src/pages/props-shadowing.astro
This should fix the props shadowing mentioned in #1126. I don't think it will help after the Go compiler is made the default, but it should still help as of now.
- Changes `props` names in two files to `$$props`
- None
- None
=> Fixed props shadowing

docs/src/pages/es/getting-started.md
Fixes 3 small typos errors in the Spanish documentation
- ES documentation typos fixes.
N/A
Just typos.
Fixed typos:
- caracteristicas -> características
- comienzes -> comiences
- version -> versión
=> Docs: Fix typos in the ES documentation

docs/src/pages/comparing-astro-vs-other-tools.md
According to [the current Lighthouse report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdocusaurus.io%2Fdocs), Docusaurus scored 61 points for performance.
Preview
Actualized the information in the docs to reflect the real situation with performance in Docusaurus.
=> Update Docusaurus performance score

.changeset/weak-sheep-clap.md, packages/renderers/renderer-lit/package.json, packages/renderers/renderer-lit/server-shim.js, yarn.lock
Bumps to the official v2 release of Lit and the official v1 release of @lit-labs/ssr in the lit renderer
Tests are passing
Shouldn't need any documentation update.
=> Update lit version to v2

.changeset/hungry-wolves-shave.md, packages/astro/src/logger.ts
* Fixed issue of compiler crash when "c" locale was encountered
* Return default locale if parsed locale is less than 2 chars long
* Fixed issue of compiler crash when "c" locale was encountered
* Return default locale if parsed locale is less than 2 chars long
This change was tested by running Astro on the docs website. Everything went fine as far as logger is concerned. It would be much appreciated if this was tested again on some different project.
No docs added due to this being an internal change
=> Fix logger locale parsing

docs/src/pages/installation.md
The `starter templates` link on [Installation](https://docs.astro.build/installation#create-astro) page is currently pointed at 404 page: https://docs.astro.build/examples.
This fix, simply replace the URL with: https://github.com/snowpackjs/astro/tree/main/examples
No tests were added. Documentation fix only.
The documentation was updated.
=> Fix URL to "starter templates" link

examples/portfolio/src/pages/project/mars-rover.md, examples/portfolio/src/pages/project/nested/lunar-eclipse.md, examples/portfolio/src/pages/projects.astro
Project page (`/projects`) of portfolio example wasn't displaying any projects.
- changed `published_at` in front matter to match `publishDate` in the [template's filter](https://github.com/snowpackjs/astro/blob/2293fa05305d5767a53f15db85fa7c3132dd1f3c/examples/portfolio/src/pages/projects.astro#L12)
- fixed the `fetchContent` pattern to find nested files
Both projects are displayed now.
Copied and built the example to check changes.
Bug fix only.
=> Portfolio example fix

packages/astro/package.json, packages/astro/src/build.ts, packages/astro/test/fixtures/astro-assets/src/pages/index.astro, yarn.lock
Refactored from #1317
- Improved functionality of `<img>` `srcset` checking as original failed when URL contained a comma ( `,` ).
- Added `srcset` checking for `<source>`
- Added test to current assets test (`packages/astro/test/fixtures/astro-assets/src/pages/index.astro`) rather than create a separate one 
N/A
=> Updated srcset checking

docs/src/pages/guides/deploy.md
Updated the deploy docs for GitLab pages to reflect a more accurate understanding of how to deploy to GitLab pages using the existing astro configuration. Hopefully, the wording is clear, I played around with it for a bit.
- Tested on my own GitLab repo
- Docs are updated to reflect the newest understanding of configuration
=> Update deploy docs for gitlab pages

docs/src/pages/getting-started.md
Remove duplicated info from Getting Started.
We already have the link to the home page in the first paragraph.
=> [docs] Remove duplicated info from Getting Started

www/src/pages/blog/astro-019.astro
Fixed  a typo in the blog post astro-019
'''astro -> ```astro
Four backticks are used to escape three backticks in the content. 
Manually run `npm run dev` under the `www` directory and checked the page rendered by the browser.
Before (the current version at https://astro.build/blog/astro-019)
After (the preview version rendered by vercel at https://astro-www-git-fork-weakish-markdown-syntax-typo-479862-pikapkg.vercel.app/blog/astro-019)
This is a documentation change.
=> fix a typo in blog astro-019 '''astro -> ```astro

examples/blog/src/components/BlogPost.astro
add string type to the props `alt` in the blog example.
only tiny type fix
only tiny type fix
=> chore: add alt type

.changeset/odd-owls-clean.md, packages/create-astro/src/index.ts
Running astro create with the doc template currently crashes with,
```UnhandledPromiseRejectionWarning: TypeError: fs.promises.rm is not a function```
This leaves a partially generated project that when run renders this cryptic error.
The reason being that `.rm` wasn't added to Node till version 14.14.0. https://nodejs.org/docs/latest-v15.x/api/fs.html#fs_fspromises_rm_path_options
This just changes to the `unlink` variant for removing the file to prevent that crash in node 12.
=> switch from rm to unlink in order to preserve node 12 compatability in astro-create

docs/src/components/Header/LanguageSelect.css, docs/src/components/RightSidebar/ThemeToggleButton.css
- Adds a different arrow to the language select since you couldn't click on it when you hovered straight over the arrow
- Adds cursor: pointer to the theme toggle css to show you can click on it
|Before|After|
|---|---|
|![Language select before](https://user-images.githubusercontent.com/71938724/135668748-3ed95935-289c-4577-9f62-bea2162d6805.png)|![Language select after](https://user-images.githubusercontent.com/71938724/135668949-a36c4790-6d61-40e9-978d-eb5e8ab83d98.png)|
|![Theme toggle before](https://user-images.githubusercontent.com/71938724/135669023-9d6f1720-3c18-441d-80c0-e80b204d9cbe.png)|![Theme toggle after](https://user-images.githubusercontent.com/71938724/135669060-3ad41e12-b610-4722-99f4-dbbd7e2b70b7.png)|
=> docs: Improvements to language select and theme toggle

docs/src/pages/comparing-astro-vs-other-tools.md
According to https://v4.gatsbyjs.com/docs/how-to/rendering-options/using-server-side-rendering/, Gatsby now supports SSR by version 4, so the comparison's information is outdated. This PR changes the comparison to reflect that Gatsby now supports SSR
- Updated comparison to reflect Gatsby supporting SSR
None because no code was changed
See changes
=> Update comparison to reflect Gatsby SSR Support

.github/workflows/ci.yml
- remove boilerplate caching code `setup-node@v2` provides, it might take one run to re-initialize the dependency cache
I've updated this successfully for various `npm` and `yarn` projects with similar boilerplate caching steps.
This is mostly a cleanup task.
=> Use setup-node action's caching

www/src/pages/blog/index.astro
Previously the index page of the blog was out of date, as mentioned by #1441. This PR fixes that.
I also could add the blog index to the website index header, but I did not because that is out of the scope of this PR and I was unsure whether there was another reason for there not being a link to the blog in the header.
- The blog index page has been updated with the demo day post for September.
None do to the change only being relevant to the blog.
None do to the change only being relevant to the blog.
=> Updated blog index with demo day post

packages/renderers/renderer-solid/client.js, packages/renderers/renderer-solid/index.js, packages/renderers/renderer-solid/server.js, packages/renderers/renderer-solid/static-html.js
This change updates Solid's renderer to hydrate instead of delete all the elements in the browser and recreate them. That being said there are some other considerations here.
Solid currently doesn't support multiple asynchronous hydration roots. Since components in Astro can be hydrated at any time there is no guarantee of synchronous execution. This can cause conflicts with automatic data serialization and event replaying. To avoid pitfalls this PR disables both of these features.
In so, I have changed the renderer to be synchronous (ie.. renderToString) during static generation. The impact is that Suspense will now only run in the browser and any async data fetching will need to happen outside of the Solid Components if you wish it to happen on the server. If a user chooses to use …
=> Add hydration to Solid renderer

packages/astro/src/internal/index.ts, packages/astro/test/astro-children.test.js
- Adds back in support for passing children into framework components
Yep, astro-children.js is uncommented out.
N/A
=> Add back in support for children

packages/astro/components/Markdown.astro
- Keeps Astro from crashing when using `<Markdown></Markdown>`
Manually
Bug fix only
=> [next] Gracefully handle <Markdown> without content

.changeset/tall-crabs-care.md, packages/renderers/renderer-react/server.js
- Fixes some problems with the React renderer as reported on Discord.
Manual, using `react-bootstrap`
Ecosystem compat improvement
=> feat: improve support for third-party React packages

packages/markdown/remark/src/remark-prism.ts
- Removes the prism warning seen in the starter template.
No
No
=> Remove prism warning when no language is provided

docs/src/pages/guides/deploy.md
Added missing capitals, periods, fixed indentation on code blocks, and fixed typo in the word "access".
- Fixed the following errors in the Deploy section of the docs:
- Added missing periods to the end of sentences (to improve readability and to maintain a consistent style across docs sections).
- Added missing capitals to start of sentences
- Fixed indentation on code blocks under the GitLab Pages section (to maintain consistent style across code blocks).
- Fixed typo in the word "access" under Google Cloud Run.
N/A - Docs grammatical fix only.
Docs updated as detailed above.
=> Docs: fixed typos in Deployment.

docs/src/pages/reference/api-reference.md
- Adds missing curly brace ('}') to API Reference example in the docs.
- N/A (docs change only, grammatical fix)
- Added missing curly brace to API Reference example.
=> Docs: Fixed typo in API Reference.

docs/src/pages/guides/imports.md
- Removes the link to `/guides/wasm`
- Maybe we could instead actually flesh out what *using wasm with astro* means? Is this something where we could pull prior art from <https://github.com/snowpackjs/astro-repl>?
=> Remove reference to nonexistent `/guides/wasm.md`

docs/src/config.ts, docs/src/pages/ja/themes.astro
- Translated the Themes page into Japanese.
I have confirmed that all the links work in my local environment
Document update only
=> Docs: Add Japanese Themes page

packages/astro/src/@types/astro-runtime.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/runtime/server/util.ts
- Moves hydration related changes to a `hydration.ts` file. This includes creating the hydration script and extracting the directives.
- Moves common utils to a `util.ts`.
- Removes `isPage` as that's not needed any more.
- Small type improvements.
N/A
N/A
=> Small refactor to the server runtime

.github/workflows/ci.yml, .github/workflows/format.yml, .github/workflows/release.yml, .github/workflows/stat.yml, packages/astro/src/core/build/index.ts, packages/astro/src/core/ssr/index.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js
Enables Windows tests, fixes Windows bugs.
Current status: dev is passing in Windows! 🎉 But build seems to still have an error. So the problem is halfway solved; it just seems like there’s an extra step in build that’s failing.
Tests should pass! 
Vite-wise, Vite currently doesn’t have any tests for these code paths. We could look into adding them, but it’d be tough to do without adding new compile-to-HTML examples. Will look into it after this is passing.
No docs needed
=> Enable Windows tests

packages/astro/package.json
This restores typings to `astro@next` by adding the appropriate `types` key back to `package.json`.
Without it, the following code reports an error in VSCode, because it "_Cannot find module 'astro' or its corresponding type declarations_".
**Note**:
In Astro v0.20, the `types` path was `./dist/types/@types/public.d.ts`.
In Astro v0.21, the `types` path is now `./dist/types/@types/astro-core.d.ts`.
This was tested by manually adding `types` to an installation of Astro.
typing fix only
=> Restore astro typings

examples/blog-multiple-authors/sandbox.config.json, examples/blog/sandbox.config.json, examples/docs/sandbox.config.json, examples/framework-lit/sandbox.config.json, examples/framework-multiple/sandbox.config.json, examples/framework-preact/sandbox.config.json, examples/framework-react/sandbox.config.json, examples/framework-solid/sandbox.config.json, examples/framework-svelte/sandbox.config.json, examples/framework-vue/sandbox.config.json, examples/minimal/sandbox.config.json, examples/portfolio-svelte/sandbox.config.json, examples/portfolio/sandbox.config.json, examples/with-markdown-plugins/sandbox.config.json, examples/with-markdown/sandbox.config.json, examples/with-nanostores/sandbox.config.json, examples/with-tailwindcss/sandbox.config.json
- each "next" example on main now has a sandbox.config.json file which specifies to open port 3000 on start.
- Previously, the browser preview in CodeSandbox showed "Upgrade required" instead of the example's home page, and an offer to open port 3000 (which, if accepted would then create the expected browser preview, but could confuse someone who didn't know about this).
- Now, these examples do open on port 3000 and the example looks like it should in the browser preview upon start.
I tested a handful of these by using CodeSandbox's quick open URL shortcut githubBOX.com/sarah11918/astro/examples/blog etc. and making sure that when the CodeSandbox container started up, the correct main example page's index was loaded in the browser preview. 
No docs updated. CodeSandbox configuration …
=> Adding CodeSandbox config file to all the "next" examples

examples/portfolio-svelte/package.json, examples/portfolio-svelte/src/components/MainHead.astro
Comparing it to the react portfolio the url for the global.scss has changed in astro@next 
- This commit changes the URL for global.scss accordingly 
In combination with astro@next I had / have problems getting the styles working in this example.
Tried it on stackblitz without success. It seems like postcss or some scss compiler dep is missing.
Couldn't figure out the problem + asked on discord. At least I adjusted in a way as it is in the react portfolio example.
bug fix only
=> minor adjustments for astro@next

packages/astro/src/core/build/index.ts, packages/astro/src/core/dev/index.ts
Fixes #1755. In some instances, when users would pass in values to `vite` in `astro.config.mjs` they would override the defaults instead of deeply-merging.
This one is tricky! I wrote a test to try and catch this bug, but it is not in the PR because it was passing initially. But when testing locally I could easily replicate the bug.
Testing locally I could see a difference before and after this fix, but it’s difficult to capture accurately in a test (this might need a dev test which we don’t have at the moment).
No docs needed
=> fix: Improve Vite config merging

packages/astro/test/astro-client-only.test.js, packages/astro/test/astro-styles-ssr.test.js, packages/astro/test/fixtures/astro-client-only/src/components/PersistentCounter.svelte, packages/astro/test/fixtures/astro-client-only/src/components/logResize.js, packages/astro/test/markdown.test.js, packages/astro/test/react-component.test.js
Enables tests from previous compiler changes. This mostly uncomments tests except for: 
- the ongoing build work (blocking most tests still commented)
- `<!doctype>` insertion (do we want to add this?)
- https://github.com/snowpackjs/astro/pull/1771
- https://github.com/snowpackjs/astro/pull/1743
After the above, any remaining tests are very minor in scope. In fact many of them may be outdated and we should review the ones left to see if it’s still missing behavior or not.
No docs needed.
=> Enable tests

docs/src/components/HeadCommon.astro, www/src/components/BaseHead.astro
- Adds `<meta name="theme-color" content="#ff5e00"/>` to both `www` and `docs`
This both lets browsers reflect this color + provides Discord embeds a nice accent color
=> DOC 📘: Add `theme-color` meta tag to sites

.changeset/beige-kings-listen.md, .changeset/curvy-glasses-rest.md, .changeset/young-steaks-report.md, packages/astro/src/runtime/server/index.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/markdown/remark/src/index.ts, packages/markdown/remark/src/rehype-escape.ts
- @jonathantneal and I uncovered a handful of bugs while migrating the Docs site for #1738.
- This fixes them.
Manually. Before it did not work, now it does work.
Bug fixes
=> Markdown bug bash!

.changeset/dull-steaks-dance.md, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/vite-plugin-build-html/index.ts, packages/astro/test/astro-styles-ssr.test.js, packages/astro/test/fixtures/astro-styles-ssr/src/components/ReactDynamic.jsx, packages/astro/test/fixtures/astro-styles-ssr/src/pages/index.astro
- Adds `display: contents;` when using hydrated components, for the astro-root element, restoring what we did in 0.20.
Test added.
N/A
=> Add display: contents for hydrated components

docs/astro.config.mjs, docs/package.json, docs/snowpack.config.mjs, docs/src/components/HeadSEO.astro, docs/src/components/Header/Header.astro, docs/src/components/Header/Search.tsx, docs/src/components/PageContent/PageContent.astro, docs/src/components/RightSidebar/MoreMenu.astro, docs/src/components/RightSidebar/RightSidebar.astro, docs/src/layouts/MainLayout.astro, docs/src/pages/guides/deploy.md, docs/src/pages/themes.astro
This updates the Astro docs site to use Astro v0.21.
docs site only
docs site only
=> Update Astro docs to use v0.21

packages/astro/src/core/build/index.ts, packages/astro/src/core/ssr/index.ts, packages/astro/test/astro-doctype.test.js, packages/astro/test/fixtures/astro-doctype/src/layouts/WithDoctype.astro, packages/astro/test/fixtures/astro-doctype/src/layouts/WithoutDoctype.astro, packages/astro/test/fixtures/astro-doctype/src/pages/preserve.astro
Unskips our Doctype test by just lazily-injecting it on SSR. Restores/maintains current behavior from 0.20 and earlier
Tests uncommented
No docs needed.
=> Inject Doctype tag

docs/public/index.css, examples/blog/public/blog.css, examples/docs/public/index.css, www/src/scss/blog.scss
This adds `word-break: break-word;` to inline code css to allow long inline code blocks to wrap lines and not blow out of the container.  @jasikpark noticed the issue in a few recent blog posts, so it seemed worthwhile to add this to the themes/examples.
Before:
After:
I added a long code block, as seen in the screenshots above, and verified that my css change had the intended effect.
No doc changes needed, just a tweak to the default styles.
=> Allow inline code blocks to wrap lines

packages/astro/src/core/dev/index.ts, packages/astro/src/core/dev/template/error.ts, packages/astro/src/core/ssr/index.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/fixtures/wasm-panic-error/src/pages/index.astro, packages/astro/test/wasm-panic-error.test.js
If a user enters invalid syntax, e.g.:
```astro
{[].map(() => (<div>))}
```
They’ll get a compiler panic error:
**Before**
**After**
Clickable link! 🎉 
Issue link contains the breaking code (courtesy of @natemoo-re)
Also improves error display for some errors in component SSR:
Test added
No docs needed
=> Improve WASM panic error

.changeset/strong-bugs-confess.md, packages/astro/src/vite-plugin-astro/index.ts
- Fixes layouts being rendered as fragments on non-unix environments
Tested on Windows 10, using the [astro blog starter](https://github.com/snowpackjs/astro/tree/main/examples/blog)
No changes
=> Use normalized path to detect layout files

packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/test/astro-styles-ssr.test.js, yarn.lock
- Prevents duplicate CSS files from being created by disabling `renderChunk` in the `vite:css-post` plugin.
- Does minification ourselves, after creating the chunks.
Tests updated to reflect change in output.
N/A
=> Start of fixing multiple CSS issue

.changeset/twenty-rabbits-repeat.md, docs/src/pages/guides/styling.md, packages/astro/package.json, packages/astro/src/core/ssr/css.ts, packages/astro/src/core/util.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-astro/styles.ts, packages/astro/test/fixtures/postcss/postcss.config.cjs, packages/astro/test/fixtures/postcss/public/global.css, packages/astro/test/fixtures/postcss/src/components/Astro.astro, packages/astro/test/fixtures/postcss/src/components/Solid.css, packages/astro/test/fixtures/postcss/src/components/Solid.jsx, packages/astro/test/fixtures/postcss/src/components/Svelte.svelte, packages/astro/test/fixtures/postcss/src/components/Vue.vue, packages/astro/test/fixtures/postcss/src/pages/index.astro, packages/astro/test/fixtures/postcss/src/styles/linked.css, packages/astro/test/postcss.test.js, yarn.lock
In our compiler, we’d run Vite’s transform hook for `<style lang="*">`, and we’d skip it if there wasn’t that `lang=""` attribute. However, we need to always run styles through Vite, because otherwise things like Autoprefixer are ignored in certain contexts.
Tests added
Doc typo fixed.
=> Fix PostCSS (and Autoprefixer) processing

.changeset/real-cats-act.md, packages/create-astro/src/index.ts
- In the latest version of npm, the default behavior of `npm init` was changed  to no longer require `--` to pass args and instead pass `--` directly to us. 
- This broke our arg parser, since `--` is a special kind of flag. 
- Filtering for `--` here fixes the issue so that create-astro now works on all npm version.
Tested locally. No way to test for this in our current test suite since this part of the logic happens in setup.
N/A
=> fix npm init flag handling in create-astro

.changeset/beige-hairs-design.md, packages/astro/src/core/create-vite.ts, packages/astro/src/core/ssr/index.ts
- HMR was broken. Now it's not.
- The problem was that Vite was ignoring `astro/runtime/client/hmr.js` because we had set `ssr.noExternal: ['astro']`. The result was that `import.meta.hot` was always undefined. The fix was to inline the contents of `astro/runtime/client/hmr.js` directly rather than load them through `import 'astro/runtime/client/hmr.js'`.
Manually, we don't have dev server tests
Bug fix only
=> fix: HMR regression

www/src/components/MainHeader.astro
Overall, improve Astro's site header:
- Remove duplicate h1 tag (an h1 tag was in header _and_ main).
- Remove article tags from header.
- Improved accessibility for the SVG logo, per guidelines from [this CSS Tricks article.](https://css-tricks.com/accessible-svgs/#2-inline-svg)
- Restructure navigation links into an unordered list with list role, guidelines from [5t3ph's HTML Recipes](https://htmlrecipes.dev/#navigation-links).
- Add [Logo structured data](https://developers.google.com/search/docs/advanced/structured-data/logo) because...why not?
Ran `astro build` — no build errors 😁
None changed
=> fix: header logo/nav/svg

packages/astro/src/core/create-vite.ts, packages/astro/test/builtins.test.js, packages/astro/test/fixtures/builtins/src/components/Version.astro, packages/astro/test/fixtures/builtins/src/pages/bare.astro
- Enables `node:*` builtins.
- **TODO** disable unprefixed versions.
Tests re-enabled.
N/A
=> fix: enable node builtins

.changeset/heavy-boxes-deliver.md, packages/astro/src/core/dev/index.ts
- Vite middleware can tackle HMR webhooks and exact asset references before our router
- Vite assets are always more specific than our user routes, which means they should run first to prevent getting caught by a super flexible route like `/*`
- Fixes that issue where HMR events get reported as `/` routing errors in the console
- Covered by existing tests (actual behavior shouldn't have been impacted, but dev server should run faster and not log as many false errors)
- N/A
=> fix middleware order to prevent HMR issues

.changeset/serious-knives-hug.md, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/test/astro-styles-ssr.test.js
- Closes #1844
- Uses similar logic as the Vite CSS build plugin, which removes "pure css" code from imported JavaScript since we are including it as link tags.
- Also uses the Vue plugin's transform function so that it correctly scopes scoped CSS. We need to do this ourselves becuase our plugin is "pre" to avoid the Vite CSS build plugin from claiming CSS.
Tests unskipped.
N/A
=> Fix for built scoped Vue styles

packages/astro/src/runtime/server/index.ts
- Fixes regression where Astro stopped supporting non-object/non-function components, e.g. custom elements.
- Resolves https://github.com/snowpackjs/astro/issues/1853
- cannot confirm locally
- local tests are failing before making any change
bug fix only
=> Support custom elements

packages/astro/src/runtime/server/index.ts
- Code currently runs `child.toString()` an objects that might not have `toString`.
- Changes check from `child.toString() === '[object AstroComponent]'` to `Object.prototype.toString.call(child) === '[object AstroComponent]'`.
```astro
---
import * as ms from 'ms';
---
{ms}
```
That should throw an error like "Cannot convert object to primitive value" but the `toString` check might be throwing before we can get it.
This has not been tested.
bug fix only
=> Fix AstroComponent check

package.json, packages/astro/package.json, packages/astro/src/vite-plugin-build-html/extract-assets.ts, scripts/package.json, yarn.lock
- This syncs the project `yarn.lock` with the allowances in the `package.json` files.
- This locks `esbuild` to `0.13.7` to prevent unexpected changes to CSS files in newer `esbuild` versions.
- This locks `typescript` to `4.4.4` to prevent `build:all` from timing out without any message in `4.5.2`.
- This fixes a typing issue in `packages/astro/src/vite-plugin-build-html/extract-assets.ts` to prevent `build:all` from failing due to a typing error.
- Resolves https://github.com/snowpackjs/astro/issues/1885
```
yarn build:all
yarn test
```
bug fix only
=> Update yarn.lock to reflect the state of the package.json files

packages/astro/src/core/dev/index.ts, packages/astro/src/vite-plugin-astro/index.ts
- Fixes error where a hard refresh shows “Expected an exported Astro component but received typeof"
- Enables 500 page to self-recover
- Improves HMR reloading in all frameworks
- 
Tested manually. As this is HMR, we don’t have a way to test these yet
No docs needed
=> Improve HMR

packages/astro/test/debug-component.test.js, packages/astro/test/fixtures/debug-component/src/data/posts/my-first-post.md, packages/astro/test/fixtures/debug-component/src/pages/posts/[slug].astro, packages/astro/test/test-utils.js
- Makes Debug use the `Code` component so that JSON is properly serialized. Without this Vite's HTML parser blows up.
- Closes #1778
Added some `<Debug />` tests.
N/A, bug fix only.
=> Add Debug tests

.changeset/popular-plants-report.md, packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js
- 6b9ec716ee10f7351c521b4677d5daceef9a45a7 removed vite as a dependency but i guess we actually did depend on it. Fix is to make our vendored version use the local copies of the client modules.
Nope
N/A
=> Resolve vite client modules to vendored vite

packages/astro/src/runtime/server/index.ts, packages/create-astro/src/index.ts
- Astro adds newlines to resolved arrays (components rendered within `map()` for example)
- This space is not authored space, and causes issues within strictly formatted blocks (`<pre>`, `<textarea>`, `white-space: pre`, etc.).
- This removes the additional newlines.
Effects were observed when migrating https://astro.build/blog/introducing-astro/
bug fix only
=> Remove additional newlines added to HTML

.changeset/rare-cars-lick.md, packages/astro/src/runtime/server/index.ts, packages/astro/test/custom-elements.test.js
- Fixes Lit example in prod
- Makes these be normal scripts that are added to the head. This ensures they are picked up and built.
N/A
=> Add polyfill scripts to result.scripts

.changeset/friendly-dingos-lie.md, packages/astro/package.json
- `vite` needs to be a dependency since a few plugins, specifically svelte and vue, depend on it existing even though they do not depend on it themselves.
Locally in the example project
N/A
=> Add vite back as a dependency

packages/astro/test/config.test.js
- Test included `/Local:/.it(chunk)` and `/Server started/.it(chunk)`.
- RegExp#it is not a function.
- Test updated to `/Local:/.test(chunk)` and `/Server started/.test(chunk)`.
fixes test
test fix only
=> Fix RegExp#test in Config test

packages/astro/src/core/preview/index.ts
- small bug fix for the preview command which was hosting at ` Local: http://localhost:3000//` by default
=> fix the preview command base URL

.changeset/clever-cobras-notice.md, packages/astro/src/runtime/server/index.ts
- Components in Markdown did not play nicely with `fetchContent`.
- This is a non-breaking change that was discussed with @FredKSchott. It's a small API update that allows Markdown + Components files to be rendered.
Example usage:
```astro
---
export function getStaticPaths() {
const posts = Astro.fetchContent('../../data/blog-posts/*.md');
return posts.map(p => ({
params: { slug: p.file.pathname.split('/').pop().split('.').shift() },
props: { post: p },
}));
}
const { Content } = Astro.props.post;
---
<html lang={ lang ?? 'en' }>
<head>
<link rel="stylesheet" href={Astro.resolve('../../scss/blog.scss')} />
</head>
<body>
<Content />
</body>
</html>
```
Manually
No docs atm
=> feat: expose `<Content />` component to `Astro.fetchContent`

docs/src/pages/core-concepts/routing.md, docs/src/pages/es/core-concepts/routing.md, docs/src/pages/es/guides/imports.md, docs/src/pages/es/reference/api-reference.md, docs/src/pages/guides/imports.md, docs/src/pages/guides/markdown-content.md, docs/src/pages/guides/pagination.md, docs/src/pages/guides/styling.md, docs/src/pages/migration/0.21.0.md, docs/src/pages/reference/api-reference.md, examples/docs/README.md, packages/renderers/renderer-lit/readme.md
- Fixes `jsx` code blocks that should have been `astro`.
- Fixes a few `md` code blocks that should have been `markdown`.
- Adds a note about JSX in Frontmatter to the Migration Guide.
doc fix only
doc fix only
=> Doc improvements

docs/src/pages/core-concepts/routing.md, docs/src/pages/es/core-concepts/routing.md, docs/src/pages/es/guides/deploy.md, docs/src/pages/es/guides/imports.md, docs/src/pages/es/reference/api-reference.md, docs/src/pages/guides/aliases.md, docs/src/pages/guides/deploy.md, docs/src/pages/guides/imports.md, docs/src/pages/guides/markdown-content.md, docs/src/pages/guides/pagination.md, docs/src/pages/guides/styling.md, docs/src/pages/migration/0.21.0.md, docs/src/pages/reference/api-reference.md, examples/docs/README.md, packages/renderers/renderer-lit/readme.md
- Cleanup `astro` code block examples
- Fix bad markup in `astro` code block examples
doc fix only
doc fix only
=> Docs codeblock fixes

packages/astro/src/core/ssr/index.ts
For some reason, Svelte returns JS for `.svelte?svelte&type=style&lang.css` but only in dev 🤷🏻. This is a quick fix for dev.
No test
No docs
=> Fix Svelte and Vue styles in dev

docs/src/pages/migration/0.21.0.md
- What does this change? The 0.21 migration guide
This is an attempt to make it clear that the provided arg to `define:vars` must be an object, and that the values must be serializable.
Docs only
Yes, the is docs only
=> Clarify rules of define:vars

docs/src/pages/migration/0.21.0.md
Added some proposed changes to help others migrate their Astro projects built with Tailwind CSS, over to the new version (0.21.0).
- Updated documentation to help others migrate to the new version.
- To validate this change, you can migrate from a 0.20 Astro project using Tailwind CSS and install the latest version of Astro (0.21.0). You will notice Tailwind CSS stopped working if you didn't have postcss installed. Installing postcss solves this issue.
- Updated the docs to include some steps I had to do in order to get it to work
=> Add migration guide for Tailwind CSS

docs/src/pages/core-concepts/astro-components.md
Updating the Astro component docs with details on how `export interface Props` is now automatically detected.  Also added a couple notes to make it more clear that `import`/`export` statements should always be at the top of an Astro component
None (docs change only)
Updating the Astro Component docs.  I could only do the English translation, would love to see the `es` translation updated as well!
=> Updating docs for automatic detection of `export interface Props`

docs/src/pages/getting-started.md, examples/with-nanostores/package.json, examples/with-nanostores/src/components/AdminsPreact.jsx, examples/with-nanostores/src/components/AdminsReact.jsx, examples/with-nanostores/src/components/AdminsSvelte.svelte, examples/with-nanostores/src/components/AdminsVue.vue, examples/with-nanostores/src/store/admins.js, examples/with-nanostores/src/store/counter.js, examples/with-nanostores/src/store/users.js
- Change example with-nanostores to use new nanostore version (`^0.5.6`)
- Change example code with-nanostores to use non deprecated function
- Manual run by running the example (npm install, npm run dev)
- Last example using deprecated functions on nanostores (getValue, createStore), which has been changed on nanostores documentation to atom, atom.get()
=> Patch: Example Nanostores Update

.changeset/six-rockets-jump.md, packages/astro/src/core/ssr/css.ts
- We had a bug in `crawlCSS` that would create infinite loops
- The entry module was never marked as scanned, only the packages which it imported.
- This fix preemptively marks the entry module as scanned so that it does not recurse into itself.
Tested manually. Can use the following as a test case, as well. https://stackblitz.com/edit/github-b1hhg9?file=src%2Flayouts%2Fpage.astro
Bug fix only
=> fix: avoid infinite loops in `crawlCSS`

.changeset/slimy-turtles-boil.md, packages/astro/src/runtime/server/index.ts
- Closes https://github.com/snowpackjs/astro/issues/1958
- I introduced a regression with `client:only` behavior in 0.21.
- When a user only has a single renderer and is using `client:only`, we now default to that renderer.
Manually
Bug fix only
=> fix: `client:only` behavior with a single renderer

docs/src/pages/reference/configuration-reference.md
- fix broken link in configuration-reference.md  
(#1960)
No tests. Just update the documentation.
This updates `/docs/src/pages/reference/configuration-reference.md`
=> docs: update link to AstroUserConfig type definitions

.changeset/big-mangos-bow.md, packages/astro/src/core/ssr/css.ts
- Supports `lang="postcss"` in addition to `lang="pcss"`
- The [PostCSS Language Support](https://marketplace.visualstudio.com/items?itemName=csstools.postcss) extension supports `.postcss` files. We should as well.
- Vite supports the following style extensions: [`css|less|sass|scss|styl|stylus|pcss|postcss`](https://github.com/vitejs/vite/blob/5987a77dce6c2e078a4b929be7165b90faf96f8c/packages/vite/src/node/plugins/css.ts#L85)
- Closes https://github.com/snowpackjs/astro/issues/1947
TBD, we don't have any style preprocessor tests
Bug fix only
=> Support `lang="postcss"`

.changeset/twenty-hounds-approve.md, examples/minimal/src/pages/404.astro, packages/astro/src/vite-plugin-build-html/index.ts
- Closes https://github.com/snowpackjs/astro/issues/1944
- There was a regression in v0.21 where `404.astro` would be built to `404/index.html`. This causes issues with most hosts.
- This PR updates `astro build` to directly output `STATUS_CODE.html`, where `STATUS_CODE` is any 3 digit sequence.
Tested manually. Will add a test to catch future regressions.
N/A, bug fix
=> fix: output `404.astro` to `404.html`

packages/astro/src/cli/index.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/dev/index.ts, packages/astro/src/core/ssr/routing.ts, packages/astro/test/config.test.js
- Before: When the pages directory does not exist, Astro throws an internal error that is less helpful to users.
- After: When the pages directory does not exist, Astro warns users that no pages directory exists.
- Resolves https://github.com/snowpackjs/astro/issues/1889
**Example**
```log
astro dev
08:00 AM [astro] Missing pages directory: src/pages/
08:00 AM [astro] Server started                               297ms
08:00 AM [astro] Local: http://localhost:3000/
```
no tests added
bug fix only
=> Warn on missing pages directory

examples/framework-multiple/src/components/PreactCounter.tsx, examples/framework-multiple/src/components/ReactCounter.jsx, examples/framework-multiple/src/components/SolidCounter.tsx, examples/framework-multiple/src/components/SvelteCounter.svelte, examples/framework-multiple/src/components/VueCounter.vue, examples/framework-multiple/src/pages/index.astro, examples/framework-multiple/src/styles/global.css, examples/framework-preact/src/components/Counter.css, examples/framework-preact/src/components/Counter.tsx, examples/framework-preact/src/pages/index.astro, examples/framework-react/src/components/Counter.css, examples/framework-react/src/components/Counter.jsx, examples/framework-react/src/pages/index.astro, examples/framework-solid/src/components/Counter.css, examples/framework-solid/src/components/Counter.jsx, examples/framework-solid/src/pages/index.astro, examples/framework-svelte/src/components/Counter.svelte, examples/framework-svelte/src/pages/index.astro, examples/framework-vue/src/components/Counter.vue, examples/framework-vue/src/pages/index.astro
Examples are how we teach people to use Astro! But some of our examples’ styling doesn’t follow our own [recommended best practices](https://docs.astro.build/guides/styling/).
Without affecting the look of the examples at all, the following changes were made:
1. Removed usage of `:global()` when it wasn’t necessary
2. But kept global CSS in all cases (simply moved the styles to be more manageable)
2. Moved styling into components, which encourages good style scoping and improves CSS tree-shaking 
3. Simplified some CSS, such as removing CSS grid when it wasn’t needed
4. When styles are shared between components, use a global `<link>` tag rather than page styles (which would easily break for users as they added pages)
The overall goal was to **keep styling simple** (it’s an example) while …
=> Clean up styling for framework-* examples

.changeset/gentle-donkeys-rule.md, packages/astro/test/fixtures/lit-element/src/components/my-element.js, packages/astro/test/fixtures/lit-element/src/pages/index.astro, packages/astro/test/lit-element.test.js, packages/renderers/renderer-lit/server.js
This change sets properties on lit-elements rather than just attributes if the bound item is detected to be a reactive property.
Added tests to test:
- standard string property
- boolean property
- `bool="false"` will equate to `true` as Lit uses `hasAttribute`
- object property
- `obj={{data: true}}` as an attribute will be stringified to `[object Object]` which Lit will interpret as `null`
- check that none of those properties are rendered as attributes
**NOTE TO REVIEWERS:** I had to check the inner html of these components because checking `$(tagname).prop(propName)` would equate to `undefined` in the testing environment. Also, checking html where there is a lit binding will output `...` which may cause a brittle test if the lit-part name is changed upstream. Am welcome to any other …
=> fix(lit-renderer): certain reactive props not init correctly

.changeset/tiny-buckets-mix.md, packages/astro/package.json, packages/astro/src/vite-plugin-build-html/extract-assets.ts, packages/astro/src/vite-plugin-build-html/index.ts, packages/astro/src/vite-plugin-build-html/util.ts, packages/astro/test/astro-scripts.test.js, packages/astro/test/fixtures/astro-scripts/src/components/NoHoistClassic.astro, packages/astro/test/fixtures/astro-scripts/src/components/NoHoistModule.astro, packages/astro/test/fixtures/astro-scripts/src/pages/external-no-hoist-classic.astro, packages/astro/test/fixtures/astro-scripts/src/pages/external-no-hoist.astro, packages/astro/test/fixtures/astro-scripts/src/scripts/no_hoist_module.js, packages/astro/test/fixtures/astro-scripts/src/scripts/no_hoist_nonmodule.js
- Scripts inside of src/, whether hoisted are not should be built.
- If not hoisted they do *not* get bundled together
- They are their own standalone scripts.
- This matches 0.20 behavior.
- Closes #1968
Tests added
=> Bring back building of non-hoisted scripts

docs/src/pages/guides/styling.md
- Corrects the documented `postcss.config.cjs` for setting up Tailwind
- The previously documented config leaves `@tailwind` directives unchanged
- See [Tailwind PostCSS plugin docs](https://tailwindcss.com/docs/installation#add-tailwind-as-a-post-css-plugin) and the Astro `with-tailwind` [example config](https://github.com/snowpackjs/astro/blob/fff00e45f00f8534ec5fe66302d8c44639b34499/examples/with-tailwindcss/postcss.config.js)
- No tests added since this only affects docs
- Updates the "Styling" docs
=> Update Tailwind PostCSS sample config in docs

.changeset/unlucky-days-rescue.md, packages/create-astro/src/index.ts
- Add a helpful message for the "could not find commit hash for ..." error. This error mostly shows when someone tries to initialize a new project but git is not installed on their system.
=> create-astro: Add a helpful message for the "could not find commit hash for ..." error

.changeset/rare-bulldogs-tie.md, packages/astro/test/0-css.test.js, packages/astro/test/fixtures/0-css/src/pages/index.astro, packages/astro/test/fixtures/svelte-component/src/components/TypeScript.svelte, packages/astro/test/fixtures/svelte-component/src/pages/typescript.astro, packages/astro/test/svelte-component.test.js, packages/renderers/renderer-svelte/index.js, packages/renderers/renderer-svelte/package.json, yarn.lock
Fixes:
- https://github.com/snowpackjs/astro/issues/1981
- https://github.com/snowpackjs/astro/issues/1976
Tests added
🤔 Is there a good docs add here? We should probably mention `svelte.config.js` somewhere but unsure where.
=> Add default TypeScript, Sass support to Svelte

packages/astro/package.json, packages/renderers/renderer-lit/package.json, packages/renderers/renderer-preact/package.json, packages/renderers/renderer-react/package.json, packages/renderers/renderer-solid/package.json, packages/renderers/renderer-svelte/package.json, packages/renderers/renderer-vue/package.json
Fixes this: 🙈
(doesn’t interfere with #1994)
Also adds repository info for renderers
No testing
No docs
=> Add package descriptions

.changeset/famous-mice-sparkle.md, docs/src/components/RightSidebar/ThemeToggleButton.tsx, packages/astro/src/runtime/client/visible.ts
Fixes #1963. Our `client:visible` intersection observer would observe all our components, but when it came to multiple instances of the same component would only listen for the first instance. This caused a problem in our docs when we have 2 components on the page and the first is hidden, but the second isn’t. The first would get evaluated, IntersectionObserver would correctly determine it wasn’t in view, then it would exit rather than see if another instance of that component was visible.
Tested manually in dev & build. Testable here:
👀 https://deploy-preview-1999--astro-docs-2.netlify.app/getting-started/
No docs needed
=> Fix client:visible for duplicate component instances

docs/src/pages/migration/0.21.0.md
- fixed alias path on the v0.21 migration guide
Tested on [stackblitz](https://stackblitz.com/edit/github-kfnit2?devtoolsheight=33&file=tsconfig.json)
Migration guide on the docs is updated.
=> fixed alias path on migration guide.

.changeset/wise-months-serve.md, packages/astro/src/core/build/index.ts, packages/astro/test/astro-envs.test.js, packages/astro/test/fixtures/astro-envs/src/components/Client.vue, packages/astro/test/fixtures/astro-envs/src/pages/index.astro, packages/astro/test/test-utils.js
- Fixes #2027
- All we needed was to provide `PUBLIC_` in the build.
- Fixes client-side JS that uses these environment variables.
Test added
Bug fix only
=> Use of PUBLIC_ environment variables

.changeset/little-carrots-sleep.md, packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js
- Fixes #2004 
- Upstream fix: https://github.com/vitejs/vite/pull/5891
- What was happening was that our astroid is the hash of the HTML produced by a component. If that HTML ever changes the astroid changes. However since Vite's dev HTML plugin turns the inline scripts into external scripts and caches them, the changed astroid was never reflected in the proxy modules.
- Fix is to invalidate the module when the script changes; a bug in Vite. There is an upstream fix listed above.
No, we don't have dev tests that change the value of a module, which would be needed to test this.
Bug fix only
=> Fix cached inline modules

.changeset/tame-hats-give.md, packages/astro/src/core/ssr/routing.ts, packages/astro/test/route-manifest.test.js
Fix #2033
* Prevent a crash with unhandled file types in `src/pages`
* Skip files in `src/pages` when extension is not '.astro' or '.md'
Added a new test case to `packages/astro/test/route-manifest.test.js`. 
No, bug fix only.
=> fix(astro): prevent crash on unexpected file in pages

examples/starter/src/pages/index.astro
I can't find the section in the documentation anymore about resolving SCSS-files (maybe it's gone since v0.21) but the Starter Example doesn't load the SCSS/CSS file anymore.
- Change: `{Astro.resolve('../styles/XXX.scss')}` → `{Astro.resolve('../styles/XXX.css')}`
Didn't add any tests, not sure if there should be for this.
Don't think this requires documentation – except for the section that I think existed at some point, but is now gone? 🤷
=> Fix resolve of scss/css-file in Starter Example

docs/src/components/Header/LanguageSelect.tsx
Italian language in docs selector
Build with no errors. Italian language shown as last item of the list.
This is docs page update
=> Add italian to language selector

docs/reference/api-reference.md, docs/src/pages/core-concepts/routing.md, docs/src/pages/guides/imports.md, docs/src/pages/reference/api-reference.md
Vite has replaced Snowpack in 0.21.
* change Snowpack references in English docs to Vite
* change https://snowpack.dev links to https://vitejs.dev
* update a reference to the Astro GitHub organisation 
* I did not update the alias docs because I am not sure how it works :-), but they also are out of date
Re-reading attentively. Docs-only changes.
Yes, the PR only contains documentation updates.
=> docs: update some Snowpack references to Vite

.changeset/honest-knives-bake.md, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/fixtures/sass/src/pages/error.astro, packages/astro/test/sass.test.js
Partially addresses #2032. When Sass encounters a compile error, we don’t properly stop WASM from trying to process the broken CSS, resulting in the error never being shown.
**Before**
😵 (no screenshot; it just crashes)
**After**
Helpful error shown
Test added
No docs needed
=> Fix Sass WASM crashes

docs/src/pages/guides/markdown-content.md
The `parser` key isn't valid, `render` needs to be used instead so just updating the docs to save anyone else a headache.
Updates the `/guides/markdown-content/` page to replace instances of  `parser` with `render` as the `markdownOptions` object does not work if you use `parser`.
Checked rendered markdown in github looks okay.
Yes
=> Rename the `markdownOptions` "parser" property to "render"

packages/astro/src/core/dev/index.ts, packages/astro/src/core/ssr/css.ts, packages/astro/src/core/ssr/index.ts, packages/astro/src/core/util.ts, packages/astro/test/fixtures/solid-component/src/pages/index.astro, packages/astro/test/fixtures/svelte-component/src/pages/typescript.astro, packages/astro/test/react-component.test.js, packages/astro/test/solid-component.test.js, packages/astro/test/svelte-component.test.js, packages/astro/test/vue-component.test.js
Fixes #2053. In dev, Windows was getting bad URLs for script proxying. This behavior only existed in dev, not build, so dev tests needed to be added that we didn’t have before.
Tests added that didn’t exist before.
No docs changes.
=> Fix Windows dev script proxying

.changeset/ten-clocks-remember.md
The build cache for CI seems to be bad on Mac. Opening up an arbitrary PR change to try and force a rebuild.
Edit: it worked!
=> Modify changeset for #2052

.changeset/bright-ravens-remain.md, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/src/vite-plugin-build-html/index.ts, packages/astro/test/astro-css-bundling-import.test.js, packages/astro/test/fixtures/astro-css-bundling-import/src/layouts/BaseLayout.astro, packages/astro/test/fixtures/astro-css-bundling-import/src/layouts/PageLayout.astro, packages/astro/test/fixtures/astro-css-bundling-import/src/pages/page-1.astro, packages/astro/test/fixtures/astro-css-bundling-import/src/pages/page-2.astro, packages/astro/test/fixtures/astro-css-bundling-import/src/styles/page-one.css, packages/astro/test/fixtures/astro-css-bundling-import/src/styles/page-two.css, packages/astro/test/fixtures/astro-css-bundling-import/src/styles/site.css
Partially fixes #2060 (there’s a remaining problem where sometimes empty `.css` files are generated, which can be tackled in a followup if this works well).
This is a tricky issue! The basic idea is that build rearranges styles from dev. While there’s no perfect fix here, this at least takes a step in the direction of fewer surprises on deploy.
Essentially, dev collects styles in a reasonable order that the user may expect. Up until the very last bit, where styles are put into a map and pulled back out in a different order. This PR only changes that part.
Test added
No docs needed
=> Enforce consistent import order of CSS

docs/src/pages/migration/0.21.0.md
I found that the configuration changed a little for `markdownOptions` in 0.21, so here's a short guide to hopefully help others realize it changed as well.
Docs only
Docs only
=> Add migration guide for markdownOptions

packages/astro/src/core/config.ts, packages/astro/test/config-validate.test.js
Closes #2072 
Added test to `config-validate.test.js`.
No, although I do have https://github.com/withastro/astro/pull/2070 open to change the migration guide docs.
=> Prevent unknown keys in markdownOptions

.changeset/wise-icons-tell.md, packages/astro/src/core/ssr/index.ts, packages/astro/test/astro-markdown-plugins.test.js
Fixes #2061. [Our own docs](https://docs.astro.build/guides/markdown-content/#add-a-markdown-plugin-in-astro) say that `import()`-ing a plugin works, so this adds a fix + test for that.
Test added
Bug fix
=> Allow importing of rehype plugins

.changeset/rare-jars-dance.md, packages/astro/src/runtime/server/index.ts, packages/astro/test/astro-basic.test.js, packages/astro/test/fixtures/astro-basic/src/components/Input.astro, packages/astro/test/fixtures/astro-basic/src/pages/input.astro
- Fixes an issue where void elements are rendered with opening and closing tags.
- Resolves https://github.com/withastro/astro/issues/2062
no tests added
bug fix only
=> Render void elements as self-closing tags

.github/workflows/ci.yml
- Add support for a lower-powered lint CI command that can run on external PRs
Works on internal PRs: 
@jonathantneal might need you to test on your fork to confirm!
=> Add external PR lint support

.changeset/dull-parents-speak.md, packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js
Note that this is the compiled output of Vite's build. See https://github.com/vitejs/vite/pull/5891 for the real changes.
- Updates code based on Vite PR review.
- Removes unused `invalidateId` method.
- Fixes #2004
Not really possible.
Bug fix only
=> Invalidate based on modulePath

.changeset/gorgeous-clocks-leave.md, packages/astro/src/runtime/server/index.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-build-html/index.ts, packages/astro/src/vite-plugin-markdown/index.ts
- Instead of returning a pathname that is the full filesystem URL this will not return `/src/images/penguin.png`, projectRoot relative.
- Depends on https://github.com/withastro/astro-compiler/pull/179
- Closes https://github.com/withastro/astro/issues/2002
- Closes https://github.com/withastro/astro/issues/1968
- Closes https://github.com/withastro/astro/issues/2068
No tests needed to be updated, but some code needed to be updated to make them all pass.
Bug fix.
=> Makes Astro.resolve return root-relative paths

.changeset/clever-suits-hide.md, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/src/vite-plugin-build-html/index.ts, packages/astro/test/astro-css-bundling-import.test.js
Fixes #2060 (hopefully for real)
A previous cut of this PR accidentally assumed that a certain asset map was in order when it wasn’t. The reality is that Rollup chunks are all processed in parallel, and they can be encountered in any order.
So this PR relies on HTML ordering to determine stylesheet ordering. Tests were added to make sure it works as intended.
Also, it prevents empty CSS from being generated (which is somewhat of an edge case and not super common, but can be frustrating when it does happen)
Tests added
🐛 Bugfix
=> Improve CSS import ordering, fix empty CSS outputs

.changeset/proud-yaks-smile.md, packages/astro/src/core/util.ts, packages/astro/test/astro-basic.test.js, packages/astro/test/fixtures/astro-basic/src/pages/special-“characters” -in-file.md
Fixes #2089. Files with special characters won’t build
Adds test
Bugfix
=> Allow special characters in filenames

docs/src/config.ts, docs/src/pages/zh-TW/themes.astro
Themes page in zh-TW
There should be a `佈景主題` link at left side bar.
This is a doc update.
=> Docs: Add Themes page in Zh-TW

.github/workflows/ci.yml, .github/workflows/main.yml, scripts/notify/index.js
- Removes manual `[skip-ci]` checks since [GitHub handles them automatically](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/).
- Removes `[ci]` from automated commit messages since that apparently skips actions
This is it!
QoL Improvement
=> Cleanup Actions

.changeset/cold-teachers-deny.md, packages/astro/package.json, yarn.lock
- Updates `@astro/compiler` and `@astro/language-server`.
- Fixes a regression that broke `XElement`. https://github.com/withastro/compiler/pull/200
- Fixes an issue with `<>` fragments. https://github.com/withastro/compiler/pull/201
dependency update only
dependency update only
=> Update Astro dependencies

.changeset/empty-oranges-provide.md, packages/astro/src/runtime/server/index.ts
- Fixes #2102
- We can't use this module due to Vite not having a shim and this needing to run inside Vite.
- This is not needed anyways because the compiler always passes through `projectRootStr` anyways.
Bug only occurs externally
Bug fix
=> Remove use of URL module in runtime

.changeset/spicy-bats-search.md, packages/create-astro/src/index.ts
Fixes #2045. Make sure the `--renderers` flag is parsed correctly as an array when passed.
I tested it manually since I tried running `yarn test:templates` locally but it fails even without any changes. I saw the `create-astro` package tests are not being run as part of CI, is that because they are broken or slow? 🤷🏻  
If I'm missing something, I'd be happy to amend the tests for it. We just need to pass the renderers for templates with `renderers: true` and it should succeed.
Bug fix only
=> Parse --renderers flag correctly when passed to the create-astro cli

.changeset/weak-planets-think.md, packages/astro/test/fixtures/lit-element/src/components/my-element.js, packages/astro/test/fixtures/lit-element/src/pages/index.astro, packages/astro/test/lit-element.test.js
- Adds lit-renderer reflection tests
This is only tests following up on #1874 
tests only
Also please lmk if this is even supposed to be a patch or whether to just remove the changeset
=> test(lit): add reflected property tests

.changeset/wet-insects-dance.md, packages/astro/package.json, packages/astro/src/vite-plugin-fetch/index.ts, packages/astro/test/fetch.test.js, packages/astro/test/fixtures/fetch/src/components/AlreadyImported.astro, packages/astro/test/fixtures/fetch/src/components/CustomDeclaration.astro, packages/astro/test/fixtures/fetch/src/pages/index.astro, yarn.lock
- Previously, `vite-plugin-fetch` would clobber existing code and _always_ inject a `fetch` import. This would cause `fetch is already declared!` errors.
- Now, we do a quick AST walk to ensure that `fetch` has not already been declared before injecting `fetch`.
- Our migration guide even mentions that you _must remove_ existing `fetch` imports. Now it's optional.
Tests added for:
- Existing `fetch` import
- Custom `fetch` variable that could point to something else
Bug fix only
=> Make `fetch` injection safe to existing code

packages/astro/test/sass.test.js
We have been plagued by 🔴 for too long! This PR skips the failing Sass test on macOS only.
This is it, the tests!
QoL improvement only
=> Skip flaky macOS Sass test

.changeset/angry-pillows-accept.md, packages/astro/src/core/ssr/sitemap.ts, packages/astro/test/astro-sitemap-rss.test.js
- Excludes 404 page from `astro build` sitemap generation.
- Closes #2129 
Test was wrong, updated the test to reflect proper output
Bug fix only
=> fix(#2129): exclude 404 from sitemap

.changeset/popular-roses-ring.md, docs/src/config.ts, docs/src/pages/es/guides/markdown-content.astro, docs/src/pages/es/guides/pagination.astro, docs/src/pages/es/guides/publish-to-npm.astro, docs/src/pages/es/guides/styling.astro, docs/src/pages/es/reference/renderer-reference.astro, docs/src/pages/zh-TW/themes.astro, netlify.toml, packages/astro/src/core/ssr/css.ts, packages/astro/src/core/ssr/index.ts, packages/astro/src/core/util.ts
Fixes #2101
The issue is that looking up modules through Vite’s moduleGraph requires a specific ID lookup to pull up dependencies. In resolving other moduleGraph issues on Windows it seems we’ve had a regression with styles.
**Before**
**After**
This is very hard to write a test for! This is very Vite implementation-specific and so even if a test was written, it might be a false positive if Vite’s internals ever changed. No tests were added, unfortunately.
But testing has been done manually on the docs: https://deploy-preview-2112--astro-docs-2.netlify.app/ (make sure **every page has header styles**)
Bugfix only.
=> Fix build missing styles (affecting docs)

.changeset/dirty-guests-wash.md, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/errors.test.js, packages/astro/test/fixtures/errors/src/pages/astro-frontmatter-syntax-error.astro
- Before passing a component to the compiler, use esbuild to validate the frontmatter against JS/TS syntax.
- This will prevent a class of bug where bad front-matter syntax can break the compiled output in very obscure ways (for example, an unclosed parenthesis).
- Once the compiler can handle this better, we can remove this.
```
---
import Layout from '../layouts/MainLayout.astro';
{
--- 
```
Unclear error output.
Clear error output, with the correct bug location. "end of file" is still a little odd wording (it should say "end of frontmatter", which we can fix by re-writing this error message if that makes sense) but this is already a nice improvement over broken output, compiler panics, etc.
- Still TODO
- Not needed
=> Validate Astro frontmatter JS/TS on compiler error

.changeset/purple-paws-shave.md, packages/create-astro/package.json
- Fixes a bad path in the package.json exports map
Tested by CI releasebot failure: https://github.com/withastro/astro/runs/4437407032?check_suite_focus=true
N/A
=> fix create-astro export map entry

.changeset/ninety-actors-try.md, packages/astro/src/core/ssr/css.ts, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/test/astro-css-bundling-import.test.js, packages/astro/test/astro-css-bundling-nested-layouts.test.js, packages/astro/test/fixtures/astro-css-bundling-nested-layouts/src/layouts/BaseLayout.astro, packages/astro/test/fixtures/astro-css-bundling-nested-layouts/src/layouts/PageLayout.astro, packages/astro/test/fixtures/astro-css-bundling-nested-layouts/src/pages/page-1.astro, packages/astro/test/fixtures/astro-css-bundling-nested-layouts/src/pages/page-2.astro, packages/astro/test/fixtures/astro-css-bundling-nested-layouts/src/styles/page-one.css, packages/astro/test/fixtures/astro-css-bundling-nested-layouts/src/styles/page-two.css, packages/astro/test/fixtures/astro-css-bundling-nested-layouts/src/styles/site.css
Fixes #2101. For some reason when we try to skip empty CSS files, we also skip necessary CSS files (this is probably due to a deeper issue with the translation from JS imports into CSS, and dumping things too early). This PR makes a tradeoff: it regresses emitting empty CSS files, but it fixes necessary CSS files sometimes missing.
Tests added
Bugfix
=> Fix missing styles

.changeset/curvy-crabs-pay.md, packages/renderers/renderer-preact/package.json, yarn.lock
- Fixes #2169
- Something in preact v10.6 caused a regression in Astro that currently impacts [`astrojs/renderer-preact@0.3.1`](https://unpkg.com/@astrojs/renderer-preact@0.3.1/package.json) (cc @JoviDeCroock may need your help debugging this one!)
- This pins us to 10.5 for now until we can resolve
- Good reminder that we should be building all examples as a part of our current smoke test
- other idea: a nightly task that updates our yarn lockfile, and PRs if tests break.
- N/A
=> pin preact to 10.5 to resolve preact issue

packages/astro-parser/package.json, packages/astro-prism/package.json, packages/astro/package.json, packages/create-astro/package.json, packages/markdown/remark/package.json, packages/renderers/renderer-lit/package.json, packages/renderers/renderer-preact/package.json, packages/renderers/renderer-react/package.json, packages/renderers/renderer-solid/package.json, packages/renderers/renderer-svelte/package.json, packages/renderers/renderer-vue/package.json
- add MIT license to package.json which were missing it
- adds info on published npm: https://www.npmjs.com/package/@astrojs/markdown-remark (currently: none)
- automated license checking tooling will complain
not covered
self documented
=> Add missing licenses to published packages

docs/package.json, examples/docs/package.json, package.json, packages/markdown/remark/src/rehype-islands.ts, packages/markdown/remark/src/remark-unwrap.ts, yarn.lock
- Updates `typescript` to 4.5.2.
- Adds typing workaround to `@astrojs/markdown-remark`.
all tests are run
dependency update only
=> Update dependencies (typescript)

docs/src/pages/guides/rss.md
Updated RSS related code-snippet in documentation
In its current state the documentation code snippet includes a gremlin-apostrophe character which is patched by this PR.
Updated quote symbol in code-snippet RSS
=> Replace invalid quote character with standard

.changeset/clever-years-appear.md, docs/src/config.ts, docs/src/pages/de/guides/styling.md, docs/src/pages/guides/aliases.md, packages/astro/package.json, packages/astro/src/core/build/index.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/core/dev/index.ts, yarn.lock
- Removes `vite-plugin-fetch` plugin, where files are parsed and `fetch` is replaced when detected.
- Adds `node-fetch` polyfill to `globalThis` using `@astropub/webapi`.
Currently, the `vite-plugin-fetch` plugin scans files to replace `fetch`. Unfortunately, this plugin can _also_ pick up code that is intended for the client, or code that is used for both the server and the client. Furthermore, the plugin fails to correct checks for `fetch` (e.g. `typeof fetch`). In effect, Astro must scan every file to replace `fetch` with something like `__import_vite_etc_etc`, it will still break if `fetch` is checked, and authors encountering this issue must scan every function to replace `__import_vite_etc_etc` with `fetch` again.
By switching to a polyfill, the code can run on the server and the …
=> Replace `fetch` walk-n-replace with polyfill

.changeset/shiny-dodos-relax.md, docs/src/pages/guides/styling.md, yarn.lock
- Closes https://github.com/withastro/astro/issues/2213
- Releases `@astrojs/renderer-svelte` with the Vite plugin pinned to exactly `1.0.0-next.30`.
Tested locally.
N/A
=> chore: release pinned version of Svelte renderer

packages/astro/package.json, packages/astro/src/core/build/index.ts, packages/astro/src/core/dev/index.ts, yarn.lock
- Update `@astropub/webapi` from v0.4.0 to v0.6.0
- Exclude polyfills for `window` and `document`
dependency bump only
dependency bump only
=> Bump `@astropub/webapi`

docs/src/pages/core-concepts/component-hydration.md
This improves the wording in the documentation for `client:*` directives.
No tests, just documentation
Yes
=> Improve wording in documentation for `client:*` directives

docs/src/pages/reference/configuration-reference.md
- This updates the configuration reference documentation to be much more useful to users who either cannot or do not wish to analyze our typescript definitions file.
[Preview](https://deploy-preview-2239--astro-docs-2.netlify.app/reference/configuration-reference/)
doc fix only
doc fix only
=> Update Configuration Reference documentation

packages/astro/package.json, yarn.lock
- Updates `@astropub/webapi` to v0.7.1
- Supports `fetch` with `file:*`
dependency bump only
dependency bump only
=> bump webapi

packages/astro/src/cli/index.ts, packages/astro/src/core/dev/index.ts, packages/astro/src/core/preview/index.ts, packages/astro/test/cli.test.js, packages/astro/test/config.test.js, packages/astro/test/fixtures/config-path/config/my-config.mjs, packages/astro/test/test-utils.js
- Fix issue with `astro --version` throwing instead of returning the current version of Astro.
- Resolves https://github.com/withastro/astro/issues/2143
- Print `astro`, `astro --help`, `astro --version` before loading any configuration 
- Speeds up those commands which do not require configuration.
- Adds CLI tests
- Improves CLI testing in the Config tests by ensuring the process has ended.
- adds cli tests
- updates config tests
bug fix only
=> Improve CLI & CLI Testing

.changeset/calm-crabs-rush.md, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/src/vite-plugin-build-html/index.ts, packages/astro/test/fixtures/remote-css/src/components/CommonHead.astro, packages/astro/test/fixtures/remote-css/src/pages/index.astro, packages/astro/test/remote-css.test.js
- Previously remote `@import` would be stripped from CSS because we were concatenating all CSS together and treating that as 1 module.
- This fixes it by treating each `<style>` on a page as a separate CSS module. Rollup correctly bundles these together, preserving the remote `@import` usage.
Test added
Bug fix only.
=> Fixes includes remote @imports in inline styles

packages/astro/CHANGELOG.md, packages/astro/test/builtins.test.js, packages/markdown/remark/CHANGELOG.md
- The formatting change caused some issues where the open release PR hadn't been updated and therefore had old formatting which caused `main` to fail once merged.
I think this won't happen in the future due to new PRs all being formatted.
=> Fix formatting issues caused by release

packages/astro/test/errors.test.js, packages/astro/test/react-component.test.js, packages/astro/test/solid-component.test.js, packages/astro/test/svelte-component.test.js, packages/astro/test/test-utils.js, packages/astro/test/vue-component.test.js
- These tests are flaky in CI on Windows, but work locally on Windows.
- Think the cause is a race condition opening a port but have had trouble tracking it down.
- Skipping to unblock the release.
=> Don't run dev mode tests on windows

examples/blog-multiple-authors/tsconfig.json, examples/blog/tsconfig.json, examples/framework-alpine/tsconfig.json, examples/framework-lit/tsconfig.json, examples/framework-multiple/tsconfig.json, examples/framework-preact/tsconfig.json, examples/framework-react/tsconfig.json, examples/framework-svelte/tsconfig.json, examples/framework-vue/tsconfig.json, examples/portfolio-svelte/tsconfig.json, examples/portfolio/tsconfig.json, examples/starter/tsconfig.json, examples/with-markdown-plugins/tsconfig.json, examples/with-markdown/tsconfig.json, examples/with-nanostores/tsconfig.json, examples/with-tailwindcss/tsconfig.json
Set `moduleResolution` inside `compilerOptions` object
As per the compiler warning in VSCode
> 'moduleResolution' should be set inside the 'compilerOptions' object of the config json file
And from the TypeScript compiler:
- [error message](https://github.com/microsoft/TypeScript/blob/7a12909ae3f03b1feed19df2082aa84e5c7a5081/src/compiler/diagnosticMessages.json#L4940-L4943)
- [test example](https://github.com/microsoft/TypeScript/blob/main/src/testRunner/unittests/config/convertCompilerOptionsFromJson.ts#L666-L673)
Config, no tests
Example, no docs
=> Adjust TSConfig example files to include compilerOptions

.changeset/soft-frogs-tap.md, packages/astro/src/core/create-vite.ts, packages/astro/src/vite-plugin-astro/index.ts
- This makes it so that if the compiler panics and `--verbose` logging is
on (debug level), we don't replace the stack trace.
- This allows you to debug the panic.
No
No
=> Don't overwrite the stack when using verbose logging

.changeset/soft-sloths-impress.md, examples/fast-build/package.json, examples/fast-build/src/components/Counter.vue, examples/fast-build/src/pages/[pokemon].astro, examples/fast-build/src/pages/index.astro, packages/astro/package.json, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/internal.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/ssr/index.ts, packages/astro/src/core/ssr/result.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/runtime/server/metadata.ts, packages/astro/src/runtime/server/util.ts, packages/astro/src/vite-plugin-astro/compile.ts, packages/astro/src/vite-plugin-build-html/index.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/astro-client-only.test.js, yarn.lock
- The 5c98456028df94aa2edef62512b24e6936d4c0b8 commit is the new code here.
- The other commit is a revert of a revert. Had to revert the new static build enhancements due to it breaking the docs site.
- In order to not rely on vite HTML post-processing the static build resolves inline script specifiers by mapping them to the hashed built file. This doesn't work for the legacy build as Vite-HTML doesn't use the same underlying API. We will want to ask Vite to expose their API, but for now since it's not needed by the legacy build, we can just not resolve the specifiers at render-time.
=> Only resolve inline script specifiers in the static build

.changeset/swift-cherries-rule.md, packages/renderers/renderer-svelte/package.json, yarn.lock
I am having funny console logs saying that my svelte component `received an unexpected slot "default".`. This issue is described [here](https://github.com/sveltejs/kit/issues/981).
Supposedly, updating svelte to version 3.44.3 solves this issue.
Sorry, I was unable to fork the renderer and test it locally. 
bug fix only
=> Update svelte version in renderer-svelte

.changeset/quick-pots-hunt.md, packages/astro/package.json, yarn.lock
- Fixes #2297
- Upgrades the language server, which no longer provides types for import.meta, fixing the above issue.
No test added in this repo.
N/A, bug fix
=> Upgrade language server

.changeset/dry-brooms-care.md, packages/astro/src/core/dev/index.ts, packages/astro/test/dev-routing.test.js, packages/astro/test/fixtures/with-subpath-no-trailing-slash/src/pages/[id].astro, packages/astro/test/fixtures/with-subpath-trailing-slash/src/pages/[id].astro, packages/astro/test/fixtures/without-site-config/src/pages/[id].astro, packages/astro/test/fixtures/without-subpath/src/pages/[id].astro
The route being passed into `ssrOptions` included the configured site pathname and therefore failed to match any patterns in the available routes when trying to extract parameters. This made it so that every valid dynamic route would error with `route pattern matched, but no matching static path found.`
I added tests for all the scenarios currently being tested under `Dynamic Routing` for both valid and invalid dynamic routes.
No documentation changes should be required since it's only a bug fix.
=> Fix dynamic routes for sites with subpath

examples/with-markdown-plugins/add-classes.mjs, examples/with-markdown-plugins/astro.config.mjs, examples/with-markdown-plugins/package.json, packages/astro/test/astro-markdown-plugins.test.js, yarn.lock
- Fixes an open security issue: https://github.com/withastro/astro/security/dependabot/yarn.lock/nth-check/open
- Brings an old dependency into the local example, as it has not been updated in 5 years and depends on a package that is 4 major versions out of date.
Tested that the example continues to work.
N/A
=> Remove rehype-add-classes

.changeset/seven-mice-do.md, packages/astro/src/core/build/scan-based-build.ts, packages/astro/src/core/create-vite.ts
- Fixes an issue where Vite Plugins are run twice.
- Hopefully improves plugin performance.
bug fix only
bug fix only
=> Fix issue with plugins running twice in dev and build

.changeset/bright-suns-brake.md, packages/astro/src/core/ssr/sitemap.ts, packages/astro/src/vite-plugin-build-html/index.ts, packages/astro/test/astro-sitemap-rss.test.js
- Preserves page pathnames.
- Does not append `/index.html`.
bug fix only
bug fix only
=> Fix sitemap.xml page urls

docs/README.md
- Fixes #2272 
- Updates the contributing docs under `docs/README.md` 
> I feel like there should be a link to contributing in both `README.md`, `CONTRIBUTING.md`, and on the docs website 🤔
=> Improve the contributing docs for the documentation!

www/src/components/BaseHead.astro, www/src/pages/blog/[slug].astro
Generate a RSS feed for Astro Blog posts, and add an alternate link to the `<head>` for discoverability.
Build and serve locally, then check `/rss.xml`.
Or check deploy preview feed: https://deploy-preview-2301--astro-www.netlify.app/rss.xml
No documentation updates, blog changes only.
Closes #1009.
=> Add Astro Blog RSS feed

docs/public/index.css
- public/index.css
added -
```css
html {
scroll-behavior: smooth;
}
```
> Just because it's a simple CSS change
Yes!, It improves the UX for developers who visit the page
=> smooth scroll behavior property added

docs/src/pages/en/core-concepts/astro-components.md
- A note was added to the "Fragments & Multiple Elements" section of the component syntax page of the English docs.
- I also added the syntax to the jsx comparison table on that page.
Just added a note to the docs.
I added a note to the docs about Astro supporting `<Fragment>` syntax for fragments in addition to `<>`.
=> Note that Astro also supports `<Fragment>` syntax

.github/workflows/ci.yml
- Previously, changeset bot only ran after tests had passed. 
- This can add extra minutes to a release process (especially waiting for the smoke test) and also lead to an outdated/missing release PR if a flakey test happens.
- Because tests will re-run in the `ci release` PR before a release, waiting for tests to run here is unnecessary. 
cc @natemoo-re would love a sanity check on this thinking to make sure it makes sense.
=> move changeset to run after build, no test required

docs/public/index.css
- Moves recent `scroll-behavior: smooth` behind `prefers-reduced-motion: no-preference`
- Respects user who prefer reduced motion.
style fix only
style fix only
=> Use smooth scrolling with reduced motion has no preference

.changeset/happy-penguins-wave.md, packages/renderers/renderer-solid/server.js
in `yarn.lock` file, the resolved `solid-js` version is 1.3.2, `solid-js`'s dependency `dom-expressions` version is 0.31.9
in `dom-expressions` package, the current property name is `_$HY`
cc:
https://github.com/ryansolid/dom-expressions/blob/d6acdfaec8fd29efa9954a56f1f6d068b9b8e528/packages/dom-expressions/src/server.js#L393-L399
bug fix only
close #2336;
=> Fix renderer-solid (fix #2336)

docs/package.json, yarn.lock
- Restores `lint:a11y` check on docs site
- Command was broken, as `pa11y-ci` dependency was missing.
These tests are not yet run as part of CI, but they can be run manually.
**Next Steps**:
- Every single page currently fails accessibility testing.
- Separate Issue/PR with current accessibility report.
- Separate PR with fixes.
run fix only
=> Fix accessibility check on docs site

.changeset/tricky-eagles-enjoy.md, packages/astro/src/core/build/static-build.ts, packages/astro/test/fixtures/static-build/src/layouts/Main.astro, packages/astro/test/fixtures/static-build/src/pages/index.astro, packages/astro/test/fixtures/static-build/src/pages/posts/thoughts.md, packages/astro/test/static-build.test.js
This fixes the `--experimental-static-build` flag to work with markdown
pages.
- Correctly check if a Rollup chunk came from one of our entrypoints.
Test added
Bug fix
=> Fix: static-build with .md pages

.changeset/long-eagles-care.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/fs.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/ssr/index.ts, packages/astro/test/fixtures/static-build-frameworks/src/components/PCounter.jsx, packages/astro/test/fixtures/static-build-frameworks/src/pages/index.astro, packages/astro/test/static-build-frameworks.test.js
- This fixes how renderers are used in the static build.
- Since we compile to ESM and then load pages in regular Node.js, we need the renderers to load the same way. This fixes that.
Tests added 
N/A, bug fix
=> Fix use of frameworks in the static build

.changeset/odd-flowers-pay.md, .changeset/spotty-flies-share.md, .changeset/yellow-dolphins-buy.md, examples/blog/src/components/BaseHead.astro, examples/blog/src/layouts/BlogPost.astro, examples/blog/src/pages/index.astro, examples/docs/src/components/Header/Search.tsx, packages/astro/package.json, packages/astro/src/core/build/static-build.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/runtime/server/metadata.ts, packages/astro/test/fixtures/static-build-frameworks/src/components/LCounter.js, packages/astro/test/fixtures/static-build-frameworks/src/components/Nested.astro, packages/astro/test/fixtures/static-build-frameworks/src/components/Nested.jsx, packages/astro/test/fixtures/static-build-frameworks/src/pages/lit.astro, packages/astro/test/fixtures/static-build-frameworks/src/pages/nested.astro, packages/astro/test/fixtures/static-build/src/pages/index.astro, packages/astro/test/static-build-frameworks.test.js, packages/astro/test/static-build.test.js, packages/renderers/renderer-lit/package.json, packages/renderers/renderer-lit/server-shim.js, scripts/stats/stats.csv, yarn.lock
- Lit needs polyfills to be build and resolved when the pages are rendered. This fixes that.
- Test added
- Example app confirmed
N/A bug fix
=> Fixes Lit support in the static build

.changeset/metal-pens-decide.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/page-data.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/ssr/index.ts, packages/astro/src/core/ssr/route-cache.ts
- On large sites that are thousands of pages rendering all pages in parallel becomes a bottleneck as it adds a lot of tasks to the microtask queue. This change throttles rendering so that there are only 10 simultaneous renders. This prevents the build from choking on very large sites.
- This also optimizes `getParamsAndProps` which was taking almost as much time as rendering, due to looping over paths frequently and validating when validation had already occurred.
- Closes https://github.com/withastro/astro/issues/1711
Manually tested against the example app in https://github.com/withastro/astro/issues/1711
Bug fix
=> Improve static build performance on large sites

docs/src/pages/de/guides/styling.md, docs/src/pages/en/guides/styling.md
`<link href={Astro.resolve("./X.css")} />` did not work on recent versions of astro.
see also #2393
This is a documentation update so no tests are added.
This commit itself is a documentation update.
=> Update doc move away from Astro.resolve on styles

.changeset/flat-tips-happen.md, examples/blog-multiple-authors/src/components/MainHead.astro, examples/docs/src/components/HeadCommon.astro, examples/framework-multiple/src/pages/index.astro, examples/starter/src/pages/index.astro, examples/with-markdown-plugins/src/layouts/main.astro, examples/with-markdown/src/layouts/main.astro, examples/with-nanostores/src/pages/index.astro, packages/astro/src/core/build/static-build.ts
- Updates the examples to use `<style global>@import "..."</style>` where they used to use Astro.resolve.
- Based on https://github.com/withastro/rfcs/blob/main/active-rfcs/0000-style-unification.md
Tested to verify they work both in the normal and static build.
N/A
=> Update examples to move away from Astro.resolve on styles

docs/src/pages/de/core-concepts/component-hydration.md, docs/src/pages/en/core-concepts/component-hydration.md, docs/src/pages/es/core-concepts/component-hydration.md
Fixes #2407 🚀 
Remove incorrect statement in the [Partial Hydration section](https://docs.astro.build/en/core-concepts/component-hydration/#concept-island-architecture) of the docs that Jason Miller coined the phrase "Island Architecture." See issue #2407 for a short discussion of possible replacement phrases. Any of the suggested phrases there also seem fine as alternatives to this PR.
N/A -- docs only change
=> Fix "Island Architecture" phrase attribution

.changeset/ten-cougars-knock.md, docs/src/pages/en/guides/markdown-content.md, docs/src/pages/en/reference/configuration-reference.md, packages/astro/src/@types/astro.ts, packages/astro/src/cli/index.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/config.ts, packages/astro/test/astro-markdown-drafts.test.js, packages/astro/test/fixtures/astro-markdown-drafts/src/pages/index.md, packages/astro/test/fixtures/astro-markdown-drafts/src/pages/wip.md
* implemented support for draft pages
* added integration test
* updated relevant documentation (english only)
An integration test has been added with both possible scenarios. The test checks whether the draft markdown page in the fixture is rendered or not.
The public documentation, as well as the configuration documentation was updated. Suggestions are welcome.
=> Implement support for draft pages

docs/src/pages/en/guides/markdown-content.md
The path denoted in the markdown sample code is
src/pages/index.md
Thus, to refer to a layout component in src/layouts,
we should use ../layouts/ instead of ../../layouts/.
This is a documentation change, so no tests are added.
This commit itself is an update to docs.
=> fix: path error in sample markdown code

packages/create-astro/src/index.ts
astro's repo changed from snowpack/astro to withastro/astro,
so I updated the error message accordingly.
No tests added since the update is meant for a human to read.
This is only a error message fix, so there is no need to update the public documentation.
Currently the public documentation did not mention this error message.
=> Update .degit cache path in error message

docs/src/components/Header/SkipToContent.astro, examples/docs/src/components/Header/SkipToContent.astro
- This PR makes the “Skip to Content” link visible on focus on the docs site and in the docs example project.
| Before (link is focused but not visible) | After (link is focused and visible) |
|---------------------------------------|------|
| ![Screen Shot 2022-01-16 at 15 38 07](https://user-images.githubusercontent.com/357379/149664622-a7e015fb-e06f-4dc2-a4fb-9874568238e3.png) | ![Screen Shot 2022-01-16 at 15 38 47](https://user-images.githubusercontent.com/357379/149664626-80d019e0-60e7-44ac-8c82-885f4aa61545.png) |
This pattern is [recommended by the Institute for Disability Research, Policy, and Practice](https://webaim.org/techniques/skipnav/#hidden) (and was also I think already the intended behaviour given that styling was included for the link when visible).
Tested by running …
=> Fix visibility of focused skip link on docs site

docs/src/pages/en/guides/markdown-content.md
- image reference path to the assets folder in public directors needs to begin with `/`. Example: Image is located at /public/assets/img/astonaut.png → Markdown: ![Astronaut](/assets/img/astronaut.png)
Local testing. 
No Tests as it’s a doc update
Yes
N/A
=> update image reference path

.changeset/cold-bottles-eat.md, packages/astro/package.json
This pins to the compiler 0.8.1 version, the last working version for the Windows smoke tests. Currently tracking down what broke in 0.8.2, but this will fix PRs in the meantime.
=> Pin to the compiler 0.8.1

docs/src/pages/en/core-concepts/component-hydration.md
Fix "Astro Components" link at "Partial Hydration" documentation
I kept the pattern linking full path instead using relative patter.
=> doc: fix "Astro Components" link reference

.changeset/gentle-cats-guess.md, packages/create-astro/README.md, packages/create-astro/src/index.ts, packages/create-astro/src/logger.ts
- This adds an option to create-astro to use verbose logging which should help debug degit issues (And others as well)
=> Add a verbose flag to create-astro

.changeset/sour-games-boil.md, examples/fast-build/package.json, examples/fast-build/src/components/ExternalHoisted.astro, examples/fast-build/src/components/InlineHoisted.astro, examples/fast-build/src/pages/index.astro, examples/fast-build/src/scripts/external-hoist.ts, packages/astro/package.json, packages/astro/src/core/build/internal.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/vite-plugin-hoisted-scripts.ts, packages/astro/src/core/ssr/index.ts, packages/astro/src/core/ssr/result.ts, packages/astro/src/runtime/server/metadata.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/fixtures/static-build/src/components/ExternalHoisted.astro, packages/astro/test/fixtures/static-build/src/components/InlineHoisted.astro, packages/astro/test/fixtures/static-build/src/pages/hoisted.astro, packages/astro/test/fixtures/static-build/src/scripts/external-hoist.ts, packages/astro/test/static-build.test.js, yarn.lock
- Adds support for hoisted scripts to the static build. This will add hoisted scripts as external in dev like `/src/components/Nav.astro?astro&type=script&index=0`.
- During the static build these are bundled at the page level and then the result is rendered out to the final HTML.
Tests added
N/A
=> Supports hoisted scripts in the static build

.changeset/flat-mayflies-ring.md, packages/astro/src/core/build/page-data.ts, packages/astro/src/core/ssr/rss.ts, packages/astro/src/core/util.ts, packages/astro/test/astro-sitemap-rss.test.js, packages/astro/test/fixtures/astro-sitemap-rss/src/pages/episodes/[...page].astro
- Follow-up to #2426
- Fixes fully valid URLs in RSS feed
- Also fixes a bug uncovered by #2426 where `rss()` could not be called multiple times
- Tests updated
Bug fix only
=> Fix pre-generated RSS URLs

.changeset/neat-seals-fold.md, package.json, packages/astro/src/core/build/static-build.ts, packages/astro/test/fixtures/static-build/package.json, packages/astro/test/fixtures/static-build/pkg/package.json, packages/astro/test/fixtures/static-build/pkg/pkg.js, packages/astro/test/fixtures/static-build/src/pages/index.astro, packages/astro/test/static-build.test.js
- In the static build, include a user's own `vite.ssr` configuration, so they can control `external` and `noExternal` config.
Test added
Bug fix
=> Pass user's viteConfig.ssr to the build

examples/docs/src/components/LeftSidebar/LeftSidebar.astro
Someone may forget to specify a section header in SIDEBAR,
which would cause build error previously.
No tests added.
Manually tested:
```sh
npm i
npm run dev
```
Previously examples/docs/README.md did not mention that header is required in `SIDEBAR`,
and this commit make it optional.
Thus no documentation need to change.
=> Allow not specfying section header in sidebar.

examples/docs/src/components/Header/Header.astro
Use SITE.title specified in config.ts as the h1 heading in Header.astro
of doc theme.
When SITE.title is null, use "Documentation" as the fallback value.
Previously the h1 heading in doc theme header is hardcoded
as "Documentation".
I run `npm run dev` and manually checked the rendered page.
Given the following config:
```
export const SITE = {
title: 'Your Documentation Website',
// omitted
};
```
The page is rendered as expected:
Then I removed the title:
```diff
export const SITE = {
-	title: 'Your Documentation Website',
};
``` 
And the page is rendered as below:
Previously `examples/docs/README.md` did not mention that the Documentation h1 heading is hard-coded in `Header.astro` and just changing `SITE.title` would not change the h1 heading.
Thus I think no documentation need to …
=> Use CONFIG.SITE.title for h1 in doc theme header

.changeset/angry-apricots-invite.md, packages/astro/src/core/ssr/index.ts, packages/astro/src/vite-plugin-astro/compile.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/vendor/vite/dist/client/client.mjs
- Fixes HMR when using this pattern:
```
<style global>
@import "../src/global.css";
<style>
```
- Previously edits to the external CSS/etc files would not result in HMR. Actually they wouldn't result in changes even on a refresh.
- This also fixes HMR in the static build generally, which was not adding the Vite client.
- Upstream Vite fix required, PR in flight.
N/A bug fix
=> Fix HMR in static build + @import HMR

packages/astro/package.json
- Runs `lit-element.test.js` separately to prevent the test suite from erroring out.
Resolves https://github.com/withastro/astro/issues/2445
bug test only
bug test only
=> run lit test separately to prevent error

CONTRIBUTING.md
- Adds link explaining what core contributors are
- Per [this discussion](https://canary.discord.com/channels/830184174198718474/853350631389265940/933879694749737030) in discord
- No code changes
- No code changes
=> Add link to GOVERNANCE from CONTRIBUTING

packages/astro/package.json, packages/astro/test/fixtures/fetch/src/components/AlreadyImported.astro, packages/astro/test/test-utils.js
- Removes `node-fetch` dependency from `astro`
- Internally, `astro` has been using `@astropub/webapi`
- Updates test util to use `fetch` from `@astropub/webapi`
- Updates `AlreadyImported.astro` test to remove `node-fetch` and presume `fetch` is _already imported_.
internal change only
=> Remove `node-fetch`

packages/astro/src/@types/astro.ts, packages/astro/src/cli/index.ts, packages/astro/src/core/config.ts
- In trying to do some cleanup of the Astro config object, I realized that we were merging CLI flags completely outside of our normal config validation. This meant that we had to duplicate/maintain validation & transformation in a second place.
- This is just a cleanup, with a followup PR to come that is based off of this cleanup.
- Covered by existing tests.
- cleanup, n/a
=> clean up config loading and flag merging

CONTRIBUTING.md, package.json, packages/astro/package.json
- Our docs were incorrect, and there was no easy way to run a single test since turbo did not support argument passing.
- Adds a new `test:match` command for running specific tests
```shell
yarn test
yarn test:match "$STRING_MATCH"
```
- is test
- n/a
=> add a new test:match command script

docs/src/pages/en/reference/configuration-reference.md
That the behavior of `pages` is relative to project root, not `src`
Manually tested in project
Aligns docs with how it currently works
=> Aligns docs on `pages` config with reality

docs/src/pages/en/reference/configuration-reference.md
Forgot to update the description in the pages section. It looks like there's still a bigger issue across the board that `projectRoot` may not be respected. But pages config is now consistently with other config settings
Look at first PR, forgot this part
This is a docs change
=> update pages config doc description

.changeset/hungry-dots-reply.md, examples/fast-build/src/pages/index.astro, packages/astro/src/vite-plugin-astro/compile.ts
- In order to fix HMR a change was made to the static build which prevented preprocessing, thinking that the module would be preprocessed later.
- This was a mistake, we have to preprocess because scoping happens in the compiler. So this restores preprocessing for the static build.
Updated the example app.
Bug fix
=> Fix use of preprocessors with the static build

packages/astro/src/runtime/server/index.ts
- Renders the tag name of a Custom Element (after any renderers).
- Prevents a tag made from an `HTMLElement` from throwing.
- ~Adds a script to register the constructor.~
**Before**:
```astro
<script hoist>
class Button extends HTMLElement {}
customElements.define('h-button', Button)
</script>
<h-button><slot /></h-button>
```
```astro
---
// src/pages/index.astro
import Button from '../components/Button.astro'
---
<Button>Button</Button>
```
**After**:
```js
// src/components/Button.js
export default class Button extends HTMLElement {}
customElements.define('h-button', Button)
```
```astro
---
// src/pages/index.astro
import Button from '../components/Button.js'
---
<Button>Button</Button>
```
testing tbd, if the pr is conceptually acceptable
docs tbd
=> Render Custom Element Tag

packages/astro/src/core/build/static-build.ts
- Fixes top-level await and other `es2021`, `es2022`, `esnext` features not working with the static build,
Tested locally.
Bug fix only
=> Changed vite.build target to esnext

packages/astro/src/core/ssr/result.ts, packages/astro/src/core/ssr/script.ts
- if `astroConfig.buildOptions.experimentalStaticBuild` is true and file path extension match `.ts` or `.js`, a new message will be presented in the console.
- Adds a file at `packages/astro/src/core/ssr/script.ts` used as util for script detection (same code structure as `css.ts` in the same folder)
```ts
export const SCRIPT_EXTENSIONS = new Set(['.js', '.ts']);
const scriptRe = new RegExp(
`\\.(${Array.from(SCRIPT_EXTENSIONS)
.map((s) => s.slice(1))
.join('|')})($|\\?)`
);
export const isScriptRequest = (request: string): boolean => scriptRe.test(request);
```
- Shows a suggestion like this when a `.ts` or `.js` file is detected
```
03:20 PM [deprecation] Astro.resolve() is deprecated. We see that you are trying to resolve ./scripts/bar.ts.
It looks like you are resolving scripts. If …
```
=> Add Astro.resolve deprecation warning case for script tags

packages/astro/src/core/build/static-build.ts, packages/astro/src/runtime/server/index.ts, packages/astro/test/static-build.test.js
- Fixes this regression: https://github.com/withastro/astro/pull/2486/files#r795260099
- no changeset needed since this regression hasn't gone out yet
- Does this need a test? Odd that none of our build tests caught this, since it feels like any buildOptions.site value would break this.
- N/A
=> Fix a regression in vite.build() base option

docs/src/pages/en/guides/styling.md
Style is written in SCSS, so there is missing '&' in nesting data-theme
=> Missing '&' in example of scoped styles

examples/portfolio-svelte/README.md
Currently, the `portfolio-svelte` example uses the same installation command as `portfolio`.
As a result, `npm init astro -- --template portfolio` does not install the `portfolio-svelte` example.
- [docs] fix typo in portfolio-svelte installation command
=> [docs] fix typo in portfolio-svelte example

.changeset/calm-suns-give.md, packages/astro/src/runtime/server/index.ts
- Updates `renderHTMLElement` method to support children like `renderComponent`.
bug fix only
bug fix only
=> Fix issue rendering content within HTMLElement

.changeset/mighty-lamps-drive.md, examples/fast-build/src/pages/index.astro, packages/astro/package.json, packages/astro/src/runtime/server/index.ts, yarn.lock
- Updates the compiler to the newest version.
- Allows styles to be added behind the flag, which allows the define:vars styles to be added.
Added via the example.
N/A
=> Fix define:vars in the static build flag

.changeset/chatty-spies-wink.md, .changeset/mighty-lamps-drive.md, packages/astro/components/Code.astro, packages/astro/components/Markdown.astro, packages/astro/components/Prism.astro, packages/astro/package.json, packages/astro/src/runtime/server/escape.ts, packages/astro/src/runtime/server/index.ts, yarn.lock
- Does not require compiler changes!
- Deprecates passing unescaped HTML inside of an expression (like `{"<style>div { color: red; }</style>"}`, logs a warning when unescaped HTML is encountered
- Does **NOT** enable automatic escaping inside of expressions! This is a simple toggle that can be enabled in a follow-up PR to be released in the next minor version.
- Adds an internal `UnescapedString` primitive to power `set:html` and internal rendering 
Tested manually in the examples. 
**TODO:** ensure all examples are working as expected.
TBD.
=> Deprecate unescaped HTML inside of expressions

.changeset/brown-dancers-perform.md, examples/fast-build/src/pages/index.astro, examples/fast-build/src/styles/_global.scss, packages/astro/src/vite-plugin-astro/compile.ts, packages/astro/src/vite-plugin-astro/hmr.ts, packages/astro/src/vite-plugin-astro/index.ts
- Previously the static build would fail to compile CSS supersets like scss because it was extracting dependencies and adding them back as imports. Since these deps were scss themselves, the CSS wouldn't load.
- This brings things back to the way that they were before; CSS is completely compiled in the compiler, including dependencies.
- Instead, we extract dependencies to track via HMR. When HMR occurs we invalidate our compilation cache so that the root .astro styles are reloaded.
No HMR unit tests exists, tested via the example app (update is included here).
Bug fix only
=> Fix support for scss in static build

packages/astro/src/core/build/index.ts
Verbose builds erroneously says "Sitemap built" even if sitemap is disabled in config.
No tests, just moved debug inside if block.
bug fix only
=> fix(sitemap): remove debug message if sitemap disabled

packages/astro/src/core/ssr/sitemap.ts, packages/astro/src/vite-plugin-build-html/index.ts
Handles all http error code file names the same as 404 files.
Fixes #2195.
I don't think test changes are necessary, although if I knew how I would add extra tests to make sure that all of the HTTP status code files are generated correctly.
Bug fix only.
=> Handles all http error code file names the same as 404 files.

.changeset/grumpy-chefs-judge.md, packages/astro/src/core/dev/index.ts
- Fixes an issue brought up in https://github.com/withastro/rfcs/discussions/80
- In the Vite server refactor we stopped sending the dev's host value to Vite
- @benjaminwy @jonathantneal 
- We can't currently test for this since it will fail if the address is not available. Both of our current tests on this do test it _loosely,_ but I can't think of a better way to do it right now.
- N/A
=> add back dev server host support

.changeset/four-mirrors-wonder.md, packages/astro/src/vite-plugin-astro/hmr.ts
- When finding modules that should be HMRed, start with the list that has already been discovered by Vite.
- If you return from `handleHotUpdate` it overrides any existing modules to update. So you must append to the list, not just return new ones.
- Closes https://github.com/withastro/astro/issues/2528
Tested via example apps.
N/A, bug fix.
=> Append to list of HMR modules, don't override

.changeset/shy-brooms-tell.md, packages/astro/src/runtime/server/index.ts
- HTML has a number of attributes that should be treated as booleans. That is, if passed a value of `true`, they should be present with just the key. Examples include `open` and `async`, among others.
- HTML and SVG also have a number of attributes that should be coerced to strings. That is, if passed a value of `true`, they should have a value of `"true"`. If passed a value of `false`, they should have a literal value of `"false"`.
- This PR updates our attribute rendering logic to account for these.
No tests added, but I should!
Bug fix only
=> fix: HTML/SVG boolean attributes

.changeset/many-oranges-retire.md, packages/astro/src/cli/index.ts, packages/astro/src/core/logger.ts
- Hooks up `--verbose` to new debugger, missed this in #2504 
- Improves formatting of debug messages, which previously were all arrays
- N/A
- N/A
=> improve debug logs

packages/astro/src/runtime/server/index.ts
- Improves error messages when matching renderers can be guessed, like if there is only a single renderer or a `.vue` file throws when `@astrojs/renderer-vue` is enabled.
**Before**
**After**
Manually
QoL improvement
=> Improve error handling

packages/astro/test/astro-attrs.test.js, packages/astro/test/fixtures/astro-attrs/src/pages/index.astro
Adds a few test cases to cover the fix for PR #2538, no production code updates
Adds a handful of tests to verify that boolean and enum HTML attributes are being serialized properly
test updates only (no docs changes)
=> adding test coverage for boolean and enum HTML attributes

packages/astro/components/Code.astro, packages/markdown/remark/src/remark-shiki.ts
Adds `data-astro-raw` to prevent Astro to think the curly braces inside codeblocks are expression
n/a
n/a
=> fix: curly braces inside Shiki

.changeset/fresh-moose-compare.md, packages/astro/src/core/build/index.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/core/dev/index.ts, packages/astro/test/astro-class-list.test.js, packages/astro/test/astro-client-only.test.js, packages/astro/test/astro-component-code.test.js, packages/astro/test/astro-doctype.test.js, packages/astro/test/astro-jsx.test.js, packages/astro/test/astro-pagination.test.js, packages/astro/test/builtins.test.js, packages/astro/test/lit-element.test.js, packages/astro/test/markdown.test.js, packages/astro/test/postcss.test.js, packages/astro/test/preact-component.test.js
- Makes it so that the Vite server plugin only runs during `astro dev`. Running during build is both unnecessary and causes the manifest to be rebuilt constantly because the filewatcher fires often during the build.
No way to test.
N/A, bug fix
=> Prevent the server plugin from running during the build

.changeset/afraid-moles-hunt.md, .changeset/loud-seals-camp.md, .changeset/many-berries-bake.md, packages/astro/package.json, packages/renderers/renderer-lit/package.json, packages/renderers/renderer-preact/package.json, packages/renderers/renderer-react/package.json, packages/renderers/renderer-solid/package.json, packages/renderers/renderer-svelte/package.json, packages/renderers/renderer-vue/package.json, yarn.lock
- `vite@2.8.0` has been released! This upgrades our dependency.
- Also upgrades our renderer dependencies.
CI
N/A
=> Upgrade `vite` and renderer dependencies

.changeset/soft-mayflies-warn.md, packages/astro/src/core/create-vite.ts
- Reverts the change that happened here: https://github.com/withastro/astro/commit/1abb9ed0800989f47351cc916f19fd8e0672e2c0#diff-025f8338e5be413b0f65c74bc50d6484c6bc9bb4f78847da0ba896b8e9569390L28-L30
- Fixes #2567
- 'astro' has to be set to `noExternal` because we cannot set just `astro/components` to noExternal. astro/components must be noExternal so that it's built with Vite.
Not testable as this only happens outside of the monorepo.
Bug fix
=> Use noExternal config on 'astro'

.gitignore, package.json, scripts/jsconfig.json, scripts/package.json, scripts/smoke/cleanup.js, scripts/smoke/index.js, yarn.lock
- Updates smoke tests to include external `docs` and `www`.
Adds tests for the externalized `docs` and `www` main branches.
testing only
=> Update smoke tests to include external docs and www

scripts/smoke/index.js
Skipping this test which is causing all PRs to fail. We should follow-up with a fix to the underlying issue shortly.
=> Skip the docs-main smoke test

packages/astro/package.json
Move SASS to be a devDependency instead of a normal dependency. The reason for this change is that we shouldn't be shipping SASS ourselves, not only does both the Astro and the Vite documentation says to manually add it to your project but I also think that it's useless to be shipping it ourselves when in reality, probably only a minority of our users uses it (this makes Astro about 5mb smaller for most people!)
For context, here's what the current docs says about it:
> Sass: Run npm install -D sass and use <style lang="scss"> or <style lang="sass"> (indented) in .astro files
Stylus: Run npm install -D stylus and use <style lang="styl"> or <style lang="stylus"> in .astro files
Less: Run npm install -D less and use <style lang="less"> in .astro files.
Users who don't have it installed will …
=> Move SASS to devDependencies

.changeset/great-suns-pump.md, packages/astro/src/@types/astro.ts, packages/astro/src/runtime/client/idle.ts, packages/astro/src/runtime/client/load.ts, packages/astro/src/runtime/client/media.ts, packages/astro/src/runtime/client/only.ts, packages/astro/src/runtime/client/visible.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/runtime/server/index.ts, packages/astro/test/astro-children.test.js, packages/astro/test/fixtures/astro-children/src/components/NoRender.jsx, packages/astro/test/fixtures/astro-children/src/pages/no-render.astro
- Fixes #642
- When a client component doesn't render `<astro-fragment>` but there are children, we know that means they did not render the children.
- Instead we add a `<template data-astro-template>` inside of the `<astro-root>`. In the client the HTML inside of this template becomes the children passed to the client component.
Tests added.
Not needed, bug fix.
=> Pass children to client components even if they do not render them

.changeset/sweet-spoons-cheer.md, packages/astro/src/core/render/core.ts, packages/astro/src/core/render/route-cache.ts, packages/astro/test/fixtures/astro-get-static-paths/src/pages/blog/[year]/[slug].astro
Bug fix for [#2235](https://github.com/withastro/astro/issues/2235) - Order of params for routing has to match
Currently, `src/pages/blog/[year]/[slug].astro` wouldn't match if `getStaticPaths` returned params of `{ slug: 'post-1', year: '2022' }`
Tests added to the `astro-get-static-paths` test suite
Bug fix only
=> Bug fix: Order of params for routing has to match

.changeset/eighty-cows-wink.md, packages/astro/package.json, yarn.lock
- Upgrade `@astrojs/compiler` to [`v0.11.0`](https://github.com/withastro/compiler/blob/main/lib/compiler/CHANGELOG.md#0110).
- At the cost of a larger `.wasm` file, this is a significant improvement for stability and memory safety.
CI passing, third-party reproductions passing
Bug fix only
=> Upgrade `@astrojs/compiler`

examples/with-tailwindcss/src/pages/index.astro
Updates the `with-tailwindcss` example to leverage `set:html` when inlining global CSS in the `<head>`
**Why?**
The `@import "../styles/global.css";` example has a few rough edges with regards to HMR, see #1943 and #2410 for more details
By importing the styles and adding them to the head with `set:html`, vite adds `global.css` to the resource graph and watches the file for changes.
Tested the example project locally with `astro dev` and `astro build`.  In `dev`, HMR now works as expected with any changes to `global.css` triggering a rebuild and update.
I also confirmed this fixes #2410.  I'm not 100% sure what the underlying issue here was, but once `global.css` is included in Vite's resource graph any components added after the dev server starts are also picked up and watched for file …
=> importing and inlining global.css with set:html

examples/blog/astro.config.mjs
- Fixes: #2288 
- As reported in #2288 , `examples/blog` template currently does not generate `sitemap.xml` nor `rss.xml`
- I configure `buildOptions.site` to generate `sitemap.xml`
- as far as I understand, to generate `rss.xml` with astro needs a dynamic page(`[page].astro`), and the way to generate `rss.xml` on the static page has not been supported yet
-  should I fix static page `posts/index.md` into dynamic page to generate `rss.xml`?
- or should I wait for astro supporting to generate `rss.xml` with static pages?
- this is a tiny fix, but I would be happy if this helps you.
I did not add any additional tests because this is the fix in the example showcase.
Not needed, this is the fix in the example showcase.
=> Chore: fix examples/blog template generate sitemap.xml

.changeset/fuzzy-drinks-drop.md, packages/astro/src/core/path.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/static-build.test.js
- Fixes #2602
- We resolve style ids to be root-relative so that the Vite CSS plugin correctly resolves relative imports. A regression in https://github.com/withastro/astro/commit/ec6f148fc8623c6549885af70512839c08905fdb made it so that the query params were removed.
Test added
Bug fix only
=> Fix loading of styles in static build

.changeset/cool-months-deliver.md, packages/astro/src/core/render/dev/index.ts
- Fixes #2603
- In the core refactor this file was moved around but the path was not changed.
- This only applies to the static build
We don't have tests for HMR yet :(
Bug fix.
=> Static build - fixes path to HMR script

.github/workflows/ci.yml, scripts/memory/index.js
**tldr: Uncovered a memory leak test bug that causes it to pass/fail unreliably. I may get this merged asap so that our CI goes back to reliable + green for any weekend PRs.**
A bit of fun to end the day: I was seeing some flakiness in the memory test and ended up refactoring a bit of it. There's a mix of usability changes (`--ci` mode if you want a final pass/fail, otherwise it will run forever and let you spot the trend in the output over time) and actual test reliability improvements. Mainly:
- Added `--expose-gc` support so that we can guarantee that garbage collection runs
- Switched `total_head_size -> used_heap_size`. `total` is the total reserved, which is largely up to Node.js. Used is actual memory used by the application. 
With these two changes I now see reliable results …
=> improve memory leak test

packages/astro/src/core/render/dev/index.ts
If you were to run this Non-HTML Pages example:
https://github.com/withastro/astro/pull/2637
When using ` --experimental-static-build` in `package.json`:
```json
{
"name": "@example/non-html-pages",
"version": "0.0.1",
"private": true,
"scripts": {
"dev": "astro dev --experimental-static-build",
"start": "astro dev --experimental-static-build",
"build": "astro build --experimental-static-build",
"preview": "astro preview"
},
"devDependencies": {
"astro": "^0.23.0-next.10"
}
}
```
Then visit http://localhost:3000/company.json you will see an error like that:
```
Cannot read properties of undefined (reading 'hoistedScriptPaths')
```
This commit resolves the issue and allows the non-html page to load, as well as regular `.astro` pages without issue.
=> Make Non-HTML Pages work for static build

.changeset/great-hotels-breathe.md, packages/astro/components/Code.astro, packages/markdown/remark/src/remark-shiki.ts
With a package.json with `{ "type": "module" }`, shiki doesn't work. That because it doesn't have a default export (although their `index.d.ts` says the opposite)
=> Fixed shiki import to work with "type": "module"

examples/with-vite-plugin-pwa/package.json, examples/with-vite-plugin-pwa/src/pages/index.astro, scripts/smoke/index.js
- Test change only
All of the examples that are smoke tested are also run with `--experimental-static-build flag.
Test only
=> Run all smoke tests with the static build

packages/astro/components/Markdown.astro, packages/astro/test/astro-markdown-shiki.test.js, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/nested-list.astro
Fixes: #2610 
- in the current implementation, `<Markdown />` trims the start of the content in each line of slot of `<Markdown />`
- However, some markdown grammar, such as nested list, have the meaning on the tab or space of the start of the line, so #2610 happens.
- I fixed this behavior to trim just the same amount of tab or space from the start of line
simply, add the test case to test about nested list
no need, this is a tiny bug fix
This is my secound contribution to astro, so there may be something I missed(testing, coding style, context, etc…). If there is something I missed, please be free to point out or close this PR 🙇
=> Fix(component): align starting position in Markdown slot

examples/blog-multiple-authors/package.json
https://astro.new/blog-multiple-authors?on=stackblitz
```
500: Internal Error
Expected an exported Astro component but received typeof undefined
Error: Expected an exported Astro component but received typeof undefined
at Module.render (file:///home/projects/bnmipkqmz.github/node_modules/astro/dist/core/render/core.js:58:11)
at async render (file:///home/projects/bnmipkqmz.github/node_modules/astro/dist/core/render/dev/index.js:41:17)
at async Module.ssr (file:///home/projects/bnmipkqmz.github/node_modules/astro/dist/core/render/dev/index.js:107:12)
at async handleRequest (file:///home/projects/bnmipkqmz.github/node_modules/astro/dist/vite-plugin-astro-server/index.js:88:18)
```
=> Add sass dev dep to blog-multiple-authors example

.changeset/twelve-eggs-join.md, packages/astro/src/core/logger.ts
Solving #2625
- npm run dev & npm init astro now works with process.env.LANG larger than 5 characters (ej: "es_ES@euro")
No testing added because I can't launch test without this change
Bug fix only
=> fix(core): Issue #2625. error with process.env.LANG larger than 5

.changeset/spicy-tomatoes-act.md, examples/ssr/server/server.mjs, packages/astro/src/vite-plugin-astro-server/index.ts
- Fixes a small bug that was causing utf-8 encoding issues. For example, we were seeing `Donâ€:tm:s Blog` instead of `Don's Blog`.
- Fixed the same bug in the ssr example directory.
- Tested manually, too small to add a test for imo but happy to add if anyone feels strongly!
- N/A
=> ensure utf8 encoding when serving html

.changeset/dry-geese-speak.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/create-vite.ts
- Improves support for third-party `.astro` packages.
- Vite now automatically does NOT process any third-party packages, which is the right approach in most cases. For Astro community packages, we reccomend exporting `.astro` files which means Vite needs to process the package.
- This PR scans a project's dependencies on startup to filter any third-party Astro packages to treat as `ssr.noExternal`.
Manually. Not sure there's a great way to test this.
N/A
=> Improve third-party Astro package compatability

.changeset/lovely-lies-dress.md, examples/fast-build/package.json, packages/astro/src/vite-plugin-astro/compile.ts
- Fixes #2655 
- Note: This is a short term fix to a longer-term problem! A longer-term fix will need more design and implementation work, so the hope is that this small fix can serve to work in the meantime.
- I have a test ready, however this only works in `--experimental-static-build`. @matthewp is it better to add the new test commented out, for when we migrate over tests?
- N/A
=> fix astro scoping of "@import" inside of style tags

packages/astro/src/runtime/server/index.ts
- In a prior version of astro, the `unescapeHTML` method was introduced to mark a string as raw, unescaped HTML.
- This method was not applied to the `renderHTMLElement` method.
- This PR applies the `unescapeHTML` method to the result of the `renderHTMLElement` method.
Resolves https://github.com/withastro/astro/issues/2664
- There are no tests for `unescapeHTML`, which applies to many other places.
- A followup PR should address the overall missing tests.
bug fix only
=> Fix HTMLElement expression warning

.changeset/thin-birds-rescue.md, packages/astro/package.json, packages/astro/src/runtime/client/hmr.ts, packages/astro/src/vite-plugin-astro/hmr.ts, packages/astro/src/vite-plugin-astro/index.ts, yarn.lock
- Improves Astro's HMR handling. Only a partial fix for #2660. Cancels #2679.
- Previously we were blocking Vite's built-in HMR handling and saying "Hey! `.astro` files should be handled entirely by us." This PR adds `.astro` HMR _on top of_ Vite's built-in handling so tools like Tailwind continue to work.
Tested manually. We don't have HMR tests.
Bug fix only
=> Fix HMR regression related to .astro updates

.changeset/wet-knives-raise.md, packages/astro/src/vite-plugin-astro/index.ts
- Fixes issue reported by @RafidMuhymin on Discord.
- HMR should never fire during `astro build`.
Manually
Bug fix
=> fix: disable HMR during build

packages/astro/package.json, yarn.lock
- In my CI work last night I accidentally merged a bad lockfile change that caused our tests to fail
- Specifically, upgrading vite from `.4` -> `.5` caused a regression being tracked here: #2678 
- This PR pins us to the last working version while the tests are fixed in #2678
=> fix failing tests on main

.github/workflows/ci.yml, .prettierignore, .prettierrc.json, scripts/smoke/index.js, scripts/smoke/sync.js, smoke/docs-main/package.json, yarn.lock
- For some reason, we're still getting a prettier format error in CI due to the astro prettier plugin
- ex: https://github.com/withastro/astro/runs/5379395471?check_suite_focus=true
- For the life of me I can't reproduce locally
- reverting the change to get main back to passing
- cc @antonyfaris @natemoo-re this can be added back in a separate PR when we figure out what's wrong
=> fix failing format command in CI

packages/astro/package.json, packages/astro/src/@types/astro.ts, packages/astro/src/core/config.ts, packages/astro/src/core/render/core.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/vite-plugin-astro/compile.ts, yarn.lock
- Improves Astro's head injection behavior per [RFC0007](https://github.com/withastro/rfcs/blob/main/proposals/0007-finalize-head-body.md)
- Relies on https://github.com/withastro/compiler/pull/315
Existing tests updated
N/A
=> Improve `head` injection behavior

.changeset/orange-coins-whisper.md, .changeset/short-rats-double.md, packages/astro/src/core/build/page-data.ts, packages/markdown/remark/src/remark-shiki.ts
While working on the docs repo, I chased down two performance issues related to docs build:
1. `ssrPreload` appears to be mostly serial work, so 142+ pages of of docs inside a `Promise.all()` all blocked each other from completing. This hung the build entirely when I switched the docs parser over to Shiki (see next).
2. Our Shiki markdown plugin and Code component are both unoptimized. After digging into why the build failed once moving over to Shiki, i tracked down the fact that `getHighlighter` is the most expensive part of shiki, and we were calling it once per page. Caching this for later returned improvement to previous Prism-levels.
@sarah11918 FYI both of these together were causing the failing builds you were seeing when we enabled that config change.
- Covered by existing tests, …
=> Improve build perf

.changeset/thirty-lobsters-ring.md, packages/astro/components/Code.astro, packages/markdown/remark/src/rehype-escape.ts, packages/markdown/remark/src/remark-prism.ts, packages/markdown/remark/src/remark-shiki.ts
Following [the roadmap](https://github.com/withastro/rfcs/discussions/1)
=> chore: changed `data-astro-raw` to `is:raw`

.changeset/fresh-ladybugs-think.md, packages/astro/src/vite-plugin-env/index.ts, packages/astro/test/astro-envs.test.js, packages/astro/test/lit-element.test.js
- Reworks the env plugin to do replacements rather than create a proxy.
- Vite removes all import.meta.env usage in the build, so we needed to do it that way.
- Still defers to vite:define when we can.
- Test updated.
- Lit test moved to the static build as well.
N/A
=> Move remaining tests to the static build

.github/workflows/ci.yml
- Allows CI to publish from [`next`](https://github.com/withastro/astro/pull/2705) branch, which is in `pre` mode.
N/A
N/A
=> Enable ci on `next`

.changeset/eighty-kiwis-brush.md, packages/renderers/renderer-svelte/index.js, packages/renderers/renderer-svelte/package.json, yarn.lock
- Updates `@astrojs/renderer-svelte` to use the experimental `useVitePreprocess` option.
- Removes the following annoying message every time a Svelte component is rendered:
```
[svelte-preprocess] PostCSS configuration was not passed or is invalid. 
If you expect to load it from a file make sure to install "postcss-load-config" and try again.
```
**BEFORE**
**AFTER**
Covered by Svelte's tests
Bug fix only
=> Remove `postcss-load-config` warning for Svelte users

packages/astro/src/core/config.ts
- Adds a warning when passing the flag, since that's no longer necessary.
Not tested.
Nope
=> Add a warning when passing the --experimental-static-build flag

.changeset/silver-foxes-bathe.md, packages/astro/src/core/render/core.ts
- Fixes https://github.com/withastro/astro/issues/2723
- Confirmed that this warning is impossible to happen during build
- left a comment explaining expected behavior, plus some hints on how to refactor
- N/A, just a warning removed
- N/A
=> remove a bad dev warning from static-build

.npmrc, .prettierignore, package.json, pnpm-lock.yaml
- Set `save-workspace-protocol=false` to prevent the examples to have the `workspace:` prefix. The dependencies will link anyways
- Removed volta key (which isn't very compatible with pnpm) and added `use-node-version` for those who uses `pnpm env`
=> chore: npmrc update

packages/astro/src/core/preview/index.ts, packages/astro/test/0-css.test.js
- Improves some preview logic for performance and bug fixes
- Fixes flakey CI tests where `close()` would resolve before the server actually closed
- Covered by CI
- N/A
=> improve preview reliability

packages/astro/src/core/build/fs.ts
- This uses code from the battle-tested rimraf library: https://github.com/isaacs/rimraf/blob/9219c937be159edbdf1efa961f2904e863c3ce2d/rimraf.js#L293-L296 in order to clear out the dist folder.
- Fixes the issue with Windows where some times in CI it would get an `EPERM` trying to stat a file.
Well, hopefully that error doesn't happen again.
N/A, bug fix.
=> Fixes windows test flakiness

.github/workflows/ci.yml
- Currently, PRs like #2740 don't run tests
- Because our test suite runs over all examples, we want example changes to run tests
=> run tests on example change

.changeset/sour-socks-enjoy.md, packages/astro/package.json, packages/astro/src/runtime/server/escape.ts, packages/astro/src/runtime/server/index.ts, packages/astro/test/astro-expr.test.js, packages/astro/test/fixtures/astro-expr/src/pages/escape.astro, pnpm-lock.yaml
- Escapes HTML inside of expressions by default.
- Remove `escapeHTML` util. The compiler is no longer using it.
Planned deprecation, no tests
Changelog points to docs
=> Escape HTML by default

.changeset/neat-snakes-know.md, packages/astro/src/cli/index.ts, packages/astro/src/core/logger.ts, packages/astro/src/core/messages.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/src/vite-plugin-astro/hmr.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/astro-doctype.test.js, packages/astro/test/cli.test.js, packages/astro/test/config.test.js, packages/astro/test/test-utils.js
- Updates Astro's logger to dedupe messages, appending `(x2)` to the end of duplicates
- Improves hmr logging with specific `update` or `reload` messages
- Updates `astro --help` output to match new logging style
- Updates `astro --version` output to match new logging style
**Old HMR**
**New HMR**
**New Help**
_On wide terminals_
_On tall terminals_
**New Version**
Tested manually + CLI tests updated
N/A
=> Improve logger (deduping, new help and version)

.changeset/clean-bottles-drive.md, packages/astro/components/Markdown.astro, packages/astro/src/@types/astro.ts, packages/astro/src/core/render/result.ts, packages/astro/test/fixtures/astro-slots/src/components/SlottedAPI.astro
- Improves `Astro.slots` API to include `has()` and `render()` utils.
```astro
---
let content;
if (Astro.slots.has("default")) {
content = await Astro.slots.render("default");
content = await doSomeCustomTransformation(content);
}
---
<Fragment set:html={content} />
```
TBD
TBD
=> Improve `Astro.slots` API

scripts/smoke/index.js
- `--experimental-static-build` is the default, don't need a second pass on smoke tests
CI
N/A
=> Remove second smoke test 

examples/blog/src/layouts/BlogPost.astro, examples/blog/src/pages/posts/index.md, examples/blog/src/styles/blog.css
The Prism syntax highlighter failed to render properly when Astro was
initialized with the blog template. This was because the Prism CSS
conflicted with the default blog template.
This change-set removes the Viewport Width from the `pre` transform as
this property conflicted with the prism CSS. This change-set also
includes Prism in the Blog Post layout and adds a small javascript
example to the sample post.
=> Support Prism in the blog template example

packages/astro/src/core/preview/index.ts
- Stops hitting the code-path inside of `sirv` that calls totalist, fixing the last (?!) windows CI issue.
- This means that preview will hit the file system for requests instead of caching them for long-term speed. I think this is acceptable and maybe even desired for the testing use-case, if I was using preview and making changes to `dist/` I think I'd expect those changes to be reflected on page refresh.
=> Fix flakey windows CI: eperm, totalist

packages/astro/src/runtime/server/index.ts, packages/astro/test/astro-directives.test.js, packages/astro/test/fixtures/astro-directives/package.json, packages/astro/test/fixtures/astro-directives/src/pages/define-vars.astro, pnpm-lock.yaml
- Does what it says on the tin.
- Closes #2753
Added `astro-directives` test
Bug fix only
=> fix(#2753): unescape `define:vars`

.changeset/stupid-pots-give.md, packages/astro/src/core/dev/index.ts, packages/astro/src/core/dev/util.ts, packages/astro/src/core/messages.ts
- Adds a warning on dev startup when Astro is in a pre-release mode.
Tested manually, we need snapshot tests to properly cover this
N/A but added Netlify redirect for https://astro.build/issues
=> CLI: add prerelease warning

packages/astro/src/@types/astro.ts
- Updates the docs added in #2755 
- Fixes some invalid JSDoc so that our docs site can continue to generate docs automatically. The fix is to use `@typeraw` if you want to document something that isn't valid JSDoc (like an inline arrow function, which JSDoc is too old to understand).
- Lets keep an eye on this for the future, we probably should add a note about reviewing these JSDoc in the PR for actual content, and could investigate doing JSDoc validation as a part of CI if this happens again.
=> update `buildOptions.sitemapFilter` jsdoc

.changeset/breezy-walls-guess.md, examples/minimal/astro.config.mjs, packages/astro/src/@types/astro.ts, packages/astro/src/cli/index.ts, packages/astro/src/core/config.ts, packages/astro/src/core/dev/index.ts, packages/astro/src/core/dev/util.ts, packages/astro/src/core/messages.ts, packages/astro/src/core/preview/index.ts, packages/astro/src/core/preview/util.ts, packages/astro/test/cli.test.js, packages/astro/test/config.test.js, packages/astro/test/fixtures/config-host/astro.config.mjs, packages/astro/test/fixtures/config-host/package.json, packages/astro/test/fixtures/config-path/config/my-config.mjs, packages/astro/test/test-utils.js, pnpm-lock.yaml
- Introduce new `--host` flag to mirror [Vite's config option](https://vitejs.dev/config/#server-host)
- When `--host` is absent, the network URL is _not_ exposed on your network
- When `--host` is present, the network URL is exposed at a default URL
- When `--host [custom host]` is present, the network URL is exposed at [custom host]
- (deprecated) When `--hostname [custom host]` is present, the network URL is also exposed at [custom host]
- Deprecate `--hostname` while maintaining functionality
- Added unit tests for current and legacy flags
- Added unit tests for `preview` command alongside `dev`
Updated configuration and CLI references on docs.
**[PR here!](https://github.com/withastro/docs/pull/207)**
=> Feat: expose server on local network with new --host flag

.changeset/strange-kings-add.md, packages/astro/src/core/render/dev/index.ts
- When we create the dynamic script tags for components, in dev we use Vite to get the file path for a module id like `astro/client/idle.js`. 
- On Windows this was generating file:// paths which of course do not work. Fix is to prepend `/@fs` which is a resolution that Vite understands.
Tested manually in the example apps only :/
N/A
=> Fix dev resolution of client modules on Windows

.changeset/nice-tables-applaud.md, packages/astro/src/core/render/core.ts
- Resolves #2627 
- Change `Object.create(...)` on `Astro.props` to object spread. See comment for reasoning
N/A
N/A
=> Fix: Astro.props missing properties

pnpm-lock.yaml
- #2771 made a change to the workspace but didn't re-run `pnpm install`, causing an out of date lockfile. This should fix that issue.
=> small lockfile update after #2771

.changeset/grumpy-dancers-smell.md, packages/astro/src/vite-plugin-astro/compile.ts
- Fixes #2781
- Tested manually with the Stackblitz project.
- Tried adding a Unit test but because of the monorepo the path to the internal astro file does *not* contain a space. So adding a fixture with a space in the folder name doesn't help.
- Would need better integration test infrastructure to do this.
N/A, bug fix.
=> Fix for allowing space in folder name

.changeset/modern-feet-lay.md, packages/astro/src/core/logger.ts
- Based on Node.js docs and [some stackoverflow research](https://stackoverflow.com/questions/34570452/node-js-stdout-clearline-and-cursorto-functions), readline is the modern way to use these APIs.
- Hopefully this blocks the new windows breaking test that we have
=> [windows:ci] handle CLI output in a cross-compat way

.changeset/quick-islands-call.md, examples/blog-multiple-authors/astro.config.mjs, examples/blog/astro.config.mjs, examples/component/demo/astro.config.mjs, examples/docs/astro.config.mjs, examples/env-vars/astro.config.mjs, examples/framework-alpine/astro.config.mjs, examples/framework-lit/astro.config.mjs, examples/framework-multiple/astro.config.mjs, examples/framework-preact/astro.config.mjs, examples/framework-react/astro.config.mjs, examples/framework-solid/astro.config.mjs, examples/framework-svelte/astro.config.mjs, examples/framework-vue/astro.config.mjs, examples/minimal/astro.config.mjs, examples/non-html-pages/astro.config.mjs, examples/portfolio/astro.config.mjs, examples/ssr/astro.config.mjs, examples/starter/astro.config.mjs, examples/subpath/astro.config.mjs, examples/with-markdown-plugins/astro.config.mjs, examples/with-markdown-shiki/astro.config.mjs, examples/with-markdown/astro.config.mjs, examples/with-nanostores/astro.config.mjs, examples/with-tailwindcss/astro.config.mjs, examples/with-vite-plugin-pwa/astro.config.mjs, packages/astro/config.d.ts, packages/astro/config.mjs, packages/astro/package.json
- Simplifies the authoring experience for `astro.config.mjs` files
- Adds a `defineConfig` export to `astro/config` that provides intellisense (even in JS files!)
- Pairs with https://github.com/withastro/astro.build/pull/46 to add https://astro.build/config shortlink to docs
- Cleans up `astro.config.mjs` files in examples
**Before**
```js
// Full Astro Configuration API Documentation:
// https://docs.astro.build/reference/configuration-reference
// @type-check enabled!
// VSCode and other TypeScript-enabled text editors will provide auto-completion,
// helpful tooltips, and warnings if your exported object is invalid.
// You can disable this by removing "@ts-check" and `@type` comments below.
// @ts-check
export default /** @type {import('astro').AstroUserConfig} */ ({
// Enable the …
```
=> Export defineConfig helper

.gitpod.Dockerfile, .gitpod.yml
Various Gitpod setup improvements:
* Install the latest `pnpm` in workspace
* Add Astro-build VSCode extension (from open-vsx)
* Run `pnpm run build` during prebuild (user doesn't have to wait)
* Automatically open preview browser when port 3000 is active
* Run `starter` demo when workspace starts
1. Open this PR in Gitpod - https://gitpod.io/#https://github.com/withastro/astro/pull/2789
1. `pnpm run build` should be ready by the time the workspace open (ran during prebuild)
1. Confirm you can see Astro's `starter` demo
1. Open `.astro` file, and confirm syntax highlighting works
* Open `blog` example from this PR in Gitpod -
https://gitpod.io/#ASTRO_NEW=blog/https://github.com/withastro/astro/pull/2789
* Open `starter` example from this PR in Gitpod - …
=> Gitpod setup improvements

.changeset/large-snakes-lay.md, packages/renderers/renderer-svelte/index.js
- Resolves #2273 
- Removed explicit `postcss: true` on Svelte renderer `preprocess(...)` call. We handle the PostCSS config mapping ourselves, so this opt-in flag is actually unnecessary!
Verified existing [postcss.test](https://github.com/withastro/astro/blob/main/packages/astro/test/postcss.test.js) still passes for Svelte.
N/A
=> fix: Svelte PostCSS config error

.changeset/spicy-chicken-pump.md, scripts/cmd/build.js
- Disables sourcemaps for built `astro` files, since they point to missing files.
- Hopefully fixes issue where Vite would yell at users.
Not possible to test in monorepo
N/A
=> Disable sourcemaps for build

.gitpod.yml, .gitpod/gitpod-setup.sh
When opening this Astro repo in Gitpod, an example project would open in the following logic:
* If Gitpod workspace was opened from a specific example project - that project would open
* If $ASTRO_NEW environment variable was set - open that project
* Otherwise, be default, open `starter` example project
* Go to https://github.com/shaal/astro/tree/gitpod--open-examples/examples
(that's a fork of Astro on my user account, with the branch that is the base of this PR. It will include the information of which directory Gitpod workspace was opened from
* Click on any example project.
* Either use Gitpod browser extension, or add `https://gitpod.io/#` before the full URL, for example -
https://gitpod.io/#https://github.com/shaal/astro/tree/gitpod--open-examples/examples/framework-lit
* Confirm …
=> Logic for opening example projects

packages/astro/test/fixtures/tailwindcss/package.json, packages/astro/test/fixtures/tailwindcss/postcss.config.js, packages/astro/test/fixtures/tailwindcss/src/components/Button.astro, packages/astro/test/fixtures/tailwindcss/src/pages/index.astro, packages/astro/test/fixtures/tailwindcss/src/styles/global.css, packages/astro/test/fixtures/tailwindcss/tailwind.config.js, packages/astro/test/tailwindcss.test.js, pnpm-lock.yaml
Follow-up to [#2791](https://github.com/withastro/astro/pull/2791) - adding test coverage now that Tailwind is working properly in `astro dev` 🎉 
Test coverage only, no feature changes
Adds tests to verify tailwind in `astro dev` and `astro build` to make sure classes are kept in HTML and styles are available in rendered CSS
Test coverage only, no docs updates
=> Adds tests for tailwind support in `dev` and `build`

.changeset/spotty-houses-stare.md, examples/ssr/astro.config.mjs, examples/ssr/src/pages/products/[id].astro, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/page-data.ts, packages/astro/src/core/render/core.ts, packages/astro/src/core/render/route-cache.ts, packages/astro/src/core/routing/validation.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/fixtures/ssr-dynamic/src/pages/[id].astro, packages/astro/test/ssr-dynamic.test.js, packages/astro/test/test-utils.js
- Dynamic routes in SSR should not have to implement getStaticPaths, since these routes are completely dynamic.
- This allows that.
- First SSR test (woot)
N/A
=> Allow SSR dynamic routes to not implement getStaticPaths

.changeset/silent-walls-tan.md, packages/astro/src/runtime/server/index.ts, packages/astro/test/fixtures/react-component/src/components/Hello.jsx, packages/astro/test/fixtures/react-component/src/pages/index.astro, packages/astro/test/fixtures/vue-component/src/components/Counter.vue, packages/astro/test/fixtures/vue-component/src/pages/index.astro, packages/astro/test/react-component.test.js, packages/astro/test/vue-component.test.js
Re-resolves an issue initially patched in https://github.com/withastro/astro/pull/846 but seemingly lost in the 0.21.0 mega-merge (https://github.com/withastro/astro/commit/d84bfe719a546ad855640338d5ed49ad3aa4ccb4) or somewhere along the way there.
This change makes the component render step account for all props, even if they don't affect the generated HTML, when deduplicating island mounts.
This resolves the following issues:
- Resolves https://github.com/withastro/astro/issues/2294
- Resolves https://github.com/withastro/astro/issues/2725
- Resolves https://github.com/withastro/astro/issues/2726
- Maybe https://github.com/withastro/astro/issues/2501
- Added props to `astroId` hash generation during component rendering.
Added tests for island mount deduplication to Vue and React …
=> Fix island deduplication ignoring props.

packages/webapi/run/build.js
- Ran into a problem when debugging with Antony.
- Fixes `pnpm run build` on Windows.
- CI doesn't catch this because the build only runs on Linux and the generated artifacts are shared with Windows.
Manually
N/A, bugfix
=> Fix webapi build script on windows

.changeset/moody-trees-allow.md, packages/astro/package.json, pnpm-lock.yaml
- Does what it says on the tin.
Caught during post-release testing
N/A
=> Fix missing `postcss-load-config` dependency

examples/blog-multiple-authors/package.json, examples/blog/package.json, examples/docs/package.json, examples/framework-lit/package.json, examples/framework-multiple/package.json, examples/framework-preact/package.json, examples/framework-react/package.json, examples/framework-solid/package.json, examples/framework-svelte/package.json, examples/framework-vue/package.json, examples/integrations-playground/package.json, examples/portfolio/package.json, examples/ssr/package.json, examples/subpath/package.json, examples/with-markdown/package.json, pnpm-lock.yaml
- Clean-up dependencies for `examples/`
- Adds required `peerDependencies` to each example
Hope this fixes StackBlitz
N/A
=> Clean-up example dependencies

.github/workflows/ci.yml, scripts/notify/index.js
- Fixes release bot notifications by generating `package.json#name` => CHANGELOG link dynamically.
- Also updates our changeset action to handle updating the lockfile after versioning. This has been failing since we switched to PNPM, but it's infrequent enough that it hasn't been a huge pain.
Nope, internal change only
=> Release bot

.changeset/tidy-jobs-beg.md, packages/integrations/lit/package.json, packages/integrations/partytown/package.json, packages/integrations/preact/package.json, packages/integrations/react/package.json, packages/integrations/sitemap/package.json, packages/integrations/solid/package.json, packages/integrations/svelte/package.json, packages/integrations/tailwind/package.json, packages/integrations/turbolinks/package.json, packages/integrations/vue/package.json
Adding keywords to the official integration packages
None, package metadata updates only
None for now.  Before the new integrations page is live, I'll be updating docs with details on what NPM data and keywords we pull down to populate the integrations page
Not part of this PR directly, but here's my current plan for supported keywords
| Integrations Category | NPM Keyword(s) |
| --- | --- |
| all (default) | `astro-component` |
| Accessibility | `a11y`, `accessibility` |
| Analytics | `analytics` |
| CMS | `cms`, `database` |
| CSS + UI | `css`, `ui`, `icons`, `renderer` (maybe framework keywords like `react`?) |
| E-commerce | `ecommerce`, `e-commerce` |
| performance | `performance`, `perf` |
| SEO | `seo` |
=> chore: integration keywords

.changeset/twenty-kiwis-tease.md, packages/astro/src/vite-plugin-markdown/index.ts
From LukeWilson in Discord:
> Hey everybody, testing out the the new tailwind integration in astro@next here, running into a problem. It works great for pages/index.astro, but for a pages/test.md, the base.css is not injected.
- Fixes that bug, and cleans up a few small edge cases where the Markdown and Astro page differ to bring Markdown back in line with Astro.
- Not covered by existing tests. Realizing that while integrations are covered by test suite, the specific hooks aren't really covered. I'll try to get to that by the end of the day but feel free to review this before then.
=> add injected scripts to markdown pages

.changeset/rude-panthers-tease.md, packages/integrations/tailwind/package.json, packages/integrations/tailwind/src/index.ts, pnpm-lock.yaml
- We currently ignore any `tailwind.config.js` in your project. This PR changes that!
- Includes integration option for a custom config path
- Includes integration option to opt-out of Astro's default config
=> Feat: support tailwind config files

.changeset/forty-badgers-relate.md, packages/astro/src/core/render/dev/index.ts
- Restore [our old caching strategy](https://github.com/withastro/astro/pull/2820/files#diff-61d8e7069b52b4ecd47d6e43210ba31015b3902bac58a8110790c15462ab0703L7-L22) for renderers instead of re-fetching from `ssrLoadModule`
- Restore [our old, not-so-fun URL constructor](https://github.com/withastro/astro/pull/2820/files#diff-3083ab6e9fa53c9fb3348d84342281e812a7d216f0cd5f947080dba2feabe855R78) for HMR scripts
Had to test by hand, manually copying the `dist` to a `node_modules` folder to avoid false positives. I encourage other devs to do the same, or install directly from this GitHub branch!
N/A
=> Fix: `isSelfAccepting`? More like `isBanishedToTheShadowRealm`

.changeset/modern-adults-dance.md, packages/astro/components/Markdown.astro, packages/astro/src/core/render/result.ts
- Previously, we created a `privateRenderMarkdownDoNotUse` on the `Astro` global.
- This property was enumerable and showed up when users did `console.log(Astro)`.
- This PR makes this value non-enumerable and also makes the name `__renderMarkdown`.
Hoping CI doesn't break 🤞🏻 
Internal change only
=> Ensure private API is not enumerable

packages/astro/src/core/build/scan-based-build.ts, packages/astro/src/core/config.ts, packages/astro/src/vite-plugin-build-html/index.ts
- I wanted to learn why we used `file://${X}` so I audited our usage. It turns out, most of our usage is valid because we're mapping from Rollup IDs (already normalized) to file paths. However, I found one usage that was incorrect based on my understanding of the Node.js docs: https://nodejs.org/api/url.html#urlfileurltopathurl
- Also, this is the second time I've been unsure if the "scan build" plugin was a part of legacy build or not, so I renamed it to make it more clear.
=> fix a bad file URL creation

package.json, packages/create-astro/package.json, packages/integrations/lit/package.json, packages/integrations/partytown/package.json, packages/integrations/preact/package.json, packages/integrations/react/package.json, packages/integrations/sitemap/package.json, packages/integrations/solid/package.json, packages/integrations/svelte/package.json, packages/integrations/tailwind/package.json, packages/integrations/turbolinks/package.json, packages/integrations/vue/package.json, packages/markdown/remark/package.json, packages/webapi/package.json, turbo.json
- Unblocks https://github.com/vitejs/vite-ecosystem-ci/pull/52
- `vite-ecosystem-ci` swaps in a different local version of `vite`, which can lead to TypeScript errors due to mismatching versions. To sidestep this, this PR introduces a `build:ci` command that skips `tsc`.
Test after merge
N/A
=> Add `build:ci` command which skips `tsc`

.changeset/wise-garlics-bathe.md, packages/astro/src/core/render/dev/index.ts, packages/integrations/preact/package.json, packages/integrations/preact/src/index.ts
- Add `.js` extensions to Preact entrypoints for consistency
- Switch to pulling server renderer IDs from the `urlToModuleMap` directly. This avoids any calls to `ensureEntryFromUrl`, which was causing the module to be loaded twice
- Remove the renderer cache. By pulling from the module map, we get the correct `?v=` version param everytime. This means... no need for a cache 😁 
- Tested on a local project using preact in isolation
- Tested on a locacl project with preact, react, and svelte together
- Cannot replicate in fixtures
N/A
=> Fix: `is self accepting` pt 2 module graph boogaloo

.changeset/silly-sloths-hammer.md, packages/markdown/remark/src/remark-shiki.ts
- #2772 didn't seem to fully fix the perf issue uncovered in https://github.com/rebelchris/ddt-v2. I'm not sure if this was a bug in the original fix, or a new regression that rendered the fix moot. Either way, this has been tested with the latest version of Astro + ddt and verified to fix the shiki perf issue.
- cc @bholmesdev 
- Tested on ddt
- N/A
=> Fix shiki perf issue pt. 2

.changeset/rude-trainers-repeat.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/page-data.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/util.ts
- Log setup steps as they occur with `ms` completed: initialization, entrypoint crawling, SSR bundling
- Add structured heading for "building resources" step
- Change Vite client build from "error" logging to "info" logging - currently SvelteKit's setup
- Add structured heading for "generating static routes" step
- log entry file
- log all generated paths. Helpful when debugging `getStaticPaths` output
- include different icons for pages (`</>`) vs. endpoints (`{-}`)
- out of scope: logging for generated SSR output. Planning a separate PR to pretty-print the generated `manifest.json`.
See for yourself!
https://user-images.githubusercontent.com/51384119/159578039-6752a798-4e04-4fcc-9527-013eba2c941b.mov
N/A
=> Feat: improve production build logging

.changeset/cyan-pigs-ring.md, examples/with-tailwindcss/src/pages/index.astro, examples/with-tailwindcss/src/pages/markdown-page.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/src/vite-plugin-scripts/index.ts, packages/astro/test/fixtures/tailwindcss/src/pages/index.astro, packages/astro/test/fixtures/tailwindcss/src/pages/markdown-page.md, packages/astro/test/fixtures/tailwindcss/src/styles/global.css, packages/astro/test/tailwindcss.test.js
- Markdown script injection was broken in a couple of small ways.
- This PR hardens our script injection to use TS types better.
- This PR also adds a Markdown example page to the with-tailwindcss example project
- Last, we add a test to the test suite and make some small improvements to the tailwind test suite.
- Manually confirmed and tests added.
- N/A
=> fix markdown page script injection

.github/ISSUE_TEMPLATE/---01-bug-report.yml, .github/PULL_REQUEST_TEMPLATE.md
- Bug report: Improve docs around minimal reproduction item, stress importance.
- Bug report: Add a "participation" checkbox. This is something that seemed to really make a difference in Snowpack, that I'd love to bring back to this repo.
- PR template: Add an entry to remind someone to create a changeset, since we keep having this problem :)
=> [chore] improve some github templates

packages/astro/src/vite-plugin-env/index.ts, packages/astro/test/astro-envs.test.js, packages/astro/test/fixtures/astro-envs/src/pages/destructured.astro
- Fixes #2846 
- We had a regression in private env variable support during SSR, this PR fixes it.
- The regression happened with destructured `import.meta.env` references. The fix was to ensure that `import.meta.env` is replaced with an `Object.assign(import.meta.env, privateVars)` call.
- For security, only private env variables that are referenced in the file will be injected statically.
Example is working again
=> fix(#2846): handle destructured private env usage during SSR

.changeset/blue-rocks-smoke.md, packages/astro/package.json, packages/astro/src/@types/astro.ts, packages/astro/src/core/app/types.ts, packages/astro/src/core/build/common.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/core/dev/index.ts, packages/astro/src/core/logger.ts, packages/astro/src/integrations/index.ts, packages/integrations/netlify/package.json, packages/integrations/netlify/readme.md, packages/integrations/netlify/src/index.ts, packages/integrations/netlify/src/integration-functions.ts, packages/integrations/netlify/src/netlify-functions.ts, packages/integrations/netlify/tsconfig.json, pnpm-lock.yaml
- Adds the Netlify adapter that works with Netlify Functions.
- Allows integrations to configure the folders where client/server code is written to.
Not testing adapters, yet.
- This will be part of https://github.com/withastro/docs/pull/255
- The readme has docs
=> Netlify adapter

packages/integrations/lit/README.md, packages/integrations/preact/README.md, packages/integrations/react/README.md, packages/integrations/solid/README.md, packages/integrations/svelte/README.md, packages/integrations/vue/README.md
- Add READMEs to our component framework integrations:
- `@astrojs/react`
- `@astrojs/preact`
- `@astrojs/solid`
- `@astrojs/vue`
- `@astrojs/svelte`
- `@astrojs/lit`
- Includes experimental `astro add` and manual installation instructions
- Adds "getting started" section to link directly to UI framework docs
- Includes lit element specific instructions from renderer docs
N/A
That's what I'm doing boss!
=> Docs: READMEs for component framework integrations

.changeset/swift-pets-lick.md, packages/integrations/partytown/README.md, packages/integrations/sitemap/README.md, packages/integrations/tailwind/README.md, packages/integrations/turbolinks/README.md
- Add remaining integration READMEs
- `@astrojs/partytown`
- `@astrojs/tailwind`
- `@astrojs/turbolinks`
- `@astrojs/sitemap`
=> Docs: remaining integration READMEs

.changeset/polite-mirrors-fix.md, packages/integrations/solid/README.md
The package name was listed as `@astrojs/solid` when it's actually `@astrojs/solid-js`
Just documentation fix
This was a docs change
=> Correct package name in solid intergration readme

.changeset/hip-vans-return.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/config.ts, packages/astro/test/config-validate.test.js
- Adds the flag
- Tests updated.
- Will revert the docs to keep this CLI flag reference, once this PR is merged
=> add "--experimental-integrations" flag

.changeset/shaggy-bulldogs-beam.md, examples/with-tailwindcss/tailwind.config.cjs, packages/astro/src/core/add/consts.ts
- Tailwind example has an empty `content` in its `tailwind.config.js`
- This causes it to fail to find any src files. (Example: https://stackblitz.com/edit/github-nkk41y?file=tailwind.config.cjs&on=stackblitz)
- I think we want to merge our default config with the user's config to prevent this bug? That's what Nuxt does, but I'm not sure. Regardless, that can be left for another PR :)
=> small tailwind example config fix

.changeset/tiny-snails-grab.md, packages/astro/src/core/build/internal.ts, packages/astro/src/core/build/scan-based-build.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/vite-plugin-pages.ts, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/test/fixtures/page-level-styles/src/layouts/Base.astro, packages/astro/test/fixtures/page-level-styles/src/layouts/Styled.astro, packages/astro/test/fixtures/page-level-styles/src/pages/blog.astro, packages/astro/test/fixtures/page-level-styles/src/pages/index.astro, packages/astro/test/fixtures/page-level-styles/src/styles/main.css, packages/astro/test/page-level-styles.test.js
- Since we are bundling into a single file for the build now, we need to do CSS slightly differently.
- This changes the static build so that at the end of the build it walks the module graph and collects the CSS for each page and builds a bundle based on that, rather than relying on Rollup's chunking; there is only 1 chunk so that way can't work now.
- Fixes #2908
Test added
N/A, bug fix.
=> Prevent CSS from being added to pages not using it

packages/astro/src/core/config.ts
Corrected a package name (from `@astrojs/solid` to `@astrojs/solid-js`) in the error message which is shown if the `renderers` array is used.
The change was tested locally and it's working.
=> Corrected package name in warning message

.changeset/real-starfishes-turn.md, packages/astro/src/@types/astro.ts
As per [docs](https://docs.astro.build/en/reference/integrations-reference/#combining-plugins), an integration can return an array of `AstroIntegration` objects to support bundling a collection of integrations as a preset. This change reflects that usage in the typing for the user config object.
I think this is just fixing the existing expected type, so I haven’t added any tests.
I left the JSDoc `@type` tag as is (`AstroIntegration[]`) as the technically correct type (`Array<AstroIntegration | AstroIntegration[]>`) doesn’t feel like it adds a huge amount to user comprehension.
=> Fix typing of `integrations` array in user config

.changeset/stale-walls-whisper.md, examples/portfolio/astro.config.mjs
Update import in the `astro.config.mjs` of the Portfolio starter to address the error raised in #2924 
Closes #2924 
Made the same change on the `bug-fix` branch branch of the original repro and the problem was solved [repro here](https://github.com/memarino92/astro-test/tree/bug-fix).
No docs change - already covered in the [Getting Started](https://docs.astro.build/en/getting-started/) section of Astro docs
=> [fix] 2924 Update import in astro config of portfolio starter

examples/ssr/src/api.ts, examples/ssr/src/components/Header.astro, examples/ssr/src/pages/cart.astro, examples/ssr/src/pages/index.astro, examples/ssr/src/pages/products/[id].astro
- Updates to the SSR example so that we don't have to hardcode the origin, instead it comes from the `Astro.request` object.
N/A, just an example update.
N/A
=> Make the SSR example infer the origin

.changeset/odd-swans-walk.md, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/fixtures/ssr-api-route/src/pages/food.json.js, packages/astro/test/ssr-api-route.test.js
- Fixes `POST` (and other non-GET) routes in the dev server with Node 14.
Test added
N/A, bug fix
=> Fixes API route compat with Node 14

packages/astro/src/@types/astro.ts
- small change to remove `@docs` from this config
- the docs site uses this to auto-generate the config reference
- safe to add when we're ready to document it on docs.astro.build
cc @matthewp
=> remove docs jsdoc tag from adapter

examples/blog-multiple-authors/.gitignore, examples/blog/.gitignore, examples/component/.gitignore, examples/docs/.gitignore, examples/env-vars/.gitignore, examples/framework-alpine/.gitignore, examples/framework-lit/.gitignore, examples/framework-multiple/.gitignore, examples/framework-preact/.gitignore, examples/framework-react/.gitignore, examples/framework-solid/.gitignore, examples/framework-svelte/.gitignore, examples/framework-vue/.gitignore, examples/integrations-playground/.gitignore, examples/minimal/.gitignore, examples/non-html-pages/.gitignore, examples/portfolio/.gitignore, examples/starter/.gitignore, examples/subpath/.gitignore, examples/with-markdown-plugins/.gitignore, examples/with-markdown-shiki/.gitignore, examples/with-markdown/.gitignore, examples/with-nanostores/.gitignore, examples/with-tailwindcss/.gitignore, examples/with-vite-plugin-pwa/.gitignore
This change adds `pnpm-debug.log*` to `.gitignore` following with the `npm-debug.log*` that is already in the `.gitignore`.
I got annoyed that I had to add this section to the .gitignore so I thought why not create a PR for it.
No, docs necessary
=> chore(.gitignore): remove pnpm error logs from git

.changeset/chatty-cows-attack.md, packages/astro/src/runtime/server/index.ts, packages/astro/test/astro-response.test.js, packages/astro/test/fixtures/astro-response/src/components/not-found.astro, packages/astro/test/fixtures/astro-response/src/pages/not-found-component.astro, packages/astro/test/fixtures/astro-response/src/pages/not-found.astro
- Allows components to return a `Response`, for redirects, etc.
- This is meant so that Layout components can act as gates for auth flows, etc.
- Tests added
N/A
=> Allow components to return a Response

.changeset/ninety-jars-swim.md, packages/astro/test/fixtures/react-component/package.json, packages/integrations/react/client-v17.js, packages/integrations/react/client.js, packages/integrations/react/package.json, packages/integrations/react/server-v17.js, packages/integrations/react/src/index.ts, packages/integrations/react/tsconfig.json, pnpm-lock.yaml
- Adds support for v18 to `@astrojs/react`
- React v17 remains the same
- Monorepo stays on v17 to confirm that this doesn't break
- Follow up PR to update Monorepo to v18
- Tested manually
- I believe this is impossible to test in our monorepo, due to how we use peer deps. In the monorepo, the peer dep is hard-coded do whatever the actual dep is of the integration. Because its a symlink, it can't follow the import the way it would in a normal project. This shouldn't impact all monorepos, just ours where the integration source code itself is literally the thing being mono-repo'd.
- N/A
=> Add support for React 18 in @astrojs/react

.changeset/swift-trainers-suffer.md, packages/astro/src/core/build/static-build.ts, packages/astro/test/fixtures/ssr-request/public/cars.json, packages/astro/test/fixtures/ssr-request/src/pages/request.astro, packages/astro/test/ssr-request.test.js
- Fixes bug that @JuanM04 noticed in another PR.
- Adds test for the bug
- Also adds test to verify that Astro.request is correct in SSR.
N/A
=> SSR - copy public folder when there is no client JS

.changeset/light-apricots-sort.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/render/result.ts, packages/astro/test/astro-slots.test.js, packages/astro/test/fixtures/astro-slots/src/components/Render.astro, packages/astro/test/fixtures/astro-slots/src/components/RenderArgs.astro, packages/astro/test/fixtures/astro-slots/src/components/RenderFn.astro, packages/astro/test/fixtures/astro-slots/src/pages/slottedapi-render.astro
- Previously, `Astro.slots.render("default")` could only render Astro components.
- Now, `Astro.slots.render("default", [...args])` can render a function child, passing `args` into the function correctly.
- This allows users to build more ergonomic utility components like `For`.
```astro
<For each={items}>
{(item) => <li>{item}</li>}
</For>
```
Test suite added for `Astro.slots.render('default')` and `Astro.slots.render('default', [args])`
TBD
=> Add function-based slot support to `Astro.slots.render()`

.changeset/tasty-zoos-wink.md, packages/integrations/tailwind/README.md, packages/integrations/tailwind/src/index.ts
Fixes [#2950](https://github.com/withastro/astro/issues/2950) - this makes the `base.css` styles in the Tailwind integration opt-out
**Why?** The [`@layer`](https://tailwindcss.com/docs/functions-and-directives#layer) directive is useful for customizing Tailwind's base styles, but `@layer` must be run after `@tailwind` directives. This also allows users to skip built-in tailwind layers in case the project doesn't need `@tailwind components` or `@tailwind utilities`
Tested locally against the `with-tailwindcss` starter
Integration README updated to describe the new config option and when you may want to opt-out
=> Allows projects to opt out of the base Tailwind styles

packages/astro/src/core/config.ts
These CLI defaults where overriding whatever was inside astro.config.mjs even when no flag were provided! Now, passing a flag overrides the config but passing no flag does nothing.
=> fix: prevent CLI defaults from overriding astro.config.mjs

packages/astro/test/ssr-adapter-build-config.test.js, packages/astro/test/ssr-api-route.test.js
- No code changes, just tests added
- Tests that adapters (or any integrations really) can change `buildConfig.client` and `buildConfig.server` to specify where files are put.
N/A, test only
=> Add tests for using buildConfig

.changeset/plenty-suits-happen.md, packages/astro/src/@types/astro.ts
Fixes [#2972](https://github.com/withastro/astro/issues/2972)
Docs fix only - `config.publicDir` and `config.outDir` were showing the wrong default values
None (docs and typedef fix only)
None, this will be picked up by the doc's `docgen` script
=> Fixing the new config defaults (docs only)

.changeset/silent-cows-shave.md, packages/markdown/remark/src/index.ts
I've recently encountered this error when using `mode: 'md'`:
```
error   Transform failed with 1 error:
/home/juanm04/dev/projects/portfolio/src/pages/docs/wsl-memory.md:34:164: ERROR: Expected "}" but found "distro"
File:
/home/juanm04/dev/projects/portfolio/src/pages/docs/wsl-memory.md
Code:
33 | Therefore, in your situation, all you need to include in your file is ⤵
35 | ```ini:.wslconfig
36 | [wsl2]
37 | memory=1GB
```
It turned out, `rehypeEscape` was only being executed when mode was equal to `mdx`, so I've made it so it always get executed. (Plus, I've made some formatting so make it more clear what is being used with MDX and what don't)
=> fix(markdown): escape when mode == 'md'

.changeset/soft-dolphins-join.md, packages/astro/astro.js
Prevent CLI from hanging. You can see it happening in [this Netlify deploy](https://app.netlify.com/sites/astro-docs-2/deploys/6249c14f8f70250008af2c0f): `astro build` is successful but the process never terminates.
=> fix(cli): prevent CLI from hanging

.changeset/flat-coats-crash.md, packages/astro/src/runtime/server/index.ts
- Was building something, found an edge case where slotted children would be rendered before they should be.
- This will unblock utility `function` children for Astro components.
Not really possible to test
Bug fix only
=> Fix edge case with slotted children

packages/astro/astro-jsx.d.ts, packages/astro/src/@types/astro.ts
Followup to https://github.com/withastro/astro/pull/2711, this time adding the types definition for the TSX generated by the language-server
The JSX definitions are namespaced under astroHTML which mean that, unlike the React definitions, they shouldn't interfere with other JSX-based files (unless you have the wrong `tsconfig` settings, that is)
This bring the same advantages adding the `end.d.ts` had, which are that definitions are now based on internal types. If we add a new client directive for instance, adding it to our types will also add it to the JSX definition, which mean that users get new features (at least part of them) without needing a new version of the language-server
A PR in the language-tools will follow this to add support for it
No docs needed
=> Add JSX definitions to astro package for language-tools consumption

package.json
I think that this will fix the npm publish to use `latest`, but maybe only 95% sure. Only one way to find out! :)
=> keep publishing to latest, even in pre mode

.changeset/big-yaks-invite.md, packages/astro/src/cli/index.ts, packages/astro/src/core/preview/index.ts
Fixes a bug that was preventing the `astro preview` server from staying alive
Tested locally
Bug fix only
=> fix(#2981): keeps `astro preview` server alive

.changeset/sweet-ways-tan.md, packages/integrations/vercel/src/index.ts
Fixed build output directory and clean-up
=> fix: @astrojs/vercel bug fixes

.changeset/ten-rice-unite.md, packages/integrations/solid/client.js, packages/renderers/renderer-solid/client.js
Updated Solid's client renderer and integration to fix issue with nested hydration, like you'd find in the recursive comments in Hackernews.
Previous behavior recreated static children as DOM elements and inserted them during hydration. This reset hydration state messing with Solid's hydration when nested.
Solid treats any `undefined` value inserted as skip during hydration assuming client will match server eventually, so I just removed the children and it will skip hydration of static children.
This also appears to improve the Solid integration's hydration performance by about 200%.
=> fix: Nested hydration with Solid

.changeset/empty-pens-talk.md, packages/astro/src/core/build/index.ts, packages/astro/src/integrations/index.ts, packages/integrations/partytown/src/index.ts, packages/integrations/vercel/src/index.ts
In the case of the Vercel integration, the static files are outputted to `.output/static/`, whereas, for example, the Sitemap integration was saving its output inside `.output/`. This PR fixes that case
=> fix(integrations): `astro:build:done` dir now matches SSR client output

.changeset/dirty-trains-yawn.md, packages/astro/src/core/config.ts, packages/astro/test/config.test.js, packages/astro/test/fixtures/astro-basic/my-config.mjs, packages/astro/test/test-utils.js
- Fixes #2987.
- Our `--config` flag wasn't handling relative values properly.
- Now it is
Tests updated to ensure coverage
Bug fix only
=> fix(#2987): relative config handling with `--config` flag

.changeset/forty-boats-remain.md, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/integrations/vercel/src/index.ts, packages/integrations/vercel/src/server-entrypoint.ts
- Adapters were not able to export `default` and some need to.
- A workaround was added for Vercel where `_default` became the default export.
- This was not obvious and not documented, so better just to allow a default export. This fixes that.
- Test adapter exports a default which exposed the bug.
N/A, already covered by the adapter docs (just fixes a bug).
=> Allow an adapter to export default

.changeset/dull-bobcats-clean.md, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/test/astro-css-bundling-import.test.js, packages/astro/test/fixtures/astro-css-bundling-import/src/layouts/InlineLayout.astro, packages/astro/test/fixtures/astro-css-bundling-import/src/pages/page-3.astro, packages/astro/test/fixtures/astro-css-bundling-import/src/styles/page-three.css
Updating `astro build` to match the behavior in `astro dev` - any CSS files imported as `?raw` or `?url` will be skipped when linking to final bundled assets
This matches Vite [behavior](https://vitejs.dev/guide/assets.html#explicit-url-imports) where these imports aren't included in the internal asset graph(s) or in `assetsInclude`
Added a test to verify a page that uses both normal ESM imports, `?raw`, and `?url` imports
Related docs [PR #326](https://github.com/withastro/docs/pull/326)
=> Exclude any ?raw or ?url css imports when adding asset links

.changeset/calm-dolphins-remain.md, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/fixtures/ssr-api-route/src/pages/login.js, packages/astro/test/ssr-api-route.test.js
- Fixes #3024
- Turns out the fetch standard doesn't provide a way to get multiple of the same header. Even though you can `.append()` them, you can't read out each value.
- Luckily node-fetch has a workaround, which is being used here.
Test added
N/A, bug fix.
=> Fixes adding set-cookie headers multiple times

.changeset/shaggy-pans-buy.md, packages/astro/env.d.ts, packages/astro/src/@types/astro.ts
This updates all of our JSDoc comments on public-facing API in Astro files (so, Astro global, its methods etc) in order to improve the hover info we provide to users in the editor
It is not necessary to document client directives and other Astro-attributes as the language-server provides its own description for those using another mechanism (because those kinda lives in "HTML" land)
Example:
**Before** 
**After**
I am not the best writer in the world regarding those short snippets so really, suggestions are very much welcome!
I guess, this is technically docs itself..
=> Update JSDoc comments that get shown in editor

.changeset/breezy-days-remember.md, package.json, packages/astro/package.json, packages/integrations/vercel/package.json, pnpm-lock.yaml, scripts/package.json
Update esbuild to its latest version (`0.14.25` --> `^0.14.32`). Also, our lockfile updates will install patch version automatically
=> chore: updated esbuild

.changeset/pre.json, package.json, patches/@changesets+assemble-release-plan+5.1.2.patch, pnpm-lock.yaml
- We're doing something odd that changesets isn't meant to do: 1 package (astro) is beta, while the rest are normal, and all packages are released to `latest`, with none released to `@beta` or `@next` on npm. This break a million different assumptions about how changeset thinks the world works.
- Most frustrating: a 3-line astro-specific change to the changeset codebase gets us the behavior that we want, but its too deep in the codebase for them to expose directly to us. 
- I've been chatting with the team, and I think this solution is the best one forward, given the 2-month window that we find ourselves in. 
- For extra background, you can see the full convo here: https://github.com/changesets/changesets/issues/786
- Introduces [`patch-package`](https://www.npmjs.com/package/patch-package …
=> Fix our incomplete beta release process

.changeset/metal-grapes-tickle.md, packages/astro/src/core/build/static-build.ts, packages/astro/test/fixtures/static build SSR/astro.config.mjs, packages/astro/test/fixtures/static build SSR/package.json, packages/astro/test/fixtures/static build SSR/public/asset.txt, packages/astro/test/fixtures/static build SSR/public/nested/asset2.txt, packages/astro/test/static-build.test.js, pnpm-lock.yaml
- When SSR is enabled and it's a static build the copying of public files is broken with sub folders
- - fix is to create subfolders as required
Test added to static -build.test.js
none
=> Fix SSR static build public file copying. fixes #3016

.changeset/afraid-mugs-call.md, packages/astro/src/@types/astro.ts, packages/astro/src/cli/index.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/astro-global.test.js, packages/astro/test/fixtures/astro-global/src/pages/index.astro
- Fixes the issue identified in #3057
- Added.
- N/A
=> fix ssr url search params bug

.changeset/sharp-moose-perform.md, packages/integrations/netlify/src/netlify-functions.ts, packages/integrations/netlify/test/cookies.test.js, packages/integrations/netlify/test/fixtures/cookies/src/pages/index.astro, packages/integrations/netlify/test/fixtures/cookies/src/pages/login.js
- Fixes #3024
Test added
N/A, bug fix
=> Allow setting multiple cookies in Netlify adapter

.changeset/clean-cherries-bow.md, packages/astro/src/runtime/server/index.ts
- resolves #3047
- resolves #3086
- `metadata` was no longer exposed to our SSR `renderToStaticMarkup` functions. This restores the object for our React integration to use
N/A
N/A
=> Fix: React hydration failure

.changeset/chilly-terms-smoke.md, .changeset/lazy-kangaroos-rush.md, packages/astro/src/runtime/server/index.ts
- Add support for the `del` export, since `export function delete() {}` is invalid JS (`delete` is a reserved word).
- Add support for a fallback `export function all() {}` handler that handles all requests (if a specific method export was not given).
- See user feedback in https://discord.com/channels/830184174198718474/852168748353060875/963124824111198238
- N/A
- Docs needed, I think a PR already exists to add. I'll check that out later today.
=> Improve API handler export naming

.changeset/neat-oranges-tan.md, packages/astro/src/core/config.ts, packages/astro/src/runtime/server/index.ts, packages/astro/test/custom-elements.test.js, packages/astro/test/fixtures/custom-elements/astro.config.mjs, packages/astro/test/fixtures/custom-elements/my-component-lib/index.js, packages/astro/test/fixtures/custom-elements/my-component-lib/server.js, packages/webapi/src/lib/CustomElementRegistry.ts, packages/webapi/src/lib/Element.ts
- Closes #3068
- Prevents rendering "undefined" as a child of custom elements
- Re-enables the custom elements tests, which were disabled during the integrations migration.
- Tests re-enabled / migrated
- New test for this case
N/A, bug fix
=> Re-enable custom element test and fix "undefined" child

.changeset/tame-lamps-roll.md, packages/astro/test/fixtures/tailwindcss/src/pages/index.astro, packages/astro/test/fixtures/tailwindcss/tailwind.config.js, packages/astro/test/tailwindcss.test.js, packages/integrations/tailwind/README.md, packages/integrations/tailwind/src/index.ts
Closes #3043
`@astrojs/tailwind` was defaulting presets to `[]` which actually tells Tailwind to [remove the default presets](https://tailwindcss.com/docs/presets#disabling-the-default-configuration) of colors, sizes, etc.
This change removes the `applyAstroConfigPreset` option, instead of our own custom flag users can disable the built-in preset in the Tailwind config as usual by including `presets: []` themselves
- Tailwind test updated to make sure custom colors are included in the build
- Tested locally with astro.build, which has a pretty extensive [tailwind.config.js](https://github.com/withastro/astro.build/blob/main/tailwind.config.js)
Updated the integration README (no docs site updates needed)
---
Forcing `presets: undefined` in our default Tailwind config makes sure that the …
=> Fixing bug that could lose Tailwind's default presets

packages/integrations/deno/package.json, packages/integrations/netlify/package.json, packages/integrations/node/package.json, packages/integrations/vercel/package.json
- Adds required `build:ci` command that Vite Ecosystem CI needs
Will see once merged
N/A
=> Add `build:ci` script to integrations

.changeset/forty-goats-warn.md, packages/astro/src/core/build/internal.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/test/astro-client-only.test.js, packages/astro/test/fixtures/astro-client-only/astro.config.mjs, packages/astro/test/fixtures/astro-client-only/package.json, packages/astro/test/fixtures/astro-client-only/src/components/JSXComponent.jsx, packages/astro/test/fixtures/astro-client-only/src/components/PersistentCounter.svelte, packages/astro/test/fixtures/astro-client-only/src/components/global.css, packages/astro/test/fixtures/astro-client-only/src/pages/index.astro, pnpm-lock.yaml
- Adds tracking for client:only usage and adds their CSS to pages they belong to
- Thanks to @bholmesdev for pairing with me on this!
- Fixes #2966
- Fixes #2225
- Added a test case to our css:only test
N/A, bug fix
=> Add client:only CSS to their pages

.changeset/brave-planes-punch.md, packages/integrations/deno/src/index.ts, packages/integrations/deno/src/server.ts, packages/integrations/deno/test/basics.test.js, packages/integrations/deno/test/deps.js, packages/integrations/deno/test/fixtures/basics/src/pages/index.astro, packages/integrations/deno/test/helpers.js
- Fixes #3117
- Test added, confirms can load a CSS asset
N/A, bug fix.
=> Handle static file serving in Deno adapter's start command

.changeset/mighty-teachers-fail.md, examples/docs/package.json, pnpm-lock.yaml
The docs example template includes Algolia’s Docsearch components to provide a search bar but this doesn’t support React 18 yet, so will error when dependencies are being installed. (See [Discord support thread](https://discord.com/channels/830184174198718474/965413318678425600).)
This PR rolls back the version of React used for that example to 17.
Bug fix only.
=> Roll back to React 17 in docs template

.changeset/eleven-guests-rhyme.md, packages/astro/components/Code.astro, packages/astro/components/Shiki.js
Fixes #3110 
This updates the built-in `<Code>` component to reuse Shiki highlighters based on the `theme` and `lang` properties
Tested locally against the [astro-imagetools docs](https://github.com/RafidMuhymin/astro-imagetools/) site
**Before**
`Error: fail to memory allocation`
**After**
N/A
=> Perf: reuse Shiki highlighters per theme/lang

.changeset/tidy-poems-occur.md, packages/astro/src/core/render/dev/css.ts, packages/astro/src/core/render/dev/index.ts, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/astro-markdown-css.js, packages/astro/test/fixtures/astro-markdown-css/astro.config.mjs, packages/astro/test/fixtures/astro-markdown-css/package.json, packages/astro/test/fixtures/astro-markdown-css/src/components/Visual.astro, packages/astro/test/fixtures/astro-markdown-css/src/markdown/article.md, packages/astro/test/fixtures/astro-markdown-css/src/markdown/article2.md, packages/astro/test/fixtures/astro-markdown-css/src/pages/index.astro, pnpm-lock.yaml
- resolves #3054 
- Instead of applying a path prefix on imported markdown files, apply a flag to the suffix. This allows Vite to resolve the markdown file in the module graph, so we can parse imported styles on our end
TODO
N/A
=> Fix: component styles within imported markdown files

.changeset/soft-fishes-switch.md, packages/integrations/vercel/README.md, packages/integrations/vercel/src/index.ts
Added warning when `ENABLE_FILE_SYSTEM_API=1` is missing. Vercel doesn't fail when it isn't set — the deployment just throws a 404
=> feat(vercel): added warning when `ENABLE_FILE_SYSTEM_API=1` is missing

.changeset/violet-cups-glow.md, packages/astro/test/astro-markdown-shiki.test.js, packages/astro/test/fixtures/astro-markdown-shiki/normal/src/pages/index.md, packages/markdown/remark/src/remark-shiki.ts
- In a live-stream, Theo tried to copy a code snippet from the docs site SSR example, and then had to remove the diff symbols after pasting
- We can handle this automatically by giving these symbols "user-select: none"
- Added test.
- N/A
=> handle diff symbols in shiki

.changeset/small-radios-whisper.md, packages/integrations/netlify/src/integration-edge-functions.ts
- Puts the manifest file in `.netlify/edge-functions/manifest.json`
- Fixes dynamic routes manifest output.
- Use `entry.js` (no mjs) as the function root, as .mjs isn't picked up.
Verified manually as this requires deployment.
N/A, bug fix
=> Adjustments for Netlify Edge Functions

.changeset/eight-pumas-repeat.md, packages/integrations/solid/client.js, packages/integrations/solid/server.js
- Makes the SolidJS pre-hydration code actually run before hydration.
- Before this fix, we were inlining a <script> block after each component, no matter if it was supposed to get hydrated or not.
- Fixes #3132.
Tested locally on Windows 10 in dev mode, build, and SSR using Netlify adapter.
This is not a visible change, just a code fix/refactor.
=> Fix location of SolidJS pre-hydration code

.changeset/purple-timers-speak.md, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/jsx-expressions.md, packages/markdown/remark/package.json, packages/markdown/remark/src/remark-expressions.ts, pnpm-lock.yaml
- Resolves #2886 
- Removes the `micromark-extension-mdx-expression` dependency. This was removing the curlies `{}` from our JSX expressions, causing some variables to remain unparsed by the Astro parser.
- added JSX expressions test to `packages/astro/test/astro-markdown.test.js`
N/A
=> Fix: markdown JSX expression inconsistencies

packages/astro/test/fixtures/lit-element/src/components/my-element.js, packages/astro/test/ssr-lit.test.js
- No changes, this already worked
- Closes #3126
- Added a test to verify that Lit works in SSR, and it does.
N/A
=> Add test to verify Lit works in SSR

.changeset/cyan-dots-admire.md, packages/astro/src/runtime/client/hmr.ts, packages/astro/src/vite-plugin-astro/hmr.ts, packages/astro/src/vite-plugin-astro/index.ts
- Removes our fully-custom HMR and leans on the built-in `vite:beforeUpdate` event instead.
- Fixes SSR-only HMR by tracking file dependencies in `vite-plugin-astro`
- Fixes edge case with Astro/Svelte styles triggering a full reload because duplicate URLs were present and one was not being picked up as self-accepting.
Still looking into HMR tests
Bugfixes only
=> Improved HMR

.changeset/old-plants-glow.md, packages/astro/src/core/build/vite-plugin-pages.ts, packages/astro/test/ssr-lit.test.js, packages/integrations/lit/src/index.ts
- Fixes #3126
- Makes it so that renderers are imported first, since framework components depend on them implicitly.
- Makes it so that the lit integration sets `lit` to be noExternal, forcing it into the bundle so that the globals set up by the renderer are applied by the time lit runs.
- Test updated.
N/A
=> Make 'lit' always be bundled in SSR

.changeset/chatty-peas-warn.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/path.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/static-build.test.js
Fixes a bug in `astro build` that was breaking injected links and styles in projects deployed to subpaths
[x] fixes a bug where `astro build` wasn't prepending the base path for injected links and styles
[x] updates the `dev` server to handle the `base` path when assets from `public` are requested
Updated static-build test suite to expect injected style links to include the `base` path from `astro.config.js`
N/A
=> Improvements to build and dev when building for subpaths

.changeset/thick-beds-flow.md, packages/integrations/preact/src/index.ts
- Previously, the Preact integration returned a partial Vite config.
- Every other integration uses the `updateConfig` helper, so now Preact does too.
CI
N/A
=> fix(preact): use updateConfig hook

.changeset/thirty-boxes-shave.md, packages/integrations/vercel/src/index.ts
When using the Vercel adapter, setting the `trailingSlash` option will result in the same behavior as the `trailingSlash` setting inside `vercel.json`:
- `always` redirects `/foo` to `/foo/`
- `never` redirects `/foo/` to `/foo`
- `ignore` doesn't redirect
=> feat(vercel): Support `trailingSlash`

packages/create-astro/src/index.ts
Removes `.stackblitzrc` and `sandbox.config.json` from `create-astro` output. These are helpful when generating from the `astro.new` command, but not necessary for local development with our CLI tool.
Debated whether it was worth killing a tree to test this change on our test runner every time. For a small change like this, I decided against it 🙃 
N/A
=> Feat: [create-astro] remove online editor configs from output

.changeset/warm-days-wash.md, packages/astro/src/core/add/index.ts
Append trailing slash to project `root` to fix `astro.config.mjs` path resolution
=> Fix: `astro add` generating config outside project root

.changeset/cool-experts-shake.md, packages/astro/env.d.ts, packages/astro/src/@types/astro.ts
- Added types `MarkdownHeader`, `MarkdownMetadata` and `MarkdownContent`
- Types for importing `.md` files
=> feat(markdown): Improved types

.changeset/large-birds-repair.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/config.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/astro-markdown-url.test.js, packages/astro/test/fixtures/astro-markdown-url/.gitignore, packages/astro/test/fixtures/astro-markdown-url/package.json, packages/astro/test/fixtures/astro-markdown-url/src/pages/docs/pages/how-to-make-a-page.md, packages/astro/test/fixtures/astro-markdown-url/src/pages/index.astro, pnpm-lock.yaml
- file.url now respects `trailingSlash`, adding a `/` at the end when it's set to `"always"`
- file.url now respects `base` (needed to change the default of `base` from `./` to `/`)
- Minor fix to this RegEx:
```diff
- fileId.replace(/^.*\/pages\//, sitePathname)
+ fileId.replace(/^.*?\/pages\//, sitePathname)
```
The `?` makes the selection "lazy", which means that it will replace the shortest match. For example:
```js
const fileId = "src/pages/docs/pages/how-to-create-a-page.md"
console.log(fileId.replace(/^.*?\/pages\//, '')) // docs/pages/how-to-create-a-page.md
console.log(fileId.replace(/^.*\/pages\//, '')) // how-to-create-a-page.md
```
=> fix(markdown): file.url fixes

.changeset/strong-seals-grow.md, packages/create-astro/package.json, packages/create-astro/src/index.ts, packages/create-astro/test/directory-step.test.js, packages/create-astro/test/install-step.test.js, packages/create-astro/test/utils.js, pnpm-lock.yaml
- Add new step to `create astro` - Would you like us to run "MY_PACKAGE_MANAGER install?"
- Update "next steps" section to recommend `pnpm dev`, `yarn dev`, or `npm run dev`.
- Infers MY_PACKAGE_MANAGER based on how you ran the command: `yarn create astro` vs `pnpm create astro`, etc.
Add super fancy unit tests to walk through the CLI: `install-step.test.js` 🔥 
https://user-images.githubusercontent.com/51384119/164801565-70004c92-01d2-472f-9dec-ded1a382fa5e.mov
N/A
=> Feat: `create astro` add install step

.changeset/metal-doors-rhyme.md, packages/astro/astro-jsx.d.ts
Add Astro attributes (`class:list`, `set:html` etc) to SVG elements
Fix https://github.com/withastro/language-tools/issues/260
No tests needed (if we have to, we'll test this in the language server itself)
No docs needed
=> Add Astro attributes to svg elements

.changeset/happy-sheep-chew.md, packages/astro/src/@types/astro.ts
`is:raw` was missing from the types of allowed attributes
No docs needed
=> Add missing is:raw in AstroBuiltinAttributes

.changeset/big-ducks-search.md, packages/astro/src/core/create-vite.ts
- Makes it so that we ignore all file watching during the build.
- This fixtures issues seen in very large projects as reported here: https://discord.com/channels/830184174198718474/966778102401368084
- Also speeds things up, in theory at least.
Not really testable unfortunately.
N/A, bug fix.
=> Prevent watcher from running during the build

.changeset/swift-houses-itch.md, packages/integrations/vercel/src/index.ts
Non-HTML pages (or endpoints) are set to always have its "trailing slash setting" to `never` ([reference](https://github.com/withastro/astro/blob/7ccda57c1d34529446bff99131ded899f1b678ab/packages/astro/src/core/routing/manifest/create.ts#L272)) This PR fixes that case
=> fix(vercel): `trailingSlash` fix for non-html pages

examples/starter/src/components/Logo.astro
A `Props` interface is defined but not used in line 7. Add `as Props` to end of that line. (Note: the comment on line 2 also look incomplete.)
=> fix: use defined Props interface

.changeset/curly-crews-cross.md, packages/astro/src/runtime/server/index.ts, packages/astro/test/astro-directives.test.js, packages/astro/test/fixtures/astro-directives/src/pages/define-vars.astro
Closes #3194 
Fixes a bug that caused compiled style blocks to be ignored in the rendered `<head>`, losing CSS variable definitions compiled for `<style define:vars>`
Added a test case in the `astro-directives` suite (this was previously being tested in the now removed `legacy-build` suite
N/A bug fix only
=> Fixes variable definitions in <style define:vars>

CONTRIBUTING.md
- Removes the “Translations” section in CONTRIBUTING
- Replaces it with a more general call out for contributions to the docs
- No code changed
- This is docs-_only_ 🎉
=> Replace outdated translations contribution guide

.changeset/loud-tigers-draw.md, packages/telemetry/src/index.ts
- Removes a line that was causing Astro to not exit.
- Tested manually.
- N/A
=> fix cannot exit astro bug

examples/blog-multiple-authors/src/pages/index.astro
Removes extra meta title from blog complex template
issue: #3270 
**Before** 
**After**
No testing needed
No docs update
=> fix: remove extra meta title from complex blog template

.changeset/tall-forks-cross.md, packages/integrations/turbolinks/client.js
Closes #3128 
This updates the turbolinks integration to remove any client hydration scripts before page navigation.
By default turbolinks will leave `<head>` scripts in place during page navigation, by manually removing them we leave it up to turbolinks to add them back if needed, triggering a fresh script execution in the browser and re-hydrating the components again 🥳
**styles**
Injected style bundles are also cleaned up on navigation now - after each page navigation they're moved down into the body where Turbolinks will clean them up when diffing the new page
Tested locally with the reproduction from #3128 
None, bugfix only
Why two different methods for cleaning up scripts vs styles?  Because it actually works...🤣 If scripts are moved into the body after page navigation it breaks the …
=> Turbolinks: clean up injected scripts and styles on page navigation

packages/astro/components/Markdown.astro, packages/astro/src/core/render/result.ts
- Based on https://github.com/withastro/rfcs/discussions/179
- While the RFC is not yet merged, this first step of the adoption plan is needed regardless, to protect users from this broken experience.
- Tested manually. 
- https://github.com/withastro/docs/pull/411
=> deprecate the markdown component in SSR

.changeset/mean-donkeys-sin.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/integrations/index.ts
Exposes a `pages` property in the `astro:build:setup` hook as discussed in: https://github.com/withastro/rfcs/discussions/188#discussioncomment-2682523 The comment suggests to add a new hook, but it seemed like it makes more sense to just add it to the setup hook instead rather than giving it it's entire own special hook.
Tested locally
The `astro:build:setup` hook wasnt yet documented at all, so I added it here as well: https://github.com/withastro/docs/pull/433
=> feat: expose pages

.github/workflows/main.yml
When Congratsbot posts new commits to our `#dev` channel on Discord, the commit message always linked to the general `withastro/astro` commit history page. This PR changes this and makes it link to the actual commit, just like our new Docsbot does.
No changeset as this doesn't change any packages, only the GitHub workflow.
Docsbot uses the same code and it was just tested in production.
Not a visible change.
=> Fix: Make Congratsbot link to actual commit

.changeset/fast-dolls-eat.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/render/route-cache.ts, packages/astro/src/runtime/server/index.ts, packages/astro/test/api-routes.test.js, packages/astro/test/fixtures/api-routes/src/pages/context/data/[param].json.js, packages/astro/test/fixtures/api-routes/src/pages/old-api/onearg/[param].json.js, packages/astro/test/fixtures/api-routes/src/pages/old-api/twoarg/[param].json.js, packages/astro/test/fixtures/ssr-dynamic/src/pages/api/products/[id].js
- Implements the API Route Change proposal RFC: https://github.com/withastro/rfcs/pull/178
- Retains backwards compatibility, with warnings.
- Provides an `APIContext` to dynamic routes: `{ params, request }` as outlined in the RFC.
- Tests added to ensure we retain backwards compatibility on the old signatures.
- Tests added for the new signature.
=> Conform to API route signature

.changeset/angry-rats-turn.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/app/index.ts, packages/astro/src/core/render/core.ts, packages/astro/src/core/render/dev/index.ts, packages/astro/src/core/render/result.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/fixtures/ssr-response/src/components/OverwriteHeader.astro, packages/astro/test/fixtures/ssr-response/src/components/SetAHeader.astro, packages/astro/test/fixtures/ssr-response/src/components/SetStatus.astro, packages/astro/test/fixtures/ssr-response/src/pages/child-set-status.astro, packages/astro/test/fixtures/ssr-response/src/pages/child-tries-to-overwrite.astro, packages/astro/test/fixtures/ssr-response/src/pages/some-header.astro, packages/astro/test/fixtures/ssr-response/src/pages/status-code.astro, packages/astro/test/ssr-adapter-build-config.test.js, packages/astro/test/ssr-api-route.test.js, packages/astro/test/ssr-dynamic.test.js, packages/astro/test/ssr-request.test.js, packages/astro/test/ssr-response.test.js
- Implements Astro.response RFC: https://github.com/withastro/rfcs/blob/main/proposals/0021-astro-response.md
- Makes `Astro.response.headers` readonly as per the RFC decision.
- Tests added for everything.
- https://github.com/withastro/docs/pull/437
=> Implement the Astro.response RFC

.changeset/tasty-numbers-destroy.md, packages/astro-rss/README.md, packages/astro-rss/src/index.ts, packages/astro-rss/test/rss.test.js
We discovered that canonicalUrl did not work as expected in the `@astrojs/rss` package. So, we're asking users to apply this value manually as a required prop.
- Rename `canonicalUrl` to `site` per @fredkshott's suggestion
- Make `site` a required argument to `@astrojs/rss`
- Remove any logic pulling in `site` from the environment
Remove test for `site` validation
- Update README
- Update docs.astro.build https://github.com/withastro/docs/pull/453
=> Fix: make RSS canonicalUrl required

.changeset/sweet-vans-begin.md, packages/astro/src/cli/index.ts, packages/astro/src/core/config.ts, packages/telemetry/src/events/session.ts, packages/telemetry/test/session-event.test.js
- This updates the telemetry so that the shallow AstroConfig keys are tracked. We have found the existing vite key data to be very valuable and intend on sharing it with other maintainers. Adding the rest of these config keys will give us better data on which features are being used.
Tests updated to reflect the new data structure.
N/A
=> Add new configKeys prop for telemetry

examples/with-tailwindcss/tailwind.config.cjs, packages/astro/src/core/add/consts.ts, packages/astro/test/fixtures/tailwindcss/tailwind.config.js
Add markdown to the default content files in the tailwind integration. This fixes an issue I was having (if you add a tailwind class to a `div` or other html component in markdown, tailwind wouldn't generate the new class).
So far, it works fine in my own project.
Doesn't need docs
=> Fix tailwind integration in markdown files

.changeset/new-carrots-cough.md, packages/astro/src/core/build/types.ts
- Fixes #3320
- `.d.ts` files don't get built in the final package, it should be `.ts`
- Also, looks like `.d.ts` files aren't checked with TS, so renaming it also triggered some TS errors to solve.
- Should this be tested? I guess we could add a test that no `.d.ts` bugs
- Update: looks like eslint really isn't designed for file name checks, and we don't have `package/astro` specific eslint rules. I think we can skip a test given how infrequent this will be.
- N/A
=> rename dts to ts file

.changeset/healthy-oranges-approve.md, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/custom-404.test.js, packages/astro/test/fixtures/custom-404/astro.config.mjs, packages/astro/test/fixtures/custom-404/package.json, packages/astro/test/fixtures/custom-404/src/pages/404.astro, packages/astro/test/fixtures/custom-404/src/pages/index.astro, pnpm-lock.yaml
Closes #2661 
Updates the dev server to fix a bug when finding the custom 404 route
Added a test suite for custom 404 pages in dev
=> Fixes custom 404 pages in astro dev

examples/docs/src/components/Header/Header.astro, examples/docs/src/config.ts
Updating the docs example to fix the mobile header layout
**Before**
**After**
NA
NA
=> Fixing mobile header for docs example

.changeset/happy-wasps-check.md, examples/minimal/src/pages/index.astro, packages/astro/src/vite-plugin-astro/hmr.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/astro-markdown-css.test.js
- Adds hoisted scripts to the module graph, so that they will trigger HMR.
- Fixes #3228
Manually tested via an example.
N/A, bug fix.
=> HMR hoisted scripts

packages/astro/src/vite-plugin-env/index.ts
- Fixes https://github.com/withastro/astro/issues/2903
- Allows Astro to hook into `process.env` variables as provided by platforms like Netlify and Vercel.
Manually
TODO
=> Allow Astro to pass `process.env` variables to `import.meta.env`

packages/astro/src/@types/astro.ts
- aligns the documentation of Astro's default `markdown.remarkPlugins` and `markdown.rehypePlugins` with the defaults used in https://github.com/withastro/astro/blob/main/packages/markdown/remark/src/index.ts#L24
- as requested by @RafidMuhymin in [this message on Discord](https://discord.com/channels/830184174198718474/853350631389265940/970743012214841414)
No tests.
Updates defaults shown in [Configurations Reference page in docs](https://docs.astro.build/en/reference/configuration-reference/#markdownremarkplugins)
=> Update markdown.remark/rehypePlugins defaults for docs

.changeset/curly-bees-collect.md, packages/astro/src/@types/astro.ts, packages/astro/src/runtime/server/index.ts
- Fixes #3343
- Exports `APIRoute`
- Removed deprecated signature which prevents type narrowing.
Our TS types are currently not tested :/
N/A, this API is already documented.
=> Fix APIRoute type

.changeset/funny-poets-walk.md, packages/astro/src/core/create-vite.ts
- Related to https://github.com/withastro/astro/issues/3338
- Adds `node-fetch` to default `vite.optimizeDeps.exclude`.
- Changeset added ✅
Manually
N/A
=> Exclude `node-fetch` from vite.optimizeDeps

.changeset/small-maps-cough.md, packages/astro/src/runtime/server/hydration.ts, packages/integrations/react/client-v17.js, packages/integrations/react/client.js
- Resolves #3010
- Update Astro core to surface `client` directive to client renderers
- Update React `client.js` to use `createRoot` on `client:only` instead of suppressing hydration warnings (spoiler: they aren't suppressed!)
- Update React `client-17.js` to use `render` on `client:only` instead of suppressing hydration warnings
N/A, check your console 😉 
N/A
=> Fix: React - Use "createRoot" instead of "hydrateRoot" for `client:only`

.changeset/dry-glasses-guess.md, packages/astro/src/core/errors.ts, packages/astro/src/core/messages.ts
- Solves a DX issue that the Solid + Builder teams were seeing, where it was unclear how to resolve a `noExternal` issue based on the console output. 
- Adds a larger "Hint" error metadata + formatter that you can use to report hints alongside errors.
- TODO
- N/A
=> add error hints

packages/astro/src/@types/astro.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/core/routing/manifest/generator.ts, packages/astro/src/core/routing/manifest/serialization.ts
Deserialized routes in SSR now have `generate()`. I was trying to figure out other thing saw this TODO
=> internal: deserialized routes now have `generate()`

.changeset/tiny-donuts-own.md, packages/astro/src/core/build/index.ts, packages/astro/src/core/render/dev/index.ts, packages/astro/src/runtime/server/index.ts, packages/astro/test/alias.test.js, packages/astro/test/fixtures/alias/astro.config.mjs, packages/astro/test/fixtures/alias/package.json, packages/astro/test/fixtures/alias/src/components/Client.svelte, packages/astro/test/fixtures/alias/src/pages/index.astro, pnpm-lock.yaml
- Fixes #2921
- Simplifies hydration id resolution in dev, now we just defer to `/@id`, an internal Vite resolution, unless it's already `/@fs`.
Test added
N/A, bug fix.
=> Support alias use with hydration scripts

.changeset/silent-books-train.md, packages/integrations/partytown/README.md, packages/integrations/partytown/src/index.ts
- Add options to partytown integration
- N/A
- Added to the README.md
=> Add options to partytown integration

.changeset/silver-toes-retire.md, packages/integrations/vercel/README.md, packages/integrations/vercel/src/serverless/adapter.ts
Remove `nodeVersion` option for `serverless` target. Now it is inferred from Vercel
=> feat(vercel): remove `nodeVersion`

.changeset/smart-bananas-kick.md, packages/integrations/turbolinks/README.md
Adding a deprecation warning to the `@astrojs/turbolinks` package.  [Turbolinks](@swup/scripts-plugin) is no longer actively maintained and unfortunately it doesn't work well with islands architecture.
N/A
Docs [PR #574](https://github.com/withastro/docs/pull/574) removing references to the integration
=> Deprecate @astrojs/turbolinks

.changeset/lucky-meals-ring.md, packages/astro/e2e/fixtures/nested-styles/package.json, packages/astro/e2e/fixtures/nested-styles/src/components/Card.astro, packages/astro/e2e/fixtures/nested-styles/src/components/partials/Header/index.astro, packages/astro/e2e/fixtures/nested-styles/src/components/partials/Layout/index.astro, packages/astro/e2e/fixtures/nested-styles/src/pages/index.astro, packages/astro/e2e/fixtures/nested-styles/src/styles/global.css, packages/astro/e2e/nested-styles.test.js, packages/astro/src/core/dev/index.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/errors.test.js, packages/astro/test/test-utils.js, pnpm-lock.yaml
- Fixes #3365
- Passing a list of deps to `import.meta.hot.accept` results in modules in the module registry being overridden, so when we try to crawl deps to find CSS we don't find any.
- This is likely a Vite bug.
- The fix is to not pass deps to `import.meta.hot.accept`, which turns out to not be needed.
- Test added for the error recovery bug, which was the original reason this code was changed and cause the regression. It turns out this part of that change isn't needed.
- playwright test added to ensure styles for nested components exist on initial page load.
=> Error recovery test and more

packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/custom-404-md.test.js, packages/astro/test/fixtures/custom-404-md/astro.config.mjs, packages/astro/test/fixtures/custom-404-md/package.json, packages/astro/test/fixtures/custom-404-md/src/layouts/Base.astro, packages/astro/test/fixtures/custom-404-md/src/pages/404.md, packages/astro/test/fixtures/custom-404-md/src/pages/index.astro, pnpm-lock.yaml
Closes #3389 
Updates the dev server to support using markdown pages for custom 404 routes (this already works in `astro preview`)
Added a test fixture for custom `404.md` pages
Related to [PR #554](https://github.com/withastro/docs/pull/554)
=> Matching custom 404 pages using the manifest's route patterns

packages/astro/test/alias.test.js, packages/astro/test/errors.test.js
- Test change only
I was extremely confused why tests weren't running. Finally tracked down the culprit as a stray `it.only`!
N/A
=> Fix tests: remove `it.only`

packages/astro/package.json, packages/astro/test/errors.test.js, packages/astro/test/test-utils.js
- Re-enables a test that was skipped but should be working.
=> Re-enable error recovery test

.changeset/thirty-drinks-shout.md, packages/astro/src/core/logger/core.ts, packages/astro/test/cli.test.js, packages/create-astro/src/logger.ts
- Fixes https://github.com/withastro/astro/issues/3309
- Use default locale based on `process.env.LANG` without implementing our own logic
- Adds a warning for future devs
- Regression tests added
Bug fix only
=> fix: locale handling for logger

.changeset/sour-years-scream.md, packages/astro/src/core/build/static-build.ts
- A few discord users were confused by the "building for SSR" messaging during SSG. This introduces new messaging:
- When using SSG: **Build entrypoints for prerendering...**
- When using an SSR adapter: **Building SSR entrypoints...**
N/A
N/A
=> Fix: update "building for SSR" messaging on SSG

.changeset/lemon-insects-smash.md, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/dev-routing.test.js
This updates the dev server to support `.html` requests, currently only `/blog` is matched and `/blog.html` would 404
Added a test to verify `.html` is supported in dev when `config.build.format === 'file'`
=> Fix: Support .html requests in dev

.changeset/good-humans-sniff.md, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/test/fixtures/ssr-assets/src/pages/index.astro, packages/astro/test/ssr-assets.test.js, packages/astro/test/test-utils.js
- Makes it so that the SSR manifest `assets` field includes server CSS. This is so that an edge function can forward those requests back to the CDN.
- Closes #3324
N/a, bug fix
=> Include server CSS in the manifest assets
