.changeset/poor-ways-relax.md, packages/astro/src/core/errors.ts, packages/astro/src/template/5xx.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/error-react-spectrum.test.js, packages/astro/test/fixtures/error-react-spectrum/astro.config.mjs, packages/astro/test/fixtures/error-react-spectrum/package.json, packages/astro/test/fixtures/error-react-spectrum/src/pages/index.astro, pnpm-lock.yaml
- This adds an error message for `@adobe/react-spectrum` which is not compatible with Vite SSR.
- Also makes it possible to add more bad package messages in the future.
- Closes #3306
Test added
N/A, bug fix
=> Provide a good error message when loading react spectrum

.changeset/fluffy-wolves-sneeze.md, packages/astro/src/runtime/server/index.ts, packages/astro/test/astro-partial-html.test.js, packages/astro/test/fixtures/astro-partial-html/src/components/Head.astro, packages/astro/test/fixtures/astro-partial-html/src/pages/head.astro
- Closes #3195, #3197
- We had a bug where `` would be replaced too early, before any scripts were ready to be inserted. This meant that if you put `<head>` inside of a component, hydration would never work.
- We've discussed removing the head injection logic all together—this PR opts to fix the immediate bug, and we can circle back to exploring different techniques in the future.
Test added
Bug fix only
=> Defer head injection until `renderPage`

.changeset/serious-vans-smell.md, packages/webapi/package.json, packages/webapi/run/build.js, packages/webapi/src/lib/fetch.ts, pnpm-lock.yaml
- Resolves #2741 
- Move `node-fetch` to external dependency for `@astrojs/webapi` bundle. This was causing strange issues with body parsing that I still haven't figured out. Still, since `@astrojs/telemetry` already pulls in `node-fetch` as a standard dependency, this shouldn't be a problem!
- moving away from using `node-fetch/src/index.js` exposed type issues. A few pieces to resolve:
- `fetch` no longer accepts `URL` as a resource type. Funny enough, you _can_ still pass a `URL` for node-fetch to run `toString()` implicitly. Still, you get red squigglies in VS Code using URL today, so removing this type option is for consistency if anything.
- `FetchInit` now uses node-fetch's body type in its type signature
@FredKSchott (a cool kid) suggested using …
=> Fix: support `FormData` object on fetch body

.changeset/hungry-elephants-smash.md, .github/ISSUE_TEMPLATE/---01-bug-report.yml, packages/astro/src/vite-plugin-astro/index.ts
This PR closes #3257
* Add IDs to bug report issue form
* Replace 'body' with correct input id for prefilling form
This approach was tested by creating a fresh repository, creating an issue template with `id`s for each input box in the form, constructing a URL and opening it to see if it works. It worked.
Additional information: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#keys
No docs required
I don't know why but this commit is falsely shown as "Unverified" even if I signed it with one of my GPG keys. Maybe it is because I uploaded the public key to GitHub after making this commit, and the fact that I was using GitHub Codespaces and not my local computer.
=> Fix GitHub Issue creation link

.changeset/wet-beds-act.md, packages/astro/src/core/app/index.ts, packages/astro/src/core/app/types.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/test/astro-client-only.test.js, packages/astro/test/astro-dynamic.test.js
Closes #2561 
This updates hydration scripts to use absolute paths when importing scripts.  This is necessary to make sure any client-hydrated scripts on a custom 404 page are loaded properly
Updated existing tests and added two new ones to confirm this behavior when `config.base` is used to deploy to subpaths
=> Updates hydration scripts to use absolute paths

.changeset/friendly-ways-collect.md, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/astro-scripts.test.js, packages/astro/test/fixtures/astro-scripts/src/components/Inline.astro, packages/astro/test/fixtures/astro-scripts/src/pages/inline.astro, packages/astro/test/fixtures/astro-scripts/src/scripts/hoist_external_imported_inline.js
- Uses `normalizeFilename` which removes the `@fs` previous which was preventing us from resolving on Windows.
- Fixes https://github.com/withastro/astro/issues/3387
- Test added in the astro-scripts package. The test passing shows this is now fixed.
N/A
=> Fix: Relative imports inside of hosited script on windows

packages/astro/src/core/build/static-build.ts
Instead using `error` as default value, use the Vite's default `logLevel`: `info`
Use the `levelLog` provided by the user or the Vite's default `levelLog`: `info`
=> feat: use Vite's `logLevel` on SSR build

.changeset/blue-bottles-explode.md, packages/astro/src/core/errors.ts
- Resolves #3226
- Add `.css` extension to `ssr.noExternal` hint
N/A
https://github.com/withastro/docs/pull/633
=> Fix: add "CSS" to noExternal hint

.changeset/fair-bananas-camp.md, packages/astro/src/core/build/static-build.ts
- Sets `logLevel` for `astro build` back to `error`. We get a LOT of warnings from using so many framework plugins and they are mostly irrelevant.
New output reflected in test logs
N/A
=> Use `error` log level since warnings are irrelevant and noisy

.changeset/orange-colts-march.md, packages/integrations/partytown/src/index.ts
- Closes #3432 
- It adds the `lib` option so the partytown scritpt can resolve the correct path if the `base` config option is provided.
Tested locally
There's no need to update the docs.
=> Add base config option to partytown snippet generation

.changeset/ten-hounds-fry.md, .gitignore, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/generate.ts, packages/astro/test/static-build-page-dist-url.test.js
- Just exposes a `distURL` path on routes for use in integrations
- Also excludes IntelliJ/WebStorm internal stuff from the `.gitignore` root file
Tested manually on PWA integration
Is there docs for this? If so, just add a hint for the `distURL` prop
=> feat: expose route dist URL on SSG

.changeset/nasty-tigers-sip.md, packages/astro/env.d.ts, packages/astro/src/@types/astro.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/raw-content.json.js, packages/astro/test/test-utils.js
Note: I highly recommend [checking the docs PR](https://github.com/withastro/docs/pull/668) to understand the use cases for each of these helpers!
- Resolves #3072 
- Adds 2 new helpers to imported markdown _and_ `?content` markdown:
- `content.raw()` -> retrieves raw markdown excluding frontmatter block
- `await content.compiled()` -> retrieves raw markdown parsed to Astro syntax. This excludes JSX, components, and layouts! Note added to docs PR (see Docs section)
- Updates type def for imported markdown
New `astro-markdown` tests against a raw content endpoint
https://github.com/withastro/docs/pull/668
=> Feat: markdown `content.raw()` and `content.compiled()` helpers

examples/basics/src/components/Card.astro
Simple fix of "Just the basics" starter for #3473 
This seems to be a bug with named slots. Named slots that are not used will break the build.
Remove unused slot in the "Just the Basics" starter:
- this slot is not used in the example
- it fixes the build bug in #3473
Tested
- `npm run dev`
- `npm run build` and `npm run preview`
No impact on the docs.
=> Remove unused slot in the "Just the Basics" starter until slot bugs are fixed (fix #3473)

.changeset/polite-eels-visit.md, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/comment-with-js.md
- Fixes #3476.
- Injects a zero-width space character into nested `*/` sequences when wrapping HTML comments to JS comments.
- I added a new test case to verify the fixed behavior.
- No visible change, just a bugfix.
=> Fix `*/` breaking HTML comments in Markdown

.changeset/old-pigs-exist.md, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/astro.config.mjs, packages/astro/test/fixtures/astro-markdown/src/pages/vite-env-vars.md
- Fix bug #3412 in `vite-plugin-markdown` by converting the first dot in every occurrence of `import.meta.env.` to its Unicode escape sequence, which prevents Vite from replacing strings like `import.meta.env.SITE` in our JS representation of loaded Markdown files
- Add tests.
I added a new test case and ran all tests successfully.
Not a visible change, just a bugfix.
=> Fix using Vite env var names in Markdown (#3412)

examples/basics/README.md, examples/blog-multiple-authors/README.md, examples/blog/README.md, examples/component/README.md, examples/docs/README.md, examples/minimal/README.md, examples/non-html-pages/README.md, examples/portfolio/README.md, examples/starter/README.md, examples/subpath/README.md, examples/with-vite-plugin-pwa/README.md
The link to documentation in the Just the Basics starter template README did not actually go to Docs. Now it does!
No test, only link.
Does not affect Docs site itself.
=> Correcting the link to docs on Just the Basics starter README

.changeset/gentle-cheetahs-divide.md, packages/integrations/lit/client-shim.js, packages/integrations/lit/client-shim.min.js
- Waits for DOMContentLoaded so that we don't try to polyfill the body before it exists.
- Closes https://github.com/withastro/astro/issues/3481
N/A, bug fix.
=> Lit polyfill - wait to polyfill on DOMContentLoaded

.changeset/fifty-mice-bow.md, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/fixtures/hmr-css/src/pages/index.astro, packages/astro/test/hmr-css.test.js
- In the dev server detect requests for `lang.css` which is a search param added for Astro, Vue, and Svelte styles. Set the correct content-type for these (`text/css`).
- Closes #3219
- Closes #3370
- Test added which mimics what Vite does in HMR.
N/A, bug fix.
=> Set the correct content-type for CSS HMR

.changeset/chilly-sheep-doubt.md, packages/integrations/deno/package.json, packages/integrations/deno/src/shim.ts, packages/integrations/deno/test/basics.test.js, packages/integrations/deno/test/fixtures/basics/src/pages/index.astro
Uses Deno.env to mock process.env
A test is added
One would expect this to work, but IMO doesn't need to be documented separately
=> Load environment variables in deno SSR

.changeset/quick-crabs-lay.md, packages/astro/e2e/astro-component.test.js, packages/astro/e2e/fixtures/astro-component/src/pages/index.astro, packages/astro/src/runtime/server/metadata.ts, packages/astro/src/vite-plugin-astro/compile.ts
Closes #3424 
This was a regression caused by #3300 - `/@fs` is being included in the script src in `<head>` which is breaking HMR in dev for hoisted scripts
TODO: will add an HMR test to cover
=> Fixing HMR for hoisted scripts

.changeset/olive-cobras-bow.md, packages/astro/src/core/dev/index.ts, packages/astro/src/core/messages.ts
Add warning log when `vite.server.fs.strict` is `false` to [follow SvelteKit's lead](https://github.com/sveltejs/kit/blob/7f958dd49cfbbc4712001b1b21ce1474b44da69e/packages/kit/src/cli.js#L232-L241). Don't worry, this value [is `true` by default](https://vitejs.dev/config/#server-fs-strict) in Vite!
N/A
N/A
=> Add console warning on fs.strict=false

.changeset/calm-queens-study.md, .changeset/spicy-turkeys-clean.md, packages/astro/src/core/create-vite.ts, packages/astro/test/fixtures/type-imports/src/pages/index.astro, packages/astro/test/type-imports.test.js, packages/integrations/deno/src/index.ts, packages/integrations/netlify/src/integration-edge-functions.ts
fixes: https://github.com/withastro/compiler/issues/378
Aliases imports for `astro` to `@types/astro` c8816d408c6ab92651556559248a9012cfbe9b4f and updates Netlify and Deno integrations to handle `vite.resolve.alias` as an array b15ca78be4483214be6f17e29559df91f206d759
Only the types live under `astro` but without alias vite resolves import to `packages/astro/astro.js` 
- Test added to check build passes when `import type { MarkdownInstance } from 'astro'` is present
No docs needed, this is fix for expected behaviour
=> fix: alias astro to @types/astro

.changeset/new-knives-raise.md, packages/astro/src/runtime/server/index.ts, packages/astro/test/0-css.test.js
- Closes https://github.com/withastro/compiler/issues/392
- Ensures our generated `link` tags are self-closing
Test added to CSS tests
Bug fix only
=> Fix `<link>` tag not being self-closing

.changeset/famous-pens-cheer.md, packages/integrations/lit/package.json, packages/integrations/lit/server-shim.js, packages/integrations/lit/test/sass.test.js, pnpm-lock.yaml
- We closed https://github.com/withastro/astro/issues/2623 as an upstream issue
- Users are still hitting this problem since an upstream fix hasn't landed https://github.com/withastro/astro/issues/3508
- The patch is very small, so I added it to our server shim
- Tests pass now
Added a specific test for this
Bug fix only
=> Patch Lit server shim to fix sass compatability

.changeset/late-swans-impress.md, packages/markdown/remark/src/remark-mdxish.ts, packages/markdown/remark/test/strictness.test.js
- After our switch to the MDX-like parsing logic in Beta 33 (PR https://github.com/withastro/astro/pull/3410), Markdown parsing has become a lot more strict. This caused commonly used syntax in Markdown to become invalid.
- This PR fixes one of the most common issues concerning self-closing tags like `<br>`. They are now considered valid again by wrapping the MDX JSX tag parsing logic.
- Fixes #3458.
- Added a new test case to `@astrojs/markdown-remark`.
- Ran all tests locally.
- Performed a full build of Astro Docs without issues.
- Not a visible change, just a bugfix.
=> Fix: Allow self-closing tags in Markdown again

.changeset/hot-waves-jump.md, packages/markdown/remark/src/index.ts
- Adds a proper source filename to Markdown errors that fail the build.
- Reason: Questions where users did not know which Markdown file was causing a build failure were asked multiple times in our Discord support channel in the last few days.
- Old error message example:
```
Expected a closing tag for `<br>` (2:74-2:78) before the end of `paragraph
```
- New error message example:
```
Failed to parse Markdown file "D:\Dev\astro-docs\src\pages\en\core-concepts\routing.md":
Expected a closing tag for `<br>` (2:74-2:78) before the end of `paragraph
```
- Works in `build`, `dev`, and SSR modes.
- Ran all tests locally.
- Performed multiple builds of the Astro Docs repo, inserting test errors in various MD files.
- Not a visible change, just a bugfix.
=> Fix Markdown errors missing source filename

.changeset/hungry-ears-clap.md, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/fixtures/import-ts-with-js/src/bar.ts, packages/astro/test/fixtures/import-ts-with-js/src/foo.ts, packages/astro/test/fixtures/import-ts-with-js/src/pages/index.astro, packages/astro/test/fixtures/import-ts-with-js/src/pages/post.md, packages/astro/test/import-ts-with-js.test.js
- Allowing doing `import './foo.js'` where a foo.ts file exists.
- Closes #3415
- Implementation is that Vite allows this scenario when a parent is a typescript module. When compiling Astro we can provide metadata to allow this.
Test added
N/A, bug fix.
=> Allow importing .ts files with .js extension

.changeset/long-spies-check.md, packages/astro/src/core/create-vite.ts, packages/astro/src/core/dev/index.ts, packages/astro/src/core/render/dev/index.ts
- Resolves #3465 
- Add all client runtime scripts to Vite's `optimizedDeps.include`. We exclude `hmr.js` from this list due to dependency issues in the monorepo when using `workspace:*`. I'm unable to find _exactly_ what's causing this, but the issue seems urgent enough to roll with this temporary solution.
N/A
N/A
=> Fix: refusing to accept `isSelfAccepting` for JSX

.github/workflows/format.yml, package.json, packages/integrations/deno/src/server.ts, packages/integrations/vercel/src/edge/entrypoint.ts, pnpm-lock.yaml
- does what the title says! Equivalent to running "Organize Imports" in VSCode, but automated on every file.
- Powered by TypeScript internally.
- Available via a new `pnpm run format:imports`
- Added to CI auto-formatting on every commit to `main`.
- Not added to the user-recommended `pnpm run format` since it adds ~30 seconds to formatting.
This feels like an important part of formatting, but I wanted to get team thoughts before merging. Be sure to see the commit linked below to see the impact of this once it is merged.
Bonus Tip: When resolving merge conflicts, this lets you "accept both" on import changes and then run this locally to resolve duplicate imports automatically.
- Tested and run locally: https://github.com/withastro/astro/commit/c11ace5f106341f09fd6b14391148d792ac5f75b
- …
=> format: automatically organize imports and removed unused

.changeset/three-news-cry.md, packages/astro/src/vite-plugin-build-css/index.ts
- Previous issue fixing `__VITE_ASSET__` bug included us turning on minification just for the `vite:css-post` plugin, so that CSS would be minified. However this inadvertently caused all server JS to be minified, which we do not want.
- The change is to remove the monkey patching and to instead create a post plugin just for doing CSS minification for the server build.
- Fixes #3500
Existing tests should cover this change.
N/A, bug fix.
=> Prevent minifying server JS

.changeset/green-ducks-reply.md, packages/astro/package.json, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/test/fixtures/fontsource-package/package.json, packages/astro/test/fixtures/fontsource-package/src/pages/index.astro, packages/astro/test/fontsource.test.js, pnpm-lock.yaml
- `vite:css-post` removes JS modules that *only* contain CSS. These modules only exist so that the CSS asset can be created. Vite removes them and updates import statements to also be removed.
- However when you import a package the compiler creates a second import like `import * as $$module from 'some/package';` which is used to discover if the package contains used web components. Because of these namespace imports, those don't get removed by vite:css-post.
- The fix here is to create empty CSS chunks when import statements are left in.
- Fixes #3536
- Test added specifically for `@fontsource/*` package since those are a bit popular.
N/A, bug fix.
=> Fix importing CSS packages in frontmatter

.changeset/stale-flowers-share.md, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/test/errors.test.js, packages/astro/test/fixtures/errors/src/pages/import-not-found.astro, packages/astro/test/test-utils.js
Closes #3539 
This updates `vite-plugin-astro` to bail when Vite attempts to let the plugin load a relative import.  This only hits when Vite couldn't resolve an import in a `.astro` file's frontmatter
When this case hits, the plugin now bails early returning `null` which lets Vite bubble up our unresolved import error message
Added an error test to check what message is shown in dev
Also re-enabled an existing error test that was waiting for Vite 2.9
N/A
=> Fix: bubbling up a more useful error message for unresolve imports in Astro components

GOVERNANCE.md
This PR serves to implement several governance changes that will help our project as it continues to grow into its second year. The biggest changes (and the rationale behind them) are highlighted below:
1. **Remove technical requirement from Core.** This will let us recognize the contributions of more amazing leaders in our community who are not necessarily focused on technical contributions.
2. **Form a new Technical Steering Committee (TSC).** This group will take on the responsibility of technical decision making, RFC approvals, etc. that Core currently performs. Initially, current core members will become the founding TSC members.
3. **Simplify TSC consensus model.** Replace our current multi-stage consensus resolution flow with a simpler "rough consensus" model (made popular by the …
=> Governance updates

.changeset/large-rings-invite.md, packages/integrations/sitemap/src/index.ts
- Closes #3546
- Handle configured base path or `canonicalURL` pathnames on sitemap generation
This change was tested locally
It's a small bug fix, we don't need to change the docs
=> Prevent sitemap URLs without pathname

.changeset/afraid-stingrays-sell.md, packages/markdown/remark/src/index.ts, packages/markdown/remark/src/rehype-jsx.ts, packages/markdown/remark/test/autolinking.test.js
- Fixes #3529.
- Due to the MDX/JSX parsing logic "capturing" `<a>` elements, the remark-gfm plugin mistakingly started adding autolinks to plaintext URLs nested inside links. This PR detects those cases and removes the nested autolinks while still allowing regular links to be used in Markdown.
- Added test cases to both test if autolinking works in general, and to test that the unwanted nested autolinking inside links does not happen anymore.
- Ran all tests locally.
- Built Astro Docs without any errors.
- Not a visible change, just a bugfix.
=> Fix autolinking of URLs inside links in Markdown

.changeset/modern-toes-glow.md, packages/astro/package.json, packages/astro/src/core/dev/index.ts, pnpm-lock.yaml
- Adds all of the hydration directive scripts and renderer client entrypoints to optimized deps.
- This prevents a race condition where Vite assigns a unique hash for all of the deps it has optimized. When it encounters an unknown dep that hash changes. The changing of the hash causes it to need to rebuild some modules, and any modules that are in the process of being loaded are in a unexpected state at the point.
- The fix is to tell Vite about things that it will need to optimize later, which is everything in runtime/hydration.ts, so just the renderers and client directives.
- Discussed with @patak-dev (thanks!) here: https://discord.com/channels/804011606160703521/831456449632534538/984795370955616287
- Tested manually, this is a race condition that's hard to capture in a unit test. …
=> Preoptimize renderers and hydration directives

.changeset/proud-forks-hammer.md, packages/markdown/remark/src/remark-mdxish.ts
- Fixes an issue reported by `JamesScheller` in our Discord support channel that causes a `Maximum call stack size exceeded` error when building sites with hundreds of Markdown pages.
- Background: The `makeFromMarkdownLessStrict` fix introduced in beta 41 was applied once per page render, inadvertently wrapping the extension function in multiple layers of fix functions. This caused the call stack to grow indefinitely.
- This PR changes this behavior by preparing all extensions (including the fix) just once and then reusing the prepared extensions later.
- Ran all tests.
- Successfully built the private example repo provided by the original issue reporter.
- Not a visible change, just a bugfix.
=> Fix remarkMdxish performance issue on huge sites

examples/basics/README.md, examples/integrations-playground/README.md, examples/subpath/README.md, examples/with-markdown-shiki/README.md, examples/with-vite-plugin-pwa/README.md
Fixes https://github.com/stackblitz/core/issues/1896
- Fixes a typo in a StackBlitz URL and the corresponding `npm init` snippet, where the example name used didn't match the folder name exactly.
- A few StackBlitz URLs where pointing to another example than the current folder (e.g. `examples/with-vite-plugin-pwa/README.md` pointing to the `minimal` example instead of the `with-vite-plugin-pwa` example). Unless this is a deliberate choice, I suspect this comes from copying an existing example folder to create a new example, and forgetting to update the StackBlitz URL.
- Added a `?initialPath=/blog/` URL parameter for the `subpath` example, so that StackBlitz shows the correct subpath in the preview iframe.
This was manually tested by following every StackBlitz URL in …
=> fix(examples): incorrect StackBlitz demo URLs

.changeset/eleven-planes-deliver.md, packages/astro/src/@types/astro.ts
The return of the `default` function includes the same `frontmatter`
data as the parent object, merged with the `astro` data. The inclusion
of that frontmatter type was previously not recognized by TS, and fell
back to a `Record<string, any>`. This change persists the more accurate
type, as the runtime code does.
|before|after|
|-|-|
|<img width="438" alt="CleanShot 2022-05-18 at 10 36 03@2x" src="https://user-images.githubusercontent.com/3663628/169068138-46efc4f3-3486-4f99-bffd-f0c18dcb77af.png">|<img width="434" alt="CleanShot 2022-05-18 at 10 36 43@2x" src="https://user-images.githubusercontent.com/3663628/169068165-451857dc-c85f-49ac-a296-d2e45e104bcd.png">|
PR NOTE:
**The second commit is optional, and I'd squash it into the first if you want it**
The second commit goes a step …
=> Fix unintentional missing type data in `MarkdownInstance`

.changeset/friendly-colts-rush.md, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/test/fixtures/fontsource-package/package.json, packages/astro/test/fixtures/fontsource-package/src/pages/index.astro, pnpm-lock.yaml
- Fixes #3580
- We create stub modules for "pure CSS" because .astro files always compile to a namespace import for all modules. Previous fix incorrectly handled only when you imported 1 CSS module (oops).
- Test added
N/A, bug fix
=> Handle importing multiple CSS packages in same bundle

.changeset/kind-feet-double.md, packages/astro/src/core/messages.ts
- Resolves #3598 
- Ensures that Astro finds an appropriate network to host `dev` or `preview` on Node 18.1+
- Checks for appropriate network differently dependent on Node version
As mentioned by @bholmesdev on #3547, this kind of change is hard to test because we have to manipulate the Node's `os` response. However, for what it's worth, adding this fix locally fixed my issue (#3598)
This change is not visible, meaning that documentation does not need to be updated.
=> Fix: Check node version and find acceptable host accordingly

examples/blog/README.md
- Fix the tree to reflect the actual example contents
- Remove RSS and Sitemap bullet points, since they aren't in the project
=> Update README.md in blog example

.changeset/nine-dots-applaud.md, packages/integrations/cloudflare/README.md, packages/integrations/cloudflare/package.json, packages/integrations/cloudflare/src/index.ts, packages/integrations/cloudflare/src/server.ts, packages/integrations/cloudflare/src/shim.ts, packages/integrations/cloudflare/tsconfig.json, pnpm-lock.yaml
- Add an SSR adaptor for Cloudflare Pages functions.
~~There is 1 change within the Astro server runtime which was necessary to make this work, `'serialize-javascript'` generates a random number at the top level of the module, this is a pattern which is forbidden by Cloudflare workers. The error given is this:~~
```
Uncaught Error: Some functionality, such as asynchronous I/O, timeouts, and generating random values, can only be performed while handling a request. at line 0 (Code: 10021)
```
~~The fix is dynamically importing the dependency so that it generates the random number at call time, even when inlined in the build.~~
=> feat: add SSR adaptor for cloudflare pages functions

.changeset/wild-phones-work.md, packages/astro/test/astro-markdown.test.js, packages/markdown/remark/src/rehype-collect-headers.ts, packages/markdown/remark/src/rehype-jsx.ts, packages/markdown/remark/test/components.test.js, packages/markdown/remark/test/expressions.test.js
- Fixes #3493.
- Removes the extra newlines that the previous code wrapped around `mdxJsxFlowElement` and `mdxJsxTextElement` elements with children in Markdown. These extra newlines caused unwanted whitespace to be introduced into the resulting HTML output.
- Updated test cases to reflect the new correct output.
- Ran all tests locally.
- Built Astro Docs using the new code without apparent issues.
- Just a bugfix.
=> Remove extra newlines around components in Markdown

.changeset/hungry-ravens-cheat.md, packages/astro/e2e/fixtures/preact-component/src/components/JSXComponent.jsx, packages/astro/e2e/fixtures/preact-component/src/pages/index.astro, packages/astro/e2e/fixtures/preact-component/src/pages/markdown.md, packages/astro/e2e/fixtures/react-component/src/components/JSXComponent.jsx, packages/astro/e2e/fixtures/react-component/src/pages/index.astro, packages/astro/e2e/fixtures/react-component/src/pages/markdown.md, packages/astro/e2e/fixtures/solid-component/src/components/SolidComponent.jsx, packages/astro/e2e/fixtures/solid-component/src/pages/index.astro, packages/astro/e2e/fixtures/solid-component/src/pages/markdown.md, packages/astro/e2e/fixtures/svelte-component/src/components/Counter.svelte, packages/astro/e2e/fixtures/svelte-component/src/components/SvelteComponent.svelte, packages/astro/e2e/fixtures/svelte-component/src/pages/index.astro, packages/astro/e2e/fixtures/svelte-component/src/pages/markdown.md, packages/astro/e2e/preact-component.test.js, packages/astro/e2e/react-component.test.js, packages/astro/e2e/shared-component-tests.js, packages/astro/e2e/solid-component.test.js, packages/astro/e2e/svelte-component.test.js
- Our E2E tests for preact, react, solid and svelte were pretty similar, but had some subtle and unexpected differences (missing client:only tests, incomplete HMR tests). I therefore refactored these tests to use a common test factory, thereby bringing them to the same level of tested features, and also avoiding future differences.
- We did not have any islands hydration tests for components inside Markdown files. I fixed this and added Markdown tests for all of the frameworks mentioned above.
- I successfully ran the new E2E tests.
- Not a visible change.
=> Add component hydration in .md E2E tests, refactor

.changeset/empty-bats-grow.md, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/pages/comment-with-js.md, packages/markdown/remark/src/index.ts, packages/markdown/remark/src/remark-escape.ts, packages/markdown/remark/test/expressions.test.js
Closes #3460 
Fixes a bug where HTML comments weren't being rendered properly inside markdown code blocks
Added tests to the `markdown/remark` and `vite-plugin-markdown` packages to test the remark plugin and markdown page rendering
=> Fixes rendering of HTML comments inside markdown code blocks

.changeset/pink-pugs-beg.md, packages/markdown/remark/src/rehype-escape.ts, packages/markdown/remark/test/expressions.test.js
Closes #3487 
Updates rehype to encode ampersands in code blocks
Added tests for markdown `<code>` and fenced code blocks
N/A
=> Encode ampersands in markdown code blocks

.changeset/great-badgers-raise.md, packages/astro/src/runtime/server/index.ts
- Fixes issue with bad error message reported on Discord
- We were not catching `undefined` components and throwing an error as expected.
N/A
N/A
=> Properly catch falsey components

packages/integrations/sitemap/README.md, packages/integrations/sitemap/src/constants.ts, packages/integrations/sitemap/src/generate-sitemap.ts, packages/integrations/sitemap/src/index.ts, packages/integrations/sitemap/src/schema.ts
- Typings
- `serialize` - sync/**async** func should return `SitemapItem` | **`Promise<SitemapItem>`**;
- use `SitemapItem` type instead of `SitemapItemLoose`;
- `'changefreq' option - use `EnumChangefreq` from the **sitemapjs** pkg instead of self made constants (DRY).
- Few corrections in README.md.
locally
=> refactor sitemap: better typings

.changeset/gold-walls-pretend.md, packages/integrations/sitemap/package.json, packages/integrations/sitemap/src/config-defaults.ts, packages/integrations/sitemap/src/generate-sitemap.ts, packages/integrations/sitemap/src/index.ts, packages/integrations/sitemap/src/schema.ts, packages/integrations/sitemap/src/validate-options.ts, packages/integrations/sitemap/test/smoke.test.js
- Fixes #3660
- Regression caused by https://github.com/withastro/astro/pull/3579/files, didn't include .js at the end.
- Basic smoke test, make sure the package can be imported.
N/A, bug fix
=> Add .js to imports in the sitemap package

.changeset/warm-panthers-clap.md, packages/astro/e2e/fixtures/ts-resolution/astro.config.mjs, packages/astro/e2e/fixtures/ts-resolution/package.json, packages/astro/e2e/fixtures/ts-resolution/src/components/Counter.tsx, packages/astro/e2e/fixtures/ts-resolution/src/pages/index.astro, packages/astro/e2e/ts-resolution.test.js, packages/astro/src/core/build/vite-plugin-analyzer.ts, packages/astro/src/core/render/dev/index.ts, packages/astro/src/core/render/dev/resolve.ts, packages/astro/src/runtime/server/metadata.ts, pnpm-lock.yaml
- Fixes #3624
- Vite only resolve .jsx -> .tsx when the importer is a TypeScript source, which includes Astro modules (so pure SSR works) but does not include .html, which is why hydration would not work.
- The fix is to remove the extension ourselves, because Vite will resolve extensionless correctly.
- E2E test added
- Verifies dev and prod
N/A, bug fix
=> Resolve .jsx -> .tsx in hydrated components

.changeset/unlucky-otters-agree.md, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/test/fixtures/ssr-scripts/astro.config.mjs, packages/astro/test/fixtures/ssr-scripts/package.json, packages/astro/test/fixtures/ssr-scripts/src/components/Hello.jsx, packages/astro/test/fixtures/ssr-scripts/src/pages/index.astro, packages/astro/test/ssr-scripts.test.js, pnpm-lock.yaml
- Fixes #3670
- Regression caused by the fact that the order of the client and ssr builds flipped. Because of this we need to collect client assets when we inject the manifest.
- Test added
N/A, bug fix
=> Include all client build artifacts in SSRManifest

.changeset/famous-icons-pull.md, packages/astro/src/core/create-vite.ts
Adds `@nanostores/preact` to the dreaded `ALWAYS_NOEXTERNAL` list.
It seems `noExternal` is required for any utility package relying on Preact hooks. From testing, this is likely due to a duplicate Preact getting bundled when used in a component, with a separate Preact coming from your `node_modules` inside the offending package.
React is a UMD package, while Preact is a true ESM package. This means React will _always_ be bundled due to Vite's heuristics, while Preact will be ignored. This is why `resolve.dedupe` does _not_ solve the issue for Preact 😓 
N/A, though a "nanostores" E2E test suite is on my list!
N/A
=> Add `@nanostores/preact` to ALWAYS_NOEXTERNAL

.changeset/pink-shirts-mix.md, packages/astro/src/core/add/index.ts
- Fixes this odd `astro add` output
- Fixes odd behavior when `astro add react` is run with yarn (reported by @Princesseuh)
This isn't perfect, but I've never seen a semver string that this wouldn't work for. The next step would be evaluating the semver using a more complex semver-aware parser. I'd rather cross that bridge when we encounter the need.
- N/A (code path not currently tested)
- N/A (bug fix)
=> simplify a complex peer semver used by astro add

.changeset/empty-chicken-refuse.md, packages/astro/test/fixtures/postcss/package.json, packages/astro/test/fixtures/postcss/postcss.config.cjs, packages/astro/test/fixtures/postcss/src/components/Astro.astro, packages/astro/test/fixtures/postcss/src/components/Solid.css, packages/astro/test/fixtures/postcss/src/components/Solid.jsx, packages/astro/test/fixtures/postcss/src/components/Svelte.svelte, packages/astro/test/fixtures/postcss/src/components/Vue.vue, packages/astro/test/fixtures/postcss/src/pages/index.astro, packages/astro/test/postcss.test.js, packages/integrations/svelte/src/index.ts, pnpm-lock.yaml
- Resolves #3528 
- Pass generated PostCSS config from Astro config into Svelte's `preprocess` plugin. Otherwise, the user has to manually generate a preprocess object to flip `postcss` to `true`
- **Why not set `postcss: true`?** - this causes console warning when a postcss config is absent in your project! See #2807 
N/A
N/A
=> Fix: pass Astro config postcss to Svelte preprocess

.changeset/cuddly-llamas-arrive.md, packages/astro/test/fixtures/ssr-partytown/astro.config.mjs, packages/astro/test/fixtures/ssr-partytown/package.json, packages/astro/test/fixtures/ssr-partytown/src/pages/index.astro, packages/astro/test/ssr-partytown.test.js, packages/integrations/partytown/src/index.ts, pnpm-lock.yaml
- Closes #3668
- Adding these files to the manifest will cause adapters such as the cloudflare adapter to serve the static files rather than try to render a route.
- Test added
N/A, bug fix
=> Include partytown scripts in SSR manifest

.changeset/sixty-mirrors-bake.md, packages/integrations/sitemap/README.md, packages/integrations/sitemap/src/index.ts
- Resolves #3682
- Add `customPages` to sitemap README
- Add warning log for SSR users - specify `customPages` to manually generate sitemap paths
N/A
See README updates!
=> Fix: document sitemap + SSR use case

.changeset/five-zoos-look.md, packages/integrations/cloudflare/src/server.ts
perviously requests that we're 404'ing would fall through and not render a custom 404 page if one existed.
This change rectifies that.
- if a request does not match a route check if 404 matches a route
- if 404 matches render that
- else default as before
=> fix: `@astrojs/cloudflare` 404 handling

.changeset/stupid-steaks-hang.md, packages/astro/src/core/render/result.ts, packages/astro/test/fixtures/ssr-redirect/package.json, packages/astro/test/fixtures/ssr-redirect/src/pages/secret.astro, packages/astro/test/ssr-redirect.test.js, pnpm-lock.yaml
- Changes Astro.redirect to use a 302 redirect instead of 301.
- 301 is permanent, but the use-case for Astro.redirect is to send someone to a login page, for example, and in that case you want the redirect to be temporary.
- New test added.
N/A
=> Make Astro.redirect use a 302 status code

.changeset/moody-crabs-stare.md, packages/astro/src/core/build/static-build.ts, packages/astro/src/vite-plugin-env/index.ts, packages/astro/test/fixtures/ssr-env/astro.config.mjs, packages/astro/test/fixtures/ssr-env/package.json, packages/astro/test/fixtures/ssr-env/src/components/Env.jsx, packages/astro/test/fixtures/ssr-env/src/pages/ssr.astro, packages/astro/test/ssr-env.test.js, pnpm-lock.yaml
- Defines `import.meta.env.SSR` to always be true. This ensures it's locked in during the build (in SSR mode that is).
- Fixes #3688
- Test added
=> Ensure import.meta.env.SSR is true in SSR mode

.changeset/early-teachers-vanish.md, packages/astro/src/jsx/renderer.ts, packages/astro/src/runtime/server/response.ts, pnpm-lock.yaml
- When upgrading to beta.55 on the docs site we were running into a max callstack issue. I assume it's because the page is large and it's possible that our streaming implementation's reader.read() implementation is leaky (or something). This change was tested on the docs site and fixes everything.
- Fixes https://github.com/withastro/astro/issues/3704
- Not captured in a unit test, but in the docs site.
N/A, bug fix
=> Simplified Response#text() implementation

examples/portfolio/src/components/MainHead.astro
This is the code Google Fonts officially provides.
The reason for adding a secound url is that the link:
https://fonts.googleapis.com/css2?family=Inter:wght@100&display=swap
lists src urls like this:
@font-face {
font-family: 'Inter';
font-style: normal;
font-weight: 100;
font-display: swap;
src: url(https://fonts.gstatic.com/s/inter/v11/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyeAZ9hiA.woff2) format('woff2');
unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
so for better performance both urls needs to be preconnected.
- Don't forget a changeset! …
=> improve performance by adding another preconnect

.changeset/eighty-turtles-drive.md, scripts/cmd/build.js
- Stop generating sourcemaps when building the monorepo in dev mode - prevents Vite console warnings for missing sourcemap files
- Resolves #3403 
N/A
N/A
=> Fix: prevent sourcemap warnings in monorepo "dev" mode

.changeset/fair-countries-perform.md
Adds a changeset to release `create-astro` which was missed in #3715
=> Add changeset to release `create-astro`

.changeset/lemon-fireants-film.md, packages/telemetry/src/project-info.ts
- Missed the `createAnonymousValue()` call when telemetry runs outside of a git repo
- N/A
- N/A
=> make sure anonymousProjectId is hashed in fallback, non-git case

packages/create-astro/src/index.ts
- Adds a code comment before the `main()` function where `create-astro` "messages" are defined.
- Directs to [installation instructions file in docs repo](https://github.com/withastro/docs/blob/main/src/pages/en/install/auto.md) which will mirror the exact flow and wording of `create-astro` wizard when https://github.com/withastro/docs/pull/867 is merged
- instructs anyone changing the steps or wording of `create-astro` to make a corresponding change in the docs if necessary
No test
Does not require a change to docs.
=> Added: reminder to update docs if create-astro flow or wording changes

packages/astro/src/@types/astro.ts
Added a type that can be used to type getStaticPaths in an easier fashion:
```ts
export const getStaticPaths: GetStaticPaths = async ({ paginate }) => {
return paginate(["Hello", "Astro"], { pageSize: 5 })
}
```
Previously, you needed to do this to type `getStaticPaths`:
```ts
export async function getStaticPaths({ paginate }: GetStaticPathsOptions): Promise<GetStaticPathsResult[]> {
return paginate(["Hello", "Astro"], { pageSize: 5 })
}
```
Which is a bit long, I think. You can still do it this way if you want to, though
Additionally fixed an issue with the type of `paginate` where it expected an empty array as a first parameter instead of an array of things. This PR also fixes some dead links in some descriptions
Types aren't tested (is that something possible? I wonder)
Updated links …
=> Improve types for getStaticPaths and fixes dead links

.changeset/sour-clocks-unite.md, packages/astro/src/cli/index.ts
- Config parsing was accidentally moved outside of a try-catch, so that config errors are no longer shown with a user-friendly presentation. This was just introduced in #3713.
- This PR fixes that specific problem, and also refactors the code to remove the need for individual try-catch blocks. The `throwAndExit()` function is meant to be a global handler, so now it handles all errors that come out of the CLI with a single try-catch.
- We already do unit test for config validation errors, but not through the CLI.
- I'm not sure if this is worth adding an entire fixture for, so I didn't touch tests for now.
- N/A
=> Fix an issue with unfriendly config validation errors

.changeset/light-moons-protect.md, packages/integrations/prefetch/src/index.ts
- Fixes the `@astrojs/prefetch` integration `name` property that apparently didn't get updated after using the lit integration as a template.
- Ran tests locally.
- Bugfix only, not a visible change.
=> Fix integration name (`prefetch` instead of `lit`)

.changeset/plenty-paws-divide.md, packages/astro/src/cli/index.ts
- We were not awaiting the final `throwAndExit()` handler, which caused error telemetry to never run. This didn't impact `DEBUG` mode so I didn't catch it originally 🤦 
- N/A
- N/A
=> await error reporter

.github/workflows/ci.yml
- I'm seeing PRs taking 15, 20+ minutes to complete CI
- This can be a huge efficiency loss when we're waiting around for CI to complete
- E2E tests seem to be a big contributor to this
- This change reduces E2E runs to just basic covers: 1 ubuntu and 1 windows 
- This is something we had to do to smoke tests in the past for the exact same reason
- Is test.
- N/A
=> Ci: improve times, reduce delay

.changeset/neat-yaks-hope.md, packages/integrations/image/components/Image.astro, packages/integrations/image/package.json, packages/integrations/image/src/index.ts, packages/integrations/image/src/loaders/sharp.ts
- Updates the integration to add `sharp` and `image-size` to the `vite.optimizeDeps` config
- Fixes a bug when resizing images - `sharp` requires all dimensions are provided as whole numbers
- Updates the file exports in the NPM package to support the `Image.astro` typescript imports at build time
All existing tests should pass
Bug fix only
=> Updates the images integration to automatically mark `optimizeDeps` for sharp

.github/workflows/format.yml
Bumps node's memory head size when running the code formatting CI job
CI updates only
N/A
=> Increases node memory during the CI format workflow

packages/integrations/image/src/endpoints/dev.ts, packages/integrations/image/src/endpoints/prod.ts
The CI `format` job gets stuck with a build break when the imports are reordered but the `@ts-ignore` comment isn't also moved to match
NA
NA
=> Manually correcting import ordering to unblock CI

.changeset/cyan-balloons-battle.md, examples/with-mdx/.vscode/extensions.json, examples/with-mdx/src/pages/index.mdx, packages/astro/src/jsx-runtime/index.ts
- `astro/jsx-runtime` used a symbol, which some other integrations can't handle, so I switched it to a string
- Update part of the example which wasn't working
Manually using `pnpm link`
Bug fix only
=> Update MDX example to address failure

.changeset/itchy-bottles-rhyme.md, packages/integrations/node/README.md
The example was suggesting `import deno from '@astrojs/node';` which doesn't work. It needs to be `import node from '@astrojs/node';`.
=> Fix example on `README.md` on @astrojs/node

.changeset/rare-elephants-add.md, packages/telemetry/src/project-info.ts
- An error that was meant to be handled was accidentally piped to the user
- N/A
- N/A
=> fix handled git error output accidentally being piped to the user

.changeset/hip-months-invent.md, packages/astro/src/runtime/server/index.ts, packages/astro/test/astro-head.test.js, packages/astro/test/fixtures/astro-head/src/components/Head.astro, packages/astro/test/fixtures/astro-head/src/pages/head-own-component.astro
- When putting a `<head>` into its own file, head contents (such as stylesheets) should be appended there.
- We have a `maybeRenderHead` function that exists for components with no head element. This function is intended to cover the case where a page has no explicit head at all.
- This function intends checks to see if a head has already rendered and if so, bail out.
- Because this function was synchronous, it would run before components higher in the tree, causing the bug.
- Maybe it be an async generator, like components are, ensures that it is put *in line* and doesn't run before stuff above it.
- Fixes https://github.com/withastro/astro/issues/3819
- Test added
N/A, bug fix
=> Ensure that maybeRenderHead runs last

.changeset/twenty-meals-train.md, packages/astro/src/runtime/server/astro-island.ts
Wraps our island `connectedCallback` in a 0ms timeout. This delays hydrate scripts until the component's children are fully mounted. `connectedCallback` _should_ handle this by definition, but safari has other ideas 😓 
N/A
N/A
=> Fix `client:visible` directive in safari

.changeset/ten-radios-rush.md, packages/astro/src/core/app/index.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/ssr-api-route.test.js
Discord comment:
> Okay, I hit a snag with our UTF-8 issue: after a triage call, we decided we should assign "charset=UTF-8" to the header of all API endpoints (in dev only) that use the { body } shorthand. Unfortunately, you can't assign a charset without also assigning a content type. 
> We could use text/plain; charset=utf-8, but this wouldn't seem valid .json endpoints. We could also infer application/json for the .json extension specifically, but this is a slippery slope for other content types we'd need to support 
> So yeah... not sure what behavior we want here 🤷‍♂️
> Oh interesting, sveltekit just says text/plain;charset=UTF-8 for any {body} shorthand, even for .json files in production 
- Resolves #3573
- Infer content type in dev and prod for `{ body }` shorthand using [mine …
=> Fix: Infer content type with charset in dev and prod

.changeset/nervous-swans-perform.md, packages/astro/src/core/create-vite.ts, packages/integrations/image/README.md, packages/integrations/image/package.json, packages/integrations/image/src/types.ts, packages/integrations/image/test/fixtures/basic-image/src/pages/index.astro, packages/integrations/image/test/image-ssg.test.js
- Makes it so you can do `import { Image } from '@astrojs/image';`
- Adds a export map condition `astro` that is used to specify a root for Vite.
- Tests updated.
- Updated the readme for astro/image.
=> Allow importing Image component from @astrojs/image

.changeset/rare-news-confess.md, packages/astro/astro-jsx.d.ts
This does many things to our JSX definitions, all improvements, hopefully!
- Fixed attributes needing numbers not accepting strings, especially ARIA attributes
- Added element-specific attributes instead of just a list of all possible attributes, this allow for better type checking (adding an attribute not allowed on a specific element but allowed on others will now show an error)
- Added some missing attributes 
Types aren't tested at the moment. When `astro check` get upgraded to use the latest language-server, it would be possible to create an absolutely MASSIVE Astro file with ALL the HTML elements attributes (with their possible values) and run the checks on it to make sure there's no errors
N/A
=> Improve JSX definitions

.changeset/funny-masks-yawn.md, packages/astro/src/@types/astro.ts
- Resolves #3691 
- Adds Adapter documentation heading for docs.astro.build. Also beefed up with links to relevant docs and more sell-y language 😉 
N/A
Need a redeploy to re-run docgen!
=> Docs: add adapter heading for configuration docs

.changeset/great-pants-chew.md, packages/astro/src/runtime/server/response.ts, packages/astro/test/fixtures/large-array/astro.config.mjs, packages/astro/test/fixtures/large-array/package.json, packages/astro/test/fixtures/large-array/src/components/Counter.jsx, packages/astro/test/fixtures/large-array/src/pages/index.astro, packages/astro/test/ssr-large-array.test.js, pnpm-lock.yaml
- Because node-fetch doesn't support streaming we have to handle `response.text()` and `response.arrayBuffer()` ourselves.
- Previous implementation was both inefficient (expanding an array) and apparently caused max call-stack errors when it was big enough.
- This new implementation just keeps all of the individual chunks and then later creates a Uint8Array at the end.
- This fixes a bug https://github.com/withastro/astro/issues/3802
- Fixes handling in Vercel which uses response.arrayBuffer()
- Test added, was failing and is now not.
N/A, bug fix
=> Better response.arrayBuffer() handling in Node

packages/astro/package.json, pnpm-lock.yaml
- Updates our `package.json` file to require `vite` `^2.9.14`
- Came up in discussing https://github.com/withastro/astro/pull/3428 with @userquin
CI
N/A
=> Bump `vite` minimum version

packages/integrations/cloudflare/README.md
- There was a broken Markdown link in the Cloudflare SSR adapter README.md
- It was mistakenly typed as (link)[URL] instead of the proper \[link\]\(URL\)
- This PR fixes that.
- Docs change only, no tests needed
- Updated README.md for Astro's Cloudflare SSR adapter
=> Fixed broken link in Cloudflare SSR adapter README

packages/astro/package.json, pnpm-lock.yaml
- Move `@babel/types` to `dependencies`
- Closes #3843
N/A
Bug fix only
=> fix(#3843): move @babel/types to dependencies

.changeset/breezy-ravens-sort.md, packages/integrations/deno/README.md, packages/integrations/image/README.md, packages/integrations/netlify/README.md, packages/integrations/node/README.md, packages/integrations/prefetch/README.md, packages/integrations/sitemap/README.md, packages/integrations/vercel/README.md
Miscellaneous small fixes caught while building the new system for showing the integration READMEs on the docs site.
- Remove a stray XML tag in the sitemap integration README. This stray tag crashes builds because micromark doesn’t expect tags to start with `<?`.
- Fix some broken links caught by the docs link checker
These are fairly minor changes to READMEs, so I haven’t included a changeset, but can do if you think these fixes should trigger a patch release.
n/a
n/a
=> Integration README fixes

.git-blame-ignore-revs
Adds a commit to git blame ignore file as mentioned in #3862 
None
Not needed
=> Ignore big formatting commit

.changeset/lucky-bottles-wait.md, packages/astro/src/core/add/index.ts, packages/integrations/cloudflare/package.json, packages/integrations/deno/package.json, packages/integrations/image/package.json, packages/integrations/lit/package.json, packages/integrations/mdx/package.json, packages/integrations/netlify/package.json, packages/integrations/node/package.json, packages/integrations/partytown/package.json, packages/integrations/preact/package.json, packages/integrations/prefetch/package.json, packages/integrations/react/package.json, packages/integrations/sitemap/package.json, packages/integrations/solid/package.json, packages/integrations/svelte/package.json, packages/integrations/tailwind/package.json, packages/integrations/turbolinks/package.json, packages/integrations/vercel/package.json, packages/integrations/vue/package.json
- Detect adapters and integrations by `package.json` keywords!
- `astro-integration` -> valid Astro integration
- `astro-adapter` -> valid Astro adapter
- Add `package.json` keywords across all official integrations and adapters
- Correctly set the adapter in your astro config instead of blindly adding to integrations
- Add warning + "continue?" prompt when installing third party integrations and adapters
- Remove `astro-` package naming requirement for third party integrations
TODO
Document magic "keywords" in the integrations API and adapter API references for package authors ❤️ 
https://github.com/withastro/docs/pull/946
=> [astro add] Support adapters and third party packages

.changeset/quiet-pugs-tie.md, packages/astro/src/runtime/server/astro-island.ts, packages/astro/src/runtime/server/index.ts
This ensures we hydrate SSR components that return `null`. This is common for dropdowns and sidebars that reveal conditionally.
N/A
N/A
=> Fix: hydrate components that return `null`

.changeset/quiet-bananas-obey.md, packages/integrations/image/components/Picture.astro
Fixing a copy/paste error in the new `<Picture />` component - it should default the img to `decoding="async"` instead of `eager`
Bug fix only
=> Updating the <Picture /> component to default to async image decoding

.changeset/nervous-points-confess.md, examples/portfolio/src/pages/projects.astro
I created a new Astro project with the `portfolio` template and noticed a JSX error in `src/pages/projects.astro` (an extra `'` after the `projects` prop), so this PR remove it.
I've also noticed that the dev server starts and render the page without any error/bug with this extra `'`, so this is not really a bug, more of a typo.
No test was added since this concern the portfolio example.
No doc was changed since this concern the portfolio example.
=> fix: portfolio example JSX error

.github/workflows/scripts.yml
- GitHub Actions change only
- Small fix to avoid running `scripts.yml` on irrelevant PRs
N/A
N/A
=> Ignore bundle size check for irrelevant PRs

.changeset/hungry-cougars-yell.md, packages/astro/src/vite-plugin-astro/compile.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/fixtures/virtual-astro-file/astro.config.mjs, packages/astro/test/fixtures/virtual-astro-file/package.json, packages/astro/test/fixtures/virtual-astro-file/src/pages/index.astro, packages/astro/test/fixtures/virtual-astro-file/src/plugin/my-plugin.mjs, packages/astro/test/hmr-css.test.js, packages/astro/test/virtual-astro-file.js, pnpm-lock.yaml
- Moves compilation to the `transform` hook.
- This allows defining Astro components as virtual modules in Vite plugins.
- Closes #3814
- Test added
N/A, bug fix
=> Allow defining Astro components in Vite plugins

.changeset/famous-moons-kick.md, .github/workflows/ci.yml, .gitmodules, examples/with-mdx/src/pages/index.mdx, package.json, packages/astro/package.json, packages/astro/src/vite-plugin-markdown/index.ts, packages/markdown/remark/package.json, packages/markdown/remark/src/ssr-utils.ts, pnpm-lock.yaml
- Remove `no-frozen` requirement from lockfile
- Remove `astro.build` and Astro docs installation. Still checking out via CI, will revisit in a future PR
- Add smoke test across example projects
- Remove `client:` directive from `with-mdx` example. This is causing an infinite build loop to debug separately
- Remove `@astrojs/markdown-remark/ssr-utils` that our generated markdown files directly imported. This caused a missing dependency issue since `@astrojs/markdown` isn't explicitly installed.
Testing CI
N/A
=> Fix: reintroduce smoke tests across example projects

.changeset/beige-lizards-scream.md, packages/astro/src/@types/astro.ts
This adds a `mode` field to the TypeScript definitions for `mode` in the configuration file.
Closes #3882 
This was tested locally
I've added a draft of what I think the docs could look like for this field. I've also opened [a GH issue to track this issue from a documentation perspective as well.](https://github.com/withastro/docs/issues/960)
=> fix: add TypeScript type and documentation for markdown "mode" config

.changeset/healthy-donuts-dream.md, packages/astro/test/astro-markdown-shiki.test.js, packages/astro/test/fixtures/astro-markdown-shiki/langs/src/pages/astro.astro, packages/astro/test/fixtures/astro-markdown-shiki/langs/src/pages/index.md, packages/markdown/remark/src/remark-shiki.ts
Fixes #3881
When a language that isn't registered by Shiki is used, show a warning instead of an error.
Added tests with a unknown language (it would be nice to analyze the logs, but I don't know how)
=> fix: don't throw when Shiki doesn't recognize a language

.changeset/weak-mangos-double.md, packages/astro-rss/src/index.ts, packages/astro-rss/test/rss.test.js
- Adds an error message whenever the required fields of the RSS plugin are missing.
- Part of #3846
- Test added
N/A, bug fix
=> Provide a better error message for when RSS is missing `link` field

packages/astro/src/@types/astro.ts
- Capitalizes a few errant "markdowns" that find their way into Docs.
- Also updates "if or not" to "whether or not" since I'm here.
- Also, admittedly a point of contention, but until we decide otherwise for the entire site: a straggling "front matter" -> "frontmatter"
No tests. Affects content on Docs site only.
This will update Docs automatically.
=> Astro Types for docs: capitalize Markdown

.changeset/many-terms-do.md, packages/markdown/remark/package.json, packages/markdown/remark/src/ssr-utils.ts
- Adds back a missing file that was removed as a patch, causing upstream to break
- Plan: release this as a patch, and then release a new minor with the file removed again (reverting this PR commit)
- N/A (existing tests)
- N/A
=> add back missing ssr-utils.ts file

.changeset/dirty-doors-call.md, packages/astro/src/runtime/server/index.ts, packages/astro/src/runtime/server/util.ts, packages/astro/test/astro-class-list.test.js, packages/astro/test/fixtures/astro-class-list/src/pages/component.astro, packages/astro/test/fixtures/astro-class-list/src/pages/index.astro
- Fixes #3920
- `class:list` wasn't ignoring `false`, it was stringifying it to `class="false"`
- `class:list={false}` was outputting `class=""`, not it outputs `''`
Tests updated
=> Handle `false` properly in `class:list`

packages/astro/src/@types/astro.ts
- Exports `AstroComponentFactory` for `tsc` validation to pass
Just CI should pass
No change in docs is needed.
=> fix: export AstroComponentFactory for tsc validation to pass

.changeset/purple-flowers-arrive.md, examples/with-mdx/src/pages/index.mdx, packages/astro/src/jsx-runtime/index.ts, packages/astro/src/jsx/babel.ts, packages/astro/src/jsx/server.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/runtime/server/jsx.ts, packages/astro/src/vite-plugin-jsx/index.ts
- Our `with-mdx` example was hanging on build, and occasionally on dev!
- This was caused by a few things...
- We were swallowing errors from the built-in JSX renderer, causing an infinite recursive loop
- We weren't passing along `metadata` from our Babel plugin, so the build was never going to find hydrated components.
- As a bonus, `client:only` wasn't really supported in `.mdx` files. Now it is!
Tested manually, but this should fix our fixtures
Bug fix only
=> Handle metadata for MDX files during build

.changeset/quiet-toys-type.md, packages/astro/e2e/shared-component-tests.js, packages/astro/src/core/render/dev/css.ts, packages/astro/src/core/render/dev/index.ts, packages/astro/src/core/render/dev/scripts.ts, packages/astro/src/core/render/dev/vite.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/runtime/server/metadata.ts, packages/astro/test/astro-scripts.test.js, packages/astro/test/fixtures/astro-scripts/src/components/Glob/GlobComponent.astro, packages/astro/test/fixtures/astro-scripts/src/pages/glob.astro
- This uses the Vite graph to discover scripts that need to be hoisted, similar to how we do so for styles.
- Previously was using the Astro metadata `hoistedScriptPaths()` method, but this does not traverse through Astro.globs, or through JS re-export pattern. Using the Vite graph ensures we get all hoisted scripts.
- This is how it's done in the build as well.
- Bug reported on Discord: https://discord.com/channels/830184174198718474/996921397978857522
- Test added
N/A, bug fix
=> Hoist Astro.globbed hoisted scripts in dev

.changeset/nice-toes-cough.md, packages/astro/astro-jsx.d.ts, packages/astro/src/@types/astro.ts
In a recent PR we fixed an import to `AstroComponentFactory`, this had the side effect of making our expected type for `Element` too strict (due to TypeScript weirdness), which lead to users encountering errors when using JSX frameworks
Also, this PR fixes the JSX definitions not working properly in the monorepo (finally!)
Fix https://github.com/withastro/astro/issues/3945
Tested manually, also ran the language-server test suite with this changes and everything passed
N/A
=> Fix expected types for Element in our JSX definitions

.changeset/warm-news-fly.md, packages/astro/components/Code.astro, packages/astro/components/Debug.astro, packages/astro/test/code-component.test.js, packages/astro/test/fixtures/code-component/package.json, packages/astro/test/fixtures/code-component/src/pages/index.astro, pnpm-lock.yaml
- Makes the Debug components styles be inlined, to prevent them from being added to pages that use the Code component but not Debug.
- Test added
N/A, bug fix
=> Moves Debug component's styles to be inlined

packages/astro/test/cli.test.js
Unfortunately, TypeScript, on Windows, in CI, in a big monorepo is a recipe for TypeScript (so `astro check`) to take a very long time. This was causing CI to fail randomly so this PR augment the timeout so this shouldn't happen
N/A
N/A
=> Make timeout higher for astro check tests as TS is slow on Windows in CI

.changeset/lemon-tools-rescue.md, packages/create-astro/src/index.ts
Brings back support for using remote GitHub repos with `create-astro`
Tested locally by cloning the `cassidoo/shopify-react-astro` repo.  I think the automated test was disabled to avoid reliability and network delay issues in CI runs, leaving it disabled for now
None (feature is already documented as supported)
=> Adds back `create-astro` support for GitHub repos

.changeset/old-walls-draw.md, packages/astro/astro-jsx.d.ts
Small fix. Running `astro check` on the docs made me realize that [the `media` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color) was missing from the Meta element definition
N/A
=> Add missing media attribute on MetaHTMLAttributes

.changeset/cold-eyes-run.md, packages/astro/src/core/add/index.ts
Adds missing export keyword to astro config file stub created by the add CLI command.
Did not test explicitly, I think this is pretty self-explanatory. The add command seems to be experimental and not covered by tests.
No docs change, bugfix.
=> fix: add export keyword to file stub

.github/workflows/ci.yml
Temporarily remove astro.build from Smoke pipeline. Vite 3 was merged before smoke tests were re-run, and we need time to properly debug!
=> TEMPORARY Chore: remove astro build from smoke

.changeset/wet-wombats-prove.md, packages/astro/src/cli/index.ts, packages/astro/src/core/config.ts
- Adds warning log to restart the server when 1. editing, 2. deleting, or 3. renaming a config file
- Restarts the dev server when a new config file is **added**. This should be nice for projects using `astro add` to programmatically add a config!
- Edge case: if you delete a config and _add it back_ while the dev server is running, the dev server will not restart and a warning will not be logged. If we supported this, we could run into all sorts of issues with old config caches we haven't busted. Changing a config's file extension is correctly handled with a warning though!
https://user-images.githubusercontent.com/51384119/179629703-37a9ea90-757f-4daf-912c-21c7480b143c.mov
N/A
N/A
=> Feat: log warning on `astro.config` change, restart server on `astro.config` added

.changeset/chatty-bikes-sin.md, packages/integrations/image/README.md, packages/integrations/image/components/Picture.astro, packages/integrations/image/test/fixtures/basic-picture/src/pages/index.astro, packages/integrations/image/test/picture-ssg.test.js, packages/integrations/image/test/picture-ssr.test.js
Closes #3909
This updates the `<Picture />` component to pass any unused attributes directly to the `<img />` element
Current behavior is that the attributes are added to the `<picture>` but this is a really uncommon use case **and** breaks accessibility since there is no way currently to add `alt` to the picture's `img`
Tests updated to verify custom `<img />` attributes are included
Integration's README updated with a note on how to add attributes to the picture's `<img>` element
=> <Picture> component should pass all unknown attributes to the <img> element

.changeset/breezy-llamas-behave.md, packages/astro/src/cli/check/print.ts
The language server returns partial URLs for files during `astro check`, as such they need to be properly decoded and transformed to paths before being shown or some characters won't show properly. Ultimately, this could be handled better in the language server itself (by, for instance, return full URLs instead of partials ones), but this is a fine fix too
Before
After
N/A
=> Fix `astro check` file paths not handling URL paths correctly

.changeset/loud-apes-flash.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/config.ts, packages/astro/src/core/dev/index.ts, packages/astro/src/core/logger/core.ts, packages/astro/src/core/util.ts, packages/astro/test/config-validate.test.js
- Removes flags for SSR and integrations.
- Removes restrictions on 3rd party usage.
- Removes warnings.
- Tests updated
N/A
=> Removes warnings / flags for integrations and ssr

.changeset/lovely-lions-attend.md, packages/integrations/svelte/src/editor.cts
This changes the shape of the generated TSX for Svelte components to be more in line with how Svelte's tooling actually work
Previously, what we did was skip over every `svelte2tsx` type and just make our own type from `render().props`, this works for getting a list of the props, but it doesn't work for optional props as those are still included in the list and we don't have the needed type info to know it's optional or not due to how optional props work in Svelte
Now we use `svelte2tsx`'s `__sveltets_1_partial` return type, which through TS trickery return the proper types and information for all kinds of situations
Fix https://github.com/withastro/language-tools/issues/314
Tested manually against https://github.com/withastro/language-tools/pull/344
N/A
=> Properly support and type optional props in Svelte components

.changeset/mighty-poets-prove.md, packages/astro/package.json, packages/integrations/lit/src/index.ts, pnpm-lock.yaml
- Vite 3.0.1 made it so you can't use `external` for non-main entrypoints in packages.
- In our case we can externalize the entire package.
- Related to https://github.com/vitejs/vite/issues/9275
- lit-element test failed in 3.0.1 but passes not.
N/A, bug fix.
=> Make the Lit integration be compat with Vite 3.0.1

packages/astro/astro-jsx.d.ts, packages/astro/src/runtime/server/index.ts
- Follow-up to https://github.com/withastro/astro/pull/3706
- Adds support for `style={{ color: 'red' }}` props
- Importantly, does not handle number => `px` string conversion for you. The logic in React that handles this is massive, and it's a convenience more than anything. Preact gets away with requiring explicit units.
Covered by #4002 
Not going to document this as it's a compat feature
=> Support objects for `style` attribute

.changeset/moody-teachers-knock.md, packages/integrations/image/README.md, packages/integrations/partytown/README.md, packages/integrations/prefetch/README.md, packages/integrations/sitemap/README.md, packages/integrations/tailwind/README.md
Removes references to astro add being "experimental" in integration package READMEs ("Other" category).
Closes [Docs 1029](https://github.com/withastro/docs/issues/1029)
No tests; documentation only.
Updates documentation
=> [READMEs] removed "experimental" from astro add instructions

.changeset/spotty-apricots-deny.md, packages/astro/src/vite-plugin-config-alias/index.ts, packages/astro/test/alias-tsconfig.test.js, packages/astro/test/fixtures/alias-tsconfig/astro.config.mjs, packages/astro/test/fixtures/alias-tsconfig/package.json, packages/astro/test/fixtures/alias-tsconfig/src/components/Client.svelte, packages/astro/test/fixtures/alias-tsconfig/src/pages/index.astro, packages/astro/test/fixtures/alias-tsconfig/tsconfig.json, pnpm-lock.yaml
- Fixes the tsconfig alias plugin. 
- Bad typing caused it :(
- Closes https://github.com/withastro/astro/issues/3835
- Test added
N/A, bug fix
=> Fixes using tsconfig to set aliases

packages/astro/src/core/errors.ts
- Provides a hint for `undefined` errors when hoisting exports
- This is more actionable than just `ReferenceError: X is not defined`, since this is likely caused by our export hoisting
Tested manually, we don't have tests for hints
Part of https://github.com/withastro/docs/pull/1001
=> Provide hint for `undefined` with hoisted exports

.changeset/rotten-candles-count.md, packages/integrations/vercel/README.md, packages/integrations/vercel/src/edge/adapter.ts, packages/integrations/vercel/src/serverless/adapter.ts, packages/integrations/vercel/src/static/adapter.ts
Removed requirement for `ENABLE_VC_BUILD=1`, since Build Output v3 is now stable. [More info here](https://vercel.com/blog/build-output-api).
=> feat(vercel): remove requirement of `ENABLE_VC_BUILD=1`

.changeset/gentle-mails-mate.md, packages/integrations/image/src/metadata.ts
Update the metadata retrieval method used by the image integration to take the EXIF orientation flag into account.
An example of this technique is shown in the Sharp docs (3rd example): <https://sharp.pixelplumbing.com/api-input#examples>
The `image-size` module being used here similarly returns `orientation` if found.
Not tested yet — would need an image with the flag to do that.
No docs needed as this is effectively a bug fix.
=> Handle EXIF orientation flag

.changeset/smooth-seahorses-hear.md, packages/astro/src/core/app/node.ts, packages/integrations/node/package.json, packages/integrations/node/src/server.ts, packages/integrations/node/test/api-route.test.js, packages/integrations/node/test/fixtures/api-route/package.json, packages/integrations/node/test/fixtures/api-route/src/pages/recipes.js, packages/integrations/node/test/test-utils.js, pnpm-lock.yaml
- Updates the Node adapter to accept the request body.
- Closes https://github.com/withastro/astro/issues/3619
- Tests added
N/A, bug fix
=> Fixes Node adapter receiving a request body

.changeset/young-radios-call.md, examples/docs/src/components/PageContent/PageContent.astro, examples/docs/src/components/RightSidebar/MoreMenu.astro, examples/docs/src/components/RightSidebar/RightSidebar.astro, examples/docs/src/components/RightSidebar/TableOfContents.tsx, examples/docs/src/styles/index.css, packages/astro/env.d.ts, packages/astro/src/@types/astro.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/markdown/remark/src/index.ts, packages/markdown/remark/src/rehype-collect-headings.ts, packages/markdown/remark/src/types.ts
This PR renames the `getHeaders()` function to `getHeadings()`. According to the HTML spec, these are headings. "headers" are not part of the HTML spec. MDN also uses "headings" to refer to tags `h1` through `h6`.
CI passes
This change deprecates one function in favor of the other without breaking things. 
Docs PR: https://github.com/withastro/docs/pull/1107
=> Rename Markdown util `getHeaders()` to `getHeadings()`

.changeset/chilled-pandas-confess.md, packages/astro/e2e/fixtures/lit-component/src/components/Counter.js, packages/astro/e2e/fixtures/lit-component/src/pages/index.astro, packages/astro/e2e/fixtures/lit-component/src/pages/solo.astro, packages/astro/e2e/lit-component.test.js, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/vite-plugin-analyzer.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/vite-plugin-scripts/index.ts
- The astro-scripts plugin was conditionally building out the before-hydration script only if it thought it needed to. This condition was based on how the build previously worked but no longer does, resulting in this script never being generated.
- Changed it so that we always build the before-hydration script if there is one to build. It will only be used by components that need it anyways (it's dynamically imported), so there's no problem building it.
- Closes #3785
- e2e Lit tests re-enabled.
- Added test to ensure there's only 1 instance of this component.
N/A, bug fix.
=> Build the before-hydration script

.changeset/large-seas-drum.md, packages/astro/src/core/create-vite.ts, packages/astro/src/vite-plugin-markdown/index.ts
- Adds warning when attempting to read from `content.astro.headers`.
- Adds warning when using `setup:` in frontmatter without the astroFlavoredMarkdown legacy flag enabled.
Just manually
N/A
=> Add warnings on markdown deprecations

packages/astro/src/@types/astro.ts
Change to use `@version` to create the `<Since />` component for docs. (not `@since`)
Also, quick sentence edit.
No tests, affects Docs autogenerated content only.
Will update Docs automatically.
=> [docs content] use "version" not since

.changeset/khaki-tables-design.md, packages/integrations/image/package.json, packages/integrations/image/src/build/ssg.ts, packages/integrations/image/src/build/ssr.ts, packages/integrations/image/src/endpoints/prod.ts, packages/integrations/image/src/lib/get-picture.ts, packages/integrations/image/src/utils/images.ts, packages/integrations/image/src/utils/metadata.ts, packages/integrations/image/src/utils/paths.ts, packages/integrations/image/src/vite-plugin-astro-image.ts, pnpm-lock.yaml
Closes #4041 
This removes the `fileURLToPath` dependency from the SSR production endpoint used by `@astrojs/image`
All existing SSR tests should pass
=> Removes `fileURLToPath` dependency from `@astrojs/image` SSR production endpoint

.changeset/great-insects-beam.md, packages/astro/test/fixtures/tailwindcss/astro.config.mjs, packages/astro/test/fixtures/tailwindcss/package.json, packages/astro/test/fixtures/tailwindcss/src/pages/mdx-page.mdx, packages/astro/test/tailwindcss.test.js, packages/integrations/mdx/src/index.ts, pnpm-lock.yaml
- This is a short-term fix to add basic script injection handling to the MDX integration, to unblock MDX + Tailwind.
- I call it short term because this is code that we've identified as a copy-paste risk that I've now pasted into a third place. On top of that, it is missing some logic to only inject the page script on MDX pages, and not non-page MDX files. That is considered a larger regression that will probably need a larger refactoring to solve for. In the meantime, this unblocks a v1.0 RC release.
- With this I now see tailwind working with `.mdx`, `.md (legacy)`, and `.md (current)`
- Added a test.
- N/A
=> Fix MDX + Tailwind, add support for injected page-ssr scripts to MDX extension

.changeset/old-stingrays-smoke.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/page-data.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/types.ts, packages/astro/test/astro-get-static-paths.test.js, packages/astro/test/fixtures/lit-element/src/pages/[page].astro, packages/astro/test/fixtures/routing-priority/src/pages/de/index.astro, packages/astro/test/lit-element.test.js, packages/astro/test/routing-priority.test.js
- The call to `getStaticPaths` during the build is moved to the end of the process, during page generation.
- This prevents us from ever needing to call `vite.ssrLoadModule` anywhere in the build now. We are 100% completely static.
- This should improve performance as we are no longer double-building this code.
- This also fixes a bug with Lit and `getStaticPaths`. Before this change if you use a Lit element in a page behind getStaticPaths you would get a `window is undefined` error. This was because getStaticPaths was being called upfront, when the renderer had not yet run, and therefore the shim was not applied. Now it happens as it should.
- Closes https://github.com/withastro/astro/issues/3951
- Tests added
N/A, bug fix.
=> Move getStaticPaths call to happen during generation

.changeset/slow-terms-repeat.md, packages/astro/src/core/app/node.ts, packages/integrations/node/test/api-route.test.js, packages/integrations/node/test/fixtures/api-route/src/pages/binary.ts
- Allows request bodies to be binary data.
- Closes #4053
- Test added
N/A
=> Fixes binary data request bodies in the Node adapter

.changeset/lucky-phones-mix.md, packages/integrations/svelte/src/index.ts
- This warning is shown in svelte: `[vite-plugin-svelte] hmr is enabled but compilerOptions.dev is false, forcing it to true`
- This sets hot to false when not in dev, getting rid of the warning.
Just manually since it's a warning that can't be easily unit-tested.
N/A
=> Prevent Svelte HMR warning during the build

packages/astro/package.json, packages/astro/test/fixtures/markdown/src/pages/entities.md, packages/astro/test/markdown.test.js, packages/markdown/remark/src/rehype-escape.ts, packages/markdown/remark/test/entities.test.js, pnpm-lock.yaml
- The underlying bug was fixed in the compiler. This adds tests for the more specific scenario that was reported.
- Closes https://github.com/withastro/astro/issues/3916
- Astro and remark plugin tests added.
N/A
=> Add tests for markdown content escaping

.changeset/giant-dolls-reply.md, packages/integrations/cloudflare/package.json, packages/integrations/cloudflare/src/index.ts, packages/integrations/cloudflare/test/fixtures/no-output/astro.config.mjs, packages/integrations/cloudflare/test/fixtures/no-output/package.json, packages/integrations/cloudflare/test/no-output.test.js, packages/integrations/cloudflare/test/test-utils.js, packages/integrations/vercel/package.json, packages/integrations/vercel/src/serverless/adapter.ts, packages/integrations/vercel/test/fixtures/no-output/astro.config.mjs, packages/integrations/vercel/test/fixtures/no-output/package.json, packages/integrations/vercel/test/fixtures/no-output/src/pages/index.astro, packages/integrations/vercel/test/no-output.test.js, packages/integrations/vercel/test/test-utils.js, pnpm-lock.yaml
- Throw an error in these adapters when `output` config is set to static.
- This problem was reported by multiple people in Discord that did not realize you needed the config.
- Closes https://github.com/withastro/astro/issues/4066
- Tests added for both.
None
=> Add errors to cloudflare/vercel adapters when no output config

.changeset/clever-nails-pump.md, packages/astro/src/core/create-vite.ts
- Adds `'@fontsource/*'` to always be part of `noExternal` config.
- Fixes https://github.com/withastro/astro/issues/4071
- tested manually
- we have a fontsource mocha test, but because of the monorepo it doesn't get loaded the same way as in a real app :/
N/A, bug fix
=> Add fontsource packages to always be noExternal

.changeset/shy-kids-hug.md, packages/astro/src/core/render/result.ts, packages/integrations/cloudflare/package.json, packages/integrations/cloudflare/src/index.ts, packages/integrations/cloudflare/test/basics.test.js, packages/integrations/cloudflare/test/fixtures/basics/astro.config.mjs, packages/integrations/cloudflare/test/fixtures/basics/package.json, packages/integrations/cloudflare/test/fixtures/basics/src/pages/index.astro, packages/integrations/cloudflare/test/test-utils.js, pnpm-lock.yaml
- Need to shim `process` in cloudflare like we do in Deno and other non-Node environments.
- Closes https://github.com/withastro/astro/issues/4060
- Tests added, run `wrangler dev` which shows the same error.
N/A
=> Fixes cloudflare throwing over process

packages/astro/README.md
`Contributors Guide` was assigned a wrong link.
No test involved.
=> Fix readme link

.changeset/quick-onions-itch.md, packages/astro/src/@types/astro.ts
- Add `url` and `file` properties to `MarkdownContent` type
N/A
[Current docs](https://docs.astro.build/en/guides/markdown-content/#markdown-layouts) indicates that `MarkdownContent` type should have properties `url` and `file`.
=> Update MarkdownContent type

packages/integrations/mdx/README.md
Adds a short section explicitly on layouts to the `@astrojs/mdx` README to have a place for Support Squad to point to. Feel free to edit to taste, or to PR later, but we're starting to get this question specifically about layouts A LOT now. So having *something* we can just link to is helpful, and I'm pretty sure this is at least working and correct.  😅 
- includes `export {default} from '../../layouts/BaseLayout.astro';` option, with link to [MDX docs on layouts](https://mdxjs.com/docs/using-mdx/#layout) for layouts that do not need to receive props.
- includes and gives an example of importing and wrapping MDX content in a `<Layout {...frontmatter}>` component, passing all frontmatter props to the layout.
Not tested. For Docs.
Will automatically update integration docs.
=> [docs content] MDX layouts

.changeset/silent-files-promise.md, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/src/utils.ts, packages/integrations/mdx/test/fixtures/mdx-get-static-paths/src/content/1.mdx, packages/integrations/mdx/test/fixtures/mdx-get-static-paths/src/pages/[slug].astro, packages/integrations/mdx/test/mdx-get-static-paths.test.js
- Makes sure we always provide `url` and `file` for MDX, like we do with md.
- Closes https://github.com/withastro/astro/issues/4074
- Tests added
N/A, bug fix
=> Ensure file and url are always present in MDX for Astro.glob

.changeset/rich-months-develop.md, packages/markdown/component/Markdown.astro
The language-server doesn't support an Astro component just being a JSX expression. This is fixed in the new TSX output, however until then, importing the Markdown component leads to an error for users, so might as well do this temporary fix by wrapping it in a Fragment
N/A
=> Fix shape of Markdown component to work with the language-server

.changeset/ninety-news-change.md, packages/astro/e2e/lit-component.test.js, packages/astro/src/@types/astro.ts, packages/astro/src/core/render/result.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/runtime/server/jsx.ts, packages/astro/src/runtime/server/scripts.ts, packages/astro/test/fixtures/hydration-race/astro.config.mjs, packages/astro/test/fixtures/hydration-race/package.json, packages/astro/test/fixtures/hydration-race/src/components/Deeper.astro, packages/astro/test/fixtures/hydration-race/src/components/One.jsx, packages/astro/test/fixtures/hydration-race/src/components/Wrapper.astro, packages/astro/test/fixtures/hydration-race/src/pages/index.astro, packages/astro/test/hydration-race.test.js, packages/integrations/cloudflare/test/basics.test.js, packages/integrations/cloudflare/test/test-utils.js, pnpm-lock.yaml
- The way that we determine to add a hydration directive inline script is to see if the `result` object has already had a script for that directive yet. 
- However this determination happened when rendering a component. Because of parallel rendering it was possible for a script to be added *after* an island that needs it, resulting in bugs.
- This change makes it so that we add hydration scripts in `renderPage`. This ensures we make the determination serial, and add it as soon as possible.
- Fixes a bug reported in discord: https://discord.com/channels/830184174198718474/1001950585135841301
- Test added to ensure the hydration script is added before the first island.
N/A, bug fix.
=> Prevent hydration scripts from being rendered in the wrong order

.changeset/witty-crews-worry.md, packages/create-astro/src/index.ts, packages/integrations/mdx/README.md, packages/integrations/mdx/package.json, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/src/utils.ts, packages/integrations/mdx/test/fixtures/mdx-frontmatter/src/layouts/Base.astro, packages/integrations/mdx/test/fixtures/mdx-frontmatter/src/pages/index.mdx, packages/integrations/mdx/test/mdx-frontmatter.test.js, pnpm-lock.yaml
- Support `layout` frontmatter property 🥳 
- Pass YAML frontmatter to layouts via `content` property
Add test for layouts and `content` property
Update layout recommendations in README
=> feat: support `layout` in MDX frontmatter

.changeset/gold-olives-cover.md, packages/astro/src/core/routing/index.ts, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/core/routing/match.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/astro-get-static-paths.test.js, packages/astro/test/fixtures/routing-priority/astro.config.mjs, packages/astro/test/fixtures/routing-priority/integration.mjs, packages/astro/test/fixtures/routing-priority/src/[id].astro, packages/astro/test/fixtures/routing-priority/src/_to-inject.astro, packages/astro/test/fixtures/routing-priority/src/pages/[page].astro, packages/astro/test/fixtures/routing-priority/src/pages/[slug].astro, packages/astro/test/fixtures/routing-priority/src/to-inject.astro, packages/astro/test/routing-priority.test.js, packages/integrations/mdx/README.md
Closes #3809 
- dev server now finds all page templates that match the requested URL and checks each one in priority order
- in SSR, users will get an error if more than one page template matches a URL in `astro dev`
- in SSG, the dev server now prioritizes URLs the same as `astro build`
- injected routes are now sorted with a higher priority than all user-provided page routes
- all existing `routing-priority` tests pass
- added tests for prioritizing injected routes
- added tests for multiple page routes matching the same URL
N/A bug fix only
=> Updates the dev server to handle multiple routes matching the same URL

packages/integrations/image/README.md
Changes some code formatting in 2 places to fix integration with Docs. Failing Docs checks, and I think it's do do with `'` used instead of `` ` ``
Not tested! Not even sure I got the second one right. But, these would seem to be the potential problem areas causing errors. For @tony-sull to review!  😄 
Will auto-update Docs integration content
=> [docs content] Image README formatting

packages/astro/src/core/add/index.ts, packages/astro/src/core/app/index.ts, packages/astro/src/core/logger/console.ts, packages/astro/src/core/logger/core.ts, packages/astro/src/core/logger/node.ts, packages/astro/src/core/preview/index.ts, packages/astro/test/static-build.test.js
- This removes a previously undiscovered transitive dependency on the npm `util` package (polyfilling the node `util` package when deploying to SSR)
- Turns out we weren't actually using this feature anywhere, and creating a more strict type signature actually found a couple of small errors in the code.
- This will let us remove the `util` dependency entirely via https://github.com/withastro/astro/pull/4096, saving [~ 44 total deps](https://npm.anvaka.com/#/view/2d/util) from our dep tree. 
- cc @Princesseuh 
- Covered by existing tests.
- N/A
=> remove unused util polyfill dependency

.changeset/dull-radios-sparkle.md, packages/astro/src/core/config.ts, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/fixtures/mdx-page/astro.config.ts, packages/integrations/mdx/test/fixtures/mdx-page/package.json, packages/integrations/mdx/test/mdx-page.test.js, pnpm-lock.yaml
- Use `vite.createServer().ssrLoadModule` to load the config, rather than using preloads plugins.
- Only do this when Proload fails, as Vite transforms modules in ways that can break them.
- Fixes https://github.com/withastro/astro/issues/4078
- Test added
N/A
=> Load configs with Vite when loading with Proload fails

packages/integrations/cloudflare/README.md
- This changes the wording "Write your code in Astro/Node" to "Write your code in Astro/Javascript"
- In my opinion, this change is good for a number of reasons.
- Cloudflare Pages is not Node and never will be: Node modules such as `fs`, `path` and `http` are missing and while Astro might be able to polyfill some of them there's really no way to polyfill a filesystem or a couple of other Node-specific things.
- With Astro you use `fetch` and similar APIs to make HTTP requests rather than 
- "Javascript" is more generic than "Node" and better represents the way you code in Astro. You don't use a router like Node's `http` server or Express and similar (like people ask us often on the Cloudflare Developers Discord), you use the framework's built-in routing and primitives.
- I'm totally open …
=> Clarify README on Cloudflare adapter

.changeset/weak-crabs-pump.md, packages/astro/src/core/render/dev/vite.ts
- I hit a very strange bug during `dev`... every page included every hoisted script in the project, even though the component was not imported.
- Turns out this was because of the way our `crawlGraph` utility interacted with Tailwind.
- Tailwind treats every component in the project as an `importedModule` of the `@tailwind base;` entrypoint. We were crawling these because they seem like valid imports.
- The fix is to check if the entrypoint is a style, and then only crawl the `importedModules` that are also styles. This sidesteps the over-eager hoisting.
Tested manually, there's not a great way to test this edge case.
N/A, bug fix
=> Do not crawl non-style deps imported by styles

.gitpod.Dockerfile, .gitpod/gitpod-setup.sh
- After #3747 was merged,
- `Open in Gitpod` button in https://astro.new ended up in a Gitpod workspace with errors.
- This PR installs the latest version of pnpm.
- Use the fork branch of this PR, with the name of example you would like to test, here's how to test `framework-vue` -
https://gitpod.io/#https://github.com/shaal/astro/tree/gitpod--fix-pnpm-version-error/examples/framework-vue
- After a few seconds, Gitpod workspace would open with the example you selected displayed in a preview
- After running `pnpm run build`, there are 2 minor changes in `packages/webapi/mod.d.ts`, I think these changes are not related to this PR, but probably should be committed to the repo.
This PR does not change anything in Astro itself, so no documentation update is needed.
=> Gitpod  - fix pnpm version error

.changeset/seven-suits-sit.md, packages/astro/src/core/app/node.ts
- With latest change astro always set body on node integration Request
With the default SSR it does not works and get error, after it works.
Error reported:
```
TypeError: Request with GET/HEAD method cannot have body.
at new Request (node:internal/deps/undici/undici:5599:17)
at createRequestFromNodeRequest (file:///Users/e01/Workspace/astro-ssr-demo/node_modules/astro/dist/core/app/node.js:11:16)
at file:///Users/e01/Workspace/astro-ssr-demo/node_modules/astro/dist/core/app/node.js:40:60
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async handler (file:///Users/e01/Workspace/astro-ssr-demo/node_modules/@astrojs/node/dist/server.js:14:30)
```
=> Do not send body with HEAD and GET on node integration

.changeset/smart-geese-grab.md, packages/astro/package.json, pnpm-lock.yaml
- Fixes https://github.com/withastro/astro/issues/3449
- This stackblitz: https://stackblitz.com/edit/github-exuehl?file=astro.config.mjs
- The above can't be turned into a unit test due to monorepo. Tried doing it but it passes even without the change.
N/A, bug fix
=> Upgrade Vite to 3.0.4

packages/integrations/mdx/package.json
[This page](https://docs.astro.build/en/guides/integrations-guide/) is autogenerated based on the packages in this repo and said packages' tags. Removing the renderer tag here should stop it from appearing in the UI Framework category.
- Removes `renderer` tag from `@astrojs/mdx` package
Only changes some npm package metadata; no test updates are needed.
This will fix an issue with the docs that was discussed [here](https://discord.com/channels/830184174198718474/853350631389265940/1003857322885517362) (discord). This fix should be visible as soon as the docs site is deployed again.
=> Remove renderer tag to fix a docs issue

.changeset/lazy-cameras-float.md, packages/astro/src/runtime/server/index.ts, packages/astro/test/fixtures/multiple-renderers/astro.config.mjs, packages/astro/test/fixtures/multiple-renderers/package.json, packages/astro/test/fixtures/multiple-renderers/renderers/one/index.mjs, packages/astro/test/fixtures/multiple-renderers/renderers/one/package.json, packages/astro/test/fixtures/multiple-renderers/renderers/one/server.mjs, packages/astro/test/fixtures/multiple-renderers/renderers/two/index.mjs, packages/astro/test/fixtures/multiple-renderers/renderers/two/package.json, packages/astro/test/fixtures/multiple-renderers/renderers/two/server.mjs, packages/astro/test/fixtures/multiple-renderers/src/pages/index.astro, packages/astro/test/multiple-renderers.test.js, pnpm-lock.yaml
- When there are multiple renderers, like React and Solid, and the first throws, we continue to check for other renderers.
- However, previously we would always rethrow if any error was found. We should only do that if no renderer is found. This fixes that.
- Fixes bug reported in Discord https://discord.com/channels/830184174198718474/1001948001599770724
N/A, bug fix
=> Only rethrow renderer error when no renderer found

.changeset/funny-poems-learn.md, packages/astro/src/core/messages.ts, packages/astro/src/vite-plugin-astro/hmr.ts, packages/astro/src/vite-plugin-astro/index.ts
- Removes full reloads when updating `style` block inside of `.astro` files
- Avoids firing HMR events when a file is saved without changes.
- Improves HMR logs
Covered by existing tests
N/A
=> Improve style HMR

.changeset/hip-glasses-beg.md, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/fixtures/mdx-frontmatter/src/layouts/Base.astro, packages/integrations/mdx/test/fixtures/mdx-frontmatter/src/pages/with-headings.mdx, packages/integrations/mdx/test/mdx-frontmatter.test.js
- Add `frontmatter` alongside `content` to MDX layout props. Clears up naming confusion while supporting legacy behavior!
- Add `headings` to layout props, based on the `getHeadings()` import property
Test `headings` and new `frontmatter` properties
To-be-updated when new markdown renderer lands 👍
=> [MDX] Add `headings` and `frontmatter` to layout props

.changeset/neat-badgers-bow.md, packages/astro/package.json, packages/integrations/image/package.json
> Update on the `astro/dist` import problem: This may be bigger than we realized, it seems to be impacting all Windows users in two different use-cases:
> - `injectRoute` + `entryPoint: @astrojs/image/endpoints/dev`
> - renderers + `serverEntrypoint: astro/jsx/server.js` 
> 
> From some digging, I think this is a Vite 3 issue. The one thing that both of these have in common is that they are both eventually passed *already-resolved* to `viteServer.ssrLoadModule(id)` in our codebase. I think this is what causes the error on Windows, where Vite tries to resolve `id` itself via `ensureEntryFromUrl ` and fails because its resolved form is not a valid package export. 
> 
> None of the other framework renderers hit this because their export maps are 1:1 with the file location. ex: …
=> fix windows package export

.changeset/curvy-donuts-build.md, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/test/css-order.test.js, packages/astro/test/fixtures/css-order/package.json, packages/astro/test/fixtures/css-order/src/components/CommonHead.astro, packages/astro/test/fixtures/css-order/src/pages/one.astro, packages/astro/test/fixtures/css-order/src/pages/two.astro, packages/astro/test/ssr-response.test.js, pnpm-lock.yaml
- Fixes bug where `output: 'server'` CSS was in a different order than `output: 'static'`. 
- We order CSS so that your dependencies CSS comes before your own (for example a component CSS comes before a page). This makes dev.
- Closes #4110
- Test added that does static and server rendering and then compares them.
N/A
=> Order server CSS the same as static

.changeset/empty-eagles-reply.md, packages/astro/src/core/build/static-build.ts, packages/astro/src/vite-plugin-build-css/index.ts, packages/astro/test/config-vite-css-target.test.js, packages/astro/test/fixtures/config-vite-css-target/astro.config.mjs, packages/astro/test/fixtures/config-vite-css-target/package.json, packages/astro/test/fixtures/config-vite-css-target/src/pages/index.astro, pnpm-lock.yaml
To solve #4092 
Support `vite.build.cssTarget` option in CSS minification
Add a test file
None
=> Add `vite.build.cssTarget` support for CSS build

.changeset/pretty-bananas-refuse.md, packages/astro/src/core/render/route-cache.ts, packages/astro/src/core/routing/index.ts, packages/astro/src/core/routing/validation.ts
- As reported here: https://discord.com/channels/830184174198718474/845451724738265138/1004770640877862912
- This error made it unclear that `output: server` mode allows you to skip `getStaticPaths` in your dynamic routes.
- Cleaned some code up while I was there, but no other behavioral changes made.
- Covered by existing tests.
- N/A
=> improve an error message for getstaticpaths

.changeset/shaggy-beds-itch.md, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/fixtures/mdx-frontmatter/src/pages/index.mdx
- Users reported needing a newline at the end of their files.
- tracked it down to MDX needing two newlines between content and where we inject any exports.
- Updated existing test to test for this.
- N/A
=> fix missing newline bug in mdx

packages/astro/src/core/render/dev/index.ts, packages/astro/src/vite-plugin-astro-server/index.ts
- Hides confusing `.tip` content in Vite's error overlay
- Updates client logs to use `[astro]` instead of `[vite]`
Tested manually, not relevant for tests IMO
N/A
=> Hide error overlay tip

packages/astro/src/core/render/dev/index.ts
- Followup to https://github.com/withastro/astro/pull/4141 to attempt a fix for one of the two Windows issues: `renderer. serverEntrypoint`
- Vite 3 appears to not like having resolved package exports passed to `ssrLoadModule` (but only on Windows?) and instead expects the unresolved package entrypoint.
- This is only safe to remove if we can confirm that the bug that this comment is referencing is out of date. I've confirmed that this change runs fine in the examples, but unclear which exact issue it was addressing since this is only ever used for loading renderers. @bholmesdev maybe you remember?
- Unclear if this is covered by existing tests or not. @bholmesdev to confirm?
- N/A
=> do not resolve renderer.serverEntrypoint url before loading it

.github/workflows/ci.yml, package.json, turbo.json
- ~~Updated CI to test every supported version of Node.js: https://nodejs.org/en/about/releases/~~
- Updated CI to take `OS` and `NODE_VERSION` into account when using cached tests
- Updated CI to run every supported version of Node.js on Windows (previously, was only v14)
- Previously, we'd limited windows to v14 only to improve CI bottlenecking, but other test speed improvements by @natemoo-re may allow us to add this back without impacting CI performance.
- Adding Node@18 TODO since there are multiple tests that break when `node-fetch` is replaced with Node@18's global `undici` fetch.
- is testing
- N/A
=> update test coverage to include more Node and Windows tests

.changeset/metal-dodos-sin.md, packages/integrations/mdx/test/fixtures/mdx-plus-react/astro.config.mjs, packages/integrations/mdx/test/fixtures/mdx-plus-react/package.json, packages/integrations/mdx/test/fixtures/mdx-plus-react/src/components/Component.jsx, packages/integrations/mdx/test/fixtures/mdx-plus-react/src/pages/index.astro, packages/integrations/mdx/test/mdx-plus-react.test.js, packages/integrations/react/src/index.ts, pnpm-lock.yaml
- Closes https://github.com/withastro/astro/issues/4084
- Underlying issue fixed in https://github.com/withastro/astro/pull/4137
Test added
N/A
=> Add test for mdx + React usage

.changeset/cold-pens-mate.md, packages/astro/package.json, packages/astro/test/astro-doctype.test.js, pnpm-lock.yaml, turbo.json
- Fixes https://github.com/withastro/astro/issues/4166
- Tests added in compiler
N/A, bug fix
=> Update compiler version

.changeset/afraid-rules-boil.md, packages/integrations/mdx/README.md, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/mdx-rehype-plugins.test.js
- Resolves #4150 
- Prevent overriding `collect-headings` plugin
Remove rehype overrides test
Update README
=> [MDX] Prevent overriding `collect-headings` plugin

.changeset/ninety-planets-work.md, packages/create-astro/package.json, packages/create-astro/src/index.ts, packages/create-astro/tsconfigs/tsconfig.strict.json, packages/create-astro/tsconfigs/tsconfig.stricter.json
This PR adds a step to `create-astro` to allow users to configure how strict they want their TypeScript install to be
I've set the "Strict" preset as the recommended one ~~in hope of making everyone's code better~~ as it's the one TypeScript itself recommend for new projects (same goes for all our other recommended settings)
The "Stricter" settings were mostly sourced from `create-t3-app`, it has very cool settings for TypeScript
Will PR docs if needed
=> Add a TypeScript step to `create-astro`

.prettierignore, .prettierrc.json, package.json, packages/integrations/image/components/Picture.astro, pnpm-lock.yaml
Add our Prettier plugin to our Prettier config. This will run in CI on every `.astro` files in the repo (apart from fixtures)
A lot of issues in our Prettier plugin have been fixed since the last attempt at adding it, however due to two compiler issues (https://github.com/withastro/compiler/issues/485, https://github.com/withastro/compiler/issues/318) four files had to be ignored for now
Tested manually, but not really relevant
N/A
=> Add `prettier-plugin-astro` to the monorepo

.changeset/itchy-hats-exist.md, packages/create-astro/src/index.ts
Fix the default and relaxed settings not working in create-astro, we should only copy when the user selected either strict or stricter, as the default template is already in the template 
I did this PR on my phone at 5am, so cannot test right now
N/A
=> Fix relaxed and default TypeScript settings not working

packages/astro/src/@types/astro.ts
- The description to Legacy Flag : `astroFlavoredMarkdown`
- Resolves issue [#1191](https://github.com/withastro/docs/issues/1191)
- No testing as this is comment section of an existing field of text. 
- This is a Autogenerated page to Docs as per @sarah11918 comment on issue 1191. See mentioned issue above.
=> docs: Modify legacy flag description

.changeset/strong-plants-tell.md, packages/astro/src/core/build/static-build.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-env/index.ts, packages/astro/test/fixtures/sourcemap/astro.config.mjs, packages/astro/test/fixtures/sourcemap/package.json, packages/astro/test/fixtures/sourcemap/src/components/Counter.jsx, packages/astro/test/fixtures/sourcemap/src/pages/index.astro, packages/astro/test/sourcemap.test.js, pnpm-lock.yaml
Fixes #3970
- Pass `viteConfig.build` config to client build Vite config
- Fix sourcemap generation in `astro:build` and `astro:vite-plugin-env` plugins
Added new `sourcemap` fixture to `astro/test`. Might be useful in the future for more sourcemaps test.
This should work by default without docs.
=> Fix client build sourcemap generation

packages/integrations/tailwind/README.md
- Add some doc to prevent mistakes like #4192
- Don't forget a changeset! `pnpm exec changeset` => is it needed for documentation changes?
Testing is probably irrelevant for documentation.
I don't know why this documentation lives here, and not at https://github.com/withastro/docs
=> doc: tailwind: link to import doc for applyBaseStyles

.changeset/thick-ducks-sparkle.md, packages/astro/src/core/preview/index.ts
Fixes problem that preview server doesn't serve a custom 404 page.
https://github.com/withastro/astro/issues/4113
=> fix: astro preview does not serve custom 404 (4113)

packages/integrations/deno/README.md, packages/integrations/image/README.md, packages/integrations/mdx/README.md, packages/integrations/netlify/README.md, packages/integrations/partytown/README.md, packages/integrations/preact/README.md, packages/integrations/prefetch/README.md, packages/integrations/sitemap/README.md, packages/integrations/tailwind/README.md
Replaces the `<details></details>` pattern (which previously hid installation and configuration instructions, and some examples) in the integration package READMEs with appropriate level headings.
Not tested.
Content auto-generated for Docs.
=> [docs] remove details tags from integration READMEs

.github/ISSUE_TEMPLATE/---01-bug-report.yml
- We're still getting bug reports with no title (just `🐛 BUG:`)
- Every issue is prefixed with `🐛 BUG:`
- The only issues people can open are bugs, so the prefix doesn't really add anything.
N/A
N/A
=> Update Issue Template

.github/workflows/ci.yml
- Test only, see below
- Adds back `windows-latest` to our smoke tests.
- All passing!
N/A
=> Add Windows back to smoke tests

.changeset/honest-bottles-drum.md, packages/integrations/mdx/README.md
README-only change!
N/A
Add frontmatter injection section with link to docs for more
=> [MDX] Add frontmatter injection to README

.changeset/slimy-parrots-exist.md, packages/astro/src/jsx/babel.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/runtime/server/jsx.ts
- Fixes https://github.com/withastro/astro/issues/4194
- Previously, JSX was referencing an export from our server entrypoint and wasn't tree-shaken out.
- This PR inlines the references where it is needed.
Manually
N/A
=> Ensure JSX does not reference server entrypoint

.changeset/thin-houses-play.md, packages/integrations/mdx/README.md, packages/integrations/mdx/package.json, packages/integrations/mdx/src/astro-data-utils.ts, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/fixtures/mdx-custom-frontmatter-name/src/pages/glob.json.js, packages/integrations/mdx/test/fixtures/mdx-custom-frontmatter-name/src/pages/index.mdx, packages/integrations/mdx/test/mdx-frontmatter.test.js, pnpm-lock.yaml
Initially, `frontmatterOptions` exposed settings to be passed to [`remark-mdx-frontmatter`](https://www.npmjs.com/package/remark-mdx-frontmatter). We've since ditched this library to handle frontmatter injection support, so exposing these options no longer makes sense! Allowing users to override the `frontmatter` export name would also break `Astro.glob` type checking.
Remove custom frontmatter test suite
README: Remove all `remark-mdx-frontmatter` and `frontmatterOptions` references
=> [MDX] Remove `frontmatterOptions`

packages/integrations/image/README.md, packages/integrations/mdx/README.md
Removes some closing HTML tags from integration package READMEs that got missed in the Great Undetailing of 2022
No tests.
Content to mirror to Docs.
=> [Docs READMEs] remove errant tags from details sweep

.changeset/warm-socks-exercise.md, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/layouts/Base.astro
Adds `rawContent()` and `compiledContent()` as props to MD layout. This replaces the need for the (undocumented) `Astro.props.content.astro.source` and `Astro.props.content.astro.html` properties.
Assert these props are correctly passed
https://github.com/withastro/docs/pull/1246
=> [MD] Add `rawContent` and `compiledContent` to MD layout props

.changeset/dry-deers-vanish.md, packages/markdown/component/readme.md
- updates the title in `packages/markdown/component/readme.md`
- previously it was `@astrojs/markdown` and was different from actual package name
=> Markdown component: fix package name in readme.md

.changeset/fast-drinks-visit.md, packages/integrations/image/README.md
Added missing subtitle for the `formats` prop of the `<Picture>` component in the @astrojs/image README.md.
Added missing subtitle for the `formats` prop of the `<Picture>` component in the @astrojs/image README.md.
Added missing subtitle for the `formats` prop of the `<Picture>` component in the @astrojs/image README.md.
=> Updated @astrojs/image README.md missing formats prop as subtitle

.changeset/two-ducks-end.md, packages/astro/src/core/add/index.ts
Just checks `flags.y` in addition to `flags.yes`.
I didn't see any tests.
QoL change. Not sure if it needs to be documented.
=> feat: Support `-y` in `astro add`

.changeset/silly-chairs-pretend.md, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/page-data.ts, packages/astro/src/core/errors.ts
- Remove starting the dev server during the build process since it's not used anymore
- Small refactor to remove unused options when passing to `collectPagesData`
No new tests added, but should be safe if all current tests pass.
N/A
=> Remove dev server during build

packages/integrations/lit/README.md
As I learned from a support Thread on Discord, the tagName convention was dropped during the beta period. Instead you need to export the class and use it in astro file.
I updated the code samples on this page accordingly.
=> Update code samples to match release version

.changeset/modern-papayas-rhyme.md, packages/integrations/cloudflare/README.md
This PR adds more context to how local development works with Wrangler and fixes spelling for middleware :)
This affects the GitHub readme only
=> [Docs]: Update Cloudflare README

.changeset/nasty-gifts-push.md, packages/astro/e2e/fixtures/invalidate-script-deps/package.json, packages/astro/e2e/fixtures/invalidate-script-deps/src/pages/index.astro, packages/astro/e2e/fixtures/invalidate-script-deps/src/scripts/heading.js, packages/astro/e2e/invalidate-script-deps.test.js, packages/astro/src/vite-plugin-astro/hmr.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-astro/query.ts, pnpm-lock.yaml
- If a module has a script importer, add the actual .astro component module to be reloaded, so that it is cached by the time the astro script reloads.
- Fixes https://github.com/withastro/astro/issues/4211
- e2e test added
bug fix only
=> Include astro components for HMR invalidation

.changeset/neat-bats-heal.md, packages/integrations/mdx/README.md
Update MDX README to use `Astro.props.frontmatter` for layout props.
N/A
README
=> [MDX] Astro.props.content -> frontmatter

.changeset/nervous-socks-sin.md, packages/astro/src/core/render/dev/index.ts, packages/astro/src/core/util.ts
Fix #4219
- Create a util to simulate Vite resolve for `/@id` and `/@fs`
- Correctly resolves modules to be loaded directly via url
Notes:
- Ideally this should be kept within Vite internally but I haven't found a way for us to do so without a big refactor.
- I could take a look in Vite to see if it's something we can expose.
Tested with an example app locally that shows no more sourcemap 404. The refactor should be covered by the existing tests too.
N/A
=> Simulate Vite resolve id to url

.changeset/old-pears-design.md, packages/astro-prism/Prism.astro, packages/astro-prism/src/highlighter.ts
- Closes #4246
- `@astrojs/prism` should not change your code indentation
- `@astrojs/prism` should not use `class="language-undefined"`, it should use `class="language-plaintext"`
Tried to add tests to `astro-prism`, but I couldn't get it working
bug fix only
=> Fix Prism indentation and class

.changeset/tasty-masks-draw.md, packages/integrations/mdx/src/astro-data-utils.ts, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/fixtures/mdx-frontmatter-injection/src/layouts/Base.astro, packages/integrations/mdx/test/fixtures/mdx-frontmatter-injection/src/pages/page-1.mdx, packages/integrations/mdx/test/fixtures/mdx-frontmatter-injection/src/pages/page-2.mdx, packages/integrations/mdx/test/mdx-frontmatter-injection.test.js
- Resolves #4216
- Moves layout generation to our frontmatter rehype plugin. This lets us parse injected frontmatter before passing as a layout prop, and aligns our MDX code with `vite-plugin-markdown`!
Test injected frontmatter in layouts
N/A
=> [MDX] Pass injected frontmatter to layouts

.changeset/real-feet-rule.md, .changeset/strange-meals-march.md, packages/astro/src/core/render/dev/vite.ts, packages/integrations/image/src/lib/get-image.ts
- Removes a user-unfriendly error from inside of our css/js crawl logic. 
- Adds a more user-friendly error when a user tries to import `@astrojs/image/components` without having added the integration to their Astro config file.
- Fixes #4257 
- Fixes #4161 ([nicolasverlhiac](https://github.com/nicolasverlhiac) to confirm!)
- Tested this manually using https://github.com/withastro/astro/issues/4257
- I don't _think_ this error warrants its own test fixture?
- N/A
=> Improve DX when astrojs/image isn't properly configured

.changeset/orange-pens-live.md, packages/integrations/netlify/src/shared.ts, packages/integrations/netlify/test/functions/404.test.js, packages/integrations/netlify/test/functions/fixtures/404/src/pages/404.astro, packages/integrations/netlify/test/functions/fixtures/404/src/pages/index.astro
- Fixes https://github.com/withastro/astro/issues/4269
Produces this example `_redirects`:
```
/    /.netlify/functions/entry    200
/404    /.netlify/functions/entry    200
/*    /.netlify/functions/entry    404
```
- Test added to check the redirects file.
N/A
=> Add 404 routing logic to Netlify redirects file

.changeset/rude-birds-ring.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/util.ts
Fix build output mistakenly adding `/index.html` to endpoints routes instead of the proper extension
Fix https://github.com/withastro/astro/issues/3954
N/A
N/A
=> Fix build output for endpoints route

.changeset/wise-cups-greet.md, packages/astro/src/core/add/index.ts
Previously, running `astro add astro-pkg`, would generate weird code:
```js
import { defineConfig } from 'astro/config';
import astro from 'astro-pkg';
export const defineConfig({
integrations: [
astro()
]
})
```
With this PR, the generated code will now be:
```js
import { defineConfig } from 'astro/config';
import pkg from 'astro-pkg';
export const defineConfig({
integrations: [
pkg()
]
})
```
Nah, we don't test `astro add`
N/A
=> Fix `astro add` with third-party integrations

.changeset/long-lobsters-ring.md, packages/integrations/preact/README.md
Close #4107
Spent a fair bit of time with this today, and I think this is the best we can do at the moment:
- Recommend alias `react` and `react-dom` to `@preact/compat` to intercept the alias into nested packages. 
- The alias works mostly for ESM libraries, but not for CJS libraries. In that case, recommend adding the library to `ssr.noExternal`.
red: extra context https://github.com/withastro/astro/issues/4107#issuecomment-1211943922
N/A (docs change)
Updated preact readme
=> Clarify preact/compat integration docs

.github/workflows/ci.yml, .github/workflows/release.yml
- `ci.yml` script exists for tests, but we'd added the release/changeset logic to it because it needed a lot of the same setup that our tests did.
- This created a problem where we were stuck waiting for old tests to finish before we could release, which delayed our release to the point that users started to notice.
- By pulling the release script into its own job, it can now run on every `main` commit without worrying about the blocking/cancelling logic of `ci.yml`.
- N/A
- N/A
=> Split release script out of CI script

packages/astro/env.d.ts
Like in https://github.com/withastro/astro/commit/8eba6d9d977920bdb0830cc219e636236433b2fd, makes the imports relative so they work inside the monorepo (and outside of it, of course)
Manually
N/A
=> Make imports inside env.d.ts relative for monorepo usage

.changeset/heavy-nails-juggle.md, packages/astro/src/vite-plugin-jsx/index.ts
- There were some cases where the Astro server runtime ended up in the browser.
- By being a bit more careful about our transforms, we can avoid this!
Bug fix only
=> fix(#4194): remove Astro runtime from browser

.changeset/four-students-rescue.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/render/result.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/runtime/server/jsx.ts, packages/astro/src/runtime/server/render/any.ts, packages/astro/src/runtime/server/render/astro.ts, packages/astro/src/runtime/server/render/common.ts, packages/astro/src/runtime/server/render/component.ts, packages/astro/src/runtime/server/render/index.ts, packages/astro/src/runtime/server/render/page.ts, packages/astro/src/runtime/server/render/types.ts, packages/astro/test/fixtures/hydration-race/src/components/Layout.astro, packages/astro/test/fixtures/hydration-race/src/pages/slot.astro, packages/astro/test/hydration-race.test.js
- Fixes another race condition in rendering hydration script that's caused when both a slot and a child component contain hydrated scripts.
- Since slots render to strings we need *not* render those scripts inside the slot, instead we inform renderPage() that the scripts are needed so that it can ensure they are added before any islands.
- Test added for this race condition.
N/A, bug fix.
=> Ensure hydration scripts inside of slots render ASAP

.changeset/fluffy-otters-guess.md, packages/astro/e2e/solid-recurse.test.js, packages/astro/src/core/build/generate.ts, packages/astro/src/core/routing/manifest/generator.ts, packages/astro/test/astro-get-static-paths.test.js, packages/astro/test/fixtures/astro-get-static-paths/src/pages/food/[name].astro
- Previously we were assuming a trailing slash until `trailingSlash: 'never'` was set in the config.
- This produced a dev/prod difference, because dev was not requiring it.
- This change aligns with what is documented, which is that a trailing slash is not shown, see https://docs.astro.build/en/reference/api-reference/#data-passing-with-props as an example.
- #4252
- Test added to confirm dev / build is same.
N/A
=> Prevents automatic trailingSlash behavior with getStaticPaths

.changeset/witty-bears-joke.md, packages/astro/src/core/add/index.ts
- Resolves #4285
- Set `output: 'server'` when adding an adapter, if not present.
N/A
N/A
=> [astro add] Set `output: 'server'` when adding adapter

.changeset/empty-parents-lie.md, packages/astro/env.d.ts, packages/astro/src/@types/astro.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/integrations/mdx/src/astro-data-utils.ts, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/fixtures/mdx-component/src/pages/glob.astro, packages/integrations/mdx/test/fixtures/mdx-frontmatter/src/layouts/Base.astro, packages/integrations/mdx/test/mdx-component.test.js, packages/integrations/mdx/test/mdx-frontmatter.test.js
- **Layout props**
- Add `file` and `url` to frontmatter props
- **`glob`**
- Add `<Content />` component export
- Add `rawContent` and `compiledContent` of type `never`. If called, this will log a helpful error message pointing to new frontmatter injection docs.
- Types
- Add `*.mdx` to declared type module
- Update `glob` to use `MDXInstance` instead. This overrides the `rawContent` and `compiledContent` props to be type `never`
- Add new `MarkdownLayoutProps` and `MDXLayoutProps`. Can remove if out of scope, but should be useful!
- test new `Content` component
- test `file` and `url` from layouts
N/A
=> [MDX] Fix remaining inconsistencies with Markdown

.changeset/yellow-insects-add.md, packages/astro/src/cli/index.ts, packages/astro/src/core/preview/index.ts, packages/astro/test/cli.test.js
- Right now, "astro preview" only supports static output 
- We have some interesting ideas for how to support deploy-specific preview commands like `netlify dev`, `vercel dev`, etc. 
- But for now, this small fix will prevent the unfriendly error that users see today.
- N/A
- N/A
=> Prevent "preview" from running if output mode is set to server

packages/integrations/image/README.md
This is a documentation change and does not impact any functionality.
None
This change adds a missing word in the integration-guide for the image integration.
=> add missing word in image integration-guide

examples/framework-multiple/astro.config.mjs
Removed all referenced to Lit within the `astro.config.mjs` file 
There is no `lit` component example within the `framework-multiple` example, this maybe something we could consider on adding at some point in the future. 
No registered `lit` dependencies either.
PR Does not need a `changeset`
User Testing: now starts perfectly without any errors being reported
No Docs needed.
=> Remove: references to Lit

packages/integrations/preact/README.md, packages/integrations/turbolinks/README.md, packages/webapi/README.md
Documentation: 
Adds langauge to the codeblock haiving: 
```sh
npm install @astrojs/preact
```
The command looks out of place, as someone who generally skips reading the text while quickly reading the guide, it's easy to miss the command.
This is a change in docs
This is a change in docs
=> docs: specify lang for a codeblock

packages/integrations/tailwind/README.md
Corrected "aother" with "another" in [the tailwind integration docs](https://docs.astro.build/en/guides/integrations-guide/tailwind/).
No tests because this pr is just fixing a typo in the docs
Well this PR fixes a typo in the docs
=> docs: fixed typo in the tailwind integration docs

.changeset/grumpy-wombats-laugh.md, packages/integrations/mdx/README.md, packages/integrations/mdx/package.json, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/src/remark-shiki.ts, packages/integrations/mdx/test/mdx-syntax-highlighting.test.js, pnpm-lock.yaml
We do too! Still, we've noticed a fair share of MDX + Shiki-twoslash issues being reported due to inconsistencies with Markdown. Namely:
- 3 support threads wondering about the injected code language at the top of each code block
- 1 issue on passing through Shiki Twoslash config via `markdown.shikiConfig` (which could involve breaking changes to resolve) #4245
- Inconsistencies in CSS class targeting, where MDX files generate `class="shiki"` while Markdown generates `class="astro-code"`
Due to this, we think bundling Twoslash by default has more cons than pros. We also don't feel we can migrate Markdown to Twoslash now that we've reached 1.0 stability.
Absolutely! If you like Shiki-twoslash, you can flip off our built-in highlighter and apply their remark plugin like so:
```js
import …
```
=> [MDX] Switch from Shiki Twoslash -> Astro Markdown highlighter

.changeset/hip-bobcats-divide.md, packages/astro/src/runtime/server/render/astro.ts, packages/astro/src/runtime/server/render/component.ts, packages/astro/src/runtime/server/render/page.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/fixtures/head-injection-md/package.json, packages/astro/test/fixtures/head-injection-md/src/components/Layout.astro, packages/astro/test/fixtures/head-injection-md/src/pages/index.md, packages/astro/test/head-injection-md.test.js, pnpm-lock.yaml
- For markdown components, we were eagerly rendering the head when appending the doctype. 
- However if any layout is used the head is going to be injected there anyways.
- The change is to only make head injection occur for a markdown page that has no layout (and therefore has no real head).
- Test added for the regression that was found.
N/A, bug fix
=> Fix double injecting of head content in md pages

.changeset/orange-llamas-glow.md, packages/astro/src/vite-plugin-astro-server/index.ts
Closes #4310
Updates route matching logic to allow SSR builds to allow multiple routes that match the same URL.  This error was originally added in #4087 but is too aggressive, the SSR build can actually handle this to prioritize the correct route match in production deployments
All existing tests should pass
#4087 included new tests to ensure that `injectRoute` routes are prioritized before `src/pages` routes
Bug fix only
=> SSR doesn't need to block multiple routes that match the same URL

packages/integrations/image/README.md, packages/integrations/lit/README.md, packages/integrations/mdx/README.md, packages/integrations/partytown/README.md, packages/integrations/preact/README.md, packages/integrations/prefetch/README.md, packages/integrations/react/README.md, packages/integrations/sitemap/README.md, packages/integrations/solid/README.md, packages/integrations/svelte/README.md, packages/integrations/tailwind/README.md, packages/integrations/turbolinks/README.md, packages/integrations/vue/README.md
- Updates `astro add` instructions in integrations READMES to use `npm run astro add ...` or `pnpm run astro add ...` instead of `npx`/`pnpx`
- I assume no changes are needed for `yarn` as it already runs a named script when found so `yarn astro add ...` was and will be correct.
- My perennial dilemma: should this include a patch changeset? Seems kind of drastic for a docs change this small.
N/A
YUP
=> integrations: update recommended method for running astro add

.changeset/thick-spiders-try.md, packages/astro/src/@types/astro.ts
Change `interface extends` to `type`. Avoids an empty `{}` that our linter (mysteriously) complains about.
N/A
N/A
=> Fix: TS lint on `MDXLayoutProps`

.changeset/few-mayflies-invent.md, packages/astro/src/core/config.ts
- If a user did not set their CLI to --draft, then `typeof flags.drafts === 'boolean'` will not be true, which would cause the drafts config to be set to `false`, overriding user configuration.
I was unable to run `pnpm install` on my machine. Any additional commits to add tests (or even pointing me the right direction to add them myself) would be very much appreciated.
I tested that this fix solves the issue by fiddling with dist/core/config.js on my own project.
This actually makes the behavior of `astro build` conform to the current documentation: https://docs.astro.build/en/guides/markdown-content/#markdown-drafts
=> Fallback to undefined rather than false when resolving CLI flags

examples/blog/src/pages/blog/markdown-style-guide.md
Image linked in markdown had .png instead of .jpg
This is the only image affected in all the example blog posts.
- Image will properly load now
N/A
N/A
=> Update example blog post markdown-style-guide.md to use correct image extension

.changeset/giant-ants-smoke.md, packages/astro/src/core/build/static-build.ts
Refactor Vite config merging for static build and remove TODO.
`vite.mergeConfig` is not used as we want control ordering in some fields, e.g. `plugins` and `rollupOptions`
Should work with `pnpm test`
N/A
=> Refactor static build config merge

.changeset/six-jars-push.md, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/dev-routing.test.js, packages/astro/test/fixtures/with-endpoint-routes/src/pages/images/[image].svg.ts, packages/astro/test/fixtures/with-endpoint-routes/src/pages/images/static.svg.ts
Fix #3950
On the dev server, we were only setting MIME types if the route had a pathname, which meant only for static routes. Endpoints like `[filename].svg.ts` would be served as `text/html`. This PR fixes that by building a fake pathname based on the endpoint filename, so that the extension can be used to hint at MIME type.
Don’t know if there’s an argument that a production server might _not_ do this for you? I’d assume in all reasonable scenarios, a server will see an `image.svg` file and serve it with the correct MIME type for you.
Added some new tests to the `dev-routing-test` to cover MIME types for JSON & SVG endpoints.
Only a bug fix.
=> Provide correct MIME type for dynamic endpoint routes in dev

packages/astro/e2e/astro-component.test.js, packages/astro/e2e/client-only.test.js, packages/astro/e2e/error-react-spectrum.test.js, packages/astro/e2e/error-sass.test.js, packages/astro/e2e/errors.test.js, packages/astro/e2e/invalidate-script-deps.test.js, packages/astro/e2e/lit-component.test.js, packages/astro/e2e/multiple-frameworks.test.js, packages/astro/e2e/namespaced-component.test.js, packages/astro/e2e/nested-in-preact.test.js, packages/astro/e2e/nested-in-react.test.js, packages/astro/e2e/nested-in-solid.test.js, packages/astro/e2e/nested-in-svelte.test.js, packages/astro/e2e/nested-in-vue.test.js, packages/astro/e2e/nested-recursive.test.js, packages/astro/e2e/nested-styles.test.js, packages/astro/e2e/pass-js.test.js, packages/astro/e2e/shared-component-tests.js, packages/astro/e2e/solid-recurse.test.js, packages/astro/e2e/tailwindcss.test.js, packages/astro/e2e/test-utils.js, packages/astro/e2e/ts-resolution.test.js, packages/astro/playwright.config.js
Fixes a bug that was causing E2E tests to restart the dev server for every single test case
Future improvements - synchronization on HMR tests seem to be flaky on Windows, need to investigate what could be breaking the `editFile` synchronization only for Windows tests
All existing tests should pass...faster
Test updates only
=> Testing perf improvements for e2e tests

.changeset/rare-comics-roll.md, packages/astro/src/core/errors.ts, packages/astro/src/core/messages.ts
Fix #4357
Preserve all error stack lines to avoid hiding important information. I'm not sure if this may expose more dirty messages, but we could monitor along as we go.
Before:
After:
Note: I also tried parsing the stack to split out the stack and frame, but it doesn't work with Vite's overlay as it expects frames to start with a `|` pipe.
Tested manually with the repro at #4357
N/A
=> Preserve all error stack lines

examples/docs/src/components/LeftSidebar/LeftSidebar.astro
Corrected spelling in `examples/docs/src/components/LeftSideBar/LeftSideBar.astro`, changing pesudoSection to pseudoSection in order to fix #4367 .
No tests necessary as the variable doesn't show up anywhere else (verified with a recursive grep) and both names were substituted at the same time.
As far as I can see, no changes are required for the docs.
=> Fix typo in the docs example

packages/create-astro/tsconfigs/tsconfig.stricter.json
- Fixes a typo in the stricter tsconfig file in create-astro package. Changes "possibe" to "possible"
No test changes required
No documentation changes required
=> Fix typo in stricter tsconfig

.changeset/smooth-nails-remain.md, packages/astro/e2e/fixtures/hydration-race/astro.config.mjs, packages/astro/e2e/fixtures/hydration-race/package.json, packages/astro/e2e/fixtures/hydration-race/src/components/Deeper.astro, packages/astro/e2e/fixtures/hydration-race/src/components/Layout.astro, packages/astro/e2e/fixtures/hydration-race/src/components/One.jsx, packages/astro/e2e/fixtures/hydration-race/src/components/Wrapper.astro, packages/astro/e2e/fixtures/hydration-race/src/pages/slot.astro, packages/astro/e2e/hydration-race.test.js, packages/astro/src/runtime/client/idle.ts, packages/astro/src/runtime/client/load.ts, packages/astro/src/runtime/client/media.ts, packages/astro/src/runtime/client/only.ts, packages/astro/src/runtime/client/visible.ts, packages/astro/src/runtime/server/astro-island.ts, pnpm-lock.yaml
- This replaces a reverted PR: https://github.com/withastro/astro/pull/4288
- That PR attempted to ensure that directive scripts always came before the first island that needed them.
- This idea was based on the flawed idea that would move those scripts up the rendering chain through state, but this resulted in scripts some times being placed in the middle of where attribute expressions go.
- This is a new approach that accepts that some times an island will exist before the directive script is ready. When this happens listen to an event that fires when the directive script gets defined.
- Closes https://github.com/withastro/astro/issues/4286
E2E test added that recreates the problem.
Bug fix
=> Fix race condition with directive definitions

.changeset/big-cougars-jam.md, packages/astro/package.json, pnpm-lock.yaml
Bump Vite to bring up the bug fixes, e.g. #4373
Note: The next Vite release will be 3.1 beta.
Tests should pass with the Vite upgrade
N/A
=> Bump Vite to 3.0.9

.changeset/heavy-pants-change.md, packages/integrations/vercel/src/edge/adapter.ts
Resolves #4391 
Handle array and object signature in Vite aliases. This check was missing on the Vercel edge adapter, so `react-dom` was never aliased to something deno-ready!
=> fix: correctly add `react-dom` alias to Vercel edge

packages/integrations/node/README.md
Assets where not served so the style was not applied, fixed this by adding the line app.use(express.static('dist/client/'))
-Just makes that express serves the assets as well, if it doesn't, styles and favicon will return a 404 error.
I tested it with a blank project and it fixed the issue properly.
There must be a change in the docs to show the small fix.
=> Updated Express code to serve assets

.changeset/silver-dragons-run.md, packages/astro/src/vite-plugin-jsx/index.ts
- Refactor the JSX plugin to move expensive work out of the hot code path
- This actually was a nice chance to clean up the file a bit, move some code into helper functions, and remove some redundant code that was no longer needed due to Astro's internal JSX renderer.
- **NOTE:** This changes one thing about current behavior, which is that it now prioritizes the explicit `@jsxImportSource` pragma over import scanning. I had assumed that the explicit pragma always beat out the implicit import scanning, and would make the case here that ignoring an explicit pragma is a bug. This change would only impact a user who had a `@jsxImportSource` to one framework and then ESM imports to another. I don't think that's realistic, but I thought I'd call it out here in case anyone feels differently.
- …
=> refactor the JSX plugin, improve performance

.changeset/purple-guests-fetch.md, examples/framework-alpine/astro.config.mjs, examples/framework-alpine/package.json, examples/framework-alpine/src/pages/index.astro, packages/integrations/alpinejs/README.md, packages/integrations/alpinejs/package.json, packages/integrations/alpinejs/src/index.ts, packages/integrations/alpinejs/tsconfig.json, pnpm-lock.yaml
- @Princesseuh and I had talked about this a while ago, but never got around to it. 
- This adds the new Alpine.js integration that should be good for most users.
- This updates the `framework-alpine` example to use the new integration.
- Helps to address feedback like this.
- Tested manually.
- Covered by existing smoke tests.
=> add an alpine integration and update example

packages/integrations/vercel/package.json
This enables the use of `{ output: static, adapter: vercelStaticAdapter}`.  
Previously, both paths, `@astro/vercel/static` and `@astro/vercel/serverless`, would resolve to the serverless adapter.
Manually tested, observed build output changed from 
`[build] deploy adapter: @astrojs/vercel/serverless` to 
`[build] deploy adapter: @astrojs/vercel/static`
nothing new to document
=> fix: vercel static export path

.changeset/chatty-ants-shop.md, packages/integrations/image/src/utils/paths.ts, packages/integrations/image/test/fixtures/basic-image/src/pages/index.astro, packages/integrations/image/test/image-ssg.test.js, packages/integrations/image/test/image-ssr.test.js
Closes #4317 
When building optimized images for SSG builds, any query params used for remote images should be stripped out from the final built HTML
Note that during `astro dev` and for SSR builds the query params are still needed to make sure the remote image can be fetched properly
Added `dev` and `build` test coverage for remote image query params in SSG and SSR
Bug fix only
=> [@astrojs/image] Handle query params in remote image URLs during SSG builds

.changeset/kind-onions-reply.md, packages/integrations/mdx/src/astro-data-utils.ts
- Resolves #4307 
- Moves frontmatter layout import to an `async` import
We found some interesting `import.meta.glob` behavior in the dev server after #4255 was introduced.
**Scenario:** a directory of MDX files use the same `layout` in their frontmatter. This layout **includes an `Astro.glob` call for that same directory of MDX files.** This is common when generating a "what to read next" section, navigation, etc.
- **Before:** When editing a single MDX file imported by the layout glob, **only that file is re-transformed by Vite.** All other globbed files will come from cache. This means near-instant dev server feedback (ignoring initial startup time).
- **After:** When editing a single MDX file imported by the layout glob, **all globbed files are re-transformed by Vite.** This could …
=> Improve MDX glob perf - move Layout to async import

.changeset/eleven-shoes-lie.md, packages/astro/src/@types/astro.ts
TL;DR: this updates the astro config type to allow falsy values in the `integrations` array, which the docs indicate should be possible. Related: https://github.com/withastro/docs/issues/1334
---
The [docs state](https://docs.astro.build/en/guides/integrations-guide/#toggle-an-integration):
> Falsy integrations are ignored, so you can toggle integrations on & off without worrying about left-behind undefined and boolean values.
> ```
> integrations: [
>   // Example: Skip building a sitemap on Windows
>   process.platform !== 'win32' && sitemap()
> ]
> ```
However, Typescript will generate the following error if you try to do this:
```
Type 'false | AstroIntegration' is not assignable to type 'AstroIntegration | AstroIntegration[]'.
```
In this particular change, I've chosen a nullish …
=> fix (core): allow falsy values in astro config integrations arrays

.changeset/flat-ads-lay.md, packages/astro/src/vite-plugin-jsx/tag.ts
Closes #4220
Fixes warning when using hooks inside the react components not exported as a function declaration
Adds proper support for react components exported as
```ts
// named arrow expression
export const X = () => {...}; 
function Y1 () {...}
const Y2 = () => {...};
// Export default
export default Y2;
// Export specifiers
export { Y1 as Comp, Y2 }
// Export default object
export default { Y1, Y2 }
```
I would like to add tests if needed, just unsure of how to test for warnings in the build output
No changes in docs needed
=> Fix invalid hook usage for exports

.changeset/odd-elephants-remember.md, packages/astro/src/core/build/generate.ts, packages/astro/test/fixtures/get-static-paths-pages/package.json, packages/astro/test/fixtures/get-static-paths-pages/src/pages/[...page].astro, packages/astro/test/get-static-paths-pages.test.js, pnpm-lock.yaml
- In 1.0 there isn't an automatic trailingSlash added for pages. A check expecting there to never ben an empty string for a generated route is now wrong. This removes it.
- Closes https://github.com/withastro/astro/issues/4306
N/A, bug fix.
=> Ensure index pages are generated on paginated results

.changeset/loud-eagles-do.md, packages/astro/src/core/add/index.ts
- Resolves #4420
- Correctly set integration to "third party" for unofficial integrations
- Remove duplicate `@` prepended to third part org scope
N/A
N/A
=> Fix `astro add @example-org/integration`

.changeset/eight-adults-guess.md, packages/astro/src/jsx/babel.ts
Fix #4101
When a JSX file imports an Astro component, e.g. using MDX for templating, we don't warn about setting `client:*` directive. This PR warns about it during compile time, and in both dev/build, for cases like this.
Tested manually with the repro at #4101
N/A
=> Warn hydration directive for Astro components in JSX

.changeset/nice-mice-teach.md, packages/astro/astro-jsx.d.ts
Small fix to our JSX definition to allow strings on the target attribute. Also disallow strings on the `type` attribute on input as it's an enumerable attribute
N/A
=> Allow string as a valid value for the target attribute

.changeset/hungry-pens-develop.md, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/fixtures/mdx-page/src/pages/index.mdx, packages/integrations/mdx/test/fixtures/mdx-page/src/styles.css, packages/integrations/mdx/test/mdx-page.test.js
- Resolves #4397 
- Add fancy `astro.needsHeadRendering` symbol to MDX when layout is not applied.
Add style import test
N/A
=> Fix MDX style imports when layout is not applied

.changeset/nine-pants-leave.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/graph.ts, packages/astro/src/core/build/internal.ts, packages/astro/src/core/build/page-data.ts, packages/astro/src/core/build/types.ts, packages/astro/src/core/build/vite-plugin-analyzer.ts, packages/astro/src/core/build/vite-plugin-css.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/test/css-order.test.js, packages/astro/test/fixtures/css-order/src/pages/two.astro
- This makes our CSS link order deterministic. It uses CSS depth; that is how deeply a module import the CSS comes from, in order to determine which CSS is page-level vs. component-level CSS. 
- This is intended to match dev ordering where, because we do not bundle, the page-level CSS always comes after component-level.
- Closes https://github.com/withastro/astro/issues/4393
- We had existing ordering tests, but they only ensured that SSG and SSR order matched.
- Adds a test to ensure that page-level is placed last in the head, and therefore takes priority.
N/A, bug fix.
=> Use CSS depth to sort CSS in production

.changeset/four-worms-wonder.md, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/core/dev/index.ts, packages/astro/src/integrations/index.ts, packages/astro/src/vite-plugin-integrations-container/index.ts
- Resolves #4321
- Add `Waiting for [X] integration...` log across all integration build hooks. This will be triggered for any hook that takes over 3 seconds to resolve. Open to tweaking this timing hook-by-hook if anyone has opinions!
N/A
N/A
=> Add logs for long-running integration hooks

.changeset/tricky-melons-grin.md, packages/astro/src/vite-plugin-astro/compile.ts, packages/astro/src/vite-plugin-astro/hmr.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-astro/styles.ts, packages/astro/src/vite-plugin-markdown-legacy/index.ts
Fix #3382
- Refactor CSS preprocess deps tracking for #3382
- Fix HMR handling for `@import` in styles in astro files
Notes:
1. I'll find some time to upstream a feature for Vite to expose its `compileCss` function to make preprocessing a lot easier.
The existing tests should cover the preprocess refactor. For HMR, I'd love to add tests, ~~but it doesn't seem like we've setup the infrastructure for it since those require editing files locally~~ will add test tomorrow. For now, I've tested locally with the repro in #3382
N/A
=> Refactor CSS preprocess and HMR

examples/basics/README.md, examples/blog/README.md, examples/docs/README.md, examples/portfolio/README.md
- The screenshots on https://astro.build/themes/official/ are really small -> Users might click on the GitHub link to see the theme in more detail
- Firing up Stackblitz for a visual inspection is a very high bar, many people will bail before this
- I've added screenshots to all "official" examples
=> feat: add screenshots to official theme readme files

.changeset/odd-oranges-laugh.md, packages/astro/package.json, packages/astro/test/0-css.test.js, pnpm-lock.yaml
Fix an incorrect test for `\` escaping. Context: https://github.com/withastro/compiler/pull/503#issuecomment-1219201138
Also bump `@astrojs/compiler`
N/A
=> Fix incorrect css test

.changeset/sour-avocados-exercise.md, packages/astro/src/core/build/vite-plugin-css.ts, packages/astro/test/css-no-code-split.test.js, packages/astro/test/fixtures/css-no-code-split/astro.config.mjs, packages/astro/test/fixtures/css-no-code-split/package.json, packages/astro/test/fixtures/css-no-code-split/src/pages/index.astro, pnpm-lock.yaml
Fix #4413 
When `vite.build.cssCodeSplit: false`, the reference to the single `style.css` file generated by Vite doesn't exist in `chunk.viteMetadata.importedCss`, but only in the `bundle`. We simulate how Vite does it [here](https://github.com/vitejs/vite/blob/b2c0ee04d4db4a0ef5a084c50f49782c5f88587c/packages/vite/src/node/plugins/html.ts#L690-L705)
Added css-no-code-split test
N/A
=> Support `vite.build.cssCodeSplit: false` option

.changeset/gold-suns-repair.md, packages/astro/src/core/build/static-build.ts
Fix #4468
in #4344 , `base: astroConfig.base,` was deleted, but it was needed because it was NOT from `viteConfig`
tested only locally
None
=> Fix load `base` option in build

.changeset/fast-oranges-collect.md, packages/astro/src/core/build/graph.ts, packages/astro/src/core/build/internal.ts, packages/astro/src/core/build/vite-plugin-css.ts, packages/astro/test/astro-scripts.test.js, packages/astro/test/fixtures/astro-scripts/src/pages/with-styles.astro, packages/astro/test/fixtures/astro-scripts/src/styles/one.css
- When appending CSS to a page, account for hoisted scripts by tracing the script to the page it belongs to.
- Closes https://github.com/withastro/astro/issues/4242
- Test case added to the existing hoisted script tests.
N/A, bug fix
=> Include styles imported by hoisted scripts

packages/integrations/react/client.js
This PR is heavily inspired from  [tweet by Ryan Florence.](https://twitter.com/ryanflorence/status/1547959632663961602 )
_I am extremely sorry if I made any mistakes :(_
=> Adding time-slicing with `startTransition` to prevent hydration from blocking the main thread for too long for those users who immediately scroll.

.changeset/beige-deers-travel.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/generate.ts, packages/astro/test/astro-get-static-paths.test.js, packages/astro/test/fixtures/page-format/package.json, packages/astro/test/fixtures/page-format/src/pages/nested/page.astro, packages/astro/test/page-format.test.js, pnpm-lock.yaml
- Makes the `Astro.url.pathname` match what configuration is set to in `build.format`.
- This means that if the config is set to `'directory'` it will be `/page/`. If it is set to `'file'` it will be `/page.html`.
- This makes it so that relative URLs you create using `Astro.url` resolve the way your configuration specifies.
- Fixes #4190
- Test added for both `'directory'` and `'file'`.
- Included in this PR in the `astro.ts` types file.
=> Make Astro.url conform to build.format during the build

.changeset/chilly-stingrays-play.md, packages/astro/src/@types/astro.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/astro-markdown.test.js, packages/astro/test/fixtures/astro-markdown/src/layouts/Base.astro, packages/integrations/mdx/src/astro-data-utils.ts, packages/integrations/mdx/test/fixtures/mdx-frontmatter/src/layouts/Base.astro, packages/integrations/mdx/test/mdx-frontmatter.test.js
- Update `MarkdownInstance` type to match new `vite-plugin-markdown` output
- Make `getHeadings` and `compiledContent` synchronous
- Change `default` to `AstroComponentFactory`
- Improve JS Docs across fields
- Add `file` and `url` as top-level layout props for Markdown and MDX. This 1) makes layout props more consistent with `MarkdownInstance`, and 2) addresses 2 confused users in our support threads that expected top-level props
Add `file` and `url` prop tests to Markdown and MDX
TODO
=> Update Markdown type signature to match behavior

.changeset/cool-turtles-lay.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/config.ts, packages/astro/test/astro-markdown-plugins.test.js, packages/astro/test/fixtures/astro-markdown-plugins/astro.config.mjs, packages/astro/test/fixtures/astro-markdown-plugins/package.json, packages/astro/test/fixtures/astro-markdown-plugins/src/pages/with-gfm.md, packages/markdown/remark/src/index.ts, packages/markdown/remark/src/types.ts, pnpm-lock.yaml
Add `extendDefaultPlugins` to preserve default markdown plugins:
```js
// astro.config.mjs
export default {
markdown: {
remarkPlugins: [myCoolPlugin],
// preserves GitHub-flavored markdown and smartypants
extendDefaultPlugins: true,
}
}
```
Add remark plugin tests with and without `extends`
https://github.com/withastro/docs/pull/1409
=> [MD] `extendDefaultPlugins` to preserve default remark plugins

packages/integrations/image/README.md
It is a bit unclear how to import the Image/Picture components for a first-time reader, this PR hopefully clears that up.
Currently, how to import the `@astrojs/image` component is only mentioned in [`#Examples`](https://docs.astro.build/en/guides/integrations-guide/image/#examples), 3/4ths down the page.
This adds a small snippet in [`#Usage`](https://docs.astro.build/en/guides/integrations-guide/image/#usage) straight after install, so that a reader can immediately copy/paste it and start tinkering.
Only docs changed
https://docs.astro.build/en/guides/integrations-guide/image
=> Earlier import snippet for `@astrojs/image`

.github/workflows/snapshot-release.yml
Replaced workflow_dispatch with the [`issue_comment`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment) trigger.
Merging into https://github.com/withastro/astro/pull/4483.
Not sure if it's possible to test actions locally.
N/A.
=> Allow releasing snapshot from issue comment

package.json
Bump pnpm min version from 7.5.0 to 7.9.5 (latest)
The lockfile Github action uses 7.5.0 which generates a different lockfile than 7.9.5 (for some reason). Enforcing the latest one should prevent the back-and-forth changes. 
N/A
N/A
=> Bump pnpm version

packages/integrations/cloudflare/README.md
Close #4416
The context of this is at https://github.com/withastro/astro/issues/4416#issuecomment-1228234136, but the gist is that since env in Cloudflare can only be accessed like:
```js
export async function onRequest({ env }) {
return new Response(env.ENV_NAME);
}
```
private env vars which are transformed as runtime code like `process.env.ENV_NAME` won't work. Perhaps we can take a look at [SvelteKit's env var handling](https://kit.svelte.dev/docs/modules#$env-static-private) for this in the future.
N/A
The docs script should auto pick this up.
=> Note private env var handling with cloudflare builds

examples/basics/src/components/Card.astro, examples/basics/src/layouts/Layout.astro, examples/blog/src/components/HeaderLink.astro, examples/blog/src/layouts/BlogPost.astro, examples/component/packages/my-component/Button.astro, examples/component/packages/my-component/Heading.astro, examples/framework-alpine/src/components/Counter.astro, examples/with-nanostores/src/layouts/Layout.astro
- This changes the astro examples to remove `as Props` casting. since it's not  needed any more with the new version of the asto language tools.
No tests were added, since  the change only touches the examples.
=> Remove "as Props" from the astro examples

.changeset/blue-peas-laugh.md, packages/integrations/solid/package.json, pnpm-lock.yaml
- Updated `@astro/solid-js` integration to use `Solid` 1.5 see the [release notes](https://github.com/solidjs/solid/releases/tag/v1.5.0)
N/A
N/A
=> chore: update to solid 1.5

.changeset/modern-schools-fold.md, packages/astro/src/core/util.ts
- Resolves #4418
- Only log `[code].html` instead of `[code]/index.html` for `404` and `500` routes.
N/A - just a production build logging fix
N/A
=> Only print file output only for 404 and 500 routes

.changeset/hungry-adults-juggle.md, packages/astro/client-base.d.ts, packages/astro/import-meta.d.ts, packages/astro/package.json, pnpm-lock.yaml
`tsc` doesn't handle paths with uppercase characters inside tripleslash directives using `types` correctly. The TypeScript team is aware of this, but it's been an issue for years now. Renaming the file to use lower case characters works, however this is understandably a breaking change for the Vite team (see https://github.com/vitejs/vite/pull/9827)
As such, for now we'll just copy the file in our own repository until Vite 4 comes out. That's okay
Fix https://github.com/withastro/astro/issues/4387
N/A
=> Vendor Vite's importMeta.d.ts inside our repo to workaround issue with `tsc` on Linux

.changeset/tough-buses-hang.md, packages/integrations/alpinejs/package.json
- Added `renderer` keyword to `AlpineJS` integration, Which should by result allow `scripts/generate-integration-pages.ts` to put AlpineJS in the right category inside https://docs.astro.build/en/guides/integrations-guide
Results on the docs: https://deploy-preview-1417--astro-docs-2.netlify.app/en/guides/integrations-guide/
Before: 
After:
This will auto update the docs.
=> Add `renderer` keyword to alpinejs integration

.changeset/thirty-taxis-lick.md, packages/astro/config.d.ts
When using `defineConfig` in an Astro config file, the type `AstroUserConfig` is not resolved correctly. No editor autocompletion is provided because the TypeScript language server is unable to resolve an import in the declaration file and defaults to `any`.
I have updated the import path to the correct location.
A testing/docs update should not be needed since this change simply fixes the code such that it has the expected behaviour.
=> Fix type import in config.d.ts

packages/integrations/node/src/index.ts
Small typo change from `@astrojs/Node` to `@astrojs/node`
N/A
N/A
=> Fix `@astrojs/node` typo

.changeset/blue-knives-collect.md, packages/integrations/image/client.d.ts
The Image integration's types didn't refer to `client-base.d.ts`, as such numerous types were lost when using them. Notably `import.meta.env`
N/A
=> Fix image integration's types not including Vite's types

.changeset/stale-paws-rhyme.md, packages/astro/astro-jsx.d.ts
`slot` was missing from the list of possible attributes on SVG elements
N/A
=> Add missing slot attribute to possible attributes on SVG elements

.changeset/fuzzy-frogs-try.md, packages/astro/src/core/build/index.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/vite-plugin-astro-server/index.ts
From https://github.com/vitejs/vite/pull/9865, we can remove the hardcoded Vite middleware removal code as we use `appType: 'custom'` that does the same thing.
N/A
=> Remove hardcoded Vite middleware handling

.changeset/thin-taxis-laugh.md, packages/integrations/react/server.js
Small change to `/* vite-ignore */` an unknown import as Vite warns about it since 3.0.9. This doesn't happen for the users, but only when they link Astro locally, which makes Astro `ssr.noExternal` by default.
Didn't add a changeset as it affects internal only.
N/A
N/A
=> Vite ignore unknown import

packages/integrations/vercel/README.md
A note related only to SSG deployment on Vercel was added to this Vercel adapter README that was confusing to readers and in the wrong place.
I'm deleting this here and making note on the Vercel deploy page instead, where we describe deploying a static site to Vercel.
Note: I'm assuming this only affects SSG (not SSR deployment) because 
a) that was the description in the original PR that put the note here (https://github.com/withastro/astro/pull/4299) and 
b) the person added this at the top of the page, with the introductory sentence about not needing an adaptor for SSG (i.e. placed this content where the mention of SSG was instead of further down the page in Usage or something like that.) 
If this `vercel.json` file is in fact needed for SSR, too, then instead of just deleting, I would …
=> [docs] remove confusing note added in wrong place

.changeset/moody-cars-return.md, packages/astro/src/core/build/generate.ts, packages/integrations/sitemap/package.json, packages/integrations/sitemap/test/fixtures/trailing-slash/astro.config.mjs, packages/integrations/sitemap/test/fixtures/trailing-slash/package.json, packages/integrations/sitemap/test/fixtures/trailing-slash/src/pages/one.astro, packages/integrations/sitemap/test/fixtures/trailing-slash/src/pages/two.astro, packages/integrations/sitemap/test/test-utils.js, packages/integrations/sitemap/test/trailing-slash.test.js, pnpm-lock.yaml
- When calculating the pages for the `pages` prop in `astro:build:done` account for the trailingSlash and build.format configs.
- This fixes integrations like sitemaps which need the correct production URLs.
- Closes https://github.com/withastro/astro/issues/4539
- Test added in the sitemap integration to cover every scenario
N/A, bug fix
=> Include trailingSlash in astro:build:done hook

.changeset/kind-lobsters-leave.md, packages/integrations/mdx/README.md
Following https://github.com/withastro/docs/issues/1234, I've added a section to the integration guide on custom components in MDX
This should be automatically pulled into the docs according to: https://github.com/withastro/docs/pull/1426
=> Add custom components to mdx integration guide

.changeset/chatty-foxes-bow.md, packages/integrations/cloudflare/package.json, packages/integrations/deno/package.json, packages/integrations/netlify/package.json, packages/integrations/node/package.json, packages/integrations/vercel/package.json
Adds the `withastro` keyword to all host adapters.  This will make sure they're included in a new `adapters` tab in the [Integrations Catalog](https://astro.build/integrations)
N/A
[Related docs PR](https://github.com/withastro/docs/pull/1441) updating the list of keywords that our integration catalog searches for
=> Adds the "withastro" keyword to adapter packages

.changeset/tough-pandas-sneeze.md, packages/astro/src/core/build/internal.ts, packages/astro/src/core/build/vite-plugin-css.ts, packages/astro/test/0-css.test.js, packages/astro/test/fixtures/0-css/src/components/SvelteDynamic.svelte, packages/astro/test/fixtures/0-css/src/pages/index.astro
As `client:load` components are built in ssr and client, this PR removes the unused CSS in the client build as SSR already builds one for it.
We fix this by tracking all CSS chunks' modules in SSR, then compare them in the client build, removing CSS chunks that also has the same modules.
Thanks @matthewp for the idea.
Add a test in 0-css
N/A
=> Remove unused CSS for `client:load` components

.gitpod.yml
Until https://github.com/gitpod-io/gitpod/issues/12551 gets resolved, this PR make sure Gitpod workspaces would always use latest pnpm.
* Open this PR in Gitpod
* Run `pnpm -v`.
* Confirm it is using latest pnpm version (7.9.5)
(this PR only affect Gitpod)
=> fix: always get latest pnpm

.changeset/sharp-brooms-drum.md, packages/integrations/deno/src/server.ts, packages/integrations/deno/test/basics.test.js, packages/integrations/deno/test/fixtures/basics/src/pages/404.astro
- Makes Deno SSR render custom 404 pages.
- It does this by detecting when it could not find a static file at a certain location, and then calling `app.render()` to make sure any custom 404 page is rendered instead of the browser's default.
- Resolves #4560 
Added a Deno test that makes sure the custom 404 page is displayed for non-existent routes.
This is a visible change, but it updates the behavior to what I believe is the _expected_ behavior, according to the current documentation, so I don't think there are any doc changes required.
=> Deno custom 404 pages

.changeset/nice-cups-mix.md, packages/astro/src/core/add/index.ts
Contributes towards #4541
- Remove duplicate content in the log shown when running `astro add` without arguments.
- Add missing integrations (image, mdx, node adapter, prefetch and alpine)
- Simplify section headings to match [docs navigation](https://docs.astro.build/en/guides/integrations-guide/#official-integrations): `UI Frameworks`, `SSR Adapters` & `Others`
Not tested — just changing the logging output.
No changes required.
=> Update `astro add` integrations list

.changeset/weak-emus-confess.md, packages/integrations/mdx/src/utils.ts, packages/integrations/mdx/test/mdx-plugins.test.js
Make sure GFM and Smartypants are applied to MDX by default.
Add test for GFM by default
N/A
=> [MDX] Fix: GFM and Smartypants missing by default

packages/astro/src/core/build/internal.ts, packages/astro/src/core/path.ts, packages/astro/test/astro-client-only.test.js, packages/astro/test/fixtures/astro-client-only/src/components/UsingCSSModules.jsx, packages/astro/test/fixtures/astro-client-only/src/components/styles.module.scss, packages/astro/test/fixtures/astro-client-only/src/pages/css-modules.astro
- With JSX the extension is removed in the compiler causing our lookups to fail. This does a second lookup to ensure we find the component.
- This is better fixed by removing partial resolution in the compiler, ie doesn't prepend `/@fs` everywhere and lean on Vite to resolve everything.
- Want to work with @bluwy to fix this.
- Fixes https://github.com/withastro/astro/issues/4587
- Test added
N/A, bug fix
=> Fix client:only when used with JSX

packages/integrations/image/README.md
When the image integration README is pulled into the docs site, Astro tries to render `<Image />` and `<Picture />` which are then undefined, breaking the build. See withastro/docs#1457
I’ve also wrapped a few more snippets of code in backticks where it makes sense.
n/a
All docs, all the time 🕶️
=> Fix image integration README

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
- Add a line to the PR template, prompting to ping @withastro/maintainers-docs for docs feedback
- Update `CODEOWNERS` to make @withastro/maintainers-docs “owners” of _all_ `README.md` files.
What does this mean? File “owners” automatically receive a review request when a PR that touches their files come in. [GitHub code owners docs →](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners)
Could be a bit too coarse-grained — could pick up `README.md` files in tests or whatever if we have them, so happy to refine that if it turns out to be annoying.
Do we want other files to auto-request a review from team docs? ~~The types file we use to generate our config reference springs to mind.~~ <-- …
=> Docs process tweaks: update PR template & CODEOWNERS

.changeset/tough-zoos-bathe.md, packages/astro/src/vite-plugin-jsx/index.ts
- Fixes #4601 
Error you get now is:
No, we don't test warnings.
No.
=> Provide a better error message when no jsx renderer configured

examples/blog/src/layouts/BlogPost.astro, examples/blog/src/pages/blog.astro, examples/blog/src/pages/index.astro, examples/ssr/src/pages/cart.astro, examples/ssr/src/pages/index.astro, examples/ssr/src/pages/login.astro
This just makes a couple of trivial changes to `examples/blog` for consistency  with other layouts:
- Moves the `<Footer />` component outside of `<main>` in `blog.astro`
- Adds a `DOCTYPE` and `lang="en-us"` attribute to `BlogPost.astro`. 
I didn't change any of the other examples as there's no consistency between all the examples. Some have a `DOCTYPE`, some have `lang="en"` or more attributes. However these changes are within the Blog example, so I felt updating them for consistency made sense (and my accessibility checked complained about the lack of a `lang` attribute).
No changeset as contributing.md says they're not needed for examples. 
This was tested by making the changes in my own Blog site and viewing the results in the browser. I don't believe there are specific tests related …
=> Blog template changes

packages/integrations/alpinejs/README.md
=> Typo in alpinejs integration README.md

.changeset/three-owls-help.md, packages/integrations/alpinejs/package.json
- Update  broken alpinejs homepage
This change requires no tests.
This change will fix the broken link on the `alpinejs` integration: https://astro.build/integrations/frameworks
=> Fix AlpineJS homepage link

.changeset/smooth-hats-smell.md, packages/astro/src/core/render/dev/css.ts
Ensure SSR module is loaded before testing is CSS in `getStylesForURL`.
There are some problems when trying to use UnoCSS with Astro in dev. Sometimes the CSS is not inlined in the HTML, making some styles not applied. For example:
- https://github.com/AllanChain/astro-uno/issues/3
I found that's because the `uno.css` SSR module is not loaded when trying to determine whether it is a JS module style. Ensuring loading the SSR module fixes the problem.
Manually tested with https://stackblitz.com/edit/withastro-astro-pzexzk and my blog.
It's not a big change, so no tests were added.
Just a fix. No docs were added.
=> fix: ensure SSR module is loaded before testing is CSS

examples/docs/src/components/Header/LanguageSelect.tsx
When user adds another language to the `KNOWN_LANGUAGES`, there's a console error because `LanguageSelect.tsx` map doesn't have unique keys for the options.
- Add key to LanguageSelect options
No tests added because it was a minor update.
No need to add docs, because it's for the initial template.
=> fix: add unique key to elements in map

.changeset/rich-dolphins-teach.md, packages/integrations/image/package.json, packages/integrations/image/src/build/ssg.ts, pnpm-lock.yaml
This change parallelizes `@astrojs/image`  transforms to get a big performance boost.
`@astrojs/image` currently processes images serially, one after the other. If it processes 10 images and takes 1 second to process each, the total time will be 10 seconds.
This change makes it process images in batches. The batch size is the # of CPUs on the machine, e.g. 8 on my dev machine.
I manually put the newly built code in dist/build/ssg.js into my current project (I can't figure out how to get `pnpm` and `npm` to let me link across projects). I then did a before and after build.
I then edited `astro.config.mts` and enabled `debug` logging:
```js
integrations: [
image({
logLevel: "debug",
}),
...
```
NOTE: Yes I know a 92s->39s build time is still abysmal. `@astrojs/image` is very slow at …
=> Parallelize @astrojs/image transforms

.changeset/fifty-avocados-lay.md, packages/astro/src/core/create-vite.ts, packages/astro/test/fixtures/third-party-astro/astro.config.mjs, packages/astro/test/fixtures/third-party-astro/package.json, packages/astro/test/fixtures/third-party-astro/src/pages/astro-embed.astro, packages/astro/test/third-party-astro.test.js, pnpm-lock.yaml
Fix #4071 
Search for Astro package dependencies beyond a project’s direct dependencies.
See [this comment](https://github.com/withastro/astro/issues/4071#issuecomment-1236431134) for more background — it lays out some alternative approaches, I’d be curious what people think!
**TL;DR** Current logic only adds _direct_ dependencies to `vite.ssr.noExternal`. The changes in this PR walk the dependency tree, checking child dependencies of any Astro packages it finds recursively. It bails out of a branch when it encounters a non-Astro package. This should still be reasonably performant, while being much more robust.
Help would be appreciated. @natemoo-re’s original PR for this code (https://github.com/withastro/astro/pull/2665) mentions:
> Not sure there's a great way to test this.
What I did …
=> Improve third-party Astro package support

.changeset/seven-zoos-lie.md, packages/astro/src/core/build/vite-plugin-css.ts, packages/astro/test/0-css.test.js, packages/astro/test/fixtures/0-css/src/components/ReactDynamic.jsx, packages/astro/test/fixtures/0-css/src/components/ReactLazy.jsx, packages/astro/test/fixtures/0-css/src/components/ReactLazy.module.css, packages/astro/test/test-utils.js
- Closes https://github.com/withastro/astro/issues/4613
- We remove duplicate CSS bundles. This caused a regression where Vite would try to preload that CSS in the client. Removing the metadata prevents it from preloading it, essentially erasing its existence.
- Test added
N/A, bug fix
=> When removing duplicate CSS, also remove from metadata

packages/integrations/alpinejs/README.md, packages/integrations/image/README.md, packages/integrations/lit/README.md, packages/integrations/mdx/README.md, packages/integrations/partytown/README.md, packages/integrations/preact/README.md, packages/integrations/prefetch/README.md, packages/integrations/react/README.md, packages/integrations/sitemap/README.md, packages/integrations/solid/README.md, packages/integrations/svelte/README.md, packages/integrations/tailwind/README.md, packages/integrations/turbolinks/README.md, packages/integrations/vue/README.md
- Fixes [#1468](https://github.com/withastro/docs/issues/1468)
- We introduced the previous non-`npx` version in #4340, but got multiple issue reports about this syntax not working both on Discord and GitHub since then. Also, a poll we made on Discord between the two versions was overwhelmingly positive for using the `npx` version (13 people were preferring `npx astro add` while only 1 person was preferring `npm run astro add`).
- Therefore, this PR changes the recommended installation instructions for npm users to the community-preferred and apparently less issue-prone choice.
- I have also unified the CTA to report any `astro add` issues on GitHub to a version that no longer states that this command is new, as it no longer is. :)
- Pure docs change, no tests required
- It's all about …
=> Integrations: Fix NPM instructions to use `npx astro add` again

.changeset/swift-wolves-argue.md, packages/integrations/image/components/Image.astro, packages/integrations/image/src/lib/get-picture.ts, packages/integrations/image/src/utils/paths.ts, packages/integrations/image/test/fixtures/basic-image/src/pages/index.astro, packages/integrations/image/test/fixtures/basic-picture/src/pages/index.astro, packages/integrations/image/test/image-ssg.test.js, packages/integrations/image/test/image-ssr-build.test.js, packages/integrations/image/test/image-ssr-dev.test.js, packages/integrations/image/test/picture-ssg.test.js, packages/integrations/image/test/picture-ssr-build.test.js, packages/integrations/image/test/picture-ssr-dev.test.js, pnpm-lock.yaml
Closes #4644
- Fixes a regression in filenames for remote images that don't include a file extension
- Updates the `<Image>` prop types to match docs, `format` isn't required for remote images
Tests added
Bug fix only
=> [@astrojs/image] Fixes a regression in remote image filenames

.changeset/giant-beds-beam.md, packages/astro/e2e/error-cyclic.test.js, packages/astro/e2e/fixtures/error-cyclic/astro.config.mjs, packages/astro/e2e/fixtures/error-cyclic/package.json, packages/astro/e2e/fixtures/error-cyclic/src/components/PreactCounter.tsx, packages/astro/e2e/fixtures/error-cyclic/src/pages/index.astro, packages/astro/src/runtime/server/hydration.ts, packages/astro/src/runtime/server/render/component.ts, packages/astro/src/runtime/server/serialize.ts, packages/astro/src/vite-plugin-astro-server/index.ts, pnpm-lock.yaml
- Fixes https://github.com/withastro/astro/issues/4332
- Follow-up to https://github.com/withastro/astro/pull/4351
- Throws a helpful when cyclic (circular) references are run through our serialization logic
- Non-breaking change, this already didn't work, this just gives a helpful error when it's broken
E2E Test added
N/A
=> Throw helpful errors when attempting to serialize cyclic references

.changeset/brown-berries-eat.md, packages/integrations/preact/client-dev.js, packages/integrations/preact/package.json, packages/integrations/preact/src/index.ts
This PR automatically sets up the bridge to Preact DevTools in the Preact integration when `astro dev` is run.
Browser extensions are very tricky to test automatically. So I mainly tested it locally in an astro starter project.
Screenshot:
I don't think there is a need to add docs as it's kinda expected that DevTools works out of the box.
=> Automatically set up Preact DevTools in dev mode

.changeset/soft-icons-travel.md, packages/astro/e2e/fixtures/namespaced-component/astro.config.mjs, packages/astro/e2e/fixtures/namespaced-component/package.json, packages/astro/e2e/fixtures/namespaced-component/src/pages/index.astro, packages/astro/e2e/fixtures/namespaced-component/src/pages/mdx.mdx, packages/astro/e2e/namespaced-component.test.js, packages/astro/src/jsx/babel.ts, pnpm-lock.yaml
Fix for issue described in: https://github.com/withastro/astro/issues/4389
Components declared using `JSXMemberExpression` nodes were not hydrating properly, due to how the `component-export` attribute was being determined in the `astroJSX` Babel plugin.
Example:
```jsx
const SampleComponent = () => { ... }
export const Namespace = { SampleComponent };
```
The `component-export` attribute for this component (`<Namespace.SampleComponent client:load />`) was `'SampleComponent'`, but will now be `'Namespace.SampleComponent'`, which can be resolved properly via the hydration logic here: https://github.com/withastro/astro/blob/dfa3519d4c1aba888dceec50f285677d659d1540/packages/astro/src/runtime/server/astro-island.ts#L72-L75
Tested locally. I also added to the existing …
=> fix: exportName metadata for JSXMemberExpressions that use named imports

.changeset/tasty-owls-watch.md, packages/astro/src/runtime/server/render/page.ts, packages/integrations/react/server.js
- Resolves #4391 
- Switch from `for await` to `while` loop on React stream renderer. Based on similar Cloudflare issue https://github.com/facebook/react/issues/24169
- Convert HTML object to string before encoding. Vercel Edge won't do this automatically, which broke other framework renderers
Manually deployed to Vercel Edge. Could use deployment tests one day!
N/A
=> Fix component frameworks on Vercel Edge

.changeset/orange-llamas-play.md, package.json, packages/integrations/react/server.js
- This broke the Deno tests: https://github.com/withastro/astro/pull/4667/files
- It's unclear why it passed in that branch.
- This fixes it, a streaming decode needs to be closed or there's a leak (which the Deno tests exposes).
- Tests were failing but now pass
N/A, bug fix
=> Make React integration work with Deno

.changeset/lovely-clocks-tease.md, packages/astro/src/runtime/server/serialize.ts, packages/astro/test/serialize.test.js
- Issue reported on Discord
- Fixes our cyclic reference detection! A regression was introduced where valid shared references would throw, but this code makes it so non-cyclic but shared references are passed through properly.
Unit tests added!
=> Improve cyclic reference detection, now ignores non-cyclic shared references

packages/astro/src/core/add/index.ts
In line with our template changes in #4544, this changes `astro add` to install to `dependencies` instead of `devDependencies`.
I couldn't find a test that this affects, and I don't think it's a new feature that needs to be tested.
We've already changed the docs to recommend `dependencies` over `devDependencies`, this just catches up `astro add`.
=> Remove devDependency flag from `astro add` 

packages/integrations/node/README.md
Replaces `netlify` with `node` in the `astrojs/node` integration guide
This is a change in the docs content
This is a change in the docs content
=> docs: correct mistake in `@astrojs/node` integration

.changeset/tricky-cows-travel.md, packages/astro/package.json, packages/astro/src/cli/index.ts, packages/astro/src/core/add/index.ts, packages/astro/src/core/config.ts, packages/astro/src/core/dev/index.ts, packages/astro/src/core/messages.ts, packages/astro/src/vite-plugin-astro/hmr.ts, packages/integrations/alpinejs/README.md, packages/integrations/image/README.md, packages/integrations/lit/README.md, packages/integrations/mdx/README.md, packages/integrations/partytown/README.md, packages/integrations/preact/README.md, packages/integrations/prefetch/README.md, packages/integrations/react/README.md, packages/integrations/sitemap/README.md, packages/integrations/solid/README.md, packages/integrations/svelte/README.md, packages/integrations/tailwind/README.md, packages/integrations/turbolinks/README.md, packages/integrations/vue/README.md, pnpm-lock.yaml
- You heard right. Restart the dev server whenever configs are added, updated, or removed 🥳
- Add `restartInFlight` flag to avoid clobbering when saving multiple times in a row
- When a `--config` is specified, only watch changes on that file. Otherwise, watch for any new `astro.config.*` files in the project root. Yes, this means your server reloads when you swap file extensions!
All good PRs have some spice: When a config file changes, **[write the config contents to temporary file at the project root](https://github.com/withastro/astro/pull/4578/files#diff-376630862e295fd5d974f4fff5419d9cb97c8f88f1a180092917500fb62b28ffR487-R504)** with a unique timestamp, and quickly delete once the config is resolved.
Proload uses a native ESM import to resolve `mjs` and `js` configs, which is …
=> No 👏 more 👏 server 👏 restarts 👏 on 👏 config 👏 changes

examples/docs/README.md
Fixes the incorrect location of `theme.css` file in the docs starter example.
N/A - wording change in a readme only
N/A - basically a docs fix itself
=> Fix theme.css location in docs starter project

.changeset/orange-clocks-exist.md, packages/astro/src/core/build/vite-plugin-analyzer.ts, packages/astro/test/astro-client-only.test.js, packages/astro/test/fixtures/astro-client-only/package.json, packages/astro/test/fixtures/astro-client-only/pkg/index.svelte, packages/astro/test/fixtures/astro-client-only/pkg/package.json, packages/astro/test/fixtures/astro-client-only/src/pages/pkg.astro, pnpm-lock.yaml
- The build analyzer tracks client:only usage. When it's from a child package we need to fully resolve the id so that the CSS plugin can find it later.
- Fixes https://github.com/withastro/astro/issues/4671
Test added
N/A, bug fix
=> Fix client:only CSS missing from child packages

.changeset/mean-dingos-juggle.md, packages/astro/src/core/add/index.ts
Move `applyPolyfill()` to top of `astro add` flow
Manual testing
N/A
=> Fix `[astro add]` fetch failure

.changeset/green-pillows-hammer.md, packages/astro/test/fixtures/vue-with-multi-renderer/astro.config.mjs, packages/astro/test/fixtures/vue-with-multi-renderer/package.json, packages/astro/test/fixtures/vue-with-multi-renderer/src/components/Counter.vue, packages/astro/test/fixtures/vue-with-multi-renderer/src/components/CounterWithScriptSetup.vue, packages/astro/test/fixtures/vue-with-multi-renderer/src/pages/index.astro, packages/astro/test/vue-with-multi-renderer.test.js, packages/integrations/vue/server.js, pnpm-lock.yaml
- Resolves #4319 
- Add `__ssrInline` to Vue component `check`. Seems Vue components have a different signature with using `script setup` during production builds
Add test build with Vue + another integration (Svelte in this example)
N/A
=> Fix: Vue `script setup` with other renderers applied

.changeset/fuzzy-rats-remain.md, packages/astro/src/integrations/index.ts
Before, it wasn't super clear why your renderer wouldn't load if it was improperly configured (it'd show something like "can't read undefined of something"). After this PR, it'll instead show a nice error message telling you your renderer is missing things. Small fix, but nice
Fix https://github.com/withastro/astro/issues/3015 (most of the issue was already fixed, so it's really just this that was blocking it now)
N/A
=> Add an error message for improperly configured renderers

.changeset/orange-cycles-serve.md, packages/astro/src/core/errors.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/error-bad-js.test.js, packages/astro/test/fixtures/error-bad-js/astro.config.mjs, packages/astro/test/fixtures/error-bad-js/package.json, packages/astro/test/fixtures/error-bad-js/src/env.d.ts, packages/astro/test/fixtures/error-bad-js/src/pages/index.astro, packages/astro/test/fixtures/error-bad-js/src/something.js, pnpm-lock.yaml
- Makes error handling more graceful. If we are unable to convert to Vite's stacktrace, just process the error we have.
- Fixes https://github.com/withastro/astro/issues/4709
- Added test case
N/A, bug fix
=> Make error handling more resilient in the dev server

.changeset/polite-beds-happen.md, packages/integrations/vercel/src/edge/adapter.ts
Use Edge Functions instead of Edge Middlewares
https://discord.com/channels/830184174198718474/845451724738265138/1018069733603545122
We used to use middlewares because that was the way to access the Edge way back in April. Now, we should use normal functions.
This could be a breaking change for some people, should we bump to `1.1.0` or to `2.0.0`?
=> [vercel] Use Edge Functions instead of Edge Middlewares

.changeset/blue-seals-warn.md, packages/astro-rss/src/index.ts, packages/astro-rss/test/rss.test.js
- Only throw when `url` is `undefined`. Empty string URLs _should_ be supported for globbing homepage routes (i.e. `src/pages/index.md`)
- Resolves #4598
Add test for globs outside `pages/` and a route with `url: ''`
N/A
=> [RSS] Fix failure when globbing index route

.changeset/many-tables-brush.md, packages/astro/src/core/build/graph.ts, packages/astro/src/core/build/internal.ts, packages/astro/src/core/build/types.ts, packages/astro/src/core/build/vite-plugin-css.ts, packages/astro/test/css-order.test.js, packages/astro/test/fixtures/css-order/astro.config.mjs, packages/astro/test/fixtures/css-order/src/pages/three.astro, packages/astro/test/fixtures/css-order/src/styles/base.css
- Order CSS sorting algorithm now uses import order to determine the order that CSS is injected into the page. That means that if you have something like:
```astro
---
import './one.css';
import './two.css';
---
```
And these end up in separate bundles, the bundle that `one.css` is within will be in the first link tag and two.css in the second. This means you can control CSS ordering by controlling your own import ordering.
- This consequentially fixes https://github.com/withastro/astro/issues/4614 because integrations using `injectScript` are prepended.
- Test added to mirror Tailwind integration scenario.
N/A, bug fix.
=> Use import order to sort CSS in prod

.changeset/dull-flowers-prove.md, packages/integrations/netlify/src/integration-edge-functions.ts
- Resolves #4376
- Co-authored-by: Jackie Macharia @jackiewmacharia (okay you did all the work 😅 )
- Serialize route pattern to match Netlify Edge's expected format. Mirrors the serialization done by [Netlify's own edge bundler](https://github.com/netlify/edge-bundler/blob/main/src/manifest.ts#L34).
Manually ran `netlify build` on Netlify CLI v10.18.1
N/A
=> Fix route validation for Netlify Edge

.github/workflows/snapshot-release.yml
Fixes a typo in #4744, the action needs to checkout the head ref not the base ref
N/A
N/A
=> fix: typo in snapshot ref checkout

.github/workflows/snapshot-release.yml
This enables the publish step of the new `Create a Snapshot Release` GitHub Action
Example output can be found [here](https://github.com/withastro/astro/pull/4738#issuecomment-1245947938) (the publish step is currently disabled, its through building the changesets for a `next-wasm.0` release then exits)
Manually tested the action with all but the publish step, will be using #4738 for a live test in production
None, dev tooling updates only
=> Enabling the publish step for snapshot releases

.changeset/kind-rats-lay.md, packages/astro/src/core/build/common.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/static-build.ts
Fix #4006
If `outDir` is out of `process.cwd()`, build the ssr output to `<cwd>/.astro` instead. This directory will be removed after the build, unless an error occurs during the build, which it's preserved for debuggability.
No test added as the monorepo structure makes it tricky to test this edge case (brings false positive). I did test with a separate project though and it works.
~~This PR handles static output only (`output: 'static'`). For server output, the `outDir` MUST be inside the current working directory as most integrations requires this for the deployment output to work. (e.g. netlify, vercel, cloudflare)~~
~~Should we document this? On the other hand, setting `outDir` outside of cwd feels like a special case.~~
~~/cc @withastro/maintainers-docs for feedback!~~
=> Handle builds with outDir outside of cwd

.changeset/nice-peaches-swim.md, packages/astro/src/runtime/server/jsx.ts
Fix #4459
The `filteredConsoleError` hook that patches `console.error` forgots to call the original `console.error` if is not filtered out.
N/A. I think this is a simple fix 😬 
N/A
=> Fix console.error filtering

.changeset/leaders-of-the-free-world.md, packages/integrations/tailwind/package.json, pnpm-lock.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19PZ4YUERbyHQejEDvvvdXZ3iceY5UuQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=pEnoTw3)
updated `package.json` with `tailwindcss` as a peer dependency of the integration itself. 
Unsure if `changeset` is needed
N/A
N/A
=> Update peer dep with Tailwindcss

.changeset/spotty-berries-grow.md, packages/astro/test/fixtures/react-component/src/components/CloneElement.jsx, packages/astro/test/fixtures/react-component/src/pages/index.astro, packages/astro/test/react-component.test.js, packages/integrations/react/server.js
- Fixes https://github.com/withastro/astro/issues/4753
- Test added
N/A, bug fix
=> Only pass through children prop if there are children

.changeset/swift-trees-double.md, packages/integrations/tailwind/CHANGELOG.md, packages/integrations/tailwind/README.md
- Add migration section to Tailwind v2 changelog
- Update README to include `tailwindcss` in manual install instructions
- Is there anywhere else we can/should document the migration steps?
Docs only
=> Tailwind v2 docs

.changeset/tricky-cats-drop.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/config.ts, packages/astro/src/vite-plugin-config-alias/index.ts, packages/astro/src/vite-plugin-jsx/index.ts, packages/astro/test/fixtures/react-and-solid/astro.config.mjs, packages/astro/test/fixtures/react-and-solid/package.json, packages/astro/test/fixtures/react-and-solid/src/components/ExampleReact.tsx, packages/astro/test/fixtures/react-and-solid/src/components/ExampleSolid.tsx, packages/astro/test/fixtures/react-and-solid/src/pages/index.astro, packages/astro/test/fixtures/react-and-solid/tsconfig.json, packages/astro/test/react-and-solid.test.js, pnpm-lock.yaml
- If the import source is not found from import statements, or from a comment, and there are multiple renderers, try reading it from tsconfig instead.
- Fixes https://github.com/withastro/astro/issues/4590
- Test added
N/A, bug fix
=> Read jsxImportSource from tsconfig

.changeset/fluffy-eyes-boil.md, packages/astro/src/core/app/index.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/runtime/server/astro-island.ts, packages/astro/src/runtime/server/hydration.ts, packages/astro/test/before-hydration.test.js, packages/astro/test/fixtures/before-hydration/astro.config.mjs, packages/astro/test/fixtures/before-hydration/deps.mjs, packages/astro/test/fixtures/before-hydration/package.json, packages/astro/test/fixtures/before-hydration/src/components/SomeComponent.jsx, packages/astro/test/fixtures/before-hydration/src/pages/index.astro, packages/astro/test/fixtures/before-hydration/src/scripts/global.js, pnpm-lock.yaml
- Previously we were always loading an empty `data:` script in prod when `before-hydration` was unused, which is most apps. This required special CSP rules to allow importing data urls.
- Change is to only load that when it's actually needed by returning an empty string instead and not adding the attribute. Without the attribute the client will not attempt to load it.
- Fixes https://github.com/withastro/astro/issues/4762
- Test added for every scenario, SSG with and without the use of before-hydration, SSR before and without.
N/A, bug fix
=> Ensure before-hydration is only loaded when used

examples/portfolio/src/pages/index.astro
Found a very small typo. `/products/` doesn't exist in the example site. Likely means`/projects/`. It was changed from `/projects/` to `/products/` in [this commit](https://github.com/withastro/astro/pull/4556/files#diff-1b82a0a1dff5a1ed618445a8f95e787ae5166d7703ada35b9a4392f738301f13L220).
=> Fix typo in portfolio example

.changeset/four-eggs-compare.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/integrations/index.ts, packages/astro/test/static-build-dir.test.js
This adds a new `astro:build:generated` hook that runs after all SSG pages are generated but **before** build artifacts are cleaned up.
**Why?**
This handles a very specific use case for `@astrojs/image`.  The new wasm-based image service uses a worker pool to build multiple images in parallel.  The workers need to reference the build's main entrypoint bundle before it's removed by the cleanup process
**Alternatives considered**
- fire `astro:build:done` before the cleanup process
This would technically be a breaking change, and feels a little gross in general since the build really isn't done until it's finished cleanup and is exiting
- refactor the SSG image service to build images during the page generation rather than building all images at the end.
This is a huge performance hit, …
=> Adds a new "astro:build:generated" hook for SSG builds

.changeset/four-eggs-compare.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/integrations/index.ts, packages/astro/test/static-build-dir.test.js
This reverts commit 03b18e8d1b9b88d7e9b22e15809a78cc222cb55b.
Reverts [PR #4772](https://github.com/withastro/astro/pull/4772), clicked merge on a `minor` too early
NA
NA
=> Revert "Adds a new "astro:build:generated" hook for SSG builds (#4772)"

examples/README.md, examples/blog/README.md, examples/component/README.md, examples/docs/README.md, examples/framework-alpine/README.md, examples/framework-lit/README.md, examples/framework-multiple/README.md, examples/framework-preact/README.md, examples/framework-react/README.md, examples/framework-solid/README.md, examples/framework-svelte/README.md, examples/framework-vue/README.md, examples/minimal/README.md, examples/non-html-pages/README.md, examples/portfolio/README.md, examples/with-markdown-plugins/README.md, examples/with-markdown-shiki/README.md, examples/with-mdx/README.md, examples/with-nanostores/README.md, examples/with-tailwindcss/README.md, examples/with-vite-plugin-pwa/README.md, examples/with-vitest/README.md, packages/create-astro/README.md
For consistency with https://github.com/withastro/docs/pull/360. Docs always use `npm create astro` (never `npm init astro`), README.md files in this repo should do the same.
Search:
`\b(npm|yarn|pnpm) init astro\b`
Replace:
`$1 create astro`
Except for two instances:
1. `packages/create-astro/CHANGELOG.md` -- skipped because changelog.
2. `packages/create-astro/test/create-astro.test.js.skipped` -- skipped, old test file disabled in https://github.com/withastro/astro/pull/3168.
_Q: should I run `pnpm exec changeset` for minor changes only touching *.md files? I would guess no._
n/a, no code changes.
n/a, changes make README.md files consistent with docs, see above.
=> .md only: npm init astro --> npm create astro

.changeset/witty-suits-grab.md, packages/astro/src/core/build/internal.ts, packages/astro/test/astro-client-only.test.js, packages/astro/test/fixtures/astro-client-only/src/components/PersistentCounterStandalone.svelte, packages/astro/test/fixtures/astro-client-only/src/pages/persistent-counter-standalone.astro
- Fixes missing CSS from client:only usage of Svelte components.
- These come through with the `@fs` prefix and we weren't checking that.
- Fixes https://github.com/withastro/astro/issues/4777
- This should have been covered by an existing test, but because we were testing multiple things in a single page it was accidentally passing.
- Moved to a standalone page to ensure that we are testing this and only this in a single test case.
N/A, bug fix.
=> Fixes client:only CSS in Svelte components

.changeset/ten-tips-argue.md, packages/astro/package.json, pnpm-lock.yaml
Fix #4727
Brings in the fix from https://github.com/vitejs/vite/pull/10144
I also bumped as `~3.1.3` as discussed by @matthewp before, or we could stick to a pinned version.
Tested the original repro in the issue and Vite 3.1.3 fixes it.
N/A
=> Update Vite 3.1.3

packages/integrations/lit/README.md, packages/integrations/mdx/README.md, packages/integrations/preact/README.md, packages/integrations/react/README.md, packages/integrations/solid/README.md, packages/integrations/svelte/README.md, packages/integrations/vue/README.md
- This PR fixes the issue in integration docs which I reported here https://github.com/withastro/docs/issues/1577
- The emoji is broken in 3rd point of `Getting started` inside integration docs
All tests are passing
Fixes https://github.com/withastro/docs/issues/1577
=> fixed broken emoji for in "Getting started" section of integration docs

.changeset/tidy-glasses-unite.md, packages/markdown/remark/package.json, pnpm-lock.yaml
This PR declares `hast-util-to-html` as a dependency of `@astrojs/markdown-remark` since it uses it here:
https://github.com/withastro/astro/blob/6e27a5fdc21276cad26cd50e16a2709a40a7cbac/packages/markdown/remark/src/rehype-collect-headings.ts#L2
Ran Astro in a strict dependency environment to verify that all dependencies were declared, after declaring `hast-util-to-html` it passed.
No docs should be needed for this bugfix.
=> fix(markdown-remark): declare `hast-util-to-html` as a dependency

.changeset/sweet-ligers-push.md, packages/astro/src/core/render/core.ts, packages/astro/src/core/render/result.ts
This header is not necessary and is ignored by essentially all HTTP servers when provided explicitly by the user. This is because the HTTP transport layer handles adding this header automatically as needed.
Some variations of HTTP transport (like HTTP/2, which is enabled by default in Deno, Netlify, and CFW) have no notion of
`Transfer-Encoding: chunked`, because all responses are streamed.
- This removes the `Transfer-Encoding: chunked` header.
If all existing streaming related tests pass, this should be considered working as I am arguing that the header is superfluous to the function of Astro.
This does not affect users in any way.
=> Remove explicit `Transfer-Encoding: chunked` header

.changeset/green-baboons-clean.md, packages/astro/src/core/build/static-build.ts
Allow changing `vite.build.target`. The default is `esnext`, which the user may want to use `es2020` instead.
I noticed it used to be `es2020` but bumped in https://github.com/withastro/astro/pull/2487. I think we should keep this value as baseline `es2020` so that user can opt-in to advanced feature instead, but it would be a breaking change.
This may help similar issues to #4812 (but not completely as we don't have full legacy support)
N/A
N/A. I think this is a transparent change.
=> Allow override `vite.build.target`

.changeset/six-weeks-grab.md, packages/create-astro/src/index.ts, packages/create-astro/test/directory-step.test.js
When initializing a new Astro project, I realized that it is not currently possible to run `create-astro` in a cloned empty git repository. The current behavior is to check for truly empty directories. This could also be an issue for macOS users trying create a new Astro project in an existing directory containing a `.DS_Store` file.
I researched how other CLI tools handle this situation and found various solutions:
- Create React App [maintains a list of files](https://github.com/facebook/create-react-app/blob/d960b9e38c062584ff6cfb1a70e1512509a966e7/packages/create-react-app/createReactApp.js#L907-L934) that should be safely ignored when checking for an empty directory.
- Create Next App [uses an identical approach](https://github.com/vercel/next.js/blob/6df8770734f53a913b4846539d322e016 …
=> Add support for running `create-astro` in cloned empty git repository

.changeset/tender-nails-sip.md, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/vite-plugin-css.ts
- replaces hard-coded `minify` values with `vite.build.minify`, so that users can override minification from `astro.config`.
=> [chore] replaces hard-coded `minify` values with `vite.build.minify`

.changeset/tricky-walls-walk.md, packages/astro/test/fixtures/react-component/src/components/ImportsThrowsAnError.jsx, packages/astro/test/fixtures/react-component/src/components/ThrowsAnError.jsx, packages/astro/test/fixtures/react-component/src/pages/error-rendering.astro, packages/astro/test/react-component.test.js, packages/integrations/react/server.js
- We were not listening for the `error` event in the stream, causing an unhandled exception that crashes the server.
- Fixes https://discord.com/channels/830184174198718474/1021564982430797895
- Test added that recreates the scenario. The lack of crashing shows a passing test.
N/A, bug fix
=> Prevent errors in React components from crashing the dev server

.changeset/lovely-seals-compare.md, packages/astro/src/core/add/index.ts
This  PR fixes a bug in `toIdent` funtion used by `astro add` to convert an arbitrary NPM package name into a JS identifier.
see #4808
=> Fix extra slash when adding integrations that ends with `/astro`

.changeset/new-ties-change.md, packages/integrations/cloudflare/src/index.ts
---
'@astrojs/cloudflare': major
---
adjusted esbuild config to work with solid ssr in worker environment
- tested with solid-js and react renderer
- this is a bug fix so no change to the docs needed
=> update cloudflare esbuild config (fixing solid ssr)

.changeset/popular-deers-grow.md, packages/astro/src/runtime/server/escape.ts, packages/astro/src/runtime/server/index.ts, packages/astro/test/astro-slots.test.js, packages/astro/test/fixtures/astro-slots/src/components/RenderArgs.astro, packages/astro/test/fixtures/astro-slots/src/pages/slottedapi-render.astro
- When `set:html` is passed a promise, await its result and unescape that.
- Fixes https://github.com/withastro/astro/issues/4818
- Test added where we do not await the result of slots.render()
N/A, bug fix
=> Allow passing promises to set:html

.changeset/grumpy-monkeys-watch.md, packages/integrations/image/README.md, packages/integrations/image/src/loaders/index.ts, packages/integrations/image/src/loaders/sharp.ts, packages/integrations/image/test/background-color-image-ssg.test.js, packages/integrations/image/test/background-color-image-ssr.test.js, packages/integrations/image/test/fixtures/background-color-image/src/pages/index.astro
Following up #4642, these changes make sure we keep transparency unless the output format doesn't support alpha channel.
I also took the liberty to allow `rgba` in `ColorDefinition`, makes it possible to use transparency when combined with #4438 without TS errors.
The existing tests assume the background is flattened every time. I went ahead and specified `jpeg` as output format for existing fixtures.
=> [@astrojs/image] flatten background only if alpha channel isn't supported

.changeset/cyan-chefs-marry.md, packages/astro/src/vite-plugin-jsx/tag.ts, packages/astro/test/fixtures/react-jsx-export/astro.config.mjs, packages/astro/test/fixtures/react-jsx-export/package.json, packages/astro/test/fixtures/react-jsx-export/src/components/DeclarationExportTest.jsx, packages/astro/test/fixtures/react-jsx-export/src/components/ListExportTest.jsx, packages/astro/test/fixtures/react-jsx-export/src/components/defaultExport/AnonymousArrowDefaultExport.jsx, packages/astro/test/fixtures/react-jsx-export/src/components/defaultExport/AnonymousFunctionDefaultExport.jsx, packages/astro/test/fixtures/react-jsx-export/src/components/defaultExport/NamedArrowDefaultExport.jsx, packages/astro/test/fixtures/react-jsx-export/src/components/defaultExport/NamedFunctionDefaultExport.jsx, packages/astro/test/fixtures/react-jsx-export/src/pages/index.astro, packages/astro/test/react-jsx-export.test.js, pnpm-lock.yaml
- Update `vite-plugin-jsx/tag.ts` for  understanding of `export {X} `, `export const X`, `export default const X` and so on. You can see the full list from `astro/test/react-jsx-export.test.js` and `astro/test/fixtures/react-jsx-export`
- The full export examples are reference [MDN#export.syntax](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#syntax)
- You can see more details from [issue#4220](https://github.com/withastro/astro/issues/4220). Close #4220
- This cr is refers to [pull#4385](https://github.com/withastro/astro/pull/4385), but add tests and support for [`Anonymous Function Default Export`](https://github.com/yuhang-dong/astro/blob/7b69cee0bc1d9fa3d88157019bd8377d3089850a/packages/astro/test/fixtures/react-jsx-export/src/components/defaultExp …
=> Fix: Invalid hook call when user use export jsx function

.changeset/silent-comics-hang.md, packages/astro/src/runtime/server/escape.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/runtime/server/jsx.ts, packages/astro/src/runtime/server/render/any.ts, packages/astro/src/runtime/server/render/astro.ts, packages/astro/src/runtime/server/render/common.ts, packages/astro/src/runtime/server/render/component.ts, packages/astro/src/runtime/server/render/page.ts, packages/astro/src/runtime/server/response.ts, packages/astro/src/runtime/server/util.ts, packages/astro/test/fixtures/set-html/package.json, packages/astro/test/fixtures/set-html/public/test.html, packages/astro/test/fixtures/set-html/src/pages/fetch.astro, packages/astro/test/fixtures/set-html/src/pages/index.astro, packages/astro/test/set-html.test.js, pnpm-lock.yaml
- This allows doing `<Fragment set:html={fetch('/posts/legacy-post.html')} />` and more.
- See the changeset.
- Closes https://github.com/withastro/astro/issues/4828
- New test cases added in `packages/astro/test/set-html.test.js` for all scenarios.
- https://github.com/withastro/docs/pull/1599
=> Allow passing fetch() Response to set:html

examples/blog/src/pages/blog.astro
This changes the blog post data text color in the examples repo to meet WCAG constrat-ratio guidelines
The new color, `#595959` was tested on a white background with https://webaim.org/resources/contrastchecker/
The contrast ratio is now 7:1 where the previous contrast ratio was 3.54:1
No doc updates are needed for updating the blog post date text color in the examples folder
=> Update blog post date text color to meet contrast-ratio guidelines

.changeset/metal-bees-pretend.md, packages/integrations/mdx/README.md
- Add `MDXLayoutProps` utility to MDX README. Includes difference with `MarkdownLayoutProps`, and advises using `MarkdownLayoutProps` instead when sharing a layout across `.md` and `.mdx`.
- Add "layout props" section to explain props available.
N/A
Uh yeah
=> docs: add MDXLayoutProps to README

.changeset/curvy-needles-boil.md, packages/webapi/package.json, packages/webapi/run/build.js, packages/webapi/src/lib/fetch.ts, pnpm-lock.yaml
- Adds support for using `fetch` behind an HTTP proxy.
- Users can now configure the http proxy through the `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables.
There are no additional tests. We could potentially add tests, but it would require standing up an HTTP proxy to test through during the test, which might be non-trivial.
It would be up to your discernment whether or not we need to pursue that.
We should add a section to the docs about use behind HTTP proxies. Especially because most things that support HTTP proxies will read both the uppercase environment variables, and the lowercase environment variables, but the `global-agent` package I used to support proxies here only supports the uppercase environment variables, so that could be a gotcha, for some people. ( It …
=> Http proxy for fetch

examples/blog/src/pages/rss.xml.js
This follows the same pattern used in https://github.com/withastro/astro/blob/main/examples/blog/src/pages/blog.astro#L8. Without adding `mdx` here, only some blog posts will be part of the rss.xml file.
This makes sure that the rss.xml lists the same posts as the /blog/ index.
> Don't forget a changeset! `pnpm exec changeset`
Don't know what that means. This change is made via the Github Edit UI.
I tested the issue in the page I am building ATM.
=> examples rss: add mdx file ending

.changeset/hot-lamps-search.md, packages/astro/src/core/build/index.ts, packages/astro/test/dont-delete-root.test.js, packages/astro/test/fixtures/dont-delete-me/astro.config.mjs, packages/astro/test/fixtures/dont-delete-me/package.json, packages/astro/test/fixtures/dont-delete-me/src/pages/index.astro, pnpm-lock.yaml
- If `outDir === root` throw a helpful error message. Not doing so blows away the root folder.
- Fixes https://github.com/withastro/astro/issues/4844
- Test added
N/A, bug fix
=> Prevent the root from being deleted during the build

.github/workflows/check-merge.yml
- This adds a new action that checks PRs to see if they can be merged, based on whether they have a changeset marked as minor.
- If there is a minor changeset it will add a blocking review that needs to be overridden.
- If there is already a blocking review from this bot, do not apply it a second time.
- Adds the `semver minor` label automatically.
- Tested in this PR - https://github.com/withastro/astro/pull/4853
N/A
=> Add action to check if PR can be merged

.changeset/fluffy-doors-vanish.md, packages/astro/src/runtime/server/escape.ts
- Prevents errors when not using `skipLibCheck`
- Tests should continue to pass
N/A
=> Define toStringTag another way

packages/integrations/alpinejs/README.md, packages/integrations/deno/README.md, packages/integrations/image/README.md, packages/integrations/mdx/README.md, packages/integrations/netlify/README.md, packages/integrations/node/README.md, packages/integrations/partytown/README.md, packages/integrations/preact/README.md, packages/integrations/prefetch/README.md, packages/integrations/sitemap/README.md, packages/integrations/tailwind/README.md, packages/integrations/vercel/README.md
Updated doc references from `#support-threads` to `#support`. 
Visually.
Updated doc references from `#support-threads` to `#support`.
=> docs: Update references to support channel in Discord.

packages/integrations/cloudflare/README.md, packages/integrations/lit/README.md, packages/integrations/react/README.md, packages/integrations/solid/README.md, packages/integrations/svelte/README.md, packages/integrations/turbolinks/README.md, packages/integrations/vue/README.md
- Adds the `Troubleshooting` and `Contributing` sections to the following `README.md` files in `packages/integrations` as discussed at in #4872.
- `cloudflare`
- `lit`
- `react`
- `solid`
- `svelte`
- `turbolinks`
- `vue`  
This brings those documents inline with the other Astro supported packages.
I found lots of instances where my markdown linting in VSCode was complaining about other items, but I avoided my desire to "clean up" additional items. 
There were places where it was unclear where these headings should live, such as in the `@astro/vue` and `@astro/svelte` packages where there was previously a line mentioning checking out the Astro Integration Documentation, but appeared not at the end of the files as many others, but instead prior to `Options` and other integration related …
=> docs: Standardize troubleshooting and contributing sections for integrations

.changeset/lucky-comics-bow.md, packages/astro/src/runtime/server/hydration.ts
fixes #4001 
With the specific reproduction, it seemed as if class:list in component with mapped attributes would always created even if value is undefined. Fixed it by checking if value exists beforehand, else it gets to the point `push(value)` and hence the empty class attribute.
=> fix: 🐛 BUG: class:list directive adding class attribute when undefined

.changeset/mighty-garlics-exercise.md, packages/astro/src/core/render/route-cache.ts, packages/astro/src/core/routing/params.ts, packages/astro/test/fixtures/routing-priority/src/pages/empty-slug/[...slug].astro, packages/astro/test/routing-priority.test.js, packages/astro/test/test-utils.js
Fix #4796 
In dev, for pages declared like `pages/[...slug].astro`, if `slug` is `undefined`, only serve at `http://localhost:3000` and `http://localhost:3000/`. Don't serve `http://localhost:3000/undefined`
This PR makes `undefined` and `"undefined"` as 2 distinct static paths to differentiate them, by not stringifying `undefined`.
Note: In build, `http://localhost:3000/undefined` is never built. So this PR makes dev consistent with build.
Added a test under `routing-priority`
N/A.
=> Prevent /undefined catch-all routes in dev

.changeset/cool-camels-tease.md, packages/astro/src/runtime/server/render/util.ts, packages/astro/test/astro-directives.test.js
fixes #4859, specifically: https://github.com/withastro/astro/issues/4859#issuecomment-1256944568
Have another approach in mind using (https://stackoverflow.com/questions/7944460/detect-safari-browser/31732310#31732310), but since define:vars is supposed to be used as passing prop on SSR (whether static build or SSR build), changing to a const shall not affect client-side operations. We might need to put alert on docs tho.
=> fix: Script with innerHTML not working on Safari

examples/ssr/src/pages/index.astro, packages/astro/src/runtime/server/render/page.ts, packages/astro/test/astro-not-response.test.js, packages/astro/test/fixtures/astro-not-response/package.json, packages/astro/test/fixtures/astro-not-response/src/pages/not-response.astro, pnpm-lock.yaml
- Add a more detailed error message on Astro file not returning an instance of `Response`
Not sure how to test this, I would love any pointer on this.
Behavior is already documented
Related issue: https://github.com/withastro/astro/issues/4631
=> add double check on astro file Response return type with more readable error

packages/astro/src/runtime/server/render/util.ts
Attempts to fix #4865 
I'm not a regex master, but given that here negative lookahead, shall behave same as lookbehind (as for matching spaces (or anything)). To me these two regexs seem same as checked on regex101.com's explanation.
This happens as the component is loaded with client:idle that requires that chunk of JS to be inserted as an island so it runs in the browser eventually.
=> fix: Lookbehind regex crashing on Safari

.changeset/curvy-comics-smash.md, packages/integrations/vercel/src/edge/adapter.ts
Fix #4630
Vercel edge, like Cloudflare, doens't have access to nodejs modules. Set `ssr.target: 'webworker'` so that Vite resolves the `browser` field of packages instead.
Ran `npm run build` with [this repro](https://stackblitz.com/edit/github-vgszev?file=astro.config.mjs) locally.
N/A. This should work ootb without docs.
=> Set SSR target webworker for Vercel edge

packages/integrations/tailwind/README.md
- File paths in the repo have moved, updated documentation to match the new location
Docs only change
Docs only change
=> docs: Fix links to Tailwind examples

.changeset/popular-horses-lie.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/render/result.ts, packages/astro/src/runtime/server/render/head.ts, packages/astro/test/fixtures/lazy-layout/package.json, packages/astro/test/fixtures/lazy-layout/src/layouts/Main.astro, packages/astro/test/fixtures/lazy-layout/src/pages/index.astro, packages/astro/test/lazy-layout.test.js, pnpm-lock.yaml
- When there is a lazy layout it creates a split point and a new chunk. The chunk imports from the main entrypoint to render the head.
- This resulted in 2 instances of the weakmap :D, which meant that we falsely would render the head contents twice.
- The fix is to remove the global weakmap and instead store this state on result._metadata, which is the same instance throughout.
- Closes https://github.com/withastro/astro/issues/4757
- Test added
N/A, bug fix
=> Ensure head content rendered once with lazy layouts

.changeset/smart-elephants-check.md, packages/astro/src/runtime/server/render/any.ts, packages/astro/src/runtime/server/render/component.ts, packages/astro/src/runtime/server/render/dom.ts, packages/astro/src/runtime/server/render/index.ts, packages/astro/src/runtime/server/render/slot.ts, packages/astro/test/astro-slots-nested.test.js, packages/astro/test/fixtures/astro-slots-nested/astro.config.mjs, packages/astro/test/fixtures/astro-slots-nested/package.json, packages/astro/test/fixtures/astro-slots-nested/src/components/Inner.tsx, packages/astro/test/fixtures/astro-slots-nested/src/components/Parent.jsx, packages/astro/test/fixtures/astro-slots-nested/src/pages/hidden-nested.astro, pnpm-lock.yaml
- When we encounter a slot that contains hydration scripts, hoist those hydration scripts out of the template. This ensures that they are rendered within the body.
- Closes https://github.com/withastro/astro/issues/4343
- Test added, ensures that the hydration script is not created within the template.
N/A, bug fix
=> Hoist hydration script out of slot templates

examples/basics/src/components/Card.astro, examples/basics/src/layouts/Layout.astro, examples/basics/src/pages/index.astro
- Redesigned the look to match our new homepage!
- This is purely copy + CSS changes, no behavior changes
- Simplified the CSS to be less overwhelming, removed some advanced CSS features and styles that felt out of scope for a basics template.
=> redesign basics template

.changeset/small-bugs-prove.md, packages/astro/package.json, packages/astro/test/css-order-import.test.js, packages/astro/test/css-order.test.js, packages/astro/test/fixtures/css-order-import/package.json, packages/astro/test/fixtures/css-order-import/src/components/One.astro, packages/astro/test/fixtures/css-order-import/src/components/Two.astro, packages/astro/test/fixtures/css-order-import/src/pages/component.astro, packages/astro/test/fixtures/css-order-import/src/pages/index.astro, packages/astro/test/fixtures/css-order-import/src/styles/One.css, packages/astro/test/fixtures/css-order-import/src/styles/base.css, pnpm-lock.yaml
- In a case like this:
```astro
---
import '../styles/global.css';
---
<style>
body { background: salmon; }
</style>
```
The Astro styles should be placed *after* the imported styles, so that they are preferred if their specificity is the same.
- Depends on https://github.com/withastro/compiler/pull/525
- Closes https://github.com/withastro/astro/issues/3357
- Tested in both development and production.
N/A, bug fix
=> Fix CSS ordering between imported and Astro styles

.changeset/thirty-crabs-shout.md, packages/astro/client-base.d.ts, packages/astro/env.d.ts, packages/astro/tsconfig.json
It turns out that importing Markdown and MDX files works outside of Astro files, so the module declaration needs to be in `client-base.d.ts` and not `env.d.ts`. The latter being only things available in Astro files
Tested manually. Stackblitz showing the behaviour working: https://stackblitz.com/edit/github-skrkkd?file=src%2Fscript.ts,src%2Fpages%2Findex.astro&on=stackblitz
N/A
=> Move module declarations for Markdown and MDX so they're available everywhere

tsconfig.json
- It's a long story.
- Basically, this prevents TypeScript from crawling up your entire directory tree. Turns out if you had a `tsconfig.json` file above this repo, things got weird.
N/A, internal change only
=> Add empty `tsconfig.json`

.changeset/tall-files-smash.md, packages/astro/src/jsx-runtime/index.ts, packages/astro/src/runtime/server/jsx.ts, packages/integrations/mdx/test/fixtures/mdx-infinite-loop/astro.config.ts, packages/integrations/mdx/test/fixtures/mdx-infinite-loop/package.json, packages/integrations/mdx/test/fixtures/mdx-infinite-loop/src/components/Test.js, packages/integrations/mdx/test/fixtures/mdx-infinite-loop/src/components/Test.jsx, packages/integrations/mdx/test/fixtures/mdx-infinite-loop/src/pages/doc.mdx, packages/integrations/mdx/test/fixtures/mdx-infinite-loop/src/pages/index.astro, packages/integrations/mdx/test/mdx-infinite-loop.test.js, pnpm-lock.yaml
- Got reports of a possible memory leak
- Was able to narrow it down to MDX (our internal `jsx-runtime`) when an error was being thrown.
- These errors were ignored and users would be dropped into an infinite loop
- This PR fixes this by adding the `[Renderer]: 'astro:jsx'` to JSX vnodes, so we know immediately that they should be rendered with the JSX renderer. If this throws, we'll be able to surface the error.
Adds a regression test in `@astrojs/mdx` and tested manually
Bug fix only
=> P5: fix MDX memory leak

packages/integrations/image/README.md
Adds a language tag to a recently added code block in the image integration README.
No testing, docs change only.
Fix for docs CI issue https://github.com/withastro/docs/pull/1649
=> Fix missing language tag on README code block

.changeset/clever-lies-reflect.md, packages/integrations/image/package.json, pnpm-lock.yaml
Change in astro image (/packages/integrations/image). Moved 'http-cache-semantics' package from dev-dependency to dependency to resolve error "Cannot find package 'http-cache-semantics' imported from /Volumes/BFD/Sites/scottwillsey2.0/node_modules/@astrojs/image/dist/build/ssg.js"
ran "pnpm run test:match "image"
No doc changes needed
No change in component functionality or use method. Fixing runtime error for component dependency.
=> Astro image cache dependency fix scottaw66

.changeset/moody-gifts-press.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/types.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/integrations/index.ts
Vite 3 stabilizes the `.ssr` property and is exposed from the types, so this type isn't needed anymore
N/A
=> Refactor ViteConfigWithSSR type

.changeset/tough-turkeys-teach.md, .eslintrc.cjs, packages/integrations/mdx/src/index.ts
Suppress `console.log` usage warnings from eslint in integration packages
N/A. GitHub shouldn't annotate them in the UI anymore.
N/A
=> Suppress eslint warnings

.changeset/fifty-icons-smash.md, packages/astro/src/runtime/server/render/common.ts, packages/astro/test/benchmark/simple/astro.config.mjs, packages/astro/test/benchmark/simple/package.json, packages/astro/test/benchmark/simple/server.mjs, packages/astro/test/benchmark/simple/src/components/Layout.astro, packages/astro/test/benchmark/simple/src/pages/index.astro, pnpm-lock.yaml
- Note that this is just a draft and might not be an improvement.
- In 1.3.0 in order to support typed arrays in the template (via set:html) I switched how we concat HTML to first convert to byte arrays. I'm not sure why this caused the slowdowns (still investigating). It does add an extra loop which could be part of it.
- New benchmark test added
- Note that this test isn't running in CI at the moment. The plan is to do a follow-up that makes it run as a nightly task.
N/A, bug fix
=> Improve rendering perf

.github/workflows/benchmark.yml, package.json
- Adds a new special comment for running benchmarks on a PR.
=> Run benchmarks on comment

.changeset/breezy-teachers-clean.md, packages/astro/src/runtime/server/render/any.ts
- This should ultimately fix the issues that came with 1.3.0
- Was using `instanceof` to check if a string is an escaped string, but there is 2 instances of this module so instanceof is returning false negative.
- This was likely happening for a long time but still working on accident.
- In 1.3.0 I added the ability for the template to handle iterators. Since a string *is* an iterator it would iterate on each character in the string.
- The result was that we were rendering 1 character at a time. Very slow!
- Fixes #4958
- Fixes #4900
Benchmarks should show
N/A, bug fix.
=> Fix regression in rendering strings

.changeset/friendly-wolves-juggle.md, packages/astro/src/core/render/result.ts, packages/astro/src/runtime/server/jsx.ts, packages/astro/test/fixtures/slots-react/src/components/Render.astro, packages/astro/test/fixtures/slots-react/src/components/RenderArgs.astro, packages/astro/test/fixtures/slots-react/src/components/RenderFn.astro, packages/astro/test/fixtures/slots-react/src/pages/slottedapi-render.mdx, packages/astro/test/slots-react.test.js
Fix #4826
The `Astro.slots.render` API only renders Astro slots, but not JSX slots. This PR updates the API to support rendering JSX slots.
Copied astro-slots tests for `Astro.slots.render` for mdx.
N/A. this should be working in the first place.
=> Support Astro.slots.render for mdx

.changeset/lemon-pets-sneeze.md, packages/astro/src/core/render/route-cache.ts, packages/astro/src/vite-plugin-astro-server/index.ts
Closes #4633
The cache used for `getStaticPaths()` will warn if it's called a second time for the same route.  This PR updates the warning to only be logged in production builds since HMR will trigger a cache invalidation in `dev`
All existing tests should pass - no new tests since it's just a logger fix
None, logging bug fix only
=> closes #4633

.changeset/swift-moles-crash.md, packages/astro/src/runtime/server/render/util.ts, packages/astro/test/astro-object-style.test.js, packages/astro/test/fixtures/astro-object-style/package.json, packages/astro/test/fixtures/astro-object-style/src/components/Span.astro, packages/astro/test/fixtures/astro-object-style/src/pages/component.astro, packages/astro/test/fixtures/astro-object-style/src/pages/index.astro, pnpm-lock.yaml
Before this PR:
```
<div
style={{
backgroundImage: `url("test.png")`,
}}
>
</div>
```
would be rendered as
```
<div
style="background-image: url("test.png")"
>
</div>
```
which is invalid HTML, since the quotes in url are not escaped.
After the fix in this PR, the output is:
```
<div
style="background-image: url(&#34;test.png&#34;)"
>
</div>
```
Also found a bug where `shouldEscape` isn't passed down to `toAttributeString` and I fixed it.
Added `astro-object-style` test
Minor fix
=> fix object styles not escaped

packages/integrations/lit/README.md
- Documents the limitations with using the Lit integration because its DOM shim can interfere with other libraries.
- Closes https://github.com/withastro/astro/issues/4994
N/A, just docs
Yep
=> Document Lit's limitations in SSR

packages/integrations/node/README.md
This documents a workaround for the node integration [issue](https://github.com/withastro/astro/issues/4974) that people are asking about in [support threads](https://discord.com/channels/830184174198718474/1025507121481134131).
Docs only
=> Docs: add yarn workaround to node integration docs

.changeset/cold-colts-laugh.md, packages/integrations/prefetch/src/client.ts, packages/integrations/prefetch/test/basic-prefetch.test.js, packages/integrations/prefetch/test/custom-selectors.test.js, packages/integrations/prefetch/test/fixtures/basic-prefetch/src/pages/index.astro
- As described in #4963 a check is added to ensure that the current page is not requested if present as a prefetch link
- Removed useless hash check that most probably was a typo IMHO
- Added prefetch link to `"/"` to the test page
- Added tests to check that the path `"/"` is only requested once
- Refactored the unnecessary use of `await` keyword
As this is a bugfix, no docs change is needed.
Fixes #4963
=> [@astrojs/prefetch]: Prevent prefetching current page

.changeset/smooth-horses-repeat.md, packages/astro/config.mjs, packages/astro/src/config/index.ts
- Moves astro/config into `src/` so we get typechecking.
- Regression occurred due to some files being moved around. We didn't know it broke astro/config because it was a plain .mjs file.
- Closes https://github.com/withastro/astro/issues/4910
- Typechecks now, that's a test!
N/A, bug fix
=> Move astro/config into src and typecheck

.changeset/friendly-bottles-push.md, packages/integrations/react/src/index.ts
- Adds configuration for mui
- Closes https://github.com/withastro/astro/issues/4079
=> Fix support for mui

.changeset/chilly-carrots-think.md, packages/astro/src/runtime/server/render/page.ts
- limiting doctype injection to the first occurrence of html string
with the example from the solid framework (by adding the cloudflare adapter)
just a simple fix, so no doc update required.
=> fixing multiple doctype injections in single file

.changeset/six-oranges-shop.md, packages/astro/src/core/build/vite-plugin-css.ts
- This shortens the naming algorithm for CSS bundles. Previously we were concatenating each page in the bundle's from-src path which created some long names.
- Now this takes just the last segment from the first page, for example `src/pages/about.astro` it takes just `about` and then also hashes all of the page ids, which gives us our unique hash.
- With this change names will be shortened to something like: `about.f6e31204.css` in all cases.
- Closes https://github.com/withastro/astro/issues/4672
- Tested with the examples to ensure short names
- Tests should pass
N/A, bug fix
=> Shorter CSS naming algorithm

.changeset/small-laws-dream.md, packages/integrations/image/package.json, packages/integrations/image/src/index.ts, pnpm-lock.yaml
Fix #4995
- Add deps to `ssr.external` so they are not transformed by Vite when calling `ssrLoadModule` to load the renderer.
- Move `kleur` as dependency as it's used in `ssg.ts`
Note: Vite's SSR externalization doesn't take into account of loading modules from `node_modules` hence we got this issue and have to use `ssr.external` manually. This could be fixed in Vite, but I feel like we should use normal `import()` to load renderers instead (that would be a breaking change)
This one's hard to test due to our monorepo structure, however I tested the repro in #4995 which works with this PR.
Existing tests should ideally pass too.
N/A. should work by default.
=> Support strict dependency install for image integration

.changeset/famous-dancers-explain.md, packages/integrations/vercel/package.json, packages/integrations/vercel/src/lib/fs.ts, packages/integrations/vercel/src/lib/nft.ts, packages/integrations/vercel/src/serverless/adapter.ts, pnpm-lock.yaml
Fixes #5020
`@astrojs/vercel` now supports monorepos correctly by adding files outside the project root (like the node_modules/ in the monorepo root)
```bash
$ pnpm add @astrojs/vercel@next--monorepos
```
=> fix(vercel): now works with monorepos

.changeset/sixty-ladybugs-return.md, packages/astro/package.json, pnpm-lock.yaml
Upgrade Astro compiler to 0.27.1 (fixes regression withastro/compier#556)
=> chore: Upgrade Astro compiler to 0.27.1

.changeset/early-pillows-deliver.md, packages/integrations/svelte/client.js
- Closes https://github.com/withastro/astro/issues/5029
- This code was old, from when the old compiler would *always* pass a class (the Astro class name). It's no longer needed and causes the above bug.
Tested in the examples
N/A, bug fix
=> Allow `class` to be passed into Svelte islands

packages/astro/components/Code.astro
in enable word wrapping, options are: true: enabled , false: enabled 
but it should be: true: enabled , false: disabled.
=> fix a typo in Code component's wrap prop

.changeset/serious-icons-dream.md, packages/astro/src/vite-plugin-jsx/tag.ts, packages/astro/test/fixtures/react-jsx-export/src/components/ListExportTest.jsx, packages/astro/test/fixtures/react-jsx-export/src/components/ListExportTestComponent.jsx, packages/astro/test/fixtures/react-jsx-export/src/pages/index.astro, packages/astro/test/react-jsx-export.test.js
Skip tagging `__astro_tag_component__` for `export { foo } from './somewhere'` as `foo` can't be referenced.
Partial fix for #4871
Added a test
N/A. a bug.
=> Skip JSX tagging for export statements with source

.changeset/witty-sheep-wave.md, packages/astro/src/core/cookies/cookies.ts, packages/astro/test/units/cookies/set.test.js, packages/integrations/deno/test/basics.test.ts, packages/integrations/deno/test/fixtures/basics/src/pages/admin.astro, packages/integrations/deno/test/fixtures/basics/src/pages/login.astro
- We were already allowing number and boolean but types did not reflect.
- Closes https://github.com/withastro/astro/issues/5031
Test added for booleans since there wasn't one.
N/A
=> Update the Astro.cookies.set types to receive boolean and numbers

.changeset/ten-phones-drop.md, .changeset/thin-parents-breathe.md, packages/astro/package.json, packages/astro/src/vite-plugin-jsx/index.ts, packages/astro/src/vite-plugin-jsx/tag.ts, packages/astro/test/fixtures/solid-component/package.json, packages/astro/test/fixtures/solid-component/src/pages/index.astro, packages/integrations/solid/src/dependencies.ts, packages/integrations/solid/src/index.ts, pnpm-lock.yaml
Fix #4871 
- Auto add solidjs deps to `ssr.noExternal` same as [vite-plugin-solid](https://github.com/solidjs/vite-plugin-solid/blob/03130c8a0a2ceaab9a07e16f1e1df832b996e1b8/src/index.ts#L251-L297)
- Support `__astro_tag_component__` in node_modules, since it imports `astro/server/index.js` in node_modules (doesn't work in pnpm). This PR pre-resolve `astro/server/index.js` to an absolute path.
Added `@solidjs/router` to test, which previously would error the app entirely.
Not sure if we should document the `noExternal` behaviour, it might be an implementation detail we want to hide.
=> Support solidjs libraries

.changeset/happy-mayflies-sort.md, packages/integrations/image/src/index.ts
Fix regression from https://github.com/withastro/astro/pull/5034
That PR fixes dev but breaks build for strict dependency installation. This removes the changes in #5034 for build only.
Tested while working on #4925. Similar to #5034 it's tricky to create a test for this.
N/A
=> Fix image external config in build

.changeset/honest-crabs-scream.md, packages/astro/src/core/config/tsconfig.ts
Starting from 1.5.0, aliases inside `jsconfig.json` were not being properly picked up anymore, this fix that. The issue was that we were returning the original `tsconfig.json` error before checking for a `jsconfig.json`
We can't test this! Since we first try for a `tsconfig.json` before falling back to `jsconfig.json`, in the monorepo we always end up finding another `tsconfig.json` up the filesystem (notably, the new one at root added by Nate after his `tsconfig.json` adventures). 
`jsconfig.json` are.. kinda rare. All of our templates includes `tsconfig.json`, `astro add` adds `tsconfig.json` etc. So I think it's not that bad for it to not be tested. Loading a `jsconfig.json` directly however is tested
N/A
=> Fix aliases from jsconfig.json not being picked up anymore

.changeset/dry-moose-join.md, packages/integrations/vue/README.md, packages/integrations/vue/client.js, packages/integrations/vue/package.json, packages/integrations/vue/server.js, packages/integrations/vue/src/index.ts, packages/integrations/vue/test/app-entrypoint.test.js, packages/integrations/vue/test/fixtures/app-entrypoint/astro.config.mjs, packages/integrations/vue/test/fixtures/app-entrypoint/package.json, packages/integrations/vue/test/fixtures/app-entrypoint/src/components/Bar.vue, packages/integrations/vue/test/fixtures/app-entrypoint/src/components/Foo.vue, packages/integrations/vue/test/fixtures/app-entrypoint/src/pages/_app.ts, packages/integrations/vue/test/fixtures/app-entrypoint/src/pages/index.astro, packages/integrations/vue/test/test-utils.js, pnpm-lock.yaml
- Adds support for `appEntrypoint` option in `@astrojs/vue` integration
- `appEntrypoint` is a root-relative import specifier to the app entrypoint file
- `appEntrypoint` should export a default isomorphic function that receives a Vue `app` instance. The return type is `void | Promise<void>`.
- This exposes [Vue Plugins](https://vuejs.org/guide/reusability/plugins.html) to users!
Tests added to Vue integration directly
TODO
=> [Vue] add support for `appEntrypoint`

packages/astro/src/core/app/index.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/endpoint/dev/index.ts, packages/astro/src/core/endpoint/index.ts, packages/astro/src/core/render/context.ts, packages/astro/src/core/render/core.ts, packages/astro/src/core/render/dev/environment.ts, packages/astro/src/core/render/dev/index.ts, packages/astro/src/core/render/dev/resolve.ts, packages/astro/src/core/render/environment.ts, packages/astro/src/core/render/index.ts, packages/astro/src/core/render/renderer.ts, packages/astro/src/core/render/result.ts, packages/astro/src/jsx/component.ts, packages/astro/src/jsx/index.ts, packages/astro/src/runtime/server/index.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/units/render/jsx.test.js
- This refactors `core/render` to make it easier to test. The goal is to be able to create rendering tests directly in JavaScript without the need for fixtures.
- Main change is that `core/render` now has 2 new types:
- `Environment` is an object that contains things that do not change between requests, such as the logging options, the routeCache, the markdown options, etc.
- `RenderContext` is an object that contains things specific to a request, such as the request object and the scripts/styles that need to be included.
- Some basic tests are added, more to come with bugs.
- Fixture tests should all pass as no external API changes occurred.
N/A, internal refactor
=> Refactor rendering for testing

.github/workflows/benchmark.yml, package.json
Currently it is output like this:
```
**Node**: 14
**PR**: [0m[1][0m 23k requests in 30.11s, 1.57 GB read
**MAIN**: [0m[1][0m 22k requests in 30.08s, 1.53 GB read
```
With this PR it should instead become:
```
**Node**: 14
**PR**: 23k requests in 30.11s, 1.57 GB read
**MAIN**: 22k requests in 30.08s, 1.53 GB read
```
=> Improved benchmark output

packages/integrations/node/README.md
- Fix node adapter exemple in README to match the function used bellow 
no need
no need
(And thanks for building Astro, I use it daily at work, It's realy great :) )
=> doc(node): fix wrong import

.changeset/tender-cars-wait.md, packages/integrations/tailwind/src/index.ts
- Tailwind is depending on an Astro 1.5 API. This fixes that
no, quick fix
N/A, bug fix
=> Compat with Astro < 1.5

.changeset/tender-lemons-remain.md, packages/astro/src/core/add/index.ts
`pnpm install <pkg>` is deprecated, `pnpm add <pkg>` should be used instead
=> fix: pnpm install command on astro add

.changeset/silver-hotels-jam.md, packages/integrations/solid/src/dependencies.ts
The latest solidjs integration crawls for solidjs libraries, but this generates a warning for pure ESM libraries that do not have a CJS entrypoint (since it relies on `require.resolve`).
Since the crawling is best-effort, we can suppress the warning here.
Tested with a local project.
N/A
=> Suppress warnings for solidjs dependency crawling

.changeset/hot-dogs-leave.md, packages/integrations/vercel/src/edge/adapter.ts
- Minify Edge output to save space
- Throw an error when `"output": "static"` in astro config
=> feat(vercel): Edge improvements

.changeset/olive-jeans-shout.md, packages/astro/astro-jsx.d.ts, packages/astro/config.d.ts, packages/astro/env.d.ts, packages/astro/import-meta.d.ts, packages/astro/package.json
`moduleResolution: 'node16'` absolutely requires file extensions to be added to import paths, we were missing those in a few places which caused `astro check` (and in the editor too) to not being able to properly get certain types. This fix that
Fix https://github.com/withastro/astro/issues/5100
N/A
=> Fix types not working properly when using `moduleResolution: 'node16'`

examples/docs/src/config.ts
replace missing `banner.jpg` resource with available `banner-minimal.png` in `config.ts` for docs example.
tested new url. non astro related. no test required.
does not effect astro. no documentation changes required.
=> Fix missing image src in config for examples docs

.changeset/eighty-planes-kneel.md, packages/astro/src/core/config/schema.ts, packages/astro/test/fixtures/astro-basic/astro.config.mjs
Fix #5102 
Revive the attached CLI flags props from https://github.com/withastro/astro/blob/c0db5818e995ea531af86c1f539129d59a260241/packages/astro/src/core/config/config.ts#L118-L127
Updated the `astro-basic` config that would cause `cli.test.js` to fail without this PR
n/a
=> Ensure CLI flags override function-style server config

.changeset/gold-roses-argue.md, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/core/routing/manifest/generator.ts, packages/astro/test/fixtures/routing-priority/src/pages/api/catch/[...slug].json.ts, packages/astro/test/fixtures/routing-priority/src/pages/api/catch/[foo]-[bar].json.ts, packages/astro/test/routing-priority.test.js
Fix #3671 
Support `[...slug].json.ts`. `[...slug].ts` already works, but the `.json` was tripping the path matcher. 
I've marked this as a patch as this was supposed to work, but it could also be a minor.
Added `routing-priority` tests
N/A. Routing logic has been explained in https://docs.astro.build/en/core-concepts/routing/ so they should apply here too.
=> Support spread parameters for server endpoints

.changeset/little-dodos-beam.md, packages/astro/astro-jsx.d.ts
- Separates built-in elements and custom elements from the `IntrinsicElements` type definition
- This lets you use `keyof DefinedIntrinsicElements` to get a list of all supported HTML elements, for implementing an `as` prop similar to [styled-components](https://styled-components.com/docs/api#as-polymorphic-prop)
- Fixes #4915
I did not test this Typescript-only change. I didn't see any references to the changed type in the codebase, but I'm happy to add tests if necessary. Please provide guidance on what those might look like.
The `IntrinsicElements` type interface is not documented anywhere at the moment, so this change shouldn't require any documentation updates.
=> Implicit element types

.changeset/afraid-baboons-return.md, packages/integrations/node/src/index.ts
- We want the server.js to be bundled, so that we can find the relative path to the `client/` directory.
- Fixes https://github.com/withastro/astro/issues/5093
- Tests already worked within the monorepo, because the monorepo does not allow actual node_modules/ folders which is where the bug occured.
- Tested with the example in the issue.
N/A, bug fix
=> Mark @astrojs/node to be noExternal

.changeset/tall-trainers-do.md, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/dev-routing.test.js, packages/astro/test/fixtures/without-site-config/src/pages/redirect.astro
- Closes https://github.com/withastro/astro/issues/4948
Test case added
N/A, bug fix
=> Throw when using Response.redirect from SSG site

examples/docs/src/components/Header/LanguageSelect.tsx
adding a 2nd (or more) language(s) to the docs example template breaks the map at the end of LanguageSelect.tsx. This causes hydration errors and ReactDOM warnings (see screenshot) complaining about child tags of \<option\> tags in the map. Although the selector and pages function despite the errors, one of the errors is: "the entire root will switch to client rendering".
- Removing \<span /\> tags appears to resolve warnings and errors and functionality is as expected (language selector works).
Followed the Multiple Languages support section from README.md and added the required translated content pages for Spanish. After removing the \<span /\> tags, both spanish and english worked as expected in the selector.
This change may not require changes to users behavior, nor may docs require …
=> fix KNOWN_LANGUAGES option child element for multi-language support

.changeset/many-lions-relate.md, packages/astro/src/core/build/common.ts, packages/astro/src/core/build/generate.ts, packages/astro/test/dynamic-route-build-file.test.js, packages/astro/test/fixtures/dynamic-route-build-file/index.html, packages/astro/test/fixtures/dynamic-route-build-file/package.json, packages/astro/test/fixtures/dynamic-route-build-file/src/pages/[...slug].astro, pnpm-lock.yaml
- When using `build.format=file` and a dynamic route of `undefined`, do not use `path.dirname(pathname)` because that will result in `.` and thus build the file to the parent folder.
- Fixes https://github.com/withastro/astro/issues/5121
- Fixture test case added
N/A,  bug fix
=> Fixes index page with build.format=file

.changeset/eight-swans-divide.md, packages/astro/src/core/build/static-build.ts
`fs.promises.rmdir` is deprecated. I got this warning when building:
```
(node:45043) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
```
https://nodejs.org/api/deprecations.html#DEP0147
Use `fs.promises.rm(path, { recursive: true, force: true })` instead.
N/A
=> Use `fs.promises.rm` to remove node deprecation warning

.changeset/silly-windows-sin.md, packages/integrations/vue/src/index.ts
- Since `vuetify` is a common library, we should include the necessary configuration out of the box
- This PR includes the proper configuration for `vuetify` in the `@astrojs/vue` integration
N/A, config change only
N/A, config change only
=> Automatically include `vuetify` in `ssr.noExternal`

.changeset/clever-keys-hammer.md, packages/integrations/mdx/README.md, packages/integrations/mdx/package.json, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/fixtures/mdx-plugins/src/pages/with-plugins.mdx, packages/integrations/mdx/test/mdx-plugins.test.js
- Expose `recmaPlugins` from MDX config
Test that recma plugin transforms are used
Add `recmaPlugins` to README. this is an in-the-weeds feature, so I didn't provide an example plugin here.
=> [MDX] Support `recmaPlugins` config

.changeset/chilly-experts-add.md, packages/integrations/image/components/Image.astro, packages/integrations/image/components/Picture.astro
This removes the `content-visibility: auto` style added to `<Image />` and `<Picture />` components by default.
**Why?** This came up in a [docs issue](https://github.com/withastro/docs/issues/1517) where the style actually broke a user's layout.  This style really doesn't impact most layouts and is rarely needed, removing this from our components leaves all image styling up to a user's project-specific styling
None, styling fix only
Fixes a bug that raised docs questions, no new docs needed 🎉 
=> Removes default content-visibility styles from image components

package.json, pnpm-lock.yaml
There are two ways to use `only-allow`:
1. `"scripts": { "preinstall": "npx only-allow pnpm" }`:
- It's not necessary to install the `only-allow` dependency when using `npx`, this is the usage the [pnpm docs](https://pnpm.io/only-allow-pnpm) show.
2. `pnpm add -D only-allow` + `"scripts": { "preinstall": "only-allow pnpm" }`: 
-  This is an alternative I ran across in https://github.com/pnpm/only-allow/issues/9
**Edit: going with option 1 [as per @bluwy](https://github.com/withastro/astro/pull/5184#issuecomment-1290190494), disregard the following.**
Given that https://github.com/withastro/astro/pull/5131 already added `only-allow` as a dependency, and that @matthewp raised the possibility of installing npm adding time to CI, approach (2) seems best.
Happy to close this and open a PR with …
=> Uninstall `only-allow`

.changeset/smart-chicken-develop.md, packages/astro/src/core/add/index.ts
Closes #5191 
`astro add` will automatically install peer dependencies for the integration being installed.  This updates that check to ignore peer dependencies marked as optional, ex: `sharp` is optional for `@astrojs/image`
Tested manually with `astro add image`
**Before**
**After**
Bug fix only, no docs update
=> Updates `astro add` to ignore optional peer dependencies

packages/integrations/mdx/README.md
- fixes a few formatting issues in the README
- updates section about custom components in imported mdx
It's just a documentation change, hence a changeset is not required.
Closes #5027
This PR replaces #5055, that would fail mergeability check for unknown reason.
It's just a documentation change, hence tests are not required.
It's just a documentation change.
=> [MDX] Improved docs for custom components

.changeset/poor-frogs-clean.md, packages/integrations/cloudflare/README.md, packages/integrations/cloudflare/package.json, packages/integrations/cloudflare/src/runtime.ts, packages/integrations/cloudflare/src/server.advanced.ts, packages/integrations/cloudflare/src/server.directory.ts
- adding a runtime symbol onto the request object to enable access to the `cloudflare` runtime, therefore enables to `KV`,  `Durable Objects`, `R2` services
Take any example from the repo and add `cloudflare` to astro. Add the following lines into the index:
```
// get runtime
const runtime = Reflect.get(Astro.request, Symbol.for("runtime"));
if (runtime && runtime.name === "cloudflare") {
console.log("Running on Cloudflare Workers");
}
```
This would add a piece of documentation to the `cloudflare` worker how it is possible to access services like `KV`, `R2` and `Durable Objects`.
=> enable access to cloudflare runtime

.changeset/dirty-cycles-lick.md, packages/astro/package.json, packages/astro/type-utils.d.ts, packages/astro/types.d.ts
- We have some common patterns that folks ask about, so this adds an `astro/types` entrypoint with some helpful utility types.
- This keeps folks from needing to access the `astroHTML.JSX.AnchorHTMLAttributes` stuff directly
- Based on docs section [TypeScript: Common Prop Type Patterns](https://docs.astro.build/en/guides/typescript/#common-prop-type-patterns)
If you would like to extend valid HTML attributes for a given HTML element, you may use the provided `HTMLAttributes` type—it accepts an element name and returns the valid HTML attributes for that element name.
```ts
import { HTMLAttributes } from 'astro/types';
interface Props extends HTMLAttributes<'a'> {
myProp?: string;
};
```
https://github.com/withastro/docs/pull/1857
=> Add `astro/types` for common prop patterns

packages/astro/src/core/preview/index.ts
- Clarify the error message that is shown when your adapter doesn't support `astro preview`
- Closes #5181
Just an error message
cc @withastro/maintainers-docs for feedback! 
I'll also make a PR to update our description of `astro preview` in the docs, which hasn't been updated since the Node adapter started supporting `astro preview`.
=> Error message: clarify "adapter does not have previewEntrypoint"

packages/astro/src/@types/astro.ts
- Docs-only change, link mentions of `extendDefaultPlugins` to relevant section.
- This change was inadvertently made (by me) and merged [in the docs repo](https://github.com/withastro/docs/pull/1777/files#diff-18c1e75709f34e49949440b223bdd17d76b3c870813a66f5d29e10875b50bd73) (in a page that is sourced from here via GitHub Action), just now getting around to open a PR here.
n/a
n/a
=> docs: `extendDefaultPlugins` cross-linking (minor)

.changeset/witty-melons-heal.md, packages/astro/package.json, packages/astro/src/core/create-vite.ts, pnpm-lock.yaml
Use https://github.com/svitejs/vitefu to handle third-party Astro libraries SSR config. This should make most work out of the box.
Existing tests should pass. Hope no Windows issue.
N/A
=> Improve Astro libraries config handling

packages/integrations/mdx/README.md
- Fixes a broken link in the MDX readme
=> [docs] Fix broken fragment link

packages/integrations/cloudflare/README.md
- Updates a code block in the Cloudflare README to include a `js` language tag (nice for syntax highlighting but also fixes a build issue in our docs integration pages: https://github.com/withastro/docs/pull/1926)
Docs only.
Docs only! /cc @withastro/maintainers-docs
=> Add missing language to code block

.changeset/new-pumas-begin.md, packages/integrations/cloudflare/package.json, packages/integrations/cloudflare/runtime.d.ts
- Fixes https://github.com/withastro/astro/issues/5222
Tested with a project
N/A
=> Export Cloudflare runtime types

.changeset/mighty-chairs-reply.md, packages/astro/src/vite-plugin-utils/index.ts, packages/astro/test/astro-global.test.js, packages/astro/test/fixtures/astro-global/src/pages/omit-markdown-extensions.astro, packages/astro/test/fixtures/astro-global/src/pages/post/post-4.markdown, packages/astro/test/fixtures/astro-global/src/pages/post/post-5.mdown, packages/astro/test/fixtures/astro-global/src/pages/post/post-6.mkdn, packages/astro/test/fixtures/astro-global/src/pages/post/post-7.mkd
Closes #5228
- After get the result of a glob import of all the markdown files using `Astro.glob` we check if any of the markdown modules `url` metadata ends with one of the markdown extensions.
- The result of that operation is passed to a data attribute that should be `false` if none of urls ends with a markdown.
Nothing changes, it's a bug fix
=> fix not omitted extension in `url` metadata for newly added markdown files in development

.changeset/empty-feet-brush.md, packages/create-astro/README.md, packages/create-astro/package.json, packages/create-astro/src/index.ts, pnpm-lock.yaml
- Adds a `--fancy` flag for Windows users that want full Unicode support
- Also gives Houston a top-hat
Updated the README. Houston is mostly undocumented right now!
=> feat(create-astro): add --fancy flag

.changeset/neat-cooks-fail.md, packages/integrations/vercel/src/static/adapter.ts
- Closes https://github.com/withastro/astro/issues/5172
Tested in example project
N/A, bug fix
=> Throw error when trying to use the vercel static adapter in server mode

.changeset/chilly-mice-agree.md, packages/create-astro/src/index.ts
- There were two cases where `create-astro` would silently `process.exit(1)`.
- I think this might be making https://github.com/withastro/astro/issues/5227 worse than it seems.
- This PR makes these exits log something so it's easier to debug.
Manually confirmed
N/A
=> fix(create-astro): improve error messages when create-astro fails

packages/integrations/image/README.md
Some suggested updates and clarifications based on Image Interrogation with @tony-sull 
- more thorough treatment of when Squoosh/sharp do/don't work
- updating some properties for remote image guidance, where defaults don't hold
- includes mention of `alt` being required
- more clearly describes what happens re: building/optimizing to images in public folder
No tests
only docs
=> [docs] update image integration README

.changeset/config.json
- Ignores `astro-scripts` in changesets, as it's not a real package.
- Noticed in https://github.com/withastro/astro/pull/5239 that it's currently scheduled to be released. Hoping this change fixes that.
N/A
N/A
=> Prevent astro-scripts from being released

.changeset/config.json
This reverts commit 4f9391b33f9ec276536039daad65b2c9a2db53ca.
- Hoped that this would prevent `astro-scripts` from showing up to be released but it actually breaks packages that depend on it.
N/A
N/A
=> Revert "Prevent astro-scripts from being released (#5257)"

.changeset/cool-ducks-mix.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/endpoint/index.ts, packages/astro/src/vite-plugin-astro-server/index.ts, packages/astro/test/fixtures/with-endpoint-routes/src/pages/invalid-redirect.json.ts
Fix #4930
- Allow returning response with 200 status code from static endpoints.
- Throw on 300 status code for static endpoints like in dev mode.
- Also throw on 300 status code for page endpoints on build, previously would silently skip.
These changes should make build similar to dev.
I'm not sure how to test errors that would cause build to fail, but I did test with #4930 to make sure it works.
Currently the docs doesn't document that they can return a response for static endpoints. I'll document this separately but I don't think it blocks this PR.
https://github.com/withastro/docs/pull/1961
=> Allow 200 response for endpoints in build

.github/workflows/ci.yml
- `pnpm run format --list`
- ↳ `pnpm run format:code --list`
- ↳ `prettier -w . --cache --plugin-search-dir=. --list`
- `[warn] Ignored unknown option --list.` <-- spotted in CI output
- [--list-different](https://prettier.io/docs/en/cli.html#--list-different) would work
- [--check](https://prettier.io/docs/en/cli.html#--check) outputs "a human-friendly message and a list of unformatted files, if any."
- In this case, since we're not trying to do anything in particular with the output, might as well go for "human-friendly"
- Originally added in https://github.com/withastro/astro/pull/2696
n/a
=> ci: fix `prettier` arg

.changeset/lemon-spies-approve.md, packages/integrations/prefetch/src/client.ts, packages/integrations/prefetch/src/index.ts
I took a general look at the prefetch package and found that prefetching doesn't make sense in some cases.
For example, when the browser is offline.
Also, 3G is a relatively slow connection over which, in my opinion, no prefetching should be done.
* Only prefetch when browser is online
* Only prefetch when browser is not 2G/3G
* Minor style changes / partly happen automatically by the linter
Tests passing
No docs required
=> Improve prefetch conditions

.changeset/long-turtles-run.md, packages/integrations/tailwind/src/index.ts
- If the tailwind config contains an error it should not crash the dev server on restart.
- Note that it *does* crash on initial start which is wanted.
- Closes https://github.com/withastro/astro/issues/5142
Tested in demo project.
N/A
=> Prevent tailwind config errors from crashing dev server

.changeset/lucky-bees-impress.md, packages/integrations/prefetch/package.json
Noticed the `@astrojs/prefetch` integration isn't showing up in our [Integrations catalog](https://astro.build/integrations)
This updates the package keywords so it will show up in the integration on the "Official" and "performance + seo" tabs
/cc @withastro/maintainers-docs in case the `package.json` update impacts any scripts that may be generating docs code
=> Updates @astrojs/prefetch package keywords

examples/blog/src/components/HeaderLink.astro
Closes #5248 
In the blog example
- calculate `isActive` correctly
- take into consideration both cases: trailing slash and no trailing slash
This was tested in a dev server as well as a production environment on vercel.
It could be a bit confusing to people why we're calculating the active path like this. I think a comment above explaining it should be enough. Do need some help coming up with a brief way to explain this.
=> fix: consider trailing slashes when calculating current path in blog example

.changeset/clever-files-wash.md, packages/astro/src/core/util.ts, packages/astro/src/vite-plugin-astro-postprocess/index.ts, packages/astro/src/vite-plugin-jsx/index.ts, packages/astro/src/vite-plugin-markdown-legacy/index.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/fixtures/impostor-mdx-file/astro.config.mjs, packages/astro/test/fixtures/impostor-mdx-file/package.json, packages/astro/test/fixtures/impostor-mdx-file/src/components/Foo.mdx.jsx, packages/astro/test/fixtures/impostor-mdx-file/src/pages/index.astro, packages/astro/test/impostor-mdx-file.js, pnpm-lock.yaml
I must mention, I'm _very_ excited to contribute in some way to this awesome project.
Now, the matter at hand:
This fixes a bug caused by wrongly treating files as markdown. If the project's path contains '.md' (or any markdown extension) serving any page containing javascript results in the server crashing due to the heap running out of memory.
I noticed this behaviour when developing my personal website, 'vladinski.md' :)
Ran entire test suite.
Writing a test seemed overkill, considering such a peculiar type of bug.
If a test is required, please tell me so and I'll find a way to implement it.
No docs added since this is a fix that doesn't modify a user's usage.
=> Fix memleak caused by directory names containing '.md' or '.mdx'

.changeset/curvy-countries-kiss.md, packages/astro-prism/package.json, packages/markdown/component/package.json
This fixes the links for `@astrojs/prism` and `@astrojs/markdown-component` on [https://astro.build/integrations](https://astro.build/integrations/) that were previously pointing back to the homepage (astro.build).
The first PR was https://github.com/withastro/astro.build/pull/386 on the actual website but I was told that the links are generated from `package.json` for each integration/package. That is what is edited here, though I haven't found where the link for `agnosticui-astro` is coming from.
No tests, it is a simple change related to astro.build website.
No docs changes are needed as it doesn't affect the user’s behavior.
=> fix homepage url for integrations

.changeset/brown-clocks-press.md, packages/astro/src/cli/index.ts, packages/astro/src/core/config/config.ts, packages/astro/src/core/dev/container.ts, packages/astro/src/core/dev/dev.ts, packages/astro/src/core/dev/index.ts, packages/astro/src/core/dev/restart.ts, packages/astro/test/units/dev/restart.test.js, packages/astro/test/units/test-utils.js
- This is a bit of a refactor of how dev restarts take place. It moves the code out of the CLI and into `core/dev`. There it watches for changes to the astro config and restarts the vite server, etc. when that occurs.
- Closes https://github.com/withastro/astro/issues/5159
- Tested the new functionality via unit tests. This is a slow test so we should be careful about adding too many.
N/A
=> Surface configuration errors to the client

.changeset/dull-days-grin.md, packages/astro/types.d.ts
- This adds the missing `class:list` to the `HTMLAttributes` type as explained in #5279
Tested manually within `examples/basic/src/components/Card.astro` by extending the `Props` with `HTMLAttributes<"div">` and destructuring `'class:list': classList` from `Astro.props as Props`.
The docs don't explicitly mention any props of HTMLAttributes.
=> fix(astro): add `class:list` to `HTMLAttributes`

.changeset/heavy-bananas-deny.md, packages/astro/src/core/create-vite.ts, packages/astro/src/vite-plugin-astro/hmr.ts, packages/astro/src/vite-plugin-load-fallback/index.ts, packages/astro/test/units/dev/dev.test.js, packages/astro/test/units/test-utils.js
- The Astro vite plugin compares previous compilation results to determine if an HMR update has resulted in anything more than a style change.
- When doing this, only compare if the module is already in the cache.
- Fixes https://github.com/withastro/astro/issues/4651
- Update the mock file system fallback plugin to account for HMR. This plugin only runs in tests.
N/A, bug fix
=> Prevent overcaching of astro components for HMR

.changeset/friendly-beds-explode.md, packages/astro/src/cli/index.ts
fixes https://github.com/withastro/astro/issues/5255
Changes slow astro cli imports of add, build, preview, devServer and telemetryHandler to dynamic. 
These changes make the cli ~50% faster.
Tested with ```pnpm run test:match "cli"```
No docs need to be updated, only internal behaviour has been changed.
=> Adds astro cli dynamic imports

.changeset/blue-parrots-jam.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/app/index.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/core/preview/index.ts, packages/astro/test/fixtures/ssr-request/src/pages/request.astro, packages/astro/test/ssr-request.test.js, packages/astro/test/test-adapter.js, packages/integrations/cloudflare/package.json, packages/integrations/cloudflare/src/server.advanced.ts, packages/integrations/cloudflare/src/server.directory.ts, packages/integrations/deno/package.json, packages/integrations/deno/src/server.ts, packages/integrations/node/package.json, packages/integrations/node/src/http-server.ts, packages/integrations/node/src/preview.ts, packages/integrations/node/src/standalone.ts
- `src/app` now trims the base when looking up routes, so it will match routes when the URL includes the base.
- `src/app` has a new `removeBase` method which trims the base from a pathname. This is useful for adapters that need to look up assets from the filesystem, such as the Node and Deno adapters.
- For the 3 adapters that use this functionality they all have a `major` bump as they now depend on it via the `peerDependency`.
- Fixes https://github.com/withastro/astro/issues/5288
Test added in our test adapter which mimics the scenario.
N/A, bug fix
=> Handle `base` in adapters

packages/create-astro/src/messages.ts
- Corrects a word that could show up when running `npm create astro`: `unqiue` -> `unique`
N/A
N/A
=> Fix typo in create-astro

.changeset/selfish-mangos-drum.md, packages/astro/src/core/dev/index.ts, packages/astro/src/core/dev/restart.ts, packages/astro/test/units/dev/restart.test.js
- We close the Vite server on config changes in order to restart it, but were determining if it was previously running *after* closing it, giving a false negative.
- Fix is to move the check to happen before we call close.
- Fixes https://github.com/withastro/astro/issues/5313
N/A, bug fix
=> When creating a new dev container, restart it if previously started

packages/integrations/image/test/image-ssr-build.test.js, packages/integrations/image/test/picture-ssr-build.test.js
Fix failing test in `main` currently caused by #5290.
There's a image test not handled for the new base handling.
Should pass
N/A
=> Fix image test fail

.changeset/chilly-ladybugs-leave.md, packages/astro/src/core/render/result.ts, packages/astro/src/runtime/server/render/common.ts, packages/astro/src/runtime/server/render/slot.ts, packages/astro/test/astro-slots-nested.test.js, packages/astro/test/fixtures/astro-slots-nested/src/components/SlotRender.astro, packages/astro/test/fixtures/astro-slots-nested/src/pages/component-slot.astro
- Use `stringifyChunk` to ensure that rendering instructions are included in the output string.
- Fixes https://github.com/withastro/astro/issues/5032
- New test case added to existing slot rendering tests.
N/A, bug fix
=> Ensure astro-island scripts render when using Astro.slots.render

.changeset/spotty-planes-fix.md, package.json, packages/astro/package.json, pnpm-lock.yaml
Updated the language-server version being bundled to not use an extremely old one, which in turn updates the prettier plugin to not use an old version of the compiler (we'll reach 1.0 on those packages one day 🤞)
Fix https://github.com/withastro/astro/issues/5289
This is not a complete fix for that issue (issue will rehappen on next minor of the compiler), but since the language-server itself will soon depend on the compiler for the TSX output, fixing it now would mean doing the work twice (in a possibly conflicting way) - I'd rather figure out a complete solution when that happen. In the meantimes, it untangles things nicely
This PR also updates our version of the Prettier plugin we use, so this PR will probably automatically cause a format commit.
N/A
N/A
=> Update language-server and prettier plugin to latest versions

.changeset/good-ghosts-attack.md, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/vite-plugin-load-fallback/index.ts, packages/astro/test/units/dev/dev.test.js, packages/astro/test/units/test-utils.js
- Use `getParts` to parse a segment (part of a file path) in injected routes the same as in real routes.
- This fixes the ability to do `test-[slug].astro` in injected routes.
- Fixes https://github.com/withastro/astro/issues/5247
- Test added
N/A, bug fix
=> Allow dynamic segments in injected routes

.changeset/plenty-eyes-develop.md, packages/astro/src/vite-plugin-astro-server/base.ts, packages/astro/test/fixtures/alias/public/test.txt, packages/astro/test/units/dev/dev.test.js
- If you are referencing an item in `public/` and using base config, you must include the base in your URL.
- Previously you had to *not* include it. This was an obvious bug.
- Fixes https://github.com/withastro/astro/issues/5107
- Fixes https://github.com/withastro/astro/issues/4988
Tests added for both base and non-base scenarios.
N/A, bug fix
=> 404 when not using subpath for items in public in dev

.changeset/fifty-olives-end.md, packages/integrations/image/src/lib/get-picture.ts, packages/integrations/image/test/picture-ssg.test.js
Fix #5185
`picture` has a fallback `img` tag (for legacy browsers). It can reuse the images generated for `source` tags to prevent duplicate images. This is safe as the format/width permutations overlaps for images and pictures.
Added an SSG picture test.
N/A. Internal optimization.
=> Share picture fallback image with source

.changeset/heavy-kangaroos-sin.md, packages/integrations/mdx/package.json, packages/integrations/mdx/src/plugins.ts, packages/integrations/mdx/src/rehype-meta-string.ts, packages/integrations/mdx/test/fixtures/mdx-syntax-hightlighting/src/pages/index.mdx, packages/integrations/mdx/test/mdx-syntax-highlighting.test.js, pnpm-lock.yaml
Fix #5163 
Support `rehype-pretty-code` by moving `data.meta` to `properties.metastring` as `rehype-pretty-code` accepts that: https://github.com/atomiks/rehype-pretty-code/blob/17e2856c5abe91eefc0830a8b5f8cab9d13aedb5/src/index.js#L151
Note this does not create a new `metastring` HTML attribute through testing.
Added a test for `rehype-pretty-code`
N/A. The plugin should work ootb now.
=> Preserve code element node meta for rehype syntax highlighters

packages/integrations/mdx/package.json, pnpm-lock.yaml
Typo from https://github.com/withastro/astro/pull/5335#pullrequestreview-1174118761
Thanks @delucis for catching this!
N/A
N/A
=> Move rehype-pretty-code as devDep

.changeset/poor-eagles-melt.md, packages/astro/package.json, packages/astro/test/astro-directives.test.js, pnpm-lock.yaml
- Compiler has a `define:vars` fix, but test was out of date with the new implementation
- This upgrades the compiler and updates the test
Existing test updated
N/A
=> Upgrade compiler

packages/astro/src/vite-plugin-astro-server/base.ts, packages/astro/test/units/dev/dev.test.js
- Talked this over in `#maintainers` and felt like breaking non-base usage in dev might be too far.
- Changed it here to a warning + 301. We can make this a 404 in a future minor.
Test updated
N/A
=> Change 404 to 301 for omitting base for items in public

examples/basics/README.md, examples/blog/README.md, examples/component/README.md, examples/deno/README.md, examples/docs/README.md, examples/framework-alpine/README.md, examples/framework-lit/README.md, examples/framework-multiple/README.md, examples/framework-preact/README.md, examples/framework-react/README.md, examples/framework-solid/README.md, examples/framework-svelte/README.md, examples/framework-vue/README.md, examples/hackernews/README.md, examples/integration/README.md, examples/minimal/README.md, examples/non-html-pages/README.md, examples/portfolio/README.md, examples/with-markdown-plugins/README.md, examples/with-markdown-shiki/README.md, examples/with-mdx/README.md, examples/with-nanostores/README.md, examples/with-tailwindcss/README.md, examples/with-vite-plugin-pwa/README.md, examples/with-vitest/README.md
Just like in https://github.com/withastro/docs/pull/1982. I have been using codesandbox a lot for my open-source contributions, and I think it's really cool. Astro doc contributors can work seamlessly, and I wanted to add it here as an option.
I noticed that in astro.new you have the option to open in codesandbox, but in the repos that are cloned, only the stackBlitz option exists. 
=> Add “Open with CodeSandbox” buttons to example project READMEs

examples/minimal/astro.config.mjs
#5298 introduced a change in the config file of the minimal example, presumably for testing purposes, but that makes `index.astro` 404 on StackBlitz. (Only detected just now when we fixed auto-push to `latest` which is what astro.new pulls from.)
This PR reverts the change from #5298.
Opening this branch on StackBlitz works as expected: https://stackblitz.com/github/withastro/astro/tree/chris/fix-minimal-example/examples/minimal
Examples fix only, no docs changes needed.
=> Fix `astro.config.mjs` in minimal example

.changeset/shiny-baboons-trade.md, packages/astro/src/core/build/css-asset-name.ts, packages/astro/src/core/build/vite-plugin-css.ts, packages/astro/test/astro-css-bundling.test.js
- This updates the naming algorithm to account for the fact that some people turn off hashing.
- What it does is see every pages that uses a CSS file and then use all of those pages as a key.
- The key is kept in a map, and we try to create a short name from the corresponding page name, for ex `src/pages/docs/index.astro becomes `docs-index`. If we encounter more than 1 "collection of pages" that both have this same short name, we increment a number, so it becomes `docs-index-1`. This ensures we never have clashing names.
- Kept the existing short naming algorithm in place for those who don't disable hashing as it creates slightly prettier names.
- Fixes https://github.com/withastro/astro/issues/5134
- Updated our CSS bundling tests to test for this, also to ensure each algorithm works as …
=> Updated CSS naming algorithm

.changeset/thin-trains-complain.md, packages/astro/src/@types/astro.ts
- `MarkdownAstroData["frontmatter"]` was too vague (`object`), now using `MarkdownInstance`
- `MarkdownParserResponse` uses `MarkdownInstance` (minor)
- I was going to go with something more like:
```ts
export type MarkdownAstroData<T extends Record<string, any>> = {
frontmatter: MarkdownInstance<T>['frontmatter'];
};
```
... but I didn't want to make those generic (breaking change).
n/a, type changes only
n/a, type changes only
=> Consistent MD frontmatter typing

.changeset/red-worms-occur.md, packages/integrations/image/src/index.ts, packages/integrations/image/src/loaders/squoosh.ts, packages/integrations/image/src/vendor/squoosh/image-pool.ts, packages/integrations/image/src/vite-plugin-astro-image.ts
This reverts commit d701ae074a4a5c7a5891e31ca50d7c51f56b353c.
- Reported that this breaks local builds. Reverting for now to unbreak people's apps until the underlying issue can be found.
=> Revert "Allow image-pool to be used as its own Worker (#5317)"

.changeset/metal-suns-tell.md, packages/astro/package.json, packages/astro/src/core/create-vite.ts, packages/integrations/solid/package.json, packages/integrations/solid/src/dependencies.ts, packages/integrations/solid/src/index.ts, pnpm-lock.yaml
- Upgrade `vitefu` from 0.1.0 to [0.2.0](https://github.com/svitejs/vitefu/releases/tag/v0.2.0) - It's a breaking bump but for an API we're not using so we're safe.
- Pass Vite user config to `vitefu` `crawlFrameworkPackages` so that the generated Vite config respects the user config. This helps the user to make a workaround if there's any issues with it.
N/A. In most case this should be transparent to the users.
=> Respect Vite user config for third-party packages

packages/integrations/node/README.md
=> Fix a typo in the @astrojs/node documentation

.changeset/chatty-kiwis-fail.md, packages/astro/src/vite-plugin-astro-server/request.ts, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/dev-routing.test.js, packages/astro/test/fixtures/without-site-config/src/pages/html-ext/[slug].astro, packages/astro/test/fixtures/without-site-config/src/pages/html-ext/[slug].html.astro
Fix #5068
Differentiate between `[id].astro` and `[id].html.astro` files when routing, similar to other extensions (`.html` was specially handled before).
Added new tests
N/A. Bug fix.
=> Fix .html.astro file routing in dev

.changeset/kind-icons-destroy.md, packages/astro/src/core/config/schema.ts, packages/astro/src/core/routing/manifest/create.ts, packages/astro/src/vite-plugin-astro-server/base.ts, packages/astro/src/vite-plugin-astro-server/plugin.ts, packages/astro/src/vite-plugin-astro-server/request.ts, packages/astro/test/astro-global.test.js, packages/astro/test/units/dev/base.test.js, packages/astro/test/units/routing/manifest.test.js, packages/astro/test/units/vite-plugin-astro-server/request.test.js
- When using `trailingSlash: 'never'` and a base such as `/docs` it should allow requests to `/docs` but not to `/docs/`.
- This was a bit tricky to fix given how we remove the base in the dev server and then later put it back. That's why this touches a few different files.
- It might be worth in the future creating a class / module or something that sort of encapsulates all of the base, trailingSlash, etc. behavior. And then have everything use that.
- Unit tests added for the dev server to ensure this works as expected.
- Unit test added for routing.
N/A, bug fix
=> Properly support trailingSlash: never with a base

.github/workflows/ci.yml
- Adds reasonable timeouts to all jobs in `ci.yml`
- Checked our logs to find roughly average times.
- Prevents infinite loops from clogging CI forever
This is the test
N/A
=> chore(ci): add timeout to all ci jobs

.changeset/thirty-cheetahs-repeat.md, packages/astro/src/core/app/index.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/vite-plugin-hoisted-scripts.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/core/config/schema.ts, packages/astro/src/core/render/ssr-element.ts, packages/astro/test/asset-url-base.test.js, packages/astro/test/astro-scripts.test.js, packages/astro/test/fixtures/asset-url-base/package.json, packages/astro/test/fixtures/asset-url-base/src/pages/index.astro, packages/astro/test/fixtures/ssr-request/src/pages/request.astro, packages/astro/test/ssr-request.test.js, pnpm-lock.yaml
- Closes https://github.com/withastro/astro/issues/5351
- Using `site` is leftover from before we had `base`
- Added tests
N/A, bug fix
=> Use base rather than site to create subpath for links/scripts

.changeset/angry-dragons-drive.md, packages/astro/src/core/render/route-cache.ts, packages/astro/test/astro-get-static-paths.test.js, packages/astro/test/fixtures/astro-get-static-paths/src/pages/nested-arrays/[slug].astro
After my recent PR that made the validation of `getStaticPaths` a bit more strict, the flatten call wasn't running at the right time, this caused the validation to fail since they expect the return value to be objects
Added a test for nested arrays
N/A. Nested array support is already documented
=> Fix `getStaticPaths` regressions with nested arrays

packages/integrations/image/README.md
- Fixed typo in Image integration docs en-only
- you -> your
- One letter change - no testing required.
- Edit is to the docs.
=> Fix typo in image integration documentatation

examples/framework-solid/src/components/Counter.tsx
In the `framework-solid` example, I updated the only Solid component not to destructure its props. Unlike in React, Solid uses property access for tracking reactivity, so those accesses need to be in the JSX in this example. I caught the problem with `eslint-plugin-solid`.
From what I can tell I don't need a changeset for this change, but please let me know if I do!
`eslint-plugin-solid` doesn't show a reactivity warning anymore.
As a patch change this shouldn't affect a user's behavior.
=> Preserve reactivity in Solid example component

.changeset/tidy-shoes-yawn.md, packages/integrations/image/src/index.ts, packages/integrations/image/src/loaders/squoosh.ts, packages/integrations/image/src/vendor/squoosh/image-pool.ts, packages/integrations/image/src/vite-plugin-astro-image.ts, packages/integrations/vercel/package.json, packages/integrations/vercel/src/serverless/adapter.ts, pnpm-lock.yaml
…" (#5360)"
This reverts commit 20e60c6e0857f7b6938494df6027e8c1ad74cdc1.
- Allows the image component to be used within Vercel.
- Bundles the squoosh worker along with the other SSR code.
- Moves the wasm files into the chunks folder, like in SSG.
- Test app https://astro-test-image-ssr-matthew6.vercel.app/
N/A
=> Fix usage of the Image component with the Vercel adapter

.changeset/violet-apricots-smash.md, packages/create-astro/src/index.ts
- fix error when don't have template input
When input `npm create astro@latest -- --template`, `create-astro` will throw error:
=> fix(create-astro): fix error when don't have template input

.changeset/swift-bees-hope.md, packages/astro/package.json, packages/astro/src/cli/index.ts, packages/astro/src/core/add/index.ts, packages/astro/src/core/config/config.ts, packages/astro/src/core/config/vite-load.ts, packages/astro/test/fixtures/tailwindcss-ts/astro.config.ts, packages/astro/test/fixtures/tailwindcss-ts/package.json, packages/astro/test/fixtures/tailwindcss-ts/tailwind.config.cjs, packages/astro/test/units/dev/restart.test.js, packages/integrations/image/src/index.ts, pnpm-lock.yaml
- Fixes https://github.com/withastro/astro/issues/5373
- When using a `astro.config.ts` proload was not able to load `@astrojs/tailwind` on a reload correctly (not sure why).
- Switches to using Vite for all non (m)js configs. 
- Restart test added
N/A, bug fix
=> Use Vite to load non JS astro configs

.changeset/olive-walls-hunt.md, packages/astro/package.json, packages/astro/src/core/config/settings.ts, packages/astro/test/units/dev/restart.test.js, packages/integrations/solid/package.json, pnpm-lock.yaml
- Adds the package.json to the list of watch files. We restart the dev container any time one of these files changes.
- This is needed to get `sass` to work when installed after the dev server has already been started.
- This now works in Vite 3.2.4
- Closes https://github.com/withastro/astro/issues/5145
- Unit test added which confirms the dev server is restarted when the package.json changes.
N/A, bug fix
=> Restart dev server on package.json changes

packages/integrations/image/README.md
fix typo
no test needed, just fixed a typo
=> [docs] fix typo in image integration README

.changeset/wild-falcons-sparkle.md, packages/astro/src/runtime/server/render/astro.ts, packages/astro/test/units/dev/hydration.test.js
- When an error occurs in a template only throw the first error that occurs. This is because latter errors can't be caught by the dev server. The user will see the first error in the error overlap (see below)
- Fixes https://github.com/withastro/astro/issues/5415
- unit test added
N/A, bug fix
=> Prevent dev from crashing when there are errors in template

.changeset/blue-rabbits-hear.md, packages/integrations/node/package.json, packages/integrations/node/src/middleware.ts, packages/integrations/node/src/response-iterator.ts, pnpm-lock.yaml
Sometimes Astro sends a [ReadableStream](https://github.com/withastro/astro/blob/main/packages/astro/src/runtime/server/render/page.ts#L105) or a Buffer as a response body and it raise an error `TypeError: body is not async iterable.`
I added a function to get a response iterator from different response types (sourced from apollo-client).
With this, node adapter can handle all the Astro response types.
Not implemented. I tested this in my project.
N/A
=> Add response iterator to node adapter

.changeset/sixty-chicken-obey.md, packages/astro/src/core/messages.ts
Fix #5303
Properly check host address ipv4 in Node.js 18
https://github.com/withastro/astro/pull/3599 and https://github.com/withastro/astro/pull/4032 were incorrectly supporting the ipv4 check in node 18. It's a 18.0.0 breaking change, not from a specific minor version.
The code is copied from [Vite](https://github.com/vitejs/vite/blob/d9779c7fae3f06e2d15b15f21f9a74f47679dce8/packages/vite/src/node/utils.ts#L884-L887)
N/A. I manually tested with node 18.0.0 and it works with this PR.
N/A. bug fix.
=> Fix preview --host in Node.js 18

.changeset/purple-tips-flash.md, packages/astro/src/core/config/vite-load.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/vite-plugin-load-fallback/index.ts, packages/astro/test/units/config/format.test.js
- Previously if importing a `astro.config.mjs` via dynamic import failed, we just failed completely.
- Didn't realize that people were relying on being able to import non-JS in these types of configs.
- Change is to fallback to the Vite flow.
- Closes https://github.com/withastro/astro/issues/5428
- Test added
- Had to clean up the mock fs fallback plugin a bit.
N/A, bug fix
=> Fix regression with loading .ts in .mjs config

.changeset/sixty-apricots-drum.md, packages/astro/src/vite-plugin-jsx/tag.ts, packages/astro/test/fixtures/react-jsx-export/src/components/defaultExport/HocDefaultExport.jsx, packages/astro/test/fixtures/react-jsx-export/src/pages/index.astro, packages/astro/test/react-jsx-export.test.js
Fix #5305 
Tag JSX (with `__astro_tag_component__`) for `export default withHoc(Something)`, which is a call expression.
It transforms into
```
const _hoc_function = withHoc(Something)
export default _hoc_function
__astro_tag_component__(_hoc_function)
```
to tag it. (Shares the same logic as arrow functions).
Added default export test.
N/A. bug fix
=> Fix JSX tagging for anonymous higher-order components default export

.changeset/violet-buckets-repeat.md, packages/integrations/node/README.md, packages/integrations/node/src/standalone.ts
Provides a way to handle runtime HOST environment variable on Node Standalone builds
I did not see any test for this section, should I write some ?
Hi! I think this could be documented next to the host definition mechanism, I can participate if needed!
=> feat: provide HOST env variable at runtime

.changeset/clever-queens-beam.md, packages/astro/astro-jsx.d.ts
Add missing `fetchpriority` attribute to `ImgHTMLAttributes`. See https://wicg.github.io/priority-hints/#img.
N/A
N/A
=> Add missing `fetchpriority` attribute to `ImgHTMLAttributes`

.changeset/popular-melons-pretend.md, packages/integrations/partytown/src/index.ts
Closes issue https://github.com/withastro/astro/issues/5424
When serving up the partytown-sandbox-sw.js it is already scoped to the base path. The code that matches the request url is at the following.
https://github.com/withastro/astro/blob/main/packages/integrations/partytown/src/sirv.ts#L209
I was able to reproduce the problem locally and then tinkered around a bit until I figured out the problem. Might need some more tesing since I am still very new.
Shouldn't have any effect on the docs. It is just a fix with the expected behavior.
=> fix: partytown base path

.changeset/dull-camels-accept.md, packages/astro/src/core/path.ts, packages/astro/src/vite-plugin-jsx/index.ts, packages/astro/test/fixtures/solid-component/deps/solid-jsx-component/Counter.jsx, packages/astro/test/fixtures/solid-component/deps/solid-jsx-component/index.js, packages/astro/test/fixtures/solid-component/deps/solid-jsx-component/package.json, packages/astro/test/fixtures/solid-component/package.json, packages/astro/test/fixtures/solid-component/src/pages/index.astro, pnpm-lock.yaml
Fix #5058
JSX files in node_modules are usually not appended with `?v=blabla` in Vite, but there are cases [where it does](https://github.com/vitejs/vite/blob/0d734732dac890cf0c6c784510059f66005a64b0/packages/vite/src/node/plugins/importAnalysis.ts#L354-L357) (not sure if it's a bug).
This PR updates `vite-plugin-jsx` to strip query strings before checking the extension.
Added a test to simulate the edge case in Vite. The `index.js` file will have a version query, and that its transferred to `Counter.jsx` during import analysis.
N/A. bug fix
=> Correctly transform third-party JSX files

.changeset/honest-chairs-confess.md, packages/integrations/mdx/README.md
- Updates a link that changed on the docs site
Clicked through from the Markdown file to ensure it went where I expected.
Small docs fix only
=> Fix docs link in MDX integration README

.changeset/thirty-bananas-smell.md, packages/integrations/tailwind/src/index.ts
Closes https://github.com/withastro/astro/issues/5439
Tested in local project.
N/A
=> Remove temp tailwind config file in finally

.changeset/nice-jokes-smile.md, packages/integrations/mdx/README.md, packages/integrations/mdx/package.json, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/fixtures/mdx-astro-markdown-remarkRehype/src/pages/index.mdx, packages/integrations/mdx/test/mdx-astro-markdown-remarkRehype.test.js, pnpm-lock.yaml
- Uses remark-rehype options from astro.config.mjs
- Based on https://github.com/withastro/astro/pull/4138
See https://github.com/withastro/astro/pull/4138 and `test/fixtures/mdx-astro-markdown-remarkRehype/src/pages/index.mdx`
=> [MDX] Support remark-rehype options from Astro Markdown config

.changeset/swift-papayas-kiss.md, packages/astro/src/core/preview/index.ts, packages/astro/test/fixtures/ssr-preview/package.json, packages/astro/test/fixtures/ssr-preview/preview.mjs, packages/astro/test/fixtures/ssr-preview/src/pages/index.astro, packages/astro/test/ssr-preview.test.js, packages/astro/test/test-adapter.js, pnpm-lock.yaml
When running `astro preview` on Windows, it didn't work with the following error.
> Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
This PR fixes this error.
I added a test. Also I tested with adapter-node manually.
Docs isn't needed as it's a bug fix.
=> Fix astro preview not working on Windows

.changeset/twelve-kings-rest.md, packages/astro/src/core/render/dev/css.ts, packages/astro/test/fixtures/0-css/src/pages/index.astro, packages/astro/test/fixtures/0-css/src/styles/_partial-1.scss, packages/astro/test/fixtures/0-css/src/styles/_partial-2.scss, packages/astro/test/fixtures/0-css/src/styles/partial-main.scss
Fix https://github.com/withastro/astro/issues/5441
Actually fixing https://github.com/withastro/astro/issues/5441 also relies on https://github.com/vitejs/vite/pull/11079 too, but we could close it as the work has been done for the issue.
SCSS partials may refer to mixins in other files, so it can't be loaded individually by itself. It's safe to skip as they are likely already inlined in other SCSS files.
Added SCSS partials to css test
n/a, bug fix
=> Prevent inlining SCSS partials in dev

.changeset/nervous-laws-knock.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/routing/params.ts
Fixes #5442.
/cc @tony-sull & @bholmesdev
[#3087 changed the type of `Params`](//github.com/withastro/astro/pull/3087) from `Record<string, string | undefined>` to `Record<string, string | number | undefined>` to formerly allow `getStaticPaths` to return numbers.
However, as the change was made to `Params` and not `GetStaticPathsResult` or `GetStaticPathsItem`, it also affects `Astro.params`.
This PR essentially moves the change made in #3087 from `Params` to `GetStaticPathsItem`, reverting the type of `Astro.params` while keeping the type of `getStaticPaths`.
**Note** that while looking into this, I [found this comment](https://github.com/withastro/astro/issues/4309#issuecomment-1239779706) by @bholmesdev:
> * if you pass a number to `params.year` in your `getStaticPaths`, it should …
=> Narrow the type of Params

.changeset/dirty-scissors-fail.md, packages/integrations/image/src/vendor/squoosh/impl.ts
=> fix bug: added a warning if the image was GIF

.changeset/ten-emus-raise.md, packages/astro/e2e/astro-component.test.js, packages/astro/e2e/fixtures/_deps/astro-linked-lib/Component.astro, packages/astro/e2e/fixtures/_deps/astro-linked-lib/package.json, packages/astro/e2e/fixtures/astro-component/package.json, packages/astro/e2e/fixtures/astro-component/src/pages/index.astro, packages/astro/src/vite-plugin-astro/index.ts, pnpm-lock.yaml
Fix https://github.com/withastro/astro/issues/5343
Remove `/@fs` when resolving third-party Astro component style virtual module. Ideally we can pass it through for Vite's resolver to resolve itself, but I found that still causes other HMR problems. So sticking with this simple fix for now.
We could revisit this again and fix as a whole, but this bug alone took quite a while to figure out ~~that I almost considerd retiring~~ so putting it aside for now.
Added new test in `astro-component`
N/A. bug fix
=> Fix linked Astro library style HMR

.changeset/tall-goats-knock.md, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-env/README.md, packages/astro/src/vite-plugin-html/README.md, packages/astro/src/vite-plugin-html/transform/index.ts, packages/astro/src/vite-plugin-load-fallback/README.md, packages/astro/src/vite-plugin-markdown-legacy/index.ts, packages/astro/src/vite-plugin-markdown/README.md, packages/astro/src/vite-plugin-scripts/README.md, packages/astro/src/vite-plugin-scripts/page-ssr.ts, packages/astro/src/vite-plugin-utils/index.ts
Making some incremental refactorings through separate PRs.
The commits can be reviewed individually to see the changes.
Added and updated the internal READMEs for new contributors.
=> Refactor internal plugins code

.changeset/wicked-dolphins-design.md, packages/astro/src/vite-plugin-jsx/import-source.ts, packages/astro/src/vite-plugin-jsx/index.ts
Optimize JSX import source detection when checking for imports. Also refactor import source detection.
Previously it would use esbuild to transform and use es-module-lexer to check for imports, which is accurate but expensive (even though fast)
This PR now uses a regex to loosely check for imports. The regex is borrowed from Vite's scanner. It's less accurate but cheaper. (should cover most cases)
N/A
=> Optimize JSX import source detection

.changeset/yellow-lizards-shout.md, packages/astro/src/runtime/server/render/astro.ts
Bit of a lazy fix. I was hoping to be able to provide more information in the warning, but much like what I faced in https://github.com/withastro/astro/pull/5316, we don't have access to much there. In the future, I'd like to investigate a larger endeavour there to see if we can drill down info for error / warnings reporting (or bubble up warnings and errors, maybe?)
For now this is still an improvement. It's not that big of an issue that the location isn't in the message as the warning will show up when you visit the page / build it so you'll know either way in which file it is. In the future we'll also add an editor warning for this, which should also help users avoid this situation!
Fix https://github.com/withastro/astro/issues/4090
N/A
=> Show warning about hydrating Astro components in build

.changeset/plenty-tigers-pretend.md, packages/integrations/vercel/package.json, packages/integrations/vercel/src/serverless/request-transform.ts, pnpm-lock.yaml
There were [some errors](https://discord.com/channels/830184174198718474/961342615805108326/1047846230870466581) with the current transformation of requests and responses in the Vercel integration. I've updated it according to what the SvelteKit have achieved
=> fix(vercel): Update request-transforms.ts

.changeset/lazy-walls-sneeze.md, .changeset/seven-seahorses-talk.md, packages/astro/src/core/compile/cache.ts, packages/astro/src/core/compile/compile.ts, packages/astro/src/core/compile/index.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/vite-plugin-astro/compile.ts, packages/astro/src/vite-plugin-astro/index.ts, packages/astro/src/vite-plugin-utils/index.ts
- Refactor `vite-plugin-astro` to split of core logic out of `index.ts` so they can be tested.
- Remove `/@fs` usage when compiling (uses `resolve.dedupe` to achieve this)
It's easier to review the changes by checking each commit individually.
All existing tests should pass.
N/A. refactors.
=> Refactor Astro plugin and compile flow

.changeset/sweet-chairs-buy.md, packages/astro/src/core/render/core.ts, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/test/fixtures/mdx-component/src/components/WithFragment.mdx, packages/integrations/mdx/test/fixtures/mdx-component/src/pages/glob.astro, packages/integrations/mdx/test/fixtures/mdx-component/src/pages/w-fragment.astro, packages/integrations/mdx/test/fixtures/mdx-slots/src/components/Slotted.astro, packages/integrations/mdx/test/fixtures/mdx-slots/src/components/Test.mdx, packages/integrations/mdx/test/fixtures/mdx-slots/src/pages/glob.astro, packages/integrations/mdx/test/fixtures/mdx-slots/src/pages/index.astro, packages/integrations/mdx/test/mdx-component.test.js, packages/integrations/mdx/test/mdx-slots.js
- Fixes #5519 
- Wraps MDX’s default `MDXContent` render function so we can pass in our definition of `Fragment` — otherwise `Fragment` is unsupported when rendering MDX using `<Content />`
- Reverts astro core workaround from #4136 which is no longer needed because this PR fixes the general case of fragments in MDX
Expanded the `mdx-component` fixture/test suite to include an example `WithFragment.mdx` file which we test renders as expected.
Bug fix only, should match existing docs expectations.
=> Support rendering `<Fragment>` in MDX `<Content />` component

.changeset/eight-deers-repair.md
- Mark the next image integration release as a patch instead of a minor
=> Mark image integration release as a patch

packages/astro/test/test-utils.js
Handle fetching URLs in Node 18. Node >= 17 sets the [DNS resolution](https://nodejs.org/api/dns.html#dnssetdefaultresultorderorder) to verbatim by default which changes how `localhost` resolves to `127.0.0.1` or `[::1]`.
Extra context: https://github.com/withastro/astro/pull/5266#discussion_r1013166899
All tests should pass. This should also make vite-ecosystem-ci pass.
N/A
=> Fix tests with node 18

.changeset/beige-forks-cough.md, package.json, packages/integrations/cloudflare/package.json, packages/integrations/deno/package.json, packages/integrations/netlify/package.json, pnpm-lock.yaml, scripts/package.json
While working on https://github.com/withastro/astro/pull/5533, I noticed esbuild v0.15 didn't have significant breaking changes. Even tsm upgraded it in a [minor bump](https://github.com/lukeed/tsm/releases).
The latest esbuild version also has perf improvements.
n/a
=> Update esbuild dependency

.github/workflows/benchmark.yml
In the `!bench` workflow, use bash as the shell
=> bench workflow - use bash as shell

.changeset/chilled-papayas-build.md, packages/astro/src/core/create-vite.ts
The Astro package and subpaths shouldn't be prebundled as they are node-only, Astro components, types, or internal files.
Fixes https://github.com/withastro/astro/issues/5517 but short-term only. The better approach which I can do soon is to have Vite's scanner recognize `---` as searches imports there. That way we can set the `optimizeDeps.entries` as `src/pages/**/*` and it should work properly.
The issue with #5517 is that they put config subfiles in `src` and that makes Vite prebundle the scanned dependencies (which are almost always not used)
Tested locally with the repro in #5517. Realistically someone shouldn't import `astro` in their codebase but it could happen indirectly like in the issue.
n/a bug fix
=> Exclude astro from Vite optimization

.changeset/chilly-pumpkins-fetch.md, packages/astro/src/@types/astro.ts
This only changes the types file, not the implementation. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#redirection_messages for the list of redirection status codes.
No docs; the restriction wasn't documented before.
=> Allow all redirection status codes in redirect()

.changeset/fast-carpets-float.md, packages/astro/src/core/app/index.ts, packages/astro/test/fixtures/ssr-params/package.json, packages/astro/test/fixtures/ssr-params/src/pages/[category].astro, packages/astro/test/ssr-params.test.js, pnpm-lock.yaml
- Internal rendering expects `pathname` to be trimmed of the base because routing is not aware of base.
- Fix is to provide the pathname without base to rendering.
- `url.pathname` is still the real pathname. The other `pathname` is just used for internal route/param matching and not provided to the user.
- Fixes https://github.com/withastro/astro/issues/5537
N/A, bug fix
=> Fix Astro.params not having values when using base in SSR

.changeset/hungry-snakes-live.md, packages/astro-rss/package.json, packages/astro-rss/src/index.ts, packages/astro-rss/test/rss.test.js, pnpm-lock.yaml
Generating XML using string concatenation is dangerous and can lead to underescaping.
Just to preemptively dismiss some excuses for this unsafety 😛:
- _“But most of the content was surrounded with with `<![CDATA[…]]>`, so it was fine!”_ Wrong. The content might contain `]]>` itself and break out of the `<![CDATA[` early.
- _“But URLs don’t need to be escaped, so it was fine!”_ Wrong. `&` commonly appears in URLs and needs to be escaped for XML or HTML serialization.
- _“But we were validating the output XML, so it was fine!”_ Wrong. A bug that’s caught at generation time is still a bug; also, some cases of underescaping could lead to incorrect output that isn’t invalid.
- _“But there’s no user-generated content for an attacker to control, so it was fine!”_ Wrong. Underescaping is still a …
=> astro-rss: Generate feed with proper XML escaping

packages/astro/src/@types/astro.ts
While the `site` property in the Astro config can be accessed in the app via `Astro.site`, the `base` property is only accessible via `import.meta.env.BASE_URL`. It wasn't documented, so this PRs fixes this.
No tests since it's just a docs change.
This updates the types that are used to generate the reference pages (https://docs.astro.build/en/reference/).
=> Documented how to access the base config in the app

.changeset/nice-pens-lie.md, packages/integrations/node/src/preview.ts
- We were accidentally logging `${fileURLToPath}` instead of `${fileURLToPath(serverEntrypoint)}`
=> Node: better serverEntrypoint error

.changeset/neat-hounds-push.md, packages/integrations/mdx/README.md
- Follows recent changes to Docs MD/MDX guide to maintain more feature/usage/examples in Docs vs this README
- Removes content that is now in "guide" format in Docs
- Leaves mostly config/reference type material with links to MDX (and our MDX) docs for features, usage and examples
Preview-in-docs (easier to read) available at https://deploy-preview-2060--astro-docs-2.netlify.app/en/integrations/mdx/
Removed content now exists here in guide form: https://docs.astro.build/en/guides/markdown-content/
No tests!
all docs! MDX integration README update only.
=> [docs] MDX README update

.changeset/few-days-refuse.md, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/test/fixtures/ssr-request/src/scripts/inject-script.js, packages/astro/test/ssr-request.test.js
- Fixes https://github.com/withastro/astro/issues/5566
N/A
=> Include base in 'page' stage injected scripts

packages/integrations/deno/README.md, packages/integrations/deno/src/server.ts
- Bumps the `deno_std` dependency to be up to date
- No new tests are required since we are just changing the dependency version
- I have also updated the dependency in the docs
=> Update deno integration dependencies

.changeset/ten-books-burn.md, packages/astro/package.json, pnpm-lock.yaml
- Updates magic-string to 0.27.0
Magic-string is used in vite-plugin-env, vite-plugin-html and vite-plugin-scripts. Tests for it pass locally.
Update, shouldn't change anything. 
Related to issue #5555 . Library used a version newer than astro so I had to explicitly install it, it was bad DX and took a little bit to figure out.
=> Updated magic-string to 0.27.0

packages/integrations/vue/README.md
- Changed the link to the new URL due to vitejs/vite has moved framework plugins out of core.
=> fix link 404 in Vue integration README

.changeset/ninety-socks-chew.md, packages/astro-rss/src/index.ts, packages/astro-rss/test/rss.test.js
This fixes #5582 by basically correcting a typo, but it also adds a test so RSS item `customData` is slightly harder to break in the future.
I added another variation of hardcoded RSS output that follows my use-case of appending a `<dc:creator>` node for the item. Adds a top-level namespace to support the node, uses `RSSFeedItem`’s `customData` property to append it, and makes sure the resulting output includes both.
Nope! Just fixes a regression. When merged, the feature will work as currently described.
=> Fix missing RSS item `customData`

.changeset/five-moose-push.md, packages/astro-rss/src/index.ts, packages/astro-rss/test/rss.test.js
Adds the `type="text/xsl"` attribute to xml-stylesheet processing instruction in rss. It was removed by mistake in #5550.
The type attribute will only be added when the stylesheet ends with `.xsl` to enable support for css-stylesheet as well.
Fix #5581
Updated the tests using `chai-xml` to verify both using a xsl stylesheet (include attribute) and a css stylesheet (no type-attribute).
Not sure if necessary. This is a bugfix for xsl-stylesheets, but technically allows use of css-stylesheets. Not sure if it should be recommended by including in docs.
=> fix(rss): add missing type-attribute for xsl stylesheets

.changeset/light-moose-attend.md, packages/astro/src/core/config/schema.ts, packages/astro/src/core/dev/container.ts, packages/astro/src/core/preview/index.ts, packages/astro/src/core/preview/static-preview-server.ts, packages/astro/src/vite-plugin-astro-server/route.ts, packages/astro/test/astro-dev-headers.test.js, packages/astro/test/astro-preview-headers.test.js, packages/astro/test/fixtures/astro-dev-headers/package.json, packages/astro/test/fixtures/astro-dev-headers/src/pages/index.astro, packages/astro/test/fixtures/astro-preview-headers/package.json, packages/astro/test/fixtures/astro-preview-headers/src/pages/index.astro, pnpm-lock.yaml
With this new `server.headers` option, the users can specify custom headers for `astro dev` and `astro preview` servers.
This is useful when they want to build a website requiring specific response headers such as `Cross-Origin-Opener-Policy`.
Adding a new `server.headers` option to allow the users to specify HTTP response headers for both `astro dev` and `astro preview`.
Added new unit tests for both `astro dev` and `astro preview`.
This document should be updated: https://docs.astro.build/en/reference/configuration-reference/#server-options
=> Add `server.headers` option

examples/docs/astro.config.mjs
Change a little typo
No new docs needed
=> Docs example: use HTTPS for `site` in `astro.config.mjs`

.changeset/fresh-bats-prove.md, packages/astro/src/runtime/server/render/component.ts, packages/astro/test/units/render/components.test.js
- Updates `renderComponent` to sanitize dynamic tags before printing
- This was an unintentional way to inject attributes, not a feature. This PR will close off that security hole.
Added a unit test
N/A, just a security patch
=> Sanitize dynamic tags

.changeset/red-nails-mix.md, packages/astro/src/content/internal.ts
Content collections requires the latest MDX minor release. Remove reference to `next--content-schemas` in MDX error message.
N/A
N/A
=> [Fix] Incorrect error message for MDX peer dependency

packages/astro/src/core/errors/errors-data.ts
- Updates `message` to avoid stringifying the function.
- Updates `description` for clarity.
N/A
This is only a docs change
=> Docs: Fix `prerender` error message

examples/with-content/README.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/errors/errors-data.ts
- Use trailing slashes on docs links as required by docs link checker
- Fix up a couple of relative links so they work when shown in editor tooltips
- Unblocks https://github.com/withastro/docs/pull/2191/ & https://github.com/withastro/docs/pull/2192/
No testing, docs only.
Docs links changes — /cc @withastro/maintainers-docs for feedback!
=> Fix links in content used by docs

packages/astro/src/@types/astro.ts
Add configuration docs for the `experimental.errorOverlay` flag to match those for `prerender` and `contentCollections`.
Currently in docs we render out those other flags but not the `errorOverlay` flag: https://docs.astro.build/en/reference/configuration-reference/#experimental-flags
n/a docs change only
Yes. Is there a reason we wouldn’t want to document this like we do other experimental features?
=> Add JSDoc comments for error overlay to match other experimental flags

.changeset/two-pants-enjoy.md, packages/astro/e2e/fixtures/client-only/src/components/ReactCounter.jsx, packages/astro/e2e/fixtures/client-only/tsconfig.json, packages/astro/src/vite-plugin-astro/compile.ts, packages/astro/src/vite-plugin-jsx/index.ts
fix https://github.com/withastro/astro/issues/5541
fix https://github.com/withastro/astro/issues/5624
If a framework component as side effects that access browser globals, and is used as `client:only`, Astro should treeshake the import of that component import to prevent the side effect from running in SSR.
#5553 accidentally break this as `"importsNotUsedAsValues": "error"` is respected when specified in the tsconfig, causing the import to be preserved and not treeshaken.
This PR forces `"importsNotUsedAsValues": "error"`
updated client-only test
n/a bug fix
=> Fix client only import with importsNotUsedAsValues error

.changeset/small-camels-mix.md, packages/astro/src/core/build/static-build.ts
- Can't say I fully understand what changed this behavior, but it looks like due to some timing changes in the build, the `chunks` directory is empty before it's populated by the client build.
- If we remove the `chunks` directory because it is empty, the client assets also disappear.
- Closes https://github.com/withastro/astro/issues/5643, closes https://github.com/withastro/astro/issues/5632, closes https://github.com/withastro/astro/issues/5621
Tested manually, need to figure out how to test this
Bug fix only
=> Patch static build regression

.changeset/lazy-tomatoes-call.md, packages/integrations/vercel/src/lib/nft.ts
This PR fixes building a website when using @astrojs/vercel/serverless . It's a temporary fix until https://github.com/vercel/nft/issues/311 gets fixed
- Added an if check to ignore "Failed to parse" errors from @vercel/nft
I don't think tests are needed for this small change, if they are let me know.
It shouldn't affect user behavior
=> fix traced warnings from unexpected token

examples/blog/src/components/BaseHead.astro
- Adds canonical URL which is important for SEO
- Helps with page duplicacy (eg. www -> non-www)
It was tested on my landing page 
No docs needs to be updated
=> Add canonical URL to blog example

.changeset/fluffy-cougars-care.md, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/src/utils.ts
- Remove "now inheriting Markdown plugins..." logs
- Remove check for legacy `extends` config option
N/A
N/A
=> [MDX] Remove verbose migration logs

.changeset/five-apes-heal.md, packages/markdown/remark/src/remark-content-rel-image-error.ts
Remove stray `console.log` from rel image error 😕
=> [Content Collections] Stray console.log snuck in!

.changeset/slow-nails-retire.md, packages/astro/src/@types/astro.ts
Added `server.headers` typing.
This is needed to use `server.headers` along with `defineConfig`.
I'm sorry but I couldn't figure out how to add TS test so no tests were added.
I'm not sure about docs generation.
=> fix(types): add `server.headers` typing

.changeset/purple-hounds-decide.md, packages/astro/src/core/build/vite-plugin-pages.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/core/dev/container.ts, packages/astro/src/vite-plugin-env/index.ts, packages/astro/src/vite-plugin-markdown-legacy/index.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/astro-pages.test.js, packages/astro/test/fixtures/astro pages/src/pages/quotes'-work-too.md
Fix https://github.com/withastro/astro/issues/5670
Use `JSON.stringify` when generating strings for all user input. I didn't update for variables that we control internally for a tiny bit of perf. 
Added a test with markdown file with quotes
n/a bug fix
=> Fix code generation quotes handling

packages/integrations/cloudflare/README.md
Incorporates feedback from two Docs issues (https://github.com/withastro/docs/issues/2142 & https://github.com/withastro/docs/issues/2180):
- updates an outdated Cloudflare docs link
- removes advice to configure streaming because it's now the default
No tests.
Only docs!
=> [docs] reflects updates to cloudflare: streams, env variables

.changeset/good-carpets-confess.md, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/test/ssr-hoisted-script.test.js
Remove inclusion of the base path from config into a hoisted script body. 
Before the hoisted script would be like this if the config has this base value: `base: 'astro-base-bug'`
```js
astro-base-bug/console.log("hello");
```
This would break when the page loads.
After my changes, things are as expected:
```js
console.log("hello");
```
Added a test to confirm the fix. While writing the tests, I had the previous version in `dist` and it fail and include the base path value in the script as well.
No changes to docs necessary
=> fix(astro/core): Do not add base to hoisted script body

.changeset/yellow-gifts-complain.md, packages/astro/src/content/utils.ts
- Resolves #5625 
- Reset `process.env.NODE_ENV` to initial value after reading content config file
Manual testing
N/A
=> [Content Collections] Fix `import.meta.env.DEV` always set to `true`

.changeset/chilled-geese-worry.md, packages/astro/e2e/error-cyclic.test.js, packages/astro/e2e/error-sass.test.js, packages/astro/e2e/errors.test.js, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/vite-plugin-prerender.ts, packages/astro/src/core/config/config.ts, packages/astro/src/core/config/schema.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/core/errors/overlay.ts, packages/astro/test/fixtures/config-vite/astro.config.mjs
Unflags `--experimental-error-overlay` and `--experimental-prerender`
CI
N/A
=> Unflag experimental features

.changeset/selfish-tigers-do.md, .changeset/tricky-rabbits-count.md, .changeset/two-geese-eat.md, examples/integration/index.ts, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/index.ts, packages/astro/src/core/render/result.ts, packages/astro/src/integrations/index.ts, packages/astro/src/runtime/server/astro-global.ts, packages/astro/test/ssr-adapter-build-config.test.js, packages/integrations/cloudflare/src/index.ts, packages/integrations/deno/src/index.ts, packages/integrations/image/src/index.ts, packages/integrations/netlify/src/integration-edge-functions.ts, packages/integrations/netlify/src/integration-functions.ts, packages/integrations/node/src/index.ts, packages/integrations/vercel/src/edge/adapter.ts, packages/integrations/vercel/src/serverless/adapter.ts
- Remove `Astro.resolve`, `Astro.fetchContent`, and `Astro.canonicalURL`.
- Remove `buildConfig` option parameter from integration `astro:build:start` hook
The changesets have more information.
Existing tests should pass (made some tweaks to the old APIs)
Needs a review of the changeset description.
=> Remove deprecated APIs

.changeset/lovely-terms-drive.md, packages/astro/src/core/render/core.ts
Removed the hack used by `@astrojs/mdx` pre v0.12.0. Breaking change for Astro 2.0.
See https://github.com/withastro/astro/pull/5522 for more details.
=> Remove MDX Fragment hack

packages/astro/test/fixtures/third-party-astro/package.json, pnpm-lock.yaml
This is needed to get the beta release out. astro-embed depends on Astro 1, so bumping to 2 breaks its peerDep.
=> Fix astro-embed peerDep issue

.changeset/shaggy-keys-turn.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/config/schema.ts, packages/astro/test/astro-markdown-plugins.test.js, packages/integrations/mdx/README.md, packages/integrations/mdx/package.json, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/src/plugins.ts, packages/integrations/mdx/test/mdx-plugins.test.js, packages/integrations/mdx/test/mdx-syntax-highlighting.test.js, packages/markdown/remark/package.json, packages/markdown/remark/src/index.ts, packages/markdown/remark/src/types.ts, pnpm-lock.yaml
Refine Markdown and MDX configuration options for ease-of-use. Decisions based [on a discord feedback thread](https://discord.com/channels/830184174198718474/872579324446928896/1054813573899092029).
- **Remove `remark-smartypants`** from Astro's default Markdown plugins.
- **Replace the `extendDefaultPlugins` option** with a simplified `gfm` boolean. This is enabled by default, and can be disabled to remove GitHub-Flavored Markdown.
- Ensure GitHub-Flavored Markdown is applied whether or not custom `remarkPlugins` or `rehypePlugins` are configured. If you want to apply custom plugins _and_ remove GFM, manually set `gfm: false` in your config.
- Support _all_ Markdown configuration options (except `drafts`) from your MDX integration config. This includes `syntaxHighlighting` and …
=> Markdown and MDX configuration rework

packages/astro/src/core/errors/errors-data.ts
Docs changed some headings, so this link needs to be updated:
frontmatter injection -> modifying frontmatter
I don't know whether we want to change the error message name or anything else in the description now that we decided to say "modifying frontmatter" vs "frontmatter injection", but at least this corrects the outdated link.
cc @bholmesdev @Princesseuh 
No tests.
Will reflect in docs.
=> update frontmatter injection link to match docs changes

.changeset/quick-impalas-rush.md, packages/integrations/mdx/README.md
Makes some links to our docs site in the MDX integration README absolute instead of relative, which won’t work on GitHub & npm (or in docs where we prefix relative links with the GitHub base for consistency).
n/a docs only
All docs!
=> Fix docs links in MDX README

.changeset/shaggy-melons-tap.md, packages/astro/src/core/build/generate.ts, packages/astro/src/core/errors/utils.ts, packages/astro/test/error-build-location.test.js, packages/astro/test/fixtures/error-build-location/astro.config.mjs, packages/astro/test/fixtures/error-build-location/package.json, packages/astro/test/fixtures/error-build-location/src/env.d.ts, packages/astro/test/fixtures/error-build-location/src/pages/index.astro, pnpm-lock.yaml
Errors in build don't go through the same pipeline as in dev, as such some information was missing from errors thrown there. This doesn't add all of it, and presumably we should do this through the sourcemap eventually, but at least this now show in which file the error happened. This is only a problem for user-thrown errors, our errors already included the location as far as I could tell.
This PR additionally adds a hint to non-Error errors recommending users to instead throw Errors to get as much information as possible from their errors
Fix https://github.com/withastro/astro/issues/5733
Added a test
N/A
=> Add file location to errors in build

.changeset/lemon-eagles-worry.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/core/render/route-cache.ts, packages/astro/src/core/routing/validation.ts, packages/astro/test/fixtures/ssr-prerender-get-static-paths/package.json, packages/astro/test/fixtures/ssr-prerender-get-static-paths/src/pages/[...calledTwiceTest].astro, packages/astro/test/fixtures/ssr-prerender-get-static-paths/src/pages/blog/[year]/[slug].astro, packages/astro/test/fixtures/ssr-prerender-get-static-paths/src/pages/data/[slug].json.ts, packages/astro/test/fixtures/ssr-prerender-get-static-paths/src/pages/food/[name].astro, packages/astro/test/fixtures/ssr-prerender-get-static-paths/src/pages/nested-arrays/[slug].astro, packages/astro/test/fixtures/ssr-prerender-get-static-paths/src/pages/pizza/[...pizza].astro, packages/astro/test/fixtures/ssr-prerender-get-static-paths/src/pages/pizza/[cheese]-[topping].astro, packages/astro/test/fixtures/ssr-prerender-get-static-paths/src/pages/posts/[page].astro, packages/astro/test/ssr-prerender-get-static-paths.test.js, pnpm-lock.yaml
- Closes #5661
- Previously, `getStaticPaths` was not validated or handled properly for `prerender`ed pages. This PR updates our `getStaticPaths` logic and some build logic to account for this case.
- Before: no error message during dev, irrelevant error message during build.
- After: clear error message during dev, same error message during build.
`getStaticPaths` tests ported to test `prerender` support as well
Error message updated to callout this case.
=> Handle `getStaticPaths` with prerendered pages

.changeset/pretty-planes-promise.md, packages/astro/src/vite-plugin-utils/index.ts, packages/astro/test/fixtures/space in folder name/app/package.json, packages/astro/test/fixtures/space in folder name/app/src/pages/index.astro, packages/astro/test/space-in-folder-name.test.js, pnpm-lock.yaml
Note that this will be backported to 1.0 after being cherry-picked.
- Fixes https://github.com/withastro/astro/issues/5598
- Test added
N/A, bug fix
=> Fix for hoisted scripts in project with spaces in the file path

.changeset/config.json, .github/workflows/release.yml
This is so that we can run a patch release for 1.0 without doing so manually. Once the legacy branch has been created we will revert this change.
=> Setup changesets to backport to 1.0 legacy branch

.github/workflows/ci.yml
- Adds `SKIP_OG` env flag for `docs` smoke test.
- This should speed up our smoke tests by avoiding Open Graph image generation in the docs!
N/A, tooling change only
N/A, tooling change only
=> [ci] Skip OG images in docs smoke test

.changeset/smart-clouds-applaud.md, packages/astro/src/core/errors/dev/vite.ts, packages/astro/src/core/errors/errors-data.ts, packages/astro/src/core/render/dev/index.ts
Addresses https://github.com/withastro/rfcs/discussions/420
Add "MDX integration missing" error when the MDX renderer is missing. This addresses a common source for bugs, where the user finds an obscure syntax error when the MDX integration isn't configured.
Manual testing
Add new error-data entry
=> Log pretty error when MDX integration is missing

packages/astro/src/core/errors/README.md, packages/astro/src/core/errors/dev/vite.ts, packages/astro/src/core/errors/errors-data.ts
Small correction to Ben's previous PR adding a error message when the MDX integration is missing, the format was wrong so docs didn't generate properly.
Also added some info to the README to avoid this situation in the future
N/A
Added some info on the technical format to follow for writing error messages
=> Fix MDX integration error message not being compatible with docs

.changeset/lovely-worms-invite.md, packages/astro/src/core/build/static-build.ts, packages/astro/test/astro-dynamic.test.js, packages/astro/test/astro-envs.test.js, packages/astro/test/sourcemap.test.js, packages/integrations/deno/src/index.ts, packages/integrations/image/src/index.ts, packages/integrations/netlify/src/integration-edge-functions.ts
=> feat: change path into assets

.changeset/kind-beers-give.md, packages/astro/test/fixtures/lit-element/src/pages/slots.astro, packages/astro/test/fixtures/lit-element/tsconfig.json, packages/astro/test/lit-element.test.js, packages/astro/test/ssr-lit.test.js, packages/integrations/lit/package.json, packages/integrations/lit/server.js, pnpm-lock.yaml
- This fixes #5475.
- It reverts the injected `<astro-slot>` components.
- And restores the `slot="name"` attributes.
I use [`parse5`](https://parse5.js.org/) to parse the HTML string into a _Fragment_ and then add the missing named slots. This is safer than using regex, but if there's a better parser, don't hesitate to change it.
```html
// Before
<my-element>
<astro-slot slot="header">
<h1>Header</h1>
</astro-slot>
<astro-slot>
<p>Content</p>
<p>Some more content</p>
</astro-slot>
<astro-slot slot="footer">
<small>Legal stuff</small>
<small>© 2023</small>
</astro-slot>
</my-element>
// After
<my-element>
<h1 slot="header">Header</h1>
<p>Content</p>
<p>Some more content</p>
<small slot="footer">Legal stuff</small>
<small slot="footer">© 2023</small>
</my-element>
```
- Tests have been …
=> [@astrojs/lit] Fix slotted content

.changeset/angry-pots-boil.md, packages/astro/src/@types/astro.ts, packages/astro/src/core/config/schema.ts, packages/astro/test/astro-markdown-plugins.test.js, packages/astro/test/fixtures/astro-markdown-plugins/src/pages/with-smartypants.md, packages/integrations/mdx/package.json, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/src/plugins.ts, packages/integrations/mdx/test/fixtures/mdx-plugins/src/pages/with-plugins.mdx, packages/integrations/mdx/test/mdx-plugins.test.js, packages/markdown/remark/package.json, packages/markdown/remark/src/index.ts, packages/markdown/remark/src/types.ts, pnpm-lock.yaml
Resolves #5752 
SmartyPants was removed from Astro's defaults per #5684. This adds back our default with a `markdown.smartypants` option to disable.
Add SmartyPants tests for Markdown and MDX
- Update configuration API
- Update docs reference https://github.com/withastro/docs/pull/2301
=> Add SmartyPants flag

.changeset/modern-bulldogs-film.md, .github/workflows/benchmark.yml, .github/workflows/ci.yml, packages/astro/test/units/test-utils.js, packages/integrations/netlify/src/netlify-functions.ts, packages/integrations/node/test/test-utils.js
Title is self-explanatory! Hopefully this result in a faster CI across the board
Fix https://github.com/withastro/astro/issues/5749
Testing in local, tests runs fine on Node 18! We'll see what CI tells us.
N/A
=> Drop Node 14 in CI for Node 16 and add Node 18 to the matrix

.changeset/calm-peas-doubt.md, packages/astro/package.json, packages/astro/src/content/utils.ts, packages/astro/src/core/config/config.ts, packages/astro/src/core/config/vite-load.ts, packages/astro/test/test-utils.js, pnpm-lock.yaml, scripts/memory/index.js
Close https://github.com/withastro/astro/issues/5748
Fix https://github.com/withastro/astro/issues/5459
- Remove proload, so only fallback to load with Vite only.
- Refactor `resolveConfigPath` to only search for a config path, and not load the config itself, this fixes #5459
Note: I tried to use Vite's `loadConfigFromFile` instead, but it doesn't bring much benefit for us, and prevents named exports from the Astro config if we ever need it. It's also harder to test with `createFs` since `loadConfigFromFile` always read from the actual filesystem.
Existing config loading test should work. Since this _removes_ a proload feature, I don't think there's new test to add.
n/a. Ideally loading the config with Vite should always work, so this change shouldn't need a docs update.
=> Remove proload for config loading

packages/astro/src/@types/astro.ts
Adds `@version 2.0.0` to the JSDoc blocks for new Markdown config options `gfm` and `smartypants`. This helps indicate when these were added in case someone using Astro v1 tries to enable them. The docs site will also pick these up and label these reference entries with “Added in: 2.0.0”.
Docs only, no tests
=> Add `@version` metadata to config reference types

.changeset/thin-seahorses-worry.md, packages/integrations/cloudflare/package.json, packages/integrations/deno/package.json, packages/integrations/image/package.json, packages/integrations/netlify/package.json, packages/integrations/node/package.json, packages/integrations/svelte/package.json, packages/integrations/tailwind/package.json, packages/integrations/vercel/package.json, packages/integrations/vue/package.json, packages/markdown/remark/package.json
- This adds `astro` as a peerDependency to many of our integrations.
- Only adds for integrations that are already doing a `major` release, in order to avoid unnecessarily creating breaking releases for packages that are not otherwise changing.
- N/A, I think.
- N/A
=> Add Astro as a peerDependency

packages/markdown/remark/package.json, pnpm-lock.yaml
Follow up to #5785. I missed that `acorn` and `hast-util-to-html` are no longer used by `@astrojs/markdown-remark` and can be removed as dependencies.
Does this need a patch changeset separate to #5785 or is it minimal enough to ignore?
No docs needed.
=> [markdown-remark] Remove unused dependencies

examples/with-content/src/content/config.ts, examples/with-content/src/content/types.generated.d.ts, packages/astro/src/content/template/types.generated.d.ts, packages/astro/src/content/utils.ts, packages/astro/test/content-collections.test.js, packages/astro/test/fixtures/content-collections/src/content/config.ts, packages/astro/test/fixtures/content-collections/src/content/with-union-schema/newsletter.md, packages/astro/test/fixtures/content-collections/src/content/with-union-schema/post.md, packages/astro/test/fixtures/content-collections/src/pages/collections.json.js, packages/astro/test/fixtures/content-collections/src/pages/entries.json.js, packages/astro/test/fixtures/content-ssr-integration/src/content/config.ts, packages/astro/test/fixtures/content-static-paths-integration/src/content/config.ts, packages/astro/test/fixtures/content/src/content/config.ts
- Allow Zod objects, unions, discriminated unions, intersections, and `transform` results as schemas
- Add helpful warning when `z.object(...)` wrapper is missing
By enforcing the `z.object(...)` wrapper, we open the door for:
- using a `transform` to add and modify frontmatter properties
```ts
const blog = defineCollection({
schema: z.object({
youtube: z.string().url(),
}).transform(data => ({
embedUrl: toEmbedUrl(data.youtube),
thumbnailUrl: toThumbnailUrl(data.youtube),
})
});
```
- using unions and discriminated unions for supporting multiple schemas on the same collection. This is common when splitting multiple options based on a `type` property:
```ts
const posts = defineCollection({
schema: z.discriminatedUnion('type', [
z.object({
type: z.literal('post'),
title: z.string(), …
```
=> [Content Collections] Allow Zod unions, objects, and transforms as schemas

packages/astro/src/core/errors/errors-data.ts
The current migration docs (pre-v1) is going to be replaced by a new page, and although we have a redirect for it, the generated error pages in docs trigger an error in our link checker now that the page doesn't exist anymore, therefore we need to remove this link for now (we can later add the new migration docs page).
100% docs!
=> Remove old migration guide link from error docs

.changeset/fuzzy-phones-rule.md, .changeset/gold-baboons-tie.md, packages/integrations/partytown/package.json, pnpm-lock.yaml
This PR fixes #5819.
No tests were added since it was only a version bump
No need to update docs.
=> Bumps partytown version to fix deprecation warning

.changeset/sweet-rocks-count.md, packages/astro/components/Code.astro
The replace uses a regex witch matches anything extra and adds it back to the css class.
Closes #5828
As mentioned in the linked issue #5828, the actual pinned shiki version v0.11 does work. The v0.12 causes the bug, as a new feature https://github.com/shikijs/shiki/pull/376 adds an extra css class, making the actual logic to fail.
There's a test already in place https://github.com/withastro/astro/blob/4b16e9ec9929269a16e7950d8fed78779149b0fc/packages/astro/test/astro-component-code.test.js#L37-L41 and it will fail when shiki gets updated to v0.12. This PR resolves the issue.
=> Fix `Code.astro` shiki css class replace logic

.changeset/beige-beds-smile.md, packages/astro/src/core/build/vite-plugin-prerender.ts
- Fixes #5754
- Manually splitting each page into a separate chunk causes some issues with execution order
- This fix emits a single chunk for all dynamic pages
Tested manually, reproduction is fixed
=> Fix order-of-execution bug when generating pages

.changeset/fluffy-onions-wink.md, packages/astro/src/cli/sync/index.ts, packages/astro/src/content/types-generator.ts, packages/astro/src/content/utils.ts, packages/astro/src/content/vite-plugin-content-server.ts
- Resolves #5711 
Better handle content type generation failures:
- Generate types when content directory is empty
- Log helpful error when running `astro sync` without a content directory
- Avoid swallowing `config.ts` syntax errors from Vite
- Fix: Generate types when the `content/` dir is added in dev
Manual testing: adding and removing the `content` directory, adding and modifying the `config.ts` file.
https://github.com/withastro/docs/pull/2345/
=> [Content collections] Improve content config handling

.changeset/thin-beers-drive.md, .gitignore, examples/with-content/astro.config.mjs, packages/astro/src/@types/astro.ts, packages/astro/src/core/build/generate.ts, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/vite-plugin-css.ts, packages/astro/src/core/build/vite-plugin-ssr.ts, packages/astro/src/core/config/config.ts, packages/astro/src/core/config/schema.ts, packages/astro/src/core/create-vite.ts, packages/astro/src/core/render/dev/environment.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/astro/test/fixtures/.gitignore, packages/astro/test/fixtures/content-collections/astro.config.mjs, packages/astro/test/fixtures/content-ssr-integration/astro.config.mjs, packages/astro/test/fixtures/content-static-paths-integration/astro.config.mjs, packages/astro/test/fixtures/content/astro.config.mjs, packages/astro/test/units/dev/collections-renderentry.test.js, packages/integrations/mdx/src/plugins.ts, packages/markdown/remark/src/index.ts, packages/markdown/remark/src/remark-content-rel-image-error.ts, packages/markdown/remark/src/types.ts, packages/markdown/remark/test/autolinking.test.js, packages/markdown/remark/test/entities.test.js, packages/markdown/remark/test/plugins.test.js, packages/markdown/remark/test/test-utils.js
- Removes `experimental.contentCollections` flag
- Remove flag wherever used
https://github.com/withastro/docs/pull/2354
=> [Content collections] Remove experimental flag

.changeset/giant-chefs-rule.md, packages/integrations/mdx/src/remark-shiki.ts, packages/markdown/remark/src/remark-shiki.ts
=> fix shiki css class replace logic in md and mdx integrations

.changeset/spicy-tips-dream.md, packages/astro/CHANGELOG.md, packages/integrations/deno/CHANGELOG.md, packages/integrations/image/CHANGELOG.md, packages/integrations/netlify/CHANGELOG.md
- Adds a changeset for https://github.com/withastro/astro/pull/5772
- Removes irrelevant changelog entries from #5584 for clarity
N/A
N/A
=> Add changeset for `_astro` directory

scripts/notify/index.js
- Our announcement script [would fail](https://github.com/withastro/astro/actions/runs/3904214156/jobs/6669686822) when the messages were >= 2000 characters.
- This adds some special handling to reformat the message if the original message is too large.
**Before**
Failed 😥
**After**
```
🥳 Some awesome updates now out. Be the first on your block to download!
• `astro@2.0.0-beta.2` Read the [release notes →](<https://github.com/withastro/astro/blob/main/packages/astro/CHANGELOG.md#200-beta2>)
Also hot and fresh:
• `@astrojs/prism@2.0.0-beta.0`
• `create-astro@2.0.0-beta.0`
• `@astrojs/cloudflare@6.0.0-beta.1`
• `@astrojs/deno@4.0.0-beta.2`
• `@astrojs/image@1.0.0-beta.2`
• `@astrojs/lit@1.0.2-beta.0`
• `@astrojs/mdx@1.0.0-beta.2`
• `@astrojs/netlify@2.0.0-beta.2`
• …
```
=> Fix announcements CI actions when 2000+ characters

.changeset/twenty-llamas-type.md, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/config/schema.ts, packages/astro/src/core/create-vite.ts
=> Support envPrefix in Astro config

.changeset/ninety-garlics-fly.md, packages/astro/src/core/build/static-build.ts, packages/astro/src/core/build/vite-plugin-alias-resolve.ts, packages/astro/test/alias.test.js
fix #5821
Add a Vite plugin to resolve aliases for client build input entries.
This is a workaround for now until the upstream Rollup fix: https://github.com/rollup/plugins/pull/1402
Added a test for alias build. There was only dev.
n/a. bug fix.
=> Fix importing client-side components with alias

.changeset/poor-ladybugs-thank.md, packages/astro/src/core/dev/restart.ts, packages/astro/test/units/dev/restart.test.js
Fix https://github.com/withastro/astro/issues/5783
Override Vite's `server.restart` API with our implementation.
Added a unit test, and manually tested the repro that it works.
n/a. bug fix.
=> Handle server restart from Vite plugins

.changeset/witty-pugs-drum.md, packages/astro/tsconfigs/base.json
Fix https://github.com/withastro/astro/issues/5061
Disable typechecking libraries and .d.ts files. This change was also debatable in Vite before, but the tradeoff (of not typechecking local .d.ts files) was worth it as it's otherwise surfacing type errors unintentionally from a library. (More context: https://github.com/vitejs/vite/issues/7867)
n/a
n/a
=> Enable skipLibCheck by default

.changeset/smooth-cycles-sing.md, packages/astro/tsconfigs/strictest.json
Add missing `noPropertyAccessFromIndexSignature` to strictest tsconfig profile
Fixes #5861.
cc @Princesseuh
=> Add missing `noPropertyAccessFromIndexSignature` to strictest tsconfig profile

.changeset/smooth-cycles-sing.md, packages/astro/tsconfigs/strictest.json
Reverts withastro/astro#5864
Revert for now per https://github.com/withastro/astro/pull/5864#issuecomment-1384782830
=> Revert "Add missing `noPropertyAccessFromIndexSignature` to strictest tsconfig profile"

.changeset/lovely-worms-invite.md, .changeset/spicy-tips-dream.md, .changeset/thin-beers-drive.md
- `@astrojs/image` and `@astrojs/mdx` were not intended to go 1.0. They were made so by mistake.
- This change the changesets to `minor` so that the changes are breaking but not major.
N/A
N/A
=> Make image and mdx changesets be minor instead of major

.changeset/mean-suits-cover.md, packages/integrations/image/components/Image.astro, packages/integrations/image/components/Picture.astro, packages/integrations/image/components/index.ts, packages/integrations/image/test/fixtures/basic-image/src/pages/index.astro
- Refactor types to support props auto-completion for the `Image` and `Picture` components.
- Pass previously missing `alt` prop to the `getPicture` function
Tested locally. There's only a small runtime change (see `alt` prop passed to the `getPicture` function). All tests should pass
N/A
=> Refactor `Props` of `Image` and `Picture` component to support type checking

.changeset/calm-emus-raise.md, packages/astro/src/@types/astro.ts, packages/astro/src/vite-plugin-markdown/index.ts, packages/integrations/mdx/src/index.ts, packages/integrations/mdx/src/plugins.ts
- Remove `content.astro` warning messages
- Remote deprecated `getHeaders()` function
- Remove `rawContent()` and `compiledContent()` errors from MDX and type signature. Users expect that checking `file.rawContent === undefined` will allow safe calling on MD and MDX files. By exporting these functions _just_ to throw errors, we made it harder to use them safely!
All deprecated APIs, so no docs changes!
=> Cleanup deprecated Markdown APIs from 0.X

.changeset/few-rice-report.md, packages/astro/src/core/errors/overlay.ts
Add a theme toggle button for the error overlay
This is a style change, doesn't need to be documented
=> feat: add theme toggle button to error overlay

.changeset/neat-eagles-trade.md, packages/astro/src/content/internal.ts, packages/astro/src/content/template/types.d.ts, packages/astro/src/content/template/virtual-mod.mjs, packages/astro/test/fixtures/content-collections/src/content/config.ts, packages/astro/test/fixtures/content-collections/src/pages/entries.json.js
- Rename `getEntry` to `getEntryBySlug`.
- The new function takes a slug as the second argument instead of an id.
- It loops over the collection and finds a matching entry that has the provided slug.
- The types here could maybe be better? I could figure out a way to type it so that the provided slug matches an entry with that slug. I think the fact that a slug can be any `string` is a blocker here. Happy to be proven otherwise.
- Tests updated
- PR https://github.com/withastro/docs/pull/2408
=> Rename getEntry to getEntryBySlug

.changeset/fluffy-cups-travel.md, examples/blog/src/pages/rss.xml.js, packages/astro-rss/README.md, packages/astro-rss/package.json, packages/astro-rss/src/index.ts, packages/astro-rss/src/schema.ts, packages/astro-rss/src/util.ts, packages/astro-rss/test/pagesGlobToRssItems.test.js, packages/astro-rss/test/rss.test.js, packages/astro-rss/test/test-utils.js, packages/astro-rss/tsconfig.json, pnpm-lock.yaml
- Expose `rssSchema` to type-check content collections for RSS feeds
- Deprecate internal `import.meta.glob` handling and move to a `pagesGlobToRssItems()` helper. This has a few benefits:
- Simplifies our `items` array to accept a single type. Better for JS docs and docs.astro.build.
- Makes the "only glob `src/pages/` entries" requirement more explicit with the function name.
- Makes handling globs and handling content collections feel equally supported. When `import.meta.glob` handling was implicit, this felt like the more encouraged solution.
- Refactor internals to use Zod all the way down. This makes error handling on bad config much clearer!
- Change glob example to a content collections example
- Add `rssSchema` and `pagesGlobToRssItems()` reference
- Chore: change …
=> [RSS] Get ready for content collections

.changeset/six-dingos-add.md, packages/astro/astro.js
Check nodejs version support via semver only, rather than whether it supports ESM, since we're relying on node 16 features now.
NOTE: The `supports-esm` dep can be removed, but I might do that as a separate PR as the lockfile needs to be fixed by the next beta release first.
Tested manually, here are the logs for lower node versions:
```
Node.js v10.24.1 is not supported by Astro!
Please upgrade Node.js to a supported version: ">=16.12.0"
Node.js v12.22.12 is not supported by Astro!
Please upgrade Node.js to a supported version: ">=16.12.0"
Node.js v14.18.3 is not supported by Astro!
Please upgrade Node.js to a supported version: ">=16.12.0"
```
The CLI works after using a supported node version.
I also tested that `ci-info` is working as well.
n/a
=> Fix CLI node version check

.changeset/kind-panthers-doubt.md, packages/create-astro/README.md, packages/create-astro/src/index.ts
- Support headless runs with `-y` / `--yes` in the create-astro cli
No testing was added. All existing tests pass. I can add testing if needed
No need for docs updates, because as far as I'm aware there are no reference docs for `create-astro` besides the `README.md` file in the root of the package.
=> Add headless support to create-astro

.changeset/large-hotels-give.md, packages/create-astro/src/index.ts
- Adds a helpful error message when a third-party template passed to `create astro` is not found.
- Inspired by https://github.com/withastro/docs/issues/2372
- Currently if a user passes `--template username/repo` and `giget` fails to load that repo, the command fails and says "does not exist!":
- A common cause is that the template repo does not have a `main` branch (which `giget` assumes by default and we have no way of guessing without calling the GitHub API), so the updated error message adds some pointers
> Could not find template **username/repo**!
> Are you sure this GitHub repo exists? This command uses the **main** branch by default.
> If the repo doesn't have a main branch, specify a custom branch name:
> **username/repo#branch-name**
Don’t think this needs tests as it’s just a …
=> Improve error message for third-party template 404s

.changeset/lucky-ants-push.md, packages/integrations/svelte/README.md
- Fixes up a few details that weren’t quite clear in the Svelte README
n/a
=> Improve Svelte README

.changeset/lucky-tigers-know.md, packages/integrations/image/package.json, packages/webapi/package.json, pnpm-lock.yaml
- Updated the required version of magic-string used in `@astrojs/image` and `@astrojs/webapi` to fix #5929
Current tests passed.
No changes.
=> Update magic-string used by @astrojs/image and @astrojs/webapi 

.changeset/real-rules-occur.md, packages/integrations/netlify/src/integration-edge-functions.ts, packages/integrations/netlify/src/integration-functions.ts, packages/integrations/netlify/src/shared.ts, packages/integrations/netlify/test/functions/dynamic-route.test.js, packages/integrations/netlify/test/functions/fixtures/dynamic-route/src/pages/pets/[cat].astro, packages/integrations/netlify/test/functions/fixtures/dynamic-route/src/pages/pets/[dog].astro, packages/integrations/netlify/test/functions/fixtures/dynamic-route/src/pages/pets/index.astro, packages/integrations/netlify/test/functions/fixtures/prerender/src/pages/404.astro, packages/integrations/netlify/test/functions/fixtures/prerender/src/pages/index.astro, packages/integrations/netlify/test/functions/fixtures/prerender/src/pages/one.astro, packages/integrations/netlify/test/functions/prerender.test.js
- Fixes https://github.com/withastro/astro/issues/5860
- A little bit of a refactor of the logic that generates the _redirects file to be a little more structured.
- Rather than use the build-generated "distURL", which is always going to be wrong for dynamic routes, builds it itself and uses Netlify's placeholder syntax. For spread routes it uses the * syntax.
- Prettifys it a bit so that each part, the input, target, and status all line up.
- Test added for the same scenario that the bug describes.
N/A, bug fix.
=> Support prerender in Netlify redirects
