- docs/syntax.md
I think this is the link you wanted for the extension
Updated broken link to what I believe is the correct one
> Update vs code link

- packages/astro/package.json
- packages/astro/src/compiler/transform/head.ts
- packages/astro/test/astro-basic.test.js
- packages/astro/test/fixtures/astro-basic/src/components/Tour.jsx
- packages/astro/test/fixtures/astro-basic/src/pages/client.astro
- packages/astro/test/helpers.js
- yarn.lock
This fixes HMR and adds a test. If there are client-side components and HMR is enabled, add the script.
- [✅] Tests are passing
- [✅] Tests updated where necessary
N/A
> Add HMR port script when needed

- packages/astro/src/runtime.ts
> Fix baseUrl passed to Snowpack

- .github/workflows/nodejs.yml
- examples/blog/package.json
- package.json
- packages/create-astro/package.json
- packages/create-astro/test/create-astro.test.js
- yarn.lock
Improves template test from #376, but still doesn’t add in CI. We still have trouble running the test, and it needs to be addressed in a followup.
> Improve templates test

- examples/starter/package.json
> config: add snowpack workspace root to starter

- .changeset/wicked-fishes-change.md
Forgot to add a changeset to the previous PR so doing so here.
> Adds a changeset for doctype change

- docs/styling.md
Clarifies docs based on some [feedback gathered on Twitter](https://twitter.com/sil/status/1404740393368014850?s=20).
No tests
This is docs
> Clarify docs suggesting that Astro may just randomly break your styles

- docs/syntax.md
Updates the Syntax document.
- Clarifies Astro's design principles
- Gets straight to the point (no more philosophical ramblings)
Just docs.
Yes, this is that.
> Update syntax docs

- .changeset/kind-baboons-melt.md
- packages/astro/src/build.ts
- packages/astro/src/compiler/transform/module-scripts.ts
- packages/astro/test/astro-resolve.test.js
- packages/astro/test/fixtures/astro-resolve/public/absolute.js
- packages/astro/test/fixtures/astro-resolve/src/pages/relative.js
- packages/astro/test/fixtures/astro-resolve/src/pages/scripts.astro
Fixes #104.
Adds tests
No docs needed
> Fix script resolution

- packages/astro/package.json
- yarn.lock
Fixes #443 and #435
Underlying issue fixed in Snowpack here: https://github.com/snowpackjs/snowpack/pull/3449
Tested in Snowpack.
N/A
> Fix issue with proxy imports not reloading on change

- .changeset/rude-cameras-rhyme.md
- packages/astro-parser/src/parse/read/expression.ts
- packages/astro/test/astro-basic.test.js
- packages/astro/test/fixtures/astro-basic/src/pages/forward-slash.astro
Fixes #407
Adds test
Internal change
> Fix parser error on forward slash

- docs/styling.md
More docs typo fixes
Docs-only change
> Fix typo, clarify layout section

- .changeset/slow-apricots-doubt.md
- packages/astro/package.json
- yarn.lock
Fixes #192 and #468
Upgrades snowpack which fixes a race condition caused by stat + read.
N/A
N/A
> Fix race condition in build

- examples/starter/public/style/global.css
- Update width for body to avoid horizontal scroll
- Fixes Issue #209
Tested if page scrolled horizontally on chromium-based browser and Firefox.
N/A
> Fix horizontal scroll for starter template.

- examples/docs/public/index.css
#Changes
- Update sidebar styles
- Add styles for scrollbar
Tested if sidebar worked for firefox and chromium-based browsers.
Styles for firefox didn't apply completely but seemed to be more complex than it's worth (at least for now)
N/A
> Fix sidebar scrolling docs

- .changeset/ninety-sheep-know.md
- packages/create-astro/src/index.ts
> update small cli output fixes

- .changeset/thin-pets-camp.md
Just the changeset that I forgot to push.
> Add changeset for node builtins

- .changeset/brave-glasses-cry.md
- examples/astro-markdown/.npmrc
- examples/blog/.npmrc
- examples/docs/.npmrc
- examples/kitchen-sink/.npmrc
- examples/portfolio/.npmrc
- examples/snowpack/.npmrc
- examples/starter/.npmrc
- examples/tailwindcss/.npmrc
- adds .npmrc to starter templates with shamefully-hoist=true
`pnpm i && pnpm start`
bug fix for pnpm users
> force pnpm to hoist packages inside astro #342 #190

- packages/astro/README.md
Fixes #342
Adds docs on using pnpm and Yarn.
Docs only
Yep
> Document pnpm and Yarn usage

- .changeset/shy-cats-brake.md
- packages/astro-parser/src/parse/read/expression.ts
- packages/astro-parser/src/parse/state/tag.ts
- packages/astro/src/compiler/codegen/index.ts
- packages/astro/test/astro-basic.test.js
- packages/astro/test/fixtures/astro-basic/src/pages/spread.astro
Fixes #521. Allows `{...spread}` props in `.astro` files.
Added a test!
Bugfix only.
> Fix `{...spread}` props

- packages/astro/src/compiler/codegen/index.ts
- packages/astro/test/helpers.js
- packages/renderers/renderer-react/index.js
Some how a merge messed up code
> Fix code from bad merge

- .changeset/twelve-islands-kneel.md
- packages/astro/package.json
- packages/astro/test/helpers.js
- yarn.lock
Fixes #546
Tested in snowpack
Bug fix only
> Upgrade postcss snowpack plugin

- .changeset/config.json
Fix changeset config again
N/A
N/A
> Fix changeset

- packages/astro/src/runtime.ts
- packages/astro/test/fixtures/react-component/src/components/GetSearch.jsx
- packages/astro/test/fixtures/react-component/src/pages/window.astro
- packages/astro/test/react-component.test.js
Addresses #551.
Adds testable repro for bug (test will fail)
Test added; no code changes
> Add test for React SSR + window

- .changeset/wild-crabs-care.md
- packages/astro/package.json
Issues reported on discord
https://discord.com/channels/830184174198718474/845451724738265138/862451674122813491
> Pin to snowpack 3.7.1

- .changeset/famous-years-bow.md
- examples/blog/src/pages/posts/introducing-astro.md
- examples/docs/src/layouts/Main.astro
- examples/framework-multiple/src/pages/index.astro
- examples/framework-preact/src/pages/index.astro
- examples/framework-react/src/pages/index.astro
- examples/framework-svelte/src/pages/index.astro
- examples/framework-vue/src/pages/index.astro
- examples/snowpack/src/pages/news.astro
- examples/snowpack/src/pages/plugins.astro
- examples/with-markdown/src/pages/index.astro
- examples/with-nanostores/src/pages/index.astro
- packages/astro/README.md
- packages/astro/src/compiler/codegen/index.ts
- packages/astro/src/compiler/transform/head.ts
- packages/astro/test/fixtures/astro-basic/src/pages/client.astro
- packages/astro/test/fixtures/astro-dynamic/src/pages/default-rename.astro
- packages/astro/test/fixtures/astro-dynamic/src/pages/index.astro
- packages/astro/test/fixtures/astro-fallback/src/pages/index.astro
- packages/astro/test/fixtures/astro-hmr/src/pages/index.astro
- packages/astro/test/fixtures/astro-hmr/src/pages/manual.astro
- packages/astro/test/fixtures/astro-markdown/src/pages/complex.astro
- packages/astro/test/fixtures/custom-elements/src/pages/load.astro
- packages/astro/test/fixtures/no-head-el/src/components/Child.astro
- packages/astro/test/fixtures/no-head-el/src/pages/index.astro
Updates hydration to use a directive syntax (#514)
WIP!  Final syntax may change to `client:idle` or similar, docs need updates, and I'm sure the Astro syntax parser will need updates to cover the change
WIP: Tests have been updated for the directive syntax.  I also ran through the `examples/framework-___` sample projects to make sure hydration scripts were being bundled and loaded on the client
WIP: No docs updates yet other than example projects
> Move hydration directives to special attributes

- packages/create-astro/src/index.ts
> Use new client:visible syntax in create-astro

- examples/blog-multiple-authors/src/pages/index.astro
> Missing `firstPage`

- package.json
- packages/astro/package.json
- yarn.lock
This fixes a script execution ordering bug.
Tested in snowpack.
N/A, bug fix.
> Upgrade to snowpack@3.8.0

- .changeset/tender-paws-smash.md
- packages/astro/README.md
Just a minor typo correction
N/A
N/A
> Docs: Correcting minor typo in ReadMe

- examples/framework-solid/README.md
Sorry for not contributing in a big thing but i saw the readme was copied for preact example so i changed it, thanks for supporting Solid it is promising as much as Astro
> Changing the preact to Solid

- www/src/layouts/Blog.astro
- www/src/pages/blog/index.astro
- www/src/pages/blog/introducing-astro.astro
- www/src/pages/index.astro
- www/src/pages/posts/introducing-astro.astro
- yarn.lock
- Adds a `lang` attribute to all https://astro.build pages.
> Add `lang` attribute to pages on https://astro.build

- .changeset/lemon-jars-poke.md
- packages/astro/package.json
- yarn.lock
Not sure why, but this must have been removed some how (a bad merge?)
> Add missing dependency

- docs/src/pages/core-concepts/astro-components.md
> closing style tag

- docs/src/pages/blog/island-architecture.md
- docs/src/pages/core-concepts/astro-components.md
- docs/src/pages/core-concepts/component-hydration.md
- docs/src/pages/core-concepts/layouts.md
- docs/src/pages/core-concepts/project-structure.md
- docs/src/pages/getting-started.md
- docs/src/pages/guides/data-fetching.md
- docs/src/pages/guides/deploy.md
- docs/src/pages/guides/markdown-content.md
- docs/src/pages/guides/publish-to-npm.md
- docs/src/pages/guides/styling.md
- docs/src/pages/reference/api-reference.md
- docs/src/pages/reference/renderer-reference.md
- Typo fixes in the documentation to improve quality
Typos fixed to improve the quality of the documentation.
> Fix typos in the documentation.

- examples/blog/src/components/BlogPost.astro
> fix: fixes prop href of author component in example blog, was url

- docs/src/config.ts
- docs/src/layouts/Main.astro
- docs/src/pages/comparing-astro-vs-other-tools.md
- docs/src/pages/getting-started.md
- Adds a new comparison page, comparing Astro to others
- Resolves one of the most frequent questions that we get in our discord
- Preview: https://astro-docs-git-comparing-docs-pikapkg.vercel.app/comparing-astro-vs-other-tools
> Docs: Add new comparison page

- docs/src/pages/core-concepts/collections.md
- Fix examples in Collections API documentation
Fixed examples in collection API documentation
> fix(docs): collection doc typos

- docs/src/pages/core-concepts/layouts.md
- Docs change.
Just adds `astro` to a code block.
> docs/fix: add language to code block

- .changeset/good-teachers-relax.md
- packages/astro/src/@types/astro.ts
- packages/astro/src/cli.ts
- packages/astro/src/compiler/index.ts
- packages/astro/src/config.ts
- packages/astro/src/dev.ts
- packages/astro/src/runtime.ts
- packages/astro/test/config-hostname.test.js
- packages/astro/test/fixtures/config-hostname/astro.config.mjs
- packages/create-astro/src/config.ts
Added ability to specify hostname in devOptions
close #716
Added test file `config-hostname.test.js`
> Add ability to specify hostname in devOptions

- docs/src/pages/index.astro
Add title ("Astro Documentation") for the Astro Documentation Page.
Not tested because it is a tiny addition.
Public documentation is updated.
> Add title for the Astro Documentation Page

- scripts/cmd/build.js
- Fixes https://github.com/snowpackjs/astro/issues/726
> fix bad build script

- docs/src/pages/reference/cli-reference.md
Adds documentation for the `--silent` cli flag.
> Docs/ Add `--silent` cli option

- .changeset/silver-goats-repeat.md
- packages/astro/package.json
User reported unfound `./snowpack-plugin-jsx.cjs` error. This fixes it!
Hotfix
Bug fix only
> fix: unfound snowpack-plugin-jsx.cjs error

- packages/astro/src/cli.ts
close https://github.com/snowpackjs/astro/issues/788
Actually, idk the way how i can test it, it will be nice if you can help me with this
> Add ability to specify site with command line

- .prettierignore
Skip running format in .github and .changeset folders. Changing a GitHub workflow and trying to commit it in an action is not supported.
N/A
N/A
> Fix formatting action

- docs/src/pages/core-concepts/astro-components.md
Adds a missing word
I did not test it, because I just added a word.
Well, yes, this is the documentation being changed 😄
> Add missing word

- contributing.md
While I am looking up how I can contribute to this open source, I spent a little time on sorting out the version set issue with yarn and node. Therefore, I believe this will be a useful and concise information for other contributors to understand the basic required yarn and node version
No
This is simply a content editing. No breaking change on code
No, because this is simply a content editing. No breaking change on code
> edit contributing Prerequisite

- docs/src/pages/core-concepts/component-hydration.md
> docs: add missing `matchMedia` reference

- docs/src/pages/quick-start.md
> Fixes typo

- .changeset/fluffy-pillows-rule.md
- docs/src/pages/guides/markdown-content.md
- packages/markdown-support/package.json
- packages/markdown-support/src/index.ts
- yarn.lock
Added [remark-slug](https://github.com/remarkjs/remark-slug) to fix #805
> Add remark-slug

- .changeset/quick-houses-sip.md
- packages/renderers/renderer-vue/index.js
Revert of #858 to address #905.
> Revert #858

- docs/public/index.css
- docs/src/layouts/Main.astro
Fixes the scroll margin on `:target` and fixes the site sidebar view on mobile
> 📘 DOC: Improve SiteSidebar styles on mobile

- docs/src/pages/guides/deploy.md
- Branch main not replaced with build files
https://github.com/mulaidev/components/runs/3192333172
https://github.com/mulaidev/components/blob/main/README.md
> Fix Github Action setup

- docs/src/pages/nl-NL/getting-started.md
Added a Dutch getting started file for the documentation.
- Some text have been altered to sound better in Dutch
Testing in browser, see screenshot above.
Only documentation update, as too suggested format by @FredKSchott
> Started on the getting started dutch docs 🇳🇱

- .changeset/friendly-hotels-explode.md
- packages/create-astro/src/index.ts
Fix #931 
please test it before accepting this PR!
i don't know, why the file removal was introduced...
> forced degit template extraction in case of non empty installation directory

- docs/src/pages/guides/styling.md
The title is Self explanatory.
> Docs: Add svelte file extension to tailwind purge configuration.

- examples/with-tailwindcss/README.md
> fix styling guide

- examples/docs/public/index.css
When using the docs example, after running `npm run build` some CSS were missing:
After changing the imports everything started working again.
I tested this on localhost and on cloudflare pages. Both with `npm start` and `npm run build`/
It doesn't requires any update in my opinion.
> Fixes throwing 404

- docs/src/components/Header/Header.astro
- docs/src/components/Header/LanguageSelect.tsx
- docs/src/components/LeftSidebar/LeftSidebar.astro
- docs/src/components/RightSidebar/MoreMenu.astro
- docs/src/config.ts
- docs/src/layouts/MainLayout.astro
- docs/src/pages/fi/getting-started.md
- docs/src/pages/fi/installation.md
- docs/src/pages/fi/quick-start.md
- docs/src/pages/index.astro
- docs/src/util.ts
- tools/vscode/.vscodeignore
- Connect the language selector to our brand new Finnish and Dutch translations! (/cc @Merri @rebelchris)
- Connect the sidebar to our new translations
> DOC: Add translations, language selector to docs site

- .changeset/fair-cameras-draw.md
- packages/astro/src/build.ts
Fixes #985
Tested locally on `portfolio` example.
Documentation update wasn't necessary.
> fix: Exclude remote srcset URLs

- docs/src/pages/core-concepts/collections.md
- Added missing but required link attribute
- Added note on how to create a full text feed
Not tested, because it's a doc update.
Docs were updated, see changes.
> Improve Collection docs for RSS

- examples/portfolio/src/components/Nav/index.jsx
Fixed `portfolio` example. #986 
> Fix portfolio example

- docs/src/pages/guides/deploy.md
Repairing my own mistake in the CF Pages part (replacing `”` with `’`).
- What does this change? Fixes a typo.
Testing n/a in this case.
Typo fix only.
> Update deploy.md (typo in newly added section)

- docs/src/layouts/MainLayout.astro
- docs/src/layouts/SplashLayout.astro
no, but it adding the dir will help adding rtl languages like Arabic Which i'm willing to start soon
> Adding Dir attribute to allow rtl languages to work

- docs/src/components/Header/LanguageSelect.tsx
- docs/src/pages/pt-br/getting-started.md
- docs/src/pages/pt/getting-started.md
- Adds Portuguese translation of Getting Started page Based on Brazilian Portuguese
- Would be nice if someone else with Portuguese knowledge could review it.
It's docs uptade
> Add Portuguese Translation of Getting Started page

- docs/src/pages/es/getting-started.md
- docs/src/pages/index.astro
- See title!
- adds support for `lang-region` codes
> DOC: update automatic docs redirect

- .github/workflows/release.yml
- package.json
- Merging the "Version Packages" PR should now trigger a release!
> update release CI script to publish

- docs/src/components/Header/LanguageSelect.tsx
- docs/src/config.ts
- docs/src/pages/bg/getting-started.md
- docs/src/pages/index.astro
Changed files: `config.ts`, `LanguageSelect.tsx`.
Added Bulgarian translation for the Getting Started page (`pages/bg/getting-started.md`) and added _"Bulgarian"_ as an option to the language selection field.
> Added Bulgarian translation for the Getting Started page.

- packages/astro/src/build.ts
Closes snowpackjs/astro#1052
1. Renamed isRemote function to isRemoteOrEmbedded within build.ts
2. isRemoteOrEmbedded should ignore both remote urls as well as data uri embedded assets
3. Simplified the Boolean statement within this function 
N/A
N/A, Bug Fix  
-->
> Ignore embedded image as page dependency during build

- .github/workflows/congratsbot.yml
> testing a github action, safe to ignore

- tools/language-server/astro.d.ts
- tools/language-server/src/index.ts
- tools/language-server/src/plugins/PluginHost.ts
- tools/language-server/src/plugins/astro/AstroPlugin.ts
- tools/language-server/src/plugins/css/CSSPlugin.ts
- tools/language-server/src/plugins/html/HTMLPlugin.ts
- tools/language-server/src/plugins/interfaces.ts
- tools/language-server/src/plugins/typescript/DocumentSnapshot.ts
- tools/language-server/src/plugins/typescript/TypeScriptPlugin.ts
- tools/language-server/src/plugins/typescript/astro-sys.ts
- tools/language-server/src/plugins/typescript/features/CompletionsProvider.ts
- tools/language-server/src/plugins/typescript/features/HoverProvider.ts
- tools/language-server/src/plugins/typescript/features/SignatureHelpProvider.ts
- tools/language-server/src/plugins/typescript/previewer.ts
- tools/language-server/src/plugins/typescript/utils.ts
Fixes #1067 and #1026
https://www.loom.com/share/ee9ee23270df40db8ccd18500fff78db
This adds support for 2 things:
- Completion for `Astro.*` APIs.
- Hover support
N/A
N/A
> Add support for Astro.* completion and Hover help

- .changeset/nice-hounds-visit.md
- .github/workflows/release.yml
- packages/create-astro/src/index.ts
- Adds new "latest" branch for docs, www,  and `create-astro` CLI
- on every release, we automatically push `main` to `latest` to update `docs`, `www` & `create-astro`
> [CI] support new "latest" branch

- docs/src/pages/core-concepts/routing.md
- docs/src/pages/de/getting-started.md
- docs/src/pages/guides/deploy.md
- docs/src/pages/guides/rss.md
- docs/src/pages/guides/styling.md
- docs/src/pages/installation.md
- docs/src/pages/reference/api-reference.md
- docs/src/pages/reference/renderer-reference.md
This PR fixes some typos in the docs.
Just typo fixes. No semantic or structural changes.
> Fix typos in the docs/ content

- docs/public/index.css
@natemoo-re @snowpackjs/docs thoughts on this change? (Compare the preview URL to current latest). Borrowed some inspiration from Giest, which is Vercel's style framework.
> DOCS: minor typography changes

- docs/src/pages/core-concepts/astro-components.md
- Fix a typo
This is a markdown dokument.
Yes, public documentation was updated.
> Fix docs typo

- .changeset/silver-shoes-lie.md
> changeset: markdown-support (fix the left-brace issue)

- docs/reference/api-reference.md
- docs/src/pages/blog/island-architecture.md
- docs/src/pages/comparing-astro-vs-other-tools.md
The changes made in this PR address typos in the docs.
These changes clean up some typos and do not affect the semantics or structure of the docs.
> Fix typos in the docs.

- packages/create-astro/src/config.ts
Simply removes one space character from the `astro.config.mjs` file.
> Remove whitespace

- .changeset/thirty-ads-destroy.md
- .github/workflows/ci.yml
- packages/astro/src/cli.ts
- packages/astro/src/compiler/codegen/index.ts
- packages/astro/src/compiler/transform/util/end-of-head.ts
- packages/astro/src/config_manager.ts
- packages/astro/src/frontend/hydrate/media.ts
- packages/astro/src/internal/__astro_component.ts
- packages/astro/src/internal/element-registry.ts
- packages/astro/src/logger.ts
- packages/astro/src/manifest/create.ts
- packages/astro/src/runtime.ts
- Fixes lint issues
- Removes non-null assertions
- Enables lint in CI
Ran `yarn lint`, no warnings or errors were reported.
Lint fix only.
> Fix linter errors and warnings

- examples/docs/src/layouts/Main.astro
Same as https://github.com/snowpackjs/astro/pull/1062, the changes were accidentally reverted in https://github.com/snowpackjs/astro/pull/1084
None
Bug fix
> Fix CSS in docs example

- .changeset/red-news-tap.md
- examples/with-markdown-plugins/astro.config.mjs
- examples/with-markdown-plugins/package.json
- packages/astro/package.json
- packages/astro/test/fixtures/astro-markdown-plugins/astro.config.mjs
- packages/markdown-support/package.json
- packages/markdown-support/src/codeblock.ts
- packages/markdown-support/src/index.ts
- packages/markdown-support/src/load-plugins.ts
- packages/markdown-support/src/rehype-collect-headers.ts
- packages/markdown-support/src/types.ts
- yarn.lock
Closes #1191, see rationale in the issue and details in the comments below 👇 
All tests pass, this is a deps- and types-only change
This is a deps- and types-only change
> Upgrade unified deps and improve unified plugins types

- docs/src/components/Header/Header.astro
- Change the logo behavior to not flip when direction is set to rtl
- fix the clipping issue on mobile, rtl
> docs: fix header rtl logo view

- docs/src/pages/reference/api-reference.md
Minor change: keep API doc alphabetized
Docs-only change
Docs-only change
> Alphabetize API doc

- .github/workflows/congratsbot.yml
- Congrats bot should now only show the first line (which is always the PR title)
> Fix congratsbot multiline issue

- .changeset/silver-icons-hope.md
- packages/astro/astro.js
- Reported in Discord: https://discord.com/channels/830184174198718474/883170719150776360/883176670838804521
- Added comments to describe the edge-case that this protects against
> Fix astro bin bug in some pre-ESM versions of Node v14.x

- .changeset/cuddly-feet-hug.md
- packages/astro/package.json
- packages/astro/src/cli.ts
- packages/astro/src/config.ts
- packages/astro/src/runtime.ts
- packages/astro/test/config-validate.test.js
- www/astro.config.mjs
> Format config errors for humans

- docs/src/pages/installation.md
Just a missing period at the end.
> docs: add a period

- docs/src/components/LeftSidebar/LeftSidebar.astro
- docs/src/util.ts
Fixes the highlighting of the current page in `LeftSidebar.astro`
> 📘DOC: Fix URL normalization for the Left Sidebar in docs

- .gitpod.yml
- Adds `.gitpod.yml` with start tasks for continuous prebuild: https://www.gitpod.io/docs/config-start-tasks
> Add `.gitpod.yml` for continuous prebuilds for speedy project startup!

- docs/src/pages/guides/deploy.md
`v14.7.0` => `node v14.7.0` since `.nvmrc` can specify npm and yarn versions as well!
> Update netlify deploy instructions for `.nvmrc` syntax

- yarn.lock
- Updates the `yarn.lock` file which was out of date for some reason.
N/A
N/A
> Add a new lockfile

- www/vercel.json
- Adds a `rewrite` to `www/vercel.json` to direct `/play` to `https://play.astro.build/play`
N/A, site change
N/A, site change
> Add `astro.build/play` link

- docs/src/pages/quick-start.md
- Order deploy host list alphabetically
- Add AWS label to S3 bucket link.
N/A
Public documentation update.
> Order deploy host list alphabetically

- docs/src/pages/core-concepts/astro-pages.md
Added info how to create a custom 404 error page
> Update astro-pages.md: Create custom 404 error page

- .github/workflows/release-next.yml
Adds publish script on PR merge to `next`
> Automate publish on merge

- docs/src/pages/guides/deploy.md
Added how to deploy to render.com.
Added information for deploying to render.com
> Update deploy.md with information how to deploy to render.com

- examples/portfolio/src/pages/index.astro
- Ensures background gradient image stretches to cover larger resolutions on desktop.
- Tested through all major break-point sizes.
Simple styling addition.
> Update gradient background sizing.

- docs/src/pages/de/getting-started.md
Thank you very much for this great project! 
I was reading through the German translation of the Getting Started Guide and corrected/changed some wording and punctuation.
No tests were added because this PR only affects the docs.
Only updated the German translation of the Getting Started Guide.
This is my very first PR in an open source project. I hope that I have not forgotten any important steps. Happy to add anything I might have forgotten.
> docs: German: Change some wording and punctuation

- docs/src/config.ts
- docs/src/pages/zh-TW/getting-started.md
> Update Doc: Getting Starteted in Zh-tw

- packages/astro/src/build.ts
- Changes the parallel pages build to run in series instead (it used Promise.all() which didn't close handles soon enough for each async job)
- Only one file is being written at a time
- The file handle is freed after one page has been created so there are no dangling handles
The previously failing build process was fixed and it does not fail when creating 10000 pages ([see the example repo](https://github.com/kometbomb/astro-file-handle-bug)). `yarn test` completed successfully in the astro repo.
No changes to documentation.
> Write pages serially and close file handle

- docs/src/pages/core-concepts/component-hydration.md
I added an example of using Astro with client side JavaScript. This fixes #754.
- Added an example to partial hydration docs for using client side JavaScript in an Astro component
No changes
See changes above
> Add script tag example

- docs/src/pages/da/getting-started.md
- Update the danish translation for the getting started page
> docs: Update danish getting started docs

- .changeset/silly-kids-collect.md
- packages/astro/test/fixtures/react-component/src/components/Pure.jsx
- packages/astro/test/fixtures/react-component/src/pages/index.astro
- packages/astro/test/react-component.test.js
- packages/renderers/renderer-react/server.js
- The React Renderer now is able to detect Pure components as being React components.
- Closes #1400
Test added
Bug fix only
> Support PureComponent in the react renderer

- packages/renderers/renderer-solid/client.js
- packages/renderers/renderer-solid/index.js
- packages/renderers/renderer-solid/server.js
- packages/renderers/renderer-solid/static-html.js
Ports over https://github.com/snowpackjs/astro/pull/1479
> Add hydration to Solid renderer (#1479)

- www/src/pages/blog/index.astro
- Add [latest blogpost](https://astro.build/blog/astro-021-preview) to [blog index](https://astro.build/blog/)
- No tests added
- no docs needed
> Add latest blogpost to blog-index

- packages/astro/package.json
- yarn.lock
- Updates `@astrojs/compiler` to v0.2.23.
We'll see if they pass ☺️
N/A
> [next] update compiler

- docs/src/data/themes.json
- Capitalized theme names for consistency
- Added more info to community packages (sandbox/command)
I haven't tested this locally, only changed it here.
Yes, to be specific the https://docs.astro.build/themes/ page and then the "Featured packages" section.
> Further enhance the community packages data

- packages/astro/src/@types/astro-runtime.ts
- packages/astro/src/runtime/server/hydration.ts
- packages/astro/src/runtime/server/index.ts
- packages/astro/src/runtime/server/util.ts
- Accepted PR accidentally merged to `next`, this redoes it against `main`
- https://github.com/snowpackjs/astro/pull/1699
N/A
N/A
> Small refactor to the server runtime (#1699)

- examples/docs/src/config.ts
Fixes the error described at #1640
> children error fix

- .changeset/shaggy-guests-type.md
- docs/src/pages/guides/styling.md
- examples/with-tailwindcss/package.json
- examples/with-tailwindcss/postcss.config.js
- examples/with-tailwindcss/src/components/Button.astro
- examples/with-tailwindcss/src/pages/index.astro
- packages/astro/src/@types/astro-core.ts
- packages/astro/src/core/dev/index.ts
- packages/astro/src/core/ssr/css.ts
- packages/astro/src/core/ssr/html.ts
- packages/astro/src/core/ssr/index.ts
- packages/astro/src/runtime/client/hmr.ts
- yarn.lock
Adds support for Tailwind HMR by scanning `.astro` files for imported `<link>`-ed styles, and firing HMR
No tests currently for HMR (this is tricky!). Manual testing done.
Updated docs
> Get Tailwind HMR working (first cut)

- docs/src/pages/installation.md
Added `--` before `--template` in `pnpm create astro my-astro-project --template starter`
> added -- to pnpm create

- .changeset/giant-shirts-sing.md
- packages/astro/package.json
- packages/astro/src/core/config.ts
- yarn.lock
- Adds support for `astro.config.cjs`, `astro.config.js`, and `astro.config.ts` files
Manually
Nope, this just improves support!
> Improve `astro.config` loading

- GOVERNANCE.md
Fixes broken anchor link in the `GOVERNANCE.md`
It's just a minor docs change
minor link fix only
> docs: fix playbook anchor in governance.md

- .changeset/little-dogs-help.md
- packages/astro/src/vite-plugin-build-html/extract-assets.ts
- packages/astro/src/vite-plugin-build-html/index.ts
- packages/astro/test/astro-scripts.test.js
- packages/astro/test/fixtures/astro-scripts/src/components/Widget.astro
- packages/astro/test/fixtures/astro-scripts/src/components/Widget2.astro
- packages/astro/test/fixtures/astro-scripts/src/scripts/another_external.js
- packages/astro/test/fixtures/astro-scripts/src/scripts/something.js
- Brings back hoisted scripts tests.
- Shows that they are failing
Uncommented existing tests
No changes
> Uncomment hoisted scripts

- examples/with-tailwindcss/tailwind.config.js
- Without this Tailwind doesn't JIT your .astro used classes.
No
The docs already have this, just not the example app.
> Tell tailwind to purge from the src folder

- packages/astro/src/core/dev/template/error.ts
Added Astro logo, updated layout, and changed colors.
- Redesigned the 404 page on Not Found errors.
- Design change only, no code changed.
- No docs updated.
> (next) Redesigned 404 page

- .github/ISSUE_TEMPLATE/---01-bug-report.yml
- Updates issue template to require reproduction with https://astro.new
N/A
N/A
> Update issue template

- .github/labeler.yml
- .github/workflows/label.yml
- For organization
- Uses the official [Labeler](https://github.com/actions/labeler) action to automatically label PRs based on the files they change.
Not sure how to test
N/A
> Automatically add PR labels

- docs/src/pages/migration/0.21.0.md
Adds Autoprefixer changes to 0.21 migration guide
Docs change
Docs change only
> Add Autoprefixer change to 0.21 migration guide

- docs/src/config.ts
- Fixes the Netlify build that has been failing
- Italian translation was missing needed config.
N/A
N/A
> Fix docs Netlify build

- packages/astro/src/vite-plugin-jsx/index.ts
- Make changes based on code review with some members of the team
- All small changes, mainly around documentation, code organization, and one babel improvement
- I had more review comments on the actual plugin itself, but will save that for another time!
> Code review comments

- .github/labeler.yml
- .github/workflows/label.yml
- More updates to our `labeler` action!
- Adds more granular labels, like `framework-vue`
N/A
N/A
> Improve PR labels

- .changeset/seven-bottles-warn.md
- packages/astro/src/core/dev/index.ts
- packages/astro/test/astro-styles-ssr.test.js
- packages/astro/test/dev-routing.test.js
- packages/astro/test/fixtures/with-subpath-no-trailing-slash/astro.config.mjs
- packages/astro/test/fixtures/with-subpath-no-trailing-slash/src/pages/another.astro
- packages/astro/test/fixtures/with-subpath-no-trailing-slash/src/pages/index.astro
- packages/astro/test/fixtures/with-subpath-trailing-slash/astro.config.mjs
- packages/astro/test/fixtures/with-subpath-trailing-slash/src/pages/another.astro
- packages/astro/test/fixtures/with-subpath-trailing-slash/src/pages/index.astro
- packages/astro/test/fixtures/without-site-config/src/pages/another.astro
- packages/astro/test/fixtures/without-site-config/src/pages/index.astro
- packages/astro/test/fixtures/without-subpath/astro.config.mjs
- packages/astro/test/fixtures/without-subpath/src/pages/another.astro
- packages/astro/test/fixtures/without-subpath/src/pages/index.astro
- packages/astro/test/test-utils.js
- Adds dev server routing tests for when using subpath, when not using subpath, etc.
- Fixes small bug with AstroDevServer not stopping cleanly.
Lots of them
N/A
> Dev server routing tests (and fixes)

- packages/astro/test/astro-styles-ssr.test.js
Minor fix: removes unnecessary timeout setting for test
No docs needed
> Fix styles-ssr timeout

- packages/markdown/remark/package.json
- yarn.lock
- Removed unused dep
- resolves https://github.com/snowpackjs/astro/issues/1884
- supercedes https://github.com/snowpackjs/astro/pull/1867
- Covered by existing tests.
- N/A
> remove unused remark dependency

- .changeset/few-pumpkins-report.md
- packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js
- packages/markdown/remark/package.json
- Updates more internal resolution of Vite to its package, resolving to our vendored copy instead. This fixes the build
No
N/A
> Remove further dependence on vite package

- examples/blog/src/pages/posts/index.md
> Fix blog example

- .changeset/giant-beds-cough.md
- .changeset/large-grapes-lie.md
- We added deps to the package.json
N/A
No
> Adding a changeset for package.json bump

- .prettierignore
- examples/blog/src/pages/posts/index.md
- Tested the glob this time
- Should work 🤞
> Fix blog example yet again

- .prettierignore
> Do not let Prettier bot mess with the blog example

- packages/astro/src/core/dev/index.ts
- packages/astro/test/dev-routing.test.js
> Allow search params

- www/src/components/BlogPost.astro
- www/src/components/BlogPostPreview.astro
- www/src/data/blog-posts/astro-021-release.md
- www/src/pages/blog/index.astro
> [blog] New 0.21 release post

- .changeset/afraid-badgers-search.md
- packages/astro/src/vite-plugin-build-html/index.ts
- You should be able to directly do `/src/styles/global.scss` and not use Astro.resolve. This fixes that.
Fixes portfolio built, which i tested.
N/A
> Allow links/images to be loaded from browser /src

- www/src/pages/index.astro
> [www] Update index.astro to point to new blog post

- docs/src/pages/getting-started.md
- Adds a note about [astro.new](https://astro.new) to the docs
doc fix only
doc fix only
> Mention astro.new in docs

- docs/src/pages/reference/configuration-reference.md
It fixes a broken link
---
---
> (docs) Fix config reference link

- docs/src/pages/ja/themes.astro
- Fix Japanese theme page layout
I have confirmed that it displays fine in my local environment.
Document update only
> Fix Japanese theme page to use v0.21

- docs/src/pages/quick-start.md
- Fix a broken link
Looks like a simple change when compared with previous lines of code.
Navigating the website lead to a 404 page.
> Fix broken "Routing guide" link

- docs/src/pages/guides/environment-variables.md
- Updates environment variable guide to use `PUBLIC_` rather than `VITE_` prefix.
N/A
This is it, this is the docs!
> docs: update env variable guide

- .changeset/tame-melons-think.md
- packages/astro/src/core/ssr/css.ts
- packages/astro/src/core/ssr/index.ts
- packages/astro/test/0-css.test.js
- packages/astro/test/fixtures/0-css/public/global.css
- packages/astro/test/fixtures/0-css/src/pages/index.astro
- packages/astro/test/test-utils.js
Fixes #1973. Simple fix.
Test added.
No docs needed
> Improve CSS URLs on Windows

- .changeset/lemon-comics-cheat.md
- packages/astro/package.json
- yarn.lock
Does what it says in the title.
> chore: update compiler

- docs/src/pages/ja/getting-started.md
- Update Online Playgrounds section
I have confirmed that all the links work in my local environment.
Document update only
> Docs: Update Japanese getting started page

- .changeset/early-pandas-teach.md
- packages/astro/src/core/preview/index.ts
- Closes https://github.com/withastro/astro/issues/2007
- Borrows the `port` retry behavior from `astro dev` for `astro preview`
Manually tested. Lookin good! 😎 
Bug fix only
> fix(#2007): astro preview port retry

- .changeset/config.json
- Adds `withastro/astro` to Changesets to improve Changelogs
This'll do it.
N/A
> chore: fix changeset

- .changeset/ten-clocks-remember.md
No code, changes, or tests; just adds missing changeset for #2052
> Add changeset for #2052

- packages/astro/package.json
- packages/astro/test/astro-css-bundling-import.test.js
- yarn.lock
> Upgrade compiler to 0.5.4

- docs/netlify.toml
- www/netlify.toml
Should ignore changes outside of `docs/` and `www/` from Netlify per [`ignore` docs](https://docs.netlify.com/configure-builds/common-configurations/ignore-builds/#custom-ignore-command). TBD.
N/A
N/A
> [experiment] Netlify Ignore

- .changeset/gold-windows-sell.md
- packages/astro/test/0-css.test.js
- packages/astro/test/fixtures/0-css/src/pages/index.astro
- packages/astro/test/fixtures/0-css/src/styles/imported-url.css
- packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js
- Upstream PR: https://github.com/vitejs/vite/pull/5940
- Allows `import url from './styles.css?url';
Test added
Bug fix only
> Fix support for ?url on CSS

- docs/src/pages/zh-CN/comparing-astro-vs-other-tools.md
> Fix a link syntax

- docs/src/pages/guides/publish-to-npm.md
**Work in Progress**
- Updates the **Publish to NPM** page to better align with our current best practices.
docs update only
docs update only
> DOCS: Update "Publish to NPM"

- packages/astro/README.md
Registered on Open collective, thanks!
> Added Qoddi inside the sponsor list

- .github/workflows/ci.yml
- Fixes turbo caching
This is the test
N/A
> Improve turbo cache

- docs/src/pages/de/migration/0.21.0.md
- docs/src/pages/migration/0.21.0.md
- Closes https://github.com/withastro/astro/issues/2190
- Small typo
N/A
This is it.
> Migration Guide typo

- docs/src/pages/zh-TW/themes.astro
http://localhost:3000/zh-TW/themes
Fix broken layout in Zh-tw
> Fix Docs layout: Themes in Zh-tw

- examples/with-nanostores/package.json
- examples/with-nanostores/src/components/AdminsReact.jsx
- examples/with-nanostores/src/components/AdminsSolid.jsx
- examples/with-nanostores/src/components/AdminsSvelte.svelte
- examples/with-nanostores/src/components/AdminsVue.vue
- examples/with-nanostores/src/pages/index.astro
- examples/with-nanostores/src/store/counter.js
- examples/with-nanostores/src/store/users.js
This changes adds Solid to the nanostores example, also improves the Svelte component and naming on others.
No tests were added since this example doesn't have tests.
Docs weren't updated.
> Adding Solid to with-nanostores example

- .github/workflows/ci.yml
- Updates `turbo` cache strategy per https://github.com/withastro/astro/pull/2167#discussion_r766858192
- Presumably fixes various caching issues we've been battling
N/A
N/A
> Update `turbo` cache

- .github/workflows/ci.yml
- package.json
- scripts/smoke/index.js
- Builds all examples as a part of our smoke test suite
- Runs smoke tests on both windows and ubuntu
- Tested in this PR
- N/A
> improve our smoke tests to run on all examples

- examples/with-vite-plugin-pwa/README.md
> Fix example path for init

- docs/src/pages/guides/aliases.md
- Updates alias docs to reflect the current capabilities of Astro.
docs update only
docs update only
> Update alias docs

- docs/src/pages/de/guides/styling.md
- Fixing minor spelling errors  
- Removing void hint to Peter-Griffin gif
Minor spelling errors corrected - proof read!  
Does not need to be reviewed.
This is the docs
> Update docs/de styling.md to correct minor spelling errors

- docs/src/pages/guides/styling.md
- examples/with-tailwindcss/package.json
- examples/with-tailwindcss/tailwind.config.js
Updated tailwind template to tailwind 3
I ran the example manually and it works 
It was updated for tailwind config changes
> chore: update tailwind to v3 and update the readme

- .github/workflows/ci.yml
- Does what the title says
Testing on this PR
N/A
> Update CI to cache `node_modules` per OS

- docs/src/pages/core-concepts/component-hydration.md
- examples/fast-build/astro.config.mjs
- Formats files so they will stop being added to other PRs.
prettier fix only
prettier fix only
> Run Prettier

- packages/astro/test/astro-css-bundling-nested-layouts.test.js
- packages/astro/test/astro-dynamic.test.js
- packages/astro/test/errors.test.js
- packages/astro/test/svelte-component.test.js
- packages/create-astro/test/create-astro.test.js
- Removes debugging logs left in tests
- Reduces noise in tests
presentational fix only
presentational fix only
> Cleanup tests with leftover console logs

- docs/src/pages/[...slug].astro
- Get old->new redirects working for nested pages
- manual testing
- it is docs
> Rename [slug].astro to [...slug].astro

- .changeset/sixty-shoes-taste.md
- packages/astro/package.json
- yarn.lock
- Updates `@astrojs/compiler` to `0.7.2`
CI
N/A
> Update compiler to 0.7.2

- docs/src/pages/en/guides/environment-variables.md
Important knowledge to avoid type errors.
What does this change?
- Docs. ;)
Be short and concise. Bullet points can help!
- Added new important paragraph.
Before/after screenshots can be helpful as well.
- Nope.
> Added "IntelliSense for TypeScript"

- .changeset/spotty-turtles-complain.md
- packages/astro/src/core/dev/template/4xx.ts
- packages/astro/src/core/path.ts
- packages/astro/src/core/preview/index.ts
- packages/astro/test/preview-routing.test.js
- Fixes various issues triggered by `buildOptions.pageUrlFormat` and `devOptions.trailingSlash`.
- @matthewp and I discussed `buildOptions.site` and agreed it represents a directory.
- This means a value of `http://example.com/blog` is to be treated as tho it were `http://example.com/blog/`.
- Tests are updated to reflect this view.
bug fix only
> Fix Astro Preview Pathing Issues

- docs/src/pages/en/guides/deploy.md
Updates Cloudflare Pages deploy guide to reflect that there's now an Astro preset. See https://developers.cloudflare.com/pages/framework-guides/astro
> Update Cloudflare Pages guide

- docs/src/pages/en/guides/deploy.md
- This PR adds that Cloudflare supports GitLab now.
- Rewords the environment variable section of deploys for Pages
> Update Cloudflare pages to show gitlab support 

- .changeset/afraid-ducks-develop.md
- packages/astro/package.json
- yarn.lock
- This fixes the need to pin the compiler version. Also includes bug fixes.
> Upgrade compiler to latest

- CONTRIBUTING.md
- GOVERNANCE.md
- Some issues in GOVERNANCE & CONTRIBUTING
- If you have any questions about what the changes are for do ask
- Yes, that is the point of this pr ;)
> Update CAPFILES (GOVERNANCE & CONTRIBUTING)

- examples/with-tailwindcss/src/pages/index.astro
Workaround for https://github.com/withastro/astro/issues/2410
> patch tailwindcss example global css

- docs/src/pages/en/migration/0.21.0.md
Someone forgot to add an "s" into install, so I added one for the docs in Migration.
IDK if this affects anything, I just found a typo.
Fixing Someone's Mistakes / Bug Fixes.
> Change from Intall to Install in line 239 Documentation in Migration

- packages/astro/package.json
See #2460
- Bug fix only
- Bug fix only
> Remove `vite-plugin-fetch` from one more location

- docs/src/pages/en/migration/0.21.0.md
closes #2441
- See title
- No code changes
- Updates 0.21.0.md
> Add note about imports to migration guide

- assets/social/banner.svg
- Removes expensive SVG animation
N/A
N/A
> Remove SVG animation on hero image

- .changeset/beige-rockets-play.md
- .changeset/spicy-bananas-enjoy.md
- Adds changesets for #2473 and #2487
changeset only
changeset only
> Changesets

- docs/src/pages/en/guides/deploy.md
- docs/src/pages/es/guides/deploy.md
This PR updates the deployment documentation for Vercel to be more concise. I've also fixed the `astro.vercel.app` URL to be updated 😄
> Update deployment documentation for Vercel.

- examples/minimal/astro.config.mjs
- examples/minimal/src/pages/index.astro
- Removes portions of the minimal example that users often remove
example improvement only
example improvement only
> Minimize the minimal example

- assets/social/banner.svg
- packages/astro/README.md
- Fixes reported performance issues, no animations in SVGs! It's a fun trick but it's unecessary.
This is that.
N/A
> Remove SVG animation on GitHub/NPM

- .changeset/warm-drinks-design.md
- packages/astro/package.json
- yarn.lock
- Upgrades `@astrojs/compiler` to [`0.10.2`](https://github.com/withastro/compiler/blob/main/lib/compiler/CHANGELOG.md#0102)
CI
N/A
> chore: upgrade compiler

- .github/workflows/ci.yml
- .gitignore
- package.json
- packages/astro/package.json
- packages/astro/src/core/create-vite.ts
- scripts/memory/index.js
- scripts/memory/mk.js
- yarn.lock
- This adds a memory leak smoke test
- Runs dev, a project with 100 pages, over and over again.
- Takes median of the run and then the average of the last 30 and compares. If the average of the last 30 is higher it assumes this means that memory is continuing to grow.
This is a test, obviously.
Nah.
> Adds memory leak test in CI

- .github/workflows/ci.yml
- package.json
- scripts/smoke/index.js
- Adds `test:smoke` command for local runs
- Improves CI to run consistently on all platforms
CI
Nah
> Improve smoke tests

- examples/blog-multiple-authors/package.json
In the migration guide, need to install sass. So the example not working correctly. I add SASS to fix it.
> Missing SASS error problem fix

- .changeset/lazy-parents-turn.md
- packages/astro/package.json
- yarn.lock
- Updates `@astrojs/compiler` to [`0.11.4`](https://github.com/withastro/compiler/blob/main/lib/compiler/CHANGELOG.md#0114)
CI
Bug Fix
> Upgrade compiler, fixes self-closing `<title />`

- packages/astro/src/@types/astro.ts
- packages/astro/src/core/config.ts
- Unblocks https://github.com/withastro/docs/pull/172
> Add detailed type annotations to AstroUserConfig

- packages/astro/test/lit-element.test.js
- Just fixes the lit test
Test fixed to no longer delete globals which caused a race condition and broke Vite.
N/A
> Remove the after in the Lit test

- .changeset/funny-pants-begin.md
- packages/renderers/renderer-svelte/index.js
- packages/renderers/renderer-svelte/package.json
- yarn.lock
- Reverts change in https://github.com/withastro/astro/pull/2715 until we can address some unintended breakage of the static build.
- Unblocks https://github.com/withastro/astro/pull/2705
- Reopens https://github.com/withastro/astro/issues/2273
Existing tests
N/A
> Revert #2715 (temporarily)

- scripts/notify/index.js
- Fixes recent notification failure
- Also fixes problem reported in Discord about incorrect CHANGELOG links 
- Hardcodes links from package names to CHANGELOG URLs in the `scripts/notify/index.js` script
N/A
> Update CI notify script

- .changeset/cool-ravens-occur.md
- packages/astro/src/@types/astro.ts
- packages/astro/src/core/build/index.ts
- packages/astro/src/core/config.ts
- packages/astro/src/core/render/sitemap.ts
- Adds `sitemapFilter` option to our config. This is _likely_ a temporary option until integrations are sorted out.
- Follow-up to https://github.com/withastro/astro/pull/2562
N/A, no sitemap tests
Config docs are JS-doc driven
> Add sitemap filter option

- packages/astro/src/core/util.ts
> add maxRetries to fix windows fs.rmsync

- .changeset/serious-guests-matter.md
- packages/astro/src/runtime/server/escape.ts
- packages/astro/src/runtime/server/index.ts
- packages/astro/test/astro-directives.test.js
- packages/astro/test/fixtures/astro-directives/src/pages/set-html.astro
- Closes https://github.com/withastro/compiler/issues/327
- Fixes `set:html={null}` and `set:html={undefined}`
Tests added
Bug fix only
> Fix `set:html` behavior with `null`

- .changeset/eighty-trees-thank.md
- packages/astro/package.json
- packages/astro/test/astro-partial-html.test.js
- pnpm-lock.yaml
- Updates compiler to pull in the new CSS parser. See https://github.com/withastro/compiler/pull/329 for more details.
CI
N/A, bug fix
> Update Compiler with new CSS Parser

- .changeset/pre.json
- packages/astro/src/core/add/index.ts
- Exits `changeset pre` mode.
- Will release `0.25.0`
CI only
CI only
> Exit `pre` mode

- .changeset/good-jobs-raise.md
- packages/astro/package.json
- pnpm-lock.yaml
Does what it says
No tests, bug fix
Bug fix
> Fix missing `execa` dependency

- .changeset/tall-cooks-begin.md
- packages/integrations/sitemap/README.md
- packages/integrations/sitemap/src/index.ts
- #2964 got dropped from #2962
- This adds it back
N/A
N/A
> Sitemap Integration

- examples/blog-multiple-authors/src/pages/authors/[author].astro
- examples/docs/src/components/HeadCommon.astro
- examples/docs/src/components/LeftSidebar/LeftSidebar.astro
- examples/docs/src/layouts/MainLayout.astro
- examples/docs/src/pages/index.astro
- examples/env-vars/src/pages/index.astro
- examples/framework-alpine/src/pages/index.astro
- examples/integrations-playground/src/pages/index.astro
- examples/non-html-pages/src/pages/index.astro
- examples/ssr/astro.config.mjs
- examples/subpath/astro.config.mjs
- examples/with-vite-plugin-pwa/src/pages/index.astro
> chore: updated examples to v0.26.0

- packages/astro/package.json
Missed this in https://github.com/withastro/astro/pull/2985 :cry:
No docs needed
> Add missing entry in files field in package.json

- packages/astro/src/core/config.ts
- Fixes a regression in v0.26.0
- Fixes #2983 
- N/A - I guess we're not testing the bug reported in #2983 ? It's getting late and I want to get this in asap, but it would be good to follow up with a test to cover this.
- N/A
> fix markdown mode default

- .changeset/odd-squids-rest.md
- packages/astro/src/core/build/generate.ts
- packages/astro/src/core/request.ts
- packages/astro/src/vite-plugin-astro-server/index.ts
- packages/astro/src/vite-plugin-build-html/index.ts
- packages/astro/test/fixtures/static build/src/pages/index.astro
- packages/astro/test/static-build.test.js
- Adds a warning when trying to get a headers in SSG mode.
- Closes #3018
No, can't test warnings very well currently.
N/A
> Warn when trying to access headers in SSG mode

- packages/astro/src/@types/astro.ts
- like the title says, adds the missing TS type property
- N/A
- Missing in docs as well, filed https://github.com/withastro/docs/issues/335
> add missing Astro.self type

- examples/docs/README.md
This PR fixes some of lint issues found in the README file of the docs example
> Fixed MD Lint issues

- examples/framework-alpine/package.json
- examples/framework-alpine/src/pages/index.astro
- pnpm-lock.yaml
- Removes the remote unpkg URL from our alpine example
- uses a local npm package as an ESM import for better bundling
- fixes #2929 
- probably shouldn't be merged until https://github.com/withastro/astro/issues/2834 is resolved
- Tested manually
- N/A
> use bundled alpinejs in the example

- packages/astro/src/core/config.ts
- A user in Discord was having trouble realizing that this was their issue: https://github.com/AREA44/astro-firstweb/commit/f2fac9afff18ff8e4014e77618eac2ff4e3dfe91
- A more specific error message is better than a vague one.
- N/A
- N/A
> improve legacy config warning message

- packages/integrations/netlify/README.md
- Notes to use `--deploy` flag when deploying.
N/A
This is a docs issue.
> Netlify adapter, add --build flag in the readme

- packages/webapi/src/lib/Element.ts
- Small change to squash WebAPI type warning
Type change only
Type change only
> chore(webapi): fix types

- .changeset/funny-houses-drop.md
- packages/astro/package.json
- pnpm-lock.yaml
- Fixes a whole bunch of compiler edge cases.
- [Full changes](https://github.com/withastro/compiler/blob/main/packages/compiler/CHANGELOG.md#0142) in the CHANGELOG
CI
Bug fixes only
> Upgrade compiler

- .changeset/lemon-humans-deliver.md
Forgot a changeset from #3175!
> Add changeset for "create astro online editor config" PR

- README.md
Merging this into my readme branch so that Juan gets credit :)
> New readme plus

- package.json
- pnpm-lock.yaml
> chore: pnpm v7

- CONTRIBUTING.md
`CONTRIBUTING.MD`
`pnpm` version was updated from 6 to 7
No tests, just a markdown update
No docs update
> update pnpm version from 6.23.6 to 7

- .changeset/big-years-type.md
- packages/astro/package.json
- packages/astro/src/@types/shorthash.d.ts
- packages/astro/src/core/create-vite.ts
- packages/astro/src/runtime/server/index.ts
- packages/astro/src/runtime/server/shorthash.ts
- pnpm-lock.yaml
[shorthash](https://www.npmjs.com/package/shorthash) hasn't been updated in 9 years and it's CJS-only. So, I've extracted it into `shorthash.ts` and removed everything that wasn't being used
> refactor: internalize shorthash

- README.md
- packages/astro/README.md
- Fix the README image, since npm doesn't support light/dark mode
- We already had this banner available as a fallback in case it didn't work
> small readme image fix

- packages/astro/src/@types/astro.ts
Brings across some [updates to the `server` config options](https://github.com/withastro/docs/pull/422/) @RafidMuhymin proposed on the docs repo but which need updating in the types file.
Closes https://github.com/withastro/docs/pull/422
Docs only.
See above 😃
> Update server options configuration reference

- .changeset/heavy-adults-obey.md
- packages/astro/src/core/app/index.ts
- packages/astro/src/core/app/types.ts
- packages/astro/src/core/build/vite-plugin-ssr.ts
fixes https://github.com/withastro/astro/issues/3298
My TS-fu failed me on this one, so please let me know if the TS/checks can be improved
locally
no docs update needed
> fix: inject script for ssr mode

- packages/astro/src/@types/astro.ts
> Fix GetStaticPathsOptions.* types

- examples/blog/src/components/BaseHead.astro
- https://astro.build/social.jpg does not exist
- https://astro.build/social.png does!
N/A
N/A
> fix: updated blog template with existing address

- packages/integrations/sitemap/src/index.ts
Add config option customPages to be able to add custom URL pages to the sitemap.xml
The change was tested locally.
> Add config option customPages

- .changeset/fast-dancers-watch.md
- packages/integrations/vercel/package.json
Added type definitions manually
> fix(vercel): added type definitions

- packages/astro/package.json
- pnpm-lock.yaml
- Closes #2480
N/A, tested in the compiler
N/A
> Upgrade the compiler

- packages/astro/e2e/multiple-frameworks.test.js
- This is a test change, see below
- Splits up the HMR test into pieces so the entire thing doesn't time out.
N/A, test refinement
> Split up e2e HMR test

- .github/scripts/bundle-size.mjs
- .github/workflows/scripts.yml
- packages/astro/src/runtime/client/idle.ts
- packages/astro/src/runtime/client/load.ts
- packages/astro/src/runtime/client/media.ts
- packages/astro/src/runtime/client/only.ts
- packages/astro/src/runtime/client/visible.ts
- Adds a `scripts.yml` workflow
- Comments on PRs with bundle size change if hydration logic is modified
I added a comment to the hydration scripts in this PR, causing [the bot to comment](https://github.com/withastro/astro/pull/3454#issuecomment-1138698834). 
N/A
> Add bundle-size check action

- packages/astro/src/core/config.ts
Refactor default config values:
- duplicated usage
- no clear overview
- easier overview
- easier change
- easier test refer
Covered by existing tests, there is no operational difference.
N/A
> refactor(config): refactor duplicated default config values

- .changeset/rare-buckets-kneel.md
- packages/astro/src/core/errors.ts
- packages/astro/src/vite-plugin-markdown/index.ts
- Resolves https://github.com/withastro/astro/issues/3527
- Improves YAML error stack traces
**Before**
**After**
No tests, just a DX improvement
N/A
> Improve YAML error handling

- packages/integrations/cloudflare/README.md
This caught me out and pages functions has no logging at the mo so it wasn't super straightforward to work out what was happening.
Wasn't sure wether this was the right place to add a note like this, especially since it wont be the case indefinitely, so feel free to close, just thought it might catch a few others out in the interim.
> feat: update `@astrojs/cloudflare` readme

- GOVERNANCE.md
- Small template change to the message that we send to contributors, based on having just done this. Mostly style changes.
- No vote needed (not a governance change)
- N/A
- N/A
> small change to a nomination message template

- packages/astro/test/astro-markdown.test.js
- Oops, another `it.only` got merged!
N/A
N/A
> Remove it.only

- examples/framework-react/package.json
- pnpm-lock.yaml
- Fix dev  devDependencies @types install location
> chore(example): fix react @types install location

- pnpm-lock.yaml
When I run `pnpm install` on a fresh install, I have this change staged for me on `main`. I've updated pnpm, cleared my `node_modules`, but nothing seems to stop it.
Okay to merge since I assume others are hitting this in their PRs?
> update lockfile on fresh install

- packages/create-astro/src/index.ts
- packages/integrations/prefetch/src/client.ts
- Just fixing CI for external PRs
N/A
N/A
> Fix lint issues

- packages/create-astro/test/install-step.test.js
- Disables `create-astro` test for now
- Need to investigate why this wasn't working
N/A
N/A
> Disable problematic `create-astro` test

- README.md
- The README.md is currently missing the `@astrojs/cloudflare` package.
- This PR adds it (matching the format of the others).
- No tests were modified, docs change only.
- Docs (well, README) was updated with `@astrojs/cloudflare` package and version.
> Added Cloudflare adapter to README.md

- examples/portfolio/src/pages/index.astro
- Very small example fix.
No, example fix.
No, example fix.
> Fix portfolio example to use lowercase srcset

- .changeset/wild-pens-hunt.md
- packages/create-astro/src/index.ts
- packages/create-astro/src/templates.ts
- Small updates as a followup to this
- Provide more guidance to a new or beginner user
> small create-astro wording changes

- packages/integrations/partytown/README.md
Fix to README.md manual import section
No tests required
@astrojs/partytown README.md only I believe
> Fix manual import

- .changeset/giant-bugs-battle.md
- packages/astro/src/core/create-vite.ts
Resolves #3901 
N/A - does not appear in monorepo
N/A
> fix: add github-slugger to ALWAYS_EXTERNAL

- .changeset/strong-squids-hide.md
- packages/astro/src/vite-plugin-env/index.ts
- packages/astro/test/astro-envs.test.js
- packages/astro/test/fixtures/astro-envs/astro.config.mjs
- packages/astro/test/fixtures/astro-envs/src/components/Client.vue
- packages/astro/test/fixtures/astro-envs/src/pages/destructured.astro
- packages/astro/test/fixtures/astro-envs/src/pages/index.astro
- Closes #3711
Test added
N/A, bug fix
> Sets import.meta.env.BASE_URL correctly in dev

- packages/integrations/image/src/types.ts
- packages/markdown/remark/src/remark-shiki.ts
Fix eslint issues. There is no changelog because it does not affect anything but the building/testing process
> ci: fix eslint issues

- .changeset/flat-shoes-camp.md
- Missed a changeset in [#3859](https://github.com/withastro/astro/pull/3859)
N/A
N/A
> Add missing changeset

- examples/basics/package.json
- examples/blog-multiple-authors/package.json
- examples/blog/package.json
- examples/component/demo/package.json
- examples/component/package.json
- examples/docs/package.json
- examples/env-vars/package.json
- examples/framework-alpine/package.json
- examples/framework-lit/package.json
- examples/framework-multiple/package.json
- examples/framework-preact/package.json
- examples/framework-react/package.json
- examples/framework-solid/package.json
- examples/framework-svelte/package.json
- examples/framework-vue/package.json
- examples/integrations-playground/package.json
- examples/minimal/package.json
- examples/non-html-pages/package.json
- examples/portfolio/package.json
- examples/ssr/package.json
- examples/starter/package.json
- examples/subpath/package.json
- examples/with-markdown-plugins/package.json
- examples/with-markdown-shiki/package.json
- examples/with-mdx/package.json
- examples/with-nanostores/package.json
- examples/with-tailwindcss/package.json
- examples/with-vite-plugin-pwa/package.json
- packages/astro/package.json
- pnpm-lock.yaml
- Updates `astro` version to `1.0.0-rc.0`
- Required before https://github.com/withastro/astro/pull/3972
N/A
N/A
> Update `astro` version to `1.0.0-rc.0`

- packages/integrations/cloudflare/test/basics.test.js
- Cloudflare adapter test is causing trouble in CI.
- Disabling for now.
N/A
N/A
> Skip cloudflare CI test

- .changeset/long-bees-promise.md
- packages/integrations/image/README.md
- packages/integrations/image/src/build/ssr.ts
- packages/integrations/image/src/endpoints/prod.ts
- packages/integrations/image/src/utils/images.ts
Fixes a bug that was breaking local image resolution on Windows
All existing tests should pass
Bug fix only
> Fixes local image resolution in SSR builds on Windows

- .changeset/purple-mirrors-smile.md
- packages/astro/src/runtime/server/index.ts
- Fixes #4118
- Use new `stringifyChunk` util in `renderToString` function
Nope, hotfix
Not, hotfix
> Fix [Object object] in MDX output

- packages/integrations/image/README.md
Updated the README of @astrojs/image with a mention of the new env.d.ts file so users coming from the newest templates know what to do
N/A
This is docs!
> Update @astrojs/image README with mention of the new env.d.ts file

- .changeset/empty-bottles-allow.md
- packages/astro/src/core/app/index.ts
- packages/astro/src/core/app/node.ts
- packages/astro/test/ssr-404-500-pages.test.js
- packages/astro/test/test-adapter.js
- When using the 404.astro route, make the status code by 404.
- Closes https://github.com/withastro/astro/issues/4164
- Test added
Bug fix
> Return 404 status code for 404.astro in SSR

- .github/workflows/ci.yml
- Fixes our `CI` action to not cancel anything in progress on `main`
- Does cancel in progress on PRs
We'll see!
N/A
> Do not cancel-in-progress on main

- packages/integrations/image/README.md
n/a
n/a
`intergration` -> `integration`
> Fix spelling mistake in @astrojs/image docs

- .github/workflows/ci.yml
- Might help with our Windows E2E tests? We'll see!
This is that
N/A
> Update CI timeout to 25 mins

- examples/docs/src/components/HeadSEO.astro
- examples/docs/src/components/PageContent/PageContent.astro
- examples/docs/src/components/RightSidebar/RightSidebar.astro
- examples/docs/src/layouts/MainLayout.astro
- Correctly pass `headings` prop to table of contents
- Update `content` to `frontmatter` across layouts to reflect new docs
N/A
Well, it's a docs site right?
> [@examples/docs] Fix table of contents

- examples/blog/src/styles/global.css
> Use auto height on blog template

- README.md
- Fix the typo `offical` to `official`
Manually
N/A
> Fix typo `offical`

- packages/integrations/vercel/README.md
> Running Astro as SSG on Vercel without adapter

- examples/basics/README.md
- update README.md folder structure
- add the missing `layouts` folder
- update `src/components` folder description
Only an example the README.md was changed, no tests should be affected.
Only an example README.md was changed, no docs should be affected.
> chore(basics): update README folder structure

- packages/astro/src/core/build/vite-plugin-css.ts
#4446 add debugger statements that weren't removed. This PR removes it.
(No changeset as it's an internal cleanup)
N/A
N/A
> Remove debugger statements

- packages/integrations/sitemap/README.md
Adds brief explanation and example of filtering multiple pages to Filter section.
> Update Filter Section

- packages/astro/src/vite-plugin-astro/index.ts
> Fix typo in vite-plugin-astro/index.ts

- .changeset/olive-gifts-hope.md
- packages/astro/src/runtime/server/astro-island.ts
Fix #4471 
Remove optional chaining i the `astro-island.ts` file for Safari <13 support
N/A
N/A
> Remove optional chaining in astro-island

- .changeset/angry-peaches-remember.md
This is a changeset for https://github.com/withastro/astro/pull/4313
> Add changeset for @astrojs/react minor

- .changeset/pre.json
- Exits prerelease mode for the 1.1 release.
N/A
N/A
> Exit prerelease mode for 1.1 release

- .changeset/blue-bees-call.md
- packages/astro/package.json
- pnpm-lock.yaml
Just update the dependency to the latest one so `astro check` supports automatically typed `Astro.props`
Tests still work + manual tests
N/A
> Update astro check to use latest version of the language server

- README.md
- Added the new integration `alpinejs` to the main readme file
N/A
N/A
> chore: update readme to include alpine js integration

- .changeset/nice-readers-mix.md
- packages/astro/package.json
Packaging is hard. I forgot to add the file to `files`, oops
N/A
N/A
> Fix import-meta.d.ts not being included in the package

- .changeset/rare-carrots-give.md
- packages/astro/src/core/add/index.ts
Based on Theo stream feedback: Change Add an Adapter -> Add an SSR Adapter
N/A
N/A
> [astro add] Add an Adapter -> Add an SSR Adapter

- README.md
- Adds integrations that are not in the readme, to it.
N/A, just a readme change
> Add missing packages to the readme

- examples/basics/package.json
- examples/basics/src/layouts/Layout.astro
- examples/blog/package.json
- examples/component/package.json
- examples/docs/package.json
- examples/docs/src/components/Header/Header.astro
- examples/docs/src/components/LeftSidebar/LeftSidebar.astro
- examples/docs/src/layouts/MainLayout.astro
- examples/env-vars/package.json
- examples/framework-alpine/package.json
- examples/framework-lit/package.json
- examples/framework-multiple/package.json
- examples/framework-preact/package.json
- examples/framework-react/package.json
- examples/framework-solid/package.json
- examples/framework-svelte/package.json
- examples/framework-vue/package.json
- examples/minimal/package.json
- examples/non-html-pages/package.json
- examples/portfolio/package.json
- examples/ssr/package.json
- examples/subpath/package.json
- examples/with-markdown-plugins/package.json
- examples/with-markdown-shiki/package.json
- examples/with-mdx/package.json
- examples/with-nanostores/package.json
- examples/with-tailwindcss/package.json
- examples/with-vite-plugin-pwa/package.json
- examples/with-vitest/package.json
- pnpm-lock.yaml
Reverts withastro/astro#4544. There was an unfixed merge conflict
> Revert "Update templates to avoid devDependencies and :global"

- .changeset/thick-guests-sell.md
- packages/astro/src/core/build/static-build.ts
- Small change to add a link to learn more on the "missing adapter" error
- Inspired by a user who was stuck on this error message: https://discord.com/channels/830184174198718474/961342615805108326/1014632383112302702
- N/A, so smol
- N/A
> Small polish to the "missing adapter" error message

- packages/integrations/cloudflare/README.md
- packages/integrations/deno/README.md
- packages/integrations/netlify/README.md
- packages/integrations/vercel/README.md
This PR adds each integration's respective deployment guide to its README.
Zero code changes.
Yes.
> Add deploy guides links to integrations READMEs

- packages/create-astro/src/index.ts
- `isThirdParty` was unused. This PR uses it, and removes an unnecessary comment.
This does not affect the behavior of the code.
This does not affect the behavior of the code.
> nit: create-astro unused variable

- .changeset/nice-cameras-hug.md
- packages/astro/package.json
- pnpm-lock.yaml
- Closes https://github.com/withastro/astro/issues/4632
- Test added in the compiler
N/A, bug fix
> Upgrade minimum compiler version

- packages/astro/src/core/create-vite.ts
Quick fix for a small eslint error hitting CI runs
All existing tests should pass
None, linter fix only
> fixes an eslint error

- packages/integrations/vercel/README.md
> Docs Typo fixes

- examples/component/package.json
Does what it says in the title
N/A
N/A
> Add private to `@example/component` to prevent accidental publish

- packages/integrations/node/README.md
- fix Readme typo
No test/code was affected
Fixed typo in readme.
> Update node integration readme [ci skip]

- packages/astro/src/runtime/server/render/head.ts
> Fix typo in render/head.ts

- .github/workflows/snapshot-release.yml
- updates the action to resolve the PR's git ref
N/A
N/A
> Updating snapshot-release.yml GitHub Action

- .eslintrc.cjs
- Fixes some `eslint` annotations that were shown on every PR
N/A, tooling change only
N/A, tooling change only
> Fix `eslint` annotations

- .github/workflows/snapshot-release.yml
- The bot was successful, but [the result output was empty](https://github.com/withastro/astro/pull/4738)
- This fixes that since most of the relevant output is stderr
> Capture stderr in snapshot-release github action

- .changeset/spotty-ways-cry.md
- packages/astro/package.json
- packages/astro/test/astro-scripts.test.js
- packages/astro/test/fixtures/astro-scripts/astro.config.mjs
- packages/astro/test/fixtures/astro-scripts/package.json
- packages/astro/test/fixtures/astro-scripts/src/pages/inline-in-page.astro
- pnpm-lock.yaml
- Upgrades to Vite 3.1
- Fixes https://github.com/withastro/astro/issues/4733
- Test added that replicates the bug in #4733
N/A, bug fix
> Compatiblity between hoisted scripts and tailwind integration

- examples/framework-preact/package.json
- pnpm-lock.yaml
This fixes CI which is currently failing on main.
> Update preact example to match @astrojs/preact ranges

- .github/workflows/ci.yml
- packages/astro/src/core/messages.ts
It turns out that ESLint has never worked on local PRs, this PR fix this! I had to disable the autofix portion of it however, as it complained about some permissions issues that didn't seem fixable 🤔 
N/A
N/A
> Fix ESLint not working in CI

- .changeset/short-ravens-marry.md
- packages/astro/src/cli/index.ts
- packages/astro/src/core/build/static-build.ts
> fix: Can't overwrite vite's MODE environment variable

- examples/ssr/src/pages/api/cart.ts
- examples/ssr/src/pages/api/products/[id].ts
- Update Astro SSR Example to include new API Context
No test needed as it's just a example update
No documentation needed for example
> update SSR example to match recent change on Astro API Context

- packages/integrations/sitemap/README.md
> fixed typing

- examples/docs/src/components/LeftSidebar/LeftSidebar.astro
> fix trailing slash mismatch in dev vs build in docs example

- .github/workflows/benchmark.yml
N/A, just testing this action.
> Build packages in the benchmark action

- .github/workflows/benchmark.yml
- Updating this to provide the PR number so the comment is correctly added.
- This should do it!
> Benchmark action: provide the PR number

- packages/astro/src/@types/astro.ts
Update the TypeScript inference. Actually solving [this](https://github.com/withastro/docs/issues/1643).
No testing needed.
It is concluded [here](https://github.com/withastro/docs/pull/1671).
> Update config base type description

- packages/astro/e2e/fixtures/astro-envs/package.json
- pnpm-lock.yaml
Fix test fail after strict hoisting from #4886
> Fix failing e2e test

- .changeset/wise-worms-add.md
- packages/astro/package.json
- pnpm-lock.yaml
- Just a compiler upgrade which fixes some bugs
> Upgrade Astro compiler to 0.26.0

- examples/ssr/src/pages/index.astro
Closes https://github.com/withastro/astro/issues/4991
> Remove early return from SSR example

- packages/astro/src/@types/astro.ts
- Reverts #4954 (which wasn't approved)
- Documents `base` according to the current behavior, pending #4988
Just docs
Consulted with @sarah11918 and @delucis.
> Correct `base` documentation

- .changeset/sixty-actors-look.md
- packages/integrations/image/src/build/ssg.ts
- packages/integrations/image/test/fixtures/get-image-remote/astro.config.mjs
- packages/integrations/image/test/fixtures/get-image-remote/package.json
- packages/integrations/image/test/fixtures/get-image-remote/src/pages/index.astro
- packages/integrations/image/test/get-image.test.js
- pnpm-lock.yaml
- Closes https://github.com/withastro/astro/issues/4916
- Test added
N/A, bug fix
> Fix remote images in SSG mode

- packages/astro/test/fixtures/ssr-api-route/astro.config.mjs
Fix failing SSR test in main branch
fixed
n/a
> Fix failing SSR test

- .github/workflows/benchmark.yml
- package.json
This reverts commit 9e041f464c97ee96eb8b0c31782f9447a831b141.
This change didn't work :( The shell is working different locally, going to investigate more, but for now this fixes the problem.
> Revert "Improved benchmark output (#5077)"

- .changeset/large-cougars-cough.md
- packages/astro/src/jsx-runtime/index.ts
- packages/astro/test/units/render/jsx.test.js
- Closes https://github.com/withastro/astro/issues/4610
- Added JSX test. Verifies both when there are an array of children and when there is just a single vnode.
N/A, bug fix
> Fixes JSX usage of slots with dashes in their name

- .gitignore
- package.json
> chore: add eslint cache

- .changeset/smart-crabs-pump.md
- packages/integrations/vercel/src/edge/adapter.ts
> fix(vercel): fixed regression #5120

- .prettierignore
- Update comment to point to new issue
- Remove file that no longer needs to be ignored (style tag was moved into head in [#4283](https://github.com/withastro/astro/pull/4283/files#diff-596f6d9d962689a44455508576c0510fd99acfe8ff60c87bd7b7108e472c5c29R40))
Ran `pnpm run format` locally and looked through diffs.
n/a
> `.prettierignore`: update comment pointing to issue

- package.json
- pnpm-lock.yaml
only pnpm is allowed to manage deps
> chore: only-allow pnpm

- packages/integrations/cloudflare/README.md
- light text editing of Cloudflare integration README.
No tests.
Will be mirrored in Docs.
> [docs] Cloudflare integration README edits

- examples/minimal/src/pages/index.astro
A change to our minimal example was mistakenly merged in https://github.com/withastro/astro/commit/ddf2f8390e8dcc64b44636524bdcddae977779f4#diff-1c4f3bd2da2b5ae4e07df62df369f359b73aed95256acb703130d345efed5128
N/A
N/A
> Fix unintentional change to minimal example

- .github/workflows/check-merge.yml
- The mergability workflow would fail some times when there were comments.
- This removes the multiple-step where a string was saved as a result and then attempted to be parsed (the reason for the failure), with an inline JS function that does the same thing.
- Hoping for the best
N/A
> Fix mergability check

- .github/workflows/ci.yml
- Huzzah! Three cheers for @bluwy! 🥳 
- https://github.com/withastro/docs/pull/1895
- https://github.com/withastro/astro/pull/4842
> Remove `shamefully-hoist` from docs smoke test

- packages/webapi/README.md
- Adds a thank you to the original author of the webapi package that ours is forked from. 
- Licensing requirements have always been met (CCO specifically gives no conditions to reuse) but this can also be good form.
- Readme only.
- N/A
> Add a thank you to the original author of the original webapi package

- packages/integrations/cloudflare/README.md
Minor improvements and an additional link to the cloudflare functions documentation.
No tests, only changes to documentation.
Yes!
Note: was unsure whether or not I would include a changeset? I checked other recent documentation pr's and chose the same path (no changeset). If this is fine, let me know and I can make a PR against the PR template to clarify this.
> [docs] cloudflare `directory` nits

- .changeset/witty-bobcats-eat.md
- packages/create-astro/create-astro.mjs
- packages/create-astro/package.json
- packages/create-astro/src/index.ts
- pnpm-lock.yaml
- Fixes a few bugs mentioned in [#5227](https://github.com/withastro/astro/issues/5227)
- Upgrades `@astrojs/cli-kit` to latest (fixes `setRawMode` issue)
- Always respect `--skip-houston` flag
N/A, bug fix
> `create-astro` bug fixes

- examples/framework-lit/src/pages/index.astro
- Fixes failing `astro-check` workflow on main
N/A, type fix only
N/A, type fix only
> @ts-check issue on `main`

- packages/integrations/image/test/fixtures/basic-image/src/pages/index.astro
- packages/integrations/image/test/fixtures/basic-picture/src/pages/index.astro
- packages/integrations/image/test/image-ssg.test.js
- packages/integrations/image/test/image-ssr-build.test.js
- packages/integrations/image/test/image-ssr-dev.test.js
- packages/integrations/image/test/picture-ssg.test.js
- packages/integrations/image/test/picture-ssr-build.test.js
- packages/integrations/image/test/picture-ssr-dev.test.js
- Just tests
- Breaking in main because dev is more strict about `base` now. Not sure why the PR wasn't failing that caused this.
N/A
> Fix the image tests

- packages/astro/src/runtime/server/jsx.ts
- Failing on main, this fixes it.
- vnodes might be things like URLs (huh), so be more careful in the logic here.
- Fixes existing test
- See https://github.com/withastro/astro/actions/runs/3434015781/jobs/5724954188
N/A
> Fixes failing mdx test

- examples/docs/src/components/Header/Search.css
The `display: none` is Repeated
> fix(template): delete extra css.

- .changeset/loud-penguins-tickle.md
- packages/astro/src/core/build/css-asset-name.ts
https://github.com/withastro/astro/issues/5400
> Fix: https://github.com/withastro/astro/issues/5400

- packages/integrations/deno/README.md
> doc: fix deno preview command

- .github/workflows/benchmark.yml
- Need to pipe stderr to the file as there is where the results are printed
- just locally
N/A
> Fix bench workflow

- README.md
Separates the recommended and manual install commands for ease of copying.
No tests were added as only the README was changed.
No docs were updated as only the README was changed.
> Improve README install guide

- .changeset/itchy-laws-smile.md
- packages/astro/src/vite-plugin-head-propagation/index.ts
- Closes https://github.com/withastro/astro/issues/5620
N/A
> Fix "maximum call stack size exceeded" error

- .changeset/config.json
- Use experimental feature compatible with not bumping peerDependencies.
N/A
N/A
> Remove astro peerDep from adapters

- packages/astro/src/core/render/result.ts
For some reason this was not caught in PR, but is failing in main.
> Fix missing ts flag on main

- examples/with-tailwindcss/README.md
- update broken link to latest relevant astrojs/tailwind link
- minor fix, no tests needed
- no new docs needed.
> fix broken link in tailwind example docs

- .changeset/kind-beers-give.md
- packages/astro/test/fixtures/lit-element/src/pages/slots.astro
- packages/astro/test/fixtures/lit-element/tsconfig.json
- packages/astro/test/lit-element.test.js
- packages/astro/test/ssr-lit.test.js
- packages/integrations/lit/package.json
- packages/integrations/lit/server.js
- pnpm-lock.yaml
- As requested, the PR from the `1-legacy` branch into `main`.
- This fixes #5475
- See #5776 
- See #5776 
Nope
> [@astrojs/lit] Fix slotted content into main

- packages/astro/env.d.ts
> Fix broken link in comments

- README.md
> Fix link to @astrojs/solid-js changelog

- .changeset/eleven-bulldogs-provide.md
- packages/astro/src/cli/index.ts
- packages/astro/src/core/dev/dev.ts
Pass `flags` to `dev` to close https://github.com/withastro/astro/issues/5799
> fix: pass flags to dev

- .changeset/spicy-tips-dream.md
- @delucis had some great suggestions for https://github.com/withastro/astro/pull/5842, but I merged too soon!
N/A
N/A
> Update changeset for `_astro` directory

- .changeset/three-comics-share.md
- packages/astro/package.json
- pnpm-lock.yaml
- Fixes #5907 by updating the compiler to 1.0.1 and including @matthewp's fix
n/a
n/a, bugfix
> Update compiler to 1.0.1

- README.md
- This PR aims to add alt text for the images that are provided in the README.md file.
N/A
N/A
> Add alt text for images in README

- .changeset/pre.json
- Exits pre-mode which will trigger changesets to create a release PR for 2.0.
N/A
N/A
> Exit pre-mode for 2.0 release

- .changeset/pre.json
- @FredKSchott wants to do one last beta.
N/A
N/A
> Go back to pre-mode

- .changeset/pre.json
- Exit pre-mode for 2.0 release (again)
N/A
N/A
> Exit pre mode

- .changeset/chatty-rivers-camp.md
- .changeset/kind-beers-give.md
> Bump lit changesets to minor

- .changeset/angry-cups-hug.md
- packages/create-astro/src/index.ts
- Fix TypeScript handling bug
N/A
> fix(create-astro): typescript prompt handling

- packages/integrations/svelte/README.md
Include "Added in" in `Intellisense for TypeScript` section
See https://github.com/withastro/docs/pull/2451 for more information
> docs(svelte): Update integration README

- packages/integrations/mdx/README.md
Typo fix in the MDX integration README
No tests.
Just docs!
> [docs] typo fix in MDX README

- examples/basics/.gitignore
- examples/basics/README.md
- examples/deno/README.md
- examples/docs/README.md
- examples/docs/package.json
- examples/hackernews/package.json
Diffing directories in examples to look for outdated files
This doesn't change functionality, only fixing configs and docs.
> Make examples more consistent

- packages/astro/CHANGELOG.md
- Updates changelog for Astro 2.0.2!
N/A
N/A
> fix error in changelog formatting

- .changeset/gentle-weeks-lie.md
- packages/astro/client-base.d.ts
Fix #6021
Simple type correction, no tests needed
This fixes a type error, no docs needed
> Remove outdated MDX import types

- .changeset/shaggy-gifts-beg.md
- packages/integrations/node/src/http-server.ts
- fixes https://github.com/withastro/astro/issues/6087
- more details: https://github.com/withastro/astro/issues/6087
- tested with the examples at my local
N/A, bug fix
> Fix incorrent encoded when path has other language characters

- .changeset/green-penguins-tease.md
- packages/integrations/netlify/package.json
- pnpm-lock.yaml
- Fixes https://github.com/withastro/astro/issues/6086
N/A
N/A
> Move @netlify/functions to be a dep

- .changeset/breezy-scissors-attack.md
- packages/integrations/preact/package.json
- pnpm-lock.yaml
- Fixes https://github.com/withastro/astro/issues/6098
N/A
N/A
> Upgrade preact's dependencies to fix security issue

- .changeset/grumpy-cameras-own.md
- packages/integrations/vercel/README.md
- Fix formatting of option details to use separate lines instead of a blockquote
- Add the version `analytics` support was added
n/a
> Vercel adapter README tweaks

- CONTRIBUTING.md
- Update minimum version of pnpm in CONTRIBUTING.md from 7.5.0 to 7.9.5.
- Based on [this line](https://github.com/withastro/astro/blob/bf3aa2bcdefb99df3787fe043fac301ef84fe98d/package.json#L44) in package.json.
N/A because this is just a markdown update
N/A because this is just a markdown update
> Update pnpm version from 7.5.0 to 7.9.5

- packages/create-astro/README.md
> docs: Update `create-astro` README.

- .changeset/gold-months-live.md
- packages/astro/src/core/build/plugins/plugin-ssr.ts
- packages/integrations/deno/src/code-constant.ts
- packages/integrations/deno/src/index.ts
- packages/integrations/deno/src/server.ts
- packages/integrations/deno/test/basics.test.ts
- packages/integrations/deno/test/fixtures/basics/src/pages/perendering.astro
This reverts commit ef5cea4dc5c4ffa33bd57ea0886e6912afb24fec.
- Fixes https://github.com/withastro/astro/issues/6270
N/A
N/A
> Revert "Deno fix #6131 (#6248)"

- .devcontainer/basics/devcontainer.json
- .devcontainer/blog/devcontainer.json
- .devcontainer/component/devcontainer.json
- .devcontainer/deno/devcontainer.json
- .devcontainer/docs/devcontainer.json
- .devcontainer/framework-alpine/devcontainer.json
- .devcontainer/framework-lit/devcontainer.json
- .devcontainer/framework-multiple/devcontainer.json
- .devcontainer/framework-preact/devcontainer.json
- .devcontainer/framework-react/devcontainer.json
- .devcontainer/framework-solid/devcontainer.json
- .devcontainer/framework-svelte/devcontainer.json
- .devcontainer/framework-vue/devcontainer.json
- .devcontainer/hackernews/devcontainer.json
- .devcontainer/integration/devcontainer.json
- .devcontainer/minimal/devcontainer.json
- .devcontainer/non-html-pages/devcontainer.json
- .devcontainer/portfolio/devcontainer.json
- .devcontainer/ssr/devcontainer.json
- .devcontainer/with-markdown-plugins/devcontainer.json
- .devcontainer/with-markdown-shiki/devcontainer.json
- .devcontainer/with-mdx/devcontainer.json
- .devcontainer/with-nanostores/devcontainer.json
- .devcontainer/with-tailwindcss/devcontainer.json
- .devcontainer/with-vite-plugin-pwa/devcontainer.json
- .devcontainer/with-vitest/devcontainer.json
Sets unique name per example app devcontainer for enhanced usability.
N/A
Docs-only change.
> Update devcontainer names

- packages/integrations/image/README.md
- Fix the markdown diff for adding Sharp
No tests, markdown fix
Docs updated 👍
> fix: sharp image configure diff

- examples/with-markdoc/package.json
- Update the markdoc integration version
N/A
N/A
> Update with-markdoc example

- packages/astro/performance/fixtures/mdoc/package.json
- packages/integrations/markdoc/package.json
- pnpm-lock.yaml
Reset back to 0.0.0 and update the lockfile.
> Fix markdoc version

- .github/workflows/format.yml
> ci: format add owner judgment

- .changeset/flat-baboons-nail.md
- packages/astro/src/content/types-generator.ts
- packages/astro/test/units/content-collections/frontmatter.test.js
- packages/astro/test/units/test-utils.js
- Closes https://github.com/withastro/astro/issues/6587
- Unit test added
N/A, bug fix
> Prevent frontmatter errors from crashing dev server

- packages/integrations/tailwind/README.md
See also: https://github.com/withastro/docs/pull/2987
Fixed links in TailwindCSS section
No tests necessary
> Fix broken links in TailwindCSS section

- examples/framework-react/README.md
- Update an example link to use the new React docs https://github.com/withastro/astro/pull/6756#issuecomment-1497664223
N/A
N/A
> Update link to use new React docs

- .github/ISSUE_TEMPLATE/---01-bug-report.yml
Updates note on *minimal example* with link to creating minimal examples on the astro docs: https://docs.astro.build/en/guides/troubleshooting/#creating-minimal-reproductions
Not really tested
No docs needed, since this is a ref to docs
> Update issue template with link

- packages/integrations/sitemap/package.json
- pnpm-lock.yaml
> chore: update `xml2js` version

- packages/integrations/vercel/README.md
Currently using rewrite with static files works but server rendered files with either edge or serverless function don't get rewritten. See: https://github.com/withastro/astro/issues/6446
Vercel integration doc update
N/A
N/A
> Added a caution about rewrites only working for static files

- .changeset/hungry-lizards-float.md
- packages/integrations/vercel/src/static/adapter.ts
- Refactored static adapter setup to use updateConfig
- Added changeset
- Ran unit tests
- No externally facing changes are present.
> Align adapter setup

- packages/astro/src/core/build/generate.ts
- packages/astro/src/core/build/plugins/plugin-ssr.ts
Clean up code, don't need a changeset I think.
> chore: cleanup code

- .changeset/polite-pears-kneel.md
- packages/astro/package.json
- packages/integrations/node/package.json
- packages/telemetry/package.json
- packages/webapi/package.json
- pnpm-lock.yaml
Bump undici to hopefully reduce the `fetch failed` errors that sometimes happen in CI.
n/a
> Upgrade undici to v5.22.0

- .changeset/red-crabs-cross.md
- packages/astro/test/fixtures/ssr-prerender/src/pages/not-prerendered.astro
- packages/astro/test/ssr-prerender-integrations.test.js
> Implement tests for integrations mutating prerendering

- packages/astro/src/@types/astro.ts
- Just a docs fix
N/A
Updated the `@version` to the accurate version this feature is released.
> Fixed scopedStyleStrategy version

- .changeset/pretty-bears-deliver.md
This updates the changeset of the middleware APIs
N/A
N/A
> chore: update middleware changeset

- packages/astro/src/@types/astro.ts
- The description is in the wrong place, causing the docs repo not to build.
N/A
👆
> Fix scopedStyleStrategy description

- .changeset/two-carrots-smile.md
- packages/astro/types.d.ts
Uncomment the Polymorphic type helper now that the language-server reached 1.0.0 officially
No tests for type helpers, we test the feature itself in the compiler and language-server though
https://github.com/withastro/docs/pull/3263
> feat: uncomment polymorphic type

- packages/astro/src/core/config/schema.ts
Seems like this is the only change that's causing the tests to fail.
Don't think it needs a changeset as it fixes an unreleased feature.
Ran the test locally and passes
n/a. bug fix.
> Fix customClientDirectives config default typo

- packages/integrations/markdoc/src/extensions/shiki.ts
The organize imports messed up the comments, and the build failed.
N/A
N/A
> fix: formatting comment

- .github/workflows/check-merge.yml
- Updates our `check-merge` action
Merge and hope is all we can do.
N/A
> Fix `semver minor` action

- .github/workflows/check-merge.yml
- Fixes script logic bug that allowed multiple blocking review comments to be left
Tested manually on my fork of `astro`
N/A
> Fix duplicate `semver minor` blocks

- .changeset/cool-readers-stare.md
- packages/integrations/lit/hydration-support.js
- packages/integrations/lit/package.json
- pnpm-lock.yaml
- Closes https://github.com/withastro/astro/issues/7230
N/A
N/A
> Upgrade lit deps

- packages/integrations/node/README.md
Closes https://github.com/withastro/astro/issues/6335
N/A
> docs: add snippet for `base` option

- .github/workflows/main.yml
- Removes inputs which are no longer needed since withastro/automation#1
- Adds some custom emoji to the Astro repo for ✨ _personality_ ✨ 
Not tested, but should work and low risk if it doesn’t? (I won’t get congratulated 😓)
No docs needed.
> Update congrats workflow for latest version

- .changeset/sweet-ducks-own.md
- packages/astro-rss/package.json
- packages/astro/package.json
- pnpm-lock.yaml
- Bumps `semver` and `fast-xml-parser` dependencies for `astro` and `@astrojs/rss`.
- Ran tests
N/A
> Bump dependency versions

- .changeset/long-geckos-battle.md
- packages/astro/src/core/endpoint/index.ts
- packages/astro/src/core/middleware/index.ts
Tiny change. For more context, the the PR https://github.com/withastro/astro/pull/7492
I manually checked if the compiled code exports the new API
Not needed for now
> feat: export a new api called `createContext`

- examples/portfolio/src/components/Nav.astro
The portfolio example is failing because of https://github.com/withastro/compiler/issues/814
Not sure what's going on with a brief look, making a quick fix for now to have CI passing.
Ran `pnpm test:check-examples` locally.
n/a
> Temporary fix for examples check

- .changeset/sour-snakes-wonder.md
- packages/create-astro/src/actions/dependencies.ts
- minor grammatical error i guess. 
- corrected the message.
It was like this : `Dependencies installing with ${ctx.pkgManager}...`,
I made it like this: `Installing dependencies with ${ctx.pkgManager}...`,
> corrected grammar. minor change

- packages/integrations/cloudflare/README.md
- docs(cloudflare): fix code snippet in enabling preview
> docs(cloudflare): fix code snippet in enabling preview

- packages/astro/src/core/render/README.md
Document the different rendering concepts and flows in the codebase to help with reading the codebase.
Open to:
1. What do you think is missing?
2. Is there any part is confusing?
3. Is the information incorrect?
n/a
Definitely need docs feedback!
> Document codebase rendering concepts

- .changeset/fluffy-timers-remain.md
- packages/astro/src/assets/services/service.ts
- packages/astro/src/assets/services/sharp.ts
- packages/astro/src/assets/services/squoosh.ts
- packages/astro/src/assets/types.ts
- packages/astro/src/assets/utils/emitAsset.ts
- packages/astro/src/assets/utils/metadata.ts
As the title says
Fix https://github.com/withastro/astro/issues/7304
N/A
> fix(assets): Fix images not following EXIF rotation

- packages/astro/src/assets/services/squoosh.ts
Damn, those paths got hands
I tested manually, a bunch this time.
N/A
> fix(squoosh): Fix wrong file path in rotation check

- packages/integrations/sitemap/README.md
This reverts commit 9352ac65f4d8c44a5d0cf9cccc37a1196da538cf.
- Reverts an errantly merged PR
N/A
- Discussed on discord and docs team didn't want to merge this one.
> Revert "Clarify SSR limitations of sitemaps of dynamic routes (#7625)"

- .changeset/shy-garlics-join.md
- packages/astro/src/assets/index.ts
- packages/astro/src/content/runtime-assets.ts
I'm not sure why this fixes it, but it does, sorry @bluwy  
Fix https://github.com/withastro/astro/issues/7407
Tested manually, both in local and actually on Vercel
N/A
> fix(assets): Remove Node deps from index of assets

- packages/astro/src/transitions/index.ts
- Missed a type import
- Fixes CI
Builds locally
N/A
> Fix ts error on `main`

- packages/astro/src/transitions/index.ts
Same as https://github.com/withastro/astro/pull/7723, got dropped on `main`
No
No
> Fix TS error (again)

- packages/astro/src/transitions/index.ts
- Main's build is breaking due to this. I have no idea how this could have happened.
N/A
N/A
> Import missing TransitionAnimationPair

- .changeset/orange-badgers-fly.md
- packages/astro/astro-jsx.d.ts
What the title says
Fix https://github.com/withastro/language-tools/issues/610
N/A
N/A
> Fix missing `referrerpolicy` attribute on script tags

- packages/integrations/markdoc/README.md
Tries again to invoke the correct GitHub aside syntax
No tests.
Only docs!
> [docs] Markdoc README

- examples/basics/README.md
> Update README.md with new image

- examples/blog/src/pages/blog/[...slug].astro
- examples/portfolio/src/pages/work/[...slug].astro
Fixes build not passing
CI should pass
N/A
> Remove support for Node 16 (#7780)

- .changeset/plenty-bats-shake.md
- packages/astro/src/vite-plugin-astro-server/route.ts
Closes https://github.com/withastro/astro/issues/7752
I tested locally using a project. I tried to create a test, but the testing suite is not suitable for this case, it seems.
N/A
> fix: dev server should redirect when a page doesn't exist

- packages/integrations/node/README.md
I removed the broken link in line 191 in the node adapter section
> [docs] removed the broken link and revised the content

- .changeset/honest-moose-type.md
- packages/integrations/netlify/README.md
~~Removes~~ updates an old link to browse projects on GitHub that didn't work.
Tested with love
It is all about us 😝
> Update old link from `@astrojs/netlify` README

- .github/workflows/release.yml
As per title.
Merge and see if a new PR pops up!
N/A
> ci: enable pre releases for Astro 3.0

- packages/integrations/cloudflare/package.json
- packages/integrations/netlify/package.json
- pnpm-lock.yaml
I forgot to update two more packages
> chore: use workspace packages

- scripts/smoke/check.js
For some reason sometimes `.config` is undefined.
Run it locally, it works!
N/A
> chore: fix issue in the check.js script

- examples/blog/src/content/blog/markdown-style-guide.md
- Update path to image in public/ to suppress warning (`files in the public directory are served at the root path. ...`)
Ran the blog example locally and confirmed that the warning disappeared and the appearance of the page did not change
N/A because this is an update of example
> Update path to image in public/ to suppress warning

- .changeset/fast-penguins-sleep.md
- packages/integrations/vercel/src/lib/nft.ts
- Closes https://github.com/withastro/astro/issues/7564
- Tested with the provided example app
N/A, bug fix
> Prevent Vercel NFT from scanning /dev

- packages/integrations/netlify/README.md
> docs(netlify): remove comma

- examples/with-markdoc/src/pages/index.astro
- Closes https://github.com/withastro/astro/issues/8008, plt-790
- Switch from `getEntryBySlug` to `getEntry`.
Ran example manually, still works!
N/A
> Update example to use `getEntry`

- packages/integrations/netlify/README.md
- updates deprecated options, to the new ones
N/A
Only docs change
> chore: update codesamples for Netlify v3 adapter

- packages/integrations/vercel/README.md
- updates deprecated options, to the new ones
N/A
Only docs change
> chore: update codesamples for Vercel v3 adapter

- .changeset/fair-eyes-promise.md
- https://github.com/withastro/astro/pull/7924 should have had a changeset for `@astrojs/mdx` since that changed as well.
- This adds the changeset.
- Just a changeset.
N/A
> Add missing mdx changeset

- .changeset/smart-numbers-shout.md
- Called it `patch` originally because I wasn't sure if it would go from 3 to 4.
> changeset(next): inlineStylesheets default switch is major

- .changeset/kind-bears-pretend.md
- packages/integrations/react/package.json
- Closes https://github.com/withastro/astro/issues/8135
- Adds missing export
Manually
> Add missing export to react integration

- .changeset/angry-dogs-shake.md
- packages/astro/src/core/polyfill.ts
What the title says
We'll see!
N/A
> fix: polyfill File using undici instead of node:buffer

- .changeset/early-owls-attend.md
- packages/integrations/react/package.json
- Fixes https://github.com/withastro/astro/issues/8135
N/A
N/A
> Fix missing package file regression

- packages/astro/src/@types/astro.ts
Updates the default value in the config file to match the description. Also tightens up the `attribute` description.
No tests, only docs
Just docs!
> [docs] update scopedStyleStragegy default and description

- packages/integrations/markdoc/package.json
- Changes version to not be `1.0`, was decided that it's not ready.
> Change version of @astrojs/markdoc

- .changeset/curvy-experts-jog.md
- .changeset/pre.json
Updated versions to trigger an RC release.
> RC Release candidate

- .changeset/serious-waves-fry.md
- packages/astro/package.json
- packages/astro/test/0-css.test.js
- pnpm-lock.yaml
As per title.
I updated a test case by removing the workaround.
Are docs needed somewhere?
> feat: style scoped hash is lowercase

- packages/astro/src/core/config/schema.ts
- packages/astro/test/units/config/config-validate.test.js
Related to: https://github.com/withastro/astro/pull/8152
Just updating the error message with the suggested one. 
n/a
n/a
> Update config error message for `outDir` infinity loop error

- .changeset/gorgeous-kiwis-stare.md
- packages/astro/src/config/index.ts
> Use .js to import logger

- packages/create-astro/src/actions/context.ts
- packages/create-astro/src/actions/intro.ts
- Very important change to make `create-astro` fancier
- Just a lil' 🥚
Manual
No, that's the point of an 🥚
> Make create-astro fancier

- .changeset/strange-peas-agree.md
- packages/astro/src/cli/install-package.ts
Fix https://github.com/withastro/astro/issues/8230
Tested manually, our tests should also still pass!
N/A
> fix: require.resolve call not finding @astrojs/check

- .changeset/chatty-houses-mate.md
- Deprecates the image integration
N/A
N/A
> Image integration deprecation

- .changeset/fair-berries-study.md
- packages/telemetry/src/config.ts
- Catch and ignore error when `JSON.parse` would fail
- Quick fix
Nah
Also nah
> Wrap `JSON.parse` in `try`/`catch`

- .changeset/flat-cows-own.md
- packages/astro/components/index.ts
Fix https://github.com/withastro/astro/issues/8364
N/A
> fix: tsc complaining about astro imports again

- .changeset/many-mayflies-punch.md
- packages/astro/src/core/build/generate.ts
Fix typo in https://github.com/withastro/astro/pull/8357
No tests, typo change.
No docs changes, typo change.
> fix: remove double `}`

- benchmark/bench/render.js
> Fix benchmark import path

- benchmark/bench/render.js
> fix: remove duplicate import

- examples/blog/src/pages/rss.xml.js
- examples/non-html-pages/src/pages/about.json.ts
- examples/ssr/src/pages/api/cart.ts
- examples/ssr/src/pages/api/products.ts
- examples/ssr/src/pages/api/products/[id].ts
- Update examples
- Uppercase endpoint HTTP methods
- Update response to `new Response()`
> Update examples & uppercase endpoints & fix response

- packages/astro/src/@types/astro.ts
- enviroment -> environment
Fixed typo.
> refactor: fix typo in astro.ts

- .changeset/lovely-shoes-scream.md
- packages/integrations/cloudflare/README.md
Updates one straggling `get` to `GET`
No tests, docs.
Only docs.
> [docs] Typo fix in Cloudflare README

- .changeset/spotty-tools-rhyme.md
- packages/astro/src/@types/astro.ts
Reflect the change made in #8266.
Types changed only.
N/A
> fix(types): make `image.service` optional

- .github/workflows/cleanup-cache.yml
Spent some time figuring it out, looks like there's an action we can use to do this.
n/a. I think it should work.
n/a.
> Clear caches older than 5 days

- .changeset/gold-weeks-hammer.md
- packages/astro/src/core/build/generate.ts
- packages/astro/test/redirects.test.js
Closes https://github.com/withastro/astro/issues/8493
I added a new test case
N/A
> fix: minify HTML for redirects when emitted as HTML files

- .changeset/five-doors-love.md
> chore: do a minor for avif support

- .changeset/five-doors-love.md
> chore: revert avif change

- packages/create-astro/README.md
> chore(create-astro): Remove npm 6.x note

- .changeset/eighty-trainers-accept.md
- packages/astro/src/runtime/server/scripts.ts
> fix: islands are not being rendered correctly

- .changeset/loud-badgers-exercise.md
- packages/integrations/tailwind/README.md
Renamed a 404 page (file ending in cjs) to a valid one.
* rename https://github.com/withastro/astro.build/blob/main/tailwind.config.cjs ⚠️ 
* to https://github.com/withastro/astro.build/blob/main/tailwind.config.ts 🆗 
> Tailwind configuration file changed from `cjs` to `ts`

- .changeset/two-jeans-serve.md
- packages/astro/src/core/build/generate.ts
> fix: redirect page type icon not properly displayed

- packages/astro/e2e/fixtures/view-transitions/src/pages/four.astro
- packages/astro/e2e/view-transitions.test.js
added e2e test
no changeset
yes :)
n/a
> test: since we check the media-type, data-astro-reload has fewer use cases

- packages/integrations/node/README.md
This changes the Node.js README to be consistent and fixes a broken link, see: https://github.com/withastro/docs/pull/4755
No.
Docs? I am the docs.
> Fix subheading inconsistency

- packages/integrations/alpinejs/README.md
Small update to change our Expressive Code to use `diff`'s instead of languages
> Update codesample for Alpine README

- packages/integrations/alpinejs/README.md
- packages/integrations/cloudflare/README.md
- packages/integrations/lit/README.md
- packages/integrations/markdoc/README.md
- packages/integrations/mdx/README.md
- packages/integrations/node/README.md
- packages/integrations/partytown/README.md
- packages/integrations/preact/README.md
- packages/integrations/prefetch/README.md
- packages/integrations/react/README.md
- packages/integrations/sitemap/README.md
- packages/integrations/solid/README.md
- packages/integrations/svelte/README.md
- packages/integrations/tailwind/README.md
- packages/integrations/vercel/README.md
- packages/integrations/vue/README.md
Updates all the README's of the integrations to new expressive code features / generalise them
> update all the readme's for expressive code

- packages/integrations/cloudflare/README.md
> fix(cloudflare): broken link in docs

- .changeset/funny-cobras-accept.md
- .changeset/hot-readers-live.md
- .changeset/yellow-kiwis-pretend.md
- packages/integrations/cloudflare/README.md
- packages/integrations/cloudflare/src/index.ts
- packages/integrations/cloudflare/src/utils/parser.ts
- packages/integrations/cloudflare/test/cf.test.js
- packages/integrations/cloudflare/test/fixtures/cf/src/pages/caches.astro
- packages/integrations/cloudflare/test/fixtures/cf/src/pages/do.astro
- packages/integrations/cloudflare/test/fixtures/cf/src/pages/index.astro
- packages/integrations/cloudflare/test/fixtures/cf/src/pages/kv.astro
- packages/integrations/cloudflare/test/fixtures/cf/wrangler.toml
- **new:** local mocking for KV bindings
- added tests for KV
> feat(cloudflare): add local mocking for KV bindings

- .changeset/funny-cobras-accept.md
- .changeset/hot-readers-live.md
- .changeset/khaki-toes-exercise.md
- .changeset/yellow-kiwis-pretend.md
- packages/integrations/cloudflare/README.md
- packages/integrations/cloudflare/src/index.ts
- packages/integrations/cloudflare/src/utils/parser.ts
- packages/integrations/cloudflare/test/cf.test.js
- packages/integrations/cloudflare/test/fixtures/cf/src/pages/caches.astro
- packages/integrations/cloudflare/test/fixtures/cf/src/pages/do.astro
- packages/integrations/cloudflare/test/fixtures/cf/src/pages/index.astro
- packages/integrations/cloudflare/test/fixtures/cf/src/pages/kv.astro
- packages/integrations/cloudflare/test/fixtures/cf/src/pages/r2.astro
- packages/integrations/cloudflare/test/fixtures/cf/wrangler.toml
- **new:** local mocking for R2 bindings
- added tests for R2
> feat(cloudflare): add local mocking for R2 bindings

- .github/workflows/release.yml
> Fix git tag release

- .github/workflows/snapshot-release.yml
Fix snapshot release commenting task
n/a
n/a
> Fix snapshot release permissions

- packages/integrations/cloudflare/README.md
port over https://github.com/withastro/docs/pull/4980
> port https://github.com/withastro/docs/pull/4980

- .changeset/great-eyes-rest.md
- packages/astro/src/cli/add/index.ts
> fix: Unexpected token < in JSON at position 1 

- .github/workflows/snapshot-release.yml
- fixes snapshot release expression matching
> fix: snapshot release workflow

- .github/workflows/snapshot-release.yml
- fixes main branch not found
- tested on the adapters repo: https://github.com/withastro/adapters/pull/34
> fix: snapshot release main branch not found

- examples/ssr/src/pages/api/products/[id].ts
Fixing the typo
- Fixing typo, use the right variable
> Update [id].ts - Fixing typo

- README.md
The code has moved to the withastro/adapters repo so it broke the changelog link. Updated the new location in two places.
- README.md CHANGELOG link and repo link.
Tested via Preview and clicked links.
This is a documentation update.
> Update new location of @astrojs/cloudflare to adapters repo.

- .prettierignore
- examples/ssr/src/pages/login.astro
- packages/astro-rss/README.md
- packages/astro/CHANGELOG.md
- packages/integrations/node/CHANGELOG.md
- packages/integrations/vercel/CHANGELOG.md
- packages/integrations/vue/CHANGELOG.md
- packages/integrations/vue/README.md
Since https://github.com/withastro/astro/pull/8721, the examples smoke test is failing. This fixes it.
(I didn't really look into why it's happening, just fixed the type issue it reported.)
Ran `pnpm test:check-examples` locally
n/a
> Fix examples smoke test fail

- .changeset/forty-eggs-raise.md
- packages/integrations/partytown/src/index.ts
- #8760
N/A
Changeset cc @sarah11918
> fix(partytown): allow overriding the lib option (close #8760)

- packages/astro/src/@types/astro.ts
- packages/astro/src/content/runtime.ts
- packages/astro/src/content/vite-plugin-content-assets.ts
- packages/astro/src/content/vite-plugin-content-virtual-mod.ts
- packages/astro/src/core/build/plugin.ts
- packages/astro/src/core/build/plugins/plugin-content.ts
- packages/astro/src/core/build/static-build.ts
- packages/astro/src/core/config/schema.ts
- Adds `experimental.contentCollectionCache` to config
- Needs a changeset
TBD
TBD
> Add `experimental.contentCollectionCache` config option

- examples/view-transitions/src/pages/movies/[id].astro
- This was previously working around a bug with `getDataEntryById` that is no longer present.
- Tested the example
N/A
> Fix ViewTransitions example

- .changeset/cuddly-walls-remember.md
- packages/underscore-redirects/src/astro.ts
- fixes a regression I introduced in #8953
- @florian-lefebvre actually asked about it, but I was not getting it.. my bad.
- still no testing, issue to add it is https://github.com/withastro/astro/issues/8960
- Changeset
> fix(underscore-redirects): fix dynamic pattern regression

- .changeset/odd-mayflies-dress.md
Removes empty changeset from https://github.com/withastro/astro/pull/8974
N/A
N/A
> Remove empty changeset

- packages/astro/src/@types/astro.ts
> fix(config types): routingStrategy is optional

- .changeset/blue-mice-hide.md
- packages/astro/src/@types/astro.ts
Updates some outdated docs that weren't changed at the final moment
no tests
only docs!
> [docs] hotfixes to i18n config-ref

- .changeset/little-deers-glow.md
- packages/astro/src/core/logger/node.ts
What the title says. The code for it was removed by accident.
Meh, it's a small fix
N/A
> fix(logging): Fix --verbose flag not working

- .changeset/grumpy-cobras-attend.md
- packages/astro/src/core/render/route-cache.ts
- packages/astro/src/core/routing/manifest/create.ts
- packages/integrations/sitemap/test/fixtures/static/astro.config.mjs
- packages/integrations/sitemap/test/fixtures/static/src/pages/[lang]/manifest.ts
- packages/integrations/sitemap/test/staticPaths.test.js
Closes https://github.com/withastro/astro/issues/9041
Closes https://github.com/withastro/astro/issues/9040
The issue comes from a naive refactor of mine when coding i18n stuff.
I reverted the code.
I added a new test that failed at the beginning, and now it passes
N/A
> fix: regression when calculating params and pattern

- packages/astro/src/transitions/router.ts
> Fix typo in router.ts

- .changeset/calm-ducks-divide.md
- packages/integrations/react/server.js
- Fixes "ERROR: Could not resolve "stream"" when using cloudflare pages with react by using the prefixed package with "node:"
- See also: https://github.com/withastro/astro/pull/8564/files#diff-a74615b421da488d5e2bcf3e14c80732c192a374f51901a2064b3e2caef9d529
Ran it on a cloudflare env with node enabled.
Already exist here: https://docs.astro.build/de/guides/integrations-guide/cloudflare/#nodejs-compatibility
> Add compatibility with cloudflare node

- packages/astro/test/i18n-routing.test.js
Closes https://github.com/withastro/astro/issues/9095
The issue is already fixed in `main`, but I wanted to create a PR to add a new test case, to avoid regressions in the future.
Added new test case
N/A
> fix: test case for #9095

- .changeset/pretty-ducks-hang.md
- Changeset only, no code changes
N/A, no code changes
- https://github.com/withastro/docs/pull/5426
> Move the Picture component out of experimental

- .changeset/tasty-parents-own.md
- packages/astro/src/runtime/client/dev-overlay/plugins/settings.ts
> Add instructions on how to hide the dev overlay

- .changeset/silent-phones-divide.md
- packages/astro/package.json
- packages/astro/src/runtime/client/dev-overlay/plugins/audit/a11y.ts
- pnpm-lock.yaml
- Follow-up to https://github.com/withastro/astro/pull/9293 as this package breaks as well.
- Doing a preview release
- N/A
> Remove aria-query and related rule

- packages/integrations/tailwind/package.json
- Downgrading to prevent a major version bump
Tested locally
N/A
> Downgrade the tailwind integration for Astro 3/4 compat

- packages/astro-rss/CHANGELOG.md
- packages/astro/CHANGELOG.md
updates the astro and rss changelogs for 4.0 release
no tests!
only docs!
> edits to release CHANGELOGS

- .changeset/nice-panthers-tell.md
- Changeset needed to cause Tailwind to get a patch change.
N/A
Docs only
> Add changeset for Tailiwind

- .changeset/neat-peaches-mate.md
- packages/integrations/mdx/package.json
- packages/integrations/node/package.json
- packages/integrations/svelte/package.json
- packages/integrations/vue/package.json
- Updates peer dependencies for  Vue, Svelte, Node, MDX
> chore: update peer dependencies

- README.md
> fix: markdown formatting issue

- .changeset/old-dragons-kneel.md
- packages/astro/astro.js
> Fix broken link

- .changeset/thirty-hats-bathe.md
- packages/astro/src/core/app/index.ts
- packages/astro/src/core/config/timer.ts
- packages/astro/src/vite-plugin-astro-server/request.ts
- packages/astro/test/fixtures/middleware space/src/middleware.js
- packages/astro/test/middleware.test.js
Closes https://github.com/withastro/astro/issues/8627
Added a new test case from the original reproduction
N/A
> fix: merge headers from the original response in error pages

- .changeset/real-bags-hope.md
- packages/astro/src/core/build/generate.ts
Fix https://github.com/withastro/astro/issues/9449
N/A, simple bug fix
N/A
> fix(assets): Prevent concurrency from being set to 0

- .changeset/eight-sheep-nail.md
- packages/integrations/node/README.md
> Fix typo in @astrojs/node README

- packages/astro/src/core/errors/errors-data.ts
Follow up of https://github.com/withastro/astro/pull/9458/#discussion_r1431400203
N/A
cc @sarah11918
> chore: fix error message

- packages/astro/src/runtime/client/dev-overlay/plugins/astro.ts
- packages/astro/src/runtime/client/dev-overlay/plugins/audit/index.ts
- packages/astro/src/runtime/client/dev-overlay/plugins/xray.ts
- Update deprecated `plugin-toggled` to `app-toggled`
None
None
> Update `plugin-toggled` to `app-toggled`

- .github/workflows/release.yml
- scripts/notify/index.js
- Updates the GitHub Action for Discord release messages to (hopefully) handle newlines properly.
- We didn't change anything but apparently it broke. Either GitHub or Discord must have changed something... Who knows!
Are you joking? This is GitHub Actions baby, YOLO
No
> Fix Discord release message

- packages/astro-rss/test/pagesGlobToRssItems.test.js
* Fixes a typo in an existing test name to better reflect its purpose, see PR #9610 
Updated test
Fix a typo in the testing code. No user-facing documentation.
> fix(rss): update test name to better match behavior

- scripts/notify/index.js
Looks like the fetch code was incorrect. The first parameter should be a URL.
n/a. 🤞 
n/a
> Fix discord fetch code

- packages/astro/src/cli/db/index.ts
- Changes the way we pass through CLI args.
N/A
N/A
> Change way args are passed to cli packages

- examples/with-vitest/package.json
- pnpm-lock.yaml
The Vitest version was super outdated, leading to type errors
N/A
N/A
> fix: update vitest

- .github/workflows/release.yml
- Follow up to #9796
- I forgot a conditional check. Whoops!
Nope, this matches the old behavior
N/A
> Fix release announcement script (again)

- examples/with-markdoc/src/components/Aside.astro
- packages/astro/performance/fixtures/utils/Aside.astro
- packages/create-astro/src/index.ts
- packages/integrations/markdoc/test/fixtures/propagated-assets/src/components/Aside.astro
- packages/integrations/markdoc/test/fixtures/render-html/src/components/Aside.astro
Update broken doc links with their updated equivalent.
N/A
N/A
> Fix: update doc links

- .github/scripts/announce.mjs
- Turns out that we should probably return the message instead of just logging it to the console 😵‍💫
We'll do it live
Nooooooooooooo
> Fix release announcement script (redemption arc)

- packages/integrations/sitemap/package.json
- packages/integrations/sitemap/test/base-path.test.js
- packages/integrations/sitemap/test/filter.test.js
- packages/integrations/sitemap/test/routes.test.js
- packages/integrations/sitemap/test/ssr.test.js
- packages/integrations/sitemap/test/staticPaths.test.js
- packages/integrations/sitemap/test/trailing-slash.test.js
- pnpm-lock.yaml
This reverts commit 82de54979e90f7f46b832cf5ae88fcc5fed43568.
> Revert "chore(@astrojs/integrations/sitemap): use Node.js for testing (#9891)"

- packages/astro/src/@types/astro.ts
> fix(docs): add missing variant

- packages/astro-rss/test/rss.test.js
- Issue introduced in #9967
Ran `pnpm test`
N/A
> fix(rss): use node assert instead of chai

- examples/view-transitions/src/components/Nav.astro
Just remove the same CSS properties `px-4`.
N/A
N/A
> Remove the same CSS properties

- .changeset/six-eels-lick.md
- packages/astro/components/Picture.astro
> chore: typo

- packages/astro/test/html-slots.nodetest.js
- See #9873
- Migrates `packages/astro/test/html-slots.test.js`
N/A
> chore: Migrate `html-slots.test.js` to `node:test`

- packages/astro/test/html-page.nodetest.js
- See #9873
- Migrates `packages/astro/test/html-page.test.js`
N/A
> chore: Migrate `html-page.test.js` to `node:test`

- packages/astro/test/html-escape.nodetest.js
- See #9873
- Migrates `packages/astro/test/html-escape.test.js`
N/A
> chore: Migrate `html-escape.test.js` to `node:test`

- packages/astro/test/html-escape-complex.nodetest.js
- See #9873
- Migrates `packages/astro/test/html-escape-complex.test.js`
N/A
> chore: Migrate `html-escape-complex.test.js` to`node:test`

- packages/astro/test/html-component.nodetest.js
- See #9873
- Migrates `packages/astro/test/html-component.test.js`
N/A
> chore: Migrate `html-component.test.js` to `node:test`

- packages/astro/test/custom-404-md.nodetest.js
* Migrates `packages/astro/test/custom-404-md.test.js`
> chore: Migrate `custom-404-md.test.js` to `node:test`

- packages/astro/test/units/vite-plugin-astro-server/response.nodetest.js
Fixes a failing test
I run whole suite locally and it now passes. CI should pass too.
> chore: fix test that was failing

- examples/with-vitest/package.json
- pnpm-lock.yaml
Updates Vitest too so it's transitive Vite dep is also updated.
Ran the test locally.
n/a
> Fix Vitest example check fail

- packages/astro/test/featuresSupport.nodetest.js
- packages/astro/test/fetch.nodetest.js
- packages/astro/test/fontsource.nodetest.js
- See #9873 
- Migrates some tests to node:test
N/A
> chore: move tests to node

- packages/astro/test/get-static-paths-pages.nodetest.js
- packages/astro/test/glob-pages-css.nodetest.js
- packages/astro/test/head-injection.nodetest.js
- packages/astro/test/hoisted-imports.nodetest.js
- packages/astro/test/hydration-race.nodetest.js
This PR moves the files that start with `g*` and `h*` to node:test
Part of https://github.com/withastro/astro/issues/9873
should pass.
> chore: move test to node

- packages/astro/src/core/errors/errors-data.ts
This removes a sentence we decided was unhelpful.
With my eyes
Yes
> Remove unhelpful message in `errors-data.ts`

- packages/astro-rss/test/pagesGlobToRssItems.test.js
- packages/astro-rss/test/rss.test.js
- packages/astro/test/astro-basic.nodetest.js
- packages/astro/test/astro-children.nodetest.js
- packages/astro/test/astro-markdown-frontmatter-injection.nodetest.js
- packages/astro/test/astro-markdown-plugins.nodetest.js
- packages/astro/test/astro-markdown-remarkRehype.nodetest.js
- packages/astro/test/astro-markdown-shiki.nodetest.js
- packages/astro/test/astro-markdown-url.nodetest.js
- packages/astro/test/astro-markdown.nodetest.js
- packages/astro/test/custom-404-html.nodetest.js
- packages/astro/test/custom-404-implicit-rerouting.nodetest.js
- packages/astro/test/custom-404-injected-from-dep.nodetest.js
- packages/astro/test/custom-404-injected.nodetest.js
- packages/astro/test/custom-404-md.nodetest.js
- packages/astro/test/custom-404-static.nodetest.js
- packages/astro/test/markdown.nodetest.js
- packages/astro/test/ssr-markdown.nodetest.js
- packages/create-astro/test/context.test.js
- packages/integrations/node/test/well-known-locations.test.js
- packages/integrations/react/test/parsed-react-children.test.js
- packages/markdown/remark/test/remark-collect-images.test.js
Change `strictEqual` to `equal` from this comment:
https://github.com/withastro/astro/pull/10125#discussion_r1490882889
should pass.
> chore: Change `strictEqual` to `equal`

- .changeset/tidy-laws-think.md
- packages/astro/e2e/dev-toolbar.test.js
- packages/astro/e2e/fixtures/dev-toolbar/src/layout/Layout.astro
- packages/astro/e2e/fixtures/dev-toolbar/src/pages/view-transition-a.astro
- packages/astro/e2e/fixtures/dev-toolbar/src/pages/view-transition-b.astro
- packages/astro/src/runtime/client/dev-toolbar/apps/astro.ts
Fix to get Integration Data even when a page is transitioned by ViewTransition.
add test case
N/A
> Fix to get Integration Data even when a page is transitioned by ViewTransition

- packages/astro/e2e/dev-toolbar.test.js
> fix: dev-toolbar test

- examples/blog/src/content/blog/second-post.md
- examples/blog/src/content/blog/third-post.md
- Swap the pubDates of the "Second post" and "Third post", so they are sorted and shown in the correct order
- Local build to check if sorting is not broken, and it's not. Otherwise this is a small transparent fix, no thorough testing is needed.
- No docs is needed to be updated.
> Fix blog ordering

- .git-blame-ignore-revs
Ignore commit from https://github.com/withastro/astro/pull/10180
N/A
N/A
> chore: ignore commit

- packages/astro/src/@types/astro.ts
> Fix typo in `@types/astro.ts`

- .changeset/good-worms-build.md
- packages/db/src/core/integration/vite-plugin-db.ts
Get remote url from utility function instead of environment.
> fix: correct remote url

- .changeset/eight-shrimps-enjoy.md
corrects changeset improvement
> chang changeset

- .github/workflows/benchmark.yml
- .github/workflows/check.yml
- .github/workflows/ci.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/scripts.yml
- .github/workflows/snapshot-release.yml
- .github/workflows/test-hosts.yml
Silence these warnings:
See github action runs.
n.a.
> Updates deprecated Node.js 16 github actions

- .changeset/soft-boxes-allow.md
- packages/astro/src/assets/endpoint/node.ts
- packages/astro/src/assets/vite-plugin-assets.ts
- packages/astro/test/core-image.test.js
This PR backports https://github.com/withastro/astro/pull/10284 to `3-legacy`
Hopefully CI should pass
N/A
> fix(assets): Solidify Node endpoint (#10284)

- .changeset/slimy-berries-mate.md
- packages/integrations/vercel/package.json
- pnpm-lock.yaml
- Closes #10297
- Need to wait for OP confirmation
Tests should still pass
Bug fix, N/A
> chore(vercel): update @vercel/nft

- .changeset/rare-badgers-smile.md
- packages/db/package.json
- fixes a small type issue where the package.json types were pointing to the wrong place
- Thanks @TheOtterlord for triaging!
- N/A
- N/A
> fix package json types

- packages/db/src/core/integration/file-url.ts
- Previous code was failing if you didn't have an assets directory at all
- N/A
- N/A
> small fix to an incorrect .length check

- .changeset/good-rats-bathe.md
- packages/db/package.json
The module declaration was added but is not being included in the package. This fixes that.
No change in logic
N/A
> Include virtual declaration in package

- .changeset/eight-spoons-nail.md
- packages/astro/src/core/routing/manifest/create.ts
- packages/astro/test/units/routing/manifest.test.js
Closes https://github.com/withastro/astro/issues/10173
Closes PLT-1772
I added a new test case
N/A
> fix(routing): regression on partial dynamic routes

- packages/astro/src/@types/astro.ts
Only changes some text and formatting of JSDoc entry for `build.assetsPrefix` to render better in docs.
No tests!
All docs!
> [docs] update JSDoc for formatting in docs

- .changeset/late-penguins-change.md
- packages/astro/client.d.ts
Some functions referenced a non existent virtual module.
manually verified in VS Code
n/a
> Fixes broken transition types

- .changeset/purple-eggs-sell.md
- packages/db/src/core/utils.ts
- The new Studio production URL, when released tomorrow
N/A
N/A
> Set new Astro Studio production URL

- .changeset/few-teachers-impress.md
- packages/db/src/core/cli/commands/link/index.ts
- packages/db/src/core/cli/commands/push/index.ts
- packages/db/src/core/cli/migration-queries.ts
- packages/db/src/core/tokens.ts
- packages/db/src/core/utils.ts
- packages/db/src/runtime/db-client.ts
- packages/db/src/runtime/utils.ts
- Fixes https://www.youtube.com/watch?v=qquVJ81APEs
- Manual 
> fix(db): separate utils for runtime

- .changeset/sharp-cobras-drive.md
- packages/astro/package.json
- pnpm-lock.yaml
Ensure that our users have a working version of Babel
See: https://github.com/withastro/astro/issues/10502
N/A
> chore: update Babel version

- .changeset/two-planes-try.md
> fix: bump internal-helpers

- .changeset/small-islands-pump.md
- packages/astro/package.json
- pnpm-lock.yaml
- Updates the compiler which had a bug with head content being pushed into body.
- Depends on https://github.com/withastro/compiler/pull/990
- Tested in compiler
- Also testing with this example: https://stackblitz.com/edit/github-pfaayw-axdvrr?file=src%2Fpages%2Findex.astro,package.json
N/A, bug fix
> Fixes issue with head content being pushed into body

- examples/basics/.gitignore
- examples/blog/.gitignore
- examples/component/.gitignore
- examples/framework-alpine/.gitignore
- examples/framework-lit/.gitignore
- examples/framework-multiple/.gitignore
- examples/framework-preact/.gitignore
- examples/framework-react/.gitignore
- examples/framework-solid/.gitignore
- examples/framework-svelte/.gitignore
- examples/framework-vue/.gitignore
- examples/minimal/.gitignore
- examples/non-html-pages/.gitignore
- examples/portfolio/.gitignore
- examples/with-markdoc/.gitignore
- examples/with-markdown-plugins/.gitignore
- examples/with-markdown-shiki/.gitignore
- examples/with-mdx/.gitignore
- examples/with-nanostores/.gitignore
- examples/with-tailwindcss/.gitignore
- examples/with-vitest/.gitignore
Add the .idea folder to the .gitignore file of each example to exclude the JetBrains settings folder from being pushed and causing unwanted conflicts.
N/A
N/A
> Add .idea folder to .gitignore files of the examples

- packages/integrations/node/test/test-utils.js
listen to errors when doing server setup in tests
(do I need to run `pnpm changeset`?)
no tests are needed as this is infra change that shouldn't affect the tests
No docs needed as it's test related
> test(@astrojs/node) listen for server setup errors in test-utils

- packages/integrations/node/test/prerender.test.js
- packages/integrations/node/test/trailing-slash.test.js
Fix flaky trailing slash tests when the server is not ready by the time the test run
> test(@astrojs/node) wait for server listening in trailing-slash tests

- packages/astro/src/i18n/utils.ts
Update utils.ts: Optimize and simplify code
- Update utils.ts: Optimize and simplify code
no tests should change
no  affect a user’s behavior
> Update utils.ts: Optimize and simplify code

- .changeset/empty-rules-type.md
> fix: rewrite Node.js changeset

- packages/create-astro/test/project-name.test.js
head and tail blank spaces should be trimed
- update unit test meet the right expectations.
- update unit test meet the right expectations.
no affect a user’s behavior
> fix: head and tail blank spaces should be trimed

- .github/workflows/snapshot-release.yml
A recent upgrade made it impossible for people to create preview releases, this should fix that.
We'll see!
N/A
> fix(actions): Make it possible for users with write access to make preview releases

- scripts/cmd/build.js
> fix: typo in build.js

- .changeset/lorem-ipsum-dolor
This changeset has been unused for 5 months because it's incorrectly named. From https://github.com/withastro/astro/pull/9378
n/a
n/a
> Delete unused changeset

- .changeset/lovely-feet-greet.md
- packages/astro/src/runtime/client/dev-toolbar/helpers.ts
Oops, not using the right event.
Fix https://github.com/withastro/astro/issues/10932
N/A
> Fixes toggleState

- packages/astro/src/core/errors/errors-data.ts
> fix: error message grammar

- packages/astro/src/core/errors/errors-data.ts
Moves an error in the correct section
N/A
> chore: move error in the correct section

- packages/astro/CHANGELOG.md
Some weird bug caused by the changesets bot
N/A
N/A
> chore: fix changelog bug caused by changesets bot

- .changeset/unlucky-seas-greet.md
- packages/integrations/react/package.json
removed wrong react types that break install
> feat(package.json): removed wrong react types

- packages/astro/src/@types/astro.ts
> docs: fix actions added-in version

- .changeset/warm-schools-applaud.md
- packages/astro/src/core/dev/dev.ts
Fix #11012
Running test locally.
It doesn't need to update docs.
> Prevents unhandledrejection error when checking for latest Astro version 

- .changeset/dirty-planes-punch.md
- packages/astro/src/@types/astro.ts
Fix potential red squiggles copying our example into a component.
> Actions: fix minor type issues in documented example

- packages/db/test/static-remote.test.js
Failed to see one missed test.
CI should pass
> chore: fix missed failing test

- packages/astro/src/@types/astro.ts
Adds the appropriate heading level for `security.checkOrigin`
No tests.
To enable proper rendering in docs.
> [docs] update heading level in config reference

- .github/ISSUE_TEMPLATE/---01-bug-report.yml
Issue template was outdated with our lowest Node version
N/A
N/A
> nit: update Node version in issue template

- .changeset/nervous-worms-sort.md
- packages/integrations/node/src/serve-app.ts
Fixes #11200
Adds missing error logging in catch block.
Testing not needed
N/A
> fix(node): add missing error logging

- .changeset/heavy-eagles-happen.md
- packages/astro/src/core/errors/errors-data.ts
- packages/astro/src/i18n/index.ts
Closes https://github.com/withastro/astro/issues/11100
N/A
N/A
> fix(i18n): improve error message

- packages/astro/src/core/errors/errors-data.ts
Fixes a regression introduced in https://github.com/withastro/astro/pull/11189/files
The smoke CI should pass
N/A
> ci: fix regression in errors data

- .changeset/bright-elephants-yell.md
- packages/astro/src/config/index.ts
Closes https://github.com/withastro/astro/issues/11221
I will create a preview release and test it
N/A
> fix: regression for getViteConfig

- .changeset/dull-carpets-breathe.md
> fix typo in changeset

- CONTRIBUTING.md
This PR adds some useful tips to our contribution guide regarding testing.
N/A
N/A
> docs: add some useful tips for testing

- packages/upgrade/package.json
- pnpm-lock.yaml
Like the title says
CI should pass
N/A
> chore(deps): remove deprecated pkg, `preferred-pm` now ships its types

- .changeset/afraid-rivers-begin.md
- packages/astro/src/actions/runtime/virtual/server.ts
> Revert "bug: removes type override from defineAction"

- packages/astro/CHANGELOG.md
> fix: changelog formatting

- .git-blame-ignore-revs
> chore: add formatting commit to blame ignore

- README.md
The current link 404s
N/A; not a code edit.
N/A; not a code edit.
> Fix readme link to astro-rss package

- biome.json
- package.json
- pnpm-lock.yaml
As per title. No changes in the code.
CI should pass
N/A
> chore: upgrade biome to the latest

- packages/astro/CHANGELOG.md
> nit: typo in changelog

- packages/astro/src/core/dev/restart.ts
- Changes a check following @bluwy review on #11551. PR was merged too fast
Tests should still pass
No changeset
> chore: optimize check

- packages/astro/src/@types/astro.ts
This makes a few small changes to the Content Layer types' docs for the 4.14 release.
Yes?!
Exactly!
> Small wording/nit improvements to 4.14 release types docs

- package.json
- pnpm-lock.yaml
- turbo.json
Ran `pnpm dlx @turbo/codemod migrate` and formatted the `turbo.json` with biome.
https://turbo.build/repo/docs/crafting-your-repository/upgrading
Hope CI passes 🙏 
n/a. internal change
> Upgrade to turbo v2

- README.md
Chore PR, it adds the `@astrojs/netlify` to the readme
N/A
N/A
> chore(readme): adds the netlify adapter

- .changeset/famous-dolls-grin.md
typo in changeset from https://github.com/withastro/astro/pull/11733
> Fix astro upgrade changeset

- examples/middleware/src/middleware.ts
- examples/middleware/src/pages/admin.astro
- examples/middleware/src/pages/api/login.ts
- examples/middleware/src/pages/api/logout.ts
- examples/middleware/src/pages/index.astro
- examples/middleware/src/pages/login.astro
Get the middleware example working at all: `npm create astro@latest -- --template middleware`
It's a self-contained implementation.
There is no need for documenation because this example missed the implementation of the backend.
> Fix middleware example

- packages/astro/src/@types/astro.ts
> [docs] fix indents

- packages/astro/src/@types/astro.ts
> [docs]: fix typo

- packages/astro/e2e/fixtures/solid-circular/src/env.d.ts
- packages/astro/e2e/fixtures/svelte-component/src/env.d.ts
- packages/astro/performance/fixtures/mdoc/src/env.d.ts
- packages/astro/performance/fixtures/mdx/src/env.d.ts
- packages/astro/test/fixtures/error-bad-js/src/env.d.ts
- packages/astro/test/fixtures/error-build-location/src/env.d.ts
- packages/astro/test/fixtures/error-non-error/src/env.d.ts
- packages/integrations/vercel/test/hosted/hosted-astro-project/src/env.d.ts
Except in `examples/` as presumably we want people to commit them to git. But for us, we gitignore them as we have too many.
n/a
> Remove lingering env.d.ts files

- packages/astro/e2e/client-idle-timeout.test.js
We have a specific one e2e that always fails. This PR fixes it
Tested locally, it passes now. CI should pass
> test: fix broken e2e test

- .changeset/new-monkeys-sit.md
> fix: syntax error in changelog

- packages/astro/src/types/public/config.ts
Updates the public types file for formatting issues so it renders properly in docs.
no tests, just docs.
all docs!
> [docs] formatting for config ref docs

- examples/hackernews/package.json
- examples/middleware/package.json
- examples/server-islands/package.json
- examples/ssr/package.json
- examples/view-transitions/package.json
- pnpm-lock.yaml
- scripts/deps/update-example-versions.js
Fix CI fail
Ran examples check locally
n/a
> Fix examples version update for removed packages

- packages/astro/package.json
- pnpm-lock.yaml
Forgot to remove the types after https://github.com/withastro/astro/pull/11772
n/a
n/a
> Remove unused types

- .changeset/pink-yaks-exercise.md
- packages/astro/src/types/public/config.ts
> feat(next): envField jsdoc

- .changeset/nasty-dogs-sort.md
- .vscode/settings.json
> chore: changeset minor

- packages/astro/src/core/errors/errors-data.ts
Updates the text and links of an Actions error message for static/hybrid merge.
No tests, just docs
Only docs!
> Update an error message

- .changeset/rare-goats-join.md
- packages/astro/src/runtime/server/render/util.ts
Close https://github.com/withastro/astro/issues/12023. Add `selected` to the list of boolean attributes.
n/a
> Add selected to the list of boolean attributes

- packages/astro/package.json
- pnpm-lock.yaml
Boxen should be safe to upgrade to v8 now based on https://github.com/withastro/astro/issues/11480#issuecomment-2268931742
existing tests should pass
n/a
> Update boxen to v8

- packages/integrations/vue/package.json
- Adds missing file from #12112
Should pass
N/A, no changeset
> fix(vue): missing file

- .github/workflows/benchmark.yml
- .github/workflows/preview-comment.yml
- .github/workflows/preview-release.yml
- .github/workflows/snapshot-release.yml
Check user permissions before executing the benchmark and previews. Thanks @pwntester for spotting this.
n/a. should work.
n/a
> Check permissions for workflows

- .changeset/gold-masks-trade.md
- packages/astro/e2e/actions-blog.test.js
- packages/astro/src/actions/runtime/middleware.ts
- packages/astro/src/core/constants.ts
- packages/astro/src/core/middleware/sequence.ts
- packages/astro/src/core/render-context.ts
- packages/astro/src/core/routing/rewrite.ts
fix https://github.com/withastro/astro/issues/12201
fix https://github.com/withastro/astro/issues/12202
I reverted the source code changes, but kept the tests (added `test.skip`) so it can be reused later
n/a
> Revert #12173

- .changeset/sharp-garlics-float.md
- packages/astro/src/core/render-context.ts
- packages/astro/src/i18n/utils.ts
- packages/astro/test/fixtures/i18n-routing-dynamic/astro.config.mjs
- packages/astro/test/fixtures/i18n-routing-dynamic/package.json
- packages/astro/test/fixtures/i18n-routing-dynamic/src/pages/[language].astro
- packages/astro/test/i18n-routing.test.js
- pnpm-lock.yaml
Closes https://github.com/withastro/astro/issues/12185
I added a new test case
N/A
> fix(i18n): correctly compute the current locale

- .github/workflows/ci.yml
Merge issue made the yml file invalid
CI should pass
N/A
> ci: fix syntax error

- .changeset/late-fireants-ring.md
- packages/astro/src/integrations/features-validation.ts
- Closes #12276 
Should pass
N/A, bug fix
> fix: astro:env warning

- .changeset/wet-masks-hide.md
> chore: add changeset for #12280

- .changeset/mighty-pants-rush.md
- packages/astro/src/cli/index.ts
> Fix cli command typo

- .changeset/friendly-radios-live.md
- packages/astro/src/env/runtime-constants.ts
- packages/astro/src/env/runtime.ts
- packages/astro/src/env/vite-plugin-env.ts
- Reverts #12227
- Closes #12324
> fix: revert #12227

- .changeset/tough-planets-dress.md
We need to release a beta with this so that the new basics template work.
N/A
N/A
> Adds missing changeset for new basics template

- .changeset/shaggy-kids-juggle.md
- packages/integrations/svelte/client-v5.js
- packages/integrations/svelte/server-v5.js
> Add support for Svelte 5 @render syntax

- .changeset/proud-terms-swim.md
I merged the previous PR before Sarah gave her review. These changes are based on her feedback, and on seeing some formatting errors in the release PR
> chore: better images changeset pt 2

- .github/workflows/snapshot-release.yml
I made a mistake in the previous PR 😢
> ci: fix changeset action

- examples/toolbar-app/package.json
- pnpm-lock.yaml
Example didn't build because of the missing node types.
N/A
> fix(examples): Missing node types for toolbar example

- .github/scripts/announce.mjs
- benchmark/bench/_template.js
- scripts/cmd/build.js
This PR fixes all the linting warnings we are experiencing in CI.
CI should pass
N/A
> chore: fix linting warnings

- packages/astro/test/fixtures/astro-cookies/astro.config.mjs
- packages/astro/test/fixtures/redirects/astro.config.mjs
- packages/astro/test/fixtures/reroute/astro.config.mjs
- packages/astro/test/fixtures/rewrite-server/astro.config.mjs
- packages/astro/test/fixtures/ssr-error-pages/astro.config.mjs
This PR updates the tests to pass
CI should pass
N/A
> fix: update tests

- .changeset/config.json
- .changeset/pre.json
This PR exits from pre-mode.
CI must pass
N/A
> chore: exit pre-mode

- examples/with-markdoc/src/pages/index.astro
Adds a null check to the markdoc example
> chore: add null check to example

- examples/basics/src/components/Welcome.astro
Make the link point to the final article url
N/A
N/A
> feat: make basics link point to final article

- .changeset/swift-pandas-serve.md
- packages/astro/src/core/app/middlewares.ts
- packages/astro/test/csrf-protection.test.js
This PR ports a fix of `checkOrigin` to v4
CI should pass
N/A
> fix: `checkOrigin` headers check

- .changeset/bright-gifts-prove.md
- packages/astro/src/core/errors/errors-data.ts
Updates a docs link in an error message.
(Missed one in my last PR.)
No tests.
Only docs!
> [error message] updates docs link

- .changeset/neat-pumas-accept.md
- packages/astro/astro-jsx.d.ts
Standards status https://chromestatus.com/feature/5097714453577728
> Adds `closedby` to dialog interface

- .changeset/friendly-eagles-bow.md
- Adds a changeset that was forgotten in https://github.com/withastro/astro/pull/12735
> Preoptimize React compiler runtime

- packages/astro/src/i18n/middleware.ts
- packages/astro/test/i18n-routing.test.js
Closes https://github.com/withastro/astro/issues/12750
Closes PLT-2714
Added a new test and update the existing ones
N/A
> fix: correctly return 404.astro in i18n

- .changeset/clean-ears-brake.md
Forgot to add a changeset for https://github.com/withastro/astro/issues/12750
N/A
N/A
> chore: changeset

- .changeset/strong-cobras-own.md
- packages/integrations/mdx/src/server.ts
- pnpm-lock.yaml
fix https://github.com/withastro/astro/issues/12802
Not completely fixing React 19 support yet, but I think a good step with other perf too.
Existing tests, especially mdx, should pass
n/a. refactor
> Make MDX integration check noop

- benchmark/make-project/_template.js
- packages/astro/src/core/build/static-build.ts
- scripts/cmd/build.js
Fix biome correctness checks so CI doesn't show them
n/a
n/a
> Fix biome correctness checks

- packages/astro/test/units/integrations/api.test.js
- Supersedes #11889
Adds a test
N/A
> chore: add test for astro:route:setup hook

- packages/astro/package.json
> chore: add `funding` to the main package

- packages/astro/src/core/request.ts
This is a follow-up of https://github.com/withastro/astro/pull/12937#discussion_r1907546785
CI should pass
N/A
> chore: better types

- .changeset/itchy-trains-allow.md
- packages/astro/src/vite-plugin-astro-server/route.ts
- packages/astro/test/astro-response.test.js
- packages/astro/test/fixtures/astro-response/src/pages/not-found-custom.astro
- packages/astro/test/test-utils.js
- Closes #12943
Manually, tests added
N/A
> fix: 404 status in dev

- packages/astro/src/core/config/schema.ts
- packages/astro/src/manifest/virtual-module.ts
- packages/astro/src/types/public/config.ts
- packages/astro/test/fixtures/astro-manifest-invalid/astro.config.mjs
- packages/astro/test/fixtures/astro-manifest-invalid/src/pages/client.astro
- packages/astro/test/fixtures/astro-manifest/astro.config.mjs
- packages/astro/test/fixtures/astro-manifest/src/pages/index.astro
- packages/astro/test/fixtures/astro-manifest/src/pages/server.astro
- packages/astro/test/serializeManifest.test.js
It applies the change in the RFC: https://github.com/withastro/roadmap/pull/1106#issuecomment-2612554199
Updated the tests, they should all pass
N/A
> chore: rename to `astro:config`

- .github/workflows/issue-labeled.yml
> chore: fix a typo in the action message

- packages/astro/client.d.ts
- packages/astro/src/core/errors/errors-data.ts
- packages/astro/src/manifest/virtual-module.ts
- packages/astro/src/types/public/config.ts
- packages/astro/test/serializeManifest.test.js
- pnpm-lock.yaml
- fixes some issue in the docs (incorrect position and indentation)
- fixes types exposed to the users
- renamed an error to be more descriptive
CI should pass
> fix: docs and types

- .changeset/nice-poems-smoke.md
- packages/astro/src/core/routing/match.ts
- packages/astro/test/i18n-routing.test.js
> fix(i18n): bypass server island with base

- packages/astro/src/assets/fonts/providers.ts
- packages/astro/src/assets/fonts/providers/bunny.ts
- packages/astro/src/assets/fonts/providers/fontshare.ts
- packages/astro/src/assets/fonts/providers/fontsource.ts
- packages/astro/src/assets/fonts/providers/index.ts
- packages/astro/src/config/entrypoint.ts
- Re-export relevant providers from unifont
> feat(fonts): more providers

- README.md
- Updates the link of sponsors
- Update the alt text
N/A
> chore: update sponsors link and alt text

- .github/workflows/preview-release.yml
The checkout step was missing lol
> ci: add missing checkout step

- .github/workflows/preview-release.yml
I probably botched the multiple line command, so now I put it one line
Merge and trigger
N/A
> ci: publish script in one line

- packages/astro/src/core/errors/errors-data.ts
- packages/astro/src/core/session.ts
Docs suggested a different label for an error
proof read
> chore: reword error message

- packages/astro/src/types/public/config.ts
Follow up fo https://github.com/withastro/astro/pull/13241/files#r1954561935
> docs: remove kind heading

- .github/workflows/preview-release.yml
> ci: remove `--pnpm`

- .github/workflows/preview-release.yml
> ci: restore `--pnpm`

- .github/workflows/preview-release.yml
> ci: remove template, add more info

- .github/workflows/preview-release.yml
> ci: remove events to avoid non-wanted triggers

- .changeset/itchy-buckets-dream.md
- packages/integrations/vue/src/index.ts
> fix(vue): compiler fallback

- packages/astro/src/assets/fonts/vite-plugin-fonts.ts
- packages/astro/test/fonts.test.js
- Sets correct headers in dev
Adds tests
N/A
> feat(fonts): dev headers

- .changeset/slow-goats-eat.md
- packages/create-astro/src/actions/template.ts
Modify the template README file to reflect the correct package manager. This fixes #13236.
⚠️ Note: I thought modifying the existing `README.md` file **_on-the-fly_** might be easier than actually maintaining three or four different versions of the `README.md` file since the change is quite predictable.
Not sure if tests need changes.
Not relevant for docs, I think, since it doesn't change user's behavior. It only changes the result.
> Modify the template README file to reflect the correct package manager

- CONTRIBUTING.md
On Friday, we discovered that a label with a colon was causing syntax issues in the workflow file, so we renamed the label.
This PR updates the name in the contribution guide
N/A
N/A
> chore: update label name for preview releases

- scripts/deps/update-example-versions.js
> fix: examples script for release

- package.json
- pnpm-lock.yaml
Upgrade our monorepo to use pnpm v10
I ran `pnpm i` and `pnpm dedupe`
CI should pass
N/A
> chore: upgrade pnpm to v10

- packages/astro/test/fixtures/ssr-api-route/src/pages/500.js
- packages/astro/test/fixtures/ssr-api-route/src/pages/fail.js
Removes test dependency on an external service. Fixes test failure on main.
> chore: fix SSR API test

- packages/astro/test/types/astro-config-virtual-module.ts
> fix: astro:config types tests

- .changeset/cold-rats-swim.md
- packages/astro/package.json
- packages/astro/src/core/compile/compile.ts
- packages/astro/src/core/config/schema.ts
- packages/astro/src/types/public/config.ts
- packages/astro/test/css-order.test.js
- packages/astro/test/fixtures/css-order-transparent/astro.config.mjs
- packages/astro/test/fixtures/css-order-transparent/package.json
- packages/astro/test/fixtures/css-order-transparent/src/components/Item.astro
- packages/astro/test/fixtures/css-order-transparent/src/pages/index.astro
- pnpm-lock.yaml
Exposes the functionality implemented in the compiler: https://github.com/withastro/compiler/pull/1055
I added a new experimental flag (name to bikeshed, of course). 
Added a test
https://github.com/withastro/docs/pull/11211
> feat: experimental flag from compiler

- package.json
In CI, pnpm still complains about few built dependencies not being listed. 
This PR adds them. 
I'll check the CI and make sure no warning is being printed
N/A
> chore: update built dependencies

- packages/astro/src/assets/fonts/vite-plugin-fonts.ts
- Improves vite plugin cleanup
N/A
N/A
> fix(fonts): vite plugin cleanup

- .changeset/all-suns-report.md
- packages/astro/package.json
- packages/integrations/mdx/package.json
- packages/markdown/remark/package.json
- pnpm-lock.yaml
This PR updates shiki to v3. Do we need a changeset? They say that v2 and v3 are boring releases because they don't add features.
CI should pass
N/A
> chore(deps): update shiki to v3

- .github/workflows/check-merge.yml
This PR restores the workflow removed in https://github.com/withastro/astro/pull/13435
The workflow is now fixed: https://github.com/tj-actions/changed-files/issues/2464#issuecomment-2727015352
Once approved, I will merge this PR and trigger again a renovate bot PR so it can pin the actions via digest.
N/A
> ci: restore workflow

- packages/astro/components/Font.astro
- packages/astro/src/assets/fonts/providers/local.ts
- packages/astro/src/assets/fonts/providers/utils.ts
- packages/astro/src/assets/fonts/utils.ts
- packages/astro/src/assets/fonts/vite-plugin-fonts.ts
- packages/astro/src/core/errors/errors-data.ts
- packages/astro/test/units/assets/fonts/providers.test.js
- packages/astro/test/units/assets/fonts/utils.test.js
- Creates astro errors and uses them
Updated
N/A
> feat(fonts): add errors

- packages/integrations/tailwind/README.md
Follow up to #13471 to align linking style with what we’d usually do
n/a
> Small change to linking style

- .changeset/little-doors-tickle.md
- packages/integrations/vercel/src/lib/redirects.ts
- packages/integrations/vercel/test/redirects.test.js
Generates the correct target URL for external redirects
Fixes #13479
Added test
> fix(vercel): generate correct external redirects

- .changeset/tough-tires-kneel.md
- packages/astro/src/runtime/server/render/server-islands.ts
Fixes #13461 by adding data-astro-rerun
n.a. / bug fix
> Repair server islands to work with client router

- .changeset/twenty-dogs-listen.md
- packages/integrations/cloudflare/package.json
- packages/integrations/cloudflare/src/entrypoints/server.ts
- packages/integrations/cloudflare/src/index.ts
- packages/integrations/cloudflare/test/fixtures/astro-dev-platform/package.json
- packages/integrations/cloudflare/test/fixtures/astro-env/package.json
- packages/integrations/cloudflare/test/fixtures/sessions/astro.config.mjs
- packages/integrations/cloudflare/test/fixtures/sessions/package.json
- packages/integrations/cloudflare/test/fixtures/sessions/src/actions/index.ts
- packages/integrations/cloudflare/test/fixtures/sessions/src/middleware.ts
- packages/integrations/cloudflare/test/fixtures/sessions/src/pages/api.ts
- packages/integrations/cloudflare/test/fixtures/sessions/src/pages/cart.astro
- packages/integrations/cloudflare/test/fixtures/sessions/src/pages/destroy.ts
- packages/integrations/cloudflare/test/fixtures/sessions/src/pages/index.astro
- packages/integrations/cloudflare/test/fixtures/sessions/src/pages/regenerate.ts
- packages/integrations/cloudflare/test/fixtures/sessions/src/pages/update.ts
- packages/integrations/cloudflare/test/fixtures/sessions/wrangler.json
- packages/integrations/cloudflare/test/sessions.test.js
- pnpm-lock.yaml
Adds support for automatically-provisioning session storage for Cloudflare KV
Automatically configures Cloudflare KV storage when experimental sessions are enabled
If the `experimental.session` flag is enabled when using the Cloudflare adapter, Astro will automatically configure the session storage using the Cloudflare KV driver. You can still manually configure the session storage if you need to use a different driver or want to customize the session storage configuration. If you want to use sessions, you will need to create the KV namespace and declare it in your wrangler config. You can do this using the Wrangler CLI:
```sh
npx wrangler kv namespace create SESSION
```
This will log the id of the created namespace. You can then add it to your `wrangler.json`/`wrangler.toml` file like …
> feat(cloudflare): add KV session storage support

- .changeset/little-steaks-rule.md
Updates the formatting of the changeset for the SVG API breaking changes
no tests, just docs
only docs!
> formatting on SVG changeset

- .github/workflows/preview-release.yml
- See https://github.com/withastro/astro/actions/runs/14262214393/job/39976145237#step:8:15
> fix(actions): pr preview label removal

- packages/astro/components/Font.astro
- packages/astro/src/assets/fonts/config.ts
- packages/astro/src/assets/fonts/constants.ts
- packages/astro/src/assets/fonts/load.ts
- packages/astro/test/fixtures/fonts/src/pages/index.astro
- packages/astro/test/fixtures/fonts/src/pages/preload.astro
- Addresses feedback from T&D
- Renames Font component `family` to `cssVariable`
- Renames font configuration `automaticFallback` to `optimizedFallbacks` 
Should pass
RFC updated
> feat(fonts): T&D feedback

- packages/astro/components/Font.astro
- packages/astro/src/assets/fonts/config.ts
- packages/astro/src/assets/fonts/providers/index.ts
- packages/astro/src/assets/fonts/providers/utils.ts
- packages/astro/src/assets/fonts/types.ts
- packages/astro/src/config/entrypoint.ts
- packages/astro/src/types/public/config.ts
- packages/astro/test/types/define-config.ts
> feat(fonts): jsdocs

- .changeset/wild-rabbits-arrive.md
- packages/astro/src/core/config/schemas/base.ts
- packages/astro/src/core/config/schemas/relative.ts
- packages/astro/src/core/create-vite.ts
- packages/astro/src/core/errors/errors-data.ts
- packages/astro/src/manifest/virtual-module.ts
- packages/astro/src/types/public/config.ts
- packages/astro/test/fixtures/astro-manifest-invalid/astro.config.mjs
- packages/astro/test/fixtures/astro-manifest/astro.config.mjs
- packages/astro/test/serializeManifest.test.js
This PR makes `astro:config` stable.
Updated the existing tests.
https://github.com/withastro/docs/pull/11380
> feat: make `astro:config` stable

- .changeset/young-kids-turn.md
- packages/astro/src/assets/utils/node/emitAsset.ts
- packages/astro/src/assets/vite-plugin-assets.ts
- packages/astro/src/content/content-layer.ts
- packages/astro/src/content/runtime-assets.ts
- packages/astro/src/content/vite-plugin-content-imports.ts
- packages/astro/src/core/config/schemas/base.ts
- packages/astro/src/types/public/config.ts
- packages/astro/test/fixtures/core-image-svg/astro.config.mjs
- packages/integrations/markdoc/src/content-entry-type.ts
Unflagging the SVG Component feature! 
Ran against the test fixture
Will need to remove this section from the experimental docs and likely move it to the standard location
> feat: unflag svg component feature

- .changeset/poor-grapes-share.md
- packages/astro/src/assets/fonts/vite-plugin-fonts.ts
- Exposes virtual module on the client
Using the preview release
Changeset
> fix(fonts): client access

- .changeset/few-flowers-notice.md
- packages/astro/src/assets/fonts/utils.ts
- packages/astro/test/units/assets/fonts/utils.test.js
- Closes #13624
Added
Changeset
> fix(fonts): tech(undefined) for local provider

- .changeset/moody-windows-flash.md
- packages/astro/src/assets/fonts/constants.ts
- packages/astro/src/assets/fonts/providers/local.ts
- packages/astro/src/assets/fonts/utils.ts
- packages/astro/test/units/assets/fonts/providers.test.js
- packages/astro/test/units/assets/fonts/utils.test.js
Fixes issue: https://github.com/withastro/astro/issues/13642
> fix(font): type to format mapping

- .changeset/plenty-loops-cry.md
- packages/astro/src/assets/fonts/vite-plugin-fonts.ts
- Closes #13672
Manual
Changeset
> fix(fonts): import side effect

- .changeset/every-garlics-share.md
- packages/astro/package.json
- pnpm-lock.yaml
- Support google subsetting
N/A
Changeset
> feat(fonts): update unifont

- .github/ISSUE_TEMPLATE/---01-bug-report.yml
Updates the version of Node.js that supports Astro.
N/A
N/A
> chore: update Node.js version in issue templates

- .changeset/tall-buses-rest.md
- packages/integrations/cloudflare/package.json
- packages/integrations/cloudflare/src/index.ts
- Closes #13947
Manually
Changeset
> fix(cloudflare): dispose platform proxy on server close

- examples/basics/README.md
Simple update to project structure on examples/basics/README.md
After
```
/
├── public/
│   └── favicon.svg
├── src
│   ├── layouts
│   │   └── Layout.astro
│   └── pages
│       └── index.astro
└── package.json
```
Before
```
/
├── public/
│   └── favicon.svg
├── src
│   ├── assets
│   │   └── astro.svg
│   ├── components
│   │   └── Welcome.astro
│   ├── layouts
│   │   └── Layout.astro
│   └── pages
│       └── index.astro
└── package.json
```
> update readme from examples basics examples

- .changeset/upset-books-ask.md
- packages/integrations/netlify/package.json
- pnpm-lock.yaml
Upgrade upstream dep. Fixes #14087
> fix: upgrade Netlify Vite plugin

- .github/workflows/preview-release-test.yml
> test: preview release

- .changeset/twelve-regions-allow.md
- packages/astro/src/runtime/server/render/page.ts
Closes https://github.com/withastro/astro/issues/13989
I manually tested this one. Current tests should pass
N/A
> fix(csp): header in response header

- .changeset/eighty-geese-act.md
- packages/integrations/netlify/package.json
- pnpm-lock.yaml
This PR bumps netlify deps. I also pinned `@netlify/functions` because if upgraded, will generate build errors.
CI should pass
> fix(netlify): update deps

- packages/integrations/cloudflare/test/fixtures/astro-env/wrangler.toml
- packages/integrations/cloudflare/test/fixtures/compile-image-service/wrangler.toml
- packages/integrations/cloudflare/test/fixtures/module-loader/wrangler.toml
- packages/integrations/cloudflare/test/fixtures/with-solid-js/wrangler.toml
- packages/integrations/cloudflare/test/fixtures/with-svelte/wrangler.toml
- packages/integrations/cloudflare/test/fixtures/with-vue/wrangler.toml
- packages/integrations/cloudflare/test/fixtures/wrangler-preview-platform/wrangler.toml
- packages/integrations/cloudflare/test/wrangler-preview-platform.test.js
- Fixes a regression from #14269
Intergations tests should pass now
N/A
> fix(cloudflare): tests

- .changeset/config.json
- .changeset/pre.json
- Follow https://github.com/withastro/astro/blob/main/CONTRIBUTING.md#entering-prerelease-mode
> feat: enable prerelease mode

- packages/astro/src/core/app/dev/pipeline.ts
- packages/astro/src/vite-plugin-hmr-reload/index.ts
Enables HMR for the environment API
> Support HMR in Environment API

- .prettierignore
Tries to fix https://github.com/withastro/astro/actions/runs/17980827973/job/51146151727
> chore: add CHANGELOG.md to .prettierignore

- packages/astro/CHANGELOG.md
- Don't forget a changeset! Run `pnpm changeset`.
- See https://contribute.docs.astro.build/docs-for-code-changes/changesets/ for more info on writing changesets.
> fix: changelog code snippet

- .changeset/green-garlics-heal.md
- packages/astro/client.d.ts
- Closes #14373
N/A
https://github.com/withastro/docs/pull/12468
> feat: deprecate import.meta.env.ASSETS_PREFIX

- packages/integrations/cloudflare/test/fixtures/vite-plugin/src/actions/index.ts
- packages/integrations/cloudflare/test/fixtures/vite-plugin/src/dev.ts
- packages/integrations/cloudflare/test/fixtures/vite-plugin/src/pages/action-success.astro
- packages/integrations/cloudflare/test/fixtures/vite-plugin/src/pages/actions.astro
This PR adds support for Astro Actions inside the Cloudflare plugin dev app
I added a new example in the plugin, and made sure that I receive the correct message when navigating to `/action-success`
N/A
> feat: support for astro actions

- packages/astro/src/assets/endpoint/node.ts
- packages/astro/src/assets/services/service.ts
- packages/integrations/node/test/image.test.js
- packages/internal-helpers/src/path.ts
- packages/internal-helpers/test/path.test.js
Cleaning up a few things missed from the last merge
> chore: fixes from merged PR

- .changeset/six-women-visit.md
- packages/astro/src/actions/runtime/utils.ts
- packages/astro/src/core/render-context.ts
- packages/astro/src/types/public/context.ts
- Closes #14370
N/A, AFAIK none was using rewrite inside an action
https://github.com/withastro/docs/pull/12477
> feat!: remove rewrite from action context
