withastro/astro

.changeset/rotten-cups-happen.md
packages/astro/e2e/css-sourcemaps.test.js
packages/astro/e2e/fixtures/css-sourcemaps/astro.config.mjs
packages/astro/e2e/fixtures/css-sourcemaps/package.json
packages/astro/e2e/fixtures/css-sourcemaps/src/env.d.ts
packages/astro/e2e/fixtures/css-sourcemaps/src/pages/index.astro
packages/astro/e2e/fixtures/css-sourcemaps/src/styles/main.css
packages/astro/src/core/render/dev/index.ts
packages/astro/src/runtime/client/hmr.ts
pnpm-lock.yaml

- Closes #5817
- Better handling for CSS in dev
- Includes the Vite ID of SSR'd styles so they can be removed once Vite takes over on the client
- E2E test added for default handling
- E2E test added to confirm this also works when `vite.css.devSourcemap` is enabled
Bug fix only

Remove duplicate CSS in dev

---

packages/astro/CHANGELOG.md
packages/integrations/lit/CHANGELOG.md

- Copies over changes merged into `1-legacy`
- Changesets respects these manual changes, so they won't be wiped out by the automatic updates when we release.
N/A
N/A

Migrate CHANGELOGs from `1-legacy` branch

---

.changeset/large-steaks-film.md
packages/astro/src/content/types-generator.ts
packages/astro/src/content/utils.ts
packages/astro/src/content/vite-plugin-content-server.ts
packages/astro/src/core/errors/errors-data.ts
packages/astro/test/content-collections.test.js
packages/astro/test/fixtures/content-collections/src/content/config.ts
packages/astro/test/fixtures/content-collections/src/content/with-custom-slugs/one.md
packages/astro/test/fixtures/content-collections/src/content/with-custom-slugs/three.md
packages/astro/test/fixtures/content-collections/src/content/with-custom-slugs/two.md
packages/astro/test/fixtures/content-collections/src/pages/collections.json.js
packages/astro/test/fixtures/content-collections/src/pages/entries.json.js

- Remove `slug()` collection configuration option
- Add special handling for the `slug` frontmatter property
- Override generated slug with the `slug` frontmatter property when present
- Respect `slug` during type generation
- Exclude `slug` from schema parsing
- Raise error when `slug` is present in a schema. Otherwise, users may attempt to use `.transform()` to manipulate slugs, and be surprised when this is not respected
- Chore: add new 9xxx error heading for content collection errors
Update tests to use `slug` frontmatter property
- New error messages
- TODO: docs updates

[Content Collections] Add `slug` frontmatter field

---

packages/astro-prism/CHANGELOG.md
packages/astro-rss/CHANGELOG.md
packages/astro/CHANGELOG.md
packages/create-astro/CHANGELOG.md
packages/integrations/cloudflare/CHANGELOG.md
packages/integrations/deno/CHANGELOG.md
packages/integrations/image/CHANGELOG.md
packages/integrations/lit/CHANGELOG.md
packages/integrations/mdx/CHANGELOG.md
packages/integrations/netlify/CHANGELOG.md
packages/integrations/node/CHANGELOG.md
packages/integrations/partytown/CHANGELOG.md
packages/integrations/preact/CHANGELOG.md
packages/integrations/react/CHANGELOG.md
packages/integrations/solid/CHANGELOG.md
packages/integrations/svelte/CHANGELOG.md
packages/integrations/tailwind/CHANGELOG.md
packages/integrations/vercel/CHANGELOG.md
packages/integrations/vue/CHANGELOG.md
packages/markdown/remark/CHANGELOG.md
packages/telemetry/CHANGELOG.md
packages/webapi/CHANGELOG.md
scripts/CHANGELOG.md

- Edits CHANGELOGs for
- Collapses all beta changelogs with `<details>` elements
- Reworks some notes that contradicted or repeated each other
- Designed to be merged into https://github.com/withastro/astro/pull/5948 before release
n/a

Improve CHANGELOGs

---

packages/astro-rss/src/index.ts

Ignores a lint warning in `@astrojs/rss` for a `console.warn` statement.

Ignore lint warning

---

.changeset/silly-bees-impress.md
packages/astro/src/content/utils.ts
packages/astro/test/content-collections.test.js
packages/astro/test/fixtures/content with spaces in folder name/astro.config.mjs
packages/astro/test/fixtures/content with spaces in folder name/package.json
packages/astro/test/fixtures/content with spaces in folder name/src/content/config.ts
packages/astro/test/fixtures/content with spaces in folder name/src/pages/index.astro
pnpm-lock.yaml

Fix Content Collections not loading config file when there are spaces in the folder tree

---

.changeset/nasty-dolphins-cry.md
packages/astro/src/core/logger/core.ts

- Should fix https://github.com/withastro/astro/issues/5926
- Requires deployment, going to ask issue creators to test.
N/A, bug fix

Protect against shimmed process usage in Vercel Edge

---

.changeset/swift-toes-divide.md
packages/astro/package.json
pnpm-lock.yaml

Fix https://github.com/withastro/astro/issues/5967
Upgrade semver to bring in the fix from https://github.com/npm/node-semver/pull/383, to allow `await import` to work properly.
n/a. bug fix.

Upgrade semver dependency

---

.changeset/fluffy-cherries-shake.md
packages/astro/src/core/render/core.ts
packages/astro/test/ssr-prerender-get-static-paths.test.js

- Closes #5975
- In static mode, routes that match a dynamic route but don't match a returned `getStaticPaths` call return 404
- This was not the case when using `prerender` in server mode in the dev server
- This PR updates our logic to account for prerender when `ssr` is true
Tests updated
Bug fix only

Handle unmatched 404 when using prerender in dev mode

---

.changeset/strong-hotels-sort.md
packages/astro/src/content/template/types.d.ts

- Add type guard support for `getCollection()` filters
Manual testing
N/A

[Content collections] Support type guards on `getCollection()` filter

---

.changeset/fresh-eels-speak.md
packages/astro/test/fixtures/react-component/src/components/WithChildren.jsx
packages/astro/test/fixtures/react-component/src/pages/index.astro
packages/astro/test/react-component.test.js
packages/integrations/react/server-v17.js
packages/integrations/react/server.js

This PR fixes #5493.
Passing `children` as props to a React component, e.g. `<WithChildren client:load children="test" />` would break in production with the component disappearing after hydration and React complaining with the following error:
```
Hydration failed because the initial UI does not match what was rendered on the server.
```
When creating the static HTML element for `children`, the `props.children` props was [previously ignored](https://github.com/withastro/astro/blob/28556a89fe1b63c88951834effd39630c7a52f90/packages/integrations/react/server.js#L73). This PR introduces a change to fallback to `props.children` if `children` is not defined which fixes the issue.
This PR also adds this change to `packages/integrations/react/server-v17.js` for the React 17 integration, altho, …

Support passing `children` as props to a React component

---

.changeset/serious-turtles-explode.md
packages/astro/src/runtime/server/render/component.ts

- just a typo, because @astrojs/solid package doesn't exist
before:

change @astrojs/solid to @astrojs/solid-js

---

.changeset/odd-rats-drop.md
packages/astro/src/core/app/node.ts
packages/integrations/node/src/standalone.ts
packages/integrations/node/test/fixtures/url-protocol/package.json
packages/integrations/node/test/fixtures/url-protocol/src/pages/index.astro
packages/integrations/node/test/url-protocol.test.js
pnpm-lock.yaml

This PR fixes #5890.
When using Astro with the `@astrojs/node` SSR adapter, `Astro.url.protocol` is always `http:` even when the server is running with HTTPS.
When creating the request used during rendering based on the Node.js request, the protocol is currently [hardcoded to `http:`](https://github.com/withastro/astro/blob/d47a9075bf13617fb5545aec50b46a76044bf85d/packages/astro/src/core/app/node.ts#L12).
This pull request fixes this issue by checking if the Node.js request is using HTTPS and updating the protocol accordingly. To do so, we check if the request socket is either an instance of `tls.TLSSocket` or if the [`X-Forwarded-Proto` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) is set to `https`.
While testing this, I also realised that when …

Fix `Astro.url.protocol` when using the @astrojs/node SSR adapter with HTTPS

---

.changeset/good-avocados-repeat.md
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/src/server.advanced.ts
packages/integrations/cloudflare/src/server.directory.ts
packages/integrations/cloudflare/src/util.ts
packages/integrations/cloudflare/test/fixtures/prerender/astro.config.mjs
packages/integrations/cloudflare/test/fixtures/prerender/package.json
packages/integrations/cloudflare/test/fixtures/prerender/src/pages/index.astro
packages/integrations/cloudflare/test/fixtures/prerender/src/pages/one.astro
packages/integrations/cloudflare/test/prerender.test.js
pnpm-lock.yaml

- Fixes the Cloudflare integration to support prerendering
- Test added that checks the generated `_routes.json`, verifies that prerendered route is included in the `excludes` config. This makes it so that the worker is bypassed in that route.
- Fixes https://github.com/withastro/astro/issues/5831
N/A, bug fix

Support for prerendering in the Cloudflare integration

---

.changeset/eighty-knives-remain.md
packages/integrations/mdx/test/fixtures/mdx-get-headings/src/pages/test-with-frontmatter.mdx
packages/integrations/mdx/test/mdx-get-headings.test.js
packages/markdown/remark/package.json
packages/markdown/remark/src/rehype-collect-headings.ts
pnpm-lock.yaml

This PR fixes #5780.
When using a frontmatter reference in a MDX heading, the ID generated for the heading is not using the reference value. For example,
```mdx
---
title: The Title
---
```
would generate `<h1 id="frontmattertitle">The Title</h1>` instead of `<h1 id="the-title">The Title</h1>`.
This pull request updates the `@astrojs/markdown-remark` rehype plugin generating these IDs to fix this behavior:
1. For MDX document, if the heading is a `MDXTextExpression`, e.g. `# {frontmatter.title}`, the plugin will use the associated ESTree entry to get the variable path, e.g. `['frontmatter', 'title']`.
2. If the variable is referencing a frontmatter value, the plugin try to get the value from the Astro data containing the frontmatter.
3. If the value is found, the plugin will use it to …

Fix MDX heading IDs generation when using a frontmatter reference

---

.changeset/cuddly-donkeys-warn.md
packages/integrations/alpinejs/README.md
packages/integrations/image/README.md
packages/integrations/lit/README.md
packages/integrations/mdx/README.md
packages/integrations/preact/README.md
packages/integrations/prefetch/README.md
packages/integrations/react/README.md
packages/integrations/sitemap/README.md
packages/integrations/solid/README.md
packages/integrations/svelte/README.md
packages/integrations/tailwind/README.md
packages/integrations/turbolinks/README.md
packages/integrations/vue/README.md

Astro imports the `defineConfig` function from `astro/config`. The `integrations` key needs to be passed into the `defineConfig` function, but it is not shown in the README. Updated the README according to the CLI example.
- The `astro.config.mjs` example shown in the README is changed

Updated according to new configuration

---

.changeset/lazy-buttons-prove.md
packages/astro/src/content/vite-plugin-content-assets.ts

Fixes #5859 where `frontmatter` is not exported but is used in 
https://github.com/withastro/astro/blob/02ba7c2250a950593961d833201e46adb3e0873c/packages/astro/src/content/internal.ts#L155
no tests
nothing changed

fix: undefined remarkPluginFrontmatter after calling render method

---

.changeset/rotten-dogs-hide.md
packages/astro/src/content/internal.ts
packages/astro/src/content/template/types.d.ts

Commit dabce6b8c684f851c3535f8acead06cbef6dce2a (#5970) broke the use of a plain boolean filter. Add an overload similar to TypeScript’s [`Array#filter` overload](https://github.com/microsoft/TypeScript/blob/v4.9.4/lib/lib.es5.d.ts#L1442-L1453).
https://github.com/withastro/astro/pull/5970#issuecomment-1405596846 (cc @bholmesdev)
Tested with my company blog, which uses `const posts = await getCollection("posts", (post) => post.data.author === author)`.
No documentation change needed.

fix: Don’t require `getCollection()` filter to be a type guard

---

.changeset/mean-tips-search.md
examples/with-tailwindcss/src/components/Button.astro
packages/astro/e2e/fixtures/tailwindcss/src/components/Button.astro
packages/astro/e2e/tailwindcss.test.js
packages/integrations/tailwind/README.md
packages/integrations/tailwind/src/index.ts

A recent PR (#5717) seems to have removed the autoprefixer postcss plugin for the TailwindCSS integration when it's not running in build mode. This breaks styles in development mode (#5989) because vendor prefixes aren't applied when it's running.
- Removed `isBuild` check before running the autoprefixer plugin. It will run in every build mode.
- Added `appearance-none` class to examples to test the components.
- Added `appearance-none` tests, as this is a vendor prefixed css value (this is tested with the -webkit prefix as playwright runs on chrome).
This change wouldn't affect the current docs.

fix: autoprefixer on dev mode for tailwind plugin

---

.changeset/modern-colts-fix.md
packages/astro/src/@types/astro.ts

This re-exports the `AstroCookies` type from the main `@types/astro.ts` type definitions.
**Current import syntax**
```ts
import type { AstroCookies } from "astro/dist/core/cookies/cookies.js"
```
**New import**
```ts
import type { AstroCookies } from "astro"
```
Tested locally
None, typescript fix only

Makes the `AstroCookies` type importable directly from "astro"

---

.changeset/polite-wombats-play.md
.changeset/strange-olives-rest.md
packages/integrations/image/src/lib/get-picture.ts
packages/integrations/image/src/loaders/index.ts

- This fixes #6001, allowing undefined passed as a variable in addition to not passing the property at all
- Updates TransformOptions for @astrojs/image
There may be more places in the integration where this is needed, idk.
I don't think the docs need an update? This is just a change for users w/ `astro/tsconfigs/strictest` enabled

`@astrojs/image`: Allow passing `undefined` to transform options

---

packages/integrations/image/README.md

- Fix local `<Image>` example: `aspectRatio` prop requires a `width` or `height` prop
No tests, README looks fine
Small fix to `<Image>` example

Fix local image example in @astrojs/image README

---

examples/docs/README.md
examples/docs/src/layouts/MainLayout.astro

Match current `src/content/docs/[lang]/...` layout with `edit this Page` url
- https://github.com/withastro/astro/blob/main/examples/docs/src/content/docs/en/introduction.md
Compare
- 404 https://github.com/withastro/astro/blob/main/examples/docs/src/pages/en/introduction.md
- 200 https://github.com/withastro/astro/blob/main/examples/docs/src/content/docs/en/introduction.md
`README` updated accordingly

Fix `edit this Page` on `examples/docs`

---

CONTRIBUTING.md

- Closes #5809
- Adds a section to CONTRIBUTING about the branch structure we use
N/A, doc change only
N/A, doc change only

Add branches info to CONTRIBUTING

---

.changeset/good-items-rest.md
packages/astro/src/@types/astro.ts
packages/astro/src/runtime/server/render/astro/head-and-content.ts
packages/astro/src/runtime/server/render/common.ts
packages/astro/src/runtime/server/render/head.ts
packages/astro/src/runtime/server/render/slot.ts
packages/astro/src/runtime/server/render/types.ts
packages/astro/test/units/render/head.test.js
packages/integrations/mdx/test/css-head-mdx.test.js
packages/integrations/mdx/test/fixtures/css-head-mdx/src/components/HelloWorld.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/layouts/One.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/layouts/Three.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/layouts/Two.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/pages/indexOne.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/pages/indexThree.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/pages/indexTwo.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/pages/testOne.mdx
packages/integrations/mdx/test/fixtures/css-head-mdx/src/pages/testThree.mdx
packages/integrations/mdx/test/fixtures/css-head-mdx/src/pages/testTwo.mdx
packages/integrations/mdx/test/fixtures/css-head-mdx/src/test.mdx

- This simplifies conditional head injection, fixing a lot of bugs related to CSS being out of place when using multiple levels of layouts with slots.
- Instead of rendering the head to a string in place, calls to renderHead and maybeRenderHead now instead yield out an instruction. At the page level this instruction is checked and if the head hasn't been rendered it will be.
- This means that head rendering is handled at the page level. This is the same mechanism used to inject the client directives and that seems to have worked well.
- Fixes https://github.com/withastro/astro/issues/5715
- Fixes https://github.com/withastro/astro/issues/5834
- Unit tests added for multiple levels of layouts, including layouts that do not include explicit head tags.
N/A, bug fix

Simplified head injection

---

.changeset/neat-actors-switch.md
packages/astro/src/vite-plugin-astro/compile.ts

- Closes #5922
- Fixes some problems with our error handling in `dev`. We "enhance" compiler errors by doing a second `esbuild` pass for possible frontmatter errors, but there were two problems here:
1. We weren't checking if the error actually came from the frontmatter first.
2. `esbuild` doesn't support top-level return (for obvious reasons) so any code using `return Astro.redirect()` would always fail with this message. As a fix, we now replace all instances of `return` with `throw` before scanning with `esbuild`.
Tested manually as the exact error messages here are subject to change
QoL improvement only

Improve top-level return error

---

.changeset/long-boats-perform.md
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/test/directory.test.js

- Fixes https://github.com/withastro/astro/issues/6018
- Test added
N/A, bug fix

Fix Cloudflare directory mode regression

---

.changeset/happy-fireants-occur.md
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/runtime/server/astro-component.ts

- Previously, the dev server completely crashed when doing something like
```astro
---
import Foo from '../components/Foo.astro';
// Called directly via function call
console.log(Foo())
---
// Called inside an expression without `<Foo />` syntax
{items.map(Foo)}
```
- This PR fixes this situation by validating the input arguments before attempting to render
- If the arguments are invalid, we now throw a new `InvalidComponentArgs` error with helpful info
- 
Tested manually since this is a smaller one. Can add a test if needed

Handle invalid argument errors

---

.changeset/chilly-ads-roll.md
packages/integrations/image/src/lib/get-picture.ts

`getPicture()` returns an object with the `GetPictureResult` interface.
This PR changes the `image` key type of that interface from `astroHTML.JSX.HTMLAttributes` to `astroHTML.JSX.ImgHTMLAttributes` .
`astroHTML.JSX.ImgHTMLAttributes` is the type set initially in the body of the `getPicture()` function and the return type for the `getImage()` function
https://github.com/withastro/astro/blob/dc2496f702e3b1b575a74c65db93f484ef95d097/packages/integrations/image/src/lib/get-picture.ts#L68
No changes needed

Fix `GetPictureResult` interface

---

.changeset/clever-panthers-end.md
packages/astro/src/core/errors/dev/vite.ts
packages/astro/src/core/errors/overlay.ts

Added ability to display an error's [`cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) if available. Closes #6027
Tested in a local project by changing code inside node modules.
Test fixture currently pending.
Not needed I think? I guess we could document how to use the `cause` property.

error overlay: show `cause` if available

---

packages/astro/src/core/errors/errors-data.ts

- Fixes rendering in the error reference in docs where otherwise MDX tries to render `<MyAstroComponent>` as an actual component.
- Unblocks https://github.com/withastro/docs/pull/2518/
Docs only
/cc @withastro/maintainers-docs @Princesseuh for feedback!

Wrap tag in example error message in code backticks

---

packages/integrations/image/README.md

Show correct usage or `getImage` function.
When providing a string to the `getImage` function, it is taken as a remote image. To use local images we need to import them.
We need to provide `alt` too as it's required
N/A docs change only
Docs change to match correct usage

Correct usage of `getImage` function

---

.changeset/orange-carpets-greet.md
packages/integrations/mdx/src/plugins.ts

- Load syntax highlighters after MDX remark plugins. This keeps MDX consistent with Astro's markdown behavior.
Manual testing in astro/docs repo. Broke during 2.0 migration!
N/A

[MDX] Syntax highlighting after user plugins

---

packages/integrations/image/README.md

Add required `alt` prop to `<Picture>` example
[Docs for `alt`](https://docs.astro.build/en/guides/integrations-guide/image/#alt)
No tests, change to docs
Update example with required prop

Add required `alt` to Picture example

---

packages/astro/src/core/errors/errors-data.ts

Added JSDOC `@message` param to `InvalidContentEntrySlugError` & `ContentSchemaContainsSlugError` errors to fix their generated docs pages.
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/61414485/215871073-70d90877-d76a-4851-b013-5ad414decf77.png) | ![image](https://user-images.githubusercontent.com/61414485/215871716-7446b969-eb04-458c-bab4-03bc5f7baf90.png) |
| ![image](https://user-images.githubusercontent.com/61414485/215871862-fe326524-ff63-48a7-84be-bdc3790b5949.png) | ![image](https://user-images.githubusercontent.com/61414485/215871965-a49cc2c4-2bfd-4bc7-8055-8fe49a3fe59c.png) |
The function we use in docs to extract the error messages from this file expects functions to follow this style:
```ts
message: (params: string) …
```

Add JSDOC `@message` param to broken error pages

---

.changeset/curvy-owls-grow.md
packages/astro/src/runtime/server/render/common.ts
packages/astro/src/runtime/server/render/component.ts

- fix small issue in SSR mode #5915
- this is not fixing the Solid build for vercel, so for Solid it will still state something like `Error: Pa is not supported in the browser, returning undefined` that is a vercel adapter issue only and we need to update the build steps there.
Tested example applications for react and solid on vercel.

fix: Failed to execute 'encode' on 'TextEncoder': parameter 1 is not of type 'String' in Edge Runtime SSR

---

.changeset/heavy-tomatoes-know.md
packages/astro/src/content/internal.ts
packages/astro/src/content/vite-plugin-content-assets.ts
packages/astro/test/content-collections-render.test.js
packages/astro/test/fixtures/content/src/components/H2.astro
packages/astro/test/fixtures/content/src/content/blog/promo/launch-week-components-export.mdx
packages/astro/test/fixtures/content/src/pages/launch-week-components-export.astro

- Resolves #6032
- Apply MDX `components` export as a prop when rendering
- Chore: clean up error messages
- Add tests for SSG, SSR, and dev
N/A

[Content collections] Apply MDX components on render

---

.changeset/wild-seas-happen.md
packages/integrations/vercel/src/edge/adapter.ts

- A second build step has been added to allow the separation of framework and library builds
- Resolves #5915 
With the example react and solid projects from the repo.

fix: solidjs integration for vercel edge build (adopting same mechanics as cloudflare)

---

.changeset/cold-maps-wash.md
packages/integrations/solid/package.json
pnpm-lock.yaml

- Since [vitefu started supporting Vite 4](https://github.com/svitejs/vitefu/releases/tag/v0.2.3), and astro package itself [uses vitefu@0.2.4](https://github.com/withastro/astro/blob/main/packages/astro/package.json#L151), this PR should bump it as well in @astrojs/solid to avoid peerDep warning.
- No tests needed, Vite4 is already being installed for astro V2
- No docs needed, just a package patch bump.

chore: bump vitefu for @astrojs/solid-js

---

.changeset/lucky-hounds-rhyme.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/render/result.ts
packages/astro/src/runtime/server/jsx.ts
packages/astro/src/runtime/server/render/astro/factory.ts
packages/astro/src/runtime/server/render/common.ts
packages/astro/src/runtime/server/render/head.ts
packages/astro/src/runtime/server/render/slot.ts
packages/astro/src/runtime/server/render/util.ts
packages/integrations/mdx/test/css-head-mdx.test.js

- MDX components rendering to strings and not to a stream. That means the technique introduced in https://github.com/withastro/astro/pull/6034 which relies on messaging order doesn't prevent head from being injected into the body when using a typical MDX + slot setup.
- This new change uses the concept of a "scope", this way we know if we are rendering inside of a JSX component (MDX) that contains a layout. If we are inside of both of these things we know that we don't need to emit the head because it will be done so by the layout itself.
- Fixes https://github.com/withastro/astro/issues/6057
- Had an existing test which didn't correct test that the head content was inside of the head tag. This fixes that.
N/A, bug fix

Prevent eager rendering of head content in multi-level MDX layout

---

.changeset/shy-cats-heal.md
packages/integrations/node/package.json
packages/integrations/node/src/http-server.ts
packages/integrations/node/src/index.ts
packages/integrations/node/src/server.ts
packages/integrations/node/src/standalone.ts
packages/integrations/node/test/fixtures/prerender/package.json
packages/integrations/node/test/fixtures/prerender/src/pages/one.astro
packages/integrations/node/test/fixtures/prerender/src/pages/two.astro
packages/integrations/node/test/prerender.test.js
pnpm-lock.yaml

- Fixes https://github.com/withastro/astro/issues/6093
- When serving static files remove the query param.
Prerendering tests added, including this scenario
N/A, bug fix

Node adapter: handle prerendering and serving with query params

---

.changeset/lemon-flies-clean.md
packages/astro/src/vite-plugin-scanner/index.ts

Fix https://github.com/withastro/astro/issues/6058
According to https://rollupjs.org/plugin-development/#transform, returning `map: null` means `code` doesn't change and preserve the current sourcemap. This PR adds the `map: null` as it's the case for us.
Manual testing in basics example.
n/a. bug fix.

Fix scanning sourcemap handling

---

packages/astro/src/content/vite-plugin-content-assets.ts
packages/astro/src/core/build/plugin.ts
packages/astro/src/core/build/plugins/index.ts
packages/astro/src/core/build/plugins/plugin-alias-resolve.ts
packages/astro/src/core/build/plugins/plugin-analyzer.ts
packages/astro/src/core/build/plugins/plugin-css.ts
packages/astro/src/core/build/plugins/plugin-hoisted-scripts.ts
packages/astro/src/core/build/plugins/plugin-internals.ts
packages/astro/src/core/build/plugins/plugin-pages.ts
packages/astro/src/core/build/plugins/plugin-prerender.ts
packages/astro/src/core/build/plugins/plugin-ssr.ts
packages/astro/src/core/build/plugins/util.ts
packages/astro/src/core/build/static-build.ts
packages/astro/src/core/build/types.ts

- The refactors the static build a bit so that our Vite plugins are organized a bit more and follow a conventional API.
- Adds the ability to do post-build processing. This is needed for https://github.com/withastro/astro/pull/6047 and is something we already do for SSR. This PR aims to formalize the process so it's easier to add this sort of thing in the future when needed.
- This is a refactor and doesn't change functionality.
N/A

Refactor build into plugins

---

examples/basics/README.md
examples/blog/README.md
examples/component/README.md
examples/deno/README.md
examples/docs/README.md
examples/framework-alpine/README.md
examples/framework-lit/README.md
examples/framework-multiple/README.md
examples/framework-preact/README.md
examples/framework-react/README.md
examples/framework-solid/README.md
examples/framework-svelte/README.md
examples/framework-vue/README.md
examples/hackernews/README.md
examples/integration/README.md
examples/minimal/README.md
examples/non-html-pages/README.md
examples/portfolio/README.md
examples/with-markdown-plugins/README.md
examples/with-markdown-shiki/README.md
examples/with-mdx/README.md
examples/with-nanostores/README.md
examples/with-tailwindcss/README.md
examples/with-vite-plugin-pwa/README.md
examples/with-vitest/README.md

I originally sent in this PR https://github.com/withastro/astro/pull/5322 which added "Open with CodeSandbox" to Astro templates. The old link would open these templates in sandboxes that use browser capabilities and might be limiting for users at scale.  
This PR opens the templates as a  [CodeSandbox repository](https://codesandbox.io/docs/learn/repositories/overview)  which run on micro VMs and provide a much better experience for users in terms of scale and capabilities. This is the recommended experience from CodeSandbox.
Learn more about [Cloud sandboxes](https://codesandbox.io/blog/a-unified-codesandbox-experience)
CodeSandbox Astro template also runs as a   [CodeSandbox repository](https://codesandbox.io/docs/learn/repositories/overview)
- Be short and …

Update open with CodeSandbox link to use synced sandboxes

---

.changeset/grumpy-bees-worry.md
packages/astro/src/content/types-generator.ts
packages/astro/src/content/utils.ts
packages/astro/src/content/vite-plugin-content-imports.ts
packages/astro/test/units/content-collections/get-entry-type.test.js

- Resolves #6031 
- Check for underscores `_` anywhere in directory path, not just the file name
- Add "always ignore" list with `.DS_Store`
- `getEntryType` unit tests
N/A

[Content collections] Fix "underscore to ignore" warnings

---

.changeset/gorgeous-mails-sniff.md
packages/astro/src/core/render/paginate.ts

- Fixes an outdated error message
- Closes #6000. There's a feature request here as well, but we can move that to the https://github.com/withastro/roadmap repo where other feature requests go.
- N/A
- N/A

Fix outdated error message in paginate() function

---

.changeset/neat-taxis-thank.md
examples/basics/src/components/Card.astro

Card component has uneven border on hover, and in some cases the border is visible even when not hovering. This commit fixes those two issues. 
<details>
<summary>uneven border</summary>
</details>
<details>
<summary>background visible even when not hovering</summary>
See the right border, a thin line appears when not hovering
</details>
For the example Card component styling, the following was changed:
* increase border size slightly so symmetry can be achieved
* hide background image and only show it on hover
<details>
<summary>appearance after fix</summary>
</details>
No tests added, this is a css change for one of the example components.
No docs added, this is a css change for one of the example components.

fix example Card component style

---

packages/webapi/src/ponyfill.ts

When I tried this in my original Node 14 PR, it didn't work... but now it seems like it does? I don't really get it 🤔
Current test covers this
N/A

fix(webapi): Polyfill with undici imports directly

---

.changeset/shaggy-pianos-sleep.md
packages/astro/src/content/index.ts
packages/astro/src/content/vite-plugin-content-assets.ts
packages/astro/src/core/build/graph.ts
packages/astro/src/core/build/page-data.ts
packages/astro/src/core/build/plugins/index.ts
packages/astro/src/core/build/plugins/plugin-analyzer.ts
packages/astro/src/core/build/plugins/plugin-css.ts
packages/astro/src/core/build/static-build.ts
packages/astro/src/core/build/types.ts
packages/astro/test/content-collections-render.test.js

- Replacement for https://github.com/withastro/astro/pull/6047
- Unskipped previously failing test
N/A

Fix hoisted script propagation in content collection pages

---

.changeset/breezy-worms-retire.md
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/core/render/paginate.ts

This PR moves the error message in the `paginate()` function into `AstroErrorData` for consistency.
Manually tested using the `blog` demo project. Can add test file if necessary.
I haven't been terribly creative and have kept the error message as is. However I believe that this refactor means that it will appear on the docs so I would appreciate some eyes on this from the doc team 🙏

Move pagination error to AstroErrorData

---

examples/portfolio/src/components/ThemeToggle.astro

Fixed keyboard accessibility for the Portfolio example's ThemeToggle.
Making the focus outline transparent for the ThemeToggle button “except for Windows High Contrast Mode” makes this component inaccessible to keyboard users. Removing the CSS declaration allows the default focus outline to show.
The example previously failed WCAG 2.4.7 Focus Visible (Level A in WCAG 2.2).
Before (with Chrome DevTools open):
After (focus is on the ThemeToggle button):
Tested locally with the keyboard in-browser before and after the change. I also ran the e2e tests but all the failures looked unrelated (framework/cross-platform errors).

fix(portfolio): keyboard a11y for ThemeToggle

---

.changeset/lazy-plums-sit.md
packages/integrations/image/components/index.ts

fix: #5979

---

.changeset/bright-dryers-attend.md
.changeset/good-wolves-remain.md
packages/astro/e2e/fixtures/lit-component/src/components/ClientOnlyComponent.js
packages/astro/e2e/fixtures/lit-component/src/pages/index.astro
packages/astro/e2e/lit-component.test.js
packages/astro/src/runtime/server/render/component.ts
packages/integrations/lit/src/client.ts

(note: I formatted `integrations/lit/src/client.ts` so the diff is uggo. [Try `?w=1`](https://github.com/withastro/astro/pull/6111/files?w=1)
- Add `@astrojs/lit` to probable renderers list
- Lit's client.js
- Renders custom element in `client:only`
- Renders slots and re-adds `slot="..."` to slotted HTML strings
- sets properties & attributes on custom element
I added the widely-used client:only test to the lit e2e tests and added slot & shadow dom-specific tests.
Add Lit to the [`client:only` docs](https://docs.astro.build/en/reference/directives-reference/#clientonly)

 [Lit] add `client:only` functionality to Lit integration

---

.changeset/tidy-buses-mate.md
packages/integrations/image/components/Picture.astro

In `packages/integrations/image/components/Picture.astro` on line 44, `{...image}` already includes the `alt` attribute, so including it again creates a duplicate which causes the output to fail HTML validation: `<img alt="" alt="" ...`
Removing `{alt}` (see changes below) solves the problem.
Do you really want to add a test to test for duplicate attributes? The current tests should confirm that the `alt` attribute is not missing, which should be sufficient to prove that the `{alt}` code mentioned above was superfluous.
I ran the tests (thank you for using pnpm!) and they passed. I'm sure you'll run them, too.
There is no reason for this to be discussed in the docs. It's a simple mistake, and this PR fixes it.

Fix duplicate alt attribute on Picture component.

---

packages/integrations/node/README.md

Adding astrojs/node + Fastify minimal code example to the docs, with the same functionality as express example has.
Will be automatically generated inside docs repo.

update node integration README with Fastify code example

---

.changeset/happy-dragons-invite.md
packages/astro/src/core/build/graph.ts
packages/astro/test/css-order-import.test.js
packages/astro/test/fixtures/css-order-dynamic-import/package.json
packages/astro/test/fixtures/css-order-dynamic-import/src/components/One.astro
packages/astro/test/fixtures/css-order-dynamic-import/src/components/Three.astro
packages/astro/test/fixtures/css-order-dynamic-import/src/components/Two.astro
packages/astro/test/fixtures/css-order-dynamic-import/src/pages/one.astro
packages/astro/test/fixtures/css-order-dynamic-import/src/pages/two.astro
packages/astro/test/fixtures/css-order-dynamic-import/src/styles/One.css
packages/astro/test/fixtures/css-order-dynamic-import/src/styles/base.css
pnpm-lock.yaml

- Fixes https://github.com/withastro/astro/issues/5676
N/A, bug fix

Take dynamic imports into account for CSS ordering

---

.changeset/tame-poems-walk.md
packages/astro/src/core/build/generate.ts
packages/astro/test/api-routes.test.js
packages/astro/test/fixtures/api-routes/src/pages/binary.dat.ts
packages/astro/test/test-utils.js

- Fixes https://github.com/withastro/astro/issues/5725
Test added
N/A

Allow binary data to be returned from api routes in SSG

---

.changeset/late-poets-own.md
packages/astro/src/content/vite-plugin-content-assets.ts
packages/astro/test/content-collections.test.js
packages/astro/test/fixtures/content-collections-base/astro.config.mjs
packages/astro/test/fixtures/content-collections-base/package.json
packages/astro/test/fixtures/content-collections-base/src/components/One.astro
packages/astro/test/fixtures/content-collections-base/src/content/config.ts
packages/astro/test/fixtures/content-collections-base/src/content/docs/one.mdx
packages/astro/test/fixtures/content-collections-base/src/pages/docs.astro
pnpm-lock.yaml

- Ensures `base` config taken into consideration for links in content collections rendered pages.
- Fixes https://github.com/withastro/astro/issues/6133
N/A, bug fix

Ensure base configuration appended to content collection styles

---

.changeset/calm-readers-learn.md
packages/astro/src/core/render/paginate.ts
packages/astro/test/astro-pagination-root-spread.test.js
packages/astro/test/fixtures/astro-pagination-root-spread/package.json
packages/astro/test/fixtures/astro-pagination-root-spread/src/pages/[...page].astro
pnpm-lock.yaml

- Closes #6147
- Closes https://github.com/withastro/docs/issues/2517
- When we're in "spread mode" (i.e., `includesFirstPageNumber` is set to `false`), and we're returning the `prev` value that refers to the first page, return an empty string. This gets `/` appended to it.
Previously, we returned `undefined`, which caused the bug.
- Created an `astro-pagination-root-spread` test fixture
Removes the need for [#2517](https://github.com/withastro/docs/issues/2517)

Fix root directory spread pagination `url.prev` for first page

---

.changeset/sixty-scissors-refuse.md
packages/astro/astro-jsx.d.ts

- Add `string` type to `border` attribute for `TableHTMLAttributes`
- Add `'false' | 'true'` types to `frame` attribute for `TableHTMLAttributes`
Thanks @Princesseuh  for helping
**What does this change?**
Fix types for TableHTMLAttributes
I am not sure if this needs testing
I don't think this adds or changes any docs

Fix types for TableHTMLAttributes

---

.changeset/great-mails-agree.md
packages/astro/components/Shiki.js
packages/astro/test/units/shiki/shiki.test.js

- Fixes https://github.com/withastro/astro/issues/6174
- Created some unit tests for this, so we can better test how we generate options in the future.
N/A, bug fix

Fixes usage of Code component in Vercel

---

.changeset/tasty-planes-knock.md
packages/astro/src/core/dev/dev.ts
packages/astro/src/core/dev/restart.ts

- Fixes #5985
- We would persist the `flags` between restarts, but the new container did not read from `--root` and always read the initial `resolvedRoot` instead.
- This PR updates it so that CLI restarts read from `--root` and fallback to `resolvedRoot` if necessary
Tested manually since this is a hard one to automate

Preserve `--root` CLI flag on restart

---

.changeset/lazy-coins-compete.md
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/test/directory.test.js

Fixes https://github.com/withastro/astro/issues/6206
Make sure the `[[path]].js` file is generated inside the `functions` folder in cloudflare.
Assertion on a test has been added
I don't think it has an impact

Fix 6206: Cloudflare function path resolving one step above

---

.changeset/eight-cameras-itch.md
packages/astro/src/runtime/server/render/common.ts
packages/astro/test/fixtures/head-injection/src/components/UsesSlotRender.astro
packages/astro/test/fixtures/head-injection/src/pages/with-render-slot-in-head-buffer.astro
packages/astro/test/head-injection.test.js
packages/integrations/mdx/test/css-head-mdx.test.js
packages/integrations/mdx/test/fixtures/css-head-mdx/src/components/BaseHead.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/components/GenericComponent.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/components/MDXWrapper.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/content/posts/using-component.mdx
packages/integrations/mdx/test/fixtures/css-head-mdx/src/layouts/ContentLayout.astro

- Fixes case where `Astro.slots.render()` is called within head buffering. Prevents head content from being rendered in the body instead of the head.
- Closes https://github.com/withastro/astro/issues/6185
- Closes https://github.com/withastro/astro/issues/6214
N/A, bug fix

Fix head injection in body with slots.render() and head buffering

---

packages/integrations/cloudflare/README.md

- two small typo fixes to the Cloudflare integration README ("you" -> "your" and a missing "to")
No tests, docs typo fixes
only docs! README fixes.

[docs] README typo fixes

---

.changeset/orange-sheep-deliver.md
packages/astro/src/content/utils.ts

Refactor: Remove legacy code that separated the dir and stitched back together. This caused a user issue when parsing the URL under `isOnIgnoreList` (sadly unable to reproduce in a test environment).
N/A - refactor

Fix `getEntryType` failure on spaces in file name

---

.changeset/orange-chicken-end.md
packages/integrations/preact/src/client.ts

- Fix hydration mismatches by using the 3rd argument form of render().
- This provides the `<astro-island>` as wrapped as a Preact component, for the same of guaranteeing a root match in render. Doing this ensures that children will all be fixed in case of a mismatch.
- Fixes https://github.com/withastro/astro/issues/5937
- Tested in the demo app. An automated test is not really possible as it takes CPU throttling to recreate.
https://user-images.githubusercontent.com/361671/218183429-09d0ba58-e7de-44a3-8e83-0a918a106448.mp4
N/A, bug fix

Prevent hydration mismatches in Preact

---

.changeset/selfish-frogs-tell.md
packages/astro/e2e/fixtures/solid-circular/astro.config.mjs
packages/astro/e2e/fixtures/solid-circular/package.json
packages/astro/e2e/fixtures/solid-circular/src/components/ContextProvider.tsx
packages/astro/e2e/fixtures/solid-circular/src/components/SimpleDiv.tsx
packages/astro/e2e/fixtures/solid-circular/src/env.d.ts
packages/astro/e2e/fixtures/solid-circular/src/pages/index.astro
packages/astro/e2e/solid-circular.test.js
packages/astro/src/core/render/dev/environment.ts
packages/astro/src/core/render/dev/resolve.ts
packages/astro/src/core/util.ts
pnpm-lock.yaml

Fix #6014 
Ensure we load hydration URLs from `/src/Component.jsx`, instead of `/@fs/...`. This is because Vite's import analysis would import from `/src/Component.jsx` instead if a circular import happens. Keeping the same path deduplicates them so only one exist at a time.
Added a test following the repro's case
n/a. bug fix.

Fix hydration path for circular imports

---

.changeset/moody-cats-train.md
packages/integrations/mdx/package.json
packages/integrations/mdx/src/index.ts
packages/integrations/mdx/test/mdx-plugins.test.js
pnpm-lock.yaml

Fix https://github.com/withastro/astro/issues/5796
Thanks to https://github.com/mdx-js/mdx/pull/2255, there's a way to properly render namespaced attributes injected by rehype plugins, without Astro needing to manually map camelCase namespaced attributes, to the normal ones.
With this PR, Astro should render `<use xlink:href` instead of `<use xlinkhref`
Added test to mdx integration
n/a. bug fix.

Support rehype plugins that inject namespaced attributes

---

.changeset/curvy-snakes-turn.md
packages/astro/e2e/fixtures/svelte-component/src/components/ToggleSlots.svelte
packages/astro/e2e/fixtures/svelte-component/src/env.d.ts
packages/astro/e2e/fixtures/svelte-component/src/pages/index.astro
packages/astro/e2e/svelte-component.test.js
packages/integrations/svelte/client.js

Fix #5690 
Properly unmount a slot for Svelte integration. Previously it's unimplemented, so conditionally mounting them results to them being "stucked" in the DOM.
added test to toggle slots
n/a. bug fix.

Fix unmount Svelte slots

---

.changeset/afraid-rivers-camp.md
packages/integrations/mdx/src/index.ts
packages/integrations/mdx/test/mdx-plugins.test.js

Quick revert of #6243 as it's breaking and should be done in a minor instead of a patch
n/a
n/a

Revert previous mdx breaking change

---

.changeset/gentle-parrots-cheer.md
packages/integrations/mdx/src/index.ts
packages/integrations/mdx/test/mdx-plugins.test.js

Same as https://github.com/withastro/astro/pull/6243 but will be released in a minor.
Context: https://github.com/withastro/astro/pull/6243#discussion_r1106939451
same as in the linked pr.
n/a. i think this minor change doesn't need a highlight in the docs, given Astro use html by default.

Support rehype plugins that inject namespaced attributes 2

---

.changeset/dull-wasps-decide.md
packages/integrations/vercel/src/edge/adapter.ts
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/src/static/adapter.ts

- Only injects the script for Vercel analytics on `build`
- Vercel’s analytics scripts rely on some extra scripts Vercel injects magically to projects built on their platform but these aren’t available locally so 404 (reported in #6230 along with other stuff)
- Folks likely don’t want to track analytics locally anyway
Philosophical question: is this difference between dev and build OK? Generally differences between the two can trip people up — what if this script interferes with some other part of the project somehow and you only notice in production?
Existing tests should pass. Do we want a test that asserts the script is _not_ included in `dev`?
No docs needed I don’t think.

Only inject Vercel analytics in production

---

packages/integrations/image/README.md

Changed the wording about SVG images when using the `format` property to make it more clear to understand, also exemplifying what's a raster image.
No code changes 😜 
100% docs.

Clarify SVG image gotcha info

---

.changeset/metal-ducks-invite.md
packages/astro/src/core/render/dev/vite.ts
packages/astro/test/content-collections-render.test.js
packages/astro/test/fixtures/content/src/components/LayoutProp.astro
packages/astro/test/fixtures/content/src/content/blog/with-layout-prop.md
packages/astro/test/fixtures/content/src/pages/with-layout-prop.astro

- Resolves #6173 
- Fixes accessive SSR rendering in our module crawler. We attempted to SSR the propagated asset module, which causes Vite to hang.
- Add `layout` prop test with recursive `getCollection()` call

Fix: recursive `getCollection()` hanging

---

packages/astro/src/vite-plugin-astro-server/response.ts
packages/astro/test/ssr-api-route.test.js

Undici 5.19.0 changes how `headers.entries()` return `set-cookies` headers, previously they were merged together and now they're separated. Super weird random change, but people probably smarter than me have debated this and decided that it's okay, I think.
This PR also removes some old code for node-fetch, unnecessary since we don't use it anymore
Tests will pass! Tested manually that this works on Node 16 after the upgrade, the CI on the lockfile PR will also reflect this
N/A

fix(cookies): Fix cookies not being all returned on Node 16 after Undici upgrade

---

.changeset/tall-geese-end.md
packages/create-astro/src/actions/dependencies.ts
packages/create-astro/src/actions/git.ts
packages/create-astro/src/actions/template.ts
packages/create-astro/src/actions/typescript.ts

- Closes #6166
- Tasks that would use the `spinner` display could throw an unhandled exception, but now they'll print the error and exit gracefully (with an error code of `1`).
- Adds a timeout to `npm install` to exit after one minute.

Improve `create-astro` error handling

---

.changeset/good-snails-attend.md
packages/astro-rss/src/index.ts

Add more information to zod error report
When generating a rss feed with the rss function, if one prop of an item is missing, the only feedback will be `Invalid input` without much of _where_ is the invalid input.
I've added a prop on a string based on zod's doc here: https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#zodissue
Not sure if this must be tested.
No doc as well, it's rather enhanced error handling.

fix: add property name to rss errors

---

.changeset/rare-lizards-grin.md
packages/create-astro/package.json
pnpm-lock.yaml

An upstream issue in giget is causing `downloadTemplate` to cause a 400 when hitting GitHub. (see https://github.com/unjs/giget/issues/81 ) Their own CI caught this, but they unfortunately still released the update. This PR pins the version to 1.0.0 in the meantime
Fix https://github.com/withastro/astro/issues/6276
N/A

fix(create-astro): Pin giget to 1.0.0

---

.changeset/breezy-eyes-cheat.md
packages/astro/package.json
packages/integrations/image/package.json
packages/integrations/mdx/package.json
packages/integrations/netlify/package.json
packages/integrations/svelte/package.json
packages/integrations/tailwind/package.json
packages/integrations/vue/package.json
pnpm-lock.yaml

Bump Vite to 4.1, this make sure that everyone that installs Astro today get Vite's 4.1 build perf optimization.
n/a
n/a

Bump Vite to 4.1

---

.changeset/beige-chairs-compare.md
packages/webapi/package.json
pnpm-lock.yaml

- A header change in undici broke set-cookie usage. This breaks the image component currently.
- There is a fix upstream but until that is released, pinning prevents the new version from surfacing.
N/A
N/A

Pin undici

---

.changeset/shaggy-moons-judge.md
examples/deno/package.json
examples/deno/src/pages/index.astro
packages/integrations/deno/package.json
packages/integrations/deno/src/__deno_imports.ts
packages/integrations/deno/src/index.ts
packages/integrations/deno/src/server.ts
packages/integrations/deno/test/basics.test.ts
packages/integrations/deno/test/fixtures/basics/src/pages/prerender.astro

- Follow-up to https://github.com/withastro/astro/pull/6281, https://github.com/withastro/astro/pull/6248
- https://github.com/withastro/astro/pull/6248 was reverted because it special-cased Deno in `core` and caused some issues in practice.
- This PR takes a different approach by providing a shim for Deno-specific imports in Node so that pages can be prerendered, then replacing that shim with the actual Deno imports for the production server.
- Also switches to Deno's `std` `serveFile` function which can serve the file without loading the file into memory for optimal performance 🔥
Test added

Fix prerendered page handling on Deno

---

.changeset/shiny-years-beg.md
packages/integrations/sitemap/src/generate-sitemap.ts
packages/integrations/sitemap/src/index.ts

ATM if you wish to configure the integration in a typescript file like so you get an error :
```ts
/* ... */
sitemap({
changefreq: 'daily' // Type '"daily"' is not assignable to type 'EnumChangefreq | undefined'. ts(2322)
})
/* ... */
```
This is due to how enums (and types made from enums) work in typescript. 
To get it working the user has to use an `as ChangeFreq` which isn't great.
```ts
changefreq: 'daily' as ChangeFreq
```
Or he can access `EnumChangefreq` by adding `sitemap` as a project dependency
```ts
changefreq: EnumChangefreq.DAILY
```
I'm not a big fan of it since `sitemap` is a dependency of this integration (could lead to version mismatch).
---
I'd like to get autocomplete without risking an version mismatch, to do so I thought of two solutions :
- re-exporting the …

update `ChangeFreq` to support typescript configurations with string literal

---

packages/astro/src/core/errors/errors-data.ts

We still generate docs links for unknown errors, so we should have documentation for them!
N/A
It's docs all the way down!

Add documentation for unknown errors

---

.changeset/kind-cameras-type.md
packages/astro/src/content/server-listeners.ts

Warn about setting the `allowJs` compiler option only when the `content` directory exists.
Tested locally
N/A fixes unexpected warning

fix(content-collections): warn about `allowJs` only when `content` directory exists

---

packages/integrations/image/README.md

- Addresses https://github.com/withastro/docs/issues/2620
- Makes it clear that images in `/path` are treated like remote images by the integration
Just docs!

Docs: Image README clarifications

---

examples/blog/src/components/HeaderLink.astro

- Use `import type` for `HTMLAttributes` in the "Headerlink" component from Blog examples. This conforms with docs examples [Typescript: Built-in HTML attributes](https://docs.astro.build/en/guides/typescript/#built-in-html-attributes)
No tests added. Change only affect examples.

Fix import of type HTMLAttributes in blog example

---

.changeset/rare-pumpkins-end.md
packages/create-astro/README.md
packages/create-astro/src/actions/help.ts

- `create-astro` help info add `--typescript` flag
No tests. Just help info.
README updated.

`create-astro` help info add `--typescript` flag

---

.changeset/great-colts-accept.md
packages/create-astro/src/index.ts

This ensures the initialized repository has all configuration changes commited in the first commit
Changes the order of the `create-astro` interactive steps.  Previously, it would run `git init`, `git add`, `git commit` *before* prompting for which tsconfig schema the project would use.  If `strict` or `strictest` are selected, this would mean that `tsconfig.json` would then be modified, and the initial repo is dirty.
pnpm install && pnpm build && pnpm test: All (47) tests passed.
There could likely be an additional test for this, though I'm not entirely sure how to start writing tests for this ATM.
Docs should not be needed.
Only affects ordering of the interactive script. Anyone using create-astro programmatically should be using the CLI --flags

[create-astro] Execute the 'git' step as the final interaction

---

examples/docs/src/content/docs/en/introduction.md

Using the `docs` template, the `src/content/docs/en/introduction.md` file references a non-existent `#ideas-and-suggestions` channel in the Discord server.  New comment is more "future-proof"
N/A (docs body change)
N/A (change to docs template md)

fix(examples/docs): future-proof Discord link

---

.changeset/lucky-flowers-wonder.md
packages/integrations/mdx/CHANGELOG.md
packages/integrations/mdx/package.json
packages/integrations/mdx/src/index.ts
pnpm-lock.yaml

Updated es-module-lexer to 1.1.1 in MDX integration using new API.
Standard astro test suite passed.
It's only a internel package update with modified API usage.

Update MDX integration to es-module-lexer@1.1.1

---

.changeset/six-crabs-hunt.md
packages/astro/src/vite-plugin-astro-server/response.ts
packages/astro/test/astro-cookies.test.js
packages/integrations/image/src/build/ssg.ts

- Related to https://github.com/withastro/astro/pull/6323
- Node 18's `fetch` implementation may have been updated to the broken version of `undici`, so we need to keep this manual workaround for now.
- Once Node 18 is on `undici@5.20.0+` this should be fine to remove?
- **UPDATE**: `18.14.1` is using the outdated version of `undici`, `18.14.2` is fine. We could wait for the CI images to update, but I think this is worth being defensive about.
Covered by existing tests
Bug fix only

Use getSetCookie, if available

---

.changeset/old-fireants-allow.md
packages/integrations/lit/server.js
packages/integrations/lit/test/server.test.js

- Update `@astrojs/lit`’s `server.js` to properly render elements with `shadowRootOptions` that include setting [delegatesFocus](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus) to `true`.
- Logic is based on `@lit-labs/ssr` [latest implementation as found here](https://github.com/lit/lit/blob/b0c3f82ef0f97326a205e77e7e1043b75a5cc53f/packages/labs/ssr/src/lib/render-value.ts#L738-L748)
A test was added to ensure an element with `delegatesFocus` set to `true` has this attribute properly included in the rendered static markup.
No documentation changes are needed. This is expected functionality that currently isn't properly supported by `@astrojs/lit`.

[Lit] render DSD attributes based on `shadowRootOptions`

---

.changeset/orange-cheetahs-hide.md
packages/astro/src/vite-plugin-head-propagation/index.ts
packages/astro/test/fixtures/head-injection/src/components/with-slot-render2/inner.astro
packages/astro/test/fixtures/head-injection/src/components/with-slot-render2/slots-render-outer.astro
packages/astro/test/fixtures/head-injection/src/pages/with-slot-render2.astro
packages/astro/test/head-injection.test.js

- Fixes https://github.com/withastro/astro/issues/6318
- Fixes https://github.com/withastro/astro/issues/6336
- We were mistakenly marking *all* modules as need head propagation. This should only be applied to those that have head propagation in their tree (currently this is only content collection usage).
- New test case added.
N/A, bug fix

Only apply head propagation in trees that need it

---

examples/non-html-pages/README.md

Replace the following dead link:
/en/core-concepts/astro-pages/#non-html-pages
Also, mentions `.js` or `.ts` instead of `.md`,
since this is a non-html-pages example (`.md` are for html pages). 
Update README, thus no tests are added.
This commit itself is a documentation change.

Update doc link in non-html-pages example README

---

packages/create-astro/src/actions/template.ts

Remove duplicate `exit` key from template function.
Manual

fix: remove duplicate exit key from create template

---

.changeset/real-balloons-cough.md
packages/create-astro/src/actions/template.ts

- Closes #6338
- Follow-up to #6357
- Respects `package.json` indentation when updating the `package.json` file
- cc @rishi-raj-jain 

Respect original `package.json` indentation

---

.github/workflows/benchmark.yml
.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/format.yml
.github/workflows/main.yml
.github/workflows/scripts.yml
.github/workflows/snapshot-release.yml

This is a housekeeping PR. It adds the `workflow_dispatch:` to some of our workflows. This enables the possibility to run workflows manually against specific branches. This help us with debugging github actions using a PR. 
This a screenshot of the menu we can have under the actions that have `workflow_dispatch:`
I added the new property only to the workflows that seemed more "internal". Let me know which workflows need to be updated.
After merging the PR, we should see the new dropdown in the workflows that are updated.
N/A

ci: add workflow_dispatch to workflows

---

.changeset/cold-mirrors-joke.md
packages/astro/src/core/create-vite.ts
packages/astro/src/core/sync/index.ts

Recently merged but unreleased change https://github.com/withastro/astro/pull/6368 regresses https://github.com/withastro/astro/pull/6238. Causing docs to fail to build because integrations that updates the Vite config isn't affecting Astro's internal Vite config.
This PR makes `astro sync` to run in `build` mode, meaning plugins with `apply: 'serve'` will not run in `astro sync`. I _think_ this is what https://github.com/withastro/astro/pull/6368 was trying to fix (the issue:  https://github.com/withastro/astro/issues/6364), so this shouldn't be regressing that. And opens up the path for `astro sync` to update Astro's internal Vite config.
cc @userquin 
I made sure the test added in https://github.com/withastro/astro/pull/6368 still passed
n/a. bug fix.

Fix astro sync config merge

---

.changeset/bright-forks-add.md
packages/astro/package.json
packages/astro/src/cli/index.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/build/static-build.ts
packages/astro/src/core/build/types.ts
packages/astro/test/test-utils.js
pnpm-lock.yaml

Use `@astrojs/compiler` `teardown()` API to remove the internal WASM instance and cache after we're finished with the Vite build.
All existing test should pass. `!bench memory` _should_ show an improvement too, but it doesn't because the technique to capture "heap used" includes the garbage collection root (for some reason).
But when testing with docs locally, I can see the optimization working where Vite build memory gets offloaded during rendering.

Teardown compiler to improve rendering perf

---

.github/workflows/benchmark.yml

Chore PR.  Follow up of #6397 
It updates the benchmark workflow to use the same action we use for comments.
cc @bluwy 
I should be able to trigger the action manually and see the message, although I am unsure if that will work. Alternatively, we would need to merge it and then use the magic comment to trigger the benchmark.
N/A

ci: use one action for comments

---

.devcontainer/devcontainer.json

Noticed there was a typo ported over from the original devcontainer with "Codespaces" written "CodeSpaces". I was going to just correct the casing but realized the extra context is probably unnecessary now so instead I just opted to remove it instead.
N/A
N/A

Fix marketing typo by just removing extra info

---

benchmark/bench/server-stress.js
benchmark/package.json
pnpm-lock.yaml

Improve `!bench server-stress` comment output. It should print a nicer markdown table now:
**Before:**
18k requests in 30.05s, 1.23 GB read
**After:**
|         |       Avg |     Stdev |     Max |
| :------ | --------: | --------: | ------: |
| Latency | 680.22 ms | 220.43 ms | 1398 ms |
|           |     Avg |   Stdev |     Min |   Total in 30s |
| :-------- | ------: | ------: | ------: | -------------: |
| Req/Sec   | 1449.54 |   73.74 |    1192 | 43.5k requests |
| Bytes/Sec |  103 MB | 5.24 MB | 84.8 MB |   3.09 GB read |
Tested by running `pnpm benchmark server-stress` locally.
n/a. internal tooling.

Improve server-stress benchmark comment

---

.changeset/lovely-elephants-peel.md
packages/astro/src/core/add/index.ts

- `astro add svelte` will update `astro.config.mjs`, but will generate redundant comments `/ https://astro.build/config`.
None
None

Remove redundant comments when `astro add` update `astro.config.mjs`

---

.changeset/witty-taxis-accept.md
packages/astro/src/core/render/dev/css.ts
packages/astro/test/css-inline.test.js
pnpm-lock.yaml

Fix https://github.com/withastro/astro/issues/6422
Use the [`isBuildableCssRequest`](https://github.com/withastro/astro/blob/9f85fb4ac2430231217e9b02579f596f68736bb7/packages/astro/src/core/render/dev/util.ts#L8) helper instead of [`isCssRequest`](https://github.com/vitejs/vite/blob/a55d0b34400e3360c4100d05e422ae9cf10fa07b/packages/vite/src/node/plugins/splitVendorChunk.ts#L16) so that imported css with `?raw` and `?inline` query suffixes aren't included in the imported styles map and inlined in style tags
- In production:
- Check that there's exactly one link tag
- Check that there's no style tag
- In development, in addition to the previously existing prod tests:
- Check that there's no link tag
- Check that there's exactly one style tag
Bug fix only

Fix `?inline` and `?raw` css query suffixes inlined in style tags in development

---

.changeset/old-rivers-remember.md
packages/astro/src/cli/check/index.ts
packages/astro/src/cli/index.ts
packages/astro/src/cli/telemetry.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/dev/dev.ts
packages/astro/src/core/preview/index.ts
packages/astro/src/core/sync/index.ts

Closes https://github.com/withastro/astro/issues/4935
While the issue was specific to `build` command, the same was valid for other commands.
This PR adds the `--help` flag to all commands. 
I tested manually. At the moment, it would make little sense to have a unit test. At the moment, help output and flags are disconnected, which means that adding a new flag to the logic and not to the help command would make the test still pass.
For the description, I copied the text from the website.
cc @withastro/maintainers-docs

feat(cli): add help flags to various commands

---

packages/astro/src/core/errors/errors-data.ts

Updates a docs link to client-side scripts in prep for Docs reorg PR https://github.com/withastro/docs/pull/2550
- Links to an existing page for Scripts and Event handling instead of a section that will soon no longer exist. (So, no problem to merge before 2550 is merged. New link is already operational in docs.)
No tests, Docs.
Just affects error docs! cc @Yan-Thomas for review!

[error docs] update link for client-side scripts

---

.changeset/wicked-pumpkins-punch.md
examples/images/src/env.d.ts
package.json
packages/astro-prism/tsconfig.json
packages/astro-rss/tsconfig.json
packages/astro/tsconfig.json
packages/create-astro/tsconfig.json
packages/integrations/alpinejs/tsconfig.json
packages/integrations/cloudflare/tsconfig.json
packages/integrations/deno/tsconfig.json
packages/integrations/image/tsconfig.json
packages/integrations/lit/tsconfig.json
packages/integrations/mdx/tsconfig.json
packages/integrations/netlify/tsconfig.json
packages/integrations/node/tsconfig.json
packages/integrations/partytown/tsconfig.json
packages/integrations/preact/tsconfig.json
packages/integrations/prefetch/tsconfig.json
packages/integrations/react/tsconfig.json
packages/integrations/sitemap/tsconfig.json
packages/integrations/solid/tsconfig.json
packages/integrations/svelte/tsconfig.json
packages/integrations/tailwind/tsconfig.json
packages/integrations/turbolinks/tsconfig.json
packages/integrations/vercel/tsconfig.json
packages/integrations/vue/tsconfig.json
packages/markdown/remark/tsconfig.json
packages/telemetry/tsconfig.json
packages/webapi/tsconfig.json
scripts/cmd/build.js

Despite dropping support for Node 14, we were still building for that target. This fixes that.
This is (hopefully) the final nail in the Node 14 coffin, as after this, Astro won't include the downlevelling necessary to run on Node 14 at all
This makes Astro slightly smaller: Before: `794kb` and after: `743kb` and the build slightly faster.
Hopefully the CI pass 🤞 
N/A

Update compilation target for Node 16

---

.changeset/config.json

My recent PR broke changesets (https://github.com/withastro/astro/pull/6433) 😬 This PR reverts the change to the changeset config and it should work again. The downside is that it bumps and generates changelogs for private packages, but I don't think there's a way around it for now.
Tested manually locally with `pnpm changeset version --dry-run` to make sure the error goes away.
n/a. fixes changeset.

Fix changeset run

---

packages/astro/src/core/add/babel.ts
packages/astro/src/core/build/plugins/plugin-internals.ts
packages/astro/src/core/endpoint/index.ts
packages/astro/src/core/render/result.ts
packages/astro/src/jsx/renderer.ts
packages/integrations/deno/src/server.ts
packages/integrations/image/src/endpoint.ts
packages/integrations/image/src/lib/get-image.ts
packages/integrations/image/src/loaders/squoosh.ts
packages/integrations/image/src/vendor/squoosh/codecs.ts
packages/integrations/image/src/vendor/squoosh/image-pool.ts
packages/integrations/image/src/vendor/squoosh/impl.ts
packages/integrations/netlify/test/edge-functions/edge-basic.test.ts
packages/integrations/netlify/test/edge-functions/prerender.test.ts
packages/integrations/netlify/test/edge-functions/root-dynamic.test.ts
packages/integrations/netlify/test/edge-functions/test-utils.ts
packages/integrations/node/src/response-iterator.ts
packages/integrations/preact/src/client-dev.ts
packages/markdown/remark/src/index.ts
packages/webapi/src/lib/Image.ts
packages/webapi/src/lib/utils.ts

This is a maintenance PR. It replaces `@ts-ignore` with `@ts-expect-error`.
The benefit of `@ts-expect-error` is that it tells the compiler that a compiler error is expected in the next line, and **if there isn't any error**, the compiler fails.
This directive is useful in cases the "compiler is not powerful enough", but then a new version comes around and fixes the issue.
The places where `@ts-ignore` was removed were the places where there wasn't a compiler error anymore.
The CI should pass, there's not change in logic.
N/A

chore: use directive `@ts-expect-error` instead of `@ts-ignore`

---

.changeset/eleven-mugs-flash.md
packages/integrations/image/src/build/ssg.ts

The code path changed by this commit isn't only taken when running using Vite. If the site is configured with a base url which is different from `/` but does **not** end with `/` (for example, because `trailingSlash` is set to `never`), the `- 1` results in an off-by-one error when truncating the URL.
By checking if the base url ends with `/`, we can determine the right length for the prefix to truncate.
Tested manually on a repository which exhibited the issue:
- With `config.base == '/'`, before change: working
- With `config.base == '/pr-preview/pr-5'`, before change: error messages in the log indicate that the integration is looking for files beginning with `5/path/to/the/image`
- With `config.base == '/'`, after change: working
- With `config.base == '/pr-preview/pr-5'`: after …

[@astrojs/image] Handle missing trailing slash in processStaticImage

---

examples/blog/src/components/BaseHead.astro

A reader of my blog [pointed out](https://github.com/chromakode/blog/issues/1#issuecomment-1447341669) that I was missing an [RSS discovery](https://www.petefreitag.com/item/384.cfm) `<link>`. When I opened this repo looking for an example, I noticed it was missing one too. Here's a quick addition.

Add RSS feed discovery link to head

---

packages/integrations/sitemap/README.md

Closes #6416 
Only changes the `@astrojs/sitemap` readme
Documents how to correctly link the sitemap, may need a look-over to see if the wording/placement can be improved.

Add instructions on how to link the sitemap

---

.changeset/cyan-readers-wonder.md
packages/astro/src/@types/astro.ts

- Adds documentation for the `image.service` config option
- Adds the `@docs` tag to include the “Experimental Flags” heading in docs
n/a docs only
/cc @Princesseuh for feedback on how I documented `image.service`

Fix configuration reference docs

---

.changeset/clever-laws-lie.md
packages/astro/src/assets/services/service.ts
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/src/core/errors/errors-data.ts
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image/src/assets/penguin.svg
packages/astro/test/fixtures/core-image/src/pages/unsupported-format.astro

We don't support optimizing SVGs at this time, however, supporting the new ESM shape for them is in scope.
Added a test for refusing unsupported formats.
N/A, the docs actually already wrongly documented that SVGs were supported 😅

Add support new `astro:assets` ESM import shape for SVGs 

---

.changeset/smart-crews-swim.md
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/src/core/util.ts
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image/src/pages/regular-img.astro

- Fixes ESM imported assets to be root relative instead of using a file URL. This means they can be used with a normal `<img>` tag.
N/A, bug fix

Fixes ESM imported assets to be root relative

---

.changeset/red-candles-retire.md
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/test/core-image.test.js

- In https://github.com/withastro/astro/pull/6465 changed to using root-relative paths for ESM imported images.
- Caused regression b/c the dev server middleware expected a file path.
- Added a test that exposes this.
- Tested in example path with dev + build now working.
N/A, bug fix

Fix asset loading in dev mode

---

.changeset/tough-tigers-drum.md
packages/astro/src/core/add/index.ts
packages/integrations/lit/README.md

Fix https://github.com/withastro/astro/issues/6444
Lit dependencies need to be hoisted to work at the meantime. This PR surfaces this requirement in a few more places.
Currently it doesn't edit the `.npmrc` if there's an existing one, but I think this would be enough for now.
Tested the CLI manually in the examples folder. Confirmed that it works for pnpm only.
Updated the lit integration readme to note this workaround in its troubleshooting section.

Add default .npmrc for `astro add lit`

---

.changeset/popular-rules-divide.md
packages/astro-rss/README.md
packages/astro-rss/src/index.ts
packages/astro-rss/src/util.ts
packages/astro-rss/test/rss.test.js

Closes https://github.com/withastro/astro/issues/6427
The PR adds a new option called `trailingSlash`, in line with the option we have in our config.
This option is useful for having links that are in line with the sitemap.
_Current tests should pass_, to keep the existing behaviour. Added a new test case.
Updated the `README.md` with the new option.

feat(rss): add option to remove the trailing slash

---

examples/docs/src/components/LeftSidebar/LeftSidebar.astro

- Fix left sidebar group titles css.
*Before*
*After*
> Another way to fix this would be to use the `heading` class defined in `examples/docs/src/styles/index.css` that is equivalent to `nav-group-title` and is used in the right sidebar. This would avoid having duplicate code, but would couple heading styles in left and right sidebars.
- tested manually, minor visual fix.
- no new docs needed.

fix(examples/docs): Styles for left sidebar's group titles are not applied.

---

packages/integrations/sitemap/README.md

Switch syntax highlighting to yaml in docs
replaces <https://github.com/withastro/docs/pull/2812>
Doesn't need te be tested
doesn't need docs

Get rid of ‘txt not found’

---

.changeset/tall-taxis-exercise.md
packages/astro/src/core/create-vite.ts

Fixes https://github.com/withastro/astro/issues/6402
Firstly, I don't like what I'm doing, but it's the best solution at the mean time 😬 
This PR makes `astro` add `prismjs/components/index.js` to `vite.ssr.external` in dev time to fix using `@astrojs/prism` in a pnpm setup.
This is needed because while we do [automatic externalizing](https://github.com/withastro/astro/blob/0438458d530fb6dfdff63b89a2cb58a04fabe699/packages/astro/src/core/create-vite.ts#L67-L97) of transitive deps of Astro libraries, in which case we externalize `prismjs` by default, `prismjs/components/index.js` is not covered. In this case, when Vite decides whether to `external` or `noExternal` this import, it checks whether it's import-able from the project root. With pnpm, it's not, so it gets `noExternal` and that …

Fix `@astrojs/prism` edgecase with pnpm

---

packages/astro/package.json

Add `pnpm run postbuild` to the `build:ci` command as `vite-ecosystem-ci` uses that and there's wasm copying errors currently. This should fix it.
n/a
n/a. internal command change.

Add postbuild to build:ci command

---

packages/astro/src/assets/utils/metadata.ts

- Looks like https://github.com/withastro/astro/pull/6488 is breaking CI
- Switches to `import('image-size')` which seems to be passing locally

Prefer dynamic import for `image-size`

---

.changeset/nasty-cougars-double.md
packages/astro/src/content/internal.ts

Follows up on a performance bottleneck we found while migrating [the Astro docs](https://github.com/withastro/docs) to content collections. @delucis noted that repeat calls to `getCollection('docs')` slowed production builds, and[ centralizing to a single, top-level `getCollection()` call](https://github.com/withastro/docs/blob/main/src/content.ts) resolved the issue. This PR introduces a production-only cache to mirror this experience.
- Created a branch on the docs repo to measure production build changes in CI: https://github.com/withastro/docs/pull/2816 Found a ~10% improvement
- Built three times locally with caching and three times without. Noticed the same ~10% improvement
- Tracked memory usage building locally with and without caching. Each peeked at roughly the same 4.30 GB …

feat: cache `getCollection()` calls in production

---

.changeset/tough-sheep-grab.md
packages/astro/src/vite-plugin-inject-env-ts/index.ts

I got my logic wrong and on every restart, the types would switch between `astro/client` and `astro/client-image`, hilarious really. I added some logging as well to make this clearer on the user's end that types were updated when enabling the feature (just like content collections do when updating the types)
Tested manually, we don't test this part of the code. This "feature" will go away in the future when assets are not experimental, so testing it seems unnecessary
N/A

Fix `env.d.ts` switching back between types on every restart when assets are enabled

---

.changeset/fair-emus-taste.md
packages/integrations/cloudflare/src/index.ts

- Closes https://github.com/withastro/astro/issues/6291
- Removes a known false-positive warning. changeset includes the info.
- No
N/A

Remove false-positive warnings from Cloudflare's build

---

.changeset/famous-games-warn.md
packages/astro/src/assets/vite-plugin-assets.ts

What the title says!
Closes https://github.com/withastro/astro/issues/6529
N/A, just a warning

Add warning when using assets with non-node adapters

---

.changeset/cyan-camels-swim.md
packages/astro/src/core/build/internal.ts
packages/astro/src/core/build/plugins/index.ts
packages/astro/src/core/build/plugins/plugin-analyzer.ts
packages/astro/src/core/build/plugins/plugin-component-entry.ts
packages/astro/src/core/build/plugins/plugin-internals.ts
packages/astro/src/core/build/static-build.ts
packages/astro/test/astro-component-bundling.test.js
packages/astro/test/fixtures/astro-component-bundling/astro.config.mjs
packages/astro/test/fixtures/astro-component-bundling/package.json
packages/astro/test/fixtures/astro-component-bundling/src/components/ManyComponents.jsx
packages/astro/test/fixtures/astro-component-bundling/src/pages/index.astro
pnpm-lock.yaml

Fix https://github.com/withastro/astro/issues/6467
When a hydrated or `client:only` component is passed to the client build, only build those that are imported. e.g. `import { Foo } from './ManyComponents.jsx'`, the bundled entry should only export `Foo` and not other unused components.
This PR changes our client component collection logic to also track exports names imported. A custom Vite plugin is used to proxy entries to something like `export { Foo } from '/resolved/path/ManyComponents.jsx'`, so that we treeshake the unused components.
Added a bundling test to make sure unused components are treeshaken.
n/a. Bug fix.

Treeshake exported client components that are not imported

---

.changeset/quick-turtles-decide.md
packages/astro/src/content/error-map.ts
packages/astro/src/content/index.ts
packages/astro/src/content/utils.ts
packages/astro/src/core/errors/errors-data.ts
packages/astro/test/content-collections.test.js
packages/astro/test/units/content-collections/error-map.test.js

This fixes a few problems in today's error formatter:
- The collection -> entry path is bolded for visibility
- Frontmatter keys are now always placed at the start of an error message. This fixes inconsistencies where the key name could be at the start of the end of a message.
- Union errors now log "Did not match union" instead of "Invalid input." Will also log "type" and "invalid literal" errors for keys shared by all members of a union.
- Unhandled errors now correctly fall through to Zod's error message. This would log "Invalid Input" for all unhandled messages before.
Example: a union between `{ key: z.literal('tutorial') }` and `{ key: z.literal('blog') }` will raise a single error when `key` does not match:
```md
Did not match union.
> key: Expected `'tutorial' | 'blog'`, received …
```

[Content collections] Better error formatting

---

.changeset/four-planets-smoke.md
packages/astro/package.json
packages/astro/src/content/runtime-assets.ts
packages/astro/src/content/runtime.ts
packages/astro/src/content/template/virtual-mod-assets.mjs
packages/astro/src/content/template/virtual-mod.mjs
packages/astro/src/content/utils.ts
packages/astro/src/content/vite-plugin-content-virtual-mod.ts
packages/astro/test/content-collections.test.js
packages/astro/test/test-plugins.js

- Fixes issue where non-Node runtimes were breaking when using astro:content due to the Node dependency that `--experimental-assets` has.
- In the content collections test, add a plugin that verifies that no Node builtins are depended on in the build.
N/A, bug fix

Prevent astro:content from depending on Node builtins

---

.changeset/dirty-flies-hunt.md
packages/astro/src/assets/services/service.ts
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image/src/pages/index.astro

What the title says. This is a regression from when I fixed images having the wrong width and height if neither were provided, kinda funny
Added tests for all situations
N/A

Fix local images having the wrong width and height when both dimensions were provided

---

.changeset/gorgeous-beds-tickle.md
packages/astro/src/core/config/schema.ts

I unnecessarily tried to think like TS in Zod when I didn't need to since we don't use the schema anyway to do the types, oops.
Fix https://github.com/withastro/astro/issues/6545
N/A

fix(assets): Fix usage of custom service resulting in Invalid Input error

---

packages/astro-rss/README.md
packages/integrations/image/README.md
packages/integrations/markdoc/README.md
packages/integrations/sitemap/README.md
packages/integrations/svelte/README.md
packages/webapi/README.md

In multiple `README`s there was a mix of spaces and tabs used, this caused weird and incosistent formatting like seen here in npm:
Docs site seems to convert tabs, so was not affected. 
This PR replaces all `/src/packages/**/README.md` tabs with double spaces, making it consistent (as far as I can tell) with the rest of the docs.
Docs change, no testing needed
This should only affect github and npm, https://docs.astro.build/ should remain the same.

Integration readme: Replace tabs with double spaces

---

.changeset/early-kangaroos-invent.md
packages/integrations/cloudflare/src/index.ts

Fixes the strip logic for _config.base. Apparently the negative indexing is a feature of the deprecated substr, not substring.
Apologies for not catching this the first time around.
Manually tested via `patch-package` locally. Verified behavior is correct now.
N/A

fix(cloudflare): base strip logic

---

.changeset/yellow-grapes-design.md
packages/astro/src/core/app/index.ts
packages/astro/test/fixtures/ssr-prerender-404/package.json
packages/astro/test/fixtures/ssr-prerender-404/src/pages/404.astro
packages/astro/test/fixtures/ssr-prerender-404/src/pages/static.astro
packages/astro/test/ssr-prerender-404.test.js
pnpm-lock.yaml

Fix https://github.com/withastro/astro/issues/6511
When falling back to `404.astro`, and that `404.astro` is prerendered, skip rendering it in SSR to prevent runtime errors. Instead, respond with a code 404 so that the environment can fallback and use the prerendered `404.html`.
I've added a test to capture the first part. But I've not confirmed if environments _do_ fallback to the `404.html` if we return a 404 status code.
But in a way, if a person opt to prerendering `404.html`, it probably means that the deployed environment supports falling back to it.
Perhaps we can document which environments support falling back to `404.html`. It might be good to get the community to fill in this information as I find it rarely documented (especially paired with functions/workers), so it needs some …

Fix prerendered 404 page handling in SSR

---

.changeset/empty-ravens-complain.md
packages/astro/src/vite-plugin-config-alias/index.ts
packages/astro/test/alias-tsconfig.test.js
packages/astro/test/fixtures/alias-tsconfig/src/components/Foo.astro
packages/astro/test/fixtures/alias-tsconfig/src/components/Style.astro
packages/astro/test/fixtures/alias-tsconfig/src/pages/index.astro
packages/astro/test/fixtures/alias-tsconfig/src/styles/extra.css
packages/astro/test/fixtures/alias-tsconfig/src/styles/main.css
packages/astro/test/fixtures/alias-tsconfig/tsconfig.json

Fix https://github.com/withastro/astro/issues/6551
Support tsconfig aliases in styles, like `@import`. This only supports `compilerOptions.paths` aliases for styles, but not `baseUrl` aliases since it's not possible to use Vite aliases without accidentally overriding Vite's internal aliases.
This could be a fine compromise for now as `compilerOptions.paths` aliases are more commonly used.
Added test for `baseUrl` alias and CSS `@import`.
n/a. bug fix. Maybe in the future we could document the `baseUrl` caveat if it turns out to be commonly used and confusing for users.

Support tsconfig aliases in styles

---

.changeset/perfect-humans-wink.md
packages/astro/src/content/template/types.d.ts

What the title says
Types only, tested manually
N/A

Fix `image()` type to be compatible with ImageMetadata

---

.changeset/tidy-crabs-warn.md
packages/astro/src/content/utils.ts
packages/astro/test/content-collections.test.js
packages/astro/test/fixtures/content-collections-empty-md-file/package.json
packages/astro/test/fixtures/content-collections-empty-md-file/src/content/config.ts
packages/astro/test/fixtures/content-collections-empty-md-file/src/pages/index.astro
pnpm-lock.yaml

When the markdown page is empty, `rawFrontmatter` is undefined which causes `rawFrontmatter.indexOf` to throw
The fix is to return early when the frontmatter is falsy.
Check that we get a correct error
Bug fix only

Fix error in empty markdown files with content

---

.changeset/soft-plants-hope.md
packages/astro/src/core/render/dev/resolve.ts

This cleans up our `.jsx` -> `.tsx` handling. The code is removed since it's already handled at
https://github.com/withastro/astro/blob/36253f47add6f6eb927407dacc6a645d9e48d48e/packages/astro/src/core/util.ts#L176-L179
This should prevent Vite's perf PR (https://github.com/vitejs/vite/pull/12450) from breaking for a specific case, where the user project imports `.tsx` components that's outside of the project root.
n/a. Existing tests should pass.
n/a. code refactor and cleanup.

Simplify internal resolver in dev

---

examples/blog/src/components/FormattedDate.astro

Added a type definition for `FormattedDate` in the Blog template. This will ensure users of the template have their `date` prop correctly typed.
No new functionality added.
I don't believe docs should need to be updated. This does not affect behaviour in any way.

Added prop type definition for FormattedDate in Blog example

---

.changeset/tender-emus-eat.md
packages/astro/src/cli/check/index.ts

**What does this change?**
- The following change adds the missing `--watch` flag for `astro check` when one runs `astro check --help`.
N/A
N/A

fix: Add missing --watch flag when running astro check --help

---

.changeset/tiny-worms-joke.md
packages/astro/tsconfigs/base.json

TS 5.0 deprecated `importsNotUsedAsValues`, which we use in our strict tsconfig template. Unfortunately, we can't migrate to the new option `verbatimModuleSyntax` until a majority of our users are on TS 5.0+ because the option is incompatible with `isolatedModules`, which we also use (having both is redundant together, that's why they're incompatible)
So, we'll just ignore the deprecations for a few TS version and upgrade our templates then. Once VS Code ships TS 5.0 (in a month or so), a big part of our users will be on TS 5.0 already, so shouldn't take long
Close https://github.com/withastro/astro/issues/6599
N/A

fix(tsconfig): Update tsconfig templates to ignore 5.0 deprecations

---

.changeset/tame-taxis-perform.md
packages/astro/src/core/create-vite.ts

`vite-plugin-inspect` relies on the `command` arg to return a value for `apply`. In Astro, it's `'dev' | 'build'`, but in Vite, it's `'serve' | 'build'`.
This PR normalizes to Vite's convention before apply it to the plugin when we filter the plugins.
Tested manually with `vite-plugin-inspect`
n/a. bug fix.

Fix plugin apply args when filtering

---

.changeset/tall-beans-own.md
packages/create-astro/src/messages.ts

When outputting projectDir in the terminal, if it contains spaces, wrap it in quotes.

chore: wrap the projectDir in quotes if it contains spaces

---

.changeset/lazy-mice-fetch.md
packages/astro/src/@types/astro.ts
packages/astro/src/content/vite-plugin-content-imports.ts
packages/astro/src/core/errors/dev/vite.ts
packages/integrations/markdoc/README.md
packages/integrations/markdoc/package.json
packages/integrations/markdoc/src/index.ts
packages/integrations/markdoc/test/entry-prop.test.js
packages/integrations/markdoc/test/fixtures/entry-prop/astro.config.mjs
packages/integrations/markdoc/test/fixtures/entry-prop/package.json
packages/integrations/markdoc/test/fixtures/entry-prop/src/content/blog/entry.mdoc
packages/integrations/markdoc/test/fixtures/entry-prop/src/content/config.ts
packages/integrations/markdoc/test/fixtures/entry-prop/src/pages/index.astro
pnpm-lock.yaml

- Expose content collection entry information to Markdoc files. This allows you to render the parsed frontmatter based on your schema, alongside the generated `id`, `slug`, and `collection` name.
```mdx
---
title: Hello Markdoc!
---
```
- Introduce a new `getRenderModule()` helper on our internal `addContentEntryType` API. This exposes the parsed `entry` to your Vite loader for use while generating the module (ex. to expose an `$entry` variable to the Markdoc transformer). This also standardizes how the result of `.render()` is generated. Before, integration authors would need to wire up a separate Vite plugin that resolves modules of your preferred extension and hope this meshes with Astro's content collection API ([see diff here](https://github.com/withastro/astro/compare/feat/markdoc-en …

feat: Expose `$entry` variable to Markdoc

---

.changeset/twenty-islands-protect.md
packages/integrations/markdoc/README.md

The commands for installing `@markdoc/markdoc` were using `astro`, but this didn't work. I'm assuming that what's required is to actually use a package manager to install it.
- added the appropriate `npm`, `yarn`, and `pnpm` commands
Running the given command (e.g., `pnpm astro add @markdoc/markdoc`) threw an error:
```
@markdoc/markdoc doesn't appear to be an integration or an adapter. Find our official integrations at https://astro.build/integrations
```
Running `pnpm add @markdoc/markdoc` worked: `import { Tag } from '@markdoc/markdoc'` did not throw an error.
This is a change in docs.

edit commands for installing @markdoc/markdoc

---

.changeset/curly-wasps-matter.md
packages/astro/src/vite-plugin-config-alias/index.ts
packages/astro/test/alias-tsconfig.test.js
packages/astro/test/fixtures/alias-tsconfig/src/pages/index.astro
packages/astro/test/fixtures/alias-tsconfig/src/ts-file.ts

Fix #6613
Check that Typescript file without `.ts` extension can be imported

Fix tsconfig alias regression

---

.changeset/sharp-timers-lick.md
packages/astro/src/vite-plugin-config-alias/index.ts
packages/astro/test/alias-tsconfig.test.js
packages/astro/test/fixtures/alias-tsconfig/src/components/Foo.astro
packages/astro/test/fixtures/alias-tsconfig/src/components/Style.astro
packages/astro/test/fixtures/alias-tsconfig/src/pages/index.astro
packages/astro/test/fixtures/alias-tsconfig/src/styles/extra.css
packages/astro/test/fixtures/alias-tsconfig/src/styles/main.css
packages/astro/test/fixtures/alias-tsconfig/src/ts-file.ts
packages/astro/test/fixtures/alias-tsconfig/tsconfig.json

- Resolves #6629 
- This reverts commit 38e6ec21e266ad8765d8ca2293034123b34e839a, which breaks resolution for virtual modules like `astro:content`

Revert `tsconfig-alias` plugin changes

---

.changeset/stupid-suns-beg.md
packages/astro/src/content/runtime-assets.ts
packages/astro/src/content/utils.ts
packages/astro/src/content/vite-plugin-content-imports.ts
packages/astro/test/fixtures/core-image-ssg/src/content/blog/one.md
packages/astro/test/fixtures/core-image/src/content/blog/one.md

Previously, all images in the frontmatter were relative to `src/assets`, this PR changes it so it's relative to the current file instead. This is a proper resolve, so you can use aliases (including `~/assets/`) and stuff.
This PR does not cover using images in certain cases, such as arrays. This is intentional as this is not supported at the moment in general so I'll tacle it in a dedicated PR
Updated tests
https://github.com/withastro/astro/pull/6627

Resolve images in the frontmatter relative to the current file

---

.changeset/smart-wombats-peel.md
packages/astro/src/cli/index.ts

Fix https://github.com/withastro/astro/issues/6645
`mode` flag wasn't pass to `build()` for it to take effect.
Regression from https://github.com/withastro/astro/pull/6394/files#diff-4585793503f675c4554733f25418e03ec1938af33dbc9d279442beef8f205741L206-R221
n/a 😬 it was easier to test with the repro, which I confirmed works with this change.
n/a. bug fix.

Pass --mode flag to build

---

.changeset/perfect-rabbits-repair.md
packages/astro/astro-jsx.d.ts

Fixes a few camel-cased attributes in the `astro.JSX.LinkHTMLAttributes` type
**Before**
**After**
None, type definition update only
None, bug fix in the type definition only

fix: updating HTML attribute types for the <link> element

---

.changeset/chilly-dingos-eat.md
packages/integrations/partytown/README.md
packages/integrations/partytown/src/index.ts

- Allows developers to use the original properties defined by [partytown](https://github.com/BuilderIO/partytown/blob/main/src/lib/types.ts#L384)
I didn't see any test's setup for the package. Do we need one?
Removed the content that explicitly mentioned about the `debug` and `forward` properties.

Expose partytown config options from astro plugin

---

.changeset/lovely-owls-sniff.md
packages/astro/src/assets/utils/transformToPath.ts
packages/astro/src/assets/vite-plugin-assets.ts
packages/integrations/image/src/index.ts
packages/integrations/image/src/loaders/index.ts
packages/integrations/image/src/utils/paths.ts

I experienced very strange behaviour which resulted in images being rotated or not depending on how i change the widths or alt tags of images. I tracked this down to the image cache not being regenerated after i switched to sharp.
The behaviour of sharp differs in some ways. In my case sharp rotates the image while removing the exif data. squoosh does remove the exif data without rotating the images. When my image was the exact same image as before I got served the cached version built previously by squoosh so some images were still up side down etc. Changing the alt tag invalidated the cache, as it is used for hashing.
- Don't use the alt tag for hashing as it has nothing to do with the actual content of the image
- Include the serviceEntryPoint in the hashKey to invalidate the image …

Fix image regeneration after changing image service

---

packages/integrations/markdoc/package.json

- Specify `"astro"` peer dep version for Markdoc. Matches existing integrations, and hopefully fixes the 1.0.0 bump here https://github.com/withastro/astro/pull/6652

Fix CI = specify astro peer dep version for Markdoc

---

.changeset/hip-avocados-grow.md

- Change minor introduced by https://github.com/withastro/astro/commit/adecda7d6009793c5d20519a997e3b7afb08ad57 to a patch. this change patches an expected API from Vite and doesn't need to trigger a 2.2.0 launch.

Change `--open` flag minor to a patch

---

.changeset/wet-lemons-rest.md
packages/integrations/react/src/index.ts

- Closes https://github.com/withastro/astro/issues/6365
- No, simple config change
N/A

Add use-immer as a noExternal module

---

.changeset/eight-humans-push.md
packages/astro/src/core/render/paginate.ts
packages/astro/test/astro-pagination.test.js
packages/astro/test/fixtures/astro-pagination/src/pages/posts/[slug]/[page].astro

- Resolves #6603
- Use `undefined` for index routes during pagination. Otherwise, this inserts an expected trailing `/`. found this also generates `/posts//` by default!
- Add tests for next and prev pagination links
N/A

Fix: Paginate adds unexpected trailing slash on index route

---

.changeset/odd-falcons-exist.md
packages/astro/src/@types/astro.ts

InferGetStaticParamsType and InferGetStaticPropsType always assumed that `getStaticPaths` was async, but it can be sync in some cases. This PR fixes this.
This PR additionally updates the JSDoc comments to show usage with `satisfies`, as trying to type `getStaticPaths` directly will cause InferGetStaticParamsType and InferGetStaticPropsType to not work (since they work by inferring the return value, which the type will overwrite. `satisfies` is great)
N/A

Fix InferGetStaticParamsType and InferGetStaticPropsType not working with sync getStaticPaths

---

.changeset/honest-paws-behave.md
packages/astro/e2e/errors.test.js
packages/astro/e2e/test-utils.js
packages/astro/src/core/errors/dev/utils.ts
packages/astro/src/core/errors/overlay.ts

Fix #6678.
An e2e test was added.
This just fixes a bug so no docs changes are needed.

Fix incorrect path in error overlay on Win

---

packages/astro/src/core/errors/errors-data.ts

Error references was broken because of the complex message, oops. I of all people should know this.
N/A
N/A

fix(errors): Add simplified message for MarkdownImageNotFound

---

.changeset/eight-stingrays-pull.md
packages/astro/src/cli/index.ts

In a past PR, we changed all the imports to other commands to be dynamically imported so the overall CLI run faster. There's still quite a bit of improvements to be made there, but still, it helped a lot.
A previous PR added `check` back as a normal import, so this PR fixes this.
Tests still pass and tested manually!
N/A

fix(check): Dynamically import check command

---

.changeset/red-parents-knock.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/cookies/cookies.ts
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/core/render/result.ts
packages/astro/src/runtime/server/render/common.ts
packages/astro/src/vite-plugin-astro-server/response.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/ssr-redirect/src/components/redirect.astro
packages/astro/test/fixtures/ssr-redirect/src/pages/late.astro
packages/astro/test/ssr-redirect.test.js
packages/astro/test/units/cookies/error.test.js

- Adds better error messaging for when trying to do `Astro.cookies.set()` and `Astro.redirect()` on a response that has already been sent.
- Closes https://github.com/withastro/astro/issues/6632
- Closes https://github.com/withastro/astro/issues/6644
- Unit test added for cookies.
- SSR test added for redirects
N/A, error message

Better errors for when response is already sent

---

.changeset/mean-guests-joke.md
packages/integrations/markdoc/components/TreeNode.ts
packages/integrations/markdoc/test/fixtures/render-null/astro.config.mjs
packages/integrations/markdoc/test/fixtures/render-null/markdoc.config.mjs
packages/integrations/markdoc/test/fixtures/render-null/package.json
packages/integrations/markdoc/test/fixtures/render-null/src/content/blog/render-null.mdoc
packages/integrations/markdoc/test/fixtures/render-null/src/pages/index.astro
packages/integrations/markdoc/test/render.test.js
pnpm-lock.yaml

- Resolves #6628
- Add handling for an array of tree nodes to support `render: null` in your config. This is an inconsistency in Markdoc's own types, which state the `transform()` function should not return an array. Turns out, transform returns an array whenever a node is set to `render: null`!
Test `render: null` on the document node
N/A

[Markdoc] Fix: Support `render: null`

---

.changeset/serious-ladybugs-eat.md
packages/astro/src/assets/image-endpoint.ts
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/test/core-image.test.js

By accident, we were using the path to the original file to determine the mime type instead of the generated format. This PR fixes this
Added a test
N/A

fix(images): Return the proper content-type for the chosen format

---

.github/workflows/check-merge.yml

This PR fixes our `Check mergeability` workflow. We were querying the incorrect info for the info number. 
The new content is valid because that's what we use for the `curl` script, which shows the correct information
Merge and see if next time doesn't throw an error
N/A

ci: use correct issue number

---

.changeset/chatty-parrots-compare.md
packages/integrations/sitemap/src/index.ts
packages/integrations/sitemap/test/trailing-slash.test.js

closes #6618 
I added a condition to check whether the base path has a trailing slash or not (when the base path and page path are concatenated) and add the trailing slash if it's missing. 
I tested using the `@example/blog` with this configuration:
```ts
site: 'https://example.com',
integrations: [mdx(), sitemap()],
base: '/base',
trailingSlash: 'never',
});
```
- sitemap-index.xml
```xml
<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>https://example.com/sitemap-0.xml</loc></sitemap></sitemapindex>
```
- sitemap-0.xml
```xml
<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" …
```

Fix #6618: sitemap urls generated without slash 

---

.changeset/empty-moose-grin.md
packages/astro/config.d.ts

Fix https://github.com/withastro/astro/issues/6750
`getViteConfig` returns a Vite config function, not the Vite config
Manually tested the `with-vitest` example which uses this API, and it still works.
n/a. it doesn't look like `getViteConfig` is documented currently.

Fix getViteConfig return type

---

.changeset/cyan-fireants-care.md
packages/integrations/vercel/src/analytics.ts

While testing out vercel analytics using the vercel adapter, I noticed there was an error in my console stating that `VERCEL_ANALYTICS_ID` has not been provided.
After some research it looks as though it is looking for `PUBLIC_VERCEL_ANALYTICS_ID` but it is never provided. I believe this is likely the cause of the error.
[packages/integrations/vercel/src/analytics.ts](https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/analytics.ts#L42)
Running `vc pull` with the analytics enabled downloads an environment locally which contains `VERCEL_ANALYTICS_ID` and not `PUBLIC_VERCEL_ANALYTICS_ID`. The documentation also mentions that the environment variable is inlined at build time.
https://vercel.com/docs/concepts/analytics/api#getting-started
> To use the Web Vitals API, …

@astrojs/vercel: Fix vercel analytics id not being provided

---

packages/astro/test/fixtures/astro-assets-prefix/src/content/config.ts

A test still used the old image() import, this caused CI to fail
CI should pass!
N/A

test: remove outdated image() import

---

.changeset/metal-lizards-arrive.md
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/core/sync/index.ts

We previously swallowed the error message when there was an error while generating content collection types. This PR fixes that
N/A

Show the actual error when there was an error while generating types

---

.changeset/big-poems-march.md
packages/astro/src/content/template/types.d.ts

As of now, if you want to declare your schemas separate from the collection function, some hacks like these are needed:
```ts
type Schema = Parameters<typeof defineCollection>[0]['schema']
const blogSchema: Schema = ({ image }) => z.object({
title: z.string(),
date: z.coerce.date(),
description: z.string(),
tags: z.array(z.string()),
draft: z.boolean().default(false),
banner: image(),
})
```
Doing this might be needed if you want to use the schema in other places so you can export the type of the schema.
Exports the `ImageFunction` and gives the object passed to the schema function a name.
Just a type change so no tests should be needed.
This should be more of a QoL update and types aren't documented in general from what I know.

Exporting ImageFunction from astro:content

---

.changeset/fast-worms-agree.md
packages/astro/client-base.d.ts

Our client types were severely outdated. We unfortunately cannot use Vite's since we need different types for images so we have to manually copy paste them
N/A

Update client types to match Vite

---

.changeset/good-gorillas-compare.md
packages/astro/src/content/template/types.d.ts

- Remove legacy `slug()` from `defineCollection()`. Was removed for 2.0 and missed in the type defs.

Fix: remove `slug()` from `defineCollection()`

---

.changeset/smart-files-flow.md
packages/astro/src/runtime/server/render/page.ts
packages/integrations/mdx/src/index.ts
packages/integrations/mdx/test/css-head-mdx.test.js
packages/integrations/mdx/test/fixtures/css-head-mdx/src/components/BasicBlock.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/layouts/DocumentLayout.astro
packages/integrations/mdx/test/fixtures/css-head-mdx/src/pages/componentwithtext.mdx

- Fixes https://github.com/withastro/astro/issues/6700
- Uses same mechanism used for astro, component metadata propagates up. Metadata was already there, we just were using it during render.
N/A, bug fix

Prevent body head content injection in MDX when using layout

---

packages/integrations/tailwind/README.md

**Closes**: [#2957](https://github.com/withastro/docs/issues/2957)
- Add `sh` language to code block in Tailwind README
None
- Fixes formatting error in Docs: https://docs.astro.build/en/guides/integrations-guide/tailwind/#class-does-not-exist-with-apply-directives

Fix Tailwind README code block

---

.changeset/shaggy-chefs-build.md
packages/integrations/vercel/src/analytics.ts

Apologies, in my efforts to find out why the key wasn't being included, allowed myself to lose track of the fact that only environment variables that are prefixed with PUBLIC_ will be bundled at build time.
- Reverts #6751 
Didn't have the desired effect, this simply reverts it back to how it was.
- Fixes a previously unfixed patch (specifically in the case where it was working before)
- Remains broken for those it was broken for before

Revert vercel env fix

---

.changeset/strong-hairs-sort.md
packages/integrations/netlify/src/integration-edge-functions.ts
packages/integrations/netlify/test/edge-functions/prerender.test.ts

fixes #6506
- This commit changes the generated edge function file from `entry.mjs`
back to `entry.js`
- Apparently Netlify doesn't identify edge functions when the file extension is `.mjs`
- The issue started in version 2.1.3 when the file extension was changed.
- The extension was changed because of this issue #6299 that was affecting Vercel and maybe could affect Netlify.
- But I tested version 2.1.2 of `@astrojs/netlify` using `type: "commonjs"` inside `package.json` and found no errors.
I just changed one test that was expecting `.mjs`.
n/a

Fix no edge functions deployed to netlify

---

packages/astro/test/alias-tsconfig.test.js
packages/astro/test/fixtures/alias-tsconfig/deps/namespace-package/index.js
packages/astro/test/fixtures/alias-tsconfig/deps/namespace-package/package.json
packages/astro/test/fixtures/alias-tsconfig/package.json
packages/astro/test/fixtures/alias-tsconfig/src/components/Foo.astro
packages/astro/test/fixtures/alias-tsconfig/src/components/Style.astro
packages/astro/test/fixtures/alias-tsconfig/src/pages/index.astro
packages/astro/test/fixtures/alias-tsconfig/src/styles/extra.css
packages/astro/test/fixtures/alias-tsconfig/src/styles/main.css
packages/astro/test/fixtures/alias-tsconfig/src/utils/constants.js
packages/astro/test/fixtures/alias-tsconfig/tsconfig.json
pnpm-lock.yaml

Add more tests to tsconfig aliases, which covers previous regressions from:
- https://github.com/withastro/astro/issues/6620
- https://github.com/withastro/astro/issues/6613
- https://github.com/withastro/astro/pull/6566
Also added tests for `@import` in todo that I'll work on in a later PR.
New tests should pass.
n/a. tests only.

Add more tsconfig alias tests

---

.changeset/beige-humans-study.md
packages/astro/src/core/errors/overlay.ts

The error overlay is designed for LTR (Left to Right) documents so when I change my document's direction to RTL (`<html dir="rtl"`) it breaks. I forced the direction to be LTR because it doesn't make sense to be RTL. The error message and the codes would be hard to read in RTL.
Before:
After:
Not needed
Not needed

fix(error-overlay): force error overlay direction to be LTR

---

.changeset/angry-experts-compete.md
packages/astro/src/cli/check/index.ts
packages/astro/src/vite-plugin-load-fallback/index.ts

Fix https://github.com/withastro/astro/issues/6629
In `vite-plugin-load-fallback`, the `fs` check wasn't right when the `fs` is from `import * as fs from 'fs'`. This PR fixes it. 
I also simplified the `resolveId` hook as the `this.resolve` and always `slashify` part doesn't seem necessary. Other plugins should've already resolve before the `load-fallback` plugin, and always `slashify` makes it impossible for a plugin to run `this.resolve` to check if an id is resolveable (e.g. `tsconfig-alias` plugin `baseUrl`)
Existing tests should pass. The edgecase in #6629 is a little hard to test, but once I do some tsconfig aliases soon, the regression shouldn't happen again.
n/a. bug fix.

Fix check CLI fs load fallback behaviour

---

.changeset/healthy-experts-worry.md
packages/astro/src/runtime/server/render/slot.ts
packages/astro/test/astro-slots.test.js
packages/astro/test/fixtures/astro-slots/src/components/Fallback2.astro
packages/astro/test/fixtures/astro-slots/src/pages/fallback-override.astro

Fix https://github.com/withastro/astro/issues/6788
Check if there's no slotted content before showing the fallback
Check if the fallback content doesn't appear next to the slotted content
N/A, bug fix

Fix slot fallbacks unexpectedly showing up in some cases

---

.changeset/sweet-cows-eat.md
packages/astro/src/assets/consts.ts
packages/astro/src/assets/services/service.ts
packages/astro/src/assets/types.ts
packages/astro/src/content/types-generator.ts
packages/astro/src/content/utils.ts
packages/astro/src/content/vite-plugin-content-imports.ts
packages/astro/test/units/content-collections/get-entry-type.test.js

The "unsupported files found" warning for content didn't make much sense to appear for images with `experimental.assets`. This PR updates this to fix that
Added a test
N/A

fix(content): Remove unsupported file warning for images

---

packages/astro/e2e/fixtures/astro-envs/package.json
packages/astro/e2e/fixtures/preact-compat-component/package.json
packages/astro/e2e/fixtures/vue-component/package.json
packages/astro/test/fixtures/content-collections-with-config-mjs/package.json
packages/astro/test/fixtures/core-image-base/package.json
packages/astro/test/fixtures/core-image-errors/package.json
packages/astro/test/fixtures/css-assets/package.json
packages/astro/test/fixtures/css-order-dynamic-import/package.json
packages/astro/test/fixtures/error-build-location/package.json
packages/astro/test/fixtures/root-srcdir-css/package.json
packages/astro/test/fixtures/static-build-ssr/package.json
packages/integrations/image/test/fixtures/rotation/package.json
packages/integrations/image/test/fixtures/squoosh-service/package.json
packages/integrations/node/test/fixtures/prerender/package.json
packages/integrations/prefetch/test/fixtures/style-prefetch/package.json

A small chore to ensure workspace packages have a unique name. This is required when I upgrade turbo, but for some reason turbo also scans gitignored packages (e.g. build output), and those build output have empty names causing https://github.com/vercel/turbo/issues/3340
So I stick with the old turbo version for now, but thought it would be good to do this cleanup.
n/a. cleanup.

Ensure unique workspace name

---

.changeset/wet-schools-clap.md
packages/integrations/vercel/README.md

Fixes syntax used for a caution in the Vercel integration README. This was added using the docs syntax of `:::caution` which doesn’t work on GH/npm. We can use GH’s syntax instead though as we use a remark plugin to convert that to our syntax in docs.
Docs only.
Docs fix!

Fix warning syntax in Vercel integration README

---

.changeset/blue-moons-cough.md
packages/integrations/vercel/src/edge/adapter.ts

Fix https://github.com/withastro/astro/issues/6713
When building for Vercel edge with `ssr.target: 'webworker'` in Vite, make sure Vite doesn't replace `process.env` as `({})` so they work in Vercel edge runtime on deploy.
cc @matthewp, didn't mean to steal your fix, but i was playing around some things while debugging it and found a fix 😬 
Ran the issue's repro https://github.com/larryhudson/astro-vercel-edge-env-testing and run `MY_ENV_VAR=foo npm run build` to build it.
After that, I open `.vercel/output/functions/render.func/chunks/pages/all.00bba6ec.mjs` to verify that the `MY_ENV_VAR` is correctly preserved as `process.env.MY_ENV_VAR`, not `{}.MY_ENV_VAR`.
n/a. bug fix.

Fix vercel edge private env vars

---

.changeset/large-pens-rhyme.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/types.ts
packages/astro/src/core/build/plugins/plugin-ssr.ts
packages/astro/test/astro-assets-prefix.test.js

- Fixes #6852
- In SSR mode, `assetsPrefix` is not being prepended to component-url and renderer-url.
We added a test to `astro/test/astro-assets-prefix.test.js`.
```js
it('react component astro-island should import from assetsPrefix', async () => {
const request = new Request('http://example.com/custom-base/');
const response = await app.render(request);
expect(response.status).to.equal(200);
const html = await response.text();
const $ = cheerio.load(html);
const island = $('astro-island');
expect(island.attr('component-url')).to.match(assetsPrefixRegex);
expect(island.attr('renderer-url')).to.match(assetsPrefixRegex);
});
```
A similar test case already existed for the SSG case, but not for SSR. I just copied and adapted the test case for SSR. When the test case was added for SSR, it …

fix: astro island urls missing assetsPrefix in SSR mode

---

.changeset/few-cats-beam.md
packages/astro/src/core/render/core.ts
packages/astro/test/fixtures/ssr-params/src/pages/東西/[category].astro
packages/astro/test/ssr-params.test.js

Fixes #6831
- Fixed bug where Astro.params does not contain path parameter when the URL has non-English characters.
- Added related test.
I noticed that `route.pattern` expects a decoded string, but the `pathname` is encoded. So I decoded the `pathname` before passing it to the pattern matching.
```js
...
route: {
route: '/東西/[name]',
type: 'page',
pattern: /^\/東西\/([^/]+?)\/?$/, // decoded value
params: [ 'name' ],
component: 'src/pages/東西/[name].astro',
generate: [Function (anonymous)],
pathname: undefined,
segments: [ [Array], [Array] ],
prerender: false
},
routeCache: RouteCache {
cache: {},
logging: { dest: [Object], level: 'info' },
mode: 'production'
},
pathname: '/%E6%9D%B1%E8%A5%BF/test', // encoded value
...
```
- I added a test that reproduces the behavior.
n/a

Fix Astro.params does not contain path parameter from URL with non-English characters

---

.changeset/curvy-schools-carry.md
examples/basics/README.md
examples/blog/README.md
examples/deno/README.md
examples/docs/README.md
examples/hackernews/README.md
examples/minimal/README.md
examples/non-html-pages/README.md
examples/portfolio/README.md
examples/with-markdoc/README.md
examples/with-vite-plugin-pwa/README.md

This PR adds the right `npm` command regarding `astro --help` for examples' `README.md` files.
UPDATE: no changeset following this advice in review: https://github.com/withastro/astro/pull/6864#pullrequestreview-1388253337
There's no test because I'm just enhancing markdown files.
There's no docs added because that's only markdown files that will be generated when users will create a new project with astro CLI.
Thanks :)

docs: add the right `npm` command regarding `astro --help` for examples' `README.md` files

---

.changeset/shiny-roses-tap.md
packages/astro/src/core/config/vite-load.ts
packages/astro/src/core/sync/index.ts

Disable the optimizer with `optimizeDeps.disabled` so that the optimize metadata is not overwritten
In the astro docs repo, what's happening is that:
1. Load `astro.config.ts` with Vite server, sees `./node_modules/.vite/deps/_metadata.json`, but hash mismatched so remove the file.
2. Start Astro dev server, which sees that there's no `./node_modules/.vite/deps/_metadata.json`.
This causes the Astro dev server startup to always re-optimize on step 2, which makes startup slow. This PR prevents step 1 from happening.
This removes 200ms of scanning and 600ms of prebundling for the Astro docs repo for warm startups.
Manual testing in astro docs repo
n/a. bug fix.

Disable Vite optimizer for sync and config loading

---

.changeset/config.json
packages/create-astro/test/fixtures/not-empty/package.json

Changeset is currently failing as I had removed the `package.json` `workspaces` field that it used to use in #6911. I don't think using that field is right, so I've tweak the changeset config, and provide a package name for one fixture to fix it.
Tested `pnpm changeset version --dry-run` to make sure there's no errors.
n/a. changeset changes.

Fix changeset version run

---

.changeset/funny-plums-drum.md
packages/astro/src/vite-plugin-config-alias/index.ts
packages/astro/test/alias-tsconfig.test.js
packages/astro/test/fixtures/alias-tsconfig/src/pages/index.astro
packages/astro/test/fixtures/alias-tsconfig/src/utils/constants.js
packages/astro/test/fixtures/alias-tsconfig/src/utils/index.js

fix https://github.com/withastro/astro/issues/6901
We were aliasing `import "."` and `import ".."` and prepending the `baseUrl` before which shouldn't happen. This PR updates the regex to ignore `.` and `..`.
Added a new test using those imports.
n/a. bug fix.

Fix tsconfig alias baseUrl handling for "." and ".." imports

---

.github/workflows/ci.yml

Uses a new `PUBLIC_TWO_LANG` field from https://github.com/withastro/docs/pull/3102 to speed up docs smoke tests. It will only generates pages for two languages to build faster, as mostly the content varies and not the functionality.
Existing smoke tests should pass and be faster.
n/a

Speed up docs smoke tests

---

.changeset/tidy-singers-thank.md
packages/integrations/cloudflare/README.md

This adds the missing `js` language to a code block that was causing issues in the docs integration page.
See: https://github.com/withastro/docs/pull/3105
No tests!
It's all about docs.

Add missing code language in Cloudflare README

---

.prettierrc.cjs
package.json
patches/@changesets__cli@2.26.1.patch
pnpm-lock.yaml

- Update dependencies related to changesets to use the new features mentioned below
- Change prettier config extension to `.cjs`(Now changesets use latest version of prettier See: https://github.com/changesets/changesets/pull/905).
- Remove workaround in prettier config(Same reason above).
Only prettier config has changed.

chore: update dependencies related to changesets

---

.changeset/wise-steaks-wash.md
examples/with-tailwindcss/package.json
packages/astro/e2e/fixtures/tailwindcss/package.json
packages/astro/test/fixtures/postcss/package.json
packages/astro/test/fixtures/tailwindcss-ts/package.json
packages/astro/test/fixtures/tailwindcss/package.json
packages/integrations/svelte/package.json
packages/integrations/tailwind/package.json
pnpm-lock.yaml

- Update dependencies to prevent the postcss peer dep warnings on install.
- Also update the `@sveltejs/vite-plugin-svelte` dep as that removes the stats log clutter in the CI logs
There's one remaining peer dep warning though:
```
 WARN  Issues with peer dependencies found
packages/integrations/svelte
└─┬ svelte2tsx 0.5.11
└── ✕ unmet peer typescript@^4.1.2: found 5.0.2
```
We need to upgrade to svelte2tsx v6 to fix it, but that bumps the peer dep of `svelte` to 3.55.0. Our svelte peer dep is 3.54.0. So we'd need to cut a major if we want to fix it, which doesn't seem worth it for now.
n/a. deps update

Update dependencies to remove peer dep warnings

---

.changeset/many-fans-reply.md
packages/integrations/react/src/index.ts

- Automatically set `noExternal` configuration for redoc, a popular React package
- Closes https://github.com/withastro/astro/issues/6656
Just in stackblitz.
https://stackblitz.com/edit/github-dubfdg?file=package.json,astro.config.mjs,src%2Fpages%2Findex.astro,node_modules%2Fastro%2Fdist%2F%40types%2Fastro.d.ts,node_modules%2Fvite%2Fdist%2Fnode%2Findex.d.ts&on=stackblitz
No

Configure redoc to be noExternal

---

.changeset/ninety-snails-study.md
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/custom-404-html.test.js
packages/astro/test/custom-404-injected.test.js
packages/astro/test/fixtures/custom-404-html/astro.config.mjs
packages/astro/test/fixtures/custom-404-html/package.json
packages/astro/test/fixtures/custom-404-html/src/pages/404.html
packages/astro/test/fixtures/custom-404-html/src/pages/index.astro
packages/astro/test/fixtures/custom-404-injected/astro.config.mjs
packages/astro/test/fixtures/custom-404-injected/package.json
packages/astro/test/fixtures/custom-404-injected/src/404.astro
packages/astro/test/fixtures/custom-404-injected/src/pages/index.astro
packages/astro/test/units/dev/dev.test.js
pnpm-lock.yaml

- Fixes #6937
- Updates `getCustom404Route` logic to find 404s added via `injectRoute`
- As a side effect, also adds support for `src/pages/404.html`, which we don’t have currently.
Added a fixture + test like we have for the current custom 404 strategies and also a dev server unit test.
I also applied the same changes in a patch inside a monorepo project to test the logic when the injected route comes from a separate package.
Bug fix, no docs needed.

Show injected custom 404 route in dev

---

packages/integrations/netlify/test/edge-functions/dynamic-import.test.js
packages/integrations/netlify/test/edge-functions/edge-basic.test.ts
packages/integrations/netlify/test/edge-functions/prerender.test.ts
packages/integrations/netlify/test/edge-functions/root-dynamic.test.ts
packages/integrations/netlify/test/edge-functions/test-utils.ts

- Remove some `@ts-expect-error` directives that aren't necessary.
Some examples of the error:
n/a
n/a

Fix some TS compilation errors

---

.changeset/tidy-points-do.md
package.json
packages/astro/package.json
pnpm-lock.yaml

Our language server reached 1.0.0 today! Yay! This finally liberates us from the multiple versions of the compiler.
Fix https://github.com/withastro/astro/issues/6803
`astro check` tests should still pass!
N/A

Upgrade to version 1.0.0 of the language server

---

.changeset/thick-frogs-call.md
packages/astro/package.json
packages/integrations/image/package.json
packages/integrations/image/test/fixtures/background-color-image/package.json
packages/integrations/image/test/fixtures/basic-image/package.json
packages/integrations/image/test/fixtures/basic-picture/package.json
packages/integrations/image/test/fixtures/get-image-remote/package.json
packages/integrations/image/test/fixtures/no-alt-text-image/package.json
packages/integrations/image/test/fixtures/no-alt-text-picture/package.json
packages/integrations/image/test/fixtures/rotation/package.json
packages/integrations/image/test/fixtures/with-mdx/package.json
pnpm-lock.yaml

Semver range for Sharp didn't allow Sharp's latest version. This fixes that. 
This PR additionally updates our code to Sharp's 0.32.0, which removes the need for `@types/sharp`
N/A
N/A

fix: fix sharp semver range to allow for 0.32.0

---

.changeset/popular-bats-pump.md
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/internal.ts
packages/astro/src/core/build/plugins/plugin-ssr.ts
packages/astro/src/core/build/static-build.ts

Integration developers might expect to able to control prerendering behavior by mutating PageBuildData.route.prerender in the `'astro:build:setup'` hook. However, the decision to prerender is currently made by inspecting BuildInternals.
This PR changes where various parts of the build pipeline look to decide if a page should be prerendered. They now exclusively consider PageBuildData, allowing integrations to participate in the decision.

Make prerendering decision based on `PageBuildData` instead of `BuildInternals`

---

.changeset/nice-jars-breathe.md
packages/astro/client-base.d.ts
packages/astro/src/assets/internal.ts

`getImage` type was pointing to the internal function, which takes two parameters. But we expose a wrapper in our vite virtual module that does not require it, so we need a separate definition
N/A

fix(types): Fix getImage type requesting for a second parameter

---

packages/astro/test/astro-get-static-paths.test.js
packages/astro/test/ssr-prerender-get-static-paths.test.js
packages/astro/test/test-utils.js

Sometimes undici fails with `fetch failed` without any other hints, this PR adds the URL that might have caused the fail, which I'm guessing it's the issue here.
Shouldn't break existing tests.
n/a

Improve undici fetch failed errors in tests

---

examples/framework-lit/src/pages/index.astro

Due to an upstream issue in the compiler (https://github.com/withastro/compiler/issues/784), the TS pragma doesn't appear on the correct line in the generated TSX, so the comment didn't work. This PR updates the example with a temporary workaround in the meantime
N/A

fix: update lit example to properly ignore error

---

.changeset/loud-bears-glow.md
packages/astro/src/core/build/plugins/plugin-component-entry.ts
packages/astro/src/vite-plugin-jsx/index.ts

Update the internal `vite-plugin-jsx` to ignore transforming for `astro-entry:` virtual files. These virtual files only contain re-exports to enable treeshaking used exports only (added in #6527), so they can be skipped as they don't contain JSX.
But also it's skipped to avoid this confusing (and harmless) error:
```bash
building client 
10:19:41 PM [renderer] astro-entry:/Users/bjorn/Work/oss/astro/packages/astro/test/fixtures/static-build-frameworks/src/components/PCounter.jsx
Unable to resolve a renderer that handles this file! With more than one renderer enabled, you should include an import or use a pragma comment.
Add import React from 'react' or /* jsxImportSource: react */ to this file.
```
It happens in the `static-build-frameworks` fixture currently. 
Existing tests should pass, …

Fix `astro-entry` error on build with multiple JSX frameworks

---

.changeset/shy-games-punch.md
packages/astro/src/content/vite-plugin-content-imports.ts

In the `astro:content-render-imports` plugin, it calls `getContentEntryModuleFromCache` in the `load` hook, but the cache is only set in `astro:content-imports`'s [`transform` hook](https://github.com/withastro/astro/blob/923dc6311682ca8183232d51df9fb38ef988fb7d/packages/astro/src/content/vite-plugin-content-imports.ts#L68-L74).
This causes this error to happen in tests sometimes. I'm not sure how it used to work before 😅 
```
[astro:content-render-imports] Could not load /Users/bjorn/Work/oss/astro/packages/integrations/markdoc/test/fixtures/entry-prop/src/content/blog/entry.mdoc (imported by test/fixtures/entry-prop/src/content/blog/entry.mdoc?astroPropagatedAssets=true): Unable to render "/Users/bjorn/Work/oss/astro/packages/integrations/markdoc/test/fixtures/entry-prop/src/content/blog …
```

Fix content render imports flow

---

.changeset/flat-peas-wave.md
packages/astro-rss/src/util.ts

- Remove `/1/` regex on RSS canonical URLs. This is legacy code ported from the _old_ RSS package from 2021, and doesn't make sense with our `import.meta.glob` and content collection handlers.
N/A
N/A

Fix: remove odd `/1/` check on RSS canonicals

---

.changeset/rotten-worms-walk.md
packages/astro/src/core/path.ts
packages/astro/test/astro-assets-prefix.test.js
packages/integrations/image/src/utils/paths.ts

Fix https://github.com/withastro/astro/issues/6844
Update `joinPaths` utility to not automatically strip the final path's leading and trailing slash. Surprisingly nothing breaks when I test it locally 😲 
This fixes `build.assetsPrefix` joining paths when the value is a root path like `/prefix/with/me`.
Added a new test, also tested the local examples manually.
n/a. bug fix.

Avoid removing leading slash for `build.assetsPrefix`

---

.changeset/twelve-feet-switch.md
packages/astro/src/vite-plugin-astro-server/response.ts
packages/astro/test/fixtures/ssr-api-route/src/pages/login.js
packages/astro/test/ssr-api-route.test.js

- Using `res.setHeader` which accepts an array of headers, which results in separate header lines. This is required for `set-cookie`.
- Fixes https://github.com/withastro/astro/issues/6525
- Updated an existing test. Using raw sockets so that we can examine the raw response and see that there are 2 separate set-cookie headers. You can't examine this for sure using `fetch` because you can't see the raw response.
N/A bug fix

Ensure multiple cookies set in dev result in multiple set-cookie headers

---

.changeset/chatty-dolls-visit.md
packages/integrations/sitemap/package.json
packages/integrations/sitemap/src/index.ts
packages/integrations/sitemap/src/utils/is-route-prerendered.ts
packages/integrations/sitemap/test/fixtures/ssr/astro.config.mjs
packages/integrations/sitemap/test/fixtures/ssr/package.json
packages/integrations/sitemap/test/fixtures/ssr/src/pages/one.astro
packages/integrations/sitemap/test/fixtures/ssr/src/pages/two.astro
packages/integrations/sitemap/test/ssr.test.js
pnpm-lock.yaml

I tested using the examples, replacing in `package.json` the `@astrojs/sitemap` version with `workspace:*` and making sure it's using `output: "server"` in the `astro.config.mjs`.
Optional: adding `const prerender = true` to a few routes.
Run `astro build` and make sure a `sitemap.xml` is created with no duplicated routes and every SSR route is created.
Optional-2: Add a hardcoded `customPages` definition to sitemap `options`.
If you wish to use this implementation, I'm happy to update the docs.

Sitemap: support SSR routes

---

packages/integrations/sitemap/test/fixtures/ssr/package.json

Build is failing because there are two packages with the same name
CI should pass

fix: double test names

---

.github/workflows/check-merge.yml

The check merge action was still buggy. The request to change the PR status requires a `body` in the request. I want to try to make the body an empty string and see if that works. If it doesn't, we will have to send a body message, which will be annoying because we will see multiple messages from the github bot.
I updated also one of the other actions. They were causing some warnings.
Merge and verify manually.

ci: fix and update check merge workflow

---

.changeset/happy-ears-call.md
packages/astro/test/fixtures/react-component/src/components/WithId.jsx
packages/astro/test/fixtures/react-component/src/pages/index.astro
packages/astro/test/react-component.test.js
packages/integrations/react/client.js
packages/integrations/react/context.js
packages/integrations/react/server.js

Resolves https://github.com/withastro/astro/issues/6849
React's useId hook generates unique IDs by incrementing down the component tree. When multiple react roots are on a single page, these IDs can collide. React provides an option, `identifierPrefix` to prefix ids per root.
Using preact adapters context solution, increment an ID per component rendered on a request, preventing collisions. 
- Ensures each react island can generate unique ids without collisions, improve accessibility
- follows the context pattern used by preact-adapter to increment id per component
- incremental id is added to astro-island element attributes, named `prefix`
- id is passed to react server rendering methods directly as `identifierPrefix` option
- id is read from attributes client side, and passed as options …

Generate unique ids within each React island

---

.changeset/mean-houses-exist.md
packages/astro/config.d.ts
packages/astro/config.mjs
packages/astro/src/assets/index.ts

The service functions were available from `astro/assets`, but it's not intended that people import things from there, as it's an internal file first and foremost. This PR moves the utilities methods to `astro/config`, so they can be imported easily in the same breath as the other utility methods.
https://github.com/withastro/docs/pull/3174

fix: move service functions from astro/assets to astro/config so it can be imported

---

packages/astro/src/@types/astro.ts

Escapes `<style>` tags in the `experimental.inlineStylesheets` text
This was painfully tested.  :sweat_smile: I've made the change in docs source to get it working immediately.
This will make its way into docs.

[docs] escape style tags for config reference

---

.changeset/wise-jars-trade.md
packages/integrations/partytown/README.md

Fixed a code example that was wrongly closed in `partytown` readme.
* BEFORE:
```js
integrations: [partytown({
// Example: Disable debug mode.
config: { debug: false },
})
```
* AFTER:
```js
integrations: [partytown({
// Example: Disable debug mode.
config: { debug: false },
})]
})
```
As only one block of code has been closed, no tests are required.
Within the partytown README there was a block that was not closed correctly, the example has been closed and corrected.

Fix `partytown` README

---

examples/basics/package.json
examples/blog/package.json
examples/component/package.json
examples/deno/package.json
examples/docs/package.json
examples/framework-alpine/package.json
examples/framework-lit/package.json
examples/framework-multiple/package.json
examples/framework-preact/package.json
examples/framework-react/package.json
examples/framework-solid/package.json
examples/framework-svelte/package.json
examples/framework-vue/package.json
examples/hackernews/package.json
examples/integration/package.json
examples/middleware/package.json
examples/minimal/package.json
examples/non-html-pages/package.json
examples/portfolio/package.json
examples/ssr/package.json
examples/with-markdoc/package.json
examples/with-markdown-plugins/package.json
examples/with-markdown-shiki/package.json
examples/with-mdx/package.json
examples/with-nanostores/package.json
examples/with-tailwindcss/package.json
examples/with-vite-plugin-pwa/package.json
examples/with-vitest/package.json
pnpm-lock.yaml

Fix https://github.com/withastro/astro/issues/6998 for now
- First commit updates non-major deps: `pnpm update --filter "@example/*"`
- Second commit update deps with breaking changes: manual with `pnpm outdated --filter "@example/*"`
I made sure the templates with breaking change deps still works by manually running dev and building + previewing them.
n/a. dep update.

Update template deps to latest

---

.changeset/giant-planes-try.md
packages/astro/client-base.d.ts
packages/astro/src/assets/internal.ts

In declaration files, you can't export a namespace, you need to declare it. Otherwise the file isn't considered an ambient declaration anymore and you can't refer to it with a triple slash
Fix https://github.com/withastro/astro/issues/7003
N/A

fix: declare namespace so client-base.d.ts stays an ambient definition

---

.changeset/new-seals-hear.md
packages/astro/package.json

> Closes #7017
This PR fixes the middleware's typing export. Read about the problem on #7017.
https://user-images.githubusercontent.com/12464600/236786864-744c4f50-1390-4950-81bc-b8a03828573e.mp4
With the fix applied:
1. Open the `examples/middleware`;
2. check the `astro/middleware` import (the type should be there)
No docs change is required since this is a functional change.

fix middleware typing export

---

.changeset/clean-carpets-battle.md
packages/astro/src/assets/services/service.ts
packages/astro/test/core-image.test.js

Man `base` is confusing. This PR properly makes it so the path to the endpoint generating the images in SSR is prefixed with the base path
Fix https://github.com/withastro/astro/issues/5807
Added a test
N/A

fix: properly prefix endpoint path with base in SSR

---

.changeset/dry-garlics-push.md
packages/astro/src/vite-plugin-config-alias/index.ts
packages/astro/test/alias-tsconfig-baseurl-only.test.js
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/astro.config.mjs
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/package.json
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/src/components/Alias.svelte
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/src/components/Client.svelte
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/src/components/Foo.astro
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/src/components/Style.astro
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/src/pages/index.astro
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/src/styles/extra.css
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/src/styles/main.css
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/src/utils/constants.js
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/src/utils/index.js
packages/astro/test/fixtures/alias-tsconfig-baseurl-only/tsconfig.json
pnpm-lock.yaml

In Astro versions < 2.3.0, simply declaring a `baseUrl` in your tsconfig would allow for path aliasing. However, commit 8539eb164 added a requirement that `paths` also had to exist for the aliases to be processed. This commit removes that unnecessary requirement so that aliasing can be achieved solely through defining a `baseUrl` again.
It remove the need for a `paths` key in a tsconfig file for path aliasing.
Added tests to ensure that only defining a `baseUrl` works
This could probably cause changes for the https://docs.astro.build/en/guides/aliases/ page to mention that the 'paths' object isn't necessary to achieve path aliasing.

fix: don't require 'paths' object in tsconfig to alias paths

---

.changeset/young-schools-refuse.md
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image-ssr/src/pages/api.ts

Remove the query params before trying to match the request, that way we avoid taking over requests with query params ending in `.png`, ha! I'm unfortunately unsure if there's a better solution at this time for this, as it doesn't necessarily seems to be the most reliable way of only taking over imports we care about, but it works!
Fix https://github.com/withastro/astro/issues/6569
Added a test
N/A

fix(image): Fix astro:assets from interfering with SSR query params ending with image extensions

---

.changeset/nice-shrimps-search.md
packages/create-astro/src/actions/dependencies.ts

Fix a regression on `create-astro` where the dependency installation step always fails
N/A, bug fix

Fix `create-astro` regression

---

.changeset/eleven-hotels-roll.md
packages/astro-rss/src/schema.ts
packages/astro-rss/test/rss.test.js

Fix a bug with `pubDate` validation caused by transforming invalid formatted strings.
Manually tested & I've added a test case to check it correctly catches invalid date strings.
N/A

RSS: Fix string validation of pubDate

---

.changeset/fresh-baboons-switch.md
packages/astro/src/runtime/server/render/util.ts
packages/astro/test/astro-directives.test.js
packages/astro/test/fixtures/astro-directives/src/pages/define-vars.astro

- Closes #7013.
I added another test to the existing `define:vars` test to test the `</script>` being escaped.

Escape closing script tag when using define:vars

---

packages/astro/e2e/lit-component.test.js
packages/astro/e2e/namespaced-component.test.js
packages/astro/e2e/nested-in-preact.test.js
packages/astro/e2e/nested-in-react.test.js
packages/astro/e2e/nested-in-solid.test.js
packages/astro/e2e/nested-in-svelte.test.js
packages/astro/e2e/nested-in-vue.test.js
packages/astro/e2e/nested-recursive.test.js
packages/astro/e2e/shared-component-tests.js
packages/astro/e2e/solid-recurse.test.js
packages/astro/e2e/test-utils.js
packages/astro/e2e/ts-resolution.test.js

While working on https://github.com/withastro/astro/pull/7074, I think I figured out the flaky tests. We were testing component interaction without waiting for it to completely hydrate.
I added a new `waitForHydrate` utility that watches the `astro-island`'s `ssr` attribute to be removed to know that the island has been hydrated. This `ssr` remove behaviour is from [here](https://github.com/withastro/astro/blob/ede36ad1ad60cb114fd22eb387c57e309576c187/packages/astro/src/runtime/server/astro-island.ts#L127).
This brings around 60-90s faster e2e tests as fewer retries are needed.
Ran e2e tests a few times locally.
n/a. internal test fix.

Fix e2e flaky tests

---

.changeset/quiet-gifts-pay.md
.changeset/silver-ties-vanish.md
packages/integrations/cloudflare/src/index.ts
packages/integrations/solid/src/index.ts
packages/integrations/vercel/package.json
packages/integrations/vercel/src/edge/adapter.ts
pnpm-lock.yaml

Part of the fix for https://github.com/withastro/astro/issues/6989
The solid integration was setting the SSR target to `node`, but in a Cloudflare / Vercel edge setup, it should be `webworker`. This PR fixes that.
Also fixes a missing esbuild dep in `@astrojs/vercel`
Manually tested with the PR repro.
n/a. bug fix.

Build edge/worker runtime with webworker ssr target

---

.changeset/long-starfishes-raise.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/endpoint/dev/index.ts
packages/astro/src/core/endpoint/index.ts
packages/astro/src/core/middleware/callMiddleware.ts
packages/astro/src/core/render/dev/index.ts
packages/astro/test/fixtures/middleware-dev/src/middleware.js
packages/astro/test/fixtures/middleware-dev/src/pages/api/endpoint.js
packages/astro/test/middleware.test.js

This PR fixes a bug where the function `renderEndpoint` was called too early, making the middleware effectively not work for ALL API endpoints.
cc @alex-sherwin
Partially addresses https://github.com/withastro/astro/issues/7070
- I renamed the function `call` to `callEndpoint`;
- I moved the warning about "simple" endpoints inside the `callMiddleware` function
I created two test cases
N/A

fix: middleware for API endpoints

---

.changeset/pretty-planets-wink.md
packages/integrations/vercel/src/edge/adapter.ts

Part of the fix for https://github.com/withastro/astro/issues/6989
Similar to https://github.com/withastro/astro/pull/7092, add `edge-light` and `worker` when bundling with esbuild for vercel edge so it bundles the right solid-js entry
Tested with the repro at https://github.com/withastro/astro/issues/6989, making sure solid-js is bundled correctly in `.vercel/output/functions/entry.mjs`
n/a. bug fix.

Add `edge-light` and `worker` to vercel edge bundling

---

.changeset/thirty-squids-relax.md
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image/src/pages/vite.astro

Ignore imports using `?raw` and `?url` in our Assets plugin, so we can leave them to Vite itself
Fix https://github.com/withastro/astro/issues/7082
Added a test
N/A

Fix imports using ?raw and ?url not working when `experimental.assets` is enabled

---

.changeset/ninety-sheep-knock.md
packages/astro/src/core/errors/errors-data.ts

- Quick fix for some over enthusiastic punctuation in an error message.
No testing.
Typo change only

Fix weird periods in `NoMatchingRenderer` error

---

.changeset/plenty-cows-act.md
packages/integrations/markdoc/template/content-module-types.d.ts

- Add `headings` to return type for `render()`
N/A - types
N/A

Fix: add `headings` to `.mdoc` render type

---

.changeset/clever-garlics-relate.md
packages/astro/src/runtime/server/render/astro/render-template.ts
packages/astro/src/runtime/server/render/page.ts
packages/astro/src/runtime/server/render/util.ts
packages/astro/test/fixtures/parallel/package.json
packages/astro/test/fixtures/parallel/src/components/Delayed.astro
packages/astro/test/fixtures/parallel/src/pages/index.astro
packages/astro/test/fixtures/streaming/src/pages/slot.astro
packages/astro/test/parallel.js
pnpm-lock.yaml

This changes the rendering behavior of Astro components to render child components in parallel.
In cases where multiple components in different subtrees fetch data, this data fetching can be done in parallel and will improve loading times in those scenarios.
A test is added to confirm the parallel execution of the artificial delays. Also, an existing test (number of stream chunks) had to be changed, because the parallel execution lead to 2 chunks instead of the expected 3.
Docs & changeset will be added as this is just a draft

Parallelize rendering of sibling components to avoid async waterfalls

---

packages/astro/src/@types/astro.ts

Tiny change so https://docs.astro.build/en/reference/configuration-reference/#experimentalinlinestylesheets to show which Astro version is required for that experimental feature.
Feature changelog:
https://github.com/withastro/astro/blob/edd30d18d105247ffa4d78a5351632e87af05d6f/packages/astro/CHANGELOG.md#L41-L47
n/a

Document inlineStylesheets available astro version

---

.changeset/good-frogs-report.md
packages/astro/src/core/build/plugins/index.ts
packages/astro/src/core/build/plugins/plugin-middleware.ts
packages/astro/src/core/build/plugins/plugin-pages.ts
packages/astro/src/core/build/static-build.ts

This PR creates a new `vite` plugin for the middleware. This plugin is in charge of creating a new virtual module that yields the code of the middleware.
This is an internal change and the current behaviour should stay the same.
This plugin is going to be helpful in the near future for:
- integrations that want to pull the code of the Astro middleware in their middleware pipeline
- a future refactor of how Astro pages will be compiled 
Current tests should pass.
I tested locally if the middleware still works in a pet project of mine.
N/A

refactor: create virtual module for middleware

---

packages/astro/e2e/client-only.test.js
packages/astro/e2e/errors.test.js
packages/astro/e2e/hydration-race.test.js
packages/astro/e2e/multiple-frameworks.test.js
packages/astro/e2e/namespaced-component.test.js
packages/astro/e2e/nested-in-preact.test.js
packages/astro/e2e/nested-in-react.test.js
packages/astro/e2e/nested-in-solid.test.js
packages/astro/e2e/nested-in-svelte.test.js
packages/astro/e2e/nested-in-vue.test.js
packages/astro/e2e/nested-recursive.test.js
packages/astro/e2e/pass-js.test.js
packages/astro/e2e/shared-component-tests.js
packages/astro/e2e/solid-circular.test.js
packages/astro/e2e/solid-recurse.test.js
packages/astro/e2e/test-utils.js
packages/astro/playwright.config.js
packages/astro/test/test-utils.js

- Fix `client:visible` test by manually scrolling the view ourselves
- Assign unique port for each e2e tests. I found even if they're running serially, they could still somehow conflict.
- This technically means we can run the tests in parallel now, but enabling it still leave some tests flaky, especially the HMR tests and the Solid nested React test (`TypeError: Cannot read properties of undefined (reading 'getCurrentStack')` error)
Ran e2e tests locally.
n/a. test refactor.

Fix e2e flaky tests again

---

.changeset/friendly-garlics-chew.md
packages/astro/src/core/build/plugins/plugin-ssr.ts
packages/astro/test/ssr-dynamic.test.js

Use manifest routes for SSR app manifest instead of page components to enable injected routes with SSR.
I don't know whether this is the right way to handle it, but it seemed logical to me looking at the data structures.
- Before, routes created by `injectRoute` didn't work for SSR. Now the injected manifest reuses the routes form the manifest, which also included injected routes.
One test added to the `ssr-dynamic` suite
Docs shouldn't be affected

Fix injectRoute for SSR

---

.changeset/brown-goats-serve.md
packages/integrations/prefetch/package.json
packages/integrations/prefetch/src/client.ts

https://github.com/withastro/astro/pull/7104 added the `"files"` field to all packages to limit the files that are published to npm. The `@astro/prefetch` package only includes the `dist` folder, however, the code tries to import from the `@types` folder, causing the following error:
```
Could not resolve "../@types/network-information.d.ts" from "node_modules/@astrojs/prefetch/dist/client.js"
```
~I added the `@types` folder to the `"files"` field to fix it.~
I changed the import to a triple-slash directive as [suggested](https://github.com/withastro/astro/pull/7123#issuecomment-1554172407) by @bluwy.
I did not test the change as it seems straightforward.
This fixes an expected behavior, so an update to the docs doesn't seem necessary.

fix(prefetch): Fix the inclusion of `@types/network-information`

---

.changeset/eleven-tables-speak.md
packages/integrations/markdoc/src/index.ts
packages/integrations/markdoc/src/nodes/heading.ts
packages/integrations/markdoc/src/nodes/index.ts
packages/integrations/markdoc/src/runtime.ts
packages/integrations/markdoc/test/fixtures/headings-custom/src/content/docs/headings-stale-cache-check.mdoc
packages/integrations/markdoc/test/fixtures/headings-custom/src/pages/[slug].astro
packages/integrations/markdoc/test/fixtures/headings/src/content/docs/headings-stale-cache-check.mdoc
packages/integrations/markdoc/test/fixtures/headings/src/pages/[slug].astro
packages/integrations/markdoc/test/headings.test.js

- Switch from a global `headingSlugger` to a context variable scoped to the config. Adding arbitrary variables to the Markdoc config _was_ endorced by the Stripe team, who uses a `services` pattern for context. We've used `ctx` here.
- Rename `applyDefaultConfig()` to `setupConfig()`. Better captures why this function should be run for each file's transform, and the fact that it sets up context
Add test for heading cache leaks for documents with the same heading IDs
N/A

Fix: Heading ID CI flakiness

---

.changeset/perfect-oranges-tease.md
packages/astro/src/core/build/plugins/plugin-hoisted-scripts.ts

Fixes #7116
The hoisted scripts plugin seems to have been written with the assumption that each chunk is more-or-less an independent chunk of code. This assumption breaks as Vite creates shared chunks when multiple pages use the same scripts. We already consider that a script may import other scripts, but not that it may be imported by others. This leads to a case where we inline a hoisted script and delete it from the bundle while other scripts have a reference to it.
The bug only manifests in large websites where Vite can deduplicate hoisted scripts by creating shared chunks from them. Not sure how to go about making a fixture for this.
Not affected.

fix(hoisted scripts): consider script's dependents

---

.changeset/lemon-flies-smoke.md
packages/astro-rss/src/index.ts

Exposes `RSSFeedItem` type. This will be helpful when we are processing multiple items and want to typecast is correctly before passing it to `rss({}: RSSOptions)` 
Nothing to test specifically since this does not change any core logic
Not sure if we need to mention this in docs that we are exposing the type, since I did not find anything about existing exported types as well like `RSSOptions` 🤔

feat: :art: export rss feeditem type

---

.changeset/tough-pots-visit.md
packages/astro/src/core/app/index.ts
packages/astro/test/fixtures/ssr-api-route-custom-404/src/pages/causes-404.astro
packages/astro/test/ssr-404-500-pages.test.js

- Currently, a 404 response doesn't render any content
- With this change, it will render the 404 page, the same fashion it also renders the 500 page
- Added a test case to the ssr error pages test
Changeset is added

Render 404 page content for existing pages with 404 Response

---

.changeset/odd-geese-shop.md
packages/astro/src/runtime/server/render/util.ts
packages/astro/test/astro-directives.test.js
packages/astro/test/fixtures/astro-directives/src/pages/define-vars.astro

#7044 Introduced the following bug:
https://github.com/withastro/astro/blob/96947fce966591b0fc6e61db7d0c23672961d865/packages/astro/src/runtime/server/render/util.ts#L46
When `value = undefined` then `JSON.stringify(value) = undefined`, which leads to the error `TypeError: Cannot read properties of undefined (reading 'replace')`. 
The change prevents that error.
Added a test where an undefined var is passed to `define:vars`.
This is just a bug fix, so no docs should be needed

fix: value of var could be undefined when using `define:vars`

---

.changeset/dull-teachers-work.md
packages/astro/package.json
packages/astro/src/content/vite-plugin-content-virtual-mod.ts
pnpm-lock.yaml

Fix https://github.com/withastro/astro/issues/7073
Make vite-plugin-content-virtual-mod run `getEntrySlug` serially as it reads the filesystem. Running in parallel all at once could cause the OS to lock reading files.
Manually tested with docs to see if there's a first-page load slowdown. I didn't notice a big difference so this should be good.
n/a. bug fix.

Make vite-plugin-content-virtual-mod run `getEntrySlug` 10 at a time

---

.changeset/fuzzy-cycles-trade.md
packages/astro/src/core/endpoint/index.ts
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/core/render/core.ts
packages/astro/test/middleware.test.js

This PR removes the check around serialisable data. Context: https://github.com/withastro/roadmap/pull/555#issuecomment-1557151100
Removed the test cases
N/A
Will do a PR to update the documentation

chore(middleware): lift restriction around serializable data

---

.changeset/orange-lizards-report.md
packages/astro/src/core/config/vite-load.ts
packages/astro/src/core/sync/index.ts

From @ematipico's suggestion https://github.com/withastro/astro/issues/7073#issuecomment-1557144748, we could prevent Vite watching when spinning up the Vite dev server.
It looks like the watching is already disabled for content collections / `astro sync` via:
https://github.com/withastro/astro/blob/6112671100122904db78aa9f880dbfe957aa0c24/packages/astro/src/core/create-vite.ts#L155
But I updated the Astro config load flow too as that will benefit from it.
Logged `viteServer.watcher.getWatched()` to verify that directories aren't watched.
n/a. internal improvement.

Prevent Vite watching on Astro config load

---

.changeset/static-slot-css.md
packages/astro/src/runtime/server/scripts.ts

In a recent version of Astro we introduced the `<astro-static-slot>` element. Prior to this only `<astro-slot>` and `<astro-island>`. 
When we have this kind of code, we expect the slot to not have an effect ad the div and the image to be on the same line.
```html
<div style="display: flex;">
<astro-static-slot>
<div>Button Content</div>
</astro-static-slot>
</div>
```
It's a simple bug fix, could be tested if browser rendering had apis.
Bug fix

fix: add astro-static-slot to the list of inert tags in astro css

---

.changeset/spotty-glasses-return.md
packages/integrations/mdx/package.json
packages/integrations/mdx/src/index.ts
packages/integrations/mdx/src/plugins.ts
pnpm-lock.yaml

Fix https://github.com/withastro/astro/issues/7176
Remove `@mdx-js/rollup` dep for `@astrojs/mdx` because we're not really using the Rollup plugin entirely. In it's[ source code](https://github.com/mdx-js/mdx/blob/30e4a5d5d561db0b14ec60467ce44d7e3bf27884/packages/rollup/lib/index.js#L44-L45), there's the `name` and `transform` field, and we're replacing it with our own `transform` field: 
https://github.com/withastro/astro/blob/f43300f1bdf80671c66678ea4596b5a0abfde05d/packages/integrations/mdx/src/index.ts#L94-L96
That leaves the `name` being used only, and we can simplify it by copying over the name and remove the dependency.
n/a. internal refactoring.

Remove `@mdx-js/rollup` dependency

---

packages/astro/src/core/app/index.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/redirects/component.ts
packages/astro/src/core/redirects/helpers.ts
packages/astro/src/core/redirects/index.ts
packages/astro/src/core/render/core.ts
packages/astro/test/redirects.test.js

- From the RFC, 308 is a status code used for non-GET permanent redirects. https://github.com/withastro/roadmap/pull/587
- Note that it's not possible to have a non-GET request in SSG, so that case is not tested.
Coming in another issue.

Use status 308 for non-GET redirects

---

.changeset/curvy-hotels-study.md
packages/integrations/partytown/src/index.ts

- Fixes the typescript type for partytown options, no need to pass `undefined` when you don't want to add any config
N.A
N.A

fix: :adhesive_bandage: update partytown options ts type

---

packages/integrations/partytown/README.md

Close https://github.com/withastro/astro/issues/5454
Note that browser extensions could make partytown scripts not working.
I followed the pattern in `@astrojs/image` troubleshooting section: https://docs.astro.build/en/guides/integrations-guide/image/#troubleshooting
n/a
Updated the partytown README.

Document partytown script block by extensions

---

.changeset/dirty-singers-enjoy.md
packages/integrations/mdx/README.md
packages/integrations/mdx/package.json
packages/integrations/mdx/src/index.ts
packages/integrations/mdx/src/plugins.ts
packages/integrations/mdx/src/rehype-optimize-static.ts
packages/integrations/mdx/test/fixtures/mdx-optimize/astro.config.mjs
packages/integrations/mdx/test/fixtures/mdx-optimize/package.json
packages/integrations/mdx/test/fixtures/mdx-optimize/src/components/Blockquote.astro
packages/integrations/mdx/test/fixtures/mdx-optimize/src/components/Strong.astro
packages/integrations/mdx/test/fixtures/mdx-optimize/src/pages/_imported.mdx
packages/integrations/mdx/test/fixtures/mdx-optimize/src/pages/import.astro
packages/integrations/mdx/test/fixtures/mdx-optimize/src/pages/index.mdx
packages/integrations/mdx/test/mdx-optimize.test.js
pnpm-lock.yaml

Add `optimize` option for `@astrojs/mdx` to optimize the MDX output for faster builds and rendering.
Most of the rehype code is copied from https://github.com/withastro/docs/blob/6b6f629e2241dce12dd4763124d00eeb223aa1f4/plugins/rehype-optimize-static.ts, but:
- Removed special heading handling as this rehype plugin will always run last
- Add custom components handling (`export const components` and from a config option)
Added tests to `@astrojs/mdx`. Also manually tested with Astro docs.
Added docs for the new option in the `@astrojs/mdx` README.

Add MDX optimize option

---

.changeset/plenty-geese-fold.md
packages/integrations/vercel/README.md

Property is called `imagesConfig`, matching Vercel's config file. Not `imageConfig`. In truth, it should probably just be named `images` anyway, but that'd be breaking now, shucks.
Fix https://github.com/withastro/astro/issues/7152
N/A
N/A

fix(vercel): Fix typo in README 🤦‍♀️

---

packages/integrations/cloudflare/package.json
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/test/directory.test.js
packages/integrations/netlify/package.json
packages/integrations/netlify/src/shared.ts
packages/integrations/netlify/test/functions/dynamic-route.test.js
packages/integrations/netlify/test/functions/redirects.test.js
packages/integrations/netlify/test/static/redirects.test.js
packages/underscore-redirects/package.json
packages/underscore-redirects/readme.md
packages/underscore-redirects/src/astro.ts
packages/underscore-redirects/src/index.ts
packages/underscore-redirects/src/print.ts
packages/underscore-redirects/src/redirects.ts
packages/underscore-redirects/test/astro.test.js
packages/underscore-redirects/test/print.test.js
packages/underscore-redirects/test/weight.test.js
packages/underscore-redirects/tsconfig.json
pnpm-lock.yaml

- Adds a new package `@astrojs/underscore-redirects` which is used to build the `_redirects` format, shared by Netlify and Cloudflare, from Astro route definitions.
- Unit tests in new package
- Integration test with Cloudflare
N/A, documented as part of release.

Implement redirects in Cloudflare

---

.changeset/eleven-tables-speak.md
.changeset/popular-berries-travel.md
packages/integrations/markdoc/README.md
packages/integrations/markdoc/package.json
packages/integrations/markdoc/src/config.ts
packages/integrations/markdoc/src/extensions/prism.ts
packages/integrations/markdoc/src/extensions/shiki.ts
packages/integrations/markdoc/src/index.ts
packages/integrations/markdoc/src/runtime.ts
packages/integrations/markdoc/test/syntax-highlighting.test.js
pnpm-lock.yaml

- Add the Prism syntax highlighter as an extension
- Exported as `@astrojs/markdoc/prism`
- Introduces `@astrojs/prism` as `@astrojs/markdoc` dependency
- Make shiki a **bundled** dependency to remove the manual `shiki` installation requirement
- Change shiki extension export from `@astrojs/markdoc/config` to `@astrojs/markdoc/shiki`. This lets us mark the Shiki package as `ssr.external`, and removes the need for a manual `shiki` install
- ⭐️ **Note:** this _will_ add `shiki` to your `node_modules` when deploying to SSR. Though with code splitting, shiki won't be imported at runtime unless `@astrojs/markdoc/shiki` is used. Verified manually building with the node and vercel adapters and checking bundled imports
- Add Prism test
- Update Shiki import in tests
- Add new syntax highlighting …

Markdoc - improve syntax highlighting support

---

packages/astro/src/@types/astro.ts
packages/astro/test/fixtures/ssr-redirect/src/middleware.ts
packages/astro/test/fixtures/ssr-redirect/src/pages/middleware-redirect.astro
packages/astro/test/redirects.test.js

- Adds test to verify that redirects that occur within middleware produce the proper redirect output.
- Test added with middleware, verify that the HTML output is the meta refresh.
N/A

Test that redirects can come from middleware

---

.changeset/eighty-gifts-cheer.md
packages/astro/src/core/build/internal.ts
packages/astro/src/core/build/plugins/plugin-css.ts
packages/astro/test/0-css.test.js
packages/astro/test/fixtures/0-css/src/pages/client-only-and-ssr/_components/SvelteOnlyAndSsr.svelte
packages/astro/test/fixtures/0-css/src/pages/client-only-and-ssr/only.astro
packages/astro/test/fixtures/0-css/src/pages/client-only-and-ssr/ssr.astro

Fix https://github.com/withastro/astro/issues/6931
May also fix this issue: https://github.com/withastro/astro/issues/7124 (cc @PxlBuzzard appreciate if you can test this after it's released)
> Preface: "CSS module" here means the CSS rollup module, not [CSS modules](https://github.com/css-modules/css-modules)
The previous CSS deduping flow was incorrect, as it assumed a CSS module found in a SSR build applies to all pages, which isn't the case most of the time. This regression was introduced in #6582
I've fixed this by implementing a more correct CSS deduping strategy, that is to make sure SSR and client builds' generated CSS chunk ids are always derived the same way. That way the chunk name and content are always the same when written to fs.
I've put more in-code comments on how it …

Fix CSS deduping and missing chunks

---

.changeset/eleven-walls-explain.md
packages/astro/e2e/nested-in-react.test.js
packages/astro/e2e/nested-in-vue.test.js
packages/integrations/preact/src/static-html.ts
packages/integrations/react/static-html.js
packages/integrations/vue/static-html.js

While investigating how islands work, I found the hydration mismatch errors in `nested-in-react` and `nested-in-vue` fixtures. That's because in SSR we use the `astro-slot` tag, while in the client we use the `astro-static-slot` tag.
The client isn't right, and it should always use the `astro-slot` tag, so this PR fixes it.
Added test for react and vue. I fixed for Preact too although it doesn't surface any errors, so I didn't made tests for it.
I updated Preact still to be consistent with the other implementation.
n/a. bug fix.

Fix `astro-static-slot` hydration mismatch error

---

packages/integrations/markdoc/test/image-assets.test.js

The markdoc tests are currently failing since https://github.com/withastro/astro/pull/7139. The PR's turbo test run skipped markdoc (for some reason), so this wasn't caught before.
Ran markdoc test manually
n/a. test fix.

Fix markdoc image tests

---

packages/integrations/mdx/src/README.md

Followup to https://github.com/withastro/astro/pull/7151#discussion_r1202441822 suggested by @ematipico
This adds internal docs on how the MDX optimization feature work.
After writing this out, I have no idea if it makes things clearer 😅 I'm not the best explainer and it could be polished a bit more.
n/a
Adds internal documentation for how MDX optimization works.

Document MDX optimize static logic

---

.changeset/olive-rabbits-rhyme.md
packages/astro/src/content/types-generator.ts
packages/astro/src/content/vite-plugin-content-virtual-mod.ts
packages/astro/test/units/dev/collections-mixed-content-errors.test.js

- Resolves #7154 
- Avoid raising errors when collection type is `unknown` (can't be inferred by files in the directory)
- Respect `_` in content glob imports
- Add test for errors on empty collections
N/A

Content collections - fix `.json` collection errors

---

.changeset/many-cats-fry.md
packages/integrations/markdoc/src/index.ts

- Resolves #7061 
- Strip `` from the rendered output based on [the Markdoc doc instructions.](https://markdoc.dev/docs/syntax#comments)
Manually tested the option works
N/A

Markdoc: strip HTML comments from output

---

.changeset/pink-ghosts-end.md
packages/astro/src/vite-plugin-utils/index.ts

- Resolve: #7149 
- Replace "process.env" into "process\\u002Eenv"
No test for this function.
This is fix bug. It unnecessary to update Doc

fix: build fail upon have 'process.env' in *.md file.

---

.changeset/eight-planes-drop.md
packages/integrations/sitemap/src/index.ts
packages/integrations/sitemap/test/filter.test.js
packages/integrations/sitemap/test/fixtures/static/deps.mjs

Fixes #7256
- Change the position of `pageUrls` value attribution.
- Added two test cases using `filter`, one for Static and the other for SSR pages.
n/a

Fix sitemap filter

---

.changeset/rotten-pens-destroy.md
packages/astro/src/content/vite-plugin-content-virtual-mod.ts

- Resolves #7154 
- Ignore underscore directories (nested and top-level) in collection file globs. Only ignored `_underscore-files` in the previous patch.
- Manual testing

Content collections: ignored underscore directories in file glob

---

pnpm-lock.yaml
scripts/package.json
scripts/smoke/check.js

The `test:check-examples` command in CI has been flaky recently. Try running only 5 examples at most in parallel instead  of 28, to ease the CPU.
Tested manually locally.
n/a.

Run example check in parallel with 5 at most

---

.changeset/chilled-insects-melt.md
packages/create-astro/src/actions/template.ts

- Adds a built-in template alias for `starlight`.
- Refactors template logic for readability.
- Once released, can be used like so...
```
pnpm create astro --template starlight
```
Manual
Will be updating the Starlight docs once this is released!

Add 'starlight' as template alias

---

packages/integrations/deno/test/basics.test.ts
packages/integrations/deno/test/dynamic-import.test.ts
packages/integrations/deno/test/helpers.ts

Instead of spinning up a new Deno server for each individual test, we can share it similar to the describe-it pattern where each `it` test shares the same server.
In Deno, it's called [test-step](https://deno.com/manual@v1.34.1/basics/testing#test-steps), so I've refactored the code with this pattern. Locally It improves Deno test time from ~25s to ~5s.
Ran the test locally.
n/a. test refactor.

Simplify Deno test

---

.changeset/stupid-pumpkins-perform.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/build/plugins/plugin-css.ts
packages/astro/src/core/config/schema.ts
packages/astro/test/css-inline-stylesheets.test.js

Stabilize `AstroConfig.build.inlineStylesheets`.
Existing ones should pass.
I think [Configuration reference](https://docs.astro.build/en/reference/configuration-reference/#experimentalinlinestylesheets) as-is would be sufficient.

Stabilize inline stylesheets

---

.changeset/khaki-onions-relax.md
packages/astro/env.d.ts
packages/astro/src/runtime/server/render/component.ts
packages/astro/src/vite-plugin-html/transform/index.ts

The export shape for HTML component is an object with a `render` function on it, this is very cool but unfortunately, it's an invalid type for JSX. This PR changes it to be a default exported function instead, which doesn't change the usage.
This PR also includes a small change to the type reference in `env.d.ts` to point to `client-base.d.ts` instead of `client.d.ts`, as the later includes some definitions that we should be overwriting later on
Fix https://github.com/withastro/language-tools/issues/447
Fix https://github.com/withastro/language-tools/issues/557
Tests should still pass!
N/A

fix(html): Export HTML components as default export so their type is valid JSX

---

packages/integrations/netlify/README.md

Changes the note syntax in the Netlify README so that the note renders properly in Docs.
No tests. Docs.
Will end up properly in docs.

[docs] fix note syntax in Netlify README

---

packages/astro/src/core/errors/errors-data.ts

Updates link in two error messages to the reference location of Astro.redirects
No tests.
Will not make docs sad.

[docs-errors] Astro.redirects link changed

---

.changeset/shaggy-deers-end.md
packages/integrations/markdoc/README.md
packages/integrations/markdoc/components/Renderer.astro
packages/integrations/markdoc/components/TreeNode.ts
packages/integrations/markdoc/test/fixtures/render-null/markdoc.config.mjs

- Replace the `Fragment` special case for arrays with a `.map` from the Renderer. It seems assets aren't propagated when the parent is _also_ a component. Code be an issue with propagation within slots?
- Update test case to use README recommendation
- Fix backwards spread order in `nodes` examples

Fix missing styles and scripts on `document: {render:null}`

---

.changeset/sour-turtles-tap.md

#7314 changes the peer dep ranges which is a breaking change, marking it as `major` from `patch` (https://github.com/withastro/astro/pull/7314#issuecomment-1579600612)
n/a
n/a

Mark #7314 changeset as major

---

.changeset/large-keys-peel.md
packages/astro/src/cli/index.ts

- Remove `instanceof ZodError` catch-all from our error logger. This could unintentionally grab _any_ Zod error (not just config errors), causing confusion for user-built Zod code.
- Move telemetry and error formatting to `handleConfigError()`. This function seems to catch all config errors before hitting the base `process.exit` already.
Manual testing
N/A

Fix: catch and report config errors from `handleConfigError`

---

.changeset/kind-cycles-smile.md
packages/astro/src/core/build/generate.ts
packages/astro/src/core/errors/errors-data.ts

- This adds a readable error when a dynamic route fails to validate.
- Manual testing that readable error throws
- Add new error code

Better dynamic route regex error

---

.changeset/modern-turkeys-shop.md
packages/markdown/component/Markdown.astro

- Fixes https://github.com/withastro/astro/issues/7335
- Previously, this error message relied on the function name of Astro.redirects. That function name changed which broke the error message.
- Think we should just remove this error (which doesn't actually stop you from building). Because:
- There's no way for an Astro component to know that the app is running in SSG or SSR mode.
- We don't want to add one, especially not to accommodate this feature.
- Very few people are still using this component.
Did not
N/A, bug fix

Remove error message for using Markdown component

---

.changeset/swift-flies-press.md
packages/astro/src/core/endpoint/index.ts
packages/astro/src/prerender/routing.ts
packages/astro/test/redirects.test.js

- Fixes https://github.com/withastro/astro/issues/7322
- Slightly different path taken in dev which is why this was failing.
- Used existing redirect test fixture, added dev server test.
N/A, bug fix

Fix redirects in dev mode

---

.changeset/thirty-books-smoke.md
.changeset/yellow-plants-stare.md
packages/astro/src/core/add/index.ts
packages/create-astro/package.json
packages/create-astro/src/messages.ts
pnpm-lock.yaml

- Introduced a fix for #7279 by introducing a utility to check the preferred package manager config to find any custom package registry, defaulting to the public npm registry (which is currently in use)
I'm not sure how to effectively test this fix without affecting the entire build process. Happy to accept suggestions.
This should enable Astro to behave as expected for users with custom package registries (such as large enterprises who might block the public npm registry for security or efficiency reasons).

Fixes an issue where create Astro doesn't respect custom npm registries

---

package.json
pnpm-lock.yaml

- pnpm introduced a new lockfile version in 8.6.0. This is the first release bumping the package lock to a new version, 6.1 ([see release notes](https://github.com/pnpm/pnpm/releases/tag/v8.6.0))
- bump `packageManager` to >=8.6.0
- recreate lockfile

chore: bump pnpm requirement 8.6.0

---

.changeset/seven-carpets-accept.md
packages/astro/package.json
packages/astro/src/content/vite-plugin-content-imports.ts
packages/astro/src/core/errors/errors-data.ts
packages/integrations/markdoc/package.json
pnpm-lock.yaml

- Resolves #6764 
- Add readable error message for unsupported `transform()` return values. We unfortunately support _any_ return value from a transform, since all data needs to be serialized at build time to avoid shipping your content config to SSR environments.
Manual testing
New error data entry

Fix: better collection entry devalue error

---

.changeset/early-colts-punch.md
examples/with-markdoc/package.json
packages/integrations/markdoc/package.json
packages/integrations/markdoc/src/index.ts
packages/integrations/markdoc/src/utils.ts
pnpm-lock.yaml

- Resolves #7325
- Use `default` instead of `node` for package exports. This was breaking commonjs resolution used by the cloudflare adapter
- Move utils that rely on node to the index file. These were getting bundled into the runtime
Manual test of a prod build using cloudflare
N/A

Fix Markdoc cloudflare errors

---

.changeset/yellow-icons-attack.md
packages/astro/src/content/vite-plugin-content-virtual-mod.ts
packages/astro/src/core/errors/errors-data.ts

- Resolves #7133 - this issue discovered that you can create duplicate content entry slugs with the `slug` frontmatter property. This silently maps multiple entries to the same identifier, breaking `getEntryBySlug()` and our internal rendering logic.
- **Raise an error** when this is detected. There may be good reasons to allow multiple entries with the same slug. But today, this is difficult to support in a non-breaking way. 
Manually test that error is readable
New AstroErrorsData entry

Raise error for duplicate content entry slugs

---

.changeset/proud-vans-approve.md
packages/astro/src/@types/astro.ts

- Changed `config.redirects` from `RedirectConfig` to `Record<string, RedirectConfig>` (fix #7365)
No testing is needed for this minor type definition, I think.
No docs were added as the code now follows the docs.

Fixed `AstroUserConfig`'s redirect type definition

---

.changeset/angry-socks-sell.md
packages/integrations/cloudflare/package.json
packages/integrations/cloudflare/src/runtime.ts
packages/integrations/cloudflare/src/server.advanced.ts
packages/integrations/cloudflare/src/server.directory.ts
packages/integrations/cloudflare/test/cf.js
packages/integrations/cloudflare/test/fixtures/cf/astro.config.mjs
packages/integrations/cloudflare/test/fixtures/cf/package.json
packages/integrations/cloudflare/test/fixtures/cf/src/pages/index.astro
packages/integrations/cloudflare/test/test-utils.js
pnpm-lock.yaml

This pull request expose the Cloudflare `caches` API and cf object (request metadata provided by Cloudflare's edge) to the runtime object.
Cloudflare add some usefull informations about the request such as geolocation properties see [the docs](https://developers.cloudflare.com/workers/runtime-apis/request#incomingrequestcfproperties)
``` ts
const runtime = getRuntime(Astro.request);
const visitor_country  = runtime.cf?.country;
```
The Cloudflare cache API can now be used.
``` ts
const runtime = getRuntime(Astro.request);
const cachedObject = await runtime.caches?.default.match(Astro.request);
```

[Cloudflare integration] Expose cf metadata and Cloudflare caches API

---

.changeset/modern-lobsters-sparkle.md
.github/workflows/ci.yml
packages/integrations/deno/src/index.ts
packages/integrations/deno/test/basics.test.ts
packages/integrations/deno/test/fixtures/basics/src/pages/nodecompat.astro

It seems to be a use case that's receiving more and more interest. Deno can leverage built-in node modules, but it's blocked by an overly restrictive configuration set by the adapter.
[nodecompat.astro](https://github.com/withastro/astro/pull/7288/files#diff-cde1d6bd05d7fffc08097404004b322be91bd41493cbbfbc49b961f64e73da2a)
Not a user facing change, though a note somewhere could be useful.

Node built-in modules support for Deno adapter

---

.changeset/beige-schools-hang.md
.changeset/real-spies-pretend.md
packages/astro/e2e/fixtures/tailwindcss/astro.config.mjs
packages/astro/test/fixtures/astro-scripts/astro.config.mjs
packages/astro/test/fixtures/middleware-tailwind/astro.config.mjs
packages/astro/test/fixtures/tailwindcss-ts/astro.config.ts
packages/astro/test/fixtures/tailwindcss/astro.config.mjs
packages/integrations/tailwind/README.md
packages/integrations/tailwind/src/index.ts

Following up #6724 (major), this renames:
- `config.path` to `configFile`
- `config.applyBaseStyles` to `applyBaseStyles`
The `config.` prefix is a bit redundant 🤔 I also chose `configFile` over `configPath` as that's the same name used by Vite and `vite-plugin-svelte`.
Existing test should pass
Updated the README to reflect the new option names.

Rename tailwind integration options

---

.changeset/large-ants-tap.md
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/static-build.ts
packages/astro/test/custom-404-injected-from-dep.test.js
packages/astro/test/fixtures/custom-404-injected-from-dep/astro.config.mjs
packages/astro/test/fixtures/custom-404-injected-from-dep/package.json
packages/astro/test/fixtures/custom-404-injected-from-dep/src/pages/index.astro
packages/astro/test/fixtures/custom-404-pkg/404.astro
packages/astro/test/fixtures/custom-404-pkg/package.json
pnpm-lock.yaml

- Closes #7397
- Fixes edge case where injected routes would emit an unsupported entry file name at build time
- Also updates our static build logging to fallback to the injected route pattern if an injected route is being generated. Previously, it would show the relative path to the injected component inside of `node_modules`
Existing tests should pass, additional `injectRoute` from packages added
No, bug fix only

Fix injected route edge case

---

examples/hackernews/src/components/Comment.astro
examples/hackernews/src/pages/stories/[id].astro

- Remove extra "ago" in Hackernews example
| Before                                                                                                                      | After                                                                                                                       |
|-----------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------|
| <img width="404" alt="image" src="https://github.com/withastro/astro/assets/46791833/02e9b130-94f8-4a98-ae45-ac913801862d"> | <img width="505" alt="image" src="https://github.com/withastro/astro/assets/46791833/d50ff15b-a3b6-4ccc-b065-cf0872474c74 …

remove extra "ago" in hackernews example

---

.changeset/clever-apes-shop.md
packages/integrations/cloudflare/src/server.advanced.ts
packages/integrations/cloudflare/src/server.directory.ts

- The cloudflare context was spread. This did not work and waitUntil was not passed on as intended.
( This might also be an issue for other context runtime functions )
- Wait until has to be "proxied" through a function, passing the reference alone will trigger illegal invocations.
Tested on our own environment.
Has been tested on our `advanced` mode website.
I cannot speak for `directory` mode, but I assume the problem is the same.
No need to update docs,  `waitUntil` should now work as intended.
I did not bother to mock waitUntil since we already have a mock In our project.
Its up to the Astro team to decide from this point on. But you could do something like what we do:
```typescript
waitUntil: (promise: Promise<any>) => {
if (runtime?.waitUntil) {
runtime.waitUntil(promise);
} else { …
```

fix: cloudflare waitUntil not working as inteded with getRuntime

---

.changeset/sour-teachers-kiss.md
packages/astro/src/@types/astro.ts

Closes https://github.com/withastro/astro/issues/7398
For some reason `server.open` wasn't correctly typed. This fixes it.
Manual check

fix: document `open` option

---

.github/ISSUE_TEMPLATE/---01-bug-report.yml
.github/ISSUE_TEMPLATE/config.yml

- update the bug report template by adding a new section called "What's the expected result", where the reporter should tell us what they expect. This is useful, because also the expectations are a form of feedback and dicussion
- fix the `config.yml`, the link to the discussions was pointing to the old repo (even though there's a redirect in place)
N/A
N/A

chore: update bug report template

---

.github/workflows/ci.yml

Adds `.github/ISSUE_TEMPLATE` to the list of paths to ignore.
N/A
N/A

ci: don't run workflow for `ISSUE_TEMPLATE`

---

.changeset/smooth-jokes-watch.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/node.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/endpoint/index.ts
packages/astro/src/core/render/context.ts
packages/astro/src/core/render/core.ts
packages/astro/src/core/render/dev/index.ts
packages/astro/src/core/request.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/ssr-locals/package.json
packages/astro/test/fixtures/ssr-locals/src/pages/api.js
packages/astro/test/fixtures/ssr-locals/src/pages/foo.astro
packages/astro/test/ssr-locals.test.js
packages/astro/test/test-adapter.js
packages/integrations/node/README.md
packages/integrations/node/src/nodeMiddleware.ts
packages/integrations/node/test/fixtures/locals/package.json
packages/integrations/node/test/fixtures/locals/src/pages/api.js
packages/integrations/node/test/fixtures/locals/src/pages/foo.astro
packages/integrations/node/test/locals.test.js
pnpm-lock.yaml

Please read https://github.com/withastro/astro/pull/7049 for more context.

feat: expose locals to render api and from requests in dev mode

---

.changeset/cyan-vans-clap.md
packages/astro/src/core/build/static-build.ts
packages/astro/src/integrations/index.ts
packages/astro/test/units/integrations/api.test.js

While working on some fixes today, I noticed `astro:build:setup` hook's `updateConfig` util doesn't actually update the config.
In contrary, the `astro:config:setup` hook's `updateConfig` util does actually update the astro config. So the above seems like a bug to me, which is fixed here.
Added unit test.
Looks like it's not documented 🤔 https://docs.astro.build/en/reference/integrations-reference/#astrobuildsetup. The feature is added in https://github.com/withastro/astro/pull/3392

Fix `astro:build:setup` hook `updateConfig` utility

---

.changeset/clever-rings-draw.md
packages/create-astro/package.json
packages/create-astro/src/messages.ts
pnpm-lock.yaml

- Resolves #7379
- Switch from `preferred-pm` to the `which-pm-runs` package we already use for detecting npm versions during the "install" step (see #7326). Seems `preferred-pm` does a lot of extra work to crawl lock files and `node_modules` to find the package manager. This result can differ from the "install" step, which doesn't seem right.
- Manual testing to ensure npm, yarn, and pnpm correctly resolve.
N/A

fix: `pnpm` failure on `create-astro`

---

.changeset/six-keys-cheat.md
packages/astro/src/integrations/index.ts
packages/astro/src/vite-plugin-markdown/content-entry-type.ts

- Remove content collections mapper for MDX version 0.17.X and below
Make sure nothing breaks
changelog should suffice!

Chore: remove legacy mdx content collections handler

---

.changeset/honest-flies-care.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/config/settings.ts
packages/astro/src/core/routing/manifest/create.ts

Fixes #7415
- Add a boolean property to set prerender value when injectingRoutes
- Effectively set `/_image` endpoint with `prerender: false` (was added as a prerendered asset/route before)
Again, I would love very much to add a couple of tests around manifest and/or routing settings, but could find relevant test suites so far. Guidance would be much appreciated.
No change relevant to user.

fix(astro:assets): inject /_image endpoint with prerendered=false on serverLikeOutput

---

.changeset/nervous-paws-knock.md
packages/integrations/vercel/src/lib/redirects.ts
packages/integrations/vercel/test/redirects.test.js

Fix https://github.com/withastro/astro/issues/7444
It was generating redirects from `/` to `//`, which was causing infinite redirects. I've removed creating redirects for the root page, which should fix this.
I don't see `@astrojs/underscore-redirects` creating redirects based on `trailingSlash` so they might be unaffected.
Added test in vercel
n/a. bug fix.

Fix vercel redirects with trailingSlash always

---

.changeset/tiny-lemons-sit.md
packages/astro/src/core/module-loader/loader.ts
packages/astro/src/core/render/dev/vite.ts
packages/astro/test/units/dev/styles.test.js

- Fixes https://github.com/withastro/astro/issues/7097
- We can't trust `importedModules` to be true imports. It includes stuff tracked for HMR.
- Using `importers` to verify that an import is an import.
- This is slower, O(n), but necessary. A dev-only issue.
- Added a new unit test
N/A

Prevent accidental CSS inclusion in dev

---

.changeset/cool-birds-prove.md
packages/astro/src/core/render/dev/vite.ts
packages/astro/src/core/util.ts

Fix a small regression from https://github.com/withastro/astro/pull/7381, where virtual modules are not properly detected as `importedModules` as they are represented as `\0astro:content`, but the URLs are `/@id/__x00__astro:content`.
I fixed the issue by inverting the `/@id/` handling to the URLs, so that we can compare directly.
I made refactors along the way, the 3 commits each show step-by-step changes. The 3rd commit is the actual fix.
No changeset as it's fixing an unreleased bug.
Existing test should pass
n/a. bug fix.

Fix markdoc test fail in main

---

packages/integrations/node/README.md

Typo fixed in `node.mdx`
A typo has been fixed, no test is needed.
Typo fixed in `node.mdx`

Typo fixed in `node.mdx`

---

.changeset/flat-papayas-invite.md
packages/astro/src/content/vite-plugin-content-virtual-mod.ts

Fixes #7406 
Makes it possible to run astro underneath a path that contains leading underscores, like e.g. `/_my/path/to/site/`.
- Make the glob patterns in the `astroContentVirtualModPlugin` relative to the content directory
I really don't know how I should test this using a written test. Tested it manually instead.
Still, out of curiosity I ran `pnpm run test`. There were a few tests that were failing for me, regardless of the proposed change from this PR.
This is a bugfix, no docs needed I guess

fix: Installs underneath a path containing leading underscores

---

.changeset/chilly-pants-fix.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/build/internal.ts
packages/astro/src/core/build/plugins/plugin-middleware.ts
packages/astro/src/integrations/index.ts
packages/astro/test/middleware.test.js
packages/astro/test/ssr-split-manifest.test.js
packages/astro/test/test-adapter.js
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/test/edge-middleware.test.js

This is another feature towards the support of Vercel Edge Middleware.
This feature exposes the file path of the middleware file emitted during the astro build.
I extended the functionality of the test adapter and created a test that makes sure that the file exists and it has content.
I will document the new payload towards the end of the feature.

feat: expose middleware URL to integrations

---

packages/integrations/sitemap/README.md

- Removes use of `txt` as a language tag in a code block, which is [not valid](https://github.com/shikijs/shiki/blob/main/docs/languages.md#all-languages) and causes error logging in docs.
- Had to use a `` comment because otherwise Prettier tries to remove the whitespace between the opening backticks and the metadata docs uses for insertion highlighting and filename.
- No changeset because in non-docs contexts this change is essentially invisible.
Docs-only, n/a.

Remove invalid code block language tag in sitemap README

---

.changeset/happy-stingrays-carry.md
packages/astro/src/vite-plugin-astro/compile.ts
packages/astro/src/vite-plugin-jsx/index.ts

Handle upcoming esbuild 0.18 changes that will be introduced by Vite 4.4. More context at https://github.com/vitejs/vite/pull/13525#issuecomment-1596678961 where Astro was failing in `vite-ecosystem-ci`.
Manually linked Vite locally and ran test
n/a.

Handle esbuild 0.18 changes

---

.changeset/brave-waves-battle.md
packages/astro/CHANGELOG.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/build/plugins/plugin-ssr.ts
packages/astro/src/core/build/static-build.ts
packages/astro/src/core/build/types.ts
packages/astro/src/integrations/index.ts
packages/astro/test/ssr-split-manifest.test.js

There were two issues:
- the test case was using `for..in` instead of `for..of`, because of that, the test was running but the for loop wasn't executed. Fixing that showed the issue and it was failing;
- fixed the path of `entryPoints`, which now uses the correct `build.server` URL
- we forgot to document the introduction of `entryPoints` in a changeset; we can't create a new changeset now because the feature is already released. I changed `CHANGELOG.md`. Once accepted, I will change the text of https://github.com/withastro/astro/releases/tag/astro%402.7.0
Fixed the current test case

fix: correct URL for entry points

---

.github/workflows/main.yml

Adds a condition to the Discord congrats bot action to not post if the commit message matches the auto-formatter commit message of `[ci] format`.
Should help reduce some unnecessary noise:
We do something like this in docs already.
N/A.

Don’t post Discord congrats for auto-formatter commits

---

packages/integrations/markdoc/src/runtime.ts

- This module is used by the Markdoc runtime and does not include bundled types (internal export). ts ignore!

Fix: `ts-expect-error` on astro runtime types

---

.changeset/unlucky-paws-own.md
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/internal.ts
packages/astro/test/fixtures/ssr-split-manifest/src/pages/prerender.astro
packages/astro/test/ssr-split-manifest.test.js
packages/astro/test/test-utils.js
packages/integrations/node/test/prerender.test.js

Closes https://github.com/withastro/astro/issues/7466
Pages in `buld.split` mode are emitted in a different way, and we didn't handle this different way for pre-rendered pages
Added a couple of test cases
N/A

fix: correctly handle prerender pages in split mode

---

.github/workflows/ci.yml
packages/integrations/alpinejs/README.md

- Uses the head repository’s name as the source repository for documentation generation when running in a PR from a fork (hopefully 😅)
- Making this PR from a personal Astro fork to test this works — hopefully these changes also work for PRs not coming from a fork.
Added a docs change, which successfully ran docgen to test and then reverted.
CI bug fix, n/a.

Use head repository name for docgen in smoke test

---

packages/astro/src/core/endpoint/dev/index.ts
packages/astro/src/core/render/dev/index.ts
packages/astro/src/core/render/index.ts
packages/astro/src/core/render/renderer.ts
packages/astro/src/prerender/routing.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/units/render/jsx.test.js

In the `preload` call, we're passing `[renderers, component]` everywhere. The `preload`'s responsibility is to only load the component, so it should return the component directly instead of a tuple.
The `renderers` were returned because it's used to assign to `env.renderers` in dev.
In this PR, I made `preload` return `component` directly, and assign `env.renderers` itself to not leak it.

Refactor component and renderers loading flow

---

.changeset/tricky-snails-poke.md
packages/integrations/vercel/README.md
packages/integrations/vercel/src/lib/fs.ts
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/test/fixtures/basic/astro.config.mjs
packages/integrations/vercel/test/fixtures/basic/package.json
packages/integrations/vercel/test/fixtures/basic/src/pages/one.astro
packages/integrations/vercel/test/fixtures/basic/src/pages/two.astro
packages/integrations/vercel/test/split.test.js
pnpm-lock.yaml

- This adds support for `build.split: true` in the Vercel adapter. Similar to cloudflare, a new function folder is created for each one.
Manually testing.
TBD

Split support in the Vercel Serverless adapter

---

packages/astro/src/@types/astro.ts
packages/astro/src/cli/index.ts
packages/astro/src/cli/telemetry.ts
packages/astro/src/core/add/index.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/config/settings.ts
packages/astro/src/core/dev/container.ts
packages/astro/src/core/dev/dev.ts
packages/astro/src/core/preview/index.ts
packages/astro/src/core/render/dev/environment.ts
packages/astro/src/core/render/environment.ts
packages/astro/src/vite-plugin-astro-server/request.ts
packages/astro/test/test-utils.js
packages/astro/test/units/routing/route-matching.test.js
packages/astro/test/units/shiki/shiki.test.js

- Use telemetry singleton everywhere.
- Refactor how tests disable telemetry.
We currently have code that passes it through several functions, because tests can then pass a telemetry stub to disable telemetry. I think it's simpler to set `process.env.ASTRO_TELEMETRY_DISABLED = true` instead to disable this so we don't leak the test implementation details.
n/a.

Refactor telemetry usage flow

---

.changeset/brown-shrimps-hug.md
.changeset/good-pigs-fetch.md
packages/astro/src/core/middleware/index.ts
packages/integrations/vercel/README.md
packages/integrations/vercel/package.json
packages/integrations/vercel/src/lib/nft.ts
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/src/serverless/entrypoint.ts
packages/integrations/vercel/src/serverless/middleware.ts
packages/integrations/vercel/test/edge-middleware.test.js
packages/integrations/vercel/test/edge-middleware.test.js.snap
packages/integrations/vercel/test/fixtures/middleware/astro.config.mjs
packages/integrations/vercel/test/fixtures/middleware/src/vercel-edge-middleware.js
pnpm-lock.yaml

This PR connects the Vercel Edge Middleware to the Astro middleware:
- created a new API called `trySerializeLocals` to serialise the `locals`. This is important because these `locals` will travel via headers, and we need to keep them when they are transferred from the vercel middleware to the Astro middleware;
- ~created a new API inside the `@astrojs/vercel` adapter, this API is called `createLocals` and allows users to initialize their `locals` with anything they want. The function accepts an object that contains `request` and `context`. You can check [Vercel documentation](https://vercel.com/docs/concepts/functions/edge-middleware/middleware-api#edge-middleware-signature);~ As per @bluwy suggestion, the new API is actually a new key file called `vercel-edge-middleware`, it receives an …

feat: connect vercel edge middleware to astro

---

.changeset/fair-trees-jump.md
packages/astro/src/core/add/index.ts
packages/create-astro/src/messages.ts

- Resolves #7471.
- Falls back `create-astro` and `astro add` registry commands to default NPM registry
- Fixes issues for Bun users 👍🏻 
Tested manually, we don't have Bun in CI

Fallback to default `npm` registry if config command fails

---

packages/astro/src/vite-plugin-astro-server/route.ts

Remove unused code since #4087
In that PR, it's moving the call of `getParamsAndProps` from `handleRoute` to `matchRoute`, which is now here: 
https://github.com/withastro/astro/blob/bca45bebe62e07fd7187e18f4982a3f28910093f/packages/astro/src/vite-plugin-astro-server/route.ts#L51-L60
`matchRoute` is already called before `handleRoute` at here:
https://github.com/withastro/astro/blob/bca45bebe62e07fd7187e18f4982a3f28910093f/packages/astro/src/vite-plugin-astro-server/request.ts#L68-L70
https://github.com/withastro/astro/blob/bca45bebe62e07fd7187e18f4982a3f28910093f/packages/astro/src/vite-plugin-astro-server/route.ts#L178-L179
So the second `getParamsAndProps` call isn't needed and it's removed in this PR.
n/a.

Remove unused getParamsAndProps call

---

.changeset/moody-singers-develop.md
packages/astro/e2e/fixtures/pass-js/src/components/React.tsx
packages/astro/e2e/fixtures/pass-js/src/pages/index.astro
packages/astro/e2e/pass-js.test.js
packages/astro/src/runtime/server/serialize.ts
packages/astro/test/serialize.test.js

I added a special case for the serialization of `undefined` so that `serializeProps` doesn't serialize it as `null`.
Closes #7528.
I expanded on the existing serialization tests and added a new case specifically for `undefined`.
I also tested it in [the example I provided for the issue](https://gitlab.com/wackbyte/astro-serializes-undefined-as-null) by changing its `astro` dependency to the `astro` package from this PR's branch.
AFAIK the specific behavior of serialization is not documented, so no docs were added.
I decided to make the changeset a patch bump, but I'm not sure if it would be considered a breaking change instead.

fix: don't serialize `undefined` as `null`

---

.changeset/old-seahorses-fold.md
packages/astro/src/core/add/index.ts
packages/create-astro/package.json
packages/create-astro/src/messages.ts
pnpm-lock.yaml

- Fixes #7480 (supports http), fixes #7362 (follows redirects + handles trailing `/`)
- In the method "getVersion", before sending request, if the registry ends with "/", trim it.
When I use the registry "https://registry.npmmirror.com/", create-astro will be failed because the request of "getVersion" gets  the 404 error and the error is not be caught.
I add the code and link the local package to global by using ``` pnpm link -g ```, and then I run ```create-astro``` again. I am successfully into creating app.
Bug fixes only

Fix multiple `create-astro` registry issues

---

packages/integrations/alpinejs/README.md
packages/integrations/deno/README.md
packages/integrations/image/README.md
packages/integrations/lit/README.md
packages/integrations/markdoc/README.md
packages/integrations/mdx/README.md
packages/integrations/partytown/README.md
packages/integrations/preact/README.md
packages/integrations/prefetch/README.md
packages/integrations/react/README.md
packages/integrations/sitemap/README.md
packages/integrations/solid/README.md
packages/integrations/svelte/README.md
packages/integrations/tailwind/README.md
packages/integrations/vue/README.md

- In https://github.com/withastro/docs/pull/3635 we prepared Astro Docs for the upcoming switch of our code block rendering to Expressive Code. This preparation was required because defining code block titles by adding a bold paragraph directly above the fenced code block is no longer supported.
- As our integration guides in Astro Docs get automatically generated from the integration README files in this repo, this PR also applies the required changes to the READMEs here.
- No testing needed, pure docs changes.
- It's all about docs! 😄

Integration READMEs: Move code block titles into comments to match docs

---

.changeset/grumpy-readers-draw.md
packages/astro/src/@types/astro.ts

`APIContext` is generic so that `props` can be typed, but `APIRoute`, which composes `APIContext`, is not likewise generic. This PR changes that.
No tests, just a backwards-compatible change to a type.
No docs added, it was intuitive to me to expect `APIRoute` to be generic and I was rather surprised that it wasn't already.

Make APIRoute generic like APIContext

---

.changeset/giant-crews-tell.md
packages/astro/package.json
packages/astro/src/runtime/server/render/util.ts
packages/astro/test/astro-directives.test.js
packages/astro/test/fixtures/astro-directives/src/pages/define-vars.astro
pnpm-lock.yaml

- Fixes #7272
- Requires compiler PR https://github.com/withastro/compiler/pull/812
- Updates `addAttribute` logic to support `[{ obj: 'value' }, defineVarsValue]` for `style` attribute
`astro-directives` test updated
Bug fix only

Update style attribute behavior for better object support

---

.changeset/few-ants-brake.md
packages/integrations/image/src/lib/get-picture.ts
packages/integrations/image/test/picture-ssg.test.js
packages/integrations/image/test/picture-ssr-build.test.js
packages/integrations/image/test/picture-ssr-dev.test.js

- Fixes #7481
- `encodeURI`ing the whole `src` has unwanted side effects other than the original purpose.
- Encoding only ` `(space characters) seems to be the only way to make sure there are no side effects.
- See #7340 for the original/wanted change.
- Added some assertions to the unit tests.
- Fixed bug in `Picture` and `getPicture` that generates invalid dev URLs.

fix: make `Picture` generate valid dev URLs

---

packages/integrations/sitemap/src/config-defaults.ts

CI is currently failing because `organize-imports-cli` is incorrectly stripping out the import in this file for some reason.
Ran `pnpm format:ci` locally
n/a

Fix incorrect format from organize-imports-cli

---

.github/workflows/ci.yml

The CI lint workflow is failing. I think it's because of the recent eslint change (#7425), the third-party action doesn't handle well with the breaking changes.
Anyways the third-party action doesn't seem to be needed since we had disable `auto_fix`, and the auto commit feature never really ran. Instead we can run our own `pnpm run lint` command to have the same & simpler effect.
The lint CI should pass.
n/a

Fix CI lint command

---

.changeset/chilled-books-shave.md
packages/astro/src/runtime/server/render/util.ts

This batches iterator buffering to solve #7460
Difficult due to inability to count the number of cals to `setTimeout`. Will be tackled in a different PR.
Changeset is included

Batch iterator buffering to reduce number of timeout calls

---

packages/astro/src/@types/astro.ts

Fix the docs
It doesn't appear https://docs.astro.build/en/reference/configuration-reference/#buildsplit
N/A
N/A

chore: fix incorrect default type

---

packages/astro/src/core/build/generate.ts
packages/astro/src/core/render/params-and-props.ts
packages/astro/src/core/render/route-cache.ts

Handle a TODO for `callGetStaticPaths`. Let the function handle the caching itself instead of the consumers.
n/a

Handle callGetStaticPaths TODO

---

packages/astro/src/core/render/environment.ts
packages/astro/src/core/render/index.ts
packages/astro/test/units/config/config-server.test.js
packages/astro/test/units/config/format.test.js
packages/astro/test/units/dev/collections-mixed-content-errors.test.js
packages/astro/test/units/dev/collections-renderentry.test.js
packages/astro/test/units/dev/hydration.test.js
packages/astro/test/units/dev/restart.test.js
packages/astro/test/units/render/components.test.js
packages/astro/test/units/render/head.test.js
packages/astro/test/units/render/jsx.test.js
packages/astro/test/units/routing/route-matching.test.js
packages/astro/test/units/test-utils.js
packages/astro/test/units/vite-plugin-astro-server/request.test.js

- Move `createBasicEnvironment` as test-util
- Prevent importing integration test-utils in unit tests
This make sure that our source code doesn't include test-related implementation, and that unit tests only imports it's unit test-utils. The integration test-utils are much heftier on load, so this should help with unit tests startup slightly.
n/a

Move createBasicEnvironment as test-util

---

.changeset/red-turtles-drum.md
packages/astro/src/core/module-loader/loader.ts
packages/astro/src/core/render/dev/vite.ts
packages/astro/test/units/dev/styles.test.js

Fix https://github.com/withastro/astro/issues/7529
Used the not-so-performant technique initially used in the first commit of https://github.com/withastro/astro/pull/7381 to fix the issue for now.
The issue seems to be that UnoCSS is invalidating the Astro files at https://github.com/unocss/unocss/blob/757b7f18b060f32387689545c878aea1e63203b4/packages/vite/src/modes/global/dev.ts#L59. This breaks our expectations where they are already loaded and exist as `ssrTransformResult`. The invalidation clears out `ssrTransformResult`, causing the issue.
A fix I intially thought is to force `loader.import()` on all modules while we're traversing the graph to counteract UnoCSS, but that feels more non-performant than the initial PR idea, so I went with the initial PR idea instead.
Existing tests …

Fix style crawling logic for CSS HMR

---

packages/integrations/mdx/src/README.md

Fixed a typo error in the Readme file. Fixed the typo from "acheive" to "achieve".

Fix MDX README typo

---

packages/astro/src/core/app/types.ts
packages/astro/src/core/build/generate.ts

This is the first step towards a unified way to "render a page or an endpoint".
In this PR, I refactored the generation of the page using the `SSRManifest`. The manifest has already ALL the information needed to render a page.
In this PR we create a `SSRManifest` using the settings, the configuration and build internals. 
N/A

refactor: use only manifest to compute information

---

.changeset/many-nails-arrive.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/endpoint/dev/index.ts
packages/astro/src/core/render/context.ts
packages/astro/src/core/render/core.ts
packages/astro/src/core/render/dev/index.ts
packages/astro/src/core/render/result.ts
packages/astro/src/runtime/server/hydration.ts
packages/astro/src/runtime/server/jsx.ts
packages/astro/src/runtime/server/render/astro/instance.ts
packages/astro/src/runtime/server/render/component.ts
packages/astro/src/runtime/server/render/head.ts
packages/astro/src/runtime/server/render/page.ts
packages/astro/src/runtime/server/render/types.ts
packages/astro/src/runtime/server/scripts.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/integrations/markdoc/components/TreeNode.ts

- Mainly removing props that are unused
- Also make `SSRResult._metadata` only contain ephemeral and mutable state
I made isolated commits that can be reviewed individually. But the whole changes aren't too big either. 

Refactor `SSRResult` and `RenderContext`

---

packages/astro/src/core/app/index.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/endpoint/dev/index.ts
packages/astro/src/core/endpoint/index.ts
packages/astro/src/vite-plugin-astro-server/route.ts

Small refactor to avoid an extra `logging` parameter, because we can use `env.logging` instead.
n/a

Simpify passing endpoint logging option

---

packages/integrations/markdoc/README.md

- Fixed code snippet in markdoc README due to the changes in #7468

Fix code snippet in markdoc README

---

.changeset/sharp-ducks-walk.md
packages/integrations/markdoc/README.md
packages/integrations/markdoc/src/load-config.ts

- Add note on named exports to README
- Add link to docs from error hint

Fix: Markdoc v0.4.0 docs

---

.changeset/witty-pandas-behave.md
packages/integrations/markdoc/src/content-entry-type.ts
packages/integrations/markdoc/test/fixtures/render-with-components/markdoc.config.ts
packages/integrations/markdoc/test/fixtures/render-with-components/src/content/blog/with-components.mdoc

- Resolves #7595
- Add tagname with hyphen to test suite

Fix: Hyphens breaking Markdoc tags

---

.changeset/funny-tomatoes-guess.md
packages/astro/src/content/vite-plugin-content-virtual-mod.ts

fix https://github.com/withastro/astro/issues/7154
Fix the glob to include nested folders/files with `_`
cc @Princesseuh my bad 😅 
Added an integration test for this.
n/a

Ignore content .json files prefixed with underscores

---

.changeset/ten-buckets-rush.md
packages/integrations/prefetch/README.md

Now that we're using `expressive-code` under the hood in Astro Docs, the filename as paragraph syntax isn't supported anymore, which means we have to resort to the comment syntax instead.

Update prefetch README filename styling

---

benchmark/bench/_util.js
benchmark/bench/cli-startup.js
benchmark/bench/render.js
benchmark/index.js
packages/astro/src/cli/index.ts

- Support `pnpm astro-benchmark cli-startup` in root
- Support `!bench cli-startup` in PR comments (once merged)
Example output:
```
Making project: render-default
Finished making project: render-default
Benchmarking `astro --help`...
Done
Benchmarking `astro info`...
Done
Result preview:
==========
| Command      | Avg (ms) | Stdev (ms) | Max (ms) |
| :----------- | -------: | ---------: | -------: |
| astro --help |   434.98 |      21.17 |   492.63 |
| astro info   |   468.74 |      28.54 |   527.03 |
==========
```
Ran `pnpm astro-benchmark cli-startup` locally. I did not test if the `!bench` PR comment would work, but it _should_ following the other patterns.
n/a. The `!bench` command should be documented in `CONTRIBUTING` in general.

Add CLI startup speed benchmark

---

.changeset/rude-balloons-sniff.md
packages/astro/src/cli/add/index.ts

A while back we started adding `astro` as a peer dependency to integrations. This means it shows up when running `astro add`. For example:
```
> astro "add" "svelte"
✔ Resolving packages...
Astro will run the following command:
If you skip this step, you can always run it yourself later
╭──────────────────────────────────────────────────────╮
│ pnpm add @astrojs/svelte astro@^2.7.1 svelte@^4.0.0  │
╰──────────────────────────────────────────────────────╯
```
This PR filters out `astro` from the peer dependencies so we don’t offer to reinstall it.
Tested in a local project with `pnpm patch`.
Not required.

Filter out astro from `peerDependencies` in `astro add`

---

.changeset/tasty-beans-give.md
packages/astro/src/runtime/server/response.ts
packages/astro/test/fixtures/middleware-dev/src/middleware.js
packages/astro/test/fixtures/middleware-dev/src/pages/clone.astro
packages/astro/test/middleware.test.js

- Implements `clone()` in our response wrapper.
- We should probably investigate removing this in 3.0.
- Fixes https://github.com/withastro/astro/issues/7602
- Updated middleware test with this test case.
N/A

Fixes Response not being cloneable by middleware

---

packages/astro/src/cli/index.ts
packages/astro/src/core/config/config.ts
packages/astro/src/core/config/index.ts
packages/astro/src/core/config/merge.ts
packages/astro/src/core/config/vite-load.ts
packages/astro/src/integrations/index.ts

- Simplify config loading via nodejs and vite
- Move config merging logic to separate file
- Bug fix with telemetry report on config error
Tested manually for config loading and restarting logic. The smoke tests should also cover this.

Refactor config loading

---

packages/astro/src/@types/astro.ts

The default value should be enclosed by backticks, rather than curly braces to avoid a rendering issue in docs.
It's all about the docs

Fix `build.excludeMiddleware` default type docs

---

.github/workflows/ci.yml

Since the lint now requires a build first, refactor so we run the `build` job first before the `lint` job.
Also updates the `build` job so it doesn't run turbo build for PR from forks as they don't have access to the turbo cache. They should still have access to pnpm deps cache, so keeping it.
The CI should still pass
n/a

Update turbo cache flow

---

.changeset/happy-frogs-appear.md
.changeset/nasty-geckos-know.md
packages/integrations/cloudflare/src/index.ts
packages/integrations/netlify/README.md
packages/integrations/netlify/package.json
packages/integrations/netlify/src/integration-edge-functions.ts
packages/integrations/netlify/src/integration-functions.ts
packages/integrations/netlify/src/integration-static.ts
packages/integrations/netlify/src/shared.ts
packages/integrations/netlify/test/functions/fixtures/prerender/src/pages/index.astro
packages/integrations/netlify/test/functions/fixtures/split-support/src/pages/blog.astro
packages/integrations/netlify/test/functions/fixtures/split-support/src/pages/index.astro
packages/integrations/netlify/test/functions/redirects.test.js
packages/integrations/netlify/test/functions/redirects.test.js.snap
packages/integrations/netlify/test/functions/split-support.test.js
packages/integrations/netlify/test/functions/split-support.test.js.snap
packages/integrations/netlify/test/functions/test-utils.js
packages/integrations/netlify/test/setup.js
packages/underscore-redirects/src/astro.ts
packages/underscore-redirects/test/astro.test.js
pnpm-lock.yaml

This PR adds `build.split` support for the `@astrojs/netlify` adapter.  
List of changes:
- changed `@astrojs/underscore-redirects` payload to accept a `Map` instead of an array of routes and a dynamic target. This logically makes more sense compared to the previous logic, because a route is mapped to a dynamic target (even though we could have duplicates);
- the changes to `@astrojs/underscore-redirects` allowed me to create redirects correctly using `RouteData` -> `URL` entry point
- I added snapshot testing for netlify redirects, so we can **actually see** the emitted file in PRs and make sure it's correct
Added new test cases
Updated the `README.md` and added a changeset. It's a copy-paste from the Vercel one.

feat(@astrojs/netlify): add `build.split` support

---

packages/astro/src/cli/build/index.ts
packages/astro/src/cli/check/index.ts
packages/astro/src/cli/dev/index.ts
packages/astro/src/cli/index.ts
packages/astro/src/cli/load-settings.ts
packages/astro/src/cli/preview/index.ts
packages/astro/src/cli/sync/index.ts

- Move the `dev`, `build`, `preview`, `sync` commands to their own folder
- Move loading `settings` to each command itself
---
This currently creates more code, but only a stop point for now to make further refactoring easier. Each command can now start the actual work with only the `flags` and `logging` params.
Tested manually. This should also improve startup perf a little. Will run the benchmark

Move all CLI commands to their subfolders

---

.changeset/fluffy-timers-remain.md
.changeset/tasty-bags-accept.md

The release PR changelog currently have weird symbols so this removes them 😄 
n/a
n/a

Remove weird changeset symbols

---

packages/astro/src/@types/astro.ts
packages/astro/src/cli/add/index.ts
packages/astro/src/cli/dev/index.ts
packages/astro/src/cli/load-settings.ts
packages/astro/src/core/config/config.ts
packages/astro/src/core/config/index.ts
packages/astro/test/units/config/config-validate.test.js

**Note: This merges into the `js-api` branch while I work on these step-by-step**
- Add new `resolveConfig` API. Does the same thing as `openConfig`, but duplicating to easier migrate step-by-step.
- Add `AstroInlineConfig` type. Ideally this will be the config type the `dev` / `build` JS API will accept. ("inline" borrowed from Vite)
- Refactor `resolveConfigPath` to not accept the raw `flags`. Easier to divide between JS and CLI code.

Add new internal `resolveConfig` API

---

packages/integrations/image/README.md

Fixes a broken URL in `@astrojs/image` integration readme
No tests, only docs.
Docs change.

[docs] fix link in image integration README

---

packages/integrations/sitemap/README.md

While this README doesn't distinguish between SSR mode and static mode (and SSR mode was recently made available for the sitemaps integration), there is one important difference: Dynamic routes that are server-rendered can't be used to create sitemap entries. As far as I can tell, anyway, based on experimentation and on [this comment](https://github.com/withastro/astro/pull/6534#issuecomment-1467906589)
This note makes that clear.
Adds a note clarifying that dynamic routes can only generate sitemaps when their pages are statically generated.
- set up a default install
- enabled SSR mode
- tried two versions of dynamic routes:
- one from [this example](https://docs.astro.build/en/core-concepts/routing/#modifying-the-slug-example-for-ssr)
- another that renders pages from a content …

Clarify SSR limitations of sitemaps of dynamic routes

---

packages/astro/src/core/app/index.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/render/dev/environment.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/request.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/units/routing/route-matching.test.js
packages/astro/test/units/vite-plugin-astro-server/request.test.js

There isn't a great change in logic. In this PR we create an `SSRManifest` in dev mode, which we pass down until the `handleRoute`.
This should "normalize" the code across dev, SSG and SSR. I also changed a bit the `App` class to prepare some methods that will be needed in the near future.
N/A

refactor: use SSR manifest in dev

---

.changeset/pretty-hats-smash.md
packages/integrations/vercel/src/edge/adapter.ts
packages/integrations/vercel/src/serverless/adapter.ts

- Fix #7654 regression
- Excludes `@vercel/nft` from the bundle automatically
Tested manually. It works!

Vercel: exclude `@vercel/nft` automatically

---

packages/astro/package.json
packages/astro/test/astro-get-static-paths.test.js
packages/integrations/cloudflare/test/basics.test.js
packages/integrations/cloudflare/test/cf.test.js
packages/integrations/cloudflare/test/test-utils.js
packages/integrations/cloudflare/test/with-solid-js.test.js

- Update cloudflare tests to prevent test timeout. Move CLI startup and teardown to before/after hook to spread out the timeout limit
- Handles `"renders the solid component"` and `"Load cf and caches API"` fails
- Set integration test timeout to 30s. Some builds take longer than expected.
- Handles `"Code component inside static build"` and `"Static build: dir takes the URL path to the output directory"` fails
- Retry getStaticPath test twice
- Handles `"only calls getStaticPaths once"` fail
Existing tests should still pass.

Handle flaky tests

---

.changeset/light-jars-cheat.md
.changeset/spicy-pugs-wonder.md
packages/astro/src/vite-plugin-env/index.ts
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/test/basics.test.js

Follow up from https://github.com/withastro/astro/pull/7651#discussion_r1263856991
Fix https://github.com/withastro/astro/issues/7137
Fix cloudflare runtime env var handling. We're using Vite's `ssr.target = 'webworker'` config, and it's converting our `process.env.RUNTIME_VAR` to `({}).RUNTIME_VAR`, causing it to not work.
This also tweaked Astro's env handling for the `PRERENDER` test, as it's indirectly passing with the bug above. Since it was passed a boolean value, I had to update `vite-plugin-env` to handle it too.
Un-skipped a test that revealed this bug.
n/a. bug fix.

Fix cloudflare runtime env var handling

---

.changeset/large-meals-joke.md
.changeset/sweet-bats-clap.md
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/src/server.directory.ts
packages/integrations/cloudflare/src/util.ts
packages/integrations/cloudflare/test/directory-split.test.js
packages/integrations/cloudflare/test/fixtures/split/src/pages/trpc/[trpc].ts

- fixed an bug, where `ts` endpoint files are not renamed to .js after bundle step
- updated test suite
- manually

fix(@astrojs/cloudflare): SSR split file renaming misses ts endpoints

---

packages/astro/src/core/app/index.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/render/core.ts
packages/astro/src/core/render/dev/index.ts
packages/astro/src/core/render/index.ts
packages/astro/test/units/render/head.test.js
packages/astro/test/units/render/jsx.test.js

Refactor.
I moved the rendering of the page inside a unique function. I called `tryRenderPage` to make it more clear that that's an operation that could throw an error. In fact, there's a place where we handle the thrown error.
I updated the unit tests. Current CI should pass
N/A

refactor: move page rendering in one single function

---

.github/labeler.yml
.github/workflows/check-merge.yml
.github/workflows/issue-labeled.yml
.github/workflows/issue-needs-repro.yml
.github/workflows/issue-opened.yml

- Updates GitHub Action labels to match cleaned up labels in this repro
- Adds some workflows inspired by [Vite](https://github.com/vitejs/vite/tree/main/.github/workflows) to automatically add `needs: triage` label and remove when issue has been triaged.
- Adds a workflow to close `needs: repro` issues after 3 days of inactivity
We'll do it live
N/A

Update Action labels

---

.github/workflows/issue-labeled.yml
.github/workflows/issue-needs-repro.yml
.github/workflows/issue-opened.yml

- Removes `:` from `needs` labels because GitHub's YAML parser treats them as an object, even within a string. 😭
```
YAML: 1
Nate: 0
```
Nope
Nah

CI: handle `needs` labels properly

---

.changeset/stupid-trains-move.md
packages/astro/src/core/render/route-cache.ts
packages/astro/src/core/routing/params.ts
packages/astro/test/astro-get-static-paths.test.js
packages/astro/test/fixtures/astro-get-static-paths/src/pages/pizza/[cheese]-[topping].astro

- Our `getStaticPaths` implementation includes a keyed object
- When we generate the `RouteManifest`, the generated `route.pattern` doesn't _always_ match the generated routes due to hyphenization.
- Rather than updating the `route.pattern` logic to account for hyphens, the correct fix is to update our `getStaticPaths.keyed` implementation to only store the final, generated pathname of the route. This removes any mismatched `keys <=> data` relationship. Hyphens are no longer relevant!
- This is way more common than it might seem for anyone that has `/route/[a]-[b]`
- Resolved #7265
Test added, existing tests should pass
Bug fix only

Fix routing behavior when getStaticPaths params include hyphens

---

.changeset/great-days-judge.md
packages/integrations/netlify/README.md

- Follow-up PR to #7698
- Adds docs and changeset for #7632, which we removed to avoid releasing before docs were polished.
Would love @ematipico to make sure none of what I wrote is lies 😀 
N/A — docs only.

Add changeset & docs for next `@astrojs/netlify` release

---

.changeset/eleven-eyes-jog.md
packages/astro/src/core/config/schema.ts

Fix https://github.com/withastro/astro/issues/7322
Extend `redirects` config validation to pass configs like:
```js
redirects: {
'/': {
status: 302,
destination: '/home',
},
},
```
Tested manually for now. I'm planning to add config validation tests in the `js-api` branch and PR so we catch this in the future.
n/a. bug fix.

Fix redirects map object-form value validation

---

.changeset/loud-hairs-tell.md
packages/astro/src/core/config/config.ts
packages/astro/src/core/config/schema.ts

Fix passing absolute paths to `root`, `srcDir`, `publicDir`, `outDir`, `cacheDir`, `build.client`, and `build.server` on Windows. We currently have code like this:
https://github.com/withastro/astro/blob/b3b9fc52b33ae8d9bd3f205758051814a1ed4add/packages/astro/src/core/config/schema.ts#L251
And they fail on Windows because `val` looks like `C:\\User\\bob`. The `C:` looks like a protocol when passed to `new URL` and that creates an invalid final URL. Switching to `path.resolve` fixes this for now.
Tested in https://github.com/withastro/astro/pull/7682 where I passed the absolute `root` path in tests, and it failed. The [fa32ff0](https://github.com/withastro/astro/pull/7682/commits/fa32ff029c68272f57b4299501f6f083152daed2) commit there fixes it, which I ported it to here to `main` first. …

Fix absolute path handling for config validation in windows

---

.changeset/fuzzy-toes-float.md
packages/integrations/sitemap/src/index.ts
packages/integrations/sitemap/test/fixtures/static/src/pages/de/404.astro
packages/integrations/sitemap/test/staticPaths.test.js

- There was a regression introduced in https://github.com/withastro/astro/pull/7655
- This PR fixes the regression, so that nested `[...slug]/404` and `[...slug]/500` pages are excluded as well
- Changeset added
Test updated to include nested 404 page

Ensure sitemap excludes nested error pages

---

packages/astro/src/@types/astro.ts

Update the description/link for the experimental View Transitions support to go to the newly-renamed page.
no tests
Only docs! The change has already been made locally in docs as a quick fix, so there is no urgent need to run ci for this correction. This should match what's already in docs, and will ensure the change in the docs repo is not written over.

[docs] update to view transitions in config ref

---

.changeset/five-phones-notice.md
packages/astro/src/vite-plugin-markdown/index.ts

Every regex that tries to match a substring with .* or .+ is guaranteed to be wrong.  In this case, it was giving incorrect matches straddling multiple quoted attributes:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Fixes #7741.
Tested with the test case in #7741.
This is a pure bugfix that doesn’t need documentation.

Fix parsing image assets from a Markdown line along with other markup

---

.changeset/sixty-peas-join.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/view-transitions.test.js

- When navigation from a page without VT enabled we want a full page refresh.
- Change is to do `location.reload()` so that a refresh is fired.
- Fixes https://github.com/withastro/astro/issues/7739
- New E2E case added
N/A, bug fix

Handle back navigation from page without VT

---

.changeset/poor-cameras-tell.md
packages/astro/components/viewtransitions.css

- Adds `prefers-reduced-motion` that eliminates the animations.
- This is a "hammer" and maybe goes further than it should. But I'd rather go to extreme measures and then pull back later.
N/A
N/A

Prevent animations with prefers-reduced-motion

---

.changeset/cool-deers-dream.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/public/two.css
packages/astro/e2e/fixtures/view-transitions/src/components/Layout.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/two.astro
packages/astro/e2e/view-transitions.test.js

- Waits on stylesheets to load before swapping the DOM, to prevent FOUC
- Fixes https://github.com/withastro/astro/issues/7751
N/A, bug fix

Prevent FOUC with production links in ViewTransitions

---

.changeset/hot-buckets-tie.md
packages/astro/src/assets/image-endpoint.ts
packages/astro/src/assets/internal.ts
packages/astro/src/assets/services/service.ts
packages/astro/src/assets/utils/index.ts
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/src/cli/load-settings.ts
packages/astro/src/config/index.ts
packages/astro/src/core/config/settings.ts
packages/astro/src/core/dev/restart.ts
packages/astro/test/test-utils.js
packages/astro/test/units/config/format.test.js
packages/astro/test/units/dev/collections-mixed-content-errors.test.js
packages/astro/test/units/dev/restart.test.js

- The types for `SharedImageService` were wrong and assumed every hook to be sync only, but we do support all of them being optionally async
- This led me to discover some spots where we in fact, did not support them being async
- Exported all the utils from `assets/utils`, they're undocumented, not an official thing, can break and change etc, but some users like to use them (especially imageMetadata, which we'll be able to make an official export once `image-size` is 2.0 if someone needs it)
- I realized that I completely misunderstood a part of `@astrojs/image`, and that we could completely remove the endpoint used only for dev. Now, the same endpoint is used in SSR and dev, making it much easier for users to try their custom endpoints in dev
Tests should still pass!
N/A

Misc improvements for `astro:assets`

---

.github/workflows/main.yml

Fixes the Discord emoji code for the Astro Pride emoji which we recently updated, causing its unique ID to change, in the congrats bot workflow.
N/A
N/A

Fix Astro pride emoji in congrats message

---

packages/astro/test/ssr-prerender-get-static-paths.test.js

Apply the same retry logic from 
https://github.com/withastro/astro/blob/83e9ba36134de357e7bfccf6860690793b9eb749/packages/astro/test/astro-get-static-paths.test.js#L57-L60
but for **prerender** getStaticPaths
Should pass.
n/a.

Fix prerender getStaticPaths flaky test

---

.changeset/dry-cycles-appear.md
packages/astro/src/runtime/server/render/common.ts

Fix https://github.com/withastro/astro/issues/7775
My bad. My PR (https://github.com/withastro/astro/pull/7730) accidentally reverted the fix from https://github.com/withastro/astro/pull/6070. I tried making a test, but I can't reproduce it. Might be a difference between wrangler and cloudflare prod?
Not sure how to test this. I can't reproduce it with wrangler.
n/a. bug fix.

Fix rendering TextEncoder encoding error regression

---

.changeset/sharp-seas-smile.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/two.astro
packages/astro/e2e/view-transitions.test.js

- DOMParser creates scripts that are non executable, event after inserting into the page.
- This makes it so that scripts are always executed. If they have already run we reinsert them. That means for inline classic scripts those will re-run. Module scripts will not.
- This approach was chosen mostly because it's the last amount of code. It also aligns with what Swup does it.
- Adds the `astro:load` even that you can listen to if you need to rerun something on page navigation.
- Fixes https://github.com/withastro/astro/issues/7765
- Test added to verify the `astro:load` event fire on forward navigation.
- Test added to verify `astro:load` fires on direct page navigation (MPA).
- https://github.com/withastro/docs/pull/3810

Execute scripts on page navigation (view transitions)

---

packages/integrations/markdoc/README.md

Fixes wonky rendering in docs because of the `:::caution` syntax. 
Replaces with a GitHub caution. Also moves the caution below so it's not between code sample and its explanation.
No tests
Only Docs!

[docs] Markdoc README syntax fixes

---

packages/astro/src/cli/dev/index.ts
packages/astro/src/core/config/config.ts
packages/astro/src/core/config/index.ts
packages/astro/src/core/config/settings.ts
packages/astro/src/core/dev/container.ts
packages/astro/src/core/dev/dev.ts
packages/astro/src/core/dev/index.ts
packages/astro/src/core/dev/restart.ts
packages/astro/test/test-utils.js
packages/astro/test/units/config/format.test.js
packages/astro/test/units/content-collections/frontmatter.test.js
packages/astro/test/units/dev/base.test.js
packages/astro/test/units/dev/collections-renderentry.test.js
packages/astro/test/units/dev/dev.test.js
packages/astro/test/units/dev/head-injection.test.js
packages/astro/test/units/dev/hydration.test.js
packages/astro/test/units/dev/restart.test.js
packages/astro/test/units/render/components.test.js
packages/astro/test/units/routing/manifest.test.js
packages/astro/test/units/routing/route-matching.test.js
packages/astro/test/units/shiki/shiki.test.js
packages/astro/test/units/test-utils.js
packages/astro/test/units/vite-plugin-astro-server/request.test.js

**Note: this merges into the js-api branch**
Refactor the `dev` command CLI flow
1. Remove `openConfig` usage, switch to `resolveConfig` instead
2. Make a somewhat cleaner `dev()` JS API (now accepts `AstroInlineConfig`)
3. Update tests with new signature.
Next will be making the same changes as no2 for all other commands, which should be easier than `dev`.
Existing tests should pass. I also tested the dev command locally, especially restarts when editing `astro.config.mjs`.
n/a. internal change for now. will document more when we expose a JS API.

Refactor dev CLI flow

---

.changeset/ninety-kids-fail.md
packages/integrations/netlify/src/integration-functions.ts
packages/integrations/netlify/test/functions/fixtures/redirects/src/pages/index.astro
packages/integrations/netlify/test/functions/fixtures/redirects/src/pages/nope.astro
packages/integrations/netlify/test/functions/fixtures/redirects/src/pages/team/articles/[...slug].astro
packages/integrations/netlify/test/functions/redirects.test.js

- In Netlify, do not build .html files because it prioritizes those
- This only is an issue with hybrid mode
- Fixes: https://github.com/withastro/astro/issues/7731
N/A, bug fix

Prevent building .html files in hybrid mode

---

.changeset/three-adults-exist.md
packages/astro/tsconfigs/base.json
packages/astro/tsconfigs/strict.json

TypeScript has this annoying behaviour where if you use an unknown compiler option, it'll.. completely refuse to do anything. I feel like they could've just added a warning instead, but whatever. This PR adds cool new options like `verbatimModuleSyntax` and updates it to use `moduleResolution: 'bundler'`, unlocking supports for the `exports` field. It's neat
N/A, we don't document this

Update `tsconfig.json` presets for TS 5.0

---

packages/integrations/markdoc/README.md

This takes yet another stab at making an aside using GitHub notation that imports properly into Docs.
This tested my patience.
Only docs!

[docs] Markdoc README problematic aside notation

---

.changeset/calm-balloons-study.md
packages/astro/src/assets/services/squoosh.ts
packages/astro/src/assets/types.ts
packages/astro/src/assets/utils/emitAsset.ts
packages/astro/src/assets/utils/metadata.ts
packages/astro/test/fixtures/core-image-ssr/src/pages/api.ts

Refactor `imageMetadata` to not do file stuff by itself, so it's more portable and safer to use on all platforms (and eventually, in `image-size 2.0` will even be usable in SSR)
FIx https://github.com/withastro/astro/issues/7814
Tests should still pass! We don't test this particular path at the moment, but https://github.com/withastro/astro/pull/7734 should cover this
N/A

fix: squoosh not working on Windows in certain situations

---

.changeset/mighty-dancers-lay.md
packages/astro/src/runtime/server/endpoint.ts

As per the title, this PR removes the code that was handling the old API syntax - which I don't know because I don't have enough knowledge 😆 
I run the tests locally, and it seems we don't have old syntax, so the current CI should pass.
question for @withastro/maintainers-docs: do we have pages that still have the old syntax?

feat: remove support for old API routes syntax

---

packages/astro/src/cli/add/index.ts

- Fixed typo from ` alpine ` -> `alpinejs `. Which is real pkg name

fix: typo alpine -> alpinejs

---

.changeset/neat-balloons-doubt.md
packages/astro/src/assets/internal.ts
packages/astro/src/cli/load-settings.ts
packages/astro/src/config/index.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/config/settings.ts
packages/astro/src/core/dev/container.ts
packages/astro/src/core/dev/restart.ts
packages/astro/test/test-utils.js
packages/astro/test/units/config/format.test.js
packages/astro/test/units/dev/collections-mixed-content-errors.test.js
packages/astro/test/units/dev/restart.test.js

What the title says. We'd only check for `experimental.assets` before running the integration's config setup hooks, so we'd miss it if an integration would enable it for the user (such as Starlight
Tested manually, we'll be removing this in 3.0 anyway, so
N/A

fix(assets): Fix endpoint not being injected when an integration would enable `experimental.assets`

---

.changeset/moody-beers-leave.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/one.astro
packages/astro/e2e/view-transitions.test.js

- Fixes https://github.com/withastro/astro/issues/7803
- Prevent hash change events from triggering VT navigation
N/A, bug fix

Prevent navigation on hash change

---

packages/astro/src/@types/astro.ts
packages/astro/src/cli/build/index.ts
packages/astro/src/cli/check/index.ts
packages/astro/src/cli/preview/index.ts
packages/astro/src/cli/sync/index.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/preview/index.ts
packages/astro/src/core/sync/index.ts
packages/astro/test/test-utils.js
packages/astro/test/units/dev/collections-mixed-content-errors.test.js

**Note: This PR merges into the js-api branch**
- Make `build`/`preview`/`sync` API accept AstroInlineConfig.
- Mostly moving code around without logic change.
The JS API is almost done! This finishes the APIs above besides `check` and `add` as those will be refactored in 3.0. Two more things to clean up in later PRs:
1. Initial config loading error handling can be improved.
2. `logging` can be tucked into `settings` so the user don't have to pass that in.
Existing tests should pass. Also tested locally for the commands to all work.

Make build/preview/sync API accept AstroInlineConfig

---

.changeset/yellow-olives-sing.md
packages/astro/src/@types/astro.ts
packages/astro/src/content/runtime.ts
packages/astro/src/core/render/result.ts
packages/astro/src/runtime/server/index.ts
packages/astro/src/runtime/server/render/astro/render.ts
packages/astro/src/runtime/server/render/index.ts
packages/astro/src/runtime/server/render/tags.ts

- https://github.com/withastro/astro/commit/80e3d4d3d0f7719d8eae5435bba3805503057511#diff-3b2bb624348e4447bb08d85298dfd18bbd849514839f175cf0ccbc1de04c2a33 introduced a regression where head content was not propagated.
- It turns out not to be a small thing, but unique style/script rendering was working by mistake perhaps. 
- Uses string keys during rendering to tell if we've rendered a script/style/link or not. And only render when we have.
- packages/integrations/mdx/test/css-head-mdx.test.js was failing but now should pass.
N/A, bug fix

Track added links/styles/scripts to prevent duplicates

---

.changeset/odd-books-live.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/logger/console.ts
packages/astro/src/core/logger/core.ts
packages/astro/src/core/logger/node.ts
packages/astro/src/integrations/index.ts
packages/astro/test/static-build.test.js

I created two classes:
- `Logger`, basic class. The objective of this class is to be used internally in our codebase. Ideally, we will pass around an instance of this class instead of passing `logging`. I plan to make this change gradually in the future.
- `AstroIntegrationLogger`, similar to `Logger`, this class has the `label` stored inside of it. The main idea is that integrations should not know anything about labels.
If an integration needs to do some logging with a different label - which I assume it's rare - they can use the `fork` function, which returns a new logger which has the same logging options. 
Current tests should pass.

feat: pass logger to integrations

---

.changeset/fair-emus-divide.md
.changeset/tricky-candles-suffer.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/build/plugins/plugin-pages.ts
packages/astro/src/core/build/plugins/plugin-ssr.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/integrations/index.ts
packages/integrations/netlify/src/integration-functions.ts
packages/integrations/netlify/src/netlify-functions.ts
packages/integrations/netlify/test/functions/edge-middleware.test.js
packages/integrations/netlify/test/functions/split-support.test.js
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/test/fixtures/functionPerRoute/astro.config.mjs
packages/integrations/vercel/test/fixtures/functionPerRoute/package.json
packages/integrations/vercel/test/fixtures/functionPerRoute/src/pages/one.astro
packages/integrations/vercel/test/fixtures/functionPerRoute/src/pages/two.astro
packages/integrations/vercel/test/fixtures/middleware-with-edge-file/astro.config.mjs
packages/integrations/vercel/test/fixtures/middleware-without-edge-file/astro.config.mjs
packages/integrations/vercel/test/split.test.js
pnpm-lock.yaml

This PR deprecates `build.split` and `build.excludeMiddleware`.
After an internal discussion, we realised that these two config values should not live inside Astro, because they are only usable only with an adapter that can understand it
Because of that, we introduced the concept of `adapterFeatures`. These features are toggles that signal Astro to change the output of the build, and then the adapter needs to do something with those. 
I updated the current test to use the new configuration. The tests should pass.

feat: adapter features, deprecate astro configs

---

.changeset/dirty-lies-cover.md
examples/deno/astro.config.mjs
packages/astro/src/@types/astro.ts
packages/astro/src/assets/generate.ts
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/src/integrations/astroFeaturesValidation.ts
packages/astro/src/integrations/index.ts
packages/astro/test/featuresSupport.test.js
packages/astro/test/test-adapter.js
packages/astro/test/units/integrations/api.test.js
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/test/fixtures/basics/astro.config.mjs
packages/integrations/deno/src/index.ts
packages/integrations/deno/test/fixtures/basics/astro.config.mjs
packages/integrations/deno/test/fixtures/dynimport/astro.config.mjs
packages/integrations/netlify/src/integration-edge-functions.ts
packages/integrations/netlify/src/integration-functions.ts
packages/integrations/node/src/index.ts
packages/integrations/vercel/src/edge/adapter.ts
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/test/no-output.test.js

Introducing **Astro features**. Astro features are features that astro has out the box, and sometimes users can opt-in. 
Few examples:
- `staticOutput` if a user uses a specific adapter, the adapter needs to be able to serve those static assets. An example is Cloudflare, which **doesn't support it**.
- `assets`: not supported by those adapters that are incompatible with node
___
This PR adds a new API that adapters can use when registering one. It's called `supportedFeatures`, and it's a new way to tell Astro if and when an adapter is able to support certain features that are enabled via configuration. 
The adapter can also tell Astro the kind of support:
- stable
- experimental
- unsupported
- deprecated
For now, this new API/object is not mandatory, but it will be in Astro 4.0.
The PR …

feat: astro features

---

.changeset/fair-emus-divide.md
.changeset/tricky-candles-suffer.md

Reworks the CHANGELOG for recent changes to the adapter/build config API. Now looks like this:
The `build.split` and `build.excludeMiddleware` configuration options are deprecated and have been replaced by options in the adapter config.
If your config includes the `build.excludeMiddleware` option, replace it with `edgeMiddleware` in your adapter options:
```diff
import {defineConfig} from "astro/config";
import netlify from "@astrojs/netlify/functions";
build: {
-        excludeMiddleware: true
},
adapter: netlify({
+        edgeMiddleware: true
}),
});
```
If your config includes the `build.split` option, replace it with `functionPerRoute` in your adapter options:
```diff
import {defineConfig} from "astro/config";
import netlify from …
```

Tweak adapter config CHANGELOG

---

.changeset/famous-queens-itch.md
.changeset/rude-ears-play.md
.changeset/unlucky-hotels-try.md
packages/astro/src/core/create-vite.ts
packages/integrations/mdx/package.json
packages/integrations/mdx/src/index.ts

... instead of doing it in Astro core.
Existing tests should pass. However, `next` might need to merge up `main` changes for the recent fixes to the MDX fails.
n/a. This change should not be visible as long as they upgrade Astro core and MDX integration to latest

Move MDX plugin re-ordering hack to MDX integration

---

packages/astro/e2e/errors.test.js
packages/astro/src/@types/astro.ts
packages/astro/src/cli/add/index.ts
packages/astro/src/cli/build/index.ts
packages/astro/src/cli/check/index.ts
packages/astro/src/cli/dev/index.ts
packages/astro/src/cli/flags.ts
packages/astro/src/cli/index.ts
packages/astro/src/cli/preview/index.ts
packages/astro/src/cli/sync/index.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/config/config.ts
packages/astro/src/core/config/index.ts
packages/astro/src/core/config/logging.ts
packages/astro/src/core/dev/dev.ts
packages/astro/src/core/dev/restart.ts
packages/astro/src/core/preview/index.ts
packages/astro/src/core/sync/index.ts
packages/astro/test/astro-sync.test.js
packages/astro/test/client-address.test.js
packages/astro/test/dev-routing.test.js
packages/astro/test/dynamic-endpoint-collision.test.js
packages/astro/test/error-bad-js.test.js
packages/astro/test/error-non-error.test.js
packages/astro/test/react-component.test.js
packages/astro/test/test-utils.js
packages/astro/test/units/dev/collections-mixed-content-errors.test.js
packages/astro/test/units/dev/hydration.test.js
packages/astro/test/units/dev/restart.test.js
packages/astro/test/units/render/components.test.js

**NOTE: this merges into the js-api branch**
- Changes `dev({ root: '...' }, { logging: { ... } })` to `dev({ root: '...', logLevel: '...' })`
- Similar changes for `build`, `preview`, and `sync`
- However, you can still do `dev({ logging: { ... } })`. I added `logging` as an internal option because some tests passes a custom `logging` to collect logs.
NOTE: After this is merged, I think we can merge `js-api` into `main`, then decide if we want to expose the JS API as a feature since the changes so far are mostly refactors.
Existing tests should pass. Also tested the commands manually.
n/a. Internal change as JS API is not exposed yet.

Move `logging` option to `logLevel` inline config option

---

.changeset/twenty-cheetahs-deny.md
packages/astro/src/core/cookies/cookies.ts
packages/astro/test/units/cookies/delete.test.js
packages/astro/test/units/cookies/get.test.js

- Astro.cookies.get(key) now returns `undefined` if the cookie isn't present.
- This is a breaking change, as previously you needed to use `has()` to check for existence.
- Test updated
- TBD

Make Astro.cookies.get(key) return undefined

---

packages/astro/package.json
packages/integrations/markdoc/package.json
packages/integrations/mdx/package.json
packages/integrations/vercel/package.json
pnpm-lock.yaml

Our release action is failing because it can't resolve the packages. Instead of using packages from `npm`, this PR attempts to fix it by using the `workspace:` protocol.
> I don't have enough background to know why we don't use the workspace package, so please if you know, tell me. When I used pnpm workspaces in the past, I used to use the `workspace:` protocol for **internal** dependencies.
Merge it and see if it works. Unfortunately the `release.yml` doesn't can't be triggered.

chore: use workspace packages 

---

.changeset/new-ants-speak.md
packages/astro/src/runtime/server/render/component.ts
packages/astro/test/streaming.test.js

fix https://github.com/withastro/astro/issues/7886
Instead of awaiting the entire Astro component before rendering, which blocks streaming, don't await it. Instead keep the chunks in a buffer and await on `render()` instead.
Edited a test that I edited before in #7782 thinking it was a mistake. It wasn't!
n/a. bug fix.

Fix streaming Astro components

---

examples/ssr/src/pages/cart.astro
packages/astro/test/fixtures/astro-cookies/src/pages/early-return.astro
packages/astro/test/fixtures/astro-cookies/src/pages/get-json.astro

`AstroCookies.get` can return `undefined` now.
The CI should pass

fix: update examples to use the new API of cookies 

---

.github/workflows/cleanup-cache.yml

Copied from https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
This will automatically cleanup the cache originating from a PR when the PR is closed or merged.
There doesn't seem to be a way to set the cache retention days. It's hardcoded to 7 days. Right now our caches are full in 4 days.
None. I trust GitHub 🙈 
n/a

Setup cleanup cache workflow

---

packages/integrations/prefetch/test/custom-selectors.test.js

Failing in main as the new config setup initializes the prefetch integration twice. Set `configFile: false` to disable one of it from `astro.config.mjs`

Fix prefetch test fail

---

.changeset/four-houses-compete.md
packages/astro/package.json
packages/astro/src/@types/astro.ts
packages/astro/src/core/config/schema.ts
pnpm-lock.yaml

What the title says, the Squoosh service is still available if someone really needs it for now
Tests should still pass!
https://github.com/withastro/docs/issues/3756#issuecomment-1660190933

feat: make Sharp the default image service

---

.changeset/tidy-tips-doubt.md
packages/integrations/vercel/src/edge/adapter.ts
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/src/static/adapter.ts
packages/integrations/vercel/test/fixtures/static-assets/astro.config.mjs
packages/integrations/vercel/test/fixtures/static-assets/package.json
packages/integrations/vercel/test/fixtures/static-assets/src/pages/index.astro
packages/integrations/vercel/test/split.test.js
packages/integrations/vercel/test/static-assets.test.js
pnpm-lock.yaml

Add cache headers to assets in Vercel adapter's route config, following [Vercel's default config](https://github.com/vercel/vercel/blob/7b01a073947d73f29584e32a9129d8797702e3b6/packages/frameworks/src/frameworks.ts#L276-L280).
Check out the built `vercel.config`
https://github.com/withastro/astro/pull/7412 hasn't had a request reflected in over a month, so you create a new PR by writing code to reflect and test the request

feat: add cache headers to assets in Vercel adapter

---

.changeset/loud-candles-admire.md
.changeset/young-roses-teach.md
packages/astro/src/core/render/core.ts
packages/integrations/mdx/src/index.ts

Move `export const components` [MDX feature](https://docs.astro.build/en/guides/markdown-content/#assigning-custom-components-to-html-elements) handling from Astro core to MDX integration.
Existing Astro and MDX tests should pass.
n/a. Should be transparent when upgraded to latest. Will note in the migration guide issue as so.

Refactor MDX components exports handling

---

.changeset/witty-bikes-relate.md
packages/astro/components/ViewTransitions.astro

Fixes #7882
When the click handler navigates to a page, it now resets the current scroll position to zero.
Otherwise, the new page might be shown half way scrolled down, depending on the scroll position of the previous page. 
Manual test: Linked the fixed module into a local copy of https://stackblitz.com/edit/github-fmqrqm?file=src%2Fpages%2Fother-page.astro

Fix scroll position in view transition (#7882)

---

.changeset/heavy-walls-arrive.md
packages/astro/package.json
packages/astro/src/assets/services/noop.ts
packages/astro/src/integrations/astroFeaturesValidation.ts
packages/astro/src/integrations/index.ts

For Cloudflare, Deno, Vercel Edge and Netlify Edge, who don't support Squoosh or Sharp, we instead provide an image service that does nothing
This shouldn't affect user behaviour from `experimental.assets`, as previously well, it didn't work. Happy to document this though if @withastro/maintainers-docs feels it's necessary!

feat: add noop service and make integrations that needs it use it

---

.changeset/unlucky-ravens-type.md
packages/astro/src/core/config/schema.ts
packages/astro/test/ssr-manifest.test.js

Changes the default value of `compressHTML` to `true`.
I updated some tests to reflect the new default.

feat: change `compressHTML` default value to `true`

---

.changeset/metal-chairs-beam.md
packages/astro/src/core/dev/container.ts
packages/astro/src/core/dev/index.ts
packages/astro/src/core/dev/restart.ts
packages/astro/test/units/dev/restart.test.js

Fix https://github.com/withastro/astro/issues/7827
When restarting the server and config load fail, don't re-create the server. Re-use the existing (already running) server instead.
Tested manually. Tried adding a test, but it seems like config loading is borked. It shouldn't have based it's root on `fixtures/alias` because it always reads that fixture's astro config.
n/a. bug fix.

Fix failed server restart calling integration hooks twice

---

.changeset/clean-tools-yawn.md
.changeset/flat-toes-fold.md
packages/astro/src/core/app/index.ts
packages/astro/src/vite-plugin-astro-server/request.ts
packages/astro/test/fixtures/ssr-request/src/pages/request.astro
packages/astro/test/ssr-request.test.js
packages/internal-helpers/src/path.ts

- Closes https://github.com/withastro/astro/issues/7806
- Duplicate slashes must be handled correctly to improve SEO experience
- Updates `dev` handling
- Updates `app` handling (meaning this will automatically roll out for all adapters)
- Properly ignores `scheme://`
Tests added

Fix duplicate slash handling

---

.changeset/metal-owls-juggle.md
packages/astro/src/runtime/server/index.ts

- Exports `createTransitionScope` from the runtime. This is used if you don't provide a `transition:animate` or `transition:name` on the element.
- Just tested locally, hot fix noticed in the demo when you remove `transition:name`.
N/A, bug fix

Export createTransitionScope from the runtime

---

packages/integrations/node/test/bad-urls.test.js
packages/integrations/node/test/fixtures/api-route/src/pages/binary.ts
packages/integrations/node/test/fixtures/api-route/src/pages/recipes.js
packages/integrations/node/test/fixtures/headers/src/pages/endpoints/astro-cookies-multi.ts
packages/integrations/node/test/fixtures/headers/src/pages/endpoints/astro-cookies-single.ts
packages/integrations/node/test/fixtures/headers/src/pages/endpoints/astro-response-cookie-multi.ts
packages/integrations/node/test/fixtures/headers/src/pages/endpoints/astro-response-cookie-single.ts
packages/integrations/node/test/fixtures/headers/src/pages/endpoints/kitchen-sink.ts
packages/integrations/node/test/fixtures/headers/src/pages/endpoints/response-cookies-multi.ts
packages/integrations/node/test/fixtures/headers/src/pages/endpoints/response-cookies-single.ts
packages/integrations/node/test/fixtures/headers/src/pages/endpoints/response-empty-headers-object.ts
packages/integrations/node/test/fixtures/headers/src/pages/endpoints/response-undefined-headers-object.ts
packages/integrations/node/test/fixtures/headers/src/pages/endpoints/simple.ts
packages/integrations/node/test/image.test.js

It's failing in `next` branch now.
Should pass.
n/a

Fix node test fail

---

packages/integrations/partytown/README.md

- Fix broken GitHub link
- closes https://github.com/withastro/docs/issues/4038
Update docs with correct GitHub link

fix broken partytown GitHub link

---

.changeset/cold-maps-report.md
packages/astro/components/ViewTransitions.astro

- In fallback mode for the router we need to wait for animations (if there are any) and also setTimeout (in case there are none). This causes a race condition that can case swap() to be called twice.
- Fix is to remove the event listener and the timeout whenever the first wins.
- Tested manually. Maybe we should think about adding Firefox as a test runner some how.
Bug fix

Fix race condition when performing swap for fallback

---

packages/integrations/deno/README.md

- updates wrong import of `dist/entry.mjs` to `dist/server/entry.mjs`
only docs change
Closes https://github.com/withastro/docs/issues/4040

chore: update Deno server import path

---

.github/workflows/check.yml

Make sure they don't run forever. Some are hanging currently.
Set to 7min as that's the max I've seen. Usually they float around 5min.

Add timeout for check CI

---

.changeset/new-otters-sell.md
packages/astro-rss/src/index.ts

- This PR adds the URL type to `RSSOptions.site`
- `site` was only of type `string` before and lead to TS errors
- Closes #7951 
- Ran `pnpm exec changeset`
- Did manual testing in TS Playground to check for the best option (wanted to use zod instead of URL directly, but did not really work)
- Existing tests still run as expected
- No changes in the docs necessary

Add URL to RSSOptions.site type

---

.changeset/red-bikes-return.md
packages/astro/src/core/create-vite.ts
packages/astro/src/vite-plugin-integrations-container/index.ts

- In https://github.com/withastro/astro/pull/7943, we missed the fact that the integrations container plugin was only applied during `dev`
- This updates the logic to ensure the integrations container plugin can always run
- Adds guard to only run `server:setup` hooks during `dev`
- Adds guard to only run `resolveInjectedRoutes` during server build (otherwise, `buildStart` runs twice)
Tested manually because monorepo
N/A

Ensure `injectRoute` works during build

---

.changeset/violet-peaches-invent.md
packages/astro/package.json
packages/astro/test/ssr-api-route.test.js
packages/astro/test/test-utils.js
packages/integrations/node/package.json
packages/integrations/node/src/response-iterator.ts
packages/integrations/node/test/prerender-404.test.js
packages/integrations/node/test/prerender.test.js
packages/telemetry/package.json
packages/telemetry/src/post.ts
pnpm-lock.yaml

Remove `undici` dependency as Node.js 18 now includes it ootb.
Existing tests should pass. I also ran the astro, node integration, and telemetry tests locally.

Remove undici dep

---

.prettierrc.cjs
examples/blog/src/content/blog/markdown-style-guide.md
package.json
packages/astro/astro-jsx.d.ts
packages/astro/content-types.template.d.ts
packages/astro/src/@types/astro.ts
packages/astro/src/vite-plugin-head/index.ts
packages/integrations/image/README.md
packages/integrations/image/src/build/ssg.ts
packages/integrations/node/src/response-iterator.ts
packages/integrations/node/src/types.ts
pnpm-lock.yaml

It updates prettier to `3.0`
I run locally the script that formats the code, and it works as expected.
N/A

chore: update prettier to `3.0`

---

.changeset/dry-pandas-flash.md
packages/create-astro/src/actions/template.ts

This adds some more special case handling for Starlight starter templates
Currently we hardcode `--template starlight` to `withastro/starlight/examples/basics`.
But https://github.com/withastro/starlight/pull/337 adds a new starter, and it would be nice to shorten the command needed to use it.
```sh
npm create astro@latest -- --template withastro/starlight/examples/tailwind
npm create astro@latest -- --template starlight/tailwind
```
If we think this is too much special-casing, we can close this.
Tested the logic works manually, but not sure if it’s possible to run the local `create-astro`?
Will only impact Starlight’s docs, which I’ll update if we merge this.

Add shorthand for Starlight templates to `create astro`

---

.changeset/funny-glasses-bathe.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/endpoint/index.ts
packages/astro/src/vite-plugin-astro-server/route.ts

Fixes `EndpointOutput` type.
```ts
// Before
const output: EndpointOutput = {
body: someBuffer, // Error! "Should be a string"
encoding: 'binary',
}
// After
const output: EndpointOutput = {
body: someBuffer, // Ok!
encoding: 'binary',
}
```
Just types updates
Docs already describe the desired behavior

fix: `EndpointOutput` type with encoding `'binary'`

---

.changeset/six-grapes-look.md
packages/astro/e2e/astro-envs.test.js
packages/astro/src/@types/astro.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/config/schema.ts
packages/astro/test/astro-envs.test.js
packages/astro/test/astro-global.test.js
packages/astro/test/dev-routing.test.js
packages/astro/test/preview-routing.test.js
packages/astro/test/public-base-404.test.js

fix https://github.com/withastro/astro/issues/6623
When `trailingSlash` is set to `ignore`, the `import.meta.env.BASE_URL` will have a string that's the same as `config.base` as-is. Unlike `always` where it always adds a trailing slash, and unlike `never` where it'll never have a trailing slash.
Since the issue was created, looks like docs now [document the old, different behaviour](https://docs.astro.build/en/reference/configuration-reference/#base):
> By default, the value of import.meta.env.BASE_URL includes a trailing slash. If you have the [trailingSlash](https://docs.astro.build/en/reference/configuration-reference/#trailingslash) option set to 'never', you will need to add it manually in your static asset imports and URLs.
where `ignore` would work like `always` (Always have a …

Preserve base slash when trailingSlash ignore

---

.changeset/gentle-deers-yawn.md
package.json
packages/astro/src/cli/check/index.ts
pnpm-lock.yaml

The examples check workflow was hanging as `@astrojs/check` wasn't installed for the examples, and it was requesting user input the install it.
This PR fixes it by installing `@astrojs/check` at the monorepo root.
Examples check should pass now.
n/a

Fix examples check hang

---

packages/integrations/markdoc/README.md

docs: Fix error link in markdoc

---

.changeset/great-icons-turn.md
packages/astro/src/runtime/server/astro-island.ts
packages/astro/src/runtime/server/serialize.ts
packages/astro/test/serialize.test.js

- Only call `JSON.stringify` once when serializing props for an island
- Match this change when deserializing props for an island
- This fixes a quadratic increase in quote escaping when using nested data, see #7978 
I added a test that the kind of nested data from #7978 results in a normal-sized serialized text.
I didn't add more tests in this branch because I'm not comfortable changing the code organization in the project but I committed to another branch how I tested the implementation, basically by adding roundtrip tests to the file `serialize.test.js`. However I had to move the deserialization to the same file as the serialization, which I'm not sure fits the project structure. See https://github.com/daltonmaag/astro/commit/a513407c9c5efb30cd7be70892c8e2c7e677db56
I believe this …

Remove nested JSON.stringify from props serialization

---

.changeset/quick-actors-sing.md
packages/astro/src/jsx/renderer.ts
packages/integrations/preact/src/index.ts

This brings Astro a step closer to running on Bun by working around an existing workaround done when loading `@babel/plugin-transform-react-jsx`.
In Bun and some other tooling, `import`ing a CommonJS module that has `module.exports.__esModule` will tell the module loader/bundler to set `module.exports.default` as the ESM default export, where without this annotation the default export will be set to `module.exports`. Node does not do this transformation, which turns transpiled-to-cjs modules like `@babel/plugin-transform-react-jsx` into `{ default: { default: Function } }`, where in bun this loads as originally intended like `{ default: Function }`
This PR fixes the three places astro uses `.default.default` and ensures it handles the case where it may be just `.default`.
Our tracking …

Support Bun by adjusting how `@babel/plugin-transform-react-jsx` is imported.

---

.changeset/wild-jobs-tan.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/build/plugins/index.ts
packages/astro/src/core/build/plugins/plugin-analyzer.ts
packages/astro/src/core/config/schema.ts
packages/astro/test/hoisted-imports.test.js

Fix https://github.com/withastro/astro/issues/7744
Supersedes and closes https://github.com/withastro/astro/pull/7997
Move the feature in https://github.com/withastro/astro/pull/7707 behind an experimental flag. And added extra comments to make the analysis easier to follow.
Updated hoisted script test to enable the experimental flags.
Added the jsdocs. cc @withastro/maintainers-docs for feedback!

Move hoisted script analysis optimization as experimental

---

packages/astro/content-types.template.d.ts

Provides more useful information when hovering variables typed with CollectionEntry<"collectionName"> 
* Does not change the functionality of existing code
* Flatten<AnyEntryMap[C]> is the same as AnyEntryMap[C][keyof AnyEntryMap[C]]
* Both will produce a union of all note entry types within the "collectionName" key
The CollectionEntry type which is a part of astro:content module that is autogenerated in .astro/types.d.ts
Made this change locally and tried it with VSCode having made sure the types were updated with both astro build and npm run dev. Tried it with multiple collections, of different shapes. 
No, it will only …

CollectionEntry type improvement 

---

packages/astro/src/core/README.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/ssrPipeline.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-analyzer.ts
packages/astro/src/core/cookies/index.ts
packages/astro/src/core/cookies/response.ts
packages/astro/src/core/endpoint/index.ts
packages/astro/src/core/pipeline.ts
packages/astro/src/core/render/context.ts
packages/astro/src/core/render/core.ts
packages/astro/src/core/render/index.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/units/render/head.test.js
packages/astro/test/units/render/jsx.test.js

This PR starts the refactors around how routes are rendered. 
The idea is the following: creating a "core" that does one single thing, render a route by returning a `Response`, and remove from the equation all the information that aren't part of a page. For example, the `Environment` is not information that belongs exclusively to a page. 
Then, in the future refactos, we are going to create **specialized** pipelines - or consumers - that compute the basic information in a different way, and then **handle** the finished `Response` in a different way. These specialized pipelines will be: the dev server, the build, SSR. In the future we will have containers and testing.
We are going to have a `Pipeline` base class, which exposes a method called `renderRoute`. It accepts the `RenderContext` …

refactor: add pipeline concept

---

.changeset/tender-tips-kneel.md
packages/astro/components/ViewTransitions.astro

- Formerly, links with a hash mark did not start view transitions. Now they will, if they lead to a different page.
- Formerly, links to the same page (without hashes) did start view transitions. Now they don't.  
Tested with the examples from #7849 and #7882
No doc updates required.
Fixes unexpected behavior

View Transitions: do not animate same page navigation, but animate hash links to different pages

---

.changeset/giant-plants-sip.md
packages/astro/e2e/css-sourcemaps.test.js
packages/astro/e2e/css.test.js
packages/astro/e2e/multiple-frameworks.test.js
packages/astro/src/cli/add/index.ts
packages/astro/src/core/util.ts
packages/astro/src/jsx/server.ts
packages/astro/src/runtime/server/render/util.ts
packages/astro/test/astro-external-files.test.js

- Clear some actionable TODO comments
- Remove kebab-case transform for camelCase CSS variables (#6264 for more context)
- Remove `astro add` error when match `package.json` files. Our config search code now only matches `astro.config.*`, so it'll never hit that condition.
Removed some test skips marked todo. See if they pass now.

Clear todos and remove css kebab handling

---

.changeset/nasty-olives-rush.md
packages/create-astro/src/actions/dependencies.ts

- Closes #5637 
- Adds a `yarn.lock` file before attempting to install dependencies, which makes yarn berry work
Tested manually! Our automated tests don't run dependency installation
N/A

[create-astro] improve yarn berry support

---

.changeset/rotten-flowers-know.md
packages/astro/src/core/build/plugins/plugin-middleware.ts
packages/astro/test/middleware.test.js

Closes https://github.com/withastro/astro/issues/7971
I manually tested that no edge functions are created.
N/A

fix: middleware entry point to not be set

---

.changeset/lovely-impalas-pretend.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/components/Layout.astro
packages/astro/e2e/view-transitions.test.js

- Prevents re-evaluation of scripts on a transition.
- This is similar to what Swup does.
- This fixes a reported bug where the VT Router re-evaluates and sets up redundant event listeners and chaos ensues.
- The fix is to set a `data-astro-exec` attribute on scripts that have ran and then preventing that from reoccurring.
- Fixes https://github.com/withastro/astro/issues/7956
- Test added

Prevent script re-execution on page evaluation

---

.changeset/ten-parrots-burn.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/astro.config.mjs
packages/astro/e2e/fixtures/view-transitions/package.json
packages/astro/e2e/fixtures/view-transitions/src/pages/query.astro
packages/astro/e2e/view-transitions.test.js
pnpm-lock.yaml

- When navigating we prevent same-page transition normally. But when there are search params we should treat that as a different page and have a transition.
N/A, bug fix

Fix same-page transition with different query params

---

packages/integrations/netlify/README.md

After discussion with @sarah11918, we've decided to reword a sentence in the `README.md` for the Netlify integration
N/A
Docs change, see above

chore: Update README.md

---

.changeset/big-tips-whisper.md

The `@astrojs/internal-helper` beta code is borked as it doesn't contain the code from v0.1. Likely caused by releasing beta, then main perhaps.
fix https://github.com/withastro/astro/issues/8052
n/a. only changeset.
n/a. only changeset.

Add changeset for internal helper package

---

.changeset/odd-plants-tie.md
packages/astro/client-base.d.ts
packages/astro/src/assets/internal.ts
packages/astro/src/assets/types.ts
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image/src/pages/inlineImport.astro

What the title says. This is a pretty common request since when using inline imports, it's super annoying to have to await + `.default` it, and especially when using components in MDX and stuff, you kinda want your code to be as neat as possible. Also, this worked in `@astrojs/image` and people wanted it back
Added a test
N/A, the proper path is already documented, this is something people might stumble upon

feat(assets): Add support for passing non-awaited imports to the Image component and `getImage`

---

.changeset/thin-plums-drop.md
packages/astro/e2e/fixtures/react-component/src/components/WithId.jsx
packages/astro/e2e/fixtures/react-component/src/pages/index.astro
packages/astro/e2e/react-component.test.js
packages/integrations/react/client.js

There was a low-impact bug with the unique id generation fix, causing client:only ids to be generated with `null`, e.g. `:nullr0:` 
The ids generated are actually still unique, and avoid clashes with server-side, but it was flagged by a team member as a possible bug, so I felt an upstream fix was wise.
- removes the identifierPrefix from client:only components, to prevent client:only useId calls from being prefixed with `null`
- quick test in browser via linking
- additional e2e test case added to validate clientside results are unique, and do not clash with static or hydrated server-rendered results.
No docs required, no change to user behaviour.

fix: prevent null prefixed results from React.useId when using client:only directive

---

.changeset/strong-papayas-chew.md
packages/integrations/cloudflare/src/index.ts

- Sync astro features setting across both adapter modes
- astro assets is supported, but only `noop`
- Not needed
- changeset review

fix(@astrojs/cloudflare): unsynced astro asset support flag

---

.changeset/neat-owls-run.md
packages/astro/package.json
packages/astro/src/core/compile/compile.ts
packages/astro/src/runtime/README.md
packages/astro/src/runtime/compiler/index.ts
packages/astro/src/runtime/server/index.ts
packages/astro/src/vite-plugin-mdx/tag.ts

(Same as changeset)
Remove exports for `astro/internal/*` and `astro/runtime/server/*` in favour of `astro/runtime/*`. Add new `astro/compiler-runtime` export for compiler-specific runtime code.
Ultimately it would be nice to get rid of `astro/runtime/*` and make it all stricter, but that's longer term.
We currently don't reference these exports in the docs, which is great since they are internal APIs. The `@astrojs/compiler` README can use an update after 3.0 is released to recommend `astro/compiler-runtime` over `astro/runtime/server/index.js`

Export astro/compiler-runtime and cleanup exports

---

packages/astro/package.json
packages/astro/src/core/config/tsconfig.ts
pnpm-lock.yaml

Implement a simpler merge function (based on Astro's mergeConfig utility but simplified) to prevent needing to use a dep.
Tested with a project running `astro add preact`, `astro add solid-js`, etc. Making sure the `tsconfig.json` updates still work.

Remove deepmerge-ts for simpler implementation

---

packages/astro/src/@types/astro.ts

close https://github.com/withastro/astro/issues/5630
It is documented how `build.format` affects `Astro.url`. This PR further explains how to prevent inconsistencies in dev by updating `trailingSlash` so it aligns with how `build.format` affects `Astro.url`.
n/a.
updates the jsdoc for `build.format`

Document SSG format and trailingSlash consistency

---

.changeset/tall-owls-act.md
packages/astro/components/Code.astro

Removed an invalid extra double quote that is added to the shiki wrapper component called Code.
Sorry, I don't have the time to learn how to properly create unit tests for this within your ecosystem.  Sorry if this is unacceptable.  The test I would add I guess would be whether the style attribute is properly formed without the extra double quote.  I am not sure how to do that.
I would assume no document changes should be needed for this.  It currently creates malformed html, but at least Chrome still renders properly even with the malformed HTML.  This should not affect the functionality other than possibly make stricter browsers (if they exist) work properly.

fix: Removed extra double quotes from computed style in shiki code component

---

README.md

This is a sister PR to https://github.com/withastro/astro.build/pull/765.
**Context:** Transloadit is a Gold Sponsor and we'd like to showcase our logo on the Astro GitHub README and on the Astro homepage. The main changes, including the addition of the logo, can be found in the sister PR mentioned above.
- Updated the `alt` for the sponsors image in the README.

Add Transloadit to the Gold Sponsors list

---

.changeset/angry-balloons-argue.md
packages/create-astro/src/shell.ts

- The timeout logic added in https://github.com/withastro/astro/pull/8077 caused some issues
- This PR refactors `shell` to rely on Node's built-in `timeout` support
- If a `ChildProcess` times out, it will emit the `close` event but the `exitCode` will be `null`.
Tested manually because it's spawning a shell

[create-astro] update shell logic

---

.changeset/shaggy-cameras-hide.md
packages/astro/components/ViewTransitions.astro

deletes `<noscript>` descendants of the `<head>` element, since they are ignored during view transitions.
Since this is a JavaScript client side router, we can ignore noscript trees completely. 
Solves #7969
Manually tested with the Minimal Reproducible Example of #7969
n.a. / bug fix

Handle noscript tags in head during ViewTransitions

---

packages/astro/src/cli/add/index.ts
packages/astro/src/core/app/ssrPipeline.ts
packages/astro/src/core/build/buildPipeline.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/internal.ts
packages/astro/src/core/build/plugins/README.md
packages/astro/src/core/build/plugins/index.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/build/plugins/plugin-ssr.ts
packages/astro/src/core/build/static-build.ts
packages/astro/src/core/logger/core.ts
packages/astro/src/core/pipeline.ts
packages/astro/src/prerender/utils.ts
packages/astro/test/astro-assets-prefix.test.js
packages/astro/test/ssr-hoisted-script.test.js

This PR refactors the build process using the `Pipeline` class.
Here's a list of significant changes:
- created a new `plugin-manifest` plugin to generate the manifest. The `manifest` object is now emitted in a separate file called `manifest.mjs`. The file is emitted in the `config.build.server` folder. This is an internal refactoring. I went with this change because the manifest was repeated for each emitted entry/route, giving the impression that a manifest belongs to an entry/route. This isn't correct. A manifest belongs to the whole app. It made more sense to have a separate file with this information. 
- created a new `BuildPipeline` class that extends `Pipeline`, which is responsible for giving all the essential information to its consumers; for example, `BuildInternals` and …

refactor: build pipeline

---

packages/astro/src/vite-plugin-integrations-container/index.ts
packages/astro/test/fixtures/integration-server-setup/integration.js

Closes #8097
Add async/await into configureServer so that integrations with an async astro:server:setup hook can function correctly.
I edited the built file directly in my target app before creating this patch, and it worked for me in that scenario.  I don't yet know how to create a proper test case around this.  Please see discussion in #8097 
No documentation change; the docs already have this hook defined to return a Promise<Void>, this change just fixes the code so it honors that.

Fix missing async/await in vite-plugin-integrations-container on astro:server:setup hook

---

.changeset/clever-bats-breathe.md
packages/astro/src/assets/types.ts
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/test/fixtures/content-collection-references/src/content/banners/welcome.json
packages/astro/test/fixtures/core-image-base/src/content/blog/one.md
packages/astro/test/fixtures/core-image-base/tsconfig.json
packages/astro/test/fixtures/core-image-ssg/tsconfig.json
packages/astro/test/fixtures/core-image/src/content/blog/one.md
packages/astro/test/fixtures/core-image/tsconfig.json
packages/astro/tsconfigs/base.json
packages/integrations/markdoc/test/fixtures/image-assets/tsconfig.json
packages/integrations/mdx/test/fixtures/mdx-images/tsconfig.json
pnpm-lock.yaml

What the title says, the alias didn't work properly in the editor because of how TypeScript works and it was a bit awkward to have now that `src/assets` isn't necessarily as special as it used to be. We'll revisit this in the future in a dedicated "should we have cool aliases?" RFC potentially. But for 3.0, no built-in aliases. Of course people can still define them themselves if they desire to.
Kept the tests for aliases since it's good to test for people who configure them, but added the alias manually to those tests
Already covered by Sarah's current work on the v3 page for assets

config: remove ~/assets alias

---

.changeset/wet-foxes-sleep.md
packages/astro/components/ViewTransitions.astro

`astroTransition = dir` is now set for the current document.
The removal of the attribute from the DOM is put on hold for now, since the removal seems to prevent fallback animations.
Plus: fix for an of-by-one bug I introduced in a previous commit that prevented the correct detection of direction ;-)
Manual tests only
n/a bug fix

fix: reinsert attribute to specify direction of ViewTransition

---

.changeset/neat-mugs-end.md
examples/middleware/src/middleware.ts
packages/astro/client.d.ts
packages/astro/package.json
packages/astro/src/@types/astro.ts
packages/astro/src/core/create-vite.ts
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/core/middleware/namespace.ts
packages/astro/test/fixtures/astro-component-code/src/pages/basic.astro
packages/astro/test/fixtures/astro-component-code/src/pages/css-theme.astro
packages/astro/test/fixtures/astro-component-code/src/pages/custom-theme.astro
packages/astro/test/fixtures/astro-component-code/src/pages/imported.astro
packages/astro/test/fixtures/astro-component-code/src/pages/inline.astro
packages/astro/test/fixtures/astro-component-code/src/pages/no-lang.astro
packages/astro/test/fixtures/astro-component-code/src/pages/wrap-false.astro
packages/astro/test/fixtures/astro-component-code/src/pages/wrap-null.astro
packages/astro/test/fixtures/astro-component-code/src/pages/wrap-true.astro
packages/astro/test/fixtures/code-component/src/pages/index.astro
packages/astro/test/fixtures/middleware-dev/src/middleware.js
packages/astro/test/fixtures/middleware-ssg/src/middleware.js
packages/astro/test/fixtures/ssr-redirect/src/middleware.ts
packages/astro/test/fixtures/static-build-code-component/src/pages/index.astro
packages/astro/test/fixtures/static-build-dir/src/pages/index.astro
pnpm-lock.yaml

- Adds aliases of `astro:middleware` and `astro:components`
- All updated to use the aliases
- [PR](https://github.com/withastro/docs/pull/4239)

`astro:` namespace for middleware and components

---

packages/astro/src/core/app/index.ts
packages/astro/src/core/pipeline.ts
packages/astro/src/core/render/environment.ts
packages/astro/src/core/render/index.ts
packages/astro/src/core/render/renderer.ts
packages/astro/src/prerender/routing.ts
packages/astro/src/vite-plugin-astro-server/devPipeline.ts
packages/astro/src/vite-plugin-astro-server/environment.ts
packages/astro/src/vite-plugin-astro-server/index.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/request.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/units/routing/route-matching.test.js
packages/astro/test/units/vite-plugin-astro-server/request.test.js

This PR takes the pipeline concept into development mode. 
The `DevPipeline` is very similar to the `BuildPipeline`. Like in the previous PR, the `pipeline` object is passed around, and functions request from it all the information that is needed.
This refactor removes the need for `DevelopmentEnviroment`: `AstroSettings` and `ModuleLoader` are stored in the `DevPipeline`, and functions use its getters `getSettings` and `getModuleLoader`.
I also removed `tryRenderRoute`, which was deprecated.
I updated some unit tests to use this new `DevPipeline`. Eventually, we should use a new `TestPipeline` for these kinds of tests, but not in this PR.
N/A

refactor: use pipeline in Development mode

---

.changeset/small-nails-try.md
packages/astro/components/ViewTransitions.astro

When the popState handler sees a entry without state, leave that alone.
The original code updated the entry and thereby introduced state.
A entry with state is viewed as an view transition entry.
Thus when navigating back, the transition gut animated 
even though it wasn't when we walked forward in the first place
only manual tests
n/a. Bug fix.

only update our own history entries during back navigation through VT

---

packages/astro/src/core/errors/errors-data.ts

We received a comment that one of our older (pre-hybrid rendering) error messages only suggests switching to `server` as a solution.
This adds the option to set hybrid rendering to the error message:
> Alternatively, set \`output: "server"\` **or \`output: "hybrid"\`** in your Astro config file to switch to a non-static server build. This error can also occur if using \`export const prerender = true;\`.
No tests; docs.
All docs!

[error msg] add hybrid option to a getStaticPaths error message

---

.changeset/lovely-walls-call.md
packages/astro/src/core/build/generate.ts

- Updates `astro build` logic error to print more accurate time stats
- Closes #6965
Tested manually, it works!
N/A

Fix build stats

---

.changeset/popular-carrots-sneeze.md
packages/astro/src/core/dev/container.ts

- When running `astro dev --open` or using `astro dev` with `server.open === true` and a set `base` path, this PR makes it so the browser opens to `/[base]`
- Closes #7486
N/A, bug fix

Open to configured base path

---

.changeset/cyan-carrots-stare.md
packages/astro/config.d.ts
packages/astro/config.mjs
packages/astro/src/assets/services/sharp.ts
packages/astro/src/core/errors/errors-data.ts

Unfortunately, due to bundling, packaging, JavaScript, etc nonsense, on pnpm Sharp fails to be found. There's no proper way to fix this that wouldn't be: risky and/or unreliable. Trust me, I tried putting `sharp` in every single Vite config I found.
So, I did the next best thing: I upgraded the error message with every bit of info I could. I also added the passthrough / noop image service to the config so it's easier to use for SSR users who don't want to install Sharp into their projects. In the future, a more optimal solution for SSR would be a way to disable the endpoint, but that also requires either rethinking how we do images in Markdown, or at least a way to disable image processing in Markdown, it's a bit complex.
Fix https://github.com/withastro/astro/issues/7966 …

fix: better error when Sharp can't be resolved (ex: pnpm)

---

.changeset/twenty-mirrors-remember.md
packages/astro/src/content/utils.ts

- Closes #8134
- Normalize id's for data entries same as content entries are.
Quick fix, tested manually.

fix(data collections): normalize file paths for DataEntry.id

---

.changeset/cool-jokes-clap.md
packages/astro/package.json
packages/astro/src/runtime/server/hydration.ts
packages/astro/src/runtime/server/render/component.ts
packages/astro/src/runtime/server/render/util.ts
packages/astro/src/runtime/server/util.ts
packages/astro/test/astro-class-list.test.js
packages/astro/test/fixtures/astro-class-list/src/components/Span.astro
packages/astro/test/fixtures/astro-class-list/src/pages/component.astro
packages/astro/test/fixtures/astro-class-list/src/pages/index.astro
packages/astro/test/units/render/components.test.js
pnpm-lock.yaml

- Closes #7747, closes #8108
- Brings back @FredKSchott's proposed changes from #3935
- Replaces custom `class:list` implementation with popular, battle-tested [`clsx`](https://github.com/lukeed/clsx) library
Test added to ensure #7747 does not regress
Need to add to migration guide and also update `class:list` note.
/cc @withastro/maintainers-docs for changeset feedback!

Replace `class:list` implementation with `clsx`

---

.changeset/rude-ducks-exist.md
packages/integrations/node/src/preview.ts

- Closes #8054
- Cause: the preview entrypoint passed a callback to nodeMiddleware, which overrode the recently refactored 404/500 handling.
- Fix: removed the callback to let src/core/app handle 404 and 500.

fix(node): delegate preview's not found and error handling to core/app

---

.changeset/yellow-tips-cover.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/ssrPipeline.ts
packages/astro/src/core/build/buildPipeline.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/endpoint/index.ts
packages/astro/src/core/pipeline.ts
packages/astro/src/core/render/core.ts
packages/astro/src/vite-plugin-astro-server/devPipeline.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/non-html-pages/src/pages/about-object.json.ts
packages/astro/test/fixtures/non-html-pages/src/pages/about.json.ts
packages/astro/test/fixtures/non-html-pages/src/pages/placeholder-object.png.ts
packages/astro/test/fixtures/ssr-api-route/src/pages/binary.js
packages/astro/test/fixtures/ssr-api-route/src/pages/food-object.json.js
packages/astro/test/fixtures/ssr-api-route/src/pages/food.json.js
packages/astro/test/non-html-pages.test.js
packages/astro/test/ssr-api-route.test.js

- Deprecate returning simple objects from endpoints
- Refactor endpoint handling to within `callEndpoint`. This makes the `#endpointHandler` convention in Pipeline not used much (only `ssrPipeline` has a special case) cc @ematipico
- NOTE: much of the refactor was a port from https://github.com/withastro/astro/pull/7588
Added test for `ResponseWithEncoding`, and tests for previous object form so they still work, until they're removed.
Added changeset. Any mention of the object form in docs might need to be removed.

Deprecate simple objects from endpoints

---

.changeset/many-ears-drum.md
packages/astro/client-base.d.ts

What the title says, once again having to manually update the type bit me
N/A, bug fix

fix(assets): Add missing type for imageConfig export

---

.changeset/spicy-icons-live.md
packages/astro/components/shiki-themes.js
packages/astro/scripts/shiki-gen-themes.mjs
packages/integrations/markdoc/src/extensions/shiki.ts
packages/integrations/mdx/src/remark-shiki.ts
packages/markdown/remark/src/remark-shiki.ts

Some theme names in pre-shiki v0.14 were preserved for backwards compatibility, which was introduced in https://github.com/withastro/astro/pull/6932.
This PR removes this compatibility. Users should rename to the new names instead.
New changeset.

Remove pre-shiki v0.14 theme names

---

packages/astro/src/@types/astro.ts

…ference
Updates the configuration reference docs for the two build options being deprecated in favour of new adaptor config options.
- removes `@version` (is that the right thing to do?) and adds the `@deprecated` tag
- provides a short description that mentions the adaptor config that replaces it, links to the adapter reference page, and also links to our list of SSR adapter guides and suggests reading those for docs on the new config options.
No tests, and you must absolutely vet this syntax!
It's all docs!

[docs] deprecate build.split and build.excludeMiddleware in config ref

---

.changeset/unlucky-cougars-heal.md
packages/astro/content-types.template.d.ts

- Makes the type for the `schema` option in `defineCollection` more permissive to match what we actually support internally.
- The current stricter type allows only the following, i.e. objects, unions of objects, or an intersection of objects:
- `z.object({...})`
- `z.union([z.object({...}), z.object({...}), ...])`
- `z.object({...}).and(z.object({...})`
- `z.discriminatedUnion('type', [z.object({...}), z.object({...})])`
- By making the type recursive, it also allows cases such as unions of unions, intersection of an object with an object union etc. If a user provides one of these types today, the code runs as expected, but `tsc` and editor tooling will complain about a type error.
- The base type is still only for objects, so this doesn’t expand the type to unsupported shapes like …

Use more permissive type for `defineCollection` schema option

---

.changeset/brown-numbers-prove.md
packages/astro/src/core/config/schema.ts
packages/astro/test/units/config/config-validate.test.js

fixes #6904
I thought that creating a ZodError in schema would be better than throwing a new error so it works for both ssr and ssg and we just need to change one file. What do you think?
And is this message ok?
New test expecting an error message.
n/a

add: config error if `outDir` is inside `publicDir`

---

.changeset/gold-carpets-film.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/one.astro
packages/astro/e2e/view-transitions.test.js

fix for #8069 
Links without hashes to the current page scroll to the top but do neither trigger reload nor page transition.
Restructured click handler logic to avoid code duplication for this case.  
added e2e test
n/a bug fix

fix: self link does not trigger page reload

---

.changeset/pretty-dancers-admire.md
packages/astro/components/ViewTransitions.astro

If `scroll-behavior: smooth` is set to the `<html>` element, the scrolling behavior of the navigation differs greatly once `<ViewTransitions/>` is added to a page.  
Unfortunately, not all browsers behave the same way. 
I started to make some decisions based on browser detection, but then decided against it. 
I took care of the main anomaly, which is that scrolling to a hash mark usually jumps to the top of the page first in Safari and the Chromium-based browsers. 
I also use `scrollIntoView()` to scroll to hash marks because it respects CSS `scroll-padding`.
detailed manual test
As soon as we introduce fine grained controls for users to change behavior

Mt scroll behavior

---

examples/portfolio/src/components/Nav.astro

- Closes https://github.com/withastro/astro/issues/8161
- Replaced the inline-style to a regular selector, for some reason it was breaking the template.

Fix: changed inline-style to regular selector

---

.changeset/spicy-stingrays-cheer.md
packages/astro/src/core/build/plugins/plugin-internals.ts

`sharp` can't be bundled and it fails in runtime if so. It's bundled by default with pnpm unless the user installs `sharp` themselves.
I'm updating some dependencies and it causes the Vercel test to OOM, this fixes it.
I also tested this with the `ssr` example app and it still works.
n/a. bug fix.

Prevent bundling sharp

---

.changeset/mean-snakes-play.md
packages/astro/src/runtime/server/render/any.ts
packages/astro/src/runtime/server/render/astro/render-template.ts
packages/astro/src/runtime/server/render/common.ts
packages/astro/src/runtime/server/render/component.ts
packages/astro/src/runtime/server/render/util.ts
packages/astro/test/astro-basic.test.js
packages/astro/test/fixtures/astro-basic/src/components/OrderA.astro
packages/astro/test/fixtures/astro-basic/src/components/OrderB.astro
packages/astro/test/fixtures/astro-basic/src/components/OrderLast.astro
packages/astro/test/fixtures/astro-basic/src/pages/order.astro

Fix https://github.com/withastro/astro/issues/8059
Previously, the `renderComponent` API will kick off the render directly, however I didn't notice that component slots are inited eagerly (for head propagation) and it kicked off the rendering of slots eagerly (not good).
This PR reverts to the previous technique where the parent will render each child in parallel manually instead. It renders all the child into a buffer first, then flush it out when it's its turn to render.
NOTE: While the benchmark shows that this is faster, it's because I removed the `bufferChunks.length = 0` optimization which seems to do more harm than good for perf. If I ported that, the perf is actually slightly lower because things are less in parallel.
n/a. bug fix.

Fix Astro components parent-child render order

---

.changeset/silent-snakes-shave.md
packages/integrations/cloudflare/README.md
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/src/server.advanced.ts
packages/integrations/cloudflare/src/server.directory.ts

Closes https://github.com/withastro/astro/issues/8060
N/A

docs: better documentation for `runtime`

---

examples/portfolio/src/components/Hero.astro

This replaces header inside hero component to a div. Closes #8203 
npm run dev
Docs not required

refactor: replace header with div

---

.changeset/lovely-ducks-move.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/components/AttributedLayout.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/other-attributes.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/some-attributes.astro
packages/astro/e2e/view-transitions.test.js

fix: extends swap() to include the attributes of the documents root element
added e2e test
n/a
bug fix

View Transition: swap attributes of document's root element

---

.changeset/tasty-dragons-smash.md
packages/astro/src/vite-plugin-inject-env-ts/index.ts

#7921 removed this code by accident, but it was intended to stay until 4.0~ to help users who are migrating to 3.0.
Copy-pasted back code in
N/A

fix: add back code to update user's env.d.ts with proper types

---

.changeset/lovely-ducks-move.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/components/AttributedLayout.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/other-attributes.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/some-attributes.astro
packages/astro/e2e/view-transitions.test.js

In an anchor element, the `data-astro-reload` property (with no value or with a value other than `'false'`) forces a reload of the target document (instead of a view transition).
Closes #7947 
manually tested on the example given in #7947, outcome documented there.
[update 2023-08-22]: added e2e test 
The documentation  of the (still experimental) View Transitions needs to be updated.
Not sure if the data property will be the final interface for users or if there will be syntactic sugar (e.g. `transition:reload`).
I plan to add one or more properties in the next few days to address other issues, in particular a property to control cross-page scrolling behavior (as opposed to on-page scrolling behavior)

 property in anchor element forces a reload of the target

---

.changeset/proud-fans-type.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/components/DarkMode.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/two.astro
packages/astro/e2e/view-transitions.test.js

> Do not merge! This is a draft as we biekshed these names. Will undraft once consensus is reached.
- From the RFC: https://github.com/withastro/roadmap/pull/607
- Renames the `astro:load` to `astro:page-load`
- `astro:load` is already taken.
- Renames `astro:beforeload` to `astro:after-swap`.
- The event fires immediate after the DOM contents are swapped, so you can update the DOM to prevent FOUC
- Most common use-case is dark mode.
- Test updated
- TBD, after the final naming decision is made.
Based on other discussions from the RFC, I think these are the major points of contention to decide:
1. The `afterswap` name doesn't mention the transition. Some think it should.
2. The names are lowercased without dashes or camelcasing. The reasoning is that this follows the naming convention of …

Finalize View Transition event names

---

packages/astro/src/core/app/index.ts
packages/astro/src/core/app/types.ts
packages/astro/src/core/build/buildPipeline.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/build/plugins/plugin-middleware.ts
packages/astro/src/core/build/types.ts
packages/astro/src/core/redirects/component.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/test/fixtures/middleware-dev/src/middleware.js
packages/astro/test/fixtures/middleware-dev/src/pages/404.astro
packages/astro/test/middleware.test.js
packages/astro/test/test-adapter.js

Closes https://github.com/withastro/astro/issues/8154
This fix goes into `next` because it requires some infrastructure that we have there but not in `main`.
This PR removes the `onRequest` function from the "ComponentInstance", instead we move its resolution inside the pipeline. The middleware now becomes 100% detached from a page/route. 
This change fits perfectly because the SSR build already creates a `middleware.mjs` file, and we already save the `middlewareEntryPoint` file.
I created a new test case.
N/A

fix(ssr): correctly call the middleware when rendering error pages

---

.changeset/long-chefs-jump.md
packages/astro/components/ViewTransitions.astro

The [scrollend](https://developer.chrome.com/blog/scrollend-a-new-javascript-event/#event-details) mechanism seems like a better way to record the scroll position compared to throttling, so we could use it whenever a browser supports it.
Additionally, I've removed the `{passive}` flag from the `scroll` event, as it does nothing ([source](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener?retiredLocale=de#improving_scrolling_performance_with_passive_listeners:~:text=You%20don%27t%20need%20to%20worry%20about%20the%20value%20of%20passive%20for%20the%20basic%20scroll%20event.%20Since%20it%20can%27t%20be%20canceled%2C%20event%20listeners%20can%27t%20block%20page%20rendering%20anyway.)).
I've tested it locally, but maybe I'm missing out how you are testing changes to …

feat(ViewTransitions): use `scrollend` instead of `scroll` where supported

---

.changeset/fresh-shrimps-happen.md
packages/integrations/react/package.json

Fix https://github.com/withastro/astro/issues/8135#issuecomment-1690080856
Looks like the fix from https://github.com/withastro/astro/pull/8137 and https://github.com/withastro/astro/pull/8149 got lost when merging to `next`.
Question: Why in #8137 we export `@astrojs/react/vnode-children.js`? It doesn't seem like the export is used and documented.
Didn't test it. The `"files"` change should work.
n/a. bug fix.

Publish missing react vnode-children.js file

---

packages/integrations/react/README.md

- Fix type for react integration
- N/A
- N/A
No tests are needed as this is a doc typo fix PR
No docs are needed as this is a typo change within the react integration doc itself

docs: Fix typo in react integration README

---

.changeset/olive-moles-tan.md
packages/integrations/deno/src/index.ts
packages/integrations/deno/src/server.ts
packages/integrations/deno/src/types.ts

- Adds `start` to the `Options` type of the deno adapter
- Extract types to a dedicated file
- Closes #8221
Not tested
No docs updated

fix(deno): add start to options and extract to new file (close #8221)

---

.changeset/chatty-ways-hunt.md
packages/astro/src/core/errors/dev/utils.ts
packages/astro/src/core/errors/dev/vite.ts
packages/astro/src/core/messages.ts

Adds a link to the docs's error reference in the CLI, much like in the overlay
N/A

feat(cli): Add docs error link to errors in the CLI

---

.changeset/grumpy-years-remember.md
packages/astro/e2e/fixtures/view-transitions/src/components/Video.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/video-one.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/core/endpoint/index.ts

- Due to StackBlitz not yet supporting Node 18, we cannot extend `Response` until the polyfills have ran.
Just manually, this only affects stackblitz.
N/A, bug fix

Lazily initialize ResponseWithEncoding

---

.changeset/strong-needles-accept.md
packages/astro/components/ViewTransitions.astro
packages/astro/src/runtime/server/transition.ts

- Allows animations on the `html` element by fixing the selector so it targets both children and the root itself.
- Simplifies the fallback logic. Previous was not working in Safari because `animationstart` did not fire before the setTimeout.
- Now using https://developer.mozilla.org/en-US/docs/Web/API/Document/getAnimations which *I think* is safe to use. Waits on their `finished` event.
- Removed `opacity: 0` for the `none` animation as that causes the element to be invisible.
https://github.com/withastro/astro/assets/361671/3e6575bb-1825-4a38-96c2-9fc5124d6af7
N/A

 Allow fallback animations on html element

---

.changeset/breezy-books-notice.md
packages/astro/src/cli/index.ts
packages/astro/src/cli/telemetry/index.ts
packages/astro/src/core/messages.ts
packages/telemetry/src/index.ts
packages/telemetry/test/index.test.js

- Closes plt-846
- Updates our telemetry notice to include opt-out instructions
- Will trigger another telemetry notice when users run the Astro CLI again
Tested manually, no test coverage for this
Waiting on site update

Update telemetry notice

---

.changeset/heavy-countries-wonder.md
packages/astro/src/@types/astro.ts

What the title says! Much like we added a generic to type `Astro.self` recently, this adds one for `Astro.params`. The last remaining one will be for slots probably, but that one can wait until a refactor of our types
Tested it manually, it worked!
N/A

feat: add generic to type params to Astro global

---

.changeset/many-impalas-sit.md
packages/astro/src/core/config/schema.ts

The schema accepted if `image` wasn't set at all, but didn't set a default value to `image.service` if `image` did exists but was missing the service. This fixes that
N/A

fix: settings requiring service to be set when settings domains or remotePatterns

---

.changeset/swift-taxis-sing.md
.github/workflows/release.yml
packages/astro/components/index.ts
packages/astro/test/code-component.test.js

- Removes `ViewTransitions` from `astro/components`.
- This was added very early (before the first release I think), but we now say to import from `astro:transitions`.
- Having this as part of astro/components brings its script if you are just using, for example, `<Code />`.
- Added a test to the Code component test
Bug fix.

Prevent ViewTransition script from being added by mistake

---

.changeset/swift-taxis-sing.md
.github/workflows/release.yml
packages/astro/components/index.ts
packages/astro/test/code-component.test.js

- Cherry-picks from the patch that went into `2-legacy`

Prevent ViewTransition script from being added by mistake (#8268)

---

.changeset/tame-knives-shake.md
packages/astro/components/ViewTransitions.astro
packages/astro/src/runtime/server/astro-island.ts

- Previous swap order was causing videos to reset.
- Manual. We have a test that should have failed before. After this is released I'll work on fixing that test.
N/A, bug fix

Fix video persistence regression

---

packages/astro/src/@types/astro.ts

Small docs change so that we render `'attribute'` and not 'attribute' in docs.
through the power of my eyes
yes

Add missing backtics to `scopedStyleStrategy` value

---

.changeset/pre.json

This PR tells changeset that we exit from "pre" mode, in preparation for the official release.
Once merged, the changeset bot should prepare an official release,
N/A

chore: exit from `next` mode

---

packages/integrations/mdx/README.md

Removes the draft pages link from the mdx integration guide.
eyes and buttons
this

Remove draft pages info from mdx integration guide

---

.changeset/hot-timers-wink.md
packages/astro/src/@types/astro.ts

removes "experimental" from the image service configs
no testing, docs.
only docs!

[docs] remove experimental from image configs

---

.changeset/proud-trains-wonder.md
packages/astro/src/core/build/index.ts

This PR adds some useful warnings in case the user uses deprecated options.
Tested locally 
N/A

chore: add warnings  to console for deprecated options

---

examples/framework-react/tsconfig.json

Config has been outdated for the past two years. Luckily, `astro add react` did set the proper config
N/A
N/A

config: set proper default config on framework-react example

---

.changeset/nervous-beans-argue.md
packages/astro/components/index.ts

The new `astro:components`'s types in `client.d.ts` meansn that `astro/component/index.ts` gets included in the TypeScript project. This causes errors in `tsc` because that file is not supposed to be really type checked. This PR adds some comments to tell `tsc` that it's ok, really
Fix https://github.com/withastro/astro/issues/8291
N/A

fix: tsc errors in components

---

.changeset/thirty-bees-check.md
packages/integrations/vercel/src/serverless/adapter.ts

We log a warning to the user, because the number of functions emitted could exceed the limit of someone's plan.
Current tests should pass
N/A
/cc @withastro/maintainers-docs please check the warning

fix(@astrojs/vercel): warn user when `functionPerRoute` is `true`

---

.changeset/nine-terms-reply.md
packages/integrations/vercel/src/serverless/adapter.ts

- Updates the copy of the warning slightly.
- Encourages people to check their plan.
N/A
Needs review

Update Vercel warning verbiage

---

.changeset/tame-seas-sort.md
packages/astro/src/integrations/index.ts
packages/integrations/mdx/test/fixtures/mdx-plus-react/astro.config.mjs
packages/integrations/mdx/test/fixtures/mdx-plus-react/src/components/Component.jsx
packages/integrations/mdx/test/fixtures/mdx-plus-react/src/pages/post.mdx
packages/integrations/mdx/test/mdx-plus-react.test.js

- Fixes https://github.com/withastro/astro/issues/8317
- Previously when the JSX plugin was added by default it would be added last. When this was moved to being used by the MDX plugin that stopped happening.
- This fixes it by moving it to the end again.
- Test added to the mdx integration to check for warnings.
N/A, bug fix

Prevent React hook call warnings when used with MDX

---

.changeset/beige-walls-grow.md
packages/integrations/vercel/src/static/adapter.ts

This PR adds the astro feature map and adapter features to Astro. This will remove the warnings emitted by Astro.
I'll do a preview release to check if the warnings are gone.
N/A

fix(@astrojs/vercel): include astro feature map and adapter features to the static adapter

---

.changeset/twenty-crabs-fry.md
packages/astro/components/ViewTransitions.astro

- When using the morph animation, there is a scroll position jump when navigating back / forward through history.
- This is because the browser is restoring the old scroll position before the DOM is swapped.
- This PR simply changes `history.scrollRestoration = "manual";` to tell the browser we'll take care of the scroll position ourselves.
- Create a morph animation with `transition:name`
- Navigate back / forwards in history at various scroll positions and see the smooth animation
- No doc updated needed, this was a bug.

View Transitions: use history.scrollRestoration="manual"

---

.changeset/late-foxes-juggle.md
packages/astro/components/ViewTransitions.astro

- Fixes an issue some have reported where navigation does not complete in Safari.
- Before trigger animations, get a list of animations that currently exist. Then trigger the animation and filter out the existing animations. What you're left with should be animations that are part of the view transition.
https://github.com/withastro/astro/assets/361671/a3d87c05-d1b5-468d-850e-eb6c8e23d42f
N/A, bug fix

Prevent View Transition fallback from waiting on looping animations

---

.changeset/eight-zebras-rest.md
.github/ISSUE_TEMPLATE/---01-bug-report.yml
packages/astro/src/cli/info/index.ts

- `astro info` did not include the Node version, so I added that
- Made some readability improvements as well:
- Simplified language when no adapter is found
- Simplified formatting of integration list (now vertical)
- Combines `plaform` and `arch` into `system` and normalizes `platform` values to macOS, Windows, etc
- Adds a prompt for automatic "copy to clipboard" functionality as well
- Only supported on macOS (`pbcopy`) or Windows (`clip`). Linux support for similar commands is notoriously hard to nail down, but that's probably okay.
N/A, mostly for our own sanity!

Improve `astro info` command

---

.changeset/gorgeous-dogs-speak.md
packages/astro/src/core/build/plugins/plugin-ssr.ts
packages/astro/test/fixtures/ssr-split-manifest/astro.config.mjs
packages/astro/test/fixtures/ssr-split-manifest/src/pages/index.astro
packages/astro/test/ssr-split-manifest.test.js

Closes PLT-864
Closes https://github.com/withastro/astro/issues/8315
Created a new test, and verified that failed.
Applied the fix and verified that build works and the test passes.
N/A

fix: exclude redirects when running `functionPerRoute`

---

.changeset/proud-forks-rescue.md
packages/integrations/vercel/src/lib/fs.ts
packages/integrations/vercel/src/lib/nft.ts
packages/integrations/vercel/src/serverless/adapter.ts

Closes https://github.com/withastro/astro/issues/8312
This PR addresses two issues:
- **slowness of the build**: our adapter, when bundling a function, needs to carry over the dependencies that are inlined. Unfortunately, some package managers rely on symbolic links, and we need to trace them. This means that most of the time, the base path to start looking for files is the root folder (`/` or `C:\`). On big projects (monorepos), this could cause a lot of overhead. Fortunately, `@vercel/nft` allows us to pass a `cache` object to reuse when bundling the functions. **The first function to bundle will always be slow**, but the next ones are way faster. 
- **symbolic link issues**: I suppose this is specific to `pnpm`. Essentially, our adapter carries over the symbolic link of our inlined …

fix(@astrojs/vercel): slowness and symbolic link

---

.changeset/shy-socks-return.md
packages/integrations/vercel/src/lib/nft.ts

What the title says. Sharp is always external, so it'll always output a warning but this is not a problem
Tested it manually, it didn't output a warning, sir
N/A

fix(vercel): Don't output an error message for failing to resolve sharp

---

.changeset/quiet-sheep-refuse.md
packages/integrations/cloudflare/README.md
packages/integrations/netlify/README.md

- Updates two adapter README examples to use `GET()` instead of `get()`
- n/a
- Spotted this in https://github.com/withastro/docs/pull/4467

Uppercase endpoint examples in adapter READMEs

---

.changeset/polite-scissors-invent.md
packages/astro/src/assets/build/generate.ts
packages/astro/src/core/build/generate.ts

Added counter to show progress for assets image generation.
Fixed small unit of measurement error.
No tests are necessary, the change is minimal and just to logging.
No documentation changes are needed, adds info to logging.

feat: add progress to asset generation

---

.changeset/eighty-laws-brake.md
packages/astro/src/core/build/static-build.ts
packages/astro/test/sourcemap.test.js

- We were getting reports of the `@astrojs/netlify` adapter being totally broken for `server` and `hybrid` deployments.
- Turns out Astro would sometimes emit chunks with invalid characters `@_@` which Netlify choked on
- The fix is to ensure `chunkFileNames` sanitizes the filename first
- Also changes our chunk asset filenames from something like `dist/server/chunks/index@_@astro.[hash].[ext]` to something like `dist/server/chunks/index_hash.[ext]`
- Notable change is `[name].[hash].[ext]` to `[name]_[hash].[ext]`
- Changeset added!
Tested manually with community reproductions. It works!
Bug fix only, will alert folks!

Ensure `chunkFileNames` do not include invalid characters

---

.changeset/hot-colts-call.md
packages/astro/src/core/build/buildPipeline.ts

You can install a preview of this branch by running
```shell
npm install astro@next--fix-mime
```
- We had an error in our `beforeHydrationScript` handling introduced by the pipeline refactors.
- Thanks to @BlankParticle for [tracking this issue down](https://github.com/withastro/astro/pull/8088/files/ce393bdaf98c1db0a26f0d363f8be769a806046f#r1313949318) and recording their thoughts.
- Closes #8379, closes #8373, closes #8355, closes #8323. If you see any others with a MIME type error on hydration, this would also fix that.
Tested manually, should come back to add a regression test for the pipeline
Bug fix only

Fix pipeline `beforeHydrationScript` handling

---

.changeset/breezy-sloths-attend.md
examples/blog/src/content/config.ts
packages/astro/test/fixtures/content-ssr-integration/src/content/config.ts
packages/astro/test/fixtures/content-static-paths-integration/src/content/config.ts

This is my first contribution to Astro, please be gentle!
- Using `z.coerce.date()` is shorter and simpler.
Shouldn't change behaviour.
Shouldn't change behaviour.

chore: use `z.coerce.date()` to pass input through `new Date(input)`.

---

packages/integrations/vercel/CHANGELOG.md

This PR fixes a typo in [4.0.3 vercel integration package CHANGELOG](https://github.com/withastro/astro/blob/main/packages/integrations/vercel/CHANGELOG.md#403):
* `funcitonPerRoute` → `functionPerRoute`
_If this is too much nitpicking, feel free to close the PR without comment._
N/A
No impact on users.

fix: `funcitonPerRoute` → `functionPerRoute` in vercel integ package changelog

---

.changeset/spotty-glasses-grin.md
packages/integrations/mdx/src/index.ts

- Exposes MDX’s line/column data for errors in the shape Astro expects them so they get shown to users.
- Closes #8404 
Tested with a patch. I guess existing tests should pass.
Do we otherwise test error handling?
N/A

Add location data to MDX compile errors

---

packages/astro/src/@types/astro.ts

- Fix some formatting problems.
- Update image options description.
N/A because this is just a comment update.
N/A because this is just a comment update.

Fix some formatting problems and description in astro.ts

---

.changeset/hip-cats-jump.md
packages/astro/client.d.ts

Not sure how that happened, but we lost https://github.com/withastro/astro/pull/8171 in the rebasing process. This PR just brings it back
N/A

fix: missing imageConfig type in astro:assets

---

.changeset/chatty-walls-happen.md
.changeset/fair-countries-admire.md
.eslintrc.cjs
packages/astro/src/core/app/index.ts
packages/astro/src/core/build/plugins/plugin-css.ts
packages/astro/test/css-dangling-references.test.js
packages/astro/test/fixtures/css-dangling-references/astro.config.ts
packages/astro/test/fixtures/css-dangling-references/package.json
packages/astro/test/fixtures/css-dangling-references/src/components/DynamicallyImportedComponent1.svelte
packages/astro/test/fixtures/css-dangling-references/src/components/DynamicallyImportedComponent2.svelte
packages/astro/test/fixtures/css-dangling-references/src/components/Wrapper.svelte
packages/astro/test/fixtures/css-dangling-references/src/pages/glob-import-1.astro
packages/astro/test/fixtures/css-dangling-references/src/pages/glob-import-2.astro
packages/astro/test/fixtures/css-inline-stylesheets/package.json
packages/integrations/svelte/src/index.ts
pnpm-lock.yaml

Closes #8329 
Inlined CSS chunks are not deleted anymore, because when using dynamic imports with `import.meta.glob()`, vite tries to preload them.
Added a fixture.

Allow vite to refer to inlined CSS

---

.changeset/weak-kids-roll.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/long-page.astro
packages/astro/e2e/view-transitions.test.js

When navigating back (history navigation) from a page without ViewTransitions to a page with ViewTransitions the scroll position got lost.
Now fixed.
Thanks to @justinbeaty: That fix would not have worked without scrollRestoration="manual" 
e2e test added
n.a.

Fix scroll position when navigating back from page w/o ViewTransitions

---

packages/integrations/cloudflare/test/basics.test.js
packages/integrations/cloudflare/test/cf.test.js
packages/integrations/cloudflare/test/runtime.test.js
packages/integrations/cloudflare/test/with-solid-js.test.js

cc @Princesseuh
I tried to use retries, but Mocha doesn't support it in the `before` hook. Implementing retries manually is also tricky, so I went with this PR instead - Try to run the test as usual, but if startup fails, skip the test suite.
Ran the cloudflare tests locally. I've not seen it fail locally though.
n/a.

Skip cloudflare CLI tests if fail to start

---

.changeset/twelve-cars-tell.md
packages/astro/src/vite-plugin-markdown/index.ts
packages/astro/test/astro-pages.test.js

fix https://github.com/withastro/astro/issues/8378
The [JSX refactor PR](https://github.com/withastro/astro/pull/7924) updated vite-plugin-markdown so it returns an Astro component instance. When rendering Astro components, head is not rendered by default unless it calls `renderHead` or `maybeRenderHead`, which it doesn't.
This PR adds it to preserve the previous behaviour, and to fix the HMR issue.
Before the PR, markdown pages return non-Astro components and it has automatic head rendering, denoted by the `astro.needsHeadRendering` symbol. So it worked before.
Added a new test to ensure to Vite script is added.
n/a. bug fix.

Fix markdown page HMR

---

.changeset/empty-rings-bow.md
packages/astro/src/assets/build/generate.ts

It reverses the check for remote images in `astro:assets`, `JSONData.expires` should be higher than `Date.now()`, not lower.
No new tests, but tested locally by changing the sign.
Actually makes what the docs say should happen.

fix: caching not working for `astro:assets`

---

.changeset/sweet-icons-stare.md
packages/astro/package.json
packages/astro/src/core/errors/errors-data.ts
pnpm-lock.yaml

We have some error handling about importing Sharp, so we can make it a optionalDep so it doesn't crash the entire install when it fails to install.
Fix https://github.com/withastro/astro/issues/8375
We'll see, planning to do a preview release
N/A. I slightly updated the error message to mention you can switch to other image services though

fix: make sharp an optional dep

---

.changeset/cold-knives-peel.md
packages/integrations/react/package.json
packages/integrations/react/src/index.ts
pnpm-lock.yaml

- React Refresh is the module `@react-refresh`. Previously we were loading it as `/basepathname/@react-refresh`. Instead packages need to be loaded from the absolute root, regardless of whether a base is used or not.
- Fixes https://github.com/withastro/astro/issues/8352
- Tested in a demo project.
- Can't be tested in our integration tests due to it requiring the browser loading the module.
N/A, bug fix

Fix React dev mode using a base

---

.github/workflows/ci.yml

- Node 20 is currently broken, pinning our tests to the last working version to unblock PRs.

Temporarily pin Node 20 version in CI

---

.changeset/olive-deers-switch.md
packages/integrations/mdx/src/index.ts

What the title says, errors in MDX are very weird. The position in the error name is very creative, but not very useful for us
N/A

fix: MDX errors not having stack trace and a confusing name

---

.changeset/tame-fans-happen.md
packages/astro/src/runtime/server/render/any.ts

- Closes #8434
- Properly handles children that return `undefined`
- Seems to happen with Markdown content mainly? Not sure why.
Manually tested with user reproduction
Bug fix only

Fix `renderToFinalDestination` handling

---

.changeset/strong-colts-hang.md
packages/astro/src/cli/telemetry/index.ts

Latest version of Astro is throwing the following error on CI:
```
error   Cannot read properties of null (reading 'name')
File:
node_modules/astro/dist/cli/telemetry/index.js:5:57
Code:
4 | async function notify() {
> 5 |   const packageManager = (await whichPm(process.cwd())).name ?? "npm";
|                                                         ^
6 |   await telemetry.notify(() => {
7 |     console.log(msg.telemetryNotice(packageManager) + "\n");
8 |     return true;
Stacktrace:
TypeError: Cannot read properties of null (reading 'name')
at notify (node_modules/astro/dist/cli/telemetry/index.js:5:57)
at async runCommand (node_modules/astro/dist/cli/index.js:97:3)
at async cli (node_modules/astro/dist/cli/index.js:144:5)
```
I will add changsets if this gets approved

Fix "Cannot read properties of null" in cli/telemetry

---

.changeset/sweet-sheep-sell.md
packages/integrations/svelte/client.js

- Closes https://github.com/withastro/astro/issues/8435
- `element` variable didn't exist (whoops, another good reason to use TypeScript)
- Renamed `target` to `element` for consistency
Manually
Bug fix only

Unmount Svelte islands properly on navigation

---

.changeset/cool-jokes-unite.md
packages/integrations/react/vnode-children.js

- Fixes #8432
- We were manually creating children with a `{ children: [] }` prop, which broke void elements like `hr` and `img`.
- Turns out that React creates `props.children` on the vnode automatically, so it's already there if we need to push children onto the stack.
- Also cleaned up some `key` warnings by automatically generating a unique ID for each child.
Tested manually with the repro provided

fix(react): support void children in experimentalReactChildren

---

packages/astro/client.d.ts
packages/astro/src/@types/astro.ts
packages/astro/src/assets/types.ts
packages/astro/src/runtime/server/serialize.ts
packages/astro/src/type-utils.ts

I love `Simplify<T>`, but I'll admit I don't need 3 of it in the same code base
N/A
N/A

refactor: move type utils into a single file

---

.changeset/witty-readers-behave.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/view-transitions.test.js

L266 + L351: This fix was mainly triggered by a bug I introduced with 3.0.11: backward navigation was no longer possible when starting from a history state that was not pushed by the CSR (e.g. navigate to a #fragment on a VT page and navigate to another page from there). 
~~Other change: the handling of self links used to call pushState, so you would have that jump in the history as well. But that doesn't really work, because we would do transitions at history navigation. (in popstate it is not possible to see if we have been on the same page before, otherwise we could prevent transitions for those).~~
pushState is required for the self-link to update the browser's address bar.  So I have reintroduced it. In popstate, the navigation of self-links is now detected by negative values for …

Bugfixes for back navigation in the view transition client-side router

---

.changeset/itchy-clouds-design.md
packages/astro/src/@types/astro.ts

fix: #8474
It was commented that setting `scopedStyleStrategy` to `attribute` causes specificity increase is intentional, so the JSDoc regarding this has been updated to reflect it.
N/A (JSDoc fixes only)
N/A

chore: correct description of `attribute` option in `scopedStyleStrategy`

---

.changeset/gorgeous-dancers-divide.md
packages/astro/src/core/render/ssr-element.ts
packages/astro/src/runtime/client/hmr.ts
packages/astro/src/runtime/server/render/tags.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/integrations/deno/test/basics.test.ts
packages/integrations/node/test/prerender-404-500.test.js

- It is deprecated to add `type="text/css"` to style elements.
> Authors should not specify a [type](https://html.spec.whatwg.org/multipage/obsolete.html#attr-style-type) attribute on a [style](https://html.spec.whatwg.org/multipage/semantics.html#the-style-element) element.
> https://html.spec.whatwg.org/multipage/obsolete.html#obsolete-but-conforming-features
> ## Deprecated attributes
> `type`
> This attribute should not be provided
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#deprecated_attributes
- [Nu HTMLChecker](https://validator.w3.org/nu/) will give you a warning
- Remove the part that detects `type="text/css"`.
- packages/integrations/deno/test/basics.test.ts
- packages/integrations/node/test/prerender-404-500.test.js

Removed `<style>` with `type="text/css"` from inline output at build time

---

.changeset/polite-ravens-serve.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/wide-page.astro
packages/astro/e2e/view-transitions.test.js

While we recorded scrollY for history navigation, we ignored scrollX up to now.
Added scrollX to history state
added e2e test
n/a

Restore horizontal scroll position on history navigation (view transitions)

---

.changeset/warm-windows-occur.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/astro.config.mjs
packages/astro/e2e/fixtures/view-transitions/src/pages/one.astro
packages/astro/e2e/view-transitions.test.js

With redirects, the location had to be updated to reflect the final destination in the browsers address bar.
Redirect errors, like same origin violation, are handled as any other errors of `fetch` by full load of the requested `href` 
(as same origin policy would prevent us from accessing the target DOM)
While we are looking at the response object now, I have also grabbed the content-type for the parser.
two new e2e tests
n/a bug fix

Vt follow redirects

---

.eslintrc.cjs

- Updates our eslint settings to detect Node built-ins that accidentally make their way into our runtime code.
- Closes PLT-572
- Might catch a few issues in the future, but doesn't cover everything.
Verified locally
N/A

Disallow node builtins in runtime

---

.changeset/slow-mirrors-provide.md
packages/astro/src/assets/internal.ts
packages/astro/src/assets/services/service.ts
packages/astro/src/core/errors/dev/utils.ts
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/core/errors/overlay.ts

Users makes some understandable mistakes around using `<Image />`:
- They pass filepaths, instead of imports
- They pass the result of a non-eager `import.meta.glob`
This PR adds better documentation and error messages around these cases to better inform users on the proper way to use `<Image />`. Hopefully it'll help!
This PR also includes a small styling change to the overlay, as informed by Mark.
Tested manually the new messages, we have tests for errors otherwise already
Some of this is docs!

feat: better errors for images

---

.changeset/grumpy-seas-learn.md
packages/markdown/remark/package.json
packages/markdown/remark/src/remark-collect-images.ts
packages/markdown/remark/test/remark-collect-images.test.js
packages/markdown/remark/test/test-utils.js
pnpm-lock.yaml

Usually images in Markdown are authored like so:
```md
```
Yet they can also use an `imageReference` with a `definition`:
```md
[ref]: url
```
Both syntaxes work fine when it comes to rendering HTML, but images referenced in the second form are not collected in `remarkCollectImages()` as that only catches `image` nodes, but not `imageReference` nodes.
This PR adds a unit test for the former, and support and a unit test for the latter.
Did not measure, but the impact on performance should be minimal. Also see the note with the relevant code.
This PR contains a test for existing functionality to assert image collection, and adds a test for the new functionality.
Since I had all my images in the yet unsupported syntax, it I didn't see why my …

feat(markdown): Add support for `imageReference` paths when collecting images

---

.changeset/thin-starfishes-love.md
packages/integrations/mdx/package.json
packages/integrations/mdx/src/index.ts
packages/integrations/mdx/src/plugins.ts
packages/integrations/mdx/src/recma-inject-import-meta-env.ts
packages/integrations/mdx/src/rehype-apply-frontmatter-export.ts
packages/markdown/remark/src/frontmatter-injection.ts
packages/markdown/remark/src/index.ts
packages/markdown/remark/src/internal.ts
pnpm-lock.yaml

NOTE: this merges into `markdown-perf` branch. When https://github.com/withastro/astro/pull/8532 is merged, I'll rebase this then merge it.
- Improve markdown rendering performance by sharing the mdx processor.
- Refactor `recmaInjectImportMetaEnv` as its own file
- Refactor `rehypeApplyFrontmatterExport` as its own file
I tested it in the astro docs and there doesn't seem to be any improvements :( but this seems like a nice change overall otherwise.
Ran astro & mdx tests locally
n/a

Improve MDX rendering performance

---

.changeset/fair-teachers-protect.md
packages/astro/client.d.ts
packages/astro/content-types.template.d.ts
packages/astro/src/@types/astro.ts
packages/astro/src/assets/internal.ts
packages/astro/src/assets/types.ts

Some small type issues that crept in when we added some features to assets.
N/A

fix(assets): Fix misc types issues

---

.changeset/fluffy-dodos-rule.md
packages/integrations/vercel/src/serverless/adapter.ts

fix: Vercel serverless adapter logs too much

---

.changeset/curly-icons-watch.md
packages/integrations/node/src/nodeMiddleware.ts

- Closes #8596
Does not affect behavior, just observability.

fix(node): report render error to the terminal

---

.changeset/serious-wolves-breathe.md
packages/astro/src/core/create-vite.ts
packages/astro/src/vite-plugin-config-alias/index.ts

Fix https://github.com/withastro/astro/issues/7508
I don't really know what's happening, for some reason if we eagerly resolve ids with aliases, it affects the CSS ordering of some CSS styles injected to the HTML. Doing it later (giving other plugins first) seems to fix it and is also what the plugin used to do before I changed it. (I didn't think they were issues with it before)
Tested with the issue's repro only. I can't find a pattern that's causing the issue.
n/a. bug fix.

Fix alias plugin causing CSS ordering issue

---

.changeset/warm-turkeys-develop.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/components/InlineScript.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/inline-script-one.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/inline-script-two.astro
packages/astro/e2e/view-transitions.test.js

- Closes https://github.com/withastro/astro/issues/8466
- Closes https://github.com/withastro/astro/issues/8482
N/A, bug fix

Prevent body scripts from re-executing on navigation

---

.changeset/large-shoes-hammer.md
packages/astro/src/cli/add/index.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/events/session.ts
packages/astro/test/events.test.js
packages/telemetry/README.md

- Removes outdated/unused/broken data from the `ASTRO_CLI_SESSION_STARTED` telemetry event
- Adds a new, more generic config info base object using "is set" boolean checks
- Adds more protection with `measureX` helper functions that prevent raw user input collective with input checking, type errors, and centralized sanitization logic.
- Tests updated.
- See https://astro.build/telemetry/ for information about how Astro collects anonymous telemetry and how we use it to improve our roadmap.

telemetry: Improve config info object format

---

.changeset/curvy-owls-rest.md
packages/astro/src/core/cookies/index.ts
packages/astro/src/core/cookies/response.ts
packages/astro/src/core/middleware/callMiddleware.ts
packages/astro/test/fixtures/middleware space/src/middleware.js
packages/astro/test/fixtures/middleware space/src/pages/return-response-cookies.astro
packages/astro/test/middleware.test.js

- When middleware return `new Response` we need to attach cookies to it.
- This aligns with how components work as well, if you return a new Response from a page component the cookies that have been set via `Astro.cookies.set()` go along for the ride.
New test case added
N/A, bug fix

Ensure cookies are attached when middleware changes the Response

---

packages/astro/src/runtime/server/scripts.ts

This reverts commit 8d361169b8e487933d671ce347f0ce74922c80cc.
- This change added style tags to scripts/styles which breaks some CSP constraints.
- Fixes https://github.com/withastro/astro/issues/8618
- The thing this supposedly fixed was a user error, not Astros, so the fix is not needed.

Revert "fix: islands are not being rendered correctly (#8580)"

---

packages/astro/client.d.ts
packages/astro/package.json
packages/astro/src/@types/astro.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/i18n/index.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/src/integrations/astroFeaturesValidation.ts
packages/astro/test/units/i18n/getI18nBaseUrl.test.js

This is a first draft of the possible configuration for the upcoming i18n routing. Closes PLT-981
> [!NOTE]
> This PR is against the branch `i18n-routing`
```js
i18n: {
defaultLocale: 'en' // mandatory. This locale must be in the locales array
locales: [
'en',
'es', 
'en-US', 
'it-IT',
'pt',
'pt-BR'
],
fallback: {
/**
* The fallback system. The fallback system handles cases where certain pages 
* aren't translated yet.
* Fallback = Redirect
* In this example, if a page for `pt-BR` isn't found, Astro will:
* 1. fallback to `pt`
* 2. fallback to `en-US`
* 3. fallback to default locale
*/
'pt-BR': ['pt', 'en-US'] 
},
detectBrowswerLanguage: false
}
})
```
~~Considering the proposal, we need the presence of some runtime in order to provide enough information to …

feat(i18n): first draft of configuration

---

packages/integrations/tailwind/README.md

- Improved the manual install guide of `astrojs/tailwind` integration as requested on this issue https://github.com/withastro/docs/issues/4587
- It was manually tested

Update: Improve manual install guide of `@astrojs/tailwind` integration

---

packages/astro/src/@types/astro.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/core/routing/index.ts
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/core/routing/manifest/serialization.ts
packages/astro/src/core/routing/match.ts
packages/astro/src/vite-plugin-astro-server/devPipeline.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/dev-routing.test.js
packages/astro/test/fixtures/i18n-routing-base/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-base/package.json
packages/astro/test/fixtures/i18n-routing-base/src/pages/en/blog/[id].astro
packages/astro/test/fixtures/i18n-routing-base/src/pages/en/start.astro
packages/astro/test/fixtures/i18n-routing-base/src/pages/index.astro
packages/astro/test/fixtures/i18n-routing-base/src/pages/pt/blog/[id].astro
packages/astro/test/fixtures/i18n-routing-base/src/pages/pt/start.astro
packages/astro/test/fixtures/i18n-routing/astro.config.mjs
packages/astro/test/fixtures/i18n-routing/package.json
packages/astro/test/fixtures/i18n-routing/src/pages/en/blog/[id].astro
packages/astro/test/fixtures/i18n-routing/src/pages/en/start.astro
packages/astro/test/fixtures/i18n-routing/src/pages/index.astro
packages/astro/test/fixtures/i18n-routing/src/pages/pt/blog/[id].astro
packages/astro/test/fixtures/i18n-routing/src/pages/pt/start.astro
pnpm-lock.yaml

Depends on https://github.com/withastro/astro/pull/8607
Addresses PLT-982
This PR adds new logic to **development** to retrieve the content of the `defaultLocale` in case the page of a locale doesn't exist.
Given the following config:
```js
{
defaultLocale: 'en',
locales: ['en', 'pt']
}
```
And let's assume we have the following pages
```
/src/pages/en/welcome
/src/pages/en/first-steps
/src/pages/pt/hola
```
If we visit `/pt/first-steps`, Astro will **render the content** of the page `/src/pages/en/welcome`. URL will stay the same.
Added new test cases.
N/A for now

feat(i18n): default locale system for dev

---

.changeset/spotty-jokes-arrive.md
packages/astro/src/content/runtime.ts
packages/astro/src/core/errors/errors-data.ts

- There was a mistake in https://github.com/withastro/astro/pull/8382 that returned an integration when it should have just warned. This replaces that.
- This also deprecates the error that no longer occurs.
- Test added in https://github.com/withastro/astro/pull/8382 will still pass
N/A

Warn on empty content collections

---

.changeset/spicy-walls-wave.md
packages/astro/content-module.template.mjs
packages/astro/src/content/runtime.ts
packages/astro/test/data-collections.test.js
packages/astro/test/fixtures/data-collections/src/pages/translations/by-id.json.js

- Found this bug while working on a VT demo.
- Was expecting the lookup map to be by base id, but it is not, so instead using `createGlobLookup` like the other lookup functions do.
N/A, bug fix

fix getDataEntryById to lookup by base name

---

.changeset/spotty-dryers-exist.md
packages/integrations/deno/src/index.ts

- Fixes #8390
Could use more tests, not sure if this is the time for it.

fix(deno): do not set vite.ssr.noExternal

---

.changeset/gentle-rocks-enjoy.md
packages/astro/src/core/errors/errors-data.ts

Fixes #8665
- Fixes the error message so that it includes the image path
I did not add a test or repro, because the bug and fix seem fairly clear to me from the code.
I don't think docs need to be updated.

fix: print image path for NoImageMetadata

---

.changeset/fast-glasses-remain.md
packages/astro/src/core/build/static-build.ts
packages/astro/src/core/create-vite.ts

The `customLogger` passed was suppressing the `logLevel` set here:
https://github.com/withastro/astro/blob/9fe4b9596988dc8b498825eae266805daf4b435b/packages/astro/src/core/build/static-build.ts#L263
Hence it never kicked in. I removed the `customLogger` as it doesn't seem to be useful. I did tweak the `logLevel` handling in `static-build.ts` so the user config value is still respected.
Before:
```
> @example/framework-svelte@0.0.1 build /Users/bjorn/Work/oss/astro/examples/framework-svelte
> astro build
09:17:22 PM [content] No content directory found. Skipping type generation.
09:17:22 PM [build] output target: static
09:17:22 PM [build] Collecting build info...
09:17:22 PM [build] Completed in 95ms.
09:17:22 PM [build] Building static entrypoints...
09:17:22 PM [build] Completed in …
```

Fix logLevel passed to Vite build

---

.changeset/little-onions-relax.md
packages/astro/src/assets/build/generate.ts

- Resolves #8668 
- Fixes a build failure when using `astro:assets` and setting `outDir` to a folder outside of the project. For example `outDir: '../outside-the-project'`
- It's caused by some assets being constrained in the project folder/cwd, by using `getOutDirWithinCwd`
- `astro:assets` does not use `getOutDirWithinCwd`, so it ends up looking for the unoptimised assets at the wrong place
I wrote a slightly deeper explanation in https://github.com/withastro/astro/issues/8668#issuecomment-1735465977.
The minimal reproducible example in the issue above (https://github.com/MichailiK/astro-images-outdir-bug) was used to test this change. I don't think this would cause regressions. I believe this change just ensures that Astro is trying to obtain the unoptimised asset from the correct …

Fix assets not getting optimized when `outDir` is outside the CWD

---

.github/workflows/ci.yml

- CI - Node 18.18 breaks ~~playwright~~ (not just playwright) on windows.
- Does not affect behavior.

chore(ci): pin CI Node version to 18.17.1

---

.changeset/wild-bees-sneeze.md
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/custom-404-implicit-rerouting.test.js
packages/astro/test/fixtures/custom-404-loop-case-1/astro.config.mjs
packages/astro/test/fixtures/custom-404-loop-case-1/package.json
packages/astro/test/fixtures/custom-404-loop-case-1/src/pages/404.astro
packages/astro/test/fixtures/custom-404-loop-case-1/src/pages/index.astro
packages/astro/test/fixtures/custom-404-loop-case-2/astro.config.mjs
packages/astro/test/fixtures/custom-404-loop-case-2/package.json
packages/astro/test/fixtures/custom-404-loop-case-2/src/pages/404.astro
packages/astro/test/fixtures/custom-404-loop-case-2/src/pages/index.astro
packages/astro/test/fixtures/custom-404-loop-case-3/astro.config.mjs
packages/astro/test/fixtures/custom-404-loop-case-3/package.json
packages/astro/test/fixtures/custom-404-loop-case-3/src/middleware.js
packages/astro/test/fixtures/custom-404-loop-case-3/src/pages/404.astro
packages/astro/test/fixtures/custom-404-loop-case-3/src/pages/index.astro
packages/astro/test/fixtures/custom-404-loop-case-4/astro.config.mjs
packages/astro/test/fixtures/custom-404-loop-case-4/package.json
packages/astro/test/fixtures/custom-404-loop-case-4/src/middleware.js
packages/astro/test/fixtures/custom-404-loop-case-4/src/pages/404.astro
packages/astro/test/fixtures/custom-404-loop-case-4/src/pages/index.astro
pnpm-lock.yaml

- Fixes closed issue #8257
- The issue has to do with implicit rerouting which will be deprecated and replaced with an [explicit API](https://github.com/withastro/roadmap/discussions/681) but that may take a while.
Added 4 cases based on what I saw people encounter in the issue and on discord.

fix(rerouting): check that the new route is different

---

packages/astro/e2e/fixtures/view-transitions/public/one.css
packages/astro/e2e/fixtures/view-transitions/public/styles.css
packages/astro/e2e/fixtures/view-transitions/src/components/Layout.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/one.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/transitions/router.ts

Over time, the preload code became a noop in virtually all relevant cases. 
If the current page had a any stylesheet link, no stylesheets were preloaded.
Fixed selector.
Bug fixing. Deliberately no changeset
Adaptation of the existing test for testing preloads
Added stylesheet link in Layout to make fixture a bit more realistic
N/A: bugfix
sorry Sarah

Fix preloading stylesheets in view transitions

---

.changeset/hot-readers-live.md
packages/integrations/cloudflare/README.md
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/src/utils/parser.ts
packages/integrations/cloudflare/test/cf.test.js
packages/integrations/cloudflare/test/fixtures/cf/src/pages/do.astro
packages/integrations/cloudflare/test/fixtures/cf/wrangler.toml

- **new:** local mocking for durable objects
- added tests for durable objects

feat(cloudflare): add local mocking for DO bindings

---

.changeset/hot-readers-live.md
.changeset/yellow-kiwis-pretend.md
packages/integrations/cloudflare/README.md
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/src/utils/parser.ts
packages/integrations/cloudflare/test/cf.test.js
packages/integrations/cloudflare/test/fixtures/cf/src/pages/caches.astro
packages/integrations/cloudflare/test/fixtures/cf/src/pages/do.astro
packages/integrations/cloudflare/test/fixtures/cf/src/pages/index.astro
packages/integrations/cloudflare/test/fixtures/cf/wrangler.toml

- **new:** local mocking for caches
- added tests for caches

feat(cloudflare): add local mocking for Caches bindings

---

.changeset/funny-cobras-accept.md
.changeset/hot-readers-live.md
.changeset/hungry-mails-boil.md
.changeset/khaki-toes-exercise.md
.changeset/yellow-kiwis-pretend.md
packages/integrations/cloudflare/.gitignore
packages/integrations/cloudflare/README.md
packages/integrations/cloudflare/package.json
packages/integrations/cloudflare/src/index.ts
packages/integrations/cloudflare/src/utils/parser.ts
packages/integrations/cloudflare/test/cf.test.js
packages/integrations/cloudflare/test/fixtures/cf/src/pages/caches.astro
packages/integrations/cloudflare/test/fixtures/cf/src/pages/d1.astro
packages/integrations/cloudflare/test/fixtures/cf/src/pages/do.astro
packages/integrations/cloudflare/test/fixtures/cf/src/pages/index.astro
packages/integrations/cloudflare/test/fixtures/cf/src/pages/kv.astro
packages/integrations/cloudflare/test/fixtures/cf/src/pages/r2.astro
packages/integrations/cloudflare/test/fixtures/cf/wrangler.toml
pnpm-lock.yaml

- **new:** local mocking for D1 bindings
- added tests for D1

feat(cloudflare): add local mocking for D1 bindings

---

.changeset/poor-frogs-melt.md
packages/astro/src/content/vite-plugin-content-assets.ts
packages/astro/src/vite-plugin-astro-server/css.ts
packages/astro/src/vite-plugin-astro-server/route.ts

Fix https://github.com/withastro/astro/issues/8720
The main fix is for this specific line: https://github.com/withastro/astro/blob/22fae5211ac77caab1b3227a64231bc2540bcbef/packages/astro/src/vite-plugin-astro-server/route.ts#L314
I changed the `url` to an `id`, thinking it doesn't affect it, but I missed that it did! This PR makes `url` an actual URL. But I also need the `id` for `data-vite-dev-id` below, so I refactored `getStylesForURL` to achieve that. The rest of the changes are the refactors for it.
Don't have a Windows machine to test this, but I spotted this is the main unintended change from #8706
n/a. bug fix.

Fix CSS styles on windows

---

.changeset/red-masks-drop.md
packages/astro/src/content/vite-plugin-content-imports.ts
packages/astro/src/core/module-loader/vite.ts

Fix https://github.com/withastro/astro/issues/7835
Couple issues fixed:
1. Handle server `ERR_CLOSED_SERVER` error if accessing the module graph after the server has been closed. Ideally Vite shouldn't ever expose this, but there isn't a nice solution without removing that safeguard.
2. When `tsconfig.json` updates, the server restarts and reloads at the same time, causing the page to be blank and doesn't show the new page after server is ready again. I did a hack to prevent the reload, as the restart also initiates a reload by itself when it's ready.
The reload is done by Vite by default so there's not much we can do to prevent it in the first place.
n/a. bug fix.

Fix `tsconfig.json` update causing the server to crash

---

.changeset/tricky-otters-cross.md
packages/integrations/partytown/src/index.ts

feat: expose partytown types (close #8723)

---

.changeset/witty-fishes-heal.md
packages/astro/src/cli/info/index.ts

- On Windows terminals, `astro info`'s copy to clipboard feature was copying the entire JSON-encoded string rather than the unencoded string as expected.
- With some help from @lilnasy, we debugged this and landed on passing the input directly to `clip`.
N/A

Improve `astro info` compatability

---

packages/astro/src/@types/astro.ts

- Minor fix on a sample code for the Markdown Rehype plugin docs, as referenced in [this issue](https://github.com/withastro/docs/issues/4549).
- Closes https://github.com/withastro/docs/issues/4549
Tested manually to verify the sample code shows the updated plugin:
I made this PR as directed from [the issue from the Astro Docs repo](https://github.com/withastro/docs/issues/4549#issuecomment-1722483590). I simply used the same example plugin already used in [the Markdown & MDX docs page](https://docs.astro.build/en/guides/markdown-content/#markdown-plugins).

Fix markdown rehype plugin example

---

.changeset/cuddly-vans-reply.md
packages/markdown/remark/src/remark-shiki.ts
packages/markdown/remark/test/shiki.js

I recently ran my page through the W3C validator and it showed me a bunch of errors and warnings about `is:raw` being not allowed. Afaik `is:raw` is an Astro specific directive that should now appear on the static page output.
The raw-attribute appears only in the Shiki highlighted syntax.
To reproduce it, you can use this template https://stackblitz.com/github/withastro/astro/tree/latest/examples/with-markdown-shiki
I removed the part of the `shiki` plugin that adds the `is:raw` to the `pre`-tags. The fact that `is:raw` is in the HTML output implies that `is:raw` or a similar mechanic is already used higher up the chain.
I added a Mocha test to verify the fix.
The attribute is hidden from the user and only visible when inspecting the page HTML. Browsers seem to ignore it and it only …

Fixes: Shiki syntax highlighting adds is:raw attribute to the HTML output

---

.changeset/tasty-meals-buy.md
packages/astro/src/core/build/plugins/plugin-css.ts

fix https://github.com/withastro/astro/issues/8567
Fixes 2 issues:
1. Fix Vite preloading CSS references by updating `importedCss`.
2. CSS files inlined to any pages should not be deleted.
I'm actually unsure if there's a bug in no2, where in the `css-dangling-references` fixture, the CSS is not inlined/duplicated to both the pages.
The existing tests (especially `css-dangling-references`) should pass
n/a. bug fix.

Remove unused CSS output files when inlined

---

.changeset/fair-otters-worry.md
packages/astro/src/runtime/server/hydration.ts

- Closes #8746
- Improves error message when rendering a dynamic component is attempted
- Our old error was likely an old holdover from before we had a proper error system and docs, and we already had an Astro error for this case!
- This PR just replaces our old, unhelpful error with a proper `AstroError`
Manually confirmed that this worked
No changes to the error data, just referencing an existing error.

Improve error message for dynamic component usage

---

.github/workflows/release.yml
packages/create-astro/package.json

Our packages failed to publish because there isn't the right permissions to generate a provenance.
I also added provenance config to create-astro, which was missing.
Copied from Vite's setup.
n/a

Fix provenance release

---

.changeset/great-bears-watch.md
packages/astro/e2e/view-transitions.test.js
packages/astro/src/transitions/router.ts

Reverts #8472 
For discussion how to fix the original issue #8114 see #8745
Closes #8604
Closes #8764 
Closes #8674
Manually tested with code from #8674, #8764, #8604
Set e2e test for #8114/#8472 to `skip`
n/a, bug fix

Revert fix #8472

---

.changeset/young-taxis-battle.md
packages/astro/src/assets/internal.ts

This pull request adds the missing `await` to properly use values returned by `getHTMLAttribute` in image services. It fixes an issue where HTML attributes do not render if getHTMLAttributes in an image service returns a Promise.
Minimum repro for this issue: [StackBlitz](https://stackblitz.com/edit/repro-astro-image-service-async-gethtmlattributes?file=src%2Fimage-service-async.ts) (You can see that the custom HTML attributes are not rendered in the HTML if `getHTMLAttribute` returns a Promise instead a plain object)
Definition for `getHTMLAttribute`:
https://github.com/withastro/astro/blob/30de324361bc261956eb9fc08fe60a82ff602a9b/packages/astro/src/assets/services/service.ts#L41-L50
No tests were added as this is a one-line fix. It should have no impact if `getHTMLAttributes` returns a …

fix(assets): add the missing `await` to getHTMLAttributes

---

.changeset/sharp-insects-yawn.md
packages/astro/src/core/build/css-asset-name.ts
packages/astro/src/core/build/plugins/plugin-css.ts

fix https://github.com/withastro/astro/issues/7469
This PR implements a lame algorithm to pick a chunk base name that is not confusing. Simply by avoiding the `404` and `500` names if there's others available.
I couldn't quite figure out a better naming-scheme without overcomplicating it. I also tried resorting this to Rollup, but there's edgecases where that's not possible. Our CSS handling that links CSS to HTML pages are very ingrained throughout the codebase. Also in practice, Rollup would also pick the confusing name otherwise.
n/a.

Make CSS chunk names less confusing

---

packages/astro/client.d.ts
packages/astro/package.json
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/util.ts
packages/astro/src/core/create-vite.ts
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/i18n/index.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/test/units/i18n/getI18nBaseUrl.test.js
packages/create-astro/src/index.ts
pnpm-lock.yaml

This PR does a cleanup of the virtual module and starts exposing function that could be used inside an application to retrieve:
- the base URL given a locale. It throws an error if a locale doesn't exist. Locales are normalized*
- the list of base URLs with their locales. Locales are normalized*
*normalized locales have the underscore `_` replaced with a das `-`. Their name is then transformed to be lower cased.

feat(i18n): better virtual module functions

---

.changeset/seven-seas-hide.md
packages/astro/e2e/fixtures/view-transitions/src/components/listener-layout.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/listener-one.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/listener-two.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/transitions/router.ts

Reading `window.scrollY` after replacing the body's DOM triggered additional CSS transitions on elements during swap()
Swap() should be atomic with respect to page renders. This is important so users can restore attributes and classes in astro:after-swap.  Intermediate state should not be observable.
Closes #8711
Added e2e test
n/a bug fix

Fix flickering during view transitions

---

.changeset/large-clouds-sip.md
packages/astro/astro.js

- Fix for #8470
- Issue still affects Vite.
😶‍🌫️

fix(windows): ensure drive letter is uppercase

---

.changeset/heavy-elephants-tan.md
packages/integrations/cloudflare/README.md
packages/integrations/cloudflare/src/index.ts

- Allow the use of the runtime library `cloudflare:sockets` without throwing a build error by adding it to the external list.
This update is needed for merge in order to further work on Postgres.js to allow for SQL socket connections for the CF tcp connec() api.
Try to reference cloudflare:sockets in an import.
https://blog.cloudflare.com/workers-tcp-socket-api-connect-databases/

fix(cloudflare): support for 'cloudflare:*' imports

---

.changeset/unlucky-avocados-brake.md
packages/integrations/cloudflare/src/entrypoints/server.advanced.ts
packages/integrations/cloudflare/src/entrypoints/server.directory.ts

- Add `CacheStorage` type from [@cloudflare/workers-types](https://www.npmjs.com/package/@cloudflare/workers-types), to override default `dom.d.ts` cache types, which do not match.
Typechange only, types compile correctly.
This update clarifies types for Runtime Cache, which afaict isn't documented.

fix(cloudflare): runtime types for Cloudflare caches
