withastro/astro

.changeset/forty-singers-ring.md
packages/astro/e2e/fixtures/view-transitions/src/components/ClickToNavigate.jsx
packages/astro/e2e/fixtures/view-transitions/src/pages/client-load.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/transitions/router.ts

- Prevents import side-effects from running during SSR.
- Makes `navigate()` do nothing on the server.
_Pending_.
There should be a note about framework usage somewhere. _Pending_.

fix(transitions router): no-op on the server

---

.changeset/tame-hairs-cheer.md
packages/astro/package.json
packages/astro/tsconfig.json
pnpm-lock.yaml

- Removes [network-information-types](https://github.com/lacolaco/network-information-types#network-information-types) package as it's no longer maintained and Typescript supports Network Information API natively.
N/A
N/A

Remove network-information-types

---

.changeset/lemon-boats-bake.md
packages/astro/components/Code.astro
packages/astro/components/shiki.js
packages/astro/src/core/errors/dev/vite.ts
packages/astro/src/core/errors/overlay.ts
packages/astro/src/core/shiki.ts

My bad! The error overlay syntax highlighting was broken. I wasn't using the code replacements to make the it work for the overlay, since it calls shiki/ji directly.
Now:
Manually tested in the examples repo
n/a. bug fix.

Fix error overlay syntax highlighting

---

.changeset/red-socks-peel.md
packages/astro/package.json
pnpm-lock.yaml

3.0.0 is identical to 3.0.0-next.9, this allows astro users to update tsconfck more easily.
no tests added because this is just updating a dependency version where both versions have identical code (and i'm not aware of any tests that cover the use of tsconfck in astro)

chore(deps): unpin tsconfck and use 3.0.0 release

---

.changeset/quiet-readers-shop.md
packages/integrations/lit/package.json
pnpm-lock.yaml

- Fixes #8825
Existing tests should pass. I would've expected them to be failing but maybe the lockfile kept CI passing.

fix(lit): pin last lit 2.x compatible versions

---

.changeset/dull-bikes-decide.md
packages/astro/components/Picture.astro
packages/astro/src/assets/services/service.ts
packages/astro/src/core/errors/errors-data.ts
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image/src/pages/picturecomponent.astro

What the title says.
This PR also adds an error message when converting from SVGs to raster formats because it's easier to do by accident on the Picture component
Added a test
N/A apart from the new error

fix(assets): Fallback format not being taken into account properly

---

.changeset/brown-pumpkins-clean.md
.changeset/serious-news-yell.md
packages/astro/components/Picture.astro
packages/astro/package.json
packages/astro/src/assets/services/service.ts
packages/astro/src/assets/utils/transformToPath.ts
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image/src/pages/srcset.astro
pnpm-lock.yaml

Continuation of https://github.com/withastro/astro/pull/8819
This PR also reworks completely how we do the transforms for `srcset`, putting special care into avoiding regenerating images when unnecessary. It's possible that there's still some edge cases where it doesn't work, nonetheless as far as I could tell, it does work!
This also fixes https://github.com/withastro/astro/issues/8839, since it's in the same area.
Added tests!
N/A

fix: remote srcset images not being resized and deduplication not working in certain cases

---

.changeset/heavy-lies-cover.md
packages/astro/src/assets/endpoint/node.ts

fix: _image endpoint returning a 404 for local images

---

.changeset/funny-deers-report.md
packages/integrations/sitemap/src/index.ts

This changes the CLI output from 
`@astrojs/sitemap: 'sitemap-index.xml' is created` to
`@astrojs/sitemap: 'sitemap-index.xml' created at '{OUTPUT DIRECTORY}'`
The CLI output isn't tested anywhere (as far as I could tell).
The CLI output isn't mentioned in the docs (as far as I could tell) so there's nothing that needs updating.

Added OUTPUT dir to sitemap build command

---

packages/astro/src/core/app/index.ts
packages/astro/src/core/app/types.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/build/plugins/plugin-middleware.ts
packages/astro/src/core/build/static-build.ts
packages/astro/src/core/build/util.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/core/create-vite.ts
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/i18n/index.ts
packages/astro/src/i18n/middleware.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/i18-routing.test.js

This PR wires the i18n middleware in the SSR system.
To achieve that, I had to update the `SSRManifest` with the information needed to handle the fallback. Considering the fact that `SSRManifest` is used in all three pipelines (DEV, SSG and SSR), the function `createI18nMiddleware` now accepts a `SSRManifest['i18n']` type.
Ultimately, I didn't use any Vite plugin; it wasn't needed.
I added new tests. I removed those test cases that use `getStaticPaths`, because they doesn't work in SSR.
N/A for now

feat(i18n): fallback system in SSR

---

.changeset/fresh-lizards-whisper.md
packages/astro/src/core/build/static-build.ts
packages/astro/src/core/create-vite.ts

- `configFile: false` added to specifically tell Vite not to automatically find, read, and merge config from `vite.config.js`. which could conflict with Astro's vite config ([docs](https://vitejs.dev/guide/api-javascript.html#inlineconfig))
fixes https://github.com/withastro/astro/issues/8702
N/A
N/A. Docs already said in the way to modify Vite behavior via `astro.config.mjs`

fix(astro): build config from astro conflict with vite.config.js

---

packages/integrations/sitemap/README.md

- This slightly modifies the language in the docs to clarify that `/dist` is the default output, but generated files may live elsewhere (a confusion that cost me a silly amount of time trying to debug).
- I considered adding a note that the Vercel adapter will output to `.vercel/output` and that other adapters may output code to a place other than `/dist`, but this felt too in-the-weeds. If this is helpful to call out, happy to make edits!
- Resolves https://github.com/withastro/docs/issues/4919 (~~Not sure if Github will auto-close this PR since it's in a separate repo, but the sitemap docs get auto-generated from this README~~)
- Also pairs with @silent1mezzo's improvements to the CLI text: https://github.com/withastro/astro/pull/8824
Docs-only change.

fix(docs): Update `@astrojs/sitemap` readme to clarify build output location

---

.changeset/seven-brooms-trade.md
packages/astro/e2e/fixtures/vue-component/src/components/State.vue
packages/astro/e2e/fixtures/vue-component/src/pages/index.astro
packages/astro/e2e/vue-component.test.js
packages/integrations/vue/client.js

Fix https://github.com/withastro/astro/issues/8071
When the `Component` is HMR-ed, `Component` has new values within itself. So when we render the Vue island, we should access `Component` dynamically so it doesn't render old values and caused hydration errors.
Added new e2e hmr test
n/a

Fix Vue HMR for script tags

---

packages/astro/src/core/app/types.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/i18n/middleware.ts
packages/astro/test/fixtures/i18n-routing-fallback/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-fallback/src/pages/en/continue.astro
packages/astro/test/fixtures/i18n-routing-fallback/src/pages/en/end.astro
packages/astro/test/fixtures/i18n-routing-fallback/src/pages/pt/continue.astro
packages/astro/test/fixtures/i18n-routing-fallback/src/pages/pt_BR/start.astro
packages/astro/test/i18-routing.test.js
packages/astro/test/units/config/config-validate.test.js
pnpm-lock.yaml

This PR makes the fallback system way simpler. The initial configuration had the idea where a user could define the order of the fallbacks. In the below example, `pt_BR` will fallback to `pt` and if `pt` doesn't have a translation, it will fallback to `en`. 
```js
const i18n = {
fallback: {
pt_BR: ['pt', 'en']
}
}
```
Nuxt inspired this, although in their latest version, they removed this configuration. Also, other vendors have a simple system. 
Also, this complex fallback system would only work if we create a middleware function for each member in the array, and this is overkill.
The new configuration is like this instead:
```js
const i18n = {
fallback: {
pt_BR: 'pt'
}
}
```
I updated the test with more test cases.

refactor(i18n): simpler fallback system

---

packages/astro/test/test-utils.js

Silent the build logs during test. They weren't shown before, but was surfaced since https://github.com/withastro/astro/pull/8678
Ran test locally to confirm
n/a.

Set vite logLevel silent for test

---

.changeset/two-lamps-tell.md
packages/astro/src/vite-plugin-astro/hmr.ts

- #8831
- Uses fileURLToPath and nozmalizes the path between OSs
Tested by pointing the `@example/basics` astro version to the local one (`workspace:*`), only on Windows.
No change required

fix(astro): terminal HMR path (close #8831)

---

packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/test/astro-css-bundling.test.js
packages/astro/test/ssr-manifest.test.js
packages/astro/test/ssr-split-manifest.test.js

Handle Vite 5 and Rollup 4 where `emitFile` now returns base64url hash with `-` replaced as `$`, and file name `[hash]` replaced with base64url hash too.
The former hash can be matched with `[\w$]{8}` while the latter `[\w-]{8}`.
Rollup 4 migration guide: https://rollupjs.org/migration/#general-changes
> Otherwise, an obvious change is that Rollup now uses url-safe base64 hashes in file names instead of the older base16 hashes. This provides more hash safety but means that hash length is now limited to at most 22 characters for technical reasons.
NOTE: These new hash regex covers a wider range of characters, so it should be backwards compatible too.
Ran tests locally.
n/a

Handle Rollup 4 hash change

---

.changeset/great-queens-yawn.md
packages/astro/src/cli/add/index.ts

- force `NODE_ENV=development` on installation command run when using `astro add` command to prevent installation to remove `devDependencies`
no real way to test
no need
fix #8037

fix(cli): prevent production install on add cmd

---

.github/workflows/snapshot-release.yml

- Updates our snapshot release workflow
- Moves away from the deprecated `::set-output` to the new `>> $GITHUB_OUTPUT` method for passing values between job steps.
- Hopefully fixes some formatting in the response message (but this is difficult to test)
Not sure how I can test this, tbh...
N/A

[ci] Update `!preview` response

---

packages/integrations/vercel/README.md

- Fixes a small typo in the import line for the code block explaining how to use Vercel serverless with Astro middleware.
- The import line needs to import `vercel` from `'@astrojs/vercel/serverless'`. Otherwise, astro throws an "Unable to load your Astro config" error due to being unable to resolve the "@astrojs/vercel" package.
- No testing performed as there are no changes to Astro packages, just to docs.
- Just a fix to docs, so no additional documentation needed (but other translations may also need to be fixed!)

Update README.md: Fix incorrect import in example code

---

.changeset/lazy-actors-enjoy.md
packages/integrations/vercel/README.md
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/test/fixtures/max-duration/astro.config.mjs
packages/integrations/vercel/test/fixtures/max-duration/package.json
packages/integrations/vercel/test/fixtures/max-duration/src/pages/one.astro
packages/integrations/vercel/test/fixtures/max-duration/src/pages/two.astro
packages/integrations/vercel/test/max-duration.test.js
pnpm-lock.yaml

- Closes #8829
- Introduces an adapter configuration to allow longer than normal function timeouts.
Added a fixture and test that `.vc-config.json` has the expected field.
Added a section to the README.

feat(vercel): maxDuration config

---

.changeset/silent-goats-invent.md
packages/astro/src/runtime/server/render/head.ts
packages/astro/test/0-css.test.js
packages/astro/test/fixtures/0-css/src/components/ModuleOrdering.jsx
packages/astro/test/fixtures/0-css/src/components/ModuleOrdering.module.css
packages/astro/test/fixtures/0-css/src/pages/index.astro
packages/astro/test/fixtures/0-css/src/styles/default.css

Fix https://github.com/withastro/astro/issues/8558
Fix CSS modules ordering by rendering styles first before links. This is needed because in `getStylesForURL`, CSS modules are passed as links (`importedCssUrls`) (CSS module has no `ssrModule.default`):
https://github.com/withastro/astro/blob/5ea6ee0ed494c792a4c94928a83c5c85b9b6ac32/packages/astro/src/vite-plugin-astro-server/css.ts#L34-L46
We then put the CSS module links in `links`, and the other styles (global styles) in `styles`.
https://github.com/withastro/astro/blob/5ea6ee0ed494c792a4c94928a83c5c85b9b6ac32/packages/astro/src/vite-plugin-astro-server/route.ts#L301-L330
Ultimately this creates a tricky situation where we shouldn't actually group head elements this way. Scripts/styles/links should all be in a single array but that …

Fix CSS modules ordering

---

.changeset/hip-rockets-glow.md
packages/integrations/markdoc/README.md
packages/integrations/markdoc/src/options.ts
packages/integrations/markdoc/src/tokenizer.ts
packages/integrations/markdoc/test/fixtures/render-with-indented-components/astro.config.mjs
packages/integrations/markdoc/test/fixtures/render-with-indented-components/markdoc.config.ts
packages/integrations/markdoc/test/fixtures/render-with-indented-components/package.json
packages/integrations/markdoc/test/fixtures/render-with-indented-components/src/components/Code.astro
packages/integrations/markdoc/test/fixtures/render-with-indented-components/src/components/CustomMarquee.astro
packages/integrations/markdoc/test/fixtures/render-with-indented-components/src/content/blog/with-indented-components.mdoc
packages/integrations/markdoc/test/fixtures/render-with-indented-components/src/pages/index.astro
packages/integrations/markdoc/test/render.test.js
pnpm-lock.yaml

- Added allowIndentation to the markdoc integration options which allows indentation of markdoc tags for better readability.
- Updated README to reflect changes
There is an existing `allowHTML` integration option which also enables allowIndentation so this change does not introduce new functionality. This was added in https://github.com/withastro/astro/pull/7597
It's nice to enable better readability without also enabling raw HTML in markdoc files. I think allowIndentation should be enabled by default once it comes out of it's experimental phase.
- Added unit tests similar to those that test the `allowHTML` integration option.
- Tested with a local astro project using the markdoc integration. No issues encountered. 
This change requires an update to the …

feat(markdoc): allowIndentation integration option

---

packages/astro/e2e/fixtures/view-transitions/src/components/listener-layout.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/transitions/router.ts

Chores: View transition router
- Simplification
- Documentation
- Improved comprehensibility and maintainability
No changes in functionality
Small changes for less flaky executions
n/a not even a change set ;-)

Chores: Tidying up the view transition router

---

.changeset/real-dryers-destroy.md
packages/integrations/react/client.js
packages/integrations/react/server.js
packages/integrations/react/test/fixtures/react-component/src/components/WithChildren.jsx
packages/integrations/react/test/fixtures/react-component/src/pages/children.astro
packages/integrations/react/test/react-component.test.js
packages/integrations/react/vnode-children.js

- Turns element children into React components with `experimentalReactChildren`
- This fixes hydration.
- Test added
N/A

Fix client hydration in experimentalReactChildren

---

.changeset/slow-cheetahs-marry.md
packages/integrations/mdx/README.md

This replaces the the old recommendation to mark MDX files as markdown with the recommendation to use the official MDX extension. MDX supports various constructs that markdown doesn’t, so that leads to bad syntax highlighting.
This is a documentation-only change.
This is a documentation-only change.

Recommend the VS Code MDX extension

---

.changeset/soft-berries-prove.md
packages/create-astro/src/actions/template.ts

- Skip cleanup if the path is `.`, `./` or starts with `../`.
- Catches and ignore errors calling `rmdirSync` after template download failed.
This ensures the original "download failed" error is thrown and displayed to the user instead of a "rmdir failed" error which could be confusing.
Closes #8785 
No new tests were added.
The changed function is not covered by existing tests.
No docs changes were made.
I don't think this behavior detail is worth documenting on `docs.astro.build`.

misc(create): Ignore errors removing directory after download failed

---

.changeset/tame-wasps-exercise.md
packages/create-astro/src/actions/typescript.ts
packages/create-astro/test/fixtures/not-empty/package.json
packages/create-astro/test/fixtures/not-empty/tsconfig.json
packages/create-astro/test/typescript.test.js
packages/create-astro/test/utils.js

- There was a regression introduced in https://github.com/withastro/astro/pull/8853 that replaced a template's existing `scripts` with just the new `build` script
- This PR fixes that case by mutating the `packageJsonData.scripts.build` instead of creating a new object.
- Changeset added!
Test added. Fixture was updated to verify that this case is handled.
N/A, bug fix

fix(create-astro): respect existing `package.json#scripts`

---

packages/astro/client.d.ts
packages/astro/src/i18n/index.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/test/units/i18n/astro_i18n.js

This PR changes the APIs of the virtual module after some discussion in the [RFC](https://github.com/withastro/roadmap/pull/734). 
This PR changes the signature of the PRs, by passing a locale mandatory argument, and then a second argument: an object with a set of options.
This type of signature will allow us to add more options in the future.
The reason why this change was needed is that users might need:
- to add a path after the locale, without bothering with trailing slashes
- to add a path before the locale, without bothering with trailing slashes 
- opt-in the normalisation of the locale, not always needed
I updated the tests
This time I need feedback on the APIs, especially the documentation. I will update the RFC accordingly later

feat(i18n): better APIs

---

.changeset/witty-waves-rhyme.md
packages/astro/src/integrations/index.ts

- for context see messages after: https://discord.com/channels/830184174198718474/845430950191038464/1165031078722011238
- I've added PRs to the two known edge runtimes:
- https://github.com/denoland/deno-astro-adapter/pull/7
- https://github.com/withastro/adapters/pull/33

fix noop overwrite image service regression

---

packages/astro/client.d.ts
packages/astro/src/i18n/vite-plugin-i18n.ts

Applies changes to the virtual module after Chris's feedback in #8908 
> While there is the edge case of / where path can be omitted, most uses will provide a path (or will provide one programmatically, so may provide one even when the variable’s value is '/' or ''). That makes requiring { path: ... } feel a bit fiddly.
Current tests should pass
/cc @withastro/maintainers-docs for feedback! 
I updated the documentation of the APIs

refactor(i18n): changes (again) the signature of the APIs after feedback

---

packages/astro/CHANGELOG.md

- Updates Astro's changelog for 3.4!
- The page partials links was broken. Now it's not.
N/A
N/A

Update page partials link in CHANGELOG

---

.changeset/violet-ants-bow.md
packages/astro/src/runtime/client/dev-overlay/overlay.ts
packages/astro/src/runtime/client/dev-overlay/plugins/astro.ts
packages/astro/src/runtime/client/dev-overlay/plugins/audit.ts
packages/astro/src/runtime/client/dev-overlay/plugins/utils/highlight.ts
packages/astro/src/runtime/client/dev-overlay/plugins/xray.ts

This PR renames various dev overlay UI Toolkit components to fix a name discrepancy between the code and the docs.
For example, the docs mention [`astro-dev-overlay-window`](https://docs.astro.build/en/reference/dev-overlay-plugin-reference/#astro-dev-overlay-window) but the component was registered as `astro-overlay-window`. After checking with @Princesseuh [on Discord](https://discord.com/channels/830184174198718474/845430950191038464/1167141643305091102), the `-dev` portion of the name is desired.
- I tested manually by running the React example (after enabling the experimental feature and adding an image element with no `alt` attribute too).
- I searched all references of `astro-overlay-` in the codebase and no results were found.
- I'm …

Fix dev overlay UI Toolkit component names

---

.changeset/swift-suits-drum.md
packages/integrations/vue/server.js
packages/integrations/vue/test/basics.test.js
packages/integrations/vue/test/fixtures/basics/astro.config.mjs
packages/integrations/vue/test/fixtures/basics/package.json
packages/integrations/vue/test/fixtures/basics/src/components/Foo.vue
packages/integrations/vue/test/fixtures/basics/src/components/Parent.astro
packages/integrations/vue/test/fixtures/basics/src/pages/index.astro
pnpm-lock.yaml

- Ignore the `slot` prop in Vue components
- Fixes https://github.com/withastro/astro/issues/8921
N/A, bug fix

Prevent passing slot names as props

---

packages/astro-rss/README.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/errors/errors-data.ts

Some headings on our SSR page in docs either have changed or will change, making some existing anchor links out of date. 
This simply removes the specific anchor link and just points links to the page.  If more specific links are appropriate after the page has been refreshed, I'll come back and add new ones back in.
No tests, just docs.
Just some docs link updates!

[docs] remove outdated anchor links

---

.changeset/young-avocados-wink.md
packages/create-astro/src/actions/typescript.ts

To fix the installation issue on TypeScript with yarn since v4.4.0, added the following changes:
- Use the `add` subcommand to add dependencies
- While `npm` and `pnpm` support both `install` and `add` for adding dependencies, `yarn` requires to use `add` to do it.
- Fixed a minor typo
- Add .changelog
<details><summary>output from `yarn create astro foo --template minimal --install --git --typescript strict`</summary>
<p>
```
$ yarn create astro foo --template minimal --install --git --typescript strict
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-astro@4.4.1" with binaries:
- create-astro
[########################################] 40/40
astro   Launch …
```

fix(create-astro): TypeScript installation failure with yarn

---

examples/blog/.vscode/extensions.json

Add the `unifiedjs.vscode-mdx` VSCode extension to recommendations in  the blog example.
This was requested as feedback from #8897.
N/A
This change kind of **is** documentation.

Recommend the VSCode MDX extension in blog example

---

examples/component/.gitignore

Added `.gitignore` to the component example. Actual content is copied from [blog example](https://github.com/withastro/astro/blob/46d3043a3f41a826061c79241d54ecbd106e4ddd/examples/blog/.gitignore).
N/A
No updates to docs required as it's just adding `.gitignore` to the component example

Add .gitignore to component example

---

packages/astro/src/transitions/router.ts

Three changes:
1. Copy and paste styles, not cut and paste: This is really a bug, ~~although no one has complained yet~~. Moving the styles from the current document to the newDocument deletes them from the current document, which is visible in view transitions. Cloning helps! Closes #8946
2. Don't load from the target URL, but load the actual contents of newDocument to simulate loading with an empty module loader: This is to prepare for the new API events where interceptors might transform newDocument after it is loaded.
3. Silence the iframe's console to reduce the observable impact of behind-the-scenes loading: This actually closes #8944  
Existing e2e tests
n/a bugfix

Three small improvements for handling client-only in view transitions

---

.changeset/sweet-nails-dream.md
packages/astro/components/viewtransitions.css
packages/astro/src/transitions/router.ts

- Moves the router announcer styles to a class name
- Closes #8937
- This prevents issues with some CSP policies.
N/A
N/A

Move VT route announcer styles to a class

---

.changeset/healthy-hornets-kiss.md
packages/astro/src/@types/astro.ts
packages/astro/src/runtime/client/dev-overlay/entrypoint.ts
packages/astro/src/runtime/client/dev-overlay/overlay.ts
packages/astro/src/runtime/client/dev-overlay/plugins/astro.ts
packages/astro/src/runtime/client/dev-overlay/plugins/audit.ts
packages/astro/src/runtime/client/dev-overlay/plugins/utils/highlight.ts
packages/astro/src/runtime/client/dev-overlay/plugins/xray.ts
packages/astro/src/runtime/client/dev-overlay/ui-library/tooltip.ts
packages/astro/src/vite-plugin-astro-server/route.ts

The diff looks really messy, but to summarize the changes here:
- The dev overlay web component has been moved to its own file, so the entrypoint that's being imported in the browser is just "create overlay, give it the plugins, add overlay to DOM". Additionally, this allow importing the type of the dev overlay element.
- This refactor allowed much easier support for view transitions, so I did it
Will update docs with any relevant changes

refactor: dev overlay to make it easier to work with VT

---

packages/astro/src/@types/astro.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/types.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/core/endpoint/index.ts
packages/astro/src/core/middleware/index.ts
packages/astro/src/core/pipeline.ts
packages/astro/src/core/render/context.ts
packages/astro/src/core/render/core.ts
packages/astro/src/core/render/index.ts
packages/astro/src/core/render/result.ts
packages/astro/src/i18n/middleware.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/package.json
packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/src/pages/en/blog/[id].astro
packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/src/pages/en/end.astro
packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/src/pages/en/start.astro
packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/src/pages/index.astro
packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/src/pages/preferred-locale.astro
packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/src/pages/pt/blog/[id].astro
packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/src/pages/pt/start.astro
packages/astro/test/fixtures/i18n-routing/src/pages/preferred-locale.astro
packages/astro/test/i18-routing.test.js
pnpm-lock.yaml

This PR adds two new features to i18n routing:
- new property to the `Astro` global, called `preferredLocaleList`, which represents a sorted list of the locales requested by the browser. This list is filtered with `i18n.locales`. 
- reviewed how `preferredLocale` is computed; now it takes into consideration `i18n.locales`
Here are the changes reflected to the RFC: https://github.com/withastro/roadmap/pull/734/commits/e07aef715688703ebcadf297c3f5ed543ed2c14c
I added new test cases to cover the new feature.

feat(i18n): rework preferred language and new preferredLanguageList

---

.changeset/plenty-spiders-act.md
packages/astro/src/runtime/server/render/astro/instance.ts
packages/astro/test/astro-slots.test.js
packages/astro/test/fixtures/astro-slots/src/components/Random.astro
packages/astro/test/fixtures/astro-slots/src/components/RenderMultipleTimes.astro
packages/astro/test/fixtures/astro-slots/src/pages/rendered-multiple-times.astro

- Fixes #7068 
Added a case to an existing fixture.

fix(slots): consume eagerly rendered slot after one use

---

.changeset/odd-maps-glow.md
packages/underscore-redirects/src/astro.ts

- adds base path as prefix for input paths
- tested manually calling the function
- changeset only

feat(underscore-redirects): add `base` to input paths

---

.changeset/five-ads-look.md
packages/astro/components/ViewTransitions.astro
packages/astro/components/viewtransitions.css
packages/astro/e2e/fixtures/view-transitions/src/pages/no-directive-one.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/no-directive-two.astro
packages/astro/e2e/view-transitions.test.js

- Moves the styles from the external viewtransition.css stylesheet into the component itself.
- `viewtransition.css` is only added if there are uses of the `transition:` directives. In apps that do not use those, the styles are never added.
- So to ensure that the route announce styles are on the page, the styles should be in the component. Should have been here in the first place!
- Test added
N/A, bug fix

Prevent the route announcer from being visible

---

.changeset/twenty-shirts-smile.md
packages/astro/e2e/dev-overlay.test.js
packages/astro/src/runtime/client/dev-overlay/overlay.ts

What the title says.
Added a test
N/A. It was already documented that the name would show in the UI where needed

feat(dev-overlay): Add a tooltip on plugin hover / focus

---

.changeset/tasty-oranges-bathe.md
packages/astro/components/Image.astro
packages/astro/components/Picture.astro
packages/astro/src/assets/internal.ts
packages/astro/src/assets/services/service.ts
packages/astro/src/assets/types.ts
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image/src/pages/picturecomponent.astro

The `sizes` attribute needs to be on every `source` element, much like it is on the `img` one. We were wrongly not including it.
This PR also includes a small refactor to the types of the internal `srcSet` object we pass around, we had two types with the same name when really, only one is needed.
Edited the picture test to test for `sizes` as well, since you can't really use `widths` without it anyway.
N/A

fix(assets): Propagate sizes attribute on all sources

---

packages/astro/src/@types/astro.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/units/config/config-validate.test.js

There was some issue with the types of `i18n.fallback`, and I added another level of validation to zod.
Added a test case to cover the new logic
@sarah11918 we can use this PR to land the correct [documentation for fallback](https://github.com/withastro/astro/pull/8974#discussion_r1380679252)

chore(i18n): reworked fallback, docs, types and validation

---

packages/astro/client.d.ts
packages/astro/src/i18n/index.ts
packages/astro/test/units/i18n/astro_i18n.js

From API bash session, we agreed that it makes sense to have the option `normalizePath` set to `true` as a default value because that's what users would want most of the times.
Updated the tests 
Update the examples

refactor(i18n): make `normalizePath` to default to `true`

---

.changeset/strange-toes-remain.md
packages/astro/components/Code.astro
packages/astro/src/core/config/schema.ts
packages/astro/test/astro-markdown-shiki.test.js
packages/astro/test/fixtures/astro-markdown-shiki/langs/astro.config.mjs
packages/astro/test/fixtures/astro-markdown-shiki/langs/src/caddyfile.tmLanguage.json
packages/astro/test/fixtures/astro-markdown-shiki/langs/src/pages/index.md

fix https://github.com/withastro/astro/issues/8970
Shiki supports languages with the `path` prop, which loads language JSON files, relative to the package root (in our case, the Astro package 😬). It's a bit of an ugly compat, but they should be removed in Astro 4.
added new test based on the issue repro.
n/a

Add shiki lang path compat

---

packages/astro/src/@types/astro.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/endpoint/index.ts
packages/astro/src/core/middleware/index.ts
packages/astro/src/core/pipeline.ts
packages/astro/src/core/render/context.ts
packages/astro/src/core/render/core.ts
packages/astro/src/core/render/index.ts
packages/astro/src/core/render/result.ts
packages/astro/src/vite-plugin-astro-server/route.ts

From the API bash session, a suggestion was to compute `preferredLocale` and `preferredLocaleList` lazily. To do so, we agreed that `i18n.locales` cab be passed down to the point where we compute the context for the endpoints, and the `Astro` faux-global.
This PR does that by removing the computation of `preferredLocale` and `preferredLocaleList` from the three pipelines, and instead, we simply pass `locales`. The computation is moved inside two new getters.
This is a refactor, so existing functionality should not change and the existing tests should still pass.
N/A

refactor(i18n): compute preferred locales lazily

---

packages/astro/src/i18n/index.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/test/units/i18n/astro_i18n.js

From the API bash session, we discovered that the utilities exported by the `astor:i18n` module should consider the `routingStrategy` configuration option.
This PR applies the required changes to return the correct URLs.
For example, when `routingStrategy` is `prefix-other-locales`, the `defaultLocale` should never appear in the URL, e.g.
```js
getLocaleRelativeUrl("en", "getting-started"); // should return `/getting-tarted`
```
I updated the current testing suite with the correct expectations 
N/A

fix(i18n): consider `routingStrategy` when computing the URLs

---

packages/astro/src/core/preview/static-preview-server.ts
packages/astro/src/core/preview/vite-plugin-astro-preview.ts
packages/astro/src/vite-plugin-scripts/index.ts
packages/astro/test/preview-routing.test.js

1. Handle type changes and renames in Vite 5.
2. Handle preview server 404 serving middleware.
3. Skip preview server tests for Vite 5 for now. Created a new [linear issue](https://linear.app/withastro/issue/PLT-1148/rework-trailingslash-buildformat) to track it.
The changes are backwards compatible, and should allow Astro to pass in [Vite's ecosystem-ci](https://github.com/vitejs/vite-ecosystem-ci/actions/runs/6766541296/job/18387806208)
Ran `pnpm test` locally with Vite 5 and `main`.
n/a

Handle Vite 5 changes

---

.changeset/tricky-clocks-end.md
packages/integrations/vercel/README.md
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/test/fixtures/streaming/astro.config.mjs
packages/integrations/vercel/test/fixtures/streaming/package.json
packages/integrations/vercel/test/fixtures/streaming/src/pages/one.astro
packages/integrations/vercel/test/fixtures/streaming/src/pages/two.astro
packages/integrations/vercel/test/static-assets.test.js
packages/integrations/vercel/test/streaming.test.js
pnpm-lock.yaml

- Before: https://astro-blog-template-i8g8rijty-lilnasy.vercel.app/streaming
- After: https://astro-blog-template-o79sdirk5-lilnasy.vercel.app/streaming
- https://vercel.com/docs/build-output-api/v3/primitives#base-config
Added a fixture.
Changeset only.

feat(vercel): streaming

---

packages/astro/src/@types/astro.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/i18n/middleware.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/i18n-routing-prefix-always/src/pages/en/index.astro
packages/astro/test/i18-routing.test.js

From the API bash session, it emerged that when we have the routing strategy `prefix-always`, we should always redirect the root index `example.com` to `example.com/<defaultLocale>`.
Not doing this will result in the index having a 404, which is a bad practice. 
Relative change in the RFC: https://github.com/withastro/roadmap/pull/734/commits/26ed3c679c97e51a5bf6f6821fe7e4c921861b52
All the existing tests should pass, plus I added new ones to cover the case. 
/cc @withastro/maintainers-docs Please review the change in the configuration description

fix(i18n): redirect the index when `prefix-always` is enabled

---

.changeset/spotty-rings-crash.md
packages/integrations/lit/server.js
packages/integrations/lit/test/server.test.js

- Fixes https://github.com/withastro/astro/issues/9017
- Hydration will now happen top to bottom with child custom elements getting `defer-hydration` attribute from Lit SSR
Added an extra assertion in nested component test that looks for `defer-hydration` attribute on the child element.
Bug fix only. No change in docs necessary.

Fix Lit integration hydration ordering

---

packages/astro/src/core/render/context.ts
packages/astro/src/i18n/index.ts
packages/astro/test/fixtures/i18n-routing/src/pages/preferred-locale.astro
packages/astro/test/i18-routing.test.js

This PR fixes some edge cases that could happen when looking for the preferred locales.
Since this feature doesn't enforce a restriction on how the locales should be written, this could be a problem when reading the locales coming from the browser. This will become a problem with the four-letter locales, e.g. `pt_BR`.
The `Accept-Language` header has a value like this `pt-BR`, but a user **might** have their routes and folders like this: `src/pages/pt-br/index.astro` and `example.com/pt-br`.
This PR fixes this issue by:
- normalizing both sources: the locales coming from the browser and the locales coming from the configuration, it use the same function we use for the virtual module
- returning the locales of the configuration, and not the locale of the browser
N/A

fix(i18n): better filtering and search for preferred locales

---

packages/astro/src/core/build/buildPipeline.ts
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/i18n-routing-prefix-always/src/pages/index.astro

This PR fixes a case where the `routingStrategy` is `prefix-always` and the `src/pages/index.astro` isn't present.
The routing strategy is pretty clear about what it does (now):
> example.com/ will redirect to `example.com/en
This works fine if `src/pages/index.astro` is present but it won't if the file isn't there.
This PR fixes the issue in dev and SSG (SSR is already handled):
- dev was a pretty easy fix
- SSG leverages the same fallback logic to create a fake "fallback" route, so we can emit a `index.html` file that redirects to `/en`
I **deleted** the `src/pages/index.astro` from the fixture of `prefix-always` and the assertions should still be valid.

fix(i18n): fallback index when routing is prefix-always

---

.changeset/rude-lizards-scream.md
packages/astro/client.d.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/test/fixtures/i18n-routing/src/pages/virtual-module.astro
packages/astro/test/i18-routing.test.js

This PR fixes the names of the functions exported by the virtual module `astro:i18n`.
The [RFC](https://github.com/withastro/roadmap/blob/i18n-routing/proposals/0041-i18n-routing.md#getrelativelocaleurllocale-string-path-string-options-options-string) and Docs are correct, although the names exported by Astro incorrect.
This PR aligns their names with the ones of the RFC.
I added a new test to make sure it works
N/A
Changeset not needed

fix(i18n): names of the functions should match the RFC

---

packages/astro/tsconfigs/base.json

My change updates the comment for the `moduleResolution` setting as this setting has been changed in #7785
The current comment says it enables "node-style module resolution" but the resolution value got changed from `node` to `Bundler` and the [TypeScript's moduleResolution documentation](https://www.typescriptlang.org/tsconfig#moduleResolution) says that this change has a major difference which I think is worth being mentioned:
> unlike the Node.js resolution modes, `bundler` never requires file extensions on relative paths in imports
It's only updating the comment, no behaviour change gets introduced.

chore: Update docs for TS 5 presets

---

.changeset/silent-experts-sip.md
packages/create-astro/package.json
packages/create-astro/src/actions/dependencies.ts
packages/create-astro/src/messages.ts
pnpm-lock.yaml

This PR is a fixed version of the closed by mistake PR: https://github.com/withastro/astro/pull/8993
@ematipico - sorry, made an error and have to reopen new PR
Added onError function to handle errors inside spinner if while function throws an errors.
new onError property inside dependencies.ts spinner
while function catches and throws an error if installing dependencies fails
messages.ts/spinner accept new args
Manual testing.
This PR does not require changes in docs.

fix: added onError functionality to spinner 

---

packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/form-two.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/transitions/router.ts

- Normally when the user navigates to the same page we do not trigger a fetch + navigation, instead we just navigate to the hash (if there is one).
- This should not be the case for form posts, which have side-effects that need to occur.
- This also makes it possible to omit the `action`.
N/A, bug fix

Allow same-page navigations on form posts

---

packages/astro/src/@types/astro.ts

Changes `Prefetch` and `i18n` into `heading`s to see if I can get the docs sidebar nested properly
This is a test! The automated PR for docs will let me test the output
Just docs!

[docs] test config-reference formatting for sidebar

---

.changeset/quick-parrots-judge.md
packages/astro/src/content/vite-plugin-content-assets.ts
packages/astro/src/content/vite-plugin-content-virtual-mod.ts
packages/astro/src/core/build/plugins/plugin-css.ts
packages/astro/test/content-collections.test.js
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/content-collections/src/pages/propagation.astro

- Resolves PLT-1196
- Closes #9066
- Fixes regression in 3.5.x with asset propagation in content collections
- Had to update a few changes made in #8854 to ensure behavior is properly behind a flag
Added a regression test
Bug fix only

Fix asset propagation regression in 3.5

---

.changeset/dirty-zoos-fail.md
packages/astro/src/core/logger/core.ts

- Fixes #9060 
- `this.options` argument is not needed in `debug` function (see below). Passing it as a first argument causes `[object Object]` in the namespace label as described in the issue
- https://github.com/withastro/astro/blob/13ca6d989b91c4575517495647fc10ba8306cf88/packages/astro/src/core/logger/node.ts#L110-L114
Tested via `pnpm --filter @example/minimal run build --verbose`
\-

fix(logger): namespace label in debug logger

---

.changeset/famous-hats-teach.md
packages/astro/src/assets/services/noop.ts

Only uses the `src` to hash images on the passthrough service, that way attributes don't cause multiple files to be generated.
Fix https://github.com/withastro/astro/issues/9002
We have tests that are testing this hook of the image service API
N/A

fix(assets): Only use src to hash files generated by the passthrough service

---

packages/astro/config.d.ts

Updates comments on `ImageServiceConfig` in `config.d.ts`.
I didn't run `pnpm changeset` because I only updated comments. I'm not sure if I am correct.
Nothing, because comment doesn't affect.
Nothing, because comment doesn't affect.

chore(config.d.ts): Update comment of `ImageServiceConfig`

---

.changeset/new-pets-fail.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/form-three.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/package.json
pnpm-lock.yaml

- Adds takes into account: `<button type="submit" formmethod="post" formaction="/other">`.
- This is a way to have a button which modifies the action and/or method of the parent form.
- Test added
N/A, bug fix

Support formmethod and formaction in ViewTransitions

---

.changeset/calm-lemons-compare.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/types.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/i18n/middleware.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/i18-routing.test.js

This PR fixes a bug where when `trailingSlash` is `always`, the middleware should take that into consideration and redirect to the correct URL.
To do so, I had to add `trailingSlash` to the manifest. This is a piece of information that so far was saved inside `routeData._meta`, although this is now required to have inside the SSR manifest, at the top level. 
I created new test cases, for each pipeline
N/A

fix(i18n): middleware should consider trailing slash when redirecting

---

packages/astro/src/@types/astro.ts

Fixes a typo for docs
No tests!
Only docs!

[docs] config-reference typo

---

.changeset/red-houses-explode.md
packages/astro/src/core/build/plugins/plugin-prerender.ts

- fixes https://github.com/withastro/astro/issues/9059
- see Discord's #dev channel for more context, and [resolution](https://discord.com/channels/830184174198718474/845430950191038464/1173670300567744573)
- the fix of the regression was tested manually and compared to `3.4.4` (known good) and `3.5.0` (known bad)
- the content collection cache implications were not tested, hopefully ci catches them
- changeset

fix(assets): image service bundling for pre-rendered pages non-node runtime regression

---

packages/astro/src/@types/astro.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/i18n/index.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/src/integrations/astroFeaturesValidation.ts
packages/astro/test/fixtures/i18n-routing/astro.config.mjs
packages/astro/test/fixtures/i18n-routing/src/pages/virtual-module.astro
packages/astro/test/i18-routing.test.js
packages/astro/test/units/config/config-validate.test.js
packages/astro/test/units/i18n/astro_i18n.js

This PR starts the work around domain support. Here are the changes:
- updated the schema with proper validation for the `domains` configuration;
- updated the Astro features with the `domains` support capability. I am not aware of any esoteric case, so notifying Astro with `SupportKind` should be enough
- updated the `getAsbsoluteLocaleUrl` function, which now accepts `domains` and a `isBuild` flag. `isBuild` is required because we can only use the URLs with domains when building the website, otherwise the dev server is broken
Closes: 	PLT-994, PLT-992 and PLT-1206
I added various cases to test the implemented features
Added some basic documentation

i18n(domains): validation and updated logic

---

.changeset/twelve-mails-drive.md
packages/integrations/svelte/README.md
packages/integrations/svelte/client-v5.js
packages/integrations/svelte/package.json
packages/integrations/svelte/server-v5.js
packages/integrations/svelte/server.js
packages/integrations/svelte/src/index.ts
pnpm-lock.yaml

Add experimental support for Svelte 5. This PR needs more testing, but seems to cover the common cases.
NOTE: When testing this locally, the `svelte` devdep in `@astrojs/svelte` needs to be bumped to 5.0.0-next.1.
n/a. manual testing for now until Svelte 5 is stable.
Updated README to note supported Svelte versions

Support Svelte 5 (experimental)

---

.changeset/flat-jobs-punch.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/build/buildPipeline.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/internal.ts
packages/astro/src/core/build/page-data.ts
packages/astro/src/core/build/static-build.ts
packages/astro/src/core/build/types.ts
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/core/routing/manifest/serialization.ts
packages/astro/src/core/routing/match.ts
packages/astro/src/i18n/middleware.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/i18n-routing-fallback/src/pages/index.astro
packages/astro/test/i18n-routing.test.js

This PR closes https://github.com/withastro/astro/issues/9108
The was a big flaw in the logic of the fallback, so I went back, and restored how the routes were stored before the introduction of the fallback logic.
The new change involves the introduction of `fallbackRoutes` as part of the `RouteData` object, very very similar to how we do it for `redirectRoutes`.
Although, now the generation of the pages is different, and each `RouteData` could create more than one page (itself + `fallbackRoutes`), hence I create a generator function called `eachRouteInRouteData`, which returns all the routes we need to create.
EDIT:
In SSR, the middleware already has the logic for doing the redirect, although we need to tell it somehow. So I updated the logic of `app/index.ts`. 
The `match` function now …

fix(i18n): review fallback system

---

packages/astro/src/@types/astro.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/types.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/i18n-routing-subdomain/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-subdomain/package.json
packages/astro/test/fixtures/i18n-routing-subdomain/src/pages/en/blog/[id].astro
packages/astro/test/fixtures/i18n-routing-subdomain/src/pages/en/index.astro
packages/astro/test/fixtures/i18n-routing-subdomain/src/pages/en/start.astro
packages/astro/test/fixtures/i18n-routing-subdomain/src/pages/pt/blog/[id].astro
packages/astro/test/fixtures/i18n-routing-subdomain/src/pages/pt/start.astro
packages/astro/test/fixtures/i18n-routing/astro.config.mjs
packages/astro/test/i18-routing.test.js
packages/astro/test/units/config/config-validate.test.js
pnpm-lock.yaml

Relative RFC change: https://github.com/withastro/roadmap/commit/713fce74bb742f18ad985055758c3818b5eed9aa
This PR adds the basic logic for supporting the new routing strategy called `domain`. We require a new routing strategy because Astro needs to make assumptions** in order to provide the correct user experience.
This assumption is that the localised folders must be at the root - `src/pages` folder. With that, the logic works as follow: during the build phase, we add to the manifest a new information called `domainLookupTable`. This table is a map that will look like this:
```js
const domainLookupTable = {
"https://fr.example.com": "fr",
"https://example.pt": "pt",
}
```
It's essentially the configuration of `i18n.domains`, reversed :)
This table maps what we are supposed to get from …

 feat(i18n): domain with lookup table 

---

.changeset/curvy-sheep-lick.md
packages/astro/src/core/build/generate.ts
packages/astro/src/core/render/params-and-props.ts
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/core/routing/params.ts
packages/astro/src/i18n/middleware.ts
packages/astro/test/i18n-routing.test.js
packages/astro/test/ssr-split-manifest.test.js

Fixes https://github.com/withastro/astro/issues/9096
Fixes https://github.com/withastro/astro/issues/9095
Closes PLT-1230
This PR refactors the fallback system again. There was a business logic flaw in how the routes and paths were computed, plus the flow of things could have been smoother, and that didn't help. 
When rendering a page, the flow **was** like this:
- we extract the styles/links/scripts
- generate the paths using `getStaticPaths`
- loop over the exploded paths
- call the `generatePath` function
- compute more styles and scripts
- create a request and render the response
Now the flow is adapted to the fallback, and a few steps have been moved:
- we extract the styles/links/scripts
- compute more styles and scripts
- **NEW** loop over the exploded routes (itself + fallbacks)
- …

fix(i18n): fallback should create consistent directories

---

.changeset/nine-houses-attend.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/non-html-anchor.astro
packages/astro/e2e/view-transitions.test.js

Currently we only trigger view transitions for clicks on or within HTMLAnchorElements. 
This excludes `<a href="" ...>` within SVG elements, which are technically not HTMLElements but SVGAElements, see #9001. This change fixes that issue and now also includes HTMLAreaElements, so you also get view transitions when you click inside your beloved image maps. 
Closes #9001
Added e2e test cases 
Most users will not recognize the difference between an `<a href=` inside or outside of `<svg>...</svg>`. So this part is not really an extension, but a bug fix. The support for image maps is an extension, but of a more theoretical nature. It is said that they were last used in the 90s.

Extend the 'click' listener of view transitions to handle links in SVGs and areas in image maps 

---

.changeset/khaki-fans-sell.md
packages/markdown/remark/package.json
packages/markdown/remark/src/index.ts
packages/markdown/remark/src/types.ts
pnpm-lock.yaml

Supersedes and closes https://github.com/withastro/astro/pull/6211
The linked PR above explains why the types is incorrect today. This PR merges into `next` which includes the latest versions of the remark/rehype plugins, which I think should work now.
Existing test should pass. Also tested the types in an Astro config manually.
n/a. bug fix.

Fix RemarkRehype types

---

.changeset/neat-mangos-judge.md
.changeset/six-owls-trade.md
packages/astro/src/prefetch/index.ts

1. Fallback to `tap` prefetch strategy on slow connection, instead of bailing.
2. Add `ignoreSlowConnection` option to prefetch API, which lets manually prefetch even on data saver mode or slow connection.
Tested on test cases added in this PR https://github.com/withastro/astro/pull/8951
Docs: https://github.com/withastro/docs/pull/5393
This PR also has changesets and JSDoc for review.

Fallback to tap prefetch strategy on slow connection

---

.changeset/sour-games-burn.md
packages/astro/client.d.ts
packages/astro/components/ViewTransitions.astro
packages/astro/package.json
packages/astro/src/core/create-vite.ts
packages/astro/src/core/middleware/namespace.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/src/prefetch/vite-plugin-prefetch.ts
packages/astro/src/transitions/vite-plugin-transitions.ts
packages/astro/src/virtual-modules/README.md
packages/astro/src/virtual-modules/i18n.ts
packages/astro/src/virtual-modules/middleware.ts
packages/astro/src/virtual-modules/prefetch.ts
packages/astro/src/virtual-modules/transitions-router.ts
packages/astro/src/virtual-modules/transitions.ts

Group the files used for `astro:middleware`, `astro:transitions`, `astro:transitions/router`, `astro:i18n`, and `astro:prefetch` under an internal export at `astro/virtual-modules/*`
n/a. internal refactor

Refactor virtual modules exports

---

packages/astro/src/vite-plugin-scanner/scan.ts

Recently we upgraded `esbuild`, which (for some reason) does partial linting and flagged this code in `packages/astro`:
```
▲ [WARNING] The "??" operator here will always return the left operand [suspicious-nullish-coalescing]
src/vite-plugin-scanner/scan.ts:75:43:
75 │             settings?.config.output === 'hybrid' ?? false
╵                                                  ~~
The left operand of the "??" operator here will never be null or undefined, so it will always be
returned. This usually indicates a bug in your code:
src/vite-plugin-scanner/scan.ts:75:6:
75 │             settings?.config.output === 'hybrid' ?? false
╵             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[05:51 PM] ⚠ updated with warnings:
[object Object]
[05:51 PM] ✔ updated
```
I removed the `?? false` in this PR. …

Fix esbuild warning for local dev

---

.changeset/rude-hairs-whisper.md
packages/astro/src/@types/astro.ts
packages/astro/src/assets/internal.ts
packages/astro/src/core/build/buildPipeline.ts
packages/astro/src/core/build/internal.ts
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/integrations/index.ts
packages/astro/src/vite-plugin-integrations-container/index.ts
packages/astro/test/astro-scripts.test.js
packages/astro/test/fixtures/custom-404-injected-from-dep/astro.config.mjs
packages/astro/test/fixtures/custom-404-injected/astro.config.mjs
packages/astro/test/fixtures/routing-priority/integration.mjs
packages/astro/test/ssr-dynamic.test.js
packages/astro/test/units/dev/dev.test.js

There's only one instance where we use `entryPoint` which is for the `injectRoute()` API. This PR renames it to `entrypoint`, and emit a warning if the old name is used
https://github.com/withastro/docs/pull/5475
I also added a warning at `packages/astro/src/integrations/index.ts`

Rename entryPoint to entrypoint

---

packages/astro/CHANGELOG.md

- Fix code block formatting for View Transitions in the changelog for 3.6.0

fix: Changelog formatting for 3.6.0 View Transition events

---

.changeset/great-hats-drive.md
packages/astro/src/core/middleware/vite-plugin.ts

- Renames middleware chunk
- Fixes #9172
- Output now looks like this

fix(middleware): rename internal middleware id

---

.changeset/shaggy-socks-glow.md
packages/astro/src/transitions/router.ts

Scroll to a fragment did not work for webKit-based browsers. It seems that you need to explicitly set scrollRestoration to "auto" before the assignment to location.href (or location.hash) scrolls to the anchor. 
Tested manually as we do not have automated e2e tests on Safari.
n./a. bug fix

fix scroll restoration issue on webKit browsers

---

CONTRIBUTING.md

Giving convenient look to Tip and Note section by available [markdown](https://github.com/orgs/community/discussions/16925) for [Contributor Manual](https://github.com/withastro/astro/blob/main/CONTRIBUTING.md).
Example of Tip by previous markdown.
Example of Tip available markdown.
---
Part of Note section for previous markdown.
And lastly part of Note section available markdown.

style: highlight markdown Tip Note section CONTRIBUTING

---

.changeset/giant-snails-perform.md
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/src/static/adapter.ts

Remove `analytics` option
I don't think this needs to be documented in the breaking tracker as this is specific to vercel? The changesets might be enough.

Remove vercel deprecated analytics option

---

.changeset/shiny-trees-sip.md
packages/markdown/remark/src/frontmatter-injection.ts
packages/markdown/remark/src/index.ts
packages/markdown/remark/src/internal.ts

These APIs are not used by us anymore. They're only kept so we can remove them in the next markdown-remark major, like now in the `next` branch
Existing tests should work.
n/a. internal refactor. Added a changeset though so we can track this change in the future.

Remove deprecated markdown-remark APIs

---

.changeset/brown-jars-lick.md
packages/astro/e2e/fixtures/prefetch/src/pages/index.astro
packages/astro/e2e/prefetch.test.js
packages/astro/src/prefetch/index.ts

Links where the path is the same, but search params are not, are prefetched
e2e test
As far as I can tell from reading the docs, they do not mention prefetching behavior in this case at all. Since this change aligns it more with expected behavior, I don't think more information would need to be added, but I can write something if necessary.
fix https://github.com/withastro/astro/issues/9185

fix: links with same path but different search params not prefetched

---

.changeset/twelve-fishes-fail.md
packages/integrations/node/README.md
packages/integrations/node/src/http-server.ts
packages/integrations/node/src/index.ts
packages/integrations/node/src/preview.ts
packages/integrations/node/src/server.ts
packages/integrations/node/src/standalone.ts
packages/integrations/node/src/types.ts
packages/integrations/node/test/assets.test.js
packages/integrations/node/test/fixtures/image/src/assets/file.txt
packages/integrations/node/test/fixtures/image/src/pages/text-file.astro

- Adds an immutable cache header for assets inside of `_astro` in the Node adapter.
- Closes https://github.com/withastro/astro/issues/9106
- Test to ensure that only stuff inside `_astro` is given the header.
N/A, bug fix

Support immutable cache headers for _astro assets

---

.changeset/chilly-sloths-move.md
packages/upgrade/src/messages.ts
packages/upgrade/test/fixtures/basic/package.json
packages/upgrade/test/utils.js
pnpm-lock.yaml

- Fixes an issue when running `@astrojs/upgrade beta` in the docs repo
- The `semverParse` logic wasn't always correct because it could return `null` in certain scenarios. But it turns out the parse wasn't even needed in this case, so I removed it.
Tested manually, it fixes the bug

fix(upgrade): Remove semver parse

---

.changeset/weak-wolves-bow.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/node.ts
packages/astro/test/middleware.test.js
packages/astro/test/ssr-404-500-pages.test.js

- This PR removes `matchNotFound`
- As discussed here: https://discord.com/channels/830184174198718474/845430950191038464/1174600194810204201
- no doc changes

remove deprecated `matchNotFound` options

---

.changeset/tricky-dragons-explain.md
packages/astro/src/runtime/client/dev-overlay/plugins/astro.ts
packages/astro/src/runtime/client/dev-overlay/plugins/audit.ts

Some small changes that came up from the dev overlay bug bash:
- Links now open in a new tab
- "Copy debug info" button now resets automatically after a delay and is a bit more clear
- "No issues found" alert now has the proper ARIA role
N/A
N/A

Small polish to the overlay

---

.changeset/spicy-starfishes-shake.md
packages/astro/src/runtime/client/dev-overlay/plugins/utils/highlight.ts
packages/astro/src/runtime/client/dev-overlay/plugins/xray.ts

Fixes docs usage
- Calculates the z-index of the island by checking its z-index and all of its parents. Then increments 1 to determine the z-index of the highlight and tooltip.
- Tested in docs site
N/A

Ensure dev overlay x-ray highlight goes over the island

---

.changeset/odd-rivers-happen.md
packages/astro/components/ViewTransitions.astro

- Deprecates the `handleForms` opt-in for the `ViewTransitions` component
- Enables form submission handling by default when `ViewTransitions` is enabled.
- Individual `form` elements can opt-out by setting the `data-astro-reload` attribute.
Added to https://github.com/withastro/docs/issues/5390

Unflag view transitions form handling

---

.changeset/wicked-books-appear.md
packages/astro/src/vite-plugin-astro/hmr.ts

- Closes PLT-1261
- Adjusts our style HMR logic so that style only changes will only treat the effected style modules as HMR candidates
- This fixes an edge case where updates inside of Astro files _referenced_ by the main page file would cause a full reload because `pages/index.astro` would remain in the module graph.
- This should close #9216, which is a report about this specific edge case. As reported, if the `style` inside of `src/layouts/Layout.astro` was updated, the whole index page would reload. With this fix, updating the `style` inside of `src/layouts/Layout.astro` does not reload the index page but swaps the new styles in seamlessly.
Tested manually, our existing HMR tests aren't capable of catching this problem
Bug fix only

fix(#9216): fix style HMR in certain cases

---

.changeset/big-cooks-notice.md
.changeset/sharp-starfishes-compete.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/node.ts
packages/astro/test/middleware.test.js
packages/astro/test/ssr-locals.test.js
packages/integrations/node/src/nodeMiddleware.ts
packages/integrations/vercel/src/serverless/entrypoint.ts

- `app.render(request, undefined, locals)` -> `app.render(request, { locals })`
Switched a couple of tests to use the new API, keeping two as-is that still test the current API.
- https://github.com/withastro/docs/pull/5510

Switch `app.render` signature

---

.changeset/famous-eels-trade.md
packages/astro/src/runtime/client/dev-overlay/ui-library/window.ts

https://github.com/withastro/astro/assets/361671/362231af-9cfb-4a21-b3ca-83fe97dc7bc5
- Uses bottom calculation (7.5%, which is the devbar's bottom + a magic number)
- works in all tested apps
Manually
N/A

Ensure dev-overlay-window is anchored to the bottom

---

.changeset/grumpy-seas-switch.md
packages/astro/src/runtime/client/dev-overlay/overlay.ts
packages/astro/src/runtime/client/dev-overlay/plugins/astro.ts
packages/astro/src/runtime/client/dev-overlay/ui-library/icon.ts
packages/astro/src/runtime/client/dev-overlay/ui-library/toggle.ts
packages/astro/src/runtime/client/dev-overlay/ui-library/window.ts

- Improves high contrast
- Mostly this is just making backgrounds white and text / fill black.
https://github.com/withastro/astro/assets/361671/44f84144-6857-4435-b810-e33cc47a3f02
N/A
N/A

Improve high contrast mode with the dev overlay

---

packages/astro/src/runtime/client/dev-overlay/overlay.ts

- Closes PLT-1245
- Sets `all: initial` on the dev overlay to reset style inheritance.
- This fixes a problem where global font-size/line-height and other inheritable styles would break the dev overlay.
- Not including a changeset because it will just go out in the next patch
Manually. It works!
Nah

Fix dev overlay style leak

---

.changeset/happy-beans-protect.md
packages/astro/src/i18n/middleware.ts
packages/astro/test/i18n-routing.test.js

- Closes #9223
- Adds conditional that checks that `prefix-always` is false before removing locale in fallback routing
I made this change locally in my project's `node_modules` and added a unit test.
No doc changes needed, as this restores functionality to match docs

[i18n] During fallback, only remove locale if prefix-always is false

---

.changeset/tall-hotels-argue.md
packages/astro/src/core/render/core.ts
packages/astro/src/runtime/server/render/page.ts
packages/astro/test/astro-slots.test.js
packages/astro/test/fixtures/astro-slots/src/pages/fallback-own.astro
packages/astro/test/fixtures/astro-slots/src/pages/fallback.astro

- Switches a `null` to a `{}`
- Fixes #9178
Added a case to `astro-slots.test.js`

fix(rendering): prevent error when slots is keyed into

---

.changeset/young-trains-shout.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/types.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/core/endpoint/index.ts
packages/astro/src/core/pipeline.ts
packages/astro/src/core/render/context.ts
packages/astro/src/core/render/core.ts
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/i18n/middleware.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/i18n-routing-base/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-prefix-always/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-prefix-other-locales/astro.config.mjs
packages/astro/test/i18n-routing.test.js

This PR addresses RFC change: https://github.com/withastro/roadmap/pull/734/commits/089253d317e4327ee4e3b93eb303ddc28859952b
Closes PLT-1269
Thanks to zod `.transform`, the only changes are user-facing and logically it stays the same.
The code changes I did are:
- renaming `routingStrategy` to `routing`, which is transformed in a string (we can then decide to change the string themselves, but it's only bikeshedding)
- Documentation and the shape of the user-facing configuration
All tests should pass after updating the configuration to use the new shape.

refactor(i18n): breakdown routing strategy

---

.github/workflows/release.yml

So that we can backport and release stuff from the `3-legacy` branch that we'l create later.
n/a
n/a

Enable releasing from 3-legacy branch

---

package.json
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/dev/dev.ts
packages/astro/src/core/module-loader/vite.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/src/prefetch/vite-plugin-prefetch.ts
packages/astro/src/transitions/vite-plugin-transitions.ts
packages/astro/src/vite-plugin-astro-server/base.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro/index.ts
packages/astro/src/vite-plugin-dev-overlay/vite-plugin-dev-overlay.ts
packages/astro/src/vite-plugin-env/index.ts
packages/astro/src/vite-plugin-head/index.ts
packages/astro/src/vite-plugin-load-fallback/index.ts
packages/integrations/react/src/index.ts

This is not completed yet! For some reason `organize-imports-cli` is stripping away `import type * as vite from 'vite';`, and I couldn't figure out why.
Likely some dependency updates from the `next` branch (now merged into `main`) had triggered this, but I tried to revert versions for `typescript`, `ts-morph`, and `@ts-morph/common>minimatch`, but it still get stripped when I run `pnpm format:ci`
This PR currently only brings in the missing `import type * as vite from 'vite';`. We can't merge it as the auto-formatter would strip it away again.
n/a
n/a

Fix missing type import from auto format

---

package.json
pnpm-lock.yaml

- Adds some `pnpm` config to ignore noisy peerDependency warnings. They're actually fine and we don't need these!
- Just a chore to make our day-to-day better, no changeset needed
`pnpm install`, it is no longer annoying
No thanks

Chore: fix noisy peerDependency warnings (it's fine)

---

.changeset/modern-lies-thank.md
packages/upgrade/src/actions/verify.ts

- `@astrojs/upgrade beta` was pointing CHANGELOG links to the `next` branch
- The `next` branch has been merged to `main`.
- This PR updates the links to point to `main` instead.
Manual
Bug fix

fix(upgrade): point beta changelogs to main

---

examples/ssr/src/pages/api/cart.ts
examples/ssr/src/pages/login.form.async.ts
examples/ssr/src/pages/login.form.ts
packages/astro/test/fixtures/content-collection-references/src/pages/welcome-data.json.js
packages/astro/test/fixtures/ssr-api-route-custom-404/src/pages/api/route.js

Make sure we don't return simple objects from endpoint anywhere else. Also made sure they're uppercase now.
I like `Response.json`
n/a. internal change to tests and examples.

Remove remaining simple objects usage

---

.changeset/lemon-crews-juggle.md
packages/astro/e2e/dev-overlay.test.js
packages/astro/e2e/fixtures/dev-overlay/src/pages/audit-no-warning.astro
packages/astro/e2e/fixtures/dev-overlay/src/pages/xray-no-islands.astro
packages/astro/src/@types/astro.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/core/config/settings.ts
packages/astro/src/integrations/index.ts
packages/astro/src/preferences/defaults.ts
packages/astro/src/runtime/client/dev-overlay/entrypoint.ts
packages/astro/src/runtime/client/dev-overlay/overlay.ts
packages/astro/src/runtime/client/dev-overlay/plugins/astro.ts
packages/astro/src/runtime/client/dev-overlay/plugins/audit.ts
packages/astro/src/runtime/client/dev-overlay/plugins/settings.ts
packages/astro/src/runtime/client/dev-overlay/plugins/utils/highlight.ts
packages/astro/src/runtime/client/dev-overlay/plugins/utils/window.ts
packages/astro/src/runtime/client/dev-overlay/plugins/xray.ts
packages/astro/src/runtime/client/dev-overlay/ui-library/button.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/src/vite-plugin-dev-overlay/vite-plugin-dev-overlay.ts

- All of the `astro-dev-overlay-*` custom elements are renamed to `astro-dev-toolbar-*`.
- These are aliased back to `astro-dev-overlay-*` as to not break existing plugins.
- `addDevOverlayPlugin` is renamed to `addDevToolbarApp`.
- `addDevOverlayPlugin` remains as an alias.
- `devOverlay` Config option renamed to `devToolbar`
- `devOverlay` Astro preference renamed to `devToolbar`
- Adds a few new tests, as well as updates the existing ones.
- https://github.com/withastro/docs/pull/5541

Rename Dev Overlay to Dev Toolbar

---

packages/astro/src/runtime/client/dev-overlay/plugins/utils/highlight.ts
packages/astro/src/runtime/client/dev-overlay/plugins/xray.ts

- Fixes a bug where highlights could overlap other highlights
- Tested manually
- N/A

[Toolbar] Fix tooltip overlap bug

---

packages/astro/e2e/dev-overlay.test.js
packages/astro/src/runtime/client/dev-overlay/overlay.ts
packages/astro/src/runtime/client/dev-overlay/plugins/audit.ts
packages/astro/src/runtime/client/dev-overlay/plugins/settings.ts
packages/astro/src/runtime/client/dev-overlay/plugins/xray.ts
packages/astro/src/runtime/client/dev-overlay/ui-library/tooltip.ts
packages/astro/src/runtime/client/dev-overlay/ui-library/window.ts

- Small updates to some styles
- Changed props display from custom `key="value"` format to JSON (more familiar format for devs = faster to parse, especially when there are many props)
- Cleanup the event handling logic
- Added click handled logic in Audit and Inspect mode. Did this after some user feedback that these modes broke expectations with how browsers implement their "inspect" mode. I intentionally didn't add this globally because some apps will implement their UI differently so that it would be impossible to accurately identify a "page" click vs. an "overlay" click.
- Tested manually
- N/A

[Toolbar] Final style polish and code cleanup

---

packages/astro/src/@types/astro.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/build/util.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/core/create-vite.ts
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/i18n-routing-base/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-fallback/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-prefix-always/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-prefix-other-locales/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-redirect-preferred-language/astro.config.mjs
packages/astro/test/fixtures/i18n-routing/astro.config.mjs
packages/astro/test/i18n-routing.test.js
packages/astro/test/units/config/config-validate.test.js

This PR moves i18n configuration out of the `experimental` flag.
This PR must be merged AFTER the RFC https://github.com/withastro/roadmap/pull/734 is merged
The whole test suite should pass
/cc @withastro/maintainers-docs to quickly check if the JSDoc are correct

chore: remove `experimental` from i18n configuration

---

.changeset/nervous-beans-peel.md
packages/astro/e2e/fixtures/view-transitions/src/pages/long-page.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/transitions/router.ts

Greater consistency between navigations with and without `<ViewTransitions>`: 
- New for direct calls to `navigate()`: Navigation to a URL whose origin does not match the origin of the current page is excluded from view transition processing and triggers the standard navigation of the browser.
- New: Navigation to the current page (= same path name and same search parameters) without a hash fragment triggers view transition processing.
- New for form submission: Navigation to a non-empty hash target on the current page does not trigger view transitions, but updates the browser history directly and scrolls to the target position. 
Had to fix one test because page.back() does not wait for asynchronous actions. 
Details have never been documented before, so there is nothing to update.

Increase consistency between navigation with and without ViewTransitions

---

packages/astro/e2e/astro-envs.test.js
packages/astro/e2e/css.test.js
packages/astro/e2e/dev-overlay.test.js
packages/astro/e2e/fixtures/astro-component/astro.config.mjs
packages/astro/e2e/fixtures/astro-envs/astro.config.mjs
packages/astro/e2e/fixtures/lit-component/astro.config.mjs
packages/astro/e2e/fixtures/prefetch/astro.config.mjs
packages/astro/e2e/fixtures/tailwindcss/astro.config.mjs
packages/astro/e2e/fixtures/view-transitions/astro.config.mjs
packages/astro/e2e/hmr.test.js
packages/astro/src/@types/astro.ts
packages/astro/src/core/compile/compile.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/runtime/client/dev-overlay/overlay.ts
packages/astro/src/vite-plugin-astro-server/route.ts

- `devOverlay` config was introduced in the `4.0.0-beta.X` release branch, meaning it is not covered by semver now that it has been renamed to `devToolbar`. The only people who would have been using this were people experimenting with early versions of the Astro 4.0 beta.
- This PR removes that no-longer-used config for the official 4.0 release.
- This PR also fixes a bug where `devOverlay` was being checked, instead of `devToolbar`
- This PR also updates tests to use `devToolbar` instead of `devOverlay`
- This PR also removes an outdated `defaultState` config, which was removed in #9230 but the config was missed. This is now a no-op and doesn't make conceptual sense since the toolbar now shows/hides based on hover/focus.
- Updated tests
- Updated docs in JSDoc
- @matthewp want your …

remove outdated devoverlay config and defaultstate config

---

.changeset/tender-eagles-learn.md
packages/astro/package.json
packages/astro/src/runtime/client/dev-overlay/plugins/audit/a11y.ts
pnpm-lock.yaml

- The package `axobject-query` is CJS and Vite doesn't ESM-ify it, can't add to `optimizedDeps.include`.
- Maybe there's something we can do to shim but removing for 4.0 release.
- N/A
N/A

Remove audit role that depends on CJS package

---

packages/astro/src/runtime/client/dev-overlay/overlay.ts

- I ran into a problem where requestIdleCallback would never fire (or, would take a very long time to fire).
- When [checking out MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback), I saw this blurb: "Note: A timeout option is strongly recommended for required work, as otherwise it's possible multiple seconds will elapse before the callback is fired."
- Adds a timeout similar to the `setTimeout()` logic we already have for Safari, in case `requestIdleCallback` is taking too long.
- Small change, don't think it's possible to test
- N/A

[Toolbar] fix issue where requestIdleCallback would take forever

---

packages/astro/src/runtime/client/dev-overlay/entrypoint.ts
packages/astro/src/runtime/client/dev-overlay/overlay.ts
packages/astro/src/runtime/client/dev-overlay/plugins/audit/index.ts
packages/astro/src/runtime/client/dev-overlay/plugins/utils/highlight.ts
packages/astro/src/runtime/client/dev-overlay/plugins/xray.ts
packages/astro/src/runtime/client/dev-overlay/ui-library/highlight.ts
packages/astro/src/runtime/client/dev-overlay/ui-library/tooltip.ts

- Sites that set their own `z-index` had trouble display the xray/audit highlights. 
- As a result, audits weren't working on astro.build due to a `z-index: 20` somewhere on the page and the one other template that I tried.
- This PR also simplifies the more complex dynamic z-index calculation in favor of a more simple approach of Large Numbers Always™️. If there's any concern here or missing context, lmk! 
- Visual changes only, tested manually
- N/A

[Toolbar] fix z-index on dev overlay tooltips and highlights

---

packages/astro/src/runtime/client/dev-overlay/overlay.ts

- Stop propagating click events inside the toolbar
- This fixed an issue where the website I was on was listening for document click events to close a modal. This captured my toolbar click, which then closed the modal before I could inspect it.
- I checked playwright and it doesn't look like it can detect/listen for events. If anyone has ideas, LMK! 
- N/A

[Toolbar] capture click events inside the toolbar

---

packages/astro/src/runtime/client/dev-overlay/plugins/xray.ts

- Solid (and others?) pass an internal `data-astro-cid-XXXXXX` prop to their components when using client-side islands. This is an internal implementation detail, and should be filtered out of the overlay to avoid confusion.
- N/A
- N/A

[Toolbar] Filter out internal island props

---

packages/integrations/markdoc/package.json

Revert to 0.7.2 (current latest version) so the next release is 0.8.0. It was bumped as 1.0.0 by changesets because of the peer dep range auto-update. I've updated that to `"astro": "^3.0.0 || ^4.0.0"`
Verified that it works with `pnpm changeset version` locally, which bumps the next version as 0.8
n/a

Release markdoc integration as v0.x

---

.changeset/angry-cows-hug.md
packages/astro/src/core/build/generate.ts

This PR fixes logs the emitted during the build
Tested on the starlight template, locally:

fix: logging build trace of pages

---

.changeset/poor-otters-doubt.md
packages/upgrade/src/actions/verify.ts
packages/upgrade/src/index.ts
packages/upgrade/test/verify.test.js

- Previously, `@astrojs/upgrade` would fail when packages weren't found in the NPM registry.
- This PR improves dependency handling so that packages without semver versions are ignored.
- In effect, this change ensures that dependencies using `link:`, `github:`, and `workspace:` protocols are ignored. It's also implemented in a future-proof way by only allowing valid semver identifiers rather than allow-listing known protocols.
- ✅ Changeset added
New test suite added for the `verify` step, unit testing this function's behavior specifically
N/A, bug fix

Improves `@astrojs/upgrade` dependency handling

---

.changeset/beige-gorillas-camp.md
packages/astro/package.json
pnpm-lock.yaml

- `vitefu` added support for Vite 5 in a patch but that isn't always picked up by package managers.
- Bumping `vitefu` to the minimum version that supports Vite 5.
- This will avoid `peerDependency` warnings that have been reported
N/A
N/A

Update `vitefu` version

---

.changeset/selfish-lamps-build.md
packages/integrations/vue/src/index.ts
packages/integrations/vue/test/app-entrypoint.test.js
packages/integrations/vue/test/fixtures/app-entrypoint-no-export-default/src/pages/_app.ts
packages/integrations/vue/test/fixtures/app-entrypoint-src-absolute/astro.config.mjs
packages/integrations/vue/test/fixtures/app-entrypoint-src-absolute/package.json
packages/integrations/vue/test/fixtures/app-entrypoint-src-absolute/src/components/Bar.vue
packages/integrations/vue/test/fixtures/app-entrypoint-src-absolute/src/components/Circle.svg
packages/integrations/vue/test/fixtures/app-entrypoint-src-absolute/src/components/Foo.vue
packages/integrations/vue/test/fixtures/app-entrypoint-src-absolute/src/pages/index.astro
packages/integrations/vue/test/fixtures/app-entrypoint-src-absolute/src/vue.ts
pnpm-lock.yaml

- Fixes #9330!
- We used `hasDefaultExport`, which is a Rollup API. This is available in `astro build` but not during `astro dev`. 
- Now uses a custom method compatible with either `astro dev` or `astro build`
Our previous test suite was missing `astro dev` tests, leading to incompatible behavior getting merged and released.
This PR adds an `astro dev` test while ensuring the previous tests are still passing
Bug fix only

Vue: Remove `hasDefaultExport` check from `appEntrypoint` logic

---

.changeset/rich-keys-rescue.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/dialog.astro
packages/astro/e2e/view-transitions.test.js

- View Transitions no longer cause navigation due to events emitted from `<form method="dialog">`
- Resolves https://github.com/withastro/astro/issues/9320
Added new E2E test confirming new requests are not sent when modal is opened and then closed using a button/form.
Documentation does not need to be updated. Behavior should now match that of Astro 3.

Prevent client-side navigation for method="dialog"

---

.changeset/strange-parrots-promise.md
packages/astro/src/runtime/client/dev-overlay/plugins/settings.ts

- Fixed the log message to correctly display 'enabled' and 'disabled' when toggling 'Disable notifications' in the Toolbar.
- Ran examples locally and verified that the log message has been corrected.
- N/A

Fix log message for `Disable notifications`

---

.changeset/modern-mice-shout.md
packages/astro/src/core/messages.ts
packages/astro/src/vite-plugin-astro-server/route.ts

- Fix issue where 404 & 500 status codes were logged as "[200]"
- This happened because the log wasn't respecting the `status` override
- N/A, fairly internal change that only impacts a log message
- N/A

Fix issue where 404/500 status codes were logged as "[200]"

---

.changeset/nasty-carrots-study.md
packages/integrations/vercel/package.json

- The Vercel adapter's peerDepedency has to be manually updated.
- This makes it work in 4.0 apps.
N/A
N/A

Define the Vercel adapter's peerDependency

---

.changeset/young-spoons-rescue.md
packages/integrations/vercel/package.json
packages/integrations/vercel/src/serverless/middleware.ts

Vercel's Edge Middleware allows async functions so should the Astro wrapper.
Note: I bumped the minor version in this commit. Was I supposed to do that? It wasn't clear in the CONTRIBUTE.md
No tests needed. This is a very small change that doesn't break anything. The `await` keyword in JavaScript waits for a Promise to resolve, if it is a Promise. Otherwise, `await` returns the value it's being called on.
No docs added. This is just a bugfix.

Allow async functions in the Vercel edge middleware integration

---

.changeset/gorgeous-buttons-remember.md
packages/markdown/remark/package.json

- Removes peerDependencies from `@astrojs/markdown-remark`

chore: markdown-remark peerDependencies

---

.changeset/shiny-glasses-care.md
packages/astro/src/core/build/index.ts
packages/astro/src/core/build/plugin.ts
packages/astro/src/core/build/static-build.ts
packages/astro/src/core/build/util.ts
packages/astro/test/astro-basic.test.js
packages/astro/test/fixtures/astro-basic/src/pages/get-static-paths-with-mjs/[...file].js

Fixes https://github.com/withastro/astro/issues/9154
Instead of globbing `**/*.mjs` to remove the unused SSR outputs, we can use the Rollup output information to remove them instead. This way we only remove the `.mjs` files that are part of Rollup, and not the ones generated by pages/endpoitns.
Added a test from the issue
n/a. bug fix.

Preserve generating routes that end with .mjs

---

.changeset/sweet-deers-watch.md
packages/integrations/vercel/README.md

Corrects code samples where the `output` property did not match the adapter usage. Also removes reference to using the removed `/edge/` adapter.
(I guess this might need a changeset to update at NPM?)
No tests, docs.
Just docs.

[docs] Vercel README - update code samples

---

examples/framework-vue/src/components/Counter.vue

- Refactor the Vue example to use the [now-recommended](https://vuejs.org/api/sfc-script-setup.html) `<script setup>` syntax.
- Tested locally by running the updated example.
- N/A because this is an update of example.

Refactor Vue example to use `<script setup>`

---

.changeset/honest-bats-own.md
packages/astro/src/core/build/buildPipeline.ts
packages/astro/test/i18n-routing.test.js

Closes https://github.com/withastro/astro/issues/9354
Added a new test, and tested locally.

fix(i18n): correctly pull the ssr entry during build

---

.changeset/young-rats-sin.md
packages/astro/package.json
packages/astro/src/cli/add/index.ts
pnpm-lock.yaml

- We didn't have an issue to track this but it's come up a few times in Discord
- `astro add svelte` would install `5.0.0-next.22`, which is not a stable version
- This PR refactors `astro add` installation logic to actually resolve the most recent stable version of packages before installing. We do this by querying the registry for all versions and filtering out any prereleases.
- The custom `peerDependency` ~~parser~~ regex has also been removed in favor of `semver`! It was already a dependency, so we might as well use it.
- If users do want to install a prerelease, they can do so manually.
Tested manually because `astro add` has ~~almost~~ no test coverage. Woooooo!
Bug fix only

Ensure `astro add` only installs stable versions

---

.changeset/dull-masks-eat.md
packages/astro/astro-jsx.d.ts

Some newer attributes were missing from our definition, this fixes that.
Fix https://github.com/withastro/astro/issues/9371
Tested manually!
N/A

Add missing global attributes to JSX definition

---

.changeset/rotten-socks-help.md
packages/integrations/vercel/src/lib/redirects.ts
packages/integrations/vercel/test/redirects.test.js

- Closes #9260
Added a test case

fix(vercel): handle dots in source path for redirects

---

.changeset/fifty-pets-hunt.md
packages/astro/src/integrations/astroFeaturesValidation.ts

Adds the feature name to logs about feature deprecation / experimental status, so users know what feature the log is about.
Didn't add any tests, because I couldn't find any test for this part of the code. Let me know where to add a test, and i'm happy to write one!
No docs update needed, because this doesn't change any behaviour that applications depend on.

fix: mention which feature is experimental/deprecated

---

.changeset/smart-colts-think.md
packages/astro/src/core/create-vite.ts
packages/astro/src/vite-plugin-fileurl/index.ts
packages/astro/test/astro-basic.test.js
packages/astro/test/fixtures/astro-basic/src/pages/fileurl.astro
packages/astro/test/fixtures/astro-basic/src/strings.js

- Wanted to support this pattern in integrations: `addDevToolbarApp(new URL('./plugin.ts', import.meta.url))`
- This doesn't currently work because we directly pass this value into the virtual module.
- Vite does not support file URLs.
- A Vite plugin is the answer! Maybe we can talk them into adding this to core.
- Test added
N/A, bug fix

Allow file URLs to be used as import specifiers

---

.changeset/brown-apricots-kick.md
packages/astro/src/assets/internal.ts
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image-errors/src/pages/get-image-undefined.astro

- `getImage({ src: undefined })` should throw a good error. Now it does.
- Existing test case was skipped, now its not.
N/A, bug fix

Error when getImage() is passed an undefined src

---

.changeset/lorem-ipsum-dolor
packages/astro/src/core/build/static-build.ts

We had an issue where some styles were not loading in the static build. We managed to pinpoint it to this - and noticed `clientBuild` calls this function on `config.outDir` - but the mutations don't. I'm not 100% sure this is the correct fix, but it certainly fixed it for us
Local testing & repo tests
Fixes static builds when `config.outDir` is located outside of the astro project

Fix static build when out dir is not within the cwd

---

.changeset/curvy-lobsters-crash.md
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/vite-plugin-astro-server/error.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/request.ts

- Unhandled rejections, caused by having a promise that rejects but has no `.catch()`, will crash the dev server. We can prevent it using `process.on('unhandledRejection')`.
---
- Manually in demo project. See above screenshot. Server does not crash, good error message is displayed.
N/A, bug fix

Handle unhandledrejections in the dev server

---

.changeset/angry-avocados-live.md
packages/astro/src/transitions/router.ts

- Binds the `pushState` and `replaceState` methods which break Partytown with Firefox.
- Fixes https://github.com/withastro/astro/issues/8862
- Manually
N/A, bug fix

Prevent Partytown from hijacking history API

---

.changeset/gentle-chefs-glow.md
packages/astro/src/core/routing/manifest/create.ts

Updates warning e.g. 
`Redirecting to an external URL is not officially supported: /external -> [object Object]` 
to 
`Redirecting to an external URL is not officially supported: /external -> https://example.com`
`pnpm run test:match "core"`
N/A

Fixes warning for external URL redirects

---

packages/astro/components/Picture.astro
packages/astro/src/assets/build/generate.ts
packages/astro/src/assets/endpoint/config.ts
packages/astro/src/assets/endpoint/generic.ts
packages/astro/src/assets/endpoint/node.ts
packages/astro/src/assets/internal.ts
packages/astro/src/assets/services/service.ts
packages/astro/src/assets/utils/imageKind.ts
packages/astro/src/assets/utils/index.ts
packages/astro/src/assets/utils/remotePattern.ts
packages/astro/src/assets/utils/transformToPath.ts
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/dev/container.ts

In the way of trying to solve https://github.com/withastro/adapters/pull/58, I realized there's some instances where the image service could get imported by accident because some utils were next to the code that loads it. This refactor move away everything unrelated to that elsewhere, so that people and adapters can import the utilities without anything else coming in by accident. 
This doesn't unblock the linked PR just yet, some other bundling nonsense is in the way, however it's a step forward!
Tests should pass, this is just a refactor!
N/A

refactor(assets): Move things around to avoid importing image service unnecessarily

---

examples/ssr/src/pages/api/cart.ts

I attempt to run the ssr demo, but I found the error:
```
01:34:54 [ERROR] Cannot read properties of undefined (reading 'value')
Stack trace:
at Module.GET (/Users/zhangpeng/my/astro/examples/ssr/src/pages/api/cart.ts:5:36)
[...] See full stack trace in the browser, or rerun with --verbose.
01:34:54 [ERROR] Cannot read properties of null (reading 'items')
Stack trace:
at /Users/zhangpeng/my/astro/examples/ssr/src/components/Header.astro:7:24
[...] See full stack trace in the browser, or rerun with --verbose.
```
this is my step:
```
git clone && cd ...
pnpm install
pnpm run build
cd examples/ssr
pnpm install
pnpm start
```

fix: error in ssr demo when init

---

.changeset/breezy-hairs-yell.md
packages/integrations/react/server.js

Fixes #9402
Preact's `forwardRef` from `preact/compat` can return function components which forward refs, which React does not support (React forward ref components are always objects, never functions, even when `forwardRef` is wrapping a function component).
I have not tested this change. What would qualify as a sufficient test as far as the astro maintainers are concerned?
No need for docs, this just prevents the React integration from picking up Preact components that it cannot render.

Fix Preact Forwarded Ref components not working in astro files when React integration is enabled

---

.changeset/friendly-tables-worry.md
packages/astro/src/@types/astro.ts
packages/astro/src/cli/add/index.ts

Closes https://github.com/withastro/astro/issues/9459. With the new version of the Astro adapter, `@astrojs/netlify` is the recommended import.
Didn't test manually, but expecting it to still work given the change.
don't think we need docs changes for this.

fix: update netlify import

---

.changeset/selfish-rings-occur.md
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/core/middleware/loadMiddleware.ts
packages/astro/src/vite-plugin-astro-server/route.ts

Closes https://github.com/withastro/astro/issues/9444
I locally tested the bug using the reproduction of the issue:
N/A

fix: handle middleware loading error

---

.changeset/silly-cycles-clap.md
packages/astro/src/core/redirects/helpers.ts
packages/astro/test/redirects.test.js

- Fixes #8914
- Added 3 cases to [redirects.test.js](https://github.com/withastro/astro/pull/9089/files#diff-f0e8bf856624a391d496c98638e77e91ca1f9ad3a3c30d4d14ff722ff6e6da97)

fix(redirects): handle non-verbatim targets

---

.changeset/warm-bats-eat.md
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/test/ssr-hoisted-script.test.js

Handles #9425 
Confirmed while debugging building of a sample app that assumption of a `.js` file extension is the root cause of wrong asset paths. Unit tests added.
N/A

fix: handle external hoisted scripts correctly

---

.changeset/khaki-ducks-give.md
packages/astro/e2e/fixtures/view-transitions/src/pages/one.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/seven.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/transitions/router.ts

The syntax of the Content-Type header specified by the [HTTP Semantics RFC](https://www.rfc-editor.org/rfc/rfc9110#appendix-A) is as follows:
```
Content-Type = media-type
OWS = *( SP / HTAB )
media-type = type "/" subtype parameters
subtype = token
type = token
parameter = parameter-name "=" parameter-value
parameter-name = token
parameter-value = ( token / quoted-string )
parameters = *( OWS ";" OWS [ parameter ] )
tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." /
"^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA
token = 1*tchar
```
The `;` that marks the start of the parameters may, even though not recommended, be preceded by any number of white spaces. The previous implementation of the `fetchHTML` function would not accept a header in that form and do full page reload. …

Fix transitions with non-recommended headers

---

.changeset/wise-wasps-sell.md
packages/astro/src/core/build/static-build.ts

Closes https://github.com/withastro/astro/issues/9450
I locally tested that the file isn't there anymore after the build.
N/A

fix: remove the manifest file from the `dist/` folder

---

.changeset/popular-meals-yell.md
packages/astro/src/core/build/generate.ts
packages/astro/src/core/logger/core.ts
packages/astro/src/core/logger/node.ts

Closes https://github.com/withastro/astro/issues/9335
I added a new option to the logger, that allows us to **not** add a new line at the end of a logging message.
This becomes useful when we build the pages, so we can log the page we are about to build, and then append the timing at the end.
I used the docs repo to test it. Here's a small video
https://github.com/withastro/astro/assets/602478/627a2f23-2b8d-4a23-8327-f50a2a42c962
N/A

chore: smoother logging when building pages

---

.changeset/shy-knives-unite.md
packages/astro/package.json
pnpm-lock.yaml

I'm not too sure, but I think this is the cause of all the recents Sharp-related issues like https://github.com/withastro/astro/issues/9345
Since Sharp changed its installation method in its latest version, mixing versions can get weird and certain package managers seems to have issues handling it. I've never been able to reproduce any issues, so I can't really tell what the problem is, nonetheless I believe this should fix it!
Can't really test if it fixes the issue or not, but it should still work.
N/A

fix(deps): Update Sharp optionalDep version

---

packages/astro/src/@types/astro.ts

Adds a short note (`This value may be set by your adapter for you.`) to the `build.format` docs.
Not tested. In response to a [Docs issue](https://github.com/withastro/docs/issues/4807) where someone was surprised this value had been changed by installing an adapter.
Only docs!

[docs] update build.format with note an adapter may set this value

---

.changeset/beige-zebras-ring.md
packages/astro/astro-jsx.d.ts

This makes it possible to write `<button autocomplete="off" disabled>Action</button>` without getting type errors in Astro components.
The change extends the JSX type of `ButtonHTMLAttributes` to include the “nonstandard and Firefox-specific” `autocomplete`. While nonstandard, for dynamic front-ends / forms it is often required to include it because of the way Firefox caches disabled-state. (E.g. [this StackOverflow question and answer](https://stackoverflow.com/a/5994462).)
See documentation of the attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#autocomplete
No tests are added, this is a singular extra attribute to be defined in the JSX types.
No docs are added, this should have no effect on Astro usage outside of type-checked components.

Add autocomplete to button JSX type

---

.changeset/small-emus-deny.md
packages/astro/e2e/dev-overlay.test.js
packages/astro/e2e/fixtures/dev-overlay/src/pages/tooltip-position.astro
packages/astro/src/runtime/client/dev-overlay/plugins/utils/highlight.ts

- This PR aims to fix [#9346](https://github.com/withastro/astro/issues/9346)
- [`attachTooltipToHighlight`](https://github.com/withastro/astro/blob/eb36e95596fcdb3db4a31744e910495e22e3af84/packages/astro/src/runtime/client/dev-overlay/plugins/utils/highlight.ts#L47) already [handled the vertical part](https://github.com/withastro/astro/blob/main/packages/astro/src/runtime/client/dev-overlay/plugins/utils/highlight.ts#L60-L66). This PR deals with the horizontal part
- I'm not sure whether this PR should include a changeset or not. Please let me know if it's needed 🙏
| ------ | ----- |
| ![before](https://github.com/withastro/astro/assets/40516784/77fce1db-0155-40b5-9709-1aed5d7314cc) | ![after](https://github.com/withastro/astro/assets/40516784/c28f737d-61a8-474d-b4ae-5c …

Prevent dev toolbar tooltip from overflowing

---

.changeset/forty-actors-wash.md
packages/integrations/svelte/client.js

Fixes https://github.com/withastro/astro/issues/9508
The existing console filter looked for class attributes. This change adds a check for warnings related to data attributes as well.
Tested by validating the change in a simple Astro app with a Svelte counter component.
Before the fix, the console output contains the following warning:
```
<Counter> was created with unknown prop 'data-astro-cid-j7pv25f6'
```
After patching client.js in node_modules and clearing the cache:
```
rm -rf ./node_modules/.vite
```
Run the app again
```
npm run dev
```
The console output is now clear, without any warnings.
N/A - no docs need to be …

Filter out Svelte's unknown data prop warnings

---

.changeset/rude-deers-turn.md
packages/integrations/tailwind/package.json
packages/integrations/tailwind/src/index.ts
packages/integrations/tailwind/test/basic.test.js
packages/integrations/tailwind/test/fixtures/basic/astro.config.js
packages/integrations/tailwind/test/fixtures/basic/package.json
packages/integrations/tailwind/test/fixtures/basic/src/pages/index.astro
packages/integrations/tailwind/test/fixtures/basic/tailwind.config.js
pnpm-lock.yaml

close https://github.com/withastro/astro/issues/9526
Add `tailwindcss/nesting` support via an option the user can enable. https://tailwindcss.com/docs/using-with-preprocessors#nesting
Added new tests
TBA in docs repo. And there's also the added jsdoc.

Add tailwindcss nesting support

---

.changeset/old-goats-occur.md
packages/astro/src/core/routing/params.ts
packages/astro/src/vite-plugin-astro-server/request.ts
packages/astro/test/ssr-params.test.js

Fix https://github.com/withastro/astro/issues/7374
Prevent unnecessary decoding in certain places. I'll add comments below to explain it.
Added a test
n/a. bug fix.

Prevent double uri decoding

---

.changeset/blue-ladybugs-march.md
packages/astro/src/content/vite-plugin-content-assets.ts
packages/astro/src/vite-plugin-astro-server/css.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/0-css.test.js
packages/astro/test/units/dev/styles.test.js

fix https://github.com/withastro/astro/issues/6885
When a `.module.css` file is imported by both an Astro file and framework component, it gets inlined by Astro to prevent a FOUC. However, the way we inline it before (using a `link`) is not how Vite handles it when it's loaded in the client (via the framework component). Vite expects the CSS module to be a `style` tag inlined.
This PR uses a `style` tag instead to fix it, which potentially causes different ordering with other style tags now (since CSS modules used to be links and they're rendered separately), but since we had changed the ordering before at https://github.com/withastro/astro/pull/8877 (which I think worked fine?), I think we can tweak this a little bit more.
Updated tests
n/a. bug fix.

Fix duplicated CSS modules inlining

---

.changeset/tidy-dogs-remain.md
packages/astro/src/@types/astro.ts
packages/astro/src/runtime/server/endpoint.ts

- Closes #9496
- improve messaging for getting the case wrong
Does not affect behavior, just messaging - existing tests should pass.

qol(routing): warn when api route method doesn't match the casing of an export

---

.changeset/gold-zebras-burn.md
packages/astro/src/content/vite-plugin-content-virtual-mod.ts
packages/astro/src/core/errors/errors-data.ts

- An error message
- https://discord.com/channels/830184174198718474/1070481941863878697/1187153439139053688
Does not affect behavior, existing tests should pass.

fix(content): helpful message for DuplicateContentEntry

---

scripts/cmd/build.js

Debugging and following errors on Astro internals when contributing currently requires looking at transpiled JS and manually finding the original TS code. Errors are reported with their transpiled positions and debug points only work on transpiled JS.
This PR just enables sourcemaps for the dev builds, allowing for debuggers (in IDEs or using Chrome's debug tools) to refer to the original TS files when stepping through code and also for Errors to report the position in the original code (so long as the option `--enable-source-maps` is passed to Node)
How an error looks without source maps:
```
Error: Example error
at file:///home/lotus/IsoWorkspaces/OSS/astro/astro/packages/astro/dist/core/routing/manifest/create.js:325:11
at Array.forEach (<anonymous>)
at createRouteManifest …
```

Enable source map on dev builds

---

.changeset/olive-sloths-brush.md
packages/integrations/node/src/nodeMiddleware.ts

- Fix for the server crashing on a promise rejection within the stream.
- `node packages/integrations/node/test/fixtures/errors/dist/server/entry.mjs`
- `curl -i localhost:4321/in-stream`

fix(node): prevent crash on stream error

---

.changeset/yellow-yaks-promise.md
packages/integrations/vercel/src/serverless/adapter.ts

- Prevents build failure on node 21.
Ran build on node 21.

fix(vercel): prevent build failure with node 21

---

.changeset/ninety-buses-occur.md
packages/integrations/vue/src/index.ts
packages/integrations/vue/test/app-entrypoint.test.js
packages/integrations/vue/test/fixtures/app-entrypoint-async/astro.config.mjs
packages/integrations/vue/test/fixtures/app-entrypoint-async/package.json
packages/integrations/vue/test/fixtures/app-entrypoint-async/src/components/Bar.vue
packages/integrations/vue/test/fixtures/app-entrypoint-async/src/components/Baz.vue
packages/integrations/vue/test/fixtures/app-entrypoint-async/src/components/Foo.vue
packages/integrations/vue/test/fixtures/app-entrypoint-async/src/pages/_app.ts
packages/integrations/vue/test/fixtures/app-entrypoint-async/src/pages/index.astro
pnpm-lock.yaml

Fixes #9557, a regression which has broken the (admittedly niche) use case of an asynchronous `appEntrypoint` function. The changes introduced in #9362 led the potentially asynchronous setup method to be wrapped in a synchronous function, making the `await setup()` in `[server,client].js` more-or-less useless. This PR makes the virtual module's wrapper method `async` as well, bringing back support for asynchronous `appEntrypoint`s.
A simple test for this scenario was added, which leverages two components registered globally in the `appEntrypoint` script separated by a simulated asynchronous call to ensure that registration works correctly following an async call within an async entrypoint script.
Not sure if docs will be needed as this is a pretty niche use case, but it is certainly nice …

Fix asynchronous `appEntrypoint` support

---

.changeset/sixty-bugs-unite.md
packages/astro/src/cli/preview/index.ts

Ref: https://github.com/withastro/astro/issues/9133#issuecomment-1872238536
We support those flags for all adapters as we collect them here
https://github.com/withastro/astro/blob/e496b2e3b84b673b81c872dad9a6b3f9dd32396a/packages/astro/src/core/preview/index.ts#L20-L22
And then pass them to adapters at:
https://github.com/withastro/astro/blob/e496b2e3b84b673b81c872dad9a6b3f9dd32396a/packages/astro/src/core/preview/index.ts#L59-L68
Tested manually in the examples app:
```
> @example/ssr@0.0.1 preview /Users/bjorn/Work/oss/astro/examples/ssr
> astro preview "--port" "4444" "--host"
15:54:49 [@astrojs/node] Preview server listening on 
local: http://localhost:4444 
network: http://192.168.68.55:4444
```
```
> @example/basics@0.0.1 preview /Users/bjorn/Work/oss/astro/examples/basics
> astro …
```

Document --host and --port flag for preview

---

.changeset/plenty-dingos-relax.md
packages/astro/e2e/fixtures/i18n/astro.config.mjs
packages/astro/e2e/fixtures/i18n/package.json
packages/astro/e2e/fixtures/i18n/src/pages/index.astro
packages/astro/e2e/i18n.test.js
packages/astro/src/i18n/index.ts
packages/astro/src/i18n/vite-plugin-i18n.ts
pnpm-lock.yaml

This PR gives a new implementation for the `getLocaleByPath` function.
It also fixes a parameter name in another `getLocaleByPath` function, one that is exposed to users.
According to the [Internationalization guide](https://docs.astro.build/en/guides/internationalization/#retrieve-the-locale-for-a-custom-path), the following behavior is expected:
For a given configuration:
```
{
i18n: {
defaultLocale: "en",
locales: ["en", "es", "fr", {
path: "portugues",
codes: ["pt-AO", "pt", "pt-BR"]
}]
}
}
```
The function is expected to behave as:
```js
import { getLocaleByPath } from "astro:i18n";
console.log(getLocaleByPath("en")) // will log "en"
console.log(getLocaleByPath("fr")) // will log "fr"
console.log(getLocaleByPath("portugues")) // will log "pt-AO"
```
However, the behavior for the …

Implement i18n's `getLocaleByPath` function

---

.changeset/tall-mayflies-deliver.md
packages/astro/src/cli/add/index.ts

I was surprised not to find Starlight in the astro CLI, so I added it. :)
This adds the Starlight to the options displayed by the CLI under a new category of "Documentation Frameworks".
- Adds Startlight to CLI's displayed options
I'm not sure if there are docs for the CLI which might also need to be added...

Add 'starlight' to displayed options under 'add' option in CLI

---

.changeset/few-days-relate.md
packages/astro/src/vite-plugin-astro-server/error.ts

The telemetry for unhandled errors are a LOT, so removing them for now. I didn't uncomment it out as I don't quite see another way we could enable it in the future.
It's a one-line removal, so should still work like before.
n/a. not docs related.

Remove telemetry for unhandled errors

---

.changeset/breezy-eyes-teach.md
packages/astro/src/transitions/router.ts

Firefox clears the history state on same page navigation, which later breaks history navigation.
This fix prevents that.
From discord user mcoms on #support > View Transitions back/forward not working in Firefox for fragment links:
> In Firefox, on all ViewTransition fallbacks but none, going back to a fragment link (#about) from another page does not work. It stays on the current page without navigating back. For example, if I have a page with a link /#about and then I go to /faq, I press back and the URL changes to /#about but the content is still /faq. This happens until I reach that does not contain a # in the URL, or if the # was initially navigated to. It even doesn't work if the # link had data-astro-reload={true}.
SvelteKit had a [similar …

Fix history navigation to hash fragment on Firefox when using view transitions

---

packages/astro/src/transitions/router.ts

reverted use of history.replaceState() to replaceState()
none.
n.a.

Fix history usage of PR 9563

---

.github/workflows/check-merge.yml
.github/workflows/main.yml
.github/workflows/release.yml

I've noticed some workflows are showing warning about `set-output` deprecation.
This PR updates all workflows that are using `set-output` to use the new environment files instead.
This has been done following GitHub's ["GitHub Actions: Deprecating save-state and set-output commands"](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) blog post and instructions on updating.
I've run syntax checks on the updated workflow files.
Their behavior should not change.
The `check-merge.yml` workflow should run on this PR, succeed, and the step "Check if any changesets contain minor changes" should not show any warning anymore.
The `main.yml` and `release.yml` workflows won't run on this PR. I don't know how to rigorously test them further after …

Patch `set-output` deprecation in workflows

---

.changeset/six-bottles-mix.md
packages/astro/src/cli/add/index.ts
packages/astro/src/cli/check/index.ts
packages/astro/src/cli/index.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/dev/dev.ts
packages/astro/src/core/preview/index.ts
packages/astro/src/core/sync/index.ts
packages/astro/src/core/util.ts

fix https://github.com/withastro/astro/issues/9574
We set a fallback `process.env.NODE_ENV` in the CLI, but we didn't set it for manual JS API calls, causing cases where `build()` has `NODE_ENV` `"development"` instead due to we calling the Vite server to load the config, before we call the Vite build.
https://github.com/withastro/astro/blob/e496b2e3b84b673b81c872dad9a6b3f9dd32396a/packages/astro/src/cli/index.ts#L134-L138
This PR moves the above code to each individual JS API calls to fix it.
Tried adding a unit test, but it's tricky to test `NODE_ENV` without actually executing the JS APIs, which can be a bit slow, and needs duplicated work from `test-utils.js` to tear it down.
I manually tested with the repro for now.
n/a. `NODE_ENV` quirks prominently affects `import.meta.env.DEV` and …

Set default NODE_ENV for JS API

---

.changeset/slow-kiwis-own.md
packages/astro/astro-jsx.d.ts

Adds a `CSSProperties` interface to the `style` attribute that consumers can extend to add their own custom properties. This matches the approach from other frameworks, e.g React and SolidJS.
I can't seem to find tests for the types, but please do point me in the right direction if they exist somewhere.
https://github.com/withastro/astro/assets/175330/15a84647-8d15-4d5f-8948-cacc7d3ddd95
https://github.com/withastro/docs/pull/6062

feat: add extendable `CSSProperties` interface

---

.changeset/funny-lobsters-promise.md
packages/astro/src/core/routing/manifest/create.ts
packages/astro/test/units/routing/trailing-slash.test.js

- Closes #9206 
- trailingSlash settings now apply to endpoints same as pages.
Added a unit test.
Does not affect behavior.

fix(routing): trailingSlash on endpoints

---

examples/component/tsconfig.json
scripts/smoke/check.js

close https://github.com/withastro/astro/issues/8786
Add `jsx: 'preserve'` to prevent TS errors. I also updated the examples check script a bit so it works better locally.
Ran `pnpm test:check-examples` locally.
I also noticed that the `with-markdoc` example has a similar `compilerOptions` config, so I think this PR change should also work correctly when e.g. you choose the strictest tsconfig.
n/a. bug fix to the template.

Fix ts errors for component template

---

.changeset/afraid-socks-rescue.md
packages/astro/src/cli/add/index.ts

fix https://github.com/withastro/astro/issues/7925
Improve error reporting if fail to install deps in `astro add`
Tested in the repro manually:
Note that the "Command failed with E..." is now logged.
n/a. bug fix.

Improve astro add deps error reporting

---

.changeset/lemon-garlics-pretend.md
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/src/static/adapter.ts

- Closes #7573
- Closes #9590
- Deprecated API: https://vercel.com/docs/speed-insights/api
- Migration: https://vercel.com/docs/speed-insights/migrating-from-legacy
- New library: https://vercel.com/docs/speed-insights/quickstart
Does not affect behavior.
- https://github.com/withastro/docs/pull/6082

chore(vercel): deprecate `speedInsights`

---

.changeset/fair-bottles-lie.md
packages/astro/src/@types/astro.ts

To set up the second generic of APIContext, we added one more generic to APIRoute.
fix https://github.com/withastro/astro/issues/9612
I tested it on a personal project and it worked well.

feat: Add APIRoute second generic

---

.changeset/slow-impalas-taste.md
packages/astro/src/@types/astro.ts
packages/astro/src/assets/services/sharp.ts

ref https://github.com/withastro/astro/pull/9546#issuecomment-1877736238
I mistyped `limitInputPixels`. It should be `number | boolean` as accepted by Sharp as well.
n/a. Should still work
Updated jsdoc as well.

Fix limitInputPixels type

---

packages/astro/src/@types/astro.ts

Updates docs here at the source to reflect a change that was added to the docs file directly.
Also updates a version number for a feature added in 4.1 minor release.
no tests, just docs!
just docs!

[docs] update config reference

---

.changeset/brown-turtles-invite.md
packages/integrations/vercel/src/static/adapter.ts
packages/integrations/vercel/test/fixtures/static/astro.config.mjs
packages/integrations/vercel/test/fixtures/static/package.json
packages/integrations/vercel/test/fixtures/static/src/pages/404.astro
packages/integrations/vercel/test/fixtures/static/src/pages/one.astro
packages/integrations/vercel/test/fixtures/static/src/pages/two.astro
packages/integrations/vercel/test/static.test.js
pnpm-lock.yaml

- Closes #9578
Added `static.test.js` along with a fixture.
Does not affect behavior.

fix(vercel): include 404.html as fallback in the static adapter

---

.changeset/odd-rivers-learn.md
packages/integrations/vue/src/index.ts
packages/integrations/vue/test/app-entrypoint-css.test.js
packages/integrations/vue/test/fixtures/app-entrypoint-css/astro.config.mjs
packages/integrations/vue/test/fixtures/app-entrypoint-css/package.json
packages/integrations/vue/test/fixtures/app-entrypoint-css/src/app.ts
packages/integrations/vue/test/fixtures/app-entrypoint-css/src/components/Bar.vue
packages/integrations/vue/test/fixtures/app-entrypoint-css/src/components/Foo.vue
packages/integrations/vue/test/fixtures/app-entrypoint-css/src/main.css
packages/integrations/vue/test/fixtures/app-entrypoint-css/src/pages/index.astro
packages/integrations/vue/test/fixtures/app-entrypoint-css/src/pages/unrelated.astro
pnpm-lock.yaml

- Closes #6827, closes PLT-1346
- Fixes bundling for styles referenced in the Vue integration's `appEntrypoint` file.
- Rather than hacking Astro's internals to treat the virtual entrypoint as a special file, this PR adds a side-effectual import to every `.vue` component. It may not be the cleanest method, but this does allow Astro to associate styles referenced by the `appEntrypoint` with pages where Vue components are rendered.
- This is probably fine to release as a patch
New test suite added for dev and build behavior
Tested manually, too

Ensure `appEntrypoint` is referenced in Vue components

---

.changeset/dirty-monkeys-bow.md
packages/integrations/vue/client.js

fix https://github.com/withastro/astro/issues/9617
The `delete props['class']` was introduced in https://github.com/withastro/astro/pull/1406/commits/1103cb1f9d2a2077f65a0d08aee67ee9bf0e9540, but I'm not sure why. But this should work fine today without the deletion.
Existing tests should pass. Also tested this fix with the repro.
n/a. bug fix.

Fix class property Vue hydration error

---

.changeset/shy-spoons-sort.md
packages/astro-rss/src/index.ts
packages/astro-rss/src/schema.ts
packages/astro-rss/test/pagesGlobToRssItems.test.js

- Close #9577 
Updated tests
https://github.com/withastro/docs/pull/6154

fix(rss): make title optional if description is provided

---

.changeset/cool-foxes-talk.md
packages/astro/src/core/app/createOutgoingHttpHeaders.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/node.ts
packages/astro/test/astro-cookies.test.js
packages/astro/test/client-address.test.js
packages/astro/test/units/app/headers.test.js

This came from working on 5 adapters over the past month. The logic for dealing with cookies and `node:http` is always duplicated. `NodeApp` takes care of converting the request, but the logic of converting response is duplicated across the node and the vercel adapters. Cookies had to be handled manually for legacy reasons (I think), but all adapters we maintain are now doing the same thing.
- Exposes well-known symbols as a static property on App. (`App.Symbol.locals`, `App.Symbol.clientAddress`)
- Adds helper functions for node-based runtimes to manage WHATWG Request and Response objects as static methods on `NodeApp`.
- `App.getSetCookieFromResponse()` in favor of `app.setCookieHeaders()` (confusing name)
- `app.render(request, { addCookieHeader: true })`
Tests for most of the …

quality of life updates for `App`

---

.github/labeler.yml

This updates `labeler.yml` rules for applying the `docs pr` label.
- `README.md` is no longer needed since we maintain these docs in the docs repo now.
- `changeset.md` meant that almost *every* PR was getting labelled, making the label less useful.
Now, only PRs with changes that will end up on the docs site are labelled. Changesets for minors are automatically reviewed because they are included in the Milestone, so a separate label is not necessary and obscures the PRs with actual changes to the docs. This change would help the docs maintainers better triage the most important PRs for reviewing.
Changesets for patches are still haphazardly reviewed, often on demand. But, more maintainers have been stepping up and serving as quality control for these. So, still moving in the right …

Updates rule for adding 'docs pr' label

---

.changeset/big-knives-own.md
packages/astro/e2e/fixtures/view-transitions/src/pages/404.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/one.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/vite-plugin-astro-server/route.ts

Changed the cloning of a Response in route.ts to retain the original headers.
With the headers the content type of the 404 page was lost.
The view transition loader expected text/html and did a full reload due to the missing header.
Closes #9629 
new e2e test to confirm that we can transition to 404 / undefined pages without reloads
n.a. / bug fix

Fixes an issue where view transitions to the 404-page did not work

---

.changeset/curvy-socks-rhyme.md
packages/astro/src/core/create-vite.ts
packages/astro/src/vite-plugin-env/index.ts

Some env var replacement can be relayed to Vite to replace instead, which is more accurate as we're using plain string replacements. I'm currently working on improving Astro's env replacement too and notice this stop gap improvement.
Existing env vars tests should pass.

Improve env var handling in SSR

---

packages/astro/src/core/errors/errors-data.ts

Closes https://github.com/withastro/astro/issues/9630
Closes PLT-1384
Some errors didn't have the metadata that are needed by docs to generate error pages.
Proof reading

fix: add metadata to build error pages

---

.eslintrc.cjs
packages/astro/src/core/errors/dev/utils.ts
packages/astro/src/core/errors/errors-data.ts

This updates a malformed link in an error message that snuck in.
No testing!
Only updates a link for the docs!

[docs] fix some error message syntax and add some lint rules to help

---

.changeset/honest-seas-raise.md
packages/astro/src/core/redirects/helpers.ts
packages/astro/src/core/routing/manifest/create.ts

Closes PLT-1371
Closes https://github.com/withastro/astro/issues/9568
I tested it locally with the use case provided
N/A, bug fix

fix(redirects): correctly compute the status code in redirects

---

.changeset/kind-waves-travel.md
packages/astro/src/core/cookies/cookies.ts
packages/astro/src/core/cookies/response.ts

- Closes #7715
Warning only. Does not affect behavior.
Does not affect usage. Although general elaboration on streaming is overdue.

qol(cookies): warn when cookies are set after the headers have been sent

---

.changeset/stale-pandas-count.md
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/test/fixtures/prerendered-error-pages/astro.config.mjs
packages/integrations/vercel/test/fixtures/prerendered-error-pages/package.json
packages/integrations/vercel/test/fixtures/prerendered-error-pages/src/pages/404.astro
packages/integrations/vercel/test/fixtures/prerendered-error-pages/src/pages/one.astro
packages/integrations/vercel/test/fixtures/prerendered-error-pages/src/pages/two.astro
packages/integrations/vercel/test/prerendered-error-pages.test.js
pnpm-lock.yaml

- Closes #9028 The issue exposes a weak point in routing - a code path where astro has to make a fetch call to itself. While this one specific side-effect is addressed, the error-prone approach remains in the codebase.
- Closes #9615
- If `404.astro` exists and is prerendered, it is used as the catch all route.
- All on-demand rendered routes now have an entry that points the serverless function. Previously, a single catch-all route pointed to the serverless function.

fix(vercel): fallback to static 404.html

---

.changeset/twenty-stingrays-hear.md
examples/starlog/package.json
packages/astro/package.json
pnpm-lock.yaml

Sharp's `0.33.0` is much better in every single regard to the 0.32.x version, however its semver checks are incompatible with ours, causing it to not install properly for a lot of users using outdated versions of Node. This PR pins it at the old version until Astro 5.0, where we'll presumably raise the Node requirements. Oh well.
For reference, Sharp's semver check is `^18.17.0 || ^20.3.0 || >=21.0.0` and ours is `>=18.14.1`
Fix #9345 
Tested manually, we were at that version previously so, it definitely does work.
N/A

fix: pin Sharp at old version

---

.changeset/early-taxis-love.md
packages/astro/src/transitions/router.ts

runScripts now only loads what should be executed in the main thread
+ stop waiting on errors, too.
manually tested
n.a./bug fix

Don't try to load partytown scripts in the main thread during view transitions

---

.changeset/afraid-suits-beam.md
packages/integrations/partytown/src/index.ts

Just before the view transition swap(), remove the Partytown `<head>` snippet.
This forces a re-execution on the target page.
n.a. / bug fix

Force re-execution of Partytown's head snippet on view transitions

---

.changeset/long-mangos-walk.md
packages/astro/src/assets/services/noop.ts

Using Picture + the noop image service didn't work properly because it didn't implement the ability to generate a srcset, this fixes that
N/A

fix(assets): Implement all hooks in the passthrough image service

---

.changeset/blue-pets-battle.md
packages/astro/src/core/config/vite-load.ts
packages/astro/src/core/sync/index.ts

Small perf improvement by setting `watch: null` in the Vite config so that chokidar is not started up at all. It's a feature from Vite 5.

Disable file watcher for internal one-off vite servers

---

CONTRIBUTING.md
packages/upgrade/package.json
packages/upgrade/test/context.test.js
packages/upgrade/test/install.test.js
packages/upgrade/test/utils.js
packages/upgrade/test/verify.test.js
pnpm-lock.yaml
scripts/cmd/test.js
scripts/index.js

For `@astrojs/upgrade` only for now as an experiment. There are quite some quirks with `node:test`:
1. Passing test glob patterns in Node <21 is broken. You can't pass trailing arguments like `--test-name-pattern` with it. https://github.com/nodejs/node/issues/50287
2. Running `.only` tests requires the `--test-only` flag. If you have nested tests, e.g. describe > it, you need both to be `describe.only` and `it.only` :((
3. Test arguments are really long and hard to use/remember
Hence I created a wrapper `astro-scripts test` CLI which should simplify these. Except no2's nested --only issue.
Tested manually with node 18.18.1 and node 20.6.1. Node 20 has slightly better test report description.
Performance-wise, running `time pnpm test`:
- Before: `pnpm test  0.89s user 0.21s system 167% …

Use node:test and node:assert/strict

---

.changeset/proud-guests-bake.md
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/core/routing/manifest/create.ts

We've had more than one report where users didn't add a index page when they use the option `i18n.routing.prefixDefaultLocale` to `true`.
The index page is required to create a redirect from `/` to `/<defaultLocale>`.
This PR adds a check during the build, and emits an error if the index is missing.
There was a case where a fixture didn't have the index, and the test cases were still passing. 
These fixtures were now raising an error, and I added the index page.

fix(i18n): emit an error when the index isn't found

---

.github/workflows/check-merge.yml

- Updates our `check-merge` GitHub Action.
- Handles single _and_ double quotes, which is what caused https://github.com/withastro/astro/pull/9671 to bypass the action 😅 
- Also handles major releases because regex is neat
I tested the bash script locally, but it's GitHub Actions so who knows
Nah

Update `check-merge` action

---

.changeset/weak-planes-help.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/one.astro
packages/astro/e2e/view-transitions.test.js

- Closes #9670
Added a test case.

fix(transitions router): attempt to find the clicked element within an open shadow root

---

.changeset/cool-foxes-talk.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/node.ts
packages/integrations/node/src/serve-app.ts

- We are planning refactors which will likely change where locals and client address are stored for the duration of rendering a page.
- Currently they are stored as symbols on the request object.
- Future features will likely involve multiple request objects per render, and the involvement of symbols in the new pipeline is uncertain.
- Chances are, the current mechanism of passing data as symbol fields will become legacy, especially considering that the `render()` method of `App` now explicitly accepts options.
- As such, we would not want to encourage the use of symbols.
- This PR removes `App.Symbol.locals`, and `App.Symbol.clientAddress` from a feature branch not yet merged into main.
- After this change, #9661 will be ready to review.
Removed the section …

adapter enhancement: revert exposing symbols

---

.changeset/poor-cherries-buy.md
packages/astro/components/ViewTransitions.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/form-five.astro
packages/astro/e2e/view-transitions.test.js

For issue [#9676 ViewTransition doesn't respect form method="post" when the action of form targets external URL](https://github.com/withastro/astro/issues/9676#issue-2078173834)
Leaving the submit handler when the form is cross-origin.
***Edited:***
Closes #9676

Opt-out ViewTransition for cross-origin form.

---

.changeset/friendly-needles-invite.md
packages/astro/src/vite-plugin-astro/index.ts

Helps https://github.com/withastro/astro/issues/9370 but does not fix it yet. This should reduce the occasional parsing error due to missing Astro compilation cache for its scripts and styles modules, which can often happen in HMR.
It does not fix the issue due to a Vite bug explained in https://github.com/withastro/astro/issues/9370#issuecomment-1887366837. I'm still trying to figure that out, but if I can't, I can probably add a workaround in a later PR too.
Tested manually with the issue's repro. I didn't add a test as the bug still exists, but it should not break other tests.
n/a. bug fix.

Add fallback compile for astro script and style load

---

.changeset/curvy-seas-explain.md
.changeset/tidy-planets-whisper.md
packages/astro/e2e/fixtures/tailwindcss/astro.config.mjs
packages/astro/e2e/fixtures/tailwindcss/src/components/Layout.astro
packages/astro/e2e/fixtures/tailwindcss/src/pages/index.astro
packages/astro/src/core/logger/vite.ts
packages/astro/src/vite-plugin-astro/compile.ts
packages/astro/src/vite-plugin-astro/hmr.ts
packages/astro/src/vite-plugin-astro/index.ts
packages/astro/src/vite-plugin-astro/query.ts
packages/astro/test/units/vite-plugin-astro/compile.test.js
packages/integrations/mdx/src/index.ts

This PR removes a good portion of the HMR code with an approach that lets Vite invalidates the modules accordingly instead. The highlights are:
1. Simplify `handleHotUpdate`. It now only does two things: "check style-only updates" and "handle circular dep edge case" (latter can be removed in the future)
2. Simplify Astro compilation caching and invalidation.
3. Remove redundant `import.meta.hot.decline()` calls. They don't work in Vite.
Added a test from https://github.com/withastro/astro/issues/9370
While this should fix it https://github.com/withastro/astro/issues/9370, I'd like to further improve HMR more noted in the `TODO`s, including:
- Refactoring away Astro compilation cache. Vite already has its own cache and we can rely on that instead. (Saves on memory)
- Fine-grained CSS …

Simplify HMR for circular imports and CSS

---

.changeset/itchy-clouds-invite.md
packages/astro/src/content/types-generator.ts
packages/astro/src/content/utils.ts
packages/astro/test/units/content-collections/get-entry-type.test.js

We decided to remove the "unsupported file type" warning from Content Collections [during our roadmap discussions](https://github.com/withastro/roadmap/discussions/805#discussioncomment-8006117). This requirement led to several bugs and special cases overtime, including an "ignore list" for `.DS_Store` and special handling for image assets.
Now, all files that are _not_ content (`.md`) or data (`.json`) are ignored by default. This means underscores are no longer required for these files. You can still use underscores to hide content or data entries from collection queries.
- Remove `unsupported` file type from warning logs and type-generation internals
- Update tests that expect `unsupported` to now expect `ignored`
- Remove one-off tests for `DS_Store` and image assets

[Content collections] Remove "unsupported file type" warning

---

.changeset/curly-seals-count.md
packages/integrations/sitemap/src/index.ts
packages/integrations/sitemap/test/base-path.test.js

fixes #9701 
The URLs from sitemap were being wrongfully generated if base path and ssr adapters were setup.
I added some tests.
n/a

@astrojs/sitemap: Fixes generated URLs when using a `base` with a SSR adapter

---

packages/astro/src/@types/astro.ts

Fixes a JSDoc syntax error for config reference docs.
Also, reworks content to avoid a Markdown table. Not entirely sure how this will look, but we are trying to avoid tables in this file:
No tests: corrects formatting errors in docs site
All docs!

[docs] fix syntax error, avoid a Markdown table

---

.changeset/smart-rules-train.md
packages/astro/src/core/routing/manifest/create.ts
packages/astro/test/units/routing/manifest.test.js

- Fix regression that causes pages ending with `index.astro` to be overridden by dynamic routes with rest parameters.
- Closes #9724
There was an incorrect test for the index priority, that was fixed and a new test for the full combination of routes in the same directory was added.
No changes in docs since this was an unintended regression. The docs already reflect the correct behavior.

Fix regression in the routing priority of index routes

---

.changeset/selfish-donuts-approve.md
packages/astro/src/cli/preferences/index.ts
packages/astro/src/preferences/index.ts

Shows whether preferences are project local or global and **warns in cases where astroConfig overrules preferences**.
It would be great if a native speaker could check the wording.
If we want to pursue this suggestion, we could also integrate the table with the defaults into the main table (stating that the value is neither project nor global but the default value). 
If we don't want to proceed with the modified table, I'd still like to keep the warning message, as I still find it very confusing in the case of the devToolbar that user preferences can override a `true` astroConfig value, but that they can't override a `false` astroConfig value.
manually tested

makes the output of 'astro preferences list' more verbose

---

.changeset/sweet-owls-trade.md
packages/astro/src/i18n/index.ts
packages/astro/test/units/i18n/astro_i18n.test.js

When using getLocaleRelativeUrl or getLocaleAbsoluteUrl while having both prefixDefaultLocale set to true and redirectToDefaultLocale set to false, should also return the locale path in the url.
For example `getLocaleRelativeUrl('en', '/posts')` should return `/en/posts` but right now it returns `/posts`
Not sure if any tests should change, there's probably an opportunity for a test but I couldn't find tests for these utilities in i18n-routing.test.js
This should be the expected behaviour no doc updates

fix getRelativeLocaleUrl when redirectToDefaultLocale is false

---

.changeset/lemon-carrots-cheer.md
packages/markdown/remark/src/load-plugins.ts

This will help with https://github.com/withastro/adapters/issues/110 (not a complete fix yet)
For some reason, Rollup sees this:
https://github.com/withastro/astro/blob/ea6cbd06a2580527786707ec735079ff9abd0ec0/packages/markdown/remark/src/load-plugins.ts#L6
As side-effectful, so it'll include the import to `pathToFileUrl` in the final bundle, which wouldn't work for Cloudflare builds.
This PR side-steps by initializing the `cwdUrlStr` variable lazily, which is also better for perf.
I didn't add a test because it's hard to create a failing test without a very specific build of Astro.

Fix `@astrojs/markdown-remark` bundling for non-node runtimes

---

.changeset/thick-carrots-run.md
packages/markdown/remark/package.json
packages/markdown/remark/src/import-plugin-browser.ts
packages/markdown/remark/src/import-plugin-default.ts
packages/markdown/remark/src/load-plugins.ts
packages/markdown/remark/test/browser.test.js
packages/markdown/remark/tsconfig.json
pnpm-lock.yaml

fix https://github.com/withastro/adapters/issues/110
Uses [imports mapping](https://nodejs.org/api/packages.html#imports) to split the `importPlugin()` function as a browser-safe and non-browser-safe version.
Created a test that runs esbuild to build a browser version.
n/a. the dependency is internal.

Make `@astrojs/markdown-remark` browser-safe

---

.changeset/mighty-icons-try.md
packages/astro-rss/src/schema.ts

- Close #9744
- Uses `object` and `refine` instead of an union
Tests are still passing

fix(rss): rssSchema definition to allow calling standard zod object methods

---

.changeset/slimy-jobs-smash.md
packages/astro/src/core/build/static-build.ts

Fixes https://github.com/withastro/astro/issues/9740
When running `astro build` outside of where the astro files are, dotfiles are not copied over because the `includeDotfiles` parameter is not passed in. This PR adds a `true` `includeDotfiles` value to `copyFiles` to fix this.
1. Check out this PR locally
1. Download astro bug example https://stackblitz.com/edit/github-es2mdg-tnkbfm?file=README.md
1. Check bug
```bash
cd another-astro
pnpm install
npm run astro build -- --root ../
ls -la ../dist
pnpm link [PR-root]/astro/packages/astro
npm run astro build -- --root ../
ls -la ../dist
```
Not sure if this requires an e2e test, but if so, please point me in the direction of an example of how one is set up.
Fixes a bug with build, so shouldn't affect any of the docs

Fix dot files not being copied over on non-root builds (#9740)

---

.changeset/fifty-pots-greet.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/types.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/i18n/middleware.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/i18n-routing.test.js

This PR adds `build.format` to the SSR Manifest.
This information is eventually needed by the i18n middleware to correctly compute the redirect.
N/A

fix(i18n): pass `build.format` when computing the redirect

---

.changeset/lazy-fireants-clap.md
packages/astro/astro-jsx.d.ts

Closes https://github.com/withastro/astro/issues/9761
Closes PLT-1487
I manually tested the change in a local project
N/A

fix: add missing attribute to button

---

.changeset/nervous-dodos-compete.md
packages/markdown/remark/src/shiki.ts

Attempting to use some of the [common transformers](https://shikiji.netlify.app/packages/transformers) raises an exception:
```
MDXError: classValue.replace is not a function
at TransformContext.transform (node_modules/@astrojs/mdx/dist/index.js:93:27)
at async Object.transform (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:64060:30)
at async loadAndTransform (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49741:29)
at async instantiateModule (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50759:10)
```
This is because `addClassToHast` returns an array of strings. But `Array`s don't have a `.replace`. See: https://github.com/antfu/shikiji/blob/31241ba4dc47c2d4d7809ee08c6573b26b07b812/packages/shikiji-core/src/utils.ts#L44
I couldn't figure out how to write a unit test for …

normalize class property

---

.changeset/honest-impalas-walk.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/logger/core.ts
packages/astro/src/runtime/client/dev-toolbar/apps/settings.ts
packages/astro/src/runtime/client/dev-toolbar/entrypoint.ts
packages/astro/src/runtime/client/dev-toolbar/settings.ts
packages/astro/src/runtime/client/dev-toolbar/toolbar.ts
packages/astro/src/vite-plugin-dev-toolbar/vite-plugin-dev-toolbar.ts

This PR attempt to handle errors inside apps better so that they don't crash the dev toolbar and it's better shown to users that apps crashed. For instance, now errors on loading and init will be shown in the server-side terminal so that users are sure to see it (it's kinda not obvious for users that the dev toolbar runs.. in the client so the logs are elsewhere, bit wonky.)
Tested manually!
N/A

fix: handle error at load for apps

---

examples/portfolio/src/styles/global.css

Setting height: 100% breaks the scroll-to-top functionality on iOS, i.e. tapping the top of the screen should scroll you to the top of the page. Setting min-height: 100% instead fixes scroll-to-top.

fix(portfolio): set min-height to 100% on html and body

---

.changeset/tall-comics-punch.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/ssrPipeline.ts
packages/astro/src/core/build/buildPipeline.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/pipeline.ts
packages/astro/src/runtime/server/endpoint.ts
packages/astro/src/vite-plugin-astro-server/devPipeline.ts

- When an endpoint that matches the path does not export the request method. a reroute to 404.astro is performed.
- This was done using "endpointHandler" on `Pipeline` implemented once for each environment. `callEndpoint` created a response with a special header. The endpoint handler recognises the special header and throws a special error. Then `App` recognises the special error and finally performs the rerouting.
- Now, `callEndpoint` creates a response with a special header ("X-Astro-Reroute=no"), and App recognises it to perform the rerouting directly.
- The meaning of the special header is reversed. Previously, it opted certain endpoint responses into rerouting (after endpoints were blanket opted-out). Now, endpoints get no blanket treatment, and the header opts-out individual …

refactor: remove endpoint handling infra

---

.github/scripts/announce.js
.github/scripts/utils.mjs
.github/workflows/release.yml

- Reorganizes our Discord announcement script and hopefully fixes everything!
- Modeled after the changes that worked in [`withastro/automation`](https://github.com/withastro/automation/blob/main/.github/utils.mjs)
- Reintroduces the Discord hook step that was removed previously
Tested on a fork, worked for me!

Fix release announcement script

---

.changeset/large-phones-guess.md
packages/astro/src/runtime/client/dev-toolbar/apps/audit/a11y.ts

Adds [`switch`](https://www.w3.org/TR/wai-aria/#switch) to the list of allowed aria roles for the dev toolbar checks.
Tested manually on the minimal example, by adding a `switch` role element.
```html
<body>
<h1>Astro</h1>
<span role="switch">Switch Off</span>
</body>
```
Before and after:
Adding `aria-checked` clears the error on the left.
Nothing to update. No explicit mention of the behavior for the `switch` role in the docs.

fix: accept the 'switch' aria role during a11y checks

---

.changeset/six-shrimps-glow.md
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/prerender/utils.ts
packages/astro/test/units/routing/manifest.test.js

- Fixes #9770
- Fixes #9779
The new test includes a nested structure of dynamic parameters as folders with indexes, including rest parameters in the middle of the route.
The rules remain the same but now apply per-segment instead of the whole route at once.
Unclear to me whether this needs to be made more clear on the docs.

Fix regression on dynamic sibling trees and index inside rest parameter folders

---

examples/component/package.json
examples/integration/package.json

According to #8893 peer deps should be tracked manually.
It was confirmed by Nate in the discord.
Tested locally. Packages under `packages/` folder have already been updated.

deps: bump peer deps to 4.0

---

.changeset/angry-dryers-hang.md
packages/astro-rss/src/index.ts
packages/astro-rss/src/schema.ts
packages/astro-rss/test/rss.test.js

Allows extending, while keeping the validation.
- Follow-up on https://github.com/withastro/astro/pull/9746
- Adds test that confirms `.extend` can be called
Added a new test for this case.
Fixes a regression

fix(rss): apply refinement at the point of parsing

---

.changeset/breezy-plants-smoke.md
packages/astro/src/content/types-generator.ts

Closes #9673
-   Added a `.js` to the end of the `configPath` for types, making it work for verbatim modules in TypeScript.
-   I also moved the logic to its own function, making it more readable.
Ran all the tests with no errors reported. I didn't add tests because I didn't think they were needed, but if you think otherwise, I'll need guidance on testing different TSConfigs on a given file.
Docs don't need to be updated. This is a fix for users with verbatim modules in TypeScript, but it works the same for users without that setting.

Fix for #9673

---

.changeset/strange-students-shake.md
packages/astro/src/vite-plugin-env/index.ts
packages/integrations/node/test/prerender.test.js

fix https://github.com/withastro/astro/issues/9734
`vite-plugin-scanner` uses static analysis to detect the value of `export const prerender = import.meta.env.*`. That means the env var needs to be statically replaced before it can detect it. In #9652, I removed the static replacement in favour of a more performant approach (that assigns `import.meta.env` in runtime), however it didn't work well for this case.
While the `export const prerender` is mainly for builds only, I think the early warning in dev is still good to keep. So I made a quick fix to statically replace for `export const prerender` only for now.
Added a dev test. We only tested the feature in build.
n/a. bug fix.

Fix env var replacement for export const prerender

---

.changeset/two-ducks-give.md
packages/integrations/vercel/src/serverless/entrypoint.ts

- Makes sure that cookies added using Astro.cookies are added as a header.
- This slipped during the Astro 4.2 "app enhancements" refactors.
- Noticed while attempting to reproduce #9801.
- Runtime tests for vercel do not seem to be set up.

fix(vercel): make Astro.cookies work again

---

packages/astro/src/@types/astro.ts

This reorders the `@docs` items for building the Docs Configuration Reference Page. There is **no content change**, only organizational changes. This should only affect how the docs page is generated (the order of items).
(File diffs may imply otherwise, because of similar text repeated throughout. But there have been no changes to any text. Only moving items around and attempting to get the indentation correct.)
- It reorganizes similar items together in an order that more reflects what people are asking about and looking for.
- It moves `integrations` and `vite` into the top-level category instead of making them standalone headers at the bottom of the page, mixed in with config items that *do* have several sub-options, taking care to:
No tests, only docs. Not sure why tests are failing. …

[docs] reorder items for configuration reference page

---

.changeset/seven-kiwis-join.md
packages/create-astro/src/actions/context.ts
packages/create-astro/src/actions/typescript.ts
packages/create-astro/src/messages.ts

- Closes #9791
- Fixes `@astrojs/check` and `typescript` addition to `package.json` dependencies when the user has decided not to auto-install dependencies
Not sure if it solves https://github.com/withastro/astro/issues/9791#issuecomment-1906722419 though
Not tested
N/A

fix(create-astro): @astrojs/check and typescript addition

---

.changeset/calm-jobs-pay.md
packages/integrations/node/src/serve-static.ts
packages/integrations/node/src/server.ts
packages/integrations/node/src/types.ts
packages/integrations/node/test/fixtures/trailing-slash/astro.config.mjs
packages/integrations/node/test/fixtures/trailing-slash/package.json
packages/integrations/node/test/fixtures/trailing-slash/src/pages/index.astro
packages/integrations/node/test/fixtures/trailing-slash/src/pages/one.astro
packages/integrations/node/test/prerender.test.js
packages/integrations/node/test/trailing-slash.js
pnpm-lock.yaml

- Add logic to support trailingSlash with `ignore`, `always` and `never` values with nodejs adapter
- Closes #7808
Add tests to use each possible value of trailingSlash and check if expected results are good and not breaking other tests
`trailingSlash = always` &#8594; Should always contain the / at the end (will always return host/pathname/?queryifexists)
`trailingSlash = never` &#8594; Should never contain the / at the end (will always return host/pathname?queryifexists)
`trailingSlash = ignore` &#8594; Should ignore the / at the end (will always work without redirect)
New behaviour of `trailingSlash = ignore` will return 200 and the content of the index.html inside the directory
> I had to change the `prerenderer.test.js` to support this new behaviour and not breaking the test
Should …

feat(node): add trailingSlash support

---

packages/integrations/node/test/node-middleware.test.js
packages/integrations/node/test/prerender-404-500.test.js
packages/integrations/node/test/prerender.test.js
packages/integrations/node/test/test-utils.js
scripts/cmd/test.js

Fixes the perf issue in https://github.com/withastro/astro/pull/9758 by running multiple tests in a single process.
Ran node test manually.

Run tests in a single process

---

packages/astro/test/i18n-routing.test.js
packages/integrations/node/package.json
packages/integrations/node/test/api-route.test.js
packages/integrations/node/test/assets.test.js
packages/integrations/node/test/bad-urls.test.js
packages/integrations/node/test/encoded.test.js
packages/integrations/node/test/errors.test.js
packages/integrations/node/test/headers.test.js
packages/integrations/node/test/image.test.js
packages/integrations/node/test/locals.test.js
packages/integrations/node/test/node-middleware.test.js
packages/integrations/node/test/prerender-404-500.test.js
packages/integrations/node/test/prerender.test.js
packages/integrations/node/test/test-utils.js
packages/integrations/node/test/url-protocol.test.js
packages/integrations/node/test/well-known-locations.test.js
pnpm-lock.yaml
scripts/cmd/test.js

This PR moves `@astrojs/node` to use Node.js for testing
N/A

chore(@astrojs/node): use Node.js for testing

---

packages/create-astro/src/actions/typescript.ts
packages/create-astro/src/index.ts
packages/create-astro/src/messages.ts

- Follow-up to #9813
- After testing the changes in #9813, I noticed that our `getVersion` function had a cache and only ever used the first version it fetched. Removed this!
- I also flipped the order of questions so that TypeScript goes before Dependency Installation. I missed that this was needed when reviewing #9813.
- No changeset needed because this hasn't been released yet!
Tested manually. Existing test coverage is still valid.
Nope, bug fix for unreleased code

Remove `create-astro` version cache

---

.changeset/rotten-masks-rhyme.md
packages/astro/src/core/app/index.ts
packages/astro/src/runtime/server/consts.ts
packages/astro/src/runtime/server/endpoint.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/dev-routing.test.js
packages/astro/test/fixtures/with-endpoint-routes/src/pages/404.astro
packages/astro/test/fixtures/with-endpoint-routes/src/pages/not-ok.ts

- fix #9829 
Added a case to dev-routing.test.js

fix(dev): dont reroute endpoint responses

---

.changeset/twenty-papayas-agree.md
packages/astro/src/core/app/common.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/types.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/build/plugins/plugin-pages.ts
packages/astro/src/core/build/plugins/plugin-ssr.ts
packages/astro/src/core/middleware/vite-plugin.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/route.ts

- The `onRequest` function is internally re-exported from each page and endpoint, and loaded after the request matches a particular one.
- The middleware is singular in astro and the current arrangement prevents enhancement that require the middleware to be independent.
- This PR moves `onRequest` from page chunks to the manifest, where it can be loaded sooner than route data.
Does not affect behavior. Existing tests should pass.

refactor: singular middleware

---

.changeset/famous-seas-press.md
packages/astro/content-types.template.d.ts

- Exports the `ContentConfig` type publicly from `astro:content`
- We realised in https://github.com/withastro/starlight/pull/1175 that we needed access not just to a user’s schema output type (`CollectionEntry['data']`), but also the schema input type. While accessing the actual schema at runtime is possible, getting its type is much trickier. Exposing this would make that simpler. (Also open to other ideas if people have them.)
Existing tests should pass; types only change.
n/a — this is a rarely needed API, but handy in some edge cases.

Expose `ContentConfig` type from `astro:content`

---

examples/blog/src/pages/index.astro
packages/astro/test/units/dev/dev.test.js

remove unused prop in `Header` component of blog template, the `SITE_TITLE` is already imported and used within
Manually by using the template

remove unused prop in blog template

---

.changeset/large-kangaroos-camp.md
packages/astro/src/core/constants.ts
packages/astro/src/core/render/context.ts
packages/astro/src/i18n/middleware.ts
packages/astro/test/fixtures/i18n-routing-fallback/src/pages/pt/start.astro
packages/astro/test/i18n-routing.test.js

Closes https://github.com/withastro/astro/issues/9847
Closes PLT-1511
During the build, the `url.pathname` contains the the extension e.g. `en.html`, so Astro could never find the correct locale.
With this fix, we use `RouteData` instead, which is an object that we attach to the request using a pipeline hook. We attach this information here:
https://github.com/withastro/astro/blob/f27f790b922247c168eb167394cea8dd4c3e3390/packages/astro/src/core/build/generate.ts#L284
And this is the value of the function
https://github.com/withastro/astro/blob/f27f790b922247c168eb167394cea8dd4c3e3390/packages/astro/src/i18n/middleware.ts#L137-L139
I modified and existing test to render the current locale
N/A

fix(i18n): compute current locale from route instead of request

---

.changeset/silent-buckets-retire.md
packages/astro/src/i18n/vite-plugin-i18n.ts
packages/astro/src/virtual-modules/i18n.ts

- Switches the approach used to deliver i18n config to the `astro:i18n` module.
- The virtual module approach broke in mysterious ways.

fix(i18n): use `define` to deliver config to virtual module

---

.eslintrc.cjs
packages/astro/src/assets/services/squoosh.ts
packages/astro/src/cli/add/index.ts
packages/astro/src/core/app/types.ts
packages/astro/src/preferences/index.ts
packages/astro/src/runtime/client/dev-toolbar/apps/settings.ts
packages/astro/src/runtime/server/scripts.ts
packages/astro/src/vite-plugin-astro/types.ts
packages/integrations/node/test/encoded.test.js
packages/integrations/node/test/headers.test.js
packages/integrations/node/test/locals.test.js

This PR adds the rule [switch-exhaustiveness-check](https://typescript-eslint.io/rules/switch-exhaustiveness-check/)
I find this rule very important because we don't want to "forget" to handle variants inside a `switch` statement.
N/A

chore: add rule `switch-exhaustiveness-check`

---

.changeset/silver-peaches-pump.md
packages/astro/src/runtime/server/endpoint.ts
packages/astro/test/units/routing/endpoints.test.js

Updated the implementation of `renderEndpoint` to only append the reroute header if the response has the HTTP status code 404 or 500.
This should resolve the issue mentioned in https://github.com/withastro/astro/issues/9871.
Added tests based on the work of @lilnasy ([cad43ea5c11e58b022df82907cd110e56dd4efed](https://github.com/withastro/astro/commit/cad43ea5c11e58b022df82907cd110e56dd4efed)).
These tests check that the response returned from an endpoint contains the expected headers and doesn't error with an HTTP 500 error.
I don't think there is a need to update the documentation because of this change, since it's only internal response rewriting.

Fix endpoint response with immutable header

---

.changeset/wet-rivers-do.md
packages/astro/src/core/build/generate.ts
packages/astro/test/astro-get-static-paths.test.js

- Fixes #9870
Updated a getStaticPaths test case to include trailingSlash.

fix(ssg): consider trailingSlash for url

---

.changeset/twelve-humans-remain.md
packages/astro/src/content/utils.ts
packages/astro/src/vite-plugin-markdown/content-entry-type.ts
packages/astro/src/vite-plugin-markdown/index.ts

- We have multiple places in the codebase that use slightly different YAML/Frontmatter parsing logic
- This removes one of those instances which wasn't throwing a useful error, replacing it with a shared utility.
Tested manually with user code shared on Discord. Existing tests should pass

Improves YAML error handling consistency

---

.changeset/long-peaches-fetch.md
packages/astro/src/vite-plugin-astro-server/response.ts
packages/astro/test/units/vite-plugin-astro-server/response.test.js

- Closes #9874
Added a unit test.

fix(dev): prevent comma-separating multiple Set-Cookie headers

---

packages/integrations/sitemap/package.json
packages/integrations/sitemap/test/base-path.test.js
packages/integrations/sitemap/test/filter.test.js
packages/integrations/sitemap/test/routes.test.js
packages/integrations/sitemap/test/ssr.test.js
packages/integrations/sitemap/test/staticPaths.test.js
packages/integrations/sitemap/test/trailing-slash.test.js
pnpm-lock.yaml

- This PR moves @astrojs/integrations/sitemap to use Node.js for testing
- See #9873 for details
No docs added as this only affects testing.

chore(@astrojs/integrations/sitemap): use Node.js for testing

---

packages/integrations/mdx/package.json
packages/integrations/mdx/test/css-head-mdx.test.js
packages/integrations/mdx/test/invalid-mdx-component.test.js
packages/integrations/mdx/test/mdx-astro-markdown-remarkRehype.test.js
packages/integrations/mdx/test/mdx-component.test.js
packages/integrations/mdx/test/mdx-escape.test.js
packages/integrations/mdx/test/mdx-frontmatter-injection.test.js
packages/integrations/mdx/test/mdx-frontmatter.test.js
packages/integrations/mdx/test/mdx-get-headings.test.js
packages/integrations/mdx/test/mdx-get-static-paths.test.js
packages/integrations/mdx/test/mdx-images.test.js
packages/integrations/mdx/test/mdx-infinite-loop.test.js
packages/integrations/mdx/test/mdx-math.test.js
packages/integrations/mdx/test/mdx-namespace.test.js
packages/integrations/mdx/test/mdx-optimize.test.js
packages/integrations/mdx/test/mdx-page.test.js
packages/integrations/mdx/test/mdx-plugins.test.js
packages/integrations/mdx/test/mdx-plus-react.test.js
packages/integrations/mdx/test/mdx-script-style-raw.test.js
packages/integrations/mdx/test/mdx-slots.test.js
packages/integrations/mdx/test/mdx-syntax-highlighting.test.js
packages/integrations/mdx/test/mdx-url-export.test.js
packages/integrations/mdx/test/mdx-vite-env-vars.test.js
packages/integrations/mdx/test/remark-imgattr.test.js
pnpm-lock.yaml

- This PR moves `@astrojs/mdx` to use Node.js for testing
- Related issue: [☂️ Move Astro tests to node:test  #9873](https://github.com/withastro/astro/issues/9873)
- timeout set to 50000 for the test script as the tests timed out from the default 20000 on my end
`pnpm test --filter @astrojs/mdx`
N/A

chore(@astrojs/mdx): use Node.js for testing

---

packages/integrations/sitemap/package.json
packages/integrations/sitemap/test/base-path.test.js
packages/integrations/sitemap/test/filter.test.js
packages/integrations/sitemap/test/routes.test.js
packages/integrations/sitemap/test/ssr.test.js
packages/integrations/sitemap/test/staticPaths.test.js
packages/integrations/sitemap/test/trailing-slash.test.js
pnpm-lock.yaml

- Migrates tests of `@astrojs/sitemap` to `node:test` ([#9873](https://github.com/withastro/astro/issues/9873))
- Removes `chai` and `mocha` from devDependencies of `@astrojs/sitemap`
- `pnpm --filter @astrojs/sitemap run test`
- Test case [Base path is concatenated correctly (using node adapter)](https://github.com/withastro/astro/blob/main/packages/integrations/sitemap/test/base-path.test.js#L17) had already failed before I made any changes
- No docs added since this PR only deals with tests

chore(@astrojs/sitemap): migrate tests to `node:test`

---

packages/integrations/markdoc/package.json
packages/integrations/markdoc/test/content-collections.test.js
packages/integrations/markdoc/test/headings.test.js
packages/integrations/markdoc/test/image-assets.test.js
packages/integrations/markdoc/test/propagated-assets.test.js
packages/integrations/markdoc/test/render-html.test.js
packages/integrations/markdoc/test/render.test.js
packages/integrations/markdoc/test/syntax-highlighting.test.js
packages/integrations/markdoc/test/variables.test.js
pnpm-lock.yaml

・This PR moves @astrojs/markdoc to use Node.js for testing
・Part of [☂️ Move Astro tests to node:test #9873](https://github.com/withastro/astro/issues/9873)
N/A
PS. Sorry, I PR'd a mix of previous commits. so I re-create PR.

chore(@astrojs/markdoc): use Node.js for testing

---

packages/integrations/vue/package.json
packages/integrations/vue/test/app-entrypoint-css.test.js
packages/integrations/vue/test/app-entrypoint.test.js
packages/integrations/vue/test/basics.test.js
pnpm-lock.yaml

- Move [`@astrojs/vue`](https://github.com/withastro/astro/tree/main/packages/integrations/vue) tests from chai to nodejs
- `chai` and `mocha` dependencies removed
- Related Issue #9873 
`pnpm test --filter @astrojs/vue` (All tests passing, 12 sec interval average - previously it was 9 sec with mocha/chai)
Not needed

chore(`@astrojs/vue`): use Node.js for testing

---

.changeset/poor-tips-turn.md
packages/integrations/vercel/package.json
packages/integrations/vercel/src/lib/nft.ts
pnpm-lock.yaml

- Ignores `@libsql/client` which has a bunch of node imports that Vercel shouldn't be trying to bundle.
N/A, can't be unit tested, tested manually
N/A, just the changeset

Provide better ignores for Vercel's file tracer

---

.changeset/tiny-moose-melt.md
packages/astro/src/core/build/plugins/plugin-ssr.ts

- Fixes a regression introduced by https://github.com/withastro/astro/pull/9776/files#diff-524e25c0bd5feda71ed7489963414a0c1f06da3caa327933574a72b85b668bddR264
- We got a report on Discord about Cloudflare failing to build in Astro 4.2.5
- Turns out that the obfuscated way this was originally written was very intentional because it bypasses some static analysis that bundlers try to do to warn against missing exports
- I added a comment to this effect so that this doesn't happen again
We unfortunately don't have automated adapter tests

Silently ignore adapters that don't export `start()`

---

.changeset/clever-roses-sleep.md
packages/astro/src/core/app/node.ts
packages/integrations/node/test/errors.test.js
packages/integrations/node/test/fixtures/errors/src/pages/generator.astro

- Closes #8714 
- `curl --raw -i http://localhost:4321`
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Added a test case to errors.test.js

fix(NodeApp): end with "Internal server error" on mid-stream error

---

packages/astro/src/@types/astro.ts

chore: fix alignment docs

---

packages/astro/CHANGELOG.md

Astro components have a default export, not a named export. Fixes the example in the changelog for release `astro@4.3.0`
No logical change, just release notes.
No docs change is needed.

fix(docs): Fix import in changelog example

---

.changeset/old-jokes-complain.md
packages/astro/astro-jsx.d.ts

- Added a property `name` for `<details>` HTML element to group several `<details>`elements.

Add a name property for DetailsHTMLAttributes

---

.changeset/eight-windows-kiss.md
packages/astro/src/vite-plugin-astro-server/base.ts

Closes #9759 
Fixes error message when requesting a public url without your base.
Now the error message will correctly show the correct publicUrl  and will add your base to the expected.
_With the following config:_
```ts
base: "/my-page",
publicDir: "static"
});
```
_Before:_
```
[ERROR] [router] Request URLs for public/ assets must also include your base. "/favicon.svg" expected, but received "/favicon.svg".
```
_After:_
```
[ERROR] [router] Request URLs for static/ assets must also include your base. "/my-page/favicon.svg" expected, but received "/favicon.svg".
```
Didn't feel like this small "text" change needed it's own test : )
Doesn't change current behavior only makes the error message more clear.

fix: use publicDir & base for 'include your base in url' error message

---

packages/astro/src/@types/astro.ts

- Tabs instead of spaces in a JSDoc type
- Noticed this in https://github.com/withastro/docs/pull/6737
n/a docs only
n/a docs fix

Fix indentation formatting in types JSDoc

---

packages/astro/src/@types/astro.ts
packages/astro/src/core/errors/errors-data.ts

We decided that prerender/ed/ing does NOT have a hyphen. This updates an error message to remove hyphens in this word.
... and, this now also updates for docs PR 6620 that changed some URLs round! (Config reference and error messages)
No tests, just docs
Docs!

[docs] update typo in error message

---

.changeset/sour-seas-hang.md
packages/astro/src/core/app/node.ts
packages/integrations/markdoc/package.json
packages/integrations/node/test/api-route.test.js
packages/integrations/node/test/errors.test.js
packages/integrations/node/test/fixtures/api-route/src/pages/astro-redirect.astro
packages/integrations/node/test/fixtures/api-route/src/pages/redirect.ts
packages/integrations/node/test/fixtures/api-route/src/pages/response-redirect.ts
packages/integrations/node/test/prerender.test.js

- Fixes #9925
- Added a test case for redirects, thanks @friedemannsommer.
- Adjusted a test introduced in #9908 to address flakiness.
- Cherry-picked #9930 to unbreak remaining tests.

fix(NodeApp): fix responses with null bodies never completing

---

packages/astro/astro.js

- On a bad install, the user can get to a place where `semver` isn't installed
- This import would fail, even if the user's node version was correct
- Manually tested
- N/A

fix semver check in CLI entrypoint

---

.changeset/shaggy-sloths-mix.md
packages/astro/src/core/build/buildPipeline.ts
packages/astro/test/fixtures/middleware space/src/middleware.js
packages/astro/test/fixtures/middleware space/src/pages/prerendered.astro
packages/astro/test/middleware.test.js

- Fixes a regression introduced in #9776 (astro 4.2.5+)
- Added a test case

fix(middleware): load while retrieving ssr manifest for prerendering

---

packages/astro/src/core/routing/match.ts

fix: #9933 
Decode `pathnames` to check.
I don't know where to add testcases.
Should I add in `dev-routing.test.js`? and also add in `preview-routing.test.js`?
I don't think to update.

fix: route matching for encoded pathnames

---

packages/integrations/lit/package.json
packages/integrations/lit/test/sass.test.js
packages/integrations/lit/test/server.test.js
pnpm-lock.yaml

- This PR moves @astrojs/integrations/lit to use Node.js for testing
- See #9873 for details
No docs added as this only affects testing.

chore(@astrojs/integrations/lit): use Node.js for testing

---

.changeset/mean-pugs-nail.md
packages/astro/src/integrations/astroFeaturesValidation.ts

This PR fixes a bug where an error log was incorrectly logged inside an adapter
N/A

fix: don't log warning if `i18nDomains` isn't enabled

---

packages/astro/test/dev-routing.test.js
packages/astro/test/fixtures/without-site-config/src/pages/te st.astro
packages/astro/test/fixtures/without-site-config/src/pages/テスト.astro

Add testcases for #9934 and #9945
N/A

Add new test cases for non-UTF-8 and space file names

---

.changeset/tidy-deers-double.md
packages/astro/src/core/preview/vite-plugin-astro-preview.ts
packages/astro/test/preview-routing.test.js

Fix: #9854 
https://github.com/ktym4a/astro/blob/520be8b113bbb3189033e2952b28a6cda2a676a1/packages/astro/src/core/preview/vite-plugin-astro-preview.ts#L81-L98
I think previous `vite404Middleware` checks were never happen because `next();` is called before that.
so, Moved to be called.
If this is good, I will add test cases.
but I just need to know where to add test cases.
don't need to add.

Fix: 404.html load correctly on preview

---

.changeset/gold-ways-attend.md
packages/integrations/vercel/package.json
packages/integrations/vercel/src/lib/nft.ts
pnpm-lock.yaml

This reverts commit 49e0c24d7f90d00e986533fcf546665967540ce7.
This commit inadvertently preventing bundling of `@libsql/client` for some people that needed it. 3 reports so far, so reverting and figuring out a different approach to the warnings.
- Fixes https://github.com/withastro/astro/issues/9936
- Fixes https://github.com/withastro/astro/issues/9935
N/A
N/A

Revert "Provide better ignores for Vercel's file tracer (#9885)"

---

.changeset/tidy-spoons-suffer.md
packages/astro-rss/src/schema.ts
packages/astro-rss/test/rss.test.js

It allows for an `enclosure` in an RSS feed to have a length of `0`.
Reference on this change: https://www.rssboard.org/rss-profile#element-channel-item-enclosure:~:text=When%20an%20enclosure%27s%20size%20cannot%20be%20determined%2C%20a%20publisher%20SHOULD%20use%20a%20length%20of%200.
Added unit test.
It would be nice to point people to use a value of `0` for `enclosure` `length` if they are processing the images with Astro.

FIX: allow rss feeds to have an enclosure with length of 0

---

packages/astro/test/fixtures/streaming/src/pages/slot.astro

Because components that are sibilings are rendered in parallel, the slot streaming tests we use runs with a timeout of `50` and `60`, making only a 10ms gap for the chunk separation, which I _think_ is what makes the macos-14 test keep failing. I extended the `60` to `100` so each wait has a 50ms gap.
I hope this fixes it 😄 
Ran the local tests a bunch of times.
n/a. test fix.

Fix flaky streaming test

---

.changeset/shy-wolves-ring.md
.changeset/six-fishes-beg.md
packages/astro/src/core/render/context.ts
packages/astro/test/fixtures/i18n-routing/src/pages/blog/[...lang]/index.astro
packages/astro/test/fixtures/i18n-routing/src/pages/spanish/index.astro
packages/astro/test/i18n-routing.test.js

Closes https://github.com/withastro/astro/issues/9970
I reverted the change to use `pathname` instead for `RouteData::route`.`.route` contains the actual name of the file e.g. `/blog/[...locale`, which is not what I needed.
So, I reverted the code to use `RouteData::pathname` first and then `URL::pathname` in the former isn't present. `RouteData::pathname` covers SSR cases.
This PR also fixes another issue where `Astro.currentLocale` wasn't returning the correct value in case a locale is configured using the `path` property
I added new test cases.
N/A

fix(i18n): fix regression in current locale

---

.github/scripts/bundle-size.mjs

Our bundle size script has been failing on:
```
Error: R] Could not resolve "aria-query"
main/packages/astro/src/runtime/client/dev-toolbar/apps/audit/a11y.ts:27:28:
27 │ import { aria, roles } from 'aria-query';
╵                             ~~~~~~~~~~~~
You can mark the path "aria-query" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
Error: R] Could not resolve "axobject-query"
main/packages/astro/src/runtime/client/dev-toolbar/apps/audit/a11y.ts:29:48:
29 │ import { AXObjectRoles, elementAXObjects } from 'axobject-query';
╵                                                 ~~~~~~~~~~~~~~~~
You can mark the path "axobject-query" as external to exclude it from the bundle, which will remove this error and leave the …
```

Fix bundle size script external for dev toolbar

---

.changeset/strong-pets-rhyme.md
packages/astro/src/content/utils.ts
packages/astro/test/fixtures/content-collections/src/content/config.ts

Resolves #8871
Support `strict()` extension on content collection schemas when `slug` is present. Before, we would accidentally parse `slug` with the user's content schema.
- Add `.strict()` to the content collection slug fixture
N/A

Fix: support `strict()` on content collection schemas when `slug` is present

---

packages/astro/src/@types/astro.ts

This fixes a small typo in the output section of the types documentation.  Replaces PR #6792 in docs repository
A minor typo in the output section of configuration documentation is fixed with this changeset
No tests performed
No docs need updating. This just fixes an obvious typo

Fix small typo in astro.ts

---

.changeset/tough-socks-change.md
packages/astro/src/i18n/middleware.ts
packages/astro/test/fixtures/i18n-routing/src/pages/endurance.astro
packages/astro/test/i18n-routing.test.js

Closes  #10005
The logic that checks the presence of the default locale was very broad and poor. This new logic should be more robust.
I added new test cases 
N/A

fix(i18n): don't consider URLs that start with the name of the defaut locale

---

.changeset/cool-walls-fail.md
packages/astro/package.json

- https://github.com/withastro/astro/pull/10013 introduced a new folder and file for types that are supposed to be shipped without processing.
- This file was not included in the npm package.
- Manually, existing tests should pass.

fix(astro:content): include required type declarations

---

.changeset/shaggy-spies-sit.md
packages/integrations/markdoc/src/content-entry-type.ts
packages/integrations/markdoc/test/fixtures/image-assets/markdoc.config.mjs
packages/integrations/markdoc/test/fixtures/image-assets/src/components/Image.astro
packages/integrations/markdoc/test/fixtures/image-assets/src/content/docs/intro.mdoc
packages/integrations/markdoc/test/image-assets.test.js

Automatically resolve the `src` attribute on tags named `image`, as it's impossible to build a full image component using the native syntax (Markdoc does not allow attributes on image nodes, see https://github.com/markdoc/markdoc/issues/156)
Technically, it's possible for a plugin to make a full image component using the native syntax, by either modifying the AST manually, or modifying the parser, but it's honestly insanely cumbersome.
Added a test
Will do, it lives in another repo now, so annoying 😠 (I'm kidding)

feat(markdoc): Add support for using a custom component for images

---

packages/astro/test/custom-404-html.nodetest.js

* Migrates `packages/astro/test/custom-404-html.test.js`

chore: Migrate `custom-404-html.test.js` to `node:test`

---

packages/astro/test/static-build.nodetest.js

- Migrates `static-build.test.js` to `node:test` ([#9873](https://github.com/withastro/astro/issues/9873))
- N/A

chore: migrate `static-build.test.js` to `node:test`

---

packages/astro/test/static-build-vite-plugins.nodetest.js

- Migrates `static-build-vite-plugins.test.js` to `node:test` ([#9873](https://github.com/withastro/astro/issues/9873))
- N/A

chore: migrate `static-build-vite-plugins.test.js` to `node:test`

---

packages/astro/test/static-build-page-url-format.nodetest.js

- Migrates `static-build-page-url-format.test.js` to `node:test` ([#9873](https://github.com/withastro/astro/issues/9873))
- N/A

chore: migrate `static-build-page-url-format.test.js` to `node:test`

---

packages/astro/test/static-build-page-dist-url.nodetest.js

- Migrates `static-build-page-dist-url.test.js` to `node:test` ([#9873](https://github.com/withastro/astro/issues/9873))
- N/A

chore: migrate `static-build-page-dist-url.test.js` to `node:test`

---

packages/astro/test/static-build-frameworks.nodetest.js

- Migrates `static-build-frameworks.test.js` to `node:test` ([#9873](https://github.com/withastro/astro/issues/9873))
- N/A

chore: migrate `static-build-frameworks.test.js` to `node:test`

---

packages/astro/test/error-non-error.nodetest.js

- See #9873
- Migrates `packages/astro/test/error-non-error.test.js`
N/A

chore: Migrate error-non-error.test.js to node:test

---

packages/astro/test/error-bad-js.nodetest.js

- See #9873
- Migrates packages/astro/test/error-bad-js.test.js
N/A

chore: Migrate error-bad-js.test.js to node:test

---

packages/astro/test/custom-404-injected.nodetest.js

* Migrates `packages/astro/test/custom-404-injected.test.js`

chore: Migrate `custom-404-injected.test.js` to `node:test`

---

packages/astro/test/custom-404-injected-from-dep.nodetest.js

* Migrates `packages/astro/test/custom-404-injected-from-dep.test.js`

chore: Migrate `custom-404-injected-from-dep.test.js` to `node:test`

---

packages/astro/test/markdown.nodetest.js

- Part of #9873 
- Progressively migrates `packages/astro/test/markdown.test.js`
Tests pass

chore: Migrate `markdown.test.js` to `node:test`

---

packages/astro/test/astro-markdown.nodetest.js

- Part of #9873 
- Progressively migrates `packages/astro/test/astro-markdown.test.js`
Tests pass

chore: Migrate `astro-markdown.test.js` to `node:test`

---

packages/astro/test/astro-markdown-url.nodetest.js

- Part of #9873 
- Progressively migrates `packages/astro/test/astro-markdown-url.test.js`
Tests pass.

chore: Migrate `astro-markdown-url.test.js` to `node:test`

---

packages/astro/test/ssr-markdown.nodetest.js

- Part of #9873 
- Progressively migrates `packages/astro/test/ssr-markdown.test.js`
Test passes.
Test-only change.

chore: Migrate `ssr-markdown.test.js` to `node:test`

---

packages/astro/test/custom-404-implicit-rerouting.nodetest.js

* Migrates `packages/astro/test/custom-404-implicit-rerouting.test.js`

chore: Migrate `custom-404-implicit-rerouting.test.js` to `node:test`

---

scripts/cmd/test.js

Since the timeout is shared, it needs to be massively increased

test: increase timeout

---

packages/astro/test/custom-404-static.nodetest.js

* Migrates `packages/astro/test/custom-404-static.test.js`

chore: Migrate `custom-404-static.test.js` to `node:test`

---

.github/workflows/label.yml

revert: labeler action to v4, the old configuration isn't valid anymore

---

.changeset/forty-hounds-look.md
.changeset/tasty-actors-dance.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/i18n/index.ts
packages/astro/src/i18n/middleware.ts
packages/astro/test/i18n-routing.nodetest.js
packages/astro/test/units/i18n/astro_i18n.test.js

This PR fixes a bug where, under certain situations, the absolute URL emitted by the utility has a double slash.
I removed logic that wasn't needed and used the existing logic coming from `getRelativeLocaleUrl`.
I added a new unit test and used the `validateConfig` function that emits the correct defaults from the Astro configuration. That's handy because I was struggling to get Astro defaults when running the unit tests. Ideally I could port all tests to use this pattern, and I'll do it in another PR.
I also updated an integration test; for some reason, the configuration passed to that test wasn't updated. Regardless, the test case that I updated works as I wanted.

fix(i18n): regression where emitted URLs had `//`

---

.changeset/tough-shirts-allow.md
packages/astro/src/core/client-directive/build.ts
packages/astro/src/integrations/index.ts

Passes on a third party package without `chdir` after these changes. Existing tests should pass.

fix(integration api): improve module resolution

---

packages/astro/test/slots-vue.nodetest.js
packages/astro/test/vue-component.nodetest.js
packages/astro/test/vue-jsx.nodetest.js
packages/astro/test/vue-with-multi-renderer.nodetest.js

- migrates vue related tests to `node:test`
- related issue #9873 
- All tests passing
N/A

chore: migrate vue related tests to `node:test`

---

packages/markdown/remark/package.json
packages/markdown/remark/test/autolinking.test.js
packages/markdown/remark/test/browser.test.js
packages/markdown/remark/test/entities.test.js
packages/markdown/remark/test/plugins.test.js
packages/markdown/remark/test/remark-collect-images.test.js
packages/markdown/remark/test/shiki.test.js

Migrates all mocha tests to node:test of `packages/markdown/remark/`
Part of ☂️ Move Astro tests to node:test  #9873 
All test passed!
No docs added as this only affects testing.

chore: Migrate All `packages/markdown/remark/tests` to node:test

---

scripts/cmd/test.js

This PR increased the timeout of the node tests.
We touched a timeout here: https://github.com/withastro/astro/actions/runs/7871758088/job/21475712185
CI should pass

ci: increase node timeout

---

.changeset/sweet-chicken-sneeze.md
packages/astro/src/runtime/server/endpoint.ts

Improves error message that confusing reported that an APIRoute handler existed even when it couldn't be used.

qol(routing): improve endpoint error message

---

packages/astro/package.json

As per title, there was still one script missing
CI should pass

test: mocha should ignore `nodetest.js` files during unit testing

---

.changeset/thin-kangaroos-exist.md
packages/astro/src/vite-plugin-astro-server/response.ts
packages/astro/test/units/vite-plugin-astro-server/response.test.js

- Applies the same fix from [#9071](https://github.com/withastro/astro/pull/9071) to `vite-plugin-astro-server`
- Closes #9698
- Manually tested with the [minimal reproduction repo](https://github.com/pilcrowOnPaper/astro-readable-stream-bug) from [#9068](https://github.com/withastro/astro/issues/9068)
- I would need some help if tests are required 🙏
- N/A

Fix an issue where ReadableStream wasn't canceled in dev mode

---

.changeset/breezy-pets-dream.md
packages/integrations/vercel/src/serverless/adapter.ts

fix(vercel): trailing slash conflict

---

.changeset/hip-hotels-divide.md
packages/astro/src/content/runtime.ts
packages/astro/src/content/types-generator.ts
packages/astro/test/fixtures/content-collections/src/content/config.ts

Starlight users have struggled with a warning message for the `i18n` collection:
> [WARN] [content] The **i18n** collection is defined but no content/i18n folder exists in the content directory. Create a new folder for the collection, or check your content configuration file for typos.
This warning was initially added to prevent typos between your configured collection name and the *actual* directory name. Even so, warning logs are easily lost during development. [This GitHub discussion describes hours lost](https://github.com/withastro/roadmap/discussions/817#discussioncomment-8211622) due to this. 
What we want is some indicator during development that there's a mismatch, without excessive console warnings. We landed here:
1. We should **remove the warning** for a configured collection …

Refine content collection warnings

---

packages/astro/test/alias-tsconfig-baseurl-only.nodetest.js
packages/astro/test/alias-tsconfig.nodetest.js
packages/astro/test/alias.nodetest.js

- related issue #9873 
- migrating `alias` related tests to `node:test`
All tests passing. `alias.nodetest.js` seems to be skipped on local testing (probably because of isWindows util)
N/A

chore: migrate `alias` tests to `node:test`

---

.changeset/silent-hotels-approve.md
packages/astro/e2e/dev-toolbar-audits.test.js
packages/astro/e2e/dev-toolbar.test.js
packages/astro/src/runtime/client/dev-toolbar/apps/astro.ts

We use the `astro:` shape for every built-in app, which we then use in telemetry and stuff to detect if an app is ours or not. The homepage however had an old name, so this renames that
Updated tests!
N/A

Rename Astro app to astro:home

---

.changeset/twelve-waves-matter.md
packages/astro/src/cli/add/index.ts
packages/create-astro/src/messages.ts
packages/upgrade/src/messages.ts

- Fixes an issue reported in a [Discord support thread](https://discord.com/channels/830184174198718474/1207399351073247283).
- The `getRegistry` functions used in our CLI tools `create astro`, `astro add` and `@astrojs/upgrade` assumed that the output of the CLI command `<package manager> config get registry` would always be a URL. However, in the reported case, the command output started with a warning message, which was then returned by `getRegistry` without further validation, causing all dependent functionality to fail in unexpected ways.
- This PR validates the output by trying to construct a URL instance from it, which will either throw an error that gets caught by the catch clause, or have an empty `host`. In both cases, our existing fallback URL `https://registry.npmjs.org` will …

Fix invalid URLs being returned from `getRegistry`, synchronize all copies of the function

---

.changeset/afraid-seals-tan.md
packages/astro/src/prerender/routing.ts

- Closes #9703 
- Workaround for what I think is a race condition in vite.
- Manually tested.
- Workaround; existing tests should pass.

fix(dev): preload matched routes sequentially

---

.changeset/empty-carrots-film.md
packages/astro/package.json
packages/astro/src/core/build/plugins/plugin-css.ts
packages/astro/src/core/build/plugins/plugin-hoisted-scripts.ts
packages/astro/src/core/build/plugins/util.ts
packages/integrations/alpinejs/package.json
packages/integrations/markdoc/package.json
packages/integrations/mdx/package.json
packages/integrations/react/package.json
packages/integrations/svelte/package.json
packages/integrations/tailwind/package.json
packages/integrations/vue/package.json
pnpm-lock.yaml

Update to Vite 5.1. Also handle the type changes for `vite.build.assetsInlineLimit` that now accepts a function. Other than that, it's just a version bump.
Vite 5.1 has other features that should trim down our code too that I'll send as separate PRs later.
n/a. version upgrade.

Update to Vite 5.1

---

packages/astro/test/css-assets.nodetest.js
packages/astro/test/css-dangling-references.nodetest.js
packages/astro/test/css-import-as-inline.nodetest.js
packages/astro/test/css-inline-stylesheets.nodetest.js
packages/astro/test/css-no-code-split.nodetest.js
packages/astro/test/css-order-import.nodetest.js
packages/astro/test/css-order-layout.nodetest.js
packages/astro/test/css-order.nodetest.js

- migrate `css-**` tests to node:test
- related issue #9873 
All tests passing with `test:node` script
N/A

chore: move `css-` related tests to `node:test`

---

.changeset/itchy-monkeys-fail.md
packages/astro/src/cli/add/index.ts
packages/astro/src/cli/db/index.ts
packages/astro/src/cli/info/index.ts
packages/astro/src/cli/preferences/index.ts
packages/astro/src/core/preview/index.ts
packages/integrations/vercel/src/serverless/adapter.ts

I tried to import Vue Astro adapter and I got an error. The error is the next one:
And I tried to import any other adapter and I get the same error when using the Vercel serverless adapter.
After seeing the problem, I added the node crypto import into the Vercel adapter and the error gone:
Edit:
This is my astro.config.mjs

fix(cli): load polyfill before loading config during `astro add`

---

.changeset/flat-rabbits-pump.md
packages/astro/src/content/types-generator.ts
packages/astro/src/core/dev/restart.ts
packages/astro/src/core/module-loader/vite.ts
packages/astro/src/core/sync/index.ts
packages/astro/src/vite-plugin-astro/hmr.ts
packages/astro/src/vite-plugin-dev-toolbar/vite-plugin-dev-toolbar.ts

Migrate from `ws` to `hot`, which provides the same interface, but allows signalling all HMR clients (not just the browser but also SSR) about certain events. `ws` was deprecated in Vite 5.1.
This unblocks one of the hurdles when using the new Vite Runtime API. cc @alexanderniebuhr 
n/a. Didn't add a changeset as there shouldn't be any visible changes.

Update Vite ws property to hot

---

packages/astro/test/experimental-content-collection-references.nodetest.js
packages/astro/test/experimental-content-collections-css-inline-stylesheets.nodetest.js
packages/astro/test/experimental-content-collections-render.nodetest.js
packages/astro/test/experimental-content-collections.nodetest.js
packages/astro/test/units/dev/hydration.nodetest.js
packages/integrations/node/test/errors.test.js
packages/integrations/node/test/prerender.test.js

This PR does the following:
- fixes a bunch of issues caused by the content collection tests. The `.clean()` function that was called in the `after` hook is **async**, but it was called without an `await` causing all the next test cases to fail the build because a clean up was in progress cc @florian-lefebvre 
- there were some issues in some other tests. I will have to ping people internally to figure out why the are failing now. The `hydration` test seems legitimate. The `errors` test is weird, I wonder if it's some kind of regression cc @lilnasy 
The CI should pass

chore: fix failing tests and skip some

---

packages/astro/src/core/errors/errors-data.ts

Fixes a missing backtick in a markdown link.

Fix docs markdown link

---

packages/astro/test/i18n-routing.test.js

- Add missing asserts in the tests for `packages/astro/test/i18n-routing` which use `try/catch` (related: https://github.com/withastro/astro/issues/9905)
- This was previously not implemented as it relied on moving tests to `nodejs`
To run the test case:
```zsh
pnpm astro-scripts test "test/**/i18n-routing.test.js"  
```
This only affects the tests, so no docs.

chore: fix tests in `packages/astro/test/i18n-routing` which use `try/catch`

---

.changeset/large-planets-kick.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/config/schema.ts

Addresses the typing issue of https://github.com/withastro/astro/issues/10157
The properties inside `i18n.routing` were incorrectly typed. Now they are optional.
The type of `domains` was placed in the wrong part of the config... ooops! I fixed that too
It should compile and current tests should pass
N/A

fix(i18n): make `i18n.routing` fields optional

---

.changeset/spotty-cobras-warn.md
packages/astro/src/runtime/client/dev-toolbar/apps/audit/a11y.ts

- Fixes an issue where audit fails to initialize when encountered `<a>` inside `<svg>` (`innerText` of an SVG element seems to be `undefined`, hence the error)
| ------ | ----- |
| ![before](https://github.com/withastro/astro/assets/40516784/76e631f5-dea3-4516-8a62-1c989d2326da) | ![after](https://github.com/withastro/astro/assets/40516784/edf2eaec-3c7b-4fec-b707-ffceed3b62fb) |
- Closes #10146
- Manually tested with the [minimal reproducible repo](https://stackblitz.com/edit/github-5z8nnr?file=src%2Fpages%2Findex.astro) from [#10146](https://github.com/withastro/astro/issues/10146)
- N/A

Fix an issue where audit fails to initialize when encountered `<a>` inside `<svg>`

---

packages/astro/src/core/errors/errors-data.ts

`acheive` -> `achieve`
Yes!?
It will update our Error page for this error, no need for changeset.

Fix typo in `errors-data.ts`

---

.changeset/sour-ties-sparkle.md
packages/integrations/sitemap/src/index.ts
packages/integrations/sitemap/test/dynamic-path.test.js
packages/integrations/sitemap/test/fixtures/dynamic/astro.config.mjs
packages/integrations/sitemap/test/fixtures/dynamic/package.json
packages/integrations/sitemap/test/fixtures/dynamic/src/pages/[...slug].astro
pnpm-lock.yaml

* fixes the issue described here: #9946 
* I've written unit tests here: `packages/integrations/sitemap/test/dynamic-path.test.js`
No docs update required

fix(sitemap): url when rest parameter is used in page file names

---

.changeset/light-masks-watch.md
packages/astro/src/vite-plugin-astro-server/response.ts

Since about a week ago, we were logging errors twice wrongly
N/A

fix(errors): Remove duplicate logging of errors

---

.changeset/cuddly-ads-fail.md
.changeset/quick-bottles-march.md
packages/astro/src/content/vite-plugin-content-virtual-mod.ts
packages/astro/src/core/build/plugins/plugin-content.ts
packages/astro/src/core/create-vite.ts
packages/astro/src/transitions/vite-plugin-transitions.ts
packages/integrations/vercel/src/serverless/adapter.ts

- Include `astro > cssesc` as an optimized dep
- Fixes https://github.com/withastro/astro/issues/9880
- Fixes https://github.com/withastro/astro/issues/10187
- Loading `astro:content` loads a lot of Astro's internal server-side code. This includes the server-side portion of View Transitions. This code depends on `cssesc` which is used to correctly escape `view-transition-name` properties to what is valid in CSS. This code is CommonJS and doesn't work in the browser unless optimized. This change makes it so that this module can be optimized.
- Note that you should not be using `astro:content` in the browser. This is only being fixed because a significant number of people are doing so. This PR will be updated to warn.
- Can't be tested in the monorepo, where dependencies are loaded …

Fix cssesc from breaking browser code

---

.changeset/three-deers-glow.md
packages/integrations/preact/package.json
pnpm-lock.yaml

`preact-render-to-string`'s last version has a regression, and it now returns an array of string instead of a string in some situations. 
Fix https://github.com/withastro/astro/issues/10191
We actually have a test for this, but it didn't catch it since we were not using the latest version of the library, oops.
N/A

fix(preact): Fixes passing children to server-rendered components causing an error

---

.changeset/popular-turtles-sort.md
packages/integrations/vercel/src/serverless/middleware.ts

- Fixes https://github.com/withastro/astro/issues/10069
- The call to the downstream function was being resolve relative to the input url. So if that's `/first/second` then it resolves to `/first/_render` which it should always resolve to `/_render`. This fixes that.
- Preview release with the reproduction working:
N/A, bug fix

Fixes edge middleware calling nested routes

---

.changeset/young-pears-brake.md
packages/db/src/core/errors.ts
packages/db/src/core/integration/index.ts
packages/db/src/core/queries.ts

Improve error messaging with hidden stack traces and greater context.

Improved error logging from config

---

.changeset/metal-schools-type.md
packages/astro/src/core/render-context.ts

- Makes computing i18n attributes lazy again. Computing `preferredLanguage`, for example, involves reading the `Accept-Language` header.

prevent warning: `Astro.request.headers` is not available in "static" output mode

---

.changeset/breezy-pears-admire.md
packages/astro/src/runtime/server/render/astro/render-template.ts
packages/astro/src/runtime/server/render/util.ts
packages/astro/test/error-bad-js.test.js
packages/astro/test/fixtures/error-bad-js/src/components/Other.astro
packages/astro/test/fixtures/error-bad-js/src/other.js
packages/astro/test/fixtures/error-bad-js/src/pages/in-stream.astro
packages/astro/test/fixtures/error-bad-js/src/something.js

- When an error occurs in an expression, capture the error and use it later when rendering occurs.
- this assures that no error go uncaught. Everything is resolve within the rendering flow.
- Fixes https://github.com/withastro/astro/issues/10062
- No test case added
N/A, bug fix

Prevent errors in rendering from crashing server

---

.changeset/dirty-boats-suffer.md
packages/astro/src/core/render/result.ts
packages/astro/src/runtime/server/escape.ts
packages/astro/test/fixtures/hydration-race/src/components/WithSlot.astro
packages/astro/test/fixtures/hydration-race/src/pages/slot.astro
packages/astro/test/hydration-race.test.js

- slots are a special kind of string a `SlotString`. The fix is to allow this to be passed into `<Fragment set:html={slotString} />`, where we were previously missing a check.
- Fixes https://github.com/withastro/astro/issues/8212
- Test added
N/A, bug fix

Fix hydration scripts missing from dynamic slot usage

---

.changeset/four-shoes-rule.md
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/test/fixtures/functionPerRoute/src/pages/prerender.astro
packages/integrations/vercel/test/split.test.js

- Filters out prerendered routes for Vercel adapter
- Closes #10211
- Test cases updated
- N/A

Fix an issue where Vercel adapter may create functions for prerendered routes

---

.changeset/tall-papayas-drive.md
packages/astro/src/core/errors/errors-data.ts

- Updates the message of `MiddlewareCantBeLoaded`
| Before                                                              | After                                                      |
| ------------------------------------------------------------------- | ---------------------------------------------------------- |
| The middleware threw an error while Astro was trying to loading it. | An unknown error was thrown while loading your middleware. |
- No tests added. Current tests should pass
- Error reference on the docs seems to be auto-generated

Improve the message of `MiddlewareCantBeLoaded` for clarity

---

.changeset/gold-baboons-drum.md
package.json
packages/integrations/svelte/package.json
pnpm-lock.yaml

Svelte's tool for editor tooling (`svelte2tsx`) require TypeScript to work. A long time ago, we were able to provide it from our language server directly, but this hasn't been the case for a long time now.
An alternative fix upstream would be for `svelte2tsx` to take in an instance of TypeScript, however at the moment it imports it from a bunch of top level places and it would be a significant refactor.
Svelte's own tooling does not suffer from this because it's all bundled together, unlike us where Svelte's specific tooling is only in its own integration.
Fix https://github.com/withastro/language-tools/issues/652
N/A
N/A

Fix Svelte editor tooling not working under relaxed TypeScripts projects

---

.changeset/eight-shrimps-enjoy.md
packages/astro/src/runtime/server/transition.ts

`transition:animate="none"` removed animations on old and new image, but not the morph animation on the transition group. Noticed that when analyzing #10241 
Mannualy tested, see #10241 
Before
After:
n.a

Removes morph animations when setting transition:animate=none

---

.changeset/wicked-houses-occur.md
packages/astro/components/Code.astro

- Replaces `BuiltinTheme` with `ThemePresets` in `Code` component
- Closes #10246
- Manually tested with the [minimal reproducible example](https://stackblitz.com/edit/github-uhurkz?file=src%2Fpages%2Findex.astro)
- N/A

Fix TypeScript type definitions for `Code` component

---

.changeset/great-flowers-own.md
packages/astro/src/core/render/route-cache.ts

Closes https://github.com/withastro/astro/issues/8241
Closes PLT-1716
This PR changes the key of our internal route caching. Previously, we were using `RouteData#component`, which used to cover most of the cases, although it seems too restrictive, because the same component can emit multiple paths.
This means that, given the [minimum use case](https://github.com/withastro/astro/issues/8241#issuecomment-1863928168), the first time we hit `/blog/world`, we correctly render the route and cache its params, props and static paths using the `/blog/[post].astro` as key. When we attempt to render `/fr/blog/world`, we hit the cache because this path is rendered by the same component, although the static paths don't match, so we emit an error and return a 404.
With this change, we use …

fix: change strategy for route caching

---

.changeset/loud-pianos-pretend.md
packages/astro/src/core/build/generate.ts
packages/astro/test/fixtures/i18n-routing-fallback-index/astro.config.mjs
packages/astro/test/fixtures/i18n-routing-fallback-index/package.json
packages/astro/test/fixtures/i18n-routing-fallback-index/src/pages/index.astro
packages/astro/test/fixtures/i18n-routing-fallback-index/src/pages/pt/index.astro
packages/astro/test/i18n-routing.test.js
pnpm-lock.yaml

Closes #10226
This PR fixes the overwriting of localised index pages with redirects:
- Fallback pages are checked before rendering. `generatePath` function now checks if there is already a page on the same path among non-fallback pages (`option.allPages`) before rendering a fallback page. And skipping if a page with the same path is found, this means the index page is localised and fallback page should not be rendered.
- Fallback pages are not rendered twice. `getPathsForRoute` function does not add fallback routes to be list of rendered as they are already handled by `eachRouteInRouteData` function. Otherwise this causes localised index pages to be overwritten with the original index page.
- New fixture is added: `i18n-routing-fallback-index`
- Localised index page's content is checked
- …

fix(i18n): localised index pages are overwritten

---

.changeset/few-worms-rush.md
packages/astro/src/@types/astro.ts

Adds auto completion for `astro:` event names when adding or removing event listeners on `document`.
VS Code shows completions 
n.a.

Adds auto completion for `astro:` event names when adding or removing event listeners on `document`

---

examples/with-vitest/package.json
pnpm-lock.yaml

Vitest check was failing again after https://github.com/withastro/astro/pull/10259. This should fix it, by making sure the Vite version used by Vitest is the same as us.
n/a

Fix Vitest check fail again

---

packages/db/src/core/cli/commands/link/index.ts

- Improves the `astro link` command to handle new project creation
- Improves the `astro link` command to handle existing project linking by name (vs. currently, only supporting an id passed as argument)
- N/A
- N/A

improve link command

---

packages/db/package.json
packages/db/src/core/cli/commands/login/index.ts
packages/db/src/core/cli/index.ts
pnpm-lock.yaml

- Improves the login flow, fixing a bug for Brave users who were blocked from talking to localhost in the browser. Now, we redirect the user directly to localhost to pass the session token via query param.
- N/A
- N/A

improve login command 

---

.changeset/perfect-poets-teach.md
packages/integrations/node/src/serve-app.ts

`new Request` can throw an error if the request is super malformed, this could crash the server in some situations.
I couldn't figure out how to test this in our fixtures, Node refuses to create an invalid request that triggers the error 🤔
N/A

fix(node): Safely create requests

---

.changeset/fifty-buttons-clean.md
packages/astro/src/core/build/generate.ts
packages/astro/test/redirects.test.js

- Reported here: https://github.com/withastro/astro/issues/10164#issuecomment-1957016426.
- A middleware returned redirects which made files disappear in build only with the vercel adapter.
- Added a case in `test/redirects.test.js`.

fix(build): skip only the configured redirects

---

.changeset/giant-lions-dance.md
packages/db/package.json
packages/db/src/runtime/db-client.ts

- Update db package to reference base `index.d.ts` to ensure `astro:db` is defined.

fix: reference base types

---

.changeset/curvy-trees-compare.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/render-context.ts
packages/astro/src/i18n/middleware.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/i18n-routing-prefix-always/src/pages/404.astro
packages/astro/test/i18n-routing.test.js
packages/astro/test/units/routing/endpoints.test.js

- Fixes #10276 
- Added cases to `test/i18n-routing.test.js`

fix(i18n): prevent overwriting 404.astro

---

examples/framework-alpine/src/components/Counter.astro
examples/framework-alpine/src/pages/index.astro
examples/framework-lit/src/pages/index.astro
examples/framework-multiple/src/pages/index.astro
examples/framework-preact/src/pages/index.astro
examples/framework-react/src/pages/index.astro
examples/framework-solid/src/pages/index.astro
examples/framework-svelte/src/pages/index.astro
examples/framework-vue/src/pages/index.astro
examples/portfolio/src/pages/index.astro
examples/with-tailwindcss/src/pages/index.astro
packages/astro/e2e/fixtures/client-only/src/pages/index.astro
packages/astro/e2e/fixtures/multiple-frameworks/src/pages/index.astro
packages/astro/e2e/fixtures/nested-in-preact/src/pages/index.astro
packages/astro/e2e/fixtures/nested-in-react/src/pages/index.astro
packages/astro/e2e/fixtures/nested-in-solid/src/pages/index.astro
packages/astro/e2e/fixtures/nested-in-svelte/src/pages/index.astro
packages/astro/e2e/fixtures/nested-in-vue/src/pages/index.astro
packages/astro/test/fixtures/hydration-race/src/pages/slot.astro

Fixes link that gives error 404, copied across several files.
https://docs.astro.build/core-concepts/astro-components/ gives 404, appears to be moved to https://docs.astro.build/basics/astro-components/

fix broken link in code examples

---

packages/db/README.md

N/A
N/A
Docs will be released on 4/12

Add minimal @astrojs/db readme

---

package.json
packages/integrations/mdx/package.json
pnpm-lock.yaml
turbo.json

ref: https://github.com/withastro/astro/issues/10320
`turbo run test` should now re-execute integration tests correctly if Astro core is updated. CI times may take longer now whenever we make changes to Astro core, but this is technically more accurate.
Also updated `turbo` to latest.
Ran `pnpm test` locally and inspected the [turbo test relationship graph](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A%20%20%20%20%20%20%20%20compound%20%3D%20%22true%22%0A%20%20%20%20%20%20%20%20newrank%20%3D%20%22true%22%0A%20%20%20%20%20%20%20%20subgraph%20%22root%22%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20%40astrojs%2Falpinejs%23test%22%20-%3E%20%22%5Broot%5D%20astro%23test%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20%40astrojs%2Falpi …

Update turbo test dependsOn

---

.changeset/slimy-berries-mate.md
packages/integrations/vercel/package.json
pnpm-lock.yaml

- Closes #10297
- Need to wait for OP confirmation
Tests should still pass
Bug fix, N/A

chore(vercel): update @vercel/nft

---

packages/integrations/vue/src/editor.cts
packages/integrations/vue/test/toTsx.test.cts
packages/integrations/vue/test/toTsx.test.js

fix https://github.com/withastro/language-tools/issues/758
- Modify the regular expression for matching defineProps
- Removes the condition where comments exist when working with code
- Fixed an issue with 'defineProps' import error

fix: fixed an error in the vue component editor

---

.changeset/sharp-scissors-think.md
packages/astro/e2e/fixtures/nested-in-react/src/pages/nested-in-only.astro
packages/astro/e2e/nested-in-react.test.js
packages/astro/playwright.config.js
packages/astro/src/runtime/server/render/slot.ts

- Fixes #9996
- The slot rendered first eagerly and stringified the island script with it. The slot was then put inside a template tag because the parent component is `client:only`.
- Island script should have been rendered right before the parent component itself. The `RenderDestination`-`RenderInstance` system makes sure that while things execute out of sequence, they get "stringified" in sequence.
- The reason was that slots are rendered in a temporary render destination and some chunk types are not handled there, falling back to stringifying immediately.
- The fix is to defer stringifying to the real destination, accumulating instructions in the `SlotString` untouched.
- Added a case in an existing E2E fixture.

fix(rendering): allow render instructions to propagate while rendering slots

---

.changeset/two-coats-smoke.md

Missed a changeset on #10330 !

add missing changeset

---

.changeset/dry-pants-act.md
packages/db/index.d.ts
packages/db/src/index.ts
packages/db/virtual.d.ts

Mixing a `declare module` statement within `index.d.ts` does not properly declare the type. This is because `index.d.ts` contains an `export` statement already.
- Move `astro:db` declaration to separate `virtual.d.ts`
- Refactor barrel export to individual exports. Barrel exports from a relative path are _not_ supported in virtual modules sadly

fix: move db ambient types to separate module

---

packages/astro/src/cli/install-package.ts

Fixes bug where every time a `astro db` command is used it prompts the user to add `@astrojs/db` even if it is already installed
No tests, it is a pretty small fix for an error that doesn't get surfaced because it is inside a try/catch
> Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
No docs needed

Fix cli package resolution for `@astrojs/db`

---

.changeset/tough-moose-prove.md
packages/astro/e2e/dev-toolbar-audits.test.js
packages/astro/e2e/fixtures/dev-toolbar/src/pages/a11y-exceptions.astro
packages/astro/src/runtime/client/dev-toolbar/apps/audit/a11y.ts

This PR adds `a` to the list of element that can be interactive.
Interactive elements are usually marked with the `"widget"` role. [`link`](https://www.w3.org/TR/wai-aria-1.1/#link) role is a `command` role, which is a superclass that includes `"widget"`.
I am happy to add a test with some guidance 
N/A

fix(toolbar): add anchor element to interactive elements

---

.changeset/polite-bats-smile.md
packages/astro/src/content/runtime.ts
packages/astro/test/content-collections.test.js
packages/astro/test/fixtures/content-collections-empty-dir/src/pages/index.astro

- Fixes an issue where `getCollection` might return `undefined` when content collection is empty
- Closes #8999
- A related test case in `packages/astro/test/content-collections.test.js` is updated
- N/A

Fix an issue where `getCollection` might return `undefined`

---

.changeset/sour-apples-try.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/base-pipeline.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/compile/compile.ts
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/core/middleware/index.ts
packages/astro/src/core/render-context.ts
packages/astro/src/core/render/index.ts
packages/astro/src/core/render/result.ts
packages/astro/src/i18n/utils.ts
packages/astro/src/runtime/server/astro-global.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/test/astro-global.test.js
packages/astro/test/ssr-api-route.test.js
packages/astro/test/units/test-utils.js

- Fixes #10303
- Colocates code for the `Astro` global alongside that of `APIContext`.
- Removes `base` out of the picture while generating `manifest.site`.
- Added to `astro-global.test.js` and `ssr-api-route.test.js`

fix(Astro global): parity with `ctx.site`

---

.changeset/fluffy-bobcats-arrive.md
packages/db/src/core/cli/commands/push/index.ts
packages/db/src/core/cli/migration-queries.ts
packages/db/src/core/consts.ts
packages/db/src/core/types.ts
packages/db/test/unit/column-queries.test.js

- Removed `experimentalVersion` on migration schemas.
- Added `version`, a date string that starts with the package's release date.
- Updated tests
N/A

db: rename experimentalVersion to version

---

.changeset/healthy-taxis-applaud.md
packages/db/src/core/cli/commands/execute/index.ts
packages/db/src/core/cli/commands/shell/index.ts
packages/db/src/core/consts.ts
packages/db/src/core/errors.ts
packages/db/src/core/integration/index.ts
packages/db/src/core/integration/vite-plugin-db.ts
packages/db/src/runtime/db-client.ts
packages/db/src/runtime/index.ts
packages/db/src/runtime/queries.ts
packages/db/test/basics.test.js
packages/db/test/fixtures/ticketing-example/db/config.ts

Require the `--remote` flag to dev or build with a studio connection. Use a local db with local seeding for standard `astro build` call.
- Add `--remote` check to dev and build
- Add `--remote` support to `shell` and `execute`
- Move table recreation from runtime to buildtime. Prevents build hanging failure and unblocks SSR app usage
- Refactor in-memory databases to a generate db hash. Solves the clobbering problem and remove all special logic for in-memory data
- Misc: remove bad `author3` and `author4` config in ticketing example
- Add in-memory db patch for seeding to ensure tests still run
https://docs-git-sarah-patch-6-astrodotbuild.vercel.app/en/guides/astro-db/#production-builds

Add `--remote` flag for remote connection

---

.changeset/weak-weeks-pump.md
packages/db/package.json
packages/db/src/core/cli/commands/execute/index.ts
packages/db/src/runtime/db-client.ts
packages/db/test/fixtures/basics/db/seed.ts
pnpm-lock.yaml

Add support for `db.batch()` to run multiple queries in a single transaction.
- Bump Drizzle to 0.29.5 (minor bump)
- Implement batching for the remote adapter. Nothing to do for local
- Add `db.batch()` call to basics test fixture
N/A

Add batch support

---

.changeset/wet-kiwis-laugh.md
packages/astro/src/cli/add/index.ts
packages/db/src/runtime/config.ts
packages/db/test/fixtures/basics/db/config.ts
packages/db/test/fixtures/integrations/db/config.ts
packages/db/test/fixtures/integrations/integration/config.ts
packages/db/test/fixtures/recipes/db/config.ts
packages/db/test/fixtures/ticketing-example/db/config.ts
packages/db/virtual.d.ts

- Renames the `defineDB()` helper to `defineDb()` to align with other APIs which use `Db` for better readability.
- Existing tests should pass
- Docs will need updating to use the new casing

Rename `defineDB` to `defineDb`

---

.changeset/khaki-emus-wait.md
packages/astro/src/core/config/vite-load.ts

Fixes #10262
This fixes an issue where creating a vite server (to e.g. load a TypeScript astro config) would trigger vite to look up and load an unrelated vite config (potentially going up directories).
This has not been tested because I'm not familiar with the astro testing setup...
This fixes an unexpected side effect of loading a TypeScript config. Since this is the expected behavior, it might not require documentation.

fix(config): prevent vite from loading config

---

.github/workflows/check-merge.yml

Noticed that the `check-marge` workflow was failing for https://github.com/withastro/astro/pull/10189. As noted in the [GH docs](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token), `GITHUB_TOKEN` has a hard permission limit for PRs from forks. The way to elevate the permissions and "trust" this PR is to use the [`pull_request_target` event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target).
However, when using that event, `actions/checkout` will only operate on the base branch of the PR. I needed to update `actions/checkout` to checkout the head of the PR instead to fix this. This means we can "trust" the code coming from the PR with the elevated `GITHUB_TOKEN` permissions, …

Fix check-merge workflow on PRs from forks

---

SECURITY.md

Update `SECURITY.md` to use GitHub to report vulnerabilties. This is only for this repo, for other repos it'll fallback to the default in https://github.com/withastro/.github/blob/main/SECURITY.md (via email).
Starting this PR as a point of discussion, we could decide whether we want to do this or not. From Discord, this new flow will look like:
1. First, we need to enable the feature at https://github.com/withastro/astro/settings/security_analysis
2. When creating a bug report, users can choose to submit a security report instead, e.g. [vite](https://github.com/vitejs/vite/issues/new/choose)
3. Users can fill in the form to describe the severity and explain in private. Only repo admins can see unless they invite others.
4. We can triage them (comment, close, update descriptions/severity, …

Update security flow to report on GitHub

---

packages/integrations/mdx/package.json
pnpm-lock.yaml

We're using shiki 1.0, and `rehype-pretty-code` has a peer dep on shiki, so we also need to bump `rehype-pretty-code` to latest so it supports shiki 1.0. This is not a breaking change for Astro since existing users of `rehype-pretty-code` can install shiki 0.x locally to continue have it work.
Ran the mdx tests locally.
n/a

Fix mdx test fail with rehype-pretty-code

---

.changeset/slimy-avocados-sniff.md
packages/astro/tsconfigs/base.json

Despite being supposed to only affect emitting, the `jsx` setting is required to import JSX and internally considered to be JSX files, or you get an error. This adds `jsx: 'preserve'`, the safest setting to our base preset. 
This shouldn't affect anything, for two reasons:
- We don't use TypeScript to emit JSX code
- Using `astro add JSX_FRAMEWORK` already changes the `tsconfig.json` to something else for frameworks that need it (most of which are in fact, using `preserve` already)
Fix https://github.com/withastro/language-tools/issues/787
N/A

fix(tsconfigs): Add `jsx: 'preserve'` to the base template

---

.changeset/brown-pets-clean.md
packages/astro/src/core/app/index.ts
packages/astro/src/core/constants.ts
packages/astro/src/core/render/params-and-props.ts
packages/astro/src/core/routing/astro-designed-error-pages.ts
packages/astro/src/runtime/server/render/astro/factory.ts
packages/astro/src/runtime/server/render/astro/instance.ts
packages/astro/src/vite-plugin-astro-server/pipeline.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/src/vite-plugin-astro-server/response.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/astro-dev-headers.test.js
packages/astro/test/fixtures/virtual-routes/astro.config.js
packages/astro/test/fixtures/virtual-routes/package.json
packages/astro/test/fixtures/virtual-routes/src/middleware.js
packages/astro/test/units/routing/trailing-slash.test.js
packages/astro/test/virtual-routes.test.js
pnpm-lock.yaml

- Allows middleware to run for 404 responses without needing a 404.astro in the project.
- Fixes https://github.com/withastro/astro/issues/8244
- Fixes https://github.com/withastro/astro/issues/8226
- Adapted from https://github.com/withastro/astro/pull/10185/files
Mentions of `404.astro` or spread routes needing to exist to run middleware should be removed.

feat: middleware and virtual routes

---

.changeset/rotten-snakes-sip.md
packages/db/src/core/cli/commands/push/index.ts
packages/db/src/core/cli/commands/verify/index.ts
packages/db/src/core/cli/migration-queries.ts

- handle undefined snapshot from API
- This is an upcoming change to the API response format that will go out on Monday, along with the release of this PR
- N/A (tested manually)
- N/A

[@astrojs/db] handle undefined snapshot from API

---

.changeset/perfect-experts-attend.md
packages/db/src/core/consts.ts
packages/db/src/core/integration/index.ts
packages/db/src/core/integration/vite-plugin-db.ts
packages/db/src/runtime/index.ts
packages/db/test/basics.test.js
packages/db/test/integrations.test.js

- Switches from dynamic to static imports for integration seed files in the `astro:db` virtual module.
- Fixes a bug where builds would fail silently when using integrations.
Added a simple test with build output for the integrations fixture and also tested `astro build` manually locally.
N/A — bug fix

Use static imports for integration seed files in `astro:db`

---

.changeset/rare-items-protect.md
packages/db/package.json
pnpm-lock.yaml

- We use `db.batch` internally.
- Upgrading to the latest `@libsql/client` fixes this as they did a patch to export the underlying functions needed.
- [Example app](https://stackblitz.com/edit/github-ztm1ny?file=src%2Fpages%2Findex.astro,package.json)
N/A

Fix use of db.batch in Stackblitz

---

.changeset/calm-roses-camp.md
packages/db/src/core/consts.ts
packages/db/src/core/integration/vite-plugin-db.ts
packages/db/src/runtime/index.ts
packages/db/src/runtime/seed-local.ts
packages/db/test/fixtures/integration-only/astro.config.mjs
packages/db/test/fixtures/integration-only/integration/config.ts
packages/db/test/fixtures/integration-only/integration/index.ts
packages/db/test/fixtures/integration-only/integration/seed.ts
packages/db/test/fixtures/integration-only/integration/shared.ts
packages/db/test/fixtures/integration-only/package.json
packages/db/test/fixtures/integration-only/src/pages/index.astro
packages/db/test/fixtures/no-seed/astro.config.ts
packages/db/test/fixtures/no-seed/db/config.ts
packages/db/test/fixtures/no-seed/package.json
packages/db/test/fixtures/no-seed/src/pages/index.astro
packages/db/test/integration-only.test.js
packages/db/test/no-seed.test.js
pnpm-lock.yaml

- Fixes `astro:db` integration support when an Astro project doesn’t include a user-defined seed file.
- Source of the bug was this change: https://github.com/withastro/astro/pull/10352/files#diff-4d4325b62adab978b9a1910a7ae9742c5269220b88f3b4372ff1a2a7d7fc9704R64-R70
- This moved the table creation to be triggered when a user’s seed file is loaded. This meant in the absence of a user seed file, tables are never created.
- The fix is moving `recreateTables()` back to runtime, called each time we `seedLocal()`. @bholmesdev had some concerns about this initially but I think these were resolved in #10381.
- To help keep things organised, I’ve split `seedLocal()` into its own file.
- Added a fixture where an integration configures and seeds tables and no user config is present.
- Added a …

Fix db for projects without a seed file or with integrations

---

.github/labeler.yml

- Adds labelling automation for PRs changing `@astrojs/db`.
- I’ve found myself wanting a quick way to see open PRs for the package.
n/a
n/a

Add `pkg: db` to labelling automation

---

.changeset/soft-foxes-grin.md
packages/db/src/core/cli/commands/push/index.ts
packages/db/src/core/cli/migration-queries.ts

- We had an issue where the server was incorrectly returning a `200` on error responses.
- This is a bit redundant if everything is working well, but a good line of defense in case anything isn't.
- n/a
- n/a

[db] Add success=false handling to API entrypoints

---

.changeset/breezy-seals-begin.md
packages/db/package.json
packages/db/src/core/consts.ts
packages/db/tsconfig.json

Before, your LSP would recommend importing `defineDb()` from `@astrojs/runtime/config` before recommending `astro:db`. This change removes `runtime/config` from public types to only surface `astro:db`
Manual `pnpm link` to check intellisense
N/A

fix: remove runtime/config suggestion for db config exports

---

.changeset/thirty-bags-live.md
packages/astro/src/cli/index.ts
packages/db/src/core/cli/index.ts
packages/db/src/core/cli/print-help.ts

Manual call for the --help flag
N/A

New CLI help reference for studio and db commands

---

.changeset/silver-foxes-protect.md
packages/db/package.json
packages/db/src/core/cli/migration-queries.ts
packages/db/src/core/load-file.ts
packages/db/src/core/schemas.ts
packages/db/src/core/types.ts
packages/db/test/unit/column-queries.test.js
packages/db/test/unit/index-queries.test.js
packages/db/test/unit/reference-queries.test.js

We need to use these types in the dashboard. Since this technically makes the internal-ish types a part of the package's public interface, I'm open to alternate approaches if we want to avoid that

export DB types

---

.changeset/gentle-gorillas-sit.md
packages/astro/e2e/dev-toolbar.test.js
packages/astro/e2e/fixtures/dev-toolbar/src/pages/xray-props-escape.astro
packages/astro/src/runtime/client/dev-toolbar/apps/xray.ts

- Escapes props content when building island tooltips
- Closes #10375
- A test case is added
- Current tests should pass
- N/A

Fix an issue where dev toolbar x-ray didn't escape props content

---

.changeset/lazy-tools-reply.md
packages/db/src/core/cli/migration-queries.ts
packages/db/test/unit/column-queries.test.js

Remove call to "drop table if exists" when adding a table. This allowed tables to be dropped unexpectedly on a bad migration merge. This was an unexpected bug, and should raise a SQL error instead of dropping user data.

chore: remove drop table check for added table

---

.changeset/beige-gorillas-warn.md
packages/db/package.json
packages/db/src/core/consts.ts
packages/db/src/core/integration/typegen.ts
packages/db/tsconfig.config-types.json
packages/db/virtual.d.ts

Split config types to a separate `dist/_internal` to keep type inference while still masking types in your editor.

feat: split config types to separate build

---

.changeset/khaki-bears-enjoy.md
packages/astro/src/core/redirects/render.ts
packages/astro/test/redirects.test.js

- Fixes #10404
- https://github.com/withastro/astro/pull/10410/files
- Another test copied from https://github.com/withastro/astro/pull/10411, where @mingjunlu independently came up with the same solution!

fix(redirects): escape `Location` header

---

.github/workflows/check.yml
examples/framework-multiple/package.json
examples/framework-multiple/src/components/preact/PreactCounter.tsx
examples/framework-multiple/src/components/react/ReactCounter.tsx
examples/framework-multiple/src/components/solid/SolidCounter.tsx
examples/framework-preact/src/components/Counter.tsx
examples/framework-preact/src/components/Message.tsx
examples/framework-solid/src/components/Counter.tsx
examples/with-nanostores/src/cartStore.ts
examples/with-nanostores/tsconfig.json
package.json
packages/astro/package.json
pnpm-lock.yaml

`main` is currently failing on the examples check fail. Seems like `@astrojs/check` after the lockfile upgrade is able to properly typecheck `.tsx` files now. This PR improves the typings so it passes.
- I also updated `@astrojs/check` to latest (0.5.8) from 0.3.1 (this updates our version only and not a breaking change)
- I tweaked the `check.yml` workflow so it'll run whenever we do deps upgrades again. 
Ran `pnpm test:check-examples` locally.
n/a

Fix check example CI fail

---

.changeset/happy-tools-grab.md
packages/db/src/core/schemas.ts
packages/db/test/basics.test.js
packages/db/test/fixtures/basics/astro.config.ts
packages/db/test/fixtures/basics/db/config.ts
packages/db/test/fixtures/basics/db/seed.ts
packages/db/test/fixtures/basics/src/pages/login.astro

- Fixes #10408 
- Quick fix. Manually tested.

fix(db): validate column type before column schema

---

packages/astro/src/@types/astro.ts

VSCode will search from the root, unlike the inline `$schema` definition
_Note: this feature is amazing, thank you!_
Tested locally in my Astro project
Documentation-only change

Update VSCode Guidance for JSON Schemas

---

.changeset/thin-deers-sin.md
packages/astro/src/core/app/index.ts
packages/astro/test/fixtures/ssr-locals/src/pages/404.astro
packages/astro/test/fixtures/ssr-locals/src/pages/500.astro
packages/astro/test/fixtures/ssr-locals/src/pages/go-to-error-page.astro
packages/astro/test/ssr-locals.test.js

- Fixes #10421 
- Added to `ssr-locals` fixture.

fix(app): provide adapter locals to error pages

---

.changeset/empty-ants-crash.md
packages/db/src/core/cli/commands/link/index.ts

- Only `us-east` and `us-west` were available, this adds back the missing 4 other regions!
- N/A
- N/A

add missing regions to link command

---

packages/astro/test/ssr-api-route.test.js

- Fix a test case in `ssr-api-route.test.js` which might fail when run locally using IPv4
- The test case was recently added in #10325
- Tests were run locally using IPv4 several times
- N/A

Fix a test case which might fail when run locally using IPv4

---

.changeset/breezy-dancers-give.md
packages/db/src/core/tokens.ts

- A new attempt to solve this problem: https://github.com/withastro/astro/pull/10428
- That PR did solve the problem when each region had a single machine running, but failed to account for replication across multiple machines in the same region. 
- In practice, Machine A in region `sjc` could create your token and Machine B (also in region `sjc`) could attempt to use it before it's been propagated. Pinning to region `sjc` did not solve the problem in that case.
- The new solution removes the complexity of the original one, and now just embraces replication as something to wait for vs. trying to build around and solve for. It adds a delay on token creation greater than the maximum time our tokens take to propagate (2sec of wait vs. 1600ms of maximum token propagation). In the near future, …

[db] wait for token to propagate

---

.changeset/eleven-lobsters-doubt.md
packages/db/src/core/integration/vite-plugin-inject-env-ts.ts

Remove duplicate `astro:db` prefix on env type update

chore: remove duplicate astro:db log

---

.changeset/dry-rivers-switch.md
packages/db/src/core/integration/vite-plugin-db.ts

- Use the runtime `process.env.ASTRO_STUDIO_APP_TOKEN` before falling back to one that's in CI.
- manually
N/A, bug fix

Prefer getting app token from runtime env

---

.changeset/hip-mugs-know.md
packages/db/src/core/cli/commands/execute/index.ts
packages/db/src/core/errors.ts

Add formatted success and error logs to `db execute.
- Add LibSQL error formatting to match seed error messages
- Add success log

feat(db): `execute` command logs

---

.changeset/thirty-dancers-wink.md
packages/astro/src/transitions/router.ts

prevents access of null object, see #10235  
Manual tested
n.a.

Fixes an TypeError when using astro:transitions/client without <ViewTransitions>

---

.changeset/slow-rabbits-care.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/render-context.ts
packages/astro/src/runtime/server/render/astro/render.ts
packages/astro/src/runtime/server/render/component.ts
packages/astro/test/fixtures/streaming/astro.config.mjs
packages/astro/test/fixtures/streaming/package.json
packages/astro/test/fixtures/streaming/src/components/react.tsx
packages/astro/test/fixtures/streaming/src/pages/multiple-errors.astro
packages/astro/test/streaming.test.js
pnpm-lock.yaml

- Fixes #10367 in a runtime-agnostic way, but only for ~70% of the similar cases.
- `renderTemplate()` did not complete - an error was thrown before we could get references to the expressions.
- Luckily, `renderComponent()` allowed us to get a reference the promise that would reject, and we could handle it.
- Adapter the repro case into `node --test test/streaming.test.js`.

fix(rendering): allow framework renders to be cancelled

---

.changeset/sharp-flowers-ring.md
packages/integrations/node/src/serve-app.ts
packages/integrations/node/test/errors.test.js
packages/integrations/node/test/fixtures/errors/src/pages/offshoot-promise-rejection.astro

- Fixes #10367 thoroughly but only for the node adapter.
- Added

fix(node): handle offshoot promise rejections

---

.changeset/cuddly-suits-hunt.md
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/runtime/server/endpoint.ts
packages/astro/test/units/runtime/endpoints.test.js

- From a bad experience in a support thread.
- Misuse of endpoints results in `cant read status of undefined` (we do a check on `response.status`)
- Does not affect behavior.
- The error will show up in error reference on docs.

qol(endpoints): helpful error message when a response is not provided

---

.changeset/small-crabs-look.md
packages/db/src/core/tokens.ts

- The `/auth/cli/token-create` endpoint is being updated to handle the propagation itself, meaning that the client-side wait is no longer needed. 
- This means that older versions of this code will run ~2sec longer than actually needed. We can also add a query-param to opt-in to the server-side handling to avoid this, but ultimately it didn't feel worth it to me. Happy to revisit if others disagree.
- For older versions of this code, there will be no change to the user experience, just a shifting of responsibility out of the client.
- N/A
- N/A

[db] remove token creation wait time

---

.changeset/light-falcons-battle.md
packages/create-astro/src/actions/template.ts

This fix helps create-astro to work with Deno when using the typescript template.
```
deno run -A npm:create-astro@latest
```
Ref https://github.com/denoland/deno/issues/22537#issuecomment-2006165841

fix(packages/create-astro): wait for writeFile to complete in updateFiles

---

.changeset/clever-glasses-rest.md
packages/db/package.json
packages/db/src/runtime/config.ts
packages/db/virtual.d.ts
pnpm-lock.yaml

Expose drizzle aggregation helpers like `count()`. This includes a minor version bump to Drizzle ORM.
Manual testing to ensure exports exist.
It was documented even though it was not exposed 🙈

db: Expose aggregation helpers

---

.changeset/thick-games-thank.md
packages/astro/src/runtime/server/render/util.ts

HTML is not XML. It doesn't have self-closing tags, it has void element tags that don't need closing slashes.
Generated void elements (e.g. `link` with path to style file) do not pass validation, which can be easily fixed by simply removing two characters.
- FYI: https://jakearchibald.com/2023/against-self-closing-tags-in-html/
I'm not sure, but I hope I did it right.
I tested this change in my astro-project — it fixed the validity of the markup.
Correcting the documentation is most likely not necessary.

fix: void elements

---

.changeset/tender-snails-accept.md
packages/integrations/node/src/serve-static.ts
packages/integrations/node/test/fixtures/trailing-slash/public/one.css
packages/integrations/node/test/trailing-slash.test.js

- What does this change? It fixes #10481 .
- How: By not appending a trailing slash to subresource urls
- Added a new couple of tests to ensure that subresources such as .css files are properly served with a 200 status response.
This change is a bugfix, no documentation changes are needed.

fix: do not append trailing slash to subresource urls

---

.changeset/yellow-ducks-greet.md
packages/db/package.json
packages/db/src/core/cli/migration-queries.ts
packages/db/src/core/integration/typegen.ts
packages/db/test/unit/column-queries.test.js
pnpm-lock.yaml

This wasn't building locally thanks to `github-slugger` missing from the dependencies.
I've added it to the package, and a couple of tests while I was in there.
New unit tests were added (though unrelated to github-slugger)
N/A

chore(db): Add missing github-slugger dependency & tests

---

.changeset/lucky-brooms-help.md
packages/db/src/core/integration/vite-plugin-db.ts

- Removes fallbacks that grab the app token from the CI env. 
- This is because we require this token be set in your host env instead.
N/A
N/A

Removing embedding appToken from CI

---

.changeset/grumpy-years-lick.md
packages/db/src/runtime/config.ts
packages/db/src/runtime/db-client.ts
packages/db/virtual.d.ts

Users can call `db.transaction()` today, even though it is not supported by our remote DB adapter. This removes `db.transaction()` from our type definitions until this is supported, and raises a runtime error if called.
Manual `pnpm pack` to ensure types work.
N/A

Fix: remove `db.transaction()` from types until supported

---

.changeset/stale-jeans-yawn.md
packages/integrations/markdoc/src/extensions/shiki.ts
packages/markdown/remark/src/highlight.ts
packages/markdown/remark/src/shiki.ts
packages/markdown/remark/test/shiki.test.js

Fix https://github.com/withastro/astro/issues/10475
Some Shiki transformers can read the meta, e.g. `{1,3-4}` annotation from ```` ```js {1,3-4}````, to process certain transforms, e.g.https://shiki.style/packages/transformers#transformermetahighlight
Added new unit tests in markdown-remark
n/a. I think this is a bug as I assumed this should have already worked.

Pass meta to shiki transformers

---

.changeset/unlucky-pumas-retire.md
packages/db/src/runtime/config.ts
packages/db/test/error-handling.test.js
packages/db/test/fixtures/error-handling/astro.config.ts
packages/db/test/fixtures/error-handling/db/config.ts
packages/db/test/fixtures/error-handling/db/seed.ts
packages/db/test/fixtures/error-handling/package.json
packages/db/test/fixtures/error-handling/src/pages/foreign-key-constraint.json.ts
packages/db/virtual.d.ts
pnpm-lock.yaml

Expose `isDbError()` to catch database exceptions in your Astro project.
Add `isDbError()` test for a foreign key constraint.
https://github.com/withastro/docs/pull/7491

db: expose `isDbError()` utility

---

.changeset/itchy-oranges-relate.md
packages/integrations/vercel/package.json
packages/integrations/vercel/src/serverless/adapter.ts
packages/integrations/vercel/src/serverless/middleware.ts
packages/integrations/vercel/types.d.ts
pnpm-lock.yaml

- The `vercel-edge-middleware.js` file allowed users to access the [vercel edge runtime's `RequestContext`](https://vercel.com/docs/functions/edge-middleware/middleware-api#requestcontext) object, and create the middleware `locals` from its fields. However, this object [includes only one field](https://github.com/vercel/vercel/blob/vercel@33.6.1/packages/edge/src/request.ts#L13) - the `waitUntil()` function - which is now available directly as `ctx.locals.waitUntil()`.
- [Edge Middleware API Reference](https://vercel.com/docs/functions/edge-middleware/middleware-api#requestcontext)
- [@vercel/edge types](https://github.com/vercel/vercel/blob/vercel@33.6.1/packages/edge/src/request.ts#L13)
<details>
<summary>
- `console.log(context)`
</summary>
</details>
- Edge runtime behavior. Manually …

deprecation(vercel): vercel-edge-middleware.js file

---

.changeset/large-trees-give.md
packages/db/src/core/cli/commands/push/index.ts
packages/db/src/core/cli/migration-queries.ts
packages/db/test/unit/reset-queries.test.js

- Previously `--force-reset` did not include DROP TABLE statements
- Now it does, and they are prepended before creation statements.
- Fixes https://github.com/withastro/astro/issues/10451
- Added new unit tests for this.
N/A, bug fix

Ensure --force-reset drops previous tables

---

.changeset/modern-roses-buy.md
packages/db/src/core/integration/vite-plugin-db.ts

This reverts commit 2fc7231df28e5a3425ee47b871ba3766e0856bd8.
- This broken everything.
- Env is definitely needed locally, we should only be not including it during the build. Will follow up with a proper fix.
- Fixes https://github.com/withastro/astro/pull/10520
- Manual for now
N/A

Revert "Removing embedding appToken from CI (#10497)"

---

.changeset/twelve-rules-collect.md
packages/astro/src/runtime/server/jsx.ts
packages/astro/src/runtime/server/render/component.ts

Fixes https://github.com/withastro/astro/issues/10158
---
This fix requires some context, so here it is 😄:
When rendering JSX nodes, there's currently a problem where it can call `renderComponentToString` to render React/Vue/MDX component from JSX nodes, but it can also render JSX nodes again if it hits the `astro:jsx` renderer (for MDX). Creating a loop.
The solution to this problem is using "Skips" to make sure this order is ran (Worst case):
1. Try to render JSX nodes.
2. If fail, try to render components with React/Vue/MDX renderers.
3. Detected MDX, try to render its JSX nodes again.
4. Try to render components with React/Vue/MDX renderers.
5. Detected MDX, try to render its JSX nodes again.
6. Try to render JSX nodes again.
8. Finished. Returns rendered string or error.
(I don't …

Improve Astro JSX rendering

---

.github/workflows/ci.yml

- we pinned node versions twice because of regressions introduced in node, both are no longer necessary
- does not affect behavior
- does not affect usage

chore: test with latest minor versions of node

---

packages/db/src/core/integration/index.ts
packages/db/src/core/tokens.ts
packages/db/test/basics.test.js
packages/db/test/test-utils.js

Introduce a mock remote db server for testing the `--remote` flag and the remote database adapter.
- Add a `test-utils` file with `setupRemoteDbServer()`
- Add basics test for `dev --remote`
Basics test for `dev --remote`
N/A

db: dev --remote test fixture

---

CONTRIBUTING.md

Closes PLT-1798
This PR adds a new header in the contribution guide. It adds two new sections:
- a triaging workflow (heavily copied from vite)
- guidelines that explain the different priorities that we assigned to bugs
What I wrote isn't set in stone, and it should kick off some discussion around providing good/better guidelines for maintainers. 
@lilnasy also opened a [thread on Discord](https://discord.com/channels/830184174198718474/1215760899114270883) about it. 
One thing that we should improve is to clarify the distinction between `p4`/`p3`. I am also open to the idea of writing some clear requirements; for example, an issue becomes a p4 only if it reaches at least 10 thumbs-up reactions. 
Proofread
[Rendered section](https://github.com/withastro/astro/blob/chore/traiging-framework/ …

chore: add issue triaging workflow

---

packages/astro/src/content/vite-plugin-content-assets.ts
packages/astro/src/core/build/css-asset-name.ts
packages/astro/src/core/build/graph.ts
packages/astro/src/core/build/plugins/plugin-analyzer.ts
packages/astro/src/core/build/plugins/plugin-css.ts
packages/astro/src/vite-plugin-head/index.ts

Avoid generators when crawling the module graph. Instead calculate the entire array directly and return it. In most cases, we're using the entire array so benefits of generators like _able to bail out of iterating_ wasn't used.
existing tests should pass
In the astro docs repo, the Rollup build time went from 3m to 2m40s.

Avoid generators when crawling module graph

---

packages/astro/src/runtime/server/render/component.ts
packages/astro/src/runtime/server/render/head.ts
packages/astro/test/streaming.test.js

Return the render instruction directly instead of using generators. This should slightly improve performance.
n/a. internal refactor. I didn't add a changeset as it doesn't affect any user-facing features.

Avoid generators in render head API

---

.changeset/spotty-bats-nail.md
packages/astro/src/transitions/router.ts

fixes #10466 
Originally fixed for client:only components that use transition:persist in #8840.
It turns out that the styles were also missing when navigating back to pages with non-persisted `client:only` components.
e2e tests successful
bug fix, n.a.

Fixes a style issue of `client:only` components in DEV mode during view transitions.

---

.changeset/curly-donkeys-sleep.md
packages/db/src/core/cli/commands/execute/index.ts
packages/db/src/core/integration/vite-plugin-db.ts
packages/db/src/runtime/db-client.ts
packages/db/test/basics.test.js
packages/db/test/fixtures/no-apptoken/astro.config.ts
packages/db/test/fixtures/no-apptoken/db/config.ts
packages/db/test/fixtures/no-apptoken/db/seed.ts
packages/db/test/fixtures/no-apptoken/package.json
packages/db/test/fixtures/no-apptoken/src/pages/index.astro
packages/db/test/ssr-no-apptoken.test.js
pnpm-lock.yaml

- When we build we always get the app token from `process.env.ASTRO_STUDIO_APP_TOKEN` at runtime.
- `createRemoteDatabaseClient` now checks that it has an app token and throws without one.
- SSR test added in the basics fixture. Using the mock services this tests that production works, can test other production things here.
- Added test specifically for when there is not a runtime ASTRO_STUDIO_APP_TOKEN, to check that it throws.
N/A, bug fix

Require that ASTRO_STUDIO_REMOTE_DB_URL is defined at runtime

---

.changeset/eighty-pumpkins-float.md
packages/markdown/remark/src/shiki.ts

Previously, there was a hardcoded if condition which detected unknown languages and replaced them with `plaintext` for codeblocks. Hardcoding this value makes it impossible to use Shiki's `ansi` feature. Changed the code from using the hard coded value over to using a library function, fixing #10539.
- Instead of using the hard-coded check for an invalid language, use the built in function to do so.
- Enables using the `ansi` language (as well as `txt`, `text`, etc.)
Before and after photos:
This change was tested by modifying the blog example locally (not tracked). Unit tests may not be necessary for change.
As this is a bug fix that only enables wrongly suppressed behavior, no documentation needs to be altered.

fix: use Shiki's `isSpecialLang` to allow `ansi` codeblocks

---

.changeset/thin-impalas-cry.md
packages/astro/src/assets/vite-plugin-assets.ts
packages/integrations/vercel/test/serverless-prerender.test.js

Fixes https://github.com/withastro/adapters/issues/185, which is a bug around Lambda bundles containing unneeded `dist` files on Netlify. This bug presumably also exists on Vercel, as they use the same tracer under the hood (`@vercel/nft`).
Added a test to ensure this isn't introduced again to the Vercel integration test suite. I picked that test suite, since we know they also have their own image integration, and that it likely has the same bug as the Netlify adapter.
It's a bug fix, I don't see a need to change docs.

fix: ensure outDir doesn't lead to bundlers bloating Lambda size

---

.github/workflows/check.yml
packages/astro/astro-jsx.d.ts
packages/astro/types.d.ts

The type in https://github.com/withastro/astro/pull/10549 didn't allow enough stuff and the key was too wide. This fixes that
Tested manually + astro check should pass
N/A

fix(types): Fixes HTMLAttribute extend to allow everything

---

.changeset/wild-nails-call.md
packages/db/package.json
packages/db/test/basics.test.js
packages/db/test/fixtures/basics/src/pages/run.json.ts
pnpm-lock.yaml

Bump to latest Drizzle release to fix `db.run()` types.
Test `db.run()` output for the development and production database clients.

Fix `db.run()` type signature in production

---

.changeset/breezy-peaches-agree.md
packages/astro/components/Code.astro
packages/astro/components/Image.astro
packages/astro/components/Picture.astro
packages/astro/src/assets/internal.ts
packages/astro/src/assets/utils/imageKind.ts

Closes https://github.com/withastro/astro/issues/10560
Suggestive changes to typing that seems to silence the errors generated by the Astro VS Code plugin in a fresh project setup with the `/examples/framework-react` example as outlined in #10560 
Tested in project, type annotation changes only
N/A

Patch for Astro VS Code Plugin type errors

---

.changeset/sixty-eels-camp.md
.eslintrc.cjs
packages/db/src/core/errors.ts
packages/db/src/runtime/errors.ts
packages/db/src/runtime/queries.ts
packages/db/src/runtime/seed-local.ts

- Importing things in `src/core` from `src/runtime` will cause production to include rollup, vite and other unwanted things.
- This eslint rule will error if you do this. 
- Verified locally
N/A, bug fix

Prevent importing db core from db runtime

---

packages/astro/src/core/request.ts
packages/astro/test/static-build.test.js

- Clarify when headers are not available.
- Updated the assertion that checked for the warning.
- Does not affect behavior. Although feedback from docs team would be nice.

qol(runtime): clarify message about unavailable headers

---

.changeset/neat-stingrays-judge.md
packages/db/src/core/integration/index.ts
packages/db/src/core/integration/vite-plugin-db.ts
packages/db/test/basics.test.js
packages/db/test/fixtures/local-prod/astro.config.ts
packages/db/test/fixtures/local-prod/db/config.ts
packages/db/test/fixtures/local-prod/db/seed.ts
packages/db/test/fixtures/local-prod/package.json
packages/db/test/fixtures/local-prod/src/pages/index.astro
packages/db/test/local-prod.test.js
pnpm-lock.yaml

- Expect a `DATABASE_FILE` during the build, which points to the production database, or error and explain that they probably wanted `--remote`.
- Note that this restriction does not apply to static mode.
- New tests added, testing both cases.
N/A, bug fix

Provide guidance when --remote is omitted

---

.changeset/ninety-islands-deny.md
packages/db/src/core/cli/migration-queries.ts
packages/db/test/unit/reset-queries.test.js

- `--force-reset` should restore the database to the current schema, but it adds a DROP TABLE for all tables in the new schema. Since those might not exist, this should be conditional.
- Updated existing tests
N/A, bug fix

For --force-reset use conditional drop table query

---

.changeset/wise-ears-flash.md
packages/astro/src/core/routing/astro-designed-error-pages.ts
packages/astro/src/core/routing/manifest/create.ts
packages/astro/src/core/routing/priority.ts
packages/astro/src/prerender/routing.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/custom-404-loop-case-5/astro.config.mjs
packages/astro/test/fixtures/custom-404-loop-case-5/package.json
packages/astro/test/fixtures/custom-404-loop-case-5/src/pages/[x].astro
pnpm-lock.yaml

- #10581
- Fixes infinite loop when an astro page with a dynamic or spread path returned a 404 response.
- The problem was that the default error page appeared lower in the `manifest.routes` array, leading to the dynamic normal page - which also matched the `/404` path - always being matched as the reroute destination.
- The solution is to sort the routes whose regex matched, using the normal sorting rules used in prod.
- Added fixture.
- Does not affect behavior

fix(dev): consider pages' route priority when matching request to a page

---

.changeset/tricky-cobras-mate.md
packages/astro/src/content/index.ts
packages/astro/src/content/utils.ts
packages/astro/src/core/build/plugins/plugin-css.ts
packages/astro/test/experimental-content-collections-css-inline-stylesheets.test.js

- Can't walk up the parent tree in propagation flag modules with CCC because `astro:content` is marked as external. So walk parents of that instead.
- Unskipped most of the inline stylesheet tests, one remains.
N/A, bug fix

Fix inline stylesheets in content collection cache

---

.changeset/blue-ghosts-rule.md
packages/db/src/core/cli/migration-queries.ts
packages/db/src/core/schemas.ts
packages/db/src/core/types.ts
packages/db/src/core/utils.ts
packages/db/test/unit/index-queries.test.js

This introduces generated index names when passing an array to `indexes`. The object configuration syntax is now deprecated. [See changelog](https://github.com/withastro/astro/pull/10589/files#diff-64f66d18b0d560e74e3df56636df8a3dd2c564e9bc453080615f2208d5a50732)
- Update `dbConfig` with a transformation step to generate index names by table and column names
- Introduce a `ResolvedDbConfig` type for migration queries
- Misc: add a `mapObject` utility to remap object values with type safety
Add tests for new array format, and move old tests to "legacy"
https://github.com/withastro/docs/pull/7639

db: Rework index config with generated index names

---

.changeset/angry-lamps-cheer.md
packages/integrations/vercel/src/lib/redirects.ts
packages/integrations/vercel/test/fixtures/isr/astro.config.mjs
packages/integrations/vercel/test/fixtures/isr/src/pages/excluded/[dynamic].astro
packages/integrations/vercel/test/isr.test.js

Adds support for dynamic route segments in the isr.exclude array. See #10492
Manually tested: the implementation transforms the route segments similar to how redirects are transformed.
N/A

feat: allow dynamic route segments in isr.exclude array

---

.changeset/forty-turkeys-tap.md
packages/astro/src/runtime/server/jsx.ts

resolves #10575
- jsx runtime no longer errors on non-`.astro` jsx function component instances represented as vnode objects with nullish prop values
- only try property access on non-nullish prop values when checking if a prop is a slot
tested locally (ran dev server for `@examples/with-mdx` and added reproduction sample from linked issue)
not sure where a test file would best go or how to construct it, since particular reproduction from linked issue uses mdx, but don't think mdx is actually necessary, merely an environment where the issue could naturally occur.
not needed, internal bugfix

fix: dont error on nullish prop values in jsx runtime

---

.changeset/eighty-olives-destroy.md
packages/astro/src/transitions/router.ts

We change the history title while we push / replace the history during view transition.
It got changes back at the end of the function which turned out to be too late when using text fragments (`#:~:text=...`) as Chrome pushes another state.
**Edit:** ~~n./a.~~ Tested manually.
bug fix n./a.

reset history title after push/replace but prior to assignment to location

---

.changeset/gold-lies-behave.md
packages/integrations/vue/src/index.ts

Solves https://github.com/withastro/adapters/issues/207
Tested the CF Pages deploy and it works now.

Remove the ssr external for vue

---

examples/starlog/src/components/BaseHead.astro
examples/starlog/src/layouts/IndexLayout.astro

The `<meta charset="utf-8" />` and `</head>` tags are not in the correct place, so the `<head>` tag is not output at build time.
So I changed it to the correct place.
Checked the output of the build.
N/A

fix(starlog): Correct layout syntax.

---

.changeset/proud-books-hope.md
packages/integrations/preact/src/index.ts

- Swaps out the config to disable `preact/compat` aliases now that `@preact/preset-vite` supports this natively (https://github.com/preactjs/preset-vite/pull/79)
- Disables incorrect `react/jsx-runtime` -> `preact/jsx-runtime` alias. `@preact/preset-vite` already covers this (correctly) and so it did not need a replacement here.
No functional changes, beyond fixing a theoretical edge case with the `jsx-runtime` alias. I don't think it's worth adding a test here, this is pretty unlikely behavior to run across and is addressed by `@preact/preset-vite` already.
N/A, not user facing.
Some of the other config bits looks to be something we can upstream, so I'll take a look soon-ish and see if we can't reduce the config here further.

refactor: Drop Preact compat hack, remove incorrect alias

---

packages/astro/src/runtime/server/render/any.ts
packages/astro/src/runtime/server/render/util.ts

Quite a lot of garbage collection happens when rendering due to the fact we create anonymous functions when buffering writes (the `catch`, the destination/write function, etc).
By extracting this logic into a class, we can instead rely on prototype methods which exist once in memory.
Existing tests should cover this.
Manual testing has happened via the benchmark script to see if any benefit was gained.
Before:
| Page   | Avg (ms) | Stdev (ms) | Max (ms) |
| :----- | -------: | ---------: | -------: |
| /astro |   203.76 |      38.25 |   315.99 |
| /md    |     2.73 |       1.99 |    22.16 |
| /mdx   |   118.25 |      17.55 |   220.04 |
After:
| Page   | Avg (ms) | Stdev (ms) | Max (ms) |
| :----- | -------: | ---------: | -------: |
| /astro |   133.88 |      25.51 |   313.56 |
| /md    | …

feat: rework child rendering to use class

---

.changeset/tough-years-fry.md
packages/db/src/core/integration/vite-plugin-db.ts
packages/db/src/runtime/index.ts
packages/db/test/local-prod.test.js

- Moves logic for the environment variable into a helper function. Normalizes a file path, relative file path, and file URL, back into a file URL.
- Added new tests
- https://github.com/withastro/docs/pull/7723

Make ASTRO_DATABASE_FILE work with file paths

---

.changeset/tidy-dancers-itch.md
packages/db/src/core/cli/commands/execute/index.ts

- Was logging the function and not calling it, oops!
N/A bug fix

Give proper error when seed missing default export

---

.changeset/plenty-lobsters-design.md
packages/db/src/core/integration/index.ts
packages/db/src/runtime/db-client.ts
packages/db/src/runtime/errors.ts
packages/db/src/runtime/seed-local.ts
packages/db/src/utils.ts
packages/db/test/fixtures/basics/db/seed.ts

Introduce well-formatted errors for remote db client exceptions.
- Add `AstroDbError` class to set "Astro DB Error" as the error name instead of `AstroUserError`.
- Format an error message using the expected error "code" and "details" from Studio.
- Special case "no such table" issues to show a hint to push the latest schema changes.
- Misc: fix "unhandled promise rejection" getting logged for eager seeding by adding a `.catch()` with manual logging.
Suspected "missing db push" errors:
General SQLite errors:

db: Better error messages when querying remote

---

.changeset/calm-spiders-listen.md
packages/integrations/svelte/client-v5.js
packages/integrations/svelte/package.json
packages/integrations/svelte/server-v5.js

- Updates import statements for Svelte v5
- Bumps peer dependency `svelte` to `5.0.0-next.90`
- Closes #10637
- Manually tested with [astro/examples/framework-svelte](https://astro.new/framework-svelte?on=github)
- N/A

fix(svelte): update import statements and bump peer dependency for v5

---

.changeset/dull-news-grab.md
packages/db/src/core/integration/index.ts
packages/db/src/runtime/db-client.ts
packages/db/src/runtime/seed-local.ts
packages/db/src/runtime/utils.ts
packages/db/src/utils.ts

fix(db): isolate AstroDbError from core utils

---

.changeset/light-bikes-study.md
packages/astro/src/cli/add/index.ts

- Removes "Use at your own risk!" when using `astro add` with a 3rd party integration. It does not remove any check
N/A
N/A

feat: make 3rd party integration warning less scary

---

packages/integrations/vercel/test/serverless-prerender.test.js

- Removes a (really long) console.log from a test
- [sample](https://github.com/withastro/astro/actions/runs/8527589611/job/23359440318?pr=10652#step:8:5368) (over a thousand lines)
- originally added in https://github.com/withastro/astro/pull/10550
- Does not affect behavior
- Does not affect usage

chore: remove console.log from test

---

.changeset/tall-apples-turn.md
packages/integrations/react/src/index.ts

- Closes https://github.com/withastro/astro/issues/10644
- Fairly popular library with 42k weekly downloads: https://www.npmjs.com/package/@material-tailwind/react
- Easily automatically fixed by adding it as a built-in noExternal fixes it
Manually
N/A, bug fix

Mark @material-tailwind/react as noExternal

---

.changeset/serious-elephants-push.md
packages/db/src/core/cli/commands/execute/index.ts
packages/db/src/core/integration/index.ts
packages/db/src/core/integration/vite-plugin-db.ts
packages/db/test/fixtures/static-remote/astro.config.ts
packages/db/test/fixtures/static-remote/db/config.ts
packages/db/test/fixtures/static-remote/db/seed.ts
packages/db/test/fixtures/static-remote/package.json
packages/db/test/fixtures/static-remote/src/pages/index.astro
packages/db/test/static-remote.test.js
packages/db/test/test-utils.js
pnpm-lock.yaml

- When building a site with `output: 'static'` (or hybrid), the temporary app token is needed to build pages.
- Pass through in this condition so this is used if the env doesn't exist (which won't most of the time).
- New test fixture added.
N/A, bug fix

Fix building static sites with Astro DB

---

.changeset/lovely-trees-wait.md
packages/astro/src/assets/types.ts

Moves format and quality options from `LocalImageProps` to `ImageSharedProps` so it doesn't cause a type error when used with remote images, these always should have been shared

Move format option from LocalImageProps to ImageSharedProps

---

.changeset/moody-spies-learn.md
packages/integrations/markdoc/package.json
packages/integrations/markdoc/src/content-entry-type.ts
packages/integrations/markdoc/test/fixtures/render-html/src/content/blog/_partial.mdoc
packages/integrations/markdoc/test/fixtures/render-html/src/content/blog/with-partial.mdoc
packages/integrations/markdoc/test/fixtures/render-partials/astro.config.mjs
packages/integrations/markdoc/test/fixtures/render-partials/markdoc.config.ts
packages/integrations/markdoc/test/fixtures/render-partials/package.json
packages/integrations/markdoc/test/fixtures/render-partials/src/content/blog/_partial.mdoc
packages/integrations/markdoc/test/fixtures/render-partials/src/content/blog/with-partials.mdoc
packages/integrations/markdoc/test/fixtures/render-partials/src/content/nested/_partial.mdoc
packages/integrations/markdoc/test/fixtures/render-partials/src/pages/index.astro
packages/integrations/markdoc/test/fixtures/render-with-components/astro.config.mjs
packages/integrations/markdoc/test/fixtures/render-with-components/markdoc.config.ts
packages/integrations/markdoc/test/fixtures/render-with-components/package.json
packages/integrations/markdoc/test/fixtures/render-with-components/src/components/Counter.tsx
packages/integrations/markdoc/test/fixtures/render-with-components/src/components/CounterWrapper.astro
packages/integrations/markdoc/test/fixtures/render-with-components/src/components/DeeplyNested.astro
packages/integrations/markdoc/test/fixtures/render-with-components/src/content/_nested.mdoc
packages/integrations/markdoc/test/fixtures/render-with-components/src/content/blog/_counter.mdoc
packages/integrations/markdoc/test/fixtures/render-with-components/src/content/blog/_example.mdoc
packages/integrations/markdoc/test/fixtures/render-with-components/src/content/blog/with-components.mdoc
packages/integrations/markdoc/test/fixtures/render-with-components/tsconfig.json
packages/integrations/markdoc/test/render-components.test.js
packages/integrations/markdoc/test/render-html.test.js
packages/integrations/markdoc/test/render-indented-components.test.js
packages/integrations/markdoc/test/render.test.js
pnpm-lock.yaml

Resolves #10418 
This adds automatic resolution for Markdoc partials by relative file path.
```md
{% partial file="./_diagram.mdoc" /%}
<figure>
<figcaption>Diagram embedded into <code>post.mdoc</cod>
</figure>
```
- **Crawl Markdoc AST to discover any `partial` tags.** When one is found, render the partial in-place and assign the node. Flattening lets us catch validation errors at buildtime and discover nested component tags for hoisted scripts.
- Ensure manually configured `partials` are still respected to make this a non-breaking feature
- Track file changes to related partials using `addWatchFile()`
- Update validator to ignore any "partial not found" errors.
Add tests to render components and HTML within a partial.
https://github.com/withastro/docs/pull/7743

feat: automatic Markdoc partial resolution

---

.changeset/neat-grapes-cry.md
packages/astro/src/cli/install-package.ts

Rarely, someone run a project in CI that doesn't have `astro check` or `typescript` (or now, `@astrojs/db`) and the CLI stall infinitely waiting for someone, out there, to press a button. This PR makes it so it fails instantly now in CI.
Tested manually by inverting the checks locally
N/A

fix(install-package): Automatically exit in CI instead of waiting for input

---

.changeset/loud-numbers-notice.md
packages/astro/src/transitions/router.ts

Closes #10249
On view transitions, Firefox does not generate popstate events on same-page navigation to hash fragments.
We already have a special handling for Firefox when it loses state on current site updates. Dispatching the popstate event can be seen as additional compensation here.
Manually tested.
N.a./bug fix

Generates missing popstate events for Firefox when navigating to hash targets on the same page

---

.changeset/tall-wombats-clap.md
packages/integrations/react/src/index.ts

- Expose Babel config for @astro/react, as it was expected to be a "very high priority" in [this proposal](https://github.com/withastro/roadmap/discussions/202).
It should not break the current tests.
It wasn't specifically mentioned before.

@astrojs/react - Expose Babel config.

---

.changeset/khaki-turkeys-sip.md
packages/db/src/core/cli/commands/link/index.ts

- When running `astro db link` we don't want to exit in the middle of a question, but instead do so when the workspace is needed.
Manual testing in example project
N/A, bug fix

Prevent errors in finding workspaceId from interrupting link prompts

---

.github/workflows/check-merge.yml

The action that was assigning the minor label stopped working, and I'm not sure why.
This PR attempts to:
- update the action to `v44`
- align out usage with [how the docs explain](https://github.com/tj-actions/changed-files?tab=readme-ov-file#using-local-git-directory-): using an environment variable 
Merge it and monitor it on another PR
N/A

ci: update check-merge.yml action

---

.changeset/olive-camels-greet.md
packages/astro/astro-jsx.d.ts

Addition of `disableremoteplayback` to the `VideoHTMLAttributes` interface for TypeScript support.
No code changes needed as it's already handled by the regex in `packages/astro/src/runtime/server/render/util.ts`
N/A - Type change only
N/A - Type change only

Add disableremoteplayback attribute to VideoHTMLAttributes interface

---

package.json

I'm pushing adding Astro to the citgm tests, so added this script that should be VERY SIMILAR to the original test script but avoid caching as it make no sense for citgm
Ref: https://github.com/nodejs/citgm/pull/1055
**Q:** Why not have a generic name for the test command?
**A:** I thought about doing `test:no-cache` but sometimes if we find that we only care about a subset of tests we wanna change the command

chore: add `test:citgm` command that would run tests without caching and `build:ci:no-cache` to skip caching for build as well

---

.changeset/plenty-bugs-hunt.md
packages/astro/src/core/build/plugins/plugin-prerender.ts

close https://github.com/withastro/astro/issues/10485 (This PR helps with the issue's repro, but fundamentally rendering >100k is not possible with Rollup)
This PR skips a prerender chunk edge case where if you put too many modules within a single chunk, Rollup has a hard time deconflicting the variable names. For example, all Markdown modules export `compiledContent`/`frontmatter`. Those exist as top-level variables in the prerender chunk, and Rollup has to deconflict the variables which proportionately gets slower when iterating over the variables.
The main bottleneck is [`getSafeName` in Rollup](https://github.com/rollup/rollup/blob/459bfe1b336814199b5c643e212390f6979de83d/src/utils/safeName.ts#L4-L16), which would be nice to fix directly, but I made this different fix within Astro for …

Skip prerender chunk in static output

---

.changeset/few-forks-taste.md
packages/integrations/vue/package.json
packages/integrations/vue/src/index.ts
pnpm-lock.yaml

Removes unused `jsxTransformOptions` and `jsxImportSource` options from the renderer config. Those two is no longer useful since https://github.com/withastro/astro/pull/7924 (Astro 3). The fields should be marked deprecated, but I'll do so in a separate PR along with other refactors.
There's an existing `vue-jsx` test that should still pass.

Remove unused config in Vue JSX integration

---

.changeset/four-pants-juggle.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/create-vite.ts
packages/astro/src/jsx/renderer.ts
packages/astro/src/jsx/transform-options.ts
packages/astro/src/vite-plugin-mdx/README.md
packages/astro/src/vite-plugin-mdx/index.ts
packages/astro/src/vite-plugin-mdx/tag.ts
packages/astro/src/vite-plugin-mdx/transform-jsx.ts
packages/astro/test/units/render/jsx.test.js

- Mark renderer `jsxImportSource` and `jsxTransformOptions` as deprecated as they're not used since Astro 3.0 (https://github.com/withastro/astro/pull/7924)
- Refactor `transformJSX` to use the `astro:jsx` transform options directly. This makes `transformJSX` less generic and make it easier to port it to `@astrojs/mdx` in the future.
- Altogether should improve the performance of transforming MDX files.
Before:
After:
Execution time of `transformJSX` dropped from 1.16s to 0.33s.
Added a changeset about `jsxImportSource` and `jsxTransformOptions` being deprecated, and in the jsdoc.

Refactor MDX transformJSX handling

---

packages/integrations/vue/src/index.ts

The tests wasn't running correctly in https://github.com/withastro/astro/pull/10687, this PR should fix the current CI fail. It looks like we had hardcoded `@astrojs/vue (jsx)` at https://github.com/withastro/astro/blob/799f6f3f29a3ef4f76347870a209ffa89651adfa/packages/astro/src/runtime/server/render/component.ts#L46 so we have to keep the name for now.
Ran the test locally.
n/a. no changeset as https://github.com/withastro/astro/pull/10687 it not published yet.

Fix vue-jsx change

---

.changeset/old-planes-walk.md
packages/db/src/core/cli/commands/push/index.ts
packages/db/src/core/cli/migration-queries.ts
packages/db/src/core/errors.ts

- Instructs on the steps required
- Fixes issue where we were telling them to add `deprecated: true` to the new table.
- Closes https://github.com/withastro/astro/issues/10510
N/A
- https://github.com/withastro/docs/pull/7655. Docs must be merged first

Provide better messaging when renaming a table

---

.changeset/swift-coats-teach.md
packages/astro/e2e/fixtures/dev-toolbar/src/pages/a11y-exceptions.astro
packages/astro/src/runtime/client/dev-toolbar/apps/audit/index.ts
packages/astro/src/runtime/client/dev-toolbar/apps/audit/rules/a11y.ts

This PR fixes the interaction check by bypassing `div` and `span` elements, which don't have a real interaction role.
I added a new test
N/A

fix(devtool): do not trigger interaction check for `div` and `span`

---

.changeset/large-knives-confess.md
packages/astro/src/runtime/server/render/util.ts
packages/astro/test/astro-attrs.test.js
packages/astro/test/fixtures/astro-attrs/src/pages/index.astro

Closes https://github.com/withastro/astro/issues/10726
Fixes a regression where some specific code could trigger some false positive. In particular, a string like the following is a valid URL:
```js
new URL("cmd: echo \"foo\" && echo \"bar\" > /tmp/hello.txt")
```
```
URL {
href: 'cmd: echo "foo" && echo "bar" > /tmp/hello.txt',
origin: 'null',
protocol: 'cmd:',
username: '',
password: '',
host: '',
hostname: '',
port: '',
pathname: ' echo "foo" && echo "bar" > /tmp/hello.txt',
search: '',
searchParams: URLSearchParams {},
hash: ''
}
```
I made the check a bit stricter by strictly checking the protocol to be `http:` or `https:`. 
N/A

fix: regression for astro attributes escaping

---

.changeset/spotty-hounds-ring.md
packages/db/src/core/integration/vite-plugin-db.ts
packages/db/test/db-in-src.test.js
packages/db/test/fixtures/db-in-src/astro.config.ts
packages/db/test/fixtures/db-in-src/db/config.ts
packages/db/test/fixtures/db-in-src/db/seed.ts
packages/db/test/fixtures/db-in-src/package.json
packages/db/test/fixtures/db-in-src/pages/index.astro
pnpm-lock.yaml

- When checking if the import for `astro:db` comes within `src/`, also check that it's not within `db/`, as it's possible for db to be inside src (when src is configured to root).
- Fixes https://github.com/withastro/astro/issues/10712
Bug fix

Fix db seeding when srcDir is root

---

.github/workflows/check-merge.yml

Adds the `ref`, which should allow to checkout the actual branch and not the `HEAD` of the repository
Merge and check it on other PRs
N/A

ci: add ref when checking out the repository

---

.changeset/sharp-elephants-clap.md
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/custom-404-implicit-rerouting.test.js
packages/astro/test/fixtures/custom-404-loop-case-5/src/pages/index.astro

- Fixes in dev #10735 
- Unskipped tests for implicit rerouting, added prod tests.

fix(dev): break implicit rerouting loop

---

.changeset/short-flies-itch.md
packages/astro/src/core/errors/overlay.ts

Close https://github.com/withastro/astro/issues/10715
- Save `localStorage.astroErrorOverlayTheme` when detected system dark mode
- Update `isDark`
```ts
const isDark = localStorage.astroErrorOverlayTheme === 'dark' || this?.classList.contains('astro-dark');
```
null
null

fix: Fixed errorOverlay theme toggle bug.

---

.changeset/fair-jars-behave.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/app/index.ts
packages/astro/src/core/app/middlewares.ts
packages/astro/src/core/app/types.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts
packages/astro/test/csrf-protection.test.js
packages/astro/test/fixtures/csrf-check-origin/astro.config.mjs
packages/astro/test/fixtures/csrf-check-origin/package.json
packages/astro/test/fixtures/csrf-check-origin/src/pages/api.ts
pnpm-lock.yaml

This PR adds the **origin header check** for the CSRF protection.
Closes PLT-1872
Here's the RFC for more details: https://github.com/withastro/roadmap/pull/879
This is a feature that is supposed to work only for on-demand pages. It should not work during the build. To enable the feature, I **had** considered some generic way to change the `internalMiddleware` that is present in the `BasePipeline` class, but after having a chat with @lilnasy, we decided that it felt a bit premature and decided to go for a more custom way.
The `manifest` inside the pipeline contains the middleware, and if the feature is enabled, the `App` class (the one that all adapters use) will modify the middleware to add the origin check middleware function.
The logic of the origin check is heavily inspired from …

feat: add origin check for CSRF protection

---

.changeset/shaggy-cats-film.md
packages/astro/src/core/cookies/cookies.ts
packages/astro/test/units/cookies/delete.test.js

Allows cookie attributes to be specified when deleting a cookie. The attributes were limited to `domain` and `path`.
See #10480 for context.
Closes #10480
The changes are validated by unit tests.
The [Astro.Cookie.delete API reference](https://docs.astro.build/en/reference/api-reference/#delete) must be updated, since following statement will no longer be true:
>Options allow setting the domain and path of the cookie to delete.

Accept common cookie attributes when deleting a cookie

---

packages/astro/src/@types/astro.ts

Updates the config reference for docs for i18n
no tests, just docs
- adds the necessary`h4` tag to the new `routing.manual` entry
- improves some existing descriptions for other i18n by adding code examples (did not uniformly have these)
STILL TO FIX:
- currently, `manual` shows up BEFORE the other config options. This should appear last, as the "least common/most manual" option. I did not want to play around with the syntax to get the `|` just right by reversing the object and the manual entry.

fix some i18n config docs

---

.changeset/few-mails-kiss.md
packages/astro/src/runtime/client/dev-toolbar/apps/audit/rules/a11y.ts

Make `a11y-no-noninteractive-tabindex` rule not apply to the roleless elements list that was added in https://github.com/withastro/astro/pull/10719 
Need to add `tabindex` for https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/

Update a11y-no-noninteractive-tabindex rule for dev tool bar

---

.changeset/late-spoons-knock.md
packages/astro/src/core/errors/dev/utils.ts

- Fixes #10741 
- Minor change. Existing tests should pass.

fix(cli): call path.replace only if it is a function

---

.changeset/old-pugs-jog.md
packages/astro/src/i18n/index.ts
packages/astro/src/i18n/middleware.ts
packages/astro/test/i18n-routing.test.js

Closes https://github.com/withastro/astro/issues/10724
Closes PLT-1955
There was a small issue when there's so `base` provided
I added a test case, and tested manually using the reproduction provided
N/A

fix(i18n): fallback SSR

---

packages/astro/src/@types/astro.ts

Live docs are fine, but source wasn't updated to fix this line with moved links.
only docs fix -- to correct a change made in docs itself that didn't make its way here.

[docs] config reference link fix

---

.changeset/four-zoos-taste.md
packages/astro/src/content/runtime.ts

This is like https://github.com/withastro/astro/pull/7125 but for another place accessing many files at once: `getCollection`. This might address some of https://github.com/withastro/astro/issues/7241 -- some of the errors don't look like they're from `getCollection` but I got `EMFILE` and this fixed my own project.
I modified the distributed `runtime.ts` (well, `runtime.js` cause it's in `dist`) in my `node_modules` install of `astro` and my project stopped erroring. Then I did those same edits to the file here.
I don't think this needs to be documented as it is a bugfix. Should I include a changelog? I did not for now.

Limit imports in flight for `getCollection`

---

.changeset/grumpy-moose-pretend.md
packages/db/package.json

- Adds repo, homepage, and issues links to the DB package.json
- These are surfaced on npm but also in places like editor tooltips
- Adds a `description` field to package.json too. Currently this is an empty string causing the first link of the README to be used in places, e.g.
npm:  
VS Code:  
n/a — copied the format used in other integrations
n/a

Add useful links to `@astrojs/db` package.json

---

packages/astro/src/core/render-context.ts

- I ran a cpu profile and noticed the createAstro function was taking up a lot of time. For some reason the object spreading is very slow.
- this change improves the server stress latency when running `pnpm run benchmark` by about 25%
|         |        Avg |     Stdev |     Max |
| :------ | ---------: | --------: | ------: |
| Latency | 2401.63 ms | 529.43 ms | 5495 ms |
|           |     Avg |   Stdev |     Min |   Total in 30s |
| :-------- | ------: | ------: | ------: | -------------: |
| Req/Sec   |   400.8 |  171.83 |     300 | 12.0k requests |
| Bytes/Sec | 70.6 MB | 30.2 MB | 52.8 MB |   2.12 GB read |
|         |       Avg |     Stdev |     Max |
| :------ | --------: | --------: | ------: |
| Latency | 1908.7 ms | 383.24 ms | 3237 ms |
|           |     Avg |   Stdev |     Min …

Performance improvement in createAstro function

---

packages/astro/src/core/errors/errors-data.ts

Fix typo in error message for IncorrectStrategyForI18n
https://docs.astro.build/en/reference/errors/incorrect-strategy-for-i18n/

Fix typo in error message for IncorrectStrategyForI18n

---

.changeset/nine-radios-peel.md
packages/integrations/vercel/src/image/build-service.ts
packages/integrations/vercel/src/image/shared-dev-service.ts

We were wrongfully not including the hooks for srcset generation in the Vercel service. This fixes that. I'll note that it's still a little bit wonky on the user side, because they need to make sure that the dimensions they're outputting are part of their Vercel config, but that's normal for Vercel.
Fixes https://github.com/withastro/astro/issues/10623
Tested manually by deploying to Vercel.
N/A

fix(vercel): Fix srcset generation not working on Vercel

---

.changeset/mean-candles-hammer.md
packages/astro/src/cli/add/index.ts
packages/astro/src/core/config/tsconfig.ts
packages/astro/test/fixtures/tsconfig-handling/baseUrl/tsconfig.json
packages/astro/test/units/config/config-tsconfig.test.js

`tsconfck` apply some transformation to the parsed `tsconfig.json`, but we need the raw config to modify it for `astro add`. This changes how we get the raw config`
Added a test
N/A

fix(add): Fixes astro add modifying baseUrl by accident

---

.changeset/orange-ladybugs-nail.md
benchmark/make-project/memory-default.js
packages/astro/src/vite-plugin-markdown/index.ts
packages/integrations/mdx/src/index.ts
packages/markdown/remark/src/highlight.ts

Similar to [`ec02b09`](https://github.com/withastro/astro/pull/10618/commits/ec02b09c0c4b8a6237ec8aa5f40ff8ba4501db0e) (https://github.com/withastro/astro/pull/10618) but for `@astrojs/mdx`.
I also updated `vite-plugin-markdown` to provide a better error in case something odd happens.
I updated the benchmark to include MDX files, but unfortunately I couldn't observe a significant difference. Likely because we're freeing up memory in the middle of a Rollup build, but the benchmark records only after the entire build ends.
Theoretically this PR should still be useful though 😅 

Remove MDX processor on buildEnd

---

.changeset/modern-mugs-raise.md
packages/astro/components/Picture.astro

Fixes match condition for specialFormatsFallback formats.
Tested locally.
[Current docs](https://docs.astro.build/en/guides/images/#fallbackformat) matches with the fix.

fix: picture fallback check

---

.changeset/stupid-countries-warn.md
packages/astro/src/transitions/router.ts

Ensures that the `finished` promise of view transition simulation not only waits for animations triggered by the data-astro-transition-fallback attribute, but also waits for JavaScript animations triggered by the viewTransition.ready promise.
n.a./bug fix

Make viewTransition.finished wait for animations triggered by viewTransition.ready

---

.changeset/rich-spoons-fold.md
packages/astro/src/assets/endpoint/generic.ts

This is similar to something we do in our edge middleware thingy where we forward the headers from the original request to the self-request (is that a thing) so that it works properly when the website is protected. For instance, this fixes image requests in preview website on Vercel that have their preview behind a auth.
Fixes https://github.com/withastro/astro/issues/10752
N/A

fix(assets): Forward headers from the original request to the internal request to the image

---

.changeset/many-hairs-jump.md
packages/astro/src/cli/install-package.ts

- If `whichPm` is unable to determine the package manager it will return `null`, not `{ name: null }`.
- This patch allows the null coalescing already added to work.
before
```
❯ npx astro init
Need to install the following packages:
astro@4.6.1
Ok to proceed? (y) y
To continue, Astro requires the following dependency to be installed: @astrojs/db.
Cannot read properties of null (reading 'name')
Stack trace:
at installPackage (file:///Users/meghandenny/.npm/_npx/aa98e6899c6baff3/node_modules/astro/dist/cli/install-package.js:79:47)
at async db (file:///Users/meghandenny/.npm/_npx/aa98e6899c6baff3/node_modules/astro/dist/cli/db/index.js:9:21)
at async cli (file:///Users/meghandenny/.npm/_npx/aa98e6899c6baff3/node_modules/astro/dist/cli/index.js:169:5)
```
after change made locally
```
❯ npx …
```

astro/cli/install-package.ts: whichPm may return null if ran in an empty directory

---

.changeset/eight-hotels-try.md
packages/astro/src/core/build/pipeline.ts
packages/astro/src/runtime/server/render/astro/render.ts
packages/astro/test/content-collections-render.test.js

Since we need the entire string before we can write to a file anyway, we don't need streaming. Streaming keeps the state in an array buffer, while non-streaming keeps it as a string. The latter is more performant as most of the input is already a string, preventing transformations.
Credits go to @delucis for the initial idea & benchmark. And @ematipico for the initial PR (https://github.com/withastro/astro/pull/9603)
---
Locally building the docs repo, the render time went from 56s to 44.3s.
I marked this as a patch because I wanted to get this out, but if anyone feels being more cautious, happy to mark this as a minor too 😄 

Disable streaming for SSG

---

.changeset/few-pets-relax.md
packages/db/src/runtime/virtual.ts
packages/db/virtual.d.ts

For convenience, expose drizzle's `alias` in `astro:db` exports. This slightly narrows the set of situations where devs need to add drizzle itself.
This `alias` helper is needed when you are joining on the same table multiple times, or joining a table on itself. For example, I have a sports-themed app where a `Game` can have a `HomeTeam` and an `AwayTeam` (which both reference a `Team` entity).
I ran `pnpm build` locally and verified `dist/_internal/runtime/virtual.d.ts` includes the new export.
It could be worth adding this to the "Drizzle utilities" section of the astrodb docs, but might be unnecessary. Let me know if you want me to add it (as a fourth bullet point, after "the sql helper...")

db: export 'alias' from drizzle-orm/sqlite-core

---

.changeset/itchy-donuts-destroy.md
packages/astro/e2e/fixtures/view-transitions/src/pages/persist-1.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/persist-2.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/transitions/router.ts

TIL: setting selectionStart on an HTMLInputElement throws an error on types other than text, search, URL, tel, and password. 
Luckily, in all other cases reading the property yields null. 
And we only restore focus if the activeElement did not change.
To prevent the errors in the console it is sufficient to just not assign if we have no numbers.
Added test for a checkbox input.
Also added explicit test for the selectionStart and selectionEnd on a text input field as an extension to the existing focus test.
n.a. / bug fix

Fixes an issue with persisted non-text input fields that have the focus during view transition navigation.

---

biome.json
packages/astro/test/fixtures/css-order-layout/src/layouts/Main.astro

This PR fixes a regression happened in here:   https://github.com/withastro/astro/actions/runs/8719929820/job/23920426920
Biome flipped a couple of imports and the test failed, because the order of imports matters in this case.
I moved some ignored files inside `files.ignore`
The CI should pass now. I also verified locally that `format:imports` doesn't flip the imports anymore
N/A

test: fix regression upon import sorting

---

.changeset/late-bags-marry.md
packages/integrations/sitemap/package.json
packages/integrations/sitemap/src/index.ts
packages/integrations/sitemap/src/write-sitemap.ts
packages/integrations/sitemap/test/fixtures/trailing-slash/src/pages/index.astro
packages/integrations/sitemap/test/trailing-slash.test.js
pnpm-lock.yaml

- fixes #10751 
- added dependency to [stream-replace-string](https://github.com/ChocolateLoverRaj/stream-replace-string) to implement the workaround described in the issue
- added additional test cases in `test/trailing-slash.test.js` that fail without the workaround
- after the fix all test cases are passing
no changes needed in my opinion

fix(sitemap): Trailing slashes on root url

---

examples/blog/src/pages/index.astro

In blog starter template, currently the 4th point on the home page says: "Check out the included blog posts in src/pages/blog/". The path here should be "src/content/blog/".
No test added as its only a text change.
No doc changes or addition required as its only a text change.

fixed the path to checkout existing blog posts on the home page of the blog starter template

---

.changeset/weak-swans-sparkle.md
packages/astro/src/transitions/router.ts

This is edge-case-land of Astro's view transition simulation when you do not use CSS only but also want to combine it with JavaScript animations.
While #10787 worked fine for Firefox on desktops, it introduced a regression on mobile WebKit browsers. 
https://github.com/withastro/astro/assets/94928215/afc58325-3fde-48a7-9581-5f53f625924f
The blinking screen in the middle of the animation is a result of un-animated rendering before the animation kicks in. Reverting #10787 fixes this.
As an afterthought, it would have been better to switch micro tasks instead of yielding to the tasks queue. But after consulting the spec again (https://drafts.csswg.org/css-view-transitions-1/), I'm not sure whether this goes into the right direction. In browsers with native view transition support …

revert handling of JavaScript animations during view transitions

---

packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/pipeline.ts
packages/astro/src/core/render-context.ts
packages/astro/src/vite-plugin-astro-server/pipeline.ts
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/fixtures/reroute/src/pages/dynamic/[id].astro
packages/astro/test/fixtures/reroute/src/pages/spread/[...id].astro
packages/astro/test/i18n-routing-manual.test.js
packages/astro/test/reroute.test.js

This PR implements rerouting for SSG!
In order to enable the feature, I had to move the logic that imports the component instance of the page inside the `pipeline` object. The logic is unchanged, only moved inside the `BuildPipeline` class.
After that, I just implemented the functions `getComponentInstance` and `tryReroute` in the `BuildPipeline` class.
Added new test cases
N/A

feat: reroute in SSG

---

.changeset/spotty-dots-beg.md
packages/db/src/core/cli/commands/login/index.ts

Add a check to `astro login` for your environment. When in Codespaces or Stackblitz, use a manual login flow that lets you enter your session ID rather than using redirects.
Related Studio PR: https://github.com/withastro/studio/pull/589
https://github.com/withastro/astro/assets/51384119/5bd68a79-de14-49d4-8a8f-c865f96888f3
Manual testing for the preview package on Stackblitz and Codespaces, connecting to a local Studio instance with a tunnel.

db: add login flow for web containers

---

packages/astro/src/runtime/server/astro-island.ts

- What does this change? Improve readability by unnesting the `<astro-island>` class, adding space between methods.
Hide whitespace to see the change easily.
N/A
N/A

unnest astro-island class

---

packages/astro/e2e/fixtures/view-transitions/src/pages/404.astro
packages/astro/test/fixtures/astro-basic/src/pages/fileurl.astro
packages/astro/test/fixtures/core-image-deletion/src/pages/index.astro

I parsed every `.astro` file in the Astro repository (to check if [tree-sitter-astro](https://github.com/virchau13/tree-sitter-astro) had any bugs), and found three files with syntax errors that don't seem intentional.
Fixes those syntax errors.
Executed `pnpm run test` at top-level and all 17 tasks passed.
It's a simple syntax error fix, so no docs are required.

fix: resolve syntax errors in fixtures

---

.changeset/sweet-coins-shop.md
packages/astro/src/assets/utils/emitAsset.ts
packages/astro/src/assets/vite-plugin-assets.ts
packages/astro/src/config/index.ts
packages/astro/src/content/runtime-assets.ts
packages/astro/src/content/utils.ts
packages/astro/src/content/vite-plugin-content-imports.ts

- Threads through Vite's `mode` which is mutated by vitest.
- Fixes https://github.com/withastro/astro/issues/10822
- https://stackblitz.com/edit/astro-vitest-image-content-collections-atavo4?file=src%2Futils%2Fcollections.test.ts,vitest.config.ts `npm run test`
N/A, bug fix

Prevent getCollection from breaking in vitest

---

packages/integrations/mdx/src/index.ts
packages/integrations/mdx/src/vite-plugin-mdx.ts

This PR simply moves the Vite plugin `@mdxjs/rollup` to its own file - `vite-plugin-mdx.ts`. No other changes are made otherwise.
This should help prepare future changes I'd like to make easier to review and diffed.
n/a.

Move MDX Vite plugin to new file

---

.changeset/curvy-humans-judge.md
packages/astro/src/core/build/static-build.ts

- Fixes an issue where `astro build` writes type declaration files to `outDir` when it's outside of root directory
- Closes #10610
- Manually tested with the [minimal reproduction repo](https://github.com/m-radzikowski/astro-issue-10610)
- N/A

Fix an issue where `astro build` writes type declaration files to `outDir`

---

.changeset/chilly-items-help.md
.changeset/tame-avocados-relax.md
packages/astro/src/jsx/server.ts
packages/integrations/mdx/src/vite-plugin-mdx-postprocess.ts

> Merges into the `mdx-v3` branch. Technically this is non-breaking, but it's easier to merge here to prevent new releases for `@astrojs/mdx`.
This PR does two things:
1. Inject `__astro_tag_component__(Content, 'astro:jsx')` so that we can render MDX components faster. No need to call `check()` to test if it's `astro:jsx` as we already tagged it.
2. Add enhanced error handling for `astro:jsx` `renderToStaticMarkup()`. Because of the above, `check()` wasn't enhancing the error anymore, which failed [a test](https://github.com/withastro/astro/blob/f513ba602c9d9bc2f1984bf994381d30cdea6a0d/packages/integrations/mdx/test/invalid-mdx-component.test.js#L31-L37).
Performance:
I tested this in the docs repo but there isn't any significant improvements nor regressions, so this would be harmless. …

Tag MDX component for faster checks when rendering

---

.changeset/thirty-poems-chew.md
packages/astro/tsconfigs/strictest.json

Resolves #10507
This allows typechecking for JS files when using the `strictest` TS config. This is consistent with our other TS configs, and fixes virtual module types provided by integrations like Astro DB (https://github.com/withastro/astro/issues/10507)

Enable `allowJs` for `strictest.json`

---

.changeset/fresh-masks-agree.md
.changeset/friendly-plants-leave.md
packages/astro/package.json
packages/astro/src/jsx/babel.ts
packages/astro/src/jsx/rehype.ts
packages/astro/src/jsx/transform-options.ts
packages/astro/src/vite-plugin-mdx/index.ts
packages/astro/src/vite-plugin-mdx/tag.ts
packages/astro/src/vite-plugin-mdx/transform-jsx.ts
packages/astro/test/units/dev/collections-renderentry.test.js
packages/integrations/mdx/src/plugins.ts
packages/integrations/mdx/src/vite-plugin-mdx-postprocess.ts
packages/integrations/mdx/src/vite-plugin-mdx.ts
pnpm-lock.yaml

- Port `jsx/babel.ts` to `jsx/rehype.ts`. The file logic are essentially the same thing but written as a rehype plugin.
- The builtin `vite-plugin-mdx` plugin is deleted by `@astrojs/mdx`, the integration will takeover MDX transformation instead, using the rehype plugin.
Performance:
Rollup build time of Astro docs dropped from **108s to 96s (12s or 11% faster)**
How this perf improvement works is by removing the hoops needed to compile MDX as JS:
- Before: MDX string -> mdast -> hast -> esast -> JSX string -> esbuild -> babel ast -> JS string
- After: MDX string -> mdast -> hast -> esast -> JS string
Existing tests should pass, we have extensive coverage for MDX usecases and edgecases.
This is a breaking change. I've added a changeset explaning the change, but the only change needed is …

Use unified plugin only for MDX transform

---

.changeset/young-chicken-exercise.md
packages/integrations/mdx/src/rehype-optimize-static.ts

`rehype-optimize-static.ts` wasn't working as intended in some cases. For example, if you have:
```mdx
<Card foo="bar">
This is content
</Card>
```
Previously it compiles to:
```jsx
<Card foo="bar">
<_components.p set:html="This is content" />
</Card>
```
But what it should be is 
```jsx
<Card foo="bar" set:html="<p>This is content</p>" />
```
This PR fixes it by adding `if (key != null && key !== 'children') return SKIP` because we accidentally visited `foo="bar"` (part of `node.attributes`), which de-optimizes the flow. The `key` check helps avoid the `attributes` key.
---
I also made a second change to add `mdxJsxTextElement` as a proper MDX node. It is kinda synonymous to `mdxJsxFlowElement`, but I forgot to add both of them.
Sorry, I don't have tests for `rehype-optimize-static` 😅 …

Only traverse children and handle mdxJsxTextElement when optimizing

---

.changeset/small-oranges-report.md
packages/integrations/mdx/src/rehype-optimize-static.ts
packages/integrations/mdx/test/fixtures/mdx-optimize/astro.config.mjs

@delucis suggested to rename the `optimize.customComponentNames` option to `optimize.ignoreComponentNames`, which I agree better reflect its usecase. Since this is an advanced option, I assume this shouldn't affect many projects and wouldn't be cumbersome to rename.
Existing tests should work
I added a changeset describing the breaking change. The docs for `@astrojs/mdx` should also be updated, but I'll send a single PR about all the breaking changes later to the docs repo.

Rename to `optimize.ignoreComponentNames` in MDX

---

.changeset/angry-lemons-tie.md
packages/db/src/runtime/index.ts
packages/db/src/utils.ts

- Improves the typing of the `asDrizzleTable()` utility
- Fixes a type error when passing the output of `defineTable()` to the utility and returns a more detailed type inferred from the columns of the passed table config.
Tested manually in an integration
n/a — bug fix

Improve `asDrizzleTable()` types

---

.changeset/afraid-mirrors-tease.md
packages/astro/src/vite-plugin-astro-server/vite.ts

Unblocks https://github.com/vitejs/vite/pull/16455
We were crawling into dependencies of CSS vite modules, which are usually not needed as these dependencies (especially CSS) are already inlined into the parent vite module.
In practice, this doesn't change the output as we coincidentally these dependencies don't have an `id`:
https://github.com/withastro/astro/blob/05d58eff075c904cdab85fe315ee4f5820060d00/packages/astro/src/vite-plugin-astro-server/vite.ts#L46-L47
So they were skipped. But https://github.com/vitejs/vite/pull/16455 will change things slightly that makes this not work, so this PR makes this skip more explicit.
Ran tests locally, and tested an example manually.

Skip crawling into CSS requests when crawling module graph

---

.changeset/slimy-cobras-end.md
packages/astro/test/units/dev/collections-renderentry.test.js
packages/integrations/mdx/src/index.ts
packages/integrations/mdx/src/vite-plugin-mdx.ts
packages/integrations/mdx/test/mdx-plugins.test.js

This PR moves the markdown options generation to the `astro:config:done` hook so that remark/rehype plugins added by integrations after `@astrojs/mdx` during `astro:config:setup` hook works.
This should unblock `astro-expressive-code` needing `@astrojs/mdx` in a specific order to work, which should remove the hack in https://github.com/withastro/docs/pull/7972
cc @hippotastic does this work for you?
cc @delucis 
---
NOTE: The implementation would be simpler if I added the Vite plugin in the `astro:config:done`, but other integrations also add Vite plugins in `astro:config:setup`. I figured it's more predictable if we also do so.
Added a new test.
I don't think this will affect many projects in practice, but I added a changeset explaining the migration path if so.

Allow remark/rehype plugins added after mdx to work

---

.changeset/curly-spoons-pull.md
packages/astro/e2e/fixtures/view-transitions/src/pages/abort.astro
packages/astro/e2e/fixtures/view-transitions/src/pages/abort2.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/src/transitions/events.ts
packages/astro/src/transitions/router.ts

Closes #10807
Detects when navigate() is called while another instance is still executing.
Uses an AbortController to abort running fetch operations and signal at various points in the implementation that the current navigation should be abandoned.
For simulation mode, adds the ability to prevent/cancel running animations of view transitions (for native view transitions this is automatic)
Made the handling of asynchronous parts in the existing implementation more robust for cases where something really goes wrong.
Two new e2e test that test for canceling of earlier requests and canceling of ongoing animations.
n.a. / Bug Fix

fix(astro): newer navigation aborts existing one

---

.changeset/twelve-bulldogs-raise.md
packages/integrations/react/server.js

ReactDOMServer.renderToStaticNodeStream() is deprecated. 
Use ReactDOMServer.renderToPipeableStream() and wait to `pipe` until the `onAllReady` callback has been called instead.
Tested manually in a project

fix a deprecated method in react integration using SSR: renderToStaticNodeStream

---

.changeset/happy-pumpkins-rescue.md
packages/db/package.json
packages/db/src/core/errors.ts
packages/db/src/core/tokens.ts
pnpm-lock.yaml

- Uses `ci-info` which seems to be the most popular library for detecting CI environments.
- Provide a message about add the ASTRO_STUDIO_APP_TOKEN, rather than the previous message which said to run `astro login`.
- None yet
N/A, bug fix

Provide a better error for when the app token is missing in CI

---

.changeset/olive-cars-run.md
packages/db/src/runtime/index.ts

`process.cwd()` doesn't have a trailing slash, so you can't do relative paths with it in an URL
N/A

Fixes ASTRO_DATABASE_FILE interaction with relative paths

---

.changeset/silent-zoos-work.md
packages/astro/src/runtime/client/dev-toolbar/helpers.ts

close #10930 
Tests should still pass.
N/A

change: NotificationPayload type

---

.changeset/blue-geese-visit.md
packages/integrations/mdx/src/rehype-optimize-static.ts
packages/integrations/mdx/test/units/rehype-optimize-static.test.js

Some MDX nodes are simply `<kbd>something</kbd>` which the optimizer bails out because it thinks that it's non-static. However, it works like a plain HTML element and should be static.
This PR tries to simplify these MDX nodes as normal hast `element` nodes so we can further optimize the strings.
Added a changeset

Simplify plain MDX nodes in optimize option

---

packages/db/src/core/integration/index.ts
packages/db/src/core/integration/vite-plugin-db.ts

Branched from db seeding refactor: https://github.com/withastro/astro/pull/10919
Adds back vite dev server loading for db seed files.
- Reuse existing dev server during development
- Create a temporary vite server during production builds. This mirrors how the Astro content collection config is loaded
- Prevent infinite seeding loops by tracking whether seeding is in-progress.
Ensure existing tests pass.
N/A

[db] Load seed files with vite dev server

---

.changeset/forty-wolves-turn.md
packages/astro/src/core/app/node.ts
packages/integrations/node/test/url.test.js

fixes #10916 
- Fix internal server error when bot `X-Forwarded-Host: hostname:8080` and `X-Forwarded-Port: 8080` are set
add another test next to the existing URL tests for `X-Forwarded-*`
The docs shouldn't need to be changed since this is just a bugfix and now works as expected.

fix: don't include port twice from x-forwarded-host and x-forwarded-port headers

---

.changeset/little-dryers-stare.md
packages/integrations/preact/src/index.ts

- Adds a flag to enable https://preactjs.github.io/preact-devtools/ in dev mode
Manually in the preact example
[TBD](https://github.com/withastro/docs/pull/8164)

feat(preact): add support for devtools

---

.changeset/thin-rabbits-wait.md
packages/integrations/vue/package.json
packages/integrations/vue/src/index.ts
pnpm-lock.yaml

- Adds a flag to enable https://github.com/vuejs/devtools-next in dev mode
Manually in the vue example
https://github.com/withastro/docs/pull/8150

feat(vue): add support for devtools

---

examples/blog/src/content/blog/markdown-style-guide.md

Updates the markdown in the `markdown-style-guide.md` blog example file:
- Updates wrong/missing heading levels (on "Syntax" and "Output" sections where its missing or skipping a level);
- Updates the syntax of the `<kbd>` tag example, where there was an extra tag surrounding the whole example command and nos just individual keys, as expected.
Heading changes were testes with the [Headings Map browser extension (Chrome)](https://chromewebstore.google.com/detail/headingsmap/flbjommegcjonpdmenkdiocclhjacmbi?hl=pt-BR&utm_source=ext_sidebar) for easier error detection.
Heading structure before:
Heading structure after:
I believe no docs changes are needed, since its a syntax fix.

Fix markdown of `markdown-style-guide.md` in the blog example

---

packages/astro/src/core/middleware/callMiddleware.ts

The logic for printing the warning wasn't correct
I tested locally, and I don't see the warning
N/A

fix: logic for printing warning

---

.changeset/breezy-lies-sparkle.md
packages/astro/src/core/errors/errors-data.ts
packages/astro/src/core/render-context.ts
packages/astro/src/vite-plugin-astro-server/plugin.ts

Closes: https://github.com/withastro/astro/issues/10972
- Add adapter name to dev manifest
- Add error message for accessing `clientAddress` on prerendered routes
- Fix/Throw error when accessing `clientAddress` on prerendered routes
I am not sure how to test this, I tested it manually. If someone could point me to an example, that would be great!
Does not change behavior, just throws a different error

Fix error when accessing `clientAddress` on prerendered routes

---

.changeset/ten-needles-rescue.md
packages/astro/components/Picture.astro
packages/astro/test/core-image.test.js
packages/astro/test/fixtures/core-image/src/pages/picturecomponent.astro

fix https://github.com/withastro/astro/issues/10307
The PR uses some tricks to get the scoped attributes or class to pass it to the `<picture>` element, instead of only to the `img` element.
The trick uses regexes for `astro-*` class and `data-astro-cid-*` attributes, which perhaps is not the most elegant, but I think it should be fine?
Question: Do we want to check for `data-astro-cid` specifically?
Added test
Added changeset

Support scope styles for picture element in Picture component

---

.changeset/lemon-otters-rest.md
packages/astro/src/@types/astro.ts

Fixes the type for `experimental.rewriting`
Checked locally
N/A

fix: incorrect type for experimental option

---

packages/astro/src/core/dev/dev.ts
packages/astro/src/core/messages.ts

The `getExecCommand` is an async function but it wasn't awaited in the `newVersionAvailable` function so the message in the console was:
```
Run [object Promise] @astrojs/upgrade to update
```
Instead of (for example):
```
Run pnpx @astrojs/upgrade to update
```
I transformed `newVersionAvailable` to an async function and added two `await`:
* one for `getExecCommand()`
* another where `newVersionAvailable` was called
Should I add a changeset for this?
Not sure how to test. If I use `pnpm link` on a project, it will use the latest version so the message will not be displayed. But I'm not sure a test is necessary.
I also run `pnpm test` and everything was ok.
No new behavior, only a minor fix so no need to update the doc.

fix: new version message when running astro dev

---

.changeset/tiny-dodos-melt.md
packages/astro/src/vite-plugin-astro-server/route.ts
packages/astro/test/dev-routing.test.js
packages/astro/test/fixtures/without-site-config/src/pages/base-index.astro

Closes: https://github.com/withastro/astro/issues/10850
- Fix loading of non-index routes that end with `index.html`
Test included
No behavior change, just aligning with expectations

Fix loading of non-index routes that end with `index.html`

---

.changeset/fluffy-zoos-hammer.md
packages/astro/src/actions/index.ts

On Windows, the path `stringifiedActionsImport` will get `/D:/XX/src/actions`, this cause the `Actions` type to be `any`.

fix:  fix incorrect actions path on windows

---

packages/astro/src/@types/astro.ts

- This PR fixes the mixed tabs and spaces in the [experimental.actions](https://docs.astro.build/en/reference/configuration-reference/#experimentalactions) code examples to ensure consistent indentation.
- Screenshots of the current document:
- ![Screenshot 2024-05-10 at 23 06 50](https://github.com/withastro/astro/assets/7889778/78d2e345-4b88-4501-8108-d51618cbf67e)
- ![Screenshot 2024-05-10 at 23 07 13](https://github.com/withastro/astro/assets/7889778/8e6dc510-b0f2-4544-960a-b5aa4bda5814)

docs: fix indentation in experimental.actions code examples

---

.changeset/popular-spiders-cough.md
packages/astro/src/actions/index.ts
packages/astro/test/actions.test.js
packages/astro/test/fixtures/actions/src/actions/index.ts
packages/astro/test/fixtures/actions/src/middleware.ts
packages/astro/test/fixtures/actions/src/pages/middleware.astro

Move actions middleware to run _after_ user middleware for `locals` access. This should unblock authwentication middleware for action handlers.
Add integration test with user middleware.
N/A: this feature is expected in the RFC already.

Fix: allow `locals` access from actions

---

packages/astro/CHANGELOG.md
packages/astro/src/@types/astro.ts

fix arguments in experimental.actions code example

docs: fix arguments in experimental.actions code example

---

.changeset/modern-donkeys-taste.md
packages/astro/src/actions/runtime/virtual/shared.ts

Zod validation errors are hidden in the error message. This makes thrown validation errors tougher to debug. This stringifies the Zod object for easier debugging.
Manual call
N/A

Actions: include zod error in message for easier debugging

---

.changeset/witty-cougars-allow.md
packages/astro/astro-jsx.d.ts

- add popovertargetaction into ButtonHTMLAttributes and InputHTMLAttributes
I manually tested the change in a local project
N/A

fix: add missing attribute popovertargetaction

---

.changeset/seven-crabs-burn.md
packages/astro/client.d.ts

Add type declarations for `import.meta.env.ASSETS_PREFIX` when defined as an object for handling different file types.
No tests should be required, but tests are running OK locally.
This was already documented [here](https://docs.astro.build/en/reference/configuration-reference/#buildassetsprefix), it just seems to have been missed in the actual codebase.

fix(astro): refine assets prefix typing

---

.changeset/many-news-rescue.md
packages/astro/src/actions/index.ts
packages/astro/src/core/errors/errors-data.ts

Throw error when `output` is missing when using actions.
Manual testing
Already documented!

actions: Throw error on missing server output

---

packages/astro/src/@types/astro.ts

Noticed a small grammatical mix-up here:
```diff
// before
Define an action using the `defineAction()` utility from the `astro:actions` module.
- These accept
the `handler` property to define your server-side request handler.
// after
Define an action using the `defineAction()` utility from the `astro:actions` module.
+ An action accepts
the `handler` property to define your server-side request handler.
```

docs: fix grammatical mix-up

---

.changeset/popular-colts-happen.md
packages/astro/config.d.ts

This PR fixes the type definition of `getViteConfig()` following the [change](https://github.com/withastro/astro/pull/10963) to allow for a second argument to specify an inline Astro configuration.
Tested by checking the type definition of `getViteConfig()` in `examples/with-vitest/vitest.config.ts`.
This PR only fixes the type definition, the [feature docs PR](https://github.com/withastro/docs/pull/8192) has been merged and does not need to be updated.

Fix `getViteConfig()` type definition

---

.changeset/many-guests-yell.md
packages/astro/src/actions/runtime/middleware.ts
packages/astro/src/actions/runtime/route.ts
packages/astro/src/actions/runtime/utils.ts
packages/astro/templates/actions.mjs
packages/astro/test/actions.test.js
packages/astro/test/fixtures/actions/src/actions/index.ts

We raised a 500 when an action's arguments or return value were `undefined`. This follows the HTTP spec to respect these cases.
- Return a 204 when the response is empty.
- Include the `Content-Length` on JSON args to check for a length of zero.
- Misc: return a 404 instead of a 500 when requesting an action that doesn't exist.
Add test for 204 status.
N/A

Actions: support empty args and empty response

---

.changeset/tame-otters-destroy.md
packages/astro-rss/src/index.ts
packages/astro-rss/src/util.ts
packages/astro-rss/test/rss.test.js

- Makes `createCanonicalURL` function return string instead of URL object
- Fixes an issue where trailing slash is not removed even if `trailingSlash` option is set to `false` when generating RSS string
- Closes #10994
- Related test case updated
- `pnpm --filter @astrojs/rss run test`
- N/A

fix(rss): fix an issue where trailing slash is not removed even if `trailingSlash` is set to `false`

---

.changeset/khaki-papayas-knock.md
packages/astro/e2e/actions-blog.test.js
packages/astro/e2e/fixtures/actions-blog/src/components/BaseHead.astro
packages/astro/e2e/fixtures/actions-blog/src/components/PostComment.tsx
packages/astro/e2e/fixtures/actions-blog/src/pages/blog/[...slug].astro
packages/astro/src/actions/runtime/middleware.ts

- When using rewrite with actions, a case where `locals._actionsInternal` is reassigned can occur. However, there's a protection to disable reassigning it so it fails. This PR does not attempt to reassign if it already exists
Manual patch in a private project
N/A, bug fix

fix: conflict between rewrite and actions middleware

---

.changeset/mean-geckos-sell.md
packages/astro/src/core/routing/manifest/generator.ts
packages/astro/test/ssr-params.test.js

- Allows the server to retrive # in dynamic paths (will need to be %23 on client to be recived)
- I do have a case in my project where this makes sense.
- Tested locally and seems to be fine. I dont know why these checks are in place well enough.
- Didnt see this beeing a problem in my older project where I used react.
- Dont think this need any new doc changes

Update generator.ts to allow %23 (#) in dynamic urls

---

.changeset/lazy-rockets-raise.md
packages/astro/src/i18n/index.ts
packages/astro/src/i18n/middleware.ts
packages/astro/test/fixtures/i18n-routing-prefix-always/src/pages/500.astro
packages/astro/test/i18n-routing-manual-with-default-middleware.test.js
packages/astro/test/i18n-routing.test.js

Fixes https://github.com/withastro/astro/issues/11011
Added a new test case with two new assertions
N/A

fix(i18n): allow to create 404.html and 500.html

---

.changeset/brave-cycles-suffer.md
packages/astro/src/core/app/pipeline.ts
packages/astro/src/core/base-pipeline.ts
packages/astro/src/core/build/pipeline.ts
packages/astro/src/core/render-context.ts
packages/astro/src/vite-plugin-astro-server/pipeline.ts
packages/astro/test/fixtures/reroute/src/middleware.js
packages/astro/test/fixtures/reroute/src/pages/auth/params.astro
packages/astro/test/rewrite.test.js

Closes https://github.com/withastro/astro/issues/11061
I tried to use `matchRoute` instead of using `pattern.test`, but unfortunately, it didn't work as I expected.
Created a new test case.
N/A

fix(rewrite): match index with params

---

.changeset/silly-parents-repair.md
packages/astro/src/core/app/index.ts

This PR improves debug logging for on-demand pages.
I was chatting with a person on Discord, trying to debug some issue they were having, and realised we don't have any logging that could help the debug.
N/A
N/A

fix: improve logging for on-demand pages

---

.changeset/metal-rocks-design.md
packages/db/src/core/cli/commands/link/index.ts
packages/db/src/core/errors.ts

Some of the error messages are using db-specific commands instead of the more general Astro ones, like our docs does. As Astro Studio become less specific to db, we orient people towards using `astro` commands instead.
N/A
Our docs already recommend the proper commands: https://docs.astro.build/en/reference/cli-reference/#astro-studio-cli

fix: use astro cli command instead of astro db's

---

.changeset/fluffy-pears-press.md
packages/astro/src/runtime/server/render/astro/render.ts
packages/astro/test/streaming.test.js

- Rendering occurs before the response starts asking for data.
- This resulted in a scenario where the first render would resolve a promise that the iterator was not listening to.
- This resulting in waiting until the *next* render to actually start streaming.
- The fix is to prevent rendering from creating the promises and instead only resolve them. Now the iterator is in charge of the promise and creates them on each pull.
- Updated existing test which only checked for more than 1 chunks when there should be several.
- Added a new assertion to verify that the first chunk does not contain the promise-blocked content.
N/A, bug fix

Fix streaming in Node.js fast path

---

.changeset/hungry-phones-melt.md
packages/astro/src/core/build/plugins/plugin-analyzer.ts
packages/astro/test/content-collections.test.js
packages/astro/test/fixtures/content-collections/src/components/ScriptCompA.astro
packages/astro/test/fixtures/content-collections/src/components/ScriptCompB.astro
packages/astro/test/fixtures/content-collections/src/content/with-scripts/one.mdx
packages/astro/test/fixtures/content-collections/src/pages/with-scripts/[...slug].astro

fix https://github.com/withastro/astro/issues/11063
regression from https://github.com/withastro/astro/pull/10959. When there's two hoisted scripts for a propagated asset (eg mdx file in content collection), there's two sets and I was incorrectly replacing the older with the new one. This PR fixes it and combines the set instead.
n/a. bug fix.

Fix hoisted scripts propagation

---

.changeset/brown-pens-type.md
packages/astro/src/core/build/consts.ts
packages/astro/src/core/build/index.ts
packages/astro/src/core/build/plugins/plugin-content.ts
packages/astro/src/core/build/static-build.ts
packages/astro/test/experimental-content-collections-render.test.js

- When `contentCollectionsCache` is enabled temporary cached content is copied into the `outDir` for processing. This fixes it so that this content is cleaned out, along with the rest of the temporary build JS.
- New test case added for both the `content` and `chunks` folder.
N/A, bug fix

Prevent cache content from being left in dist folder

---

.changeset/good-turtles-guess.md
packages/integrations/web-vitals/README.md
packages/integrations/web-vitals/src/db-config.ts
packages/integrations/web-vitals/src/index.ts

- Adds an option to the web vitals integration that allows users to “deprecate” the Astro DB tables web vitals adds.
- Currently, Astro DB requires a user to set `deprecated: true` on a table and push that before it will allow you to remove it completely. Because integrations control the tables themselves this is not something users can do themselves, so this PR reflects that up to the integration options.
- See the README changes in this PR for a full description of the “uninstall” process. (It’s not amazing, might be something for us to be aware of/think about.)
Tested manually that the `deprecated` property is being set properly on the table config.
/cc @withastro/maintainers-docs for feedback on the README changes!

Support deprecating Web Vitals table

---

.changeset/gorgeous-dancers-return.md
packages/astro/src/actions/runtime/middleware.ts

Respect error status when using a progressive fallback. This will overwrite any `status` set from Astro frontmatter with `response.status`. Curious if we think this makes sense?
Already have e2e test for progressive fallback validation errors. It doesn't check the status, but this is difficult to assert.
N/A

fix: set status on error with progressive fallback

---

.changeset/new-mice-occur.md
packages/astro/astro-jsx.d.ts

Closes #11072 
Changed IntrinsicAttributes's slot attribute type, adding `null` as a possible type
```
interface IntrinsicAttributes {
....
slot?: string | undefined | null
....
}
```
Now `slot` is consistent in IntrinsicAttributes and HTMLAttributes
None, since I only widened the type choice
None, change doesn't affect docs

fix type definition of IntrinsicAttributes's slot attribute

---

packages/astro/e2e/fixtures/view-transitions/src/pages/abort2.astro
packages/astro/e2e/view-transitions.test.js
packages/astro/playwright.firefox.config.js

Adds `e2e/view-transitions.test.js` to `playwright.firefox.config.js`, see #11036.
=> e2e tests for view transitions will now not only run on Chrome, but also run on Firefox.
Our approach for counting full page loads during navigation was off by one as Firefox always generated an additional load for `about:blank` for each test case.
Few tests do not work the same or at all for simulated view transitions
- "No page rendering during swap()": Other than the native implementation, the simulation can not stop the renderer.
- "transition:name should be escaped correctly": setting view-transition-name w/o native support is a CSS error.
- "animation get canceled when view transition is interrupted": as entry animations run before exit animations in the simulation, only the entry animations get …

Enables view transition e2e tests with Firefox

---

.changeset/wild-mice-battle.md
packages/astro/src/runtime/server/jsx.ts
packages/integrations/mdx/test/fixtures/mdx-plus-react-errors/astro.config.mjs
packages/integrations/mdx/test/fixtures/mdx-plus-react-errors/package.json
packages/integrations/mdx/test/fixtures/mdx-plus-react-errors/src/components/BrokenComponent.jsx
packages/integrations/mdx/test/fixtures/mdx-plus-react-errors/src/content/config.js
packages/integrations/mdx/test/fixtures/mdx-plus-react-errors/src/content/files/file.mdx
packages/integrations/mdx/test/fixtures/mdx-plus-react-errors/src/pages/broken.astro
packages/integrations/mdx/test/mdx-plus-react-errors.test.js
pnpm-lock.yaml

I've noticed that when using the following code in an mdx file with a content collection, everything works fine if I have a properly compiling page
```ts
<MyComponent {...props} />
```
But if there's an error anywhere in the codebase _after_ a react dependency is being used, let's say
```ts
import { useState } from 'react';
export default function MyComponent() {
useState(0);
someKindOfRenderBreakingErrorHere;
return <p>something</p>;
}
```
we're greeted with an error that makes no sense
```
Cannot read properties of null (reading 'useState')
```
But if the error happens earlier in the code like
```ts
import { useState } from 'react';
export default function MyComponent() {
someKindOfRenderBreakingErrorHere;
useState(0);
return <p>something</p>;
}
```
then we get the expected error
``` …
```

fix(renderer): omitting internal symbol from mdx props

---

.changeset/wild-hounds-repair.md
packages/astro/src/actions/runtime/middleware.ts

Fixes unexpected warning that `headers` were accessed on prerendered routes: 
- Short circuit on `GET` requests
- Add warning when `getActionResult()` is used for POST requests with a `null` body
Manual testing that the log does not fire.
N/A

Actions: stop warning about `headers` usage on prerendered routes

---

packages/db/package.json
packages/db/test/basics.test.js
packages/db/test/db-in-src.test.js
packages/db/test/error-handling.test.js
packages/db/test/integration-only.test.js
packages/db/test/integrations.test.js
packages/db/test/local-prod.test.js
packages/db/test/no-seed.test.js
packages/db/test/ssr-no-apptoken.test.js
packages/db/test/static-remote.test.js
packages/db/test/unit/column-queries.test.js
packages/db/test/unit/index-queries.test.js
packages/db/test/unit/reference-queries.test.js
packages/db/test/unit/reset-queries.test.js
pnpm-lock.yaml

This PR moves the tests of the `@astrojs/db` integration to use `node:test`
For some reason, `error-handling.test.js` -> `build --remote` is failing, and it doesn't raise any errors. Not sure why.
N/A

chore(db): move tests to node runner

---

.changeset/five-crabs-rhyme.md
packages/astro/src/@types/astro.ts
packages/astro/src/core/build/generate.ts
packages/astro/src/core/build/plugins/plugin-manifest.ts
packages/astro/src/core/config/schema.ts
packages/astro/src/integrations/features-validation.ts
packages/astro/test/fixtures/i18n-routing-subdomain/astro.config.mjs
packages/astro/test/units/config/config-validate.test.js
packages/astro/test/units/i18n/astro_i18n.test.js

This PR removes the experimental flag `experimental.i18nDomains`
Current tests should pass
/cc @withastro/maintainers-docs for feedback! 
https://github.com/withastro/docs/pull/8285

feat: make i18n domains stable

---

.changeset/healthy-planets-dream.md
packages/astro/src/core/app/node.ts
packages/astro/test/client-address-node.test.js
packages/astro/test/fixtures/client-address-node/astro.config.mjs
packages/astro/test/fixtures/client-address-node/package.json
packages/astro/test/fixtures/client-address-node/src/pages/index.astro
packages/astro/test/test-utils.js
pnpm-lock.yaml

Added logic to extract the client's IP address from the request headers (x-forwarded-for)
CI should pass
N/A

feat: prefer using x-forwarded-for as clientAddress

---

.changeset/six-icons-pump.md
packages/astro/src/actions/runtime/virtual/server.ts
packages/astro/test/fixtures/actions/src/actions/index.ts

- Go back to accessing API Context from the second `handler()` param
- Add `@deprecated` note to the `getApiContext()` function
Update fixture to use second param
Updated RFC

Actions: restore api context param

---

.changeset/sweet-needles-juggle.md
packages/integrations/vue/package.json
packages/integrations/vue/src/index.ts
pnpm-lock.yaml

- Vue Devtools support a launchEditor for "open in Editor"
- This accepts the option and forwards it to the vue dev tools
- no Idea how :D 
- more than happy to add a test with some guidance
Would probably make sense to update this section in the docs, happy to file a separate pr
https://github.com/withastro/docs/pull/8295

feat(vue): add support vue devtools options

---

packages/astro/src/@types/astro.ts

Adds missing `@docs` field for config reference entry for `security.checkOrigin` and corrects the version number.
No tests. Just docs.
Updates for inclusion in docs.

[docs] updates security.checkOrigin config reference

---

packages/astro/src/@types/astro.ts

Fixes errant inline code formatting in config reference
No tests
For proper rendering in docs

[docs] fix config reference code formatting

---

.changeset/eighty-taxis-wait.md
packages/astro/e2e/actions-blog.test.js
packages/astro/e2e/fixtures/actions-blog/src/pages/blog/[...slug].astro
packages/astro/src/actions/runtime/middleware.ts
packages/astro/src/actions/runtime/route.ts
packages/astro/src/actions/runtime/utils.ts
packages/astro/src/actions/runtime/virtual/server.ts
packages/astro/src/core/render-context.ts
packages/astro/templates/actions.mjs
packages/astro/test/actions.test.js
packages/astro/test/fixtures/actions/src/actions/index.ts
packages/astro/test/fixtures/actions/src/pages/rewrite.astro
packages/astro/test/fixtures/actions/src/pages/subscribe.astro

Allow actions to be called on the server.
```astro
---
// src/pages/blog/[postId].astro
import { actions } from 'astro:actions';
await actions.like({ postId: Astro.params.postId });
---
```
- Ensure API context exists by wrapping the `next()` call from middleware with a context provider.
- Add an SSR code path to the `actions.mjs` template. This imports the `getAction()` utility to retrieve the appropriate action by path name.
Add e2e test for calling the like action from astro frontmatter.
TODO: RFC update

Actions: Allow actions to be called on the server

---

.changeset/shy-pets-lie.md
packages/astro/src/integrations/features-validation.ts

- Previously any adapter that didn't support the `i18nDomains` feature would cause an error. Even if this feature was not used by the app.
This actually happens in the test adapter, but since it's just logging there's no way to assert. Otherwise tested manually.
N/A, bug fix

Prevent errors from adapters when i18n domains is not used

---

.changeset/rich-singers-accept.md
packages/upgrade/package.json
packages/upgrade/src/actions/context.ts
packages/upgrade/src/messages.ts
pnpm-lock.yaml

@astrojs/upgrade wrongfully used the current package manager used to run the command instead of the package manager used to install the project its run in. This normally would be fine, however many people uses `npx` even when using pnpm and other package managers, so using the package manager of the project ends up working better
Notice it now using pnpm despite using npx in this screenshot.
Tested manually, see screenshot
N/A

fix(upgrade): use preferred-pm instead of which-pm-runs

---

.changeset/thirty-dots-end.md
packages/astro/src/container/index.ts
packages/astro/src/core/render-context.ts
packages/astro/test/container.test.js

This PR allows to pass `props` when rendering a component using the container APIs.
The change is very minimal. I exposed `props` as a public property of the class `RenderContext`.
When calling `.render`, the props are computed only if they were set externally (in this case, by the container)
I added a new test case
/cc @withastro/maintainers-docs for feedback! 
I will send a PR when this PR is merged.

feat: pass props to container

---

packages/astro/CHANGELOG.md

This link does not work in the markdown preview on Github.

Changelog: Fix link

---

.changeset/silver-bananas-move.md
packages/astro/src/runtime/server/render/astro/render.ts
packages/astro/test/container.test.js

This PR fixes an issue in our runtime engine. This fix allows the `AstroContainer` to render the `Container` component.
I tested it manually against the source code that Chris created yesterday.
We could potentially create a PR to update the RSS page and use the container to render the content collection.

fix(runtime): check head+content component before throwing an error

---

.changeset/gold-meals-march.md
packages/integrations/lit/client-shim.js
packages/integrations/lit/client-shim.min.js

- Removes a deprecated API in lit plugin's client-shim which is causing a big hit to page insights.
Chrome's deprecation info:
https://chromestatus.com/feature/5116094370283520
Related story:
https://github.com/withastro/astro/issues/11160
- Removes the `shadowroot` attribute which was deprecated by chrome and not needed by other browsers
Deprecation info:
https://chromestatus.com/feature/6239658726391808
The original file did not include tests so I installed `client-shim` and client-shim-min` locally and tested them with the latest astro install I have, which has `lit` components in it
Should not change the user experience. Worked for me with both local dev server and build/preview

:bug: removed deprecated items from lit integration

---

.changeset/gentle-moose-provide.md
packages/astro/src/assets/utils/proxy.ts

The global is never supposed to be undefined here, but in some cases where you use code intended for the server on the client, or in some weird setups it can be. This doesn't *really* fix the issue, because well, you're still using the wrong code at the wrong place, but at least it won't fail on this cryptic error.
Does not exactly fix, but in my opinion, closes https://github.com/withastro/astro/issues/11042
N/A

fix: guard asset global usage

---

.changeset/wicked-dragons-draw.md
packages/astro/src/core/build/plugins/plugin-content.ts
packages/astro/test/experimental-content-collections-render.test.js

- We keep track of client input in order to know what to build in future builds, but were not keeping client scripts (aka hydrated scripts) as part of that.
- Not yet, trying a preview release first
N/A, bug fix

Retain client scripts in content cache

---

.changeset/purple-pears-divide.md
packages/astro/src/cli/install-package.ts

- pnpx was removed in pnpm v7 and replaced by pnpm exec and pnpm dlx. (pnpm/pnpm#3652)
- pnpm dlx works the same as yarn dlx.
- Astro update check's command sample should suggest `pnpm dlx`
Before:
```
update  ▶ New version of Astro available: 4.9.2
Run pnpx @astrojs/upgrade to update
```
After:
```
update  ▶ New version of Astro available: 4.9.2
Run pnpm dlx @astrojs/upgrade to update
```
N/A
N/A

fix(cli): Suggest `pnpm dlx` instead of `pnpx`

---

.changeset/green-moose-fetch.md
packages/astro/src/runtime/server/util.ts

Adjusts the `isPromise` utility to first check for the presence of the `'then'` key before accessing it to check the type.
The absence of this check on a Proxy object was causing an error to be thrown  - as my Proxy object throws on access of an unknown keys.
This should be a totally transparent change, and not quite worth setting up a test IMO.
Note that a few tests were failing for me locally, but they are failing on main as well, so seem to be unrelated.
N/A - This should hopefully be a totally transparent change that affects nothing other than this very specific error scenario.

fix: better isPromise check for proxy objects

---

.changeset/fair-singers-reflect.md
.changeset/gold-mayflies-beam.md
examples/container-with-vitest/package.json
examples/container-with-vitest/test/ReactWrapper.test.ts
packages/astro/client.d.ts
packages/astro/src/@types/astro.ts
packages/astro/src/container/index.ts
packages/astro/src/virtual-modules/container.ts
packages/integrations/lit/src/index.ts
packages/integrations/mdx/src/index.ts
packages/integrations/preact/src/index.ts
packages/integrations/react/src/index.ts
packages/integrations/solid/src/index.ts
packages/integrations/svelte/src/index.ts
packages/integrations/vue/src/index.ts
pnpm-lock.yaml

This PR does the following:
- updates our client-side integrations to expose a new function called `getContainerRenderer`. This function will be used by the consumers of a vite-full environment
- creates a new virtual module, `astro:container`, that exposes a utility function that loads the renderers when people are in a vite-full environment
- rollbacks the types of the `renderers`; this change should allow vite-less environments to load the renderer modules manually and pass them
I updated the example with the new code
We will probably need to update the docs for that
https://github.com/withastro/docs/pull/8428

feat(container): provide a virtual module to load renderers

---

packages/astro/src/core/errors/errors-data.ts

This fixes a typo and some formatting for astro:env error messages
no tests, docs.
only docs!

[docs] format error messages

---

.changeset/sweet-trainers-eat.md
packages/astro/src/core/build/generate.ts
packages/astro/test/fixtures/page-format/src/pages/nested/index.astro
packages/astro/test/page-format.test.js

- Updates `Astro.url` in generated pages with `format: 'preserve'` so that it is *not* treated like format: file which removes `index`. Instead it behaves like `format: 'directory'`, directories exist and get the same trailingSlash behavior.
- Fixes https://github.com/withastro/astro/issues/11107
- Added a test
- Updated an old one with wrong assumption
N/A, bug fix

Make Astro.url in format: 'preserve' match dev

---

.changeset/tidy-days-decide.md
packages/astro/src/config/index.ts
packages/astro/src/core/config/config.ts

Closes https://github.com/withastro/astro/issues/11175
The were a bug where we were merging `inlineConfig` and `userConfig`, but at end we were not using the merged config anymore other than creating the `AstroConfig`.
That `AstroConfig` is used to create `AstroSettings`, but when returning the vite config, we only use `inlineConfig`. Instead, we should use the merged configuration mentioned before.
Tested it against reproduction, it now returns the correct URL.
N/A

fix: merge userConfig inside `getViteConfig`

---

.changeset/metal-onions-hope.md
packages/astro/src/env/vite-plugin-env.ts
packages/astro/test/env-secret.test.js
packages/astro/test/fixtures/astro-env-server-secret/astro.config.mjs

- `process.env` was not populated
Added a test
N/A

fix(astro): getSecret in dev and build

---

.changeset/six-kangaroos-beam.md
packages/astro/src/@types/astro.ts

typo things.
change the word "private" to "secret"

fix(astro:) config reference typo

---

.changeset/silly-beds-hammer.md
packages/astro/client.d.ts
packages/astro/package.json
packages/astro/src/env/constants.ts
packages/astro/src/env/setup.ts
packages/astro/src/env/vite-plugin-env.ts
packages/astro/src/virtual-modules/env-setup.ts
packages/astro/test/test-adapter.js

- Uses an entrypoint instead of a virtual module
Tests should still pass, tested manually with the node adapter
N/A

feat(astro): update astro env setup

---

.changeset/friendly-eagles-arrive.md
packages/integrations/partytown/src/index.ts

This pull request intend to resolve the incompatibility of Partytown integration and View Transitions.
The Partytown snippet is supposed to be loaded only once, but when the View Transitions API gets activated, the <script> element containing this snippet is recreated on every transition. It has been changed and now it's executed only once.
Under certain conditions, Partytown may need an <iframe> element to be present on the page. When a view transition happens, this <iframe> is removed from the DOM. There has been a change added, which will move `<iframe>` element from the old document to the new one. The side-effect is all Partytown scripts will get re-executed. That behavior is aligned with other frameworks like Nuxt.
Closes https://github.com/withastro/astro/issues/11033
There is no …

fix(@astrojs/partytown): prevent crashes when View Transitions are enabled

---

packages/astro/src/content/types-generator.ts

- No functional change.
- Use an existing `collectionKey` variable defined at line 117 containing the `collectionEntryMap` key, rather than recalculate it.
- Don't check for an entry before deleting it, just delete it. Deleting a non-existing property in an Array will always succeed. Slightly reduces cyclomatic complexity.
The behavior of deleting a non-existent key was checked via the `node` REPL and the [MDN docs for `delete`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete).
The change was otherwise not tested.
Not necessary.

Minor cleanup in the content types generator

---

.changeset/warm-pets-tap.md
packages/db/src/runtime/index.ts
packages/db/src/runtime/virtual.ts

This type used to be exported, was moved around a bit starting in https://github.com/withastro/astro/pull/10457 and ended up no longer being exported
This PR moves the import and export to runtime/index.ts to ensure it ends up exported from `@astrojs/db/runtime`

Export type Database from db/runtime
